### ISSUE TITLE
Is there a MyPy extension that can generate annotations from dynamic types?

### ISSUE THREAD

**Issue by sonthonaxrk** [python/mypy#10006]
MyPy can not statically analyse the following:

```
def func(arg: int) -> str:
    return str(arg)


class MyMetaclass(type):

    def __new__(self, cls, bases, dct):
          dct['dynamically_added_function'] = func
          return super(cls, bases, dct)
           
class MyClass(metaclass=MyMetaclass):
    pass

# The type checker will ignore this.
not_a_str: int = MyClass().dynamically_added_function('string not int')
```

This is expected. However, being able to use the annotations of a dynamically created classes is extremely useful because metaprogramming is used a great deal in Python.

I started writing a very very crude extension to be able to do this. https://github.com/sonthonaxrk/b2c2_test/blob/master/b2c2/open_api_client_mypy_plugin.py

But then I thought, "surely someone else needed to do this, and I'm just reinventing the wheel here. This is not hugely difficult to do, and not much work, with quite a big payoff".

----

If nothing of the like exists I'm probably going to write the extension and built this API:

```
from mypy_dynamic_ext import is_dynamic

@is_dynamic
class MyClass(metaclass=MyMetaclass):
    pass
```

That would tell the extension to load up the class and infer its computed annotations.

**Comment by uv0xab** [comment]
I am also curious about this question. Currently, I am working on an extension that lets users write rust-like traits in Python. 

Now everything works well except for typing. It would be nice if there is any approach to tell mypy some extra annotations.

**Comment by sonthonaxrk** [comment]
@uv0xab I think what you have to do, and what I did in the extension demo that I wrote is actually load the code to compute is properties.

The limitation of my extension (other than it only being a proof on concept) is that it can't be used for functions that generate dynamic types.  So you can't have a function that generates a class with a metaclass and have that typed.  The only solution to that would be some pretty hardcore AST checking for nested classes.

**Comment by dimberman** [comment]
@sonthonaxrk were you able to get code completion in IDEs to work with this? I'm trying something similar but it's not showing up

**Comment by AlexWaygood** [comment]
I'm closing this, as I think this discussion has run its course
