### ISSUE TITLE
Subclassing `Any` Causes Unexpected Results

### ISSUE THREAD

**Issue by dylanmann** [python/mypy#10027]
**Bug Report**
Subclassing `Any` (as a result of untyped library imports) results in mypy being unable to find a common ancestor for two classes.  Is this expected behavior?

**To Reproduce**
Run mypy on this file:

```
from typing import Any, Type


def test(arg: Type[A]) -> None:
    return

def test2() -> None:
    for obj in (B, C):
        test(obj)  # ERROR IS HERE 


class A(Any):
    pass


class B(A):
    pass


class C(A):
    pass
```

**Expected Behavior**
Because B and C are both subclasses of A, I expected this to typecheck without error, and When I change `A` to be a subclass of `object` instead, mypy passes.

**Actual Behavior**

```
test.py:9: error: Argument 1 to "test" has incompatible type "Type[object]"; expected "Type[A]"
```

(Write what happened.)

**Your Environment**
Mac OS Catalina 10.15.7
brew installed python 3.9
mypy==0.800
No command line flags or mypy.ini

**Comment by hauntsaninja** [comment]
Thanks for the report! I fixed this a while back in #14404
