### ISSUE TITLE
Incorrect detection of name after failed import

### ISSUE THREAD

**Issue by AlbertoEAF** [python/mypy#10042]
The following:

```python
# File bug.py
try:
    import simplejson as json
except (ImportError, SyntaxError):
    import json
```

results in:

```bash
mypy.py:4: error: Name 'json' already defined (by an import)
Found 1 error in 1 file (checked 1 source file)
```
under mypy 0.8 in Ubuntu18.04 with python 3.7.4. (`mypy bug.py`)

**Comment by pspacek** [comment]
FTR this is reproducible using mypy==0.961.

**Comment by pspacek** [comment]
Hmm, maybe this is a duplicate of much older https://github.com/python/mypy/issues/1153.

**Comment by JelleZijlstra** [comment]
Yes, that's basically the same thing.
