### ISSUE TITLE
Any advices on how to automate typing process?

### ISSUE THREAD

**Issue by LeMeteore** [python/mypy#10060]
Hello everyone, really hope you're all doing fine.

After configuring and running Mypy, he will tell me what needs to be typed for having the first clean run (before having to add more and more types). Is there any way to guess or to find what will be (where will be?) the minimum amount of types to add? 

Also, is there any particular order to follow when incrementally adding types? I think I should begin with all the variables, all the constants, all the classes and take care of inheritance trees at last. The objective is to more or less automate this process. 

Thanks a lot for your advices and suggestions.

**Comment by ethanhs** [comment]
Hi, I'd recommend reading our docs on using mypy with an existing code base: https://mypy.readthedocs.io/en/stable/existing_code.html
