### ISSUE TITLE
macOS wheel builds broken because of find_sources test failure

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#10073]
macOS wheel builds are broken because of a test failure:
```
...
        files = {
            "pkg/a1/b/c/d/e.py",
            "pkg/a1/b/f.py",
            "pkg/a2/__init__.py",
            "pkg/a2/b/c/d/e.py",
            "pkg/a2/b/f.py",
        }
        fscache = FakeFSCache(files)
>       assert len(find_sources(["/"], options, fscache)) == len(files)

site-packages/mypy/test/test_find_sources.py:363: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
site-packages/mypy/test/test_find_sources.py:59: in find_sources
    return normalise_build_source_list(create_source_list(paths, options, fscache))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   mypy.find_sources.InvalidSourceList: There are no .py[i] files in directory '/'
```

This is blocking the 0.810 release #10062.

**Comment by JukkaL** [comment]
Actually it's unclear if this is failing on the 0.810 release branch. If it's only failing on master, this doesn't block the 0.810 release.

**Comment by JukkaL** [comment]
Yes, this is failing on the 0.810 release branch, as I feared originally. I'm working on a fix.

**Comment by JukkaL** [comment]
The wheel build is still failing. I have another attempt being built, but at least if it doesn't work, I'll probably have to postpone until the next week.

**Comment by hauntsaninja** [comment]
Sorry for the trouble, I'm optimistic https://github.com/python/mypy/pull/10077 would fix.

**Comment by hauntsaninja** [comment]
Your fix seems to have worked... But maybe we should change the logic a little:
https://github.com/python/mypy/blob/6bfc2dbc0e877408f5b70b86818683cd211c0031/mypy/modulefinder.py#L479
We currently normalise the path for the purposes of `--exclude` using abspath, but maybe we should use relpath. In the common case that people are running mypy from within their project, this could make behaviour more consistent across project locations.

**Comment by hauntsaninja** [comment]
I opened a PR in case you think using relpath is better: https://github.com/python/mypy/pull/10078

**Comment by JukkaL** [comment]
@hauntsaninja Thanks, the macOS wheel builds work now.
