### ISSUE TITLE
ItemsView[...], iterator protocol and tuple conversion

### ISSUE THREAD

**Issue by mataha** [python/mypy#10087]
Disclaimer: I am not good at Python.

Given the following code in `test.py` (Python 3.9):

```py
from typing import ItemsView, Iterator


class Foo:

    def __init__(self) -> None:
        self._member = {'a': 'A', 'b': 'B'}

    def __iter__(self) -> Iterator[ItemsView[str, str]]:
        return iter(self._member.items())

    def bar(self, string: str) -> str:
        for key, value in self:
            string = string.replace(key, value)
        return string
```

`mypy` reports the following:

```
test.py:10: error: Argument 1 to "iter" has incompatible type "ItemsView[str, str]"; expected "Iterable[ItemsView[str, str]]"
test.py:14: error: Argument 1 to "replace" of "str" has incompatible type "Tuple[str, str]"; expected "str"
test.py:14: error: Argument 2 to "replace" of "str" has incompatible type "Tuple[str, str]"; expected "str"
```

From my understanding, as `_member` is a `dict[str, str]`, `_member.items()` should return a view of that dictionary's items, i.e. `ItemsView[str, str]`. Then, in accordance with the iterator protocol, that should be wrapped in something that provides `__iter__()` and `__next__()`, hence `iter()`. However, this does not seem to work because of type incompatibility, even though both `Iterable[...]` and `Iterator[...]` should be fine in this context.

Is there a `ItemsView[str, str]` to `Tuple[str, str]` conversion under the hood in that `iter()`?

**Comment by JelleZijlstra** [comment]
The annotation for `__iter__` should be `-> Iterator[Tuple[str, str]]`. It returns an iterator that produces pairs of strings, not an iterator that produces ItemsViews.
