### ISSUE TITLE
Problem with classmethods in generic protocols

### ISSUE THREAD

**Issue by SergeyTsaplin** [python/mypy#10081]
**To Reproduce**

I have the following protocol:

```python
from typing import Protocol, TypeVar, Dict, Type

ModelType = TypeVar("ModelType", bound="DictSerializable")


class DictSerializable(Protocol):
    @classmethod
    def from_dict(cls: Type[ModelType], data: Dict) -> ModelType:
        ...

    def to_dict(self: ModelType) -> Dict:
```

With the following usage:

```python
from dataclasses import dataclass

@dataclass
class Item:
    value: int

    @classmethod
    def from_dict(cls: Type[Item], data: Dict) -> Item:
        return Item(value=data["value"])

    def to_dict(self) -> Dict:
        return {"value": self.value}


item: DictSerializable = Item(value=1)
```

**Expected Behavior**

I expect that there is no error

**Actual Behavior**

The mypy output:

```
main.py:29: error: Incompatible types in assignment (expression has type "Item", variable has type "DictSerializable")
main.py:29: note: Following member(s) of "Item" have conflicts:
main.py:29: note:     Expected:
main.py:29: note:         def from_dict(cls, data: Dict[Any, Any]) -> <nothing>
main.py:29: note:     Got:
main.py:29: note:         def from_dict(cls, data: Dict[Any, Any]) -> Item
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.800
- Mypy command-line flags: -
- Mypy configuration options from `mypy.ini` (and other config files): -
- Python version used: 3.9
- Operating system and version: Any

**Note**

There is no chance to change the `Item` because it's generated by some 3rd party tool, so using the instance methods instead of classmethods are not suitable.

Mypy playground link: https://mypy-play.net/?mypy=latest&python=3.9&gist=cd5f30078d13e2cac70376a0bdc2ff06

**Comment by AlexWaygood** [comment]
[Can't reproduce](https://mypy-play.net/?gist=e641d5617fcdc7d8100981a7fd182468&mypy=0.930&python=3.10&flags=strict) on 0.930+
