### ISSUE TITLE
[GSOC 2021] Google Summer of Code 2021 project ideas

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#10099]
Here are our projects for Google Summer of Code 2021:

* [Speeding up string operations in mypyc](https://github.com/mypyc/mypyc/issues/801)
* [Support singledispatch efficiently](https://github.com/mypyc/mypyc/issues/802)

**Update:** These are final! You can apply (only) to one of the above projects.

**Comment by JukkaL** [comment]
Ideas about starter issues and links documentation: #10195

**Comment by badal8381** [comment]
hello Sir,
I am new to Google Summer Of Code. How can I contribute to your Project. I have intermediate knowledge of Python and I Read about Mypy and which is based on python. honestly speaking I have worked on few open source projects and learned few things but I want to start my journey as a software developer and an Open Source contributor from this project. help me find my way to become a software engineer.

**Comment by JukkaL** [comment]
@badal8381 Please have a look at #10195 and the documentation links in the issue description. They will hopefully help you get started.

**Comment by vanshhhhh** [comment]
> @badal8381 Please have a look at #10195 and the documentation links in the issue description. They will hopefully help you get started.

Thanks sir

**Comment by ysachinj99** [comment]
hello Sir,
I am new to Google Summer Of Code.  can I contribute to your Project? I have a knowledge of Python and I Read about Mypy and which is based on python. honestly speaking I haven't worked on any open-source projects but learned few things from my colleges and Searching Around but now, I want to start my journey as a software developer and an Open Source contributor from this project. help me find my way to become a software engineer.

**Comment by Ashu-1309** [comment]
Hello Sir,
I am 2nd year student and I am also new to GSoC . I want to contribute in your project. I did paticipation in Hacktober fest 2020 and also have idea about Python. I want to be an open source contributor so that I can help our community to to grow. I want to get knowledge about these Open source so that I can help something good for our community.

**Comment by Pranav957** [comment]
Hello sir! 
I'm pranav kulkarni I'm new to Google summer of code & want to contribute in your project. I want to contribute to open source. & Please help me to do that
I read about mypy which is based on Python, I have completed coursera course of Python from Michigan University. & I have core Python skills

**Comment by Bharadwajsai-121** [comment]
Hello sir !
I'm Bharadwajsai . I'm new to Open Source contribution . I have intermediate knowledge of Python . I'm fascinated to contribute to Open source . I have read about mypy . I want to start my journey with open source contribution from here . Please help me how to get started .

**Comment by JukkaL** [comment]
The application deadline is tomorrow (April 13), and it's probably too late to apply if you haven't started working on some issues by now. I'll try to respond any PRs promptly today and tomorrow so that last-minute PRs can still get at least one review cycle.

**Comment by sameershaik-tech** [comment]
hello sir!
I'm am  Sameer Shaik. I'm new to Open Source contribution ,I have intermediate knowledge in  python. I have ability to solve problems also, I have done some Projects also in Python, I'm so fascinated to contribute to Open Source . I have read about mypy. I want to start my journey with Open Source contribution from here, Please help me how to get started

**Comment by Rohan581** [comment]
Hello Sir, I'm new to open source ecosystem and possess decent knowledge of python. I've read about mypy and would like to begin my open source journey right here. Would you be kind to help me get started?

**Comment by ethanhs** [comment]
Both of the projects were completed by @pranavrajpal and @97littleleaf11 thank you both!  I am going to close this since it is no longer relevant.
