### ISSUE TITLE
nullcontext treated as having no __enter__ or __exit__ method

### ISSUE THREAD

**Issue by l0b0** [python/mypy#10109]
**Bug Report**

[Using `nullcontext` to randomly get a specific context manager](https://stackoverflow.com/a/56971244/96588) results in `mypy` errors.

**To Reproduce**

Run `mypy` on the following code:

```console
$ cat test.py 
from contextlib import nullcontext
from random import getrandbits

with (open("path") if bool(getrandbits(1)) else nullcontext()):
    pass
```

**Expected Behavior**

As far as I can tell from looking at contextlib.py it *does* have `__enter__` and `__exit__`, so this error should not happen.

**Actual Behavior**

```console
$ mypy test.py 
test.py:4: error: "object" has no attribute "__enter__"  [attr-defined]
test.py:4: error: "object" has no attribute "__exit__"  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.800
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files):

   ```
   [mypy]
   check_untyped_defs = true
   disallow_any_generics = true
   disallow_untyped_defs = true
   no_implicit_optional = true
   show_error_codes = true
   warn_redundant_casts = true
   warn_return_any = true
   warn_unused_ignores = true
   ```

- Python version used: 3.8.6
- Operating system and version: Arch Linux

**Comment by JelleZijlstra** [comment]
The issue isn't with `nullcontext`, it's that mypy infers `(open("path") if bool(getrandbits(1)) else nullcontext())` to be of type `object`. Variants of this have been reported many times. A workaround is to first declare a variable like `cm: ContextManager[None] = (open("path") if bool(getrandbits(1)) else nullcontext())`.

**Comment by l0b0** [comment]
Thank you @JelleZijlstra, is there an overarching issue I can follow? That way we can also close this as a duplicate.

**Comment by jamesderlin** [comment]
Seems like a duplicate of https://github.com/python/mypy/issues/5512.

**Comment by JelleZijlstra** [comment]
Yes, one of many in the #join-v-union genre.
