### ISSUE TITLE
`inspect.isfunction` and `inspect.ismethod`

### ISSUE THREAD

**Issue by mristin** [python/mypy#10117]
**Bug Report**

I use an union between a callable and a class:

```python
# example.py

import inspect
from typing import Union, Callable, Type


def some_func(
        error: Union[Callable[..., BaseException], Type[BaseException]]
)->None:
    if (inspect.isfunction(error) or inspect.ismethod(error)):
        reveal_type(error)
    else:
        reveal_type(error)
```

Mypy does not infer that the type is `Callable` based on `inspect.isfunction` and `inspect.ismethod`, but still assumes the union:

```
example.py:9: note: Revealed type is 'Union[def (*Any, **Any) -> builtins.BaseException, Type[builtins.BaseException]]'
example.py:11: note: Revealed type is 'Union[def (*Any, **Any) -> builtins.BaseException, Type[builtins.BaseException]]'
```

**To Reproduce**

Execute the following command:

```
mypy example.py
```

**Your Environment**

- Mypy version used: 0.812

**Comment by mristin** [comment]
(I am not sure if this is a bug or a feature request, please change as you see fit.)

**Comment by JelleZijlstra** [comment]
This should be fixable in typeshed once we have support for PEP 647 (https://www.python.org/dev/peps/pep-0647/). Mypy could also special-case these functions directly but that might be overkill.

**Comment by mristin** [comment]
@JelleZijlstra thanks for considering the issue. In fact, I think that mypy should handle `inspect.is*` methods directly as this seems a canonical way to chech whether an object is a callable, a coroutine *etc.* at runtime.

Otherwise, it would be great if mypy documentation explicitly stated how the user is expected to check for "is a callable" property. (There is no `isinstance(obj, Callable)` as far as I am aware.)

**Comment by JelleZijlstra** [comment]
We support using `callable()` (as of #2627).

**Comment by AlexWaygood** [comment]
Hmm, well, the relevant changes to typeshed have been made, but there still [seem to be some problems](https://mypy-play.net/?mypy=latest&python=3.10&gist=4e09cee3bb054e565936712f4c649fc9) on mypy's end:

```python
import inspect
from typing import Union, Callable, Type


def some_func(
        error: Union[Callable[..., BaseException], Type[BaseException]]
)->None:
    if (inspect.isfunction(error) or inspect.ismethod(error)):
        reveal_type(error)  # Revealed type is "<nothing>"
    else:
        reveal_type(error)  # Revealed type is "Union[def (*Any, **Any) -> builtins.BaseException, Type[builtins.BaseException]]"
```

**Comment by erictraut** [comment]
It looks like this is working as expected with the latest version of mypy.

The first revealed type is now:
```
Revealed type is "Union[types.FunctionType, types.MethodType]"
```
