### ISSUE TITLE
Have dmypy gracefully ignore report generation settings

### ISSUE THREAD

**Issue by natemcmaster** [python/mypy#10118]
**Feature**

If mypy.ini/setup.cfg enable report generation, running dmypy fails with an error
```
dmypy: start/restart cannot generate reports
```

Can we update dmypy to skip report generation and let the user know their report settings are being ignored?

**Pitch**

Currently, my project has
```ini
[mypy]
cobertura_xml_report = build/mypy/
```
Every time I want to run `dmypy`, I have to...
1. comment out the cobertura_xml_report setting in setup.cfg, 
2. run dmypy, and 
3. undo and/or remember not to commit my change to setup.cfg when I am ready to make a pull request.

This is a little nuisance I'd love to fix if you're okay taking a PR to make this non-fatal.

**Comment by JelleZijlstra** [comment]
Sounds like a good idea, feel free to submit a PR.

**Comment by natemcmaster** [comment]
Small fix proposed here: https://github.com/python/mypy/pull/10181
