### ISSUE TITLE
Build wheels for Apple Silicon

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#10114]
Currently we don't generate binary wheels for macs with Apple Silicon, and the only option is to use the slower, interpreted version of mypy when using an ARM CPython build. A compiled wheel could up to 4x faster than the interpreted one.

cibuildwheel (https://github.com/joerick/cibuildwheel), which we use to compile wheels, now supports cross-compiling `arm64` wheels for Apple Silicon on Intel. We should generate `arm64` wheels for macOS. We can support at least Python 3.9 and possibly 3.8 (https://bugs.python.org/msg382939). Just supporting 3.9 would be okay.

Building the wheels happens in a GitHub action [here](https://github.com/mypyc/mypy_mypyc-wheels/blob/master/.github/workflows/build.yml).

Would anybody to like to try this out? If you can generate the wheels, I can help test them, since I have a Mac with Apple Silicon.

**Comment by 97littleleaf11** [comment]
Hey @JukkaL, I briefly went through the `workflows/build.yml` just now. What should I do next, to modify`mypy/misc/build_wheel.py` or build wheels locally?

**Comment by JukkaL** [comment]
@97littleleaf11 You can modify `misc/build_wheel.py` to also generate `arm64` wheels when running on macOS and Python 3.9. I think that you can use `CIBW_ARCHS_MACOS` to define the platforms. We don't want universal wheels, since they will be much bigger. If you will create a PR, I can try the wheel generation manually.

**Comment by 97littleleaf11** [comment]
@JukkaL I just made a PR about it.

**Comment by JukkaL** [comment]
@97littleleaf11 Thanks for the PR! This seems to work great based on some quick experiments, with about 4.3x performance improvement. [Here](https://github.com/mypyc/mypy_mypyc-wheels/releases/download/v0.820%2Bdev.5161d93950cdb6daa5a13559b64e9e016ab78183/mypy-0.820+dev.5161d93950cdb6daa5a13559b64e9e016ab78183-cp39-cp39-macosx_11_0_arm64.whl) is a Python 3.9 arm64 wheel for the current GitHub master. More recent builds will appear [here](https://github.com/mypyc/mypy_mypyc-wheels/releases).

**Comment by henryiii** [comment]
That wheel works correctly for me on AS as well, thanks! (sorry for the delay, haven't had a chance to boot my AS machine back up till today 👶 )
