### ISSUE TITLE
[mypyc] Can compile TypedDict but throws TypeError at runtime

### ISSUE THREAD

**Issue by twoertwein** [python/mypy#10127]
**Bug Report**

test.py
```py
# example from PEP589
from typing import TypedDict

class Movie(TypedDict):
    name: str
    year: int

move: Movie = {"name": "Blade Runner", "year": 1982}
```

```sh
$ mypyc test.py
...
$ python -c "import test"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "test.py", line 6, in <module>
    class Movie(TypedDict):
TypeError: mypyc classes can't have a metaclass
```
**Expected Behavior**
`TypedDict` should be supported at runtime.

**Actual Behavior**

`TypeError` is thrown.

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: -
- Mypy configuration options from `mypy.ini` (and other config files): -
- Python version used: 3.8.7
- Operating system and version: 4.13.0-36-generic, 64 bit

**Comment by TH3CHARLie** [comment]
Thanks for reporting this! If possible, could you please reopen this at https://github.com/mypyc/mypyc/issues/ to help better track mypyc specific issues?

This I believe is a known-limitation of mypyc's metaclass support, see: https://github.com/python/mypy/blob/4827f3adf0acebd2dea7cc0dbf358b8daede6694/mypyc/lib-rt/misc_ops.c#L105-L107

**Comment by twoertwein** [comment]
I moved it https://github.com/mypyc/mypyc/issues/803
