### ISSUE TITLE
While walrus operator syntax error in mypy 0.812

### ISSUE THREAD

**Issue by t4n1o** [python/mypy#10123]
I'm using aiohttp with python3.8 and python3.9. The error in mypy is caused by the walrus operator, used like this:

```
while chunk := await response.content.readany():
     data = chunk.decode('utf8')
```

The code runs just fine. But mypy 0.812 says:
`error: invalid syntax`

and refuses to type check anything else in the file.

**Comment by hauntsaninja** [comment]
You'll need to install mypy using Python 3.8 or greater.

**Comment by akanter** [comment]
@hauntsaninja Is there a workaround for those of us who cannot upgrade mypy but are using Python 3.8?

**Comment by hauntsaninja** [comment]
This isn't upgrading mypy, it's just installing mypy with Python 3.8.

**Comment by t4n1o** [comment]
My python version is 3.9 but hauntsaninja is correct.

You need to do:
`python3.9 -m pip install mypy`

And it will be fixed
