### ISSUE TITLE
Union of dicts fail

### ISSUE THREAD

**Issue by socketpair** [python/mypy#10135]
https://mypy-play.net/?mypy=latest&python=3.9&gist=6770a34c37170183d0fefe8b1444aa27

```python

from typing import Dict, Union

def fun() -> Union[Dict[str, int], Dict[int, float]]:
    return {}
```

```
error: Incompatible return value type (got "Dict[<nothing>, <nothing>]", expected "Union[Dict[str, int], Dict[int, float]]")
```

**Comment by socketpair** [comment]
I guess, `{}` should be `Dict[Any, Any]` and not `Dict[<nothing>, <nothing>]`

**Comment by srittau** [comment]
There is prior discussion in python/typeshed#4846 and a PR in python/typeshed#4987.

**Comment by socketpair** [comment]
Not reproduced anymore, so closing.
