### ISSUE TITLE
method signature bug

### ISSUE THREAD

**Issue by socketpair** [python/mypy#10133]
```python
class Base:
    @staticmethod
    def method():
        pass

class Derived(Base):
    def method(self):
        print(self)
```

mypy considers:  
`error: Signature of "method" incompatible with supertype "Base"  [override]`

**Comment by ethanhs** [comment]
Mypy is correct here. I would recommend reading https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides

**Comment by socketpair** [comment]
OK. you are right. This case will generate error in code:

```
Derived.method()
```
