### ISSUE TITLE
mypy confused about return type of metaclass __new__

### ISSUE THREAD

**Issue by jwodder** [python/mypy#10132]
Consider the following trivial metaclass:

```python
from typing import Any, Dict, Tuple

class MyMeta(type):
    def __new__(
        metacls,
        name: str,
        bases: Tuple[type, ...],
        namespace: Dict[str, Any],
    ) -> MyMeta:
        return super().__new__(metacls, name, bases, namespace)
```

When run on this code with the default settings, mypy fails with "`Incompatible return value type (got "type", expected "MyMeta")`".  If the return type annotation of `__new__` is changed to `type`, the error then becomes "`Incompatible return type for "__new__" (returns "type", but must return a subtype of "MyMeta")`".  It seems that mypy knows that a metaclass' `__new__` should return a class with that metaclass, yet it doesn't know that `super().__new__(metaclass, ...)` does indeed return such a type.

**Your Environment**

- Mypy version used: v0.812
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.9.2
- Operating system and version: macOS 11.2.1

**Comment by AlexWaygood** [comment]
As @Akuli says, this is [no longer reproducible](https://mypy-play.net/?mypy=0.902&python=3.10&gist=fa48b58f0f9e6225aaaee20c9482759b&flags=strict) on mypy 0.902+
