### ISSUE TITLE
Syntactic short form of Callable

### ISSUE THREAD

**Issue by joelberkeley** [python/mypy#10156]
**Feature**

A short form for `Callable`.

**Pitch**

`Callable` definitions can get very long and difficult to read and write, especially when nested, such as
```python
Callable[[FooBar], Callable[[int, str], Baz]]]
```
How about adding some form of syntactic sugar, akin to `int | str` for union types?

Haskell/Idris write `int -> str -> Foo` for a function with two arguments returning a `Foo`. This comparison is limited in that it's also a function from `int` to another function `str -> Foo`.

[Scala](https://docs.scala-lang.org/style/types.html) uses `str => Foo` and `(int, str) => Foo`.  This also emphasises a need to differentiate between arity-n and n nested arity-one functions.

It looks like [Rust](https://doc.rust-lang.org/reference/types/function-pointer.html) would do `fn(int, str) -> Foo`.

Three options that come to mind are then use an existing operator in place of `->` or `=>`, such as `>` or `>>`, then differentiate arity-n functions with either
  -  another operator, like `int > str >> Foo`
  -  use Scala's style as `(int, str) > Foo` or `(int, str) >> Foo`
  - use Rust's style with a new item `Fn` in `typing`: `Fn(int, str) > Foo` or `Fn(int, str) >> Foo`

One consideration: we would also need to support functions as arguments.

I think Scala's style reads more cleanly than the Haskell-like option, aligns closer with `Callable`, in that function arguments are collected in a sequence, and uses up fewer operators. I don't know if it's possible to overload `__gt__` or `__rshift__` on tuples at the type level, however. If not, then the Rust option would solve that by putting all the overloads on a new `Fn` type

Since we're here, I'll add `->` and `=>` to the conversation, in case that's actually valid python and I've missed it, or it would be considered.

**Comment by erictraut** [comment]
You may be interested in this typing-sig discussion: https://mail.python.org/archives/list/typing-sig@python.org/thread/3MCLUHZFRVZUJ42ITN37E6TL4RAXTSNY/

**Comment by JukkaL** [comment]
Since mypy generally does not support any type syntax not standardized in Python, this would need to go through the 
[PEP process](https://www.python.org/dev/peps/pep-0001/). The discussion linked to by @erictraut is a good place to move this forward.  Overloading operators at type level is possible (for example, 3.10 will support `int | str`), but again this  requires a PEP.
