### ISSUE TITLE
yield from inside list comprehension gives wrong type

### ISSUE THREAD

**Issue by Akuli** [python/mypy#10188]
**Bug Report**

runtime and mypy types don't match, possibly related to #6457

**To Reproduce**

```
from typing import Generator

def f() -> Generator[int, None, str]:
    yield 1
    return "lol"

def g() -> Generator[int, None, None]:
    x = [(yield from f()) for lel in range(5)]
    print(x)        # <generator object g.<locals>.<listcomp> at 0x7fba92696a20>
    reveal_type(x)  # List[str]

g()
```

**Expected Behavior**

`reveal_type` outputting `Generator[something]` to match runtime

**Actual Behavior**

`List[str]`

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.7.3

**Comment by JelleZijlstra** [comment]
Similar to my comment in #10189, this was made a SyntaxError in 3.8 because the runtime behavior made little sense. It doesn't seem worth the effort to try to match the runtime behavior in mypy for 3.6/3.7, but maybe we can emit an error and infer Any.

**Comment by erictraut** [comment]
Mypy correctly flags the use of `yield` within a list comprehension as an error, consistent with Python 3.8 and newer. Now that 3.7 support in mypy has been deprecated, this issue can safely be closed.

**Comment by hauntsaninja** [comment]
Technically mypy's only dropped support for running with 3.7, not necessarily type checking targeting 3.7. But agreed this should be closed
