### ISSUE TITLE
Tuple[X, ...] is incompatible with Type[<nothing>]

### ISSUE THREAD

**Issue by mitsuse** [python/mypy#10193]
**Bug Report**

`Tuple[X, ...]` is compatible with `Type[<nothing>]` on  mypy 0.770, but becomes incompatible on mypy 0.812.

**To Reproduce**

Please type checking this code with mypy 0.812 and CPython 3.7 ~ 3.9 .

```python
from typing import List
from typing import Tuple
from typing import Type


def f(x: Type) -> None:
    ...


# error: Argument 1 to "f" has incompatible type "object"; expected "Type[<nothing>]"
# f(Tuple[int, ...])

# OK
f(List[int])
```

**Expected Behavior**

Both `Tuple[X, ...]` and `List[X]` are compatible with `Type[<nothing>]` or neither are not.

**Actual Behavior**

An error was caused by passing `Tuple[int, ...]`  to Type:

```
Argument 1 to "f" has incompatible type "object"; expected "Type[<nothing>]"
```

**Your Environment**

- Operating system and version:  Ubuntu 18.04
- Python version used: CPython (3.7.6, 3.8.1, 3.9.1)
- Mypy version used: 0.812
- Mypy configuration options from `mypy.ini` (and other config files):

```ini
check_untyped_defs = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
disallow_untyped_decorators = False
no_implicit_optional = True
strict_optional = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_ignores = True
warn_unused_configs = True
ignore_missing_imports = True
```

**Comment by AbhiSahane0** [comment]
Should I solve this plz.

**Comment by JukkaL** [comment]
@AbhiSahane0 Sure, go ahead! The most logical behavior is that both `List[int]` and `Tuple[int, ...]` in an expression context have type `object`, since they can't be used to construct values. 

However, on Python 3.9 and later `list[int]` and `tuple[int, ...]` should probably have callable types, but they shouldn't be compatible with `Type`. `list[int]()` is valid but `List[int]()` isn't, and `isinstance([], list[int])` is not valid.

**Comment by mitsuse** [comment]
@JukkaL @AbhiSahane0 Thanks for the discussion. Fundamentally, I'm aware that the problem is whether the inconsistent behavior of `List[T]` and `Tuple[T, ...] is good or not. Additionally, is there any impact on the existing code or not?

I'll share my more specific use case as a supplement.

```python
T = TypeVar('T')

def decode(type_: Type[T], x: Any) -> T:
    # Validate `x` and convert it to a value of `T` by using annotations of T's properties.  
    ...
```

This works for types like dataclass, but `decode(Tuple[int, ...]) , x)` causes a type error in mypy 0.812.

If `List[T]` should be treated like `Tuple[T, ...] `, then maybe it should be something like `decode_as_list(element_type: T, x: Any) -> List[T]` (though it difficult to handle the case of tuple).

**Comment by hauntsaninja** [comment]
https://github.com/python/mypy/issues/9773

**Comment by mitsuse** [comment]
@hauntsaninja Thank you for the guide!

@JukkaL @AbhiSahane0 I close this issue as the discussion seems to be resolved once the PEP about `TypeForm` is released. Thanks!
