### ISSUE TITLE
"if isinstance(...)" filter in dictionary comprehension causes var type to be inferred as <nothing>

### ISSUE THREAD

**Issue by phyrwork** [python/mypy#10199]
Version:
```
pip list | grep mypy
mypy                          0.812
mypy-extensions               0.4.3
```

```
class Port(ABC):
    id_: int
    type_: ClassVar[ConnectionType]

    @property
    def key(self) -> PortKey:
        return self.type_, self.id_


P = TypeVar('P', bound=Port)

# and within some class
def get_ports_type(self, cls: Type[P]) -> Mapping[PortKey, P]:
    return {
        port.key: port  #
        for _, port in self.ports.items()
        if isinstance(port, cls)
    }
```

Results in
`error: <nothing> has no attribute "key"`.

If the `if isinstance(port, cls)` filter is removed the type of `port` is correctly inferred:
`error: Value expression in dictionary comprehension has incompatible type "Port"; expected type "P"`.

Seems similar to previous issue https://github.com/python/mypy/issues/5640.

**Comment by hauntsaninja** [comment]
(Not quite what you're looking for, but you might find using Protocols a more natural fit for this kind of thing)

**Comment by erictraut** [comment]
Can you provide a full, self-contained repro case? I've tried to guess how `ConnectionType` and `PortKey` might be defined, but I'm not able to repro the problem with the following:

```python
from abc import ABC
from typing import ClassVar, Mapping, Tuple, Type, TypeVar

class ConnectionType:
    ...

PortKey = Tuple[ConnectionType, int]

class Port(ABC):
    id_: int
    type_: ClassVar[ConnectionType]

    @property
    def key(self) -> PortKey:
        return self.type_, self.id_

P = TypeVar("P", bound=Port)

def get_ports_type(self, cls: Type[P]) -> Mapping[PortKey, P]:
    return {
        port.key: port for _, port in self.ports.items() if isinstance(port, cls)  #
    }
```

This produces no error with the latest published version of mypy.

**Comment by phyrwork** [comment]
ConnectionType is an Enum of str.

PortKey is an alias for a Tuple[...] type.

I can provide a more complete example later if this is not enough.

**Comment by uSpike** [comment]
I'm running into this issue, I think.

Here's a pretty minimal example:
```python
from dataclasses import dataclass
from typing import Dict, Type, TypeVar

@dataclass
class Base:
    key: str

@dataclass
class Subclass(Base):
    pass

T = TypeVar("T", bound=Base)

BaseDict = Dict[str, T]

objs = [Base("A"), Subclass("B")]

def dict_of_obj(obj_type: Type[T]) -> BaseDict[T]:
    return {obj.key: obj for obj in objs if isinstance(obj, obj_type)}

print(dict_of_obj(Base))
print(dict_of_obj(Subclass))
```
Running this results in:
```
{'A': Base(key='A'), 'B': Subclass(key='B')}
{'B': Subclass(key='B')}
```
however mypy complains:
```
test.py:20: error: <nothing> has no attribute "key"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by uSpike** [comment]
Per my previous example, this causes a mypy error (as shown above):
```python
def dict_of_obj(obj_type: Type[T]) -> BaseDict[T]:
    result: Dict[str, T] = {}
    for obj in objs:
        if isinstance(obj, obj_type):
            result[obj.key] = obj
    return result
```
however, the following does not if I access the `key` attribute before `isinstance()`:
```python
def dict_of_obj(obj_type: Type[T]) -> BaseDict[T]:
    result: Dict[str, T] = {}
    for obj in objs:
        key = obj.key  # access key attribute earlier
        if isinstance(obj, obj_type):
            result[key] = obj
    return result
```

**Comment by uSpike** [comment]
Sorry for the noise, but here's the smallest reproducible example I could make:

```python

from typing import Type, TypeVar

class Base:
    key: str = "foo"

T = TypeVar("T", bound=Base)

def func(obj_type: Type[T]) -> None:
    for obj in [Base()]:
        print(obj.key)  # OK
        if isinstance(obj, obj_type):
            print(obj.key)  # ERROR

func(Base)
```
```
test.py:13: error: <nothing> has no attribute "key"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by AlexWaygood** [comment]
Here's a round-up:

The original example that started this issue isn't self-contained, as @erictraut says, so isn't really much use here.

Examples [1](https://mypy-play.net/?mypy=0.920&python=3.10&flags=strict%2Cwarn-unreachable&gist=d6d5f8ac33becf2f17b16ab115518d69), [2](https://mypy-play.net/?mypy=0.920&python=3.10&flags=strict%2Cwarn-unreachable&gist=b5e20827c07654a2abc68e8a6fa4a841) and [3](https://mypy-play.net/?mypy=0.920&python=3.10&flags=strict%2Cwarn-unreachable&gist=23e2c9fa27fc8b78e1dcc59fc22aa82c) by @uSpike no longer reproduce on mypy 0.920+ (hooray! Also thanks @uSpike for providing the self-contained examples, which are always very helpful 🙂).
