### ISSUE TITLE
Support completely skipping a specific file from any mypy processing

### ISSUE THREAD

**Issue by omry** [python/mypy#10205]
**Feature**

Support excluding Python files based on a header comment without parsing them.
e.g:

file.py
```python
# mypy: skip_file

# mypy should not care about this syntax error.
def foo(:
  ...
```

This is similar to Flake's `# flake8: noqa` comment.

**Pitch**

I have a library that supports Python 3.6 and newer.
I am supporting a Python 3.8 feature (positional only arguments) , and I wanted to add some tests for it.
My library tests and lint are running in all supported Python version. The problem is that when mypy runs 3.6 and 3.7, it will fail when it hits the one file that contains the 3.8 syntax.

I tried several alternatives to (`# type: ignore`, `ignore_errors = True` in the config etc), I may have missed something but I think there is no solution for this case.

**Comment by hauntsaninja** [comment]
mypy 0.812 supports `--exclude`
