### ISSUE TITLE
Callable... has no attribute "__get__"

### ISSUE THREAD

**Issue by p00ya** [python/mypy#10206]
**Bug Report**

Python functions should have an inferred type that is aware they have a `__get__` attribute.

**To Reproduce**

Create `test.py` with the contents:

```
from typing import Any


def foo(x: Any) -> None:
    pass


class Bar():

    def __init__(self) -> None:
        self.f = foo.__get__(self, self.__class__)
```

Then run: `python3 -m mypy --strict test.py`

**Expected Behavior**

No errors.  Python functions are guaranteed to have `__get__` attributes as per https://docs.python.org/3.7/howto/descriptor.html#functions-and-methods

I understand there is a workaround using protocols and decorators, but this is quite cumbersome.  It would be great if mypy could infer that `foo` is a Python function and therefore has a `__get__` attribute.

**Actual Behavior**

mypy prints the error:
`test.py:11: error: "Callable[[Any], None]" has no attribute "__get__"`

**Your Environment**

- Mypy version used: mypy 0.812
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: Python 3.9.2
- Operating system and version: macOS 11.2

**Comment by AlexWaygood** [comment]
[No longer reproducible](https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=184d1ef02926bc3e5ed663873f35a2a4) due to changes made in typeshed.
