### ISSUE TITLE
PySide6 - mypy doesn't handle slots correctly

### ISSUE THREAD

**Issue by UmbralReaper** [python/mypy#10209]
**Bug Report**

As far as I can tell, this is the cause of mypy, not Qt. The type signature looks okay to me, and it works correctly as an object, only failing as a decorator.

**To Reproduce**

1. Install `PySide6` and `mypy`
2.  Run `mypy` on the following script
```py
from PySide6.QtCore import Slot

@Slot()
def slot_function() -> None:
    pass
```

**Actual Behavior**

Raises error: `error: "Slot" not callable`

**Your Environment**

```
python -m venv .venv3
.venv3\Scripts\Activate
(.venv3) pip install -U pip
(.venv3) pip install mypy
(.venv3) pip install PySide6==6.0.2
(.venv3) python -m mypy test.py
```

- Mypy version used: `0.812`
- Python version used: `3.9.1`
- Operating system and version: `Windows 19042.867`

**Additional Context**
Here's the `.pyi` stub of `Slot`:
```py
class Slot(object):
    def __init__(self, *types:type, name:typing.Optional[str]=..., result:typing.Optional[str]=...) -> typing.Callable: ...
```

Interestingly, `reveal_type(slot_function)` returns `Any`.

**Comment by JelleZijlstra** [comment]
That stub is wrong; it should presumably have a `__call__` method.

```
@Slot()
def slot_function(): ...
```
is equivalent to `Slot()(slot_function)`, which will try to use `Slot.__call__`.

**Comment by UmbralReaper** [comment]
Which makes it a problem on Qt's end. Thanks for the help!
