### ISSUE TITLE
Rejecting a single constraint on TypeVar prevents subtype restriction

### ISSUE THREAD

**Issue by alexchandel** [python/mypy#10239]
**Bug Report**

mypy rejects a single constraint on a `TypeVar` that would restrict instances to one particular subtype.

**To Reproduce**

Consider the following, where `_T` meant to constrain `x`, `b`, and `t` to the same, unspecified subtype of `Number`:

```py
from typing import TypeVar
from numbers import Number

_T = TypeVar('_T', Number)

def clamp(x: _T, b: _T, t: _T) -> _T:
    """Clamp x between [b, t]."""
    return b if x < b else t if x > t else x
```

**Actual Behavior**

mypy reports `TypeVar cannot have only a single constraint`.  (Ignore that `<` isn't supported for generic Number, this is a bad example.)

**Your Environment**

- Mypy version used: 0.812
- Python version used: 3.9.2

**Comment by hauntsaninja** [comment]
mypy is correct here, you want to use `bound`.

**Comment by alexchandel** [comment]
😅 🤦‍♀️
