### ISSUE TITLE
mypy failure for "Need type annotation for 'options'

### ISSUE THREAD

**Issue by chunji08** [python/mypy#10263]
Hi there, 
I have such define in my python file: 
```
options = defaultdict(lambda: defaultdict(lambda: defaultdict(str)))
options['modem1']['ByCost'] = ...
options['modem1']['ByCarrier'] = ...
options['modem1']['BySimSignal'] = ...
options['modem1']['SwitchBackByTimer'] = ...

```

And it fails during the mypy checking, for the message that : **Need type annotation for 'options'**,  Since I don't see anything wrong with this code, so is there any work around that I can have it passed the mypy checking for this ?  

Thanks, 

Chun

**Comment by hauntsaninja** [comment]
You can use `disable_error_codes` with error code `var-annotated`. Note that because mypy isn't able to infer types it will also likely not report errors in case you do make some.

**Comment by chunji08** [comment]
I don't know if my code would be accepted if I add this ?  is there any alternatives ?  Thanks anyway for the help.
