### ISSUE TITLE
Function returning int or float can't be typed as returning Number or Real

### ISSUE THREAD

**Issue by turlando** [python/mypy#10262]
**Bug Report**

I'm not sure about the scope of this issue, so I'm opening it here for the moment.

[This](https://mypy-play.net/?mypy=latest&python=3.8&gist=dbfd62544816baebec6d2bd19c2337c5) code:

```
from numbers import Number
from dataclasses import dataclass


@dataclass
class Foo:
    n: int
    f: float


def n_key(f: Foo) -> Number:
    return f.n


def f_key(f: Foo) -> Number:
    return f.f


l0 = [Foo(23, 23.00), Foo(42, 42.00)]
l1 = sorted(l0, key=n_key, reverse=True)
l2 = sorted(l0, key=f_key, reverse=True)
```

produces the following errors:

```
error: Incompatible return value type (got "int", expected "Number")
error: Incompatible return value type (got "float", expected "Number")
error: Argument "key" to "sorted" has incompatible type "Callable[[Foo], Number]"; expected "Callable[[Foo], SupportsLessThan]"
error: Argument "key" to "sorted" has incompatible type "Callable[[Foo], Number]"; expected "Callable[[Foo], SupportsLessThan]"
```

Regarding the first two, according to the [Python's numeric tower](https://docs.python.org/3/library/numbers.html) and also according to my REPL:

```
>>> from numbers import Number
>>> isinstance(3, Number)
True
>>> isinstance(3.0, Number)
True
```

int and float should be instances of Number.

Regarding the other two errors: I think a Number should support `__lt__`.

---

**EDIT**:

I just realized that Number also includes Complex which of course isn't comparable.

Switching to Real as follows:

```
def n_key(f: Foo) -> Real:
    return f.n


def f_key(f: Foo) -> Real:
    return f.f
```

changes the scope of the issue, producing:

```
main.py:12: error: Incompatible return value type (got "int", expected "Real")
main.py:16: error: Incompatible return value type (got "float", expected "Real")
```

I'm not sure anymore what should be the right thing.

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: _none_
- Mypy configuration options from `mypy.ini` (and other config files): _none_
- Python version used: 3.8,6
- Operating system and version: Linux x64

**Comment by JelleZijlstra** [comment]
This is an instance of #3186.
