### ISSUE TITLE
Incompatible default error on generic function

### ISSUE THREAD

**Issue by hatal175** [python/mypy#10276]
**Bug Report**

Mypy gives an Incompatible default error. I'm having trouble finding if this issue has come up before, so please close if you're familiar.

The following code (Taken from difflib.SequenceMatcher) shows the error:

from typing import Optional, Callable, Sequence
_T = TypeVar("_T")

def ff(
        self, isjunk: Optional[Callable[[_T], bool]] = None, a: Sequence[_T] = '', b: Sequence[_T] = ''
    ) -> None:
        pass

**Expected Behavior**

No errors.

**Actual Behavior**

main.py:16: error: Incompatible default for argument "a" (default has type "str", argument has type "Sequence[_T]")
main.py:16: error: Incompatible default for argument "b" (default has type "str", argument has type "Sequence[_T]")

**Your Environment**

latest mypy on mypy playground with python 3.9.

**Comment by hauntsaninja** [comment]
Yeah, this is a common issue https://github.com/python/mypy/issues/3737
