### ISSUE TITLE
"Skipping analyzing <code in my app>: found module but no type hints or library stubs" even though the code is in my app and has type annotations

### ISSUE THREAD

**Issue by jfhbrook** [python/mypy#10273]
When I try to use mypy, mypy tells me that it can't find type annotations in my project, even though I can open/import the files in my app and see the type annotations that I intentionally put there.

I don't know what kind of Hell situation I'm looking at in my app's state, but all I did was:

1. Take an existing app with Python library code in a "src" directory and add type annotations to it
2. Ensure I can import the modules manually, that tests pass, that the app runs
3. Add mypy to my virtualenv (my app is installed in this virtualenv as an editable package)
4. Attempt to run `mypy ./src`

What I expected was to either get either a clean type check or actionable errors not involving my code missing type annotations.

What I actually got was a bunch of error messages like `src/app/mappers.py:3: error: Skipping analyzing 'app.json': found module but no type hints or library stubs` even though `./src/app/json.py` exists, can be imported, and *entirely consists* of type annotations.

- Mypy version used: 0.812 in a virtualenv
- Mypy command-line flags: I ran `. ./venv/bin/activate; mypy ./src`
- Mypy configuration options from `mypy.ini` (and other config files): I don't have a mypy.ini but I do have `package_dir={"": "src"}` and `packages=find_packages(where="src")` in my setup.py
- Python version used: 3.7.3
- Operating system and version: MacOS Catalina 10.15.7

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules and use `mypy -v` to see what's going on. For more help ask in Gitter.
