### ISSUE TITLE
Outer type guards do not apply in nested functions

### ISSUE THREAD

**Issue by bijij** [python/mypy#10280]
**Bug Report**

Type guards evaluated before nested function calls are ignored by the type checker.

**To Reproduce**

Create a nested function with union argument, and type guard in the outer function.
E.g. File: `test.py`
```py
from typing import Optional, Union

def foo(item: Union[str, int]) -> Optional[str]:
    if isinstance(item, int):
        return None
    
    def bar() -> str:
        return item.capitalize()

    return bar()
```

**Expected Behavior**

Type checking would pass.

**Actual Behavior**

Mypy ignores the guard in the outer function and assumes variable `item` 

```
PS> mypy .\test.py
test.py:8: error: Item "int" of "Union[str, int]" has no attribute "capitalize"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: v0.812
- Python version used: 3.9.2 64-bit (Windows)

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/latest/common_issues.html#narrowing-and-inner-functions
