### ISSUE TITLE
--ignore-missing-imports not working for modularized typeshed types

### ISSUE THREAD

**Issue by FuegoFro** [python/mypy#10283]
**Bug Report**

Mypy does not respect the `--ignore-missing-imports` flag/`ignore_missing_imports = True` config for types that are now modularized out of typeshed (eg the [`legacy_bundled_packages`](http://github.com/FuegoFro/mypy/blob/98edc4148ac9fb3bdb601419ab2bafbac848fc6c/mypy/stubinfo.py#L4-L86)).

I don't *think* this is a typeshed bug, but let me know if you disagree and I can make an issue there instead.

**To Reproduce**

Given the following file:

```python
from redis.sentinel import Sentinel
```

I always get the following output:

```
python -m mypy --ignore-missing-imports example.py
example.py:1: error: Library stubs not installed for "redis.sentinel" (or incompatible with Python 3.7)
example.py:1: note: Hint: "python3 -m pip install types-redis"
example.py:1: note: (or run "mypy --install-types" to install all missing stub packages)
example.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

It doesn't matter whether `--ignore-missing-imports` is included or whether `types-redis` is installed, it will always give me exactly that output.

Note that a line like `from foo_asdf import bar` *is* correctly ignored by the `--ignore-missing-imports` flag and types that *are* defined by `types-redis` (like `redis.StrictRedis`) will work correctly (with or without the flag) when that package is installed.

**Your Environment**

- Mypy version used: `mypy 0.820+dev.e46aa6df6126cf47bea97bf9f94d7cba093d0103` (latest `master` at time of filing)
- Mypy command-line flags: `--ignore-missing-imports`
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: Python 3.7.6
- Operating system and version: macOS 10.15.7

**Comment by FuegoFro** [comment]
Digging into it a bit more this seems to be intentional:
https://github.com/python/mypy/blob/e46aa6df6126cf47bea97bf9f94d7cba093d0103/mypy/build.py#L2446-L2452
However even putting the more specific, non-global ignore in config (eg `[mypy-redis.*] ignore_missing_imports = True`) fails to suppress the error as long as the global `--ignore-missing-imports`/`[mypy] ignore_missing_imports = True` is set.

Given the comment, I wonder if the "fix" here is to look for a more specific ignore and honor that if it exists? Is that even feasible?

Either way it would be great to inform users that the `--ignore-missing-imports` flag is being intentionally ignored for this (somewhat arbitrary?) set of packages.

**Comment by JukkaL** [comment]
I think that if we have `ignore_missing_imports = True` under `[mypy-redis.*]`, mypy should honor it, even if `ignore_missing_imports` is set globally. So that seems like something we should fix by the next public release, assuming it's technically feasible. Otherwise, we should at least document this behavior clearly, as it's pretty unintuitive.
