### ISSUE TITLE
"--follow-imports=error" is confusing

### ISSUE THREAD

**Issue by wlf100220** [python/mypy#10285]
**Documentation**
Today, when I used `--follow-imports=error` with mypy, it prompted follow errors.
```
main.py:1: note: Import of 'mycode.bar' ignored
main.py:1: note: (Using --follow-imports=error, module not passed on command line)
```
This description is not clear enough.

My first feeling was that there might be some errors in the package or mypy could not find the package, or it might need passing the module to mypy(in some way) because it told that the "module not passed on command line". In fact, mypy had found it, but I didn't know that, and I wanted mypy to check those packages. So I went to search what the problem is.

And eventually, it took me one hour to find that:

**this setting will force mypy to replace the package with `Any`。Just like `--follow-imports=skip`**

and  `--follow-imports=normal` fit my demand.

# For more explicit
I suggest you add more information about this setting.
Such as:
```
main.py:1: note: import of 'mycode.bar' found but replaced with Any (Using --follow-imports=error).
main.py:1: note: to type check the module, you can use --follow-imports=normal or --follow-imports=silent.
```

And `--follow-imports=skip-with-error` or `--follow-imports=skip-with-warning` might be more appropriate.

**Comment by hauntsaninja** [comment]
Why do people love misusing this option? The documentation already strongly recommends (in boldface) the default here: https://mypy.readthedocs.io/en/latest/running_mypy.html#following-imports 

If you're going to go counter that recommendation without understanding what the option does, I don't think any further amount of documentation would save you that hour.

**Comment by wlf100220** [comment]
> Why do people love misusing this option? The documentation already strongly recommends (in boldface) the default here: https://mypy.readthedocs.io/en/latest/running_mypy.html#following-imports
> 
> If you're going to go counter that recommendation without understanding what the option does, I don't think any further amount of documentation would save you that hour.

Thank you for replying. But I still think that the doc could be more explicit. Because it does confuse me and the doc is too long to read, in terms of an option. A  friendly doc would make more users. So, be as friendly as possible. Just a little advice.
