### ISSUE TITLE
literal NamedTuple as a type

### ISSUE THREAD

**Issue by belm0** [python/mypy#10294]
**Pitch**

I have an API that accepts dynamically created NamedTuple types.  I'd at least like to specify `NamedTuple` as a type hint, and have mypy allow any attribute access on top of Tuple operations.  The infinitely wider scope of `Any` isn't too attractive.  (Is there something else suitable from `typing` that I'm missing?)

```
error: "NamedTuple" has no attribute "x"  [attr-defined]
```

**Comment by JelleZijlstra** [comment]
You could create a Protocol that has the tuple operations that you need plus a `def __getattr__(self, attr: str) -> Any:`. NamedTuple by itself doesn't make sense as a type because it's not actually a type.

**Comment by belm0** [comment]
Thank you

I found some related issues with info:
  * https://github.com/python/typing/issues/431
  * https://github.com/python/mypy/issues/3915

**Comment by AlexWaygood** [comment]
I think @JelleZijlstra's suggestion is the best realistic solution here :/

**Comment by JelleZijlstra** [comment]
Actually, we made a change a while ago that now allows NamedTuple as a type.

**Comment by belm0** [comment]
It's not working as I expect.  Since the specific NamedTuple type is unknown, I don't expect `attr-defined` errors from mypy on attribute access.

```python
def func(x: NamedTuple) -> None:
    y = x.foo

class MyTuple(NamedTuple):
    baz: int

func(MyTuple(5))
```

```
error: "NamedTuple" has no attribute "foo"  [attr-defined]
```

Rather, I think what has been implemented so far is attribute checking for known types derived from NamedTuple:
```python
class MyTuple(NamedTuple):
    baz: int

def func(x: MyTuple) -> None:
    y = x.baz

func(MyTuple(5))
```

**Comment by JelleZijlstra** [comment]
As implemented, it's basically a NamedTuple version of `object`, allowing operations valid on all NamedTuples, while you seem to want a NamedTuple version of `Any`. That's obviously unsafe and doesn't feel worth an addition to the type system.
