### ISSUE TITLE
No "Missing return statement" if the return type's library lacks stubs

### ISSUE THREAD

**Issue by opk12** [python/mypy#10297]
```
$  cat -n a.py
     1	import pandas as pd
     2	
     3	def to_float() -> float:
     4	    print()
     5	
     6	def to_series() -> pd.Series:
     7	    print()
     8	

a.py:1: error: Skipping analyzing 'pandas': found module but no type hints or library stubs
a.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
a.py:3: error: Missing return statement
Found 2 errors in 1 file (checked 1 source file)
```

Quoting [mypy's CLI docs](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-warn-no-return):

> By default, mypy will generate errors when a function is missing return statements in some execution paths. The only exceptions are when:
> 
>  -  The function has a None or Any return type
>  -  The function has an empty body or a body that is just ellipsis (...). Empty functions are often used for abstract methods.

So it seems that mypy treats the externally-defined return type as a potential alias for `None` or `Any`, but this is very rare. (Even when it happens, mypy can assume it is going to be called again with the library stubs installed and there is no harm in giving an additional warning now.)

mypy latest on python 3.7 and python 3.9

**Comment by erictraut** [comment]
I think mypy's current behavior is intended and correct. If the import can't be resolved or the library lacks type information, all symbols imported from it will be evaluated as `Any`. A function that is annotated to return `Any` does not need to have a return statement.

**Comment by opk12** [comment]
@erictraut @hauntsaninja  The point is that
* No real-world library exposes a public type alias for `None`.
* If a library type-aliases `Optional[...]`: an execution path in my function that returns `None` should be marked as such explicitly, to document that it's intentional.

This is different from a locally-defined type alias for `Any` (which may be a development-only thing) or an unannotated function.
