### ISSUE TITLE
false "not async iterable" on use of overload with async iterable

### ISSUE THREAD

**Issue by belm0** [python/mypy#10301]
**Bug Report**

Using typing.overload on an async iterator doesn't behave as I expected:

```python3
@overload
async def transitions(self, value: T) -> AsyncIterator[Tuple[T, T]]: ...
@overload
async def transitions(self, predicate: P) -> AsyncIterator[Tuple[T, T]]: ...
async def transitions(self, value_or_predicate):
    # impl with yield ...
```

if I remove `async` qualifier on the overloads, it appears to work.  But that doesn't seem right...

**Expected Behavior**

no errors on correct usage

**Actual Behavior**

error on usage:
```
error: "Coroutine[Any, Any, AsyncIterator[Tuple[str, str]]]" has no attribute "__aiter__" (not async iterable)  [attr-defined]
```

**Your Environment**

- Mypy version used: .812
- Python version used: 3.7.7

**Comment by hauntsaninja** [comment]
That's kind of unfortunate. Removing the "async" from the overloads is probably your best solution, see https://github.com/python/mypy/issues/5385#issuecomment-407281656 for some more context

**Comment by belm0** [comment]
Removing the `async` qualifier from the overloads seems sure to catch some tools off guard (IDE, etc.).

The agreed-upon solution should be clearly documented in the `typing.overload` docs so that everyone has a standard reference.

**Comment by belm0** [comment]
Removing the `async` qualifier now also confuses pylint:  https://github.com/PyCQA/astroid/issues/1015

**Comment by dm9pZCAq** [comment]
i think this is related to this issue

code:
```py
from abc import ABC, abstractmethod
from typing import Any, AsyncIterator


class MyABC(ABC):
    @abstractmethod
    async def func(self) -> AsyncIterator[Any]: pass


class MyClass(MyABC):
    async def func(self) -> AsyncIterator[Any]:
        yield 1
```
error:
```
test.py:11: error: Return type "AsyncIterator[Any]" of "func" incompatible with return type "Coroutine[Any, Any, AsyncIterator[Any]]" in supertype "MyABC"
```

@hauntsaninja as you can see in code example abstract and actual classes have the same `func` function signature, so i think https://github.com/python/mypy/issues/5385#issuecomment-407281656 is not fit into this example

---
* Mypy version used: 0.931
* Python version used: 3.9.9

**Comment by hauntsaninja** [comment]
They do not have the same type, because `yield` fundamentally changes what `def` does, so #5385 still applies. Feel free to replace `pass` with `if False: yield 1`. Or remove the `async` qualifier.

Closing because while mypy's behaviour here is surprising, it is correct, and I don't see a better solution here.
