### ISSUE TITLE
attrs plugin: support the auto_detect option

### ISSUE THREAD

**Issue by hynek** [python/mypy#10328]
**Feature**

attrs has had an option to automatically detect dunder methods that are directly on the current class. It's called `auto_detect` and is off by default in old-school APIs (attr.s/attrs) and on in NG (define).

mypy currently doesn't support that.

**Pitch**

This feature is really nice at preventing a common gotcha of writing an own method and forgetting to set `init=False` and attrs silently overwriting that code.

Here's an example that works as expected but doesn't pass mypy:

```python
@attr.define
class SortableTableHeaders:
    headers: dict[str, str]
    default: str

    def __init__(self, names: tuple[str, ...]) -> None:
        def normalize(s: str) -> str:
            return s.replace(" ", "-").lower()

        self.default = normalize(names[0])
        self.headers = {normalize(n): n for n in names}
```

It does it for all dunders but I think only `__init__` is relevant. To stress once more: only the current class is considered, not anything inherited.

Ref https://github.com/python-attrs/attrs/issues/793

**Comment by ngnpope** [comment]
Sort of related to this is that `__attrs_init__` is not recognised when `init=False`, so if I want to define my own `__init__` that calls `__attrs_init__`, I get:

```
error: "X" has no attribute "__attrs_init__"; maybe "__attrs_attrs__"?  [attr-defined]
```

Unrelated, it would be nice if the plugin recognised `attrs.define` as well as `attr.define`, etc.

**Comment by hynek** [comment]
> Unrelated, it would be nice if the plugin recognised `attrs.define` as well as `attr.define`, etc.

It does for me? attrs.define is a re-import from attr and MyPy should be able to follow it. At least I've replaced it in all my projects and MyPy is happy.

**Comment by ngnpope** [comment]
> It does for me? attrs.define is a re-import from attr and MyPy should be able to follow it. At least I've replaced it in all my projects and MyPy is happy

Maybe I just got confused amongst the other errors 😅

**Comment by hynek** [comment]
I believe this has been fixed!
