### ISSUE TITLE
lambda expression not recognised as FunctionType, reported as Callable[[Any], Any] instead

### ISSUE THREAD

**Issue by neutrinoceros** [python/mypy#10320]
**Bug Report**

Very likely related to #8869 and #9934

**To Reproduce**

(Write your steps here:)

run mypy against this file
```python
from types import FunctionType

my_lambdas:dict[str, FunctionType] = {}
my_lambdas["example"] = lambda x: x**2

```

**Expected Behavior**
no errors or warnings (since `is instance(lambda x: x**2, FunctionType)` evaluates to `True`).

**Actual Behavior**

```
mypy_bug.py:4: error: Incompatible types in assignment (expression has type "Callable[[Any], Any]", target has type "FunctionType")
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: Python 3.9.1
- Operating system and version: OSX

**Comment by JelleZijlstra** [comment]
`FunctionType` should not be used in type annotations at the moment. See #5958 and #3171 for some context.

**Comment by neutrinoceros** [comment]
fair enough. Thanks
