### ISSUE TITLE
Unstable error output for overload violation

### ISSUE THREAD

**Issue by antonagestam** [python/mypy#10336]
**Bug Report**

Using pytest-mypy-plugins to [add type checks for py-moneyed](https://github.com/py-moneyed/py-moneyed/pull/162/files#diff-8bc94a3006768345d17c827c0bb5840e6e4daee6de1c2b1ea672f53f162d171dR8-R9), I stumbled into an issue where mypy produces different output depending on whether or not the cache is populated. The tests check that trying to instantiate `Money` without providing a `currency` argument yields an error. When the cache is populated, the output contains `Money` in the signature, but when it's fresh it instead contains `__init__`.

While trying to reproduce this with a minimal example, I discovered that it doesn't occur with a plain file, so something about the module structure plays into it. With a plain file the output was always `__init__`.

**To Reproduce**

A package structured like this: 

```
repr
├── __init__.py
└── repr.py
```

Where repr.py contains:

```
from __future__ import annotations
from typing import overload


class Money:
    @overload
    def __init__(self, amount: object = ..., *, currency: str) -> None:
        ...

    @overload
    def __init__(self, amount: object, currency: str) -> None:
        ...

    def __init__(
        self,
        amount: object = 0,
        currency: str | None = None
    ) -> None:
        if currency is None:
            raise TypeError(
                "__init__() missing 1 required positional argument: 'currency'"
            )
```

And a script `reprod.py` outside the package:

```python
from repr import Money
Money(1)
```

Running `mypy --no-incremental reprod.py` outputs:

```
reprod.py:4: error: No overload variant of "Money" matches argument type "int"  [call-overload]
    Money(1)
    ^
reprod.py:4: note: Possible overload variants:
reprod.py:4: note:     def __init__(self, amount: object = ..., *, currency: str) -> Money
reprod.py:4: note:     def __init__(self, amount: object, currency: str) -> Money
Warning: unused section(s) in setup.cfg: [mypy-moneyed.test_l10n], [mypy-moneyed.test_moneyed_classes], [mypy-babel.*]
Found 1 error in 1 file (checked 1 source file)
```

While consecutive runs of `mypy reprod.py ` outputs:

```
reprod.py:4: error: No overload variant of "Money" matches argument type "int"  [call-overload]
    Money(1)
    ^
reprod.py:4: note: Possible overload variants:
reprod.py:4: note:     def Money(self, amount: object = ..., *, currency: str) -> Money
reprod.py:4: note:     def Money(self, amount: object, currency: str) -> Money
Found 1 error in 1 file (checked 1 source file)
```

**Expected Behavior**

Stable output, don't know whether it should be `Money` or `__init__`.

**Your Environment**

- Mypy version used: mypy 0.812
- Mypy command-line flags: -
- Mypy configuration options from `mypy.ini` (and other config files):

```
[mypy]
python_version = 3.9
show_error_codes = True
pretty = True
files = moneyed

ignore_missing_imports = False
no_implicit_optional = True
strict_equality = True
strict_optional = True
check_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_defs = True
disallow_untyped_calls = True
disallow_untyped_decorators = True
disallow_subclassing_any = True

warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
warn_unreachable = True
```

- Python version used: Python 3.9.4
- Operating system and version: MacOS 11.2.3, but same behavior also observed in Github Actions with ubuntu-latest.

**Comment by erictraut** [comment]
This bug appears to have been fixed. I can't repro it with the latest version of mypy (1.5).
