### ISSUE TITLE
mypy error `Too many arguments for "object"` for creating instance of a Type with arguments

### ISSUE THREAD

**Issue by anikolaienko** [python/mypy#10343]
Consider the code:
```python
from typing import Type, TypeVar

TargetObjType = TypeVar("TargetObjType")

def build_object(target_class: Type[TargetObjType]) -> TargetObjType:
    return target_class(1)  # mypy error
```

Why am I getting `Too many arguments for "object"` error when passing arguments to `target_class()` and how to avoid this error?

**Comment by mataney** [comment]
Same here

**Comment by JelleZijlstra** [comment]
This mypy error seems correct. There is no bound on `TargetObjType`, so the function should work with any type. But if you run `build_object(object)`, your function will throw.

**Comment by anikolaienko** [comment]
I agree @JelleZijlstra , now I see that there is no way for type checker to predict how many arguments `target_class(...)` can actually accept and it's safer to assume no arguments in this case. I use `# type: ignore [call-arg]` in this case.

BTW, this is my project, if anybody is interested, using an opportunity to promote it :)
https://github.com/anikolaienko/py-automapper

**Comment by Goliaten** [comment]
Maybe `Callable[[Any], TargetObjType]` for `target_class` could be a solution, that doesn't involve `# type: ignore`?
