### ISSUE TITLE
Report a missing function that is not missing in pandas

### ISSUE THREAD

**Issue by guruyaya** [python/mypy#10369]
Code In a file named testmypy.py goes like this:
`import pandas as pd
a = pd.DataFrame([ ['A', 1, 2], ['B', 2, 3] ], columns=['0', '1', '2'])
y = pd.Series([3,4])

y.groupby(a['0']).mean()

print (y)`
**Expected Behavior**
No error should be reported, as groupby is a valid method for pandas series

**Actual Behavior**
testmypy.py:5: error: "Series[int]" has no attribute "groupby"

**Your Environment**
Mypy 0.812
pandas 1.2.4
pyhton 3.8.5 (installed in anaconda)
Windows 10
No command line params passed
mypy.ini
`
[mypy]
python_version = 3.8
warn_return_any = True
warn_unused_configs = True
python_executable = C:\\Users\\User\\anaconda3\\python.exe
; plugins = numpy.typing.mypy_plugin

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-nptyping.*]
ignore_missing_imports = True
`
- Mypy version used:
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used:
- Operating system and version:

**Comment by JelleZijlstra** [comment]
Mypy itself doesn't know anything about pandas, and pandas itself apparently doesn't provide types. You may have installed some incomplete stubs package for pandas.
