### ISSUE TITLE
Weak type checking mode

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1038]
This is place-holder issue for a 'weak' type checking mode where mypy would do some useful type checking within functions that have no annotations.

**Comment by JukkaL** [comment]
We could use the same mode for module top levels by default to generate fewer errors.

This is a generalization of #374.

**Comment by JukkaL** [comment]
To rephrase, the objective is to do useful type checking without many false positives / useless reported errors for plain vanilla Python code without annotations.

**Comment by JelleZijlstra** [comment]
Weak mode was removed in #2213 last year, so I think this issue can be closed.
