### ISSUE TITLE
Nested unpacking of `addrinfo` gives "too many values to unpack"

### ISSUE THREAD

**Issue by thijsvandien** [python/mypy#10387]
**Bug Report**

```
addrinfo = await loop.getaddrinfo(hostname, None)
ips = (ip for _, _, _, _, (ip, _) in addrinfo)
```
results in:
```
error: Too many values to unpack (2 expected, 4 provided)
```
and changing it to:
```
ips = (sockaddr[0] for _, _, _, _, sockaddr in addrinfo)
```
makes that go away.

It seems that mypy has an issue with nested unpacking, but I don't see in what way it goes wrong; "4 provided" makes no sense to me. Using `(ip, port)` instead of `(ip, _)` does not make any difference.

I'm using:
- mypy 0.812
- Python 3.8.7

**Comment by JelleZijlstra** [comment]
This is because of the function's definition in typeshed: https://github.com/python/typeshed/blob/4ac3ccad45266d3417a3f8f94b1685bca3c227c5/stdlib/asyncio/base_events.pyi#L83. The last element of the tuple may be either a 2-tuple or a 4-tuple.

**Comment by JelleZijlstra** [comment]
Yes, at least the first variant. I'm not sure when it's a 4-tuple, so maybe that possibility can't actually happen with your code.

**Comment by thijsvandien** [comment]
It appears to be a matter of IPv4 vs IPv6. Obviously mypy can't know I'm only dealing with IPv4 here. Thanks for pointing this out. Other than that the error could've been clearer, the mypy isn't in the wrong then.
