### ISSUE TITLE
None appears to not be compatible with Type[<nothing>]

### ISSUE THREAD

**Issue by DevilXD** [python/mypy#10396]
**Bug Report**

`None` appears to not be compatible with `Type[<nothing>]`, possibly because of it being a singleton. The reproduction steps show a simplified version of the code where this issue have been encountered.

**To Reproduce**

```py
from typing import Generic, Type, TypeVar

_T = TypeVar("_T")

class A(Generic[_T]):
    pass

def create_typed_obj(ret_type: Type[_T]) -> A[_T]:
    obj: A[_T] = A()
    return obj

a1 = create_typed_obj(int)  # OK
reveal_type(a1)  # note: Revealed type is "A[builtins.int*]"

# error: Need type annotation for "a2"
# error: Argument 1 to "create_typed_obj" has incompatible type "None"; expected "Type[<nothing>]"
a2 = create_typed_obj(None)
reveal_type(a2)  # note: Revealed type is "A[Any]"

# error: Argument 1 to "create_future" has incompatible type "None"; expected "Type[None]"
a3: A[None] = create_typed_obj(None)
reveal_type(a3)  # note: Revealed type is "A[None]"
```

**Expected Behavior**

`create_typed_obj(None)` should result in a `A[None]` type being assigned, and no errors.

**Actual Behavior**

See the reproduction code.

**Your Environment**

- Mypy version used: mypy-0.820+dev.44925f4b121392135440f53d7c8a3fb30593d6cc (latest master)
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.8.8
- Operating system and version: Win7x64

**Comment by JelleZijlstra** [comment]
That seems correct to me, since None is not a type. You may be interested in the `TypeForm` proposal at #9773.
