### ISSUE TITLE
mypyc: Class attributes not being set when subclassing dict

### ISSUE THREAD

**Issue by monoidic** [python/mypy#10398]
**Bug Report**

When using mypyc, class attributes may not be instantiated in some cases where it is set to be a subclass of some other class. Observed with a class subclassing the builtin `dict` class.

**To Reproduce**

A code example is given here.

```python
#!/usr/bin/env python3

from typing import Dict

class Buggy(dict):
    attr = 'foo'

    def method(self) -> str:
        return self.attr

class Workaround(dict):
    def __init__(self) -> None:
        self.attr = 'foo'

    def method(self) -> str:
        return self.attr

class Expected:
    attr = 'foo'

    def method(self) -> str:
        return self.attr


def bug() -> Dict[str, str]:
    ret_values = {}
    ret_values['expected'] = Expected().method()
    ret_values['workaround'] = Workaround().method()

    try:
        ret_values['buggy'] = Buggy().method()
    except AttributeError as e:
        ret_values['buggy'] = str(e)

    return ret_values

print(bug())
```

Three classes are given: `Buggy`, `Workaround` and `Expected`. `Buggy` subclasses dict and displays the bug described, where the attribute `attr` is inaccessible from the method `method` (and by directly accessing it from a class instance). `Workaround` suclasses `dict`, but instantiates the attribute within `__init__` and the attribute works just fine as an instance attribute. With `Expected`, the class attribute works just fine.
When running this script without mypyc compilation, it outputs:
`{'expected': 'foo', 'workaround': 'foo', 'buggy': 'foo'}`
After compiling the script with e.g `mypyc test.py` and running it with e.g `python -c 'import test'`, it produces this output:
`{'expected': 'foo', 'workaround': 'foo', 'buggy': "'Buggy' object has no attribute 'attr'"}`

**Expected Behavior**

mypyc-compiled classes subclassing `dict` are able to have class attributes.

**Actual Behavior**

mypyc-compiled classes subclassing `dict` are not able to have class attributes.

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: n/a (bare `mypyc test.py`)
- Mypy configuration options from `mypy.ini` (and other config files): n/a / defaults?
- Python version used: tested with 3.9.4 and 3.8.9
- Operating system and version: Gentoo Linux, n/a

**Comment by JukkaL** [comment]
Can you file this issue again in https://github.com/mypyc/mypyc/issues? We like to keep mypyc issues separate from mypy issues.

**Comment by monoidic** [comment]
Very well. Opened [this](/mypyc/mypyc/issues/867) bug and closing this one.
