### ISSUE TITLE
Only type checking files that explicitly opt in

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1043]
Currently mypy follows all imports when type checking a file. For a large program not originally written with mypy in mind this can make it pretty hard to adopt mypy, as the a mypy run may generate hundreds or thousands of messages. Instead, mypy could initially treat every program file (also library modules without stubs) as 'ignored' (all imports targeting that file would get type `Any`), and only files with an annotation such as `# mypy: check`, `# mypy: weak` or `# mypy: strict` would be parsed and type checked, or modules that have a stub file. (Maybe this should be a special mode of running mypy instead of being the default.)

A large program would be migrated to mypy like this:

* Enable one extra file at a time using an annotation such as mentioned above, starting with a single file. Fix any issues until there is clean mypy output.
* For library modules, generate stubs as we encounter them (or just point mypy to them without adding any annotations, and mypy will treat the modules as having `Any` types).
* Generally follow imports when picking the next file to migrate. Either continue to files imported by one of the already processed files, or files that import one of the already processed files.

This could also work for a 'top-down' mypy migration, where many of the 'leaf' modules initially don't get processed by mypy at all. The current workflow only really supports a 'bottom-up' migration well, where we start with modules that depend on few modules and gradually follow the imports to modules that depend on these modules.

This was inspired by a discussion about Facebook's Hack yesterday. I understood that Hack enables this workflow (if you have experience with Hack, please correct me if I didn't understand this correctly.)

**Comment by kirbyfan64** [comment]
I thought the original plan was to only type check files containing `from typing import xyz`?

**Comment by gvanrossum** [comment]
Just to clarify, when you write "library modules" you're not proposing to
ignore existing stdlib stubs, are you?

**Comment by JukkaL** [comment]
Yeah, I mentioned modules that have a stub file as an exception, and that includes std library modules. I'm talking about ignoring library modules that only have `.py` files in the module search path. I'll make it clearer.

**Comment by JukkaL** [comment]
@kirbyfan64 That was the original plan, but we are probably not going to implement that. The general goal remains the same -- when running mypy against (a part of) a large existing code base, it shouldn't generate a ton of errors.

The current competing alternative approaches for reducing the number of false positives are 1) the one proposed here and 2) using a weak mode (#1038) by default for module top levels, or 3) both.

**Comment by gvanrossum** [comment]
So my current personal favorite is the following: Type-check only modules that are explicitly mentioned on the command line (if it's a package, all modules in that package's tree), use .pyi files when they exist, but when only a .py file is found and it's not on the command line, don't read it but just assume the module object has type Any.

**Comment by gvanrossum** [comment]
Is the `--silent-imports` flag enough to close this issue or should we also work on a feature where you can mark files as explicitly checked by adding `# mypy: check`?

**Comment by JukkaL** [comment]
Hmm i don't know if we have enough data to decide whether `--silent-imports` solves this issue satisfactorily. Let's keep this open still but there's probably no immediate need to work on this in the near future until we learn something new.

**Comment by gvanrossum** [comment]
@JukkaL Do you think it's okay to close this now? We have extensive experience with `--silent-imports` . We also have mypy.ini.

**Comment by gvanrossum** [comment]
Closing now. I really think `--silent-imports` is the right solution here. It has problems, but for those we should file separate issues.
