### ISSUE TITLE
incorrect type identified when union narrowed then used in returned lambda

### ISSUE THREAD

**Issue by danielknell** [python/mypy#10436]
**Bug Report**

a narrowed type is expanded again if used in a returned lambda

**To Reproduce**

```
import typing

def starts_with(value: typing.Union[str, bytes]) -> typing.Callable[[object], bool]:
    if isinstance(value, str):
        reveal_type(value)
        return (
            lambda x: isinstance(x, str) and reveal_type(x).startswith(reveal_type(value))
        )

    reveal_type(value)
    return (
        lambda x: isinstance(x, bytes) and reveal_type(x).startswith(reveal_type(value))
    )
```

```
main.py:5: note: Revealed type is 'builtins.str'
main.py:7: note: Revealed type is 'builtins.str'
main.py:7: error: Argument 1 to "startswith" of "str" has incompatible type "Union[str, bytes]"; expected "Union[str, Tuple[str, ...]]"
main.py:7: note: Revealed type is 'Union[builtins.str, builtins.bytes]'
main.py:10: note: Revealed type is 'builtins.bytes'
main.py:12: note: Revealed type is 'builtins.bytes'
main.py:12: error: Argument 1 to "startswith" of "bytes" has incompatible type "Union[str, bytes]"; expected "Union[bytes, Tuple[bytes, ...]]"
main.py:12: note: Revealed type is 'Union[builtins.str, builtins.bytes]'
Found 2 errors in 1 file (checked 1 source file)
```

can also be recreated here:

https://mypy-play.net/?mypy=latest&python=3.9&gist=0acb93bb8fa3da68180cd147923d9fd6

**Expected Behavior**

for the narrowed union to also apply within the lambda as `value` cannot change in this instance.

**Actual Behavior**

the original union is applied rather than the narrowed single type.

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9.4
- Operating system and version: debian stretch

**Comment by hauntsaninja** [comment]
This is the same sort of thing as https://mypy.readthedocs.io/en/latest/common_issues.html#narrowing-and-inner-functions
See https://github.com/python/mypy/issues/2608#issuecomment-727074535 for more details
