### ISSUE TITLE
Literal[Class]

### ISSUE THREAD

**Issue by Ierezell** [python/mypy#10437]
I rather post here than to pollute the bug issues. 

I was trying to have a type of `Literal[Class1, Class2]` with classes being classes (and not instances). 
However, mypy detect it as `Any` and raise an error : 

```python
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC, LinearSVC

ComponentType = Literal[MLPClassifier, LinearSVC, SVC]
```

Which raises : ` error: Parameter 1 of Literal[...] cannot be of type **"Any"**`

Thanks in advance for any help.

**Comment by JelleZijlstra** [comment]
Class objects are not allowed in Literal according to https://www.python.org/dev/peps/pep-0586/. You can use `Union[Type[...]]` instead, but that will also allow subclasses.

**Comment by Ierezell** [comment]
Hi @JelleZijlstra 
Thanks a lot for the fast reply ! 

If I define my type as a `Union[Type...]` it raises `"XXX" is incompatible with "Type[XXX]"`

However without type and just with `Union[X,y,z]` it does what I need and create the `Type[X]` implicitly in the alias (python 3.9.4).

Thanks again 
Have a great day

**Comment by JelleZijlstra** [comment]
I don't know what's going on in your code, but `Union` definitely does not implicitly add `Type[]`.

**Comment by Ierezell** [comment]
I guess it's because I then do a list of those components `list[Union[X,y,z]]`.
I guess it's working correctly and thanks for your time and help ! :)
