### ISSUE TITLE
Declaring a decorator to preserve the signature of the function that decorates, but which calls the function with an additional (named) argument, is it possible to avoid "missing (named) argument" error without making it optional?

### ISSUE THREAD

**Issue by julenpardo** [python/mypy#10441]
**Questions and Help**

Hello,

I've been searching for similar issues but haven't found anything similar, sorry if there's an existing ticket for this.

My use case is the following: I have a decorator that calls the function, passing an additional parameter to this function (which is obviously declared in the function signature). The context for this is that the decorated function is called within a context manager for dealing with database sessions (is the session object what is passed to the function). The callers of the decorated functions know nothing about the parameter passed by the decorator.

I've followed the [Generics/Declaring decorators](https://mypy.readthedocs.io/en/stable/generics.html#declaring-decorators) documentation for preserving the function signature, which works great, except for additional argument (which actually makes sense, as defined in the function signature).

In case the issue is not clear, I leave a MWE (omitting the mentioned context manager and database session stuff for simplicity; in this case it's just a constant), run with Python3.7 and mypy 0.782. In this case, the parameter is defined as a named parameter (because that's how in the actual code is done), but probably not really relevant; it could also be just a regular parameter.

```python
from functools import wraps
from typing import Any, Callable, Iterator, TypeVar, cast


FuncT = TypeVar("FuncT", bound=Callable[..., Any])


def my_decorator(function: FuncT) -> FuncT:
    @wraps(function)
    def wrapper(*args, **kwargs):
        result = function(*args, **kwargs, decorator_parameter=10)

        return result

    return cast(FuncT, wrapper)


@my_decorator
def insert(a: int, *, decorator_parameter):
    pass


insert(10)
```

Running mypy yields the missing argument error:

```
venv ❯❯❯ mypy test_type_check.py
test_type_check.py:23: error: Missing named argument "decorator_parameter" for "insert"
Found 1 error in 1 file (checked 1 source file)
```

Which, again, technically makes sense, as we're calling a function with a non-optional argument that is missing, but it's an argument defined by the assumption that the function is decorated.

So, the main question is the following, based on the assumption that we don't want to make the `decorator_parameter` optional: **is there any clever way for mypy to infer that a required argument will be passed by the decorator decorating the function?**

Thanks beforehand, and also thank you for your amazing work!

**Comment by JelleZijlstra** [comment]
This is close to what PEP 612 (https://www.python.org/dev/peps/pep-0612/) supports with `Concatenate`, but it doesn't help with keyword arguments.

**Comment by AlexWaygood** [comment]
Yes, unfortunately there isn't really a good way to express this in the current type system :(

I'm closing this issue, as I think the question has been answered, and feature requests that apply to the Python-typing framework as a whole (rather than specifically to mypy) should be discussed in the https://github.com/python/typing issue tracker or the [typing-sig mailing list](https://mail.python.org/archives/list/typing-sig@python.org/) rather than this issue tracker.
