### ISSUE TITLE
Protocols: issue with namedtuple

### ISSUE THREAD

**Issue by Tinche** [python/mypy#10466]
**Bug Report**

This is something I've come across working on enhancements to the attrs plugin.

**To Reproduce**

Doesn't work (but should):

```
from collections import namedtuple
from typing import Protocol, ClassVar

NT = namedtuple("NT", [])

class P(Protocol):
    a: tuple

class Test:
    a: NT = NT()

def test(a: P): pass

test(Test())
```

**Expected Behavior**

The function call should type-check, as `NT` is a subclass of `tuple`. This works:

```
from collections import namedtuple
from typing import Protocol, ClassVar

NT = namedtuple("NT", [])

class P(Protocol):
    a: tuple

class Test:
    a: tuple = NT()

def test(a: P): pass

test(Test())
```

**Actual Behavior**
```
a.py:14: error: Argument 1 to "test" has incompatible type "Test"; expected "P"
a.py:14: note: Following member(s) of "Test" have conflicts:
a.py:14: note:     a: expected "Tuple[Any, ...]", got "NT"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: commit 3cbcad0771a244031787c57231acb2bff39c3974 (so very recent as of time of writing)
- Mypy command-line flags: `mypy a.py`
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.9.4
- Operating system and version: Ubuntu 21.04

**Comment by AlexWaygood** [comment]
[Simpler repro](https://mypy-play.net/?mypy=latest&python=3.10&flags=warn-return-any&gist=bd0bf783fcef8bdd42c10a51b9cfdd15) that doesn't involve namedtuples:

```python
from typing import Protocol

class Foo: ...
class Bar(Foo): ...

class P2(Protocol):
    f: Foo

class Baz:
    f: Bar

class Baz2:
    f: Foo = Bar()

def test2(a: P2) -> None: ...

test2(Baz())
test2(Baz2())
```

But I'm afraid that this is expected behaviour; please see https://mypy.readthedocs.io/en/stable/common_issues.html#covariant-subtyping-of-mutable-protocol-members-is-rejected

**Comment by Tinche** [comment]
Interesting, thanks!
