### ISSUE TITLE
Binder bug with descriptor

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#10464]
This was discovered by the pyright author. Look at this message:

https://github.com/microsoft/pyright/issues/1814#issuecomment-830722301

Note that `member` is described by a descriptor whose getter and setter have incongruous types (`__get__` returns Animal, but `__set__` takes `HasName`, which is a protocol). Also note that `Cat` is a subclass of `Animal` but `Dog` is not.

Never mind the context, it seems he's discovered a bug in mypy; see lines in the comment marked with `!!!!`. The first time after
```
inst.member = cat_or_dog
reveal_type(inst.member)  # Animal
```
things seem all right. But then after
```
inst.member = dog
inst.member = cat_or_dog
reveal_type(inst.member)  # Dog ?!
```
it appears that the `Dog` type lingers in the binder.

**Comment by erictraut** [comment]
I filed a separate mypy bug for this already, so I think we can close this as a duplicate. See https://github.com/python/mypy/issues/10399.

**Comment by hauntsaninja** [comment]
Thanks both!
