### ISSUE TITLE
[mypyc] Compiled method is no longer a method

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#10503]
After compiling a module, I get an error at runtime because a 3rd-party library looks for a method and then tries to get the type hints from it. The problem is that after compiling the method is no longer a method (according to `inspect.ismethod()`) and even if I bypass that check then `typing.get_type_hints()` will fail because it is not a method.

To reproduce:
```
git clone https://github.com/Dreamsorcerer/bthidhub.git
cd bthidhub
mypyc agent.py
python3 -c 'import agent'
```

Maybe this is by design, but I don't think I saw this mentioned in the docs, especially as it is decorated, which I assumed to mean that it would not be compiled as a native class.

**Comment by JukkaL** [comment]
We prefer to keep mypyc issues [here](https://github.com/mypyc/mypyc/issues). Could you please file the issue again there?

**Comment by Dreamsorcerer** [comment]
Ah, didn't realise it now had it's own repository (and organisation...).
