### ISSUE TITLE
<directory> is not a valid python package name

### ISSUE THREAD

**Issue by matthieudesprez** [python/mypy#10515]
Migrating from 0.790 to 0.812, we are experiencing issues running mypy because we have an __init__.py file at the root of our project, and our project repository contains a dash in it's name.

I believe it comes from this PR #9614 which seems to change the way modules are crawled

Is there some option we can pass to prevent mypy to throw an error during this step ?

We are thinking about renaming the project root folder or moving all our code in a subfolder but any other solution would be appreciated

**Comment by hauntsaninja** [comment]
Maybe remove the `__init__.py`?

**Comment by matthieudesprez** [comment]
Wow now I feel dumb, thanks for the suggestion @hauntsaninja 

I thought this __init__.py file was needed to ease import across our different packages, but it seems it could be safely removed.
