### ISSUE TITLE
Redefinitions with more precise type are treated as errors

### ISSUE THREAD

**Issue by evtn** [python/mypy#10544]
I have two classes, A and B (which is a child of A)
Also, I have a function, which takes an argument of type A and processes it to make it 'nice' (let's call it that way to keep it simple):

```python
def func(x: A) -> A:
    x = x.process() # For some arguments, it produces the desired result.
    if x.is_nice:
        return x

    # As I wrote the 'nice'-checker, I know that any non-B object is considered 'nice'.
    # But B object can be 'nice' too (so using type-guard for that would be weird)
    # So at this point we definitely have a B object

    x: B
    
    # and there we have more processing which implies that x has type of B (uses type-specific methods and attributes)
```
As I wrote this code, I assumed that mypy would see this as [redefinition with more precise type](https://mypy.readthedocs.io/en/latest/common_issues.html#redefinitions-with-incompatible-types), as B is inherited from A.

But mypy produces this:
`Name 'x' already defined on line <line number>`
I've tried `--allow-redefinition` to avoid that, but it persists. And errors about non-existent attributes (which exist on B, but not on A) persist too

**Comment by hauntsaninja** [comment]
Try `assert isinstance(x, B)`

**Comment by evtn** [comment]
Looks like it works, thanks!
Although `x: B` would look cleaner, but whatever
