### ISSUE TITLE
Regular automatic typeshed merge testing

### ISSUE THREAD

**Issue by srittau** [python/mypy#10540]
In python/typeshed#5540 I propose to drop the mypy test suite from running in typeshed as this repeatedly caused problems in typeshed, without having much inherent value for typeshed itself. The biggest drawback is that it can cause a greater integration burden for mypy, as typeshed changes causing test suite failures will only be noticed then. One idea to alleviate this problem is to add a GitHub Action to mypy that runs at regular intervals, merging the latest typeshed version in a test branch and run the mypy test suite, reporting any issues. This could run similar to our [unused whitelist workflow](https://github.com/python/typeshed/blob/master/.github/workflows/stubtest-unused-whitelist.yml) in typeshed.

**Comment by JukkaL** [comment]
I like this idea. If there is no regular testing, typeshed syncs can become painful.
