### ISSUE TITLE
manage setuptool package_dir

### ISSUE THREAD

**Issue by dfroger** [python/mypy#10564]
We would like to use mypy on a large codebase containing several Python packages.

A package `foo.bar` is in a directory `project/common/foo/src/bar`, where `src/bar` is mapped to `foo.bar` by setuptools with: `package_dir={"foo": "src/"}`.

By default, mypy can find the packages it they are installed, but it would be great if we could use mypy directly with the sources, without install.

Is there a way to tell mypy that package `foo.bar` should be found in `project/common/foo/src/bar`? (equivalent of the `package_dir` in setuptools).

# Example

## project layout

```
project/
└── common
    └── foo
        ├── setup.py
        └── src
            ├── bar
            │   ├── hello.py
            │   ├── hi.py
            │   └── __init__.py
            └── __init__.py
```

## File contents

`setup.py` contains:

```python
# setup.py
from setuptools import setup
setup(name="foo", package_dir={"foo": "src/"}, packages=["foo", "foo.bar"])

# hello.py
def hello():
    print("hello")

# hi.py
import foo.bar
def hi():
    foo.bar.hello()

# bar/__init__.py
from .hello import hello
from .hi import hi
```

## Installation

```bash
python -m venv venv
source venv/bin/activate
cd common/foo
pip install .
python -c 'import foo.bar; foo.bar.hi()'
```

## myy errors (without installation)

```
common/foo/src/bar/hi.py:1: error: Cannot find implementation or library stub for module named 'foo.bar'
common/foo/src/bar/hi.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
common/foo/src/bar/hi.py:1: error: Cannot find implementation or library stub for module named 'foo'
```

**Comment by hauntsaninja** [comment]
I don't think there's a way to do this. Here's the documentation on how mypy determines module names: https://mypy.readthedocs.io/en/latest/running_mypy.html#mapping-file-paths-to-modules

You could write a dumb script to wrap mypy that copies your files to a temporary folder and checks them there.

**Comment by dfroger** [comment]
Would it be worth that I propose a PR for this? Something like `--package-dir=project/common/foo:foo:src`, and/or `--package-dir-auto`?

**Comment by dfroger** [comment]
Maybe the feature can be added in [SourceFinder.crawl_up](https://github.com/python/mypy/blob/98ac4874f84dc83e0b9845ef10b73c1799111a7a/mypy/find_sources.py#L131) and [FindModuleCache.find_module](https://github.com/python/mypy/blob/98ac4874f84dc83e0b9845ef10b73c1799111a7a/mypy/modulefinder.py#L197)? I didn't tried, but I can if their are feedback that it's feasible and desirable.

For now I'll copies all files in a temporary directory as suggested, but it may be more complicated for mypy integrated in an editor.
