### ISSUE TITLE
TypeVar introspection not working in mypy. 

### ISSUE THREAD

**Issue by supreetsingh10** [python/mypy#10571]
**Bug Report**

When we make an object of ```TypeVar``` and try to use the ``` Type variables``` in mypy, then we will get an error. This error will not come during runtime. 

```
   from typing import TypeVar
    from typing import List
    S = TypeVar("S")
    def showName(x: S) -> None: 
        print(x.__name__)
        print(x__constraints__)
    
    showName(S)
```

**Expected Behavior**

The expected output, in this case, should be 
``` 
S
()
```
(Write what you thought would happen.)

**Actual Behavior**

When we run it with mypy
```
fibo.py:12: error: "S" has no attribute "__name__"
fibo.py:13: error: "S" has no attribute "__constraints__" 
```

(Write what happened.)

**Your Environment**

- Mypy version used: 0.820+dev.e702679ede667b8ea48685326a2ca54b3c95fdd2.dirty 
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9
- Operating system and version: Manjaro Linux

**Comment by JelleZijlstra** [comment]
The type annotation here is wrong: it should logically be `def showName(x: TypeVar)`. But mypy is not designed to support dynamic introspection of typing constructs anyway.

**Comment by supreetsingh10** [comment]
Thank you for your answer. I was looking up the documentation of Typing, that is when I saw this example. In that documentation, it was written that it is meant for ```static introspection``` so I thought it would be implemented in mypy too. So should I close this issue?
