### ISSUE TITLE
mypy command not found

### ISSUE THREAD

**Issue by FatnLazy** [python/mypy#10592]
Hi team,

i just tried to install mypy using python3 -m pip install -U mypy and it looked like the installation were successful but when i try to run mypy --version it tells me command mypy not found.

when i tried to run the installation command again  it told me that the mypy is already installed.

Any help?

**Comment by Akuli** [comment]
Consider using a virtualenv:

```
python3 -m venv env
source env/bin/activate
pip install mypy
```

You will need to activate the venv every time you want to use mypy. To uninstall mypy (and everything you installed into the venv), delete the `env` folder. This way you can have multiple projects with different dependencies installed.

**Comment by pranavrajpal** [comment]
If you're not already using a virtualenv for something else, it might be easier to just use `python3 -m mypy` instead of `mypy` whenever you want to run mypy.

**Comment by hauntsaninja** [comment]
`hash -r` can help if this is a shell issue.
