### ISSUE TITLE
Run --install-types without user input

### ISSUE THREAD

**Issue by patrickelectric** [python/mypy#10598]
**Feature**

Allow the usage of --install-types without user input.

**Pitch**

Mypy can run in a serie of files or repositories and asking the user input every single time is annoying.
It's also problematical when using such option in CI, since it does not have user input.

**Comment by KerberosMorphy** [comment]
I would love a simple `-y` to skip the use input part.

**Comment by JukkaL** [comment]
Let's move discussion about improvements to `--install-types` to #10600. I think that it's better to discuss them together, since they are related.
