### ISSUE TITLE
async for/async with are allowed in non-async functions

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#10594]
**To Reproduce**

```
async def b():
 for i in range(5):
  yield i

def a():
 return [x async for x in b()]
```

**Expected Behavior**

Syntax error. When trying to run with python this code gives a syntax error.

**Actual Behavior**

Passed with no errors.

**Your Environment**

- Mypy version used: 0.812
- Python version used: 3.8

**Comment by msullivan** [comment]
Yeah, more generally it looks like we don't enforce that async for/async with are only used in async functions.

**Comment by SwagatSBhuyan** [comment]
I would like to take up this issue. It's just that I need a few doubts cleared. 

You're stating that the compiler throws an error stating async is not allowed outside an async function, but mypy doesn't do anything right? Does checking for async fall under static checking? (I am still new to the repository, sorry)
If so, can you point me to the scripts that have the relevant code for this? And also, some guidance will be appreciated, thanks!

@msullivan @Dreamsorcerer
