### ISSUE TITLE
Document TypeGuard (PEP 647)

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#10591]
We don't have documentation about TypeGuard ([PEP 647](https://www.python.org/dev/peps/pep-0647/)). It will be included in Python 3.10, and it would be good to have at least basic documentation after Python 3.10 is out, at the latest.

**Comment by saikatsahana77** [comment]
hello sir, Saikat here, can I start working on this issue.

**Comment by JukkaL** [comment]
@saikatsahana77 Sure, go ahead!

**Comment by saikatsahana77** [comment]
so, sir, can you instruct me exactly which section of the documentation I need to edit and what I need to mention exactly?

**Comment by saikatsahana77** [comment]
hello sir, can you kindly reply?
