### ISSUE TITLE
Migrate and translate cpython test suites

### ISSUE THREAD

**Issue by Varriount** [python/mypy#106]
The test suites that CPython uses to test a python language implementation should be migrated to mypy, with as minimal change as possible.

The addition of the test suites would allow developers and users of mypy to test whether certain syntactical constructs are supported, showing what works, and what doesn't.

**Comment by JukkaL** [comment]
This is no longer important. The existing migrated Python std lib code is still useful as regression tests, but it's probably not worth migrating additional code.
