### ISSUE TITLE
`--install-types` suggests incompatible stub packages

### ISSUE THREAD

**Issue by tpazderka** [python/mypy#10602]
**Bug Report**

Running `mypy --install-types` suggest installation of stubs that are ot compatible with the current running version of python.
**To Reproduce**

(Write your steps here:)

1. Create a project containing `import OpenSSL.crypto`
2. `mypy --install-types`

**Expected Behavior**

Does not suggest installing library stubs incompatible with python version.

**Actual Behavior**

Suggests (and installs) stubs incompatible with the current version.

**Your Environment**

- Mypy version used: 0.901
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.8, 3.9
- Operating system and version: Debian

**Comment by tpazderka** [comment]
https://github.com/python/typeshed/issues/5593

**Comment by JukkaL** [comment]
I'm working on a fix. I'll add Python version compatibility metadata for all the stub packages that mypy suggests.

**Comment by JukkaL** [comment]
The fix to this issue was released in mypy 0.902.
