### ISSUE TITLE
Generic Class generated dynamically

### ISSUE THREAD

**Issue by jules-ch** [python/mypy#10611]
**Bug Report**

Hi,
I'm currently implementing typing for the pint library xref: https://github.com/hgrecco/pint/pull/1259.
`Quantity` is the main class which is a Generic class built Dynamically to inject `UnitRegistry` as a class variable to delegate some methods.

I'm encountering a weird behaviour with this dynamically generated class regarding generic, here is a minimal example to illustrate this & reproduce. 

**To Reproduce**

```python
from typing import Any, ClassVar, Generic, Type, TypeVar, overload


T = TypeVar("T")

class Item(Generic[T]):
    _REGISTRY: ClassVar[Any]

    def __new__(cls, value: T) -> "Item[T]":
        instance = super(Item, cls).__new__(cls)
        instance._value = value
        return instance
    

def build_item(registry) -> "Type[Item]":
    class DynamicItem(Item):
        _REGISTRY=registry

    return DynamicItem


ItemType = build_item("dynamic_class_var")
item_static = Item(0.1)
item_dynamic = ItemType(3.0)

reveal_type(type(item_static))
reveal_type(item_static)
reveal_type(type(item_dynamic))
reveal_type(item_dynamic)
```

**Expected Behavior**

I would expect this behaviour:
```
note: Revealed type is "Type[pint.item.Item[builtins.float*]]"
note: Revealed type is "pint.item.Item[builtins.float*]"
note: Revealed type is "Type[pint.item.Item[builtins.float*]]"
note: Revealed type is "pint.item.Item[builtins.float*]"
```

**Actual Behavior**

```
note: Revealed type is "Type[pint.item.Item[builtins.float*]]"
note: Revealed type is "pint.item.Item[builtins.float*]"
note: Revealed type is "Type[pint.item.Item[Any]]"
note: Revealed type is "pint.item.Item[Any]"
```

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): Defaults
- Python version used: 3.7
- Operating system and version: Win 10.0.19041 Build 19041

I also tried on master with same behaviour

I managed to have a workaround with `@overload` and another TypeVar but it seems like it's not the proper way to do this.

```python
from typing import Any, ClassVar, Generic, Type, TypeVar, overload


T = TypeVar("T")
T_ = TypeVar("T_")

class Item(Generic[T]):
    _REGISTRY: ClassVar[Any]

    @overload
    def __new__(cls, value: str) -> Any:
        ...
    @overload
    def __new__(cls, value: T_) -> "Item[T_]":
        ...
    def __new__(cls, value):
        instance = super(Item, cls).__new__(cls)
        instance._value = value
        return instance
    

def build_item(registry) -> "Type[Item]":
    class DynamicItem(Item):
        _REGISTRY=registry

    return DynamicItem


ItemType = build_item("dynamic_class_var")
item_static = Item(0.1)
item_dynamic = ItemType(3.0)

reveal_type(type(item_static))
reveal_type(item_static)
reveal_type(type(item_dynamic))
reveal_type(item_dynamic)

```

**Comment by ethframe** [comment]
I believe that observed behaviour is correct. The [documentation](https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-type-arguments-exist-type-arg) states that omitted arguments of generic type are implicitly set to `Any`, so `build_item` is equivalent to:

```python
def build_item(registry) -> "Type[Item[Any]]":
    class DynamicItem(Item[Any]):
        _REGISTRY=registry

    return DynamicItem
```

That's why revealed type for `item_dynamic` is `Item[Any]`.

**Comment by jules-ch** [comment]
Even if I put this method in a classmethod to keep genericity, type inference does not work.
I have no way around it though, even with `cast` method.

**Comment by ethframe** [comment]
After re-reading PEP 484, it seems that this is a limitation of the type system. Types can't contain unbound type variables, and type variables used in function signature are inferred to some specific types at the call site, so there is no way to return generic type from a function and assign it to a variable.

**Comment by hauntsaninja** [comment]
ethframe is correct.

**Comment by ethframe** [comment]
@jules-ch, I recently found a way to properly annotate the `build_item` function. You can define a protocol with a __generic__ `__call__` method and use it as the return type:

```python
class DynamicItemCtor(Protocol):
    def __call__(self, value: T) -> Item[T]:
        ...


def build_item(registry) -> DynamicItemCtor:
    ...
```

After that, the actual behavior matches the expected:

```
note: Revealed type is "Type[foo.Item[builtins.float*]]"
note: Revealed type is "foo.Item[builtins.float*]"
note: Revealed type is "Type[foo.Item[builtins.float*]]"
note: Revealed type is "foo.Item[builtins.float*]"
```

**Comment by jules-ch** [comment]
@ethframe I'll give it a shot with your example
