### ISSUE TITLE
Class definition shadowed by nonexistent type in builtins.pyi under Python 3.6

### ISSUE THREAD

**Issue by jwodder** [python/mypy#10617]
**Bug Report**

I have a library that defines a dataclass named "`ArgSet`".  It type-checked fine until mypy 0.900 was released, at which point the scheduled CI jobs started failing with a bunch of errors of the form:

```
test/test_cls.py:30: error: Unexpected keyword argument "takes_args" for
"ArgSet"  [call-arg]
        a = ArgSet(
            ^
.tox/typing/lib/python3.6/site-packages/mypy/typeshed/stdlib/builtins.pyi:95: note: "ArgSet" defined here
```

First of all, it's my understanding that my library's definition of `ArgSet` should be used over any `ArgSet`s defined in typeshed in scopes where only the former is imported, like my test code.  Secondly, and more mysteriously, opening the given `builtins.pyi` file and looking at line 95 shows this:

```python
class object:
    __doc__: Optional[str]
    __dict__: Dict[str, Any]
    __slots__: Union[str, Iterable[str]]
    __module__: str
    __annotations__: Dict[str, Any]
    @property
    def __class__(self: _T) -> Type[_T]: ...
    # Ignore errors about type mismatch between property getter and setter
    @__class__.setter
    def __class__(self, __type: Type[object]) -> None: ...  # type: ignore # noqa: F811
    def __init__(self) -> None: ...  # <-- LINE 95
    def __new__(cls) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __eq__(self, o: object) -> bool: ...
    def __ne__(self, o: object) -> bool: ...
    def __str__(self) -> str: ...
```

There is no `ArgSet` to be found in the file, nor does there seem to be one in the whole of typeshed!

Note that this only happens when running mypy under Python 3.6; Python 3.7 and up run without error.  Packagewise, the only difference between the two environments is that the 3.6 one has the `dataclasses` backport installed.

**To Reproduce**

* Clone https://github.com/jwodder/argset
* Run `tox -e typing`

**Your Environment**

- Mypy version used: 0.901
- Mypy configuration options from `mypy.ini` (and other config files):

```ini
[mypy]
ignore_missing_imports = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
local_partial_types = True
no_implicit_reexport = True
strict_equality = True
show_error_codes = True
show_traceback = True
pretty = True
exclude = test/data/
```

- Python version used: 3.6.13
- Operating system and version: Debian Buster and Ubuntu 20.04.2

**Comment by jwodder** [comment]
So I was able to fix the problem by installing `types-dataclasses` (I missed the message about that at first because there was so much output).  I still feel that the fact that this behavior happens at all is a bug.

For the record, here's an MVCE.  Running mypy 0.901 with the default options under Python 3.6 with `dataclasses` installed but not `types-dataclasses` produces an error (though I can't figure out the minimal options to get the output to include a reference to `builtins.pyi`).

```python
from dataclasses import dataclass

@dataclass
class ArgSet:
    field: int

print(ArgSet(field=42))
```

**Comment by JelleZijlstra** [comment]
Yes, the reference to `builtins.pyi` is pretty misleading, and if there's a way to make the `types-dataclasses` error more prominent, that would also be helpful. Jukka already put something in to hide excessive errors if there have been types- related errors.

**Comment by erictraut** [comment]
It appears this bug has been fixed. I can no longer repro it with the latest version of mypy (1.5).
