### ISSUE TITLE
mypy should use typing on newer Python versions and only require typing_extensions for older Python versions

### ISSUE THREAD

**Issue by gitpushdashf** [python/mypy#10649]
For example, here: https://github.com/python/mypy/blob/master/mypy/semanal.py#L56

We could import `Final` from typing for Python 3.8+: https://docs.python.org/3/library/typing.html#typing.Final

If typing was able to provide all of the types for some Python versions, we could mark that dependency for only older Python versions.

Granted, may not be worth the hassle at all. Just figured I'd throw this out there.

**Comment by hauntsaninja** [comment]
Thanks, but I think this isn't worth the hassle. typing_extensions is a lightweight and high trust dependency. And feels like it should be low friction to use new typing_extensions additions in mypy.

**Comment by gitpushdashf** [comment]
Completely fair. Thank you!
