### ISSUE TITLE
Optional parameter being treated as potentially None even after being confirmed to be not None

### ISSUE THREAD

**Issue by crbunney** [python/mypy#10654]
**Bug Report**
Running mypy on this code:
```python
from typing import Optional


class MyObj:
    def do_something(self) -> str:
        return "foo"


def test_fun(my_obj: Optional[MyObj] = None, bar: Optional[str] = None) -> Optional[str]:
    do_the_thing = my_obj and bar

    var = my_obj.do_something() if do_the_thing else None
    return var

```
This error was given:
```
bug.py: note: In function "test_fun":
bug.py:12: error: Item
"None" of "Optional[MyObj]" has no attribute "do_something"
        var = my_obj.do_something() if do_the_thing else None

```

Given that `do_the_thing` is only true if `my_obj` is not `None`, then I wouldn't expect that error to occurr.

**Your Environment**
- Mypy version used: `mypy 0.812`
- Mypy command-line flags: `n/a`
- Python version used: `Python 3.8.5`
- Operating system and version: `Windows 10 Enterprise (Version 20H2; OS Build: 19042.985)`
- Mypy configuration options from `mypy.ini` (and other config files):
```ini
[mypy]
strict = True
pretty = True
show_error_context = True
ignore_missing_imports = True
exclude = .*tests?/|dist/|build/|.*_cdk/|\.?env/|\.?venv/|cdk.out/|setup.py|versioneer.py

[mypy-*._version]
ignore_errors = True
```

**Comment by JelleZijlstra** [comment]
Mypy doesn't do this sort of reasoning across multiple assignments. `if myobj else None` should work correctly.
