### ISSUE TITLE
mypy 0.902 complains about attributes when module and source share a name.

### ISSUE THREAD

**Issue by seanctech** [python/mypy#10662]
**Bug Report**

Running into issue creating a template for internal projects. The module created here is a base module used for handling things such as argparse. Currently the module attributes with dunder format seem to have issues in mypy and I'm not sure the best way to manage this without a type ignore on the failing import or changing the name of the entry point for the project.

**To Reproduce**

Project layout:
```bash
├─- project/
│     ├── project.py
│     ├── project/
│     │     ├── __init__.py
│     │     ├── config.py
```
In project.py:
```python
from project import config
```

In project/\_\_init\_\_:
```python
__project_name__ = "project"
__version__ = "v0.0.0"
```
In project/config.py:
```python
from project import __version__, __project_name__
```

mypy returns following error:
```bash
host:project (main) $ pipenv run mypy --ignore-missing-imports project.py
project/config.py:9: error: Module 'project' has no attribute '__project_name__'
project/config.py:9: error: Module 'project' has no attribute '__version__'
Found 2 errors in 1 file (checked 1 source file)
```

**Expected Behavior**

mypy should handle this correctly as I do not see any issues with this layout within PEP8

**Your Environment**

- Mypy version used:  0.902
- Mypy command-line flags: --ignore-missing-imports
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9.5
- Operating system and version: macOS 11.4

**Comment by ethanhs** [comment]
I don't think we can or should support this. Having conflicting module names is not only a bad idea, but it would make analysis much more difficult and break a lot of our existing logic.

I'm honestly am surprised this works with Python.
