### ISSUE TITLE
Type-check only imports

### ISSUE THREAD

**Issue by hosford42** [python/mypy#10674]
**Feature**

Imports that apply only during type-checking and not at runtime, e.g. by placing them inside a string literal (similar to forward references in type annotations) or a structured comment.

```python3
import module.used.at.runtime as rt
'import module.used.during.type.checking as tc'  # No-op at run-time but recognized by mypy

def foo(x: rt.TypeA, y: 'tc.TypeB') -> 'tc.TypeC':
    # Do something at runtime that references rt.TypeA explicitly, 
    # but only implicitly utilizes tc.TypeB and tc.TypeC
    ...
```

**Pitch**

It's very easy to run into situations where imports have to be added only to support type inference, particularly where two types refer to each other only in their type annotations. Often these lead to import cycle errors which can be a pain to resolve. Rather than use forward references and importing the relevant modules at the end of the file (which is clumsy, hard to read, and doesn't always resolve the issue) it would be nice if the imports could be "virtual" in the sense that they are only applied during type checking and not at runtime.

**Comment by hauntsaninja** [comment]
Use:
```
if typing.TYPE_CHECKING:
    import whatever_you_wnat
```
https://mypy.readthedocs.io/en/stable/runtime_troubles.html#import-cycles

**Comment by hosford42** [comment]
Awesome! I wasn't aware of this feature. Thanks!
