### ISSUE TITLE
Errors from decorated property setters

### ISSUE THREAD

**Issue by symbiont-val-melamed** [python/mypy#10692]
**Bug Report**

There seems to be a problem with decorated property setters. (I'm sorry if this is a known issue but I didn't see any solutions or mentions so far.)

**To Reproduce**

```python
from functools import wraps
from typing import Any, Callable, Sized

Setter = Callable[[Any, str], None]

def not_empty(func: Setter) -> Setter:
    @wraps(func)
    def _wrapper(*args, **kwargs):
        if type(args[1]) is Sized and len(args[1]) == 0:
            raise ValueError('The value cannot be empty')
        return func(*args, **kwargs)

    return _wrapper

class WithSetter:
    def __init__(self):
        self._prop: str = ''

    @property
    def prop(self) -> str:
        return self._prop

    @prop.setter
    @not_empty
    def prop(self, value: str):
        self._prop = value

a = WithSetter()
a.prop = 'foo'
print(a.prop)
```

**Expected Behavior**

There shouldn't be any errors from mypy or while running the script.

**Actual Behavior**

```bash
> mypy ClassWithSetter.py         
ClassWithSetter.py:25: error: Decorated property not supported
ClassWithSetter.py:32: error: Property "prop" defined in "WithSetter" is read-only
> python .\ClassWithSetter.py
foo
```

I understand that I can ignore these errors with `# type: ignore`.

**Your Environment**

- Mypy version used: **0.902**
- Mypy command-line flags: **none**
- Mypy configuration options from `mypy.ini` (and other config files): **none**
- Python version used: **3.9.5**
- Operating system and version:
  - Windows 10 (10.0.21390 Build 21390), as well as
  - Windows 10 WSL2:
    - > PRETTY_NAME="Pengwin"
NAME="Pengwin"
VERSION_ID="11"
VERSION="11 (bullseye)"
ID=debian
ID_LIKE=debian
HOME_URL="https://github.com/whitewaterfoundry/Pengwin"
SUPPORT_URL="https://github.com/WhitewaterFoundry/Pengwin/issues"
BUG_REPORT_URL="https://github.com/WhitewaterFoundry/Pengwin/issues"
VERSION_CODENAME=bullseye
PENGWIN_VERSION="21.5.4"

**Comment by AlexWaygood** [comment]
Neither decorated getters nor decorated setters are yet fully supported; see #1362
