### ISSUE TITLE
Enforce error codes on type: ignores

### ISSUE THREAD

**Issue by TylerYep** [python/mypy#10718]
**Feature**

As far as I know, there's no way to enforce an error code is added to the end of a type ignore. Since error codes can narrow the type errors ignored on a specific line, it would be useful to ensure all # type: ignores in a codebase included an error code, to avoid silencing additional errors or disabling otherwise valid typechecking on a line.

The feature could be a config option `--enforce-error-codes` that verifies all type: ignores specify an error code.
```
x: int = None  # type: ignore                <- mypy complains
x: int = None  # type: ignore[assignment]    <- good!
```

**Comment by AlexWaygood** [comment]
Implemented in #10712

**Comment by TylerYep** [comment]
I don't think you linked a PR that adds this command line argument. Could you double check? Reopening.

**Comment by JelleZijlstra** [comment]
It's #11633

**Comment by AlexWaygood** [comment]
Whoops, my bad. Thanks @JelleZijlstra!

**Comment by TylerYep** [comment]
Ah, thanks!

Nit: wish this option was called `warn-ignore-without-code` since `ignore_without_code = True` in mypy configs is confusing to read
