### ISSUE TITLE
Poetry errors: Source file found twice under different module names

### ISSUE THREAD

**Issue by jirka-tribi** [python/mypy#10726]
**Bug Report**

Mypy error: `error: Source file found twice under different module names: "test3.database" and "test1.test2.test3.database"` when  poetry is used as package tool

**To Reproduce**

Create simple app https://github.com/jirka-tribi/test-app/tree/master/poetry
Create venv `C:\Python38\Scripts\virtualenv.exe", "venv"`
Install poetry and install package
Run test `poetry run pytest`

**Expected Behavior**
When package is created with setuptools (setup.cfg, setup.py) all mypy checks passed
simple app example https://github.com/jirka-tribi/test-app/tree/master/setuptools

Not reproduced with mypy ver 0.790 and lower

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: `addopts = "-p no:cacheprovider --verbose --pylint --pylint-rcfile=pyproject.toml --mypy"`
- Mypy configuration options from `pyproject.toml`:
```ini
[tool.mypy]
ignore_missing_imports = true
```
- Python version used: 3.8.9
- Operating system and version: Windows 10

**Comment by hauntsaninja** [comment]
Invoke mypy like this: `MYPYPATH=src mypy --explicit-package-bases .`
See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more details.
