### ISSUE TITLE
mypy not recognizing child class inside callable

### ISSUE THREAD

**Issue by somughosh** [python/mypy#10738]
**Bug Report**

**To Reproduce**

class BaseClass:
    p: int

class DerivedClass:
    q: int

def p(q: Callable[[BaseClass], str]) -> None:
    return None

def r(derived: DerivedClass) -> str:
    return ""

p(r)

**Expected Behavior**

No error from mypy

**Actual Behavior**

Argument 1 to "p" has incompatible type "Callable[[DerivedClass], str]"; expected "Callable[[BaseClass], str]"

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: 
- Mypy configuration options from `mypy.ini` (and other config files):
[mypy]
disallow_untyped_defs = True
exclude = tests

- Python version used: 3.9.5
- Operating system and version: RHEL 7.4

**Comment by hauntsaninja** [comment]
This is correct, callables are contravariant https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generic-types

**Comment by somughosh** [comment]
Hmm. Then I shouldnt be getting the error right? What can I do to make mypy accept this as correct?

**Comment by erictraut** [comment]
This is a type violation, and mypy is correct to flag it as an error. Function `p` is expecting you to pass a function that accepts an input parameter of `BaseClass`, but you're passing it a function that does not accepts only a specific subclass (`DerivedClass`). Function `p` may call back `r` and pass it any instance of `BaseClass`, not necessarily an instance of `DerivedClass`, so if `r` is written to assume `DerivedClass` only, it will crash.
