### ISSUE TITLE
Incompatible type "Dict[int, str]"; expected "Dict[Union[int, str], str]"

### ISSUE THREAD

**Issue by joakimnordling** [python/mypy#10730]
**Bug Report**

A `Union` definition for the key of a dictionary doesn't match a single type from the union.

**To Reproduce**

1. Create the file `example.py` with the following content:
```python
from typing import Dict, Union


def foo(_: Dict[Union[int, str], str]) -> None:
    pass


def bar() -> Dict[int, str]:
    return {1: "abc"}


foo(bar())
```
2. Run `mypy example.py`, output:
```
example.py:12: error: Argument 1 to "foo" has incompatible type "Dict[int, str]"; expected "Dict[Union[int, str], str]"
Found 1 error in 1 file (checked 1 source file)
```

**Expected Behavior**

I would expect a dictionary keyed with an integer (or a string) to match the defintion of a dictionary with a key being a union of an integer and a string.

**Actual Behavior**

It fails with this error:
```
example.py:12: error: Argument 1 to "foo" has incompatible type "Dict[int, str]"; expected "Dict[Union[int, str], str]"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: Python 3.8.5
- Operating system and version: macOS Mojave

**Comment by erictraut** [comment]
Because a Dict is a mutable container, the type arguments are invariant. See [this documentation](https://mypy.readthedocs.io/en/stable/type_inference_and_annotations.html#compatibility-of-container-types) for details.

Here's an extension of your sample that demonstrates where this will cause problems:
```python
def foo(a: Dict[Union[int, str], str]) -> None:
    a["hi"] = "abc"

def bar() -> Dict[int, str]:
    return {1: "abc"}

d = bar()
foo(d) # Mypy: Argument 1 to "foo" has incompatible type "Dict[int, str]"; expected "Dict[Union[int, str], str]"
for x in d:
    print(1 + x) # Crash because d contains str key
```

**Comment by JelleZijlstra** [comment]
@erictraut is right.

**Comment by joakimnordling** [comment]
Thanks for the explanation @erictraut and sorry for the spam.
