### ISSUE TITLE
TypedDict.values() always returns object.

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#10759]
```
from typing import TypedDict

class A(TypedDict):
    a: str

def foo(a: A):
    for v in reveal_type(a.values()):
        v.lower()
```

This produces:
```
test.py:7: note: Revealed type is 'typing.ValuesView[builtins.object]'
test.py:8: error: "object" has no attribute "lower"
Found 1 error in 1 file (checked 1 source file)
```

**Expected Behavior**

`TypedDict.values()` to return a different type if all values of a `TypedDict` are of the same type.

**Your Environment**

- Mypy version used: 0.910

**Comment by JukkaL** [comment]
TypedDict types support structural subtyping, so it's always possible that there is a subtype of `A` that has a value with a non-str type:

```py
class B(TypedDict):
    a: str
    b: int

b: B = {'b': 1, 'a': 'y'}
foo(b)
```

One way to make this work as proposed could be to support final TypedDict types that don't allow additional keys in subtypes.

**Comment by JelleZijlstra** [comment]
Pyright supports @final TypedDicts; it would be a useful addition for mypy too. Not sure if there's already an issue about it.
