### ISSUE TITLE
["foo"] is not compatible with List[Union[Dict[str, Any], Any]]

### ISSUE THREAD

**Issue by l0b0** [python/mypy#10767]
**Bug Report**

It looks like [putting `Any` in a `Union`](https://github.com/slackapi/python-slack-sdk/blob/c2cfa4f5b76d7f9c55d053ba6d29e1f9b79dc853/slack_sdk/webhook/client.py#L58) triggers an issue where no content is compatible with the `Any` anymore. (The third party code has since been [changed](https://github.com/slackapi/python-slack-sdk/commit/b8a94bd3af7f03cebe8c25dabfe0c2d57c0277b6#diff-d8aa89c62ac5265031aa722a9dfad2fd7fcb7aea3548d64883ca6fc22fa8f244) to use `Sequence` rather than `List`, presumably because of this or a related issue; maybe this is a known antipattern?)

**To Reproduce**

Run `mypy --strict` on the following code:

```python
from typing import Any, Dict, List, Union

my_list = ["foo"]


def foo(bar: List[Union[Dict[str, Any], Any]]) -> None:
    pass


foo(my_list)
```

**Expected Behavior**

This should not cause any issues, because the revealed type (`builtins.list[builtins.str*]`) should be considered a to match `List[Union[Dict[str, Any], Any]]`. Basically, a `Union` which contains any `Any` entries should just reduce to `Any`.

**Actual Behavior**

```text
example.py:9: error: Argument 1 to "foo" has incompatible type "List[str]"; expected "List[Union[Dict[str, Any], Any]]"  [arg-type]
example.py:9: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
example.py:9: note: Consider using "Sequence" instead, which is covariant
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files):

   ```
   [mypy]
   show_error_codes = true
   strict = true
   ```
- Python version used: 3.8.10
- Operating system and version: Arch Linux

**Other information**

Annotating the list with the exact type (`my_list: List[Union[Dict[str, Any], Any]] = ["foo"]`) makes mypy succeed. Annotating it with the more reasonable `List[str]` makes mypy fail.

**Comment by hauntsaninja** [comment]
mypy is correct here. List is invariant: https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generic-types
E.g., if `foo` added a `Dict[str, Any]` to `bar`, where `bar` was a `List[str]`, this would be incorrect.
