### ISSUE TITLE
Syntax error with Python 3.9

### ISSUE THREAD

**Issue by MasterSergius** [python/mypy#10769]
**Intro**
I know, a lot of issues were created regarding my problem, for example https://github.com/python/mypy/issues/8872, and all of them are closed, but my problem still exists.

**Bug Report**
A lot of errors for type comments, like `Tuple[str, str]` -  error: syntax error in type comment
Code was tested with python 3.6-3.8, but syntax errors appears only for Python 3.9, the last check was done with CPython-3.9.5 and mypy-0.910, full log can be found here https://github.com/MasterSergius/acachecontrol/pull/17/checks?check_run_id=2905621045

**To Reproduce**

1. Write some code like:
```py
def any_method(self, key: Tuple[str, str]) -> bool:
   pass
```
2. Run mypy check within Python 3.9+, syntax error in result

**Your Environment**
CPython-3.9.5, mypy-0.910 (GH actions)
The same true for CPython-3.9.2, mypy-0.910, Ubuntu-20.04 (local system)

**Comment by hauntsaninja** [comment]
That's because all those issues were fixed, a long time ago. You're not using the mypy version you claim, you're using v0.720.

**Comment by MasterSergius** [comment]
@hauntsaninja I bet, you haven't even opened that check log, provided via link above. I've also tested locally via pyenv. I can provide screenshots.

**Comment by ethanhs** [comment]
@MasterSergius I'm actually quite sure that @hauntsaninja did click through to the log because that's they only way to know that your pre-commit config [lists mypy 0.720](https://github.com/MasterSergius/acachecontrol/blob/master/.pre-commit-config.yaml#L13) as mentioned, and that you haven't changed that. Please be more respectful to people who are volunteering their time to work on a tool you use.

**Comment by MasterSergius** [comment]
@ethanhs hmm, you're right... Sorry, @hauntsaninja , I haven't spotted that, that's definitely my fault. The only question that I need to find the answer to - why I've got an error on my local machine, probably, some issues with pyenv. After full removal and recreating just for Python3.9.2 it started to work on my local machine too. Thank you again, I'll behave better, I promise )
