### ISSUE TITLE
Mypy reports previously not-None checked dict item as optional

### ISSUE THREAD

**Issue by malfet** [python/mypy#10784]
**Bug Report**

Mypy fails to infer that dict item referenced by key can not be optional in a loop over dict items
**To Reproduce**
Consider following example:
```
from typing import Iterable, Dict, Optional
class Foo:
    bar: str

    def __init__(self, bar: str) -> None:
        self.bar = bar


def foo(foo: Dict[str, Optional[Foo]]) -> Iterable[str]:
    for i, f in foo.items():
        if f is not None:
            yield foo[i].bar
```

**Expected Behavior**

This code should be mypy clean, as `foo[i] == f`, which is checked on previous line as not None. 
**Actual Behavior**

Mypy fails with `error: Item "None" of "Optional[Foo]" has no attribute "bar"`
**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.7.5
- Operating system and version: MacOS

**Comment by malfet** [comment]
Same trick does not work with `List` and `enumerate`:
```
from typing import Iterable, List, Optional
class Foo:
    bar: str

    def __init__(self, bar: str) -> None:
        self.bar = bar


def bar(foo: List[Optional[Foo]]) -> Iterable[str]:
    for i, f in enumerate(foo):
        if f is not None:
            yield foo[i].bar

if __name__ == "__main__":
    print(list(bar([Foo("aaaa"), None])))
```

**Comment by hauntsaninja** [comment]
mypy doesn't do this kind of analysis, nor is it necessarily safe to assume that `foo[i]` is the same object (it's easy to make dict subclasses that return different objects each time you index). In your examples, I'd also argue that it's better style to use the variable you've already narrowed.
