### ISSUE TITLE
Is there any way to implicity unwrap an optional?

### ISSUE THREAD

**Issue by samgermain** [python/mypy#10785]
Here's a situation that I have, with a case that `mypy` see's as an error, but it isn't

```
def helper(self, float1: Optional[float], float2 Optional[float]):

        if float2 is not None:
              if float1 is not None:
                    self.float1 = max(float1, float2)
            else:
                self.float1 = float2
            self.float2 = float2
        else:
            # Will always be true, here for mypy, if it's not true, someone used this function incorrectly and I would like there to be an error
            if float1:  
                self.float1 = float1

    def set_float1(self, float1: float):
        self.helper(float1=float1, float2=self.float2)

    def set_float2(self, float2: float):
        self.helper(float1=self.float1, float2=float2)
```

Is there any way in `mypy` to [implicitly unwrap](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#ID334) (force unwrap) the value stored in the optional?

**Comment by hauntsaninja** [comment]
`assert float1 is not None` is the quickest thing to do

**Comment by samgermain** [comment]
Assert statements can be disabled on a interpreter level with global variables. [how to](https://realpython.com/python-assert-statement/#disabling-assertions-in-production-for-performance).

**Comment by AlexWaygood** [comment]
> It would be cool to see implicitly unwrapped optionals as a feature, I like them in Swift

I'd open an issue over at https://github.com/python/typing if you want to propose a new feature for the Python typing framework :)
