### ISSUE TITLE
Problem with recursive generic protocol in object attribute

### ISSUE THREAD

**Issue by StefanUlbrich** [python/mypy#10790]
**Bug Report**

Hi, I ran into an issue with generic protocols. As far as I understand, they are supposed to be used recursively too. 
However, I get mypy errors (0.770 and 0.910) when using it for object attributes, see from the following snippet

**To Reproduce**

```python
class A:
    def __init__(self) -> None:
        pass
class B:
    def __init__(self, a: Optional[A]=None, b: Optional['B']=None) -> None:
        self.a=a
        self.b=b


N = TypeVar('N')
class PB(Protocol[N]):
    a: Optional[N]
    b: Optional['PB[N]']

def spam(b: PB[N], a: N):
    pass

spam(B(), A())
```

**Expected Behavior and actual Behavior**

I think from the call to spam it should be inferred that `PB[A]` is desired (which B should fulfill) but I get this error:

```
Argument 1 to "spam" has incompatible type "B"; expected "PB[A]"mypy(error)
Following member(s) of "B" have conflicts:mypy(note)
    b: expected "Optional[PB[A]]", got "Optional[B]"mypy(note)
(class) B(a: A | None, b: B | None)
```

The same error happens with the direct assignment `b: PB[A] = B()`.
Is this a bug (that I should but on the tracker) or did I make a mistake (I'm still a bit new to the type checking in Python)?

**Your Environment**

- Mypy version used: 0.770 and 0.910
- Mypy command-line flags: Used as linter in VSCode
- Mypy configuration options from `mypy.ini` (and other config files): Called from VSCode – no dedicated settings file
- Python version used: 3.7.9
- Operating system and version: Ubuntu 20.04, x64

**Comment by ilevkivskyi** [comment]
This is expected, because mutable attributes are invariant. If you want this to work make `b` a property _in protocol definition_. See https://mypy.readthedocs.io/en/stable/common_issues.html#covariant-subtyping-of-mutable-protocol-members-is-rejected
