### ISSUE TITLE
mypy complaints about type annotation for Union of callables

### ISSUE THREAD

**Issue by chronicom** [python/mypy#10796]
Basically I have a couple of functions which are passed to another function as argument. I annotated the argument as union of callables. However mypy seems to be not happy with the annotation.  I am not sure if it is bug or I have missed something.

Below is sample code and mypy outputs. 

```
def fun1() -> str:
    return "nothing"

def fun2(s: str) -> str:
    return s

@overload
def call_fun(func: Callable[[], str]) -> str: ...
@overload
def call_fun(func: Callable[[str], str]) -> str: ...

def call_fun(func: Union[Callable[[], str], Callable[[str], str]]) -> str:
    new_func: Callable[[], str]

    if len(inspect.signature(func).parameters) == 1:
        new_func = partial(func, "something")
    else:
        new_func = func

    return new_func()

print(call_fun(fun1))
print(call_fun(fun2))
```

mypy outputs
```
error: Incompatible types in assignment (expression has type "Union[Callable[[], str], Callable[[str], str]]", variable has type "Callable[[], str]")
Found 1 error in 1 file (checked 1 source file)
```

Python 3.8.10
mypy              0.910    
mypy-extensions   0.4.3

**Comment by JelleZijlstra** [comment]
Mypy doesn't know to narrow the type based on the `inspect.signature` call, and it's unlikely that it ever will. Your best bet is to use `typing.cast`.

Also this code is technically unsafe:
```python
def fun3(s: str, t: bool = False) -> str:
     return s

call_fun(fun3)  # accepted by mypy, fails at runtime
```

**Comment by chronicom** [comment]
> Mypy doesn't know to narrow the type based on the `inspect.signature` call, and it's unlikely that it ever will. Your best bet is to use `typing.cast`.
> 
> Also this code is technically unsafe:
> 
> ```python
> def fun3(s: str, t: bool = False) -> str:
>      return s
> 
> call_fun(fun3)  # accepted by mypy, fails at runtime
> ```

Hi Jelle, thank you for the fast reply.  Reason that I use inspect.signature is that I could not find better solution to overload 'call_fun'.  The python singledispatch also does not seem to work when the argument is a callable.  Could you please advice how can I achieve this by typing.cast ?

**Comment by JelleZijlstra** [comment]
You'd change `new_func = func` to `new_func = cast(Callable[[], str], func)`.

**Comment by erictraut** [comment]
Here's another approach that uses the new PEP 647 (TypeGuard):

```python
from typing import Callable, Union, overload
from typing_extensions import TypeGuard
import inspect
from functools import partial

def fun1() -> str:
    return "nothing"

def fun2(s: str) -> str:
    return s

def is_zero_param_callable(
    func: Union[Callable[[], str], Callable[[str], str]]
) -> TypeGuard[Callable[[], str]]:
    return len(inspect.signature(func).parameters) == 0

@overload
def call_fun(func: Callable[[], str]) -> str:
    ...

@overload
def call_fun(func: Callable[[str], str]) -> str:
    ...

def call_fun(func: Union[Callable[[], str], Callable[[str], str]]) -> str:
    new_func: Callable[[], str]

    if is_zero_param_callable(func):
        new_func = func
    else:
        new_func = partial(func, "something")

    return new_func()

print(call_fun(fun1))
print(call_fun(fun2))
```

**Comment by chronicom** [comment]
> You'd change `new_func = func` to `new_func = cast(Callable[[], str], func)`.

This method works out. Thanks a lot 👍

**Comment by chronicom** [comment]
> Here's another approach that uses the new PEP 647 (TypeGuard):
> 
> ```python
> from typing import Callable, Union, overload
> from typing_extensions import TypeGuard
> import inspect
> from functools import partial
> ```
Hi Eric, the TypeGuard works as intended as well.  I need to spend sometime to understand how TypeGuard works though. Thank you very much 👍
