### ISSUE TITLE
__slots__ isn't effective for limiting attributes

### ISSUE THREAD

**Issue by StevenLu2004** [python/mypy#10801]
**Bug Report**

Thank you for Mypy! It's been great help :) Recently, I want to use `__slots__` in a class definition to limit the attributes. This way I don't accidentally define attributes with similar but different names (like "bar" in one class but "baz" in another) when I copy my code to a new class. But Mypy seems to ignore it completely, even if CPython throws an `AttributeError` when executing the code.

Originally I just want to prevent definition of attributes outside `__init__`, but Mypy doesn't seem to provide an option to check this, so I thought about `__slots__` as a workaround, but unfortunately this failed too. Please point out any probable workarounds for the above issues.

**To Reproduce**

Put the following in "main.py" and first execute with python then check with mypy.

```python
class TestClass:
    __slots__ = ('bar',)
    def __init__(self) -> None:
        self.bar: int = 0
    def modify(self) -> None:
        self.baz = 42
    def __str__(self) -> str:
        return f"TestClass(bar={self.bar})"

t = TestClass()
t.modify()
print(t)
```

```
$ python main.py
$ mypy main.py
```

**Expected Behavior**

Actual Python output:

```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    t.modify()
  File "main.py", line 6, in modify
    self.baz = 42
AttributeError: 'TestClass' object has no attribute 'baz'
```

Expected Mypy output, to be consistent with the Python output above:

```
main.py:6: error: "TestClass" has no attribute "baz"
Found 1 error in 1 file (checked 1 source file)
```

**Actual Behavior**

Actual Mypy output:

```
Success: no issues found in 1 source file
```

**Your Environment** (flags, configs, and OS are probably irrelevant)

- Mypy version used: 0.910 (pypi)
- Mypy command-line flags: (None)
- Mypy configuration options from `mypy.ini` (and other config files): (None)
- Python version used: 3.7.6 (conda-forge)
- Operating system and version: macOS Catalina Version 10.15.7

**Comment by erictraut** [comment]
I don't think mypy has any support for `__slots__`. I recently added [this support to pyright](https://github.com/microsoft/pyright/issues/2022#issuecomment-868199513). It should be straightforward for someone familiar with the mypy source base to add similar support to mypy.

**Comment by sobolevn** [comment]
I've made a really small prototype that kinda works:

```python
class A:
    __slots__ = ('a',)


class B(A):
    __slots__ = ('b',)

    def __init__(self) -> None:
        self.a = 1
        self.b = 2
        self.c = 3

b: B
reveal_type(b.c)
```

<img width="752" alt="Снимок экрана 2021-07-24 в 18 41 14" src="https://user-images.githubusercontent.com/4660275/126873684-da2ce2dd-962d-4b2d-8c72-5b404bae8f65.png">

Going to make a PR soon, stay tuned.
