### ISSUE TITLE
Comparisons with `Any` return `Any`

### ISSUE THREAD

**Issue by ktbarrett** [python/mypy#10809]
[Asked for assistance on the gitter](https://gitter.im/python/typing?at=60eba6a7f1274d5e5042fc48) first, but got no reply.

**Bug Report**

```python
class A(typing.Protocol):
    def __lt__(self, other: typing.Any) -> bool:
        ...
    def __le__(self, other: typing.Any) -> bool:
        return self < other or self == other  # error: Returning Any from function declared to return "bool"
    def __gt__(self, other: typing.Any) -> bool:
        return not self < other and self != other  # no error
    def __ge__(self, other: typing.Any) -> bool:
        return not self < other  # no error

a: A
b: typing.Any
reveal_type(a < b)  # note: Revealed type is "Any"
```

[mypy playground](https://mypy-play.net/?mypy=latest&python=3.9&flags=strict&gist=70da3795f4ec7104f0488b50991bcbd5) of the problem.

Comparisons returns `Any` if either operand is an `Any`. I am defining `def __lt__(A, Any) -> bool` but it doesn't seem to be respecting that. However, interestingly `Any < A` returns `bool`, which doesn't seem to be consistent? And mypy complains about only one of the above comparison implementations even though they all ostensibly return `Any` and are declared to return `bool`.

**Expected Behavior**

I would expect that the result of `a < b` would be `bool` because I defined `def __lt__(A, Any) -> bool`. I would expect that *any* comparison with *any* types would return a `bool` and implying the contrary would result in an error.

**Your Environment**

* mypy 0.910
* Python 3.9
* Using `--strict` option

**Comment by erictraut** [comment]
Do you really mean `Any`, or do you mean `object`? If you change it to `object`, mypy handles it as you would expect.

**Comment by ktbarrett** [comment]
And so it does. I understand there is a difference between `typing.Any` and `object`, I've run into that distinction a few times, one being type erased and the other being "any" concrete type (definitely confusing with the names), but I still don't understand the behavior here. Why aren't all comparisons returning `bool`? There is one obvious and known result type of comparisons?

**Comment by ktbarrett** [comment]
Nvm, I see now that one could return an object with a `__bool__` overload from comparison functions because `bool` calls in branches are implicit. Only, `__eq__` *must* return a `bool`.
