### ISSUE TITLE
Constructing a list from a single object results in the wrong type

### ISSUE THREAD

**Issue by stinodego** [python/mypy#10804]
I hope this is not a duplicate; I found it hard to adequately describe this case. The issue pertains to a mixup of the types `List[Union[x, y]]` and `Union[List[x], List[y]]`.

## The problem
Take the below code to construct a list from a single object. 
```python
def list_from_instance(a: Union[int, str]) -> Union[List[int], List[str]]:
    return [a]
```
Running `mypy` results in:
```
error: Incompatible return value type (got "List[Union[int, str]]", expected "Union[List[int], List[str]]")
```
...even though we can be sure the resulting list object will only have elements of a single type. In fact, the exact same code, but with `float` instead of `string`, does not result in any errors!

```python
def list_from_instance_v2(a: Union[int, float]) -> Union[List[int], List[float]]:
    return [a]
```
So there is clearly some inconsistency here. Additionally, the version below does NOT result in a `mypy` error, even though it is functionally equivalent:
```python
def list_from_instance(a: Union[int, str]) -> Union[List[int], List[str]]:
    if isinstance(a, int):
        return [a]
    else:
        return [a]
```
Please let me know if you agree that this is an issue; I would be happy to try and fix it.

**Comment by ktbarrett** [comment]
This is not a bug. The `a` argument is a `Union[int, str]`, mypy does not know the type of the argument, it's checking the body at this point. When you do `[a]` you are making a list of the type of `a` or `List[Union[int, str]]`. The solution with `isinstance` type guards works, but it seems like your intent is that you don't want to check the body until the function call, so you should instead use a generic.

```python
import typing

T = typing.TypeVar("T", bound=typing.Union[int, str])

def list_from_instance(a: T) -> typing.List[T]:
    return [a]
    
reveal_type(list_from_instance(1))  # note: Revealed type is "builtins.list[builtins.int*]"
reveal_type(list_from_instance("test"))  # note: Revealed type is "builtins.list[builtins.str*]"
list_from_instance(object())  # error: Value of type variable "T" of "list_from_instance" cannot be "object"
```

**Comment by stinodego** [comment]
Hey @ktbarrett , thanks for the explanation. That solution with the TypeVar should indeed do the trick. I am still wondering though: why does the second example with the `Union[int, float]` work without any issue?

**Comment by JelleZijlstra** [comment]
@stinodego likely because there is an implicit subtype relationship between int and float (https://www.python.org/dev/peps/pep-0484/#the-numeric-tower).

**Comment by stinodego** [comment]
Thanks so much! Learned something new today. Will close the issue.
