### ISSUE TITLE
mypy spends a long time in a linux kernel if high number of cores.

### ISSUE THREAD

**Issue by grahamjenson** [python/mypy#10818]
**Questions and Help**

OS: Ubuntu 21.04
mypy version: 0.812
python version: 3.7.10
(I have tested with latest python version and mypy version)

I ran into a perf issue ubuntu 21.04 with mypy when running on a AMD 5950x, to the point a much slower CPU with less cores is 1/3 faster.

The issue looks like:

```
time mypy
mypy  2.72s user **2.33s system** 76% cpu 6.636 total
```

It is spending an equal time in system as to actually running.

Executing `perf mypy` resulted in:

```
sudo perf record -F 100 -g -- scripts/mypy.sh
```

```
  Children      Self  Command        Shared Object                                                Symbol
+   26.68%     0.00%  mypy           [unknown]                                                    [k] 0x0000000000000004
+   24.22%     1.16%  mypy           libc-2.33.so                                                 [.] __sched_yield
+   23.91%     0.00%  mypy           [kernel.kallsyms]                                            [k] entry_SYSCALL_64_after_hwframe
+   20.54%     2.77%  mypy           [kernel.kallsyms]                                            [k] do_syscall_64
+   16.45%     0.35%  mypy           [kernel.kallsyms]                                            [k] __x64_sys_sched_yield
+   13.60%     1.02%  mypy           [kernel.kallsyms]                                            [k] do_sched_yield
+   12.59%     0.00%  mypy           [kernel.kallsyms]                                            [k] schedule
+   12.58%     2.25%  mypy           [kernel.kallsyms]                                            [k] __schedule
+    8.26%     8.26%  mypy           python3.7                                                    [.] r_object
+    7.81%     3.04%  mypy           [kernel.kallsyms]                                            [k] pick_next_task_fair
+    6.85%     0.00%  mypy           [unknown]                                                    [.] 0x0000557d16125be0
+    5.49%     5.49%  mypy           [kernel.kallsyms]                                            [k] __x86_indirect_thunk_rax
+    5.13%     5.13%  mypy           python3.7                                                    [.] _PyEval_EvalFrameDefault
+    5.06%     0.00%  mypy           [unknown]                                                    [.] 0x0000557d16121d40
```

I am not familiar with this, but it looks like with lots of CPUs mypy spends a bunch of time in the kernel scheduler. I am not sure if this is a linux issue or mypy. 

Any help would be appreciated.

**Comment by meshy** [comment]
I failed to reproduce the result of high system usage.
That may have been because the details of my system are not the same.

**OS:** Ubuntu 22.04.1 LTS.
**Kernel version:** `5.15.0-56-generic`
**mypy version:** 0.812 and 0.982
**Python version:** 3.10.6
**Processor:**  i7-12700H

It's also possible that the difference lies in the files tested (I was testing against quite a large directory of files).

For reference:

```console
$ time mypy tasks/
...
mypy tasks/ 159.48s user 0.40s system 99% cpu 2:40.61 total
```

**Comment by JukkaL** [comment]
@grahamjenson Can you try profiling using `py-spy` (https://github.com/python/mypy/wiki/Profiling-Mypy)? It may give a better picture of where time is being spent. 

My guess is that mypy is spending a lot of time looking up modules. You can try running mypy with `-v -v` flags and look at what mypy output tells about search paths (warning: this can produce a lot of output). Example of what I'm looking for:
```
TRACE: python_path:
TRACE:     /home/jukka/src/mypy/t
TRACE:     /home/jukka/src/mypy
TRACE: No mypy_path
TRACE: package_path:
TRACE:     /home/jukka/venv/mypy/lib/python3.11/site-packages
TRACE:     /home/jukka/venv/mypy/lib/python3.11/site-packages
TRACE: typeshed_path:
TRACE:     /home/jukka/src/mypy/mypy/typeshed/stdlib
TRACE:     /home/jukka/src/mypy/mypy/typeshed/stubs/mypy-extensions
TRACE:     /usr/local/lib/mypy
```

**Comment by grahamjenson** [comment]
Hey, cheers for all the work. I am off this project and no longer have any of the code to test with. I will close and you can reopen if someone else has the same issues.
