### ISSUE TITLE
Fail pointless None checks

### ISSUE THREAD

**Issue by johng** [python/mypy#10814]
**Feature**

When checking for None on a type that is not marked as `Optional`, mypy should be able to fail.  

e.g 

```python
a: int = 1
if a is None
    ....
```  

**Pitch**

Irrelevant `None` checks can pollute the code base, this could be an optional feature for those that want it

**Comment by hauntsaninja** [comment]
I believe `--warn-unreachable` should do this.

**Comment by johng** [comment]
That's done it! Maybe the flag should be added to strict mode?
