### ISSUE TITLE
Generic Callable argument disappears!

### ISSUE THREAD

**Issue by Timmmm** [python/mypy#10815]
**Bug Report**

See the following code:

```python
from typing import Callable, Generic, TypeVar

S = TypeVar('S')
T = TypeVar('T')

class Foo(Generic[S, T]):
    _func: Callable[[S], T]

    def __init__(self, func: Callable[[S], T]):
        self._func = func

    def do(self, x: S):
        self._func(x)
```

Mypy gives the following errors.

```
$ mypy --python-version 3.9 --ignore-missing-imports --no-implicit-optional --no-strict-optional --strict-equalit foo.py
foo.py:10: error: Cannot assign to a method
foo.py:10: error: Incompatible types in assignment (expression has type "Callable[[S], T]", variable has type "Callable[[], T]")
foo.py:13: error: Too many arguments
Found 3 errors in 1 file (checked 1 source file)
```

Note that it thinks `self._func` is `Callable[[], T]` even though I clearly included the `S`! This works fine with Pyright.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: See above
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8.7
- Operating system and version: Linux, CentOS of some kind I think.

**Comment by JelleZijlstra** [comment]
This seems like a variant of #2427.
