### ISSUE TITLE
mypy rejects type-applied generics in a NewType

### ISSUE THREAD

**Issue by alexchandel** [python/mypy#10827]
**Bug Report**

`mypy` rejects generic type application in `NewType`.  It seems to forget that the type is generic, and complains that any arguments are applied.

**To Reproduce**

Any of these:

```py
from typing import NewType
MyList = NewType['MyList', list[str]]
```

```py
from typing import NewType
mylist = list[str]
MyList = NewType['MyList', mylist]
```

```py
from typing import NewType, List
MyList = NewType['MyList', List[str]]
```

```py
from typing import NewType, List
mylist = List[str]
MyList = NewType['MyList', mylist]
```

**Expected Behavior**

No lint.

**Actual Behavior**

* `error: Type application is only supported for generic classes`
* `error: Type application has too many types (1 expected)`
* `error: Cannot resolve name "MyList" (possible cyclic definition)`

mypy does not recognize `list` (or `List`, or any other generic) as a generic type.  It complains that type arguments were wrongly applied.

**Your Environment**

- Mypy version used: latest / 0.910
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.9.5
- Operating system and version: macOS 11.4

**Comment by erictraut** [comment]
`NewType` is a function, so it needs to be used like this:

```python
MyList = NewType("MyList", list[str])
```

**Comment by JelleZijlstra** [comment]
Yes. Perhaps the error message could be changed, but the first error already says what's wrong.
