### ISSUE TITLE
mypy.ini: Unrecognized option: exclude

### ISSUE THREAD

**Issue by ssbarnea** [python/mypy#10832]
While [documentation states](https://mypy.readthedocs.io/en/stable/config_file.html#confval-exclude) that `exclude` can be used in main section of `mypy.ini` file, an attempt to add it produces `mypy.ini: [mypy]: Unrecognized option: exclude`

```
[mypy]
exclude = xxx
```

**Comment by ethanhs** [comment]
What mypy version are you using? My guess is that it is old.

**Comment by ssbarnea** [comment]
Yeah, 0.790 did not had exclude. Apparently I failed to do what I asking all my bug reports to do, sorry.

On a side note, I observed that some tools do mention inside docs version on which a particular feature was added or modified, making it much easier to question yourself if you have the right version. Examples: tox and ansible.
