### ISSUE TITLE
Implement overload using variable assignment

### ISSUE THREAD

**Issue by cleoold** [python/mypy#10856]
**Feature**
Declarations with `@overload` always require an implementation following the overload unless using a stub file. The implementation must be defined using function def. However it is inconvenient to define separate functions every time when you can simply assign something to it.

**Pitch**
simple example:
```py
from typing import TypeVar, overload, Union, Callable

T = TypeVar('T')

def make_fun(name: str) -> Callable[[T], T]:
    def f(s: T) -> T:
        print(name)
        return s
    return f

@overload
def a(s: int) -> int: ...
~~~~^ An overloaded function outside a stub file must have an implementation
@overload
def a(s: str) -> str: ...

a = make_fun('a')
^ Incompatible types in assignment (expression has type "Callable[[T], T]", variable has type overloaded function)

@overload
def b(s: int) -> int: ...
~~~~^ An overloaded function outside a stub file must have an implementation
@overload
def b(s: str) -> str: ...

b = make_fun('b')
^ Incompatible types in assignment (expression has type "Callable[[T], T]", variable has type overloaded function)
```

To make them happy, `# type: ignore` or use this walkaround:
```py
...

_a = make_fun('a')
_b = make_fun('b')

@overload
def a(s: int) -> int: ...
@overload
def a(s: str) -> str: ...

def a(s: T) -> T:
    return _a(s)

@overload
def b(s: int) -> int: ...
@overload
def b(s: str) -> str: ...

def b(s: T) -> T:
    return _b(s)
```

This does not seem necessary. Would it be possible to allow such use case.
The only problem I can think of is the difference between function def and `Callable`s

**Comment by ichard26** [comment]
I doubt this would be practical (and honestly I don't really understand how the sample code is supposed to work). If there is genuine want for this feature, it's better discussed over at the [python/typing](https://github.com/python/typing) repository as this would be standardization before being implemented by mypy.
