### ISSUE TITLE
`Enum` types cannot be inherited

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#10857]
**Feature**

## Subtyping with `Enum` exact values

This core currently passes `mypy`:

```python
from enum import Enum

class A(Enum):
   x = 1

class B(A):
    ...
```

But, in runtime this code fails with:

```
Traceback (most recent call last):
  File "ex.py", line 6, in <module>
    class B(A):
  File "/Users/sobolev/.pyenv/versions/3.8.9/lib/python3.8/enum.py", line 146, in __prepare__
    metacls._check_for_existing_members(cls, bases)
  File "/Users/sobolev/.pyenv/versions/3.8.9/lib/python3.8/enum.py", line 527, in _check_for_existing_members
    raise TypeError(
TypeError: B: cannot extend enumeration 'A'
```

This is also the case for `Flag`, `IntEnum`, and `IntFlag`.

## Subtyping without exact values

However, subtyping without `Enum` values is fine:

```python
from enum import Enum

class A(Enum):
   ...

class B(A):
    ...
```

This is also the case for `Flag`, `IntEnum`, and `IntFlag`.

So, the rule is: types inherited from `Enum` with at least one enumeration value should be marked as implicitly `final` type.

Related #10852 
Related #5599

**Comment by sobolevn** [comment]
I would love to work on it after #10852

**Comment by RJPercival** [comment]
There appears to be a bug in the implementation of this feature. Mypy complains that `error: Cannot inherit from final class LabeledEnum` in the following example, even though it works at runtime:
```python
class LabeledEnum(enum.Enum):
    __labels__: Dict[str, str]

class Foo(LabeledEnum):
    A = 1
    B = 2

    __labels__ = {
        "A": "first enum",
        "B": "second enum",
    }
```

I'm guessing mypy is unaware that members prefixed with `__` are not considered enum values?

**Comment by RJPercival** [comment]
I see that this bug has been raised in #11850.
