### ISSUE TITLE
[meta] Use GitHub labels for collecting issues of certain sub-components (stubgen, ...)?

### ISSUE THREAD

**Issue by bluenote10** [python/mypy#10876]
**Documentation**

I'm currently mainly looking into what the stub generation can or cannot do, what are known issues etc. It's a bit hard to get an overview or find duplicates within all the other (core related) issues. Since the stub generation is a fairly isolated sub-component, what do you think about using the GitHub labels/tags for such a purpose as well? Perhaps there are other isolated components where it would make sense.

There is probably no need to identify and label them all once, but rather over time. For identifying duplicates it would already be sufficient to label a few important ones. If desired I can collect a list.

**Comment by JelleZijlstra** [comment]
Yes, this would make sense. I just created `topic-stubgen` and `topic-stubtest` labels.

**Comment by JelleZijlstra** [comment]
https://github.com/python/mypy/labels/topic-stubgen now has a bunch of issues. (Fortunately I realized you can mass-edit labels from the issue search UI :) )

**Comment by bluenote10** [comment]
Awesome, thanks for adding! Probably safe to close this issue as well now.
