### ISSUE TITLE
Mypy thinks float is a supertype of int

### ISSUE THREAD

**Issue by calebho** [python/mypy#10882]
**Bug Report**

Given the following `.pyi` file:
```python
import typing

@typing.overload
def foo(x: float) -> None:
    ...

@typing.overload
def foo(x: int) -> None:
    ...
```

`mypy` yields
```
foo.pyi:8: error: Overloaded function signature 2 will never be matched: signature 1's parameter type(s) are the same or broader
Found 1 error in 1 file (checked 1 source file)
```

However, if you add an implementation (i.e. in a plain `.py` file), there are no errors: https://mypy-play.net/?mypy=latest&python=3.8&gist=e048d0a7153278e9005ed9dec06787ad

**To Reproduce**

1. Run `mypy` on the `.pyi` file

**Expected Behavior**

No errors

**Actual Behavior**

```
foo.pyi:8: error: Overloaded function signature 2 will never be matched: signature 1's parameter type(s) are the same or broader
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: `0.910`
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: `3.8.8`
- Operating system and version: Ubuntu 20.04.1 LTS

**Comment by hauntsaninja** [comment]
Hello!

PEP 484 actually states that type checkers should treat float as a supertype of int (despite `issubclass(int, float) is False`).

It's also not the case that all type errors lead to runtime exceptions (e.g. `x.asdf = 5` is will not raise an exception for many kinds of `x`, but is something a type checker will often rightly complain about). For intuition behind your specific error, replace `float` with `object` in your example (and possible change the return types such that they're incompatible).

P.S. I was Swat '17, do we know each other?

**Comment by calebho** [comment]
> PEP 484 actually states that type checkers should treat float as a supertype of int 

TIL; thanks for the info! This explains why I'm getting the error in the stub file, but why don't I get the same error in the module file?

Since we're both math/CS it's likely we've crossed paths 🙂

**Comment by hauntsaninja** [comment]
Oh, in your mypy-play.net you have the overloads in a different order. In general the overload order matters for type checking, refer to https://mypy.readthedocs.io/en/stable/more_types.html#type-checking-calls-to-overloads
