### ISSUE TITLE
Generic help

### ISSUE THREAD

**Issue by nhatmicls** [python/mypy#10909]
I have some issue when using Generic in class

```python
from typing import *

A = TypeVar("A")


class test_genertic(Generic[A]):
    def __init__(self) -> None:
        super().__init__()

    def test_a(self, inp: int) -> A:
        return inp


test = test_genertic[int]()
print(test.test_a(5))
```

When I run it it show this

```
testing.py:11: error: Incompatible return value type (got "int", expected "A")
Found 1 error in 1 file (checked 1 source file)
```

I think it should be no error in this run, can someone explain what I wrong in here ?

**Comment by JelleZijlstra** [comment]
The error seems pretty self-explanatory to me: the function is supposed to return `A` but actually always returns an int, regardless of the generic parameter to `test_genertic`. I'd suggest discussing this on https://gitter.im/python/typing where others may be able to help explain.

One other note I'll give is that mypy basically checks each function in isolation, so the fact that you're using `test_genertic[int]` later doesn't matter to this error. mypy sees the signature of the `test_a` method, compares it to the implementation, and reports a discrepancy.
