### ISSUE TITLE
MyPy needs to ignore 'gc.set_threshold(150 * 1000)' when running on PyPy3-3.8

### ISSUE THREAD

**Issue by stonebig** [python/mypy#10917]
Testing on PyPy-3.8 nightly, I discover that 1 line may be to ignore, when MyPy is running on PyPy3:

![image](https://user-images.githubusercontent.com/4312421/128015822-10196ec1-6401-4064-ba6b-59615ad98399.png)

then it's apparently functionnal, see https://foss.heptapod.net/pypy/pypy/-/issues/3526
![image](https://user-images.githubusercontent.com/4312421/128015997-c4825270-81ca-4a00-82e5-9ff49d32013e.png)

**Comment by stonebig** [comment]
hum, or PyPY3-3.8 just implement  a dummy function 'gc.set_threshold' that just does nothing.

**Comment by JelleZijlstra** [comment]
Sorry, what does the `iter_primes` sample have to do with `gc.set_threshold`? And what is the error you're seeing?

**Comment by JelleZijlstra** [comment]
I see, and the problem is that mypy calls gc.set_threshold internally, so running mypy under pypy fails. I don't think we officially support pypy, but it would be easy enough to set something like `if hasattr(gc, "set_threshold"):`.

**Comment by ethanhs** [comment]
The bigger issue with PyPy support is that the AST in PyPy nightly won't work with mypy (yet) as it doesn't handle AST feature versions (at least when I checked a month ago).
