### ISSUE TITLE
Types don't branch correctly in nested if conditions

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#10944]
```python
if self.username or self.password:
    if self.username:
        auth_args: Tuple[str, ...] = (self.username, self.password or "")
    else:
        auth_args = (self.password,)
```

On the last line this produces:
`error: Incompatible types in assignment (expression has type "Tuple[Optional[str]]", variable has type "Tuple[str, ...]")  [assignment]`

But, the first condition ensures that atleast one of username and password is not None, then the else ensures that the username is None, so the password must not be None.

Mypy version 0.910.

**Comment by AlexWaygood** [comment]
This isn't really a reproducible example — can you recreate this behaviour with a self-contained code snippet?

**Comment by JelleZijlstra** [comment]
Mypy can't be expected to be able to understand cross-variable type information like this. There have been several similar reports here and on the pyright tracker.
