### ISSUE TITLE
new union syntax (`types.Union`) doesn't work on generic bounds

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#10949]
```py
from typing import TypeVar


T = TypeVar("T", bound=int | str)

def foo(value: T):
    ...
```
https://mypy-play.net/?mypy=latest&python=3.10&flags=show-column-numbers%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=e32e412ddf26892faaadcf3bda061ad6

**Comment by hauntsaninja** [comment]
Thanks, repros on latest master (in general, latest master has fixes for several PEP 604 issues at runtime)

**Comment by DetachHead** [comment]
seems to be working now on master. assuming #11140 fixed it

**Comment by DetachHead** [comment]
@hauntsaninja here you go #11431
