### ISSUE TITLE
One-in-many types for tuples?

### ISSUE THREAD

**Issue by simaoafonso-pwt** [python/mypy#10963]
I think my issue is better explained with an example. The issue title reflects this:

```python
import math
import typing


def layout(spec: str) -> typing.Tuple[int, int]:
    amount: int = 1000
    if spec == 'x':
        return 0, 0
    elif 'x' in spec:
        rows, cols = [None if v == '' else int(v) for v in spec.split('x')]
        # At least one of `rows`/`cols` is not `None`
        if rows is None:
            rows = math.ceil(amount / cols)  # mypy error
        if cols is None:
            cols = math.ceil(amount / rows)
        return rows, cols
    return 0, 0
```

This is the result I get with the latest stable version:
```
mypy_issue.py:13: error: Unsupported operand types for / ("int" and "None")
mypy_issue.py:13: note: Right operand is of type "Optional[int]"
```

I know that at least one of `rows`/`cols` is not `None`, so the error doesn't really apply.

I have two questions:
- Can I tell this to the type checker in a smarter way, other than `type: ignore`?
- Should I bother?

**Comment by erictraut** [comment]
Static type checkers generally do not track cross-variable type dependencies (e.g. "if `rows` is `None`, then the type of `cols` is `int`, but if `rows` is not `None`, then `cols` might be `None`).

The technique I recommend in this case is to add an assert statement before the error line:
```python
assert cols is not None
```

This assert will not only quiet the mypy error, but it also serves as documentation and runtime validation of your assumption.

**Comment by AlexWaygood** [comment]
As Eric explains, this kind of type-narrowing is too complex for mypy to reasonably be expected to understand.
