### ISSUE TITLE
Callback protocol with other attributes

### ISSUE THREAD

**Issue by erictraut** [python/mypy#10976]
I'm not sure if this is a mypy bug or intended behavior. I'm looking for advice.

PEP 544 introduced the concept of a [callback protocol](https://www.python.org/dev/peps/pep-0544/#callback-protocols). In particular, it says:

> [Callback protocols] can be defined as protocols with a __call__ member

It is not clear to me whether a protocol that defines members other than `__call__` is considered a callback protocol. PEP 544 says:

> Callback protocols and Callable[...] types can be used interchangeably.

This could imply that a protocol class that includes attributes other than `__call__` is not a callback protocol, but maybe I'm reading too much into it. I thought I remembered reading somewhere (perhaps on a typing-sig thread?) that if a protocol class included attributes other than `__call__`, it would not be considered a callback protocol, but I can't seem to find that thread.

A pyright user (@kennipj) recently filed [this bug report](https://github.com/microsoft/pyright/issues/2179). Currently, the behavior of pyright matches mypy in this case. I'm wondering if mypy's behavior is intended or whether it's a bug.

Here's another mypy bug that is related to this issue: https://github.com/python/mypy/issues/10403.

**Comment by JelleZijlstra** [comment]
I'm not sure "callback protocol" should be defined as a concept by itself: it's just an emergent property of the type system that a Protocol with a `__call__` method will match a callable.

For the bug report you link to, I feel the issue is that the type checker doesn't understand that a function is a `FunctionType` instance with a `__name__`.

**Comment by erictraut** [comment]
It sounds like there's no definitive answer. After much discussion, we've decided to interpret "callback protocol" in a more lax manner, consistent with what @JelleZijlstra said above. 

We've made this change in pyright, which now deviates from mypy in the following sample. If you agree with our conclusion, please consider this a request for a change in mypy.

```python
from typing import Protocol

class SomeFunc(Protocol):
    __name__: str
    other_attribute: int

    def __call__(self) -> str:
        ...

def other_func(f: SomeFunc):
    print(f.__name__)
    f.other_attribute = 1

    f.other_attribute = "str"  # pyright and mypy emit an error
    f.missing_attribute = 3  # pyright and mypy emit an error

@other_func  # pyright does not emit an error, but mypy does
def some_func() -> str:
    ...
```
