### ISSUE TITLE
Incompatible types in assignment (expression has type "BinaryIO", variable has type "TextIO")

### ISSUE THREAD

**Issue by jdhao** [python/mypy#10982]
**Bug Report**

mypy reports correct reading of pickle files as error.

**To Reproduce**

Use the following code:

```python
import json
import pickle

with open('test_ids.json') as f:
    my_ids = json.load(f)

for _id in my_ids:
    id_path = f'{_id}.pkl'

    with open(id_path, 'rb') as f:
        v2_feat = pickle.load(f)
```

Then use mypy to check the code: `mypy test.py`

**Expected Behavior**

No error occurs.

**Actual Behavior**

I see the following errors:

> test.py:10: error: Incompatible types in assignment (expression has type "BinaryIO", variable has type "TextIO")
test.py:11: error: Argument 1 to "load" has incompatible type "TextIO"; expected "IO[bytes]"

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.7.6
- Operating system and version: CentOS 7.4

**Comment by ethanhs** [comment]
mypy is *technically* correct here. Note that even after a context manager scope has been left, the variable `f` is still valid. 

```python
with open('test.txt') as f:
    pass
print(f) # works
```

Therefore, you are actually re-defining the variable `f` between uses of the context manager.

I do understand this is rather un-intuitive but I'm not sure if there is a good workaround for this pattern.

**Comment by erictraut** [comment]
I would expect this to work if you specify the `--allow-redefinition` flag, but it still generates an error.

**Comment by AlexWaygood** [comment]
Mypy [no longer emits an error](https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=a995e55b5501aed9668e36b641d0e8a8) for this code (I believe this is a result of #12254).
