### ISSUE TITLE
mypy doesn’t admit Optional Exception types in except statement.

### ISSUE THREAD

**Issue by xiaoyu2006** [python/mypy#10980]
**Bug Report**

I have a variable T with type `Union[Type[Exception], Tuple[Type[Exception]]]`. But when I use it as a type in `except T as e` it says it must be derived from BaseException. However it’s acceptable to receive a tuple of Exception types into except statement. 

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: mymodule 
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.9
- Operating system and version: Ubuntu 20.04

**Comment by erictraut** [comment]
Could you provide a minimal sample that reproduces the problem? I tried to repro it using the following code, but this type checks without errors in the latest version of mypy.

```python
from typing import Tuple, Type, Union

def foo(x: Union[Type[Exception], Tuple[Type[Exception]]]):
    try:
        pass
    except x:
        pass
```

**Comment by JelleZijlstra** [comment]
I vaguely remember we fixed this not too long ago; there were previous issues about it.

**Comment by xiaoyu2006** [comment]
@erictraut Sorry but the problem is not `Tuple` but `Optional`.

This script can reproduce:
```python
from typing import Callable, Optional, Union, Type, Tuple

def handle(
    func: Callable,
    exception_type: Optional[
        Union[Type[Exception], Tuple[Type[Exception]]]
    ] = Exception,
    *args,
    **kwargs
):
    try:
        return func(*args, **kwargs)
    except exception_type as e:
        print(e)
```

**Comment by xiaoyu2006** [comment]
Oh sorry it’s my own problem. I misunderstood `Optional`’s meaning
