### ISSUE TITLE
Incorrect mypy behaviour when inheriting a generic with List[T] field

### ISSUE THREAD

**Issue by Fatal1ty** [python/mypy#10986]
I have the following sample of code:

```python
from dataclasses import dataclass
from typing import Generic, List, TypeVar


T = TypeVar('T', int, str)


@dataclass
class A(Generic[T]):
    x: List[T]


@dataclass
class B(A[int]):
    pass


B(x=[1])  # error: List item 0 has incompatible type "int"; expected "T"
```

mypy 0.910 gives `error: List item 0 has incompatible type "int"; expected "T"` that is not what I expected since I declared `x` as `List[int]` with generic inheritance.

- Mypy version used: 0.910
- Python version used: 3.9.1

**Comment by ilevkivskyi** [comment]
FWIW this works correctly on the current master.
