### ISSUE TITLE
Callable constraint inference doesn't consider argument kinds

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1098]
`visit_callable_type` in `mypy/constraints.py` should look at argument kinds and use them to match arguments. Currently it assumes that the kinds of arguments are the same in both callables.

We may be able to reuse or adapt similar code from call expression type checker (`map_actuals_to_formals`).

See also discussion in #1085.

**Comment by ddfisher** [comment]
Can you add a test case for this issue?

**Comment by JukkaL** [comment]
Closing as duplicate of #702.
