### ISSUE TITLE
FastApi could benefit from this potentially

### ISSUE THREAD

**Issue by nilansaha** [python/mypy#10991]
I wonder if https://github.com/tiangolo/fastapi can benefit from this. A huge amout of the Python community is switching to it for building web api so it could be worthwhile if we can make it work

@tiangolo

**Comment by hauntsaninja** [comment]
https://github.com/tiangolo/fastapi/blob/master/scripts/lint.sh

**Comment by nilansaha** [comment]
I meant FastApi could benefit from mypyc. Not mypy.
I guess its confusing because mypyc is a subdirectory under the repo

**Comment by hauntsaninja** [comment]
In either case, better discussed on the FastAPI repo since that's the project where changes would be made.
