### ISSUE TITLE
Format code using Black?

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#10996]
There have been suggestions to use Black to format the mypy (and mypyc) codebase for a long time. Maybe it's time to actually do the switch now? 

We'd need a volunteer to drive the project. I don't expect it to be a lot of work, but we'd need to at least update contributor documentation and pip dependencies. We'd also need to decide whether we'd fail a PR if it's not correctly formatted.

Next steps:
- [ ] Find a volunteer who'd like to drive this
- [ ] Collect feedback from contributors
- [ ] Write a more detailed plan about what needs to be done (if most contributors are happy with this or at least don't hate the idea)
- [ ] Merge some PRs as many of them will get merge conflicts after the switch? Or leave comments asking the contributors to run black themselves?
- [ ] Implement the switch

**Comment by hauntsaninja** [comment]
Seems fine to me, although I'd like us to merge PRs before doing this (I recently got a number of PRs merge-conflict free, but haven't had time / knowledge to review them). I'd also prefer it if mypy kept its current line length.

**Comment by 97littleleaf11** [comment]
Personally speaking, I'm quite like the black coding style. Also, I agree that we might still keep the line length to 99.

**Comment by 97littleleaf11** [comment]
Several things need to discuss which would bring lots of style change to current codebase:
* Black uses double quotes `"` while mypy uses single quote `'` primally
* Black splits `()` and let each item take one line. (imports, function calls, logical expressions, etc)

**Comment by JukkaL** [comment]
@97littleleaf11 Those style changes would be necessary, since Black doesn't have many configuration options. Since they would change a large fraction of lines, many open PRs would get merge conflicts.

I can dedicate some time to reviewing PRs before we implement the switch. It would be good to have a timeline for the switch announced at least a few weeks ahead of time, so that there's time to merge a bunch of open PRs.

**Comment by jhance** [comment]
I think we don't need to be too nervous about existing PRs. Its pretty easy to automatically rebase such PRs with something like:
1. First rebase to the commit prior to black
2. Run black on the top of your PR.
3. Re-parent your diff on top of the black commit (NOT a rebase). You can do this by checking out the black commit and then doign `git checkout your-pr .` for example.

**Comment by KotlinIsland** [comment]
Thanks @jhance, I think it's important to communicate these steps onto all conflicting PR's, I will add it to the OP in theBlack PR.

**Comment by KotlinIsland** [comment]
@JukkaL The PR is fully formed I think, what steps should we take next?

**Comment by q0w** [comment]
Maybe it's worth adding pycln as it was done in https://github.com/python/typeshed/pull/8304?

**Comment by KotlinIsland** [comment]
@q0w That seems more like a linter, and less like a formatter. I don't want to bloat this change because it's already hard enough.

**Comment by KotlinIsland** [comment]
I found a really good strategy to rebase conflicting PR branches:
1. Rebase onto the configuration commit (not the format commit).
1. Interactively rebase from the start of your branch pausing on every commit.
1. Run `git checkout --theirs .; black .; isort .; git add -A; git rebase --continue`
1. repeat 3 until you pass over all commits
1. Once complete rebase onto master
