### ISSUE TITLE
closured value not narrowed for immediately invoked lambda, but incorrectly narrowed for non-immediately invoked lambda

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#10993]
```py
f: int | str

if isinstance(f, int):
    # error: Unsupported operand types for + ("str" and "int")
    # even though there's no chance the value could be a string here since the lambda is immediately invoked
    (lambda: f+1)()

    # no error, even though the lambda could get called later when the type changes
    asdf = lambda: f + 1
```
https://mypy-play.net/?mypy=latest&python=3.10&gist=9853f815e80f43e878bc9e1ae2d29108

**Comment by erictraut** [comment]
I just introduced a new feature in pyright that addresses this case. It applies type narrowing to local variables and parameters that are captured in an inner-scoped function or lambda. It's able to do so in a type-safe manner by verifying that the symbol is not assigned a new value on any code path after the lambda or def statement. If it detects such a reassignment, it does not apply type narrowing (i.e., it falls back to the current behavior).

```python
def func1(x: int | None):
    if x is not None:
        lambda: x + 1  # This no longer generates an error

def func2(x: int | None):
    if x is not None:
        lambda: x + 1  # This still generates an error
    x = get_new_value()
```

This feature was tricky to implement. I needed to apply some limitations and handle a bunch of edge cases that were not obvious at first. If someone is interested in implementing similar functionality in mypy, I'd be happy to assist you by providing some pointers. You might also find [these test cases](https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/tests/samples/capturedVariable1.py) to be useful.

**Comment by bluebird75** [comment]
I ran into this bug too.

**Comment by hauntsaninja** [comment]
For people who stumble onto this issue, see https://mypy.readthedocs.io/en/stable/common_issues.html#narrowing-and-inner-functions and discussion in this issue #2608

Awesome that Pyright tracks assignments to make things better here. For my future self, https://github.com/microsoft/pyright/commit/e121a78576760011f7aaa99a3d8a36d15a42caae seems to be the relevant commit

**Comment by hauntsaninja** [comment]
Note that these days mypy handles this much better in practice, at least inside of functions. I don't think it's ever going to learn exactly the trick about immediate evaluation, but hopefully the current heuristics work significantly better in most cases.

**Comment by hauntsaninja** [comment]
Closing as per my previous comment
