### ISSUE TITLE
Mypy misses conditional name not defined errors

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#11006]
```python
if False:
    bar = "a"

print(bar)
```

Mypy passes successfully on this code. Python obviously errors with `NameError: name 'bar' is not defined` at runtime.

Mypy should ensure that a variable when referenced has been defined in all possible paths of execution up to that point.

**Comment by erictraut** [comment]
This is related to https://github.com/python/mypy/issues/2400 and https://github.com/python/mypy/issues/686

**Comment by Dreamsorcerer** [comment]
Thanks
