### ISSUE TITLE
typing.NamedTuple does not allow default values

### ISSUE THREAD

**Issue by lilyz622** [python/mypy#11012]
**Bug Report**
when I try to define defaults for NamedTuple, I get thrown a TypeError. I am not sure if this is expected behavior.

**To Reproduce**

(Write your steps here:)

from typing import NamedTuple
x = NamedTuple('hi', a=str, b=str, defaults=[None])

**Expected Behavior**

x = NamedTuple('hi', a=str, b=str, defaults=[None])
y = x(a='1',b=None)

c = NamedTuple('hi', a=str, b=str, defaults=['bye'])
b = c(a='1')
b # returns hi(a='1', b='bye')

**Actual Behavior**
x = NamedTuple('hi', a=str, b=str, defaults=[None])

... lib/python3.8/typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: NamedTuple('Name', [(f0, t0), (f1, t1), ...]); each t must be a type Got ['hi'].

c = NamedTuple('hi', a=str, b=str, defaults=['bye'])

lib/python3.8/typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: NamedTuple('Name', [(f0, t0), (f1, t1), ...]); each t must be a type Got ['bye'].

**Your Environment**
- Python version used: Python 3.8.6
- Operating system and version: Linux

**Comment by erictraut** [comment]
As a workaround, you can use the class declaration form:

```python
class x(NamedTuple):
    a: Optional[str] = None
    b: Optional[str] = None
```

**Comment by JelleZijlstra** [comment]
This is a runtime error, so mypy can't do anything about it. Closing in favor of python/typing#850.
