### ISSUE TITLE
Mypy alternates between "error: Skipping analyzing" and no errors

### ISSUE THREAD

**Issue by NiklasRosenstein** [python/mypy#11010]
**Bug Report**

I have in my environment a bunch of packages in the `nr` namespace packages (e.g. `nr.preconditions`, `nr.stream`, `nr.optional`, etc.). When using Mypy to check my package, every other invokation (starting with the first time), it shows errors that the type hints for the `nr` module cannot be found.

![image](https://user-images.githubusercontent.com/1318438/130451805-b7b3b10a-53e1-4f94-bd67-d234fa0c2f31.png)

The `nr.*` packages I listed above and also the `databind` packages check out with Mypy individually. It seems that only every other invokation, Mypy understands that it doesn't need to look for type hints for `nr` because it is just a namespace package. The `nr/__init__.py` file is the same for all of these packages with the following content:

```py
__path__ = __import__('pkgutil').extend_path(__path__, __name__)  # type: ignore
```

What also surprises me is that Mypy seems to be checking the validity of dependencies? (I.e. source code in `.venv`) My understanding was that Mypy axiomatically assumes the correctness of type hints in dependencies and only fully checks static typing in the files/directories specified on the CLI.

**To Reproduce**

I'm having a bit of a hard time to find a small example to reproduce this issue consistently. The project where I experience this is internal, so I can't share the entire project. Until I find a definitive reproduction scenario, happy to take any advice or answer questions.

**Expected Behavior**

Mypy does not look for type hints for the `nr` namespace.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: n/a
- Mypy configuration options from `mypy.ini` (and other config files): n/a
- Python version used: 3.9.6
- Operating system and version: OSX

**Comment by aberres** [comment]
Maybe related to https://github.com/python/mypy/issues/9852?

**Comment by NiklasRosenstein** [comment]
Thanks @aberres , it does seem related. Adding `--no-incremental` as suggested in the linked issues also makes it work consistently for me.

**Comment by hauntsaninja** [comment]
This should be fixed on latest master (please re-open if can still repro!)
