### ISSUE TITLE
Mypy won't follow imports to local files. " cannot find implementation"

### ISSUE THREAD

**Issue by Luttik** [python/mypy#11044]
**Bug Report**

The exception "error: Cannot find implementation or library stub for module named "mypy_src_issue_example.a" is thrown for local files that are in scope, even when `py.typing` is added to the project. An example project is added here: [mypy-local-import-issue-example](https://github.com/Luttik/mypy-local-import-issue-example/settings), but the gist is that:

For a file `src/my_project/a.py`

```py
def foo() -> str:
    ...
```

and a file  `src/my_project/a.py`

```py
from my_project.a import foo

foo()
```

The following exception will be thrown:
```
my_project\b.py:1: error: Cannot find implementation or library stub for module named "my_project.a"
src\my_project\b.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 2 source files)
```

this happens with and without the following `pyproject.toml` config:
```toml
# more non-mypy config above

[tool.mypy]
mypy_path = "src"
python_version = "3.8"
```

**To Reproduce**

I've stored a small examplary project here: [mypy-local-import-issue-example](https://github.com/Luttik/mypy-local-import-issue-example/settings)

**Expected Behavior**
It should not throw any error since there is no reason why it shouldn't be able to resolve `src/my_project/a.py`.

**Your Environment**

- Mypy version used: "0.910"
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): see above
- Python version used: 3.8
- Operating system and version: Windows 10 Pro (build 19043.1165)

**Comment by hauntsaninja** [comment]
I believe this should work if you set `--namespace-packages=True` (this should be made the default, see #8584)

**Comment by pietermarsman** [comment]
An alternative solution is to add a `__init__.py` file to the directory. This indicates that the directory is a python module.

**Comment by KomaGR** [comment]
> An alternative solution is to add a `__init__.py` file to the directory. This indicates that the directory is a python module.

Why might this solution not be working for me? I'm not entirely familiar with python modules but this didn't work whereas adding `--namespace-packages=True` worked.

**Comment by franco-demarco** [comment]
Note that if you have added an __init__.py file to src/, you may be getting that error. This happens because adding __init__.py to src/ makes src a package, which can cause the error. With the src layout, src/ should just be a container, not a Python package.
