### ISSUE TITLE
`isinstance` on floats and ints

### ISSUE THREAD

**Issue by onnokort** [python/mypy#11054]
On mypy 0.910, py3.8, checking this file
```
from typing import Union

def f(x : Union[int, float]):
    if isinstance(x, float):
        print("b", x)
    elif isinstance(x, int):
        print("a", x)
```
with `--warn-unreachable` returns an error:
```
$ mypy  --warn-unreachable  intfloat.py
intfloat.py:6: error: Statement is unreachable
Found 1 error in 1 file (checked 1 source file)
```

I have found the closely related https://github.com/python/mypy/issues/10471, in which @srittau states:

> Per PEP 484, int is a subtype of float, meaning that every function that takes float arguments also takes int arguments.  [..]

However, the implementation of `isinstance` does not assume `int` to be a subtype of `float`. 

This seems to be a case where the duck typing assumption (as per the mypy docs) on `int` vs. `float` is incompatible with the actual implementation and behavior of `isinstance` - as all the code is reachable:
```
>>> f(3)
a 3
>>> f(3.0)
b 3.0
```

**Comment by hauntsaninja** [comment]
Yeah, this comes from https://www.python.org/dev/peps/pep-0484/#the-numeric-tower
I'd recommend using `# type: ignore` here.
