### ISSUE TITLE
Did Travis die?

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#11062]
I noticed Travis wasn't running on my PR. Travis' website still exists, but it looks like it hasn't run a build for us, on PR or master, in 18 days. Anyone know what's up? Pretty bad to have CI silently disappear.

**Comment by JelleZijlstra** [comment]
This happened to python/typing too and we just moved CI fully to GH Actions. I'm afraid we'll have to do the same here.

**Comment by christianbundy** [comment]
I can maybe take a look at this in the next week or so.

**Comment by 97littleleaf11** [comment]
This issue is quite important thus I'll open a draft PR today. I might only add one or two tests at first and it would be great if anyone can make further contribution.
