### ISSUE TITLE
Conditional class import

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1107]
It's pretty common to conditionally import a class. Here is a synthetic example:

```
try:
    from m1 import C
except ImportError:
    from m2 import CC as C
```

It's not quite obvious how code like the above should be type checked, as `m1.C` and `m2.CC` generally don't have identical interfaces.

See also #649.

**Comment by kirbyfan64** [comment]
Maybe Mypy could set `C`'s type to the intersection (all the common attributes/methods) of `m1.C` and `m2.CC`.

**Comment by JukkaL** [comment]
That just might work. There are still some details that are non-obvious -- for example, what happens if the type of an attribute or a method argument is different is `m1.C` and `m2.C`. Also, generating useful error messages when accessing an attribute defined in `m1.C` but not `m2.CC`, for example, would need some extra logic.

Implementation-wise, we could internally create a new class that is a subclass of only the common base classes of `m1.C` and `m2.CC`, and only includes definitions that are implemented by both of the classes. The class would *not* be a subclass of either `m1.C` or `m2.CC`, which might be a problem.

**Comment by lkraider** [comment]
Wouldn't it effectively be treated as an `Union[C, CC]` for the code that performs this conditional import?

**Comment by NYKevin** [comment]
> Wouldn't it effectively be treated as an `Union[C, CC]` for the code that performs this conditional import?

No, that fails to ensure that every instance is of the same type (thus causing problems for binary operator overrides, among other things).  However, I would think that `TypeVar('C', m1.C, m2.CC)` would be entirely suitable for this use case.

**Comment by JukkaL** [comment]
This seem too difficult to fix relative to the benefit. Generally using `# type: ignore` is an acceptable workaround.
