### ISSUE TITLE
Dict is not a subtype of MutableMapping while using structural subtyping

### ISSUE THREAD

**Issue by Tomatosoup97** [python/mypy#11081]
**Bug Report**

According to the [docs](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#standard-duck-types), MutableMapping should be a type to describe dict-alike objects, whereas it fails on describing `dict` itself in case of using `Protocol`s

**To Reproduce**

```
from dataclasses import dataclass
import typing as t

class MappingParamProto(t.Protocol):
    x: t.MutableMapping

@dataclass
class DictParam:
    x: dict

def f(my_mapping: t.MutableMapping):
    pass

def lift_f(mapping_param: MappingParamProto):
    pass

dict_param = DictParam({42: '17'})

# works just fine
f(dict_param.x)

# Error:
# Following member(s) of "DictParam" have conflicts:
#    x: expected "MutableMapping[Any, Any]", got "Dict[Any, Any]"
lift_f(dict_param)
```

**Expected Behavior**

dict should be a subtype of MutableMapping

**Actual Behavior**

`expected "MutableMapping[Any, Any]", got "Dict[Any, Any]"`

**Your Environment**

- Mypy version used: 0.910
- Python version used: 3.9.6

**Comment by JelleZijlstra** [comment]
This is because attribute inheritance is invariant. Your protocol would allow setting `y.x = MutableMapping()`, but if `y` is actually a `DictParam`, you'd get an incorrect type. Use `@property` to make a read-only field on the protocol.
