### ISSUE TITLE
Declaring types as cython typed memoryviews causes a SyntaxError

### ISSUE THREAD

**Issue by jacklovell** [python/mypy#11118]
**Bug Report**

Annotating a variable which is a Cython memoryview, e.g. `double[:]`, in a Python file using Cython's [https://cython.readthedocs.io/en/latest/src/tutorial/pure.html](pure mode), causes mypy to issue syntax error messages and prevents type checking from completing. It is also not possible to type check a module which imports the module using cython types, even when specifying the cython-typed module is to be ignored.

**To Reproduce**

The following module compiles fine with Cython and runs fine in both pure Python and in Cythonized form.

```python
# cython: language_level=3
import cython
from cython import double, size_t
import numpy as np


@cython.boundscheck(False)
def func_with_mv(a: double[:]) -> np.ndarray:
    b: double[:] = np.empty_like(a)
    i: size_t 
    for i in range(len(a)):
        b[i] = 2 * a[i]
    return np.asarray(b)
```

**Expected Behavior**

Mypy reports no typing errors.

**Actual Behavior**

Mypy reports syntax errors on lines 8 and 9 (where `double[:]` is used):

```
mypy_cython_mwe.py:8: error: syntax error in type comment
mypy_cython_mwe.py:9: error: syntax error in type comment
Found 2 errors in 1 file (errors prevented further checking)
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.7.1
- Operating system and version: Scientific Linux 7 x86_64

**Comment by hauntsaninja** [comment]
Looks like mypy no longer treats this as a blocking error
