### ISSUE TITLE
"Import solcx could not be resolved"

### ISSUE THREAD

**Issue by yellowcheese773** [python/mypy#11110]
**Documentation*
I have a very annoying problem. I can't import from solcx although I have installed it, when I do `pip3 list` it even shows solc and solcx as packages in the list (I am using VSC).

<img width="830" alt="Bildschirmfoto 2021-09-15 um 11 37 37" src="https://user-images.githubusercontent.com/80122924/133410551-068211e5-65b1-4bf5-acc0-32576a5e9f70.png">

I have installed Python correctly. When I type `python3 --version` it shows `Python 3.9.7` 

I have installed pip correctly. When I type `pip --version` it shows `pip 18.1 from /Library/Python/2.7/site-packages/pip (python 2.7)`

I have also installed pip3. When I type `pip3 --version` it shows `pip 21.2.4 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)`

I have installed py-solc-x. When I install it, it shows that:

<img width="815" alt="Bildschirmfoto 2021-09-15 um 11 44 40" src="https://user-images.githubusercontent.com/80122924/133410907-0337ddd3-8c70-41c8-a597-356aa7521cf7.png">

Despite all that, it don't want to import it. 

<img width="1156" alt="Bildschirmfoto 2021-09-15 um 11 42 00" src="https://user-images.githubusercontent.com/80122924/133410441-21bb4237-3367-42ec-b919-5c5c0470aa69.png">

I try since 2 days to solve this problem. I did almost everything. I am new to Python and the Chainlink Developer was right, installing these things is the hardest. 
I would be really thankful if somebody could help me out.

**Comment by JelleZijlstra** [comment]
Your issue seems to be coming from Pylance, not mypy. Most likely it's because solcx is not marked as a typed package using PEP 561.

**Comment by erictraut** [comment]
Please file an issue in the [pylance repo](https://github.com/microsoft/pylance-release), and someone there will help you out.
