### ISSUE TITLE
Order of overloads determines Protocol compatibility

### ISSUE THREAD

**Issue by suned** [python/mypy#11154]
Classes implementing a protocol with overloaded methods is deemed incompatible with the protocol, unless the overloaded methods are defined in the same order:

```python
from typing import overload, Protocol

class P(Protocol):

    @overload
    def f(self, x: int) -> int: ...

    @overload
    def f(self, x: str) -> str: ...

    def f(self, x): ...


class C:
    @overload
    def f(self, x: str) -> str: ...

    @overload
    def f(self, x: int) -> int: ...
    
    def f(self, x): ...
    
p: P = C()
```
Mypy output:

```console
>  mypy test_types.py --pretty
test_types.py:29: error: Incompatible types in assignment (expression has type "C", variable has type "P")
    p: P = C()
           ^
test_types.py:29: note: Following member(s) of "C" have conflicts:
test_types.py:29: note:     Expected:
test_types.py:29: note:         @overload
test_types.py:29: note:         def f(self, x: int) -> int
test_types.py:29: note:         @overload
test_types.py:29: note:         def f(self, x: str) -> str
test_types.py:29: note:     Got:
test_types.py:29: note:         @overload
test_types.py:29: note:         def f(self, x: str) -> str
test_types.py:29: note:         @overload
test_types.py:29: note:         def f(self, x: int) -> int
```

I expected the assignment `p: P = C()` to be type-safe, since the order of overloads doesn't impact `C`s ability to act as a `P` in this case.

- Mypy version used: 0.910
- Mypy command-line flags: --pretty
- Python version used: 3.8
- Operating system and version: MacOS 10.15.4

**Comment by hauntsaninja** [comment]
Order of overloads is important, e.g. if you had a subclass of int and str.

**Comment by suned** [comment]
> Order of overloads is important in general, e.g. if you had a subclass of both int and str.

For some types yes, but for e.g the intersection of `int` and `str` no, since that's not a valid type in python or mypy.
