### ISSUE TITLE
Certain attributes of the locale module are not found

### ISSUE THREAD

**Issue by vyasr** [python/mypy#11183]
This script:
```
import locale

print(locale.AM_STR)
print(locale.DAY_1)
```
will run fine, but mypy gives the following error:
```
test.py:3: error: Module has no attribute "AM_STR"
Found 1 error in 1 file (checked 1 source file)
```
I've reproduced this with a few versions of mypy >0.700 (0.725, 0.750, and 0.782).

So far as I can tell, the Python library defines all such constants in C in [this file](https://github.com/python/cpython/blob/main/Modules/_localemodule.c), exports them to Python, and then imports them via [a wildcard import in locale.py](https://github.com/python/cpython/blob/main/Lib/locale.py#L47). What's particularly strange is the fact that the `DAY_1` access is not marked as erroneous while the `AM_STR` access is because both of these are being defined in exactly the same way (via the `LANGINFO` module pulling from the contents of [langinfo.h](https://pubs.opengroup.org/onlinepubs/009696699/basedefs/langinfo.h.html)). I don't know whether this indicates a limitation of mypy w.r.t. wildcard imports (seems unlikely since the standard lib uses them extensively for such purposes), a problem with the standard library's imports (also seems unlikely because these two constants are defined in the same way) or something else entirely. I've marked this as a question for now, but it can be reclassified or migrated to a different issue tracker (e.g. CPython's) if necessary.

**Comment by sobolevn** [comment]
Hi, @vyasr! Thanks a lot for the report. Looks like `AM_STR` and `PM_STR` were missing from `locale.pyi` in `typeshed`.
After https://github.com/python/typeshed/pull/6065 is merged and typeshed in mypy is updated, it should be fine.

**Comment by vyasr** [comment]
Awesome thanks! I'll let you close this issue once the mypy-local copy of typeshed is updated.
