### ISSUE TITLE
Stricter compatibility checking of opaque types

### ISSUE THREAD

**Issue by wmdrichards** [python/mypy#11188]
**Feature**

Allow some way of treating types with no stubs as opaque, but distinct, types, rather than treating them as Any.

**Pitch**

A _lot_ of errors are missed by the current behavior when using types from a 3rd party untyped library. For example, the following code passes mypy checks:
```
import tensorflow as tf


def bar() -> tf.Tensor:
    return tf.zeros(0)


def foo() -> str:
    return bar()
```
Treating tf.Tensor as an opaque type would allow mypy to flag the code as incorrect. FWIW, PyCharm shows a warning. Obviously there are some edge cases to consider w.r.t subclasses, but opting in to this behavior on a per-class level could catch a lot of problems.

**Comment by wmdrichards** [comment]
One workaround that I tried was adding a single Tensor class to a tensorflow stub, but I couldn't find a way to ignore all of the other 'module has no attribute ...' errors. I would think adding more support for partial stubbing would be the most natural way to address this need.

**Comment by erictraut** [comment]
You should be able to avoid the 'module has no attribute ...' errors in a partial stub file by adding a `__getattr__` method at the module level as specified in [PEP 484](https://www.python.org/dev/peps/pep-0484/#id44), like this:

```python
def __getattr__(name) -> Any: ...
```

**Comment by wmdrichards** [comment]
Ah thanks -- googling for partial stubs leads [here](https://www.python.org/dev/peps/pep-0561/#partial-stub-packages), which is a bit less helpful in this case. That gets around most of the issues, though I still believe that an opaque type (basically the same as an Any, but only compatible with itself) would be useful, since properly stubbing out the class is tedious.

**Comment by hauntsaninja** [comment]
mypy isn't going to support this. E.g. consider `from tensorflow import Tensor`, where mypy has no way of knowing what kind of thing `Tensor` is.
