### ISSUE TITLE
`can_be_true` and `can_be_false` should be properties

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#11196]
Right now they are defined as:

```python
        self.items = items
        self.can_be_true = len(self.items) > 0
        self.can_be_false = len(self.items) == 0
```

But, I can see a potential inconsistency here. Since `items` is writable and mutable (`list`), someone (let's say in a plugin) can add an item to `Tuple`, `Union`, or `TypedDict` without updating `can_be_true` and `can_be_false` attributes.

But, `@property`s are dynamically computed, so it will always produce the correct result.
It is also used not-to-often, so it should not slow down the whole program.

I will send a PR with the proposed changes.

**Comment by sobolevn** [comment]
After https://github.com/python/mypy/pull/11197

**Comment by joaopedro-s** [comment]
Hi, 
I'm new to the mypy and was looking for open issues to do my first contribution, and when analyzing this one, both "can_be_true" and "can_be_false" are properties in types.py, probably been solved in a previous pull request, so this issue could be consider to be closed.

**Comment by hauntsaninja** [comment]
Thanks! They're properties but I think that's just for lazy init. Either way, I don't see the code Nikita is referencing on master. There's something like it in TypedDictType, where if we're worried about mutability we could type TypedDictType.items as Mapping instead of dict
