### ISSUE TITLE
Unable to debug an INTERNAL ERROR Message

### ISSUE THREAD

**Issue by rmagier1** [python/mypy#11209]
**Crash Report**

Currently getting an internal error but not sure where it originated from as the line it is complaining about is `-1` and the traceback doesn't give me anything to go off of. Any help on how to find the source of the problem is appreciated. How can I get a better traceback?

**Traceback**

```
$ mypy --show-traceback app/views/error.py
/app/quality_and_revenue/models/posting.py:-1: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "mypy/semanal.py", line 4872, in accept
  File "mypy/nodes.py", line 687, in accept
  File "mypy/semanal.py", line 577, in visit_func_def
  File "mypy/semanal.py", line 609, in analyze_func_def
  File "mypy/semanal.py", line 4583, in defer
AssertionError: Must not defer during final iteration
/app/quality_and_revenue/models/posting.py:-1: : note: use --pdb to drop into pdb
```

**Your Environment**

- Mypy version used: mypy 0.910
- Python version used: Python 3.8.12

**Comment by hauntsaninja** [comment]
Thanks for the report! mypy crashing is never your fault. I've seen some crashes like this in cases with import cycles where some imported name doesn't exist (e.g. #11064)

**Comment by AlexWaygood** [comment]
I'm going to close this as:

- There's no reproducible example
- There are many other issues where this assertion is hit:
  - https://github.com/python/mypy/issues/12113
  - https://github.com/python/mypy/issues/10140
  - https://github.com/python/mypy/issues/11728
  - https://github.com/python/mypy/issues/12112

If you're able to provide a minimal, reproducible example that's different to all of the above, I will happily reopen the issue! 🙂
