### ISSUE TITLE
TypeGuard doesn't work on overloads

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#11219]
When an option in an overload is a TypeGuard the object doesn't get narrowed.
```py
from typing import TypeGuard, overload

@overload
def guard(obj: int) -> TypeGuard[bool]: ...
@overload
def guard(obj: object) -> bool: ...
def guard(obj: object) -> bool: ...


x: int

if guard(x):
    reveal_type(x)  #  note: Revealed type is "builtins.int" 
```

```
>mypy -V
mypy 0.920+dev.febec7123c839fce87815dbe847266596f985d72
```

**Comment by erictraut** [comment]
I wouldn't expect this to work because of [the way that overloads are applied](https://mypy.readthedocs.io/en/stable/more_types.html#type-checking-calls-to-overloads). 

Can you explain the use case for this?

**Comment by KotlinIsland** [comment]
user case:
```py
@overload
def isCertainFunction(obj: Callable[P, R]) -> TypeGuard[CertainFunction[P, R]]: ...
@overload
def isCertainFunction(obj: object) -> bool: ... # don't type guard here because you don't know the fn signature
```

**Comment by erictraut** [comment]
I don't understand why you need an overload. If you want to be able to pass any callable to the type guard function, this should suffice:

```python
def isCertainFunction(obj: Callable[P, R]) -> TypeGuard[CertainFunction[P, R]]:
    ...
```

If you want to be able to pass any callable or any other non-callable, then you can use:

```python
def isCertainFunction(obj: Callable[P, R] | object) -> TypeGuard[CertainFunction[P, R]]:
    ...
```

**Comment by KotlinIsland** [comment]
```py
from typing import TypeGuard, overload, Callable, ParamSpec, Any

P = ParamSpec("P")


def guard(obj: Callable[P, Any] | object) -> TypeGuard[Callable[P, bool]]:
    ...

f1: object

if guard(f1):
    reveal_type(f1)  # I would expect that sometimes this code is executed, but I don't know what the P of f1 is
    # note: Revealed type is "def (*Any, **Any) -> builtins.bool"

f2: Callable[[int], int]

if guard(f2):
    reveal_type(f2)  # I want (int) -> bool
    # note: Revealed type is "def (*Any, **Any) -> builtins.bool"
```

That doesn't really work for what I want, it guards it when I don't want it and it converts `P` into icky `Any`

**Comment by KotlinIsland** [comment]
I don't understand what you mean by "the way that overloads are applied" it looks to me like if the static type is known to match the typeguard branch of the overload then the type can be safety narrowed.

**Comment by erictraut** [comment]
Mypy (like other Python type checkers) does not pick a single overload to apply to a call expression. It expands unions of input parameters and applies overloads independently for each combination, then unions all of the results. I would expect the fact that one of the overloads happens to return a TypeGuard would be lost in that process. That's the case in pyright, and it's likely what's happening in mypy as well.

I'm the author of PEP 647, and it was not my intent to support overloaded functions as user-defined type guards. I realize that's not spelled out in the PEP. Perhaps it should be amended to include this clarification.

**Comment by KotlinIsland** [comment]
So how am I supposed to type my function?

**Comment by erictraut** [comment]
I don't understand enough of your scenario to offer other suggestions than the one above. It sounds like you don't like that solution because of "an icky `Any`". I'm not sure why that's objectionable to you, but if it is, then you'll need to find a different solution.

How would you have typed this function prior to the existence of TypeGuard?

**Comment by KotlinIsland** [comment]
The actual real use case is that I'm trying to type asyncio.coroutine.iscoroutinefunction, and what I've got that I think would work is:

If your function type is known then I would think it's okay to narrow it, otherwise just do bool
```py
@overload
def iscoroutinefunction(func: Callable[_P, _R]) -> TypeGuard[Callable[_P, Coroutine[None, None, _R]]]: ...
@overload
def iscoroutinefunction(func: object) -> bool: ...
```

**Comment by erictraut** [comment]
I see. Yeah, I think my suggestion above works fine in this case.

```python
def iscoroutinefunction(
    func: Callable[_P, _R] | object
) -> TypeGuard[Callable[_P, Coroutine[None, None, _R]]]:
    ...
```

If the signature of the call isn't known, it will be narrowed to `Callable[..., Coroutine[None, None, Any]]`. IMO, that's better than not narrowing it because you can then at least call it.

```python
async def func(o: object):
    if iscoroutinefunction(o):
        await o()
```

If it's not narrowed at all, this code would generate a type error.

**Comment by KotlinIsland** [comment]
```py
def iscoroutinefunction(
        func: Callable[_P, _R] | object
) -> TypeGuard[Callable[_P, Coroutine[None, None, _R]]]:
    ...


f1: object

if iscoroutinefunction(f1):
    reveal_type(f1)
    f1()
    # note: Revealed type is "def (*Any, **Any) -> typing.Coroutine[None, None, _R`-2]"
f2: Callable[[int], str]

if iscoroutinefunction(f2):
    f2()
    reveal_type(f2)
    # note: Revealed type is "def (*Any, **Any) -> typing.Coroutine[None, None, _R`-2]"
```

This didn't generate any type errors.

**Comment by KotlinIsland** [comment]
is that a limitation of mypy?

**Comment by KotlinIsland** [comment]
pyright is a little better but still not perfect
```py
from typing import Callable, Coroutine, TypeVar
from typing_extensions import ParamSpec, TypeGuard

_P = ParamSpec("_P")
_R = TypeVar("_R")

def iscoroutinefunction(
        func: Callable[_P, _R] | object
) -> TypeGuard[Callable[_P, Coroutine[None, None, _R]]]:
    ...

f1: object

if iscoroutinefunction(f1):
    a = f1(1) # error 
    c = f1() # no error
    reveal_type(f1)
    # "Callable[_P@iscoroutinefunction, Coroutine[None, None, _R@iscoroutinefunction]]"
```

**Comment by KotlinIsland** [comment]
Thanks for the help @erictraut
