### ISSUE TITLE
stubgen remove quotes in an argument definition that has a literal type

### ISSUE THREAD

**Issue by sami-evangelista** [python/mypy#11222]
With the following `test.py` file:
```python
import typing
def test(x: typing.Literal['abc', 'def']) -> int:
    ...
```
stubgen removes the quotes around `abc` in the output `pyi` file:
```
$ stubgen test.py
Processed 1 modules
Generated out/test.pyi

$ cat out/test.pyi 
import typing

def test(x: typing.Literal[abc, 'def']) -> int: ...
```
mypy version:
```
$ mypy -V
mypy 0.920+dev.bbea3b56297d3d966b9a98900c218df6616fec85
```

**Comment by sobolevn** [comment]
This also happens for this code:

```python
import typing
def test(x: typing.Literal['sys']) -> int:
    ...
```

**Comment by Bracciata** [comment]
I am going to try to tackle this now!

**Comment by 0x000A** [comment]
I'd like to give it a shot if possible

**Comment by JelleZijlstra** [comment]
@0x000A go ahead!

**Comment by 0x000A** [comment]
`typing.Literal['abc', 'def']` is represented as the following:
```
UnboundType(
   name = 'typing.Literal'
   args = [
       UnboundType(name='abc'),
       RawExpressionType(value='def')
   ]
)
```
is this the right representation?

**Comment by Infinil** [comment]
is the issue still open? If yes I want to try it (I am pretty new to open source contribution)

**Comment by sobolevn** [comment]
@Infinil there's a PR for this already: https://github.com/python/mypy/pull/11292

Feel free to choose any other issue. If you need help, just ping me and ask your question. I will try to help 🙂

**Comment by Infinil** [comment]
@sobolevn 
I made 2 commits a while ago but I was quite confused by test cases etc so I didnt add any 😥

**Comment by sobolevn** [comment]
@Infinil which commits? Can you please provide a link?

**Comment by Infinil** [comment]
@sobolevn
This is the link of pull request : https://github.com/python/mypy/pull/11476

Btw I am checking "good first issues" and I will be honest till now all I could do was solve a typo in docs .. I do have my basics of Python cleared but I think that's definitely not enough.. any tips on how to start understanding these issues ? Btw is it fine to ask for discord tag here 😅 [for communication purposes]

**Comment by JelleZijlstra** [comment]
Hi @Infinil, mypy is unfortunately not the easiest codebase to get started with; I have somehow become a maintainer and much of the codebase is a mystery to me too (which is part of why I don't merge that many PRs).

I'd recommend starting out with a simpler subsystem like stubgen, or perhaps try to make some contributions to typeshed (https://github.com/python/typeshed), which tends to be a bit simpler.

I am on the #type-hinting channel on PyDis (https://www.pythondiscord.com/). A few of us also use Gitter at https://gitter.im/python/typing.
