### ISSUE TITLE
Specifying to ignore python module in configuration file

### ISSUE THREAD

**Issue by james-riley678** [python/mypy#11239]
**mypy version 0.910 is being used along with Python 3.7**

I am importing the python module azure-storage-blob in my code. When using mypy it comes up with the following errors:

```
/virtualenvs/src-foikFr8K/lib/python3.7/site-packages/azure/storage/blob/_serialize.py:129: error: Type signature has too many arguments
/virtualenvs/src-foikFr8K/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py:1406: error: Type signature has too few arguments
```

This fails on the line when I do this import

`from azure.storage.blob import BlobServiceClient, BlobClient`

Obviously I cannot change the code for this package so I need to specify in the config file to ignore it.

However, whatever I put in, it doesn't seem to ignore it:

```
[mypy-azure-storage-blob]
ignore_errors = True
```

Any ideas?

**Comment by sobolevn** [comment]
@james-riley678 Two things here.
1. Looks like `azure` is a 3rd party library. You can change how you treat your imports. Try this:

```ini
[mypy]
follow_imports = silent
```

Example: https://github.com/dry-python/returns/blob/master/setup.cfg#L178

2. I am pretty certain that this is not how this should be fixed, but. It looks like you are using `-` notation in module ignores. I am not sure that it works. Try this:

```ini
[mypy-azure.storage.blob]  # or azure.storage.blob.*
ignore_errors = True
```

Example: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/setup.cfg#L129

**Comment by hauntsaninja** [comment]
I'd recommend not changing your global follow_imports setting, since that will affect all your imports, not just the azure one. Maybe try a combination of the two things Nikita suggested:
```
[mypy-azure.storage.blob.*]
follow_imports = skip
```

**Comment by jayqi** [comment]
This actually seems like a different bug than described, and the suggested fixes of setting `follow_imports` should not be necessary. 

By default, it appears that mypy is supposed to ignore errors from modules in `site-packages`. This is controlled by the setting [`no_silence_site_packages`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-no_silence_site_packages). I am seeing the same errors (as do other people based on https://github.com/Azure/azure-sdk-for-python/issues/20771), both when leaving `no_silence_site_packages` and when explicitly setting it to `False` in my `[mypy]` configuration. For some reason, this setting is not working for silencing these errors.

- mypy v0.910
