### ISSUE TITLE
Python 3.10 and Match statements: fastparse.py AttributeError: 'ASTConverter' object has no attribute 'visit_Match

### ISSUE THREAD

**Issue by joe-narvaez** [python/mypy#11251]
**Crash Report**

(Tell us what happened.)

**Traceback**

```
fastparse.py", line 327, in visit
    visitor = getattr(self, method)
AttributeError: 'ASTConverter' object has no attribute 'visit_Match'
```

**To Reproduce**
I wrote a match statement
```python
def setup_logger() -> None:
    level = config.log_level.upper()
    match level:
        case "ERROR" | "WARN" | "INFO" | "DEBUG":
            pass
        case _:
            raise ValueError("Logger only accepts ERROR, WARN, INFO, and DEBUG levels")
    logging.basicConfig(format="%(levelname)s: %(message)s", level=level)

```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags:  --install-types --non-interactive
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10
- Operating system and version: Linux

**Comment by JelleZijlstra** [comment]
We don't support match yet. #10191 is trying to fix that.

**Comment by JelleZijlstra** [comment]
#10191 just landed.
