### ISSUE TITLE
`functools.partial` assignment is ignored if a different type is used in a different branch

### ISSUE THREAD

**Issue by jwodder** [python/mypy#11269]
Consider the following code:

```python
from functools import partial
from typing import Any, Callable, Union

yesno = True

thingy: Union[Callable, int]
reveal_type(thingy)
if yesno:
    thingy = partial(isinstance, "foo")
    reveal_type(thingy)
else:
    thingy = 42
reveal_type(thingy)
```

Running `mypy` on this produces the output:

```
partial01.py:7: note: Revealed type is "Union[def (*Any, **Any) -> Any, builtins.int]"
partial01.py:10: note: Revealed type is "<nothing>"
partial01.py:13: note: Revealed type is "builtins.int"
```

Observe that mypy thinks that `thingy` can only be an `int` after the `if`-block is executed, despite one branch assigning it a `functools.partial`.  This happens regardless of the value of `yesno`, whether the `partial` assignment block comes before or after the `int` assignment block, and whether `yesno` is assigned a value or used as a parameter in a function containing the above code.

**Your Environment**

- Mypy version used: both 0.910 and mypy 0.920+dev.82f767a3d7bc675be4b32ffab527d14b4abbf8a4
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.9.7
- Operating system and version: macOS 11.6

**Comment by hi-ogawa** [comment]
The issue might not be due to branching.
Here I made a simpler example with just an assignment of `partial` into `Callable` and this already exhibits `<nothing>` type (aka UninhabitedType).

```py
from functools import partial
from typing import Callable

def f(x: str) -> str:
    return x

g: Callable
g = partial(f, "foo")
reveal_type(g)  # Revealed type is "<nothing>"
```

I'm guessing the union of `<nothing>` and `int` simply becomes `int` and that the behaviour seen in the OP's example.

**Comment by hauntsaninja** [comment]
This looks fixed on latest master
