### ISSUE TITLE
`None` alias for `NoneType` doesn't work on generic bound when using `type` of the generic

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11275]
```py
from typing import TypeVar
from types import NoneType

T = TypeVar("T", bound=None)
def foo(value: type[T]) -> None: ...

U = TypeVar("U", bound=NoneType)
def bar(value: type[U]) -> None: ...

foo(NoneType) #error: Value of type variable "T" of "foo" cannot be "NoneType"
bar(NoneType) #no error
```
https://mypy-play.net/?mypy=latest&python=3.10&gist=ce1d20fa9232f609b36053e10a117a8b

**Comment by KotlinIsland** [comment]
```py
from typing import TypeVar, Generic
from types import NoneType

T = TypeVar("T", bound=None)
def foo(a: T, b: type[T]) -> None: ...

U = TypeVar("U", bound=NoneType)
def bar(a: U, b: type[U]) -> None: ...

foo(None, NoneType) #Value of type variable "T" of "foo" cannot be "Optional[NoneType]"
bar(None, NoneType) #Value of type variable "U" of "bar" cannot be "Optional[NoneType]"
```
This is absolute whack

**Comment by KotlinIsland** [comment]
I think this might be related to the fact that the stubs define `NoneType` as a subtype of the type of `None`

**Comment by KotlinIsland** [comment]
wait, not it's not, it's completely unrelated to `None`
```py
@final
class NoneType:
    def __bool__(self) -> Literal[False]: ...
    ```
LOOOOOOL!!

**Comment by erictraut** [comment]
I wouldn't expect this to work. The `types.NoneType` symbol has no type relationship to `builtins.None`, just as `types.UnionType` has no type relationship to `typing.Union`. If you want to refer to the type of the object `builtins.None`, you can use the expression `type(None)`.

**Comment by KotlinIsland** [comment]
at runtime `NoneType is type(None)` but `typing.Union` and `types.UnionType` are completely different constructs.

**Comment by erictraut** [comment]
```python
from typing import TypeVar

T = TypeVar("T", bound=None)

def foo(value: type[T]) -> None:
    ...

U = TypeVar("U", bound=type[None])

def bar(value: type[U]) -> None:
    ...

foo(type(None))
bar(type(None)) # Error
```

**Comment by KotlinIsland** [comment]
`type[None]`, that's a good one :)

**Comment by KotlinIsland** [comment]
What a mess lmao.

in a type context, `None` really means `type[None]`(the value None, not the type). So when you say `type[None]` I think in the type realm it is `type[type[None]]`.

**Comment by JelleZijlstra** [comment]
`NoneType` should never be used in types. I'd welcome PRs improving documentation for this.

The original example doesn't make much sense to me: None cannot be subclassed, so bounding on None or NoneType isn't useful.

**Comment by KotlinIsland** [comment]
https://github.com/python/typeshed/pull/6125
