### ISSUE TITLE
return type of `sorted` incorrectly widened to `list[object]` when sorting a union of lists

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11271]
```py
class Foo: ...

class Bar: ...
    

foo: list[Foo] | list[Bar] = [Foo()]

# error: Incompatible types in assignment (expression has type "List[object]", variable has type "Union[List[Foo], List[Bar]]")
bar: list[Foo] | list[Bar] = sorted(foo)
```
https://mypy-play.net/?mypy=latest&python=3.10&gist=3ac599a876ba17132ebbd315e71333f4

**Comment by erictraut** [comment]
The problem is that `sorted` requires a type that supports `__lt__`, but `Foo` and `Bar` don't define this operator.

If you add the following method to `Foo` and `Bar`, it will type check without error.

```python
    def __lt__(self, val: object) -> bool: ...
```
