### ISSUE TITLE
(🎁) Warn when `NoneType` is used in a type

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#11288]
`NoneType` is a mangled up mess in the type realm and should never be used in a typing context.

With the special case of `None` being a secret alias to `NoneType` I think that many, many people are going to try to use `NoneType` as an annotation. Adding a warning for the 99% of the time that it's invalidly used would be a great one.

I understand that there are always edge cases, and disabling those warnings with a type comment would be the way to go IMO. 

```py
from types import NoneType

def foo(a: NoneType):  # sus alert, NoneType is a mess in the type realm, you should use `None` or `type[None]` instead.
    print(isinstance(a, NoneType))
```

**Comment by JukkaL** [comment]
Some more context from the duplicate issue #13139 below.

Hints:
* Fix this in `mypy.typeanal`
* Currently `types.NoneType` is treated as an `mypy.types.Instance` type but `None` is mapped to `mypy.types.NoneType`
* If we'd create an `Instance` with `fullname` equal to `types.NoneType`, generate an error

Example illustrating the problem:
```
from types import NoneType

def f(x: NoneType) -> None:
    pass

f(None)   # Incompatible type None, expected NoneType
```

**Comment by KotlinIsland** [comment]
@JukkaL I have partially improved this case in basedmypy.

basedmypy:
```py
from types import NoneType

def foo(n: NoneType):  # error: Variable "types.NoneType" is not valid as a type
    print("hi")

nt: type[None] = NoneType  # no error
```

just by simply making `NoneType` an alias instead of a class def. It's not perfect, but I think it's a big improvement.

https://github.com/KotlinIsland/basedmypy/commit/f424a34b4fe774d920a744ca2fc981264958a0b5

**Comment by kevinsullivan** [comment]
The name itself is terrible. NoneType is not an, Empty type. It's Unit, for goodness sake. Use Unit. Deprecate None. Then phase it out.

**Comment by wyattscarpenter** [comment]
@kevinsullivan NoneType is the type containing only the value None. So, I think it's a fairly good name for the type, given that we already have None, that wacky absence-indicator value that Python programmers love using. (Not to be confused with `None` by itself in a type annotation, which means NoneType.) While it is *a* unit type (it has only one value), it's not the only possible unit type, so I think Unit would be a worse name for it. That also wouldn't suggest anything about how it's used to indicate absence. Anyway, the empty type in Python is called [Never](https://typing.python.org/en/latest/spec/special-types.html#never) ([typing.Never](https://docs.python.org/3/library/typing.html#typing.Never)); I hope that helps you if you were looking for it!
