### ISSUE TITLE
Type aliases to PEP 604 unions do not work, saying it's not valid as type

### ISSUE THREAD

**Issue by AMDmi3** [python/mypy#11280]
**Bug Report**

When I create a type alias to PEP604-style union type, mypy complains that it's "not valid as a type".

**To Reproduce**

```python
MyType = str | None
myvar: MyType
```
```shell
mypy 1.py
```

**Expected Behavior**

No errors, the same output as for:

```python
from typing import Optional
MyType = Optional[str]
myvar: MyType
```

**Actual Behavior**

```
1.py:2: error: Variable "1.MyType" is not valid as a type
1.py:2: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10
- Operating system and version: FreeBSD 13.0

**Comment by JelleZijlstra** [comment]
#10770
