### ISSUE TITLE
Move test code out of mypy package

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1129]
Having the tests in a subpackage of mypy causes unwanted hits when grepping for e.g. call sites or error messages. (Spun off #1074.)

**Comment by ddfisher** [comment]
This is going to cause merge conflicts for any outstanding diffs that make test modifications.  We should figure out a good time to do this.

**Comment by gvanrossum** [comment]
I don't have any -- do you?

--Guido (mobile)

**Comment by ddfisher** [comment]
Oh.  I thought incremental typing might.  I have the bare Callable PR I just put up, but it's small.

**Comment by gvanrossum** [comment]
Nope, not yet...

--Guido (mobile)

**Comment by gvanrossum** [comment]
I don't consider this urgent.

**Comment by elazarg** [comment]
Moving the non-DDTs to pytest may be such an opportunity. I think that doing it without massive churn (i.e. countless removals of `self.fixture`) requires awkward jumping through hoops and ad-hoc magic, in addition to the pytest magic involved.

**Comment by JukkaL** [comment]
Closing as there hasn't been any recent activity.
