### ISSUE TITLE
mypy does not support PEP 612 -- Parameter Specification Variables (python 3.10)

### ISSUE THREAD

**Issue by rvaquerizor** [python/mypy#11295]
**Bug Report**

mypy does not support python 3.10 PEP 612 - Parameter Specification Variables

**To Reproduce**

1. Create a python module with the content:

```
from typing import Callable, TypeVar, ParamSpec


T = TypeVar('T')
R = tuple[T, float]
P = ParamSpec('P')


def decorator_block(func: Callable[P, T]) -> Callable[P, R]:
    """
    Decorator.
    """
    def wrapper(*args, **kwargs) -> R:
        result = func(*args, **kwargs)
        return result, 0.1
    return wrapper
```

2. Execute mypy on the file just created above.

**Expected Behavior**

No complains from mypy. All new features in python 3.10 should be supported.

**Actual Behavior**

mypy complains whenever I use Param Spec variables with the following message:

`new_file.py:9: error: The first argument to Callable must be a list of types or "..."
`

**My Environment**

- Mypy version used: 0.812
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): dependencies: mypy-extensions >=0.4.3,<0.5.0, typed-ast >=1.4.0,<1.5.0, typing-extensions >=3.7.4
- Python version used: 3.10
- Operating system and version: Ubuntu 5.11.0-37-generic #41-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

__

**Comment by JelleZijlstra** [comment]
#8645

**Comment by JelleZijlstra** [comment]
Also, 0.812 is quite old. There is some (very) rudimentary support for ParamSpec in newer releases I believe.
