### ISSUE TITLE
Improved hinting / warning diagnostics where parameter named `self` is missing on instance method

### ISSUE THREAD

**Issue by shoffmeister** [python/mypy#11309]
The code below is faulty - mypy correctly emits an error "Too many arguments for "set_log_level"":
```python
class LoggableDB:
    def set_log_level(v):
        print(type(v).__name__)

LoggableDB().set_log_level("i am not myself")
```

**Pitch**

With the code being faulty, it needs to be fixed by a developer. 

The most ergonomic approach is telling the developer about a most likely fix. Therefore, it would be helpful to enrich the output with a _nudging_ diagnostic (hint, warning) to the effect of "\<method\> is missing a parameter named self as the first parameter" would be appreciated.

I believe that having this diagnostic would reduce mental effort and accelerate development, by allowing a developer to merely read, without having to spend too many brain cycles.

Additionally, the added nudge would be _at the location of the real problem_ (missing `self`) as opposed to being only at the call site. Depending on the distance between definition and caller, that additional nudge might accelerate the fix.

This nudging hint would be valuable both during interactive use (in an editor) and in batch mode (CI).

Hiding this nudge behind a config switch would alleviate any challenges where developer have not followed / do not want to follow the convention of naming that first parameter `self`

**Comment by hauntsaninja** [comment]
Thanks, yeah, I agree that it'd be nice to point out the missing `self`. Want to take a shot at implementing it? :-)

**Comment by shoffmeister** [comment]
Many thanks for the invitation :)

My plate is quite overloaded already, and I'd have to become proficient in Python typing and mypy implementation before even thinking about contributing to implementation of mypy. Perhaps in a year or so, depending on much free lunch Python typing I get to eat elsewhere?

**Comment by hauntsaninja** [comment]
Yep, agreed, I meant the second approach :-)

**Comment by sobolevn** [comment]
Looks like we've fixed a bunch of bugs.

- Now `self` is shown in incompatible method definition:

```
 _____________________ testAbstractClassWithAllDynamicTypes _____________________
 Expected:
  main:10: error: Signature of "g" incompatible with supertype "I"
  main:10: note:      Superclass:
  main:10: note:          def g(x: Any) -> Any  (diff)
  main:10: note:      Subclass:
  main:10: note:          def g(self, x: Any, y: Any) -> None
Actual:
  main:10: error: Signature of "g" incompatible with supertype "I"
  main:10: note:      Superclass:
  main:10: note:          def g(self, x: Any) -> Any (diff)
  main:10: note:      Subclass:
  main:10: note:          def g(self, x: Any, y: Any) -> None
```

- `CallableType` was accessing `.arguments` that can be deleted from `FuncDef`: `________________________ testDisallowAnyExprIncremental ________________________` showed it
