### ISSUE TITLE
`Callable` doesn't work with `self` type

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11382]
version: 0.920+dev.76a7542e790561038b18e65e35054ef4ed671fa6
```py
from __future__ import annotations

from typing import Callable


class Foo:
    bar: Callable[[Foo, bool], None]


foo = Foo()

# Too few arguments  [call-arg]
# Argument 1 has incompatible type "bool"; expected "Foo"  [arg-type]
foo.bar(True)
```
this worked in 0.910 https://mypy-play.net/?mypy=latest&python=3.10&flags=strict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-defs%2Cno-strict-optional%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=588ce19b73c0a1c76c36d453330b565c

**Comment by AlexWaygood** [comment]
The original example is [no longer reproducible](https://mypy-play.net/?mypy=latest&python=3.10&gist=17f47495b026df4678e317c123969edb) on 0.941

**Comment by KotlinIsland** [comment]
This never made it to 0.920 release

**Comment by AlexWaygood** [comment]
> This never made it to 0.920 release

Correct
