### ISSUE TITLE
allow `...` in place of generic parameters

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11389]
**Feature**
in kotlin, you can omit a generic from a type annotation when you don't care what its value is:
```kotlin
class Foo<T: Number>

fun foo(value: Foo<*>) {}
```

more info: https://typealias.com/guides/star-projections-and-how-they-work/

in python, to do the same thing you need to use `Any`, which is gross:
```py
from typing import Any, Generic, TypeVar

T = TypeVar("T", bound=int | str)


class Foo(Generic[T]):
    ...


def foo(value: Foo[Any]) -> None:
    ...
```
or simply duplicate the bound, which isn't convenient:
```py
def foo(value: Foo[int | str]) -> None:
    ...
```

**Pitch**

it's especially useful for types that have multiple bounded generics

i think this could be accomplished by simply allowing `...` to be used in place of the generics
```py
Thing1 = TypeVar("Thing1", bound=Base1)
Thing2 = TypeVar("Thing2", bound=Base2)
Thing3 = TypeVar("Thing3", bound=Base3)


class ThingWithLotsOfGenerics(Generic[Thing1, Thing2, Thing3]):
    ...


def foo(value: ThingWithLotsOfGenerics[..., ..., ...]) -> None:
    ...
```

**Comment by AlexWaygood** [comment]
> This discussion is probably better suited to the typing-sig rather than the mypy issue tracker, since a change like this would need to be standardized as part of the language.

I agree with @erictraut. Feature requests for the typing system as a whole should be discussed in the https://github.com/python/typing repo or the [typing-sig mailing list](https://github.com/python/typing).

Since this feature request doesn't really belong in this issue tracker, I'm closing this issue.
