### ISSUE TITLE
`int` allowed in places expecting `float`

### ISSUE THREAD

**Issue by cristicbz** [python/mypy#11385]
**Bug Report**

Mypy seems to treat `int` as a subtype of `float` even though python doesn't think so and in some cases they are not interchangeable. We hit this multiple times: with FFI, using some strict runtime type assertions, and comparing json output of "equal" inputs where the inputs differed in float-ness and therefore the strings ended up having `.0` only some of the time.

While I understand why, in some less-strict codebases this may be desireable, it would be good to at least be able to opt out of this.

**To Reproduce**

```python
def foo(x: float) -> None:
    assert isinstance(x, float)

foo(10) 
```

**Expected Behavior**

`mypy` rejects the call to `foo` in the example

**Actual Behavior**

`mypy` accepts the call to `foo` in the example, but the program fails at runtime.

**Your Environment**

- Mypy version used: mypy==0.910
- Mypy command-line flags: `mypy example.py`
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]
exclude=.*_pb2[.]py
check_untyped_defs=True
disallow_any_generics=True
disallow_incomplete_defs=True
disallow_subclassing_any=True
disallow_untyped_defs=True
ignore_missing_imports=True
no_implicit_optional=True
strict_optional=True
warn_return_any=True
warn_unused_ignores=True
plugins = pydantic.mypy

[pydantic-mypy]
init_typed = True
```
- Python version used: 3.8.10
- Operating system and version: Ubuntu 20.04

**Comment by dpinol** [comment]
Though the standard says `when an argument is annotated as having type float, an argument of type int is acceptable`, it is not true in practice.

What's the argument for not having an opt-in check for these kind of errors?

```
a=2
f"{a:.3}"
ValueError: Precision not allowed in integer format specifier

```
