### ISSUE TITLE
overly permissive parsing: f(yield) should be syntax error

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1138]
mypy incorrectly parses this program with no errors:

``` python
from typing import Generator

def g() -> Generator[None, int, None]:
    f(yield)

def f(x: int) -> None:
    print(x)
```

However, `f(yield)` is not valid Python syntax.  It needs another set of parens, i.e. `f((yield))`.

**Comment by ddfisher** [comment]
This should be fixed by the new parser.

**Comment by gvanrossum** [comment]
I'm going to close this as a won't fix because the new parser will solve this and we're not going to put any work in the old parser/lexer.
