### ISSUE TITLE
`x and bool` interpreted as `Union[type(x), bool]`  instead of `bool`.

### ISSUE THREAD

**Issue by paw-lu** [python/mypy#11410]
**Bug Report**

**To Reproduce**

```python
"""bar.py"""

def foo(x: str) -> bool:
    return x and x != "0"
```

```sh
% mypy bar.py
bar.py:4: error: Incompatible return value type (got "Union[str, bool]", expected "bool")
Found 1 error in 1 file (checked 1 source file)
```

**Expected Behavior**

I expected mypy to recognize that the string will always be casted to bool here (I think!).

**Actual Behavior**

mypy treats `x and x != "0"` as `Union[str, bool]` instead of `bool`. I don't think `x and x != "0"` can ever be `str`.

**Your Environment**

- Mypy version used: mypy 0.910
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.9.5
- Operating system and version: macOS 11.6

**Comment by paw-lu** [comment]
For the record—and if anyone comes across this—the "solution" for now is simple—just explicity cast the non-boolean variable to bool.

```python
""bar.py"""

def foo(x: str) -> bool:
    return bool(x) and x != "0"
```

**Comment by erictraut** [comment]
I think mypy is correct here. Try running this code:

```python
def foo(x: str) -> bool:
    return x and x != "0"

x = foo("")
print(type(x))  # <class 'str'>
```

**Comment by paw-lu** [comment]
Yep! mypy (and @erictraut) are correct. Good example there. Closing.
Sorry for the issue nosise!

---

Any explanation for why this happends? This was unexpected for me

**Comment by JelleZijlstra** [comment]
> Any explanation for why this happends? This was unexpected for me

The `and` operator returns its first operand when it is falsy.
