### ISSUE TITLE
mypy ReadTheDocs build is failing

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#11412]
See https://readthedocs.org/projects/mypy/builds/

It looks like this is related to https://github.com/sphinx-doc/sphinx/issues/9777 , in which case the quickest resolution is probably just pinning some package versions.

However, it looks like the ReadTheDocs build its own instructions that are unrelated to `tox -e docs` / the versions specified in the mypy repo. I'm not really familiar with RTD — where are its build steps coming from and who has permission to change it?

**Comment by astrojuanlu** [comment]
MyPy could add a `.readthedocs.yaml` file to tell Read the Docs to use https://github.com/python/mypy/blob/master/docs/requirements-docs.txt, see https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-952034858

**Comment by hauntsaninja** [comment]
Thanks astrojuanlu and sobolevn!!!

**Comment by hauntsaninja** [comment]
[![hooray](https://readthedocs.org/projects/mypy/badge/?version=latest)](https://mypy.readthedocs.io/en/latest/?badge=latest) Hooray!
