### ISSUE TITLE
Readthedocs failures

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#11421]
Lately I've been getting a fair number of emails from readthedocs indicating a docs build failure. I have lost the skill to figure out how to unsubscribe from these, and I'm not sure if anyone else is getting them. The most recent one I got links here: https://readthedocs.org/projects/mypy/builds/15139657/

**Comment by sobolevn** [comment]
Looks like it is fixed now by https://github.com/python/mypy/pull/11419

Latest build at the moment: https://readthedocs.org/projects/mypy/builds/15143406/

**Comment by hauntsaninja** [comment]
I think you and possibly Jukka are the only people who get these. The good news is we were able to fix without needing admin access to RTD! (see #11412 and #11419)

**Comment by gvanrossum** [comment]
Indeed, currently it's just Jukka and me. If any of you create an account on RtD and tell me the username here (apparently it's not tied to GitHub), I'll give you admin permissions.

**Comment by hauntsaninja** [comment]
My RTD username is hauntsaninja, thank you!

**Comment by gvanrossum** [comment]
> My RTD username is hauntsaninja, thank you!

Added!
