### ISSUE TITLE
new union syntax doesn't work on `Literal`s

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11426]
```py
from __future__ import annotations

from typing import Literal

Foo = Literal[1, 2]

Bar = Foo | Literal[3] # error: Unsupported left operand type for | ("object")
```
https://mypy-play.net/?mypy=latest&python=3.10&gist=3a429dfa3e9e3b692aac25887027ab69

**Comment by sobolevn** [comment]
This also happens without `__future__` import:

```python
from typing import Literal

Foo = Literal[1, 2]
Bar = Foo | Literal[3]
# error: Invalid type alias: expression is not a valid type
# error: Unsupported left operand type for | ("object")
```

Will fix it right now, thanks!

**Comment by sobolevn** [comment]
On python3.10 it generates a single error:

```
» mypy out/ex.py --show-traceback
out/ex.py:4: error: Unsupported left operand type for | ("object")
```

**Comment by JelleZijlstra** [comment]
On 3.9 without the import the error is correct since `|` doesn't work at runtime in 3.9. But it should not error in 3.10 or with the future import on, or in stringified annotations.
