### ISSUE TITLE
Errors in '# type: (args) -> type' are attributed to the preceding 'def' line

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1143]
This is minor, but it's a little confusing (especially when you build a web UI on top of it :-) that errors about the `# type` comment form of a signature are attributed to the line before. Found by @ddfisher .

**Comment by ddfisher** [comment]
We should address this after the new parser lands.

**Comment by hauntsaninja** [comment]
Don't know if this is still relevant
