### ISSUE TITLE
Narrow variables when `cast`

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#11441]
**Feature**
Usages of `cast` should narrow a variable
```py
def foo(a: object):
    cast(int, a)
    reveal_type(a)  # expect: int, actual: object
```

**Pitch**
```py
assert isinstance(a, int)
```
I don't like this, why not just narrow on cast?

**Comment by erictraut** [comment]
This isn't how `cast` works. It doesn't change the type of the expression passed as an input. The return type of the cast is modified.

Changing the way `cast` works would break most typed Python code bases. Please don't do this.
