### ISSUE TITLE
calling `dataclass` as a function doesn't work

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11464]
```py
from dataclasses import dataclass


@dataclass
class Foo:
    value: int


foo = Foo(1) # no error


class Bar:
    value: int


Baz = dataclass(Bar)

baz = Baz(1) # Too many arguments for "Bar"  [call-arg]
```
https://mypy-play.net/?mypy=latest&python=3.10&gist=0922fb96d0d8d4953ad33ed7b2e35f2f

**Comment by sobolevn** [comment]
Because we would need a different kind of plugin for this. See `get_dynamic_class_hook()` https://mypy.readthedocs.io/en/stable/extending_mypy.html

**Comment by erictraut** [comment]
the `dataclass` call (somewhat surprisingly) mutates the class that you pass it. It doesn't create a copy of the class and then modify the copy. That means `dataclass(Bar)` actually changes the class `Bar` in the example above. For that reason, I think it's dangerous and ill-advised to use the pattern `Baz = dataclass(Bar)`. You should always use `dataclass` as a class decorator applied directory to the `class` definition. For this reason, I this it's reasonable to say that static type checkers will not support this dangerous pattern.
