### ISSUE TITLE
`Callable`s that don't return `None` should be compatible with `Callable[[<args>], None]`

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#11466]
I think that any function should be assignable to `Callable[<args>, None]` if it's arguments match, it's typesafe and many other languages behave that way.
```py
from typing import Callable

fn: Callable[[int], None] = lambda arg: arg  # currently an error
print(fn(1))  # error, function does not return a value
```

TypeScript:
```ts
const fn: (arg: number) => void = (arg) => arg  // no error
console.log(fn(1))
```

Kotlin:
```kt
val fn: (arg: Int) -> Unit = { it }  // no error
println(fn(1))
```

From https://github.com/python/typing/issues/924 where it was revealed that the `void` nature of `-> None:` is non-standard mypy behaviour.

**Comment by intgr** [comment]
Why do you think that would be correct behavior?

```python
fn: Callable[[int], None] = lambda arg: arg
value: Optional[str] = fn(123)    # value would be int instead
```

A return type of `None` is compatible with `Optional[X]`, but if you erase the **actual** return type as proposed, that would cause unsafety.

Aren't TypeScript and Kotlin wrong here?

**Comment by intgr** [comment]
To clarify:
```ts
const fn: (arg: number) => void = (arg) => arg  // no error
console.log(fn(1))
```

You're calling a function that's supposed to not return anything, and logging the result. But it did return a value, it violated its type signature.

In the case of Kotlin, it looks like some magic is happening that prevents the actual return. Mypy can't affect the function's behavior, however, it's just a type checker.

**Comment by srittau** [comment]
The recommended way to annotated callbacks where the return value is ignored is to use `object` (i.e. Python's "unknown" type) as return type.

**Comment by intgr** [comment]
Ah thanks for clarifying. But there are still cases the return value of a `() -> None` callable might get exposed.

For example it's allowed to assign `() -> None` to a variable/argument with type `() => Optional[X]`:

```python
fn1: Callable[[int], None] = lambda arg: arg
fn2: Callable[[int], Optional[str]] = fn1     # Note this assignment
value: Optional[str] = fn2(123)    # value would be int actually
```

To implement your idea soundly, assignment `fn2` should be disallowed.

**Comment by KotlinIsland** [comment]
> To clarify, per your TypeScript example:
> 
> ```ts
> const fn: (arg: number) => void = (arg) => arg  // no error
> console.log(fn(1))
> ```
> 
> You're calling a function that's supposed to not return anything, and logging the result. But it did return a value, it violated its type signature.


Despite `void` not being the root type, because it is meaningless, anything can be assigned to it.

**Comment by KotlinIsland** [comment]
LOOOOOOOOOOL!

That's how Typescript behaves:
https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZmAjALhgCgB6rAVwLYBGApgE4CUMAvAHwwBuIAlgCZXqMU0yMBQoksBACZUmbPmLkqtaCUZgA5jAA+9Jq0ox4SPuGjcoqWfKWqGLNsLSIhAZjI8ejOOygUA3jy1b+EEABsiADp-EAU0RigggkZwsgcAXx4gA

I need to rethink my life...

**Comment by KotlinIsland** [comment]
```kt
fun bar(): String {
    return "asdf"
}

fun foo(fn: () -> Unit) {
    println(fn())  // Unit
}

fun main() {
    foo(::bar)
}
```

Kotlin does behave like this as well, but under the hood it wraps the function in another function that returns `Unit`.
