### ISSUE TITLE
Implementation annotation not used when using overload

### ISSUE THREAD

**Issue by farmio** [python/mypy#11480]
**Bug Report**

When using `@overload` the annotation of the implementation is not used for checking.

**To Reproduce**

```python
from typing import overload


@overload
def match_max_scale(output_colors: tuple[float, float, float]) -> tuple[int, int, int]:
    ...


@overload
def match_max_scale(
    output_colors: tuple[float, float, float, float]
) -> tuple[int, int, int, int]:
    ...


def match_max_scale(output_colors: tuple[float, ...]) -> tuple[int, ...]:
    """Match the maximum value of the output to the input."""
    max_out = max(output_colors)
    if max_out == 0:
        factor = 0.0
    else:
        factor = 255 / max_out
    return tuple(int(round(i * factor)) for i in output_colors)


three: tuple[int, int, int] = match_max_scale((1, 2, 3))  # OK
four: tuple[int, int, int, int] = match_max_scale((1, 2, 3, 4))  # OK
# Argument 1 to "match_max_scale" has incompatible type "Tuple[int, int, int, int, int]"; expected "Tuple[float, float, float]"
five: tuple[int, ...] = match_max_scale((1, 2, 3, 4, 5))
```
**Expected Behavior**

I'd expect mypy to fall back to the annotation of the implementation if no overloaded annotation fits.

**Actual Behavior**

Mypy fails unless I add
```python
@overload
def match_max_scale(output_colors: tuple[float, ...]) -> tuple[int, ...]:
    ...
```
which just duplicates the implementation funcion header to a overload.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: --strict
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9.1
- Operating system and version: macOS 10.13.6

**Comment by erictraut** [comment]
Mypy's behavior here is consistent with other Python type checkers. The behavior is dictated by PEP 484, which says:

>  The @overload-decorated definitions are for the benefit of the type checker only, since they will be overwritten by the non-@overload-decorated definition, while the latter is used at runtime but should be ignored by a type checker.

**Comment by farmio** [comment]
Aha, thanks, I didn't know that.

I wonder if it should be ok then to omit annotations at all on the implementation without raising
`Function is missing a type annotation  [no-untyped-def]` since they are ignored anyway and could lead to confusion.

**Comment by erictraut** [comment]
The overload signatures are used when evaluating calls of the function. The implementation's annotations are used for type checking the implementation. If you don't care about type checking the implementation, you can omit those annotations.

**Comment by farmio** [comment]
Thank you for your explanation! 👍
