### ISSUE TITLE
Mypy is a waste of time

### ISSUE THREAD

**Issue by irodionzaytsev** [python/mypy#11492]
Mypy is a useless product. Python is a dynamic language. You are wasting yours, and, something I will never forgive you, my time. Please remove this trash from public use. We don't need it. You could do something useful with your programming skills instead making this rubbish. You could make some money, but instead you work for free to create something people don't give a damn about. Get a life.

**Comment by sobolevn** [comment]
Please, don't be rude 🙂 

@JukkaL @hauntsaninja  this probably needs to be deleted.

**Comment by acidjunk** [comment]
For us it flagged a lot of dynamic typing bugs before stuff went to production so it was cost effective.  (usecase: enterprise software).

But we also lost countless hours on weird typing problems and bugs. As an example; right now I am looking into some weird walrus operator behaviour (equivalent code without walrus has no type problems + code with walrus operator complains about trying to access; probably related to https://github.com/python/mypy/issues/7316). We also had quite some extra work, on occasion, when mypy or python was upgraded, in the last couple of years.

I understand that you can be sentimental about code and especially time: but there is no need to be rude (IMHO).

**Comment by enomado** [comment]
Totally agree. Current python syntax and interpreter slows development of python as usable language. 

You should create brand new, back incompatible  Python with scopes, lambdas, const/let, optimization based on types.

**Comment by theLastOfCats** [comment]
> Totally agree. Current python syntax and interpreter slows development of python as usable language.
> 
> You should create brand new, back incompatible Python with scopes, lambdas, const/let, optimization based on types.

You welcome: https://www.rust-lang.org/

**Comment by ambv** [comment]
@irodionzaytsev your attempt at bullying volunteers is not appreciated and is in direct violation of our [Code of Conduct](https://www.python.org/psf/conduct/). Continue on that path and see what happens.

Python is a huge language these days with many users from different backgrounds. Few of them use the entire feature set. It's okay to have features you're not interested in. Typing isn't mandatory, neither is asyncio, nor using IDLE as your main editor. You don't have to store configuration in .ini files parsed with `configparser` and you don't have to use `pip`, even though it comes bundled with Python. But believe me, for each part of Python you consider useless, there are thousands of people for whom that part is indispensable.

There are 10+ accepted typing-related PEPs. Plenty of organizations adopt typing on their own accord with no action from core developers. Clearly, it's useful for them. An increasing number use other type checkers so this isn't functionality specific to Mypy. It's a big community already, and growing! So when you say "we don't need it", you're just wrong. Or maybe you're a descendant of tsars who uses the "royal we" when addressing himself? In any case, it's laughable. Stop it.

**Comment by hzlmn** [comment]
It would be great if it was possible to ban such users from @github forever...

**Comment by abhiramr** [comment]
@irodionzaytsev Łukasz was nicer than your comment warranted. It was toxic and unnecessary. If you don't like something, don't use it. No one's forcing you to.

**Comment by PythonicNinja** [comment]
@irodionzaytsev you are just being rude! 

No arguments were given, you just wrote adpersonam comment which is very harmfull to opensource community.

**Comment by mazulo** [comment]
![image](https://user-images.githubusercontent.com/1661112/140783881-97a7b62c-49ca-43dc-8075-46fbc546a16a.png)

**Comment by reed9999** [comment]
People can support or not support whatever projects they like, but it's "something people don't give a damn about," that makes this a work of art. The Internet is full of vehement, self-negating posts about how X is something people shouldn't care about.

**Comment by OsKaR31415** [comment]
Well i personally just discovered mypy, and i find that it seems quite usefull !
How many times did i got a python bug because i wasn't properly handling the type i gave it or it was doing some fuss because of python bizzare behaviour...

So actually, if you don't find it usefull does not mean that it is useless.
