### ISSUE TITLE
bug: main repository shows mypy errors

### ISSUE THREAD

**Issue by SwagatSBhuyan** [python/mypy#11497]
**Bug Report**
Not sure if it is a bug or simply something that can be ignored, but the master mypy repository itself has mypy static check errors.
Also, this happened on two separate occasions. I was working on a previous issue and I found this error in the test directory, talked about something called "Bogus". I have mentioned it below.

**To Reproduce**
Simply after cloning the mypy repo, go the the root directory of the repo and:
```
mypy .
```

This will yield the following errors in mypy:
```
$ mypy .
mypy\typeshed\stdlib\_typeshed\__init__.pyi: error: Duplicate module named "_typeshed" (also at ".\mypy\typeshed\stdlib\@python2\_typeshed\__init__.pyi")
mypy\typeshed\stdlib\_typeshed\__init__.pyi: note: Are you missing an __init__.py? Alternatively, consider using --exclude to avoid checking one of them.
Found 1 error in 1 file (errors prevented further checking)
```

On another separate occasion, while I was working on a previous issue on automating test files, I happened to check for type-check errors in the directory "./mypy/test", and found the following errors, (reproduced similarly as above, simply changing the root directory to mypy/test):

```
$ mypy .
C:\Users\Swagat\Documents\Python Scripts\mypy\mypy\mypy\bogus_type.py:24: error: Cannot assign multiple types to name "Bogus" without an explicit "Type[...]" annotationdata.py:41: error: Incompatible types in assignment (expression has type overloaded function, variable has type overloaded function)
Found 2 errors in 2 files (checked 41 source files)
```

**Expected Behavior**
No mypy type checking errors, I guess. (All this could also be irrelevant, sorry for the inconvenience)

**Your Environment**
- Mypy version used:  0.920+dev
- Python version used: 3.8.8
- Operating system and version: Windows 10

**Comment by SwagatSBhuyan** [comment]
So are the necessary documentation changes merged? @A5rocks

**Comment by SwagatSBhuyan** [comment]
As mentioned in issue #11403, I renamed the mypy config file and also typed "mypy -p mypy -p mypyc" in the terminal. Now the following error is being thrown:
```
$ mypy -p mypy -p mypyc
mypy\test\data.py:41: error: Incompatible types in assignment (expression has
type overloaded function, variable has type overloaded function)  [assignment]
            join = posixpath.join
                   ^
Found 1 error in 1 file (checked 256 source files)
```

**Comment by A5rocks** [comment]
Try `mypy mypy mypyc --config-file mypy_self_check.ini` instead, that should work.

**Comment by sobolevn** [comment]
Or `python runtests self` 🙂

**Comment by JelleZijlstra** [comment]
The actionable part here is that it's not straightforward to figure out how to run mypy on itself, but that's already covered by #11403, so closing this issue.
