### ISSUE TITLE
option to enforce error codes in `type: ignore` comments

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11509]
**Feature**
it would be cool if there was an option like `--disallow-ignore-without-code` or something that enforces error codes in `type: ignore` comments

**Pitch**
`# type:ignore` comments risk suppressing an unintended error, which is why it's preferred to specify the exact error code you're suppressing

**Comment by KotlinIsland** [comment]
https://github.com/KotlinIsland/basedmypy/issues/11

**Comment by asears** [comment]
Would also be useful if we could use # type: ignore below comments in the python file.  Seems the # type: ignore is ignored if there is a license header in this format.  Might be a separate bug/issue here.

```python
# license copyright info
"""This is a file""
# type: ignore
```

This works.
```python
# type: ignore
# license copyright info
"""This is a file""
```

The above request seems more like a flake8 check?  Maybe in https://pypi.org/project/flake8-annotations/ it would be simpler to implement?

**Comment by KotlinIsland** [comment]
@asears What are you talking about? that code looks like a syntax error with an unterminated triple-quoted string.

**Comment by asears** [comment]
Just a typo in this github issue, in the full code there is a type error that isn't ignored with the first case and no typos/flake8 warnings.   The problem can be reproduced by introducing a type error and trying to silence it with this:

# license copyright info
"""This is a file"""
# type: ignore

Adding the type: ignore to top of file works fine.

**Comment by JelleZijlstra** [comment]
@asears this seems unrelated to the proposal. Please open a new issue if you'd like to see a change in mypy.

**Comment by KotlinIsland** [comment]
@asears are you asking for a whole file type ignore?

In Kotlin annotations can target the file `@file:Suppress("UNCHECKED_CAST")`

For mypy if that's what you want configure your pyproject.toml to specify the options you want, for eg:

pyproject.toml:
```toml
[[tool.mypy.overrides]]
module = "my.module"
ignore_errors = true
```

**Comment by PeterJCLaw** [comment]
How should this option interact with file-level `# type: ignore` comments? Should those be exempt? (Currently it's not possible to specify error codes to ignore per-file, so it feels like it would be hard to require that those ignores have error codes)

**Comment by DetachHead** [comment]
@PeterJCLaw hmm, perhaps a separate option to prohibit file-level ignore comments?

**Comment by JelleZijlstra** [comment]
I would not worry about those. If you're using a file-level ignore, you probably want to ignore everything.

**Comment by KotlinIsland** [comment]
Kotlin handles per code file wide suppression
`@file:Suppress("UNCHECKED_CAST")`, and I agree.
