### ISSUE TITLE
Warn on redundant union entries

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#11517]
I think it would help with understand-ability and discover-ability of certain parts of the python type system.
things such as:
- duck typing
- `bool` extends `int`
- `NoneType` extends `object`

```py
i: int | bool = 1
f: float | int = 1
b: bytes | bytearray | memoryview = b''
o: object | None = "AMONGUS"
```
I would expect all these to trigger warnings that the types are redundant.

**Comment by DetachHead** [comment]
as well as any union consisting of `Any`

**Comment by ethanhs** [comment]
This unfortunately isn't practical. The following code is entirely acceptable:

```python
s: str | None = "foo"
s = None
```

The same could hold for any other union.

I suppose we could see if the other members of the union are ever used, but tracking that sounds too expensive.

**Comment by KotlinIsland** [comment]
> This unfortunately isn't practical. The following code is entirely acceptable:
> 
> ```python
> s: str | None = "foo"
> s = None
> ```
> 
> The same could hold for any other union.
> 
> I suppose we could see if the other members of the union are ever used, but tracking that sounds too expensive.

@ethanhs 
That's not what I'm talking about, `str | None` is not redundant at all, unlike `object | None` where the `None` is redundant.

**Comment by ethanhs** [comment]
I see, in that case, I still don't think we should do this as the redundant types can have readability benefits.

Marking something as `int | float` vs just `float` signals different semantics in the code, and makes it easier to understand.

We could maybe add this as something that is added in `--strict`, but I honestly don't think it is worthwhile.
