### ISSUE TITLE
allow using modules as a type

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11518]
**Feature**
```py
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from Sandpit import foo


def asdf() -> foo: # or Module[foo]
    from Sandpit import foo

    return foo
```

**Pitch**
this pattern is useful as a quick hack for resolving circular imports, also pycharm allows it

**Comment by erictraut** [comment]
I don't think modules should be allowed in the type system. The semantics of a module type are not well defined.

PEP 544 provides a potential solution here. It allows a protocol to describe a module's interface. This is how this would be solved in other languages like TypeScript.

It looks like mypy doesn't support this part of PEP 544 though. See [this issue](https://github.com/python/mypy/issues/5018) for details.

The other solution, of course, is to eliminate the circular dependency in your code. ;)

**Comment by ethanhs** [comment]
I think in the past people have used `types.ModuleType` then used `hasattr` etc. But I would agree that modules as types are tricky, and I think #5018 is a better solution.
