### ISSUE TITLE
Support an `implicit-reexport` that only reexports things in `__init__.py` files

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#11527]
**Feature**

`implicit_reexport = false` is a based one imo, but it's very idiomatic to reexport everything in `__init__.py` files.

**Pitch**
What about:
`implicit_reexport = "init"`

**Comment by mikeroll** [comment]
Looks like a duplicate of https://github.com/python/mypy/issues/10198

**Comment by AlexWaygood** [comment]
> Looks like a duplicate of #10198

Yup.
