### ISSUE TITLE
Potential warning about mis-placed type annotation?

### ISSUE THREAD

**Issue by mihneagiurgea** [python/mypy#1155]
I can imagine the following scenario becoming confusing & potentially common

```
def correctly_annotated(x):
  # type: (int) -> int
  """docs..."""
  ...

def incorrectly_annotated(x):
  """docs..."""
  # type: (int) -> int
  ...
```

It might be useful for mypy to at least print a warning about the 2nd case?

**Comment by ilevkivskyi** [comment]
This is now fixed by ``typed_ast``.
