### ISSUE TITLE
usage of `ellipsis` type should be an error

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11559]
```py
foo: ellipsis = ...
```
https://mypy-play.net/?mypy=master&python=3.10&gist=c2d3912a93b253bbf3f0589148d945bf

this fails at runtime because `ellipsis` doesn't exist

**Comment by erictraut** [comment]
This appears to be a bug in typeshed's `builtins.pyi` file, which declares this symbol in the builtins namespace. Perhaps it should be moved to `_typeshed.pyi` or renamed `_ellipsis` to indicate that it's private?

**Comment by ethanhs** [comment]
Yeah, I think this should probably be reported against typeshed, thanks for debugging that Eric!

**Comment by DetachHead** [comment]
https://github.com/python/typeshed/issues/3556

**Comment by DetachHead** [comment]
i think this should be reopened as it looks like there's a change required on the mypy side in order to fix it. see https://github.com/python/typeshed/issues/3556#issuecomment-570332493

also see the mypy crashes on https://github.com/python/typeshed/pull/6311

**Comment by JelleZijlstra** [comment]
Yes, this is one of the instances where typeshed can't change until mypy changes. #3171 discusses the analogous issue with `builtins.function`.
