### ISSUE TITLE
`typing.Tuple[T]` is `object` in runtime context?

### ISSUE THREAD

**Issue by A5rocks** [python/mypy#11557]
**Bug Report**

```py
reveal_type(typing.Tuple[int])  # N: Reveal type is "builtins.object"
```

**To Reproduce**

See bug report.

**Expected Behavior**

```py
reveal_type(typing.Tuple[int])  # N: Reveal type is "typing.Type[typing.Tuple[int]]"
```

**Actual Behavior**

See bug report.

**Your Environment**

- Mypy version used: master and latest
- Mypy command-line flags: does not matter
- Mypy configuration options from `mypy.ini`: none, reproduced in mypy playground
- Python version used: 3.8
- Operating system and version: debian linux

Technically this is the correct behaviour according to typeshed:

https://github.com/python/typeshed/blob/9eabedca5f47a710f29d6e3e2b3a389853fab5aa/stdlib/typing.pyi#L35-L36

However, I believe telling a lie (?) here is useful: my context here is that I'm telling some generic types their runtime types as an argument to init, so that I can use something like cattrs to convert to that.

**Comment by KotlinIsland** [comment]
This is because `Tuple` is a special form, and `Tuple[int]` is not an instance of `type`, at runtime it's an instance of `typing._GenericAlias`(a generic alias to `typing._SpecialForm`), so it would be incorrect to reveal it's type as `Type[Tuple[int]]`.

If mypy were to lie about it's  type you would run into all sorts of errors

```py
from typing import Tuple
a: type[type] = Tuple[int]  # normally type error
a()  # runtime error, but no type error
```

Could you elaborate on your usecase?

**Comment by JelleZijlstra** [comment]
You may be interested in #9773.

**Comment by A5rocks** [comment]
> Could you elaborate on your usecase?

Sure!

So I have some classes, I'll call them `Request`, that represent the abstraction of "some request." Of course, it wouldn't very nice to use them unless I offered some way to get the return value of the request (since all of these requests are against an API).

https://github.com/A5rocks/bloom/blob/a812c19e524e9d36b70d1cb1edcd2803bf859146/bloom/rest/models.py#L13 definition of this `Request` type -- imagine I added a `cast_type` as the first parameter to it (as the type to cast the response to)

https://github.com/A5rocks/bloom/blob/a812c19e524e9d36b70d1cb1edcd2803bf859146/bloom/ratelimits.py#L183 where I would cast to the type of the request (note the function type)

---

I realize now why this isn't possible and could definitely just use `tuple[T]` instead [(if only it wasn't `object` but that should be fixable :/)](https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=77ee1edd38f808971433664f8aa30257)

> You may be interested in #9773.

I don't think that would help this case, as `Tuple[T]` will still be an `object` (though it would be nicer for unions).

**Comment by KotlinIsland** [comment]
hmmmmmmmm
Woudl something like this work?` 
```py
async def request(self, req: Request[ReturnT]) -> ReturnT:
    ...
        return cast(ReturnT, result.json())
```

**Comment by A5rocks** [comment]
> Casting at runtime is meaningless, it's just there to statically tell the type checker that a value should be assumed to be a certain type, which I think looks like what you want.

Actually, I don't quite mean casting. The response is a JSON object that I convert to a model (see: pydantic, [cattrs](https://github.com/python-attrs/cattrs)) -- I need to know the type for the model. If I know the API will return a list of messages, I'd love to tell that to consumers; it would be even nicer to hand off the model itself to consumers instead of them having to construct it.

I think I should close this issue (because the issue is more a problem with `tuple[T]` and not `Tuple[T]` now), but I'll leave it open for a bit in case I notice something :P

**Comment by A5rocks** [comment]
I [ended up using some bad runtime schenanigans](https://github.com/A5rocks/bloom/commit/08ab6afb936df0edf158dc6bb9f8cfccd906a152), maybe a better way will pop in head eventually.
