### ISSUE TITLE
possible bug in type mismatch of Generic ctor

### ISSUE THREAD

**Issue by OrenGitHub** [python/mypy#11562]
Hey, can you take a look at this SO question which looks like a bug: [link](https://stackoverflow.com/questions/69990049/template-generic-user-defined-classes-in-python-weird-behavior)

**Comment by OrenGitHub** [comment]
I missed this part from the documentation:

**Comment by ethanhs** [comment]
I answered in the stackoverflow question but in short this is covered in common issues: https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code
