### ISSUE TITLE
Mypy seems to not infer type properly when using isinstance() with dictionaries

### ISSUE THREAD

**Issue by trevor87** [python/mypy#11580]
**Bug Report**
I have a parent dataclass and two child dataclasses. I create a dictionary of the parentclass type which contains elements of both child types. If I use isinstance(items[key], ChildClassA) to check the type of a dictionary element, mypy does not understand that items[key] is of type ChildClassA. This is best explained with the example code below.

**To Reproduce**
```
from dataclasses import dataclass
from typing import Dict


@dataclass
class ParentClass:
    fieldA: str


@dataclass
class ChildClassA(ParentClass):
    fieldB: str


@dataclass
class ChildClassB(ParentClass):
    fieldC: str


items: Dict[str, ParentClass] = {
    "test": ChildClassA("A", "B"),
    "test2": ChildClassB("A", "C"),
}

for key in items:
    if isinstance(items[key], ChildClassA):
        print(f"{items[key]} is a ChildClassA element")

        if items[key].fieldB is not None:
            print("field B is none!")
```
When runing mypy on this file, I get the error: `error: "ParentClass" has no attribute "fieldB"; maybe "fieldA"?`

When replacing ` items[key] ` with a variable, the code suddenly works without errors:
```
from dataclasses import dataclass
from typing import Dict


@dataclass
class ParentClass:
    fieldA: str


@dataclass
class ChildClassA(ParentClass):
    fieldB: str


@dataclass
class ChildClassB(ParentClass):
    fieldC: str


items: Dict[str, ParentClass] = {
    "test": ChildClassA("A", "B"),
    "test2": ChildClassB("A", "C"),
}

for key in items:
    item = items[key]
    if isinstance(item, ChildClassA):
        print(f"{item} is a ChildClassA element")

        if item.fieldB is not None:
            print("field B is none!")
```

**Expected Behavior**
I would expect mypy to understand that `items[key]` is of type `ChildClassA`.

**Actual Behavior**

Mypy thinks the object is of type `ParentClass`

**Your Environment**

- Mypy version used: mypy 0.910
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: Python 3.8.10

**Comment by JelleZijlstra** [comment]
#11534 has a good explanation of why mypy can't support this pattern.
