### ISSUE TITLE
Generator[None, None, None] doesn't count as Any

### ISSUE THREAD

**Issue by timabbott** [python/mypy#1158]
Reproducer:
```
from typing import *

def foo():
    # type: () -> Any
    yield
```
throws:
```
/home/tabbott/foo.py: note: In function "foo":
/home/tabbott/foo.py:5: error: Yield value expected
```
It seems like this should be OK.

**Comment by gvanrossum** [comment]
Yeah, I'm pretty sure this was okay before @ddfisher fixed generators. IIRC the old code required `Iterator[...]` but special-cased Any and object.

**Comment by ddfisher** [comment]
This is how `return`s work, so I made `yield`s behave in the same way.

```python
from typing import *

def foo():
    # type: () -> Any
    return
```

```
/Users/ddfisher/test/test.py: note: In function "foo":
/Users/ddfisher/test/test.py:5: error: Return value expected
```

After thinking about this some more and chatting with @gnprice, I think neither of them should work this way.

**Comment by gvanrossum** [comment]
Agreed (but only for Any).

**Comment by JukkaL** [comment]
Agreed as well.

**Comment by ddfisher** [comment]
Fixed a while ago.
