### ISSUE TITLE
mypy does not support "|" as a union type inside dicts

### ISSUE THREAD

**Issue by rvaquerizor** [python/mypy#11587]
**Bug Report**

Union type using | as per PEP 604 is not well supported on mypy.

**To Reproduce**

1. Define a type alias like this one: `D = dict[str, list[dict[str, Optional[str | int | float]]]]`

2. mypy will complain, dumping a number of violations

**Expected Behavior**
mypy should support "|" for union of types.

**Actual Behavior**
mypy complains with the following messages:

```
error: Type expected within [...]
error: Invalid type alias: expression is not a valid type
error: Value of type "Type[Dict[Any, Any]]" is not indexable
error: Value of type "Type[List[Any]]" is not indexable
error: Unsupported left operand type for | ("types.Union")
```

It seems that using union types expressed with  "|" is not supported by mypy, at least if they values of dicts.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.0
- Operating system and version: Ubunut 21.10

**Comment by JelleZijlstra** [comment]
Does this work on master? We've made a lot of improvements in this area since 0.910.

**Comment by rvaquerizor** [comment]
Thanks for the reply.

After updating to the tip of the master branch, all those errors are gone.

`Updating mypy (0.910 -> 0.920+dev.4dfa38c53d5bed4f1ce020440c934d998770e3d8 4dfa38c)
`

When are those changes going to be officially available on pypy?

**Comment by JelleZijlstra** [comment]
You can follow along in #11158. The 0.920 branch is also some way behind master now but as I recall it includes all the `|` fixes.

Anyway, closing since this is fixed on master at least.
