### ISSUE TITLE
Confusing error when unpacking a mapping into a dict

### ISSUE THREAD

**Issue by decorator-factory** [python/mypy#11604]
## Playground link
https://mypy-play.net/?mypy=master&python=3.10&gist=c627233cc195ce16ec828d813e0b9370

## Code
```py
from typing import Mapping


def f(x: Mapping[str, object]) -> int:
    d = {
        "foo": 3.14,
        **x,
    }
    return len(d)
```

## Error
```
main.py:7: error: Argument 1 to "update" of "dict" has incompatible type "Mapping[str, object]"; expected "Mapping[str, float]"
```

1. Why is this an error? `pyright` infers the type of `d` to be `dict[str, Unknown]` (or `dict[str, float | object` if you enable `strictDictionaryInference`).
2. The error mentions `update`, which doesn't appear anywhere. This really confused me when I encountered this error.

# Environment

the same as in the playground link: Python 3.10, mypy on master (or 0.910)

**Comment by sobolevn** [comment]
Would this little change help?

> Argument 1 to "**" of "dict" has incompatible type "Mapping[str, object]"; expected "Mapping[str, float]"

**Comment by decorator-factory** [comment]
> Would this little change help?

I think that's a better error message, yes.

> It does not allow to change the collection type by `.append` / `.update` / `*` / `**` / etc.

Hm, `*` seems to allow mixing types ([Playground link](https://mypy-play.net/?mypy=master&python=3.10&flags=strict&gist=b71ab6aab1b0f54567d521b3a701083a)):
```py
from typing import Sequence


def f(x: Sequence[str]) -> int:
    things = [1, 2, *x]
    reveal_type(things)
    
    numbers = [3, 4]
    other_things = [*numbers, *x]
    reveal_type(other_things)
    
    return len(things) + len(other_things)
``` ```
main.py:6: note: Revealed type is "builtins.list[builtins.object*]"
main.py:10: note: Revealed type is "builtins.list[builtins.object*]"
```

**Comment by sobolevn** [comment]
Yes, one of this is totally a bug. 🤔 
But, which one?

I would say that mixing types is a natural thing in python. It just should infer that `**` in going to make a more general typed container.

**Comment by decorator-factory** [comment]
It seems to me that `mypy` takes the type of the very first thing in the dict literal (`x` in the first case and `y` in the second case) and uses its type for the entire dict.
```py
from typing import Mapping


def f(x: Mapping[str, object], y: Mapping[str, int]) -> None:
    a = {**x, **y}
    reveal_type(a)  # dict[str, obejct]
    
    b = {**y, **x}  # error!
```

**Comment by Cnoor0171** [comment]
> It seems to me that mypy takes the type of the very first thing in the dict literal (x in the first case and y in the second case) and uses its type for the entire dict.

@decorator-factory This isn't exactly true either. For instance, it uses the type of `"z"`'s value to derive the dict literal's type

```python
def f(x: dict[str, int]) -> None:
    a = {
        **x,  # Error
        "z": "blah",
    }
    reveal_type(a)  # dict[str, str]
```

It seems like there is some sort of prioritization going on, where it prefers to take the type of non-unpacked entries before unpacked entries, and then considers their order.

**Comment by socketpair** [comment]
Shouldn't MyPy consider such a dicts as  `Dict[Any, Any]` ?

**Comment by erictraut** [comment]
It looks like this issue was fixed in recent versions of mypy. I no longer see an error for the above code samples.
