### ISSUE TITLE
Abstract readable/writable properties support

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#11601]
This code is not considered valid by mypy:

```python
from abc import abstractmethod

class Array(object):
    @property
    @abstractmethod
    def _length_(self) -> int: ...

    @_length_.setter
    @abstractmethod
    def _length_(self, value: int) -> None: ...
```

Output:

```
out/ex.py:4: error: Overloaded method has both abstract and non-abstract variants
out/ex.py:7: error: Decorated property not supported
```

But, this code is valid:
1. It works in runtime
2. It is documented here: https://docs.python.org/3/library/abc.html#abc.abstractproperty
3. It has clear semantics: we need subclasses of this type to have a read/write property implementation

Refs https://github.com/python/typeshed/pull/6361

**Comment by AlexWaygood** [comment]
This is #1362, no?

**Comment by sobolevn** [comment]
It is related, but we have one more extra warning: `Overloaded method has both abstract and non-abstract variants`

**Comment by AlexWaygood** [comment]
Closing as a duplicate of #4165
