### ISSUE TITLE
`NewType` documentation is incorrect 

### ISSUE THREAD

**Issue by AlexWaygood** [python/mypy#11620]
The documentation for `NewType` at https://mypy.readthedocs.io/en/stable/more_types.html#newtypes states:

>...the typing module provides a helper function `NewType` that creates simple unique types with almost zero runtime overhead.

However, as [the cpython documentation for `NewType`](https://docs.python.org/3/library/typing.html#newtype)` states:

> _Changed in version 3.10_: `NewType` is now a class rather than a function. There is some additional runtime cost when calling `NewType` over a regular function. However, this cost will be reduced in 3.11.0.

In Python >=3.10, `NewType` is a class rather than a function, meaning the mypy documentation is now incorrect.

I'm not immediately sure how it could be rewritten in a more accurate way that is still concise, however.

**Comment by JelleZijlstra** [comment]
We can just replace "function" with "object". The overhead is still tiny, and it doesn't matter to readers of the mypy documentation exactly how NewType is implemented.

**Comment by AlexWaygood** [comment]
> We can just replace "function" with "object". The overhead is still tiny, and it doesn't matter to readers of the mypy documentation exactly how NewType is implemented.

Makes sense, thanks!
