### ISSUE TITLE
Pass path list to check via list file

### ISSUE THREAD

**Issue by abcdenis** [python/mypy#11631]
**Feature**

Allow user to:
- write file and directory names to file, one path per line (optional comments from "#" till EOL)
- pass this file name to mypy instead of specifying all file names in command line

**Pitch**

I've got a huge project but unable to fix all the issues at once. Using "# type: ignore" is  a bit strange.
I'd rather
- write new code in new modules 
- extract legacy code out of existing files to new ones
The main goal is to support file checking with mypy, prevent spoiling them and avoid writing bash loop scripts to process such file list.

```bash
$ mypy --input-path-list=./files 
```

Thank you.

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/stable/running_mypy.html#reading-a-list-of-files-from-a-file

For your stated use case, you might want to play around with the ignore_errors or import following options as well.

**Comment by abcdenis** [comment]
Thank you.
It was unclear from command line help:
```
$ mypy --help | grep '@' | wc -l
       0
```
