### ISSUE TITLE
mypy requires type annotations for empty lists even if they're never added

### ISSUE THREAD

**Issue by timabbott** [python/mypy#1164]
Reproducer:

```
foo: bool
if foo:
    x = []
else:
    x = ["liststr"]

print(x)
```

Error: `foo.py:12: error: Need type annotation for variable`

It seems like this is a case where mypy can be 100% confident that a type annotation is pointless, and so it should probably not throw an error.

**Comment by JukkaL** [comment]
Yeah, mypy should infer the type of `x`. This was actually on my to-do list when I recently improved type inference, but I didn't implement this because I hadn't seen examples in the wild. Now I have :-)

**Comment by saxbophone** [comment]
+1 for this, have found the same is true for empty dicts.

I think it would also be quite helpful if there was an option to make type-checking of variables optional, but this would be a separate issue I think. If such an issue does not already exist, I may create one to explore this idea.

**Comment by yoon28** [comment]
Why should we declare the type of container? Python container, such as list, set and dict, can have various types of data. We can store 'str' and 'int' to one list at the same time. Why mypy need that?

**Comment by JukkaL** [comment]
Mypy needs to know the item types so that it can check that any operations on the items are valid. It also uses the types to check that you don't accidentally add values with invalid types. If you don't care about the types, you can use `List[Any]`, for example, to allow arbitrary items.

**Comment by robertocarta** [comment]
@JukkaL is there a setting to make List[Any] the default list type?

**Comment by JukkaL** [comment]
@robertocarta You can try `--allow-untyped-globals`.

The original example no longer generates an error, so I'm closing this issue. If there are other cases which don't work as expected, feel free to open a new issue.
