### ISSUE TITLE
'tuple[int, ...]' raises 'Unexpected "..."' error

### ISSUE THREAD

**Issue by asvetlov** [python/mypy#11654]
I replaced `Tuple[int, ...]` with `tuple[int, ...]` generic alias during upgrading my codebase to Python 3.9.

mypy 9.10 raises `error: Unexpected "..."  [misc]` error for this line.

What I've missed?

The reproducer is trivial:

1. Create a file with the following content:
```
ID = tuple[int, ...]
```

2. Run mypy for this file

**Comment by hauntsaninja** [comment]
Thanks, this has been fixed on master for a long time.

**Comment by asvetlov** [comment]
Nice! 
Is there any estimation for the new release?

**Comment by hauntsaninja** [comment]
Hopefully soon, but it's out of my hands. You can subscribe to #11158

**Comment by asvetlov** [comment]
Thanks!
