### ISSUE TITLE
The site hosting the documentation is not updated and hence has key detail missing

### ISSUE THREAD

**Issue by bhattbhuwan13** [python/mypy#11674]
**Documentation**

(A clear and concise description of the issue.)
The `mypy/docs/source/getting_started.rst` file, in the section [library-stubs-and-typeshed](https://github.com/python/mypy/blob/master/docs/source/getting_started.rst#library-stubs-and-typeshed) clearly states that in order to install the missing stubs for the `requests` package, the user need to run the command: `python3 -m pip install types-requests`. However, It is not reflected(it is missing in) the [documentation](https://mypy.readthedocs.io/en/stable/getting_started.html#library-stubs-and-typeshed): 
<img width="724" alt="Screen Shot 2021-12-07 at 9 23 36 AM" src="https://user-images.githubusercontent.com/15955955/144961927-c0fd4784-10a4-4ef4-bbff-9a8c34379d93.png">

**Comment by JelleZijlstra** [comment]
Looks like this was fixed in #10720 months ago but it doesn't show up in the stable docs because we haven't released that change yet.

**Comment by bhattbhuwan13** [comment]
Alright then :)
