### ISSUE TITLE
Need type annotation for queue.Queue

### ISSUE THREAD

**Issue by nickeldan** [python/mypy#11688]
With this sample code:

```
import queue

q = queue.Queue()
```

mypy complains (using Python 3.10)

> error: Need type annotation for "q"

Changing the code to

```
q: queue.Queue = queue.Queue()
```

satisfies mypy but it seems strange that mypy doesn't recognize the type automatically.

**Comment by hauntsaninja** [comment]
Yeah, not a great error message. What's going on here is that `queue.Queue` is generic, so mypy is fishing to get you to tell it what the queue contains (e.g. `Queue[int]`).

**Comment by nickeldan** [comment]
Ah, thanks!
