### ISSUE TITLE
Type equivalence confusion with TypedDict and inferred type via TypeVar

### ISSUE THREAD

**Issue by jsaout** [python/mypy#11684]
The following test case demonstrates the issue. I believe that the assignment in line 23 (last line `y = x`) should not fail as the types are supposedly the same. It works for e.g. `int` but fails for a TypedDict. (error says `Incompatible types in assignment (expression has type "Test", variable has type "Test")`)

    from typing import Any, cast, TypedDict, TypeVar
    
    _T = TypeVar("_T")
    
    
    def runtime_cast(value: Any, tp: type[_T]) -> _T:
        return cast(_T, value)
    
    
    # Working
    z: int = runtime_cast(1, int)
    
    # Failing
    class Test(TypedDict):
        v: int
    
    
    x = runtime_cast(dict(v=1), Test)
    y: Test
    reveal_type(x)
    reveal_type(y)
    
    y = x

The output is:

    x.py:20: note: Revealed type is "x.Test*"
    x.py:21: note: Revealed type is "TypedDict('x.Test', {'v': builtins.int})"
    x.py:23: error: Incompatible types in assignment (expression has type "Test", variable has type "Test")

The mypy version is 0.910

**Comment by jsaout** [comment]
I've used constructs like these before and they generally worked.

Unless I've misunderstood if you say e.g. `var: XZY` it means that `var` is an instance of `XYZ` and if you say `tp` type[XYZ]` it means that `tp` is the respective type. The type deduction notices that the return type of `runtime_cast` above should be an instance of `Test` (not `type[Test]`). Like, if you try it for simple types like an `int` it will work as intended.

**Comment by JelleZijlstra** [comment]
`type[]` is meant only for concrete types, not special forms like TypedDict (as documented in https://docs.python.org/3.10/library/typing.html#typing.Type). There is a pending proposal to add a new `TypeForm` special form that would match more type forms.

**Comment by jsaout** [comment]
So there's currently no good way to annotate the above function until this proposal is implemented?

**Comment by JelleZijlstra** [comment]
Correct.

**Comment by jsaout** [comment]
> Correct.

Ok, thank you!

**Comment by erictraut** [comment]
For what it's worth, this works fine in pyright. It's more permissive than mypy when dealing with `type[_T]`. Pyright accepts certain special forms where they make sense. This includes `TypedDict` and unions of types (like `int | str`). Is there a reason why mypy needs to be so strict in this case? I can't think of any type consistency rules that would be broken by supporting these cases.

**Comment by JelleZijlstra** [comment]
Consider this example:
```
from typing import Type, Any
from typing_extensions import TypedDict

def is_type(x: object, y: Type[Any]) -> bool:
    return isinstance(x, y)
    
class TD(TypedDict):
    a: int
    
is_type(1, int)
is_type(1, TD)
is_type(1, 1)
```

The second call will fail at runtime because you can't do isinstance() on a TypedDict. Mypy actually accepts it, though, which seems like a bug to me.

Interestingly, pyright even accepts the third call, which seems like a bug to me.
