### ISSUE TITLE
Mypy treats types with `__getitem__` as not iterables

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#11695]
Sample:

```python
class Some:
    def __getitem__(self, i: int) -> str:
        if i >= 2:
            raise IndexError()
        return chr(97 + i)

s = Some()
for x in s:  # error here
    print(x)
```

Output:

```
» mypy out/ex.py --strict-optional --warn-unreachable --show-traceback
out/ex.py:10: error: "Some" has no attribute "__iter__" (not iterable)
```

But, in runtime it works just fine:

```
» python out/ex.py
a
b
```

Docs: https://pyneng.readthedocs.io/en/latest/book/23_oop_special_methods/iterable_iterator.html#iteration-protocol

I will try to send a PR soon!

**Comment by JelleZijlstra** [comment]
I'm pretty sure there's already a bug for this. Thanks for working on it!

**Comment by sobolevn** [comment]
Yes: https://github.com/python/mypy/issues/2220 Found it!

**Comment by hauntsaninja** [comment]
@sobolevn want to review #10386 ?

**Comment by sobolevn** [comment]
@hauntsaninja done!
