### ISSUE TITLE
Conditional import of StringIO from StringIO or cStringIO doesn't work

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1169]
This code:
```
try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO
```
doesn't work: it complains `error: Name 'StringIO' already defined` on the second import. I think this is because in cStringIO, the function StringIO is an overloaded function (returning different types with and without argument) while in StringIO.py there is a class StringIO.

I'm not sure how to fix this.

**Comment by JukkaL** [comment]
I've seen cases like this as well (in the Python standard library).

When we have a conditional definition where one of the alternatives is a function and the other alternative is a class, we should probably generate a callable type as the result that isn't a type object. If the signatures are different, as in this case, we should try to calculate the most general signature that is compatible with both definitions.

**Comment by ddfisher** [comment]
Duplicate of #1107.

**Comment by denfromufa** [comment]
related to this, how do i properly annotate this code so that mypy checks these types? Right now mypy does not even complain if I remove the Union, BinaryIO, Optional.

```python
def writeln(msg: str, file: Optional[Union[str, BinaryIO]] = None) -> None:
    msg += '\n'
    print(msg)
    if file:
        if isinstance(file, (str, six.text_type)):
            with open(file, mode='a') as f:
                f.write(msg)
        elif isinstance(file, six.StringIO):
            file.write(msg)
        else:
            raise Exception('bad file string(IO) {} with type {}'.format(file, type(file)))
    return
```

**Comment by JukkaL** [comment]
@denfromufa Your problem doesn't look directly related to this issue. You can ask on Gitter or create a new issue.
