### ISSUE TITLE
Defining _order_ in an enum class rejected

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#11699]
This generates an error, even though it's valid:

```py
from enum import Enum

class E(Enum):
    _order_ = 'X Y'  # Cannot override writable attribute "_order_" with a final one
    X = 1
    Y = 2
```

According to the [docs](https://docs.python.org/3/library/enum.html#supported-sunder-names), `_order_` is a somewhat magical attribute, but it's okay to define it.

The error started happening as a side effect of #10852. 

It looks like `_order_` actually isn't a valid attribute at runtime, so a potential fix would be to remove it from typeshed. If we want to do this right, we should also remove an explicit definition from the TypeInfo, since it's not available at runtime.

@sobolevn What do you think?

This is a regression, so marking as high priority.

**Comment by sobolevn** [comment]
I think that `Enum` subclasses should be special cased for `Cannot override writable attribute "_order_" with a final one` rule. Because, a lot of things like 

```python
from enum import Enum

class E(Enum):
    value = 1

print(E.value)
```

work just fine in runtime, but `mypy` is not really happy.

**Comment by sobolevn** [comment]
My proposal: https://github.com/python/mypy/pull/11713
