### ISSUE TITLE
Unclear error from tuple[int, ...] outside typing context

### ISSUE THREAD

**Issue by PeterJCLaw** [python/mypy#11703]
**Bug Report**

Given `tuple[str, ...]` outside a typing context mypy produces an error which doesn't seem very clear:
``` python
x: tuple[str, ...] = ('',)
y = tuple[str, ...]  # error: Unexpected "..."  [misc]
print(x)
print(y)
```
Python is quite happy with the code however:
```
('',)
tuple[str, ...]
```

**Expected Behavior**

If this really is considered an error, it would be great to have a bit more detail here about what's gone wrong and why it's a problem.
I'm guessing that catching this and telling the user that they're likely got a type annotation outside a typing context could be useful, however it feels like type aliases (`Foo = tuple[int, ...]`) might be broken by the current behaviour.

In my case we hit this while partially upgrading an old function-style `NamedTuple` declaration (to use `tuple` but not class-style `NamedTuple`), where the error was particularly confusing as `Tuple[int, ...]` had worked fine.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.9
- Operating system and version: Ubuntu 20.04

**Comment by pranavrajpal** [comment]
Could you check what mypy master shows? This looks like the same issue as #9980, which has been fixed for a while.

**Comment by PeterJCLaw** [comment]
Ah, sorry for the duplicate report. Looks like this has indeed been fixed on master.
