### ISSUE TITLE
Support `StrEnum` in `python3.11`

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#11714]
Source: https://github.com/python/cpython/blob/4fe5585240f64c3d14eb635ff82b163f92074b3a/Lib/enum.py#L1118
Typeshed: https://github.com/python/typeshed/blob/f9cedff5af015cd2814b3e9ed05ebe10e778585d/stdlib/enum.pyi#L82-L97

We would need to treat it as `.is_enum`.

**Comment by odesenfans** [comment]
Is anyone working on this? If not, I could try to tackle it myself but I'd need a few pointers to get me started.

**Comment by DrewMcArthur** [comment]
bump

**Comment by erictraut** [comment]
Mypy 1.5 appears to support `StrEnum`. Is there anything left to do, or can this be closed?
