### ISSUE TITLE
IntEnum members are treated as ints

### ISSUE THREAD

**Issue by howardzlee** [python/mypy#1172]
Using enum34's IntEnum, mypy treats its members as type int rather than the containing enum.

```
from enum import IntEnum

class AnIntEnum(IntEnum):
	A = 1
	B = 2

def foo(e):
	# type: (AnIntEnum) -> None
	assert type(e) == AnIntEnum
	print 'type = %s' % type(e)

foo(AnIntEnum.A)

def bar(e):
	# type: (int) -> None
	pass

bar(AnIntEnum.A)
```

```
hlee-mbp:server hlee$ mypy --py2 testintenum.py 
[...]
testintenum.py:12: error: Argument 1 to "foo" has incompatible type "int"; expected "AnIntEnum"
```

**Comment by gvanrossum** [comment]
Oh, good one. There's some support for Enum and there's even one test for IntEnum but I think this is indeed an underdeveloped area in mypy.

**Comment by wittekm** [comment]
Still not fully supported - see [Jukka's comment on the pull request](https://github.com/python/mypy/pull/1535#issuecomment-219790552) - but better than it was before.

Is there any unhacky way to do this in the future? Enum is implemented with [an overridden `__getattr__` on the class object](https://hg.python.org/cpython/file/3.5/Lib/enum.py), which shadows its true members. That is to say, SomeEnum.x calls getattr, not the member 'x' of SomeEnum.

I'm not sure if MyPy supports typing on `__getattr__`, but even if it did, there would have to be some sort of placeholder type that changes for each subclass, like
```
def __getattr__(cls, name: str) -> WhateverClsIs
```
I don't have an in-depth background in type theory, but this probably breaks every convention :(

**Comment by gvanrossum** [comment]
At issue here seems to be that Enum does some very clever things to change the semantics of assignments in the class body. Those clever things are mostly hidden from the type checker, which has a much more "naive" view of the world than what's actually possible in Python. If this hackery were a third-party package we would probably say "too bad" and recommend a clunkier way to spell it; given that it's in the stdlib we're trying to make mypy support it as well as we can. But it's unrealistic to expect mypy to understand the `__getattr__` implementation on the metaclass. (Halting problem anyone? :-)

**Comment by gvanrossum** [comment]
Closing this; filed #1555 for the left-over task.
