### ISSUE TITLE
Sub-subclassing typing.NamedTuple should be an error

### ISSUE THREAD

**Issue by intgr** [python/mypy#11721]
Subclassing a NamedTuple class seems to not work in Python. This seems to be intentional, [quoting PEP 557](https://www.python.org/dev/peps/pep-0557/#why-not-just-use-typing-namedtuple):

> Data Classes, **unlike typing.NamedTuple**, support combining fields via inheritance.

Mypy could detect this and display an error. For example:

```python
from typing import NamedTuple

class NTup1(NamedTuple):
    a: bool

class NTup2(NTup1):   # Should be an error
    b: bool
```
NTup2 behaves weird, Python seems to ignore the `b` field entirely, for example:
```python
tup = NTup2(a=True, b=False)  # Python: TypeError: <lambda>() got an unexpected keyword argument 'b'
                              # Mypy: error: Unexpected keyword argument "b" for "NTup2"

tup = NTup2(a=True)  # Works in Python

tup.b   # Python: AttributeError: 'NTup2' object has no attribute 'b'
# but mypy thinks the `b` field exists
reveal_type(tup.b)  # Mypy: note: Revealed type is "builtins.bool"
```

**Your Environment**

- Mypy version used: mypy 0.920+dev.51c1acc44039ab398db06f568f8a16b090db7847
- Mypy command-line flags: -
- Mypy configuration options from `mypy.ini` (and other config files): -
- Python version used: Python 3.9.9
- Operating system and version: Arch Linux

**Comment by intgr** [comment]
I tried to implement this, but there are a lot of test cases covering the current behavior.

And it looks like there *are* actually cases where this behavior works. The sub-subclass attrs aren't exposed in the NamedTuple constructor, but methods can be added, and attrs can be assigned after the instance is created. E.g.:

```python
class NTup1(NamedTuple):
    a: bool

class NTup2(NTup1):
    b: bool
    def method(self):
        self.b = True

tup = NTup2(a=False)
tup.method()
tup.b  # Valid
```

The `b` attribute exists after calling `.method()`. This usage IMO violates the implied contract that tuples are immutable. But it works and perhaps some legit code depends on this behavior.

So I'm not sure how to proceed with this. I'll leave my work-in-progress code at https://github.com/intgr/mypy/pull/1

**Comment by StefanHeng** [comment]
I observe the same issue subclassing `transformers.trainer_utils.EvalPrediction`. 

`python` version: 3.9.7. 
`transformers` version: 4.16.2.

**Comment by AlexWaygood** [comment]
I don't think this check should be implemented.

The ability to create a non-`NamedTuple` subclass of a `NamedTuple` can definitely seem a bit counterintuitive  when compared to the behavior of `dataclasses` and `TypedDict`. But `typing.NamedTuple` is supposed to be fully backwards-compatible with `collections.namedtuple`, and creating a non-`namedtuple` subclass of a `collections.namedtuple` is a _very_ common pattern. I'm sure there's a lot of code out there that uses `typing.NamedTuple` in a similar way, and I think people who use that pattern will be very surprised if mypy starts emitting errors for something that's a legitimate use of the `NamedTuple` API.
