### ISSUE TITLE
assert does not work as expected

### ISSUE THREAD

**Issue by Ampfing** [python/mypy#11732]
**Bug Report**

Consider the following code in x.py
```
from typing import Dict, List, Union


def _func2(do_something: bool) -> Dict[str, Dict[str, Union[str, List[str]]]]:
    dict1: Dict[str, Union[str, List[str]]] = dict()
    dict2: Dict[str, Union[str, List[str]]] = dict()
    dict3: Dict[str, Union[str, List[str]]] = dict()
    if (do_something):
        dict1['key1'] = 'string1'
        if ('key1' not in dict2.keys()):
            dict2['key1'] = list()
        assert(isinstance(dict2['key1'], list))
        dict2['key1'].append('otherstring')
    return {'outer_key_1': dict1, 'outer_key_2': dict2, 'outer_key_3': dict3}


def _func1(do_something: bool) -> Dict[str, Dict[str, Union[str, List[str]]]]:
    dict1: Dict[str, Union[str, List[str]]] = dict()
    dict2: Dict[str, Union[str, List[str]]] = dict()
    dict3: Dict[str, Union[str, List[str]]] = dict()
    keys: List[str] = ['key1']
    if (do_something):
        dict1['key1'] = 'string1'
        if (keys[0] not in dict2.keys()):
            dict2[keys[0]] = list()
        assert(isinstance(dict2[keys[0]], list))
        dict2[keys[0]].append('otherstring')
    return {'outer_key_1': dict1, 'outer_key_2': dict2, 'outer_key_3': dict3}
```
**Note**: The only difference between _func1 and _func2 is, that in _func1 the key is part of a list of strings, not directly a string.

**To Reproduce**

1. Run "mypy --strict --show-error-codes x.py" (if the above code is pasted into x.py)

**Expected Behavior**

mypy does not output an error

**Actual Behavior**

Mypy outputs:
x.py:27: error: Item "str" of "Union[str, List[str]]" has no attribute "append"  [union-attr]
Found 1 error in 1 file (checked 1 source file)

**Your Environment**

- Mypy version used: 0.7.9
- Mypy command-line flags: --strict --show-error-codes
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.7.6
- Operating system and version: Windows 10

**Comment by pranavrajpal** [comment]
This seems to be similar to #11534, which also has an explanation for why this is hard to support.

**Comment by hauntsaninja** [comment]
Yup, Pranav is correct and Eric explains it well in the linked issue :-)
