### ISSUE TITLE
TypedDict tracking issue

### ISSUE THREAD

**Issue by 97littleleaf11** [python/mypy#11753]
## `**` unpacking

Related discussion and proposal
- [https://github.com/python/mypy/issues/4441](https://github.com/python/mypy/issues/4441)
- [PEP proposal from Franek](https://github.com/franekmagiera/peps/blob/more-precise-kwargs-typing/pep-9999.rst)

There has been a lot of discussion about better ** typing in typing-sig mailing list. 

Unpack TypedDict into dict 
- [https://github.com/python/mypy/issues/9117](https://github.com/python/mypy/issues/9117)
- [https://github.com/python/mypy/issues/4122](https://github.com/python/mypy/issues/4122)

Unpack TypedDict into TypedDict
- [https://github.com/python/mypy/issues/10585](https://github.com/python/mypy/issues/10585)
- [https://github.com/python/mypy/issues/11108](https://github.com/python/mypy/issues/11108)
- [https://github.com/python/mypy/issues/9408](https://github.com/python/mypy/issues/9408)

## update()

`update()` should accept whose fields is the subset of the caller's fields.
- [https://github.com/python/mypy/issues/9335](https://github.com/python/mypy/issues/9335)
- [https://github.com/python/mypy/issues/6462](https://github.com/python/mypy/issues/6462)

`update(x=1,...)`
- [https://github.com/python/mypy/issues/6019](https://github.com/python/mypy/issues/6019)

## Generics

- #3863

## Useful materials

- [The future of TypedDict | Typing Summit | PyCon US 2022](https://www.youtube.com/watch?v=WEFdYKcK8SM) by @davidfstr

**Comment by 97littleleaf11** [comment]
## Rejected feature requests

### Definition

* [https://github.com/python/mypy/issues/2739](https://github.com/python/mypy/issues/2739)
* [https://github.com/python/mypy/issues/11555](https://github.com/python/mypy/issues/11555)

We wouldn't going to support these syntax and we encourage users to use the class-based syntax since it has been officially supported by Python.

### Instantiation

- [https://github.com/python/mypy/issues/2738](https://github.com/python/mypy/issues/2738)

According to PEP589: 
> It can be used as a callable object with keyword arguments corresponding to the TypedDict items. Non-keyword arguments are not allowed

**Comment by davidfstr** [comment]
@hauntsaninja thanks for taking the time organize some of the current remaining outstanding features for TypedDict!

Is this list intended to be comprehensive? Or perhaps it is a subset of features that you personally are interested in driving forward? Or some other subset?

Related: It appears that you don’t have placeholders for all 4 proposals from the tech talk you have referenced (“The Future of TypedDict”). Is the omission intentional?

**Comment by hauntsaninja** [comment]
I'm assuming you meant to tag 97littleleaf11? :-)

**Comment by 97littleleaf11** [comment]
@davidfstr It's not a complete list. It would be great if you put your ideas here!

**Comment by hauntsaninja** [comment]
Closing, since this is basically all complete, minus https://github.com/python/mypy/issues/6019
