### ISSUE TITLE
Not recognizing provided definition of Optional[Callable]

### ISSUE THREAD

**Issue by nickeldan** [python/mypy#11758]
Here's my MRE:

```python
import typing

def func(x: typing.Optional[typing.Callable] = None) -> typing.Callable:
    if x is None:
        def x() -> None:
            pass

    return x
```

mypy complains:
> error: Incompatible return value type (got "Optional[Callable[..., Any]]", expected "Callable[..., Any]")

I'm using Python 3.10 and mypy 0.910.

**Comment by erictraut** [comment]
The problem is that you have two incompatible type declarations in the same scope for the symbol `x`. You first declare it as type `Callable | None`, then you declare it as `() -> None`. A symbol cannot have different type declarations. The error message in this case could be improved.

You can fix the problem in your code by using a separate symbol name:

```python
def func(x: typing.Optional[typing.Callable] = None) -> typing.Callable:
    if x is None:
        def y() -> None:
            pass
        x = y

    return x
```

**Comment by nickeldan** [comment]
Why are they incompatible?  as `() -> None` is a type of `Callable | None`.

**Comment by erictraut** [comment]
You are declaring `x` as two different types.

I assume you'd agree that this should not be allowed, since it's declaring `x` to be an `int` and a `str`.
```python
x: int
x: str
```

This is effectively what you're trying to do:
```python
x: Callable[..., Any] | None
x: Callable[[], None]
```

**Comment by nickeldan** [comment]
Then why is this okay?

```python
def func(x: Optional[str]) -> str:
    if x is None:
        x = 'hello'
    return x
```

**Comment by JelleZijlstra** [comment]
The idea is that a `def` counts as "declaring" a variable, not just defining it. Both mypy and pyright work that way, but honestly I don't find it particularly compelling.

**Comment by erictraut** [comment]
There's an important distinction between declaring the type of a symbol and assigning a value to it.

`x: Optional[str]` and `def x() -> None: ...` and `class x: ...` are type declarations. They specify the type of `x`. The primary job of a type checker to verify that any value assigned to a symbol is compatible with its declared type. If you provide conflicting type declarations for a symbol, the type checker won't know which type to enforce.

`x = 'hello'` assigns a value to the symbol, and the assigned value must be compatible with the declared type. In your example above, the expression `'hello'` is compatible with the declared type `Optional[str]`.
