### ISSUE TITLE
Is there any licensing issue with the lib certifi?

### ISSUE THREAD

**Issue by ruimmpires** [python/mypy#11750]
I tested a fork in my own repository with Snyk and I got the info that certifi lib is a MPL:
certifi MPL-2.0 license
Detailed paths
Introduced through: project@0.0.0 › sphinx@4.3.1 › requests@2.26.0 › certifi@2021.10.8
Fix: No remediation path available.
Introduced through: project@0.0.0 › sphinx-rtd-theme@1.0.0 › sphinx@4.3.1 › requests@2.26.0 › certifi@2021.10.8
Fix: No remediation path available.
![image](https://user-images.githubusercontent.com/46453695/146182513-511ac1e2-3a80-484e-b912-9b8e4dcb4d7d.png)

**Comment by JelleZijlstra** [comment]
This is only used for the documentation, and it gets picked up through a very widely used library (requests). So I'm not sure this is a concern for mypy users.

**Comment by ruimmpires** [comment]
> 

thanks, good to know.
Was just trying out some tools and came across this notification
