### ISSUE TITLE
ImportError: cannot import name 'TypeVarDef' from 'mypy.types'

### ISSUE THREAD

**Issue by adam-pawluczuk** [python/mypy#11767]
**Bug Report**

`TypeVarDef` raises an `ImportError`.

**To Reproduce**

1. On Python 3.8.9, when doing:

`from mypy.types import TypeVarDef`

I get this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TypeVarDef' from 'mypy.types' (/Users/username/Library/Python/3.8/lib/python/site-packages/mypy/types.py)
```

**Expected Behavior**

No errors.

**Actual Behavior**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TypeVarDef' from 'mypy.types' (/Users/username/Library/Python/3.8/lib/python/site-packages/mypy/types.py)
```

**Your Environment**

- Mypy version used: 0.920
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.8.9
- Operating system and version: MacOS 12.1

**Comment by hauntsaninja** [comment]
Yes, see https://github.com/python/mypy/issues/6617#issuecomment-892438903

If you're coming from pydantic, you can fix it by doing what I suggest here: https://github.com/samuelcolvin/pydantic/pull/3175#issuecomment-914897604

**Comment by adam-pawluczuk** [comment]
Thank you for the link!

I believe the issue comes from `pydantic`:

https://github.com/samuelcolvin/pydantic/blob/master/pydantic/mypy.py#L62

In our codebase we do not import `TypeDefVar` anywhere.

Created an issue for pydantic:
https://github.com/samuelcolvin/pydantic/issues/3528
