### ISSUE TITLE
Exclude doesn't work with files

### ISSUE THREAD

**Issue by Timmmm** [python/mypy#11760]
**Bug Report**

If you specify some files for mypy to find with the `files = ` config option, then exclude can't let you ignore them. E.g.

**To Reproduce**

```
$ cat mypy.ini
[mypy]
files = **/*.py
exclude = .*
$ cat foo/bar.py 
asdsdfsdf
$ mypy
foo/bar.py:1: error: Name "asdsdfsdf" is not defined
Found 1 error in 1 file (checked 1 source file)
```

**Expected Behavior**

`exclude` should override `files`.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: See above
- Mypy configuration options from `mypy.ini` (and other config files):  See above
- Python version used: 3.8
- Operating system and version: Centos of some kind

**Comment by hauntsaninja** [comment]
This is documented behaviour: https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-exclude

>  If you pass a file or module explicitly it will still be checked. For instance, mypy --exclude '/setup.py$' but_still_check/setup.py.

Consider using per-module ignore errors

**Comment by Timmmm** [comment]
Ah it's not clear that `files = ...` is the same as passing files on the command line. Maybe worth documenting.

It would be nice if there was a way to do `files_exclude = ...` but for now I will just run Mypy over each file one by one using a script. :-/
