### ISSUE TITLE
Subscribe to the mypy blog via email

### ISSUE THREAD

**Issue by ardakuyumcu** [python/mypy#11804]
Hi team, I'm wondering if there is a way for us to subscribe to updates from [The Mypy Blog](https://mypy-lang.blogspot.com/) via email.

Looks like other blogs using Blogger are able to set this up using Google FeedBurner, would be great if this was made available for mypy as well.

Thanks!

**Comment by ethanhs** [comment]
I believe FeedBurner is being phased out https://support.google.com/blogger/answer/10477563?hl=en

The mypy blog does have an rss feed, so you may consider using that, though I know it isn't exactly what you want.

**Comment by ardakuyumcu** [comment]
Thanks for the quick response @ethanhs! I was actually able to create my own feed for the Mypy blog on FeedBurner [here](http://feeds.feedburner.com/TheMypyBlog), and even enable email subscriptions for it, which solves my problem for now.

The FeedBurner website does mention the below, unclear on the future support:
> Existing feeds will continue to serve indefinitely, and existing users can download past usage statistics and email subscriptions. Users will still be able to create new accounts and burn new feeds. However, some existing features, like email subscriptions and detailed analytics, will no longer be supported.

It would be great if the maintainers could still consider adding an official feed for it, and add the email subscription widget to the blog (you can see https://pythoninsider.blogspot.com/ for an example). Also happy to transfer ownership of the feed I created to maintainers if that's preferred. 

Otherwise I'm all set here, thanks for all your help! 🙏
