### ISSUE TITLE
INTERNAL ERROR with SQLAlchemy caused by mypy 0.930 regression

### ISSUE THREAD

**Issue by Hawool** [python/mypy#11838]
mypy --show-traceback .
./db/base_class.py:7: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.930
Traceback (most recent call last):
  File "mypy/semanal.py", line 5132, in accept
  File "mypy/nodes.py", line 1005, in accept
  File "mypy/semanal.py", line 1105, in visit_class_def
  File "mypy/semanal.py", line 1184, in analyze_class
  File "mypy/semanal.py", line 1193, in analyze_class_body_common
  File "mypy/semanal.py", line 1239, in apply_class_plugin_hooks
  File "/home/dev/projects/hydra/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 233, in _base_cls_decorator_hook
    decl_class._scan_declarative_assignments_and_apply_types(
  File "/home/dev/projects/hydra/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 88, in _scan_declarative_assignments_and_apply_types
    _scan_declarative_decorator_stmt(cls, api, stmt, cls_metadata)
  File "/home/dev/projects/hydra/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 293, in _scan_declarative_decorator_stmt
    left_node.node.type = api.named_type(
  File "mypy/semanal.py", line 4538, in named_type
  File "mypy/semanal.py", line 4504, in lookup_fully_qualified
  File "mypy/semanal.py", line 4520, in lookup_fully_qualified_or_none
AssertionError: 
./db/base_class.py:7: : note: use --pdb to drop into pdb
(venv) dev@user-virtual-machine:~/projects/hydra$ mypy .
./db/base_class.py:7: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.930
./db/base_class.py:7: : note: please use --show-traceback to print a traceback when reporting a bug

from typing import Any
from sqlalchemy.ext.declarative import as_declarative, declared_attr

@as_declarative()
class Base:        # string №7
    id: Any
    __name__: str
    # Generate __tablename__ automatically
    @declared_attr  # type: ignore
    def __tablename__(self):  # noqa: N805
        return self.__name__.lower()

I don’t understand what happened?

**Comment by donghyeon-kim98** [comment]
I faced this issue

**Comment by Hawool** [comment]
@donghyeon-kim98 downgraded mypy version helped.

**Comment by donghyeon-kim98** [comment]
What's mypy version?
There was no problem when using sqalchemy 1.4.26 with mypy 0.910.

**Comment by TheZavitaev** [comment]
Hi everyone! 
We caught the same error during CI. 
Downgraded mypy version, problem went away.

```
mypy==0.910
SQLAlchemy==1.4.9
```

**Comment by sobolevn** [comment]
Do you enable `sqlalchemy` plugin? Or does it happen even without it?

**Comment by donghyeon-kim98** [comment]
It does happen when i `sqlalchemy==1.4.29` use with `mypy 0.910`
I think it caused by [this patch](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-1.4.29-mypy)
So, if I use it with `mypy==0.930` this problem does not happen 
However i should use `mypy==0.910` because pydantic mypy plugin is compatible with `mypy <= 0.910`

**Comment by mikepii** [comment]
Looks like this was [fixed](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-f3dab8f79a76e23c32f26c81a97902e5) in SQLAlthemy 1.4.29 (see https://github.com/sqlalchemy/sqlalchemy/issues/7496).

Minimal example to reproduce:

demofile.py:

```python
from sqlalchemy.orm import declarative_base
Context = declarative_base()
```

mypy.ini:

```ini
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
```

Run:

```sh
pip3 install mypy 'SQLAlchemy[mypy]==1.4.28'  # change to 1.4.29 to fix
mypy demofile.py
```

**Comment by Synrom** [comment]
Hey,
I have the same problem with ` SQLAlchemy[mypy]==1.4.39 ` and `mypy==0.971`.
I get the following Error:
```
$ poetry run mypy --show-traceback bot
bot/database.py:36: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.971
bot/database.py:36: : note: use --pdb to drop into pdb
bot/database.py:13: error: Module "sqlalchemy.orm" has no attribute "registry"
Traceback (most recent call last):
  File "mypy/semanal.py", line 5354, in accept
  File "mypy/nodes.py", line 1039, in accept
  File "mypy/semanal.py", line 1123, in visit_class_def
  File "mypy/semanal.py", line 1203, in analyze_class
  File "mypy/semanal.py", line 1212, in analyze_class_body_common
  File "mypy/semanal.py", line 1257, in apply_class_plugin_hooks
  File "/builds/identeco/telegram-channeler/.venv/lib/python3.10/site-packages/sqlalchemy/ext/mypy/plugin.py", line 257, in _base_cls_hook
    _add_globals(ctx)
  File "/builds/identeco/telegram-channeler/.venv/lib/python3.10/site-packages/sqlalchemy/ext/mypy/plugin.py", line 273, in _add_globals
    util.add_global(ctx, "sqlalchemy.orm.attributes", "Mapped", "__sa_Mapped")
  File "/builds/identeco/telegram-channeler/.venv/lib/python3.10/site-packages/sqlalchemy/ext/mypy/util.py", line 177, in add_global
    lookup_sym: SymbolTableNode = ctx.api.modules[module].names[
KeyError: 'Mapped'
Cleaning up file based variables 00:01
ERROR: Job failed: exit code 1

```
I use poetry and my pyproject.toml looks like this:
```
[tool.poetry]
name = "telegram-channeler"
version = "0.1.0"
description = "Crawl through Telegram Channels, download leaks!"
authors = ["max.leiwig <s6maleiw@uni-bonn.de>"]
packages = [
	{ include = "bot" }
]

[tool.poetry.dependencies]
python = "^3.10"
Pyrogram = "^2.0.30"
pydantic = {version = "^1.9.1", extras = ["dotenv"]}
TgCrypto = "^1.2.3"
pylint = "^2.14.5"
click = "^8.1.3"
SQLAlchemy = "^1.4.39"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
sqlalchemy-stubs = "^0.4"
pylint = "^2.14.5"
sqlalchemy2-stubs = "^0.0.2-alpha.24"
mypy = "0.971"
SQLAlchemy = {extras = ["mypy"], version = "^1.4.39"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
telegrambot = "bot.run:run"
```
and my mypy.ini
```
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
```
Does anybody have an idea? I already tried changing the mypy and the sqlalchemy versions.

**Comment by goodoldneon** [comment]
I'm running into this, too. I've tried a variety of `mypy` and `SQLAlchemy` versions

**Comment by Synrom** [comment]
@goodoldneon Thank you very much! Deleting sqlalchemy-stubs from the pyproject.toml actually worked :)
But now Im getting some errors regarding mypy missing library stubs.

```
bot/database.py:12: error: Skipping analyzing "sqlalchemy.engine.base": module is installed, but missing library stubs or py.typed marker
bot/database.py:13: error: Skipping analyzing "sqlalchemy.orm": module is installed, but missing library stubs or py.typed marker
bot/database.py:14: error: Skipping analyzing "sqlalchemy.orm.decl_api": module is installed, but missing library stubs or py.typed marker
bot/bot.py:33: error: Skipping analyzing "sqlalchemy.orm": module is installed, but missing library stubs or py.typed marker
bot/bot.py:33: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 4 errors in 2 files (checked 6 source files)
```

The following are the lines of code, that cause the errors:
bot/database.py:12-14:
```
from sqlalchemy.engine.base import Engine
from sqlalchemy.orm import relationship, Session, registry
from sqlalchemy.orm.decl_api import DeclarativeMeta
```

bot/bot.py:33:
```
from sqlalchemy.orm import Session
```

Does anyone have an idea why this is happening?

**Comment by Synrom** [comment]
Thanks a lot, after enabling the plugin everything works now :)
