### ISSUE TITLE
handling of `exclude` configuration changed in an incompatible way in 0.930

### ISSUE THREAD

**Issue by asottile** [python/mypy#11830]
https://github.com/python/mypy/issues/11825 seems related but slightly different as that one causes a crash -- I believe this was broken in https://github.com/python/mypy/pull/11329

**Bug Report**

for example: (this is reduced from a larger example just to demonstrate a minimal example)

```ini
# mypy.ini
[mypy]
exclude=(?x)
    ^(
        setup\.py$
    )
```

**To Reproduce**

set up a configuration above and run mypy

**Expected Behavior**

in mypy 0.920 this excluded all `setup.py` files

**Actual Behavior**

this appears to exclude *all* files:

```console
$ mypy .
There are no .py[i] files in directory '.'
```

**Your Environment**

- Mypy version used: 0.930
- Mypy command-line flags: (see above)
- Mypy configuration options from `mypy.ini` (and other config files): (see above)
- Python version used: 3.8.10
- Operating system and version: ubuntu 20.04

**Comment by hauntsaninja** [comment]
cc @nipunn1313 something like #11828 should work for pyproject.toml, but curious for your opinion on what this should look like going forward for ini files

**Comment by nipunn1313** [comment]
Great question.

I think the safest option is to maintain the old behavior on `.ini` files - such that you cannot provide multiple `--exclude` inside `ini` files. `ini` files don't have support for array structures so this seems ok.

There is a simple workaround to get access to the new feature - using pyproject.toml instead of mypy.ini.

**Comment by posita** [comment]
I can try to augment #11828 (or provide a PR that depends on it) to restore the old `.ini` behavior. Would that work?

**Comment by posita** [comment]
I added #11881 to address #11830 by reverting to treating `exclude` in `mypy.ini` as a single string. This *should* be compatible with #11828.
