### ISSUE TITLE
call-overload error on `environ.pop("…", default="…")`

### ISSUE THREAD

**Issue by l0b0** [python/mypy#11831]
**Bug Report**

It's all in the title.

As far as I can tell it's not a duplicate of #10152, because I'm not dealing with `TypeVar`s, or #3750, because I'm not doing any overloading myself.

**To Reproduce**

```
$ mypy --strict <(echo 'from os import environ; environ.pop("…", default="…")')
/dev/fd/63:1: error: No overload variant of "pop" of "MutableMapping" matches argument types "str", "str"  [call-overload]
/dev/fd/63:1: note: Possible overload variants:
/dev/fd/63:1: note:     def pop(self, str) -> str
/dev/fd/63:1: note:     def [_T] pop(self, str, Union[str, _T] = ...) -> Union[str, _T]
Found 1 error in 1 file (checked 1 source file)
```

**Expected Behavior**

This should succeed. This is a regression since 0.910.

**Your Environment**

- Mypy version used: 0.930
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8.12
- Operating system and version: NixOS 21.11

**Comment by jamescooke** [comment]
Similar problems happen with `get()`. A reminder that the help for `environ.get()` includes the `default` kwarg in the signature:

```
In [2]: os.environ.get?
Signature: os.environ.get(key, default=None)
Docstring: D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.
File:      /usr/lib/python3.8/_collections_abc.py
Type:      method
```

With the following:

```sh
cat > papersize.py 
import os

print(os.environ.get('PAPERSIZE', default='fool'))
```

Then:

```sh
mypy papersize.py
papersize.py:3: error: No overload variant of "get" of "Mapping" matches argument types "str", "str"
papersize.py:3: note: Possible overload variants:
papersize.py:3: note:     def get(self, key: str) -> Optional[str]
papersize.py:3: note:     def [_T] get(self, str, Union[str, _T]) -> Union[str, _T]
```

I've reproduced with `mypy==0.930`, strict is not required and on Pythons `3.8.10` and `3.6.15`.

I think these problems might be related to this change in typeshed here: https://github.com/python/typeshed/pull/5772 which is an attempt to solve this error: https://github.com/python/typeshed/issues/5771

What I'm wondering is what Python developers are meant to experience with this functionality? Use the `os.environ` methods as described in `help()` (with explicit and readable kwargs), but get a type error - so have to remove the helpful kwargs to get it to work correctly?! 🤔 There must be a better way!

**Comment by domWalters** [comment]
I got this error today in slightly different circumstances.

mypy 1.2.0, python 3.10.10.

The example given in this issue does not error for me:

```console
$ mypy --strict <(echo 'from os import environ; environ.pop("…", default="…")')
Success: no issues found in 1 source file
```

However, a modification does:

```console
$ mypy --strict <(echo '{}.pop("…", default=None)')
/proc/self/fd/11:1: error: No overload variant of "pop" of "dict" matches argument types "str", "None"  [call-overload]
/proc/self/fd/11:1: note: Possible overload variants:
/proc/self/fd/11:1: note:     def pop(self, <nothing>, /) -> <nothing>
/proc/self/fd/11:1: note:     def [_T] pop(self, <nothing>, _T, /) -> _T
Found 1 error in 1 file (checked 1 source file)
```

Interestingly, calling pop on a type annotated variable, plus passing `None` as a positional argument instead of a keyword avoids this issue:

```console
$ mypy --strict <(echo 'a: dict[str, str] = {}; a.pop("…", None)')
Success: no issues found in 1 source file
```

If you keep `default=None`, this will error:
```console
$ mypy --strict <(echo 'a: dict[str, str] = {}; a.pop("…", default=None)')
/proc/self/fd/11:1: error: No overload variant of "pop" of "dict" matches argument types "str", "None"  [call-overload]
/proc/self/fd/11:1: note: Possible overload variants:
/proc/self/fd/11:1: note:     def pop(self, str, /) -> str
/proc/self/fd/11:1: note:     def [_T] pop(self, str, Union[str, _T], /) -> Union[str, _T]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by hauntsaninja** [comment]
mypy's correct here:
```
λ python
Python 3.9.9 (main, Aug  7 2022, 02:25:38) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> {}.pop("...", default=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: dict.pop() takes no keyword arguments
```
