### ISSUE TITLE
Type-checking

### ISSUE THREAD

**Issue by John9766** [python/mypy#11849]
I am using Python 3.10,  I am trying out mypy first time,  runs ok on other files, until I come across this error, not sure whether it  recognise the match  statement in the source code,  not sure whether this is bug or  simply not include in type-checking 
 

    match opt:
        case '1':
            details()
        case'2':
            search()
        case _:
            print('Invalid option')

main.py:49:  error: Match statement is not supported
Found 1 error in 1 file (errors prevented further checking)

**Comment by srittau** [comment]
The match statement is not yet supported in mypy. See #10191.
