### ISSUE TITLE
error: Unsupported left operand type for + ("object")

### ISSUE THREAD

**Issue by lmar76** [python/mypy#11841]
Problem: I have a list of tuples `x` and a list of ints `y`:

```python
  x = [(1, 10), (2, 20)]
  y = [100, 200]
```

and I need to generate a new list having elements of `y` concatenated to the tuples in `x`:

```python
w = [(1, 10, 100), (2, 20, 200)]
```

I have created `main.py` script with this content:

```python
from functools import reduce


def main() -> None:

    x = [(1, 10), (2, 20)]
    y = [100, 200]
    z = list(zip(x, y))
    w = [reduce(lambda a, b: a + (b,), elm) for elm in z]

    print(f"x: {x}")
    print(f"y: {y}")
    print(f"z: {z}")
    print(f"w: {w}")


if __name__ == '__main__':
    main()
```

When I execute the script I obtain what I need (see `w` variable):
```
% python main.py
x: [(1, 10), (2, 20)]
y: [100, 200]
z: [((1, 10), 100), ((2, 20), 200)]
w: [(1, 10, 100), (2, 20, 200)]
```

But when I run mypy on the script I get this error:

```
% mypy main.py  
main.py:9: error: Unsupported left operand type for + ("object")
Found 1 error in 1 file (checked 1 source file)
```

It seems that, in this case, mypy does not recognize the concatenation between the two tuples in the lambda expression: `a` and `(b,)` but I don't know if this issue is due to my error or to a bug. Can you please help me?

**Comment by srittau** [comment]
I have reduced the script to more clearly see the problem:

```python
from functools import reduce

elm = ((1, 10), 100)
reduce(lambda a, b: a + (b,), elm)  # Unsupported left operand type for + ("object")
```

In typeshed `reduce` is defined as follows:

```python
@overload
def reduce(function: Callable[[_T, _S], _T], sequence: Iterable[_S], initial: _T) -> _T: ...
@overload
def reduce(function: Callable[[_T, _T], _T], sequence: Iterable[_T]) -> _T: ...
```

The first overload isn't matched as there is no `initial` argument. In the second overload, `_T` is `tuple[int, int] | int`. mypy tries to find a common base class, which is `object`, hence the error.

I think the correct way is not to use reduce here:

```python
from functools import reduce


def main() -> None:

    x = [(1, 10), (2, 20)]
    y = [100, 200]
    z = list(zip(x, y))
    w = [a + (b,) for a, b in z]

    print(f"x: {x}")
    print(f"y: {y}")
    print(f"z: {z}")
    print(f"w: {w}")


if __name__ == '__main__':
    main()
```

**Comment by lmar76** [comment]
@srittau Thank you! I don't know if this example may lead to an improvement on mypy, anyway I will use your workaround.

**Comment by sgonzalezgap** [comment]
Having the same issue to compare two datetime objects, the error:

Just for a quick example:
`
fmt: str = '%Y-%m-%d'

dt1 = datetime.strptime(date_string1, fmt)
dt2 = datetime.strptime(date_string2, fmt)

if dt1 > dt2:
    print("ok")

No matter which dates are
`
