### ISSUE TITLE
Consider `from .sub import *` as re-exporting all the public symbols of `sub`

### ISSUE THREAD

**Issue by tibdex** [python/mypy#11856]
**Bug Report**

This goes directly against what was made in #7361 but it's more consistent with [PEP 484](https://www.python.org/dev/peps/pep-0484/) which says:

> - Modules and variables imported into the stub are not considered exported from the stub unless the import uses the import ... as ... form or the equivalent from ... import ... as ... form. (UPDATE: To clarify, the intention here is that only names imported using the form X as X will be exported, i.e. the name before and after as must be the same.)
> - However, as an exception to the previous bullet, all objects imported into a stub using from ... import * are considered exported. (This makes it easier to re-export all objects from a given module that may vary by Python version.)

I know that these notes are for "stub files" but, for typed libraries with a `py.typed` (see [PEP 561](https://www.python.org/dev/peps/pep-0561/)), it makes sense for regular `.py` files to follow the same rules as `.pyi` files.

Not considering `from .sub import *` as re-exporting all the public/exported symbols of `sub` forces the developers to manually list all the symbols of `sub`, making the attention they paid to correctly make symbols public or private in this sub module worthless.

**To Reproduce**

```py
# sub.py
from .other import A as A, B

def _private_function() -> None:
   ...

def public_function() -> None:
   ...
```

```py
# __init__.py
from .sub import *
```

**Expected Behavior**

`__init__.py` exports:
- `A` from `.other` (not `B` because it wasn't re-exported)
- `public_function` from `.sub` (not `_private_function` because it's considered private as it starts with `_`)
- `sub` since this is what PEP 484 mentions in:
  ```
  Just like in normal Python files, submodules automatically become exported attributes of their parent module when imported
  For example, if the spam package has the following directory structure:

      spam/
          __init__.pyi
          ham.pyi

   where __init__.pyi contains a line such as from . import ham or from .ham import Ham, then ham is an exported attribute of spam.
  ```

This is consistent with what @erictraut [did in Pyright](https://github.com/microsoft/pyright/blame/b7735bb8626ebabd87a6c85c6aee8fae39eb776d/docs/typed-libraries.md#L35).

**Actual Behavior**

`__init__.py` only exports `sub`.

**Your Environment**

- Mypy version used: 0.930

**Comment by tibdex** [comment]
Linking https://github.com/python/mypy/issues/8754 which is not the same but also has issues related to re-exports and is another discrepancy between mypy and Pyright.

**Comment by hauntsaninja** [comment]
Thanks for flagging this, I'd be in favour of changing mypy's behaviour here.
Should be backward compatible in that we're allowing strictly more code.

**Comment by erictraut** [comment]
This change would make mypy consistent with the rules that (I thought) we had agreed to a while back when it comes to py.typed libraries.

These rules are documented [here](https://github.com/python/typing/blob/master/docs/source/libraries.rst#library-interface), and they indicate that symbols imported through wildcard import statements should be treated as re-exported.

**Comment by hauntsaninja** [comment]
Yes, Guido, you and I had agreed on a typing-sig thread at some point :-)
I'd made changes to PEP 484 and mypy at the time (`X as X`), but didn't realise mypy's behaviour differed for `import *`. It looks like mypy's previous explicit decision on `import *` that tibdex links predates that by quite a bit.

https://github.com/python/mypy/pull/11867 will change mypy's behaviour to what we discussed.
