### ISSUE TITLE
Abstract dataclasses don't work

### ISSUE THREAD

**Issue by inducer** [python/mypy#11868]
Consider this snippet, let's name it `mypy-abstract-dataclass.py`:
```py
from dataclasses import dataclass
from abc import ABC, abstractmethod


@dataclass(frozen=True)
class Something(ABC):
    xyz: int

    @abstractmethod
    def abc(self) -> int:
        pass
```
I think this should typecheck (subclasses of this can be instantiated without error), but mypy 0.930 says:
```
mypy-abstract-dataclass.py:5: error: Only concrete class can be given where "Type[Something]" is expected
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.930
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10
- Operating system and version: Linux

**Comment by AlexWaygood** [comment]
I think this _may_ be a duplicate of https://github.com/python/mypy/issues/5374? 🙂

**Comment by inducer** [comment]
Looks that way. Thanks for the pointer!
