### ISSUE TITLE
type-coverage reports presences of Anys on calls to isinstance, TypeError

### ISSUE THREAD

**Issue by alex** [python/mypy#11878]
**Bug Report**

Producing a type-coverage report, e.g. with `mypy --html-report type-coverage src/cryptography` shows missing coverage on any calls to `isinstance` or `TypeError`.

**To Reproduce**

1. `git clone https://github.com/pyca/cryptography`
2. `cd cryptography`
3. `mypy --html-report type-coverage src/cryptography`
4. Look at coverage for `cryptography.hazmat.primitives.constant_time`

**Expected Behavior**

There is full coverage

**Actual Behavior**

Lines with `isinstance` and `TypeError` show as having missing coverage.

**Your Environment**

mypy 0.930

**Comment by sobolevn** [comment]
This happens because `isinstance` has this type:

```python
def (builtins.object, Union[builtins.type, types.UnionType, builtins.tuple[Union[builtins.type, types.UnionType, builtins.tuple[Any, ...]], ...]]) -> builtins.bool
```

And later our `stats.py` finds this `Any` and records it as imprecise type: https://github.com/python/mypy/blob/229913e8e31ee2889ad3e2a3f85ffe82b29fa198/mypy/stats.py#L256-L260

**Comment by alex** [comment]
Perhaps builtin functions should be special cased, or something like that?

**Comment by karlicoss** [comment]
smaller sample which reproduces this:
```
$ cat test.py 
x = 1 
is_int = isinstance(x, int)

$ mypy test.py --html-report .cov && cat .cov/html/test.py.html 
<td class="table-lines"><pre><span id="L1" class="lineno"><a class="lineno" href="#L1">1</a></span>
<span id="L2" class="lineno"><a class="lineno" href="#L2">2</a></span>
</pre></td>
<td class="table-code"><pre><span class="line-precise" title="No Anys on this line!">x = 1</span>
<span class="line-imprecise" title="Any Types on this line: 
Explicit (x1)">is_int = isinstance(x, int)</span>
```

**Comment by karlicoss** [comment]
also I tried hinting mypy the type of isinstance: 

```
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    def isinstance(x: object, t: type) -> bool: ...

y: object = 'aaa'

if isinstance(y, str):
    print(y.lower())
```

interesting enough, this colours the `if isinstance(y, str)` line as green, however it breaks case analysis, now we get the error on the next line

```
test.py:8: error: "object" has no attribute "lower"  [attr-defined]
        print(y.lower())
```

which is somewhat surprising to me, I would have expected it not to have impact at all (because `isinstance` is pretty fundamental to mypy analysis)

**Comment by JelleZijlstra** [comment]
You are shadowing `builtins.isinstance`, so mypy doesn't apply its special-casing of `isinstance()` calls any more. To do what you want to do you'd have to change the stub files for the builtins module.

**Comment by karlicoss** [comment]
@JelleZijlstra aah good point, thanks! 
I tried changing it to `def isinstance(x: object, t: type) -> bool: ...` here https://github.com/python/mypy/blob/7e38877750c04abfd436e6ad98da23d6deca4e8f/mypy/typeshed/stdlib/builtins.pyi#L1220-L1222 
, (passed `--custom-typeshed`), and it works, everything is green

but seems that this change would break stuff like `if isinstance(y, str | int):` (didn't even know isinstance supported this!)  https://docs.python.org/3/library/stdtypes.html#types-union

**Comment by JelleZijlstra** [comment]
Yes, that's not a change we can make in the real typeshed. We can handle the case you flag pretty easily, but the hard case is `isinstance(y, (str, (int, (float,))))`. We need recursive type support in mypy to type that precisely.

**Comment by karlicoss** [comment]
What do you think of a change like this to `typeshed`? 
It seems to work, and while won't help in all cases (like you said, need recursive types), will cover the vast majority?

```
    @overload
    def isinstance(
        __obj: object, __class_or_tuple: type | types.UnionType
    ) -> bool: ...
    @overload
    def isinstance(
        __obj: object, __class_or_tuple: tuple[type | types.UnionType | tuple[Any, ...], ...]
    ) -> bool: ...
```

**Comment by JelleZijlstra** [comment]
I'm not enthusiastic about complicating the builtin stubs for the benefit of a niche mypy feature, but if other typeshed maintainers are OK with this change, I won't stop it.

**Comment by karlicoss** [comment]
Ok, thanks! For me personally it's not that niche since I tend to use `isinstance(res, Exception)` a lot for [error handling](https://beepb00p.xyz/mypy-error-handling.html#kiss).
I might create a PR since it shouldn't take that much time, but also will understand if it's rejected, appreciate it's annoying to have special cases.

**Comment by AlexWaygood** [comment]
> I'm not enthusiastic about complicating the builtin stubs for the benefit of a niche mypy feature, but if other typeshed maintainers are OK with this change, I won't stop it.

I'm also a typeshed maintainer, and also am not particularly enthusiastic about this proposed change to the stub. The solution here is really for mypy to support recursive type aliases (#731). Then we could do:

```python
_IsInstanceType = type | UnionType | tuple[_IsInstanceType, ...]

def isinstance(__obj: object, __class_or_tuple: _IsInstanceType) -> bool: ... 
```

**Comment by karlicoss** [comment]
Yeah, fair enough, I understand recursive types would be the proper solution, but also it's not clear what the timeline is for it since it's pretty complicated, right? 
Perhaps it's more realistic to support some sort of suppression mechanism for the coverage report, although arguably this also has marginal benefits. Plus I could do something adhoc with the HTML/xml report rewriting.

**Comment by webknjaz** [comment]
With https://github.com/python/mypy/issues/731#issuecomment-2257486416, it seems like the recursive type aliases are in place now. Does `typeshed` still need updating in like @AlexWaygood said?

**Comment by webknjaz** [comment]
Looks like https://github.com/python/typeshed/pull/9134/files#diff-1580ddf7dc331234b0845ffb953b6f7a5f1e9afa15048ebc0762226a08f194b4R1333 implemented that already.

@alex it seems like this issue can be closed.
