### ISSUE TITLE
0.930: `mypyc --help` crashes with `KeyError: __file__`

### ISSUE THREAD

**Issue by asottile** [python/mypy#11894]
**Bug Report**

```
$ mypyc --help
Traceback (most recent call last):
  File "/tmp/y/venv/bin/mypyc", line 5, in <module>
    from mypyc.__main__ import main
  File "mypyc/__main__.py", line 18, in <module>
KeyError: '__file__'
```

**To Reproduce**

1. `mypyc --help`

**Expected Behavior**

not to crash

(Write what you thought would happen.)

**Actual Behavior**

see above

(Write what happened.)

**Your Environment**

- Mypy version used: `0.930`
- Mypy command-line flags: `--help`
- Mypy configuration options from `mypy.ini` (and other config files): n/a
- Python version used: 3.8.10
- Operating system and version: ubuntu 20.04

**Comment by A5rocks** [comment]
This is a known regression: https://github.com/python/mypy/issues/11700#issuecomment-1001288444

There will be a 0.931 release that solves this sooner or later, I believe.

**Comment by hauntsaninja** [comment]
Thanks for the report. This is obviously a pretty bad bug. Fixed on master and tests have been added to the wheel build to catch this kind of thing going forward.

Also linking https://github.com/mypyc/mypyc/issues/912#issuecomment-1002737352
