### ISSUE TITLE
empty list inferred as `List[<nothing>]` when assigning to union of `list` types

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11929]
```py
# error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "Union[List[int], List[str]]")  [assignment]
foo: list[int] | list[str] = []
```
https://mypy-play.net/?mypy=master&python=3.10&flags=show-error-codes%2Callow-redefinition%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=09a53c54f76ecf2899f83da3f3ebec46

**Comment by lopuhin** [comment]
Simplified example where I hit this:

```
$ cat t.py
from typing import Optional, List
def foo(x: Optional[List[int]]):
    print(x)
foo(sum([[1], [2]], []))

$ python t.py
[1, 2]

$ mypy t.py
t.py:8: error: Argument 1 to "foo" has incompatible type "Union[List[int], List[<nothing>]]"; expected "Optional[List[int]]"
Found 1 error in 1 file (checked 1 source file)

$ mypy --version
mypy 0.950 (compiled: yes)
```

**Comment by ilevkivskyi** [comment]
This works now
