### ISSUE TITLE
mypy does not infer correct return type for method of int subclass

### ISSUE THREAD

**Issue by rhjdjong** [python/mypy#11922]
**Bug Report**

`mypy` does not infer correct return type for `from_bytes` for subclassed `int` class

**To Reproduce**

Run `mypy` on the following minimal example:

```
from typing import Type, TypeVar

T = TypeVar("T", bound="MyInt")


class MyInt(int):
    @classmethod
    def unpack(cls: Type[T], value) -> T:
        return cls.from_bytes(value, "big", signed=False)


if __name__ == "__main__":
    x = MyInt.unpack(b'0010')
    assert isinstance(x, MyInt)
```

**Expected Behavior**

`mypy` reports no errors

**Actual Behavior**

`mypy` reports an error on line 9:

```
 error: Incompatible return value type (got "int", expected "T")
```

**Your Environment**

- Mypy version used: 0.930
- Mypy command-line flags: 
- Mypy configuration options from `mypy.ini` (and other config files): 
- Python version used: 3.10.0
- Operating system and version: Windows 10 Pro 21H1

**Comment by AlexWaygood** [comment]
It's a typeshed bug, see https://github.com/python/typeshed/pull/6842

**Comment by rhjdjong** [comment]
Thanks for the quick response. Looking forward to the arrival of the fix.

**Comment by AlexWaygood** [comment]
It should be fixed in the typeshed stubs now, but you may have to wait until mypy 0.940 to see it reflected in mypy :)
