### ISSUE TITLE
Type not inferred in comprehensions

### ISSUE THREAD

**Issue by pchanial** [python/mypy#11933]
**Bug Report**

The item type is not inferred in a comprehension

**To Reproduce**

Using https://mypy-play.net, for a generator:

```python
v: list[int] = [1, 2, 3]
reveal_type(_ for _ in v)
```

and also for a list comprehension:

```python
v: list[int] = [1, 2, 3]
reveal_type([_ for _ in v])
```

**Expected Behavior**

That the type int is inferred.

**Actual Behavior**

```
main.py:2: note: Revealed type is "typing.Generator[Any, None, None]"
````

```
main.py:2: note: Revealed type is "builtins.list[Any]"
````

**Your Environment**
mypy playground
- Mypy version used: 0.930
- Python version used: 3.10

**Comment by ktbarrett** [comment]
```python
v: list[int] = [1, 2, 3]
reveal_type(i for i in v)  # Revealed type is "typing.Generator[builtins.int*, None, None]"
reveal_type([i for i in v])  # Revealed type is "builtins.list[builtins.int*]"
```

The name `_` is used as a "throw-away" variable idiomatically. My guess is that mypy globally sets the variable `_` to `Any` so you can "throw away" any value without a type error.

**Comment by hauntsaninja** [comment]
Kaleb is correct.
If (like me) you're curious where it happens, here's the code link: https://github.com/python/mypy/blob/31586774b7f801cb185c866f35e954c4ef6ffd55/mypy/semanal.py#L2872
