### ISSUE TITLE
Generating more detailed class attribute typing other than Any

### ISSUE THREAD

**Issue by wj-Mcat** [python/mypy#11930]
**Feature**
In our project, all of developers follow the strict type annotation rules. So if we use the subgen tool of mypy, it should generate more clear class attribute.

I understand your design: `The stubs will be much more useful if you add more precise type annotations, at least for the most commonly used functionality.` But if the generated type annotation is more clear, it seems that it will decrease the work of developers.

**Pitch**

I take the example from your [official docs](https://mypy.readthedocs.io/en/stable/stubgen.html#automatic-stub-generation-stubgen):

```python
from other_module import dynamic

BORDER_WIDTH = 15

class Window:
    parent = dynamic()
    def __init__(self, width, height):
        self.width = width
        self.height = height

def create_empty() -> Window:
    return Window(0, 0)
```

But, in the modern project, this is the ugly code which contains less type annotations.  so here are our teams strict code:

```python
from other_module import dynamic, DynamicType

BORDER_WIDTH = 15

class Window:
    parent: DynamicType = dynamic()
    def __init__(self, width: int, height: int):
        self.width: int = width
        self.height: int = height

def create_empty() -> Window:
    return Window(0, 0)
```

The code below is expected: 

```python
from typing import Any

BORDER_WIDTH: int = ...

class Window:
    parent: DynamicType = ...
    width: int = ...
    height: int = ...
    def __init__(self, width: int, height: int) -> None: ...

def create_empty() -> Window: ...
```

But all of types of `width` and `height` attribute in generated stubfile is `Any`. If it's 18 years now, it's probably right. But it's 22 years now. We will require full & strict type anntations in open-source project.  So, the attribute of python class should not be `Any` otherwise it will make the code-complete confused in IDE . How do you think about it?

Or we can add an argument to indicate whether we need to turn on more detailed type annotation in generated stubfile. How do you think about it? 

`Any` is too vague to make project more clear. If you agree, I will try to improve this feature. Looking forward to discuss with you.

**Comment by erictraut** [comment]
Out of curiosity, if your code is fully annotated, why do you want to generate type stubs for it? I presume this is library code you're talking about. Many libraries are now shipping as "py.typed" (as per [PEP 561](https://www.python.org/dev/peps/pep-0561/)) with inlined types.

**Comment by wj-Mcat** [comment]
Yes, I think I get the wrong direction. Thanks for your timely & biting suggestion, I will use `py.typed` for full annotated code.
