### ISSUE TITLE
Optional value is not properly inferred for a condition 

### ISSUE THREAD

**Issue by mykola-mokhnach** [python/mypy#11977]
**Bug Report**

Please check the below code for more details.

**To Reproduce**

```python
    @dataclass
    class PresetsSearchQuery(BaseModel):
        kinds: List[PresetKind] = field(default_factory=list)
      ....
    search_query: PresetsSearchQuery

    or_condition: Optional[QueryCondition] = QueryCondition() if search_query.kinds else None
    if PresetKind.RECENT in search_query.kinds:
        # assert or_condition
        or_condition.add_conditions(f'{RECENT_TABLE}.preset_id IS NOT NULL', MISSING)
```

**Expected Behavior**

I expect `or_condition` variable to be assumed as always defined, because `if PresetKind.RECENT in search_query.kinds` would only work if `or_condition` is not None.

**Actual Behavior**

mypy complains about the last line:  `error: Item "None" of "Optional[QueryCondition]" has no attribute "add_conditions"`. It is necessary to uncomment the above assertion to get rid of this error.

**Your Environment**

- Mypy version used: 0.931
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files): 
```
[mypy]
python_version = 3.9
```
- Python version used: 3.9.2
- Operating system and version: macOS 12.0.1

**Comment by JelleZijlstra** [comment]
Type checkers are unlikely to support this kind of cross-variable dependency. You should refactor your code to make it more clear to the type checker, for example by putting all the code in an `if search_query.kinds:` block.
