### ISSUE TITLE
branch with generic type narrowed to `<nothing>` treated as reachable

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11976]
```py
foo: list[str]
if isinstance(foo, list):
    reveal_type(foo) # note: Revealed type is "list[str]"
else:
    # error: Unused "type: ignore" comment
    # note: Revealed type is "<nothing>"
    reveal_type(foo) #type:ignore[unreachable]
```
https://mypy-play.net/?mypy=master&python=3.10&flags=show-error-codes%2Callow-redefinition%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=491d109a359283211d39cd01c908de91

**Comment by sobolevn** [comment]
I don't see a problem here 🤔 

There's no error generated (because `reveal_type` is not counted as unreachable code on purpose). So, no error = unused `# type: ignore`.

Do you agree?

**Comment by DetachHead** [comment]
it still happens when not using `reveal_type`
```py
foo: list[str]
if isinstance(foo, list):
    print(1)
else:
    print(1) # no error here but it's unreachable
```
https://mypy-play.net/?mypy=master&python=3.10&flags=show-error-codes%2Callow-redefinition%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=516e1cbce0b89517ec04016eca56e1cc

**Comment by KotlinIsland** [comment]
> I don't see a problem here 🤔
> 
> There's no error generated (because `reveal_type` is not counted as unreachable code on purpose). So, no error = unused `# type: ignore`.

@sobolevn That is not true, a `reveal_type` in unreachable code is not analyzed at all:
```py
a = 1
if False:
    reveal_type(a)  # error: Statement is unreachable
if False:
    reveal_type(a)  # type: ignore[unreachable]
```

**Comment by sobolevn** [comment]
Please, see https://github.com/python/mypy/pull/11443

**Comment by KotlinIsland** [comment]
This issue looks the same as #11437

**Comment by DetachHead** [comment]
this seems to be fixed now, though perhaps a test should be added so it doesn't break again

**Comment by erictraut** [comment]
Yes, this bug appears to have been fixed. This doesn't repro with mypy 1.5.
