### ISSUE TITLE
PEP 604 union syntax does not work for TypedDict

### ISSUE THREAD

**Issue by astrojuanlu** [python/mypy#11987]
When writing something like

```python
LegacyImages = Literal["stable", "latest", "testing"]

class LegacyImageBuild(TypedDict):
    image: LegacyImages


class APTPackagesBuild(TypedDict):
    apt_packages: list[str]

Build = Union[LegacyImageBuild, APTPackagesBuild]
```

everything seems to work, but if instead I do

```
Build = LegacyImageBuild | APTPackagesBuild
```

then I get the following error:

```
src/readthedocs_assistant/types.py:46:9: error: Invalid type alias: expression is not a valid type  [misc]
    Build = LegacyImageBuild | APTPackagesBuild
            ^
src/readthedocs_assistant/types.py:46:9: error: Unsupported left operand type for | ("Type[LegacyImageBuild]")  [operator]
    Build = LegacyImageBuild | APTPackagesBuild
            ^
```

I'm using this config:

```
[mypy]
python_version = 3.8
warn_redundant_casts = True
warn_unused_configs = True
pretty = True
show_error_codes = True
show_error_context = True
show_column_numbers = True

disallow_any_generics = True
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_unused_ignores = True
warn_return_any = True
no_implicit_reexport = True

# More strict checks for library code
[mypy-readthedocs_assistant]
disallow_untyped_defs = True

# Ignore certain missing imports
[mypy-jsonschema.*]
ignore_missing_imports = True
```

**Comment by astrojuanlu** [comment]
(Sorry, I don't know how I arrived to python/typing, indeed I wanted to file this in here)

**Comment by AlexWaygood** [comment]
Is the issue not the fact that you have `python_version = 3.8` in your config file? The expression `Build = LegacyImageBuild | APTPackagesBuild` will fail at runtime on Python <3.10. I can't reproduce the issue with `python_version = 3.10`: https://mypy-play.net/?mypy=latest&python=3.10&gist=d4edf4d7a9ea068c26236356a2e46a75

**Comment by astrojuanlu** [comment]
Thanks for looking into this @AlexWaygood . Isn't `from __future__ import annotations` supposed to help here? (I don't remember now if I was using it or not)

**Comment by AlexWaygood** [comment]
`from __future__ import annotations` would make code like this valid, as the annotation would be stringified:

```python
Build: LegacyImageBuild | APTPackagesBuild
```

But the code you have in your minimal repro is different:

```python
Build = LegacyImageBuild | APTPackagesBuild
```

This is a runtime assignment, so whether or not `from __future__ import annotations` is enabled would make no difference.

**Comment by astrojuanlu** [comment]
Thanks for the clarification, now I get it. Time for me to upgrade then :) Closing!

**Comment by AlexWaygood** [comment]
> Thanks for the clarification, now I get it.

Glad I could help :)
