### ISSUE TITLE
Type inference problem with union of `TypedDict` and overlapping properties

### ISSUE THREAD

**Issue by astrojuanlu** [python/mypy#11988]
**Bug Report**

MyPy infers types incorrectly when there are unions of `TypedDict` with overlapping properties (more info in the section below). Possibly related to https://github.com/python/mypy/issues/11987.

Problematic type definitions:

```python
class A(TypedDict):
    a: str

class BC(TypedDict, total=False):
    other: str
    a: str

Spec = Union[A, BC]

class Config(TypedDict):
    prop: Spec
```

Somehow MyPy gets confused by `A` and `BC` both having a possible key with the same name and type. However, if I change the name or type of the key in one of the dictionaries, the problem does not appear. For example, with this code:

```python
def main_prop(build: Spec) -> None:
    reveal_type(build)
    print(build)

def main_config(config: Config) -> None:
    reveal_type(config["prop"])
    print(config["prop"])

if __name__ == "__main__":
    custom_config = Config({"prop": {"other": "..."}})

    main_prop(custom_config["prop"])
    main_config(custom_config)
```

Each `reveal_type` should give exactly the same, but they don't.

**To Reproduce**

Scripts and MyPy configuration in https://gist.github.com/astrojuanlu/be60d6890b91d3588e27958f83ac9cb4

```
git clone https://gist.github.com/astrojuanlu/be60d6890b91d3588e27958f83ac9cb4 typeddict_problem
cd typeddict_problem
mypy .
```

**Expected Behavior**

This is the output I would expect:

```
$ mypy .
main.py: note: In function "main_prop":
main.py:5:17: note: Revealed type is "Union[TypedDict('config_types.A', {'a': builtins.str}), TypedDict('config_types.BC', {'other'?: builtins.str, 'a'?: builtins.str})]"
main.py: note: In function "main_config":
main.py:10:17: note: Revealed type is "Union[TypedDict('config_types.A', {'a': builtins.str}), TypedDict('config_types.BC', {'other'?: builtins.str, 'a'?: builtins.str})]"
```

**Actual Behavior**

```
$ mypy .
main.py: note: In function "main_prop":
main.py:5:17: note: Revealed type is "Union[TypedDict('config_types.A', {'a': builtins.str}), TypedDict('config_types.BC', {'other'?: builtins.str, 'a'?: builtins.str})]"
main.py: note: In function "main_config":
main.py:10:17: note: Revealed type is "TypedDict('config_types.A', {'a': builtins.str})"
```

**Your Environment**

- Mypy version used: 0.931
- Mypy command-line flags: (see `mypy.ini` above)
- Python version used: 3.9.9
- Operating system and version: Linux Mint 20.3 Cinnamon

**Comment by brendon-boldt** [comment]
This seems to be fixed in version `0.990`.
