### ISSUE TITLE
Warn about unnecessary casts

### ISSUE THREAD

**Issue by hackaugusto** [python/mypy#12000]
**Feature**

A flag to warn about unnecessary casts.

**Pitch**

When introducing typing to a large code base, sometimes `cast`s are useful. When the quality of the annotations improve, some of those casts become obsolete, it would be nice to have a flag to warn about those, just like we have for the unnecessary `# type: ignore`:

```python
from typing import cast


def plus(a: int, b: int) -> int:
    return a + b


plus(1, 2)
plus(1, cast(int, 2))  # warning for code like this
```

**Comment by JelleZijlstra** [comment]
We already have that: https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-cast-is-not-redundant-redundant-cast

**Comment by hackaugusto** [comment]
Cool, I missed it. Thanks!
