### ISSUE TITLE
`# type: ignore` not recognised after comment

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#12014]
This fails:
`            self._t = t.__qualname__  # If concrete class  # type: ignore[union-attr]`
But, this works:
`            self._t = t.__qualname__  # type: ignore[union-attr]  # If concrete class`

Expectation is that the comment should be recognised at any point on the line.

Version: 0.931

**Comment by ethanhs** [comment]
Hi! Type ignores should go before other comments, which is the documented behavior. Changing this would mean it would be impossible to comment out a type ignore while working on code, which I think is a usability loss.
