### ISSUE TITLE
Refactor checker.py 

### ISSUE THREAD

**Issue by 97littleleaf11** [python/mypy#12027]
Currently the checker.py is quite large. Splitting some stateless funcs into submodules might be a good idea.

cc @JukkaL @ilevkivskyi @sobolevn

**Comment by 97littleleaf11** [comment]
Here is some thoughts from @JukkaL : 
https://github.com/python/mypy/pull/12026#issuecomment-1047844048

**Comment by hauntsaninja** [comment]
Closing since this isn't too concrete, but feel free to open PRs
