### ISSUE TITLE
(🎁) Modernization report with recommendations

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12031]
**Feature**

Mypy should have a report mode that lists all the places that old references(old style code) are used.

**Pitch**
I guess you would have to supply the minimum python version.
```py
a: Optional[int]  # Recommend: `int | None `
b: List[int]  # Recommend: `list[int]`
c: Union[int, str]  # Recommend: `int | str`
from typing_extensions import old_reference  # Recommend `from typing import old_reference`
from typing import Mapping # Recommend `from collections.abc import Mapping`
```

**Comment by JelleZijlstra** [comment]
https://github.com/asottile/pyupgrade already does much of this. We're also working on similar recommendations for stub files in https://github.com/pycqa/flake8-pyi.

I don't think this feature is a good fit for mypy.
