### ISSUE TITLE
mypy fails on context  manager

### ISSUE THREAD

**Issue by rvaquerizor** [python/mypy#12041]
**Bug Report**

Mypy fails on context manager invocation for a decorated function.
 
**To Reproduce**

Steps:

1. Decorate a function _f_ with context manager decorator (@contextlib.contextmanager)
2. The return type of the decorated function is Generator[T, None, None], where T can be any type
3. Now invoke the function using context manager syntax `with`
4. mypy fails saying  "Generator[Any, None, None]" has no attribute "__enter__"; maybe "__iter__"?

**Expected Behavior**

mypy should be aware of the function being decorated as a context manager, and so, it supports the Context Manager Protocol.
Instead, it thinks it is a plain generator, not wrapped into a context manager object.

**Actual Behavior**

mypy thinks it is a plain generator, not wrapped into a context manager object.

`"Generator[Any, None, None]" has no attribute "__enter__"; maybe "__iter__"
`

**Environment**

- Mypy version used: 0.931
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10
- Operating system and version: Ubuntu 21.10

**Comment by A5rocks** [comment]
Could you provide some code? This seems to work:
```py
from typing import TypeVar, Generator, Any
from contextlib import contextmanager

T = TypeVar("T")

@contextmanager
def f(x: T) -> Generator[T, None, None]:
    yield x

with f(5) as n:
    print(n)
```

**Comment by rvaquerizor** [comment]
@A5rocks 
For some reason, I can only reproduce it on my existing projects.

If I create a new basic project, with just the code you put above, then mypy does not complain at all:
`
$ mypy contextmanager
Success: no issues found in 2 source files    
`

But that is not the case with my existing projects:
`
myproject.py:47: error: "Generator[Any, None, None]" has no attribute "__enter__"; maybe "__iter__"?
`

The **with** statement used is identical in both cases.

And both the existing project and the new basic one use the same mypy versions:

```
$ poetry show mypy
name         : mypy
version      : 0.931
description  : Optional static typing for Python

dependencies
 - mypy-extensions >=0.4.3
 - tomli >=1.1.0
 - typing-extensions >=3.10 
```        


The context manager is available as a dependency I publish to my local Pypi server that I have installed in both projects' virtual envs. Then, I do something like the following:
`
from mystuff import my_context_manager
`

Not sure what is going on in here .....
Initially, I thought that it could be a problem in the way the typing is exposed from my dependency module, but that does not seem to be the case, since the new basic project does not have any mypy issue.

Maybe there is some side effect from modules/dependencies used on my existing projects.

**Comment by A5rocks** [comment]
One very nice trick is you can `reveal_type(<thing>)` to see what mypy thinks it is. I'm not sure how to help beyond that, just remember `Generator[Something, None, None]` is not the type you want to see.

Maybe, what's your definition for `my_context_manager` if you can share? (With unnecessary details scrubbed of course).

**Comment by rvaquerizor** [comment]
@A5rocks 
Thanks a lot for the prompt reply.

This is the definition of my context manager in the dependency module:

```
@contextlib.contextmanager
def my_context_manager(dbname: str, ...) -> Generator[records.Database, None, None]:

```

Thanks for the reveal_type trick. I was not aware of it .....

Using it on both projects, I get exactly the same result, wrapping both the function and the value obtained from the yield.

- On the new one:

```
# for the decorated function:
contextmanager/cm.py:5: note: Revealed type is "def (dbname: builtins.str, ...) -> contextlib._GeneratorContextManager[Any]"
```

```
# for the value obtained from the yield:
contextmanager/cm.py:6: note: Revealed type is "Any" 
```

- On the existing one:

```
# for the decorated function:
file.py:48: note: Revealed type is "def (dbname: builtins.str, ...) -> contextlib._GeneratorContextManager[Any]"
```

```
# for the value obtained from the yield:
file.py:49: note: Revealed type is "Any"   
```

**Comment by rvaquerizor** [comment]
OK, I am dumb ..... I found what the problem is. I did not realise I had an associated ".pyi" where the import of the dependency module was not done. So, this was taking precedence and the type of the decorated function was not known to mypy.

Sorry for the hassle.
