### ISSUE TITLE
stubtest: Honor VERSIONS file for sub-modules

### ISSUE THREAD

**Issue by srittau** [python/mypy#12062]
**Bug Report**

Cf. python/typeshed#6789. Currently, stubtest doesn't honor version ranges in stdlib's `VERSIONS` file. For example, when testing stdlib with Python 3.9, stubtest will complain about `asyncio.mixins failed to find stubs`, even though `asyncio.mixins` is marked as `asyncio.mixins: 3.10-` in `VERSIONS`.

**Your Environment**

- Mypy version used: as of today, typeshed uses mypy 0.931

**Comment by srittau** [comment]
Cc @sobolevn

**Comment by sobolevn** [comment]
I am able to reproduce it locally, let's see why it happens.
