### ISSUE TITLE
Confusing error about __attrs_attrs__ when using multiple inheritance

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#12065]
This code now generates an error about class AB:

```py
import attr

@attr.s
class A:
    x = attr.ib(type=int)

@attr.s
class B:
    y = attr.ib(type=int)

# Definition of "__attrs_attrs__" in base class "A" is incompatible with definition in base class "B"
class AB(A, B):
    pass
```

The code is arguably questionable, and the error goes away if we decorate AB with `@attr.s`, but that's not clear from the error message. It would be better to add a note, such as something like this:

```
... :note: Should class "AB" use the @attr.s decorator?
```

This started happening after #11794, and it might be considered a minor regression because of the confusing message.

(Behind the scenes, a `__attrs_attrs__` attribute gets generated with a class-specific named tuple as the type. These named tuples aren't compatible with each other.)

cc @Tinche

**Comment by Tinche** [comment]
Interesting, I can take a look at this.

**Comment by Tinche** [comment]
In runtime,

```
>>> AB.__attrs_attrs__
(Attribute(name='x', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'int'>, converter=None, kw_only=False, inherited=False, on_setattr=None),)
```
So I'm guessing it just follows the MRO and gets the class attribute from A.

Here's the equivalent situation without attrs:

```
class C:
    _test_: str = "a"


class D:
    _test_: int = 1


class CD(C, D):
    pass
```
This is a Mypy error (`error: Definition of "_test_" in base class "C" is incompatible with definition in base class "D"`).

So if we want to keep this behavior and still raise an error, the note approach is the way to go?

**Comment by JukkaL** [comment]
Yeah, the note approach seems fine. If you don't use `@attr.s` in the derived class, the inherited `__init__` doesn't initialize all the attributes, the value of `__attrs_attrs__` won't include all attributes, etc.

**Comment by JelleZijlstra** [comment]
This feels similar to #12008. (Does attrs autocreate `__match_args__`?)

**Comment by Tinche** [comment]
> This feels similar to #12008. (Does attrs autocreate `__match_args__`?)

It does.
