### ISSUE TITLE
Improve the "Argument must be a mapping" error message

### ISSUE THREAD

**Issue by DevilXD** [python/mypy#12070]
**Feature**

This could also be classified as a bug report, but it's also a feature request. Consider code like this:

```py
from typing import Any, Optional

def test(**kwargs):
    ...

kwargs: Optional[Any]
test(**kwargs)
```

Now, this is obviously wrong on purpose, and in latest MyPy, results in this error message:

```
error: Argument after ** must be a mapping
```

The problem with this message is that, it doesn't say what exactly is wrong, unlike when you normally mismatch types where it says: `Argument 1 to "test" has incompatible type "Union[int, str]"; expected "bool"`, for example. In my case, I had a variable with the same name inferring `Optional[Any]` higher up in the code, and tracking down the root cause took me good 10 minutes,

**Pitch**

Even though `**kwargs` usage like this is uncommon, having a similarly improved message would help with debugging why this may be happening. Something like: `Argument after ** to "test" has incompatible type "Union[Any, None]", expected "Mapping[str, Any]"` should help a lot.

**Comment by JelleZijlstra** [comment]
Yes, we should improve this. PR welcome!

**Comment by himanshi-2602** [comment]
@JelleZijlstra 
I would like to work on this issue.
I am a beginner but really interested in open source.

**Comment by JelleZijlstra** [comment]
Go for it! I haven't looked at the code for this error, but here's what I would do:

- Find the place where the `must be a mapping` error is raised. Start by grepping for this string, then keep grepping to look for the code where we actually perform the check.
- Find out how to get additional information to make the error more informative. Look for examples where we already give a more informative error, e.g. when there's an argument type mismatch.
- Update the code you found to give the more detailed error, and update the test suite.

**Comment by himanshi-2602** [comment]
@JelleZijlstra  
Thanks for the response.

**Comment by PurnaChandraMansingh** [comment]
Hi @JelleZijlstra, I am new to open source and really interested to contribute my favorite language i.e python, may I work on this issue or could you please suggest any other beginner-friendly issue to start with. Thanks!!

**Comment by JelleZijlstra** [comment]
This is a pretty good one to start! Everyone reading this should feel free to go ahead, start coding, and submit a PR.

**Comment by PurnaChandraMansingh** [comment]
Thanks @JelleZijlstra

**Comment by MihirHundiwala** [comment]
Hello, even i am a beginner to open source contribution, found this good-first-issue, so i have managed to find the file where we raise the issue 'Argument after ** must be a mapping' but i dont know what grepping is, how it is done, also how can i debug the process step by step, i have know the python lib 'pdb' for debugging but how do i call it will mypy
