### ISSUE TITLE
mypy does not ignore on multiline function definitions

### ISSUE THREAD

**Issue by andylamp** [python/mypy#12087]
**Bug Report**

Types for functions are not being correctly ignored when the function spans multiple lines.

**To Reproduce**

Below is a toy example that exhibits the aforementioned pathological behavior:

```python
class A:
    def my_func(self, a_long_variable_this_big: int, b_long_variable_this_big: int):
        pass


class B(A):
    def my_func(
        self,
        a_long_variable_this_big: int,
        b_long_variable_this_big: int,
        c_long_variable_this_big: int,
        d_long_variable_this_big: int,
    ):  # type: ignore
        pass


class C(A):
    def my_func(self, a_long_variable_this_big: int, b_long_variable_this_big: int):  # type: ignore
        pass
```

**Expected Behavior**

Types to be ignored correctly in both `my_func` definitions in both class `B` and `C`.

**Actual Behavior**

Types get ignored in class `C` correctly when it does not spill to newlines. However, in class `B` the types are not ignored and produce an error.  

```text
example.py:39: error: Signature of "my_func" incompatible with supertype "A"
example.py:39: note:      Superclass:
example.py:39: note:          def my_func(self, a_long_variable_this_big: int, b_long_variable_this_big: int) -> Any
example.py:39: note:      Subclass:
example.py:39: note:          def my_func(self, a_long_variable_this_big: int, b_long_variable_this_big: int, c_long_variable_this_big: int, d_long_variable_this_big: int) -> Any
```

This happens often enough when using `black` code formatting tool that prompted this bug report.

**Your Environment**

- Mypy version used: `v0.931`
- Mypy command-line flags: I run it through the `mypy` pre-commit hook.
- Mypy configuration options from `mypy.ini` (and other config files): the only flag that is used is `ignore_missing_imports = True`
- Python version used: 3.9 x64
- Operating system and version: tested on Ubuntu Linux 20.04 and 21.10

**Comment by kreathon** [comment]
I am not sure if this is actually a bug, because `# type: ignore` suppresses errors on a line basis. The line of the function definition (and thus the line of the error) is the line of the first character of the definition.

You can still write:

```
class B(A):
    def my_func(   # type: ignore
        self,
        a_long_variable_this_big: int,
        b_long_variable_this_big: int,
        c_long_variable_this_big: int,
        d_long_variable_this_big: int,
    ):
        pass
```

Or am I missing your point?

**Comment by andylamp** [comment]
aha, right - I see. I thought that by "line" meant where the definition ended in such cases. I could argue that putting at the last line of the function definition is more elegant, but I suppose as long as I can ignore errors by putting the `type: ignore` in any location works as well.

Closing unless you think it is worth more attention, in which case feel free to reopen.
