### ISSUE TITLE
mypy not checking code within child scope

### ISSUE THREAD

**Issue by loynoir** [python/mypy#12085]
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

(Write your steps here:)

```sh
$ mypy reproduce.py
```

```python
# reproduce.py
def DPoint(w: int, *, x: int, y: int):
    return locals()


def foobar():
    DPoint(
        "2",
        x="1",
        y=1,
    )


class Foo:
    def bar(self):
        DPoint(
            "2",
            x="1",
            y=1,
        )


DPoint(
    "2",
    x="1",
    y=1,
)
```

**Expected Behavior**

```txt
error: Argument 1 to "DPoint" has incompatible type "str"; expected "int"
error: Argument "x" to "DPoint" has incompatible type "str"; expected "int"
error: Argument 1 to "DPoint" has incompatible type "str"; expected "int"
error: Argument "x" to "DPoint" has incompatible type "str"; expected "int"
error: Argument 1 to "DPoint" has incompatible type "str"; expected "int"
error: Argument "x" to "DPoint" has incompatible type "str"; expected "int"
```

(Write what you thought would happen.)

**Actual Behavior**
```txt
error: Argument 1 to "DPoint" has incompatible type "str"; expected "int"
error: Argument "x" to "DPoint" has incompatible type "str"; expected "int"
```

(Write what happened.)

**Your Environment**

- Mypy version used: 0.931
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10.2 / 3.9.9
- Operating system and version:

**Comment by JelleZijlstra** [comment]
Mypy was built on the idea of gradual typing, where you start gradually type checking your code by adding annotations to it. Personally I don't feel that part of the idea has worked out very well, but it's still what mypy is built on.
