### ISSUE TITLE
Type is int in boolean logic with sys.flags

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#12099]
```
a: bool
b: int
reveal_type(a or not b)  # Revealed type is "builtins.bool"
reveal_type(sys.flags.dev_mode or not sys.flags.ignore_environment)  # Revealed type is "builtins.int"
```

I can find no reason why this should be interpreted as int. `dev_mode` is `bool` and `ignore_environment` is `int`. The `not` will convert the `int` to a `bool`, as correctly inferred in the first example.

Code from here: https://github.com/aio-libs/aiohttp/pull/6549/files#diff-b797dd8733928df191ba2061121ab8b69976c185fcbfad4534891d3252b9ac30R84

- Mypy version used: 0.931
- Mypy configuration options: https://github.com/aio-libs/aiohttp/blob/master/.mypy.ini

**Comment by AlexWaygood** [comment]
`sys.flags.dev_mode` was previously incorrectly annotated as `bool` in the typeshed stubs, but this has recently been corrected (https://github.com/python/typeshed/pull/6816). The change has yet to be reflected in mypy, but should be fixed after the next typeshed sync p.

**Comment by Dreamsorcerer** [comment]
Ah, great, thanks.
