### ISSUE TITLE
Generic class inheritance produces unexpanded function type variable

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#12101]
This is a very strange bug that only seems to happen when I import the base class.  So, this issue requires installing [tjax](https://github.com/NeilGirdhar/tjax/) (it's on PyPi, so just `pip install tjax` will work).
```python
from typing import Generic, TypeVar
from tjax._src.fixed_point.base import IteratedFunctionBase

State = TypeVar('State')
Parameters = TypeVar('Parameters')
Trajectory = TypeVar('Trajectory')


class SimpleScan(IteratedFunctionBase[Parameters, State, Trajectory, State],
                 Generic[Parameters, State, Trajectory]):
    pass

class EncodingSampler(SimpleScan[int, int, int]):
    pass

e = EncodingSampler()
reveal_type(e.sample_trajectory)  # "F`-`"!!
```

Replacing the import of `IteratedFunctionBase` with an import of a local source file (`from b import IteratedFunctionBase`) makes the problem go away:
```python
a.py:20: note: Revealed type is "def (theta: builtins.int*, initial_state: builtins.int*, maximum_iterations: builtins.int, tap_function: Union[def (None, typing.Sequence[Tuple[builtins.str, builtins.dict[builtins.str, Any]]]), None]) -> Tuple[builtins.int*, builtins.int*]"
```
This is extremely surprising to me :smile:

**Comment by soma2000-lang** [comment]
I would like to work on this issue

**Comment by NeilGirdhar** [comment]
@soma2000-lang Awesome, thank you very much!

**Comment by erictraut** [comment]
It appears that this bug has been addressed. When using mypy 1.5, I'm not able to repro the buggy behavior described above.

**Comment by NeilGirdhar** [comment]
Thanks!
