### ISSUE TITLE
no error when reading global variable without  `global` keyword when assigning to it

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#12139]
```py
foo: int = 1

def bar() -> None:
    foo
    foo = 2
```
https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-context%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Clocal-partial-types%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=05e07294e647133f277ca771bde443ab

**Comment by erictraut** [comment]
This appears to have been fixed. Mypy 1.5 now correctly generates an error in this case.

**Comment by DetachHead** [comment]
yeah the new `used-before-def` error seems to cover this case
