### ISSUE TITLE
Overriding non-enumeration attributes in Enum subclass fails

### ISSUE THREAD

**Issue by flaeppe** [python/mypy#12132]
**Bug Report**

Inheriting an `Enum`-class and overriding, for example, a dunder-attribute fails to typecheck. Although it works fine during runtime.

**To Reproduce**

```python
from enum import Enum


class BaseEnum(Enum):
    __something__ = 3


class SomeEnum(BaseEnum):
    __something__ = 2
```

**Expected Behavior**

It should typecheck, as it passes during runtime.

**Actual Behavior**

```
error: Cannot override final attribute "__something__" (previously declared in base class "BaseEnum")
```

**Your Environment**

- Mypy version used: `master` (26fdd456b7e665c3c0f161234ee48b9e6144940d)
- Mypy command-line flags: -
- Mypy configuration options from `mypy.ini` (and other config files): 
```
strict_optional = True
```
- Python version used: `3.9.4`
- Operating system and version: MacOS Catalina `10.15.6`

---

The issue has also been briefly mentioned in these places:

- https://github.com/python/mypy/issues/11850#issuecomment-1030679580
- https://github.com/python/mypy/issues/10857#issuecomment-1010459198

**Comment by sobolevn** [comment]
@flaeppe are you interested in working on this? 🙂

**Comment by flaeppe** [comment]
I could take a swing at it if I find some time, though I'm not too familiar with mypy code so I'm not sure what'll come out of it. 

If someone else feels like working on it, please go ahead
