### ISSUE TITLE
Implement Const type to indicate non-rebindable variables/attributes

### ISSUE THREAD

**Issue by hashstat** [python/mypy#1214]
As a Python developer, I would like a _Const_ type so that I can indicate that a variable or attribute may not be rebound to another value. This would be especially useful for module and class constants, but could also be helpful for instance attributes that really shouldn't be modified. Not only does it help prevent accidentally overwriting constants, it would hopefully reduce the need to use `@property` on non-critical attributes. Here is a contrived example:

``` python
GRUNT = 0   # type: Const
MANAGER = 1   # type: Const


class Employee:
    kind = GRUNT   # type: Const

    def __init__(self, idnum: int, name: str):
        self.id = idnum   # type: Const
        self.name = name


class Manager(Employee):
    kind = MANAGER   # type: Const
```

`kind = MANAGER   # type: Const` reqiures the _Const_ type to rebind _kind_ without an error just as a const variable in C requires a cast during reassignment to quiet compiler warnings/errors.

I'm not sure if it makes sense to allow _Const_ to take parameters as the type can be inferred in most cases. One might want other variables, such as those passed into functions, to be const, in which case it makes sense to allow _Const_ to take parameters. Here is an example:

``` python
def frobnicate(kind: Const[int]) -> None:
    kind = 5   # Error
    kind = 6   # type: Const  # Okay
```

**Comment by JukkaL** [comment]
Early in the history of mypy I was actually planning to have something like this, but I guess I later forgot about it. This would likely require a PEP 484 (and potentially `typing`) change.

**Comment by davidroeca** [comment]
Const in Python could have similar guarantees to something like JavaScript ES6's const, to prevent reassignment https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

A clever programmer would be able to get around this through methods that mutate, or by a shared reference, but the guard rails are still nice. 

Alternatively, it could only be allowed for immutable non-container primitives such as int or str, or maybe even extended to tuples/namedtuples of immutable primitives as well

**Comment by JukkaL** [comment]
We are now considering something like this, perhaps spelled as `Final`. An interesting use case would be with literal types (another potential new feature) -- it would allow mypy to infer things like `if X:` never being taken if there is `X: Final = False`.
