### ISSUE TITLE
no error when making `abstractmethod` `final`

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#12164]
```py
from typing import final
from abc import ABC, abstractmethod

class Foo(ABC):
    @final
    @abstractmethod
    def foo(self) -> None: ...
```
https://mypy-play.net/?mypy=master&python=3.10&flags=show-error-codes%2Callow-redefinition%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=ca9254869c885fad1c4e53dda87390a6

**Comment by sobolevn** [comment]
Good one!

**Comment by sobolevn** [comment]
@AlexWaygood just checking if you are interested in working on this? It is a good entry-level issue. I will be happy to help with anything in the process 🙂

**Comment by AlexWaygood** [comment]
Interestingly, looks like this already (correctly) raises an error:

```python 
from typing import final
from abc import ABC, abstractmethod

@final
class Weird(ABC):
    @abstractmethod
    def bad(self) -> None: ...
```

**Comment by AlexWaygood** [comment]
I'm unassigning myself from this, as I already have a lot of projects on the go, and don't think I'll realistically get to this any time soon, since I regard it as fairly low priority.

I think it should be fairly easy to fix, though, so others should feel free to tackle it if they want to.

**Comment by nakatomotoi** [comment]
@AlexWaygood 
Hi, may I work on this issue?
This is my first issue to work on in mypy !

**Comment by AlexWaygood** [comment]
@nakatomotoi, yes, go for it!
