### ISSUE TITLE
mypy error reporting should include column position

### ISSUE THREAD

**Issue by shivawu** [python/mypy#1216]
Currently it seems that only line number is included, and confusion will be introduced when there's multiple errors in the same line. Is there any plans to improve this?

```
typecheck_error.py: note: In function "f":
typecheck_error.py:2: error: Unsupported operand types for * ("str" and "complex")
typecheck_error.py:2: error: Incompatible return value type: expected builtins.int, got builtins.complex
```

**Comment by JukkaL** [comment]
It would be nice to have the column numbers as well. We are planning a parser rewrite and that might make this easy enough to implement.

**Comment by ddfisher** [comment]
Yeah, the parser rewrite should make this info easily available.

**Comment by bavardage** [comment]
was there any progress here? pretty interested in this too

**Comment by gvanrossum** [comment]
I apologize, we have been occupied with higher priority projects. Thanks for showing your interest though -- we'll be sure to bump the priority eventually. (We also accept PRs of course.)

**Comment by bavardage** [comment]
happy to attempt a PR at some point, not super familiar with the code yet

thoughts:
 - add column info to node @ https://github.com/python/mypy/blob/master/mypy/nodes.py#L91
    - potentially also add start column, end column, start line, end line (?) 
 - modify the parser to add on this info (where it's available)

for the parser, this would mean modifying both fastparse, fastparse2 and parse?

**Comment by gvanrossum** [comment]
We're phasing out parse.py, but yes, both fastparse{,2}.py would need to be
updated. The big question is whether typed_ast, which we use for the actual
parser, is collecting this info. If not, we have to modify typed_ast first.

**Comment by gvanrossum** [comment]
This was done. Thanks to Ben Duffield! Note that you need to use `--show-column-numbers`.

**Comment by shivawu** [comment]
Thank you so much guys! This is amazing!
