### ISSUE TITLE
asyncio.Event's wait method's return type behaves strangely

### ISSUE THREAD

**Issue by DevilXD** [python/mypy#12175]
**Bug Report**

`asyncio.Event`'s `wait` method appears to behave strangely when it comes to its return type. The type definition says its return type is `Literal[True]`, yet the `reveal_type` in the "sample 1" code below says it becomes `bool`. I wasn't able to reproduce this with a user-made class, only with this particular case. I'm not sure if there's something with MyPy going on here, or there's something in my env that interferes here, so any pointers would be appreciated.

**To Reproduce**

Sample 1:
```py
import asyncio
from typing import Literal

event = asyncio.Event()

async def func() -> Literal[True]:
    result = await event.wait()
    reveal_type(result)
    return result
```

Sample 2:
```py
import asyncio
from typing import Literal

class MockEvent:
    async def wait(self) -> Literal[True]:
        ...

event = asyncio.Event()
mockevent = MockEvent()

async def func1() -> Literal[True]:
    result = await event.wait()
    reveal_type(result)
    return result

async def func2() -> Literal[True]:
    result = await mockevent.wait()
    reveal_type(result)
    return result
```

**Expected Behavior**

Both samples end up with `Literal[True]` as the revealed type, in every case.

**Actual Behavior**

Sample 1:
```
main.py:8: note: Revealed type is "builtins.bool*"
main.py:9: error: Incompatible return value type (got "bool", expected "Literal[True]")
Found 1 error in 1 file (checked 1 source file)
```

Sample 2:
```
main.py:13: note: Revealed type is "builtins.bool*"
main.py:14: error: Incompatible return value type (got "bool", expected "Literal [True]")
main.py:18: note: Revealed type is "Literal[True]"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: `0.931`
- Mypy command-line flags: `none`
- Mypy configuration options from `mypy.ini` (and other config files): `none`
- Python version used: `3.8.10`
- Operating system and version: `Win 7`

**Comment by AlexWaygood** [comment]
I think this is because the stub for `Event.wait` was changed only 10 days ago (https://github.com/python/typeshed/pull/7122), and mypy hasn't updated its bundled stubs on the master branch since then, let alone released a new version of mypy with the new signature.
