### ISSUE TITLE
TypeGuard methods should work on self

### ISSUE THREAD

**Issue by chadrik** [python/mypy#12176]
**Bug Report**

A `TypeGuard` written as a method should work similarly to one written as a function.

**To Reproduce**

Below you see that `TypeGuard` `Thing.is_b()` does not work, but `is_b(Thing)` does. 

```python
from typing_extensions import TypeGuard
from typing import Union

class Thing:
    def is_b(self) -> TypeGuard['ThingB']:
        return isinstance(self, ThingB)

class ThingA(Thing):
    pass

class ThingB(Thing):
    def do_b_thing(self):
        print("BBBBB")


def is_b(x: Thing) -> TypeGuard['ThingB']:
    return isinstance(x, ThingB)

x: Thing = ThingB()

if x.is_b():
    reveal_type(x)  # note: Revealed type is "Thing"
    x.do_b_thing()  # error: "Thing" has no attribute "do_b_thing"

# this works
if is_b(x):
    reveal_type(x)  # note: Revealed type is "ThingB"
    x.do_b_thing()
```

**Your Environment**

- Mypy version used:  0.931
- Python version used:  3.8.5
- Operating system and version:  Mac OS

**Comment by JelleZijlstra** [comment]
The PEP explicitly rejects this: https://www.python.org/dev/peps/pep-0647/#narrowing-of-implicit-self-and-cls-parameters. If you want to change that, the mypy issue tracker isn't the right place; could you open a discussion on the python/typing repo or the typing-sig mailing list instead?

**Comment by erictraut** [comment]
As @JelleZijlstra said, this is explicitly rejected from the PEP.

In object-oriented programming, it's generally not a good idea for a parent class to have knowledge of classes that derive from it. As such, I'd recommend making the `is_b` type guard function a stand-alone function (not a method within the `Thing` class) that accepts a `Thing` and returns a `TypeGuard[ThingB]`.
