### ISSUE TITLE
`mypy -` to read from stdin

### ISSUE THREAD

**Issue by shamrin** [python/mypy#12235]
**Feature**

Support `-` dash to read from stdin:
```
echo 'print("hello") | mypy -
```

(Currently, the example fails with `mypy: can't read file '-': No such file or directory`.)

The `-` dash could be used together with other files, to type-check across modules:
```
echo 'from somemodule import fun; fun("hello")' | mypy somemodule -
```

**Pitch**

The `-` dash is a common way to read from stdin. It's widely supported:

* [`python`](https://docs.python.org/3/using/cmdline.html): `echo "print('hello')" | python -`
* `cat`: `echo hello | cat -`
* [`black`](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#standard-input): `echo "print ( 'hello' )" | black -`

Previously, [`--stdin` option proposal](https://github.com/python/mypy/issues/2119) was rejected. This proposal is different, because it doesn't require a new option. 

**Real-world example**

One real-world example is type-checking Python examples in README.md, to make sure the examples are valid and up-to-date with an API:
```
codeblocks python README.md | mypy somemodule -
```

([codeblocks][] is a simple tool that extracts Markdown code blocks.)

The current work-around is using process substitution. It works, but requires bash-compatible shell and also knowledge of this feature:
```
mypy somemodule <(codeblocks python README.md)
```

Another example is type-checking the output of code generation scripts:

```
generate-some-code | mypy -
```

[codeblocks]: https://github.com/shamrin/codeblocks

**Comment by hauntsaninja** [comment]
Thanks for suggesting this! Given that this hasn't attracted much attention and there are reasonable alternatives, I'm closing this issue

**Comment by roguh** [comment]
I'd be interested in this for a linter/fixer plugin I'm working on. Is there a workaround that doesn't require `<()`?

**Comment by shamrin** [comment]
@roguh Would a shell wrapper script work for you?

`mypy-runner`:
```bash
#!/usr/bin/env bash
poetry run mypy "$@" <(cat)
```

Usage:

```console
$ echo 'x: int = "string"' | ./mypy-runner --strict --pretty
/dev/fd/63:1: error: Incompatible types in assignment (expression has type "str", variable has type "int")
    x: int = "string"
             ^
Found 1 error in 1 file (checked 1 source file)
```

@hauntsaninja We have got one other interested person 😆  I still believe it would be nice to make `mypy` a good shell citizen. (I can try to contribute this feature myself, but I don't want to submit a PR with zero chance of being merged.)

**Comment by roguh** [comment]
Certainly! I ended up just using `mypy <(cat)` for an editor plugin I'm writing.

I agree that `mypy -` would be ideal for our use-case, or perhaps it could be hidden behind a flag (which is how pylint does it) such as `mypy --from-stdin [module_from_stdin]` where the user must assign a name to the stdin module.

**Comment by shamrin** [comment]
In 2016 Guido resisted adding an stdin flag, because "mypy already has too many flags": https://github.com/python/mypy/issues/2119#issuecomment-246149241. That's why I suggested to support `mypy -` in this ticket, to avoid a flag.

@hauntsaninja Can we reconsider the `mypy -` feature? I think there is a demand, but many simply give up after reading through #2119.

@roguh To continue on a workaround-for-a-workaround train, an existing [`--shadow-file` option][1] may help with assigning a name:

```
mypy "$@" --shadow-file file-name-in-the-editor.py <(cat) file-name-in-the-editor.py
```

(Make sure `file-name-in-editor.py` exists. [Mypy complains][2] if it doesn't. It could even be an empty file.)

[0]: https://github.com/python/mypy/issues/2119#issuecomment-246149241
[1]: https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-shadow-file
[2]: https://github.com/python/mypy/issues/4746

**Comment by FeLiNa0** [comment]
@hauntsaninja bumping this. I can work on a PR.
