### ISSUE TITLE
Support loading `stubs/` from typeshed

### ISSUE THREAD

**Issue by not-my-profile** [python/mypy#12241]
When I create a file `foo.py` with `import toml` and execute `mypy foo.py --custom-typeshed-dir my-typeshed/` I get:

```
foo.py:1: error: Library stubs not installed for "toml" (or incompatible with Python 3.9)
foo.py:1: note: Hint: "python3 -m pip install types-toml"
foo.py:1: note: (or run "mypy --install-types" to install all missing stub packages)
foo.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

Although `my-typeshed/stubs/` contains `toml/`.

I find this really inconvenient because I'd like to test my third-party stub typeshed contributions with mypy.

It's worth noting that pyright handles this, `pyright foo.py --typeshed-path my-typeshed/` works as expected.

**Comment by Akuli** [comment]
This works, but is probably not documented anywhere and we should at least document it: `MYPYPATH=stubs/toml/ foo.py`
