### ISSUE TITLE
Executing `mypy` outside a venv on packages inside a venv

### ISSUE THREAD

**Issue by not-my-profile** [python/mypy#12242]
I would like to check type check untrusted code with mypy. My idea was to:

1. create a venv
2. install the untrusted packages with `pip install --only-binary :all:`
3. running mypy outside the venv on the packages within the venv

However unless I am missing something there does not appear to be a suitable option for that.

It's worth noting that pyright does support this with its `--venv-path` option.

**Comment by hauntsaninja** [comment]
passing `--python-executable venv/bin/python` should work.

**Comment by not-my-profile** [comment]
Thank you, that indeed works!
