### ISSUE TITLE
(🎁) `reveal_type` should reveal both the bounds, not just the lower bound

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12243]
```py
a: int | str = 1
reveal_type(a)  # int | str
a = ""
reveal_type(a)  # str
```
Is this a narrowed `str` of a `int | str` or is this an upper bounded `str`?
<details>
<summary>Spoiler!</summary>

It's being redefined as `str` (depending on your settings of course)
https://mypy-play.net/?mypy=latest&python=3.10&flags=allow-redefinition&gist=d21640195c51062bf4edf4e4b0300857

</details>

**Comment by erictraut** [comment]
The current behavior in mypy is how `reveal_type` is intended to work. It reveals the current (narrowed) type of the expression at that point in the code flow. This will soon be standardized in a PEP and included in Python 3.11.

**Comment by KotlinIsland** [comment]
I don't understand the issue, I want the output to be more informative than it currently is

expected:
```py
a: int | str = 1
reveal_type(a)  # int | str
a = ""
reveal_type(a)  # narrowed 'str' of 'int | str'
```

**Comment by sobolevn** [comment]
In my opinion, what you are looking for is not a feature of `reveal_type`.
Right now `reveal_type` is very straight-forward, it does not take any internal details into account.

What you are looking for is more like `debug_type()` (does not exist). This function can possibly tell why some type is what it is.

But, I don't really think it is worth implementing.
