### ISSUE TITLE
Final TypedDict

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#12266]
We could perhaps support final TypedDicts that don't allow subtypes to have extra keys. Example:

```py
from typing import final, TypedDict

@final
class A(TypedDict):
    x: int

@final
class B(TypedDict):
    x: int
    y: str

def f(d: A) -> None: ...

d: B = {...}
f(d)  # Error -- extra key 'y'
```

Here are some random thoughts:
* We should be able to infer a more precise type for `values()`, since there can't be extra "hidden" values with arbitrary types.
* A non-final TypedDict isn't compatible with a final one, since it could have some extra keys due to structural subtyping.
* This could help with exhaustiveness checking in match statements.

I haven't thought carefully about all the implications of this feature. Before implementing this, some additional analysis would be useful.

See #10759 for more context.

**Comment by 97littleleaf11** [comment]
Previous discussion: https://github.com/python/mypy/issues/7981

**Comment by JukkaL** [comment]
Closing as dupe of #7981, oops.
