### ISSUE TITLE
Support for PEP 646

### ISSUE THREAD

**Issue by erictraut** [python/mypy#12280]
[PEP 646](https://www.python.org/dev/peps/pep-0646/) has been accepted for inclusion in Python 3.11. Both pyre and pyright support it currently.

Third-party libraries and typeshed stubs will probably avoid using this functionality until mypy offers some level of support for it. 

Perhaps as a first step, mypy could implement a minimal understanding of `TypeVarTuple`, `Unpack`, and the new grammar change for `*`? This would allow libraries to start using the new facilities without generating false positive errors in mypy. This is a similar approach to the one for PEP 612 (ParamSpec) and PEP 634 (structural pattern matching).

**Comment by tyralla** [comment]
@jhance: I thought about giving it a try but then realised you already did a lot of work (at least #13105, #13210, #13211, #13586, #13889) that has been merged.  Is there still much to do where others could help?

**Comment by uriyyo** [comment]
Hi all,
Do we have a list of things left to implement to support PEP 646 fully?

**Comment by vavanade** [comment]
What's the current state on this?

**Comment by AlexWaygood** [comment]
> What's the current state on this?

See https://github.com/python/mypy/pull/16242#issue-1934014569

**Comment by Lordfirespeed** [comment]
With #16242 merged, is this issue resolved?
