### ISSUE TITLE
Support for output message ranges, instead of just the position

### ISSUE THREAD

**Issue by DevilXD** [python/mypy#12288]
**Feature**

Following the discussion in https://github.com/microsoft/vscode/issues/142810, I propose MyPy to output a range over which a typing error occurs, instead of just the position of it. The current message with `--show-column-numbers` and `--no-pretty` looks like this:

```
test.py:4:5: error: Argument 1 to "foo" has incompatible type "str"; expected "int"
```

It'd be great if a range would be included for the column numbers, if possible:

```
test.py:4:5-15: error: Argument 1 to "foo" has incompatible type "str"; expected "int"
```

Output with `--pretty` could then use multiple `^` characters to visualize the range. Omitting `--show-column-numbers` wouldn't display column numbers at all, thus the output would remain unchanged.

**Pitch**

This change would allow the VSCode Python extension to output diagnostic objects with proper ranges, since the current implementation only underlines one character and makes it hard to work with, and [other proposed solutions](https://github.com/microsoft/vscode/issues/142810#issuecomment-1054682229) appear to be non-trivial at the very least.

**Comment by cdce8p** [comment]
Some implementation considerations:
* The end position should also contain a lineno in case the error stretches across multiple lines.
* Only Python 3.8 added the `end_lineno` and `end_col_offset` attributes to AST nodes. It might not be practical to support it for 3.7

**Comment by JelleZijlstra** [comment]
Agree that we should do this in Python versions where we have the right information in the AST.

**Comment by devmessias** [comment]
I can address that. 
About the use of multiple `^` in my project ([pyastrx-alpha](https://github.com/pyastrx/pyastrx)) I did something similar, take a look 
![image](https://user-images.githubusercontent.com/6979335/172055997-86458f65-902e-47ef-a1ba-8441f37cc5e1.png)

The range of code shown is controlled by other parameters (context).  For colors, I'm using rich, but  I believe that is not a good idea to add a dependency in mypy.

**Comment by 97littleleaf11** [comment]
Closed by https://github.com/python/mypy/pull/13148
