### ISSUE TITLE
Color output missing when errors redrected (windows 10)

### ISSUE THREAD

**Issue by mrolle45** [python/mypy#12298]
**Bug Report**

When redirecting error output, ANSI color codes are missing from regular output.

**To Reproduce**

1. Start a window cmd terminal with ansi codes enabled.  There's a program named 'ansicon' that will do this.
2. `mypy mymodule.py`
3. `mypy mymodule.py 2> mypy.txt`

**Expected Behavior**
Errors show in the console with colors, after both 'mypy' commands.

**Actual Behavior**
Errors show in the console with colors, after first 'mypy' command.
Errors show in the console **without colors**, after second 'mypy' command.

**Your Environment**

- Mypy version used: 0.931
- Mypy command-line flags: none.
- Mypy configuration options from `mypy.ini` (and other config files): none.
- Python version used: 3.7
- Operating system and version: Windows 10.

**Comment by mrolle45** [comment]
On Windows 10, using the usual cmd window (with ANSI codes enabled), I run mypy and see the error messages with colors.
However, if I type
 `mypy myfile.py 2> mypy.txt`
then the error messages are still written to the console, but **without colors**.

**Comment by hauntsaninja** [comment]
I think this is by design. You can use the environment variable `MYPY_FORCE_COLOR` to ensure colourised output

**Comment by mrolle45** [comment]
@hauntsaninja:
I would say that it should apply `stdout`, and `stderr` _separately_,
Or perhaps to `stdout` alone because I don't think anything colorizeable is written to stderr.
My own use case:  I have verbosity configured, so I redirect stderr to a file.  I would have liked to see the colors on my terminal just the same.
Therefore, I request that you reopen this issue and fix things so that stdout and stderr are colorized _independently_ based on (1) whether the respective file is a terminal, (2) `MYPY_FORCE_COLOR`, and (3) the `use-color` option.

Possible ways to do this:

1. Drop replace the `f_out` and `f_err` arguments to a single file argument, and then create two separate formatter objects in the main `run_build()` function.  `run_build` will use the appropriate formatter in every case, as it has already decided whether to write the message to `stdout` or `stderr`.
2. Add a file argument to formatter.colorize() method, which can decide, based on whether the file is a tty, and `MYPY_FORCE_COLOR`.  And drop both `f_out` and `f_err` from the formatter constructor.
