### ISSUE TITLE
Mypy infers the type of an async generator expression as `Generator`

### ISSUE THREAD

**Issue by michaeloliverx** [python/mypy#12307]
**Bug Report**

Mypy thinks the type of an async generator expression is `Generator`

**To Reproduce**

```python
# example.py
import asyncio
from collections.abc import AsyncIterator
from random import random
from uuid import uuid4


async def get_value() -> str:
    await asyncio.sleep(random())
    return uuid4().hex


async def process_values(ait: AsyncIterator[str]) -> None:
    async for item in ait:
        print(item)


async def main() -> None:
    agen = (await get_value() for _ in range(10))
    reveal_type(agen)
    await process_values(agen)


asyncio.run(main())

```

**Expected Behavior**

That the type would be `AsyncGenerator`

**Actual Behavior**

```
mypy .\example.py --strict
example.py:19: note: Revealed type is "typing.Generator[builtins.str*, None, None]"
example.py:20: error: Argument 1 to "process_values" has incompatible type "Generator[str, None, None]"; expected "AsyncIterator[str]"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: `0.931`
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: `3.9.0`
- Operating system and version: Windows 10

**Comment by A5rocks** [comment]
https://github.com/python/mypy/issues/10534

**Comment by michaeloliverx** [comment]
Closing as duplicate of https://github.com/python/mypy/issues/10534, thanks @A5rocks
