### ISSUE TITLE
(🐞) No error when using unbound `TypeVar` as type parameter in `TypeAlias`

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12311]
Originally spotted by @Eldar1205
```py
from typing import *
T = TypeVar("T")

A: TypeAlias = list[T]  # no error
B: TypeAlias = Union[T]  # no error
C: list[T]  # error
```

**Comment by JelleZijlstra** [comment]
This isn't an error; it creates a generic alias.

**Comment by KotlinIsland** [comment]
```py
from typing import *
T = TypeVar("T")

A: TypeAlias = list[T]  # no error

def foo(a: A) -> A: ...

reveal_type(foo([1]))  # list[Any]
```
Well something seems broken

**Comment by KotlinIsland** [comment]
Also these forms are then inconsistent:
```py
A: TypeAlias = T | None  # error
B: TypeAlias = T  # error
```

**Comment by JelleZijlstra** [comment]
Your first example produces `main.py:6: error: Missing type parameters for generic type "A"` with `--disallow-any-generics`. Agree that the `T | None` case should be accepted.

**Comment by KotlinIsland** [comment]
@JelleZijlstra  Fair enough, thanks for explaining. I've updated the title and OP, want to reopen it?

**Comment by AlexWaygood** [comment]
> Agree that the `T | None` case should be accepted.

That one's a PEP 604 bug; it works fine with `typing.Union`. https://mypy-play.net/?mypy=latest&python=3.10&gist=440bf42209bcc85bd6faa7b03b7e23d7

And it's already been reported in a different issue, lemme just find it

**Comment by AlexWaygood** [comment]
Here: https://github.com/python/mypy/issues/12211
