### ISSUE TITLE
Tags not right in the repository

### ISSUE THREAD

**Issue by akaihola** [python/mypy#1232]
Currently the GitHub repository contains the following tags:
- v0.1.0
- v0.2.0
- v1.3.1

There's no tag for the 0.3.0 release, and `v1.3.1` looks like a typo for `v0.3.1`.

**Comment by gvanrossum** [comment]
I've taken care of this. There's now a tag v0.3.1 and the tag v1.3.1 is gone. (Though if you pulled when it existed you may have to delete it locally.)
