### ISSUE TITLE
get this error about asyncio which is applicable to python 3.7 but code covers python versions as shown

### ISSUE THREAD

**Issue by mark-nick-o** [python/mypy#12331]
my code is below :- 
=======================================================================
import sys

    if (sys.version_info.major == 3 and sys.version_info.minor >= 7):
        asyncio.run(main())
    elif (sys.version_info.major == 3 and sys.version_info.minor <= 6) and (sys.version_info.major == 3 and sys.version_info.minor >= 5):
        loop = asyncio.get_event_loop()
        loop.run_until_complete(asyncio.wait(main()))
    else:
        print("you currently need to have python 3.5 at least")

runs fine but when checked with mypy i get
8008: error: Module has no attribute "run"
which i guess is for python < 3.7

im running this command line
mypy --ignore-missing-imports <myfile.py>

im using Python 3.8.3 on this machine
in WSL
Linux DESKTOP-M4HNI3V 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JelleZijlstra** [comment]
You need to use a slightly different form of version checks. See https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks.
