### ISSUE TITLE
`--implicit-any` is poorly named

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1233]
The `--implicit-any` flag is named for its implementation details (adding `Any`s to all unannotated functions) rather than for its desired effect (to typecheck functions unannotated functions).

I think something along the lines of `--check-untyped-functions`, `--check-all`, `--check-all-functions`, or similar would suit it better.

**Comment by gvanrossum** [comment]
Agreed that the name isn't perfect, but let's not rush into this (since naming is always hard).

Maybe rename it when it acquires some more functionality -- e.g. I would like to see it behave more like the fixer I wrote, which takes the type of the default value (if given) as the arg type, e.g.
```
def foo(a='', b=0): ...
```
is implied to mean
```
def foo(a: str = '', b: int = 0) -> Any: ...
```

**Comment by ddfisher** [comment]
Interesting!

After thinking about it a bit, my inclination would be not to include that functionality, because I think it'll be harder for users to reason about the behavior.  The current behavior of "type check all functions instead of just those with explicit type annotations" is easy to explain, understand, and reason about.  I worry that if we add that partial type inference (and perhaps some other small things like it), the behavior would become "type check all functions and do type inference on their signatures in a way that's correct most of the time but occasionally has complicated caveats", which I think would be a bit unfortunate.  Is that something you'd be concerned about?

**Comment by gvanrossum** [comment]
You're right. It would be strange if it behaved more strictly than just
adding any as the return type.

--Guido (mobile)

**Comment by ddfisher** [comment]
I was also hoping to use the name change as a chance to make a couple minor fixups in how the feature is implemented.  I'd:
1) switch to using a build flag
and 2) change the typing mode in the checker rather than generating function signatures in the parser.  In working on `--disallow-untyped-calls` I came across code elsewhere which does the same thing later down the line, and it'd be better to not have that written twice, I think.

**Comment by JukkaL** [comment]
I think that options like these should ultimately be configured for each file or package separately, perhaps in addition to providing a global command-line option. I created a new issue to discuss this (#1235).
