### ISSUE TITLE
[feature request] Support ellipsis (...) like Callable when we want untyped arguments

### ISSUE THREAD

**Issue by wittekm** [python/mypy#1234]
Hi all,

It would be nice if MyPy supported a similar ellipsis notation to `typing.Callable`. 

From the typing [docs](https://docs.python.org/3/library/typing.html), 
> It is possible to declare the return type of a callable without specifying the call signature by substituting a literal ellipsis for the list of arguments in the type hint: `Callable[..., ReturnType]`.

It would be nice if MyPy supported something similar - i.e. 
`# type: ... -> ReturnType`
or
`# type: (...) -> ReturnType`

Which would basically evaluate the same way as `# type: (Any, Any, Any, Any) -> ConcreteType` for a 4-argument function.

**Comment by ddfisher** [comment]
This seems pretty reasonable to me, and could be a good starter task for someone looking to get their hands dirty.

Of the two proposed syntaxes, I'd vastly prefer the second one (`# type: (...) -> ReturnType`), because the first would require special casing in the parser (and there's no point in doing that when the second syntax is fine).

@gvanrossum would this require a change to PEP 484?

**Comment by wittekm** [comment]
(I'd actually love to jump on this task myself, once the powers that be give it the OK!)

**Comment by gvanrossum** [comment]
Yes, it would require a PEP change. But go ahead and make a PR.

--Guido (mobile)

**Comment by ddfisher** [comment]
Here's a good place to start: https://github.com/python/mypy/blob/master/mypy/parse.py#L404

**Comment by JukkaL** [comment]
Note that in Python 3 this is already possible by omitting argument type annotations. For example:

```
def f(a, b) -> int:
    ...
```

This proposal brings Python 2 syntax closer to Python 3, which is good. Mixing annotated and unannotated arguments in a single function won't be supported for Python 2, but I'd argue that it's a marginal need.

**Comment by ddfisher** [comment]
Agreed.  Also, aren't unannotated arguments treated equivalently to arguments annotated with `Any`?  So putting `Any`s in Python 2 annotations is the same as leaving them unannotated in Python 3 (from a type checking perspective).

**Comment by gvanrossum** [comment]
Yes, but I think the point of the feature request is that it would be
nice not to have to count how many Anys to put.

**Comment by ddfisher** [comment]
Right.  I was just responding to Jukka's point about mixing annotated and unannotated arguments in a single function.

**Comment by gvanrossum** [comment]
I cross-filed this for PyCharm: https://youtrack.jetbrains.com/issue/PY-18598

**Comment by JukkaL** [comment]
And if https://github.com/python/typing/issues/186 gets accepted, this would make the syntax even closer to the Python 3 syntax in terms of supported features. I assume that this would be okay:

```
def f(x,  # type: int
      y):
    # type: (...) -> str
    # Note that only x has an annotation, y has an implicit Any type
    ...
```

**Comment by gvanrossum** [comment]
Yes.

--Guido (mobile)
