### ISSUE TITLE
mypy does not consider a generic container of a subtype to be compatible with same generic container of the supertype

### ISSUE THREAD

**Issue by zzzeek** [python/mypy#12353]
looking at https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides, things are only demonstrated in terms of the outer type, e.g. List, Iterable, Sequence.

At the moment it seems like if the container types inner type is more specific, that's not accepted at all.   pyright doesnt seem to have this issue.   I'm not coming up with a decent workaround yet but just want to make sure this is a bug or if there is some typing wisdom I'm missing, see demo below with `mypy 0.950+dev.0fecec8c72605ec7bae343b28d545c477c726e81`

```py
from typing import Set

class Thing:
    pass

class SubThing(Thing):
    pass


class Foo:
    def get_things(self) -> Set[Thing]:
        ...


class Bar(Foo):
    def get_things(self) -> Set[SubThing]:
        ...

```

output:

```
test3.py:16: error: Return type "Set[SubThing]" of "get_things" incompatible with return type "Set[Thing]" in supertype "Foo"  [override]
Found 1 error in 1 file (checked 1 source file)
```

if I have a `Set` of `SubThing`, that is certainly a `Set` of `Thing` objects, so this seems like a bug.

**Comment by JelleZijlstra** [comment]
This is invariance at work. Your code would allow this:

```
foo: Foo
foo.get_things().add(Thing())
```
And now if `foo` is actually a `Bar`, `get_things()` will no longer return a `Set[SubThing]`.

The standard solution is to return an immutable type, e.g. `Collection[Thing]`.

**Comment by erictraut** [comment]
I'll note that pyright also flags this as an error if you enable `reportIncompatibleMethodOverride`.

**Comment by hauntsaninja** [comment]
Yup, I'd use `typing.AbstractSet`

**Comment by zzzeek** [comment]
crazytown.  thanks for the tips.   As is customary for everyone who reports github issues everywhere, I will express a desire to have this noted at https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides .  I'm always annoyed when my users do it yet it's impossible to to resist

**Comment by JelleZijlstra** [comment]
Variance is already covered at https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance. Honestly in my experience it's not that common to encounter variance problems specifically with overrides.

**Comment by zzzeek** [comment]
> Variance is already covered at https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance. Honestly in my experience it's not that common to encounter variance problems specifically with overrides.

yup, the dance is complete    (   :)    )


i switched it to frozenset which is great, actual immutability is great for deep sleep at night
