### ISSUE TITLE
Unsupported type inferring for Unions of dicts

### ISSUE THREAD

**Issue by claudio-ebel** [python/mypy#12366]
**Bug Report**

`mypy` does not cope with a combination of nested `dict`s and `Union`s when types coincide, namely `dict[str, bool | int] | dict[str, float | int]`.

**To Reproduce**

Minimal working example:
```python
# file mypy_bug.py
from typing import TypeAlias
Brian: TypeAlias = dict[str, bool | int] | dict[str, float | int]


def spam() -> Brian:
    return {'a': True}
```
Then use `mypy`:
```shell
$ mypy --version
mypy 0.941
$ mypy --config-file= mypy_bug.py
mypy_bug.py:6: error: Incompatible return value type (got "Dict[str, bool]", expected "Union[Dict[str, Union[bool, int]], Dict[str, Union[float, int]]]")
Found 1 error in 1 file (checked 1 source file)
```

**Expected Behaviour**

According to `Union Type` on [python.org](https://docs.python.org/3/library/stdtypes.html#union-type),
> Union objects can be tested for equality with other union objects. Details:
> * Unions of unions are flattened:
>    ```python
>    (int | str) | float == int | str | float
>    ```
> * Redundant types are removed:
>    ```python
>    int | str | int == int | str
>    ```
> * When comparing unions, the order is ignored:
>    ```python
>    int | str == str | int
>    ```
So I would also expect that 
```python
(dict[str, bool | int] | dict[str, float | int]
 == dict[str, bool] | dict[str, int] | dict[str, float]
 == dict[str, bool | float | int])
```
**Playing around**
* Indeed, `mypy` _accepts_ the minimal working example if we
  1. :heavy_check_mark:  Use a `Union` of three `dict`s
        ```python
        from typing import TypeAlias
        Brian: TypeAlias = dict[str, bool] | dict[str, float] | dict[str, int]
        
        
        def spam() -> Brian:
            return {'a': True}
        
        
        def ham() -> Brian:
            return {'a': 0}
        
        
        def eggs() -> Brian:
            return {'a': 3.14}
        ```
    2. :heavy_check_mark: Use a `dict` of three `Union`s
        ```python
        from typing import TypeAlias
        Brian: TypeAlias = dict[str, bool | float | int]
        
        
        def spam() -> Brian:
            return {'a': True}
        
        
        def ham() -> Brian:
            return {'a': 0}
        
        
        def eggs() -> Brian:
            return {'a': 3.14}
        ```
* `mypy` still _fails_ with the minimal working example if we
  1. :x: Remove `TypeAlias` completely
        ```python
        Brian = dict[str, bool | int] | dict[str, float | int]
        
        
        def spam() -> Brian:
            return {'a': True}
        ```    
  2. :x: Replace `|` with `Union`
        ```python
        from typing import TypeAlias, Union
        Brian: TypeAlias = Union[dict[str, Union[bool, int]],
                                 dict[str, Union[float, int]]]
        
        
        def spam() -> Brian:
            return {'a': True}
        ```

**Related Tickets**

- #3935
- #3933
- #5149

**Your Environment**
- Mypy version used: `0.941`
- Mypy command-line flags: `--config-file= `
- Mypy configuration options from `mypy.ini` (and other config files): Ignored!
- Python version used: 3.10.2
- Operating system and version: Linux

**Comment by JelleZijlstra** [comment]
https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance

`dict[str, bool]` is not compatible with `dict[str, bool | int]` because `dict` is invariant in both type parameters.

**Comment by claudio-ebel** [comment]
> https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance
> 
> `dict[str, bool]` is not compatible with `dict[str, bool | int]` because `dict` is invariant in both type parameters.

Thank you for your ultra fast reply! I'll try to learn, what it exactly means.
