### ISSUE TITLE
match statement support in mypyc

### ISSUE THREAD

**Issue by freundTech** [python/mypy#12362]
**Feature**

While mypy got proper match statement support now, the match statement isn't yet supported in mypyc.
See https://github.com/python/mypy/blob/master/mypyc/irbuild/visitor.py#L183

**Pitch**
In the future match statements should also be supported in mypyc

**Comment by jhance** [comment]
https://github.com/mypyc/mypyc/issues/911 FYI

**Comment by freundTech** [comment]
Closing in favour of the issue in the mypyc repo
