### ISSUE TITLE
(📚) docs state that they are copyright to some ancient year I've never heard of (2016😳😳😳)

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12374]
![image](https://user-images.githubusercontent.com/65446343/158992591-6dc4158c-bb23-45e0-a22b-78ddb41ef313.png)

**Comment by ethanhs** [comment]
You do not (and most likely should not) update the year of copyright AIUI. The year is the initial date of copyright, not the current year. In the US copyright is the lifetime of the author plus 70 years, so there is no reason to update the year.

Unless you have a source about why the year should be updated, I think this is wrong.
