### ISSUE TITLE
Allow class variable and instance variable be of different type

### ISSUE THREAD

**Issue by sterliakov** [python/mypy#12381]
In the following use case it would be great to make some mechanism to distinguish between class variable and instance variable:

```python3
class A:
    def bar(self): return 'bar'

class B:
    foo: ??? = A
   
    def __init__(self) -> None:
        if callable(self.foo):
            self.foo = self.foo()

def baz(b: B) -> None:
    print(b.foo.bar())
```

Actually we can subclass `B` and declare foo as either `A` or `A()`. However, when some other code unit uses `B` instance, it should be aware that `foo` is always instance of `A`, not `A` class. 

We can
* declare `foo: A` (then assignment is invalid and any subclass will have same problem)
* declare `foo: Union[Type[A], A]` (then `baz` will be reported with `error: Missing positional argument "self" in call to "bar"`)
* declare `foo: Any`

All options have serious drawbacks. Real case: Django `forms.Field` class with `widget` attribute: in `Field.__init__` widget is instantiated if needed, so real types are `Field.widget: Widget | Type[Widget]` and `Field().widget: Widget`. It can be represented with something like
`widget: ClassVar[Type[Widget] | Widget] | Widget`
but it's a) unclear and b) not really correct. Now `mypy` correctly complains with `Invalid type: ClassVar nested inside other type`.

**Comment by hauntsaninja** [comment]
I don't see a good solution here and I'm not really in favour of encouraging this kind of thing — it's confusing for humans, not just type checkers. Is renaming not an option? If not, maybe you can use a Protocol to describe the shared structure.

If you have an idea for a good annotation for your use case, I recommend sharing your design at https://github.com/python/typing or the typing-sig mailing list. That's where Python type system features get propose.
