### ISSUE TITLE
Protocol implementation isn't recognized as being of type of the protocol

### ISSUE THREAD

**Issue by shayrybak** [python/mypy#12391]
**Bug Report**

When defining  a protocol and implementing it in another class, when I try to assign or use the implementation class anywhere that expects the protocol I'm getting an error from mypy (code works just fine)
**To Reproduce**
```
class Proto(Protocol):
    def test(self) -> None:
        ...


class InstanceA:
    def test(self) -> None:
        print("hello")


a: Proto = InstanceA
```
**Expected Behavior**

This should be valid according to the documentation here: https://mypy.readthedocs.io/en/stable/protocols.html#simple-user-defined-protocols

**Actual Behavior**
Getting error
Incompatible types in assignment (expression has type "Type[InstanceA]", variable has type "Proto")  [assignment]

**Your Environment**

- Mypy version used: mypy 0.941
- Mypy command-line flags: 
- Mypy configuration options from `mypy.ini` (and other config files): 
```[tool.mypy]
check_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
explicit_package_bases = true
namespace_packages = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true

pretty = true
python_version = "3.10"
show_column_numbers = true
show_error_codes = true
show_error_context = true
show_traceback = true
```
- Python version used: 3.10
- Operating system and version: macOS 12.2.1

**Comment by erictraut** [comment]
Mypy is correct here. You are attempting to assign the class `InstanceA` to a variable that is annotated with `Proto`, which indicates that it accepts an _instance_ of `Proto`.

You can resolve the inconsistency in your code by doing one of the following:
```python
a: Proto = InstanceA()
```

or
```python
a: type[Proto] = InstanceA
```

**Comment by JelleZijlstra** [comment]
Eric is correct.

**Comment by shayrybak** [comment]
Thank you @erictraut @JelleZijlstra
