### ISSUE TITLE
(🐞) 'truthy-bool' should not apply to `object`

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12405]
```py
def func(o: object) -> None:
    if o: ...  # error: "o" has type "object" which does not implement __bool__ or __len__ so it could always be true in boolean context  [truthy-bool]
```

I think this diagnostic isn't helpful, an exception should be made for `object`.

Or maybe it is an indication of a bad pattern, discuss below.

**Comment by ikonst** [comment]
This check isn't enabled by default in part of this, since a derived type of a non-final type can _maybe_ implement `__bool__` or `__len__`.

I'd like to see more practical examples.

Would `o: Any` be equivalently expressive in this case?

**Comment by KotlinIsland** [comment]
@ikonst Unfortunately `Any` isn't type checked at all. I think in this case I rewrote it or something.
