### ISSUE TITLE
Explicit type aliases fail in typeshed

### ISSUE THREAD

**Issue by srittau** [python/mypy#12422]
I can't reproduce this locally, but please have a look at the CI failures of python/typeshed#7534. The change is adding explicit type aliases to `_typeshed/*`. CI runs mypy 0.941 with all Python versions.

**Comment by JelleZijlstra** [comment]
For reference #11305 added PEP 613 support.

**Comment by AlexWaygood** [comment]
Happy to confirm that #12431 solved this issue — now only the pytype test is failing in typeshed's CI (https://github.com/python/typeshed/pull/7534) 🎉
