### ISSUE TITLE
False Positive: "An overloaded function must have an implementation" in a class using custom metaclass

### ISSUE THREAD

**Issue by qexat** [python/mypy#12423]
**Bug Report**

**To Reproduce**

1. Create a class using the metaclass from [this script](https://github.com/mCodingLLC/VideosSampleCode/blob/master/videos/077_metaclasses_in_python/overloading.py)
2. Write a correctly typed overloaded method using `@overload` decorator **without default implementation** from the same script as step 1

**Expected Behavior**

No errors should be reported.

**Actual Behavior**

`error: An overloaded function outside a stub file must have an implementation` is raised.

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.0
- Operating system and version: Ubuntu 21.10

**Comment by JelleZijlstra** [comment]
Mypy version 0.812 is old; please upgrade before reporting a bug.

Also, could you provide a minimum code sample that shows the issue?

**Comment by qexat** [comment]
Sorry for the delay, gonna work on it today and update my issue report.

**Comment by qexat** [comment]
I completely forgot this issue, I'm very sorry about this.

I tried to reproduce the bug (mypy 0.991), but I failed to do so...
