### ISSUE TITLE
The type of asynccontextmanager type appears to depend on the existence of a `raise` in the wrapped function?

### ISSUE THREAD

**Issue by danking** [python/mypy#12437]
**Bug Report**

I expected all three functions to type check fine. However, the last one fails to type check. I'm particularly surprised because the second one only differs in that it has some dead code.

**To Reproduce**

```
(base) # mypy foo.py
foo.py:13: error: Argument 1 to "asynccontextmanager" has incompatible type "Callable[[], Coroutine[Any, Any, AsyncGenerator[int, None]]]"; expected "Callable[[], AsyncIterator[<nothing>]]"
Found 1 error in 1 file (checked 1 source file)
(base) # cat foo.py
from contextlib import asynccontextmanager
from typing import AsyncGenerator

@asynccontextmanager
async def foo(self) -> AsyncGenerator[int, None]:
    yield 3

@asynccontextmanager
async def bar() -> AsyncGenerator[int, None]:
    raise NotImplementedError
    yield 3

@asynccontextmanager
async def baz() -> AsyncGenerator[int, None]:
    raise NotImplementedError
```

**Your Environment**

- Mypy version used: mypy 0.931
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: Python 3.7.7
- Operating system and version: Mac OS 11.6.2

```
Darwin wm06b-953 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64
```

**Comment by JelleZijlstra** [comment]
This looks right to me. The last one doesn't have a `yield`, so it's not an async generator.

**Comment by danking** [comment]
Ah, thanks.
