### ISSUE TITLE
Missing definitions for typing_extensions

### ISSUE THREAD

**Issue by taasan** [python/mypy#12438]
**Bug Report**

Missing definitions in typeshed.  They have been added to upstream typeshed.

**To Reproduce**

```
mypy -c 'from typing_extensions import assert_never, Never'
```

**Expected Behavior**

Type checking should succeed

**Actual Behavior**

```
<string>:1: error: Module "typing_extensions" has no attribute "assert_never"
<string>:1: error: Module "typing_extensions" has no attribute "Never"
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: Tried both 0.921 (from fedora) and 0.941
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10
- Operating system and version: Fedora 35

**Comment by hauntsaninja** [comment]
Will be included in the next release, presumably from https://github.com/python/mypy/pull/12321
