### ISSUE TITLE
slice of list[T] becomes a T*

### ISSUE THREAD

**Issue by johnburnett** [python/mypy#12479]
**Bug Report**

The inferred type of a slice of a `list[T]` appears to be `T`, not `list[T]`

**To Reproduce**

```
from typing import List, Tuple

def foo() -> None:
    my_tuple: Tuple[int] = (1, 2, 3)
    my_tuple_slice = my_tuple[:]

    my_list: List[int] = [1, 2, 3]
    my_list_slice = my_list[:]

    reveal_locals()
```

**Expected Behavior**

The type of `my_list_slice` to be `builtins.list[builtins.int]` (similar to how a slice of the example `my_tuple` is `tuple[int]`)

**Actual Behavior**

The type of `my_list_slice` is inferred to be `my_list_slice: builtins.int*`:

```
note: Revealed local types are:
note:     my_list: builtins.list[builtins.int]
note:     my_list_slice: builtins.int*
note:     my_tuple: Tuple[builtins.int]
note:     my_tuple_slice: Tuple[builtins.int]
```

**Your Environment**

- mypy 0.931
- Python 3.7.7

**Comment by JelleZijlstra** [comment]
Can't reproduce this on 0.941:

```
main.py:4: error: Incompatible types in assignment (expression has type "Tuple[int, int, int]", variable has type "Tuple[int]")
main.py:10: note: Revealed local types are:
main.py:10: note:     my_list: builtins.list[builtins.int]
main.py:10: note:     my_list_slice: builtins.list[builtins.int*]
main.py:10: note:     my_tuple: Tuple[builtins.int]
main.py:10: note:     my_tuple_slice: Tuple[builtins.int]
Found 1 error in 1 file (checked 1 source file)
```
https://mypy-play.net/?mypy=latest&python=3.10&gist=850a37c626afe058c011853a531ef0ed

**Comment by AlexWaygood** [comment]
I cannot reproduce on 0.941 or 0.931.

**Comment by johnburnett** [comment]
Apologies - this appears to be an issue with a semi-broken mypy install here.

**Comment by AlexWaygood** [comment]
No worries :)
