### ISSUE TITLE
Dict with key type of Union[…] produces "incompatible type" error

### ISSUE THREAD

**Issue by janw** [python/mypy#12486]
**Bug Report**

I found that typing a dict as `Dict[Union[int, str], Any]` consistently gives me an "incompatible type" on assigment of `Dict[int, str]`, which, from my understanding, should match the annotation just fine.

**To Reproduce**

See https://mypy-play.net/?mypy=latest&python=3.10&gist=d4eeeb02789c540de702021c95214108

**Expected Behavior**

No error is produced

**Actual Behavior**

incompatible type error is produced, à la

> "Argument […] has incompatible type Dict[int, str]"; expected "Optional[Dict[Union[int, str], str]]")

**Your Environment**

- Mypy version used: 0.941
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.9.7
- Operating system and version: macOS 12.3

**Comment by JelleZijlstra** [comment]
https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance
