### ISSUE TITLE
A stricter version of `--warn-unreachable`

### ISSUE THREAD

**Issue by harahu** [python/mypy#12487]
**Feature**

A variant of the `--warn-unreachable` flag, that also warns on `assert False`, `raise` and `NoReturn` calls that are deemed unreachable.
 
**Pitch**

Per [mypy's docs](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-warn-unreachable), the “Statement is unreachable” warning will be silenced in exactly two cases:

1. When the unreachable statement is a raise statement, is an `assert False` statement, or calls a function that has the [NoReturn](https://docs.python.org/3/library/typing.html#typing.NoReturn) return type hint. In other words, when the unreachable statement throws an error or terminates the program in some way.
2. When the unreachable statement was intentionally marked as unreachable using [Python version and system platform checks](https://mypy.readthedocs.io/en/stable/common_issues.html#version-and-platform-checks).

Although I see the usefulness of no. 1, I think it should be possible to disable on demand. Here's why:

I work on a project that has evolved over a fairly long time. Hence, it has also been type checked by multiple older versions of `mypy` (and other type checkers). In that process I suspect we have accumulated a fair bit of defensive code that wouldn't be needed any more. Some of this superfluous defensive code, `mypy` will help me detect. If I upgrade `mypy` and, for instance a `cast` call is no longer needed, the `--warn-redundant-casts` flag will help me clean those up. The `--warn-unused-ignores` flag provides a similar benefit. However, due to case no. 1 above, there is no way I can use `mypy` to help me detect superfluous defensive code written with the purpose of informing a type checker that execution would halt at or before some point. By superfluous I mean a piece of defensive code that once (or maybe never) was required to help the type checker, but isn't needed in the release of `mypy` being run.

If `mypy` thinks I can remove defensive code, I'd really like to know about it.

**Comment by harahu** [comment]
A concrete example:

The [release notes for mypy 0.940](http://mypy-lang.blogspot.com/2022/03/mypy-0940-released.html) states that:
> [...] Note that exhaustiveness checking is still not generally supported across class hierarchies, since mypy doesn’t support sealed classes with a fixed set of subclasses. You can use an union type or `assert False` as a workaround [...]

Imagine this scenario:
1. I decide to follow this advice, and add an `assert False` statement to my code.
2. Someone contributes support for sealed classes in `mypy`.
3. I update to the latest version of `mypy`, with which the `assert False` statement is correctly identified as superfluous.

Now, what is the better continuation?

4. `mypy` informs me that I can safely remove the `assert False` statement,

or:

4. The `assert False` statement lingers on in my code, harming readability, until I figure out myself that it doesn't serve a purpose any more.

**Comment by hauntsaninja** [comment]
Thanks for the suggestion, but I think this is a won't fix. I don't think a few extra `assert False` hurt readability, in fact, I think it often helps even when technically unnecessary, since I'm often less smart than my type checker. `--warn-unreachable` is important, because it can indicate cases where the user is doing something unintended — but with `assert False`, the intention is pretty clear.
