### ISSUE TITLE
The .pyd or .so files don't appear to behave the same as corresponding .py files.

### ISSUE THREAD

**Issue by mrolle45** [python/mypy#12482]
**Bug Report**
I wanted to try changing something in my mypy library by editing something like `X.py`.  This had no effect because there was also an `X.pyd` in the same directory.
I renamed the `X.pyd` so that python would use `X.py`.
I **expected** mypy to behave exactly the same (other than the change I had edited).
What **actually** happened was that the results were different.  Depending on which modules I renamed in this way, either it hung, or got a fatal error, or otherwise incorrect results.
I renamed all `mypy/*.pyd`, but I still got problems.
Finally, I also renamed `mypy/server/*.pyd` and `mypy/plugins/*.pyd`.  And now I got the correct behavior.

So my conclusion is that although for mypy as a whole, the set of .py modules behaves the same as the set of .pyd modules, there are differences in at least some individual modules.

As part of your testing process, do you run stubgen on both the .py and the .pyd modules and see if the stubs match?  I would guess that you would find that, perhaps, the signatures for some module level functions, or class methods, are different (especially public ones).

I am curious about a few things...

1. How do you build your .pyd files?  Do you have some tool that generates C code from the .py, or is it a process of manually maintaining the C code?
2. Do you run the tests on both the complete set of .py modules, and the complete set of .pyd modules?
3. How can a user pip install mypy without any of the .pyd modules?

I especially would like an answer for question 3, for the benefit of other would-be tinkerers.  And perhaps something in the documentation for outside contributors.

**To Reproduce**

1. Go to the mypy folder in your python library.
2. `mkdir save`
3. `mv *.pyd save` (or `*.so` on linux)
4. Go to your project directory
5. `mypy .` (or however else you run mypy on your project)
6. Go back to the mypy folder in your python library.
7. `mv save/*.pyd .` (or `*.so` on linux) to restore mypy

**Expected Behavior**

In step 5, whatever results normally would occur.

**Actual Behavior** during step 5

Segmentation fault (core dumped) on linux
Ended after a few seconds with no output, notwithstanding verbosity = 1, on Windows.

**Your Environment**

- Mypy version used: 0.942
- Python version used: 3.8
- Operating system and version: Ubuntu running under Windows 10 YSL.

I also tried this directly under Windows.  Yes, it does work, #90 notwithstanding.

- Mypy version used: 0.931
- Python version used: 3.7
- Operating system and version: Windows 10

**Comment by hauntsaninja** [comment]
1. mypy comes with a Python to C compiler, called mypyc. Naturally, we use this to compile mypy itself. This makes mypy about 4x faster than when interpreted as plain Python. See https://mypyc.readthedocs.io/en/latest/index.html for more details. Our exact build happens in https://github.com/mypyc/mypy_mypyc-wheels

2. Yes, we run tests against compiled mypy and not compiled mypy.

3. Try something like `pip install mypy --no-binary :all:`

**Comment by mrolle45** [comment]
Thanks for the --no-binary tip.  And thanks for the speedy reply.

But **isn't it a bug** when mixing binaries and non-binaries doesn't work?  Am I naive in assuming that any binary module should behave exactly the same (as seen from other modules) as the source non-binary?

If so, it is a bug in `mypyc` which you want to track down and fix.  And then you will be able to mix binary and non-binary modules in mypy itself.

**Comment by JukkaL** [comment]
If you want to update a .py file when using a compiled mypy, you'll need to recompile mypy using mypyc afterwards. You can do it using `python3 setup.py --use-mypyc build_ext --inplace` or similar. It would be good to have an option to check that the .py files aren't changed when importing a compiled module. We could then fail with a useful error message asking the user to recompile the .py file.
