### ISSUE TITLE
"variable arguments" in error message

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#12508]
Checking `sum(*1)` produces "error: List or tuple expected as variable arguments". I'm pretty sure this should say *variadic* arguments.

**Comment by cmcgee0308** [comment]
Hi there! Is this issue still open?

**Comment by DominiqueGarmier** [comment]
From what I can tell the method `invalid_var_arg` triggers the wrong fail? Perhaps a translation error since var could be short for variable as well as variadic?https://github.com/python/mypy/blob/222029b07e0fdcb3c174f15b61915b3b2e1665ca/mypy/messages.py#L978
