### ISSUE TITLE
Type Alias for attribue in dataclass with restricted type shows unexpected behavior

### ISSUE THREAD

**Issue by jn-chrn** [python/mypy#12500]
**Bug Report**

When a type alias is created, it can be used as attribute annotation for a dataclass. In that case, MyPy does not seem to perform any type check during the instantiation of an object from the class in the case shown in the code below.

If the attribute is annotated without the alias, but with the aliased type directly, mypy does perform a type check in the code below.

**To Reproduce**

Minimal example:

```python
import dataclasses
from typing import TypeVar, Generic


class Parent:
    pass


class Daughter(Parent):
    pass


class Son(Parent):
    pass


RestrictedChild = TypeVar("RestrictedChild", Daughter, Son)
TupleChildrenX2 = tuple[RestrictedChild, RestrictedChild]


@dataclasses.dataclass
class ContainerWithAlias(Generic[RestrictedChild]):

    children: TupleChildrenX2
    reveal_type(children)


@dataclasses.dataclass
class ContainerNoAlias(Generic[RestrictedChild]):

    children: tuple[RestrictedChild, RestrictedChild]


container_with_alias = ContainerWithAlias[Daughter](children=(0, 0))  # No type checking (unexpected)
container_no_alias = ContainerNoAlias[Daughter](children=(0, 0))  # Error as expected

container_with_alias_unbound = ContainerWithAlias(children=(0, 0))  # No type checking (unexpected)
container_no_alias_unbound = ContainerNoAlias(children=(0, 0))  # Error as expected
```

Running `mypy` on a file with this code (without flags) returns:

```
$ mypy tests.py
tests.py:25: note: Revealed type is "Tuple[Any, Any]"
tests.py:35: error: Argument 1 to "ContainerNoAlias" has incompatible type "Tuple[int, int]"; expected "Tuple[Daughter, Daughter]"
tests.py:38: error: Value of type variable "RestrictedChild" of "ContainerNoAlias" cannot be "int"
Found 2 errors in 1 file (checked 1 source file)
```

**Expected Behavior**

MyPy should have returned an error for the four different instantiations of a Generic class with the given attribute with incorrect types.
It should also have not shown `ContainerWithAlias.children` as having a type `Tuple[Any, Any]`.

**Actual Behavior**

MyPy only displayed an error for the attributes created without type aliases. 
It also considered the types in the type alias as being `Any` instead of the provided `TypeVar`.

**Your Environment**

- Mypy version used: **0.942**
- Mypy command-line flags: **None**
- Mypy configuration options from `mypy.ini` (and other config files): 

  in `setup.cfg`: `ignore_missing_imports = true`

- Python version used: **3.9.7**
- Operating system and version: Ubuntu LTS 20.04

**Comment by thomkeh** [comment]
The problem is the generic TypeAlias. If you do it like this, it works:
```python
@dataclasses.dataclass
class ContainerWithAlias(Generic[RestrictedChild]):

    children: TupleChildrenX2[RestrictedChild]
```
output:
```
tests.py:34: error: Argument "children" to "ContainerWithAlias" has incompatible type "Tuple[int, int]"; expected "Tuple[Daughter, Daughter]"
```

**Comment by erictraut** [comment]
Mypy is doing the right thing here. If you don't specify the type arguments for a generic type alias, mypy will correctly assume that you meant `Any` for these type arguments. If you use `--strict`, mypy will emit an error to remind you about these missing type arguments.

I don't see a bug here. I think this should be closed.
