### ISSUE TITLE
json

### ISSUE THREAD

**Issue by karmingc** [python/mypy#12522]
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

(Write your steps here:)

1. Step 1...
2. Step 2...
3. Step 3...

**Expected Behavior**

(Write what you thought would happen.)

**Actual Behavior**

(Write what happened.)

**Your Environment**

- Mypy version used:
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used:
- Operating system and version:

**Comment by JelleZijlstra** [comment]
python/typing#152. If you have a more specific problem, please report a bug that indicates it clearly.

**Comment by karmingc** [comment]
@JelleZijlstra apologies, it would seem I involuntarily clicked submit. I redirected my issue on [typeshed](https://github.com/python/typeshed/issues/7584). Do let me know if typing is more appropriate though.

**Comment by JelleZijlstra** [comment]
And I sent you on a chase to yet another repo :)
