### ISSUE TITLE
Mypy inferring `Union[str, str]` when using `enum.value` inside `dict.get`

### ISSUE THREAD

**Issue by patrick91** [python/mypy#12523]
Hi folks, I was updating Mypy and I discovered this (potential) bug, basically running mypy on this code:

```python
from enum import Enum


class Example(str, Enum):
    ACCOUNT = "account"
    ACCOUNT_2 = "account_2"
    
    def t(self) -> None:
        print(example_map.get(self.value))


example_map = {
    Example.ACCOUNT: 1,
    Example.ACCOUNT_2: 2,
}
```

triggers this error:

```
# print(example_map.get(self.value))
No overload variant of "get" of "Mapping" matches argument type "Union[str, str]"
```

This if fixed by doing:

```
print(example_map.get(self))
```

or by changing the map to

```
example_map = {
    Example.ACCOUNT.value: 1,
    Example.ACCOUNT_2.value: 2,
}
```

Is this behaviour expected? I'm asking because we have a lot of code that uses that pattern and changing it will require a lot of time. All the examples I've posted work in python

Playground URL: https://mypy-play.net/?mypy=latest&python=3.10&gist=d16680b7aa62a2f37ab09788432e9fa9

**Comment by JelleZijlstra** [comment]
Mypy's behavior seems correct to me. The map is of type `dict[Example, int]`, and `self.value` is of type str. It works at runtime because str-based enums compare equal to the corresponding string, but a type checker enforces more precise types.

The `Union[str, str]` is odd though. I guess we're missing a union simplification somewhere.

**Comment by patrick91** [comment]
> Mypy's behavior seems correct to me. The map is of type `dict[Example, int]`, and `self.value` is of type str. It works at runtime because str-based enums compare equal to the corresponding string, but a type checker enforces more precise types.

yeah, I do agree, I wish there was a way to make the transition easier though 😊

**Comment by JelleZijlstra** [comment]
Another workaround (though I haven't checked) is explicitly annotating the map as `dict[str, int]`. Unfortunately I don't see a feasible way for mypy to help your transition here. Maybe you can write a codemod script to help if this is a common issue in your codebase.

**Comment by AlexWaygood** [comment]
Yes, it [works fine](https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=b24361a974c8d2f4bd8cc0740a0ace0c) with the explicit annotation:

```python
from enum import Enum


class Example(str, Enum):
    ACCOUNT = "account"
    ACCOUNT_2 = "account_2"
    
    def t(self) -> None:
        print(example_map.get(self.value))


example_map: dict[str, int] = {
    Example.ACCOUNT: 1,
    Example.ACCOUNT_2: 2,
}
```

**Comment by patrick91** [comment]
thanks for the workaround! shall I keep this issue open or not?

The `No overload variant of "get" of "Mapping" matches argument type "Union[str, str]"` error I think it comes from Mypy typing `example_map` as a `Dict[Literal[] | Literal[]]`

**Comment by erictraut** [comment]
I agree with Jelle that mypy is doing the right thing here. I think this can be closed. It's not a bug.
