### ISSUE TITLE
Cannot find builtins when installed via buildout

### ISSUE THREAD

**Issue by vakaras** [python/mypy#1252]
Not sure if this is a problem with `buildout` or with `mypy`, but function `build.default_data_dir` returns `~/.buildout/eggs/mypy_lang-0.3.1-py3.4.egg` when it should return `~/.buildout/eggs/mypy_lang-0.3.1-py3.4.egg/lib/mypy`. As a result, I get an error: `mypy.errors.CompileError: tests/test_loop.py:1: error: Could not find builtins`.

**Comment by JukkaL** [comment]
Hmm I'm not familiar with buildout. Something with the directory layout seems to confuse mypy. It would be helpful if you can verify these things:

* Is there a `builtins.pyi` file in the installation (and where does it get installed)?
* Where does file `main.py` get installed?
* Where does file `mypy` get installed?

**Comment by vakaras** [comment]
The problem can be reproduced by using these steps:

    cd /tmp/test
    wget -c \
        https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.5.tar.gz \
        -O virtualenv.tar.gz
    tar -xvf virtualenv.tar.gz
    python3 virtualenv-14.0.5/virtualenv.py env
    env/bin/python bootstrap.py -c broken.cfg
    bin/buildout -U -c broken.cfg
    bin/mypy test.py

Expected behavior: prints nothing.
Actual behavior: prints `test.py:1: error: Could not find builtins`

I have tested this inside a docker image set up in this way:

    sudo docker run --rm -ti -v "$(pwd):/tmp/test" ubuntu:15.10
    apt-get update && apt-get install -y wget python3-dev git

**Comment by vakaras** [comment]
In my example:

+   `*.py` files get installed at `/tmp/test/eggs/mypy_lang-0.3.1-py3.4.egg/mypy`
+   `main.py` gets installed at `/tmp/test/eggs/mypy_lang-0.3.1-py3.4.egg/mypy/main.py`
+   `mypy` gets installed at `/tmp/test/bin/mypy`
+   `builtins.pyi` gets installed at `/tmp/test/eggs/mypy_lang-0.3.1-py3.4.egg/lib/mypy/typeshed/stdlib/3/builtins.pyi`
