### ISSUE TITLE
`allow-subclassing-any` also applies to subclassing the `Any` type as well as values with `Any` type

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#12529]
the `allow-subclassing-any`/`disallow-subclassing-any` flag seems to apply to two completely different scenarios:

### 1. subclassing a superclass of type `Any`

```py
from some_untyped_package import Foo   # type:ignore[import]

class Bar(Foo): # subclass has the type Any
    ...
```

### 2. subclassing the `Any` type itself
```py
from typing import Any

class Bar(Any): # subclass is the Any type
    ...
```

the latter is always invalid, as it's a runtime error (at least until python 3.11, see https://github.com/python/cpython/commit/5a4973e29f2f5c4ee8c086f40325786c62381540):
```
Traceback (most recent call last):
  File "c:\Users\amogus\project\Sandpit\test.py", line 4, in <module>
    class Foo(Any):pass
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\typing.py", line 377, in __mro_entries__
    raise TypeError(f"Cannot subclass {self!r}")
TypeError: Cannot subclass typing.Any
```

however when `allow-subclassing-any` is enabled, it allows both, when it should only allow scenario 1. scenario 2 should always be an error regardless of whether the flag is set or not

**Comment by AlexWaygood** [comment]
How would you propose tackling this without disallowing the following code (which seems perfectly reasonable to me)?

```python
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    class VeryDynamicClass(Any):
        # specific implementation here
else:
    class VeryDynamicClass:
        # specific implementation here
```

All mypy will see is the definition inside the `if TYPE_CHECKING` block.

**Comment by DetachHead** [comment]
perhaps creating error codes other than `misc` such that it can be safely `type:ignore`d in such edge cases

```py
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    class VeryDynamicClass(Any):  # type:ignore[no-subclass-any-type]
        # specific implementation here
else:
    class VeryDynamicClass:
        # specific implementation here
```

and a different error code for the other scenario:
```py
from some_untyped_package import Foo   # type:ignore[no-subclass-any-value]

class Bar(Foo): # type
    ...
```

**Comment by KotlinIsland** [comment]
@AlexWaygood 
> How would you propose tackling this without disallowing the following code (which seems perfectly reasonable to me)?
> 
> ```python
> from typing import Any, TYPE_CHECKING
> 
> if TYPE_CHECKING:
>     class VeryDynamicClass(Any):
>         # specific implementation here
> else:
>     class VeryDynamicClass:
>         # specific implementation here
> ```
> 
> All mypy will see is the definition inside the `if TYPE_CHECKING` block.

There are many situations where mypy could allow invalid code within `TYPE_CHECKING` blocks. So until such time that that is implemented simply type ignoring it would be perfectly sufficient IMO.

```py
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
     class VeryDynamicClass(Any):  # type: ignore[misc]
         # specific implementation here
else:
     class VeryDynamicClass:
         # specific implementation here
```

I think the value of finding the invalid subtyping of `Any` outweighs the value of this easy workaround.

What I find concerning is that this isn't an error unless the strict/any flags are enabled.

**Comment by AlexWaygood** [comment]
The purpose of allowing subclassing Any is to do [things like this](https://mypy-play.net/?mypy=latest&python=3.10&gist=05378063ec15e1a539615be248be6f4d), where certain methods/attributes are statically defined, but the class is assumed to behave like `Any` in all other respects:

```python
from typing import Any

class Foo(Any):
    def bar(self, arg: int) -> bytes: ...

f = Foo()
reveal_type(f.bar(6))  # revealed type is bytes
f.bar('not an int')  # error
reveal_type(f.baz('idk'))   # revealed type is Any
```

**Comment by KotlinIsland** [comment]
@AlexWaygood sure, but subclassing `Any` is only supported in 3.11

**Comment by hauntsaninja** [comment]
Consider mypy support for subclassing Any in stubs or via the `if TYPE_CHECKING` in Python 3.10 and lower "official"
