### ISSUE TITLE
`match` crashes on Union of Tuple and non-Tuple

### ISSUE THREAD

**Issue by bkovitz** [python/mypy#12533]
**Crash Report**

_mypy_ 0.942 crashes when the match expression in a match statement is a Union of a Tuple type and a non-tuple type.

**Traceback**

```
$ mypy --python-version 3.10 --show-traceback x.py
x.py:14: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.942
Traceback (most recent call last):
  File "mypy/checker.py", line 424, in accept
  File "mypy/nodes.py", line 1405, in accept
  File "mypy/checker.py", line 4110, in visit_match_stmt
  File "mypy/checkpattern.py", line 107, in accept
  File "mypy/patterns.py", line 87, in accept
  File "mypy/checkpattern.py", line 301, in visit_sequence_pattern
  File "mypy/checkpattern.py", line 656, in construct_sequence_child
  File "mypy/checkpattern.py", line 663, in construct_sequence_child
AssertionError: 
x.py:14: : note: use --pdb to drop into pdb

```

**To Reproduce**

(Write what you did to reproduce the crash.  Full source code is
appreciated.  We also very much appreciate it if you try to narrow the
source down to a small stand-alone example.)

```
from typing import Union

def func(e: Union[str, tuple[str]]) -> None:
    match e:
        case (a,) if isinstance(a, str):
            print('HERE', e)
```

**Notes**

If we change the type of tuple inside the Union to a tuple with no contents specified, like this:

    def func(e: Union[str, tuple]) -> None:

then there is no crash.

This might be due to the same underlying bug as [#12532](https://github.com/python/mypy/issues/12532).

**Environment**

- Mypy version used: 0.942
- Mypy command-line flags: ` --python-version 3.10 --show-traceback x.py`
- Mypy configuration options from `mypy.ini` (and other config files): (none)
- Python version used: 3.10.2
- Operating system and version: Ubuntu 18.04

**Comment by MartinNowak** [comment]
I have a similar, but slightly different case triggering this.
```py
        match cast(results.get(table_ref), tuple[str, int | None]):
            case _, None:
                return f"`{table_ref.undecorated}{m['alias'] or ''}`"
            case _, snapshotTime:
                return f"`{table_ref.undecorated}{m['alias'] or ''}` FOR SYSTEM_TIME AS OF TIMESTAMP_MILLIS({snapshotTime})"
            case None:
                return m[0]
            case table_info:
                raise NotImplementedError(f"Unexpected table info {table_info}")
```
Will try to reduce this test case further when I find some time :/.

**Comment by Artemis21** [comment]
Minimised test case:
```python
foo: tuple[int] | int
match foo:
    case (x,): pass
```

**Comment by gertvdijk** [comment]
Similar if not identical traceback with union of tuples (so not just non-tuple):

```python
import ipaddress
from typing import Literal

from typing_extensions import reveal_type

fam = Literal["4", "u"]

myvar: tuple[fam, ipaddress.IPv4Address] | tuple[fam, str] = ("u", "/mysock")

match myvar:
    case ("u", socket_path):
        reveal_type(socket_path)
    case ("4", ip):
        reveal_type(ip)
```

```
mypyerror.py:12: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.961
Traceback (most recent call last):
  File "mypy/checker.py", line 431, in accept
  File "mypy/nodes.py", line 1415, in accept
  File "mypy/checker.py", line 4155, in visit_match_stmt
  File "mypy/checkpattern.py", line 104, in accept
  File "mypy/patterns.py", line 87, in accept
  File "mypy/checkpattern.py", line 300, in visit_sequence_pattern
  File "mypy/checkpattern.py", line 651, in construct_sequence_child
  File "mypy/checkpattern.py", line 658, in construct_sequence_child
AssertionError: 
mypyerror.py:12: : note: use --pdb to drop into pdb
```

**Comment by sparkiegeek** [comment]
With #13514 landing in master, I thought it would be worth trying a development build of mypy which was crashing for me with what I believe to be this bug.

I can confirm that mypy no longer crashes, but it also seems to have lost typing information for variables assigned in the `match` statement.

I have tried to simplify down my complex scenario to a simple reproducer

```python
from typing import Literal, TypeAlias

CreateOp: TypeAlias = tuple[Literal[1], list]
DeleteOp: TypeAlias = tuple[Literal[2], list]
Ops: TypeAlias = list[CreateOp | DeleteOp]
# No issue when Ops isn't a Union
#Ops: TypeAlias = list[CreateOp]


changes: Ops = []
for change in changes:
    match change:
        case [1, target]:
            reveal_type(target)
            target.append(1)
    
```

Running the above through mypy 0.942 causes a crash, and with master outputs the following:

```
$ mypy test_mypy.py 
test_mypy.py:14: note: Revealed type is "builtins.object"
test_mypy.py:15: error: "object" has no attribute "append"
Found 1 error in 1 file (checked 1 source file)
``` 

By switching around the definition of Ops to the commented one, mypy passes and the Revealed type is `builtins.list[Any]` as expected

**Comment by antonagestam** [comment]
@sparkiegeek FWIW, that sounds exactly like what is pointed out in a TODO in the merged PR, here:

https://github.com/python/mypy/pull/13514/files#diff-9100781e1e8bb8997aa611cce8014d8680677e036e9652d59fbd86336f80c3feR1624

**Comment by sparkiegeek** [comment]
> @sparkiegeek FWIW, that sounds exactly like what is pointed out in a TODO in the merged PR, here:
> 
> https://github.com/python/mypy/pull/13514/files#diff-9100781e1e8bb8997aa611cce8014d8680677e036e9652d59fbd86336f80c3feR1624

Possibly, but if it were that, then wouldn't my reproducer have an inferred type of `Union[builtins.list, builtins.list]` (AKA `builtins.list`) and not `builtins.object`? Since both of the potential types of an 'Op' have the same type after the Literal

**Comment by hauntsaninja** [comment]
Btw, is the project you encountered this on open source? If so, I can add it to https://github.com/hauntsaninja/mypy_primer

**Comment by bkovitz** [comment]
@hauntsaninja The project where I ran into this issue is: https://github.com/bkovitz/FARGish
It's an open-source project, but the directories are a mess right now—lots of old versions—and there's no good written explanation of what it does. You're welcome to list it, though.
