### ISSUE TITLE
mypy incorrectly identifies statements as unreachable when matching against constants

### ISSUE THREAD

**Issue by menma1234** [python/mypy#12545]
**Bug Report**

When using a `match` statement with `case`s that are constants, it incorrectly identifies the later cases as being unreachable.

**To Reproduce**

I have the following file structure:

```
project_root
    util
        __init__.py
        consts.py
        test.py
```

In `consts.py`:

```python
BLANK = ""
SPECIAL = "asdf"
```

In `test.py`:

```python
from util import consts


def test_func(test_str: str) -> str:
    match test_str:
        case consts.BLANK:
            return "blank"
        case consts.SPECIAL:
            return "special"
        case _:
            return "other"
```

**Expected Behavior**

`mypy` succeeds as the code is reachable.

**Actual Behavior**

Running `mypy --warn-unreachable .\util\test.py` gives:

```
util\test.py:9: error: Statement is unreachable
util\test.py:11: error: Statement is unreachable
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.942
- Mypy command-line flags: `--warn-unreachable`
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10
- Operating system and version: Windows 10

**Comment by Kurt-von-Laven** [comment]
Not sure whether this is related or separate, but I experience the same symptom in the following scenario:

```py
match {"x": {"y": [1]}}:
    case {"x": {"y": [value]}:
        print("mypy believes this line is unreachable")
```

Happy to file a separate issue if desired. Intriguingly, if you remove the outer dictionary, mypy stops complaining. This bug particularly impacts the use of structural pattern matching in code that handles JSON, which obviously frequently contains complex nested data structures.

**Comment by Kurt-von-Laven** [comment]
Evidently the issue I mentioned was a separate one, so I filed #12770.
