### ISSUE TITLE
Regression on exclude definition in setup.cfg

### ISSUE THREAD

**Issue by ingwinlu** [python/mypy#12567]
**Bug Report**

I noticed a regression between 0.930 and 0.942 of mypy.

On 0.930 the following exclude section in our setup.cfg works:
```
[mypy]
files=our_project_name_cdk,tests
ignore_missing_imports=true
exclude =
    hefm_cdk/constructs/apis/lambdas/data_processing_api
    hefm_cdk/constructs/batches/some_replaced_folder/jobs/lambdas/dummy_segmentation
    hefm_cdk/constructs/ec2s/scripts/some_replaced_folder/processor-share
    hefm_cdk/constructs/ec2s/scripts/some_replaced_folder/results_processor
    hefm_cdk/constructs/ec2s/scripts/some_replaced_folder/uploads_processor
    hefm_cdk/constructs/stepfunctions/some_replaced_folder/lambdas/encapsulate_pdf
    hefm_cdk/constructs/stepfunctions/some_replaced_folder/lambdas/extract_data
    hefm_cdk/constructs/stepfunctions/some_replaced_folder/lambdas/generate_pdf
    hefm_cdk/constructs/stepfunctions/some_replaced_folder/lambdas/normalize_dicom_files
    hefm_cdk/constructs/stepfunctions/some_replaced_folder/lambdas/pseudonymize_dicom_files
```

Once I update to 0.942 I get errors mentioning the excluded folders.

As you can guess from the folder structure we use python cdk and deploy lambdas (both are checked with mypy but in different tox environments, hence we want to exclude the lambda folders for the global mypy check).

**Expected Behavior**

Config is respected

**Actual Behavior**

Config is not respected

see above

**Your Environment**

see above

**Comment by hauntsaninja** [comment]
Closing since there isn't enough info to reproduce and this is stale
