### ISSUE TITLE
Using a decorator breaks type detection

### ISSUE THREAD

**Issue by xmatthias** [python/mypy#12585]
**Bug Report**

The following code  raises an "incompatible type" exception on the argument of `some_func` if the decorator is disabled - which is correct.
If the decorator `@some_decorator` is added, then this type-error is hidden, so mypy is no longer detecting this as error.

This effectively disables type-checking for all decorated functions.

``` python

from functools import wraps


def some_decorator(fn):
    @wraps(fn)
    def decorator(*args, **kwargs):
        return fn(*args, **kwargs)
    return decorator


# Comment this decorator to see exception
@some_decorator
def some_func(arg: int = 10):
    return arg


for x in (None, 100):
    print(some_func(x))

```

**Expected Behavior**

Mypy shows an error in the above code for the  argument of `some_func`
`error: Argument 2 to "some_func" has incompatible type "Optional[int]"; expected "int"`

**Actual Behavior**

Mypy is not showing any error when the decorator is applied.
With the error removed, mypy is working as expected, showing type-errors.

**Your Environment**

- Mypy version used: 0.942
- Mypy command-line flags: NA
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9.7
- Operating system and version: linux

**Comment by JelleZijlstra** [comment]
Your decorator is untyped, so mypy assumes it returns Any. See https://mypy.readthedocs.io/en/stable/generics.html?highlight=decorator#declaring-decorators
