### ISSUE TITLE
Remove Python 2 `lib-typing`

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1260]
This may need to be disentangled from the build system, and we may need to get `typing` before running integration tests.

**Comment by gvanrossum** [comment]
Actually I think lib-typing still serves a purpose. It installs a recent version of typing.py when mypy is installed with Python 3.2, 3.3, 3.4 and that's reasonable -- it means the user doesn't have to remember to also run `pip install typing`. It also contains a recent Python 2 backport of typing.py and even a setup.py script for that (although the usual way to install typing is again `pip install typing`). I think I'll leave this as-is.
