### ISSUE TITLE
Typevar and multiple  arguments bug

### ISSUE THREAD

**Issue by srobertson** [python/mypy#12603]
**Bug Report**

MyPy 0.942 seems to ignore TypeVar for multiple arguments.

**To Reproduce**

Create code like tho following and type check it
```python
T = TypeVar('T')

def tie_type_to_val(type_:Type[T], val:T)-> T:
    return val

def const(a:T, b:T) -> T:
    return a

def test_foo()-> None:
    tie_type_to_val(str, 1) # This should fail Type[T] = str so val should also be a str
    const("a",2) # This should not type check  a=str, b=int
```

**Expected Behavior**

Expect mypy to complain when calling tie_type_to_val() or const() that the types do not match

**Actual Behavior**

This code type checks.
**Your Environment**

- MyPy 0.942 
- Mypy command-line flags:
- none
- Mypy config
```[mypy]
namespace_packages = True
disallow_untyped_defs = True
```

**Comment by JelleZijlstra** [comment]
This is correct behavior. TypeVars get resolved to their common type, not necessarily to the same type. In your case, mypy likely solves `T` to `object`.
