### ISSUE TITLE
Disabling implicit_reexport in an override leads to a different error

### ISSUE THREAD

**Issue by rnestler** [python/mypy#12646]
**Bug Report**

I have the issue that a third party library uses an implicit export, which leads to an error when checking with strict mode:
```
error: Module "simple_pid" does not explicitly export attribute "PID"; implicit reexport disabled
```

If I disable on the command line with `mypy --implicit-reexport` or globaly in pyproject.toml with `implicit_reexport = true` it works.

But if I disable it for the affected module in `[[tool.mypy.overrides]]` it leads to a different error:
```
error: Module "simple_pid" has no attribute "PID"
```

**To Reproduce**

1. install `simple-pid==1.0.1`
2. test.py with just `from simple_pid import PID`
3. pyproject.toml with
    ```toml
    [tool.mypy]
    strict = true

    [[tool.mypy.overrides]]
    module = "test"
    implicit_reexport = true
    ```

**Expected Behavior**

Module overrides should behave the same as global overrides

**Actual Behavior**

Module override leads to a different error.

**Your Environment**

- Mypy version used: mypy 0.942
- Mypy command-line flags: See above
- Mypy configuration options from `mypy.ini` (and other config files): See above
- Python version used: Python 3.10.4
- Operating system and version: ArchLinux

**Comment by hauntsaninja** [comment]
The error message got improved at some point since then!
