### ISSUE TITLE
Document practices in a CONTRIBUTING file

### ISSUE THREAD

**Issue by gnprice** [python/mypy#1265]
@brettcannon pointed out yesterday as a followup to #924 that GitHub has a handy feature to help us highlight some information for people who participate by creating PRs and issues: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

We should make one of those -- doesn't need to be very long. Topics to cover include
* the code of conduct (#924)
* the conventions @ddfisher, @JukkaL, and I established yesterday for triaging issues and haven't yet properly documented
* the basic workflow of PRs (#1070)
* either link to or incorporate all the other material at http://www.mypy-lang.org/wiki/DeveloperGuides

**Comment by brettcannon** [comment]
GitHub also launched issue and PR templates recently in case you didn't know about that as well: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by gnprice** [comment]
@brettcannon: also interesting, thanks! I don't immediately have ideas I want to use that feature for, but we certainly might.
