### ISSUE TITLE
MyPy does not consider classes instances of their metaclass

### ISSUE THREAD

**Issue by wittekm** [python/mypy#1267]
Playing around with a toy situation as below:

```
class AsdfMeta(type): pass
class AsdfConcrete1(object):
  __metaclass__ = AsdfMeta

def accepts_an_asdf_class(klass): # type: (AsdfMeta) -> None
  pass

accepts_an_asdf_class(AsdfConcrete1)
accepts_an_asdf_class(AsdfConcrete1())
accepts_an_asdf_class("hello, i am a string and not a class with metaclass AsdfMeta")
```

I get back 

```
56: error: Argument 1 to "accepts_an_asdf_class" has incompatible type "AsdfConcrete1"; expected "AsdfMeta"
57: error: Argument 1 to "accepts_an_asdf_class" has incompatible type "AsdfConcrete1"; expected "AsdfMeta"
58: error: Argument 1 to "accepts_an_asdf_class" has incompatible type "unicode"; expected "AsdfMeta"
```

(This is super low-priority in my opinion.)

**Comment by Diggsey** [comment]
This is problematic with Enums, because enums have the `__members__` property on their metaclass. Annoyingly it can't be faked by adding a `__members__` field to the enum class itself, because it gets retyped by mypy as though it were a variant of the enum.

**Comment by gvanrossum** [comment]
Another curious case where this is problematic: ctypes defines classes (e.g. `c_char`) that can be multiplied (e.g. `c_char*16` is an array of 16 bytes).

**Comment by ilevkivskyi** [comment]
This issue seems to be fixed by #2475 (but only with python 3 syntax, ``metaclass=AsdfMeta``). The first function call passes. two other fail.

**Comment by JukkaL** [comment]
Updated priority since it looks like this should be easier to fix now that #2475 has landed.

**Comment by gvanrossum** [comment]
Looks like this is now fixed (in master). I get the last two errors (which seem expected) but this line is now error-free in the example:
```python
accepts_an_asdf_class(AsdfConcrete1)
```

**Comment by wittekm** [comment]
Cool! Yes, the latter two are counterexamples.
