### ISSUE TITLE
Code examples not readable with dark-mode

### ISSUE THREAD

**Issue by cdce8p** [python/mypy#12684]
**Documentation**

The new docs theme looks great! Unfortunately though, most code blocks aren't readable with dark mode.
/CC: @97littleleaf11

https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#variables

<img width="782" alt="Screen Shot 2022-04-28 at 01 53 36" src="https://user-images.githubusercontent.com/30130371/165649559-83ebccfa-ea4e-406f-a3aa-026be24dbc02.png">

**Comment by 97littleleaf11** [comment]
Thanks for reporting! What's your web browser? I am using safari and chrome and it looks good.
<img width="861" alt="截屏2022-05-02 10 44 11" src="https://user-images.githubusercontent.com/11172084/166178375-8328df6c-8dc7-48c9-850b-19e698741151.png">

**Comment by cdce8p** [comment]
Just checked it again. Seems like the issue is gone. Maybe something with my browser cache. Will close it.
