### ISSUE TITLE
[unclear documentation] Are incomplete type annotations allowed under --disallow-untyped-defs?

### ISSUE THREAD

**Issue by beauxq** [python/mypy#12693]
**Documentation**

The config file documentation specifies that incomplete type annotations are not allowed under `disallow_untyped_defs` https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_untyped_defs

But the command line documentation https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-untyped-defs does not specify whether incomplete type annotations are allowed.

Is the command line option different from the config file option?

semi-related functionality issue about whether incomplete type annotations are allowed under `disallow-untyped-defs`: https://github.com/python/mypy/issues/12256

**Comment by dibrinsofor** [comment]
was this ever handled?
