### ISSUE TITLE
Upgrade typing.py from python/typing repo

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1272]
The versions of typing.py installed by mypy (in lib-typing/{2.7,3.2}) are out of date. They should be updated to the latest versions in python/typing.

**Comment by gvanrossum** [comment]
(But wait for https://github.com/python/typing/issues/187.)

**Comment by ddfisher** [comment]
Maybe we should just remove `lib-typing` instead?  (#1260)

**Comment by gvanrossum** [comment]
Well, IIUC installing mypy installs typing.py from there. Check setup.py.

--Guido (mobile)

**Comment by JukkaL** [comment]
Yeah, mypy installs typing.py when not on Python 3.5 Perhaps we should use the typing backport on PyPI instead. That's probably not a priority, though.

**Comment by gvanrossum** [comment]
You could just add it to the package dependencies I suppose.

Also, there's no way that the included 2.7 version of typing will
actually be installed, right?

**Comment by gvanrossum** [comment]
Done in #1479 (8b7eea9ce30fa7662528ec389d0fe94ad27271ce). While this is theoretically an ongoing task I don't like keeping an issue open for it.
