### ISSUE TITLE
(🐞)  Sus imposter `?` when revealing an inferred literal type

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12721]
```py
from typing import *

a: Final = 1
reveal_type(a)  # Literal[1]?
reveal_type(1)  # Literal[1]?
```
https://github.com/python/mypy/blob/ad177f99fd3322072e389a1a7432ee7b15c84472/mypy/types.py#L2629-L2635

**Comment by AlexWaygood** [comment]
How is this different to the (very useful) other issue you filed a while back:

- #11519

?

**Comment by KotlinIsland** [comment]
That one is regarding documenting all the hieroglyphics in output messages, this is specifically regarding the functionality of this bug.

**Comment by AlexWaygood** [comment]
My preferred solution to both would just be to not add the `?` at all, so personally I think they could both be discussed in the same issue.

**Comment by hauntsaninja** [comment]
Closing as a duplicate
