### ISSUE TITLE
TypedDict with total=False does not allow clear

### ISSUE THREAD

**Issue by haroldmeerwaldt** [python/mypy#12732]
**Bug Report**

I made a TypedDict with `total=False` . Then I wanted to clear it, but I got an [attr-defined] error. I can do pop, so I would expect to be able to do clear as well.

**To Reproduce**
```python
from typing import TypedDict


class MyTypedDict(TypedDict, total=False):
    param1: int
    param2: str

td: MyTypedDict = {"param1": 2, "param2": "foo"}
td.pop("param1")
td.clear()
```

**Actual Behavior**

I got 

```
scratch_37.py:10: error: "MyTypedDict" has no attribute "clear"  [attr-defined]
```

**Your Environment**
- Mypy version used: 0.950
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): 
```
# The following options are set by the --strict command line flag
warn_unused_configs=True
disallow_any_generics=True
disallow_subclassing_any=True
disallow_untyped_calls=True
disallow_untyped_defs=True
disallow_incomplete_defs=True
check_untyped_defs=True
disallow_untyped_decorators=True
no_implicit_optional=True
warn_redundant_casts=True
warn_unused_ignores=True
warn_return_any=True
no_implicit_reexport=True
strict_equality=True
# End of --strict options

ignore_missing_imports=True
show_error_codes=True

plugins=pydantic.mypy, numpy.typing.mypy_plugin
```
- Python version used: 3.9.9
- Operating system and version: Windows 10

**Comment by alicederyn** [comment]
This behaviour is correct. According to https://peps.python.org/pep-0589/

> clear() is not safe since it could remove required keys, some of which may not be directly visible because of structural subtyping. popitem() is similarly unsafe, even if all known keys are not required (total=False).

**Comment by JukkaL** [comment]
If somebody still really wants to allow this, the best bet would be to define a specific error code for these errors which could be disabled globally (I'm not promising that we'd accept a PR, but we might).

**Comment by alicederyn** [comment]
I believe the correct approach would be to declare the type `@final`, disallowing the structural subtyping that is making the `clear` illegal. However, mypy doesn't handle that correctly. I opened https://github.com/python/mypy/issues/12732 to track.

**Comment by alicederyn** [comment]
That's a good point lol, https://github.com/python/mypy/issues/14914

**Comment by JukkaL** [comment]
A great point, supporting `@final` would be a better way to deal with this.
