### ISSUE TITLE
typed_ast>=1.4.0 in MAC M1 build Failed

### ISSUE THREAD

**Issue by th-520** [python/mypy#12739]
typed_ast==1.4.0 in Mac M1 build failed
mypy==0.812
pip3 install mypy==0.812    

Collecting mypy==0.812
  Using cached mypy-0.812-py3-none-any.whl (2.5 MB)
Collecting mypy-extensions<0.5.0,>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting typed-ast<1.5.0,>=1.4.0
  Using cached typed_ast-1.4.3.tar.gz (210 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: typed-ast
  Building wheel for typed-ast (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-39
      creating build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      copying typed_ast/conversions.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      copying typed_ast/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      copying typed_ast/ast3.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      copying typed_ast/ast27.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      package init file 'ast3/tests/__init__.py' not found (or not a regular file)
      creating build/lib.macosx-10.9-universal2-cpython-39/typed_ast/tests
      copying ast3/tests/test_basics.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast/tests
      running build_ext
      building '_ast27' extension
      creating build/temp.macosx-10.9-universal2-cpython-39
      creating build/temp.macosx-10.9-universal2-cpython-39/ast27
      creating build/temp.macosx-10.9-universal2-cpython-39/ast27/Custom
      creating build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser
      creating build/temp.macosx-10.9-universal2-cpython-39/ast27/Python
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Custom/typed_ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Custom/typed_ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/acceler.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/acceler.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/bitset.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/bitset.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/grammar.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/grammar.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/grammar1.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/grammar1.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/node.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/node.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/parser.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/parser.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/parsetok.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/parsetok.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/tokenizer.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/tokenizer.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/Python-ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/Python-ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/asdl.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/asdl.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/graminit.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/graminit.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/mystrtoul.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/mystrtoul.o
      gcc -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-cpython-39/ast27/Custom/typed_ast.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/acceler.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/bitset.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/grammar.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/grammar1.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/node.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/parser.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/parsetok.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/tokenizer.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/Python-ast.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/asdl.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/ast.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/graminit.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/mystrtoul.o -o build/lib.macosx-10.9-universal2-cpython-39/typed_ast/_ast27.cpython-39-darwin.so
      building '_ast3' extension
      creating build/temp.macosx-10.9-universal2-cpython-39/ast3
      creating build/temp.macosx-10.9-universal2-cpython-39/ast3/Custom
      creating build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser
      creating build/temp.macosx-10.9-universal2-cpython-39/ast3/Python
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Custom/typed_ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Custom/typed_ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/acceler.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/acceler.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/bitset.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/bitset.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/grammar.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/grammar.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/grammar1.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/grammar1.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/node.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/node.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/parser.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/parser.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/parsetok.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/parsetok.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/tokenizer.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/tokenizer.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Python/Python-ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Python/Python-ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Python/asdl.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Python/asdl.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Python/ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Python/ast.o
      ast3/Python/ast.c:844:5: warning: code will never be executed [-Wunreachable-code]
          abort();
          ^~~~~
      ast3/Python/ast.c:4514:9: error: implicit declaration of function '_PyUnicode_DecodeUnicodeEscape' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          v = _PyUnicode_DecodeUnicodeEscape(s, len, NULL, &first_invalid_escape);
              ^
      ast3/Python/ast.c:4514:9: note: did you mean 'PyUnicode_DecodeUnicodeEscape'?
      /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/unicodeobject.h:588:23: note: 'PyUnicode_DecodeUnicodeEscape' declared here
      PyAPI_FUNC(PyObject*) PyUnicode_DecodeUnicodeEscape(
                            ^
      ast3/Python/ast.c:4514:7: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
          v = _PyUnicode_DecodeUnicodeEscape(s, len, NULL, &first_invalid_escape);
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      2 warnings and 1 error generated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for typed-ast
  Running setup.py clean for typed-ast
Failed to build typed-ast
Installing collected packages: typed-ast, mypy-extensions, typing-extensions, mypy
  Running setup.py install for typed-ast ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for typed-ast did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      running install
      /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-39
      creating build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      copying typed_ast/conversions.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      copying typed_ast/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      copying typed_ast/ast3.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      copying typed_ast/ast27.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast
      package init file 'ast3/tests/__init__.py' not found (or not a regular file)
      creating build/lib.macosx-10.9-universal2-cpython-39/typed_ast/tests
      copying ast3/tests/test_basics.py -> build/lib.macosx-10.9-universal2-cpython-39/typed_ast/tests
      running build_ext
      building '_ast27' extension
      creating build/temp.macosx-10.9-universal2-cpython-39
      creating build/temp.macosx-10.9-universal2-cpython-39/ast27
      creating build/temp.macosx-10.9-universal2-cpython-39/ast27/Custom
      creating build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser
      creating build/temp.macosx-10.9-universal2-cpython-39/ast27/Python
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Custom/typed_ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Custom/typed_ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/acceler.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/acceler.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/bitset.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/bitset.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/grammar.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/grammar.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/grammar1.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/grammar1.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/node.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/node.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/parser.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/parser.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/parsetok.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/parsetok.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Parser/tokenizer.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/tokenizer.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/Python-ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/Python-ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/asdl.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/asdl.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/graminit.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/graminit.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast27/Python/mystrtoul.c -o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/mystrtoul.o
      gcc -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-cpython-39/ast27/Custom/typed_ast.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/acceler.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/bitset.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/grammar.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/grammar1.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/node.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/parser.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/parsetok.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Parser/tokenizer.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/Python-ast.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/asdl.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/ast.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/graminit.o build/temp.macosx-10.9-universal2-cpython-39/ast27/Python/mystrtoul.o -o build/lib.macosx-10.9-universal2-cpython-39/typed_ast/_ast27.cpython-39-darwin.so
      building '_ast3' extension
      creating build/temp.macosx-10.9-universal2-cpython-39/ast3
      creating build/temp.macosx-10.9-universal2-cpython-39/ast3/Custom
      creating build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser
      creating build/temp.macosx-10.9-universal2-cpython-39/ast3/Python
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Custom/typed_ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Custom/typed_ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/acceler.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/acceler.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/bitset.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/bitset.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/grammar.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/grammar.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/grammar1.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/grammar1.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/node.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/node.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/parser.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/parser.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/parsetok.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/parsetok.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Parser/tokenizer.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Parser/tokenizer.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Python/Python-ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Python/Python-ast.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Python/asdl.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Python/asdl.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast3/Include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c ast3/Python/ast.c -o build/temp.macosx-10.9-universal2-cpython-39/ast3/Python/ast.o
      ast3/Python/ast.c:844:5: warning: code will never be executed [-Wunreachable-code]
          abort();
          ^~~~~
      ast3/Python/ast.c:4514:9: error: implicit declaration of function '_PyUnicode_DecodeUnicodeEscape' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          v = _PyUnicode_DecodeUnicodeEscape(s, len, NULL, &first_invalid_escape);
              ^
      ast3/Python/ast.c:4514:9: note: did you mean 'PyUnicode_DecodeUnicodeEscape'?
      /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/unicodeobject.h:588:23: note: 'PyUnicode_DecodeUnicodeEscape' declared here
      PyAPI_FUNC(PyObject*) PyUnicode_DecodeUnicodeEscape(
                            ^
      ast3/Python/ast.c:4514:7: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
          v = _PyUnicode_DecodeUnicodeEscape(s, len, NULL, &first_invalid_escape);
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      2 warnings and 1 error generated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> typed-ast

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by JelleZijlstra** [comment]
Mypy 0.812 is old. Please upgrade.
