### ISSUE TITLE
Optionally silence success output

### ISSUE THREAD

**Issue by berzi** [python/mypy#12738]
**Feature**
Could the "Success: no issues found in ### source files" be optionally disabled with a flag like `--silent-success` or similar?

**Pitch**
Most code quality tools show no output or have at least an option to silence it when there are no errors, which is conventional for many scripts and Linux commands, so I believe my team and I are the only ones who would wish this.
This would allow cleaner outputs in scripts that run Mypy alongside other tools and in pipeline logs, where more noise can make important information harder to find.

Possible names for the option:
- `--silent-success`
- `--silent`
- `--no-success-message`
- `--quiet` && `-q` (my personal preference, as it's already used by other tools such as `black`)

**Comment by hauntsaninja** [comment]
`--no-error-summary` should work but also note that it's easy to write shell logic to do this kind of thing
