### ISSUE TITLE
Can’t use DefaultArg(…) within Concatenate[…]

### ISSUE THREAD

**Issue by andersk** [python/mypy#12735]
There seems to be no way to annotate a decorator that prepends a parameter with a default value. Trying to use `DefaultArg(…)` within `Concatenate[…]` results in an error:

```python
from typing import Callable, Concatenate, ParamSpec
from mypy_extensions import DefaultArg

P = ParamSpec("P")

def foo(f: Callable[P, None]) -> Callable[Concatenate[DefaultArg(int), P], None]:
    def g(n: int = 0, /, *args: P.args, **kwargs: P.kwargs) -> None:
        f(*args, **kwargs)

    return g
```

[Mypy playground link](https://mypy-play.net/?mypy=latest&python=3.10&gist=5aab4b85fecbac3dc1fc83033d625bb9)

```
main.py:6: error: Invalid type comment or annotation
main.py:6: note: Suggestion: use DefaultArg[...] instead of DefaultArg(...)
Found 1 error in 1 file (checked 1 source file)
```

(The automatic suggestion is clearly wrong and doesn’t work either.)

**Comment by JelleZijlstra** [comment]
This isn't supported by PEP 612 and it is unsafe, because P could contain required positional-only arguments.

We should think about deprecating DefaultArg and friends. They are mypy-specific and the use case is better covered by callback protocols.

Agree the note doesn't make much sense though.

**Comment by andersk** [comment]
AFAICS, nothing unsafe would happen if `P` contains required positional-only arguments. The resulting type would simply prevent you from omitting the initial default parameter in that case, which is fine.

Callback protocols [don’t work](https://github.com/python/typing/discussions/1040) for defining methods (which my [actual use case](https://github.com/zulip/zulip/blob/7a24da70a1d83bc54f3cb94c1fa3202583e4a7f2/zerver/lib/test_helpers.py#L358) is).

**Comment by AlexWaygood** [comment]
> We should think about deprecating DefaultArg and friends. They are mypy-specific and the use case is better covered by callback protocols.

They're already deprecated: https://mypy.readthedocs.io/en/stable/additional_features.html#extended-callable-types

**Comment by ilevkivskyi** [comment]
Yes, `DefaultArg` etc are all deprecated and should not be used. If you have troubles using callback protocols, you can ask for help elsewhere (or file a separate issue, if you think there is a bug, btw I don't think the question you linked applies to your case, it is about a heavily special-cased situation of defining a method using an _assignment statement_, and this special-casing apparently doesn't handle callback protocols well yet).
