### ISSUE TITLE
can't use assert_type to check that a class implements a protocol; maybe there's a use for `typing.assert_subtype`?

### ISSUE THREAD

**Issue by DMRobertson** [python/mypy#12746]
As part of debugging a typing problem, I tested my understanding of mypy's behaviour with the following example.

```python
from typing_extensions import *

class HasName(Protocol):
    name: str

class Dog:
    pass

class NamedDog(Dog):
    name: str
    def __init__(self, name: str):
        self.name = name
        
rover = NamedDog("Rover")

assert_type(rover, HasName)
assert_type(rover, Dog)
assert_type(rover, NamedDog)
```

Mypy objected to the first two assertions:

```
temp.py:16: error: Expression is of type "NamedDog", not "HasName"  [assert-type]
temp.py:17: error: Expression is of type "NamedDog", not "Dog"  [assert-type]
```

I was surprised by this, but after reading through the [3.11 alpha docs](https://docs.python.org/3.11/library/typing.html#typing.assert_type) it some thought I think it makes sense. I think that `assert_type(x, T)` is analagous to `type(x) is T` rather than `isinstance(x, T)`?

I think a `typing.assert_subtype` function would be great to have.

(Not sure if this is the right place to propose it. I found https://mail.python.org/archives/list/typing-sig@python.org/thread/MITFQ6Z45RRMXY3HNM66IC3XXS3TA3JN/ but am not sure of how that list/process works.)

**Comment by JelleZijlstra** [comment]
You're right that `assert_type` does an exact match, not a subtype check, and you're also right that typing-sig is a good place to propose new features, though you can also open an issue on https://github.com/python/typing.

An approach that works today is defining a function that takes a `HasName` argument:

```python
def needs_has_name(arg: HasName) -> None: ...

needs_has_name(rover)  # no error
```

I think that's good enough that it's not worth adding a new type system feature here.

**Comment by DMRobertson** [comment]
> An approach that works today is defining a function that takes a `HasName` argument:

Ahh, that's a good tip, and more than does the trick. Thanks!
