### ISSUE TITLE
`no-implicit-reexport` resolves implicit re-exports as `Any`

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#12749]
```py
# foo.py
class Foo:
    ...
```
```py
# bar.py
from foo import Foo
```
```py
# baz.py
from bar import Foo # Module "bar" does not explicitly export attribute "Foo"; implicit reexport disabled  [attr-defined]

reveal_type(Foo) # Revealed type is "Any"
```

mypy should still resolve the import like it does when `no-implicit-reexport` is disabled.

in my case, i'm trying to use a library that imports its own classes using implicit re-exports, which results in pretty much everything being treated as `Any` in my project

**Comment by KotlinIsland** [comment]
As a workaround you could apply an override to the mypy config:
```toml
[[tool.mypy.overrides]]
module = "thepackage.*"
implicit_reexport = True
```

**Comment by Zeckie** [comment]
Just to be clear - are you expecting mypy to give the error (`... does not explicitly export attribute ...`) but then still treat it as being exported?

Also, in your examples the files are all .py files - are there stubs for the external libraries? If so, can you change the stubs to have explicit re-exports?

**Comment by DetachHead** [comment]
> Just to be clear - are you expecting mypy to give the error (`... does not explicitly export attribute ...`) but then still treat it as being exported?

yes

> Also, in your examples the files are all .py files - are there stubs for the external libraries? If so, can you change the stubs to have explicit re-exports?

the library i'm using has types defined in its `.py` files, but i'm pretty sure it would behave the same if they were stubs. i also can't really fix them without making stubs for the entire thing which would be a waste of time because they're already typed

**Comment by whai-kung** [comment]
using `__all__ = ["Foo"]` mypy will know about it.
