### ISSUE TITLE
Generic TypeGuard's Cast Types to Generic Variants, not Their Concrete Type

### ISSUE THREAD

**Issue by ultrabear** [python/mypy#12753]
**Bug Report**

When using a TypeGuard with a generic in it, mypy will make (cast?) whatever is TypeGuarded into the Generic type, not the monomorphized type

**To Reproduce**

run `mypy --strict test.py`:
```py
from typing import TypeVar, TypeGuard, Type

T = TypeVar("T")

class Dummy:
	def foo(self) -> str:
		return "bar"

def custom_isinstance(val: T, typ: Type[T]) -> TypeGuard[T]:
	return isinstance(val, typ)

dummy = Dummy()

if custom_isinstance(dummy, Dummy):
	reveal_type(dummy)
	dummy.foo()

if isinstance(dummy, Dummy):
	reveal_type(dummy)
	dummy.foo()
```
output:
```
test.py:15: note: Revealed type is "T`-1"
test.py:16: error: "T" has no attribute "foo"
test.py:19: note: Revealed type is "test.Dummy"
```

**Expected Behavior**

mypy should be able to monomorphize the generic function and replace the TypeGuard[T] above with TypeGuard[Dummy], narrowing `dummy`'s type to `Dummy` and allowing .foo() to be called

**Actual Behavior**

mypy does not monomorphize the type and casts dummy into a generic T`-1

**Your Environment**

- Mypy version used: `mypy 0.950 (compiled: yes)`
- Mypy command-line flags: `mypy --strict`
- Mypy configuration options from `mypy.ini` (and other config files): None present.
- Python version used: CPython 3.10.4
- Operating system and version: Linux 5.15

**Comment by ultrabear** [comment]
Not relevant to the issue, but pyright correctly infers the type, which is what led me to treat this as an issue and not a bug in my code

**Comment by hauntsaninja** [comment]
Thanks, this is fixed on master

**Comment by ultrabear** [comment]
Ah, I see this was already a closed issue now, I only checked the open errors before reporting, sorry about that!
