### ISSUE TITLE
Wrong type inference in if clause

### ISSUE THREAD

**Issue by Nosterx** [python/mypy#12781]
**To Reproduce**
mypy version 0.950

```
a = 'str'
b = None

def test(a: str | None, b: str | None) -> str:
    parts: list[str] = []
    if a or b:
        parts.append(a or b)
    return ','.join(parts)
```
result in 
```
$ mypy example.py
> example.py:7: error: Argument 1 to "append" of "list" has incompatible type "Optional[str]"; expected "str"
```

With extra variable mypy sees no error
```
a = 'str'
b = None

def test(a: str | None, b: str | None) -> str:
    parts: list[str] = []
    _a = a or b
    if _a:
        parts.append(_a)
    return ','.join(parts)
```

**Your Environment**

- Mypy version used: 0.950
- Mypy command-line flags: no flags used
- Mypy configuration options from `mypy.ini` (and other config files): 
```
[mypy]
ignore_missing_imports = True
follow_imports = skip
warn_unused_ignores = False

[mypy-tests.*]
ignore_errors = True
```
- Python version used: 3.8 and 3.10
- Operating system and version: Ubuntu 20.04

**Comment by AlexWaygood** [comment]
You're asking mypy here to perform type-narrowing for the result of a dynamically evaluated expression. In general, I think that's an unreasonable ask of mypy, which is a _static_ type checker, after all.

For a list of supported type-narrowing operations, see the docs here: https://mypy.readthedocs.io/en/stable/type_narrowing.html. The solution in this case is just to introduce a temporary variable, as you identified.

Here's your two tests with some comments and calls to `reveal_type` added:

```python
def test(a: str | None, b: str | None) -> str:
    parts: list[str] = []
    if a or b:
        # this is a dynamically evaluated expression, not a variable,
        # so mypy can't perform type narrowing
        reveal_type(a or b)  # Revealed type is "Union[builtins.str, None]"
        parts.append(a or b)  # error: Argument 1 to "append" of "list" has incompatible type "Optional[str]"; expected "str"
    return ','.join(parts)

def test2(a: str | None, b: str | None) -> str:
    parts: list[str] = []
    _a = a or b
    reveal_type(_a)  # Revealed type is "Union[builtins.str, None]"
    if _a:  # the boolean check allows mypy to narrow the variable
        reveal_type(_a)  # Revealed type is "builtins.str"
        parts.append(_a)
    return ','.join(parts)
```

Playground link here: https://mypy-play.net/?mypy=latest&python=3.10&gist=1e8984a0bad97b6c314691dc991b68cc

**Comment by AlexWaygood** [comment]
> As a variant on Alex's workaround, a walrus operator can be used.

+1, though note that this is only an option on 3.8+
