### ISSUE TITLE
None unification

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1278]
Currently, `None` types in the code either mean:
- the internal `Void` type: a type that cannot be used
- `None`: an uninhabited type (i.e. a type without any values)
- the internal `NoneTyp` type: the type that contains only the value `None` (this cannot currently be explicitly specified)

After doing proper Optional checking, I propose that we make `None` types always mean `NoneTyp`.  Optional checking will prevent functions that return `None` from being used in places they shouldn't, and allowing users to specify something is the uninhabited type isn't currently useful at all.

**Comment by ddfisher** [comment]
Doing this should fix #299.

**Comment by gvanrossum** [comment]
Marked as needs discussion since it would be good to understand the consequences more precisely.

**Comment by ilevkivskyi** [comment]
There is no more `Void`, and `None` always means `NoneTyp()` so I think this can be closed.
