### ISSUE TITLE
(🐞) Variable incorrectly narrowed to `Any` `special_form` after being separately narrowed in `if`/`else` 

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12783]
Given:
```py
from typing import Iterable

class X(Iterable[str]): ...

a: Iterable[str]
x: X
b: bool
```

```py
if b:
    a = x or []
else:
    a = [""]
reveal_type(a)  # Revealed type is "Any"  TypeOfAny.special_form
```
```py
a = x or [] if b else [""]
reveal_type(a)  # Revealed type is "list[str] | test.X | list[<nothing>]"
```

It should not be `Any`(and why `special_form`?) here, it should be `list[str] | test.X | list[<nothing>]` (ideally `list[str] | test.X]`) .
[playground](https://mypy-play.net/?mypy=latest&python=3.10&flags=allow-redefinition&gist=4c6b5ca3ed9edd4bb9c22181039a4911)

```py
from typing import Iterable, NoReturn

class X(Iterable[str]): ...

a1: X | list[NoReturn]
a2: list[str]

b: bool

c: Iterable[str]
if b:
    c = a1
else:
    c = a2
reveal_type(c)  # Any
```

I think the issue is: joining `<subclass of Iterable[str]> | list[<nothing>]` and `list[str]` becomes `Any`

**Comment by erictraut** [comment]
This bug was apparently fixed in mypy 1.0.0.
