### ISSUE TITLE
Enforce Type Hints

### ISSUE THREAD

**Issue by theonewolf** [python/mypy#1282]
I would love an option on the command line to force the use of type hints so that all code is statically typed.

Is this possible or easy to accomplish with mypy?

**Comment by gvanrossum** [comment]
You can get halfway there with the `--disallow-untyped-calls` flag.

**Comment by theonewolf** [comment]
Thanks @ddfisher and @gvanrossum!

**Comment by zanellia** [comment]
Is there any way to strictly enforce type hints in the current version? I'd like to enforce static typing also for trivial expression like `n = 10` (which should be `n : int = 10`, obviously). This can be rather useful in some contexts, e.g. when trying to generate code in a statically typed language like C for performance reasons (see https://github.com/zanellia/prometeo, for example).

**Comment by JukkaL** [comment]
There is no way to require variables to be annotated if the type can be inferred by mypy, if I understood correctly that this is what you'd like to do.

**Comment by zanellia** [comment]
I see. Thanks for the quick reply @JukkaL!

**Comment by rkr87** [comment]
Would it be possible to force required annotations on variables even if mypy can infer the type?

I understand why it isn't currently there but it would be handy for certain situations. EG one I've just encountered;

async method:
```python
async def __category_setup(self, config_item: list[str]) -> bool:
```
call to the above method I had in my code:
```python
enabled = self.__category_setup(path)
```
The above code is incorrect as the method should be awaited, mypy doesn't raise any errors as it can infer the method type of Coroutine.

However, if I'd typed the enabled variable as bool, my would've raised typing error prompting me to add in the await flag.

```python
enabled: bool = await self.__category_setup(path)
```
