### ISSUE TITLE
How to handle cchardet as an optional dependency

### ISSUE THREAD

**Issue by djmattyg007** [python/mypy#12836]
What's the appropriate way to handle this code?

```python
try:
    import cchardet as chardet
except ImportError:
    import chardet
```

Mypy warns about no type information for `cchardet`. How can I make it use the type information for `chardet`?

It also warns about `chardet` being redefined. How should optional dependencies like this be handled?

**Comment by hauntsaninja** [comment]
If you want to lie to mypy and make it think cchardet is the exact same thing as chardet, try:
```
if TYPE_CHECKING:
    import chardet
else:
    try:
        import cchardet as chardet
    except ImportError:
        import chardet
```
