### ISSUE TITLE
Support named arguments in ParamSpec Concatenate

### ISSUE THREAD

**Issue by intgr** [python/mypy#12863]
**Feature**

[PEP 612 contains this example](https://peps.python.org/pep-0612/#concatenating-keyword-parameters) for using `Concatenate[]` with named arguments (tweaked slightly):

```python
from typing import Callable, ParamSpec, TypeVar, Concatenate, Any

P = ParamSpec("P")
R = TypeVar("R")


def add_n(f: Callable[P, R]) -> Callable[Concatenate[("n", int), P], R]:
    def inner(*args: Any, n: int, **kwargs: Any) -> R:
        return f(*args, **kwargs)

    return inner
```

Right now mypy considers this an error:

```
param_concat.py:7: error: Syntax error in type annotation
param_concat.py:7: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
Found 1 error in 1 file (checked 1 source file)
```

**Comment by AlexWaygood** [comment]
Discussing this example, the PEP says:

> In principle the idea of concatenation as a means to modify a finite number of positional parameters could be expanded to include keyword parameters [...] However, enforcing these constraints would require enough additional implementation work that we judged this extension to be out of scope of this PEP. Fortunately the design of `ParamSpec`s are such that we can return to this idea later if there is sufficient demand.

If you'd like to propose a change to the spec, it would be best to file an issue over at [python/typing](https://github.com/python/typing/issues). This change would require new type-annotation syntax, so it would affect all users of the type system, not just mypy. It might well also require a PEP.

**Comment by intgr** [comment]
Doh! Never mind, I did not notice that this code is from "Rejected Alternatives" section of the PEP. 🤦

**Comment by AlexWaygood** [comment]
> Doh! Never mind, I did not notice that this code is from "Rejected Alternatives" section of the PEP. 🤦

Heh, no worries!
