### ISSUE TITLE
Error in TypeVar bound Protocol

### ISSUE THREAD

**Issue by abersheeran** [python/mypy#12871]
```python
from typing import Protocol, Tuple, Type, TypeVar, Union


class UploadFileInterface(Protocol):
    def write(self, data: bytes) -> None:
        ...

    async def awrite(self, data: bytes) -> None:
        ...

    def seek(self, offset: int) -> None:
        ...

    async def aseek(self, offset: int) -> None:
        ...


class UploadFile:
    def write(self, data: bytes) -> None:
        ...

    async def awrite(self, data: bytes) -> None:
        ...

    def seek(self, offset: int) -> None:
        ...

    async def aseek(self, offset: int) -> None:
        ...


_UploadFile = TypeVar("_UploadFile", bound=UploadFileInterface)


def parse_multipart_form_data(
    file_factory: Type[_UploadFile] = UploadFile,
) -> Tuple[str, Union[str, _UploadFile]]:
    ...
```

Use `mypy .\t.py` got a error:
```
error: Incompatible default for argument "file_factory" (default has type "Type[UploadFile]", argument has type "Type[_UploadFile]")
```

**Your Environment**

- Mypy version used: 0.960
- Mypy command-line flags: no flags
- Mypy configuration options from `mypy.ini` (and other config files): no config
- Python version used: CPython 3.10.4
- Operating system and version: Windows10

**Comment by JSS95** [comment]
Same here. My code passed with Mypy 0.950, but fails with 0.960.

**Comment by JSS95** [comment]
Oh, okay!

**Comment by abersheeran** [comment]
> @JSS95 could you open a separate issue with your code? OP's example reproduces on 0.950 (and older versions) and I think is basically just a duplicate of #3737 On the other hand, sounds like yours is a regression, so it's likely different root cause and is likely much more fixable

I removed the default and it passed the check successfully. Thank u!
