### ISSUE TITLE
(regression: 0.960) Generic[Protocol] fails with dataclass

### ISSUE THREAD

**Issue by JSS95** [python/mypy#12876]
**Bug Report**

The following code uses Generic with Protocol for dataclass. It passes with mypy 0.950, but fails with 0.960.

```python
from dataclasses import dataclass
from typing import Protocol, Dict, TypeVar, Generic


class DataclassProtocol(Protocol):
    __dataclass_fields__: Dict


T = TypeVar("T", bound=DataclassProtocol)


@dataclass
class MyDataclass:
    x: int = 1


class MyGeneric(Generic[T]):
    ...


class MyClass(MyGeneric[MyDataclass]):
    ...

```

Error messge:

```
error: Type argument "MyDataclass" of "MyGeneric" must be a subtype of "DataclassProtocol"
```

**Your Environment**

- Mypy version used: 0.960
- Mypy command-line flags: no flag
- Mypy configuration options from `mypy.ini` (and other config files): no config
- Python version used: 3.10
- Operating system and version: Ubuntu 20.04

**Comment by hauntsaninja** [comment]
Thanks for opening a new issue with repro! This bisects to #12762

**Comment by JSS95** [comment]
@JukkaL

Hello. I am encountering the same issue again.
Until mypy v0.982 the `Generic[Protocol]` worked fine, but from v0.990 to the latest v1.0.1 the test fails with the same error message.

**Comment by hauntsaninja** [comment]
Add ClassVar to the Protocol, I think

**Comment by JSS95** [comment]
@hauntsaninja Thanks! It worked.
