### ISSUE TITLE
Standardize capitalization of the project's name

### ISSUE THREAD

**Issue by gnprice** [python/mypy#1288]
Most of our existing documentation refers to the project as "mypy", in lower case, except capitalizing it at the start of the sentence -- just like an ordinary noun.

I've generally preferred to refer to the project in the manner of a proper name: "Mypy", capitalized. Mostly this is in informal transient contexts like emails and chat messages, but it's also landed in some bits of semi-outward-facing documentation like [our CONTRIBUTING file](https://github.com/python/mypy/blob/master/CONTRIBUTING.md).

I chatted with @JukkaL about this briefly in person, and he was open to the proper-name style but correctly pointed out that we should come to a clearly decided consistent view on the preferred style. Hence this issue. For this issue thread, I think it's enough to come to a decision which we'll then all carry out when we see something that doesn't match -- then in the background, perhaps tracked by a follow-up issue, we can optionally sweep through existing documents for consistency.

My own view on which style is preferable:
* The name of the project and of the overall body of software is a pretty classic proper name, and it makes sense to capitalize it in the same fashion as other proper names. When it's lower-cased, I find it can get swallowed somewhat in a sentence.
* When referring specifically to the command-line program `mypy`, the name is lowercase. Similarly the Python package (as in `python3 -m mypy`), the PyPI package (as in `pip install mypy-lang`), and other contexts where it's a specific identifier that is meaningful to the computer. Generally these are usages that should also be enclosed in backticks or marked in some other way as literal fragments of text-for-a-computer.
* This style is broadly common among software projects:
  * Git is a version-control system and `git` is a command.
  * Emacs is a text editor and `emacs` is a command.
  * Twisted is a Python networking-and-concurrency framework and `twisted` is a Python package.
  * `grep` is a command and the software as a whole is often called "grep" in lower case. This is a nice example because this program is very closely identified with its command-line interface, which pushes things toward just using the lower-case name everywhere. And even here, the [official web page](https://www.gnu.org/software/grep/) actually turns out to say "Grep" more often than "grep" (it isn't totally consistent) when referring to the software as a whole and the project.

**Comment by ddfisher** [comment]
What about "MyPy", like "PyPy" and similar to "PyPI"?

More seriously, if we're considering an actual rename, I think we should put this off until then -- there'll be a large duplication of work otherwise.

**Comment by gnprice** [comment]
I don't foresee doing a lot of work based on any choice of capitalization.
Even if we make a 100% comprehensive sweep to update everything, there's no
change required in
* the domain name
* the repo name on GitHub
* the package name on PyPI
* the filenames in the repo
* the identifiers in the code

or generally in anything else meaningful to a computer, which are the
really painful parts of any rename.

**Comment by gvanrossum** [comment]
This needs to be decided by fiat. (Probably @JukkaL's :-)

**Comment by gvanrossum** [comment]
Since nobody seems to care I am deciding. I like Jukka's original convention, which is to use "mypy" (all lowercase) as the official name of the tool but to capitalize it at the start of a sentence.
