### ISSUE TITLE
unpack dataclasses/types or subsets of them to act as typed dict 

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python/mypy#12906]
**Feature**

often times helper methods take all the fields or subsets of the fields of a type/dataclass

in coordination with #4441 

```python
@dataclass
class MyModel:
   id: uuid
   name: str
   hostname: str
   memory_size: int
```

and i want to declare helpers like

```python
# bad names
Magic = SubsetTypedDict(MyModel, exclude=["id"], total=False)

def wait_for_update(model_or_id: Model|uuid, **kw: Magic) -> Model:
   ...
```

** context **

spin out of #4441, based on [my comment](https://github.com/python/mypy/issues/4441#issuecomment-1110894776) and [the suggestion in](https://github.com/python/mypy/issues/4441#issuecomment-1140563711)

**Comment by AlexWaygood** [comment]
There's already a PR to make this happen: #8583

**Comment by RonnyPfannschmidt** [comment]
@AlexWaygood i strongly disagree

my understanding is that the pr makes mypy pretends that the return value of the as_dict methods is a matching typed dict
it does not in any way give access to that type for other usage in the actual code

**Comment by AlexWaygood** [comment]
I see, apologies. Your proposed new way of constructing a `TypedDict` (a `SubsetTypedDict`), however, looks like it would probably require a PEP. It should probably be discussed over at the https://github.com/python/typing issue tracker rather than here, since it would impact the typing ecosystem as a whole rather than mypy.

**Comment by tony** [comment]
@RonnyPfannschmidt I propose as a next step, writing this out on the [typing-sig list](https://mail.python.org/archives/list/typing-sig@python.org/latest) and seeing what the reception is

I think the conversation it'd generate (whether there's overlap with someone else or a PEP) would be fruitful.  Would you like to write a message there?

**Comment by RonnyPfannschmidt** [comment]
Unfortunately my bandwidth for this is currently zero, and likely to stay like that for the next few months

**Comment by tony** [comment]
@RonnyPfannschmidt No problem.  Is it okay if in the future if someone stumbles upon this they can cite this as an idea on the typing-sig list if they want to?

**Comment by RonnyPfannschmidt** [comment]
Yes

**Comment by kdkavanagh** [comment]
Hi @RonnyPfannschmidt curious if you know if this was ever formally proposed/superseded by something else?  Very interested in this functionality

**Comment by RonnyPfannschmidt** [comment]
Nope still missing as fas as i know
