### ISSUE TITLE
TypedDict not recognised as valid dict when passed as parameter to a function

### ISSUE THREAD

**Issue by berzi** [python/mypy#12934]
**Bug Report**

Mypy reports an error when a `TypedDict` is passed as an argument to a function that is annotated as accepting `dict`s more generally.

**To Reproduce**

```python
class TestDict(TypedDict):
    a: int


def myfunc(test: dict):
    print(test)


myfunc(TestDict(a=2))
```

Note that:
```python
>>> type(TestDict(a=2))
<class 'dict'>
```

**Expected Behavior**

No error.

**Actual Behavior**

```
error: Argument 1 to "myfunc" has incompatible type "TestDict"; expected "Dict[Any, Any]"  [arg-type]
    myfunc(TestDict(a=2))
           ^
```

**Your Environment**

- Mypy version used: 0.960 (compiled: yes)
- Python version used: 3.9.10

**Comment by berzi** [comment]
TypedDict can also be instantiated with `complete=False`, which would effectively make its keys read-write. That would still not Nähe it 100% compatible with dict but it seems worth mentioning.

So does this mean I just have to change my typing of dict to Mapping? That's fair on one hand, but on the other i think this is an easy enough mistake to make. Maybe the message can be made more explicit about why it doesn't type-check.

Also, external libraries more often than not use dict rather than mapping, and i can't control their annotations. If i want to annotate my code to specify more exactly what a dict coming from such a library contains, and TypedDict is not correct, then what should i use?

**Comment by davidism** [comment]
I'm not sure the explanation makes sense. If the function can accept any dict with arbitrary keys, then a `TypedDict` with specific keys seems to satisfy that requirement. This also came up in https://github.com/pallets/flask/pull/4695, `TypedDict` fails both as a return value for `dict` and as the signature of a decorated function.

**Comment by erictraut** [comment]
This isn't a bug in mypy. It's doing the correct thing here. [PEP 589](https://peps.python.org/pep-0589/#type-consistency) is very clear that a TypedDict instance is not type compatible with `dict` and gives the reasons why. A TypedDict instance is compatible with `Mapping[str, Any]`.

**Comment by JelleZijlstra** [comment]
Mypy is following the spec here, though I have some reservations about whether the spec got this right.
