### ISSUE TITLE
Provides `end_col_offset` for mypy ast nodes (pr proposal)

### ISSUE THREAD

**Issue by devmessias** [python/mypy#12940]
I can work and send a PR solving this

**Feature**
The mypy ast nodes sould have the `end_col_offset` attribute if this information is available in the original python AST nodes

**Pitch**

AST nodes from python version 3.8 and up providess the `end_col_offset` attribute. This information can be used to adress some issues in  mypy:

https://github.com/python/mypy/issues/12288
https://github.com/python/mypy/issues/4868
https://github.com/python/mypy/issues/12513

and also in LibCST

https://github.com/Instagram/LibCST/issues/451

The reason is because the `end_col_offset`  allows to associate a section in the source code with the type information.
We can latter on implement something similar to pyre query API using this feature. 
![image](https://user-images.githubusercontent.com/6979335/172017253-a13868e6-05b7-4d6d-912e-3e943688e01c.png)

I working on in a TypeVisitor that  represents a MypyFile node as json string (similar to pyre query result), which maybe in the future can be used by `dmypy`. 
But I need `end_col_offest` to be exposed, currently, I have a local copy of mypy that exposes the `end_col_offset`.  I can work in a PR to integrate this modification in mypy. I don't think that PR will change so much stuff.

**Comment by JelleZijlstra** [comment]
Seems useful! We could also use this in mypy itself for giving an output range for errors.

**Comment by devmessias** [comment]
Hi @JelleZijlstra . Can I start working in a PR to expose that?

**Comment by JelleZijlstra** [comment]
Sure! We'll have to think about how to use this new data in mypy's output and about what to do on mypy 3.6/3.7 where the feature is not yet available.

**Comment by devmessias** [comment]
> Sure! We'll have to think about how to use this new data in mypy's output and about what to do on mypy 3.6/3.7 where the feature is not yet available.

For mypy 3.6/3.7 this could be an optional int as well the `end_line` attr 
https://github.com/python/mypy/commit/fc79289981c635822d7a64fc609e690c351726e4 (first commit) I need to apply the same modifications in the *pyi* files.

Regarding the use of this new data, I've made a comment on #12288. I can work in a separate PR for that because I think that changing the report system needs a lot of discussion and also will create much more changes in the codebase than just exposing the `end_col_offset`

What I doing in my project ([pyastrx](https://github.com/pyastrx/pyastrx)) using the `end_col_offset` is creating a report with ^ and >  chars like this 

![image](https://user-images.githubusercontent.com/6979335/172163651-b4518ded-2a62-46df-a148-b74e512edbea.png)

The other thing that I have now using the `end_col_offset` is a `mypy-query` system that returns to me a json with the types similar to `pyre query`. Although this is just in my local repo using my modified mypy

![image](https://user-images.githubusercontent.com/6979335/172165092-04ee6bec-0dd3-4919-aa52-1f1411bca4f8.png)
