### ISSUE TITLE
Environment markers for type: ignore comments

### ISSUE THREAD

**Issue by tsibley** [python/mypy#12946]
**Feature**

Extend `# type: ignore[code]` comments to allow further tagging/scoping/targeting them to a particular type checker (e.g. mypy vs. pyright). Perhaps something like:

```
# type: ignore[attr-defined]; type_checker=mypy
```

aping the [PEP 508 environment marker syntax](https://peps.python.org/pep-0508/#environment-markers), but any syntax would be ok.

This will require co-operation with the rest of the type checking tools, but I'm hoping mypy can lead here.

**Pitch**

I use both mypy and pyright to check types as their checks don't completely overlap and so using both catches a bit more than just using one. When an ignore is necessary for one but not the other, I'd like to be able to more selectively ignore just for that type checker so that the other continues to check the line.

**Comment by tsibley** [comment]
@AlexWaygood Ah, thank you! I'd missed that issue when I searched before filing this one and hadn't noticed the tag I could have used to help find it.

**Comment by AlexWaygood** [comment]
@tsibley no worries! There are a lot of mypy issues to wade through :)
