### ISSUE TITLE
dataclass with Generic parameter does not honor default value

### ISSUE THREAD

**Issue by aha79** [python/mypy#12962]
**Bug Report**

A dataclass with generic field does not infer the generics type when a default is provided.

**To Reproduce**

```
@dataclass
class Data(Generic[T]):
    field: T = 1
# -> "Incompatible types in assignment (expression has type "int", variable has type "T")"  (INCORRECT, should be accepted w/o error)

reveal_type( Data(17.5).field )
#  -> Revealed type is "builtins.float*"    (CORRECT)
reveal_type( Data().field )
#  -> Revealed type is "<nothing>"    (FAILED, should be int)
```

**Expected Behavior**

The default value supplied in the dataclass should be honored. Semantically the construct is not an assignment, but a default value
in the  `__init__`  function:

Under the hood the (autogenerated) dataclass constructor looks like this 
```
def __init__(self, field = 1):
     self.field = field 
```
So when `field` is not provided during construction of `Data` instance the field is passed as an `int`, so the generic type `T` should be inferred as `int` (if field is omitted in constructor). In the exactly same way as T is inferred as `float` when the field is given explicitly in the constructor (e.g. `Data(17.5).field`)

Concluding, what should happen:
   - `Data()` -> infer T as int (from the default in dataclass) (does not work)
   - `Data(val)` -> infer T as same type as `val`  (this works)

**Actual Behavior**

Default argument is ignored

**Your Environment**

- Mypy version used:  0.960
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9.7
- Operating system and version: Windows 10

**Comment by aha79** [comment]
#11923 seems to be a related issue

**Comment by erictraut** [comment]
I would not expect this to work. A dataclass decorator effectively adds a synthesized `__init__` method to the class. For your sample, that method would look like the following:

```python
def __init__(self, field: T = 1) -> None: ...
```

If you were to explicitly create a generic class with this `__init__` method, mypy would similarly reject it because concrete default argument values are not supported for generic parameters.

**Comment by aha79** [comment]
I see. So the real issue is that concrete default arguments are now allowed for generic parameters. However, after looking around on this site I found that this feature seems to meet some interest and has been requested several times so far (https://github.com/python/mypy/issues/4236, https://github.com/python/mypy/issues/3737, https://github.com/python/mypy/issues/10854, https://github.com/python/mypy/issues/10504 and perhaps more)

The issue is that the proposed workaround or solution with @overload (as in https://github.com/python/mypy/issues/4236#issuecomment-521628880) does not work for dataclasses (or at least I cannot see how this would work in my case). With dataclasses the `__init__` is autogenerated and manually overwriting `__init__`would undermine the purpose of using dataclasses in the first place.

**Comment by AlexWaygood** [comment]
This isn't supported by the current type system, so I'm closing for now; but it sounds like you may be interested in https://github.com/python/peps/pull/2717
