### ISSUE TITLE
Incorrect assuming class property is a method

### ISSUE THREAD

**Issue by Behoston** [python/mypy#12975]
**Bug Report**

**To Reproduce**

```
class Example:
    @property
    @classmethod
    def example(cls) -> typing.List[str]:
        return ['str', 'ing', 's']
variable: typing.List[str] = Example.example
```
**Expected Behavior**
no mypy errors

**Actual Behavior**
error:
`error: List or tuple expected as variable arguments`

**Your Environment**

- Mypy version used: `0.941`
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: `3.9`
- Operating system and version: `Linux Mint IDK`

**Comment by AlexWaygood** [comment]
`classmethod` properties are not yet supported by mypy (see #11619), and are deprecated at runtime on 3.11+ (https://github.com/python/cpython/pull/92379)
