### ISSUE TITLE
Tuple & TypeVarTuple Default Arguments

### ISSUE THREAD

**Issue by adam-grant-hendry** [python/mypy#12981]
**Feature**

It would be nice if `Tuple` and `TypeVarTuple` supported default arguments (particularly for use with `Unpack`).

**Pitch**

As a motivating example, I work with several 3rd-party C++ libraries with python bindings (e.g. `PySide6`). These bindings often have methods that do not support keyword arguments (C++ doesn't support keyword arguments natively). Sometimes, they have wrappers that forward `*args` to the particular binding. e.g.

```python
    @staticmethod
    def mouseMove(*args):
        qtpy.QtTest.QTest.mouseMove(*args)
```

has C++ signatures

```cpp
void mouseMove(QWindow *window, QPoint pos = QPoint(), int delay = -1)
void mouseMove(QWidget *widget, QPoint pos = QPoint(), int delay = -1)
```

that has default positional arguments for `pos` and `delay`.

Currently, AFAIK, there is no way to specify default arguments to either `Tuple` or `TypeVarTuple`. Without specifying default values, `@overloads` would be required (which one may argue is a sensible alternative, but is tedious when having to be performed for multiple methods in a large codebase):

```bash
Argument missing for parameter "args[n]"
```

**Syntax Idea**

I'm not sure how it would be implemented, but intuitively I am trying to achieve something like

```python
MouseMoveArgs = tuple[
    qt_api.QtWidgets.QWidget | qt_api.QtGui.QWindow,
    qt_api.QtCore.QPoint = qt_api.QtCore.QPoint(),
    int = -1,  # c int
]
```

that I can then unpack

```python
class QtBot:
    @staticmethod
    def mouseMove(*args: Unpack[MouseMoveArgs]) -> None: ...
```

**Comment by AlexWaygood** [comment]
I'm not sure I fully understand your proposal here, but it sounds like you're proposing a change to the spec for `tuple`/`TypeVarTuple`. Discussions like that should happen over at https://github.com/python/typing rather than the mypy issue tracker, since they affect all users of Python typing, not just mypy users.
