### ISSUE TITLE
module google.cloud has no attribute firestore - Incorrect

### ISSUE THREAD

**Issue by adamcunnington-mlg** [python/mypy#12985]
**Bug Report**

`module google.cloud has no attribute firestore`
The bug is that this statement is not true.

There have been a few related stackoverflow issues (e.g. [1](https://stackoverflow.com/questions/63339732/module-google-cloud-has-no-attribute-storage), [2](https://stackoverflow.com/questions/55212535/issue-with-google-cloud-storage-module-has-no-attribute-client/55212631#55212631)) relating to incorrect "module x as no attribute y" specifically relating to google.cloud.
Some issues were sorted by recreating the virtual env.
Other issues on this repo were historically traced back to using incremental mode but solution seemed incomplete (e.g. [1](https://github.com/python/mypy/issues/10360), [2](https://github.com/python/mypy/issues/12232)).
We disabled mypy cache (e.g. incremental mode) which dealt with a chunk of the problem

**To Reproduce**
Hard to know exactly how to reproduce because the problem with this issue is it seems random and indeterministic - even after disabling incremental mode.

All I can tell you is in our code we do:
```python
from google.cloud import bigquery, firestore
```
Both `google-cloud-bigquery` and `google-cloud-firestore` are in setup.cfg/requirements.txt and installed in the virtual environment which mypy is being activated from.

We have no issues (currently) with the bigquery import but we do with firestore. They are completely identical for all intents and purposes here.

**Expected Behaviour**

No complaint about missing attribute.

**Actual Behaviour**

Incorrect complaint about missing attribute.

**Your Environment**

mypy 0.950 (compiled: yes)
python 3.9.x

Please can we get to the bottom of this once and for all?

**Comment by hauntsaninja** [comment]
Are you using `namespace_packages=True`? If not, please try with that. This will be made the default at some point soon.

**Comment by adamcunnington-mlg** [comment]
Will try and see if it fixes

**Comment by adamcunnington-mlg** [comment]
It has no effect unfortunately - which is unsurprising anyway because then we'd have to understand why `bigquery` wasn't causing an issue here but `firestore` was.

**Comment by shevron** [comment]
I'm seeing a similar behavior - with:
```python
from google.cloud import bigquery, storage
```
I get:
```
$ mypy --no-incremental mynamespace/
mynamespace/package/module.py:19: error: Module "google.cloud" has no attribute "storage"
```

This is with mypy 0.961; 
My code is using namespace packages (i.e. `mynamespace` in the example above is a namespace package), but so far I haven't had any issues. 

I was able to work around it for now by doing:
```python
from google.cloud import bigquery
from google.cloud.storage import Client as StorageClient
```
which of course may not work for everyone, but for me it's good enough. I am not sure why it would work, but it does.
