### ISSUE TITLE
Support Pandas IO operation Return Types

### ISSUE THREAD

**Issue by ShivnarenSrinivasan** [python/mypy#12999]
**Bug Report**

Incorrect type inference for annotated pandas functions
==================

Example Code
----------------

```python
import sqlite3
import pandas as pd

def load_excel() -> pd.DataFrame:
    df = pd.read_excel('example.xlsx')
    return df


def load_sql() -> pd.DataFrame:
    con = sqlite3.Connection('a.db')
    df = pd.read_sql('', con)
    return df

```

**Expected Behavior**

Return type should be `DataFrame` (*not `Any`*), as that is the source code annotation for [`read_excel`](https://github.com/pandas-dev/pandas/blob/v1.4.2/pandas/io/excel/_base.py#L422-L495) and [`read_sql`](https://github.com/pandas-dev/pandas/blob/v1.4.2/pandas/io/sql.py#L438-L599).

**Actual Behavior**

Terminal output: 
![image](https://user-images.githubusercontent.com/71850263/174666655-a0853d4f-ef18-4cc3-bd48-a994feca4650.png)

**Your Environment**

- Mypy version used: 0.961
- Mypy command-line flags: None
- Mypy configuration options: file attached
- Python version used: 3.10
- Operating system and version: Windows 10 21H2

**Comment by JelleZijlstra** [comment]
Do you have stubs installed for pandas? As I recall, pandas is not a py.typed library (see PEP-561), so mypy will not use its inline types.

**Comment by ShivnarenSrinivasan** [comment]
Thanks, @JelleZijlstra—I do have [pandas-stubs](https://github.com/pandas-dev/pandas-stubs) installed:

![image](https://user-images.githubusercontent.com/71850263/174714693-f51977e8-7229-484f-8022-37253f0372da.png)

However, I see that the stubs are installed *within* the package itself--i.e, the `.pyi` files are added alongside the source files.
Not like the usual `types-xxx` install, where the packages are installed in a separate directory.

![image](https://user-images.githubusercontent.com/71850263/174715020-3293992a-0a92-402f-b3ca-89b6381a9d37.png)


![image](https://user-images.githubusercontent.com/71850263/174715273-ba7e8edf-23be-451a-af4f-7138fa0701d5.png)


Anything different I need to do to get it to work?

**Comment by hauntsaninja** [comment]
No, it's just a shortcoming of the version of the stubs you're using. If you look at:
https://github.com/VirtusLab/pandas-stubs/blob/5b38cae915aa2aedc39df511e58545b0e9c9715d/third_party/3/pandas/io/excel/_base.pyi#L13
you'll see that it's genuinely returning Any.

It looks like there's a better version of the stubs available at https://github.com/pandas-dev/pandas-stubs (and is meant to replace the existing ones), but that hasn't been released yet.

**Comment by ShivnarenSrinivasan** [comment]
> No, it's just a shortcoming of the version of the stubs you're using. If you look at: https://github.com/VirtusLab/pandas-stubs/blob/5b38cae915aa2aedc39df511e58545b0e9c9715d/third_party/3/pandas/io/excel/_base.pyi#L13 you'll see that it's genuinely returning Any.
> 
> It looks like there's a better version of the stubs available at https://github.com/pandas-dev/pandas-stubs (and is meant to replace the existing ones), but that hasn't been released yet.

Thanks--I tried, to clone the repos and pip install it that way (i.e v1.42), but same result, unfortunately.

Guess I'll wait for the official release.

**Comment by hauntsaninja** [comment]
Here, I opened https://github.com/pandas-dev/pandas-stubs/pull/33 to fix read_excel. Similar changes need to be made for read_sql to work. I guess those stubs aren't quite ready for prime time :-)
