### ISSUE TITLE
Support combinations of multiple types (not unions)

### ISSUE THREAD

**Issue by mohkale** [python/mypy#13009]
**Feature**

Support the ability to create a type that can be treated as a combination of one or more other types. Meaning if type A has a method `foo` and type b has a method `bar` then `var: Combination[A, B]` can support both `var.a()` and `var.b()`.

**Pitch**

I have a service which make requests and returns responses. Responses are always dictionaries unpacked from JSON. For the request `{"fooRequest": {}}` I get back something like `{"fooResponse": {}}`. 

Note: the schema of these requests and responses are generated from some configuration file (XML) so I can't have typed requests and responses (yet). 

```python
Response = Dict[str, Any]

def make_request(request) -> Response:
  ...

response = make_request({"fooRequest": {}})["fooResponse"]  # Has type Any
```

Today I discovered a bug where instead of accessing a value from this dictionary I was instead trying to access it as a field. For example:

```python
response.errorCode  # Should be response["errorCode"]
```

MyPy could not detect this because the type of `response` is Any.

What should the type of Response be to detect any clear violations of type safety here? 

+ I could create a JSON union type (something like `JSON = typing.Union[Dict[str, JSON], List[JSON], str, int, float]`, but I've got a lot of existing code and don't want to add tens of thousands of type casts and checks everywhere. That's partly why the type is currently Any.
+ I can't have typed requests and response. Worst case I could probably write a generator to produce these but having an explicit compile step for that prior to any python code isn't ideal.

I know that a type is one of a series of other types, and I want to be able to treat it as all those other types. I need a narrower Any. One that can tell me that this variable definitely doesn't have a `errorCode` field, but may have dictionary access or numeric addition or string concatenation.

**Thought Experiments**

In practice I think most situtations would have Combinations applied recursively. 

So for example how do we deal with conflicting type declarations across combined types. 

```python
class A:
  def foo(self) -> str:
    pass

class B:
  def foo(self) -> int:
    pass

a: Combination[A, B] = ...
a.foo()  # Combination[int, str]
```

What if there are different parameter signatures for the same method? 

Then we should treat them as overloads. 

What If they have the same parameter signature type and different return types 

The result is an overload with a Combination return type.

**Disclaimer**

I realize this is kind of a ridiculous feature request. Even if this is likely rejected I'm hoping the discussion helps me find a good workaround.

**Comment by JelleZijlstra** [comment]
You're looking for an intersection type. That's being discussed in python/typing#213; going to close this as a duplicate.
