### ISSUE TITLE
dump diagnostic info to json file

### ISSUE THREAD

**Issue by 2bndy5** [python/mypy#13017]
**Feature**

Add an optional generated report of all diagnostic information in json form. I'm thinking of something similar to the coverage report options, but tailored to any warnings/errors/notes produced by mypy (according to it's config).

**Pitch**

I'd like to write a problem matcher for my CI workflow(s). I could just use regex to parse stdout and go from there, but different projects have different output configurations. If I could get a comprehensive json (as verbose as possible) of all the errors/warnings/notes in json form, then I can adequately match the diagnostic info to exact places in the source code.

I imagine a single warning would look like:
```json
[
  {
    "severity": "error",
    "line": 92,
    "column": 29,
    "path": "clang_autodoc/clang_parse.py",
    "symbol": "arg-type",
    "message": "Argument 1 to 'serialize_src_loc' of 'ClangParse' has incompatible type 'int'; expected 'SourceLocation'"
  }
]
```
FWIW, pylint has a similar CLI option:
```
pylint --output=json:somefile.json srcs/*.py
```

**Comment by AlexWaygood** [comment]
Duplicate of #10816

**Comment by AlexWaygood** [comment]
> Duplicate of #10816

(note that this already has a PR attached to it :)

**Comment by 2bndy5** [comment]
Sorry it was hard to search through the 2K issues. Thanks for the quick response!
