### ISSUE TITLE
Mypy logo isn't displayed in the docs

### ISSUE THREAD

**Issue by rahulporuri** [python/mypy#13022]
**Documentation**

The Mypy icon on the top-left corner of https://mypy.readthedocs.io/en/stable/ isn't displayed on Chrome or Edge. I tested with the latest versions of both Chrome and Edge. However, the icon is visible on Firefox.

|firefox (v 101.0.1)|chrome (v 103.0.5060.53)/ edge (v 102.0.1245.44)|
|----|----|
|![image](https://user-images.githubusercontent.com/1926457/175798123-75090f91-6ac1-49b9-8e1b-c5efcda56f5e.png)|![image](https://user-images.githubusercontent.com/1926457/175798135-0de05c74-e4c8-471a-8935-4a8900f986f4.png)|

Note that the logo is accessed from the static files on the mypy website at http://mypy-lang.org/static/mypy_light.svg . Ref: https://github.com/python/mypy/blob/89bdcfb8c658340dae70312c5b76b703838d8123/docs/source/conf.py#L123-L125

The reason why the icon loads on Firefox but not on Edge/Chrome seems to be that Edge/Chrome force the use of `https` whereas Firefox happily uses the `http` link for the icon and the `https` link returns a 404.

Console output on Firefox

```
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: http://mypy-lang.org/static/mypy_light.svg
Loading mixed (insecure) display content “http://mypy-lang.org/static/mypy_light.svg” on a secure page
```

Console output on Edge

```
GET https://mypy-lang.org/static/mypy_light.svg net::ERR_CONNECTION_REFUSED
```

Request information on Edge

```
Request URL: https://mypy-lang.org/static/mypy_light.svg
Referrer Policy: no-referrer-when-downgrade
```

This feels like a Sphinx (documentation) issue as well and I'll follow up with the Sphinx project. For now, I wanted to report the missing/broken icon here. Is there any particular reason why a URL is provided instead of a simpler local file?

**Comment by hauntsaninja** [comment]
Thanks for reporting! I think this was fixed in https://github.com/python/mypy/pull/12939 (but won't yet have made it's way onto stable)

**Comment by rahulporuri** [comment]
thanks @hauntsaninja . I looked at the issues, not at the PRs.
