### ISSUE TITLE
Double `@overload` is not considered an error

### ISSUE THREAD

**Issue by denballakh** [python/mypy#13034]
**Bug Report**
```py
from typing import overload
@overload
@overload
def f(x: int) -> int:
    ...
@overload
@overload
def f(x: str) -> str:
    ...
def f(x: int | str) -> int | str:
    return x
reveal_type(f)
```

**Expected Behavior**
some error such as "Double @overload not allowed"

**Actual Behavior**
no errors

**Your Environment**
- `mypy 0.961 (compiled: no)`
- no command-line flags, no config file
- `CPython 3.10.4`
- Windows 10

**Comment by denballakh** [comment]
Also no errors:
```py
from typing import Protocol, final, runtime_checkable
@final
@final
class X:
    pass
@runtime_checkable
@runtime_checkable
class P(Protocol):
    pass

```

**Comment by AlexWaygood** [comment]
Why should any of these be considered an error? What's unsafe about any of these? Why would anybody use any of these constructs in real-world code?

**Comment by denballakh** [comment]
I find this code confusing. Wouldn't it be better to warn the user about this?

**Comment by AlexWaygood** [comment]
Yes, it's not the job of a type checker to check for code that's confusing or inelegant. It's the job of a type checker to check for code that is provably incorrect or unsafe in some way.

Also, adding any new check to a program such as a type checker or a linter adds complexity to that program, making it harder to maintain. You have to weigh the benefits of the proposed new check against those costs, and in this case, I don't think it would be worth it.

So, thanks for the suggestion, but I think we'll decline this idea :)
