### ISSUE TITLE
Incorrect type inference while combining @property / @staticmethod / @abstractmethod

### ISSUE THREAD

**Issue by Delgan** [python/mypy#13035]
**Bug Report**

Hi.

I'm combining `@property` with `@staticmethod` and `@abstractmethod` and it does not seem to infer the type correctly. The runtime value is a `str` as expected but `mypy` types it as a function. It seems `pyright` / `pylance` handles it properly.

Note that if the `@staticmethod` is replaced by `@classmethod`, then the type is correctly inferred.

**To Reproduce**

```python
from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

class Foo(ABC):
    
    @property
    @staticmethod
    @abstractmethod
    def name() -> str:
        pass

class Bar(Foo):
    name = "bar"

class Baz(Foo):
    name = "baz"

instances = [Bar(), Baz()]

print(instances[0].name)

if TYPE_CHECKING:
    reveal_type(instances[0].name)
```

**Expected Behavior**

The output of `reveal_type()` should be:

```
main.py:23: note: Revealed type is "builtins.str"
```

**Actual Behavior**

The output of `reveal_type()` is:

```
main.py:23: note: Revealed type is "def () -> builtins.str"
```

**Your Environment**

- Mypy version used: 0.961
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.10
- Operating system and version: N/A

See Mypy Playground: https://mypy-play.net/?mypy=0.961&python=3.10&gist=5769925c4ace0e3f66337533fb42e27a

**Comment by erictraut** [comment]
The code above contains a bug. It attempts to apply `@property` to a static method, which isn't allowed. Later versions of mypy added a check for this error. If you fix the code (change the static method to an instance method in the ABC), mypy then correctly evaluates the type. 

I recommend closing this issue.
