### ISSUE TITLE
Inconsistent error "Cannot instantiate abstract class" depends on size of iterable

### ISSUE THREAD

**Issue by awaelchli** [python/mypy#13044]
**Bug Report**

The mypy check over a loop with three or more classes that have abstract methods fails.
Apologies in advance for the terrible title but I couldn't find a good short way to express the issue here.

**To Reproduce**

The following fails:

```py
from abc import ABC, abstractmethod


class Base(ABC):

    @staticmethod
    @abstractmethod
    def detect() -> bool:
        pass


class A(Base):
    @staticmethod
    def detect() -> bool:
        return True


class AA(Base):
    @staticmethod
    def detect() -> bool:
        return True


class AAA(Base):
    @staticmethod
    def detect() -> bool:
        return True


# With three of them mypy FAILS.
# ------------------------------
for cls in (AAA, AA, A):
    if cls.detect():
        cls()

```

The error:
```
error: Cannot instantiate abstract class "Base" with abstract attribute "detect"  [abstract]
```

However, this ONLY appears with three of these subclasses in a tuple. Any combination of classes that have three or less passes the mypy test:

```py
# Any of the below combinations of iterables work however

for cls in (AA, A):
    if cls.detect():
        cls()


for cls in (AAA, AA):
    if cls.detect():
        cls()


for cls in (AAA, A):
    if cls.detect():
        cls()
```

**Expected Behavior**

There should either be consistently no error or an error in all cases regardless of over how many classes we iterate. 

**Your Environment**

- Mypy version used: mypy 0.961 (compiled: yes)
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10
- Operating system and version: MacOS

**Comment by awaelchli** [comment]
I'm not sure exactly, but perhaps this is a duplicate of #3115?

**Comment by AlexWaygood** [comment]
> I'm not sure exactly, but perhaps this is a duplicate of #3115?

Correct

**Comment by AlexWaygood** [comment]
Also I can't reproduce: I get the same (bad) error whether it's a two-element tuple or a three-element tuple: https://mypy-play.net/?gist=fa096551bb49746165501ebd5016670b
