### ISSUE TITLE
No error in function definition that returns unbound `T`

### ISSUE THREAD

**Issue by denballakh** [python/mypy#13061]
```py
from typing import TypeVar

T = TypeVar('T')

def f() -> T: # no error
    ...

if f():
    print() # Statement is unreachable
else:
    print() # Statement is unreachable

```

**Actual Behavior**
No error in `f` definition. Two `unreachable` errors inside `if f(): ... else: ...`

**Expected Behavior**
Error in `f` definition. For example:
```
Type variable "T" is unbound
(Hint: Use "T" in function arguments to bind "T" to return type)
```
No errors inside `if f(): ... else: ...`

**My Environment**
- `mypy 0.961 (compiled: no)`
- no command-line flags, no config file
- `CPython 3.10.4`
- Windows 10

**Comment by JukkaL** [comment]
Hints:
* We'd only reject a plain type variable as a return type, but not things like `list[T]` where the type variable is a component of some other type. Returning `list[T]`, for example, could be reasonable.
* If a return type is an instance of `TypeVarType` but the return type is not present as a component in function argument types, generate an error.
* You can use a `TypeTraverserVisitor` to traverse the argument types, and override `visit_type_var` to collect all the references to type variables within a type. See `CollectAllInstancesQuery` for an example of doing a similar thing.

**Comment by odesenfans** [comment]
Could you elaborate on why and when types like `list[T]` could be acceptable if `T`is not bound to any type?

**Comment by JukkaL** [comment]
@odesenfans The only example that I can think of is creating an empty container. For example, something like this:
```py
def make_bucket() -> Bucket[T]: ...

b: Bucket[int]  = make_bucket()  # similar to x: list[int] = list()
b.add(1)
```

Usually you would just call the type object, but having a factory function seems like a plausible use case (e.g. we could do some extra things like logging or collect statistics in the factory function).

**Comment by ajjayymahato** [comment]
Hi there! I would like to work on this issue. Can you please assign this issue to me!

**Comment by ilevkivskyi** [comment]
I think this was already fixed by https://github.com/python/mypy/pull/13166, but accidentally was not closed.
