### ISSUE TITLE
Some level of dynamic inference for enums

### ISSUE THREAD

**Issue by tobast** [python/mypy#13082]
**Feature**

Although I can see in eg. #4865 that enum typing doesn't go well with dynamic declaration through the functional API, and the typing error message is quite clear
```
Enum() expects a string, tuple, list or dict literal as the second argument
```

it would be nice — but most probably hard — to have support for some extent (to be defined wrt. what is feasible/desirable) of dynamic inference of enumerations.

**Pitch**

While trying to write a low-effort pythonic wrapper around a very C-like Python binding (the [Capstone disassembler](https://github.com/capstone-engine/capstone/tree/master/bindings/python/capstone), see eg. [this file](https://github.com/capstone-engine/capstone/blob/master/bindings/python/capstone/x86_const.py)), I wished to transform a few cherry-picked sets of those constants into enumerations. This could certainly be done by autogenerating Python files containing proper `Enum`s, but it seems more elegant to do this dynamically to avoid out-of-sync interfaces.

A simplified version of the code boils down to
```python3
CsRegister = IntEnum(
    "CsRegister",
    {
        getattr(capstone.x86, key): key
        for key in filter(lambda x: x.startswith("X86_REG_"), dir(capstone.x86))
    },
)
```

This definition of an enumeration is certainly very dynamic. It however looks like a legit pattern one might wish to have when interacting with code they don't have control over.

I assume that it is not desired to run application code inside the type checker — which would, apart from execution time, yield determinism and purity questions. Would there be, however, some possible middle-ground to make such an example possible? Maybe code tagged with a specific decorator could be run at typechecking time?

**Comment by JukkaL** [comment]
Running code during type checking time is not something we are planning to support, unfortunately.
