### ISSUE TITLE
Problems type-checking reduce() in Python 2

### ISSUE THREAD

**Issue by mulkieran** [python/mypy#1308]
Version: mypy 0.3.1

Program:

```
from functools import reduce

from typing import List

def func(x, y):
    # type: (int, int) -> int
    return x + y

def junk(li_of_int):
    # type: (List[int]) -> None

    res = reduce(func, li_of_int, 0)
    print(res)

if __name__ == "__main__":
    junk([1, 2])
```

The type of ```func()``` is obviously correct.

The type of ```junk()``` is asserted to be List[int].

The reported errors are:

```
[mulhern@dhcp-25-209 justbases]$ python3 -m mypy junk.py
junk.py: note: In function "junk":
junk.py:12: error: Argument 1 to "reduce" has incompatible type Callable[[int, int], int]; expected Callable[[int], int]
junk.py:12: error: Argument 2 to "reduce" has incompatible type List[int]; expected Iterator[int]
```
I think they are both wrong. The first argument to reduce() _must_ be a function that takes two arguments. reduce() is perfectly compatible with List, it should not be required to make it an Iterable. I get the idea that List and Iterable need a common supertype, since probably neither is a subtype of the other.

**Comment by gvanrossum** [comment]
Can you report this for the typeshed project instead? It looks like
the 2.7 stub for functools has the wrong signature for reduce(). You
could even submit a fix (glean the correct definition from the Python
3 stub).

**Comment by mulkieran** [comment]
Done: https://github.com/python/typeshed/pull/127
