### ISSUE TITLE
Weird numpy behavior with complex multiplication

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#13121]
```python
from typing import Any
import numpy as np
import numpy.typing as npt
RealArray = npt.NDArray[np.floating[Any]]
x: RealArray = np.zeros(10)
y: RealArray = np.zeros(10)
reveal_type(x)
reveal_type(y)
w = x + 1j * y
reveal_type(w)
reveal_type(w @ w)
```
```
a.py:7: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.floating[Any]]]"
a.py:8: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.floating[Any]]]"
a.py:10: note: Revealed type is "numpy.ndarray[Any, Any]"
a.py:11: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.bool_]]"
```

**Comment by ethanhs** [comment]
Are you using the numpy mypy plugin?

**Comment by NeilGirdhar** [comment]
@ethanhs No, should I be?

**Comment by ethanhs** [comment]
I don't know if it will fix this particular issue, but it might help overall. I have had a good experience using it with my own code.

**Comment by NeilGirdhar** [comment]
@ethanhs I looked at it briefly and it seems to be chiefly concerned with platform-dependent typing.  Anyway, pyright doesn't have a problem inferring types, so I feel like mypy's error is due to bugs.

**Comment by JelleZijlstra** [comment]
It would help if you could link the relevant stubs, and maybe extract them to a repro case that doesn't depend on numpy.

**Comment by NeilGirdhar** [comment]
Looks like it's 
```
a.py:11: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[Any]]"
```
now, which is good enough.
