### ISSUE TITLE
Errors are shown in third-party packages with inline annotations when using daemon

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#13140]
To reproduce:
* Start daemon on a code that uses e.g. `pytest` before installing `pytest`
* Install `pytest` (it has inline annotations)
* Run `dmypy run` again and get a lot of error messages.

**Comment by ilevkivskyi** [comment]
Note that restarting the daemon fixes the issue.

**Comment by JukkaL** [comment]
This also happens with `types-*` packages. For example:
* Start daemon on a file that imports `requests` using `--disallow-untyped-defs`
* Install `types-requests`
* Run `dmypy run` and get lots of errors 

Again restarting the daemon helps.
