### ISSUE TITLE
Cannot access "__init__" directly

### ISSUE THREAD

**Issue by gsakkis** [python/mypy#13173]
Calling `__init__` explicitly is a valid (albeit uncommon) pattern, for example after calling explicitly `__new__`; however mypy considers it an error:

```py
from __future__ import annotations


class Foo:
    def __init__(self, a: int):
        self.a = a


class Bar(Foo):
    def __new__(cls, a: int) -> Bar:
        self = super().__new__(cls)
        # ....
        self.__init__(a)
        # ....
        return self


if __name__ == '__main__':
    print(Bar(1))
```

**Comment by hauntsaninja** [comment]
Interestingly, this check goes back to 2013 (and beyond, in Alore). See the reasoning here: https://github.com/python/mypy/issues/89
The error message isn't great, so I would accept a PR improving it

**Comment by gsakkis** [comment]
I'm not sure I'm following the reasoning in the mentioned ticket but from a quick [code search](https://sourcegraph.com/search?q=context:global+%5Cw%5C.__init__%5C%28%5B%5Es%5Cs%5D%5Ba-z%5D+lang:python+&patternType=regexp) there seem to be quite a few cases of calling `__init__` directly, a lot of them to initialize an instance created with `__new__`.

> As an exception, it is valid to use super() to access `__init__` (we know the exact method to call).

Even this exception is limited:
```py
    def __init__(self, a: int):
        # this typechecks
        super().__init__(a)

        # this doesn't
        s = super()
        s.__init__(a)
```

**Comment by hauntsaninja** [comment]
mypy does not complain about e.g. `concrete_type.__init__(...)` which is what many of your code search examples are.

Here's a more explicit example of the unsoundness that mypy is avoiding:
```
class A:
    def __init__(self, x: int): ...
class AA(A):
    def __init__(self, x: int, y: str): ...

def foo(a: A):
    a.__init__(5)

a: A = AA()
foo(a)  # boom
```

**Comment by hauntsaninja** [comment]
For example, mypy will allow:
```diff
- self.__init__(a)
+ Bar.__init__(self, a)
```

**Comment by gsakkis** [comment]
Thanks for the example, this makes sense. Still I would argue that reporting an error for ` s = super(); s.__init__()` or `s = super().__new__(cls); s.__init__()` is a false positive according to the reasoning for the exception in #89 ("we know the exact method to call").

**Comment by gsakkis** [comment]
Another case this comes up: [calling `__init__` from `__setstate__`](https://stackoverflow.com/questions/23461479/is-it-ok-to-call-init-from-setstate).

I'd argue for reopening this issue; the (main) problem was not the error message.

**Comment by JeanOlivier** [comment]
I found this issue by googling "Cannot access "__init__" directly" after implementing a `__setstate__` method and being confused by the error message.

I think it should at least not generate this error message when called from a `__setstate__`  method.
It's also not hard to imagine a valid case for calling `__init__` after initialization even outside of `__setstate__`, let's say for a "reset object" feature.


Doing something like:
``` python
class Class():

    def __init__(self) -> None:
        self.__init_for_real()

    def __init_for_real(self) -> None:
        ...

    def __setstate__(self, state: dict) -> None:
        self.__init_for_real()
```
might circumvent the error message in mypy, but it's not elegant.
