### ISSUE TITLE
mypy doesn't understand set operations on optional

### ISSUE THREAD

**Issue by Palpatineli** [python/mypy#13192]
I have tried to search for similar issues but failed because I can't find the keywords to limit the open issues to a manageable list. Sorry if it's indeed an old bug. Hope someone here can help

**Bug Report**

mypy doesn't seem to understand that `Set[Optional[T]]` minus `None` is just `Set[T]`

**To Reproduce**
```python
from typing import Set
a: Set[str | None] = {'a', None, 'b'}
b: Set[str] = a - {None}
c = ','.join(b)
b2: Set[str] | None = None if None in a else a
```

**Expected Behavior**

both line 3 and line 5 should be correct

**Actual Behavior**
```
> python3 -m mypy temp.py
temp.py:3: error: Incompatible types in assignment (expression has type "Set[Optional[str]]", variable has type "Set[str]")
temp.py:5: error: Incompatible types in assignment (expression has type "Optional[Set[Optional[str]]]", variable has type "Optional[Set[str]]")
Found 2 errors in 1 file (checked 1 source file)
```
**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags: none
- Python version used: 3.10.4
- Operating system and version: Ubuntu 22.04LTS

**Comment by AlexWaygood** [comment]
The [typeshed stub for the `__sub__` method of `builtins.set`](https://github.com/python/typeshed/blob/f178ae0d832ac10f73979446c24f3051db814238/stdlib/builtins.pyi#L1090) is currently:

```python
from typing import MutableSet, Generic, AbstractSet, TypeVar

_T = TypeVar("_T")

class set(MutableSet[_T], Generic[_T]):
    def __sub__(self, __s: AbstractSet[_T | None]) -> set[_T]: ...
```

I guess we _could_ special-case `None`:

```python
from typing import MutableSet, Generic, AbstractSet, TypeVar, overload

_S = TypeVar("_S")
_T = TypeVar("_T")

class set(MutableSet[_T], Generic[_T]):
    @overload
    def __sub__(self: set[_S | None], __s: AbstractSet[None]) -> set[_S]: ...
    @overload
    def __sub__(self, __s: AbstractSet[_T | None]) -> set[_T]: ...
```

But I'm not sure this kind of thing is common enough to be worth special-casing here.

**Comment by tungol** [comment]
Shouldn't the special casing should really be for singleton types in general, similar to the changes made here? https://github.com/python/mypy/issues/13117

**Comment by TeamSpen210** [comment]
Well that one is different since it's about `is` and `if` - core syntax, unlike set operations here which are regular magic method operations.

Implementing the other singleton objects too would be tricky, since you'd need to account for all possible combinations of `NotImplemented`, `None`, `Ellipsis`, `True` and `False`. Bools might not really work since `{False, True}` is just going to have a type of `set[bool]`, it's not going to track whether or not both values are present which you'd need in order to remove from the union.

**Comment by AlexWaygood** [comment]
I agree with @TeamSpen210. There's no generalised way in the type system at the moment of indicating that a type is a singleton, and I don't think there would be enough use cases to make it worth the added complexity of creating a generalised way of doing that. The changes made in #13117 are highly specific to `EllipsisType`; it's the _opposite_ of "special casing for singleton types in general".

I'm closing this as I don't think there's anything actionable for mypy here. If we did want to do something in this area, the change would have to be made over at typeshed.

**Comment by erictraut** [comment]
Here's a straightforward workaround:

```python
def func(base_chars: set[str | None]):
    chars = frozenset(x for x in base_chars if x is not None)
    reveal_type(chars) # frozenset[str]
```
