### ISSUE TITLE
mypy stubtest raises error for non existing functions

### ISSUE THREAD

**Issue by maxbachmann** [python/mypy#13207]
**Bug Report**

MyPy stubtest reports errors for one of my libraries: https://github.com/maxbachmann/Levenshtein (https://github.com/maxbachmann/Levenshtein/runs/7435291548?check_suite_focus=true). Examples for the reported errors are:
```
error: Levenshtein._Editops.__add__ is not present at runtime
Stub: at line 902
def (builtins.list[_T`1], builtins.list[_T`1]) -> builtins.list[_T`1]
Runtime:
MISSING
```
```
error: Levenshtein._Editops.sort is not present at runtime
Stub: at line 886
Overload(def [SupportsRichComparisonT <: Union[_typeshed.SupportsDunderLT, _typeshed.SupportsDunderGT]] (self: builtins.list[SupportsRichComparisonT`-1], *, key: None =, reverse: builtins.bool =), def (self: builtins.list[_T`1], *, key: def (_T`1) -> Union[_typeshed.SupportsDunderLT, _typeshed.SupportsDunderGT], reverse: builtins.bool =))
Runtime:
MISSING
```

It is true that these functions do not exist, but I do not understand why mypy expects them to exist in the first place. My type hints do not claim that they exists:
```python
from typing import Tuple, List, Union, Any

_AnyOpList = Union[
    List[Union[Editop, Tuple[str, int, int]]],
    List[Union[Opcode, Tuple[str, int, int, int, int]]],
]

class Editop:
    tag: str
    src_pos: int
    dest_pos: int

    def __init__(self, tag: str, src_pos: int, dest_pos: int) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, i: int) -> Union[str, int]: ...
    def __repr__(self) -> str: ...

class Editops:
    def __init__(
        self, editops: _AnyOpList = None, src_len: int = 0, dest_len: int = 0
    ) -> None: ...
    @classmethod
    def from_opcodes(cls, opcodes: Opcodes) -> Editops: ...
    def as_opcodes(self) -> Opcodes: ...
    def as_list(self) -> List[Tuple[str, int, int]]: ...
    def __eq__(self, other: object) -> bool: ...
    def __len__(self) -> int: ...
    def copy(self) -> Editops: ...
    def inverse(self) -> Editops: ...
    @property
    def src_len(self) -> int: ...
    @src_len.setter
    def src_len(self, value: int) -> None: ...
    @property
    def dest_len(self) -> int: ...
    @dest_len.setter
    def dest_len(self, value: int) -> None: ...
    def __getitem__(self, key: int) -> Editop: ...
    def __repr__(self) -> str: ...
```
This error is either invalid, or I just fail to read it correctly.
Not sure whether this is relevant for this issue, but the class is defined in cython as `cdef class Editop`/`cdef class Editops`. 

**Your Environment**

- Mypy version used: mypy 0.971 (compiled: yes)
- Mypy command-line flags: python -m mypy.stubtest Levenshtein --ignore-missing-stub
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: Python3.10
- Operating system and version: Fedora 35

**Comment by maxbachmann** [comment]
The issue occurs since `v0.920`

**Comment by maxbachmann** [comment]
This behaviour exists since https://github.com/python/mypy/commit/7d9f20af865be334cbf7670bfb361530c19ecbb0

**Comment by JelleZijlstra** [comment]
cc @hauntsaninja

**Comment by hauntsaninja** [comment]
stubtest will check "private" definitions like "_Editops" if something exists with the same qualified name at runtime.

It looks like the runtime is importing "_Editops" here: https://github.com/maxbachmann/Levenshtein/blob/84ed32ad382e996a1e4851cbb32d41ac10609d31/src/Levenshtein/__init__.py#L31
This is a different object than what the stub has for "_Editops": https://github.com/maxbachmann/Levenshtein/blob/84ed32ad382e996a1e4851cbb32d41ac10609d31/src/Levenshtein/__init__.pyi#L7

Consider renaming the object in the stubs to something else. You could also try using an allowlist. stubtest supports regex matching in allowlists, so `Levenshtein._Editops..*` would silence these errors.

**Comment by hauntsaninja** [comment]
(let me know if I looked at the wrong code)

**Comment by maxbachmann** [comment]
Thanks @hauntsaninja renaming the definitions in the stub file fixed the issue :+1:
