### ISSUE TITLE
Move the wiki to github wiki

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1320]
The old moinmoin wiki has a pretty bad spam problem and moinmoin doesn't seem very actively maintained. I'm going to migrate the wiki to the github wiki.

**Comment by JukkaL** [comment]
This is done. The hosted documentation on readthedocs now has broken links to the old wiki, so we may want to do a new minor release soon.

**Comment by gnprice** [comment]
Awesome, thanks for the fast action on this!

A new minor release just to update the documentation's links to the wiki would be reasonable. With or without that, ideally we'd add redirects from all the useful pages on the old wiki to the corresponding pages on the new, to help people find it from any existing links floating around and to help Google Web Search find it.

How is the website hosted? Adding redirects could be as simple as making a `.htaccess` file with some `Redirect` lines.

**Comment by matt-the-bass** [comment]
@JukkaL I'm interesting in migrating a moinmoin wiki to github wiki. Are you able to share anything about how you did that? Was it a manual migration or did you use a tool?

**Comment by JukkaL** [comment]
@matt-the-bass I did a manual migration as the wiki was small enough and we had some custom macros that needed special handling anyway. 

(I also noticed that github doesn't have perfect spam controls either, but we'll see.)

**Comment by matt-the-bass** [comment]
@JukkaL Thanks for the quick reply.
