### ISSUE TITLE
About class attributes, its type and the stance about them

### ISSUE THREAD

**Issue by alexbarcelo** [python/mypy#1321]
[Maybe my google-fu or my manual-reading skills are poor, I apology beforehand if that's the case]

I read some things about [instance and class attributes](http://mypy.readthedocs.org/en/latest/class_basics.html#instance-and-class-attributes). However, the PEP0484 does not say anything about class attributes (anything I could find).

I am currently using Python 2, and I would be interested in using "something" for explicit types for class attributes, as in the Mypy documentation, but I am also eager to follow the PEP0484 or, at least, be somewhat compatible with the `typing` module for Python 3. As fas as I know there is no such thing as "annotations for class attribute assignment". And I am not sure of internals, so maybe it is out of the question for technical reasons. Or maybe there is plan to add the concept and I can start working on that.

Some thoughts about that?

Edit: Sorry, forgot my question related to class attributes and the Mypy "instance and class attributes" approach: is there something like the `typing.get_type_hints` but for the class attributes? I could not find anything similar on the frontend.

**Comment by JukkaL** [comment]
You can query the types of class variables because the type is either inferred or given as a comment, and comments aren't easily accessible at runtime, as they are lost during parsing. Example:

```
class A:
    x = 1 # type: int
```

We'd have to parse the file to detect that the type of `A.x` is `int`. But we'd also need to be able to evaluate `int` in the right namespace, as it could refer to something unexpected. Example:

```
from typing import Any as int
class A:
    x = 1 # type: int   # Actually Any!
```

This would be pretty hard to do so PEP 484 doesn't support it.

**Comment by gvanrossum** [comment]
I think you meant to write "You can't query the types of class variables"
right?

**Comment by JukkaL** [comment]
Yeah, sorry about the typo. I'll edit my response.

**Comment by alexbarcelo** [comment]
I didn't realize the typo in my first read through, my internal voice read it as "can't".

Thanks for the answer. I was thinking that comments were not easily accessible during runtime, as you stated. But didn't realize the extra problem with the namespace and runtime name bindings.

Seems that I should take another approach. On the bright side, it won't be PEP484 incompatible, as it would be quite orthogonal :-/
