### ISSUE TITLE
(🎁) Support `TypeVar`s in the bounds of other `TypeVar`s

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#13217]
```py
from typing import _T as T, TypeVar

L = TypeVar("L", bound=list[T])  # error: Type variable "typing._T" is unbound

def foo(l: L) -> L | T:  # error: A function returning TypeVar should receive at least one argument containing the same Typevar
    res = l[0]
    if res:
        return res
    return l

a: list[int] | list[str]

reveal_type(foo)  # "def [L <: list[T?], T] (l: L) -> L | T"
reveal_type(foo(a))  # list[int] | list[str]
```
Expected:
```py
reveal_type(foo)  # "def [T, L <: list[T]] (l: L) -> L | T"
reveal_type(foo(a))  # list[int] | list[str] | int | str
```
Mypy should understand that `T` should be bound to `foo` from `L`

# Typescript example
The same idea could be represented in TypeScript as:
```ts
declare function foo<T, L extends T[]>(l: L): L | T

declare let a: number[] | string[]

let b = foo(a)
```
Although TS fails to infer the correct type here. (it infers as `unknown`)

**Comment by erictraut** [comment]
This concept doesn't make sense. A TypeVar used within the bound of a TypeVar would have no defined scope. It should therefore be considered an error to use a TypeVar within a bound or constraint expression. PEP 484 isn't as clear as it could be on this point. I've attempted to remedy that omission in draft [PEP 695](https://peps.python.org/pep-0695/#upper-bound-specification).

**Comment by DetachHead** [comment]
how so? typescript supports it:
```ts
declare function foo<T, L extends T[]>(l: L, t: T): T

declare const a: number[]
declare const b: number

const c = foo(a, b) //inferred as foo<number, number[]>
```

**Comment by KotlinIsland** [comment]
In my opinion this is orthagonal to generic `TypeAliases`:
```py
L = list[T]
a: L[int]
```
Here `T` is unbound, yet it's a valid and semantically sound expression.

> I've attempted to remedy that omission in draft [PEP 695](https://peps.python.org/pep-0695/#upper-bound-specification).
```py
class ClassC[T: dict[str, V]]: ...  # Type checker error: generic type
# But
class ClassC[V, T: dict[str, V]]: ...  # LGTM
```
The second example is how I understand the example in the OP.

**Comment by AlexWaygood** [comment]
Things like this should be discussed in the python/typing issue tracker or on the typing-sig mailing list, not the mypy issue tracker. We'd need agreement on the spec before individual type checkers could start supporting this.

**Comment by KotlinIsland** [comment]
@AlexWaygood Could you transfer the issue to python/typing?
