### ISSUE TITLE
Incorrect type narrowing when unpacking union of tuple

### ISSUE THREAD

**Issue by wplohrmann** [python/mypy#13218]
**Bug Report**

I have the following two snippets:

```python
from typing import Tuple, Union
def a(b: bool) -> Union[Tuple[str, str], Tuple[int, int]]:
    if b:
        return 0, 0
    else:
        return "", ""

kl = a(True)
if isinstance(kl[0], str):
    reveal_type(kl[1])
```
and
```python
from typing import Tuple, Union


def a(b: bool) -> Union[Tuple[str, str], Tuple[int, int]]:
    if b:
        return 0, 0
    else:
        return "", ""

k, l = a(True)
if isinstance(k, str):
    reveal_type(l)
```

The first snippet outputs `Revealed type is "builtins.str"` (correct) whereas the second outputs
`Revealed type is "Union[builtins.str, builtins.int]"` (wrong). Presumably what's happening in the second snippet is that the dependency between `k` and `l` is removed as soon as the unpacking occurs. 

**Your Environment**

mypy == 0.960
python == 3.9.13

**Comment by hauntsaninja** [comment]
Yes, that's right. mypy doesn't do this kind of inter variable analysis and unfortunately won't anytime in the medium future. I'm not aware of any other Python type checkers that have this feature, either.
