### ISSUE TITLE
stubgen drops default values for function arguments

### ISSUE THREAD

**Issue by davidgilbertson** [python/mypy#13238]
**Bug Report**

I have a file with _some_ types defined (that I can't modify), and want to create a stub for this file so that I can fill out the remainder of the types.

So I run stubgen, and it creates draft stubs, but all the default parameter values that had been defined are lost.

`.py` source file:
```py
def hash_pandas_object(
    obj: Index | DataFrame | Series,
    index: bool = True,
    encoding: str = "utf8",
    hash_key: str | None = _default_hash_key,
    categorize: bool = True,
) -> Series:
```

Generated `.pyi` file
```py
def hash_pandas_object(
    obj: Union[Index, DataFrame, Series],
    index: bool = ...,
    encoding: str = ...,
    hash_key: Union[str, None] = ...,
    categorize: bool = ...,
) -> Series: ...
```

I understand that typically these default values are considered implementation code and don't 'belong' in a stub file, but nonetheless they are quite useful to me. For example, with a stub file present, IntelliJ will show me the signature from the stub, but now I've lost the information of what the default encoding is:
![image](https://user-images.githubusercontent.com/4443482/180908609-fd7905fa-1778-49cf-99e3-0f12b29e1775.png)

It would be nice to at least have an (opt-in) option when generating stubs to keep these default values.

**Comment by thomkeh** [comment]
The title of the issue should probably be something like "stubgen drops default values for function arguments". Saying it "drops types" seems a bit misleading.

**Comment by davidgilbertson** [comment]
@thomkeh agreed, fixed.
