### ISSUE TITLE
(🐞) no error when overriding read only property with attribute not initialised in class body

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#13230]
```py
class Foo: 
    @property
    def foo(self) -> int: ...
class Bar(Foo):
    foo: int
    def __init__(self) -> None:
       self.foo = 2  # runtime error
Bar()
```
[playground](https://mypy-play.net/?mypy=latest&python=3.10&gist=a93475271582357694f05edee99628e4)

**Comment by AlexWaygood** [comment]
Closing in favour of #14413 (this bug report was filed first, but there's more description in #14413 of exactly why this behaviour is problematic)
