### ISSUE TITLE
CHANGELOG file

### ISSUE THREAD

**Issue by tony** [python/mypy#13279]
I've seen an earlier issue on this closed (#2859) as well as a recent issue bringing up changelogs (#12210)! 

**Feature**

Single file changelog, with changes release manager deems most significant weighted to the top

**Pitch**

_Problem_
I feel it's really difficult a user to track changes the maintainer deems useful.  Users are left to git log or taking several clicks to find release notes.

A normal user is going to end up being a few releases behind, and they may be overwhelmed by how much effort it takes to see what changed

_What I think is most helpful_
I personally find git logs interesting to read, however, I imagine mypy may be far along enough its worth keeping a changelog.

When a maintainer is cutting the release, they can go back and take a few minutes to weigh what's happened since last release and curate highlights of the changelog.

_Why I think a single, curated changelog is best_
- Can be linked to via PyPI, one page
- No extra clicks or pagination
- Search via control-f / command-f
- Scroll
- Can be linked to git tags (in future release, if a changelog is added)

**Other references**
- #2859
- #12210: Changelog is referenced here: https://github.com/python/mypy/issues/12210#issuecomment-1044447884

**Comment by tony** [comment]
It would be a dream to have this (still!)

**Comment by jessestricker** [comment]
for anyone, who like me ended up here in search of a changelog file: 
there is none, but the release notes are available on their blog, which you can find here:
https://mypy-lang.blogspot.com/

i'm in favor of a proper `CHANGELOG` file, though

**Comment by hauntsaninja** [comment]
We're going to try to keep release notes inside the repo, see https://github.com/python/mypy/pull/16280
These are just the equivalent of the blogspot posts, for a full revision history, git log will always be authoritative
