### ISSUE TITLE
isinstance(x, (t1, t2)) doesn't change mypy's knowledge of x's type.

### ISSUE THREAD

**Issue by nathanielherman** [python/mypy#1328]
For example in the following code:
```
def f(x):
  # type: (object) -> list
  if isinstance(x, (list, set)):
    return [g(i) for i in x]
```
mypy will complain that an `Iterable` is expected (it still only sees `x` as an `object`). This can be resolved with e.g. a manual `cast` of `x` to `Union[list, set]`, but this adds a slight overhead and isn't as clean.

**Comment by JukkaL** [comment]
Mypy doesn't understand tuples in `isinstance` yet, but this should be easy to implement.

**Comment by gvanrossum** [comment]
What should the type of x be inferred to though? `Union[t1, t2]`?

If this is important I can give it a shot for the current milestone.

**Comment by kirbyfan64** [comment]
I just implemented this. I'll write the tests and submit a PR.

In my implementation, the type of `x` would by `Union[t1, t2]`, like @gvanrossum said.

**Comment by gvanrossum** [comment]
Awesome!!
