### ISSUE TITLE
(🎁) Adopt pre-commit.ci

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#13281]
The last remaining incomplete task from adopting black (#12424/#10996) is to add the [pre-commit GitHub app](https://github.com/marketplace/pre-commit-ci) to the mypy project. 
I believe only owners have permission to do so. (@JukkaL)

**Comment by ssbarnea** [comment]
It is like crack! A huge help and productivity boost for incoming PRs as it does report problems in seconds and can also fix basic mistakes, reducing the polishing time considerably. I used it for 3-4 years by now.

PS. I see that current pre-commit config uses only 3 hooks, I know few more that could help so there is space for improvement there too.

**Comment by JukkaL** [comment]
Yeah, this sounds like a good idea. I'm not sure if I can do this, however, since mypy is under the Python org.

**Comment by AlexWaygood** [comment]
> I'm not sure if I can do this, however, since mypy is under the Python org.

So is typeshed, but @JelleZijlstra  managed to enable it for that repo!

**Comment by JelleZijlstra** [comment]
That prompted me to try whether I could do it for mypy too. I went through the flow on pre-commit.ci and tried to add mypy, but I think I only "requested" it. Maybe Jukka has enough access to actually enable it.

**Comment by ikonst** [comment]
@ssbarnea mypy's self-check might be a good candidate :) though probably as a 'system' hook rather than using pre-commit's mypy hook, since the latter wouldn't have our custom plugin.

**Comment by hauntsaninja** [comment]
Thanks to @ambv , we got pre-commit.ci added to the repo. #15116 shows that it works

**Comment by ssbarnea** [comment]
The next move would be to replace flake8 with ruff, something I started about a month ago on ~10 project, it is awesome.
