### ISSUE TITLE
mypy does not recognize `!= None` check

### ISSUE THREAD

**Issue by Jylpah** [python/mypy#13318]
**Bug Report**

mypy's check for [Optional None type](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#optional-types-and-the-none-type) work for `is not None` but does not work for `!= None`. 

**To Reproduce**

For example [os.cpu_count()](https://docs.python.org/3/library/os.html#os.cpu_count) has return type `Optional[int]`i.e. it returns `int` normally and `None` when undetermined. 

1. Make a test script `mypy-none-check.py` with content:
```
#!/usr/bin/env python3
from os import cpu_count
THREADS 		= 5

# works
cpus = cpu_count()
if cpus is not None:
	THREADS = cpus

# does not work
cpus = cpu_count()
if cpus != None:
	THREADS = cpus   # line 13
```

2. run mypy:

```
% mypy mypy-none-check.py
mypy-test.py:13: error: Incompatible types in assignment (expression has type "Optional[int]", variable has type "int")
Found 1 error in 1 file (checked 1 source file)
```
The first None check works fine, but the latter gives an error. 

**Expected Behavior**

I would expect both "textual" (is, is not) and C-style logical operators work the same with mypy. 

**Actual Behavior**

See above

**Your Environment**

- Mypy version used:

```
% mypy --version
mypy 0.971 (compiled: yes)
```

- Mypy command-line flags:

None

- Mypy configuration options from `mypy.ini` (and other config files):

```
% cat ~/.config/mypy/config 
[mypy]
warn_return_any         = True
warn_unused_configs     = True
disallow_untyped_calls  = True

[mypy-aioconsole.*]
ignore_missing_imports = True

[mypy-lz4.*]
ignore_missing_imports = True
```

- Python version used:
```
% python --version
Python 3.10.4
```
- Operating system and version:

Ubuntu 22.04 LTS on WSL2 on Windows 11 (amd 64)

```
% uname -srpov
Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux
```

```
% cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

**Comment by Jylpah** [comment]
It seems the issue here is that *type-narrowing* requires *Identity* operator `is(a,b,)` and does not work with *equality* operator `eq(a,b)`. `==` is equal to `eq()`, not `is()` and `!=` is equivalent of `ne()`, not `not is()`. 

Therefore, this is not a bug, but feature request _IF_ it would make sense for language perspective. Big thanks to `mypy` for teaching me write correct Python :-)

**Comment by sobolevn** [comment]
I think that the reason behind this is that `!= None` is tricky.
You can create a class with something like:

```python
class My:
   def __ne__(self, other):
       return False

x: My | None
if x != None:
   reveal_type(x)  # ???
```

**Comment by sobolevn** [comment]
I am going to close this issue as "working as it should" 🙂
