### ISSUE TITLE
`stubtest` produce no error when `@abstractmethod` is omitted from stubs

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#13322]
If I have this runtime implementation:

```python
from abc import abstractmethod

class A:
    @abstractmethod
    def some(self) -> None:
        raise NotImplementedError
```

And this stub:

```python
class A:
    def some(self) -> None: ...
```

There's no error. 

Why is that important?
Because with the stub like above, mypy will allow to create an instance of `A`.
But, mypy should not be allow to do that.

I think it is a bug that should be fixed. And it is a pretty easy one.

**Comment by AlexWaygood** [comment]
I used a stubtest patch along these lines to work on this typeshed PR in May:
- https://github.com/python/typeshed/pull/7443

But I never got round to writing tests and submitting a PR to mypy. I'm glad you're picking it up :D
