### ISSUE TITLE
Stubgen doesn't infer abstract base classes such as Iterator automatically 

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1333]
For example, when generating a stub for `itertools` mypy should notice that bunch of the classes define `__iter__` and `__next__` and infer an `Iterator` base class.

(Reported originally by Rahul Gopinath.)

**Comment by ilevkivskyi** [comment]
I think this is not needed, since all these are now protocols, so mypy will figure out all the subtyping correctly.
