### ISSUE TITLE
Cannot access `__optional_keys__` on TypedDict: "has no attribute"

### ISSUE THREAD

**Issue by lmmx** [python/mypy#13358]
The [docs](https://docs.python.org/3.9/library/typing.html#typing.TypedDict.__optional_keys__) say you can access `__optional_keys__` on a TypedDict (3.9+) but mypy complains there's no such attribute

- mypy playground: https://mypy-play.net/?mypy=latest&python=3.10&gist=435298e6fd5651af318d112e5fa40db6
- GitHub gist: https://gist.github.com/435298e6fd5651af318d112e5fa40db6

**To Reproduce**

```sh
from typing import TypedDict


class BaseTD(TypedDict, total=False):
    opt: int  # Optional key


class MyTD(BaseTD):
    req: int  # Required key


d = MyTD(req=0, opt=1)

print(MyTD.__optional_keys__)
```

**Expected Behavior**

It shouldn't error, the `__optional_keys__` of the class should exist for a TypedDict. Indeed, the program runs fine, just doesn't type check.

**Actual Behavior**

```
Failed (exit code: 1) (2107 ms)

main.py:14: error: "Type[MyTD]" has no attribute "__optional_keys__"
Found 1 error in 1 file (checked 1 source file)
```

Mypy appears to not see the attribute

- Python version used: 3.9 or 3.10 (see mypy playground link above)
- Operating system and version: Linux (Python in conda, also mypy playground reproduces so not just on my machine)

**Comment by AlexWaygood** [comment]
It's a typeshed bug, not a mypy bug. I've filed https://github.com/python/typeshed/pull/8512 to fix it.

**Comment by lmmx** [comment]
Awesome work Alex looks like it's about to pass :clap:
