### ISSUE TITLE
PEP 604 Union types do not properly infer default value types

### ISSUE THREAD

**Issue by plinss** [python/mypy#13364]
**Bug Report**

mypy does not correctly infer types with default values of arguments and PEP 604 union syntax.

**To Reproduce**

```
def foo(x: (int | float) = None) -> None:
    pass
```
gives: `Incompatible default for argument "x" (default has type "None", argument has type "Union[int, float]")`

Where:
```
def foo(x: Union[int, float] = None) -> None:
    pass
```
works fine.

**Expected Behavior**

mypy should infer that the type of the default value is an acceptable union type. 

**Actual Behavior**

Type error.

**Your Environment**

mypy 0.971
Python 3.8

**Comment by erictraut** [comment]
`None` is not compatible with the type `int | float`. It looks like you're relying on long-ago deprecated behavior where a default argument of `None` implied an `Optional` type for a parameter annotation. PEP 484 was updated a couple of years ago to indicate that this behavior was no longer recommended for type checkers. ("A past version of this PEP allowed type checkers to assume an optional type when the default value is None,") Mypy left the old behavior in place for backward compatibility with older code, but if you're writing new code or updating old code to use PEP 604 syntax, that's a good opportunity to move away from this deprecated behavior.

**Comment by plinss** [comment]
Ok, fair enough. It was just surprising behavior when updating code. Sorry for the bother.
