### ISSUE TITLE
`ParamSpec` errors when (re)used as generic argument

### ISSUE THREAD

**Issue by flaeppe** [python/mypy#13403]
**Bug Report**

Passing "through" a `ParamSpec` variable as argument up a generic class declaration chain generates errors.

I'm not sure if I'm taking an incorrect approach down here, but I'd like to be able to declare a decorator as a callable class that when decorating a function "disassembles" and copies the function signature on to the decorators `__call__` signature. 

**To Reproduce**

I'm running in to 2 slightly different errors when attempting the following two things. I can understand why I get the error on __1.__, but I'm a little bit confused by the error in __2.__

1. Passing a `ParamSpec` as argument, directly

```python
from typing import Generic, ParamSpec

P = ParamSpec("P")

class Base(Generic[P]):
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> None:
        ...

class Child(Base[P], Generic[P]):  # yields -> error: ParamSpec "P" is unbound
    ...
```

2. Using a `ParamSpec` argument to assemble a callable, which is passed as new argument to a base class

```python
from typing import Any, Callable, Generic, ParamSpec, TypeVar

P = ParamSpec("P")
C = TypeVar("C", bound=Callable[..., Any])

class Base(Generic[C]):
    def __init__(self, func: C) -> None:
        ...


class Child(Base[Callable[P, Any]], Generic[P]):  # yields -> error: The first argument to Callable must be a list of types, parameter specification, or "..."
    ...
```

[Extended use case through playground](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-codes%2Cstrict&gist=525b125a85e0f0077815354b5afc5e09)

**Expected Behavior**

I'd like to be able to use a `ParamSpec` variable to pass on an expected definition to some base class.

**Actual Behavior**

Mypy yields errors when "passing" a `ParamSpec` as a generic error to some base class.

**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags: -
- Mypy configuration options from `mypy.ini` (and other config files): -
- Python version used: 3.10
- Operating system and version: macOS Catalina 10.15.7

**Comment by A5rocks** [comment]
I think this works now! Check your mypy playground link -- since you were using `latest` it'll use mypy 1.0 which fixes this!

**Comment by hauntsaninja** [comment]
Thanks for updating this issue!
