### ISSUE TITLE
Internal errors in third pass go uncaught

### ISSUE THREAD

**Issue by gnprice** [python/mypy#1341]
We have a nice `report_internal_error` mechanism for catching unexpected exceptions and reporting them explicitly as internal errors with the source file and line number that triggered the issue.

In the crash reported as #1319, that mechanism didn't fire. That was in the third pass of semantic analysis, and from the code it looks like we invoke that mechanism around the main (second) pass of semantic analysis and the type checker itself, but not the third pass.

Because it seems somewhat tricky to get this error reporting into every context where we know a specific line number, it might be helpful, in addition to any fix specifically for `ThirdPass`, to put a backstop layer of reporting that makes sure we at least identify the file. (As #1319 illustrates, it can be tricky to identify that from the outside!) It looks like the `State.process` call in the main build loop in `BuildManager.process` could be an effective spot for that.

**Comment by JukkaL** [comment]
A good idea!

**Comment by gvanrossum** [comment]
Doing this to State.process() would require me to rewrite the logic once incremental lands, so I propose to wait for that (it's also targeted for 0.3.2).

**Comment by gnprice** [comment]
Sounds good. And thanks for the fast fix!
