### ISSUE TITLE
Regression with recent mypy versions and Pydantic Generic support

### ISSUE THREAD

**Issue by EldarSehayekZenity** [python/mypy#13421]
# Bug

I use Pydantic latest version 1.9.1 and Mypy 0.940. I tried to upgrade to Mypy 0.950 and received new type compatibility issues because the type arguments for Pydantic generic models wasn't resolved properly when inheritance was involved, the code sample below will show mypy error: Argument "data" to "GenericDerivedClass" has incompatible type "List[str]"; expected "List[_TResult]"
I'll mention that I work with VSCode, and Pylance doesn't have the same issue, it recognizes the generics usage as valid.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`: 
```
pydantic version: 1.9.1
pydantic compiled: True
install path: <my project's virtual env pydantic lib path, omitted for privacy reasons>
python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
platform: Windows-10-10.0.22000-SP0
optional deps. installed: ['typing-extensions']
```

```py
from typing import Generic, TypeVar
from pydantic.generics import GenericModel

_TResult = TypeVar("_TResult")

class GenericSuperClass(GenericModel, Generic[_TResult]):
    data: list[_TResult]
    total: int

class GenericDerivedClass(GenericSuperClass[_TResult], GenericModel, Generic[_TResult]):
    extra: int

def use_generic_super_class() -> None:
    strings: list[str] = ["foo", "bar"]

    derived_class: GenericDerivedClass[str] = GenericDerivedClass(data=strings, total=2, extra=5)
    print(derived_class)
```

# Troubleshooting

Didn't solve: I tried making `GenericDerivedClass` not inherit from `GenericModel`
Did solve: I tried making `GenericDerivedClass` have a field of type `GenericSuperClass[_TResult]` instead of inherit from it,
So I can say this is an inheritence issue with generic models.

I opened same issue for Pyndatic and was asked to open it as mypy issue: https://github.com/pydantic/pydantic/issues/4327

**Comment by phillipuniverse** [comment]
A bit more information - this still occurs in Pydantic 1.10.2 and Mypy 0.982 (both the latest at time of writing).

Modifying the above code slightly to add `reveal_type`:

```python
def use_generic_super_class() -> None:
    strings: List[str] = ["foo", "bar"]

    derived_class: GenericDerivedClass[str] = GenericDerivedClass(data=strings, total=2, extra=5)
    reveal_type(derived_class)
    reveal_type(derived_class.data)
    print(derived_class)
```

I get this:

```
pydantic_issue_test.py:21: note: Revealed type is "pydantic_issue_test.GenericDerivedClass[builtins.str]"
pydantic_issue_test.py:22: note: Revealed type is "builtins.list[_TResult`1]"
```

Basically the generic type is getting replaced with something appended with "`1", so "_TResult`1"

**Comment by erictraut** [comment]
This bug appears to have been fixed at some point. I'm not able to repro it with the latest version of mypy (1.5).
