### ISSUE TITLE
Reusing a function in an ``or`` statement doesn't affect type narrowing

### ISSUE THREAD

**Issue by DanielNoord** [python/mypy#13430]
**Bug Report**

When using a function twice and doing checks on the type of the return value this doesn't seem to affect a second call to that function in an ``or`` statement.

**To Reproduce**

```python
from typing import Any

def f(x: Any) -> None | str:
    ...

def h(x: Any) -> Any:
    if f(x) is None or f(x).endswith("foo"):
        return x
```

**Expected Behavior**

Since the return value of `f(x)` isn't `None` it has to be a `str` and the attribute exists.

**Actual Behavior**

```console
test.py:7: error: Item "None" of "Optional[str]" has no attribute "endswith"  [union-attr]
```

**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags: `--strict`
- Python version used: `3.10`
- Operating system and version: Mac

**Comment by hauntsaninja** [comment]
There is no guarantee that `f(x)` is deterministic. Consider using the walrus operator
