### ISSUE TITLE
`callable` typeguard doesn't work on `Any`

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#13443]
```py
from typing import Any

foo: Any
assert callable(foo)
reveal_type(foo) # Any
```
[playground](https://mypy-play.net/?mypy=latest&python=3.10&gist=19e1d7f09aba4e7a6371095cde226ed4)

`TypeGuard`s usually narrow `Any`:
```py
from typing import Any, TypeGuard

foo: Any

def narrow(value: Any) -> TypeGuard[int]:
    ...

assert narrow(foo)
reveal_type(foo) # int
```
so `callable` should behave the same

**Comment by ethanhs** [comment]
Interestingly copying the definition of callable from typeshed does narrow the type:

```
from typing import TypeGuard, Any, Callable

def callable(__obj: object) -> TypeGuard[Callable[..., object]]: ...

a: Any
assert callable(a)
reveal_type(a) # main.py:7: note: Revealed type is "def (*Any, **Any) -> builtins.object"
```

I guess we special case things for callable somewhere.

**Comment by DetachHead** [comment]
The special cased typeguards such as `isinstance` act completely differently to user defined `TypeGuard`s, see #11229

**Comment by erictraut** [comment]
Support for `callable` type narrowing in mypy predates the introduction of `TypeGuard`. The special-case code that handles `callable` type narrowing acts more like `isinstance` narrowing than `TypeGuard`. It would be possible to remove the older special-case code. The downside of doing this is that existing typed code bases may rely on the current behavior. The other benefit of sticking with the current special-case logic is that it supports narrowing in the negative ("else") case whereas `TypeGuard` does not.

**Comment by erictraut** [comment]
As I explained above, I don't think this is a bug. Mypy (like pyright) special cases the `callable` call, which is beneficial. I recommend closing.

**Comment by hauntsaninja** [comment]
Thanks to sobolevn for trying it out so we could see the damage in mypy_primer
