### ISSUE TITLE
__new__ and subclassing is wrongly interpreted by mypy

### ISSUE THREAD

**Issue by socketpair** [python/mypy#13440]
```python
class Base:
    def __new__(cls):
        return 42

    def get(self) -> str:
        return 'hello'

class Child(Base):
    pass


print(Child())
print(Child().get())
```

This code obviously will fail at runtime:

```
42
Traceback (most recent call last):
  File "/tmp/qwe2.py", line 13, in <module>
    print(Child().get())
AttributeError: 'int' object has no attribute 'get'
```

But MyPy sees nothing wrong.

**Comment by hauntsaninja** [comment]
That's because mypy sees `def __new__(cls):` as `def __new__(cls) -> Any:`. If you annotate it as `def __new__(cls) -> int:`, you'll get an error

**Comment by socketpair** [comment]
@hauntsaninja why mypy does not infer return type of `__new__` ? I think it should

**Comment by hauntsaninja** [comment]
mypy does not infer unannotated types in general. I agree that it would be useful if mypy was capable of that, see e.g. https://github.com/python/mypy/issues/4409
