### ISSUE TITLE
Idea: issue an error if a '# type: ignore' comment is unused

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1345]
Sometimes we put in `# type: ignore` comments because of some mypy or typeshed bug (or a missing feature). It would be nice if mypy told us when we can take those out (e.g. because the bug is fixed).

Maybe this should be a command-line flag, I can imagine it might be annoying occasionally too.

**Comment by ddfisher** [comment]
This is a good idea!  I think it should definitely be behind a flag, though -- it'd be annoying to cause errors in people's code whenever we fix a bug.  Also, they may need the code to work across multiple mypy versions for some reason, which this would disallow.  The fast parser transition is a concrete example:  because it can change the line errors are assigned to, you'll need some extraneous type ignores during the transition period.

**Comment by gvanrossum** [comment]
It was @rwbarton's suggestion -- IIRC he said GHC has this.

--Guido (mobile)
On Apr 7, 2016 5:10 PM, "David Fisher" <notifications@github.com> wrote:

This is a good idea! I think it should definitely be behind a flag, though
-- it'd be annoying to cause errors in people's code whenever we fix a bug.
Also, they may need the code to work across multiple mypy versions for some
reason, which this would disallow. The fast parser transition is a concrete
example: because it can change the line errors are assigned to, you'll need
some extraneous type ignores during the transition period.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/python/mypy/issues/1345#issuecomment-207145490>

**Comment by ddfisher** [comment]
I think it's become clear that this is a good idea to have available behind a flag.  I think I'd discourage running with this on in CI (because sometimes you need unused # type: ignores for forward compatibility), but it would be great to have for periodic sweeps.

**Comment by gvanrossum** [comment]
Yes!

**Comment by rwbarton** [comment]
Even a simple version of this behind a flag will be useful, and I sort of promised this to the Zulip people, so I'll take a shot at this in the near future (traveling again this weekend but will still have time for mypy work).

**Comment by wittekm** [comment]
Potentially related request: could the same thing be accomplished for superfluous cast(some_obj, SomeType) when some_obj is already guaranteed to be SomeType?

**Comment by ddfisher** [comment]
Sounds like a good idea to me -- could even be the same flag, IMO.

**Comment by rwbarton** [comment]
> could the same thing be accomplished for superfluous cast(some_obj, SomeType) when some_obj is already guaranteed to be SomeType?

Yes! In fact, that is #958. Mypy itself has many redundant casts from before mypy understood isinstance checks; I removed about 60 of them a while ago but I'm sure there are a lot more.
