### ISSUE TITLE
Can't determine input argument type with structural pattern matching when class is set as attribute of another class

### ISSUE THREAD

**Issue by jeremyn** [python/mypy#13455]
**Bug Report**

mypy errors with "Cannot determine type" of an input argument when using structural pattern matching against a class set as an attribute of another class.

**To Reproduce**

Example:

```python
from dataclasses import dataclass

@dataclass
class A:
    x: str

class B:
    A = A

match A("y"):
    case B.A(z):
        # mypy: error: Cannot determine type of "z"
        # correctly prints: "x: y"
        print(f"x: {z}")
```

`case A` works fine, as does defining `A` directly inside `B` instead of setting `A = A`.

**Expected Behavior**

I don't get the mypy error above.

**Actual Behavior**

I get the error.

**Your Environment**

Mypy version used: 0.971 (compiled: yes)
Python version used: 3.10.4
Operating system and version: Ubuntu 22.04

**Comment by AlexWaygood** [comment]
If you declare `B.A` as an explicit type alias, everything works as expected:

```python
from dataclasses import dataclass
from typing import TypeAlias

@dataclass
class A:
    x: str

class B:
    A: TypeAlias = A

match A("y"):
    case B.A(z):
        print(f"x: {z}")
```

https://mypy-play.net/?mypy=latest&python=3.10&gist=1cffece9249ad85ed59efbbb4a4a6e44

**Comment by jeremyn** [comment]
@AlexWaygood Thanks for the response. Unfortunately in my actual code, the container class is a dataclass, so mypy raises a not supported error which led me to https://github.com/python/mypy/pull/12792.

I'm not completely sure but based on that issue it looks like mypy just doesn't support TypeAlias in dataclasses, and there aren't any plans to ever support it, not even a wish list open issue. Is that right?

Also @JukkaL said in https://github.com/python/mypy/pull/12792#pullrequestreview-980116894

> this error mode is probably quite rare and it is easy to work around anyway (just move the type alias to an outer scope).

but I'm not sure if he was talking about a workaround in the mypy code or a workaround for users like me.

**Comment by AlexWaygood** [comment]
Right, yeah, this is an awkward corner-case. Type aliases inside dataclasses are difficult for a number of reasons. But you can't put the alias in the global scope here — you need the dotted lookup for pattern-matching.

I guess my best suggestion here is... Don't do that? Would it be possible to make the container class not-a-dataclass?

**Comment by jeremyn** [comment]
There are some other ways to go, sure. Thanks again for your help.

**Comment by AlexWaygood** [comment]
> There are some other ways to go, sure. Thanks again for your help.

No worries. Sorry about the limitations here :)
