### ISSUE TITLE
Check which files were rechecked in incremental mode test cases (and which weren't)

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1350]
We need to improve the test harness for incremental tests (in testcheck.py) to check which files were or weren't rechecked. We probably need to add new syntax to test descriptions to describe expectations here.

**Comment by Michael0x2a** [comment]
As an update: the new syntax was added in https://github.com/python/mypy/pull/1811.

**Comment by ilevkivskyi** [comment]
This is now supported by `[rechecked]`, `[stale]`, etc.
