### ISSUE TITLE
(🐞) Bad error message when using `Concatenate` incorrectly

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#13518]
Despite the fact that a good message is output afterwards, the initial error seems like nonsense: "first arg to Callable must be a parameter specification". Huh? it **is** a `ParamSpec`?! I presume that this is because the type becomes `Any (from error)` due to the args being invalid.  At runtime the type here would be `Never` (because it would `raise`).

```py
from typing import Concatenate, Callable, ParamSpec, TypeVar, Any

P = ParamSpec("P")

def f(fn: Callable[Concatenate[P, int], None]): ...
```
```
main.py:5: error: The first argument to Callable must be a list of types, parameter specification, or "..."
main.py:5: note: See https://mypy.readthedocs.io/en/stable/kinds_of_types.html#callable-types-and-lambdas
main.py:5: error: The last parameter to Concatenate needs to be a ParamSpec
Found 2 errors in 1 file (checked 1 source file)
```
[playground](https://mypy-play.net/?mypy=latest&python=3.10&gist=481ae1cb9df8dc9177c47f83481d2a97)

**Comment by KotlinIsland** [comment]
@sobolevn Should the message `The first argument to Callable must be a list of types, parameter specification, or "..."` be updated to include `Concatenate` or do you think that `Concatenate` falls under "parameter specification"?

**Comment by sobolevn** [comment]
> do you think that Concatenate falls under "parameter specification"?

I think this is correct 🤔

**Comment by gandhis1** [comment]
Does MyPy actually support `Concatenate`? I attempted to use it, but it's rejecting my first parameter in `Callable[Concatenate[Dict[str, sa.Table], P], sa.sql.expression.Selectable]`
