### ISSUE TITLE
Handle interaction of -i and -s

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1351]
When using --incremental mode (-i) with -s (--silent-imports) the cache should technically be invalidated when a different set of files is passed, since imports that are "silenced" by this flag are stored as objects of type Any in the importing module's namespace.

We need this to work seamlessly, either by emptying the cache whenever the set of files changes, or by recording the silenced dependencies in the cache metadata, or by some other approach.

**Comment by ddfisher** [comment]
Talked in person.  It looks like adding some indication in the cache file or metadata that the file was excluded due to -s could be a fruitful approach.  We'd need to check if files have explicit dependencies on their silent imports or not (and add that if they don't).

**Comment by gvanrossum** [comment]
Fixed by d84bdea.
