### ISSUE TITLE
Turn on the incremental cache by default

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1352]
We now have incremental mode but it's off by default; we would like to turn it on by default.

This is a follow-up on #932, which was closed after #1292 landed.

Dependencies are at least #1349 (add tests), #1350 (check which files we rechecked), and #1351 (interaction between -i and -s).

We probably also want some command-line options to force resetting the cache or control the name of the cache directory.

**Comment by gvanrossum** [comment]
More dependencies: #1354 (reset cache when mypy changed), #1355 (cache reading error handling).

**Comment by ilevkivskyi** [comment]
Finally!!!!!!
