### ISSUE TITLE
Make typed_ast mypy's default and only parser

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1353]
Currently, typed_ast is mypy's preferred parser (as it's much faster, more correct, and supports features like multiline type comments), but it is not yet mypy's default parser. The main blocker to this is Windows support.

Here are the high-level items remaining:
- [x] make typed_ast compile and run correctly on Windows
- [x] autobuild Windows wheels with AppVeyor
- [ ] [optional] autobuild OS X wheels in TravisCI
- [ ] update tests to account for minor line differences between typed_ast and the current parser
- [ ] make typed_ast the default parser
- [ ] remove old parser

**Comment by ddfisher** [comment]
After this is complete, we can start converting mypy to use typed_ast's ast (which is very similar to the official python ast) node by node (which will further help perf).

**Comment by ddfisher** [comment]
`typed_ast` code now available at https://github.com/dropbox/typed_ast

**Comment by gvanrossum** [comment]
@ddfisher: I've created a label "New Parser" and added it to all issues that look like they would be fixed by the new parser or could be fixed once the new parser is the only parser.

**Comment by ddfisher** [comment]
The progress of making typed_ast compile and run on Windows is being tracked in this issue: https://github.com/dropbox/typed_ast/issues/20

**Comment by ethanhs** [comment]
Since typed_ast now supports Windows fully, would there be interest in me working on appveyor integration? I know it was tried previously, but once this is completed, I see no reason why it shouldn't be added.

**Comment by gvanrossum** [comment]
Yes @ethanhs we would it if you could contribute Appveyor integration! I once tried but didn't understand how it was supposed to work.
