### ISSUE TITLE
return type of arithmetic operators is different with typing.Any arguments

### ISSUE THREAD

**Issue by francesco-ballarin** [python/mypy#13578]
**Bug Report**

Hi, 
I am a new mypy user. While type checking my library, I noticed that sometimes mypy says that the return type of arithmetic operators is `Any` when passed `Any` arguments, even if I correctly typed a non-`Any` return type.
My actual `Any` arguments come from an untyped library.

**To Reproduce**

Consider the following `test.py` file

```
import typing

class Left(object):
    def __mul__(self, other: typing.Any) -> int:
        return 0


l = Left()

def test_str(other: str) -> None:
    if typing.TYPE_CHECKING:
        reveal_type(l * other)
        # note: Revealed type is "builtins.int"
        # OK
        reveal_type(l.__mul__(other))
        # note: Revealed type is "builtins.int"
        # OK

    print(l * other)
    print(l.__mul__(other))

test_str("a")

def test_any(other: typing.Any) -> None:
    if typing.TYPE_CHECKING:
        reveal_type(l * other)
        # note: Revealed type is "Any"
        # I WAS EXPECTING int, NOT Any
        reveal_type(l.__mul__(other))
        # note: Revealed type is "builtins.int"
        # OK

    print(l * other)
    print(l.__mul__(other))

test_any("a")
```

Run `python test.py`, and confirm that it prints `0` four times, i.e. the `__mul__` operator of the `Left` operand is used.

**Expected Behavior**

Running `mypy test.py`, I would expect to see that the revealed types are `int` in each of the four notes.

**Actual Behavior**

Running `mypy test.py`, the third revealed type is Any, instead of int.

**Your Environment**

- Mypy version used: `mypy 0.971 (compiled: yes)`
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: `Python 3.10.6`
- Operating system and version: `Debian GNU/Linux bookworm/sid`

**Note**
I am getting this behavior also with other arithmetic operators (e.g., I've also tried a similar test with `__add__`).

**Comment by TeamSpen210** [comment]
Mypy is actually correct here. There's a special case for binary operators: if the right hand side is a subclass of the left hand side, its method will be called first to give it an opportunity to override the superclass. If you add `@typing.final`, potentially it would be valid then. But [Mypy doesn't check that](https://github.com/python/mypy/blob/b29051c8979ae83835204f7813e4307b05d73156/mypy/checkexpr.py#L3140)...

**Comment by francesco-ballarin** [comment]
Thanks!

> if the right hand side is a subclass of the left hand side

To be more concrete: I am not interested in that case in my application. The left hand side is a class in my library, the right hand side is a class (which I do not extend) in an external untyped (hence the `Any`) library. 

> But Mypy doesn't check that

Would there be another workaround? I'd rather not have to replace `*` with `__mul__` in the end user code, and neither having to add a `# type: ignore` every time I use `*`.

**Comment by hauntsaninja** [comment]
If it's valid for your use case, changing `Any` to `object` will fix.

According to your bug report, you're using mypy without any options, so you shouldn't be having to `type ignore` anything because of some extra `Any`. Perhaps you're using `--strict` and getting complaints from `--warn-return-any`? If so, consider using `--no-warn-return-any`

**Comment by hauntsaninja** [comment]
Yeah, I think your options are:
- Use `--strict --no-warn-return-any` to tell the typechecker to trust that all the `Any`s you're returning are of the types your signatures claim they are
- Use `--strict` and then manually tell the type checker wherever you return an `Any` that what you are returning is the correct type using `assert isinstance` or `# type: ignore[no-any-return]`

**Comment by francesco-ballarin** [comment]
Thanks @hauntsaninja , I've used the second approach you proposed.
