### ISSUE TITLE
no error when not awaiting `Future`

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#13589]
```py
from typing import Coroutine
from asyncio import Future

a: Future[int]
b: Coroutine[None, None, int]

a # no error
b # error
```
[playground](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-context%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Clocal-partial-types%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=c8774f5979e8b70b0d35101537199c7e)

**Comment by AlexWaygood** [comment]
If you run mypy with `--show-error-codes --enable-error-code=unused-awaitable`, you get the following output when running mypy on your snippet:

```
test.py:7: error: Value of type "Future[int]" must be used  [unused-awaitable]
test.py:7: note: Are you missing an await?
test.py:8: error: Value of type "Coroutine[None, None, int]" must be used  [unused-coroutine]
test.py:8: note: Are you missing an await?
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by DetachHead** [comment]
thanks. though i find it strange that only one of these error codes is enabled by default
