### ISSUE TITLE
Normalize paths before checking 

### ISSUE THREAD

**Issue by mgilson** [python/mypy#13587]
**Bug Report**

I'm running into some issues in some scripting where we have a local repository of stubs that generally sits in the repository at some path relative to the python code in the project.  Our linting scripts might look something like:

```sh
MYPYPATH=${PWD}/../stubs
```

This seems to be causing some issues in https://github.com/python/mypy/blob/3c7e21600874948fb15e6ba2370d3f44a81b9378/mypy/modulefinder.py#L816-L842

Would it be problematic to normalize the paths before doing the `p.startswith(...)` check?

**To Reproduce**

1. Find a python file that you want to check by itself.
2. change your working directory to be the same directory as the file to check
3. Run something like `MYPYPATH=${PWD}/../any_sibling_directory mypy file_to_check.py`  (edit as necessary if you don't use `bash` :)

**Expected Behavior**

I would expect mypy to be able to check this file without any problems.

**Actual Behavior**

mypy basically just says it won't check the file and exits (with a non-successful exit status)

**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags: reproduced with/without `--strict`
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: python3.8
- Operating system and version: Linux (ubuntu 20.04)

**Comment by hauntsaninja** [comment]
0.971 just has a bad bug, see https://github.com/python/mypy/issues/13214

I fixed this in https://github.com/python/mypy/pull/13223 but mypy didn't end up making a patch release: https://github.com/python/mypy/issues/13089#issuecomment-1193070448
