### ISSUE TITLE
Incorrect arg/type matching when unpacking type-hinted dict to call function with optional arg and **kwargs

### ISSUE THREAD

**Issue by nuztalgia** [python/mypy#13614]
**Bug Report**

Consider the following code (simplified from an actual use case), which works as intended at runtime:

```py
def f(s: str = "", **kwargs: int) -> None:
    pass

d: dict[str, int] = {}

f(**d)
```

**Expected Behavior**

No errors - the types match up, and the first parameter isn't required.

**Actual Behavior**

```
main.py:6: error: Argument 1 to "f" has incompatible type "**Dict[str, int]"; expected "str"
Found 1 error in 1 file (checked 1 source file)
```

Any one of these code changes will "fix" the above error, even though they all seem less correct:
- Changing the type hint for `d` to `dict[str, Any]`
- Changing the type hint for `d` to `dict[str, str]` (this was very unexpected)
- Getting rid of `d` entirely and changing the function call to `f(**{})`
- Removing the first parameter from the function signature (not viable in practice)

**Your Environment**

- Mypy version used: **0.971**
- Mypy command-line flags: None
- Mypy configuration options: None
- Python version used: **3.10**
- Operating system and version: Windows 10
- **Reproducible on [Mypy Playground](https://mypy-play.net/?mypy=0.971&python=3.10&gist=8019159029955fc81c8357fc1c48edc1).**

**Comment by JelleZijlstra** [comment]
Mypy is correct here. A `dict[str, int]` could have a key `"s"`, and its value (an int) would be passed to your parameter that expects a str.
