### ISSUE TITLE
Cannot deduce type of generic attributes within match statements

### ISSUE THREAD

**Issue by ariebovenberg** [python/mypy#13612]
**Bug Report**

It seems like `mypy` is having trouble deducing the type of generic attributes in `match` statements. If `__match_args__` contains a generic attribute, this attribute becomes `Any` after `case` matching.

**To Reproduce**

Run `mypy` on the code below

```python
from typing import Generic, TypeVar

T = TypeVar("T")


class A(Generic[T]):
    x: T

    __match_args__ = ("x",)

    def __init__(self, x: T):
        self.x = x


a = A("foo")
reveal_type(a)  # A[str] (correct)
reveal_type(a.x)  # builtins.str (correct)

match a:
    case A(b):
        reveal_type(b)  # Any (incorrect! Should be builtins.str)
```

**Expected Behavior**

The total output should be:

```
Revealed type is "mycode.A[builtins.str]"
Revealed type is "builtins.str"
Revealed type is "builtins.str"
```

**Actual Behavior**

the last line doesn't reveal `builtins.str`

```
Revealed type is "mycode.A[builtins.str]"
Revealed type is "builtins.str"
Revealed type is "Any"
```

**Your Environment**

- Mypy version used: 0.971 (also occurs on `master` branch)
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.5
- Operating system and version: MacOS 12.5.1

**What I've found so far**

- If we declare `A` as a minimal dataclass the attribute _is_ correctly inferred! 

  ```python
  @dataclass
  class A(Generic[T]):
      x: T
  ```

- If the `case` explicitly matches on the attribute name, it also correctly infers the type:
  
  ```python
  match a:
      case A(x=b):
          reveal_type(b)  # builtins.str (correct)
  ```

- Issue #12364 may be related
- PEP626 mentions [generics are special](https://peps.python.org/pep-0622/#type-erasure), but the examples don't appear relevant to this case.

**Comment by sobolevn** [comment]
Hi, @ariebovenberg 👋 

Confession: I've never used a match statement in Python.
But, I will try to take a look (with no promises)

**Comment by sobolevn** [comment]
@ariebovenberg reviews are welcome (at least of tests!) :)
