### ISSUE TITLE
mypy imports python3 package, while running with --py2 flag

### ISSUE THREAD

**Issue by TaekedeHaan** [python/mypy#13628]
**Bug Report**

I am trying to type check python2 code by running mypy with python3.8. However, it seems that it checks python3 libraries instead of python2. Running mypy with python3.6 does work.

**To Reproduce**
script test.py:
```
#!/usr/bin/env python2
from packaging import version
version.parse(("0"))
```
**Expected Behavior**
`python3.6 -m mypy --py2 test.py` returns:
```
test.py:2: error: Cannot find implementation or library stub for module named "packaging"
test.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```
This error is as expected. 
**Actual Behavior**

`python3.8 -m mypy --py2 test.py` returns 
```
/home/taeke/.local/lib/python3.8/site-packages/packaging/version.py:42: error: invalid syntax
Found 1 error in 1 file (errors prevented further checking)
```
Why is it importing from python3.8?

**Your Environment**
Ubuntu 18.04.6
 - `python3.8 --version`: Python 3.8.0
 - `python3.6 --version`: Python 3.6.9
 - `python2.7 --version`: Python 2.7.17
 - `python3.8 -m mypy --version`: mypy 0.971 (compiled: yes)
 - `python3.6 -m mypy --version`: mypy 0.942

**Comment by sobolevn** [comment]
Hi, @TaekedeHaan! Thanks for your submission.

We've dropped support of python2 in the `main` branch (and `typeshed` also did).
I am almost certain that this won't be fixed in older versions as well.

If other maintainers have time / need to fix this, please reopen.
In my opinion it would be quite hard / time consuming for a feature that is no longer supported.

**Comment by TaekedeHaan** [comment]
Okay thanks. I was not aware of this, but it makes sense. It might be a good idea to add something about this to the documentation [https://mypy.readthedocs.io/en/stable/python2.html](https://mypy.readthedocs.io/en/stable/python2.html)

**Comment by sobolevn** [comment]
New docs are here: https://mypy.readthedocs.io/en/latest/
It does not have `python2.html` at all :(
