### ISSUE TITLE
Allow empty directory

### ISSUE THREAD

**Issue by mraarone** [python/mypy#13634]
Requesting feature to add command line option for allowing empty directory or for the comment to be addressed in the reference, below, to use "expand_dir" instead of "create_source_list":

https://github.com/python/mypy/blob/520b83e40efb2400e3679ec97bd620c3c63560c0/mypy/test/testfinegrained.py#L286

Thank you!
Aaron

**Comment by sobolevn** [comment]
Do you mean running `mypy` on an empty directory?

Like:

```bash
mkdir ./temp
mypy ./temp
```

?

**Comment by erictraut** [comment]
@mraarone, could you answer the question above? It's not clear what functionality you're requesting.
