### ISSUE TITLE
Running mypy and managing imports and incompatible stubs

### ISSUE THREAD

**Issue by vmsh0** [python/mypy#13633]
**Documentation**

From the [Library stubs not installed](https://mypy.readthedocs.io/en/stable/running_mypy.html#library-stubs-not-installed) section of Running mypy and managing imports:

> You can resolve the issue by running the suggested pip command or commands. Alternatively, you can use [--install-types](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-install-types) to install all known missing stubs [...]

This is incomplete, as it only addresses the issue of missing stubs.

In my case, the issue is that the stubs are not compatible with Python 3.10. I'm confirming this by trying to use Python 3.8, in which case the error disappears and type checking works.

However, I have no idea about what any of that means or entails, as, to the best of my documentation-searching abilities, it's not documented. What makes stubs to be incompatible with a particular Python version? I think that should be documented and referenced in the aforementioned section.

(Stubs not installed and incompatible stubs should also probably separated into two different error states, as for incompatile stubs the advice in the notes is irrelevant and confusing, but this is probably beyond this bug report)

**Comment by JelleZijlstra** [comment]
What makes the stubs incompatible? What issues are you seeing? Generally stubs should work with any Python 3 version.

**Comment by vmsh0** [comment]
That's also my thinking, that's what's so confusing about that error message.

Quick repro steps (assumes you're running Python 3.10):
```
mkdir empty-dir && cd empty-dir
python -m venv venv
source venv/bin/activate
pip install requests types-requests
echo "import requests" > app.py
mypy app.py
```

**Comment by hauntsaninja** [comment]
You need to install types-requests in the environment that mypy is installed in, or point mypy to the correct environment using e.g. `--python-executable venv/bin/python`

**Comment by JelleZijlstra** [comment]
@hauntsaninja is right. But maybe we should remove the "(or incompatible with Python 3.10)" part from the error; I'm not really sure when that would be helpful.

**Comment by vmsh0** [comment]
Thank you for your clarifications. I don't agree that the issue should be closed, as this still looks to me like a documentation issue. I will give some additional context to clarify my point of view.

I see how my Python 3.8 testing methodology was flawed from @hauntsaninja's comment (and thus why it worked when I tested it with Python 3.8). However:

1) I agree with @JelleZijlstra's remark that it would be useful to clarify that error message to reflect the actual potential error states it represents
2) Since I was 100% positive I had that package in my current environment, and I had read on the documentation that's what was needed (and the note is not suggesting anything different), it seemed pointless to me to run `mypy --install-types app.py` - so I didn't. The link contained in the note wasn't even about my specific issue, so it didn't help convincing me to do that.

[Here](https://mypy.readthedocs.io/en/stable/installed_packages.html), which is what I was referring to in point (2), the following is mentioned:

> Typically mypy will automatically find and use installed packages that support type checking or provide stubs. This requires that you install the packages in the Python environment that you use to run mypy.

The way I understand this, and I don't think it's unreasonable, is: you need the stubs in the venv where you're running mypy from. A better phrasing, in my opinion, would be something like:

> Typically mypy will automatically find and use installed packages that support type checking or provide stubs. This requires that you install the packages in the Python environment where you have installed mypy (which might be different from the current Python environment)

**Comment by hauntsaninja** [comment]
Here you go https://github.com/python/mypy/pull/13636
