### ISSUE TITLE
Fails with `--silent-imports`; passes without it

### ISSUE THREAD

**Issue by bdarnell** [python/mypy#1364]
```
$ mypy -f tornado/ioloop.py
$ mypy -f -s tornado/ioloop.py
tornado/ioloop.py:48: error: Module has no attribute 'set_close_exec'
tornado/ioloop.py:48: error: Module has no attribute 'Waker'
```

In Tornado, I prefer to use inline annotations instead of stub files, but occasionally I use a stub for something that would be too tricky to mark up inline. In [this case](https://github.com/tornadoweb/tornado/blob/b6998247702a960f0c73004a6b5f8ae775607c03/tornado/platform/auto.pyi), a stub file imports and reexports definitions from a python file. With `-s`, python imports are silently ignored.

My suggestion would be to solve this by making `-s` apply only to imports that appear in `.py` files; imports in `.pyi` files would always be processed regardless of their target.

(Versions tested: tornadoweb/tornado@b69982477, python/mypy@ac193cf9dd, python/typeshed@68306484a)

**Comment by gvanrossum** [comment]
Note that the feature requested here and implemented in #1372 was rolled back (over a year later) in #3727.
