### ISSUE TITLE
TypeVar not compatible with object

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#13689]
In order to keep code type safe and declare that my code will work with any type, I have used `object`. But, when trying to use a `TypeVar` in another part of the code, it complains that it is incompatible with `object`.

My code looks roughly like:
```
jobs: Set[Job[object]] = set()

async def spawn(self, coro: Coroutine[object, object, _T]) -> Job[_T]:
    jobs.add(job)
```

I'm getting:
```
error: Argument 1 to "add" of "set" has incompatible type "Job[_T]"; expected "Job[object]"  [arg-type]
```

I don't think it's an invariance problem..

**Comment by JelleZijlstra** [comment]
Your code sample is incomplete, but that does look like an invariance problem. If `Job` is invariant in its type parameter, a `Job[_T]` is not compatible with a `Job[object]`.

**Comment by Dreamsorcerer** [comment]
One day I'll get my head round covariance properly. :P

After making the TypeVar covariant, I still have one more error in:
```
_T = TypeVar("_T", covariant=True)
task: asyncio.Task[_T]
_failed_tasks: asyncio.Queue[Optional[asyncio.Task[object]]] = asyncio.Queue()
_failed_tasks.put_nowait(task)  #  Argument 1 to "put_nowait" of "Queue" has incompatible type "Task[_T]"; expected "Optional[Task[object]]"  [arg-type]
```

That seems pretty much the same to me as the previous problem. I'll have the real code up in a PR in a couple of days, if it's useful to look at.

**Comment by JelleZijlstra** [comment]
The variance you set there doesn't do anything. What matters is how Task is declared in the stubs, and the TypeVar is invariant there: https://github.com/python/typeshed/blob/6ca80d340ef16714e61284df8338dac91479aa79/stdlib/asyncio/tasks.pyi#L268

**Comment by Dreamsorcerer** [comment]
OK, is that correct though?

I'm looking at the list example at: https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generics
But, I'm not seeing a reason that `Task` would need to be invariant. It's not a mutable container, and I can't think of anything else that would break it.

**Comment by Dreamsorcerer** [comment]
https://github.com/python/typeshed/pull/8781

**Comment by hauntsaninja** [comment]
Hmm asyncio.Future is mutable, if you made it covariant set_result would be unsound
