### ISSUE TITLE
error: Unsupported left operand type for >= ("object")

### ISSUE THREAD

**Issue by sgonzalezgap** [python/mypy#13707]
Having the an issue to compare two datetime objects, the error:

Just for a quick example:
```
fmt: str = '%Y-%m-%d'

dt1 = datetime.strptime(date_string1, fmt)
dt2 = datetime.strptime(date_string2, fmt)

if dt1 > dt2:
    print("ok")
```
No matter which dates are

**Comment by AlexWaygood** [comment]
I can't reproduce: https://mypy-play.net/?mypy=latest&python=3.10&gist=4c81d377fab596fbeb9180650649bf82. Happy to reopen if you can post a reproducible example :)

**Comment by sgonzalezgap** [comment]
I found a solution explicit using the type of object:

The format date function takes a string with format '%Y-%m-%d' and convert it to a datetime object with utc timezone.

the format_full_date function takes a isoformat and convert it in the same way.

So after the conversion explicit the type of object that I was receiving, and that allows to use the logical operators.
 
```
    args_start_: datetime = _format_date(args_start)
    args_end_: datetime = _format_date(args_end)
    term_start_: datetime = _format_full_date(term_start)
    term_end_: datetime = _format_full_date(term_end)

    if (term_start_ >= args_start_) and (term_end_ <= args_end_):
        return True
```
