### ISSUE TITLE
dict[Literal["a"], Any] is not a subclass of dict[str, Any]

### ISSUE THREAD

**Issue by quodlibetor** [python/mypy#13708]
**Bug Report**

I would expect the following code to type check correctly, since `Literal["a"]` is in fact a specification of `str`:

```python
from typing import Any, Literal
def takes_dict(arg: dict[str, Any]) -> None:
    pass
is_literal: dict[Literal["a"], Any] = {"a": 1}

takes_dict(is_literal)
```

But I get an error:

```console
$ mypy ./ex.py
ex.py:6: error: Argument 1 to "takes_dict" has incompatible type "Dict[Literal['a'], Any]"; expected "Dict[str, Any]"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: `mypy 0.971 (compiled: yes)`
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.3

**Comment by AlexWaygood** [comment]
This is expected behaviour due to the fact that `dict` is invariant. Please see https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance and https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generics

**Comment by hauntsaninja** [comment]
dict (and maybe more surprisingly, Mapping) are invariant in key type.

**Comment by quodlibetor** [comment]
Ah thanks for that, that is surprising.

For folks who come across this the solution is to specify a covariant typevar, this works:

```python
from typing import Any, Literal, TypeVar

T = TypeVar("T", bound=str, covariant=True)

def takes_dict(arg: dict[T, Any]) -> None:
    pass

is_literal: dict[Literal["a"], Any] = {"a": 1}

takes_dict(is_literal)
```

**Comment by hauntsaninja** [comment]
That is a solution, but one with potential for confusion. I'd remove the `covariant=True` from there (and it will still "work"). You can't change the variance of dict. Also you may run into issues inside `takes_dict`, depending on what you want it to do.

The solution I recommend is using your own Protocol, like so https://github.com/python/typeshed/blob/66751e2ebfed2540715426b3d6b2ffb8c8e16b57/stdlib/_typeshed/__init__.pyi#L121

Finally, Literals as a key type in a dict is pretty suspicious and smells like you'd be better served by a TypedDict

**Comment by quodlibetor** [comment]
> Finally, Literals as a key type in a dict is pretty suspicious and smells like you'd be better served by a TypedDict

Right, in my case I'm actually passing the an auto-generated API response into a method that just expects a dict that has string keys. I don't actually have control over it.

> You can't change the variance of dict.

hmm, yeah this is a good point, fair enough.
