### ISSUE TITLE
Mypy strict mode does not trust imported library type hints no matter what

### ISSUE THREAD

**Issue by EldarSehayekZenity** [python/mypy#13712]
**Bug Report**

Mypy strict mode applies to imported packages as well without ability to make it trust the type hints provided by the library.
I encountered it with pydantic library function parse_obj_as which has a generic type hint. I emphasize - this is not an issue with pydantic, this is an issue with how mypy treats imported modules type hints, pydantic is just a good example where type hints don't reflect what mypy analyzes about the imported code.

**To Reproduce**

1. Install latest pydantic
2. Write the following code:

```
from pydantic import AnyHttpUrl, parse_obj_as

def get_url() -> AnyHttpUrl:
    return parse_obj_as(AnyHttpUrl, "https://contoso.com")
```

3. Run mypy with strict=True

**Expected Behavior**

Mypy should provide some way to instruct it to respect the type hints of the imported module. `parse_obj_as` has a type hint to return the type `T` which is the first argument. When inspecting the function's implementation, it's true it's not type hinted strictly and mypy infers its return type as Any and not as T. However I expect to have some way to make mypy trust the library's type hints and apply strictness only to my code.

**Actual Behavior**

Mypy emits error:

error: Returning Any from function declared to return "AnyHttpUrl"

I use pyproject.toml and I tried the following with overrides, nothing prevented the error:

[[tool.mypy.overrides]]
module = "pydantic"
ignore_errors = true

[[tool.mypy.overrides]]
module = "pydantic"
strict = false

[[tool.mypy.overrides]]
module = "pydantic"
following_imports = "silent"

If I instruct mypy to "skip" the "pydantic" import then no errors, but mypy treats what's returned from `parse_obj_as` as having type `Any` and I want it to be treated as having the correct type, e.g. in above example the correct type is `AnyHttpUrl`.

**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files):

follow_imports = "normal"
ignore_errors = false
implicit_reexport = false
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
disallow_untyped_defs = true
check_untyped_defs = true
allow_redefinition = false
local_partial_types = true
strict_optional = true
strict_equality = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
no_implicit_optional = true
strict = true

- Python version used: 3.10.4
- Operating system and version: Windows 11

**Comment by hauntsaninja** [comment]
Interesting, looks like it's because pydantic puts a `no_type_check` on `__new__`.
https://github.com/pydantic/pydantic/blob/60cad30b2cd1dc3aa1858ddf907666e6f3429182/pydantic/networks.py#L184

This decorator means that that function should be treated as not having type hints, so mypy treats `__new__` as `Any`. I'd ask pydantic to change that and use `# type: ignore` to circumvent whatever they were trying to circumvent (or possibly to make it completely invisible to mypy using `if TYPE_CHECKING`).

**Comment by EldarSehayekZenity** [comment]
@hauntsaninja May I ask why you ignored my statement that this pydantic is only serving here as an example?
This can happen with any module whatsoever. Configuring mypy checks to be strict on my code base shouldn't make it so it has to be the case for imported packages. Pyright strict mode knows to respect imported packages type hints, why shouldn't mypy support that as well?

**Comment by hauntsaninja** [comment]
No it's not a general problem. It's a specific problem with a specific type hint in pydantic, which I link to above.

**Comment by EldarSehayekZenity** [comment]
So mypy won't analyzer any other library and infer by its own its type hints instead of trusting its type hints?

**Comment by hauntsaninja** [comment]
Use --no-warn-return-any if you don't want mypy to tell you that bad type hints are causing code you expect to have types to be Any instead.

**Comment by hauntsaninja** [comment]
No, you didn't click on the link and understand the problem. mypy is listening to what pydantic is saying here and what pydantic is saying is incorrect.

**Comment by EldarSehayekZenity** [comment]
1. Specfying no-warn-return-any just for pydantic using mypy overrides didn't work, and I don't want to specify it for the entire code base.
2. I understand the problem, I just don't agree that I shouldn't be able to ask mypy to trust type hints of an imported library. When a generic function from an imported library says it returns T, I think mypy should support a flag to trust that. It's fine if you disagree, please don't assume I didn't click on the link and do not patronize telling me I don't understand, I did click on the link and did understand.
