### ISSUE TITLE
0.981 `@classmethod` and `@property` can no longer be chained

### ISSUE THREAD

**Issue by bzoracler** [python/mypy#13746]
[Class properties were introduced in Python 3.9](https://docs.python.org/3/howto/descriptor.html#class-methods), and used to be unanalysed in 0.971:

```python
# mypy 0.971
class A:
    @property
    @classmethod
    def bad_class_property(cls) -> int:  # No mypy error
        return 8
    @classmethod
    @property
    def good_class_property(cls) -> int:  # No mypy error
        return 8
```
```python
>>> A.bad_class_property
 <property at 0x...>
>>> A.good_class_property
8
```

Now, we have

```python
# mypy 0.981
class A:
    @classmethod  # Only instance methods can be decorated with @property [misc]
    @property
    def good_class_property(cls) -> int:
        return 8
```

**Comment by erictraut** [comment]
I don't know if this was related to the change in mypy 0.981, but chaining of property and classmethod has been [deprecated in Python 3.11](https://github.com/python/cpython/pull/92379). More details can be found in the [Python 3.11 release notes](https://docs.python.org/3.11/whatsnew/3.11.html), but I'll quote the relevant part here:

> Chaining classmethod descriptors (introduced in bpo-19072) is now deprecated. It can no longer be used to wrap other descriptors such as property. The core design of this feature was flawed and caused a number of downstream problems.

**Comment by hauntsaninja** [comment]
Yeah, this is from https://github.com/python/mypy/pull/13409. I don't think mypy should support property + classmethod, given that it's deprecated. But that can be discussed at https://github.com/python/mypy/issues/11619
