### ISSUE TITLE
Warn when a base class has type Any due to --silent-imports

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1374]
Sometimes, --silent-imports prevents importing a module that defines the base class for some other class. The other class then implicitly inherits from Any, and this means that many operations on the instances of that class are not type-checked at all. I just fixed (#1365) an issue where something _was_ type-checked without taking this unknown base class into account, and the result was an incorrect error. However there are also plenty of situations imaginable where this situation prevents useful type-checking from happening. So perhaps we should issue a warning in this situation (i.e. a base class being undefined due to an import being suppressed due to --silent-imports). Maybe --almost-silent could be augmented to also issue these warnings.

**Comment by ilevkivskyi** [comment]
We now have `--disallow-subclassing-any`
