### ISSUE TITLE
Possible regression in mypy 0.981: Generics don't work when TypeVar are previously used in a TypedDict

### ISSUE THREAD

**Issue by jzazo** [python/mypy#13755]
**Bug Report**

When pulling the example of Generics from the [documentation](https://mypy.readthedocs.io/en/stable/generics.html) and specifying a generic TypedDict following the [blog post](https://mypy-lang.blogspot.com/2022/09/mypy-0981-released.html), I get an error on simple Generic example.

**To Reproduce**
```python
from typing import Generic, TypeVar
from typing_extensions import TypedDict  # I am using python 3.10.4

T = TypeVar("T")
MyDict = TypedDict("MyDict", {"foo": T})

class Stack(Generic[T]):  # mypy error: Free type variable expected in Generic[...]  [misc]
    def __init__(self) -> None:
        pass
```
Commenting line 5 removes the error. Moving line 5 after the declaration of `Stack` also works.

**Expected Behavior**
That class Stack is a correct Generic and mypy should not error.

**Your Environment**
- Mypy version used: 0.981
- Python version used: 3.10.4

**Comment by AlexWaygood** [comment]
@ilevkivskyi, one for you? :)

**Comment by jzazo** [comment]
Another example that may come from the same issue. Commenting `MyDict1` declaration removes the error.

```python
from typing import Sequence, TypeVar
from typing_extensions import TypedDict

T = TypeVar("T")

MyDict1 = TypedDict("MyDict1", {"foo": Sequence[T]})
MyDict2 = TypedDict("MyDict2", {"foo": Sequence[T]})

MyDict1[int]  # ok
MyDict2[int]  # mypy(error): The type "Type[MyDict2]" is not generic and not indexable  [misc]
```

**Comment by hauntsaninja** [comment]
(This isn't a regression, since support for generic TypedDicts is new in mypy 0.981)

I don't think it's a bug either. You'll need to use the class-based syntax to bind the type variable. For example:
```
from typing import Generic, TypeVar
from typing_extensions import TypedDict  # I am using python 3.10.4

T = TypeVar("T")
class MyDict(TypedDict, Generic[T]):
    foo: T

class Stack(Generic[T]):  # mypy error: Free type variable expected in Generic[...]  [misc]
    def __init__(self) -> None:
        pass
```

**Comment by ilevkivskyi** [comment]
This is not really a regression, as previously you would still get an error (in a different place). It is however indeed a bug, you should be able to reuse the type variable. Unless I am missing something, should be a simple fix.

**Comment by ilevkivskyi** [comment]
Oh, actually both examples work correctly on master. It looks like @Michael0x2a already added the missing TypeVar scope frame in https://github.com/python/mypy/pull/13678 (and also fixed a docstring for me, thank you!)

**Comment by ilevkivskyi** [comment]
(btw it was one of rare cases where `git blame` was used as `git gratitude`)
