### ISSUE TITLE
A function returning TypeVar should receive at least one argument containing the same Typevar

### ISSUE THREAD

**Issue by Xophmeister** [python/mypy#13765]
**Documentation**

mypy recently (first noticed today: 2022-09-29) started failing my code with the following:

> A function returning TypeVar should receive at least one argument containing the same Typevar

I did a cursory search and found no reference to this rule. Personally, I find it unnecessarily restrictive. For example, an object method could return that TypeVar without having any arguments; i.e., just relying on the object's state. Nonetheless, I assume it was added for good reason. Can that reason please be elaborated on somewhere in the documentation and/or mypy's output?

**Comment by hauntsaninja** [comment]
mypy won't complain about the situation you suggested (method of generic class being different from a function):
```
from typing import *
T = TypeVar("T")
class X(Generic[T]):
    def f(self) -> T: ...
```

The reason for the lint is that a single TypeVar (in all the cases that mypy warns about) will not do anything.
Generics and TypeVars are parts of the typing system users find complicated, so warning when a type hint isn't doing anything helps such users detect misuse.

**Comment by aspacca** [comment]
```
from typing import Generic, TypeVar

T = TypeVar("T")


class StaticFactoryClassWithError:
    @staticmethod
    def create() -> T:
        ...


class StaticFactoryClassWithoutError(Generic[T]):
    @staticmethod
    def create() -> T:
        ...
```

I have the same failure reason with the above code, for `StaticFactoryClassWithError.create()` but not for `StaticFactoryClassWithoutError.create()`.

to me being `create()` a static method makes sense to not have any argument containing the same TypeVar


```
class StaticFactoryClassWithoutError:
    @staticmethod
    def create(t: T) -> T:
        ...

```
this does not fail as well

you can see the real code at https://github.com/elastic/elastic-serverless-forwarder/blob/main/shippers/factory.py

**Comment by hauntsaninja** [comment]
```
class StaticFactoryClassWithError:
    @staticmethod
    def create() -> T:
```
doesn't do anything.

In your real code, you want to just return ProtocolShipper, not ProtocolShipperType. I added a suggestion for that which didn't quite make it into release 0.980: https://github.com/python/mypy/pull/13730

If someone has a concrete suggestion on how to improve the docs or error messages, open a PR.

**Comment by aspacca** [comment]
> In your real code, you want to just return ProtocolShipper, not ProtocolShipperType

I've hinted that just after sending my comment. but thanks for the quick reply :)

**Comment by aspacca** [comment]
Indeed I remember now why I used the `ProtocolShipperType`

I have somewhere else: 
```
shipper: ElasticsearchShipper = ShipperFactory.create_from_output()
```

that using `ProtocolShipper` instead produces the following error:
```
handlers/aws/utils.py:165: error: Incompatible types in assignment (expression has type "ProtocolShipper", variable has type "ElasticsearchShipper")
```

**Comment by JelleZijlstra** [comment]
@alelom you can achieve what you want with overloads. If the function simply returns `T`, there is no way for the type checker to know that `someBool` being True leads to a particular return type.

**Comment by evbo** [comment]
@hauntsaninja please reopen this issue. There's no way to support the most basic generic function:

```python
def fetch_whatever_depending_on_type_specified_by_caller[T]() -> T:
    return requests.get(url=os.getenv("X")).json()
```

**Comment by hauntsaninja** [comment]
mypy is right to flag that annotation, it literally doesn't mean anything. maybe read the docs before you tag people?

**Comment by evbo** [comment]
I've read everything contained in this issue and see no links to docs. I still don't get what you mean by it doesn't mean anything, especially now that python 3.13 supports upper bounds on generic types.

I get that in older versions of python, it was the same as just not typing the return value though.

I suggest leaving this issue open so that the mypy error is better documented, and supports upperbound checking, which is definitely meaning something.

**Comment by evbo** [comment]
And I'm sorry if the tag was disruptive. My understanding with closed issues is only a maintainer can reopen, which would not happen otherwise given how stale this issue is.

**Comment by evbo** [comment]
the more I read about mypy the more it seems just use `Any` when generics go too far. I guess this is just another one of those situations...
