### ISSUE TITLE
Undesirable import following behavior

### ISSUE THREAD

**Issue by huguesb** [python/mypy#13773]
I am working with a large legacy codebase whose layout is roughly as follows:

```
<git root>
|- foo
|    |- <company>
|    |    |- __init__.py
|    |    \- foo
|    |         |- ...
|    |- alembic
|    |    |- env.py
|    |    \- versions
|    |        |- ...
|    |- tests
|    |    |-...
|    |- ...
|- bar
|    |- <company>
|    |    |- __init__.py
|    |    \- bar
|    |         |- ...
|    |- alembic
|    |    |- env.py
|    |    \- versions
|    |        |- ...
|    |- tests
|    |    |-...
|    |- ...
|- baz
|    |- <company>
|    |    |- __init__.py
|    |    \- baz
|    |         |- ...
|    |- alembic
|    |    |- env.py
|    |    \- versions
|    |        |- ...
|    |- tests
|    |    |-...
|    |- ...
...
```

This peculiar layout has caused us performance issues in the past, that were addressed with `--fast-module-lookup`.

However, I have now found another issue with that I'm not quite sure how to deal with.

To ensure mypy can reliably follow import even when typechecking a small subset of the codebase, we add every root package (i.e. `foo`, `bar`, and `baz` in the example above) to `MYPY_PATH`. This gets the job done but causes an annoying issue wherein mypy will allow any of the `alembic` folders to be used to resolve an import to the `alembic` 3rd-party library if it cannot be found elsewhere on the search paths.

Right now, the only hack I have found to prevent mypy from following undesirable imports is to use `--no-namespace-packages` and have a very aggressive linter that ensure the presence of `__init__.py` in all paths we want to be found by mypy, and the absence of any `__init__.py` in files we want ignored by mypy.

This is fairly constraining and brittle though. I would much rather have a way to pass `foo/<company>` into `MYPY_PATH` and have mypy do the right thing (resolve imports of the form `<company>.foo...` but not follow imports anywhere else in the codebase).

Is there any way to get mypy to robustly do what I want without an extensive codebase re-org?

**Comment by hauntsaninja** [comment]
I don't see any clever tricks that make it work without changing your codebase. If you can change your codebase, the smallest change is probably renaming your `alembic` folders to something that is not a valid identifier.

One vaguely related feature request we sometimes get is concerning `--exclude`. Currently `--exclude` only applies to recursive file discovery and doesn't affect import following. This can be surprising to users. It might not be the worst idea to have `--exclude` also imply follow_imports=skip for excluded files. Such a thing could conceivably be useful to you here. (This would also probably be a pretty fiddly feature request to get right)

**Comment by huguesb** [comment]
For posterity:

I worked around this issue by running mypy on a synthetic "shadow" tree, generated on-demand by a custom runner script.

Given the above tree, the synthetic tree looks like:

```
<git-root>
| - .shadow/
      |- <company>
           |- foo  -> <git-root>/foo/<company>/foo
           |- bar  -> <git-root>/bar/<company>/bar
           |- baz  -> <git-root>/baz/<company>/baz
   
```

in other words, it provides a maximally mypy-friendly view of the codebase, where all packages are merged into a single tree of import paths, with leaf nodes pointing to the actual code wherever it is located in the git repo.

This requires some care with munging the error paths in the output, as well as managing potential interactions between concurrent runs, but it is very quick to create and robustly addresses unwanted import following, As a side-benefit, it significantly speeds up import following by going from N search paths to 1!
