### ISSUE TITLE
int | float ?= float inconsistency in Callable's return value ignores overlapping overloads

### ISSUE THREAD

**Issue by twoertwein** [python/mypy#13775]
**Bug Report**

```python
from typing import overload, Union, Callable, Any

Scalar = Union[int, float, complex]  # shows the error
# Scalar = complex  # hides the error

class A: ...
class B: ...

@overload
def apply(self, func: Callable[[A], Scalar]) -> B: ...

# error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [misc]
@overload
def apply(self, func: Callable[[Any], float]) -> A: ...
```

**Expected Behavior**

In both cases the overloads should be overlapping.

**Your Environment**

- Mypy version used: 0.971 and 0.981
- Python version used: 3.10

**Comment by ethanhs** [comment]
I'm not sure I agree about the expected behavior, if you pass a function `Callable[[A], complex]` to apply, if `Scalar = complex` then only the first overload can apply, in other words they are not overlapping.

**Comment by twoertwein** [comment]
> I'm not sure I agree about the expected behavior, if you pass a function `Callable[[A], complex]` to apply, if `Scalar = complex` then only the first overload can apply, in other words they are not overlapping.

Thank you - I agree, when changing `Scalar = float` it also errors.
