### ISSUE TITLE
follow_imports now working from module specific configuration

### ISSUE THREAD

**Issue by dpinol** [python/mypy#13796]
**Bug Report**

**To Reproduce**

* Create a file utils/file.py with contents "import aenum"
* `pip install aenum`
* Create a mypy.ini with these contents:
```
[mypy-utils.*]
follow_imports = skip
```
* `mypy --config=mypy.ini utils/file.py`

**Expected Behavior**
No error, since I don't want mypy to follow imports from my utils package

**Actual Behavior**
```
utils/file.py:2: error: Skipping analyzing "aenum": module is installed, but missing library stubs or py.typed marker
```
**Your Environment**

- Mypy version used: mypy 0.981 (compiled: yes)
- Mypy command-line flags: mypy --config=mypy.ini utils/file.py`
- Mypy configuration options from `mypy.ini`:
```
[mypy-utils.*]
follow_imports = skip
```
- Python version used: Python 3.10.4

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/stable/config_file.html#confval-follow_imports

> If this option is used in a per-module section, the module name should match the name of the imported module, not the module containing the import statement.

**Comment by hauntsaninja** [comment]
Don't think there's a good way to do what you want to do (although you could easily globally skip aenum using ^^ per module follow_imports)

**Comment by dpinol** [comment]
@hauntsaninja  thanks for your quick response!
I want to disable all errors from a module, but I see no way to do it with mypy. It's a bit confusing that I cannot do it with exclude, follow_imports or ignore_missing_imports :disappointed:

**Comment by hauntsaninja** [comment]
Based on your description I'm not quite sure what you want, but I'm guessing it's probably:
```
[mypy-aenum.*]
follow_imports = skip
```
