### ISSUE TITLE
Inner class attribute with type the inner class is an undefined name in pyi file

### ISSUE THREAD

**Issue by JonathanPlasse** [python/mypy#13799]
**Bug Report**

Using the inner class as a type for one of its attributes results in an undefined name in pyi file.

**To Reproduce**

```python
class A:
    class B:
        a: B
```

**Expected Behavior**

The attribute `B.a` should have the type `B` and not result in an undefined name.

**Actual Behavior**

`error: Name "B" is not defined`

**Your Environment**

- My version used: 0.971
- Mypy command-line flags:
- My configuration options from `mypy.ini` (and other config files):
```
strict = true
show_column_numbers = true
```
- Python version used: 3.10.6 and 3.8.2

**Comment by erictraut** [comment]
The symbol `B` is undefined at the location where you are using it. It is not visible within the inner scope of class `B`. Mypy is correct for generating an error here. If you want to use class `B` as an annotation here, you need to refer to it as `A.B`.

**Comment by JonathanPlasse** [comment]
Thanks
