### ISSUE TITLE
100% single assignment variables

### ISSUE THREAD

**Issue by begoon** [python/mypy#13798]
**Feature**

An optional checker to enforce the single assignment rule to general purpose free variables 

**Pitch**

Currently mypy has a checker blocking reuse of variables if the type of the variable changes. It would be even more useful if it will block any variable reassignment. 

This checker is quite opinionated, that's why it's proposed to be always optional.

**Comment by hauntsaninja** [comment]
You can use Final for this https://peps.python.org/pep-0591/
