### ISSUE TITLE
Hashable and None have overlapping type in mypy >= 0.981

### ISSUE THREAD

**Issue by headtr1ck** [python/mypy#13805]
**Bug Report**

mypy 0.981 and 0.982 consider `Hashable` and `None` to be overlapping.
I know that technically it is correct, since `None` is indeed hashable, but the way that `None` is used in python for default values makes this overlap inconvenient.

I could not find any hint in the changelog that indicates that this has changed.

**To Reproduce**

```python
from typing import Hashable

@overload
def x(a: Hashable) -> Hashable: ...

@overload
def x(a: None = None) -> None: ...

def x(a: Hashable | None = None) -> Hashable | None:
    return a
```

**Expected Behavior**

Like mypy <= 0.971 no issue here.

**Actual Behavior**

> error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [misc]

**Other**

In case the new behavior is intended, is there a way to specify a "hashable but not None" type?

**Your Environment**

- Mypy version used: 0.981 (and 0.982, 0.971 to compare)
- Mypy command-line flags: /
- Mypy configuration options from `mypy.ini` (and other config files): show_error_codes = True
- Python version used: 3.9.7

**Comment by hauntsaninja** [comment]
Side effect of https://github.com/python/mypy/pull/13303.

Like you say, these overloads do overlap, and in fact you likely want to switch the order of them (and then type ignore the overlap lint, mypy will still understand what's going on).

For more type system features, maybe follow https://github.com/python/typing/issues/801. But Hashable is just a tricky thing.
