### ISSUE TITLE
Mypy was crashed if venv might be in same the root of project.

### ISSUE THREAD

**Issue by bsnresearcher** [python/mypy#13801]
**Crash Report**
Perhaps, if venv(py3.9) might be in same the root of project, mypy will crash. In pycharm 2022, Although venv was outer from project, mypy crashed.  

I investigate the clauses for reproduce of this, sometimes, mypy test was passed. So I could not understand the clauses. However, it can be reproduced.
**Traceback**

<pre>
./vpy39/bin/mypy mypy_crash_trial.py --config-file mypy.ini --show-traceback
mypy_crash_trial.py:42: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.982
Traceback (most recent call last):
  File "mypy/semanal.py", line 5915, in accept
  File "mypy/nodes.py", line 1285, in accept
  File "mypy/semanal.py", line 2484, in visit_assignment_stmt
  File "mypy/semanal.py", line 2830, in apply_dynamic_class_hook
  File "/Users/test/mypy_crash_trial/vpy39/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 128, in _dynamic_class_hook
    _add_globals(ctx)
  File "/Users/test/mypy_crash_trial/vpy39/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 273, in _add_globals
    util.add_global(ctx, "sqlalchemy.orm.attributes", "Mapped", "__sa_Mapped")
  File "/Users/test/mypy_crash_trial/vpy39/lib/python3.9/site-packages/sqlalchemy/ext/mypy/util.py", line 178, in add_global
    lookup_sym: SymbolTableNode = ctx.api.modules[module].names[
KeyError: 'Mapped'
mypy_crash_trial.py:42: : note: use --pdb to drop into pdb
</pre>

**To Reproduce**

```requirements.txt
pip
wheel 
sqlalchemy>1.4 
numpy 

sqlalchemy-stubs
sqlalchemy2-stubs
types-sqlalchemy
data-science-types 
```

```mypy.ini
[mypy]
plugins = sqlalchemy.ext.mypy.plugin, numpy.typing.mypy_plugin

disallow_untyped_defs = True
ignore_missing_imports = True
warn_return_any = True
warn_unused_configs = True
ignore_errors = True
```

```mypy_crash_trial.py
from sqlalchemy import Column, Integer

from sqlalchemy.orm.decl_api import declarative_base

Base = declarative_base()  

class LogTable(Base):
    id = Column(Integer, primary_key=True, autoincrement=True)  # Error occurred (Crash Point) 
```

1. `/usr/local/bin/python3.9 -mvenv ~/mypy_crash_trial/vpy39`
2. `cd ~/mypy_crash_trial`
3. `~/mypy_crash_trial/vpy39/bin/pip install -U -r requirements.txt`
4. `./vpy39/bin/mypy mypy_crash_trial.py --config-file mypy.ini --show-traceback`

**Your Environment**
- Mypy version used: 0.982
- Mypy command-line flags: Above.
- Mypy configuration options from `mypy.ini` (and other config files): Above.
- Python version used: 3.9.14
- Operating system and version: macOS 12.6

**Comment by hauntsaninja** [comment]
This looks like it's a bug in the SQLAlchemy mypy plugin that you're using. Issue should be reported to that project.

**Comment by bsnresearcher** [comment]
Thank you!
