### ISSUE TITLE
Nested NewType casting from super-supertype 

### ISSUE THREAD

**Issue by sharonyogev** [python/mypy#13827]
**Bug Report**

When you have a nested NewType, i.e NewType of a NewType, and we try to cast from the original type we got error of incompatible type

**To Reproduce**

```python
from typing import NewType, cast
from datetime import datetime, timezone

NaiveDatetime = NewType("NaiveDatetime", datetime)
AwareDatetime = NewType("AwareDatetime", datetime)
UTCDatetime = NewType("UTCDatetime", AwareDatetime)

dt = datetime.now(timezone.utc)
reveal_type(dt)  # Revealed type is "datetime.datetime*"
x1 = UTCDatetime(dt)  # error: Argument 1 to "UTCDatetime" has incompatible type "datetime"; expected "AwareDatetime"
reveal_type(x1)  # note: Revealed type is "__main__.UTCDatetime"
x2 = UTCDatetime(AwareDatetime(dt))
reveal_type(x2)  # note: Revealed type is "__main__.UTCDatetime"
x3 = cast(UTCDatetime, dt)
reveal_type(x3)  # note: Revealed type is "__main__.UTCDatetime"

Negative = NewType("Negative", int)
NonNegative = NewType("NonNegative", int)
Positive = NewType("Positive", NonNegative)

y1 = Positive(3)  # error: Argument 1 to "Positive" has incompatible type "int"; expected "NonNegative"
reveal_type(y1)  # note: Revealed type is "__main__.Positive"
y2 = Positive(NonNegative(3))
reveal_type(y2)  # note: Revealed type is "__main__.Positive"
y3 = cast(Positive, 3)
reveal_type(y3)  # note: Revealed type is "__main__.Positive"
```
or in mypy-play:
https://mypy-play.net/?mypy=latest&python=3.10&gist=d27af455d5f15145ff208806af184ac8

**Expected Behavior**

We shouldn't get incompatible type error

**Actual Behavior**

Casting from the supertype of the supertype yields incompatible type error

**Your Environment**

As you can see in the link above latest mypy(=0.981) & python=3.10
But also happened with mypy=0.981 & python=3.8

**Comment by erictraut** [comment]
By my read of [PEP 484](https://peps.python.org/pep-0484/#newtype-helper-function), mypy is doing the right thing here. 

PEP 484 says that `NewType('Derived', Base)` is equivalent to:

```python
class Derived(Base):
    def __init__(self, _x: Base) -> None:
        ...
```

That means `UTCDatetime` in your example above is equivalent to:
```python
class UTCDatetime(AwareDatetime):
    def __init__(self, _x: AwareDatetime) -> None:
        ....
```

And that means you must pass the constructor for `UTCDatetime` an argument of type `AwareDatetime`, not `datetime`.

**Comment by JelleZijlstra** [comment]
I agree with @erictraut that the current behavior is correct.

**Comment by sharonyogev** [comment]
OK, got it, what do you think is the right approach here when I want to mark datetime as UTCDatetime?
This:
```
UTCDatetime(AwareDatetime(dt))
```
Or
```
cast(UTCDatetime, dt)
```

Thanks for the quick reply

**Comment by JelleZijlstra** [comment]
The former, because it's type safe. `cast()` turns off the type system and lets you do anything you want.
