### ISSUE TITLE
Typeddict.get does not respect default values

### ISSUE THREAD

**Issue by yogurtandjam** [python/mypy#13872]
**Bug Report**

types of values produced by a TypedDict.get() call do not respect provided default values.

**To Reproduce**

A simple version
```python
from typing import Dict, Optional
from typing_extensions import TypedDict

class Params(TypedDict):
    integer: Optional[int]
    string: str
    
def get_int(params: Params) -> int:
    return params.get("integer", 1)

get_int(Params(string="hi", integer=None))
```
https://gist.github.com/mypy-play/76044ab306be3e8aa3f903cd573f6c8c

An example that's closer to how i'm actually using it in my application. I've created a gist but it fails when using Unpack because
--enable-incomplete-features is not an selectable option on mypy-play
```
from typing import Dict, Optional
from typing_extensions import TypedDict, Unpack

class Params(TypedDict):
    integer: Optional[int]
    string: str
    
class SomeClass:
    def __init__(self, **kwargs: Unpack[Params]):
        self.integer = kwargs.get("integer", 1)
        self.string = kwargs["string"]
        
    def use_integer_attribute(self) -> int:
        return self.integer

class SubClass(SomeClass):
    def __init__(self, **kwargs: Unpack[Params]):
        if kwargs["string"] == "some_illegal_string":
            raise Exception
        super().__init__(**kwargs)
```
https://gist.github.com/mypy-play/17a9240300a9b0f777d77123c9bd1973

**Expected Behavior**
no errors - mypy assumes params.get will always return an int due to the default value

**Actual Behavior**
This is returned in both the simplified and actual usecases
```
main.py:9: error: Incompatible return value type (got "Optional[int]", expected "int")
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: .981
- Mypy command-line flags: --enable-incomplete-features
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]
python_version = 3.10
ignore_missing_imports=True
allow_redefinition=True
exclude = ^\.|tests|_scripts|bin|terraform
```
- Python version used:
3.10.3

**Comment by hauntsaninja** [comment]
I think mypy is correct here. `kwargs.get("integer", 1)` will not give you 1 if kwargs is `{"integer": None}`.

**Comment by JelleZijlstra** [comment]
You may be looking for `NotRequired[int]` from PEP 655 instead.
