### ISSUE TITLE
Mypy 0.990 Release Planning

### ISSUE THREAD

**Issue by svalentin** [python/mypy#13871]
I am planning to make a 0.990 release around late October.

Please post here any issues you'd like to see fixed in the release, or PRs you'd like to have merged. There is no release branch yet - I will update the issue once it exists.

**Comment by hauntsaninja** [comment]
Possible things to fix:
- https://github.com/python/mypy/issues/13800
- https://github.com/python/mypy/issues/13803
- https://github.com/python/mypy/issues/13850
- https://github.com/python/mypy/pull/13851#issuecomment-1274519216
- https://github.com/python/mypy/issues/13821

**Comment by cdce8p** [comment]
It would be awesome if these PRs could be included. The first one is already approved
- #13686
- #13762

**Comment by ilevkivskyi** [comment]
@sobolevn IIUC you are working on `LiteralString`, right? Will you have time to finish it in time for 0.990?

**Comment by sobolevn** [comment]
Yes, I will :)

**Comment by svalentin** [comment]
How are we doing on the potential things to fix for next release list? Do all of them have someone working on them?
I'm thinking of cutting a release branch tomorrow. (We can of course add more stuff after)

**Comment by svalentin** [comment]
Sorry got carried away. Will make the release branch today!
Looking to release this around Tuesday unless there's any pressing issues.

**Comment by svalentin** [comment]
Created `origin/release-0.990` at ec6d9d974

**Comment by hauntsaninja** [comment]
Cherry picked 2d70ac0b3 (useful for typeshed)

**Comment by hauntsaninja** [comment]
Cherry picked 5319fa34a (likely addresses performance regression in #13821, no mypy_primer hits, maybe should be solved within mypy rather than in typeshed)

**Comment by hauntsaninja** [comment]
I think it would be very good (but not necessarily blocking) to get in https://github.com/python/mypy/pull/13892 cc @JukkaL @sobolevn 

False negatives related to https://github.com/python/mypy/issues/13890 / https://github.com/python/mypy/pull/13472 show up pretty often (e.g. we just got another report in https://github.com/python/mypy/issues/13966, where things would silently not work)

**Comment by sobolevn** [comment]
Yes, reporing invalid `ParamSpec` usage seems quite important.

**Comment by hauntsaninja** [comment]
Okay, I've gone ahead and merged https://github.com/python/mypy/pull/13892 and cherry picked it to release branch. There are probably still some improvements we can make, but the basic checks should catch many user errors and it seems important we include it in the release.

**Comment by svalentin** [comment]
Unfortunately we'll have to postpone the release by 2-3 days. Jukka found that mypy crashes if except* is used in python 3.11 (https://peps.python.org/pep-0654/). The thinking is to make it at least not crash so we can announce the start of (basic) support for 3.11 in this release. This way maybe we can get some testing until 1.0.0 version.

**Comment by hauntsaninja** [comment]
@svalentin I think treating except* exactly like except is pretty viable for "make it not crash". Opened https://github.com/python/mypy/pull/13991 for this

https://github.com/python/mypy/issues/12840 contains two other language changes that we should add tests for to make sure mypy can handle (but they're not headline features, so it's not as important and they likely won't crash mypy)

**Comment by ilevkivskyi** [comment]
FWIW I was going to work on proper `except*` support this and/or next weekend. But I don't want to postpone release for this, so please go ahead with a minimal no-crash support.

**Comment by svalentin** [comment]
v0.990 wheels should be on pipy now! Please test it out!
Will publish blog post later today or tomorrow morning if there's no problems.

**Comment by svalentin** [comment]
Blog post is out: https://mypy-lang.blogspot.com/2022/11/mypy-0990-released.html

**Comment by svalentin** [comment]
http://mypy-lang.org/ is updated with the link to the new version and blog post!

**Comment by sobolevn** [comment]
@svalentin thank you for your hard work!

**Comment by svalentin** [comment]
Thank you!
Though it looks like we might need a point release: https://github.com/python/mypy/issues/14027

**Comment by svalentin** [comment]
Reopening this for a point release to fix some of the reported issues!

**Comment by intgr** [comment]
If #14042 isn't just a fluke, it seems like a pretty important thing to fix.

**Comment by intgr** [comment]
By the way, https://mypy-play.net still doesn't have mypy 0.990 (and not even 0.982).

**Comment by hauntsaninja** [comment]
Want to ask over at https://github.com/ymyzk/mypy-playground/issues ? (no one here has control over mypy-play.net)

**Comment by hauntsaninja** [comment]
Fixes to cherry pick:
https://github.com/python/mypy/pull/14060 (this one is bad enough that we should make a release sometime in the next couple of days regardless of state of other issues)
https://github.com/python/mypy/pull/14038

Things worth cherry picking once fixed:
https://github.com/python/mypy/issues/14027
https://github.com/python/mypy/issues/14046
https://github.com/python/mypy/issues/14048 (docs)

(feel free to edit this message)

**Comment by svalentin** [comment]
Yes! #14060 and #14038 are already CPed in the release-0.990 branch. Waiting for the other 3.

**Comment by hauntsaninja** [comment]
Made PRs for the other three issues!

**Comment by ilevkivskyi** [comment]
Merged two out of three, and left feedback for the third one.

**Comment by hauntsaninja** [comment]
Thanks! All are merged now, just cherry picked to release-0.990 branch

**Comment by svalentin** [comment]
Thanks! I'll go through the release formalities on Monday

**Comment by ilevkivskyi** [comment]
I don't like this idea. It is not a regression, some people may actually like semantics in 0.990. Point releases are for bad obvious bugs (and crashes).

**Comment by AlexWaygood** [comment]
> I don't like this idea. It is not a regression, some people may actually like semantics in 0.990. Point releases are for bad obvious bugs (and crashes).

If we merged the changes to the `ast` stubs as suggested in https://github.com/python/typeshed/pull/9130, would you be open to cherry-picking those changes into the patch release?

**Comment by ilevkivskyi** [comment]
Yes, this is a safer option, unless someone else is against.

**Comment by AlexWaygood** [comment]
Okay, I merged the typeshed change. Would be great if https://github.com/python/typeshed/commit/f9cd5ee859e481e2c3094804f68d5e888d2b6ee2 could be cherry-picked to the patch release :)

**Comment by svalentin** [comment]
v0.991 wheels should be on pypi now!

**Comment by svalentin** [comment]
Marking this as Done!
Will reopen if we need another point release.
