### ISSUE TITLE
mypy doesnt understand "in" when a None is involved

### ISSUE THREAD

**Issue by tommyjcarpenter** [python/mypy#13886]
```
x: Optional[int]
...
if x is None or x is 0:
    raise Exception()
print(1/x)
```

works

```
if x == None or x is 0:
    raise Exception()
print(1/x)
```

also works although I acknowledge this is not the standard way of checking None (== rather than is) however its legal python:
```
>>> x = 1
>>> x == None
False
>>> x = None
>>> x == None
True
```

However:
```
if x in [None, 0]:
    raise Exception()
print(1/x)
```

does not work - mypy complains that you cant divide by None. I also tried `(None, 0)`. It seems mypy doesnt "break the in" into x == each of the subparts.

**Comment by tommyjcarpenter** [comment]
Im not sure if this is actually a bug or a "feature"

**Comment by mausch** [comment]
Another instance of this I just ran into:

`if a is None or b is None or c is None:` -> works as expected
`if None in [a, b, c]:` -> fails to detect variables as not None after the `if` block, just as described by OP.
