### ISSUE TITLE
Return type "None" of "send_signal" incompatible with return type "int" in supertype "SubprocessTransport"

### ISSUE THREAD

**Issue by allisonkarlitskaya** [python/mypy#13885]
This message is incorrect:

```
$ mypy broken.py
broken.py:6: error: Return type "None" of "send_signal" incompatible with return type "int" in supertype "SubprocessTransport"
Found 1 error in 1 file (checked 1 source file)
```

```
$ cat broken.py
```

```python
import asyncio

class Transport(asyncio.SubprocessTransport):
    """A bi-directional transport speaking with stdin/out of a subprocess."""

    def send_signal(self, signal: int) -> None:
        pass
```

I get the same message with the Fedora 37 package:
```
python3-mypy-0.981-1.fc37.noarch
mypy 0.981 (compiled: no)
```

But also with the latest version installed from `pip`:
```
mypy 0.982 (compiled: no)
```

There is no annotation on the base type (or any of its implementations) but none of the implementations return anything, so `None` is certainly correct here.

https://github.com/python/mypy/issues/13885#tasklist-block-db70dc05-b82a-427f-a8e0-46d5fc2c469c

**Comment by JelleZijlstra** [comment]
This was fixed in typeshed, thanks for the PR!
