### ISSUE TITLE
Type assertions in function calls not recognized

### ISSUE THREAD

**Issue by vinceranga** [python/mypy#13915]
**Bug Report**

Mypy does not recognize type assertions made in function calls.

**To Reproduce**

https://gist.github.com/b0e00808211899a67072601b1062602f

**Actual Behavior**

```
main.py:7: error: Unsupported operand types for + ("None" and "int")
main.py:7: note: Left operand is of type "Optional[int]"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.981 (latest at the time of writing)
- Mypy command-line flags: N/A (defaults on mypy playground)
- Mypy configuration options from `mypy.ini` (and other config files): N/A (defaults on mypy playground)
- Python version used: 3.10

**Comment by erictraut** [comment]
This is what `TypeGuard` was designed for. See [PEP 647](https://peps.python.org/pep-0647/) for details.

```python
from typing import TypeGuard, TypeVar

T = TypeVar("T")

def isvalid(num: T | None) -> TypeGuard[T]:
    return num is not None

def func(num: int | None):
    if isvalid(num):
        print(num + 1)
```

**Comment by JelleZijlstra** [comment]
Agree, closing this as mypy is very unlikely to addd support for the pattern in the OP's gist.
