### ISSUE TITLE
Mypy uses installed Python version even when explicitly specified

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#13912]
When running mypy under Python 3.8, I'm getting `Module has no attribute "to_thread"` in relation to `asyncio.to_thread()`.

This keeps happening even when I've added this to the file: `# mypy: python-version=3.9`

The same problem also happens in reverse, if I run mypy on Python 3.10 with `# mypy: python-version=3.7` the error does not appear.

**Comment by Dreamsorcerer** [comment]
https://github.com/aio-libs/aiohttp/actions/runs/3260012218/jobs/5353259107

**Comment by hauntsaninja** [comment]
python_version can only be set globally, documented here: https://mypy.readthedocs.io/en/stable/config_file.html#confval-python_version

Making python_version per-file would likely not be feasible
