### ISSUE TITLE
Bad error message for `assert_type` with `Callable`

### ISSUE THREAD

**Issue by Rogdham** [python/mypy#13935]
**Bug Report**

Using `assert_type` with `Callable` expects all parameters to be positional-only, and report a confusing error message otherwise.

**To Reproduce**

```python
from typing import Callable
from typing_extensions import assert_type  # or from typing in Python 3.11


def foo(a: str) -> int:
    return len(a)

assert_type(foo, Callable[[str], int])
# error: Expression is of type "Callable[[str], int]", not "Callable[[str], int]"
```

Note that the following works:

```python
def bar(a: str, /) -> int:
    return len(a)

assert_type(bar, Callable[[str], int])  # mypy is silent
```

**Expected Behavior**

At the very least, the error message should be more descriptive.

However I would have assumed that the `assert_type` call would be silent for both `foo` and `bar` functions.

Indeed, `foo` can be assigned to a variable typed as `Callable[[str], int])` without any issue:
```python
foo2: Callable[[str], int] = foo  # ok for mypy
assert_type(foo2, Callable[[str], int])  # this time mypy is silent
```

**Actual Behavior**

```
error: Expression is of type "Callable[[str], int]", not "Callable[[str], int]"
```

**Your Environment**

- Mypy version used: `mypy 0.982 (compiled: yes)`
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: `Python 3.10.8`

**Comment by JelleZijlstra** [comment]
I think mypy is right here. `assert_type()` is supposed to check the *exact* type. It's true that the type of `foo` is assignable to `Callable[[str], int]`, but its type is a subtype of `Callable[[str], int]`, not exactly the same.

We should improve the error message, though.

**Comment by Rogdham** [comment]
I failed to find a PEP defining `assert_type`, the only thing I found in the following from [Python 11's documentation](https://docs.python.org/3.11/library/typing.html#typing.assert_type):

> Ask a static type checker to confirm that val has an inferred type of typ.

If I understand this correctly, you are right @JelleZijlstra that the given type should be exact.

---

With that being said, I feel like this issue will be frequent when asserting the type of a `Callable`, because  _positional-or-keyword_ are the default (and what most programmers would write when creating a function).

Changing the error message would be great indeed, so that:
 1. It is not confusing
 2. It points at a possible solution

For point 2 is there any better way than defining a callback protocol just for this? I feel like this adds some boilerplate:

```py
class ExpectedType(Protocol):
    def __call__(self, a: str) -> int:
        ...

assert_type(foo, ExpectedType)
```

**Comment by JelleZijlstra** [comment]
Instead of assert_type() you could write a function. `def want_callable_int_str(c: Callable[[int], str]) -> None: ...`, then call `want_callable_int_str(foo)`. That will fail typechecking if `foo` is not of the expected type.

**Comment by erictraut** [comment]
I agree with Jelle that mypy is doing the right thing here. And it looks like the error message has been improved since the bug was originally logged, so I think it would be OK to close this issue.

**Comment by Rogdham** [comment]
Here is the new error message (as of mypy 1.5.0):

```
error: Expression is of type "Callable[[Arg(str, 'a')], int]", not "Callable[[str], int]"  [assert-type]
```

This falls into my expected behavior of “the error message should be more descriptive”.

Thank you @erictraut for pointing it out, I'm closing this ticket!
