### ISSUE TITLE
Mypy appears to have an internal "Never" type which can't be reveal_typed

### ISSUE THREAD

**Issue by kmillikin** [python/mypy#13947]
In this contrived example:

```
class A: pass

class B: pass

def f(x: A):
  if isinstance(x, B):
    if not isinstance(x, B):
      reveal_type(x)
```

mypy just does not reveal any type.  It does look like mypy internally knows that it is impossible to both be an instance of B and not be an instance of B, but this internal knowledge is not getting revealed as `Never` (or anything else).

**Comment by hauntsaninja** [comment]
What's going on here is https://mypy.readthedocs.io/en/stable/common_issues.html#unreachable-code

**Comment by kmillikin** [comment]
Aha!  Thanks for the explanation.
