### ISSUE TITLE
"Sequence[Collection[str]]" has no attribute "append"

### ISSUE THREAD

**Issue by hvignolo87** [python/mypy#13948]
**Bug Report**

When appending a dictionary to a nested list inside another dictionary, the linter throws an error with the text:

`"Sequence[Collection[str]]" has no attribute "append"`

This is a screenshot from VSCode:

![mypy-bug](https://user-images.githubusercontent.com/205441/198044433-72644634-439f-4477-978b-9dd999799fe7.png)

This is a screenshot from the console output in the same file:

![mypy-bug2](https://user-images.githubusercontent.com/205441/198047689-348fd0d2-6ed8-42eb-87db-0c62f0afbaca.png)

**To Reproduce**

```python
from pprint import pprint

# The main dict
section = {
    "type": "section",
    # Nested list
    "fields": [
        {"type": "mrkdwn", "text": "*File:*"},
        {
            "type": "mrkdwn",
            "text": "*Broken links:*",
        },
        {"type": "mrkdwn", "text": "*Links*"},
        {"type": "mrkdwn", "text": "*Status Code*"},
    ],
}

for text in ['a', 'b', 'c']:
    # Here is where the linter throws the error, in section variable
    section["fields"].append({"type": "plain_text", "text": f"{text}", "emoji": False})

pprint(section)
```

**Expected Behavior**

No error should be thrown.

**Actual Behavior**

`"Sequence[Collection[str]]" has no attribute "append"`

**Your Environment**

- Mypy version used: 0.982
- Mypy command-line flags: `--follow-imports=skip`
- Mypy configuration options from `mypy.ini` (and other config files):
```config
[mypy]
ignore_missing_imports = True
```
- Python version used: 3.10.7

**More info about my system**

I'm working in Ubuntu 22.04 on WSL2. More information about my system is below:

Output of `lsb_release -a` command:

```text
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
The output of the `uname -a` command:

```text
Kernel name: Linux 
Kernel release: 5.15.68.1-microsoft-standard-WSL2 
Kernel version: #1 SMP Mon Sep 19 19:14:52 UTC 2022
Machine: x86_64 
Processor: x86_64 
Hardware platform: x86_64 
OS: GNU/Linux
```
The output of the `docker version` command:

```text
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thomkeh** [comment]
Shorter reproduction:
```python
l = ["foo", [{"a": 0}]]
reveal_type(l)
```
gives
```
main.py:2: note: Revealed type is "builtins.list[typing.Sequence[typing.Collection[builtins.str]]]"
```
I think the problem is that mypy tries to find a common superclass of `str` and `list[dict[str, int]]` when it should probably just infer a `Union`.

However, in your code, a union also wouldn't help. I think you need a `TypedDict`.

**Comment by hvignolo87** [comment]
> Shorter reproduction:
> 
> ```python
> l = ["foo", [{"a": 0}]]
> reveal_type(l)
> ```
> 
> gives
> 
> ```
> main.py:2: note: Revealed type is "builtins.list[typing.Sequence[typing.Collection[builtins.str]]]"
> ```
> 
> I think the problem is that mypy tries to find a common superclass of `str` and `list[dict[str, int]]` when it should probably just infer a `Union`.
> 
> However, in your code, a union also wouldn't help. I think you need a `TypedDict`.

Hi @thomkeh! Thanks for your suggestions, I totally agree 💯 
However, this is still a bug of the linter, am I right?

**Comment by JelleZijlstra** [comment]
It's not really a bug, but an unfortunate consequence of mypy's inclination to use the join operator. There are lots of issues about that in https://github.com/python/mypy/labels/topic-join-v-union, I don't think we need another.

**Comment by hauntsaninja** [comment]
To be clear, your best option is an explicit annotations, e.g. `section: dict[str, Any] = ...`
