### ISSUE TITLE
`TypeVar` erroneously coerses `List[Any]` to `List[str]`

### ISSUE THREAD

**Issue by DamianBarabonkovQC** [python/mypy#13959]
**Bug Report**

When annotating a value using only `a : list`, the contents of said list are assumed to be `Any`. I believe that is a fair assumption. However, when passing this `a` to a function which takes a `TypeVar("T", int, list[str])`, it should fail, but it gets accepted by the `list[str]` clause and also type coerced to be said type.

**To Reproduce**

```python
from typing import TypeVar, Any, List

T = TypeVar("T", int, List[str])

def f(x: T) -> T:
    return x

a : int = 3
reveal_type(f(a))

b : List = [3]
reveal_type(b)
reveal_type(f(b))
```

**Expected Behavior**

Mypy should fail with `debugging/playground_qc_thek/mypy_fun.py:13: error: Value of type variable "T" of "f" cannot be "List[int]"` as it does when I set `b : List[int] = [3]`.

**Actual Behavior**

```
debugging/playground_qc_thek/mypy_fun.py:9: note: Revealed type is "builtins.int"
debugging/playground_qc_thek/mypy_fun.py:12: note: Revealed type is "builtins.list[Any]"
debugging/playground_qc_thek/mypy_fun.py:13: note: Revealed type is "builtins.list[builtins.str]"
```

**Your Environment**

- Mypy version used: mypy 0.982
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: Python 3.10.6

**Comment by kmillikin** [comment]
I'm afraid that this is working as intended, because that's just how the type system works.  Values of type `list[Any]` can be passed where `list[str]` is expected.  You will see the same behavior without type variables if you try:

```python
def f(x: list[str]) -> list[str]:
  return x

b: list = [3]
reveal_type(f(b))
```

So if you want static checking here, you have to avoid the raw `list` annotation (or explicit `list[Any]`).

**Comment by DamianBarabonkovQC** [comment]
Hi Keven, Thanks for the clarification. To me it seems a bit peculiar since it essentially feels like down casting `Any` a super-set of types to `str`. Could you explain why this is intended or even beneficial?

**Comment by kmillikin** [comment]
It will seem that way if your mental model of `Any` is that it is the set of all Python values.

A better way to think of `Any` is that each occurrence is an unknown static type.  That is, it's some set of Python values, but not necessarily all.  You use `Any` where you don't want any static checking.

**Comment by AlexWaygood** [comment]
> Could you please explain why this is intended or even beneficial?

Whether it's "beneficial" is of course open for debate, but this is definitely intended behaviour. `Any` is meant to be an "escape hatch" in the typing system — it's deliberately unsound, doesn't follow the normal rules, and should generally be used, as @kmillikin says, in situations where you just want the type checker to shut up for some reason.

You can get mypy to emit an error for bare `list` annotations (etc) by using the `--disallow-any-generics` flag, which is enabled by default if you use the `--strict` flag.

**Comment by hauntsaninja** [comment]
You might be looking to use `list[object]`
