### ISSUE TITLE
How to retrieve type of "nodes.Expression" using internal "State" and "TypeChecker"?

### ISSUE THREAD

**Issue by Delgan** [python/mypy#13972]
Hi there.

I'm trying to retrieve the type of an `mypy.nodes.OpExpr` after running the type checker and getting the generated AST.

Such a node has a `method_type` attribute which contains what I'm looking for most of the time. However, for a reason I ignore, it's `None` when analyzing `or` operator, like `True or False` for example.

Here is my code (I'm playing with some "undocumented" features of Mypy used internally):

```python
import sys

from mypy.build import build
from mypy.modulefinder import BuildSource
from mypy.options import Options

if __name__ == "__main__":
    options = Options()
    options.preserve_asts = True
    options.fine_grained_incremental = True
    options.show_traceback = True

    # File tested must contain "True or False" literally.
    source = BuildSource(sys.argv[1], "__main__", None)
    result = build([source], options)
    state = result.graph["__main__"]

    checker = state.type_checker()
    tree = state.tree

    expr = tree.defs[0]  # mypy.nodes.ExpressionStmt
    op_expr = expr.expr  # mypy.nodes.OpExpr

    op_expr.method_type  # => None
    op_expr.accept(checker.expr_checker)  # => AssertionError
    checker.expr_checker.visit_op_expr(op_expr)  # => AssertionError
    checker.expr_checker.accept(op_expr)  # => SegFault
    checker.expr_checker.accept(expr)  # => SegFault
```
Do you please have any clue about why is `op_expr.method_type` equals to `None`?
What is the appropriate way to generically retrieve the type of `node.Expression` given a parsed `State` and a `TypeChecker`? 

Thanks!

**Comment by erictraut** [comment]
@Delgan, did you find an answer to your question? If so, please mark this as closed.

**Comment by Delgan** [comment]
Using `checker.expr_checker.visit_op_expr(op_expr)` seems to return the expected `Literal[True]` type with Mypy 1.5.0, instead of raising an `AssertionError` at the time this ticket was created.

I'll close it, thanks.
