### ISSUE TITLE
Error when passing time window as string to pandas.DataFrame.rolling() function

### ISSUE THREAD

**Issue by ramonbotella** [python/mypy#13971]
**Bug Report**

I'm having a mypy type-checking error when trying to commit code with the pandas.DataFrame.rolling() function. Particularly when the dataframe has a datetimelile index and I pass a frequency as a string in the form "2D" (for two days), for instance. I have tried to set the index as a column and pass on="column_name" to rolling and to use other time intervals ("3D" and "7D"), but the error is the same.

**To Reproduce**
Error type-checking on pandas.DataFrame.rolling()

```python
import pandas as pd
s = pd.Series(range(5), index=pd.date_range("2023-01-01", periods=5, freq="1D"))
s.rolling(window="2D").sum()
```
**Actual Behavior**

`error: No overload variant of "rolling" of "Series" matches argument type "str"`
`note: Possible overload variants:`
`note:     def rolling(self, window: Union[int, BaseOffset, BaseIndexer], min_periods: int = ..., center: bool = ..., *, win_type: str, on: str = ..., axis: Union[Literal['index'], Literal[0]] = ..., closed: str = ..., step: int = ..., method: Union[Literal['single'], Literal['table']] = ...) -> Window[Series[Any]]`
`note:     def rolling(self, window: Union[int, BaseOffset, BaseIndexer], min_periods: int = ..., center: bool = ..., *, win_type: None = ..., on: str = ..., axis: Union[Literal['index'], Literal[0]] = ..., closed: str = ..., step: int = ..., method: Union[Literal['single'], Literal['table']] = ...) -> Rolling[Series[Any]]`

**My Environment**

- Mypy version used: 0.971
- Mypy command-line flags: `error: No overload variant of "rolling" of "Series" matches argument type "str"`
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.8.10
- Pandas version used: 1.4.3
- Pandas-stubs version used: 1.4.3.220829

**Comment by hauntsaninja** [comment]
Why is this a mypy bug? Please report it to pandas-stubs
