### ISSUE TITLE
Decorator with an explicit positional argument result in the error return-value

### ISSUE THREAD

**Issue by JonathanPlasse** [python/mypy#13970]
**Bug Report**

Typed decorator with an explicit positional argument result in the error `return-value`

**To Reproduce**

[Link to mypy-play](https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=946073c3dfa453f9c944316a14da57bf)

```python
import functools
from typing import Any, Callable, Concatenate, Coroutine, ParamSpec, TypeVar

P = ParamSpec("P")
T = TypeVar("T")


class Client:
    _outgoing_calls_sem: Any = None


def _outgoing_call(
    method: Callable[Concatenate[Client, P], Coroutine[Any, Any, T]]
) -> Callable[Concatenate[Client, P], Coroutine[Any, Any, T]]:
    @functools.wraps(method)
    async def decorated(self: Client, *args: P.args, **kwargs: P.kwargs) -> T:
        if not self._outgoing_calls_sem:
            return await method(self, *args, **kwargs)

        async with self._outgoing_calls_sem:
            return await method(self, *args, **kwargs)

    return decorated
```

**Expected Behavior**

I was expecting to be able to use a positional argument for a decorator.

**Actual Behavior**

```
Incompatible return value type (
     got "Callable[[Arg(Client, 'self'), **P], Coroutine[Any, Any, T]]",
expected "Callable[[Client, **P], Coroutine[Any, Any, T]]")  [return-value]mypy(error)
This may be because "decorated" has arguments named: "self"mypy(note)
```

**Your Environment**

- Mypy version used: 0.981
- Mypy command-line flags: --strict it works without it
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10

**Comment by hauntsaninja** [comment]
Needs to be marked as positional only (PEP 570 or double underscores). I improved the error message in #13777. There's also --no-strict-concatenate

**Comment by JonathanPlasse** [comment]
Thanks
