### ISSUE TITLE
Deduce length of tuple when using slice expression

### ISSUE THREAD

**Issue by dosisod** [python/mypy#14001]
**Bug Report**

Basically, Mypy does not deduce the length of a tuple which is being sliced, even if the length is a constant.

**To Reproduce**

Given the following code:

```python
expected = (0, 1, 2)
recieved = tuple((0, 1, 2))[:3]

error: tuple[int, int, int] = recieved

reveal_locals()
```

Mypy returns:

```
$ mypy x.py
x.py:4: error: Incompatible types in assignment (expression has type "Tuple[int, ...]", variable has type "Tuple[int, int, int]")
x.py:6: note: Revealed local types are:
x.py:6: note:     expected: Tuple[builtins.int, builtins.int, builtins.int]
x.py:6: note:     recieved: builtins.tuple[builtins.int, ...]
Found 1 error in 1 file (checked 1 source file)
```

I would expect the type of `recieved` to be `tuple[int, int, int]`, but instead it is variadic.

**Proposal**

Basically, so long as we know the following:

* That the right-hand side of the slice is a constant value (3 in this case)
* And the length of the tuple we are constructing is at least length 3

We should be able to safely deduce the length of the tuple. Is my assumption correct?

This is similar to https://github.com/python/mypy/issues/5068, but not quite (IMO). In this case, we are able to set an upper bound for the length (via the slice).

This might be better off merged/deleted in favor of #5068.

**Your Environment**

```
$ python --version
Python 3.10.8
$ mypy --version
mypy 0.982 (compiled: yes)
```

**Comment by JelleZijlstra** [comment]
This isn't about slicing, the problem is that `tuple((0, 1, 2))` is of type `tuple[int, ...]`. If you do `reveal_type((0, 1, 2)[:2])`, the type is `"Tuple[Literal[0]?, Literal[1]?]"`.

**Comment by dosisod** [comment]
Ok, I will close this in favor of #5068 then. Thanks for the insight!
