### ISSUE TITLE
mypy 0.990 is 1000x slow on pydantic codebase vs 0.982

### ISSUE THREAD

**Issue by samuelcolvin** [python/mypy#14034]
**Bug Report**

Running mypy on the current pydantic codebase (specifically the code as of https://github.com/pydantic/pydantic/pull/4735), give the following run times:

* running `mypy pydantic` with mypy `0.982`, and no `.mypy_cache`: 8s
* running `mypy pydantic` with mypy `0.982`, `.mypy_cache` present: 0.17s
* running `mypy pydantic` with mypy `0.990`, and no `.mypy_cache`: 3m19s
* running `mypy pydantic` with mypy `0.990`, `.mypy_cache` present: 3m6s

(1000x comes from `(3 * 60 + 6) / 0.17`)

There are quite a few errors, mostly due to `no_implicit_optional=True`, but still - this seems like a significant regression.

While mypy 0.990 is running, I see 100% usage on 1 CPU.

**To Reproduce**

Should be as simple as cloning pydantic, checkout that branch (`uprev-mypy`), install requirements from `requirements/linting.txt`, run mypy.

**Your Environment**

- Mypy version used: `0.990`
- Mypy command-line flags: just `mypy pydantic`
- Mypy configuration options from `mypy.ini` (and other config files): see [this bit of `pyproject.toml`](https://github.com/pydantic/pydantic/blob/aea7016e6cbc7c589713e9ffb7891316d9cde262/pyproject.toml#L155-L187)
- Python version used:3.10.0 (just realised how old my version of 3.10 is, I've upgraded to 3.10.8, same result)

**Comment by samuelcolvin** [comment]
As with #14027, would it be worth adding pydantic to mypy_primer @hauntsaninja?

As with sqlalachemy, pydantic pushes python's type system fairly hard, in particular, the schema for pydantic-core, is [defined](https://github.com/pydantic/pydantic-core/blob/463ed7aa83b08c43bc699e7e5380026551e38876/pydantic_core/core_schema.py#L1102) as a recursive union of TypedDicts.

**Comment by ilevkivskyi** [comment]
Note that when an error is present in a file, mypy will not use cache for that file.

**Comment by ilevkivskyi** [comment]
Btw can you try `--disable-recursive-aliases`? Such big recursive types are known to be slow.

**Comment by samuelcolvin** [comment]
Yup, that makes a big different, time reduces to 9s.

**Comment by ilevkivskyi** [comment]
Also, just to be sure, can you also try `--enable-recursive-aliases` on 0.982?

**Comment by samuelcolvin** [comment]
Takes 261s as you predicted - seems that's the problem.

**Comment by ilevkivskyi** [comment]
OK, then this will be not easy to fix. The problem is that you have that big union of 40 items. Previously mypy didn't support recursive types, so most likely all recursive types were either plain `Any` or shallow TypedDicts with `Any`. Mypy used to give an error about this however. I guess this error was not shown because `pydantic_core` is checked as third party dependency? You can try `--no-silence-site-packages` when using `--disable-recursive-aliases`. (Btw everything on `PYTHONPATH` is considered third party, cc @JukkaL)

So now when recursive types are properly supported imagine you have a triple nested dictionary typed as `CoreSchema`. Mypy will need to try every item in the union until it finds a matching one. This will take on average 20 * 20 * 20 = 8000 type checks for a single dict. To make things worse, TypedDicts are structural, and some have overlapping keys so it may take a while to figure out that a given item doesn't actually match.

We will still try to profile this. Maybe there is some room for optimizations.

**Comment by samuelcolvin** [comment]
Thanks so much for the explanation.

Simple answer might be to move to pyright, which we already use to check pydantic-core and seems to do a reasonably good job (although that union found a bug in pyright too). (I don't mean this to sound hostile, mypy is amazing and I'd love to continue to use it, but I understand if this is a fundamental limitation of the library)

If it helps, all those TypedDicts have a `type` key which can (mostly) be used as a discriminator - that's how we validate pydantic-core schema using pydantic-core, see [here](https://github.com/pydantic/pydantic-core/blob/463ed7aa83b08c43bc699e7e5380026551e38876/src/validators/union.rs#L318-L361). Using that discriminator, the number of types checked could be massively reduced, but I guess that's too specific for mypy to be able to pick up on.

**Comment by ilevkivskyi** [comment]
Btw if you fix the errors coming from `no_implicit_optional=True` the cache should became effective again. I guess even with recursive types enabled, a typical run should take just few seconds with warm cache.

**Comment by samuelcolvin** [comment]
ye, I thought that, but it's still not really acceptable for either CI or new contributors for mypy to take minutes.

I guess we'll have to use `--disable-recursive-aliases`.

**Comment by hauntsaninja** [comment]
Thanks, pydantic is already in mypy_primer :-) However, we don't currently monitor perf regressions in mypy_primer... it's a feature I've been thinking about though

**Comment by samuelcolvin** [comment]
Any update on this, or generally update on mypy performance?

We're at the point where we're going to have to litter pydantic's docs with messages discouraging use of mypy, which seems really sad.

As of today running mypy `mypy 1.1.1 (compiled: yes)` on the following code

```py
from pydantic import BaseModel

class MyModel(BaseModel):
    x: int
```
* `mypy example.py` runs indefinitely, definitely for hours
* `mypy example.py --disable-recursive-aliases` takes 90s on my i7 desktop with no cache

@sobolevn @AlexWaygood @JukkaL Sorry to push, but this is a very unfortunate situation, is there anything you could do to help?

Even if you had a hack to automatically ignore the `pydantic_core` package (e.g. treat it like it has no `py.typed` file) while still allowing us run mypy with it included in CI, that would help a lot until the performance issues could be fixed.

To be clear, the problem is [this](https://github.com/pydantic/pydantic-core/blob/main/pydantic_core/core_schema.py) which is very important to pydantic, but kills mypy.

**Comment by hauntsaninja** [comment]
Hmm...
```
from pydantic import BaseModel

class MyModel(BaseModel):
    x: int
```
Running mypy on this file takes about 16s for me with no cache (with both mypy versions 1.1.1 and 1.2, pydantic version 1.10.7, no extra mypy configuration)

Obviously it would be preferable to actually solve the issue, but note that one potential hack is to use a `MYPY` constant. mypy will always treat this as True, so you could do something like:
```
MYPY = False
if MYPY:
    BigSchemaType = Any  # or possibly a slightly better fallback
else:
    BigSchemaType = Union[...]
```

**Comment by adriangb** [comment]
The issue is that if you _use_ those types that 16s grows exponentially (give or take).

> one potential hack is to use a MYPY constant

We are indeed exploring that: https://github.com/pydantic/pydantic-core/pull/528. Is this approach documented anywhere?

**Comment by hauntsaninja** [comment]
Yeah, makes sense, sounds like Samuel didn't paste the full example.py he was running against in https://github.com/python/mypy/issues/14034#issuecomment-1499250007 then

MYPY constant is documented, but not particularly thoroughly, e.g. at https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks Too much of its use would probably be bad for the typing ecosystem

**Comment by cdce8p** [comment]
> Running mypy on this file takes about 16s for me with no cache (with both mypy versions 1.1.1 and 1.2 both compiled, pydantic version 1.10.7, no extra mypy configuration)

I believe the issue is only present in the current dev builds for pydantic as a result of the upcoming move to version 2. I can reproduce the issue with `pydantic==2.0a1` and `--no-incremental`.

<details><summary>To reproduce</summary>

1. Create a new venv (I'm using Python 3.11)
2. `pip install -U pip wheel setuptools` (might not be necessary)
3. `pip install mypy==1.2.0 pydantic==2.0a1`
4. `mypy -v --no-incremental example.py`

```py
# example.py
from pydantic import BaseModel

class MyModel(BaseModel):
    x: int
```

Mypy starts to hang at
```
LOG:  Processing SCC singleton (pydantic_core.core_schema) as inherently stale with stale deps (__future__ builtins datetime sys typing)
```
</details>

**Comment by samuelcolvin** [comment]
Correct @cdce8p, my mistake - I was running on `main` but the same will be true on `2.0a1` - or indeed any V2 release until we use a hack like `if not MYPY:` on [this[(https://github.com/pydantic/pydantic-core/blob/8a0ecd4eb05de20f8b3910df7be049071442fc35/pydantic_core/core_schema.py#L3286) line, or mypy fixes some of these performance issues.

**Comment by hauntsaninja** [comment]
@cdce8p weird, I still can't repro
```
~/test λ pip freeze                             
annotated-types==0.4.0
mypy==1.2.0
mypy-extensions==1.0.0
pydantic==2.0a1
pydantic_core==0.23.0
tomli==2.0.1
typing_extensions==4.5.0
~/test λ mypy --version                     
mypy 1.2.0 (compiled: yes)
λ cat example.py
from pydantic import BaseModel

class MyModel(BaseModel):
    x: int
~/test λ time mypy --no-incremental example.py   
Success: no issues found in 1 source file
mypy --no-incremental example.py  2.96s user 0.16s system 99% cpu 3.124 total
```

**Comment by hauntsaninja** [comment]
Oh looks like pydantic_core made a new release

**Comment by adriangb** [comment]
Yes, we basically used that constant to the disable type checking for mypy and will have to tell our users that if they want proper type checkin they need to use a different type checker 😔

**Comment by hauntsaninja** [comment]
Okay, took a look tonight and found a simple patch that makes this terminate (but is still extremely slow).

Note for self: `pip install 'pydantic-core==0.22.0' 'pydantic==2.0a1'` to get the right versions.

**Comment by JukkaL** [comment]
#14150 further improved performance of the simple example by 3.5x for me (when not using a compiled mypy).

**Comment by hauntsaninja** [comment]
https://github.com/python/mypy/pull/15128 should be another 25% for me on the pydantic codebase
