### ISSUE TITLE
0.990 reports error for function with body that is just ellipsis

### ISSUE THREAD

**Issue by haxtibal** [python/mypy#14048]
mypy 0.990 (python 3.8) reports an error for the following source code
```py
def foo() -> int:
    ...
```
```
$ mypy foo.py 
/tmp/foo.py:1: error: Missing return statement  [empty-body]
Found 1 error in 1 file (checked 1 source file)
```
mypy 0.981 would let the same code pass. Was that an intended change in between, or a regression?

From [mypy CLI documentation](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-warn-no-returnl)
> By default, mypy will generate errors when a function is missing return statements in some execution paths. The only exceptions are when:
> - The function has a None or Any return type
> - The function has an empty body or a body that is just ellipsis (...). Empty functions are often used for abstract methods.

I'd expect Success for the given example, because the 2nd exception ("body that is just ellipsis") applies.

**Comment by JukkaL** [comment]
This was an intentional change in 0.990 and the special casing for `...` bodies was mostly removed (#13729). The documentation seems to be now out of date.

**Comment by JukkaL** [comment]
cc @ilevkivskyi

**Comment by ilevkivskyi** [comment]
Yep, I will update the docs. Now you need `--allow-empty-bodies` if you want old behavior (or disable empty-body error code in your mypy config)

**Comment by ilevkivskyi** [comment]
IIUC the situation, my personal preference would be to replace `...` with `raise AttributeNotGeneratedError`. This way if empty stub is used accidentally, you will know immediately, instead of discovering random `None` somewhere down the call stack.
