### ISSUE TITLE
no attribute "__dict__"

### ISSUE THREAD

**Issue by jukebox** [python/mypy#1405]
```
⌁40% [juke:~/minidict] % cat minidict.py  
class MyClassMiniDict(object):
    def __init__(self):
        self.foo = object()

    def __eq__(self, otheri: object):
        return self.__dict__ == other.__dict__


⌁40% [juke:~/minidict] % mypy  minidict.py
minidict.py: note: In function "__eq__":
minidict.py:6: error: Name 'other' is not defined
minidict.py: note: In member "__eq__" of class "MyClassMiniDict":
minidict.py:6: error: "MyClassMiniDict" has no attribute "__dict__"


```

**Comment by gvanrossum** [comment]
It's already fixed in the repo. (Actually it was a typeshed PR: https://github.com/python/typeshed/pull/134)

Please always use the latest version from the repo before reporting bugs.

We're planning a new PyPI release for May 5th, please be patient.

**Comment by ruissalo** [comment]
Hi, 

Not sure if this is still an issue, but using the latest version from github I get the same message:

`python3 -m pip install -U git+git://github.com/python/mypy.git`

`mypy --py2 helpers/utils.py  --ignore-missing-imports`

`something/something.py:33: error: "MyObj" has no attribute "__dict__"`

Thanks
