### ISSUE TITLE
mypyc: `Cls.__dict__` is `mappingproxy`, not `dict`

### ISSUE THREAD

**Issue by kai3341** [python/mypy#14056]
**Bug Report**

It looks mypy's type inference works fine and it's mypyc (maybe) bug
Maybe it's connected to builtins `vars` signature -- vars by the signature should return `dict`
But it's false, `vars` may return `mappingproxy`:
```
>>> class Foo:
... 
>>> Foo.__dict__
mappingproxy({'__module__': '__main__', '__dict__': <attribute '__dict__' of 'Foo' objects>, '__weakref__': <attribute '__weakref__' of 'Foo' objects>, '__doc__': None})
>>> vars(Foo)
mappingproxy({'__module__': '__main__', '__dict__': <attribute '__dict__' of 'Foo' objects>, '__weakref__': <attribute '__weakref__' of 'Foo' objects>, '__doc__': None})
>>>
```

**To Reproduce**

```python
from typing import Type, TypeVar

T = TypeVar("T")


def decorate(cls: Type[T]) -> Type[T]:
    clsdict = cls.__dict__
    # clsdict = vars(cls)
    print(clsdict)
    return cls


@decorate
class Foo:
    pass
```

Then build it via mypy:
```
(.venv) kai@asus-ux360c:~$ mypyc mypyc_weird.py 
running build_ext
copying build/lib.linux-x86_64-3.9/mypyc_weird.cpython-39-x86_64-linux-gnu.so -> 
```

And run it

**Expected Behavior**

```
(.venv) kai@asus-ux360c:~$ python -m mypyc_weird
{'__module__': '__main__', '__dict__': <attribute '__dict__' of 'Foo' objects>, '__weakref__': <attribute '__weakref__' of 'Foo' objects>, '__doc__': None}
```

**Actual Behavior**

```
(.venv) kai@asus-ux360c:~$ python -m mypyc_weird.cpython-39-x86_64-linux-gnu.so 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "mypyc_weird.py", line 14, in <module>
    class Foo:
  File "mypyc_weird.py", line 7, in decorate
    clsdict = cls.__dict__
TypeError: dict object expected; got mappingproxy
```

**Your Environment**

- Mypy version used: `mypy-1.0.0+dev.dbcbb3f5c3ef791c98088da0bd1dfa6cbf51f301` (latest@git)
- Mypy command-line flags: empty
- Mypy configuration options from `mypy.ini` (and other config files): empty
- Python version used: 3.9
- Description:	Debian GNU/Linux 11 (bullseye)

**Comment by AlexWaygood** [comment]
Currently [the stub for `vars()` in typeshed](https://github.com/python/typeshed/blob/7b3fff714a48f0413141ba10344f9473e3ec4a18/stdlib/builtins.pyi#L1671) is this:

```python
def vars(__object: Any = ...) -> dict[str, Any]: ...
```

Maybe it should be this:

```python
def vars(__object: Any = ...) -> Mapping[str, Any]: ...
```

Or this:

```python
@overload
def vars(__object: type) ->  types.MappingProxyType[str, Any]: ...
@overload
def vars(__object: Any = ...) -> dict[str, Any]: ...
```

_However_, that doesn't explain why mypyc seems to think that `cls.__dict__` should be of type `dict`. Typeshed correctly already has `type.__dict__` as being of type `types.MappingProxyType`: https://github.com/python/typeshed/blob/7b3fff714a48f0413141ba10344f9473e3ec4a18/stdlib/builtins.pyi#L149

**Comment by AlexWaygood** [comment]
https://github.com/python/typeshed/pull/9146 has just been merged, which improves the signature for `vars()`.

**Comment by kai3341** [comment]
@AlexWaygood I didn't find docs how to install latest [typeshed](https://github.com/python/typeshed/blob/7b3fff714a48f0413141ba10344f9473e3ec4a18/stdlib/builtins.pyi#L149) and my try to install it directly into venv from git failed. Is there any way to update typeshed to test new behavior?

**Comment by AlexWaygood** [comment]
In general you can get mypy to use the latest typeshed using [the `--custom-typeshed-dir` command-line argument](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-custom-typeshed-dir): clone typeshed, then use that option to point to your local clone of typeshed. I've never done any hacking on mypyc so I'm not _sure_ if the option works the same way with mypyc, but it certainly doesn't reject the argument if you pass it on the command line.

Unfortunately if I do `mypyc mypyc_weird.py --custom-typeshed-dir <path-to-my-typeshed-clone>`, the compiled module still raises the same exception when I import it. Which is sort of expected -- my PR to typeshed improved the stub for `vars()`, but didn't alter the stub for `type.__dict__` in any way (since that's [already correct over at typeshed](https://github.com/python/typeshed/blob/805519717b7213ed232593931df815fd6c839ff5/stdlib/builtins.pyi#L148-L149)).

It looks like this is ultimately a mypyc bug rather than a typeshed bug.

**Comment by JelleZijlstra** [comment]
Fixing that bug may be quite disruptive; I expect we'll have to get much stricter in typeshed about adding `ClassVar` annotations.

**Comment by AlexWaygood** [comment]
> Fixing that bug may be quite disruptive; I expect we'll have to get much stricter in typeshed about adding `ClassVar` annotations.

I'd like to have a go, anyway. I have some ideas :)

**Comment by JukkaL** [comment]
(I created a new label for mypy issues that are known to cause issues for mypyc users.)
