### ISSUE TITLE
`classmethod`s should not be able to be called on abstract classes

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#14062]
```py
from abc import ABC, abstractmethod

class Foo(ABC):
    @classmethod
    def foo(cls) -> Foo:
        return cls()
    
    @abstractmethod
    def bar(self) -> None:
        ...

Foo.foo() # no error
```
[playground](https://mypy-play.net/?mypy=latest&python=3.10&flags=strict%2Cdisallow-any-expr%2Cwarn-unreachable&gist=0408843a25e954f3018b1cfc80da6edb)

most of the time, `classmethod`s are instantiating the class, so it should not allow you to call them on abstract classes.

i do however think `staticmethod`s should still be allowed as they do not have access to the `cls`

**Comment by JelleZijlstra** [comment]
Classmethods can do other things than instantiating a class. I think this check would be too noisy to be useful.

**Comment by erictraut** [comment]
I agree that this would be too noisy. Recommend closing.
