### ISSUE TITLE
Support PEP 698 – Override Decorator

### ISSUE THREAD

**Issue by tmke8** [python/mypy#14072]
[PEP 698](https://peps.python.org/pep-0698/) adds an `@override` decorator.

Todo:

- [x] basic support for `@override` (done in #14609)
- [ ] optional [strict mode](https://peps.python.org/pep-0698/#strict-enforcement-per-project) (relevant discussion: https://github.com/python/typing/issues/1376 )

Related issue: #1888

**Comment by tmke8** [comment]
The PEP has now been officially accepted for Python 3.12.

**Comment by tmke8** [comment]
Ah, I shouldn't have linked this issue to the PR because there is still a missing piece: a new flag which enforces the use of `@override` on every overriding method.

**Comment by NeilGirdhar** [comment]
FYI: [this discussion](https://github.com/python/typing/issues/1376) may be relevant for whoever implements the flag. 😄

**Comment by cdce8p** [comment]
Just opened #15512 to add a strict flag for method overrides as suggested in the PEP.

**Comment by mttbernardini** [comment]
There seems to be some issue with the way this plays with `--check-untyped-defs`, see [this playground example](https://mypy-play.net/?mypy=latest&python=3.11&flags=check-untyped-defs&gist=6a2e49ffa6670369246e11fcecac37e2):

```python
from typing_extensions import override

class A:
    def f(self, x: int) -> int:
        return 2

class B(A):
    
    @override
    def f(self, x: int): # why `-> int` is not inferred?
        return None # why return type violation is not reported?
    
    @override
    def g(self, y): # why "no base method" is not reported?
        return 4
```

**Comment by bersbersbers** [comment]
Thanks, this is great! I have already added `enable_error_code = ["explicit-override"]` to enable it.

Are there plans for this error code to be included in `strict` mode any time soon?

**Comment by cdce8p** [comment]
> Are there plans for this error code to be included in `strict` mode any time soon?

I don't think that will happen. Just an example, enabling this for [Home Assistant](https://github.com/home-assistant/core) would create 11k+ new errors and that's just one project. It'll probably take quite a long time until all code is sufficiently updated, especially given that `@override` will only be added to the stdlib in Python 3.12.
