### ISSUE TITLE
type hint with "Union" operator doesn't work properly

### ISSUE THREAD

**Issue by djccnt15** [python/mypy#14090]
**Bug Report**

It seems like nested type hint with "Union" operator doesn't work properly

**To Reproduce**

```python
vector = list[int | float]
matrix = list[vector]

def mat_identity(n: int) -> matrix:
    """
    returns n by n sized identity matrix
    """

    I = [[1 if i == j else 0 for j in range(n)] for i in range(n)]
    return I
```

[playground link](https://mypy-play.net/?mypy=latest&python=3.10&gist=35856a154c66c2a93160fb9b4c07b8f2)

**Expected Behavior**

obviously the function shouldn't have any problem, as code below returns no error at all

```python
vector = list[float | int]
matrix = list[vector]

m: matrix = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
```

[playground link](https://mypy-play.net/?mypy=latest&python=3.10&gist=0ab032d22a3c9bbf19c437330c6ed658)

**Actual Behavior**

testing with mypy returns error like below

```
main.py:10: error: Incompatible return value type (got "List[List[int]]", expected "List[List[Union[float, int]]]")  [return-value]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.990
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): default
- Python version used: 3.10, 3.11

**Comment by JelleZijlstra** [comment]
https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance

**Comment by hauntsaninja** [comment]
mypy is able to use type context within an expression, so you could also add a type hint like `I: matrix = [[1 if i == j else 0 for j in range(n)] for i in range(n)]` to make things work
