### ISSUE TITLE
"Missing return statement" in pseudo-abstract methods with empty bodies

### ISSUE THREAD

**Issue by brianmedigate** [python/mypy#14100]
I have a metaclass which inherits from `ABCMeta` (let's call it `MyABCMeta`), with a decorator `@my_abstractmethod` which does some other stuff and then delegates to the original `abstractmethod`.

After upgrading to 0.991 (without configuring `--allow-empty-bodies`), mypy started complaining that the methods marked with `@my_abstractmethod` are missing return statements.

I have a workaround like this:

```python
if TYPE_CHECKING:
    my_abstractmethod = abstractmethod
else:
    def my_abstractmethod(method):
        ...
```

But mypy apparently doesn't follow the assignment. In fact, mypy also complains about this:

```python
abstractmethod_alias = abc.abstractmethod

class Foo(abc.ABC):
    @abstractmethod_alias
    def foo(self) -> int:
        pass
```

Would it be possible to follow the assignment, so that my workaround will work?

**Comment by rhshadrach-8451** [comment]
More generally, a decorator can provide an implementation for a method. With a decorator typed to return a callable with a compatible return type, does it make sense to not flag an empty body?

**Comment by ilevkivskyi** [comment]
There is a simple workaround, use:
```python
if TYPE_CHECKING:
    from abc import abstractmethod as my_abstractmethod
else:
    from abc import abstractmethod  # if needed
    def my_abstractmethod(method):
        ...
```

**Comment by brianmedigate** [comment]
That's the workaround I used to use, but it doesn't exempt the body of the function from needing a return statement.
