### ISSUE TITLE
Paths on commandline not fully described in doc

### ISSUE THREAD

**Issue by ydirson** [python/mypy#14105]
**Documentation**

https://mypy.readthedocs.io/en/latest/command_line.html#specifying-what-to-type-check describes 3 ways to specify code to be checked:
- paths
- `-m` modules
- `-p` packages

Experimentation shows that in 0.991 paths and packages seem to be handled the same (expect from the separators), but some clarification could be useful.

I observed that 0.990 behaved differently (not reporting some (any?) errors) - which is especially confusing as http://mypy-lang.org/ does not even mention 0.990 as having been ever released, even giving as 0.991 release date what looks like the 0.990 one according to git.

**Comment by hauntsaninja** [comment]
0.990 had a bad regression, see e.g. https://github.com/python/mypy/issues/14042

**Comment by ydirson** [comment]
> 0.990 had a bad regression, see e.g. #14042

OK, but the main point of this ticket was about improving the doc the path syntax ;)

(probably it was a mistake from me, trying to discuss it here at the same, that it could be helpful to advertise that 0.991 fixes a bad 0.990 regression - #14042 would likely be a better place, but my search did not find that one)
