### ISSUE TITLE
--use-python-path is an attractive nuisance

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1411]
It seems that many people try to use `--use-python-path` because they see some missing imports (e.g. django, see #1410) and then mypy crashes on some random problem. Maybe we shouldn't have `--use-python-path` at all? @JukkaL, why was it introduced anyway?

**Comment by gvanrossum** [comment]
UPDATE: I think it was introduced in response to https://github.com/python/mypy/issues/486 (the diff was 6230e3f9680b7e0056593bb9f9ae5bbdbf960a58 by the same user). But I wish it never existed -- people are really better off ignoring imports for which no stubs exist than trying to deal with the errors and crashes from analyzing 3rd party (or stdlib) libraries that haven't been made mypy-clean.

**Comment by JukkaL** [comment]
I tend to agree that `--use-python-path` isn't very useful as such. If #638 was implemented (ignoring errors in library modules) and mypy hardly ever crashed, it *might* be useful, but currently it's unlikely to be helpful. Let's just remove it?
