### ISSUE TITLE
Optional type leads to "Too many arguments" error when unpacking tuple

### ISSUE THREAD

**Issue by jevandezande** [python/mypy#14126]
**Bug Report**

Mypy reports `error: Too many arguments for "test"  [call-arg]` for the following code (the code runs correctly).

```
def test(a, b):
    return a + b


x: tuple[float] | None
x = (1,)

test(*x, 2)
```

The following each fix the error, but it doesn't seem consistent with the naming of the error:
- Removing the `Optional` type on x (i.e `x: tuple[float]`)
- Setting `x: tuple[int] | None`
- Setting `x = (1.0,)` (either as a replacement for the line `x = (1,)` or placed after)
- Decreasing the arity of function (i.e. `def test(a):...` and `test(*x)`)

The following do no fix the error, and I don't understand why:
- Setting `x: tuple[float] | None = (1.0,)` and removing following line that set x (unless x is further updated with `x = (1.0,)`)
- Increasing the arity of function (and adjusting the size of the tuple or added arguments, e.g. `def test(a, b, c):...` and `test(*x, 2, 3))

If x is set in the same line as the type is defined (e.g. `x: tuple[float] | None = (1.0,)`) and not changed, the original error occurs, along with the following: `List or tuple expected as variadic arguments  [misc]`

**Your Environment**

Tested with mypy 0.991 in python 3.10 and 3.11.

**Comment by jevandezande** [comment]
Additionally,

```
x: tuple[float] | None = (1.0,)

a, b = *x, 2
```
Results in the following errors when unpacking:

`error: Invalid type 'Union[Tuple[builtins.float], None]' for *expr (iterable expected)`
`error: Need more than 1 value to unpack (2 expected)`

Which is fixed by setting x on a separate line:
```
x: tuple[float] | None
x = (1,)

a, b = *x, 2
```

**Comment by erictraut** [comment]
It appears this bug was fixed in mypy 1.0.0. I'm not able to repro it in that version or any subsequent version.

**Comment by jevandezande** [comment]
I can confirm that the original version of this bug was fixed, but the second version of this (in the first comment) still produces an error as of mypy 1.5.0. Should I file a new issue?

```
x: tuple[float] | None = (1.0,)

a, b = *x, 2
```
Results in the following errors when unpacking:

`error: Invalid type 'Union[Tuple[builtins.float], None]' for *expr (iterable expected)`
`error: Need more than 1 value to unpack (2 expected)`

**Comment by erictraut** [comment]
@jevandezande, that's currently expected behavior. Mypy doesn't currently perform type narrowing on assignment if the assignment is on the same line as the type annotation. This behavior is slated to change (see [this issue] for details), but until it does, you need to move the assignment to a separate line for type narrowing to be applied.

```python
x: tuple[float] | None
x = (1.0,)

a, b = *x, 2
```
