### ISSUE TITLE
Overloaded decorators can hide parameters with default values

### ISSUE THREAD

**Issue by wlritchi** [python/mypy#14144]
**Bug Report**

Some decorators change the type of the decorated function's inputs. Because there is no easy way to describe a "mapping" over a ParamSpec, such decorators may be typed with a series of overloads, one for each number of parameters up to a reasonable maximum:

```python
@overload
def boxed_args(
    func: Callable[[_P1], _R],
) -> Callable[[Box[_P1]], _R]:
    pass

@overload
def boxed_args(
    func: Callable[[_P1, _P2], _R],
) -> Callable[[Box[_P1], Box[_P2]], _R]:
    pass

@overload
def boxed_args(
    func: Callable[[_P1, _P2, _P3], _R],
) -> Callable[[Box[_P1], Box[_P2], Box[_P3]], _R]:
    pass

...
```

When such a decorator is applied to a function with default values for one or more parameters, mypy selects the first matching overload for the decorator, i.e. the overload with only the required parameters. It then forgets about the parameters with default values:

```python
# inferred type (Box[str]) -> None
@boxed_args
def takes_str_and_default_int_decorated(p1: str, p2: int = 404) -> None:
    print(p1, p2)

# does not typecheck
takes_str_and_default_int_decorated(Box("Luc"), Box(0))
```

**To Reproduce**

Complete example [on GitHub](https://github.com/wlritchi/python-tooling-sandbox/blob/variadic-decorator-with-default-params/sandbox/__init__.py)

<details>
<summary>Inline:</summary>

```python
#!/usr/bin/env python3

from abc import ABC
from functools import wraps
from typing import Any, Callable, Generic, TypeVar, overload

_T = TypeVar('_T')


class Box(ABC, Generic[_T]):
    def __init__(self, value: _T):
        self.value = value


_P1 = TypeVar('_P1')
_P2 = TypeVar('_P2')
_P3 = TypeVar('_P3')
_R = TypeVar('_R')


@overload
def boxed_args(
    func: Callable[[_P1], _R],
) -> Callable[[Box[_P1]], _R]:
    pass


@overload
def boxed_args(
    func: Callable[[_P1, _P2], _R],
) -> Callable[[Box[_P1], Box[_P2]], _R]:
    pass


@overload
def boxed_args(
    func: Callable[[_P1, _P2, _P3], _R],
) -> Callable[[Box[_P1], Box[_P2], Box[_P3]], _R]:
    pass


def boxed_args(func: Callable[..., _R]) -> Callable[..., _R]:
    @wraps(func)
    def wrapper(*args: Any) -> _R:
        return func(*(arg.value for arg in args))

    return wrapper


def takes_str_and_default_int(p1: str, p2: int = 404) -> None:
    print(p1, p2)


@boxed_args
def takes_str_and_default_int_decorated(p1: str, p2: int = 404) -> None:
    print(p1, p2)


if __name__ == '__main__':
    # typechecks successfully
    takes_str_and_default_int("Typechecker", 1)
    # does not typecheck
    takes_str_and_default_int_decorated(Box("Luc"), Box(0))
```
</details>

**Expected Behavior**

The inferred type for the decorated function should be overloaded based on each matching overload of the decorator. In the example above, the decorated function should have a type equivalent to `(Box[str]) -> None` overloaded with `(Box[str], Box[int]) -> None`.

**Actual Behavior**

```
sandbox/__init__.py:63: error: Too many arguments for "takes_str_and_default_int_decorated"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.991
- Python version used: 3.10.8

Env initialized via poetry 1.2.2, no flags or command line arguments other than the target directory.

**Additional context**

Pyright and Pyre both have very similar bugs; discussion at microsoft/pyright#4211 and facebook/pyre-check#693 may be relevant if this is a weakness in the Python type system rather than in mypy's implementation.

**Comment by JelleZijlstra** [comment]
As @erictraut explained on the linked pyright issue, this isn't a bug.
