### ISSUE TITLE
Improper handling of Optional values in dict with variable as key

### ISSUE THREAD

**Issue by racinmat** [python/mypy#14164]
**Bug Report**

When I have `Dict[str, Optional[int]]` and branch code by `if .... is not None`, the mypy should properly inferthat value can not be `None`.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=23466db45f1c95cfab36bbb3361435a1

**Expected Behavior**

I expect the code not to throw errors, because the branching makes sure value is not None.

**Actual Behavior**

See output of the playground.

**Your Environment**

See the playground.

**Comment by erictraut** [comment]
I think mypy is working as intended here. Recommend closing.
