### ISSUE TITLE
mypy ignores isinstance

### ISSUE THREAD

**Issue by e2t** [python/mypy#14197]
After passing `isinstance(obj, dict)` successfully, obj is certainly of type dict.
mypy gives warnings as if there was no check.

**To Reproduce**

```python
from typing import Callable

b: list[Callable[[str], str] | str] = []

def myfun(a: dict[str, str] | str) -> None:
    if isinstance(a, dict):
        b.append(lambda key: a[key])
    else:
        b.append(a)

myfun({"key": "hello"})
myfun("world")
print(b[0]("key"), b[1])  # hello world
```

**Expected Behavior**

There are no warnings.

**Actual Behavior**

```
1.py:7: error: Invalid index type "str" for "Union[Dict[str, str], str]"; expected type "Union[SupportsIndex, slice]"  [index]
1.py:13: error: "str" not callable  [operator]
Found 2 errors in 1 file (checked 1 source file)
```

**Environment**

- Mypy version used: mypy 0.991 (compiled: no)
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: Python 3.11.0

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/stable/common_issues.html#narrowing-and-inner-functions
