### ISSUE TITLE
Crash with recursive namedtuple when generating a report

### ISSUE THREAD

**Issue by johnnv1** [python/mypy#14200]
**Bug Report**

Recursive `NamedTuple` causes mypy to crash with `Segmentation fault (core dumped)`  when running with `--cobertura-xml-report ` -- I haven't tested them all, but they seem to fail with other report flags as well (`--any-exprs-report`, `--html-report`, `--xml-report`)

**To Reproduce**

```python
from typing import NamedTuple
from typing import Optional

class Example(NamedTuple):
    data: Optional['Example']

item = Example(data=Example(None))
```

Then run `$ mypy --cobertura-xml-report ./`

**Expected Behavior**
...

**Actual Behavior**

`Segmentation fault (core dumped)`

**Your Environment**

- Mypy version used: 0.991
- Mypy command-line flags: `--cobertura-xml-report` -- also seems to crash with other reports flags
- Python version used: 3.7, 3.8, 3.9, 3.10

**Comment by ilevkivskyi** [comment]
It doesn't crash on current master (and generates a ~reasonable report). I guess I fixed this when fixing another (plain text) report.
