### ISSUE TITLE
Cannot resolve recursive/cyclic definitions (v0.991, Python 3.8/3.9)

### ISSUE THREAD

**Issue by bartfeenstra** [python/mypy#14219]
**Bug Report**

Mypy fails to check recursive/cyclic type aliases, even with https://github.com/python/mypy/issues/731 being part of v0.991. However, this happens on Python 3.8 and 3.9 only (and possibly below), but not on 3.10 or 3.11.
Example:
```python
RecursiveTypeAlias: TypeAlias = Union[bool, int, float, str, Sequence['RecursiveTypeAlias']]
```
for which mypy raises `error: Cannot resolve name "RecursiveTypeAlias" (possible cyclic definition)  [misc]`.

**To Reproduce**
- Create an environment with:
  - Mypy v0.991
  - Python 3.8 or 3.9
  - typing_extensions 4.4.0
- Create a Python file with the offending type alias. See https://github.com/bartfeenstra/mypy-type-alias/blob/main/mypy-type-alias/main.py for additional imports for cross-Python-version compatibility.
- Run mypy without any additional options or arguments

Alternatively, clone https://github.com/bartfeenstra/mypy-type-alias and run `tox`.

**Expected Behavior**
Mypy not raising any errors for recursive/cyclig type aliases and correctly parsing them as it does on Python 3.10 and 3.11.

**Actual Behavior**
Mypy fails on recursive/cyclic type aliases with the error `error: Cannot resolve name "RecursiveTypeAlias" (possible cyclic definition)  [misc]`.

**Comment by bartfeenstra** [comment]
I can confirm this works with mypy commit `3a3cf412b278ee7bf710742b168beed41c1c02f2` in combination with the imports turned around. Thanks!

**Comment by ssbarnea** [comment]
For reference, this is the full solution that seems to currently work with py39+ and also pass mypy and ruff:

```
from __future__ import annotations
from collections.abc import Mapping, Sequence
from typing import Any, Union

try:
    from typing_extensions import TypeAlias
except ImportError:
    from typing import TypeAlias  # type: ignore[no-redef,attr-defined]

JSON: TypeAlias = Union[dict[str, "JSON"], list["JSON"], str, int, float, bool, None]
JSON_ro: TypeAlias = Union[
    Mapping[str, "JSON_ro"],
    Sequence["JSON_ro"],
    str,
    int,
    float,
    bool,
    None,
]
```
