### ISSUE TITLE
(🎁) Validate arguments to `dataclasses` utility functions `replace` and `fields`

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#14215]
Mypy should special case these functions to only work with dataclasses.
```py
from dataclasses import dataclass, replace

@dataclass
class D:
    pass
class C:
    pass

replace(D())
replace(C())  # TypeError: replace() should be called on dataclass instances
```
[playground](https://mypy-play.net/?mypy=latest&python=3.11&flags=strict)

PS: PyCharm correctly reports these

**Comment by jakezych** [comment]
Hello! I'm working with a team of CMU students and we're looking to contribute to this issue for a class project. I was wondering if anyone could give us some pointers on where to get started on this issue?

**Comment by A5rocks** [comment]
I haven't touched the mypy code in a while but there's a dataclass plugin in the source which would be the first place I would look. Barely knowing anything my instinct is either to make dataclass generated classes inherit from some pretend class if there isn't already some marker (there probably is lol), and then... I don't know, patch mypy's typeshed? Maybe override replace calls? I'd look at the plugin API to see if that's even possible.

But please take everything I said with a grain of salt!

**Comment by AlexWaygood** [comment]
Looks like there's a lot of interest in fixing this! We've already had two PRs filed over at mypy and one over at typeshed, so I think we probably don't need any more PRs for this one -- let's concentrate on reviewing what we've already got 😀

**Comment by AlexWaygood** [comment]
Fixed in https://github.com/python/typeshed/pull/9362
