### ISSUE TITLE
Type inference and hasattr

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1424]
I just encountered code like this:

```
if hasattr(x, 'initialize'):
     x.initialize()
```

The type of `x` was an ABC but it doesn't include `initialize`. This can be easily worked around by rewriting it like this:

```
if hasattr(x, 'initialize'):
     cast(Any, x).initialize()
```

However, mypy could do better, plausibly. For example:
- If `x` has a union type, infer only union item types with attribute `initialize` after the `hasattr` check. So if type of `x` is `Union[str, X]` and `X` has `initialize`, infer type of `x` to be `X` in the if body.
- Allow specifying "potentially undefined" attributes in types. Accessing these requires a `hasattr` check (a little like `Optional[...]` requiring something like an `is not None` check). Not sure what the syntax for this would be like. It would be nice to support these in ABCs as well.

**Comment by timabbott** [comment]
I ran into an instance of this in the Zulip test runner code, where we add an attribute to a test method via a decorator to track the fact it's expected to be slow, and then check it like this:
```
def enforce_timely_test_completion(test_method, test_name, delay):                                                                                                     
    # type: (Callable[[], None], str, float) -> None                                                                                                                   
    if hasattr(test_method, 'expected_run_time'):                                                                                                                      
        # Allow for tests to run 50% slower than normal due                                                                                                            
        # to random variations.                                                                                                                                        
        max_delay = 1.5 * test_method.expected_run_time
```
See https://github.com/zulip/zulip/blob/master/zerver/lib/test_runner.py for the full code.

**Comment by gvanrossum** [comment]
In general i despise hasattr() checks; it's usually much better to add a
class level initialization to None and check for that.

On Saturday, June 4, 2016, Tim Abbott <notifications@github.com> wrote:

> I ran into an instance of this in the Zulip test runner code, where we add
> an attribute to a test method via a decorator to track the fact it's
> expected to be slow, and then check it like this:
>
> def enforce_timely_test_completion(test_method, test_name, delay):
>     # type: (Callable[[], None], str, float) -> None
>     if hasattr(test_method, 'expected_run_time'):
>         # Allow for tests to run 50% slower than normal due
>         # to random variations.
>         max_delay = 1.5 * test_method.expected_run_time
>
> See https://github.com/zulip/zulip/blob/master/zerver/lib/test_runner.py
> for the full code.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/mypy/issues/1424#issuecomment-223795217>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACwrMgWW3Km5ug5KWyGjSWJtCKdAsPpuks5qIme4gaJpZM4INlY->
> .
>


-- 
--Guido (mobile)

**Comment by timabbott** [comment]
Just to be clear, these are attributes monkey-added to a function, not a class, so I don't think that solution would work here.

**Comment by gvanrossum** [comment]
So there's no place to declare their type anyway. Maybe using three-arg
getattr is better?

--Guido (mobile)

**Comment by jhance** [comment]
> If x has a union type, infer only union item types with attribute initialize after the hasattr check. So if type of x is Union[str, X] and X has initialize, infer type of x to be X in the if body.

Likely has false positives if one of the elements on the union is an ABC

**Comment by ikelos** [comment]
I was wondering whether the protocol/structural subtyping work could be used on a `hasattr` call to in some way to coerce the type into one that accepts the attribute within that scope?

**Comment by isidentical** [comment]
This also affects using features from future python versions (I'm aware that we can do sys.version_info compare but IMHO this case shouldn't give errors)
```py
import ast
if hasattr(ast, "unparse"):
    print(ast.unparse)
else:
    print("no")
```

**Comment by TornaxO7** [comment]
This might be interesting for some people who encounters this problem. You could use the [getattr](https://docs.python.org/3/library/functions.html#getattr) function to get the value and set the default value to `None` (or any other value to check) and add an `if` condition afterwards to do some other action if this attribute doesn't exist. Herer's a little example:

```py

unknown = getattr(<object>, 'valname', None)
if unknown is None:
    # your action if it's None
```

**Comment by alexmojaki** [comment]
Based on when the fix above was merged, it should be in mypy 0.982, right? It still doesn't seem to be working, e.g. this:

```python
class C:
    pass

c = C()

setattr(c, "foo", 42)
if hasattr(c, "foo"):
    print(c.foo)
```

still leads to `error: "C" has no attribute "foo"`

**Comment by JelleZijlstra** [comment]
It's not in 0.982. In the https://github.com/python/mypy/commit/b29051c8979ae83835204f7813e4307b05d73156 page you can see the tags that include the commit, and there aren't any. (Example commit that was in 0.981/2: https://github.com/python/mypy/commit/0ec789d5322b6bc388ca045544beb57759aee457)

**Comment by BlackHC** [comment]
Any updates on this? When will the fix make it into mypy? Thanks so much!

**Comment by jenshnielsen** [comment]
@BlackHC if you follow @JelleZijlstra's instructions above you can see that it should be in mypy 0.991

**Comment by BlackHC** [comment]
Thanks! Upgraded my package dependencies and it works perfectly now!

(You made me realize that `poetry update` was not doing what I thought it was doing and that I had to install the `poetry up` plugin. Apologies for my confusion around this!)
