### ISSUE TITLE
Enums with only one member do not exhaustively match correctly

### ISSUE THREAD

**Issue by johnthagen** [python/mypy#14264]
**Bug Report**

Enums with only one member do not exhaustively `match` correctly.

**To Reproduce**

```python
from enum import Enum, auto

from typing_extensions import assert_never


class Color(Enum):
    Red = auto()


def f(color: Color) -> None:
    match color:
        case Color.Red:
            print("red")
        case _ as unreachable:
            assert_never(unreachable)
```

**Expected Behavior**

No type checking errors.

**Actual Behavior**

```
$ mypy main.py
main.py:15: error: Argument 1 to "assert_never" has incompatible type "Color"; expected "NoReturn"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

```
$ pip list
Package           Version
----------------- -------
mypy              0.991
mypy-extensions   0.4.3
pip               22.3.1
setuptools        65.6.3
tomli             2.0.1
typing_extensions 4.4.0
wheel             0.38.4
```

- Mypy version used: 0.991
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.8

**Additional Context**

What's strange is that if the `Enum` has at least 2 members, everything works correctly:

```py
from enum import Enum, auto

from typing_extensions import assert_never


class Color(Enum):
    Red = auto()
    Blue = auto()


def f(color: Color) -> None:
    match color:
        case Color.Red:
            print("red")
        case Color.Blue:
            print("blue")
        case _ as unreachable:
            assert_never(unreachable)
```

**Comment by AlexWaygood** [comment]
It looks like the bug is specific to pattern-matching; mypy has no problems with this version of the same function using `if/else` idioms (and it will correctly identify the `else` branch as unreachable if you add a call to `reveal_type`):

```python
from enum import Enum, auto

from typing_extensions import assert_never


class Color(Enum):
    Red = auto()


def f(color: Color) -> None:
    if color is Color.Red:
        print("red")
    else:
        assert_never(color)
```

https://mypy-play.net/?mypy=latest&python=3.11&gist=ca293bc0ccb5ec9c77af029f0c95360e

**Comment by thomkeh** [comment]
Same issue? #14109

**Comment by AlexWaygood** [comment]
> Same issue? #14109

Yup, thanks @thomkeh!
