### ISSUE TITLE
Cannot annotate a "class as class attribute" to be both "valid as a type" and typechecked in derived classes

### ISSUE THREAD

**Issue by ydirson** [python/mypy#14278]
It seems we cannot annotate a class attribute that is a type, and have at the same time ability to use it as a type (like declared as `TypeAlias`) and to typecheck that derived classes properly provide a subclass of their parent's attribute.

Illustration of the type errors I want to catch:
```
class N0:
    pass

class A:
    N: type[N0] = N0

class N:
    pass

class B(A):
    N = N
```
mypy 0.991 properly reports that `B.N` is not a subclass of `A.N`:
```
error: Incompatible types in assignment (expression has type "Type[N]", base class "A" defined the type as "Type[N0]")
```

Naturally this is meant to be fixed eg. like:
```
class N(N0):
    pass

class B(A):
    N = N
```

But then if I want to avoid duplication of information (i.e. don't want to chase all `N0` occurrences should the `A.N` implementation detail chance, i.e. remove that implementation detail from my public API), with the following:
```
class N(A.N):
    pass

class B(A):
    N = N
```
then mypy refuses with:
```
error: Variable "test-mypy-nested-type.A.N" is not valid as a type  [valid-type]
note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
error: Invalid base class "A.N"  [misc]
```

But then, if I follow this advice and use `TypeAlias` (or even `TypeAlias[N0]`, which is not rejected, though I can only find the syntax in [rejected ideas in PEP613](https://peps.python.org/pep-0613/#rejected-ideas)) as annotation for `A.N` instead of `type[N0]`, then mypy won't catch the subclassing error of my first example.

It also won't catch it if I define `N` as a nested class, as:
```
class B(A):
    class N:
        pass
```

**Comment by erictraut** [comment]
I think mypy is working correctly in all of these cases. Recommend closing.
