### ISSUE TITLE
Errors non-reproducible locally

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#14282]
Something odd seems to have happened after multidict 6.0.3 was released.

Since then, aiohttp has been getting a few type errors in the CI. e.g. https://github.com/aio-libs/aiohttp/actions/runs/3669704915/jobs/6203726675

The cause of these errors is unclear, the only notable change I can find is modernising the syntax, the actual values don't appear to have changed, so I'd expect mypy to produce the same results we had before: https://github.com/aio-libs/multidict/pull/758/files

The main problem though, is that I can't reproduce any of these errors locally, so I can't even start figuring out what is wrong. When run locally with 6.0.3 installed, I get no errors.

**Comment by webknjaz** [comment]
@Dreamsorcerer since we now know it's because of the py310+ imports, this can be closed now.

**Comment by Dreamsorcerer** [comment]
Yep. Different results were caused by the underlying version of Python that mypy was run on, which we didn't expect to result in different results when analysing the same code. Not sure if that is expected behaviour, or if there should be a bug report for that.
