### ISSUE TITLE
NoReturn as covariant type argument in inheritance is assignable to type parameter when it should not be (apparently)

### ISSUE THREAD

**Issue by schuelermine** [python/mypy#14287]
**Bug Report**

(with `--strict` enabled)

If you inherit from `Foo[NoReturn]` where `Foo[T]` is covariant in `T`, functions returning `Foo[T]` are fine returning `Foo[NoReturn]` instead.

It was my opinion until recently that this is correct behaviour, but I have since been corrected by the developers of Pyright, which, apparently, does this correctly. Please see https://github.com/microsoft/pyright/issues/4309

(A clear and concise description of what the bug is.)

**To Reproduce**

```python
from __future__ import annotations
from typing import Generic, NoReturn, TypeVar
T = TypeVar("T", covariant=True)
U = TypeVar("U")
class Foo(Generic[T]):
    pass
class Bar(Foo[NoReturn]):
    pass
def mkFoo(x: U | None) -> Foo[U]:
    if x is None:
        return Bar()
    return Foo()
```

**Expected Behavior**

mypy flags the call to `Bar()` as incompatible with the type `Foo[U]`

**Actual Behavior**

No type error is returned.

**Your Environment**

- Mypy version used: mypy 0.991 (compiled: yes)
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files): `strict = true`
- Python version used: Python 3.10.8

**Comment by JelleZijlstra** [comment]
I'm not sure I see the bug here. A `Foo[NoReturn]` is compatible with a `Foo[U]` because `NoReturn` is compatible with any type that `U` could be. It would similarly be legal to return `Foo[Any]`.

**Comment by erictraut** [comment]
Thinking about this more, I think my analysis was wrong in the linked pyright issue. For covariant type arguments, `NoReturn` should be assignable to type `U`. Mypy gets this right, so you can close this issue. I'll re-open the pyright issue.
