### ISSUE TITLE
Recursive protocols do not work in methods

### ISSUE THREAD

**Issue by unparalleled-js** [python/mypy#14291]
**Bug Report**

When you have a method that expects a protocol arg that is recursive, models that fit the protocol or marked as the wrong type

**To Reproduce**

Run `mypy` on the following script:

```python
from typing import Protocol, List


class CallTree(Protocol):
    name: str
    subcalls: List["CallTree"]


class MyCallTree:
    name = "myMethod"
    subcalls: List["MyCallTree"] = []


def get_subcall_len(call_tree: CallTree) -> int:
    return len(call_tree.subcalls)


if __name__ == "__main__":
    tree= MyCallTree()
    result = get_subcall_len(tree)
    print(result)  # 0
```

**Expected Behavior**

mypy tells me everything gooood

**Actual Behavior**

```
recursiveproto.py:20: error: Argument 1 to "get_subcall_len" has incompatible type "MyCallTree"; expected "CallTree"  [arg-type]
recursiveproto.py:20: note: Following member(s) of "MyCallTree" have conflicts:
recursiveproto.py:20: note:     subcalls: expected "List[CallTree]", got "List[MyCallTree]"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: mypy 0.991 (compiled: yes)
- Mypy command-line flags: just the script name
- Mypy configuration options from `mypy.ini` (and other config files): n/a
- Python version used: Python 3.9.13

**Comment by hauntsaninja** [comment]
So I think mypy is correct here, because list is invariant. E.g. a function that takes CallTree could add some other kind of CallTree to a MyCallTree's subcalls.

cc @erictraut since I think pyright handles this incorrectly

**Comment by erictraut** [comment]
@hauntsaninja, it's possible that pyright is missing a check here, but I'm not sure what situation you have in mind. The class in question (`MyCallTree`) doesn't provide any method that accepts a `CallTree` parameter. Even if it did, that method wouldn't be able to append that value onto the `subclass` list without generating a type violation because of the invariance of `list`. Perhaps you could provide a code sample that demonstrates the problem you have in mind?

**Comment by hauntsaninja** [comment]
```
from typing import Protocol, List

class CallTree(Protocol):
    name: str
    subcalls: List["CallTree"]

class MyCallTree:
    name = "myMethod"
    subcalls: List["MyCallTree"]
    
class OtherCallTree:
    name: str
    subcalls: List["CallTree"]

def bad(ct1: CallTree, ct2: CallTree):
    ct1.subcalls.append(ct2)

mct: MyCallTree = MyCallTree()
oct: OtherCallTree = OtherCallTree()
bad(mct, oct)
```

**Comment by erictraut** [comment]
Yep, I agree that pyright is missing a check here. I've filed [this bug](https://github.com/microsoft/pyright/issues/4332) to track the issue.

Mypy is correctly detecting this potential type violation, so I agree this isn't a mypy bug.

**Comment by unparalleled-js** [comment]
Does anyone have any advice on a recursive type structure that would fit my use-case then?

Here is more details about my scenario:

* I have 1 Python package that emits certain objects (e.g. `MyCallTree`).
* I have another Python package with an abstract method that takes in an object like `MyCallTree` but it is not limited to the objects from the first Python package... It can also define its own, default ones... 

How can I define my abstract method accordingly?

**Comment by unparalleled-js** [comment]
> E.g. a function that takes CallTree could add some other kind of CallTree to a MyCallTree's subcalls.

I need my function to work on all types of CallTrees, even mix-n-matched. Basically, I need to define a baseclass / abstract classwithout the first python package having access to that baseclass / abstractclass. I thought protocol is made for this.

**Comment by hauntsaninja** [comment]
Use the following protocol:
```
from typing import Protocol, Sequence

class CallTree(Protocol):
    name: str
    @property
    def subcalls(self) -> Sequence["CallTree"]: ...
```
