### ISSUE TITLE
Infinite loop 

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#14292]
MyPy seems to never terminate when run on https://github.com/NeilGirdhar/tjax/tree/mypy_problem

```shell
pip install poetry
git clone git@github.com:NeilGirdhar/tjax.git
cd tjax
git switch mypy_problem
poetry install
# Installing mypy master doesn't seem to help at this time.
mypy tjax  # Never terminates
```
The problem seemed to have happened in the last commit or two, so bisection might be the easiest way to track this down.

**Comment by NeilGirdhar** [comment]
Never mind, I just wasn't patient enough!

**Comment by hauntsaninja** [comment]
If it's a performance regression that would also be interesting (you may need to use `--no-incremental` to check for perf regressiosn)

**Comment by NeilGirdhar** [comment]
@hauntsaninja So I just use `--no-incremental` and run with different versions of MyPy to check for performance differences?  I'm happy to do that from now on and report any issues I run into. 😄
