### ISSUE TITLE
typing_extensions TypeVar seems to be unsupported

### ISSUE THREAD

**Issue by evtn** [python/mypy#14312]
**Bug Report**

Mypy doesn't support `typing_extensions.TypeVar` at all

**To Reproduce**

[Playground](https://mypy-play.net/?mypy=latest&python=3.11&gist=e1e77a65ff20e0f16cd37281f18b95be)

```python
from typing import Generic
from typing_extensions import (
    TypeVar,
)

T = TypeVar("T")

class A(Generic[T]):
    def __init__(self, value: T):
        self.value = value

a: A = A(8)
b: A[str] = A("")
```

**Expected Behavior**

This code should work fine (importing `TypeVar` from `typing` works, but my actual use case depends on `default` argument of `TypeVar`, so I can't use `typing.TypeVar`)

**Actual Behavior**

```
main.py:8: error: Free type variable expected in Generic[...]  [misc]
main.py:9: error: Variable "__main__.T" is not valid as a type  [valid-type]
main.py:9: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
main.py:13: error: "A" expects no type arguments, but 1 given  [type-arg]
Found 3 errors in 1 file (checked 1 source file)
```

**Your Environment**

mypy Playground, latest mypy (0.991)

**Comment by JelleZijlstra** [comment]
This should be an easy fix if you're up for it. For inspiration, you can look at the commit adding support for `typing_extensions.overload`: https://github.com/python/mypy/commit/0df8cf532918f888610a5afd7bb88192712de984.

**Comment by JelleZijlstra** [comment]
Yes, that would be much harder. :) I think @Gobot1234 already has a draft implementation of PEP 696 for mypy.

**Comment by Gobot1234** [comment]
https://github.com/Gobot1234/mypy/tree/TypeVar-defaults is my draft implementation of PEP 696, its not bug free and is more lax than the current specification but it should work for most basic things.

**Comment by cdce8p** [comment]
I opened #14313 to add basic support for the `typing_extensions` variant. This doesn't include `default` just yet though.

@Gobot1234 Would you be able to rebase your `TypeVar-defaults` branch? A lot has happened in the last 2 months and it got a bit out of sync. That would make it much easier to see how we can add it to mypy.

**Comment by Gobot1234** [comment]
@cdce8p should be done now, not sure how out of sync everything is, it sure does look like a lot changed
