### ISSUE TITLE
"Make mypy more positive #7368" breaks CI/CD workflow

### ISSUE THREAD

**Issue by snowyurik** [python/mypy#14349]
**Bug Report**
Unwanted output on success. However I need to be able to capture both error message and any script output on failure.

**To Reproduce**
 - create valid python script
 - run `mypy script.py`
 
**Expected Behavior**
return empty string and status 0

**Actual Behavior**
returned "Positive" string "Success: no issues found in 1 source file"

**Your Environment**
- Mypy version used: 0.982

**Suggestion**
You can use something like 'mypy --cicd script.py' to switch between "positive" and useful mode.

**Comment by JelleZijlstra** [comment]
Why can't you rely on the exit status 0 for determining whether mypy was successful? What is the concrete problem here?

**Comment by hauntsaninja** [comment]
The concrete problem is that [OP is rather rude](https://github.com/python/mypy/issues/7368#issuecomment-1365449386). If OP read the docs they'd know there's a way to remove the summary message.

**Comment by snowyurik** [comment]
I'm relying on exit status 0, yes. This is exactly what I want.
But in case of status 0, I need empty stdout.

ok, i can do 
out=`mypy ...` ; if [ $? -nq 0]; then echo $out; fi

But.. i still think that quiet mode is mush-have feature and it's much more important than "being positive".
Why do you exchange functionality for abstract idea of emotional comfort? That offends my engineering feelings, bro )

**Comment by snowyurik** [comment]
So --no-error-summary is quiet mode? Ok...
