### ISSUE TITLE
Check for redefinition of function uses contravariance in return type instead of covariance

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1434]
Two classes:
```
class C:
    pass

class D(C):
    pass
```
Two functions:
```
def f() -> C:
    pass

def g() -> D:
    pass
```
Now use conditional redefinition:
```
if True:
    v3 = f
else:
    def v3() -> D:
        pass
```
This should be correct, but we get an error on `def v3() -> D`:
```
error: Incompatible redefinition (original type Callable[[], C], redefinition with type Callable[[], D])
```
OTOH if we reverse roles we don't get an error:
```
if True:
    v3 = g
else:
    def v4() -> C:  # No error here?!
        pass
```
The code for regular assignment gets it right:
```
v1 = f
v1 = g  # No error

v2 = g
v2 = f  # Error here
```
The error on the last line is:
```
error: Incompatible types in assignment (expression has type Callable[[], C], variable has type Callable[[], D])
```

**Comment by gvanrossum** [comment]
@JukkaL If you agree, this is probably a simple reversal of a subtype check? Or am I missing something? (Co/contravariance always gives me a headache.)

**Comment by JukkaL** [comment]
Yeah, conditional redefinition with a narrower return type should be okay. The subtype check seems to have been reversed.

More generally, the order of definition vs. redefinition shouldn't matter. Mypy should pick the more general type as the type of the function. However, this is a separate issue.
