### ISSUE TITLE
Type 'type' inferred for a collection of types

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1437]
Mypy infers the type `type` for type objects in a collection, even when a more specific type would be possible. Example:

```
class A: pass

class B(A):
    def __init__(self, x: int) -> None: pass

class C(A):
    def __init__(self, x: int) -> None: pass

a = [B, C]
a[0](1)  # "type" not callable
```

A better type would be something like `Callable[[int], A]` with `fallback` attribute set to `builtins.type` (also we could preserve keyword arg names).

In more technical terms, `join_types` doesn't do the right thing when given two type object types.

**Comment by JukkaL** [comment]
Inferring `Type[CommonBaseClass]` would be reasonable, at least unless that base class has an incompatible `__init__` signature. When `__init__` signatures vary, things can get trickier.

**Comment by gvanrossum** [comment]
Yeah, but there are other things you can do with classes, e.g. call some class method. Anyway, we're never going to solve the "varying `__init__` signature" problem completely, so I prefer to ignore it. (Maybe eventually we could add a way to declare that subclasses must have a compatible `__init__` signature?)

**Comment by elazarg** [comment]
I can't reproduce this error.

**Comment by ilevkivskyi** [comment]
Currently the revealed type of ``a[0]`` is ``def (x: builtins.int) -> __main__.A``, this is reasonable I think.
