### ISSUE TITLE
Method must have at least one argument [misc]

### ISSUE THREAD

**Issue by Luiz-Cruz** [python/mypy#14385]
I have the following code:
```

class SpreadsheetInterface(ABC):
    
    @abstractmethod
    def is_page_account():
        pass
```

But im receiving an error aside of the code 

Method must have at least one argument [misc]

How do i fix this message?

**Comment by hauntsaninja** [comment]
`def is_page_account(self):`

**Comment by Luiz-Cruz** [comment]
thanks, it works!

**Comment by Luiz-Cruz** [comment]
I'm new to Python using OOP, so I missed this error, thanks!

**Comment by hauntsaninja** [comment]
Sure, happy to help! Just opened a PR to improve the error message here: https://github.com/python/mypy/pull/14386
