### ISSUE TITLE
Default value for Generic self is erased by @dataclass

### ISSUE THREAD

**Issue by Ovsyanka83** [python/mypy#14382]
Note that pyright has a similar behavior so I am not sure whether it is a bug per se but I do believe that it is an incorrect behavior.

**Bug Report**

It is possible to specify the default value for a generic self using `__init__` parameter type hint or `__new__` return type hint. However, when a `@dataclass` decorator is applied to the class and when it generates `__init__`, the `__new__` definition gets erased.
 
**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=13b4e50085788299b532d56cf70c3eb8

**Expected Behavior**
Mypy must show:
```
main.py:22: note: Revealed type is "__main__.User[Literal['NotLoggedIn']]"
```

And it does show it if the `@dataclass` gets commented out, `init=False` is passed to the dataclass, or if the following `__init__` is added to the class:
```python
def __init__(self: "User[Literal['NotLoggedIn']]", name: str) -> None:
    self.name = name
```

**Actual Behavior**
```
main.py:21: error: Need type annotation for "f"  [var-annotated]
main.py:22: note: Revealed type is "__main__.User[Any]"
```
**Your Environment**

- Mypy version used: 0.991
- Python version used: 3.11

**Relevant links**

https://github.com/python/mypy/issues/4236

**Comment by Ovsyanka83** [comment]
@erictraut I decided to go back and check whether I'll be able to use typevardefaults with the latest pyright and succeeded.

And it does solve my problem in its entirety. Take a look at the modified code that reveals the expected type:

```python
from dataclasses import dataclass
from typing import Generic, TypeVar, cast

from typing_extensions import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    T = TypeVar("T", bound=Literal["LoggedIn", "NotLoggedIn"], default=Literal["NotLoggedIn"])


@dataclass
class User(Generic[T]):
    name: str

    def log_in(self) -> "User[Literal['LoggedIn']]":
        return cast(User[Literal["LoggedIn"]], self)

    def scream(self: "User[Literal['LoggedIn']]") -> None:
        print(f"{self.name} screams!")


f = User("admin")
reveal_type(f)
```

**Comment by JelleZijlstra** [comment]
(Also, to be clear, PEP 696 is @Gobot1234's work, not mine; I am just the PEP sponsor.)

**Comment by hauntsaninja** [comment]
Closing in favour of whatever issue is tracking 696
