### ISSUE TITLE
Segfault, recursive TypedDicts, --html-report option

### ISSUE THREAD

**Issue by si-23** [python/mypy#14429]
**Bug Report**

If you run mypy with "--html-report" opt on recursive TypedDicts you get a segmentation fault.
Without "--html-report" opt the errors does not happen.

**To Reproduce**

Add a file with the following content:
```python
#!/usr/bin/env python3

from __future__ import annotations
from typing import TypedDict

class MyTree(TypedDict):
    my_tree: dict[str, MyTree]

MyTree(my_tree={})
```

Run mypy
```bash
$ mypy --html-report /tmp /path/to/test_my_tree.py
Segmentation fault (core dumped)

$ mypy /path/to/test_my_tree.py
Success: no issues found in 1 source file
```

**Expected Behavior**

I expect no error as without "--html-report" opt.

**Actual Behavior**

It produces a segmentation fault.

**Your Environment**

- Mypy version used: 0.991
- Mypy command-line flags: --html-report
- Mypy configuration options from `mypy.ini` (and other config files): -
- Python version used: 3.10.6

**Comment by hauntsaninja** [comment]
Thanks for the report, I think this is fixed on master
