### ISSUE TITLE
Parameter type mismatches only flagged at top level

### ISSUE THREAD

**Issue by kalafut** [python/mypy#1443]
I'm brand new to mypy and this scenario is so simple that I assume I'm doing something wrong. Can't figure it out though. I'm using version 0.3.1 with Python 3.5.1. I'm very interested in using mypy to check function signature mismatches, but it only seems to be working for top level invocations:

```
def foo(a: str) -> str:
    return "Hello"

def bar():
    foo("a", "b") # error: Too many arguments for "foo"   (good)
    foo(5)        # <nothing>   (bad)

foo(5)            # error: Argument 1 to "foo" has incompatible type "int"; expected "str" (good)
```

Why doesn't `foo(5)` within `bar()` cause an error?

Thanks,
Jim

**Comment by gvanrossum** [comment]
You should add an annotation to bar. Probably `def bar() -> None:`. (It's actually arguably wrong that you get the first error, and in the next release you won't get it.)

**Comment by kalafut** [comment]
Thank you.
