### ISSUE TITLE
Syntax error when `type` in commented out code

### ISSUE THREAD

**Issue by mbrancato** [python/mypy#14431]
**Bug Report**

I get a syntax error running `mypy` on `my_app.py`, but `python` reports no syntax error. This is due to the word `type` being in the comment line. I've made a minimal example below.

**To Reproduce**

```python
# class A():
#     type: Optional[str] = field(
#         default=None,
#     )

pass
```

**Expected Behavior**

This is commented code and should just be ignored. I ran across is testing a file that had a large chunk of code commented out.

**Actual Behavior**

```
mypy my_app.py
my_app.py:2: error: invalid syntax
Found 1 error in 1 file (errors prevented further checking)
```

**Your Environment**

- Mypy version used: `mypy 0.991 (compiled: yes)`
- Mypy command-line flags: 
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: `Python 3.10.9 (main, Jan 11 2023, 15:12:53) [GCC 10.2.1 20210110] on linux`

**Comment by JelleZijlstra** [comment]
You have created a Python 2-style type comment. We're discussing deprecating support for those in #12947. Unfortunately, for now we can't really change this behavior.

**Comment by JelleZijlstra** [comment]
#13177 specifically would help you.
