### ISSUE TITLE
Type check str format calls

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1444]
Mypy has some special logic to type check `%` string formatting. It would be nice to also get errors for invalid `format` calls. Examples:

```
'{} does not exist'.format(1, 2)   # too many arguments
'i like {target}'.format(tagret=name)   # misspelled keyword argument
```

This could be pretty useful since `format` calls often happen in exception and error handlers which are often not tested carefully.

**Comment by JukkaL** [comment]
This could be supported using the plugin system, but it we may have to extend it a little to support this use case.

**Comment by gvanrossum** [comment]
Maybe a good test of the flexibility of the plugin system would be to see how it can be used to do some *existing* things that are currently done with custom checks in various places. This could include '%' formatting, and even TypedDict and NamedTuple.

**Comment by ilevkivskyi** [comment]
> and even TypedDict and NamedTuple

This may be a too high bar. These two require lots of special-casing deep inside second and third semantic passes.

**Comment by JukkaL** [comment]
% formatting should be a good candidate but I agree with @ilevkivskyi that TypedDict and NamedTuple (maybe also Enum) might be too tricky, at least for now. I'd rather look at Django models or attrs (https://pypi.python.org/pypi/attrs/15.2.0) first.

**Comment by JelleZijlstra** [comment]
This is a duplicate of #470 (although this one has more discussion).
