### ISSUE TITLE
Casting from Any to Literal does not work

### ISSUE THREAD

**Issue by JanEricNitschke** [python/mypy#14446]
**Bug Report**

Mypy does not respect casting from Any.

**To Reproduce**

```python
import typing

my_value: typing.Any = "test"
typing.reveal_type(my_value)  # Revealed type is "Any"
my_value = typing.cast(str, my_value)
typing.reveal_type(my_value)  # Revealed type is "Any"
my_value = typing.cast(typing.Literal["test"], my_value)
typing.reveal_type(my_value)  # Revealed type is "Any"

my_value_other: str = "test"
typing.reveal_type(my_value_other)  # Revealed type is "builtins.str"
my_value_other = typing.cast(typing.Literal["test"],my_value_other)
typing.reveal_type(my_value_other)  # Revealed type is "Literal['test']"
```

https://mypy-play.net/?mypy=latest&python=3.11&gist=95efc058e86af06661c36a189acae86d

**Expected Behavior**

My expectation is is that after casting `my_value` of type `Any` to `Literal["test"]` that mypy would reveal its type as ``Literal["test"]``

**Actual Behavior**

The revealed type is still `Any`

**Your Environment**

- Mypy version used: 0.991
- Python version used: 3.11

**Comment by erictraut** [comment]
I think mypy is doing the right thing here.

The `cast` call does indeed perform a cast to another type. If you assign the cast value to some other variable, you can see that it is applied:

```python
my_other_value = typing.cast(str, my_value)
typing.reveal_type(my_other_value) # builtins.str
```
However, in your code, you are immediately assigning the cast value back to the variable `my_value` which has a declared type of `Any`. Keep in mind that `Any` is special in that it is not generally narrowed, even on assignment.

You could declare the type of `my_value` as `object`. Then mypy will narrow the value upon assignment.
