### ISSUE TITLE
Missing list of incomplete features

### ISSUE THREAD

**Issue by Barry1** [python/mypy#14452]
**Documentation**

Within the CLI we have the command line switch `--enable-incomplete-feature` which expects a feature name to enable.
Until now I have not been able to find a list of possible (incomplete/under development) features, which I could enable over here.

Have I missed something?

**Comment by thomkeh** [comment]
It's defined here, but you're right that it's not documented anywhere:

https://github.com/python/mypy/blob/83660d0ad72ab5a61cea5fe5955e66c33ef54111/mypy/options.py#L70-L73

**Comment by soumdatta81** [comment]
So, we have to go through the codebase to identify all of the features that can be enabled with the --enable-incomplete-feature switch if I am not wrong?

**Comment by intgr** [comment]
I also noticed that the `enable_incomplete_feature` settings key is not documented. But if I add `enable_incomplete_feature = ["Unpack"]` to my pyproject.toml, it seems to work as expected.

**Comment by JelleZijlstra** [comment]
I think this is somewhat intentional; incomplete features are experimental and incomplete and may be broken in some way, so we don't want to advertise them too much.

However, it should be fine to add a list to the documentation with a note that these features are experimental, we don't guarantee any form of backward compatibility, use at your own risk, etc.

**Comment by jgarte** [comment]
> However, it should be fine to add a list to the documentation with a note that these features are experimental, we don't guarantee any form of backward compatibility, use at your own risk, etc.

I think the latter is a great idea. I'll add a `TODO` to look into this when I find the time otherwise feel free to pick up this issue and resolve it.

**Comment by intgr** [comment]
By the way, the `enable_incomplete_feature` setting is still undocumented.
