### ISSUE TITLE
Calling a typed function with default arguments causes "Too few arguments  [call-arg]"

### ISSUE THREAD

**Issue by PrincipalsOffice** [python/mypy#14482]
**Bug Report**
I have a function `foo` with default arguments assigned. I want to pass it to another function `bar` to call it. But mypy would complain about the lack of arguments even though they're not needed:
```
from typing import Callable
from __future__ import annotations

def foo(a: int | None = 1) ->  None:
    return None

def bar(func: Callable[[int | None], None]) -> None:
    func() #  error: Too few arguments  [call-arg]

bar(foo)
```
I know it's possible to walk around this with `Protocol`, but it'd be nice to avoid that. 
**Expected Behavior**

No errors

**Actual Behavior**

`#  error: Too few arguments  [call-arg]`

**Your Environment**

- Mypy version used: 0.991
- Python version used: 3.8.7

**Comment by hauntsaninja** [comment]
You should type it as `Callable[[], None]` in this case. Just silencing this error would be incredibly unsound on mypy's part. 

If you need to use it as both, yeah, a callback Protocol is your option. If you have a concrete suggestion (that's better than the rejected PEP 677 https://peps.python.org/pep-0677/#extended-syntax-supporting-named-and-optional-arguments ), open an issue on https://github.com/python/typing or send an email to typing-sig@

**Comment by PrincipalsOffice** [comment]
@hauntsaninja if I want to conditionally call func like this
```
def bar(func: Callable[[int | None], None], flag: int) -> None:
    if flag == 100:
        func(flag)
    else:
        func()
```
Is `Protocol` the only option? What's wrong with the `Callable[[int | None], None]` syntax that made it unable to recognize `func()` as valid?

**Comment by erictraut** [comment]
The annotation `Callable[[int | None], None]` means that it's a callable that accepts a single positional argument that is of type `int` or `None`. The `Callable` type form doesn't provide a way to express default arguments. You would need to use a callback protocol if that is your intent.

```python
class MyCallback(Protocol):
    def __call__(self, a: int | None = None, /) -> None:
        ...
```

**Comment by hauntsaninja** [comment]
`Callable[[int | None, None]` means that `f(5)` and `f(None)` are valid calls. It does not mean that you can choose not to pass an argument.

Other options:
- Instead of having one function with a flag, have two functions
- Rebind the function to use an Any type, e.g. do `func2 = cast(Callable[..., None], func)` and then use func2 everywhere
- Use `# type: ignore`

**Comment by PrincipalsOffice** [comment]
Thanks all. That's clear now.
