### ISSUE TITLE
Strange issue when using full width numerals in TypedDict keys

### ISSUE THREAD

**Issue by justuswilhelm** [python/mypy#14528]
**Bug Report**

When using full width numerals such as １ or ２, the dict key is not properly recognized and mypy will complain that I am supplying extra keys to a TypedDict. I was able to reproduce the issue in the mypy playground using mypy latest 0.991.

**To Reproduce**

```python
from typing import TypedDict


class ThisWorks(TypedDict):
    
   value1: str

this_works: ThisWorks = { "value1": "Hello, world" }


class ThisBreaks(TypedDict):
    
    value１: str

this_breaks: ThisBreaks = { "value１": "Hello, world" }

# main.py:15: error: Extra key "value１" for TypedDict "ThisBreaks"  [typeddict-item]

# It appears that mypy normalizes the full width numeral
wat: ThisBreaks = { "value1": "hello, world"}
# This will work

# Found 1 errors in 1 file (checked 1 source file)
```

Playground: https://mypy-play.net/?mypy=latest&python=3.11&gist=f4fb7e77f993c0311a45dc4c3f63c414
Gist: https://gist.github.com/mypy-play/f4fb7e77f993c0311a45dc4c3f63c414

**Expected Behavior**

I should be able to properly use full width numerals. This is especially relevant because I work with a lot of Japanese language text processing. I want to write dictionaries containing these full width numerals.

**Actual Behavior**

Mypy normalizes the key to a normal 1 and I can't set the correct dict key. Then I am not able to read the csv in correctly that I create using this dictionary.

```
main.py:15: error: Extra key "value１" for TypedDict "ThisBreaks"  [typeddict-item]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: mypy 0.991 (compiled: yes)
- Mypy command-line flags: `pipenv run mypy .`
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]
files = **/*.py
strict = True
```
- Python version used: Python 3.9.16 (but the playground fails too)

**Comment by JelleZijlstra** [comment]
Consistent with what @erictraut said, this works as expected if you use the alternative syntax for defining the TypedDict: `ThisBreaks = TypedDict("ThisBreaks", {"value１": str})`.

It's definitely an interesting edge case; I doubt anyone thought of this when TypedDict was designed. Perhaps mypy should gain some tests to cover this behavior.

**Comment by hauntsaninja** [comment]
I don't see an action item for mypy here. We can add docs if this comes up again, so far it hasn't
