### ISSUE TITLE
attrs plugin should support attrs.evolve

### ISSUE THREAD

**Issue by ikonst** [python/mypy#14525]
**Feature**

In the attrs plugin, we should add special treatment for [attrs.evolve](https://www.attrs.org/en/stable/api.html#attrs.evolve).

**Pitch**

We should validate attr names and types match.

**Comment by thomkeh** [comment]
Similar treatment for `dataclasses.replace` would also be nice. (There was previously PR #14263 which intended to support `replace` but that one also included special treatment for `astuple` and `asdict` which was thought to be better handled in typestubs.)

**Comment by ikonst** [comment]
By modifying the type annotations? I don't think dataclasses have any common base, do they? Or maybe through a protocol?

**Comment by thomkeh** [comment]
> By modifying the type annotations? I don't think dataclasses have any common base, do they? Or maybe through a protocol?

Yes, @AlexWaygood suggested doing it with a protocol: https://github.com/python/typeshed/pull/9362

**Comment by AlexWaygood** [comment]
> > By modifying the type annotations? I don't think dataclasses have any common base, do they? Or maybe through a protocol?
> 
> Yes, @AlexWaygood suggested doing it with a protocol: [python/typeshed#9362](https://github.com/python/typeshed/pull/9362)

Applying the same technique to `attrs` would be difficult unless all type checkers could be counted on to synthesise `__attrs_attrs__` attributes for `attrs` classes in the same way that they can be counted on to synthesise `__dataclass_fields__` attributes for classes decorated with `@dataclass`. Mypy has a custom plugin for `attrs`, meaning it can be counted on to synthesise this attribute. On the other hand, pyright has (reasonably) resisted adding any special-casing for any third-party libraries.

**Comment by ikonst** [comment]
If attrs ships its own type annotations, then they could decide that e.g. you could only used them with mypy and a certain plugin being installed, but I agree we cannot make this decision for typeshed's annotations.

And for this case, the plugin can easily make this check, and I would have to in #14526 anyway.

**Comment by AlexWaygood** [comment]
To be clear, `attrs` does ship its own type annotations, and typeshed does not have stubs for `attrs`. If somebody did want to try a solution for `attrs` along the lines of my `dataclasses` PR to typeshed, they'd have to implement it in the annotations shipped by `attrs`, not in typeshed.
