### ISSUE TITLE
Don't issue `no-redef` with conditional variable declaration

### ISSUE THREAD

**Issue by TheMythologist** [python/mypy#14534]
**Bug Report**

Mypy is returning an error `no-redef` wrongly.

**To Reproduce**

```python
import json
import os


class A:
    def __init__(self, file: str = "file.json"):
        if os.path.isfile(file):
            with open(file, 'r') as f:
                self.data: dict = json.load(f)
        else:
            self.data: dict = {"random_data": "asdf"}
```

**Expected Behavior**

Mypy runs against this file with no errors.

**Actual Behavior**

Error message:
```
script.py:11: error: Attribute "data" already defined on line 9  [no-redef]
Found 1 error in 1 file (checked 1 source file)
```

Mypy should check on attribute definition based on if-else conditions. If attribute declaration should be done in another conditional fashion, do let me know.

**Your Environment**

- Mypy version used: mypy 0.991 (compiled: yes)
- Mypy command-line flags: None (command ran was `mypy script.py`)
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.0

**Comment by TheMythologist** [comment]
I realised the following code snippet will also generate this bug:

```python
import os

if os.path.isfile("data.json"):
    boolean: bool = True
else:
    boolean: bool = False
```

Editing the issue name accordingly.

**Comment by TheMythologist** [comment]
Adding the line `self.data: dict` solves the problem. Perhaps this should be added to [documentation under common issues](https://mypy.readthedocs.io/en/stable/common_issues.html)?

**Comment by hauntsaninja** [comment]
It's there in the cheat sheet: https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#variables
Not sure that we get enough questions about it for it to be worth adding to the common issues page
