### ISSUE TITLE
Add support for homogenous subclass collections

### ISSUE THREAD

**Issue by neelmraman** [python/mypy#14563]
**Feature**

From what I've seen, it is not currently possible to indicate that something like a Sequence should be homogenous/have only one subclass type besides doing something like `Union[Sequence[SubclassA], Sequence[SubclassB], ...` (which is unwieldy if you have a lot of subclasses and requires manual updates if you introduce more subclasses). One might think to use `Sequence[Superclass]` or a `TypeVar` bounded to the Superclass, but both of those approaches consider a `Union` of subclasses a valid subtype. 

However, I'm not sure if this is something that makes more sense to be included in python's type system itself or if there should be an optional mypy flag that disallows Unions of subclasses to be used when the parameter/return type is not itself explicitly a Union.

**Pitch**

One example of where this could be used is a simple validation engine of sorts where one wants to enforce that each rule is only checking one thing.

```python
class Rule(ABC):
    @abstractmethod
    def get_violations(self) -> ?some type that references the superclass of violation types?:
        pass

class FunRule(Rule):
    def get_violations(self) -> Sequence[FunViolation]:  # this should be valid
        return []

class OtherFunRule(Rule):
    def get_violations(self) -> Sequence[OtherFunViolation]:  # this should be valid
        return []

class ComplexRule(Rule):
    def get_violations(self) -> Sequence[Union[FunViolation, OtherFunViolation]]:  # I'd like this to be invalid
        return []
```
I also came across this [StackOverflow question](https://stackoverflow.com/questions/69873787/how-to-hint-homogenous-list-of-instances-of-same-subclass), indicating other people have also wanted a feature like this.

**Comment by erictraut** [comment]
Is this what you're looking for? This already type checks without errors.

```python
from abc import ABC, abstractmethod
from typing import Sequence

class Violation: ...
class FunViolation(Violation): ...
class OtherFunViolation(Violation): ...

class Rule(ABC):
    @abstractmethod
    def get_violations(self) -> Sequence[Violation]:
        pass

class FunRule(Rule):
    def get_violations(self) -> Sequence[FunViolation]:
        return []

class OtherFunRule(Rule):
    def get_violations(self) -> Sequence[OtherFunViolation]:
        return []

class ComplexRule(Rule):
    def get_violations(self) -> Sequence[FunViolation | OtherFunViolation]:
        return []
```

**Comment by neelmraman** [comment]
Hi, sorry if my initial post was unclear (the comments on the `get_violations` lines may have been easy to miss). The functionality I am looking for is the ability to indicate that the Sequence will only have instances of a single subclass type in it (i.e., unions of subclass types would be explicitly disallowed). What I could do to achieve this is something like the following, but this approach gets messy with many subclasses and requires someone to manually update the return type of the abstract method each time a new rule/violation is introduced (since mypy wouldn't allow this type to be generated programmatically/dynamically).

```python
from abc import ABC, abstractmethod
from typing import Sequence

class Violation: ...
class FunViolation(Violation): ...
class OtherFunViolation(Violation): ...

class Rule(ABC):
    @abstractmethod
    def get_violations(self) -> Sequence[FunViolation] | Sequence[OtherFunViolation]:  # manually specifying a homogenous sequence of each violation type
        pass

class FunRule(Rule):
    def get_violations(self) -> Sequence[FunViolation]:
        return []

class OtherFunRule(Rule):
    def get_violations(self) -> Sequence[OtherFunViolation]:
        return []

class ComplexRule(Rule):
    def get_violations(self) -> Sequence[FunViolation | OtherFunViolation]:  # this would fail, as intended
        return []
```

**Comment by hauntsaninja** [comment]
An ad hoc rule that makes `Child1 | Child1` not a subtype of `Parent` would break the transitivity of subtyping, which makes typing very hard to reason about. So I don't think there's really a sane way to make the specific feature you ask for.

I think a big union of homogenous sequences is the best you're going to get.

**Comment by erictraut** [comment]
Ah, my apologies. I misinterpreted your intent. 

Yes, I don't see any way in the current Python static type system to express what you're looking for. I think it's unlikely that the type system could accommodate such a feature for the reason that @hauntsaninja gave.

As you point out, you can use a union in the base class, but that requires maintenance when you add a new subtype. You could also use a generic base class, which you may find more palatable than maintaining a union.

```python
from typing import Generic, Sequence, TypeVar
from abc import ABC, abstractmethod

class Violation: ...
class FunViolation(Violation): ...
class OtherFunViolation(Violation): ...

_TV = TypeVar("_TV", bound=Violation)

class Rule(ABC, Generic[_TV]):
    @abstractmethod
    def get_violations(
        self,
    ) -> Sequence[_TV]:
        pass

class FunRule(Rule[FunViolation]):
    def get_violations(self) -> Sequence[FunViolation]:
        return []

class OtherFunRule(Rule[OtherFunViolation]):
    def get_violations(self) -> Sequence[OtherFunViolation]:
        return []

class ComplexRule(Rule[OtherFunViolation]):
    def get_violations(
        self,
    ) -> Sequence[FunViolation | OtherFunViolation]:
        return []
```

**Comment by neelmraman** [comment]
Ah yup a bounded TypeVar + Generic was one of the things I tried as well but, unless I'm missing something, it didn't seem to get me anything because one can just make the type parameter for Rule a union (and that is still considered a subtype of the bounded superclass). For example, the following passes with the latest version of mypy.
```python
from typing import Generic, Sequence, TypeVar
from abc import ABC, abstractmethod

class Violation: ...
class FunViolation(Violation): ...
class OtherFunViolation(Violation): ...

_TV = TypeVar("_TV", bound=Violation)

class Rule(ABC, Generic[_TV]):
    @abstractmethod
    def get_violations(
        self,
    ) -> Sequence[_TV]:
        pass

class FunRule(Rule[FunViolation]):
    def get_violations(self) -> Sequence[FunViolation]:
        return []

class OtherFunRule(Rule[OtherFunViolation]):
    def get_violations(self) -> Sequence[OtherFunViolation]:
        return []

class ComplexRule(Rule[FunViolation | OtherFunViolation]):
    def get_violations(
        self,
    ) -> Sequence[FunViolation | OtherFunViolation]:
        return []
```
