### ISSUE TITLE
no error when calling `Callable` with `ParamSpec` using `Concatenate` with not enough args

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#14571]
```py
from typing import Callable, Concatenate, ParamSpec

P = ParamSpec("P")


def decorator(fn: Callable[Concatenate[str, P], None]) -> None:
    fn("value") # runtime TypeError: foo() missing 1 required positional argument: 's2'


@decorator
def foo(s: str, s2: str) -> None:
    ...
```
[playground](https://mypy-play.net/?mypy=master&python=3.11&flags=show-error-context%2Cshow-column-numbers%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Cno-strict-optional%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=db8aac32d8fa17451e5231403308a801)

**Comment by AlexWaygood** [comment]
I think mypy should indeed emit an error on your code snippet, but not the error you think. Your use of `ParamSpec` here is invalid -- the `ParamSpec` `P` in the `decorator` function will go unsolved, since it is only used once in the function signature.

**Comment by KotlinIsland** [comment]
@AlexWaygood It is true that the `ParamSpec` is only used once, but there is still an issue that the `P` could represent any signature. Look at this [playground](https://mypy-play.net/?mypy=master&python=3.11&flags=show-error-context%2Cshow-column-numbers%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Cno-strict-optional%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=06553c2e60219a380fcd64e610befa43)

**Comment by AlexWaygood** [comment]
> @AlexWaygood It is true that the `ParamSpec` is only used once, but there is still an issue that the `P` could represent any signature. Look at this [playground](https://mypy-play.net/?mypy=master&python=3.11&flags=show-error-context%2Cshow-column-numbers%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Cno-strict-optional%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=925e84f802413a564c50857d35e1f525)

Yes, that example illustrates the type-safety issue much more clearly.

**Comment by sterliakov** [comment]
Seems like this has nothing to do with `Concatenate`. The following is green on master, with and without `--strict`:

```python
from typing_extensions import ParamSpec
from typing import Callable

_P = ParamSpec("_P")

def run(predicate: Callable[_P, None], *args: _P.args, **kwargs: _P.kwargs) -> None:
    predicate()
```

**Comment by sterliakov** [comment]
@AlexWaygood Since this is a major problem (not detecting a relatively common problem of forgetting to pass args&kwargs), I'll try to ping someone here once again: are there any blockers that prevent #17323 (green, small, mergeable) from being merged? Is there anyone I can ping to get that patch reviewed? Something wrong there from my side, making the review or the patch implausible/undesired/inefficient/whatever?

**Comment by AlexWaygood** [comment]
Unfortunately I'm only a triager here so do not have power to merge. I could review, but I also have pretty limited time to work on mypy right now, sadly. I'll post on the mypy maintainer Discord, however

**Comment by hauntsaninja** [comment]
Thanks sterliakov and DetachHead!
