### ISSUE TITLE
no error when using `covariant` or `contravariant` `TypeVar` on class with writable attribute

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#14588]
```py
from typing import Generic, TypeVar

T = TypeVar("T", covariant=True)


class Foo(Generic[T]):
    def __init__(self, value: T) -> None:
        self.foo = value
```
here, `T` is used in both an in and out position as the value can be modified as well.

jailbreak:
```py
objects = Foo[object](None)

ints = Foo[int](1)


def do_thing(value: Foo[object]) -> None:
    value.foo = "asdf"


do_thing(ints)

if TYPE_CHECKING:
    reveal_type(ints.foo) # int
print(ints.foo) # "asdf" (hacked!!!!!!)
```
[playground](https://mypy-play.net/?mypy=latest&python=3.11&flags=show-error-context%2Cshow-column-numbers%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Cno-strict-optional%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=b5a19b248e413da1477da68a456b0f3c)

**Comment by hauntsaninja** [comment]
Thanks, I think this is basically just a special case of https://github.com/python/mypy/issues/3208
