### ISSUE TITLE
Mypy error on assigning an empty dict to Union variable

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/mypy#1458]
This fails:
```py
d = {} # type: Union[Dict[str, int], List[int]]
```
with error message:
```
error: Incompatible types in assignment (expression has type Dict[None, None],
variable has type "Union[Dict[str, int], List[int]]")
```
This also fails with a similar error message:
```py
d = [] # type: Union[Dict[str, int], List[int]]
```
```
error: Incompatible types in assignment (expression has type List[None],
variable has type "Union[Dict[str, int], List[int]]")
```
This works however:
```py
d = {"abc":123} # type: Union[Dict[str, int], List[int]]
```

I was expecting empty dict to work with `Union`, since the following 2 statements work:
* `d = {} # type: Dict[str, int]`
* `d = 3 # type: Union[int, str]`

**Comment by rwbarton** [comment]
This is related to inference for unions like #1430 (but simpler because a `Dict` is not a `List`). I'll add support for this case to #1408.
