### ISSUE TITLE
Virtual subclasses of abstract base classes

### ISSUE THREAD

**Issue by jtatum** [python/mypy#1459]
Seeing a couple of different errors with virtual subclasses:

``` python
from abc import ABCMeta
class M(metaclass=ABCMeta):
    pass
class A:
    pass
M.register(A)  # error: "M" has no attribute "register"
def test(obj: M):
    pass
obj = A()
test(obj)  # error: Argument 1 to "test" has incompatible type "A"; expected "M"

```

**Comment by gvanrossum** [comment]
ABC.register() is not supported and it's unclear to me how it could be supported without a relatively big change to mypy. It probably would require an extra pass over the code looking for register() calls everywhere.

The only thing that's easy to do is to add register() to the stubs in typeshed -- can you send a PR for that?

**Comment by jtatum** [comment]
Hmm, there might be another issue with metaclasses that prevents me from adding register to typeshed:
```python
class M(type):
    def __new__(cls, *args, **kwargs):
        return super().__new__(cls, *args)
    def test(cls):
        pass
class C(metaclass=M):
    pass
C.test()  # error: "C" has no attribute "test"
```

**Comment by gvanrossum** [comment]
Ohh... Yes, that looks like we have a problem with metaclasses.

**Comment by jsoref** [comment]
FWIW, this is a pretty common/frustrating bug in the Python ecosystem, here's the equivalent [IntelliJ/PyCharm issue](https://youtrack.jetbrains.com/issue/PY-30747#focus=streamItem-27-3809530.0-0).

**Comment by AlexWaygood** [comment]
For ABCMeta.register() support, see #2922 (newer issue but has more discussion than this one).

For generalised metaclass support, this [example](https://github.com/python/mypy/issues/1459#issuecomment-216063442) no longer reproduces [on mypy 0.941](https://mypy-play.net/?mypy=latest&python=3.10&gist=fcbc5e5286a35df7326cdbee84366ef3).
