### ISSUE TITLE
Allow `self: Self` for backwards compatability

### ISSUE THREAD

**Issue by SimpleArt** [python/mypy#14608]
**Bug Report**

Using `self: Self` or `cls: type[Self]` results in an error.

**To Reproduce**

```python
from typing import Self


class A:

    def foo(self: Self) -> Self:
        return self
```

**Expected Behavior**

The behavior should be equivalent to the workaround explained in [PEP 673](https://peps.python.org/pep-0673/#motivation) before we had `typing.Self`. Users which previously used the old code would otherwise have to change all of the code which used the previous workaround to work with the new change or continue to use the old workaround.

```python
# Should be a simple change to `from typing import Self`.
from typing import TypeVar
Self = TypeVar("Self", bound="A")


class A:

    def foo(self: Self) -> Self:
        return self
```

**Actual Behavior**

```
main.py:6: error: Variable "typing.Self" is not valid as a type  [valid-type]
main.py:6: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
```

Requires `self: Self` to be changed to just `self` everywhere.

**Your Environment**

[mypy Playground](https://mypy-play.net/?mypy=latest&python=3.11&gist=f97ec9a8fca549a3ca0cddcbd52fab61)

**Comment by AlexWaygood** [comment]
Are you using mypy master? Mypy doesn't support `typing.Self` yet in any released version, so if you're using mypy 0.991 or older, that's why you're seeing the error. It will support `typing.Self` in the way you'd like it to in the next release (mypy 1.0).

**Comment by AlexWaygood** [comment]
(Follow #13685 for updates on the release schedule.)

**Comment by SimpleArt** [comment]
Thanks, I was testing in the linked mypy Playground. Checking back on it with the other versions, you're right in that the master branch works as expected, while every other version failed.
