### ISSUE TITLE
Potentially incorrect `MutableSet` inplace operator types

### ISSUE THREAD

**Issue by SimpleArt** [python/mypy#14612]
**Bug Report**

Mutable sets should accept any iterable for inplace operators.

**To Reproduce**

```python
from collections.abc import MutableSet

x: MutableSet
x &= [1, 2]  # Same for __ior__, __isub__, and __ixor__.
```

**Expected Behavior**

Should work fine.

**Actual Behavior**

```
main.py:4: error: Argument 1 to "__iand__" of "MutableSet" has incompatible type "List[int]"; expected "AbstractSet[Any]"  [arg-type]
```

**Your Environment**

[mypy Playground](https://mypy-play.net/?mypy=master&python=3.11&gist=ca3777f9c9bb2ee7651e7d06cef5e17f)

**Comment by tmke8** [comment]
That seems more like a typeshed issue. See this line:

https://github.com/python/typeshed/blob/88a761ed4ec293be781e54ba6f04cdfd471d72cf/stdlib/typing.pyi#L531

**Comment by SimpleArt** [comment]
I looked into it more on the Python side, and it looks to be a contradiction in how abstract sets were implemented compared to the builtin sets. `builtins.set` and `builtins.frozenset` were never supposed to support binary operators with anything other than sets to avoid potential confusions, and iterable arguments should be handled using methods like `set.intersection_update`. Abstract sets were designed without these methods, so in order to provide the behavior without forcing the user to cast everything to a set beforehand, abstract sets accept iterable arguments.

I think the way it currently is here is more pure and that there's not too much that can be done about it. If you need this type of behavior, I would recommend building your own protocols and using those instead.
