### ISSUE TITLE
No proper executable installed on Windows

### ISSUE THREAD

**Issue by FichteFoll** [python/mypy#1461]
When I run `pip install mypy-lang`, there is no proper executable installed in `%PYTHONHOME%/Scripts`. There is a file named `mypy` with a shebang, but no normal Windows installation is able to interpret that and map it to a *proper* executable (the one referenced in the shebang).

Instead, an executable (`mypy.exe`) should be installed like most other similar packages do.

**Comment by FichteFoll** [comment]
Refer to `distutils.core.setup`'s `entry_points` kwarg, as used by [flake8](https://gitlab.com/pycqa/flake8/blob/master/setup.py#L58).

**Comment by kirbyfan64** [comment]
I think this was already fixed by #1348.

**Comment by FichteFoll** [comment]
Yes indeed, this is a duplicate of #1226. Didn't come up in my searches unfortunately.
