### ISSUE TITLE
Regression: "Attributes without a default cannot follow attributes with one" despite dataclass_transform with kw_only_default=True

### ISSUE THREAD

**Issue by rbuffat** [python/mypy#14629]
Since mypy 1.0 the following code results in the following type error: 

```
import envee


@envee.environment
class Environment:
    one: int = 1
    two: int  # error: Attributes without a default cannot follow attributes with one  [misc]`


env = envee.read(Environment)

```

The [environment decorator](https://github.com/c-technology/envee/blob/main/envee/envee.py#L161-L168] ) of the `envee` library ensures that a dataclass with kw_only is created (if supported by Python) and indicates this using `dataclass_transform(kw_only_default=True)`.

**Comment by JelleZijlstra** [comment]
cc @wesleywright for dataclass-transform. I added https://github.com/python/mypy/labels/topic-dataclass-transform to classify similar issues in the future. I believe #14580 will fix this issue.
