### ISSUE TITLE
Ignore specific warnings on specific lines

### ISSUE THREAD

**Issue by Alex031544** [python/mypy#14630]
**Feature**

Similar to [this issue](https://github.com/python/mypy/issues/500) it would be nice to be able to accept deviations from the MyPy checks for special cases. Sometimes there are reasons to solve something this way rather than following the common rule.

Nevertheless, it is important to provide information to code reviewers to help them to understand:

- which warning (e.g. by using the identifiers of MyPy) is suppressed
- optional comment
- it must be easy to find the exceptions/approvals

**Pitch**

- adding a line hint:
  ```
  class MyTinyClass:  # R0903 : ignore
  ```

- adding a line hint with a comment:
  ```
  class MyTinyClass:  # R0903 : ignore - No further public methods are required here (Alex)
  ```

- adding a line hint with several keys:
  ```
  class MyTinyClass:  # R0903,R0915 : ignore
  ```

**Comment by JelleZijlstra** [comment]
You can use type ignores with error codes, is that not enough?

https://mypy.readthedocs.io/en/stable/error_codes.html#silencing-errors-based-on-error-codes

**Comment by Alex031544** [comment]
Yes - thanks :)
