### ISSUE TITLE
Cannot return `Enum` instance in `classmethod` marked as `Self`

### ISSUE THREAD

**Issue by johnthagen** [python/mypy#14650]
**Bug Report**

It is not possible to annotate an `Enum` `classmethod` returning `Self` if the method returns a specific `Enum` variant.

**To Reproduce**

```py
from enum import Enum, auto, unique
from typing_extensions import Self

@unique
class Color(Enum):
    Red = auto()
    Green = auto()
    Blue = auto()

    @classmethod
    def stop(cls) -> Self:
        return cls.Red

print(Color.stop())
```
**Expected Behavior**

No type check errors. We are using `Self` to reduce the forward reference problem and avoid `from __future__ import annotations`.

**Actual Behavior**

```
$ mypy --strict main.py
main.py:14: error: Incompatible return value type (got "Color", expected "Self")  [return-value]
```

**Your Environment**

- Mypy version used: 1.0.0
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.10.8
- `typing_extensions`: 4.4.0

**Comment by hauntsaninja** [comment]
Same issue as your other issue

**Comment by eigenein** [comment]
@hauntsaninja Could you please elaborate on what other issue? I believe, OP's got a valid point here: somehow `@classmethod` coerces `Self` to the specific class, even though it's being referred by `cls`:

```python
from typing import Self


class Foo:
    foo: Self

    @classmethod
    def bar(cls) -> Self:
        reveal_type(cls.foo)  # note: Revealed type is "__main__.Foo"
        return cls.foo  # error: Incompatible return value type (got "Foo", expected "Self")  [return-value]

    def qux(self) -> Self:
        reveal_type(self.foo)  # note: Revealed type is "Self`0"
        return self.foo
```

**Comment by eigenein** [comment]
@johnthagen Would you mind amending the issue title? It seems to be applicable to any `@classmethod` returning an instance of `Self`.

**Comment by johnthagen** [comment]
> Could you please elaborate on what other issue?

- #14649

Specifically the underlying issue is

- https://github.com/python/mypy/issues/14635#issuecomment-1420769005

**Comment by johnthagen** [comment]
> Would you mind amending the issue title?

I'd rather not amend the title, especially since it was marked as "Not Planned".

**Comment by eigenein** [comment]
> I'd rather not amend the title, especially since it was marked as "Not Planned".

Fair enough!

> https://github.com/python/mypy/issues/14649
> Specifically the underlying issue is
> https://github.com/python/mypy/issues/14635#issuecomment-1420769005

I dare to argue this is a different situation:

#14649 is caused by returning a specific child in place of `Self`, and #14635 – by violating the parent's interface (again, by specifying a concrete child in place of `Self`).

Here, the return type is `Self` and the actual value type is also `Self`. And as I've shown [above](https://github.com/python/mypy/issues/14650#issuecomment-1520120151), this passes just fine without the `@classmethod`, which doesn't match the issues above either.

**Comment by johnthagen** [comment]
> I dare to argue this is a different situation:

I agree with you. Perhaps @hauntsaninja will consider re-opening the issue? If it's agreed, I'm happy to change the title at that time.

**Comment by eigenein** [comment]
As there was no reaction, I've created a separate issue: https://github.com/python/mypy/issues/15223
