### ISSUE TITLE
Add `--dry-run` flag to `mypy --install-types`

### ISSUE THREAD

**Issue by JakeSummers** [python/mypy#14663]
**Feature**

When adding mypy to existing projects, you often need to track down the missing typesheds.  

My projects dependencies are managed with poetry.  What I would like to do is something like this: 

```
$ mypy --install-types --dry-run
types-google-cloud-ndb
types-response
```

Then I can run a `poetry add types-response` for each of the items listed.

**Comment by hauntsaninja** [comment]
Thanks, we should do https://github.com/python/mypy/issues/10600#issuecomment-950170169 which I believe meets your use case
