### ISSUE TITLE
Update of class' abstract status (update_abstractmethods) appears to not be handled properly.

### ISSUE THREAD

**Issue by Nuno-Mota** [python/mypy#14662]
**Bug Report**

The usage of `abc.update_abstractmethods()` appears to not be handled by `mypy`.

**To Reproduce**

Consider the following base code:
```python
class A(ABC):
	@abstractmethod
	def __init__(self) -> None: ...

	@abstractmethod
	def foo(self) -> None: ...

class B(A):
	def __init__(self) -> None: ...
```

Attempting to instantiate `B` results in the expected behaviour. Both `python` and `mypy` raise the correct error:
```python
B()
"""
PYTHON:
	TypeError: Can't instantiate abstract class B with abstract method foo.

MYPY:
	error: Cannot instantiate abstract class "B" with abstract attribute "foo"  [abstract]
		B() # TypeError: Can't instantiate abstract class B with abstract method foo
		^~~
"""
```

However, when the `foo` method of `B` is dynamically set, and the abstract status of `B` is updated, `mypy` fails to recognize that fact:
```python
def dynamic_foo(self) -> None:
	print("bar")
setattr(B, 'foo', dynamic_foo)
update_abstractmethods(B)

B().foo()

"""
PYTHON:
	'bar'
MYPY:
	error: Cannot instantiate abstract class "B" with abstract attribute "foo"  [abstract]
		B().foo()
		^~~
"""
```

**Expected Behavior**

`mypy` should update the abstract status of `B`.

**Your Environment**

- Mypy version used: `mypy 0.991 (compiled: yes)`
- Mypy command-line flags: `--warn-redundant-casts --warn-unused-ignores --warn-unreachable --allow-redefinition --show-error-context --pretty --disable-error-code=type-abstract`
- Mypy configuration options from `mypy.ini` (and other config files): NA
- Python version used: 3.10.8

**Comment by JelleZijlstra** [comment]
Mypy is a static type checker and does not recognize runtime updates (monkeypatching) like the one in your example.
