### ISSUE TITLE
Wrong infered type for dict with bool and float

### ISSUE THREAD

**Issue by rnestler** [python/mypy#14690]
**Bug Report**

A simple dictionary with `bool` and `float` entries gets an inferrred type of `builtins.dict[builtins.str, builtins.float]` instead of `builtins.dict[builtins.str, Union[builtins.bool, builtins.float]]`.

**To Reproduce**

```python
unexpected_type = {
    "bar": True,
    "value_0": 1.0,
    "value_1": 2.0,
}
reveal_type(unexpected_type)
```

**Expected Behavior**

I'd expect `test.py:6: note: Revealed type is "builtins.dict[builtins.str, Union[builtins.bool, builtins.float]]"`

**Actual Behavior**

Output: `test.py:6: note: Revealed type is "builtins.dict[builtins.str, builtins.float]"`

**Your Environment**

- Mypy version used: mypy 1.0.0 
- Mypy command-line flags: None
- Mypy configuration options from `pyproject.toml` (and other config files):
   ```toml
   [tool.mypy]
   strict = true
   ```
- Python version used: Python 3.10.9

**Comment by erictraut** [comment]
I suspect this is another case where mypy uses a join rather than a union. The join of `bool` and `float` is `float`.

**Comment by erictraut** [comment]
Actually, mypy's behavior is correct here. The type `bool | float` is the same as `float` because `bool` is a subtype of `float`. It's fine for a type checker to resolve this union since the two types are equivalent. Recommend closing.
