### ISSUE TITLE
Type narrowing ClassVar in subclass prohibits a grandchild to use base type

### ISSUE THREAD

**Issue by thejcannon** [python/mypy#14702]
**Bug Report**

I think the reproduction code speaks for itself :sweat_smile: 

**To Reproduce**

Playground URL: https://mypy-play.net/?mypy=latest&python=3.11&gist=333f013c023a7d031cf8ecfb30143bc3
Code:
```
from __future__ import annotations
from typing import ClassVar

class Foo:
    x: ClassVar[int | str]

class Bar(Foo):
    x = "s"

class Baz(Bar):
    x = 0  # womp womp

reveal_type(Baz.x)
```

**Expected Behavior**

The type didn't get narrowed when inheriting from `Bar` such that I can still assign `x` to `int`.

Note `pyright` doesn't have this particular affliction.

**Actual Behavior**

`# Incompatible types in assignment (expression has type "int", base class "Bar" defined the type as "str")  [assignment]`

**Your Environment**

(See playground link))

**Comment by hauntsaninja** [comment]
Note that pyright isn't narrowing types (since it infers `int | str`, not `int`), it's using the context of the parent type to determine the type in the Bar class. This is a missing feature from mypy, but I'd track this in e.g. https://github.com/python/mypy/issues/10375
