### ISSUE TITLE
Unexpected '...' for homogeneous tuples using builtin list, set (PEP 585)

### ISSUE THREAD

**Issue by ibondar-altilan** [python/mypy#14707]
**Bug Report**

The same error for tuple was fixed in #10766 but I see now an error "Unexpected" for the builtin types list, set:

**To Reproduce**

```python
# the snippet
l = list[str, ...]  # error

t = tuple[str, ...]  # no error

s = set[str, ...]  # error

```

**Expected Behavior**
No errors

**Actual Behavior**
test.py:1: error: Unexpected "..."  [misc]
test.py:1: error: "list" expects 1 type argument, but 2 given  [type-arg]
test.py:5: error: Unexpected "..."  [misc]
test.py:5: error: "set" expects 1 type argument, but 2 given  [type-arg]
Found 4 errors in 1 file (checked 1 source file)

**Your Environment**

- Mypy version used: 1.0.0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): default after installation
- Python version used: 3.10.5

**Comment by JelleZijlstra** [comment]
This is correct. `tuple` is special; `...` is invalid for other types (other than Callable, where it has a different specialized meaning).

**Comment by ibondar-altilan** [comment]
Thank you. But the built-in PyCharm linter handles all these types in the same way. Tuple is special for mypy only or it is written in PEP 585?

**Comment by erictraut** [comment]
PEP 484 specifies the behavior of Tuple. The `...` is not allowed in the other type annotations above. It sounds like PyCharm is not in compliance with the typing spec.

**Comment by ibondar-altilan** [comment]
Yes, I've got that, thanks
