### ISSUE TITLE
arg-type error with collections of objects of generic type

### ISSUE THREAD

**Issue by TheWizier** [python/mypy#14716]
**Bug Report**

Mypy will use List[object] for lists that contain many of the same generic type instead of List[generic type]

**To Reproduce**

```python
https://mypy-play.net/?mypy=latest&python=3.11&gist=d49f692879e482e4d84e75ce2a95a45a
```

**Expected Behavior**

No error

I would expect c to be considered a List[Test[Any]]

**Actual Behavior**

main.py:16: error: Argument 1 to "fun" has incompatible type "List[object]"; expected "List[Test[Any]]"  [arg-type]

fun([a,b]) also fails for me with the same error message, but seems to only fail if the function was imported.

**Your Environment**

- Mypy version used: 1.0.0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.11

**Comment by hauntsaninja** [comment]
mypy is correct here. Test is invariant so it can't infer Test[object]. Inferring Any would he unsound.

**Comment by TheWizier** [comment]
Thank you! Maybe there should be a mention of covariance in the error message? I was not aware that it was a thing.
