### ISSUE TITLE
Cannot resolve constrained TypeVar with union of allowed types

### ISSUE THREAD

**Issue by pwschaedler** [python/mypy#14721]
**Bug Report**

When writing a function that accepts a parameter that is Type[T] for some constrained TypeVar, mypy will throw an error if the provided argument is a Union of allowed types.

**To Reproduce**

Gist URL: https://gist.github.com/f21aca1a2b7805a62659990d5be038c7
Playground URL: https://mypy-play.net/?mypy=latest&python=3.11&gist=f21aca1a2b7805a62659990d5be038c7

```python
from typing import Type, TypeVar

T = TypeVar('T', str, int)

def f(t: Type[T]) -> T:
    return t()

union_type: Type[str] | Type[int]
f(union_type)
```

**Expected Behavior**

In the above example, T is constrained to be either `str` or `int`, therefore the parameter `t` should be `Type[str]` or `Type[int]`. I would expect an argument `Type[str] | Type[int]` to be allowed.

**Actual Behavior**

However, mypy produces the following:

```
main.py:9: error: Value of type variable "T" of "f" cannot be "object"  [type-var]
```

It seems like when used as a function argument, the type gets reduced to just `object`.

**Your Environment**

- Mypy version used: 1.0.0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: I tested on 3.8, 3.10, and 3.11

**Comment by erictraut** [comment]
Mypy is working correctly here. A constrained (restricted) TypeVar mandates that the type must be one of the constrained types. In this example, it must be either `str` or `int`. It cannot be `str | int` unless you include that type as a separate constraint. Recommend closing.
