### ISSUE TITLE
Type for key in sorted() based on variable instead of expression

### ISSUE THREAD

**Issue by jorants** [python/mypy#14749]
**Bug Report**

When using the building `sorted()` function, mypy bases the type signature of the `key`  on the type signature of the variable that will be stored in, while it should be based on the types of the iterator that is passed. 

As `sorted` always produces a new list it should possibly be allowed for the beginning and ending list to be of different types. Even ignoring this and explicitly calling `list()` does not fix the problem however. 

**To Reproduce**
gist: https://mypy-play.net/?mypy=master&python=3.11&gist=24a47dff700b33fd0b37838a26ae0cba
```python
def key_for_ints(item : int) -> int:
    return -item
# Example 1: works
a = [1, 2]
a.sort(key = key_for_ints)
resa : list[int | str] = list(a)

# Example 2: error
b = [1, 2]
resb : list[int | str] = sorted(b,key = key_for_ints)

# Example 3:  still an error
c = [1, 2]
resc : list[int | str] = list(sorted(c,key = key_for_ints))
```

**Expected Behavior**

No errors

**Actual Behavior**

```
main.py:10: error: Argument "key" to "sorted" has incompatible type "Callable[[int], int]"; expected "Callable[[Union[int, str]], Union[SupportsDunderLT[Any], SupportsDunderGT[Any]]]"  [arg-type]
main.py:14: error: Argument "key" to "sorted" has incompatible type "Callable[[int], int]"; expected "Callable[[Union[int, str]], Union[SupportsDunderLT[Any], SupportsDunderGT[Any]]]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: both 1.0.0 and master branch
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.11

**Comment by hauntsaninja** [comment]
I agree that there's no unsafety in this program, but I think it would be hard to convince type checkers of this in our current type system. I think the best you have is `cast`.
