### ISSUE TITLE
Cannot access nested classes with Self type

### ISSUE THREAD

**Issue by ndido98** [python/mypy#14748]
**Bug Report**

I have this piece of code, which type checks just fine:
```python
from typing import Generic, TypeVar, cast

T = TypeVar("T", bound="Base.Config")


class Base(Generic[T]):
    class Config:
        field1: int

    config: T

    def __init__(self):
        self.config = cast(T, self.Config())

class Derived(Base["Derived.Config"]):
    class Config(Base.Config):
        field2: int


x = Derived()
reveal_type(x.config)
```

I expected the newly-introduced `Self` type to also be able to access nested classes, so that the code above could be in my head rewritten to:

```python
from typing_extensions import Self

class Base:
    class Config:
        field1: int

    config: Self.Config

    def __init__(self):
        self.config = self.Config()

class Derived(Base):
    class Config(Base.Config):
        field2: int


x = Derived()
reveal_type(x.config)
```

**Expected Behavior**

When running mypy, I expected the latter piece of code to output that the revealed type would be "Derived.Config".

**Actual Behavior**

When running mypy on the second piece of code, I got this:
```
test.py:7: error: Name "Self.Config" is not defined  [name-defined]
test.py:18: note: Revealed type is "Any"
```

**Your Environment**

- Mypy version used: 1.0.1
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.6

**Comment by sterliakov** [comment]
Attribute access on type hints should not work this way, why do you expect this? Such thing is not mentioned in [PEP673](https://peps.python.org/pep-0673/). Your initial generic solution is a proper way to go, IMO, not everything should be rewritten with `Self`. There is nothing like `SomeTypeVar.attribute` in python typing system, why should it be added specifically to `Self`?

**Comment by jhbuhrman** [comment]
Instead of having to make your class generic, I guess the following will suffice:
```python
    # config: Self.Config
    config: Config
```

**Comment by JelleZijlstra** [comment]
Agree, this is working as it should.

**Comment by erictraut** [comment]
Here's a simpler solution that doesn't require `Self` or even a `TypeVar`. 

```python
class Base:
    class Config:
        field1: int

    config: Config

    def __init__(self):
        self.config = self.Config()


class Derived(Base):
    class Config(Base.Config):
        field2: int

    config: Config

Derived().config.field2
Base().config.field2  # Type error
```
