### ISSUE TITLE
Typing module included in lib-typing doesn't have DefaultDict

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1475]
I wonder if there other things that are out of date.

**Comment by gvanrossum** [comment]
Shall I just replace it with the latest copy of typing.py from https://github.com/python/typing/?

**Comment by JukkaL** [comment]
Probably the best thing to do -- once we've checked that it works on Python 3.2.

**Comment by gvanrossum** [comment]
OK will do.

**Comment by ilevkivskyi** [comment]
When I added `DefaultDict` as type alias, the `typing.py` was already quite outdated. This is why I didn't include `DefaultDict` also there.
