### ISSUE TITLE
Using Literal to Access TypedDict setdefault does not work properly.

### ISSUE THREAD

**Issue by RonNabuurs** [python/mypy#14762]
**Bug Report**

When using `Literal` in combination with `setdefault`, typing does not work like I expect.

**To Reproduce**

```python
from typing import List, Literal, Optional, TypedDict

class Example(TypedDict, total=False):
    val: List[Optional[int]]

example: Example = {}

val: Literal['val'] = 'val'

example.setdefault(val, []) # "List[<nothing>]"; expected "List[Optional[int]]"

if val not in example:
    example[val] = [] # Works like expected
```

**Expected Behaviour**

I expect the behaviour to be the same as the if statement. Or at least for both cases to be the same. 

**Actual Behavior**

See example

**Your Environment**

- Mypy version used: 1.0.1
- Mypy command-line flags: --strict
- Python version used: 3.10.6

**Comment by JukkaL** [comment]
I suspect that `typed_dict_setdefault_signature_callback` in `mypy.plugins.default` needs to be modified to also accept literal types (`LiteralType`), not just literal expressions (`StrExpr`).

**Comment by Cnoor0171** [comment]
Seems like this is fixed already and issue can be closed. The following code
```python
from typing import Literal, TypedDict

class Example(TypedDict, total=False):
    val: list[int | None]

example: Example = {}

val: Literal['val'] = 'val'

out = example.setdefault(val, [])
reveal_type(out)
```
generates
```
example.py:11: note: Revealed type is "builtins.list[Union[builtins.int, None]]"
Success: no issues found in 1 source file
```

**Comment by RonNabuurs** [comment]
Just ran this again with the latest mypy version (`1.7.1`) and it seems to work fine!
