### ISSUE TITLE
Command line option to read list of files to check from a file

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1476]
This would be handy when you have a truly long list of files, possibly containing spaces, produced by a shell pipeline (e.g. `FILES=$(find . -name '*.py' --print0 | xargs -0 grep -l '# type:')`).

**Comment by ilevkivskyi** [comment]
This request appeared few times again at PyCon, so I am raising priority to high.

**Comment by JukkaL** [comment]
You can already do things like `mypy @files.txt` which seems to be good enough.

**Comment by ilevkivskyi** [comment]
OK, so we can close this.

**Comment by Herst** [comment]
For completeness sake and in case someone comes across this thread here, in `bash` the example from the original post then should be able to be made into the following one-liner using process substitution:
~~~bash
mypy @f<(find . -name '*.py' --print0 | xargs -0 grep -l '# type:')´
~~~
