### ISSUE TITLE
inferred type of "(cond and a) or b"

### ISSUE THREAD

**Issue by rwbarton** [python/mypy#1477]
If `cond: Bool`, `a: A`, and `b: B`, then mypy thinks `(cond and a) or b` has type `Union[bool, A, B]`. But in fact the type should just be `Union[A, B]`. The only way `(cond and a) or b` can be a `bool` is for it to be `(cond and a)`, and for that to be truth-y; but in that case `(cond and a)` would have type `A`, and never type `bool` (from `cond`).

**Comment by rwbarton** [comment]
See also discussion at #1698.

With `False` and `True` types we could type check this as follows: with

* `cond: bool`, `a: A`, `b: B`, we first have

* `cond and a: Union[falsey_type(bool), A] = Union[False, A]`, and then

* `(cond and a) or b: Union[truthy_type(Union[False, A]), B] = Union[A, B]`.

**Comment by dmoisset** [comment]
Just checked that my PR #1989 happens to fix this too

**Comment by ddfisher** [comment]
Fixed by #1989.
