### ISSUE TITLE
Callables in dicts lose their typing

### ISSUE THREAD

**Issue by kristjanvalur** [python/mypy#14779]
**Bug Report**

typing of callables falls away in dicts, without warnings.

**To Reproduce**

```python
from typing import Callable, Any, Mapping

def api(handlers: Mapping[Any, Callable[[str], int]]) -> None:
    pass

def handler1(arg):
    return 1

def handler2(arg:int) -> str:
    return "foo"

handlers = {
    1: handler1,
    2: handler2
}

api(handlers)
```

**Expected Behavior**

Running MyPy `--strict` on the above file should somehow warn us that the type of `handler2` is being recast as a
callable taking `Any`

**Actual Behavior**
MyPy approves this file, even though an incorrect type is being passed in as a handler via the dict.

**Comment by kristjanvalur** [comment]
Adding the line `handlers = 1` will reveal the type of `handlers`:

```
tests/type.py:22: error: Incompatible types in assignment (expression has type "int", variable has type "Dict[int, Callable[[Any], Any]]")  [assignment]
```

A dict with `Any` callables is valid as an argument.

**Comment by hauntsaninja** [comment]
This is expected; the type of handler1 is Callable[[Any], Any] because it is unannotated. There is no recast happening.

**Comment by kristjanvalur** [comment]
Also note that passing the dict as a literal to the `api()` will correctly identify that `handler2` is of an incorrect type.  It is the intermediate dict which is the problem.

**Comment by kristjanvalur** [comment]
Handler1 is type any, yes, but handler2 is typed.  That is the whole point.  Please don't close this without a dialogue.  This problem stems from a production system (Starlette).

**Comment by hauntsaninja** [comment]
In the single line version, mypy is able to use type context to infer the type of the dictionary based on its usage.

mypy is not capable of using multiline or whole program type context (and I'm not aware of another type checker that does); if you have a lot of Any's floating around in your program, you'll want to give your variables explicit types.

mypy does have some extremely strict options like `--disallow-any-expr` that will complain about this, but if your codebase is at a point where it has unannotated functions that option is likely going to be too strict.

In general, behaviour around Any is specified by PEP 484 and is an important part of gradual typing.

**Comment by kristjanvalur** [comment]
Okay, this is the problem, distilled.  Callable[[Any]] silently seems to work wrong.  Or, shall we say, this is quite expected.  I mean, yes, this is what I would expect for the _return_ value, but not _arguments_

```python
from typing import Callable, Any

def handler(arg:int) -> int:
    return 1

callback: Callable[[Any],int] = handler  # shouldn't be ok!
callback("foo")  # This is fine!
```

**Comment by JelleZijlstra** [comment]
`Any` is compatible with everything and everything is compatible with `Any`. That's how it's supposed to work. If you don't want type unsafety, annotate your functions and don't use Any.

**Comment by kristjanvalur** [comment]
Yes, quite, but the original case is that an accidental use of Any (by having one function untyped) _poisons_ the dict so that all of the other callables added to it silently get cast to Any too, and this is without warning, even on --strict.

In this particular case, developers were quite unaware that a number of functions they carefully had typed were in fact not bein type-checked, because they got assigned to a collection with an un-typed function, and the whole lot then got recast as Any.  I'd say that is a bit unexpected, from my point of view, at least.
