### ISSUE TITLE
Arguments of `type[bool]` and `type[int]` are considered overlapping

### ISSUE THREAD

**Issue by Dr-Irv** [python/mypy#14772]
**Bug Report**

If you have a function/method where the arguments can be `type[int]` or `type[bool]`, but the resulting function returns different types based on the type argument, mypy reports them as being overlapping.  (pyright does not)

**To Reproduce**

```python
@overload
def getval(x: type[bool]) -> bool:
    ...


@overload
def getval(x: type[int]) -> str:
    ...


def getval(x: type[bool] | type[int]) -> bool | str:
    if x == bool:
        return True
    elif x == int:
        return "abc"
    else:
        raise Exception("bad argument")

```

**Expected Behavior**

No error from mypy .   `type[bool]` and `type[int]` should be considered distinct.  (This is needed for pandas-stubs)

**Actual Behavior**

boolinttypes.py:5: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [misc]

**Your Environment**

- Mypy version used:  1.0
- Mypy command-line flags:  None
- Mypy configuration options from `mypy.ini` (and other config files):  None
- Python version used:  3.10

**Comment by hauntsaninja** [comment]
`bool` is a subclass of `int` at runtime, so mypy is doing the right thing here. Sometimes in stubs you need to silence the "overlap with incompatible return types" error; mypy will still use the overlapping overloads to resolve types the way you intend, despite it being unsound.

**Comment by erictraut** [comment]
I agree with @hauntsaninja. Mypy is correct here.

Pyright also flags this as an overlapping overload if you enable the `reportOverlappingOverload` check.

**Comment by Dr-Irv** [comment]
It would be nice if there was an annotation that meant "match this exact type and NOT a subclass" .

**Comment by hauntsaninja** [comment]
Such an annotation would either be unsound or would require assertions in every caller. It's okay for `# type: ignore` to be the right solution sometimes.

**Comment by Dr-Irv** [comment]
> Such an annotation would either be unsound or would require assertions in every caller. It's okay for `# type: ignore` to be the right solution sometimes.

Maybe.  But in pandas, we (at runtime - not in typing yet!), support `pd.Series([1,2,3], dtype=int)`, but we don't support `pd.Series([1,2,3], dtype=IntSubclass)`, where `IntSubclass` is a subclass of `int`.  So if typing had something like `StrictType[int]`, that would help in this particular case.

**Comment by gandhis1** [comment]
This almost feels like the `Sequence` vs `str` debate elsewhere, where implementations often care about this distinction but annotations don't necessarily by virtue of the type hierarchy. And just like there, where for instance `pytype` ignored soundness in favor of practicality, I wonder whether here too that would lead to a better developer experience. Not just for overloads - for everything. But I'm sure this has been raised and debated elsewhere already, so I won't press the issue.

**Comment by JelleZijlstra** [comment]
For the pandas use case it sounds like what would make sense is supporting `Literal[int]` to mean "exactly the `int` type".

**Comment by hauntsaninja** [comment]
@gandhis1 No, I don't think this is like that. As far as I'm aware there aren't any soundness implications based on whether to consider str a Sequence or not. The only consideration there is whether to model the runtime accurately or not.

Soundness is important because without soundness the type checker doesn't guarantee you everything.

Jelle's suggestion of Literal is a good way to spell the "callers should assert" option in https://github.com/python/mypy/issues/14772#issuecomment-1442376933

**Comment by erictraut** [comment]
I don't think the notion of a `Literal[int]` makes sense in the Python type system. Would `Literal[int]` be incompatible with `1` which has a type of `Literal[1]`? The type system is built on the notion of subtyping. For better or worse, `bool` is a subtype of `int`, as is `Literal[1]`.

**Comment by Dr-Irv** [comment]
> I don't think the notion of a `Literal[int]` makes sense in the Python type system. Would `Literal[int]` be incompatible with `1` which has a type of `Literal[1]`? The type system is built on the notion of subtyping. For better or worse, `bool` is a subtype of `int`, as is `Literal[1]`.

What if there was support for `Literal[type[int]]`, which would mean "a type that is `int` and not a subclass of `int`" ?

**Comment by JelleZijlstra** [comment]
@erictraut I'm not sure what the issue is. `Literal[int]` would mean "exactly the `int` type", just as `Literal[1]` means "exactly the value 1". `True` is also not acceptable as a value for `Literal[1]`.
