### ISSUE TITLE
Release 0.4 on pypi + write blog post

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1481]

**Comment by JukkaL** [comment]
Done. Blog post here: http://mypy-lang.blogspot.co.uk/2016/05/mypy-04-released.html

**Comment by kirbyfan64** [comment]
@JukkaL You haven't updated http://mypy-lang.org yet. Also, I already posted this to Reddit. :)

**Comment by JukkaL** [comment]
Web site is now updated.
