### ISSUE TITLE
AttributeError: attribute 'arguments' of 'FuncDef' undefined

### ISSUE THREAD

**Issue by nbro10** [python/mypy#14812]
**Bug Report**

```
/Users/ME/Library/Caches/pypoetry/virtualenvs/my_package-dyX6J5JG-py3.8/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py:700: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.950
Traceback (most recent call last):
  File "mypy/checker.py", line 425, in accept
  File "mypy/nodes.py", line 740, in accept
  File "mypy/checker.py", line 776, in visit_func_def
  File "mypy/checker.py", line 787, in _visit_func_def
  File "mypy/checker.py", line 1494, in check_method_override
  File "mypy/checker.py", line 1522, in check_method_or_accessor_override_for_base
  File "mypy/checker.py", line 1608, in check_method_override_for_base_with_name
  File "mypy/checker.py", line 1770, in check_override
  File "mypy/messages.py", line 876, in signature_incompatible_with_supertype
  File "mypy/messages.py", line 898, in pretty_callable_or_overload
  File "mypy/messages.py", line 2019, in pretty_callable
AttributeError: attribute 'arguments' of 'FuncDef' undefined
/Users/ME/Library/Caches/pypoetry/virtualenvs/my_package-dyX6J5JG-py3.8/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py:700: : note: use --pdb to drop into pdb
```

Error occurs at this line of `/Users/ME/Library/Caches/pypoetry/virtualenvs/my_package-dyX6J5JG-py3.8/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py:700`

```
    def result(  # type: ignore  # (signature complaint)
        self, retry: "retries.Retry" = DEFAULT_RETRY, timeout: float = None
    ) -> "_AsyncJob":

```

**To Reproduce**

```python
poetry run mypy my_package
```

Clearly, I cannot share `my_package`.

Poetry version: `Poetry (version 1.3.2)`

**Expected Behavior**

No error

**Actual Behavior**

See above

**Your Environment**

- Mypy version used:  0.950
- Mypy command-line flags: `--show-traceback`
- Mypy configuration options from `mypy.ini` (and other config files):

```

[tool.mypy]
python_version = 3.8
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
...
]
ignore_missing_imports = true

```

- Python version used: 3.8.13
- `google-cloud-bigquery         3.6.0      Google BigQuery API client library`

**Similar issues**

Many, I lost the count

**Possible solutions (suggested by me to myself)**

Try to update mypy. See https://mypy-lang.blogspot.com/2022/

**Comment by AlexWaygood** [comment]
> I haven't looked too deeply but I remember seeing various other similar crashes with this same error. We probably fixed this already; 0.950 is pretty old by now.

Agreed. I think we can close this for now — but feel free to open a new issue if the crash still occurs with mypy 1.0.1 (or ping us here, and we can reopen this).
