### ISSUE TITLE
mypy 1.1.1 spits out invalid python suggestions for overloads

### ISSUE THREAD

**Issue by zzzeek** [python/mypy#14858]
apologies if I don't understand what mypy is getting at here syntax wise,  below is a dictionary subclass that has typed correctly up until mypy 1.0.0:

```py
from typing import TYPE_CHECKING, TypeVar, Dict, Optional, overload

_KT = TypeVar("_KT")
_VT = TypeVar("_VT")


class MutableDict(Dict[_KT, _VT]):

    if TYPE_CHECKING:


        @overload
        def setdefault(self, key: _KT) -> Optional[_VT]:
            ...

        @overload
        def setdefault(self, key: _KT, value: _VT) -> _VT:
            ...

        def setdefault(
            self, key: _KT, value: Optional[_VT] = None
        ) -> Optional[_VT]:
            ...

```

under mypy 1.1.1 we now see:

```
test3.py:12: error: Signature of "setdefault" incompatible with supertype "MutableMapping"  [override]
test3.py:12: note:      Superclass:
test3.py:12: note:          @overload
test3.py:12: note:          def setdefault(self, _KT, None = ..., /) -> Optional[_VT]
test3.py:12: note:          @overload
test3.py:12: note:          def setdefault(self, _KT, _VT, /) -> _VT
test3.py:12: note:      Subclass:
test3.py:12: note:          @overload
test3.py:12: note:          def setdefault(self, key: _KT) -> Optional[_VT]
test3.py:12: note:          @overload
test3.py:12: note:          def setdefault(self, key: _KT, value: _VT) -> _VT
```

I dont know what it wants me to do.  that "None" is not valid python.   Here is that file:

```py
from typing import TYPE_CHECKING, TypeVar, Dict, Optional, overload

_KT = TypeVar("_KT")
_VT = TypeVar("_VT")


class MutableDict(Dict[_KT, _VT]):

    if TYPE_CHECKING:


        @overload
        def setdefault(self, _KT, None = ..., /) -> Optional[_VT]:
            ...


        @overload
        def setdefault(self, _KT, _VT, /) -> _VT:
            ...

        def setdefault(
            self, key: _KT, value: Optional[_VT] = None
        ) -> Optional[_VT]:
            ...
```

that's a syntax error.    Can the suggestion show what we should be doing exactly?

**Comment by AlexWaygood** [comment]
Ah, that's quite unfortunate. I believe this is due to the way mypy is displaying positional-only arguments here -- it's just showing you the type, and not the argument name (because of the fact that the argument name is irrelevant when the argument is positional-only, I guess). Which results in a highly confusing suggestion in this instance.

I believe the immediate trigger for the suggestion getting worse here was probably https://github.com/python/typeshed/commit/9e71de0421e007faa22ab6d2fc04f6092b79be34.

What mypy wants you to do is to allow users to pass in a second argument for the first overload iff the second argument is `None`. I.e.:

```diff
  from typing import TYPE_CHECKING, TypeVar, Dict, Optional, overload
  
  _KT = TypeVar("_KT")
  _VT = TypeVar("_VT")
  
  
  class MutableDict(Dict[_KT, _VT]):
  
      if TYPE_CHECKING:
  
  
          @overload
-         def setdefault(self, key: _KT) -> Optional[_VT]:
+         def setdefault(self, key: _KT, value: None = None) -> Optional[_VT]:
              ...
  
          @overload
          def setdefault(self, key: _KT, value: _VT) -> _VT:
              ...
  
          def setdefault(
              self, key: _KT, value: Optional[_VT] = None
          ) -> Optional[_VT]:
              ...
```

That will then match the new signature for `MutableMapping.setdefault` in typeshed's stub for `typing.pyi`.

**Comment by zzzeek** [comment]
Yeah the above code is what I tried but still fails now (did not fail in 1.0.0).  is this due to changes in typeshed?   overall it's been very difficult to make Python types that subclass Dict, Mapping, Set, etc.   The rules for these methods are extremely difficult to get right and as we see here they keep changing also.

**Comment by erictraut** [comment]
Is there anything actionable for mypy in this issue? It looks like Alex's answer to the question works fine.

**Comment by zzzeek** [comment]
looks fine now, my program at the top passes on current mypy versions without issue.
