### ISSUE TITLE
setup.py install fails to install a working mypy script on OS X

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1487]
I tried `setup.py install` with Python 3 installed via `brew install python3` only. I ran Python as `/usr/local/Cellar/python3/3.5.1/bin/python3`. Now I can't run `mypy`, but `<python3> -m mypy` works. This is probably and old issue and maybe this isn't even supposed to work?

```
$ mypy
-bash: /usr/local/bin/mypy: /usr/local/opt/python3/bin/python3.5: bad interpreter: No such file or directory
$ cat /usr/local/bin/mypy
#!/usr/local/opt/python3/bin/python3.5
"""Mypy type checker command line tool."""

from mypy.main import main

main(__file__)
```

**Comment by JukkaL** [comment]
This also happens when installing Python 3.5 using the official installer.

**Comment by gvanrossum** [comment]
(Sorry about the topic changes. I just saw the second comment. We'll have to look into this later.)

**Comment by ilevkivskyi** [comment]
I have not seen this problem on my two macs for few years, so I suppose it is fixed now.
