### ISSUE TITLE
Continuous assertions

### ISSUE THREAD

**Issue by mcclurem** [python/mypy#14897]
**Feature**

Propose new syntax to allow for "continuous assertions" that can be used for both inference as well as for testing logical behavior.
Primarily this is for the purpose of helping refine types, usually Optionals, however this could be extended to checking for contradictions

**Pitch**

Often times you need to build up state inside a class incrementally and so you might have many Optionals that are first initialized to None, but then after initializing the variable you'll want to use it without putting tons of guard if statements or assertions in place. Oftentimes you want a single sentry variable that can be used instead of multiple tests.
Contrived example:
```python
import asyncio
from typing import Optional

class MyComplicatedTask:
    def __init__(self) -> None:
        self.first_task:Optional[asyncio.Task] = None
        self.second_task:Optional[asyncio.Task] = None
        self.tasks_running:bool = False

    def start_tasks(self) -> None:
        self.first_task = asyncio.create_task(self.first_task_func(), name="first_task")
        self.second_task = asyncio.create_task(self.second_task_func(), name="second_task")
        self.tasks_running = True

    async def wait_for_the_tasks(self) -> None:
        if not self.tasks_running:
            print("ideally, this would be sufficient for inference of type of self.first_task/self.second_task but it's not")
            return
        await asyncio.wait_for(asyncio.shield(self.first_task), 20)
        await asyncio.wait_for(asyncio.shield(self.second_task), 20)
        self.tasks_running = False
        self.first_task = None
        self.second_task = None

    async def first_task_func(self) -> None:
        for i in range(10):
            await asyncio.sleep(1)

    async def second_task_func(self) -> None:
        for i in range(10):
            await asyncio.sleep(1)
```

It would be really great to be able to add a hint syntax something like
```python
always assert self.first_task is not None if self.tasks_running
always assert self.second_task is not None if self.tasks_running
```

with this added information, it would be possible for the checker to infer the not-none-ness of various locations as well as flag violations of the assertion (for example if the setting of the `tasks_running` flag was done out of order from setting the tasks to None)

This likely would need to be some comment-based syntax or else requires a full PEP I'm not sure

**Comment by AlexWaygood** [comment]
Runtime features that require new syntax need to be discussed at https://discuss.python.org/.

Proposals for the typing system that would impact other type checkers as well as mypy need to be discussed on the https://github.com/python/typing issue tracker.
