### ISSUE TITLE
Value of type variable "Self" of "__new__" of "tuple" cannot be <some subclass of typing.Tuple>

### ISSUE THREAD

**Issue by robsdedude** [python/mypy#14890]
**Bug Report**

Starting with version 1.1, I get an error when calling `Tuple[float, ...]`'s `__new__`.

**To Reproduce**

```python
from typing import Iterable, Tuple


class Foo(Tuple[float, ...]):
    def __new__(cls, values: Iterable[float]) -> Foo:
        return tuple.__new__(cls, map(float, values))
```

**Expected Behavior**

This should not be rejected by mypy (and it wasn't until version 1.1.1)

**Actual Behavior**

Starting with mypy 1.1.1, mypy complains with the following error
```
test.py:8: error: Value of type variable "Self" of "__new__" of "tuple" cannot be "Foo"  [type-var]
```

**Remark**
Changing `tuple.__new__` to `super().__new__` makes mypy complain (both mypy version 1.1.1 and 1.0.1) with 
```
Argument 1 to "map" has incompatible type "Type[float]"; expected "Callable[[float], _T_co]"
```

**Your Environment**

- Mypy version used: 1.1.1 and 1.0.1
- Mypy command-line flags: none
- Mypy configuration options from ` pyproject.toml`:
  ```toml
  [tool.mypy]
  
  [[tool.mypy.overrides]]
  module = "pandas.*"
  ignore_missing_imports = true
  ```
- Python version used: tested on 3.8 and 3.11

**Comment by AlexWaygood** [comment]
Probably due to this change in typeshed, where we moved from using a `TypeVar` in `tuple.__new__` to using `typing_extensions.Self`: https://github.com/python/typeshed/pull/9694/files#diff-1580ddf7dc331234b0845ffb953b6f7a5f1e9afa15048ebc0762226a08f194b4R915-R916

**Comment by AlexWaygood** [comment]
Cc. @ilevkivskyi as the person who implemented `typing.Self`.

If need be, we could maybe revert the change to `tuple.__new__` in typeshed, but it would make it inconsistent with all the other `__new__` methods in typeshed. I'm also not sure I'd want to do that unless we were sure this was a tuple-specific problem that didn't affect any other classes.

**Comment by ilevkivskyi** [comment]
This passes without errors on current master.
