### ISSUE TITLE
`Optional[str]` not adapted to `str` by `all()`

### ISSUE THREAD

**Issue by ChrisHills463** [python/mypy#14901]
**Bug Report**

If a variable has type `Optional[str]`, it is not adapted to `str` by `all()`.

**To Reproduce**

```python
import os

def some_func(arg: str):
    print(arg)

a = os.environ.get("a", None)

if a:
    # OK
    some_func(a)

if all([a]):
    # error: Argument 1 to "some_func" has incompatible type
    #        "Optional[str]"; expected "str"  [arg-type]
    some_func(a)
```

https://mypy-play.net/?mypy=latest&python=3.11&gist=f6c53f4784c2045a6e1d7cdbf4d65a91

**Expected Behavior**

all() guarantees that variables defined are not None, so there should be no errors.

**Actual Behavior**

`error: Argument 1 to "some_func" has incompatible type "Optional[str]"; expected "str"  [arg-type]`

**Your Environment**

- Mypy version used: latest (1.0.0)
- Mypy command-line flags: see playground
- Mypy configuration options from `mypy.ini` (and other config files): see playground
- Python version used: 3.11 (playground)

**Comment by sobolevn** [comment]
Yes, this is kinda complex inferece, that is not supported at the moment.
