### ISSUE TITLE
`abstractclassmethod` not equal to `abstractmethod` with `classmethod`

### ISSUE THREAD

**Issue by zyxkad** [python/mypy#14920]
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

<https://gist.github.com/zyxkad/e3043ccfbdf4260d80b4c45a502db6ed>
```python
from abc import ABC, abstractclassmethod

class A(ABC):
	@abstractclassmethod
	def func(cls, a: int) -> str:
		raise NotImplementedError()

class B(A):
	@classmethod
	def func(cls, a: int) -> str: # L11: error happend here
		return str(a)
```

**Expected Behavior**

There should be no error

**Actual Behavior**

```
a.py:11: error: Signature of "func" incompatible with supertype "A"  [override]
```

**Your Environment**

- Mypy version used: **mypy 1.0.1**
- Mypy command-line flags: *None*
- Mypy configuration options from `mypy.ini` (and other config files): *None*
- Python version used: **Python 3.11.2**

**Comment by zyxkad** [comment]
I tried split the `abstractclassmethod` into `abstractmethod` and `classmethod`. It seems works fine.
I think you only need to let mypy skip `abstractclassmethod`

**Comment by erictraut** [comment]
`abstractclassmethod` has been deprecated since Python 3.3 according to the [documentation](https://docs.python.org/3/library/abc.html#abc.abstractclassmethod), so it's a good idea to avoid using it in favor of separate `@abstractmethod` and `@classmethod` decorators.

**Comment by zyxkad** [comment]
Oh, I see, thanks :)
