### ISSUE TITLE
[stubtest] Consider support `@override` decorator

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#14925]
Right now this source code:

```python
from typing import override

class A:
   def method(self) -> None: ...

class B(A):
   @override 
   def method(self) -> None: ...
```

and this stub:

```python
from typing import override

class A:
   def method(self) -> None: ...

class B(A):
   def method(self) -> None: ...
```

will pass the `stubtest`.

The question is: do we need to support `@override` and require it?

I am leaning to the "maybe not" answer, why?
1. Ideally we can just remove `B.method`, because it has the same typing signature. It is a duplicate
2. `@override` does not add any new information to our users. It does not help them (except when they are reading the stub code)
3. I don't know any real-life examples of source code that uses it with the `stubtest`. Because this is quite a modern typing feature. Usually modern typing features mean that user uses in-code type annotations and does not need external stubs

But, I am open to other arguments!

**Comment by AlexWaygood** [comment]
> I am leaning to the "maybe not" answer, why?
> 
> 1. Ideally we can just remove `B.method`, because it has the same typing signature. It is a duplicate
> 2. `@override` does not add any new information to our users. It does not help them (except when they are reading the stub code)

Yeah, you've persuaded me that this probably isn't worth doing :) I agree that it doesn't seem to make much difference to the stubs whether or not the runtime version is decorated with `@override` or not!

**Comment by sobolevn** [comment]
Let's close it for now, if any other use-cases are discovered, we can always reopen.
