### ISSUE TITLE
Fast parser fails with syntax error on Zulip codebase

### ISSUE THREAD

**Issue by timabbott** [python/mypy#1493]
I haven't debugged what the cause is, but this is a pretty easily reproducer after cloning https://github.com/zulip/zulip:
```
tabbott@zaset:~/zulip$ mypy -s --py2 --fast-parser zerver/lib/rate_limiter.py
zerver/lib/rate_limiter.py:23: error: invalid syntax
```

**Comment by ddfisher** [comment]
This is the line in question:
```python
return [tuple(int(l) for l in limit.split(':')) for limit in user.rate_limits.split(',')] # type: List[Tuple[int, int]]
```

The fast parser gives a syntax error when a type comment is used in an invalid position, as is the case here.  This is partly so invalid type comments don't get silently ignored (which would result in unexpected/hard to find overpermissiveness), and partly for historical reasons.

**Comment by timabbott** [comment]
Hmm, yeah, that code was totally busted.  Fixed by deleting the type comment and moving it to the return statement.  Thanks @ddfisher!  Leaving this open in case you want to make the error message clearer.

**Comment by rwbarton** [comment]
I haven't tried Tim's reproducer, but for an invalid type annotation like this (missing parentheses around argument type):
```py
def h(x):
    # type: float -> int
    return 'a'
```
the error message looks at first like a mypy crash rather than an error in the input program:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
[... many lines omitted ...]
  File "/Users/rbarton/mypy/mypy/fastparse.py", line 237, in visit_FunctionDef
    func_type_ast = ast35.parse(n.type_comment, '<func_type>', 'func_type')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/typed_ast/ast35.py", line 42, in parse
    return _ast35._parse(source, filename, mode)
SyntaxError: invalid syntax (<func_type>, line 1)

*** INTERNAL ERROR ***

x/T1517b.py: error: Internal error -- please report a bug at https://github.com/python/mypy/issues

NOTE: you can use "mypy --pdb ..." to drop into the debugger when this happens.
```
Tim, is that what you're referring to by making the error message clearer?

**Comment by timabbott** [comment]
I didn't get the crash you show (I guess how it handles an annotation on a `return` statement is different); what I had in mind in either:
(1) Making clear what's wrong with the syntax (e.g. "invalid syntax: annotation on invalid line")
(2) Make the fast parser consistent with the non-fast parser (which doesn't complain), if that's something you folks care about :)

**Comment by ddfisher** [comment]
(1) is important and we want to do that.  As for (2), we actually consider the fast parser's behavior to be better here.

**Comment by timabbott** [comment]
OK, maybe we should rename this ticket to something about making the parser errors clearer?

**Comment by ddfisher** [comment]
I forgot to circle back, but I actually did that yesterday in this commit: https://github.com/dropbox/typed_ast/commit/e4c4b812a122859a8aa5596ed29f6109224c446b

**Comment by gvanrossum** [comment]
I think this is ready to be closed. (Reopen if I misunderstood.)
