### ISSUE TITLE
MyPy not recognizing "self" type of protocol

### ISSUE THREAD

**Issue by JamesHutchison** [python/mypy#14937]
**Bug Report**

Perhaps this is user error, but I have tried various things and consulted with GPT 4.0 and cannot arrive at a solution that allows me to define a generic type and its return value.

If this is possible, I would request that an example is provided in the documentation (or provided with more visibility if it is already somewhere) as I do not see this use case as being that far fetched.

**To Reproduce**
```python
from __future__ import annotations
from typing import Generic, Protocol, TypeVar

R_co = TypeVar("R_co", covariant=True)


class CallableProtocol(Protocol[R_co]):
    def __call__(self) -> R_co:
        ...


T = TypeVar("T", bound=CallableProtocol)


class Foo(Generic[T, R_co]):
    def __init__(self, val: T) -> None:
        self._val = val

    def my_val_response(self) -> R_co:
        return self._val()

    def my_val(self) -> T:
        return self._val


class SomeCallable:
    def __call__(self) -> str:
        return str(5)


# Need type annotation for "bar"
bar = Foo(SomeCallable())
```

The issue seems to be that MyPy doesn't know what `T`, the `self` argument, is. If I remove that and only have the return value be generic, I do not get this problem.

I've also tried (and appropriately updated the example elsewhere):

```python
class CallableProtocol(Protocol[T_co, R_co]):
    def __call__(self: T_co) -> R_co:
        ...
```

and a few other things.

**Expected Behavior**

MyPy has enough information to determine the type, so I would expect it to know it and not require the developer to provide a type annotation.

**Actual Behavior**

MyPy errors and states that a type annotation is required. In other words, the user must type out:

`bar: Foo[SomeCallable, str] = Foo(SomeCallable())`

**Your Environment**

Python 1.11
MyPy 1.1.1
Unix dev container

**Comment by erictraut** [comment]
Yes, you don't need the `T_co` type variable here. The `self` parameter requires no annotation.

```python
R_co = TypeVar("R_co", covariant=True)

class CallableProtocol(Protocol[R_co]):
    def __call__(self) -> R_co:
        ...

class Foo(Generic[R_co]):
    def __init__(self, val: CallableProtocol[R_co]) -> None:
        self._val = val

    def my_val_response(self) -> R_co:
        return self._val()

    def my_val(self) -> CallableProtocol[R_co]:
        return self._val

class SomeCallable:
    def __call__(self) -> str:
        return str(5)

bar = Foo(SomeCallable())
```

Or if you'd like this to work with callables with arbitrary signatures, you could use a `ParamSpec`.

```python
R_co = TypeVar("R_co", covariant=True)
P = ParamSpec("P")

class CallableProtocol(Protocol[P, R_co]):
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R_co:
        ...

class Foo(Generic[P, R_co]):
    def __init__(self, val: CallableProtocol[P, R_co]) -> None:
        self._val = val

    def my_val_response(self, *args: P.args, **kwargs: P.kwargs) -> R_co:
        return self._val(*args, **kwargs)

    def my_val(self) -> CallableProtocol[P, R_co]:
        return self._val
```

**Comment by JamesHutchison** [comment]
Thanks! That's unblocked me. If we feel that mypy should handle the case I presented, as presented, then we can leave this ticket open, otherwise I'm fine with closing. It's currently a bug ticket.

**Comment by JamesHutchison** [comment]
Actually, I might still be stuck. I want `my_val()` to be typed against the callable class and not typed against the protocol. I see `CallableProtocol[Foo] has no attribute "z"`

**Comment by erictraut** [comment]
If you simply need to record the fact that the value is callable along with its return type, you can use the following.

```python
class Foo(Generic[R_co]):
    def __init__(self, val: Callable[[], R_co]) -> None:
        self._val = val

    def my_val_response(self) -> R_co:
        return self._val()

    def my_val(self) -> Callable[[], R_co]:
        return self._val
```

If you want to capture the exact type of the callable and make it generic in its return type, then I don't think there's a way to do that in today's Python type system. To do this, you'd need a feature called "higher-kinded types" (HKTs) which allow a TypeVar to be parameterized by another TypeVar. There have been some discussions about adding HKTs to the type system, but they haven't gone very far.

As for your original bug report about the `self` type of a protocol, I think mypy is doing the correct thing here based on the way protocols are defined in the type system, so this isn't a bug.

**Comment by JamesHutchison** [comment]
> I don't think there's a way to do that in today's Python type system

After much flailing, I agree. Very unfortunate.

> As for your original bug report about the self type of a protocol, I think mypy is doing the correct thing here based on the way protocols are defined in the type system, so this isn't a bug.

I can understand this behavior as a technical limitation that simply hasn't been worked on, but I would need more context to understand why this would be desired or correct behavior. From what I can tell, mypy will throw that `Need type annotation` error whenever mypy doesn't know how to fill in the value. Its like a soft error. A user could flub on various things and the end result is the same. Is there a circumstance where type annotating the `self` argument in a protocol does something useful?

**Comment by erictraut** [comment]
In your (corrected) sample at the top of this bug report, the constructor for `Foo` references the type variable `T`, but it doesn't reference `R_co`. That means there's no way for a type checker to infer the type of `R_co` based on the arguments passed to the constructor. Mypy's error message is telling you this.

You could provide the type arguments for `Foo` explicitly by constructing it as follows:
```python
bar = Foo[SomeCallable, str](SomeCallable())
```

**Comment by JamesHutchison** [comment]
Correct! However, for my use case I am writing a developer convenience library and unfortunately, having the developer write out the types would create a burden, which moves against the objectives of my library. I would rather ask the user to cast the return value as needed than have the class in question instantiated in this manner.

**Comment by erictraut** [comment]
I don't think there's anything actionable for mypy to do in this bug. Recommend closing.
