### ISSUE TITLE
Get attr-defined & name-defined error when use protobuf

### ISSUE THREAD

**Issue by CwjXFH** [python/mypy#14935]
Hi,
I use protobuf in my code and generated a py file using the command: `protoc --python_out=. samples/msg.proto`, my proto file is:
```proto
syntax = "proto3";

message MsgPackage
{
  message Msg
  {
    uint32 code = 1;
    string msg = 2;
  }

  repeated Msg messages = 1;
}
```
|Package|Version|
|---|---|
|Python|3.11.2|
|mypy|1.0.1
|protobuf|4.22.0|

![image](https://user-images.githubusercontent.com/11468733/226916526-4e89962c-d389-43ce-bdab-f2b4591a57e8.png)

The [Python protocol buffer compiler](https://protobuf.dev/getting-started/pythontutorial/#protobuf-api) doesn’t generate data access code directly, it create type dynamic. So executing the type check by mypy will get some errors:
![image](https://user-images.githubusercontent.com/11468733/226917705-5f44ee32-2d6b-42b4-b414-dafe9bb83137.png)

How do I resolve the error like: ` Name "MsgPackage.Msg" is not defined`

Thanks!

**Comment by erictraut** [comment]
You can use the protoc plugin [mypy-protobuf](https://github.com/nipunn1313/mypy-protobuf) to generate type stubs that are compatible with Python type checkers like mypy.

**Comment by CwjXFH** [comment]
It works, thanks!
