### ISSUE TITLE
mypy.bat is missing from the pypi download (version 0.4)

### ISSUE THREAD

**Issue by kearnh** [python/mypy#1495]
I tried to update mypy-lang with pip on Windows, which failed because mypy.bat was missing. To install I had to extract the download from pypi, manually copy mypy.bat into the scripts directory, and run "py -3 setup.py install".

**Comment by JukkaL** [comment]
This is because I created the package on OS X but setup.py only includes the .bat file when run on Windows. Perhaps we can use MANIFEST.in as mentioned in #1489.

Oh well, we'll probably need to do a 0.4.1 release soon.

**Comment by gvanrossum** [comment]
Fixed, we've released 0.4.1.

**Comment by AngeloSalvade** [comment]
Seems to be missing again in 0.470.

**Comment by gvanrossum** [comment]
Thanks, confirmed. I've opened a new issue (#2688).
