### ISSUE TITLE
Error on destructuring syntactic sugar

### ISSUE THREAD

**Issue by Xophmeister** [python/mypy#1496]
In Python 3.5 onwards, you can do, for example:

``` python
foo = {'a': 123, 'b': 456}
bar = {**foo, 'b': 789}
```

...this will destructure `foo` into `bar` and then override the `b` element (so `bar == {'a': 123, 'b': 789}`). This bit of syntactic sugar is particularly useful for overriding defaults. You can also do something similar with destructuring tuples, although I guess that's less useful (e.g., `foo = (*bar, x, y, z)`),

Anyway, Mypy (0.4) tags this as a parse error in the dictionary case and an internal error for tuples.

**Comment by JukkaL** [comment]
I don't think that the new destructuring syntax of Python 3.5 is supported at all by mypy yet. The new parser will likely parse it, though.

**Comment by gvanrossum** [comment]
I'm going to close this as a won't fix because the new parser will solve this and we're not going to put any work in the old parser/lexer.
