### ISSUE TITLE
Objects matching `SupportsKeysAndGetItem[str, Any]` cannot be used after `**`

### ISSUE THREAD

**Issue by bryanforbes** [python/mypy#14986]
**Bug Report**

Given the following code:

```python
from __future__ import annotations

from collections.abc import Iterable
from typing import Any


class MyThing:
    def keys(self) -> Iterable[str]:
        return ['foo']

    def __getitem__(self, __key: str) -> Any:
        return 'bar'


def foo(**args: Any) -> None:
    print(args)


foo(**MyThing())
```

`mypy` generates an error at line 19: `Argument after ** must be a mapping, not "MyThing"`

**Expected Behavior**

No error should be generated since it works at runtime. This has been [discussed](https://github.com/python/typing/discussions/1375) over in the Python Type School, and `pyright` [has been updated](https://github.com/microsoft/pyright/issues/4826) to support this.

**Your Environment**

- Mypy version used: 1.1.1
- Mypy command-line flags: n/a
- Mypy configuration options from `mypy.ini` (and other config files): n/a
- Python version used: 3.10.10

**Comment by hauntsaninja** [comment]
Should be https://github.com/python/mypy/blob/c99133f405f286ed3429c809e9ae2cb3faaa2ceb/mypy/checkexpr.py#L2129 if someone wants to pick this up!

**Comment by bryanforbes** [comment]
@hauntsaninja so that could simply be changed to `self.chk.named_type("_typeshed.SupportsKeysAndGetItem")`?

**Comment by hauntsaninja** [comment]
There's a good chance the core of that change is that simple. Will need some effort in unit tests as well, since I don't think we currently have a `_typeshed` stub in unit tests.

**Comment by bryanforbes** [comment]
@hauntsaninja Well, I gave it a shot. I figured out that there are a couple of other places that need to be changed:

https://github.com/python/mypy/blob/89469ac51aff1eefcd693d87d621577370ddedb4/mypy/checkexpr.py#L4933-L4950

Both of those need to be changed from `typing.Mapping` to `_typeshed.SupportsKeysAndGetItem`. With the change to the line you noted as well as these extra changes, it seems that it fixes the issue (when I run tests by calling `python -m mypy foo.py` in my venv).

However, I'm unable to get the unit tests to pick up a `_typeshed.pyi` file in `test-data/unit/lib-stub` or in `test-data/unit/fixtures` (I had to modify `mypy/test/data.py` to attempt the latter, but it still didn't work). It's been a while since I've worked on mypy, so I may be missing something really simple. The changed calls always raise `KeyError: '_typeshed'` in the unit test runner.

**Comment by hauntsaninja** [comment]
Might need to do something like `import _typeshed` in the `builtins.pyi` fixture so that it's always part of the mypy build. Also feel free to open a draft PR and I can help fix up whenever I get time

**Comment by bryanforbes** [comment]
@hauntsaninja I was able to fix some of the unit test issues by updating the `Mapping` and `dict` definitions to add `keys()` and `__getitem__()` where needed and adding `import _typeshed` to some fixture files, but I'm still running into problems. This may be better solved by coming up with a way to force `mypy` to evaluate `_typeshed` early (much like it does with `builtins`).
