### ISSUE TITLE
MyPy doesn't understand types.ModuleType

### ISSUE THREAD

**Issue by wittekm** [python/mypy#1498]
I tried doing `# type: (module) -> str` and MyPy was okay with it, but our linter was not. Some discussion in our Slack channel:

> Guido:
> From types import ModuleType?
> Oh wow. Please file a bug. Mypy uses builtins.module but that doesn't exist so can't be used at runtime; types.ModuleType exists but mypy doesn't understand it.
> 
> David Fisher:
> oh interesting
> we have a "class module" entry in builtins
> with the comment `# TODO not defined in builtins!`

**Comment by gvanrossum** [comment]
Yeah, so apparently when mypy sees a variable that's a module (as opposed to just an import statement) it gives it the type `builtins.module` even though that doesn't exist. The actual type of module objects is `types.ModuleType`. This would probably be easy to fix.
