### ISSUE TITLE
[name-defined] Ignore some errors based on str/regex

### ISSUE THREAD

**Issue by yorickbrunet** [python/mypy#15005]
**Feature**

mypy raises **name-defined** error when a name is not known.
The new feature would allow to modulate the raise of such a error based on a string or a regex to be able to ignore some potential errors.

**Pitch**

I'm developing Python code for the Aimsun Next simulator.
The Python code runs within the simulator, using its API.
Each Python file must include `from AAPI import *` to import the Aimsun Next API.
The functions are named with a specific naming, for example `AKIPrintString`.
When I run mypy on my code (outside of the simulator), these functions are unknown and mypy returns an error for each used function, e.g.:
```
Simulation/vehicule.py:22:27  Name "boolp" is not defined  [name-defined] [mypy]
Simulation/simulation.py:69:9  Name "AKIPrintString" is not defined  [name-defined] [mypy]
```

The requested feature would allow the developer to tell mypy to ignore unknown code based on string or regex, e.g.
```
ignore-name-defined = boolp, AKI.*
```

**Comment by hauntsaninja** [comment]
Maybe you could add type stubs to `AAPI`? 

Thanks for the suggestion, but we're unlikely to implement this. Maybe a good solution for you is to write a small script that runs mypy and parses its output.
