### ISSUE TITLE
Type compatibility issues with Generic classes with class-local TypeVars

### ISSUE THREAD

**Issue by ktbarrett** [python/mypy#15003]
**Bug Report**

When creating a generic class which uses a class-local `TypeVar`, which is bound using the class's `TypeVar`, in the parameter list of a method, any call or overload of the method results in a type compatibility error.

**To Reproduce**
https://mypy-play.net/?mypy=latest&python=3.11&gist=abf11462f5fbdb4f34d668b832eaf521

**Expected Behavior**

I expect that `Broadcaster[int]` is compatible with `Connectable[int]` and that `Input[int]` can be given as argument to `Connectable[int].connect`.

If I make `Broadcaster` inherit from `Input[T]` and `Connectable[T]`, I get the same issue but it complains about the method being incompatible with the supertype.

If the types are turned into `Generic` ABCs instead of `Protocol`s, I get the same errors.

**Actual Behavior**

```
main.py:40: error: Incompatible types in assignment (expression has type "Broadcaster[int]", variable has type "Connectable[int]")  [assignment]
main.py:40: note: Following member(s) of "Broadcaster[int]" have conflicts:
main.py:40: note:     Expected:
main.py:40: note:         def [V <: Input[T_co]] connect(self, V, /) -> V
main.py:40: note:     Got:
main.py:40: note:         def [V <: Input[T]] connect(self, V, /) -> V
main.py:41: error: Value of type variable "V" of "connect" of "Broadcaster" cannot be "A"  [type-var]
main.py:41: note: Revealed type is "__main__.A"
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.1.1
- Python version used: 3.11

See link for other details.

**Comment by erictraut** [comment]
The `bound` for a `TypeVar` cannot be a generic type, as it is in your code sample. It must be a concrete type. PEP 484 is quite specific about this. 

> A type variable may specify an upper bound using bound=<type> (note: <type> itself cannot be parameterized by type variables).

Mypy should probably emit a better error message in this case.

If you replace `Input[T_co]` and `Input[T]` with `Input[Any]`, the errors go away.

**Comment by ktbarrett** [comment]
> If you replace `Input[T_co]` and `Input[T]` with `Input[Any]`, the errors go away.

However `Input[Any]` is more accepting (unsafe) than it should be.

> A type variable may specify an upper bound using bound= (note: itself cannot be parameterized by type variables).

This seems to be an over-specification in the PEP. There are also no examples of putting `TypeVar`s in class bodies in PEP 484, which tells me that the PEP never attempted to handle this case. I guess this means there would need to be a further PEP to handle this particular case.

**Comment by erictraut** [comment]
I think mypy is working correctly here. Recommend closing the issue.

If you want to propose extensions to the type system (such as supporting higher-kinded types), you can do so in the [python/typing discussion forum](https://github.com/python/typing/discussions).
