### ISSUE TITLE
`Dict[Key, Value]` cannot be assigned to parameter `Dict[Key, Optional[Value]]`

### ISSUE THREAD

**Issue by DrewMcArthur** [python/mypy#15013]
**Bug Report**

I have a function with an argument of type `Dict[Key, Optional[Value]]` (in my case, Key is a `str,enum`, and Value is a `DataFrame`, not sure if that affects the bug).  I try to pass in a variable of type `Dict[Key, Value]` (value is not Optional, is always present in this case), by mypy cannot assign the variable to the argument's type.  See error message in **Actual Behavior**

**To Reproduce**

```python
def f(x: Dict[str, Optional[str]]):
    for k, v in x.items():
        print(k)
        if v is not None:
            print(v)

y: Dict[str, str] = {"hello": "world"}
f(y)
```

**Actual Behavior**
```
(variable) tables: Dict[str, str]
Argument of type "Dict[str, str]" cannot be assigned to parameter "tables" of type "Dict[str, str| None]" in function "f"
  "Dict[str, str]" is incompatible with "Dict[str, str| None]"
    TypeVar "_VT@dict" is invariant
      Type "str" cannot be assigned to type "str | None"
        Type cannot be assigned to type "None"
```

note, my original error has a `str,enum` custom class for the key, and a `DataFrame` as the value.  unsure if this affects the bug, but i'd assume not. 

**Your Environment**

- Mypy version used: v0.2.3
- Mypy command-line flags:  just using the vs code extension
- Python version used: 3.9

**Comment by JelleZijlstra** [comment]
https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance

**Comment by DrewMcArthur** [comment]
ah cool.  thank you @JelleZijlstra :)
