### ISSUE TITLE
There's a difference between TypeVar('T', bound=Callable) and TypeVar('T', bound=Callable[..., Any])

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1501]
@rwbarton Any idea? I found this in our internal code base, haven't come up with a small repro yet. Plain `Callable` is supposed to mean the same as `Callable[..., Any]` but in this case it's apparently not the case. I had some code that gave a long list of errors when I used the shorter form. OTOH I had some other code where it worked...

**Comment by rwbarton** [comment]
I can reproduce this by making that change to test `testBoundOnDecorator`. Will investigate.
