### ISSUE TITLE
dict considered incompatible with dict type with supertype for key

### ISSUE THREAD

**Issue by jwodder** [python/mypy#15030]
**Bug Report**

Consider the following code:

```python
from pathlib import Path

def mkfiles(spec: dict[str | Path, str]) -> None:
    ...

spec: dict[str, str] = {
    "foo.txt": "Fooey",
    "bar.txt": "Bar-y",
}

mkfiles(spec)
```

Running mypy on this code with the default options produces the following error:

```
superkey01.py:11: error: Argument 1 to "mkfiles" has incompatible type "Dict[str, str]"; expected "Dict[Union[str, Path], str]"  [arg-type]
```

Changing `dict` to `collections.abc.Mapping` does not get rid of the error.

**Expected Behavior**

mypy should have accepted the code, as the key type `str | Path` is more general than `str`.

**Your Environment**

- Mypy version used: 1.2.0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.11.3 on macOS 11.7.2

**Comment by JelleZijlstra** [comment]
https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance
