### ISSUE TITLE
(🎁) Deprecate python 3.7 support

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#15056]
Python 3.7 is an old reference (deprecated), maybe mypy should drop support for it 😳

[PEP 537 -- Python 3.7 Release Schedule](https://peps.python.org/pep-0537/)

It's actually deprecated as of 2023-06, but close enough.

**Comment by JelleZijlstra** [comment]
3.7 has now reached EOL. Time to remove support?

**Comment by AlexWaygood** [comment]
As @ikonst has noted elsewhere, the tests on 3.7 are by far the slowest in CI, so it would definitely be a nice quality of life improvement to be able to ditch them :)

**Comment by JelleZijlstra** [comment]
Isn't some of that because we run a subset of tests on 3.7 only as it's the earliest supported version? Not sure that would be any better if we run them on 3.8 instead.

**Comment by AlexWaygood** [comment]
> Isn't some of that because we run a subset of tests on 3.7 only as it's the earliest supported version?

I wasn't aware that we did that!

**Comment by JelleZijlstra** [comment]
If we *don't* drop support for 3.7 in the next release, we need to bump our typing-extensions requirements: https://github.com/python/mypy/pull/15543#discussion_r1245928214

**Comment by ikonst** [comment]
I think the issue I filed was about windows running tests nearly 2x slower. Don't think 3.7 had to do with it.

**Comment by hauntsaninja** [comment]
Let's pull the trigger. 3.7 is getting annoying. It's fallen to fewer than 10% of mypy users and I bet the fraction is even smaller for latest mypy version.
