### ISSUE TITLE
Exit zero option

### ISSUE THREAD

**Issue by ElBe-Plaq** [python/mypy#15051]
**Feature**

This feature request and the following PR would add a option to both the CLI and the configuration files for exiting with zero. This could be useful for debugging or testing.

**Pitch**

The implementation would add the option to `options.py` and something like `code = 0 if options.exit_zero else code` to the main file before exiting.

**Comment by JelleZijlstra** [comment]
Why would this be useful?

**Comment by hauntsaninja** [comment]
Why can't you use `mypy xyz || true`?

**Comment by JelleZijlstra** [comment]
Then you should configure your CI to not fail if mypy fails.

**Comment by ElBe-Plaq** [comment]
Is there a problem with my changes?

**Comment by JelleZijlstra** [comment]
Every change we make to mypy increases the complexity of the project and future maintenance load, and risks introducing new bugs. If a user issue can be solved simply without changes to mypy itself, we strongly prefer that.

**Comment by ElBe-Plaq** [comment]
Okay, thanks. I will delete the fork and close both the PR and the issue.
