### ISSUE TITLE
Mypy and mypyc sprint at PyCon 2023

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#15067]
There will be a mypy and mypyc sprint at PyCon 2023 in Salt Lake City on Monday and Tuesday (Apr 24 and 25). If you are interested in helping with running the sprint, you can leave a comment here (or find me at PyCon). You don't need to be a very experienced contributor to help. 

Here are some things where help would be useful:
* Help everybody get their development environment set up.
* Help with the basics of mypy development, such as writing tests and finding documentation.
* Help keep track of which issues are being worked on to make it easier to find issues to work on and to avoid duplicate work.
* Set up a discussion room for the sprint.
* Create or label additional beginner issues, and add more implementation details to beginner issues.

**Comment by hauntsaninja** [comment]
During PyCon, we merged 26 PRs from 16 different contributors and there are a couple PRs still open.

Thanks to everyone who made mypy better! :-)
