### ISSUE TITLE
type not inferred in application of higher-order function to a generic function

### ISSUE THREAD

**Issue by rwbarton** [python/mypy#1507]
```
from typing import TypeVar, Callable
S = TypeVar('S')
def apply(f: Callable[[int], S]) -> S: pass
def g(x: S) -> S: pass
y = apply(g) # E: Argument 1 to "apply" has incompatible type Callable[[S], S]; expected Callable[[int], S]
reveal_type(y) # E: Revealed type is 'S`-1'
```

The call to `apply` should type check, with both types `S` and the type of `y` being `int`.

I encountered this sort of situation in `mypy/codec/pytokenize.py` in the lines

```
tokenprog, pseudoprog, single3prog, double3prog = map(
    re.compile, (Token, PseudoToken, Single3, Double3))
```
#1471 was an attempt to fix this, but since it fixes this case but not #1506, I'm filing these as two related but distinct issues.

**Comment by davidhalter** [comment]
This is working now.

See https://mypy-play.net/?mypy=latest&python=3.12&gist=2265ae341b2994f28577afc8788c0879

**Comment by hauntsaninja** [comment]
Thanks!
