### ISSUE TITLE
Overloaded function implementation does not accept all possible arguments

### ISSUE THREAD

**Issue by aimtsou** [python/mypy#15072]
**Bug Report**
I am trying to remove typing.io namespace from pyspark [here](https://github.com/aimtsou/spark/blob/typing-patch/python/pyspark/broadcast.py):

Original code: 
```python
from typing.io import BinaryIO  # type: ignore[import]
```
Modified putting BinaryIO inside the typing declaration
```python
from typing import (
    overload,
    Any,
    BinaryIO,
    Callable,
    Dict,
    Generic,
    IO,
    Iterator,
    Optional,
    Tuple,
    TypeVar,
    TYPE_CHECKING,
    Union,
)
```

After running the tests I get 
`python/pyspark/broadcast.py:100: error: Overloaded function implementation does not accept all possible arguments of signature 3  [misc]`

**To Reproduce**
Just change the code and let the pyspark tests already configured to run

**Your Environment**

- Mypy version used: 0.92.0
- Python version used: 3.9

**Comment by JelleZijlstra** [comment]
That's a big block of code. Could you provide a smaller example that reproduces the error you are seeing?

Note that `from typing.io import BinaryIO` just gets resolved to `Any`, so your previous code wasn't type checked.

**Comment by JelleZijlstra** [comment]
Also, mypy 0.920 is quite old. We're on 1.2.0 now.

**Comment by aimtsou** [comment]
> Note that `from typing.io import BinaryIO` just gets resolved to `Any`, so your previous code wasn't type checked.

How is that possible? Why it gets resolved to Any?
Well upgrading spark's infra is going to take a while I can test on my fork the latest version though.

**Comment by aimtsou** [comment]
Hi @JelleZijlstra,

I checked with mypy 1.2.0 and it still throws the same error, so indeed you are the way typing.io was imported was not checked. I was wondering if you can point me to any documentation where I can read and understand.
At the moment I am trying to understand the spark code so I can provide a minimal example.

**Comment by JelleZijlstra** [comment]
`typing.io` was never supported by type checkers, which is why we deprecated it. This is mentioned in https://docs.python.org/3.10/library/typing.html#typing.IO

**Comment by aimtsou** [comment]
Now I understand 

```python
    @overload  # On worker with decryption server
    def __init__(self: "Broadcast[Any]", *, sock_file: str):
        ...

    def __init__(
        self,
        sc: Optional["SparkContext"] = None,
        value: Optional[T] = None,
        pickle_registry: Optional["BroadcastPickleRegistry"] = None,
        path: Optional[str] = None,
        sock_file: Optional[BinaryIO] = None,
    ):  
```

I assume that since my error points in signature 3, it is the third function which causes the problem. My understanding is I have to change the definition of the overloaded init to something more concrete. 

My question is why signature which instead of sock_file uses until path in overloading does not have any problems?

Apologies if the questions are amateur like, i am getting used to mypy.

**Comment by erictraut** [comment]
@aimtsou, did you find an answer to your question? Is there anything actionable remaining in this issue, or can it be closed?

**Comment by aimtsou** [comment]
Good morning @erictraut,

I have not found an answer to my question. Since this is a piece of code inside spark, I am not sure how I can write a similar example. I am going to take another look at it the next few days and keep you posted.

**Comment by hauntsaninja** [comment]
I don't think there's anything actionable. If you want the old behaviour back, you can do `BinaryIO = Any` (which is obviously terrible, but is what is currently happening)
