### ISSUE TITLE
(🐞) Silent crash regression in 1.2 with complex `Concatenate` return value

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#15073]
**Crash Report**

Absolutely nothing.

**Traceback**

N/A

**To Reproduce**

```py
from typing import TypeVar, Callable, Concatenate, ParamSpec

R = TypeVar("R")
P = ParamSpec("P")

def f(
) -> Callable[[Callable[Concatenate[Callable[P, R], P], R]], Callable[P, R]]:
    def r(fn: Callable[Concatenate[Callable[P, R], P], R]) -> Callable[P, R]:
        pass
    return r
```

[playground](https://mypy-play.net/?mypy=latest&python=3.11&gist=48843af89909b2af64595b8f5c1477dc)

**Your Environment**

- Mypy version used: 1.2.0
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.11.3
- Operating system and version: Windows version 10

# Why?

This is because of an infinite recursion in `mypy.expandtype.ExpandTypeVisitor.visit_callable_type`.

**Comment by ilevkivskyi** [comment]
This crash is caused by https://github.com/python/mypy/pull/14677. @A5rocks please take a look at this.
