### ISSUE TITLE
Release 1.3 planning

### ISSUE THREAD

**Issue by wesleywright** [python/mypy#15075]
I'm aiming to make the 1.3 release by the end of April.

Please post here any issues you'd like to see fixed in the release, or PRs you'd like to have merged.

**Comment by wesleywright** [comment]
Created a release branch for this release: https://github.com/python/mypy/tree/release-1.3

**Comment by wesleywright** [comment]
Looks like https://github.com/python/typeshed/issues/10060 will be a blocker

**Comment by Viicos** [comment]
I would be grateful if https://github.com/python/mypy/pull/14471 could get fixed, I've spent some time trying to see what was failing but my knowledge of the mypy internals is too limited. It may be straightforward, as it is kind of reverting https://github.com/python/mypy/pull/7656 and this one doesn't have a large diff. More context here: https://github.com/python/mypy/issues/8330#issuecomment-1380684785

**Comment by cdce8p** [comment]
Would be awesome if the performance fix for union subtyping could be included
- #15104

**Comment by ethanhs** [comment]
I'd love to get a review/merge on https://github.com/python/mypy/pull/14888 so that https://mypy.app can start using official mypy wheels.

**Comment by JelleZijlstra** [comment]
Merged #14888, would be good to cherry-pick.

**Comment by wesleywright** [comment]
Cherry-picked #14888 as well as https://github.com/python/typeshed/pull/10061 to fix a known Typeshed bug

**Comment by wesleywright** [comment]
@cdce8p cherry-picked #15104.

@ikonst unfortunately it seems that #15050 has a conflict when I try to cherry-pick it; seems like that is related to https://github.com/python/mypy/commit/768ba66af4c90c14c19275896067a4e4fe6f2f46, which is pretty big, so I'm hesitant to cherry-pick that as well.

**Comment by wesleywright** [comment]
@JukkaL identified at least these two issues as potential blockers:

- https://github.com/python/mypy/pull/15043
- https://github.com/python/mypy/pull/15049
-

**Comment by wesleywright** [comment]
Cherry-picked https://github.com/python/mypy/pull/15179 to fix the above-mentioned issues.

**Comment by wesleywright** [comment]
The release is out now (the news page on the website is lagging behind a bit at present): https://mypy-lang.blogspot.com/2023/05/mypy-13-released.html

**Comment by cdce8p** [comment]
Thanks for the release!

If there is interest, I would like to start getting support for [PEP 696](https://peps.python.org/pep-0696/) (TypeVar defaults) merged. Maybe even in time for the `1.4` release. Still looking for reviews though: #14872

**Comment by A5rocks** [comment]
https://mypy.readthedocs.io/en says 1.2?

**Comment by CoolCat467** [comment]
Since version is now `1.4.1` as of writing, this should probably be closed
