### ISSUE TITLE
Over-restrictive requirements for iterable argument to dict

### ISSUE THREAD

**Issue by ods** [python/mypy#15074]
**Bug Report**

When constructing dictionary from iterable of pairs mypy incorrectly requires the items to be tuples, while Python accepts any interable of iterables.

**To Reproduce**

The following example is pretty valid, while mypy produces error for it:
```python
dict([[1, 2], [2, 3]])
# error: Argument 1 to "dict" has incompatible type "List[List[int]]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
```
As well as the following:
```python
dict(iter([iter([1, 2]), iter([2, 3])]))
# error: Argument 1 to "dict" has incompatible type "Iterator[Iterator[int]]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
```

**Expected Behavior**

mypy should accept `Iterable[Iterable[...]]` as argument to `dict`. 

**Your Environment**

- Mypy version used: 1.2.0
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10.9

**Comment by ikonst** [comment]
I suppose you'd want to disallow tuples of known length that's != 2, but we don't really have a syntax for that. In any case, we're merely using the typeshed annotations, so best to create an issue at https://github.com/python/typeshed.

**Comment by ods** [comment]
Thank you for pointing out to typesheds. Actually, such bug even already has been reported (https://github.com/python/typeshed/issues/10013), but it's closed as "not planned". Closing it here anyway, as it appears not a mypy issue.
