### ISSUE TITLE
Easy way to run lint, black etc. (all fast checks)

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#15076]
Add an easy way to run `runtests.py self lint format-black format-isort`. Often one of these fails in CI, so running them locally is helpful, but currently it's too annoying. It could be `runtests.py <something>`.

**Comment by JelleZijlstra** [comment]
I think this is pretty easy to do with pre-commit, something like `pre-commit run -a black`. Perhaps we could provide an alias for a pre-commit invocation like that. (Note that this does *not* require actually using pre-commit as a pre-commit hook.)

**Comment by hauntsaninja** [comment]
@JukkaL The best flow for contributors is where they don't need to think about black and isort at all. If you setup #13281 it'll just automatically push fixup commits; we use this in typeshed and it works great. Contributors don't have to think about pre-commit or any other tool

**Comment by AlexWaygood** [comment]
I agree with @hauntsaninja! pre-commit.ci has worked seamlessly at typeshed and really improved the contributing experience. It's very easy to enable it for a repo; just a matter of ticking a box in the repo settings to give it the necessary permissions.

**Comment by JukkaL** [comment]
Yes, running black and isort automatically for PRs sounds like a good idea. That would address much of the friction.

I think that this issue is still worthwhile, particularly for self check and lint, which often require manual action, but running black and isort is also pretty quick and by running them locally there won't be need to pull fixup commits .
