### ISSUE TITLE
TypeVar and Dictionaries

### ISSUE THREAD

**Issue by VasLem** [python/mypy#15081]
**Bug Report**

I am not sure whether this a bug. Based on my small ablation [research](https://stackoverflow.com/questions/76054162/how-to-use-typevar-with-dictionaries), I am having issues understanding what the right way is to make a dictionary values types be dependent on the keys types. I refer you to the following minimum example:

```python
from typing import Dict, TypeVar
from typing import Generic
T = TypeVar("T")
class Test(Generic[T]):
    A: Dict[T, T] = {bool: bool}
```
The only way I have made it work is by inheriting the class, just like a protocol, but this does not seem very practical:
```python

class Test(Generic[T]):
    A: Dict[T, T]

class TestInheritor(Test[str]):
    A = {"x": "x"}
```

**Expected Behavior**

No complaints would be expected.

**Actual Behavior**
Error:
`Dict entry 0 has incompatible type "Type[bool]": "Type[bool]"; expected "T": "T"`

**Your Environment**

- Mypy version used: 1.2.0
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8

**Comment by JukkaL** [comment]
This is working as expected. You need to use a subclass to use a more specific type such as `str` for a value with a type variable type in the body of a class.
