### ISSUE TITLE
Support hints for dynamically set attributes

### ISSUE THREAD

**Issue by BEllis** [python/mypy#15085]
**Feature**

Support hints for dynamically set attributes in the form of a set of attributes that are only processed by mypy.

**Pitch**

This would allow for mypy to continue to type check in cases where there are dynamic types that the programmer knows will be added at runtime.

It *should* be relatively simple to implement as it would just require changing mypy to process the lines in comments between lines with the comments `mypy-dynamics-start` and `mypy-dynamics-end` as if they were part of the class declaration. Code on the commented lines will have the leading space removed and be indented to be the same depth as the mypy-dynamics-start comment.

e.g.
```python
class Example:
    # mypy-dynamics-start:
    # _name: str
    #
    # @property
    # def name(self) -> None:
    #    pass
    # mypy-dynamics-end:

    def __init__(self) -> None:
        setattr(self, '_name', 'value')
        setattr(self, 'name', property(lambda self: self._name))
    
    def a_function(self) -> bool:
        return self._name == 'value'

example = Example()
print(example.name)
```

In the above example, mypy would currently give errors for,

`return self._name == 'value'` gives `error: "Example" has no attribute "_name"  [attr-defined]`
`print(example.name)` gives `error: "Example" has no attribute "name"  [attr-defined]`

However, with this feature implemented it would give no errors and be able to provide type checking on the dynamic attributes as if they were static attributes.

**Comment by erictraut** [comment]
You can already do this with a `TYPE_CHECKING` conditional. 

```python
class Example:
    if TYPE_CHECKING:
        _name: str

        @property
        def name(self) -> None:
            pass
```

However, you need to be careful when using `TYPE_CHECKING` because it will cause mypy to analyze code that is different than the code at runtime. This can mask errors. It's therefore recommended not to use this type of dynamic behavior if you're interested in getting the full benefits of static type checking.

**Comment by BEllis** [comment]
This unblocked me, but I think still not as nice a solution as I believe I have to copy my definitions in the case of wanting to tweak decorators. i.e. compare,

```python
class MyClass(MyBaseClass):
    if TYPE_CHECKING:

        @classmethod
        def get_value_type(cls) -> Type:
            raise NotImplementedError()

    else:

        @classmethod
        @abstractmethod
        def get_value_type(cls) -> Type:
            raise NotImplementedError()
```
to

```python
class MyClass(MyBaseClass):
    @classmethod
    # not-mypy-dynamics-start:
    # @abstractmethod
    # not-mypy-dynamics-end
    def get_value_type(cls) -> Type:
        raise NotImplementedError()
```

I've had to introduce a `not-` form of the feature for this to work in this case.

**Comment by hauntsaninja** [comment]
Like Eric says, `if TYPE_CHECKING` is already a good way to lie to mypy. It's natural and mirrors Python's scoping. You can conditionally alias / define your decorators if you want to reduce duplication.
