### ISSUE TITLE
Want new error code optional-attr

### ISSUE THREAD

**Issue by wrohdewald** [python/mypy#15093]
I am converting my code to use mypy. I often know better than mypy that something Optional[T] cannot be None. From many other open issues I can see that this problem will not go away soon. 

I could either rewrite my code (sometimes ugly workarounds) or use 

``type:ignore[union-attr]``

But that might hide other problems, so I would much prefer to narrow  this to

``type:ignore[optional-attr]``

**Comment by ikonst** [comment]
I think [strict_optional](https://mypy.readthedocs.io/en/stable/config_file.html#confval-strict_optional) `=False` might already do what you want.

**Comment by wrohdewald** [comment]
I would not know how to apply that to just a few source lines, it seems to be a per-module-option

**Comment by ikonst** [comment]
Oh, I see. I thought you're questioning the usefulness of optional checking for your project in general.

If you're confident `None` is not possible in a particular case, would an `assert x is not None` be an easy way to cast off the None?

**Comment by hauntsaninja** [comment]
+1 to ikonst's suggestion of using `assert x is not None` to get rid of this class of type error. `Optional[T]` really is just the same as `Union[T, None]`, so I'm not sure that I'm supportive of artificially creating a difference here.
