### ISSUE TITLE
Handle changing a generic attrs class with attrs.evolve

### ISSUE THREAD

**Issue by mwchase** [python/mypy#15108]
**Feature**

Given a class defined like:
```python
@attrs.frozen
class Example(Generic[T]):
    value: T
    other_data: str
```
I would like to be able to transform it like:
```python
example_int: Example[int]
example_int = Example(5, "example initially int")
example_str = attr.evolve(example_int, value=str(example_int.value))
reveal_type(example_str) # Example[str]
```

**Pitch**

I'm working on a project that involves a variety of generic wrapper types, and there are various instances in which I'd like to take the metadata attached to a wrapper value around one type, and transfer it to a wrapper value around another type. As it stands, this "changes the type" from Mypy's perspective, and means that I need to construct a value from scratch. The problem with *that* is, there's no guard rail against forgetting to pass an attribute value that has a default in the constructor.

So, if I start with:
```python
@attrs.frozen
class SlightlyMoreComplexExample(Generic[T]):
    value: T
    info: str = ""
```
Then I have to transform it like:
```python
def update_example(ex_int: SlightlyMoreComplexExample[int]) -> SlightlyMoreComplexExample[str]:
    return SlightlyMoreComplexExample(str(ex_int.value), ex_int.info)
```
But if I add another field, like:
```python
@attrs.frozen
class SlightlyMoreComplexExample(Generic[T]):
    value: T
    info: str = ""
    children: tuple[SlightlyMoreComplexExample[T], ...] = ()
```
Then now the original update function will silently discard data.
I'd like to be able to write it like:
```python
def update_example(ex_int: SlightlyMoreComplexExample[int]) -> SlightlyMoreComplexExample[str]:
    return attrs.evolve(ex_int, value=str(ex_int.value))
```
And have the result of updating it be that Mypy raises some kind of argument error because the type of `children` no longer matches.

**Comment by tmke8** [comment]
Have you tried it with mypy master? This recent PR might have fixed this: #15050

**Comment by mwchase** [comment]
Yep. Just checked against master with the full version of the code from the pitch, and here's how it shook out:

```python
from __future__ import annotations

from typing import Generic, TypeVar

import attrs

T = TypeVar("T")


@attrs.frozen
class SlightlyMoreComplexExample(Generic[T]):
    value: T
    info: str = ""
    children: tuple[SlightlyMoreComplexExample[T], ...] = ()


def update_example(
    ex_int: SlightlyMoreComplexExample[int],
) -> SlightlyMoreComplexExample[str]:
    return attrs.evolve(ex_int, value=str(ex_int.value))
```
Result of running master against that file:
```
complex.py:20: error: Incompatible return value type (got "SlightlyMoreComplexExample[int]", expected "SlightlyMoreComplexExample[str]")  [return-value]
complex.py:20: error: Argument "value" to "evolve" of "SlightlyMoreComplexExample[int]" has incompatible type "str"; expected "int"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```
What I want is for the return value error not to show up, and for, in this case, there to be an `arg-type` error for `children`, which is, granted, a little magical when I put it like that.

**Comment by JelleZijlstra** [comment]
The code in this example looks unsafe to me, since `children` is not being replaced, so mypy is correct to reject it.

**Comment by mwchase** [comment]
> The code in this example looks unsafe to me, since `children` is not being replaced, so mypy is correct to reject it.

I was trying to do too many things with that example. Here it is without the deliberate unsafety:

```python
from __future__ import annotations

from typing import Generic, TypeVar

import attrs

T = TypeVar("T")


@attrs.frozen
class SlightlyMoreComplexExample(Generic[T]):
    value: T
    info: str = ""


def update_example(
    ex_int: SlightlyMoreComplexExample[int],
) -> SlightlyMoreComplexExample[str]:
    return attrs.evolve(ex_int, value=str(ex_int.value))
```
And run:
```
complex.py:19: error: Incompatible return value type (got "SlightlyMoreComplexExample[int]", expected "SlightlyMoreComplexExample[str]")  [return-value]
complex.py:19: error: Argument "value" to "evolve" of "SlightlyMoreComplexExample[int]" has incompatible type "str"; expected "int"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```
Basically, I want it to treat *this* situation as valid, and I suppose that would be accomplished by redoing unification.

**Comment by ikonst** [comment]
The unsafe bit flags an issue, though: if we do this, then for:
```
@attrs.define
class MyClass(Generic[T]):
    value: T
    value2: T
    info: str
```
you'd have to return ... a signature with 2 overloads?
```python
@overload
def evolve(inst: MyClass[A], *, value: A = ..., info: str = ...) -> MyClass[A]: ...
@overload
def evolve(inst: MyClass[T], *, value: T, value2: T, info: str = ...) -> MyClass[T]: ...
```
Note how the second overload needs `value` and `value2` as `NAMED` rather than `NAMED_OPT`.

**Comment by mwchase** [comment]
The second one should still have `MyClass[A]`, shouldn't it?
Regardless, this does exacerbate some other issues, like, what if none of the attributes contain one of the parameters?

I'm currently leaning towards finding other ways to deal with my initial issue. Probably a plugin for either Mypy or Pylint, to emit some warnings. I'd be interested if anyone works out a clean way to add this feature, but it's not looking to me like a case of "Just do this and you're done".

**Comment by ikonst** [comment]
> The second one should still have MyClass[A], shouldn't it?

As the first argument's type? Sure, it'll be just as good. Ultimately it should just be something that checks, because you already know the first argument's type (or types, in case of a union).

> what if none of the attributes contain one of the parameters?

Can you give an example?

**Comment by mwchase** [comment]
In my project, I've got a class that I wouldn't want to use this with, or call `attrs.evolve` on it at all, but it does show off what I was talking about:
```python
from __future__ import annotations

import typing

import attr

T = typing.TypeVar("T")


@attr.dataclass(frozen=True, eq=False)
class Label(typing.Generic[T]):
    """Marker class for storing and retrieving typed values."""

    purpose: str
```
This class is mainly used as keys to a mapping type that requires a plugin to typecheck properly, but this class itself has nothing special going on.

**Comment by ikonst** [comment]
Yeah, I suppose then an instance of `Label[A]` could not be made an instance of `Label[B]` through a call to `evolve`, just like there's nothing but a `cast` that would make the last line pass:
```
class A:
    pass

class B:
    pass

class NothingSpecial(Generic[T]):
    pass

a = NothingSpecial[A]()
b: NothingSpecial[B] = a
```

**Comment by mwchase** [comment]
I've managed to put together a horrible prototype plugin that can get me around this issue by making Mypy stricter, but I think that if I'm going the plugin route anyway, I'd rather try to support this more nicely.

I see a few problems with "make evolve more permissive", so I'm going to look into an idea that hopefully addresses the problems with this request, and see what I think of it in practice. Basically, "what if we had another function that was like a combination of evolve and cast, so it takes everything evolve does, but also a type argument?". I think there's potential there, and if it doesn't work, I can fall back on the plugin I already wrote.

Not sure if there's any point in keeping this open.

**Comment by mwchase** [comment]
Having experimented with writing a plugin that is easier to get right than what I'm proposing, I cannot in good conscience ask anyone to do this. The edge and corner cases are *horrendous*, at least to my level of experience with writing plugins.

Major issues I'm trying to work out the right way around:
- Non-final classes can break expectations so badly, I think making them an error in the context of the plugin's checker is the only sensible option
- The desired semantics of unions are much subtler than in the existing code, to the point where I'm tempted to make them fail in the plugin with, like, "PRs welcome"

I'm feeling a little burned out on this plugin code, but if helping with all of this sounds interesting, maybe I'll be around on gitter in a few weeks.
