### ISSUE TITLE
Fix pyinfo.py if PYTHONSAFEPATH is set

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#15110]
Python 3.11 adds a PYTHONSAFEPATH environment variable / `-P` flag that prevents script directory from ending up on PYTHONPATH: https://docs.python.org/3/using/cmdline.html#cmdoption-P

The logic in pyinfo.py will be broken if this environment variable is set.

The best fix is probably to set the environment variable when calling pyinfo in a subprocess on Python 3.11 and newer. This happens in modulefinder.py. We can then only do the sys.path hackery in pyinfo.py on older Python versions

**Comment by fgrabowski** [comment]
Could you please assign this to me? I think I know how to fix it with the potential fix you described and I am new to open source.

**Comment by JelleZijlstra** [comment]
We don't usually do assignments, but feel free to submit a PR!
