### ISSUE TITLE
--disallow-untyped-defs forces return type annotation on __init__ with no arguments

### ISSUE THREAD

**Issue by ziima** [python/mypy#15113]
**Bug Report**

I discovered a bug when using mypy with `--disallow-untyped-defs`. In case `__init__` method takes no arguments, mypy enforces the return type annotation even though it doesn't enforce it in case `__init__` has any arguments.

**To Reproduce**

```python
# mypy --disallow-untyped-defs
class Foo:
    def __init__(self):  # error: Function is missing a return type annotation  [no-untyped-def]
        pass


class Bar:
    def __init__(self, foo: int):  # no error
        pass
```

https://mypy-play.net/?mypy=latest&python=3.11&flags=disallow-untyped-defs&gist=ea8db3c54db1d455855db2848d15871e

**Expected Behavior**

Mypy should not enforce the explicit return type on `__init__` regardless of how many arguments it has.

**Actual Behavior**

```
main.py:2: error: Function is missing a return type annotation  [no-untyped-def]
main.py:2: note: Use "-> None" if function does not return a value
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.2.0
- Mypy command-line flags: `--disallow-untyped-defs`
- Mypy configuration options from `mypy.ini` (and other config files): --
- Python version used: 3.11

**Comment by JelleZijlstra** [comment]
This is intended behavior. Functions with no annotations aren't type checked, so argument-less `__init__` methods need the return type annotations to indicate they should be checked.
