### ISSUE TITLE
Infer Union for ternary expressions

### ISSUE THREAD

**Issue by smallnamespace** [python/mypy#1511]
Ternary expressions currently infer to type `object`, when they should at least infer a `Union` of both branch's types (if not more, in the case where the predicate is known to be constant).

```python
from typing import Union

u = 0 if True else ''  # type: Union[int, str]
```

currently results in

``` error: Incompatible types in assignment (expression has type "object", variable has type "Union[int, str]")```

**Comment by gvanrossum** [comment]
Indeed! This is a duplicate of #622.

**Comment by smallnamespace** [comment]
Thanks! I'd searched for existing issues, but wasn't aware that Python calls them conditional expressions.
