### ISSUE TITLE
Using intermediate variable breaks type-checking for Union variable

### ISSUE THREAD

**Issue by whalebot-helmsman** [python/mypy#15176]
**Bug Report**

Using intermediate variable breaks type-checking for Union variable

**To Reproduce**

```python
from pathlib import Path
from typing import Union, Dict


def get_f() -> Union[Path, Dict]:
    return Path('foo')


def read_f(p) -> Dict:
    return {}


def foo() -> None:

    f:Union[Path, Dict] = get_f()
    m = f
    if isinstance(m, Path):
       f = read_f(m)
    f['a'] = 'b'
```

**Expected Behavior**

No error

**Actual Behavior**

```
/home/user/tmp/t.py:19: error: Unsupported target for indexed assignment ("Union[Path, Dict[Any, Any]]")  [index]
```

**Your Environment**

- Mypy version used: 0.991 (compiled: yes)
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10

**Comment by hauntsaninja** [comment]
Yeah, thanks for the issue! mypy doesn't track the relationship between variables like this (and will not any time soon)

**Comment by lopuhin** [comment]
Related example where this becomes inconvenient:

```
from pathlib import Path
from typing import Union, Dict

def foo() -> None:
    a: Union[Path, Dict] = {}
    is_path = isinstance(a, Path)
    if is_path:
        print(a.name)
```

Results in 

```
% mypy t.py
t.py:8: error: Item "Dict[Any, Any]" of "Union[Path, Dict[Any, Any]]" has no attribute "name"  [union-attr]
Found 1 error in 1 file (checked 1 source file)
```

while if `` isinstance(a, Path)`` is checked directly in the ``if`` condition, it type-checks.
