### ISSUE TITLE
mypy forgets that value is not None inside function definition

### ISSUE THREAD

**Issue by schuelermine** [python/mypy#15178]
**Bug Report**

mypy thinks that the type of a variable is `Optional[A]` when it has been previously determined to not be `None` when the variable is used in a function definition

**To Reproduce**

```python
from typing import TypeVar, ParamSpec, Concatenate
from collections.abc import Callable

A = TypeVar("A")
B = ParamSpec("B")
C = TypeVar("C")


def guard_none(a: A | None, f: Callable[Concatenate[A, B], C]) -> Callable[B, C]:
    if a is None:
        raise TypeError()
    else:
        
        def g(*args: B.args, **kwargs: B.kwargs) -> C:
            return f(a, *args, **kwargs)
        
        return g
```

**Expected Behavior**

I expect no error.

**Actual Behavior**

mypy produces this error:

```
main.py:15: error: Argument 1 has incompatible type "Optional[A]"; expected "A"  [arg-type]
```

**Your Environment**

mypy playground

- Mypy version used: 1.2.0
- Mypy command-line flags: `--strict`
- Python version used: 3.11

**Comment by schuelermine** [comment]
apparently this is a duplicate

**Comment by JelleZijlstra** [comment]
Of https://github.com/python/mypy/issues/2608
