### ISSUE TITLE
Segfault when manipulating a recursive union

### ISSUE THREAD

**Issue by jonathan-laurent** [python/mypy#15192]
**Bug Report**

Running mypy on the following program produces a segfault.

**To Reproduce**

```python
from typing import Literal, TypeAlias, Union


Expr: TypeAlias = Union[
    tuple[Literal["const"], int],
    tuple[Literal["neg"], "Expr"],
]


def eval(e: Expr) -> int:
    if e[0] == "const":
        return e[1]
    elif e[0] == "neg":
        return -eval(e[1])
```

**Expected Behavior**

Mypy returns successfully.

**Actual Behavior**

Mypy segfaults: 

```
fish: Job 1, 'mypy ...' terminated by signal SIGSEGV (Address boundary error)
```

The problem can be replicated in the [mypy playground](https://mypy-play.net/?mypy=latest&python=3.11&gist=51e21382324203063b7a6373c7cf1405).

**Your Environment**

- Mypy version used: 1.2.0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.11

**Comment by hauntsaninja** [comment]
Thanks for the report! I think #15128 will fix this
