### ISSUE TITLE
Inference doesn't catch simple type mismatch across functions

### ISSUE THREAD

**Issue by berdario** [python/mypy#1519]
def f() -> str:
        return ''
    
    def g(x: int) -> int:
        return x + 1
    
    def main():
        g(f())

Here I would expect a `error: Argument 1 to "g" has incompatible type "str"; expected "int"`
(which is what I get if I change the `main` function to a `if __name__ == '__main__'` block), but instead no error is reported

Sorry if this is already reported, but I couldn't find it

**Comment by gvanrossum** [comment]
This is as expected, because you have no annotations on `main()`. If you add `-> None` there the error will be reported.

**Comment by berdario** [comment]
The documentation probably needs to be updated, [it currently states](http://mypy.readthedocs.io/en/latest/type_inference_and_annotations.html#type-inference):

> Type inference is not used in dynamically typed functions (those without an explicit return type) — every local variable type defaults to Any, which is discussed later.

So, I'd expect mypy to treat

`def foo(): pass`

and

`def foo() -> Any: pass`

the same way, but this is obviously not the case, since with the former type errors won't be reported, but with the latter they will be.

Obviously the ideal thing would be to have every type explicitly stated, but in the process of getting there, this behavior is quite puzzling, since all the information needed for the type checker is already there (In fact I spent quite a while adding stubs, thinking that was the problem, since in the original code obviously it wasn't anything as simple as `int`/`str`... once I realized that it was working in a block on its own, after a little while I also realized that the type missing in the 3rd function would be the cause)

Moreover, there are even [some cases](https://github.com/Pylons/pyramid/issues/977) in which using type annotations is impossible/unsupported (I now sorted out that problem that was preventing me to adding the type signature by upgrading to Pyramid 1.6.1)

**Comment by gvanrossum** [comment]
You missed the bit at
http://mypy.readthedocs.io/en/latest/basics.html#mixing-dynamic-and-static-typing
:



On Wed, May 11, 2016 at 8:53 AM, berdario <notifications@github.com> wrote:

> The documentation probably needs to be updated, it currently states
> <http://mypy.readthedocs.io/en/latest/type_inference_and_annotations.html#type-inference>
> :
>
> Type inference is not used in dynamically typed functions (those without
> an explicit return type) — every local variable type defaults to Any, which
> is discussed later.
>
> So, I'd expect mypy to treat
>
> def foo(): pass
>
> and
>
> def foo() -> Any: pass
>
> the same way, but this is obviously not the case, since with the former
> type errors won't be reported, but with the latter they will be.
>
> Obviously the ideal thing would be to have every type explicitly stated,
> but in the process of getting there, this behavior is quite puzzling, since
> all the information needed for the type checker is already there (In fact I
> spent quite a while adding stubs, thinking that was the problem, since in
> the original code obviously it wasn't anything as simple as int/str...
> once I realized that it was working in a block on its own, after a little
> while I also realized that the type missing in the 3rd function would be
> the cause)
>
> Moreover, there are even some cases
> <https://github.com/Pylons/pyramid/issues/977> in which using type
> annotations is impossible/unsupported (I now sorted out that problem that
> was preventing me to adding the type signature by upgrading to Pyramid
> 1.6.1)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/python/mypy/issues/1519#issuecomment-218503375>
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by berdario** [comment]
I see, thanks for pointing that out
-- 
Sent from mobile. Please excuse my brevity.
