### ISSUE TITLE
property setters are not correctly type checked

### ISSUE THREAD

**Issue by tusharsadhwani** [python/mypy#15225]
**Bug Report**

Mypy seems to verify that when you call a setter with `foo.prop = value`, the value is the same type as the return-type of the getter.

But this is not the expected behaviour, since the setter can cast the value before storing it. Mypy should instead be checking against the `@prop.setter` function signature.

**To Reproduce**

```python
class Foo:
    _value = "test"

    @property
    def value(self) -> str:
        return self._value

    @value.setter
    def value(self, value: object) -> None:
        self._value = str(value)

foo = Foo()
foo.value = 10
```

**Expected Behavior**

No error to be shown.

**Actual Behavior**

```console
$ mypy asd.py
asd.py:13: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.3.0

**Comment by erictraut** [comment]
I think this is a duplicate of https://github.com/python/mypy/issues/3004.

**Comment by tusharsadhwani** [comment]
Oh wow, that is a long thread. Thanks for the link!
