### ISSUE TITLE
1.3.0: self test fails during Debian packaging: 

### ISSUE THREAD

**Issue by mr-c** [python/mypy#15224]
Hello,

While preparing an experimental MyPy 1.3.0 package for Debian, I got the following error from the selftest:

```
I: pybuild base:240: python3.11 -m mypy 	--config-file /tmp/autopkgtest.fL08IA/build.Slw/src/mypy_self_check.ini -p mypy
mypy/fastparse.py:846: error: "TypeIgnore" has no attribute "tag"  [attr-defined]
                parsed = parse_type_ignore_tag(ti.tag)
                                               ^~~~~~
```

Python version is 3.11.2-1+b1

**Comment by mr-c** [comment]
Looks like we need to upgrade our typeshed package to one that includes https://github.com/python/typeshed/commit/62a833c50f99e3bb32770cf74a119505e2e42961 a.k.a https://pypi.org/project/types-typed-ast/1.5.8.5/ or newer

**Comment by AlexWaygood** [comment]
> Looks like Debian needs to upgrade our typeshed package to one that includes [python/typeshed@62a833c](https://github.com/python/typeshed/commit/62a833c50f99e3bb32770cf74a119505e2e42961) a.k.a https://pypi.org/project/types-typed-ast/1.5.8.5/ or newer

Correct :)
