### ISSUE TITLE
Flag to generate junit.xml

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1523]
It would be nice if there was a flag that cause mypy to create a junit.xml file containing the errors (in addition to printing them to stdout). I wrote a wrapper Python script to do this for internal use, and it's proliferated like wildfire, so this would be very useful.

**Comment by anentropic** [comment]
seems like this exists now?
http://mypy.readthedocs.io/en/latest/command_line.html#the-mypy-command-line

**Comment by gvanrossum** [comment]
Fixed by ##2326.
