### ISSUE TITLE
Signature of function incompatible with protocol if function is marked optional

### ISSUE THREAD

**Issue by bersbersbers** [python/mypy#15243]
**Bug Report**

Mypy does not recognize that a function implements an *optional* `Callable` in a `Protocol`. `fun` works, `optional_fun` does not.

**To Reproduce**

```python
from typing import Callable, Protocol

class Proto(Protocol):
    fun: Callable[[], None]
    optional_fun: Callable[[], None] | None

class Class(Proto):
    def fun(self) -> None:
        pass

    def optional_fun(self) -> None:
        pass
```
https://mypy-play.net/?mypy=latest&python=3.11&gist=34b3c560691b847ae4c174dd729b0a52

**Expected Behavior**

No error

**Actual Behavior**

```
bug.py:13: error: Signature of "optional_fun" incompatible with supertype "Proto"  [override]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: mypy 1.3.0 (compiled: yes)
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.11.2

**Comment by hauntsaninja** [comment]
It's probably because it wants it to look like something settable. mypy's correct to complain here, but the error messaging could be improved, particularly with the explicit inheritance. See https://mypy.readthedocs.io/en/stable/protocols.html#invariance-of-protocol-attributes

General tip: instantiating protocols is how you get the most detailed errors in mypy.

```
from typing import Callable, Protocol

class Proto(Protocol):
    optional_fun: Callable[[], None] | None

class Class:
    def optional_fun(self) -> None:
        pass

def check(c: Class):
    p: Proto = c
```
Gives you the clearer error message:
```
main.py:11: error: Incompatible types in assignment (expression has type "Class", variable has type "Proto")  [assignment]
main.py:11: note: Following member(s) of "Class" have conflicts:
main.py:11: note:     optional_fun: expected "Optional[Callable[[], None]]", got "Callable[[], None]"
main.py:11: note: Protocol member Proto.optional_fun expected settable variable, got read-only attribute
Found 1 error in 1 file (checked 1 source file)
```

As mentioned in https://mypy.readthedocs.io/en/stable/protocols.html#invariance-of-protocol-attributes, the usual fix for this is using `property`:
```
from typing import Callable, Protocol

class Proto(Protocol):
    @property
    def optional_fun(self) -> Callable[[], None] | None: ...

class Class:
    def optional_fun(self) -> None:
        pass

def check(c: Class):
    p: Proto = c
```
This type checks.

However, the error message seems to totally suck if you explicitly inherit:
```
from typing import Callable, Protocol

class Proto(Protocol):
    optional_fun: Callable[[], None] | None

class Class(Proto):
    def optional_fun(self) -> None:
        pass

def check(c: Class):
    p: Proto = c
```
Gives you the not very helpful:
```
main.py:7: error: Signature of "optional_fun" incompatible with supertype "Proto"  [override]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by bersbersbers** [comment]
Thanks for the explanations!

> the error messaging could be improved, particularly with the explicit inheritance

I guess that's another case for #15240 then.

> As mentioned in https://mypy.readthedocs.io/en/stable/protocols.html#invariance-of-protocol-attributes, the usual fix for this is using `property`:

Yes, this works for mypy, thanks!

Unfortunately, now it's pylint that is not happy, as it seems to confuse the getter with the function itself:

```python
"""Bug."""
from typing import Callable, Protocol

class Proto(Protocol):
    @property
    def fun(self) -> Callable[[int], None] | None:
        ...

class Class(Proto):
    def fun(self, i: int) -> None:
        print(i)
```

```
bug.py:10:4: W0221: Number of parameters was 1 in 'Proto.fun' and is now 2 in overriding 'Class.fun' method (arguments-differ)
bug.py:10:4: W0236: Method 'fun' was expected to be 'property', found it instead as 'method' (invalid-overridden-method)
```

Removing explicit inheritance and adding the type-check you mentioned (in the form of `if TYPE_CHECKING: _proto: Proto = Class()` works around this issue, but I will report it with the pylint team as well.

**Comment by bersbersbers** [comment]
Since improving error messages is tracked in #15240 and the pylint issues does not belong here, I guess this issue should be considered a duplicate of #601.
