### ISSUE TITLE
using `.split()` on a `six.string_types` isn't supported

### ISSUE THREAD

**Issue by timabbott** [python/mypy#1525]
mypy doesn't like this code:

```    
if isinstance(data, six.string_types):                                                                                 
        data = data.split(',')                                                                                             
```

with this error:

```
zerver/lib/actions.py: note: In function "extract_recipients":
zerver/lib/actions.py:789: error: "basestring" has no attribute "split"
```

I haven't had a chance yet to investigate whether "split" should be supported on basestring objects (and thus it's a stub issue) or whether the code is wrong.

**Comment by gvanrossum** [comment]
Check the open PRs on typeshed. There's an incomplete one adding methods to
basestring.

--Guido (mobile)

**Comment by timabbott** [comment]
Yeah, that would definitely solve this.  I guess we can close the mypy issue and just track that PR.  Thanks @gvanrossum!

**Comment by gvanrossum** [comment]
Could you try out that PR? I'm a little scared to apply it since there are so many affected methods.

**Comment by timabbott** [comment]
yep, trying now

**Comment by timabbott** [comment]
Well, it fixes that issue, but introduces several new ones:
```
tools/run-dev.py: note: At top level:
tools/run-dev.py:68: error: Argument 1 to "check_call" has incompatible type "str"; expected Sequence[str]
tools/emoji_dump/emoji_dump.py:46: error: Argument 1 to "call" has incompatible type "str"; expected Sequence[str]
zerver/lib/bugdown/__init__.py: note: In member "run" of class "AlertWordsNotificationProcessor":
zerver/lib/bugdown/__init__.py:839: error: Type argument 1 of "search" has incompatible value "object"
analytics/views.py: note: In function "get_realm_day_counts":
analytics/views.py:103: error: Incompatible types in assignment (expression has type "str", variable has type List[int])
```

The first few are essentially `subprocess.call("command")`; the last one is https://github.com/zulip/zulip/blob/master/analytics/views.py#L103

**Comment by gvanrossum** [comment]
Aha, the subprocess stub is wrong; it says the args must be Sequence[str] but it's actually Union[str, Sequence[str]]. It's interesting that it previously didn't complain; I guess the reason is that a str is also a sequence of str. And so (despite the stub deficiency) it still shouldn't have complained, so this still points to a problem in my basestring PR. I'll have to look into that later (busy with a talk right now).

The last one is an occurrence of something else (you can't redefine a variable as something different). I'm guessing previously the type was Any so it didn't complain?

**Comment by timabbott** [comment]
Yep, I think you're right, this is mypy catching an issue it wasn't before.  The zerver/lib/bugdown/__init__.py one I think is an issue with running `re.search` on the output of `re.compile`; probably a stub issue with the `re` module.

**Comment by gvanrossum** [comment]
Oh, that's https://github.com/python/typeshed/issues/188

**Comment by timabbott** [comment]
Yep, just with a different function in `re`.
