### ISSUE TITLE
Warn about apparently misspelled # type: comments

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1528]
We got a bunch of new users internally and at least one accidentally left out the `:` from a `# type` comment. Fortunately the watchful eye of an experienced user found it quickly. But maybe mypy could warn about such comments?

**Comment by wittekm** [comment]
I can pick this up.

**Comment by wittekm** [comment]
Discovered some noisiness and some weird tests.
https://gist.github.com/wittekm/075997aadc82cc97cffe24ea4611728b
I summarized the problems I found at the bottom. The two weird things I found in the tests were:

1) `# type (A, B, C)` on Tuple indexing - is that even valid syntax? not `# type: Tuple[A, B, C]` ?
2) I saw some `# type. A` in some of our tests; is that some legacy syntax or just a typo?

how should we proceed with the following two?

**Comment by gvanrossum** [comment]
- The `os/__init__pyi` false positive shows why this is shaky ground. I wonder if it should be a linter instead of integrated into mypy?

- Re `testWhitespaceAndCommentAnnotation3`: Why would you need to change anything? If that's not a valid type annotation why should it elicit a warning?

- `type (A, B, C)`: With the colon this is valid for multiple assignments, see https://www.python.org/dev/peps/pep-0484/#type-comments; I think it's a bug in the test that these have no colon

- I'm less sure about the `# type. A` cases -- here it seems at least plausible that these are meant to tell the human reader what the type is. But Jukka doesn't usually do that, so maybe they're what you think they are.

One way to proceed would be to fix those things that you believe are bugs and see if all tests still pass. (E.g. submit a PR with a "don't commit yet" message.)

**Comment by JukkaL** [comment]
* `type (A, B, C)`: Agree with Guido, this is probably bug in a test case.
* `# type. A`: This looks like a typo.

Perhaps we could be more selective in what to report? For example, just focusing on cases like these might reduce the false positive count:

* `# type` not followed by `:` but followed by `->` on the same line
* `# type (`
* `# Type:` (capital `T`) followed by something looking like a type
* `# type [A-Za-z_0-9.]+$` (something looking like an identifier or qualified name, such as `# type int`)
* `# type [A-Za-z_0-9]+\[` (something looking like a generic type)

Also, before enabling this, it would be nice to run it against a large corpus of Python code to see if there still are a significant number of false positives. For examples, go through the Python standard library and any internal codebases you work on.

**Comment by wittekm** [comment]
Yeah, good suggestions. Definitely agree there should be no warning on just `# type` without a following `:`. 

I'm concerned that too-intense regexes might really bring down mypy performance.
* As such, maybe this _is_ better suited as a linter. 
* Are there any performance regression tests?

**Comment by JukkaL** [comment]
Yes, this would be better suited for a linter, but if linters still don't properly support PEP 484 I'm okay with having this in mypy as a stopgap measure, as long the false positive rate is low.

This can be made fast by doing regexp checking in two passes. First, look for comments that look like this:

`# *(type[^:]|Type)`

This should cover all the other cases, plus some we don't care about. Then if this matches, enumerate through all the possible special cases, and only report a warning if one of them matches. The first regular expression will only match a trivial subset of all comments, so the performance of the latter check won't matter. (Not sure whether the optimization is important, but it's worth considering.)

Sadly, we don't have performance regressions tests.

**Comment by ddfisher** [comment]
I'm not sure what the implementation plan is here, but can we consider how this will interact with the fast parser?  It'd be unfortunate to have to redo the majority of this work.

**Comment by gvanrossum** [comment]
Yet, yet another reason to make it a linter. (It also doesn't make sense to
run this over all files -- the typical linter setup often only runs over
new or changed files, and that's just what you'd want here.)

**Comment by ddfisher** [comment]
Agreed.
