### ISSUE TITLE
Readthedocs site does not match latest PyPI Mypy version

### ISSUE THREAD

**Issue by wesleywright** [python/mypy#15284]
**Documentation**

The [Readthedocs site](https://mypy.readthedocs.io/en/stable/) seems to match the 1.2 docs, although 1.3 was released several weeks ago now. This can be seen in both the version number on the site and the lack of updates that were included in 1.3 (for example, https://github.com/python/mypy/pull/14973 should have updated [Typing async/await](https://mypy.readthedocs.io/en/stable/more_types.html#typing-async-await)). The automation to sync the site with the published package is likely broken.

Thanks to @A5rocks for [reporting this elsewhere](https://github.com/python/mypy/issues/15075#issuecomment-1555419927).

**Comment by hauntsaninja** [comment]
I manually rebuilt stable here https://readthedocs.org/projects/mypy/builds/20781681/ and I think it seems to have been picked up?

Not sure exactly what went wrong but maybe we were still affected by https://github.com/readthedocs/readthedocs.org/issues/10290 when the tag got pushed

**Comment by hauntsaninja** [comment]
Did this for mypyc too
