### ISSUE TITLE
Abstract base classes are expected to have case in structural pattern matching.

### ISSUE THREAD

**Issue by CharString** [python/mypy#15289]
**Bug Report**

When pattern matching on an ABC, handling all possible subclasses is not considered exhaustive by mypy.

**To Reproduce**
https://mypy-play.net/?mypy=latest&python=3.11&gist=e8c3ebe10bb09ce9c833108f12640945
```python
from abc import ABC, abstractmethod
from typing import assert_never


class AbstractThing(ABC):
    @abstractmethod
    def foo(self) -> None:
        ...


class Something(AbstractThing):
    def foo(self):
        pass


class OtherThing(AbstractThing):
    def foo(self):
        pass


def handle_thing(thing: AbstractThing) -> None:
    match thing:
        case Something():
            pass
        case OtherThing():
            pass
        case _ as unreachable:
            assert_never(unreachable)
```

**Expected Behavior**

I thought this would type check; as all possible values of AbstractThing in this context are handled.

**Actual Behavior**

main.py:28: error: Argument 1 to "assert_never" has incompatible type "AbstractThing"; expected "NoReturn"  [arg-type]
Found 1 error in 1 file (checked 1 source file)

**Your Environment**

See the mypy-play link.

**Comment by JelleZijlstra** [comment]
There could be other child classes in other files. Mypy is correct here.

I would recommend typing the argument to your function as a union like `SomeThing | OtherThing` here. There has been some discussion about this in the past; it was suggested to add something called `@sealed` that would enforce that child classes can only be defined in a single file. However, for now the union trick is what we have.
