### ISSUE TITLE
`@override` warnings are silenced by accidentally type-annotating `override`

### ISSUE THREAD

**Issue by bersbersbers** [python/mypy#15293]
**Bug Report**

I am thinking about using `override` on Python < 3.12 without having to have `typing_extensions` as a forced run-time dependency. I am using a conditional import for this, which I had previously also done for `overrides.override`, see #13914. However, when I leave this type annotation in place for `typing_extensions.override`, all `@override` warnings are gone.

**To Reproduce**

```python
from typing import Any, Callable, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

# this silences @override even if typing_extensions is installed.
override: Callable[[F], F]

try:
    from typing_extensions import override
except ModuleNotFoundError:

    def override(method: F, /) -> F:
        return method

class ClassA:
    ...

class ClassB(ClassA):
    @override
    def this_should_error(self) -> None:
        pass
```
https://gist.github.com/mypy-play/74cf551a06f0cc5b56ddc8cc96708ab8

**Expected Behavior**

Mypy error about `this_should_error`

**Actual Behavior**

No error

**Your Environment**

- Mypy version used: master on playground

**Comment by ikonst** [comment]
Shorter repro:
https://mypy-play.net/?mypy=master&python=3.12&gist=985cd92890a29ba55c4a37bf818e526a

**Comment by bersbersbers** [comment]
> Doesn't it work as expected without the override: Callable[[F], F]?

Yes, it does - that's why I wrote "accidental" in the title. The `override: Callable[[F], F]` is/was a leftover from my previous code using the `overrides` packages, which needs this kind of gymnastics for reasons that are not clear to me.

The point of this issue not to improve my code, but to make you aware that by typing `override`, one can silently render it useless.

**Comment by hauntsaninja** [comment]
Yeah, I think this is a won't fix. As ikonst says, this looks like something that could get rebound. pyright's behaviour is similar, except that it issues a `no-redef` kind of warning that you were looking to avoid in #13914

tmke8's suggestion of `if TYPE_CHECKING` is a good way to go for this kind of thing. Type checkers are special cased to always know about `typing_extensions` even if it's not installed, so everything should just work.
