### ISSUE TITLE
TypeGuard is incompatible with exhaustiveness checking

### ISSUE THREAD

**Issue by antonagestam** [python/mypy#15305]
**Bug Report**

Narrowing with a `TypeGuard` function doesn't work in conjunction with exhaustiveness checking using `assert_never()`.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=b6bc8609a83ff0538459d658c74f23ea

**Expected Behavior**

In the example, I expected the `TypeGuard` function to work no differently from the inlined type checks.

**Actual Behavior**

When using `TypeGuard`, the variable seems to be properly narrowed (`revealed_type()` within the branch is identical), but it seems somehow the result isn't recorded identically as the inlined checks. In the function using `TypeGuard`, the exhaustiveness check is not passing.

**Your Environment**

- Mypy version used: 1.3.0
- Mypy command-line flags: -
- Mypy configuration options from `mypy.ini` (and other config files): -
- Python version used: 3.11

**Comment by erictraut** [comment]
Mypy is correct here. `TypeGuard` does not perform narrowing in the negative (`else`) case. For the reasoning behind this, you can refer to [PEP 647](https://peps.python.org/pep-0647/). There has been some discussion of adding a variant called `StrictTypeGuard` that is more limited than `TypeGuard` but allows negative type narrowing. This would require a new PEP, and it hasn't made it beyond the [discussion phase](https://github.com/python/typing/discussions/1013) yet.

**Comment by AlexWaygood** [comment]
What Eric said

**Comment by antonagestam** [comment]
Ah my bad, thanks for explaining! 🙏
