### ISSUE TITLE
mypy not recognizing Protocol implementation

### ISSUE THREAD

**Issue by cmolinero** [python/mypy#15312]
**Bug Report**

When implementing a Protocol that requires a method that receives and returns another Protocol, mypy is not recognizing it. I have also tried without using the TypeVar T, but problem persists.

Am I doing something wrong, or it's a mypy limitation when working with protocols?

Thanks for your help!

**To Reproduce**
```python
from typing import Protocol, TypeVar


class SubDummyProtocol(Protocol):

    def __init__(self, value: str) -> None:
        pass


T = TypeVar("T", bound=SubDummyProtocol)


class DummyProtocol(Protocol):

    def dummy_method(self, p: T) -> T:
        ...


class SubDummyImp:

    def __init__(self, value: str) -> None:
        self.value = value


class DummyImp:

    def dummy_method(self, p: SubDummyImp) -> SubDummyImp:
        return p


def test_function(d: DummyProtocol) -> None:
    pass


test_function(DummyImp())
```

**Actual Behavior**
This is what mypy outputs:

error: Argument 1 to "test_function" has incompatible type "DummyImp"; expected "DummyProtocol"  [arg-type]
note: Following member(s) of "DummyImp" have conflicts:
note:     Expected:
note:         def [T <: SubDummyProtocol] dummy_method(self, p: T) -> T
note:     Got:
note:         def dummy_method(self, p: SubDummyImp) -> SubDummyImp

If TypeVar is not used, and only ask for SubDummyProtocol in arg and return value, there is still an error:

error: Argument 1 to "test_function" has incompatible type "DummyImp"; expected "DummyProtocol"  [arg-type]
note: Following member(s) of "DummyImp" have conflicts:
note:     Expected:
note:         def dummy_method(self, p: SubDummyProtocol) -> SubDummyProtocol
note:     Got:
note:         def dummy_method(self, p: SubDummyImp) -> SubDummyImp

- Mypy version used: 0.991
- Python version used: 3.9

**Comment by jakobkogler** [comment]
This is not a bug. `mypy` is correct to show an error here.

The protocol `DummyProtocol` says, that the class needs a method `dummy_method` that accepts arbitrary objects of the protocol `SubDummyProtocol`. And this is not the case for `DummyImp`, it's method `dummy_method` only accepts objects of type `SubDummyImpl` and not of any arbitrary.

You could change the method protocol to the following, allowing all objects that fulfill the protocol.

```python
class DummyImp:
    def dummy_method(self, p: T) -> T:
        return p
```

Or if you want to limit it to a certain implementation of the project, - what you probably want to do - you can use generics. That way you tell the typing system, that you want a specific implementation of the 

```python
class DummyProtocol(Protocol[T]):
    def dummy_method(self, p: T) -> T:
        ...

class DummyImp:
    def dummy_method(self, p: SubDummyImp) -> SubDummyImp:
        return p
```

Notice the generic protocol `Protocol[T]`. `DummyImp` satisfies then the protocol `DummyProtocol[SubDummyImp]`.
So you can write something like `def test_function(d: DummyProtocol[SubDummyImpl]) -> None:`. 

If you don't specify the `T` value, mypy will assume the type `DummyProtocol = DummyProtocol[Any]` and you'll loose some checks again.
