### ISSUE TITLE
Mypy gets confused between Process and process

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1531]
Repro (on OS X only):
```
mypy --py2 -c 'from multiprocessing import Process'
```
This gives the following mysterious error (and no others):
```
typeshed/stdlib/2.7/multiprocessing/__init__.pyi:5: error: Name 'Process' already defined
```
Using `-v` I found the reason is that mypy believes that Process is a submodule of multiprocessing, because `os.stat('.../Process.pyi')` succeeds -- the filesystem is case-insensitive, so it returns stat() info for `.../process.pyi`. :-(

I'll try to figure out what the right idiom is to handle this.

**Comment by kirbyfan64** [comment]
Wouldn't this also be an issue on Windows, which is also case-insensitive?

**Comment by gvanrossum** [comment]
Yes, Windows should have the same problem. In either case I expect the
solution is to list the directory and double-check whether the file is
exactly there rather than just believing os.path.exists() or similar.
