### ISSUE TITLE
Decorating a coroutine function with an `*args` seems to confuse mypy

### ISSUE THREAD

**Issue by Anvil** [python/mypy#15333]
Dear MyPy Maintainers

I am the maintainer of the [kaioretry module](https://github.com/Anvil/kaioretry). Which, in short, is a retry decorator implementation for asyncio coroutines. It was originally a pet project, but now I'm using it in production. 

And now I think I've found an interesting issue... But I'll let you be the judges of that.

Before I start describing it, I'll let you know that the tests cases I'll be talking about are currently located in the 3 following files which i just added with the followig commit https://github.com/Anvil/kaioretry/commit/e543371bc437de1df5bcecea47c1c63358cc933e
* https://github.com/Anvil/kaioretry/blob/more-tests/test/static_analysis/41_aioretry_args.py
* https://github.com/Anvil/kaioretry/blob/more-tests/test/static_analysis/42_aioretry_args_explicit_decorate.py
* https://github.com/Anvil/kaioretry/blob/more-tests/test/static_analysis/43_aioretry_params.py

The first one of those files triggers an error. The two others don't, despite being very similar. It took me like 2 days to identify the issue and reduce the code to this minimal form in order to reproduce what I consider a bug.

**Bug Report**
In substance, I'd say mypy incorrectly think my kaioretry-decorated coroutine is a `def (*Any, **Any) -> Any`, instead of a `def (*args: Any) -> typing.Coroutine[Any, Any, builtins.str]`. But it depends of the way I use the decorator. And it seems related to `*args`.

**To Reproduce**, please consider the following code sample:

```python
from __future__ import annotations
from typing import reveal_type, Any
from kaioretry import Retry, Context # Using version >= 0.10.0.

# This, is a Retry object, with some parameters which do not matter for our purpose
# And the aioretry method of this object is a decorator.
aioretry = Retry(
    exceptions=(ValueError, NotImplementedError),
    context=Context(tries=5, delay=2)).aioretry

# Here I decorate a random a coroutine function with aioretry
# Notice the *args. It's relevant to our problem.
@aioretry
async def request(*args: Any) -> str:
    return "asdf"
reveal_type(request)

# Here I just use the decorated coroutine
async def get_obj(obj_id: str) -> int:
    response = await request(1, 2, 3)
    return int(response)
```

When running mypy I get the following output:
```
test/static_analysis/41_aioretry_args.py:12:13:12:19: note: Revealed type is "def (*Any, **Any) -> Any"
test/static_analysis/41_aioretry_args.py: note: In function "get_obj":
test/static_analysis/41_aioretry_args.py:15:22:15:37: error: Call to untyped function "request" in typed context  [no-untyped-call]
        response = await request(1, 2, 3)
                         ^~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 1 source file)

```

I could not figure out why, so I tried some things and I've discovered this:
1. Not using the `@decorate` syntax does not trigger that error. i.e:
```python
from __future__ import annotations
from typing import reveal_type, Any
from kaioretry import Retry, Context

# Same decorator
aioretry = Retry(
    exceptions=(ValueError, NotImplementedError),
    context=Context(tries=5, delay=2)).aioretry

# Same coroutine, but undecorated.
async def request(*args: Any) -> str:
    return "asdf"
reveal_type(request)
# Explicit decoration.
request = aioretry(request)
reveal_type(request)

async def get_obj(obj_id: str) -> int:
    response = await request(1, 2, 3)
    return int(response)
```
mypy output:
```
test/static_analysis/42_aioretry_args_explicit_decorate.py:17:13:17:19: note: Revealed type is "def (*args: Any) -> typing.Coroutine[Any, Any, builtins.str]"
test/static_analysis/42_aioretry_args_explicit_decorate.py:19:13:19:19: note: Revealed type is "def (*args: Any) -> typing.Coroutine[None, None, builtins.str]"
Success: no issues found in 1 source file
```

2. If the original non-decorated coroutine function has a fixed arity, this does not happen either. i.e: 
```python
from __future__ import annotations
from typing import reveal_type, Any
from kaioretry import Retry, Context

# Again, same decorator
aioretry = Retry(
    exceptions=(ValueError, NotImplementedError),
    context=Context(tries=5, delay=2)).aioretry

# The @decorator syntax is used. The implementation of the function is the same 
# but this one does not have an `*args` and have 3 explicit parameters instead.
@aioretry
async def request(i: int, j: int, k: int) -> str:
    return "asdf"
reveal_type(request)

async def get_obj(obj_id: str) -> int:
    response = await request(1, 2, 3)
    return int(response)
```
mypy output for this file:
```
test/static_analysis/43_aioretry_params.py:18:13:18:19: note: Revealed type is "def (i: builtins.int, j: builtins.int, k: builtins.int) -> typing.Coroutine[None, None, builtins.str]"
Success: no issues found in 1 source file
```

**Expected Behavior** 
I would have expected all 3 cases to behave the same: `Success: no issue found`, but I wont be offended if you tell me if I did something wrong. 

**My Environment**

Tonight I'm working with my personnal workstation, which runs an up-to-date fedora 38 system.
* Python version is 3.11.3
* kaioretry==0.10.0, mypy==1.3.0, mypy-extensions==1.0.0

But I've encountered the same issue with  python 3.10 on ubuntu 22.04. (same kaioretry/mypy/mypy-extensions modules version)

The mypy settings I use are located in the [pyproject.toml](https://github.com/Anvil/kaioretry/blob/main/pyproject.toml#L46) file of kaioretry. The matching section of the file is reproduced below, and I just call mypy as is, without any parameter or with a file parameter.

```
[tool.mypy]
color_output = true
ignore_missing_imports = false
pretty = true
raise_exceptions = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
show_error_end = true
show_traceback = true
strict = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
disallow_untyped_decorators = true
packages = ["kaioretry", "test.static_analysis"]
```

The aioretry method implementation is here:
https://github.com/Anvil/kaioretry/blob/main/kaioretry/decorator.py#L223

Feel free to comment or ask about my code. I've dug deeeeep - I think - in the type-hinting topic in the last few days, but I'm eager to learn.

What do you think ?

And, in advance, thank you for your time.

**Comment by erictraut** [comment]
Your code looks fine. This should type check without errors. (For comparison, it type checks fine with pyright.)

Mypy appears to be confused by the overloaded method `Retry.aioretry`. If I comment out the second overload, mypy produces the expected results (i.e. it evaluates the decorated function as `def (*args: Any) -> typing.Coroutine[None, None, builtins.str]`). When both overloads are present, it evaluates the decorated function as `def (*Any, **Any) -> Any`. One thing that is unusual about `Retry.aioretry` is that it has two overloads that both use function-scoped ParamSpecs. This is perfectly legal, but it's unusual.

Perhaps those clues can help someone who is more familiar with the mypy code home in on the source of the bug.

**Comment by Anvil** [comment]
Thank you for your reply.

It's unusual, I agree. The decorator can take a regular function or a coroutine function and will produce a coroutine function whatever the input function was. The signature of the original function is left unchanged except about the `RetVal` basically becoming an `Awaitable[RetVal]` 

I originally tried to annotate the function without the overloads, in a way which sounded shorter and more direct: 
https://github.com/Anvil/kaioretry/blob/b3e584abddb517a87dd8657f459c1aad3b9e37bb/kaioretry/decorator.py#L215 

And the result turned out to be even more confusing at least for me. e.g:

```
test/static_analysis/41_aioretry_args.py:14:2:14:2: error: Argument 1 has incompatible type "Callable[[VarArg(Any)], Coroutine[Any, Any, str]]"; expected
"Union[Callable[[VarArg(<nothing>), KwArg(<nothing>)], Awaitable[<nothing>]], Callable[[VarArg(<nothing>), KwArg(<nothing>)], <nothing>]]"  [arg-type]
    @aioretry
     ^
test/static_analysis/41_aioretry_args.py:18:13:18:19: note: Revealed type is "def (*<nothing>, **<nothing>) -> typing.Awaitable[<nothing>]"
test/static_analysis/41_aioretry_args.py: note: In function "get_obj":
test/static_analysis/41_aioretry_args.py:22:16:22:37: error: Need type annotation for "response"  [var-annotated]
        response = await request(1, 2, 3)
                   ^~~~~~~~~~~~~~~~~~~~~~
test/static_analysis/41_aioretry_args.py:22:30:22:30: error: Argument 1 to "request" has incompatible type "int"; expected <nothing>  [arg-type]
        response = await request(1, 2, 3)
                                 ^
test/static_analysis/41_aioretry_args.py:22:33:22:33: error: Argument 2 to "request" has incompatible type "int"; expected <nothing>  [arg-type]
        response = await request(1, 2, 3)
                                    ^
test/static_analysis/41_aioretry_args.py:22:36:22:36: error: Argument 3 to "request" has incompatible type "int"; expected <nothing>  [arg-type]
        response = await request(1, 2, 3)
```

I did not fully understand why "nothing" was a thing. And it took me something like 3 full-time days to obtain "something" instead of "nothing".

This being said, a quick question : since `reveal_typs` itself reports something "wrong" in the first test case, is the issue really about `mypy` or about the code  `mypy` and `reveal_type` both rely on ? 
Shoud I report this issue somewhere else ?

**Comment by erictraut** [comment]
I'm not able to repro this with the latest version of mypy (1.5). I wonder if it was fixed. Or perhaps the `kaioretry` library changed since the bug was originally filed.
