### ISSUE TITLE
Feature Request: Make variable annotations optional

### ISSUE THREAD

**Issue by saxbophone** [python/mypy#1534]
I think it might be a good idea to make the type-checking of variable declarations optional, by passing an appropriate flag to mypy when running static code checking.

The reason I think this would be useful would be for those who might want to have type-checking of function signatures and the calling of them, but not for declaration of variables.

If the maintainers think this is a feature they'd like to have, some further discussion probably needs to happen regarding how the behaviour is handled (i.e. variable checking being *optional* versus *ignored*).

> This is following on from observations related to #1164

**Comment by gvanrossum** [comment]
I'm not sure there'd be a huge demand for this. In a sense variable annotations are already optional -- except for cases where mypy can't infer the type (mostly for empty containers). If you want signature annotations but don't care about the body being type-checked period, perhaps you should use stub files, which are exactly that.

**Comment by saxbophone** [comment]
Aha! Great, thanks @gvanrossum, that looks perfect!
