### ISSUE TITLE
Generic function parameter `type[T]` does not allow argument to be a `UnionType`

### ISSUE THREAD

**Issue by daniil-berg** [python/mypy#15354]
### Bug Report

A generic function with a parameter declared to be `type[T]` does not allow a union of types to be passed as an argument.

### To Reproduce ([Playground link](https://mypy-play.net/?mypy=latest&python=3.11&gist=2cf4894c38f1676a4f41c752daf24468))

```python
from typing import TypeVar

T = TypeVar("T")


def f(_typ: type[T]) -> T: ...  # type: ignore[empty-body]


f_output = f(str | int)  # error [arg-type]
reveal_type(f_output)    # Any


def g(obj: T) -> type[T]: return type(obj)


arg: str | int
g_output = g(arg)        # passes
reveal_type(g_output)    # Union[Type[builtins.str], Type[builtins.int]]
```

I added the function `g` just as a seemingly analogous contrasting example to show how `T` collapses just fine to `str | int`, when passed an argument of that type.

### Expected Behavior

I expected `f(str | int)` to pass without errors **and** I expected `f_output` to be inferred as being of type `str | int`.

I have not tested it with Pyright, but judging from what is mentioned in [this issue](https://github.com/microsoft/pyright/issues/4298) (see the `func2` example) and a subsequent comment by @erictraut, it seems to work just like that with Pyright.

### Actual Behavior

```
9: error: Need type annotation for "f_output"  [var-annotated]
9: error: Argument 1 to "f" has incompatible type "UnionType"; expected "Type[<nothing>]"  [arg-type]
10: note: Revealed type is "Any"
18: note: Revealed type is "Union[Type[builtins.str], Type[builtins.int]]"
```

Using the "old" syntax `Union[str, int]` instead does not seem to fundamentally change the error. It just says `incompatible type "object"` instead (which I would attribute to the _join_ of the two types).

### Environment

- Mypy version used: `1.3.0`
- Mypy configuration options:  `strict = True` `show_error_codes = True`
- Python version used: `3.11.1`

**Comment by hmc-cs-mdrissi** [comment]
The broader issue here is this [one](https://github.com/python/mypy/issues/9773). Mypy's current behavior is fine under strict reading of pep 484. Pyright is laxer here. I'm pretty happy with laxer view as I commonly need TypeForm[T], but both choices are reasonable and long term the solution is for someone to continue driving PEP for TypeForm and be able to distinguish the two.

**Comment by daniil-berg** [comment]
@hmc-cs-mdrissi Ah, I was not aware of this being a broader issue. Very interesting. Thanks for linking it.

So the current position of the team is that `type` (or `Type`) should remain reserved for _actual_ classes, i.e. things that can be passed as the second argument to `isinstance`. (Judging from [this comment](https://github.com/python/mypy/issues/9773#issuecomment-738581285).)

And for all other types some new construct like the proposed `TypeForm` should be created. But there is currently nobody actively/openly working on this. 

Did I sum that up correctly?

But with the introduction of such a `TypeForm` construct, would we be able to annotate my example function to express that if a **union** of types `str | int` is passed in, it will return an object that can be of either `str` or of `int` type?

```python
from typing import TypeForm, TypeVar

T = TypeVar("T")


def f(_typ: TypeForm[T]) -> T: ...  # type: ignore[empty-body]


f_output = f(str | int)  # would pass ?
reveal_type(f_output)    # would reveal `Union[str, int]` ?
```

Just making sure I understand the scope of the initial proposal correctly.

**Comment by hmc-cs-mdrissi** [comment]
Yes that is a correct understanding.
