### ISSUE TITLE
Callable with tuple-any doesn't match tuple

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#15356]
```python
from typing import Any
from collections.abc import Callable

class X:
    pass

def f(x: tuple[X], /) -> None:
    pass

def g(c: Callable[[tuple[Any, ...]], None]) -> None:
    pass

g(f)  # error: Argument 1 to "g" has incompatible type "Callable[[Tuple[X]], None]"; expected "Callable[[Tuple[Any, ...]], None]"  [arg-type]
```

**Comment by hauntsaninja** [comment]
I think mypy is right here, `c` needs to accept tuples of arbitrary length:
```
from typing import Any
from collections.abc import Callable

class X:
    pass

def f(x: tuple[X], /) -> None:
    assert len(x) == 1

def g(c: Callable[[tuple[X, ...]], None]) -> None:
    t = (X(), X(), X())
    c(t)

g(f)  # raises
```

**Comment by hauntsaninja** [comment]
pyright's behaviour looks different from mypy's, but I think mypy's behaviour here is better (or at least, stricter). For example, pyright only complains about `f`, not `g`:
```
class X: ...

def f(x: tuple[X], y: tuple[X, X]):
    x = y

def g(x: tuple[X], y: tuple[X, ...]):
    x = y
```

**Comment by NeilGirdhar** [comment]
That makes sense.  I guess there's no way to make the length of the tuple unchecked?

So the best we can do right now for an unconstrained length tuple is just Any.

Ideally, we might have some VarArgs[T] that stands in for an arbitrarily sized parameter list of T.  Then I could type the base class as accepting tuple[VarArgs[Any]].  What do you think?

**Comment by hauntsaninja** [comment]
Yeah the following type checks:
```
from typing import Any, Callable, TypeVar

T = TypeVar("T", bound=tuple[Any, ...])

class X:
    pass

def f(x: tuple[X], /) -> None:
    pass

def g(c: Callable[[T], None]) -> None:
    pass

g(f)
```

**Comment by NeilGirdhar** [comment]
Fascinating workaround. I've never used a type variable in one place. I'll try that in pyright when I get home and if it also accepts it then that's good enough for me.
