### ISSUE TITLE
mypy cannot change the dictionary value types via dictionary/list comprehensions

### ISSUE THREAD

**Issue by cjproud** [python/mypy#15350]
**Bug Report**

When changing the type of a dictionary via a list comprehension, for example from an string to a float, mypy returns the following error:

`mypy_dict_test.py:16: error: List comprehension has incompatible type List[Optional[float]]; expected List[str]  [misc]`

I'm wondering whether I'm seeing this behaviour as mypy treats dictionaries as invariant?  If I output the list comprehension to another dictionary, I have no issues.

**To Reproduce**

```python
def get_float_from_str(string_in: str) -> float | None:
    if string_in == "":
        return None
    else:
        return float(string_in)

example_dict = {
    "a": ["1","2"],
    "b": ["3","4"],
    "c": ["5","6"],
}

for key, val in example_dict.items():
    example_dict[key] = [get_float_from_str(x) for x in val]

```

**Expected Behavior**

I expected mypy to observe the output from `get_float_from_str` to be an `Optional[float]` and update the type of the dictionary to be `dict[str, list[float | None]`. My understanding here could be completely incorrect!

**Actual Behavior**

`mypy_dict_test.py:16: error: List comprehension has incompatible type List[Optional[float]]; expected List[str]  [misc]`

**Your Environment**

- Mypy version used: 1.3.0
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): No `.ini` file used.
- Python version used: 3.10.11

**Comment by hauntsaninja** [comment]
In general, mypy doesn't change the types of variables. There is a setting that lets you change types of variables if rebound, but that's not what's happening here. This kind of mutation is pretty hard to reason about (e.g. mypy would need to have special cased understanding that `items` returns all possible keys for this to be sound), and it's possible to construct similar looking examples where users would want this to error.

**Comment by hauntsaninja** [comment]
Note if you'd just like mypy to get out of your way, you can type your dictionary as `dict[str, Any]` or use `# type: ignore`

**Comment by cjproud** [comment]
Thanks for the clarification @hauntsaninja, appreciate it!
