### ISSUE TITLE
Supporting Typescript-like Mapped Types

### ISSUE THREAD

**Issue by bewakes** [python/mypy#15371]
**NOTE**: Weirdly, I could not find any similar issues/discussions(because I think this is so commonly required feature), so I had to create an issue.

**Feature**
In typescript, if we have an object like this:
```typescript
type X = {
  a: string;
  b: string;
  c: string;
};
```
then, we can create a new mapped type with different type for the values,
```typescript
type Y = {
  [p in keyof X]: number;
};
/*
type Y = {
  a: number;
  b: number;
  c: number;
}
*/
```
There doesn't seem to be any way to do so in python.

**Pitch**

I think this is a very useful usecase. For example: I have a data:
```python
class OptionsConf(TypedDict):
    options: List[Tuple[int, str]]
    discarded: List[int]

# This one!
class OrgSetting(TypedDict):
    career_stages: OptionsConf
    professional_fields: OptionsConf
    goals: OptionsConf

# This is the target value type
class KeyLabel(TypedDict):
    key: str
    value: str

# And this one!
# Now, I want new type with same keys as OrgSetting, but with different value, say another typed dict for each key
class OrgKeyLabels(TypedDict):
   career_stages: List[KeyLabel]
   professional_fields: List[KeyLabel]
   goals: List[KeyLabel]
```

I would like to derive `OrgKeyLabels` type just using `OrgSetting` type.

In any case, is there any pythonic way to do this?

**Comment by tmke8** [comment]
Does this work for you? https://mypy-play.net/?mypy=latest&python=3.11&gist=cc85ca014e577e9288776130be53f0d3

**Comment by bewakes** [comment]
It works, many thanks!
