### ISSUE TITLE
Ability to specify return type of class attribute

### ISSUE THREAD

**Issue by kwint** [python/mypy#15370]
**Feature**

I would like to tell mypy that a specific function returns an instance of class with specific attribute types. So the class has an optional attribute, but this specific function always returns an instance of this class where the attribute is always a specific type.

Currently this code generates a mypy error:

```
@dataclass
class Foo:
    value: str | None

def create_foo_from_bar(bar: str) -> Foo:
    return Foo(value=bar)

foo = create_foo_from_bar(3)
foo.value.upper() # Item "None" of "Optional[str]" has no attribute "upper"
```

It would be nice if mypy could see that the function `create_foo_from_bar` always populates `Foo.value` with a string.

Maybe an explicit notation would be even better:

```
def create_foo_from_bar(bar: str) -> Foo[int]:
    return Foo(value=bar)
```

I guess the current way to do this is to create a subclass of `Foo` with a stricter type?

**Pitch**

This would clean up the code from having type guards and such. So it would be remove the need of having `assert foo.value is not None`

Must add that I'm fairly new to more advanced python typing, so not fully sure if something like this already exists or if it goes against some design aspects

**Comment by tmke8** [comment]
You could do this with a generic class, as you already almost suggested with the `Foo[int]` notation. See here how to do it: https://mypy-play.net/?mypy=latest&python=3.11&gist=b8def928f8e3b505a28ae62976ede48e
