### ISSUE TITLE
Duplicate arguments in a function definition blocks the checking

### ISSUE THREAD

**Issue by xiaxinmeng** [python/mypy#15390]
In Mypy, duplicate arguments in  a function definition cause blocking. See the following example. 

mypy_example.py
```
def impl(a, a):
    nb_type = 1
    return nb_type
```

### The expected behavior:
no "errors prevented further checking"

### The actual output
```
>> mypy  '' 
mypy_example.py:17: error: Duplicate argument "a" in function definition
Found 1 error in 1 file (errors prevented further checking)
```

### Test Environment
mypy 1.4.0+dev
Python 3.11.3
Ubuntu 18.04

**Comment by tmke8** [comment]
Given that this is a syntax error, it seems okay to me that mypy stops checking the file?

**Comment by erictraut** [comment]
Mypy uses the Python parser to parse the file, and the Python parser doesn't continue past syntax errors, so I don't think this can be fixed in mypy.
