### ISSUE TITLE
Stubtest cannot find module with stubs in separate directory

### ISSUE THREAD

**Issue by rayzchen** [python/mypy#15394]
**Bug Report**

Running `stubtest --mypy-config-file pyproject.toml foo` yields `foo failed to import, ModuleNotFoundError: No module named 'foo'`

**To Reproduce**

1. Clone https://github.com/rayzchen/stubtest-bug
2. Run `stubtest --mypy-config-file pyproject.toml foo`

**Expected Behavior**

Stubtest finds the `foo` module

**Actual Behavior**

```
error: foo failed to import, ModuleNotFoundError: No module named 'foo'
Stub: in file stubs\foo\__init__.pyi:1
MypyFile:1(
  stubs/foo/__init__.pyi)
Runtime:
MISSING

error: foo.bar failed to import, ModuleNotFoundError: No module named 'foo'
Stub: in file stubs\foo\bar\__init__.pyi:1
MypyFile:1(
  stubs/foo/bar/__init__.pyi)
Runtime:
MISSING

error: foo.bar.baz failed to import, ModuleNotFoundError: No module named 'foo'
Stub: in file stubs\foo\bar\baz.pyi:1
MypyFile:1(
  stubs/foo/bar/baz.pyi)
Runtime:
MISSING

Found 3 errors (checked 3 modules)
```

**Your Environment**

- Mypy version used: 1.3.0
- Mypy command-line flags: N/A (used stubtest)
- Mypy configuration options from `mypy.ini` (and other config files): `mypy_path = "stubs/"`
- Python version used: 3.10.6

**Comment by rayzchen** [comment]
Does running `stubtest` as a python entrypoint not add `.` to the pythonpath? Shouldn't running `stubtest foo` try to import `foo` since the argument to `stubtest` is called `modules`?

**Comment by hauntsaninja** [comment]
From https://docs.python.org/3/library/sys_path_init.html

> The first entry in the module search path is the directory that contains the input script, if there is one. Otherwise, the first entry is the current directory, which is the case when executing the interactive shell, a [-c](https://docs.python.org/3/using/cmdline.html#cmdoption-c) command, or [-m](https://docs.python.org/3/using/cmdline.html#cmdoption-m) module.

This means you e.g. get bin/ in your virtual environment added to sys.path. Running stubtest does try to `import foo`, but you need to tell Python where to find `foo` using one of the three options I mention above.

**Comment by rayzchen** [comment]
Alright, thank you for the info.

**Comment by hauntsaninja** [comment]
#15398 will improve the error message here
