### ISSUE TITLE
Details about inner implementation of mypy type system

### ISSUE THREAD

**Issue by SoptikHa2** [python/mypy#15418]
Hi,

I was searching quite a bit, but I was unable to find any papers or documentation about mypy's type system and how is it actually checked and implemented.

Is there something available that would shed light on this? I'm interested in the type system details, and what is it capable of. Maybe some paper/preprint/conference speech?

I believe it might be an interesting extension to people who already read through the whole documentation but would like to dive a bit deeper into mypy, it would be great if a link to something covering mypy in greater technical detail might be added.

**Comment by AlexWaygood** [comment]
We have a wiki here, which might be of interest: https://github.com/python/mypy/wiki

**Comment by SoptikHa2** [comment]
Thanks! I didn't think of checking the wiki. It looks great. Thank you!
