### ISSUE TITLE
Improve error code linkability

### ISSUE THREAD

**Issue by Avasam** [python/mypy#15431]
**Documentation**

In https://github.com/microsoft/vscode-mypy/pull/58, I'm adding the functionality to link to specific mypy error code documentation. However, there's two issues affecting maintainability:
- The error codes span 2 pages
- The anchors are autogenerated from titles

Which leads to having to keep a map of all code-to-url, like this:
https://github.com/microsoft/vscode-mypy/pull/58/files#diff-3c2e579f59d8e749f5527d64f087396907db30414fe139bc91a1ecce9f9613ddR22

I would prefer if it was possible to programmatically link to mypy error codes documentation with only the information given by the mypy/dmypy CLI. Redirection is an acceptable solution to me.

**Comment by ilevkivskyi** [comment]
Note btw there is also https://github.com/python/mypy/issues/7186 I think it is a good idea to add direct short links. I am quite sure we can write a Sphinx extension for this.

**Comment by ilevkivskyi** [comment]
OK, so here is the proposed fix https://github.com/python/mypy/pull/15435

**Comment by Avasam** [comment]
> Note btw there is also #7186 I think it is a good idea to add direct short links. I am quite sure we can write a Sphinx extension for this.

I missed that. This is basically a duplicate. I'm essentially asking for the same thing.

**Comment by ilevkivskyi** [comment]
OK, I guess I actually broke the readthedocs build. Everything works locally and in CI because `mypy` is available there, but likely not available in readthedocs build env. I will submit a follow-up PR to only verify the error code completeness in tests.

**Comment by ilevkivskyi** [comment]
https://github.com/python/mypy/pull/15437 should fix the build.

**Comment by ilevkivskyi** [comment]
OK, this is now available in latest: https://mypy.readthedocs.io/en/latest/_refs.html#code-union-attr
