### ISSUE TITLE
ignore specific imports

### ISSUE THREAD

**Issue by jvanasco** [python/mypy#15450]
**Feature**

[Apologies if this has been asked before.  I searched the relevant terms and went through a few dozen pages of hits.  I did not find a match.  I've also asked friends with more mypy experience than me about existing functionality, and no one knew it.]

The mypy configuration file should allow for specific third-party imports to be skipped.

This would allow for a streamlined way to deal with third party projects that are not typed or stubbed.
Users can simply list the third party packages in setup.cfg, or similar.

**Pitch**

When importing from third party projects that are not typed, the options are essentially:

* tell mypy to ignore all imports on your own code
* do a per-import ignore comment: ` # type: ignore[import]`

The feature I suggest would instruct mypy to globally ignore imports of a specific package:

Consider a project that imports a module that is not typed:

    import is_typed
    import is_not_typed

A common way people handle this for CI systems is to either ignore this in the file:

    import is_typed
    import is_not_typed  # type: ignore[import]

Or turn disable all import errors in their project or a specific project file.

The feature i propose would shift the `ignore` on a per-package basis, into the mypy configuration:

    [mypy]
    ignore_missing_import_projects =
        is_not_typed

This would enable at least the following benefits:

* there is no ignore on the actual code
* a missing import of one third party project does not `ignore` issues from another
* the first party project has a centralized list of missing imports.  
  * this makes it easier to periodically audit the listing, to see if that package is now typed.  
  * this makes it easier to remove the `ignore` when third party packages become typed
* most importantly, this allows mypy to ignore the expected/known import errors - while preserving the unexpected import errors

**Comment by hauntsaninja** [comment]
This exists, use:
```
[mypy-is_not_typed.*]
ignore_missing_imports = True
```

Documented at:
- https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
- https://mypy.readthedocs.io/en/stable/config_file.html#confval-ignore_missing_imports
