### ISSUE TITLE
 Mypy doesn't typecheck raise statements with 2 or 3 arguments

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1547]
https://github.com/python/mypy/blob/master/mypy/checker.py#L1753

**Comment by ddfisher** [comment]
This will be fixed by the introduction of the new parser.

**Comment by gvanrossum** [comment]
I'm going to close this as a won't fix because the new parser will solve this and we're not going to put any work in the old parser/lexer.

**Comment by ddfisher** [comment]
Turns out the new parser *doesn't* solve this.

**Comment by ilevkivskyi** [comment]
It looks like this is fixed now.
