### ISSUE TITLE
Should `mypy>=1.4.0` require `typing_extensions>=4.4.0`?

### ISSUE THREAD

**Issue by bersbersbers** [python/mypy#15484]
Regarding `override`, the mypy blog says in https://mypy-lang.blogspot.com/2023/06/mypy-140-released.html that
> The decorator will be available in typing in Python 3.12, but _you can also use the backport from a recent version of `typing_extensions`_ on all supported Python versions.

I wonder if `mypy` might help ensuring a "recent version of `typing_extensions`" by requiring `typing_extensions>=4.4.0`, where 4.4.0 is the version where `override` was first introduced.

**Comment by hauntsaninja** [comment]
mypy will be able to correctly type check code `override` even with an older `typing_extensions` installed, so I don't think this is necessary. What mypy actually needs at runtime is quite modest.

I don't think mypy needs to serve as a forcing function to get users to upgrade. >80% of downloads are 4.5 and newer already. By default, Python installers will install latest and pinning typing_extensions (in libraries) is highly discouraged.
