### ISSUE TITLE
Following imports but only within a set of enumerated files

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1552]
Currently you can run mypy without `--silent-imports` and it follows all imports. Alternatively, you can run mypy with `--silent-imports` to only follow imports within the explicit set of files (or directories) that is being type checked. However, it's not possible to run mypy against one set of files, and follow imports from these files only within another, larger set of files.

For example, suppose this is how I usually run mypy:

```
$ mypy --silent-imports a.py b.py c.py     # a imports b and c imports a
```

Now if I'm working on `a.py` and I want to see whether my changes to the file make sense locally, I could run the same command as above, but it could report errors in `c` which I may want to ignore. More importantly, if `c` is a big file (or a large number of files), type checking could be slow. Basically, I'd want to type check `a` and `b` only. I can do this manually:

```
$ mypy --silent-imports a.py b.py
```

However, if `b` and `c` are actually hundreds of files each, doing this manually would be hard, if `a.py` is just an arbitrary file among a large number of files. Instead, I`d like to do something like this:

```
$ mypy --silent-imports --entry-point=a.py a.py b.py c.py
```

Now mypy would only look at `a.py` and its dependencies, but only if they are in the list of all files included at the end of the command line. It should be possible to pass multiple entry points as well.

Finally, I could have my personal `mypy-run` script that runs mypy using `--silent-imports` against the large number of target files that I generally care about -- if I run it without arguments. Now if I'd run `mypy-run a.py` it would pass the `a.py` argument as an `--entry-point` argument (in addition to the normal arguments) and I could narrow down the set of target files easily, while still following imports within my target set only.

(A more general approach for dealing with slow type checking would be to make incremental checking not always type check all files that recursively import `a` in our example. This would be harder and wouldn't solve the problem if a large number of files directly import `a`.)

**Comment by gvanrossum** [comment]
The speed problem (when doing this repeatedly) is what `--incremental` is supposed to solve, and I think it solves it quite well as long as there isn't a huge cycle of modules in c that depends on a (because any change to a would force the whole cycle to be re-checked, and then everything that depends on the cycle).

**Comment by ilevkivskyi** [comment]
I don't think this is relevant anymore. We now have incremental mode on by default and following imports is now a per-file option.
