### ISSUE TITLE
Usage error when using --find-occurrences

### ISSUE THREAD

**Issue by JeroenSchmidt** [python/mypy#15527]
Hi All,
I am trying to use `--find-occurrences` but it looks like it might be broken. 
I could also be reading `--help` wrong; in that case it would help if there was clear documentation on how to use it - related https://github.com/python/mypy/pull/2042

**Commands tried:**
```sh
python -m mypy <path_to_project>/some_module.py --find-occurrences Example.ClassName
python -m mypy <path_to_project>/some_module.py --find-occurrences "(Example.ClassName)"
python -m mypy <path_to_project>/some_module.py --find-occurrences "(Example,ClassName)"
python -m mypy <path_to_project>/some_module.py --find-occurrences
```

**Output**
```
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/bkng-data-lineage2/lib/python3.10/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/user/miniconda3/envs/bkng-data-lineage2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/user/miniconda3/envs/bkng-data-lineage2/lib/python3.10/site-packages/mypy/__main__.py", line 37, in <module>
    console_entry()
  File "/Users/user/miniconda3/envs/bkng-data-lineage2/lib/python3.10/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 66, in main
  File "mypy/main.py", line 1335, in process_options
TypeError: tuple[str, str] or None object expected; got list
```

**Your Environment**

- Mypy version used: `mypy==1.4.1`, `mypy-extensions==1.0.0`, `pylsp-mypy==0.6.7`
- Mypy configuration options: None
- Python version used: 3.10

**Comment by hauntsaninja** [comment]
Oh interesting, I didn't know this was an option. Looks like it's documented as experimental. Anyway easy enough to fix...

**Comment by hauntsaninja** [comment]
As a workaround, you could probably install mypy without mypyc, e.g. via `pip install --no-binary mypy` (note: this version of mypy will be significantly slower than the usual one)

**Comment by JeroenSchmidt** [comment]
Thanks @hauntsaninja I'll try the work around. 
To anyone else reading this you need to run `pip install --no-binary mypy mypy`  - the command above doesn't work

**Comment by JeroenSchmidt** [comment]
@hauntsaninja it might be out of scope for this bug report but I noticed that ` --find-occurrences` silently does nothing if a `.mypy_cache` exists. The solution is to remove it before every time running ` --find-occurrences`.

**Comment by hauntsaninja** [comment]
A slightly more ergonomic workaround would be to pass `--no-incremental` to mypy. I'm not planning on fixing that, but you might be able to make a PR to fix? Likely just setting `options.incremental = False` in the right place would fix.

**Comment by JeroenSchmidt** [comment]
@hauntsaninja will do. Thank you for the help.
