### ISSUE TITLE
mypy not accepting recursive dictionary/union

### ISSUE THREAD

**Issue by jgarvin** [python/mypy#15538]
**Bug Report**

I've shrunk an error I'm experiencing down to the small reproducer below. mypy seems to be having trouble with dealing with a recursive dictionary when the recursion happens inside a union.

**To Reproduce**

[Playground link](https://mypy-play.net/?mypy=latest&python=3.11&gist=c8d222cfd0bb1ea3d5b289b547f435c4)

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from typing import Dict, List, Union, TypeAlias

Smap: TypeAlias = Dict[str, Union[str, "Smap", List["Smap"]]]

def foo(smaps: Union[List[Smap], Smap]):
    pass

smap = {
    "TEST_FOO" : [
        {
            "a" : "hello",
            "b" : "world"
        },
    ]
}

foo(smap)
```

**Expected Behavior**

Since `smap` at the top level is a dictionary when checking against the declared argument type of `smaps`, which is a `Union`, I expect `List[Smap]` to not match, so then I expect mypy to try matching against `Smap`, which has a `Dict` with `str` keys which matches the keys we see in the top level dict, then to see if the value type matches it should look at the types of the keys, of which there is only one, which is another dictionary. `Smap` has a `Union` value type but only one of the possible types in that union is `Dict` so I expect it to pick that one, and then recurse into `Smap`. Then within that dictionary we have strings to strings. `Smap` allows string keys, and one of the types in the union for values is also string, so all good.

**Actual Behavior**

```
main.py:20: error: Argument 1 to "foo" has incompatible type "dict[str, list[dict[str, str]]]"; expected "list[Smap] | Smap"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

Can reproduce on the playground which uses mypy 1.4.0 and python 3.11.

**Comment by hauntsaninja** [comment]
Dictionaries are invariant, so mypy is correct to report an error here. You can provide an explicit annotation like `smap: Smap = {...}` and that will fix the issue.
