### ISSUE TITLE
Mypy not inferring more than one chained condition to be not None

### ISSUE THREAD

**Issue by PashaWNN** [python/mypy#15535]
**Bug Report**

Mypy does infer the type cannot be None if it is checked within a condition statement. Although, the inferred type affect only the next condition in the same statement, while more conditions still produce an error.

**To Reproduce**

```python
class Foo:
    i: int = 6

x: Foo | None

...

if (
    True,
    x is not None,
    x.i > 5,
    x.i < 10,   # error: Item "None" of "Optional[str]" has no attribute "i"
    ):
    print("Yay!")

if (
    True,
    x is not None,
    10 > x.i > 5,  # Just fine
    ):
    print("Yay!")

```

**Expected Behavior**

When you do a conditional statement like `if a is not None and a.b and a.c and a.d`, it works well.

**Actual Behavior**

When you do a conditional statement like `if a is not None and a.b and a.c and a.d`, accessing `a.b` within statement is fine, but next occurences like `a.c` and `a.d` produce an error.

**Your Environment**

- Mypy version used: 0.961
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): 
```
[mypy]
python_version = 3.10
mypy_path = ./types_stubs/
ignore_missing_imports = True
warn_no_return = False
check_untyped_defs = True
warn_unused_ignores = True
disallow_untyped_defs = True
allow_redefinition = True
follow_imports = skip
exclude = env|venv|venv.*|migrations|tests|media
```
- Python version used: 3.10.10

**Comment by JelleZijlstra** [comment]
The errors in your code sample are correct: in code like `if (x is not None, x.i > 5)`, each member of the tuple is evaluated regardless of the value of the previous ones, so mypy is right to report if `x.i` may be None.

I also can't reproduce your claim "When you do a conditional statement like if a is not None and a.b and a.c and a.d, accessing a.b within statement is fine, but next occurences like a.c and a.d produce an error." Mypy produces no error on this self-contained sample:

```python
class A:
    b: str | None
    c: str | None
    d: str | None

def func(a: A | None) -> None:
    if a is not None and a.b and a.c and a.d:
        print(a.b)
        print(a.c)
        print(a.d)
```
