### ISSUE TITLE
function that returns decorator as class member raises "self-argument missing"

### ISSUE THREAD

**Issue by jacobszpz** [python/mypy#15549]
**Bug Report**

Similar to #7778, where having a function that returns a decorator inside a class without a self parameter
is not possible.

**To Reproduce**
I have this setup to be able to do this inside a class:
```
@log('hello world')
def method(self):
    ...
```

```python
from functools import wraps
from typing import Callable

class MyClass:
    def log(text: str):
        def log_decorator(func: Callable) -> Callable:
            @wraps(func)
            def log_wrapper(self):
                func(self)
                print(text) # Passed as param in log
            return log_wrapper
        return log_decorator


    @log('print this')
    def test(self) -> None:
        print('word')

foo = MyClass()
foo.test()

```

**Expected Behavior**
mypy should not find any errors with this.

**Actual Behavior**
```
mypy test_concept.py
test_concept.py:5: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: mypy 1.4.1 (compiled: yes)
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.0

**Comment by rafales** [comment]
This is not entirely valid code. `MyClass` now has an invalid `MyClass.log` method:

```python
m = MyClass()
m.log()  # error
```

**Comment by JelleZijlstra** [comment]
I'm going to say this is out of scope. This use case is very rare, and any reasonable solution is going to make it a lot harder for mypy to correctly report cases where the user forgot to add `self` (a common mistake).

**Comment by erictraut** [comment]
If you mark the method `log` as a `@staticmethod`, it will work fine at runtime and type check without errors.

**Comment by geipel** [comment]
> If you mark the method `log` as a `@staticmethod`, it will work fine at runtime and type check without errors.

That does run for more recent python, but not 3.8.10 (for example).
