### ISSUE TITLE
Mypyc TypedDict tests broken on master by typing_extensions 4.7.0

### ISSUE THREAD

**Issue by AlexWaygood** [python/mypy#15542]
Our mypyc TypedDict tests are failing on `master` due to the latest typing_extensions release. You can see in this run that the one job that used typing_extensions 4.7.0 failed, but all the others passed: https://github.com/python/mypy/actions/runs/5405782682

And on this PR, which is using 4.7.0 on all jobs, the mypyc TypedDict tests are failing on all jobs: #15541

Cc. @JelleZijlstra

**Comment by JelleZijlstra** [comment]
This is quite possibly broken on 3.7 only. When are we dropping 3.7 support?

**Comment by AlexWaygood** [comment]
> This is quite possibly broken on 3.7 only.

Yes, looks like that's probably the case!
