### ISSUE TITLE
Mypy cannot infer variable type in match case, when matching on more than one variable

### ISSUE THREAD

**Issue by K1T3K1** [python/mypy#15552]
Hi,
I discovered an issue about match case statement.
If I use match case and match against single variable, then variable's type is inferred correctly in instructions contained within case. But if we match against two or more variables, then mypy treats that variable as an union type

**To Reproduce**

If we have classes defined like this

```
class Parent:
# something something
class A(Parent):
  def __init__(self, arg: int):
    self.arg = arg
class B(Parent):
  def __init__(self, arg_with_other_name: int):
    self.not_A_arg = arg_with_other_name
```

and somewhere in code we use match case like this:
```
class WorkingClass:
  def method_of_working_class:
    match self.above_class_instance, self.some_funny_int:
       case A(), int():
          self.above_class_instance.arg = self.some_funny_int
```
we will get an Error like this:
```
error: Item "B" of "A | B" has no attribute "arg"  [union-attr]
                    self.above_class_instance.arg = self.some_funny_int
```
even though we matched against A()
if we matched like this
```
match self.above_class_instance:
  case A():
     self.above_class_instance.arg = 5
```
error doesnt appear

**Expected Behavior**
Error shouldn't appear. `above_class_instance` is known since we matched against it. It works if we match only against that single variable, it should work when we match against multiple variables

**Actual Behavior**
```
error: Item "B" of "A | B" has no attribute "arg"  [union-attr]
                    self.above_class_instance.arg = self.some_funny_int
```
union-attr error is propagated

**Your Environment**
- Mypy version used: 1.4.1
- Mypy command-line flags: c.run(f"mypy {' '.join(paths_to_lint)}", pty=True)
- Mypy configuration options from `mypy.ini` (and other config files):
- [tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_calls = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict = false
pretty = true
strict_equality = true
strict_optional = true
show_error_codes = true
show_error_context = true

- Python version used: 3.11.4

**Comment by sobolevn** [comment]
@K1T3K1 can you please update your code sample a bit, so I can actually run it? :)
Ideally a link to https://mypy-play.net/ would be an amazing addition. 

Right now I don't undestand what `self.above_class_instance` is, so I cannot help you.

**Comment by erictraut** [comment]
@K1T3K1, as @sobolevn said, it's difficult to follow your bug report above. Could you provide a minimal self-contained code sample that demonstrates the problem you're seeing?
