### ISSUE TITLE
Add setuptools as a dependency on Python 3.12?

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#15579]
Mypyc needs `distutils` or `setuptools` to run, but Python 3.12 no longer bundles `distutils` ([PEP 632](https://peps.python.org/pep-0632/)). This seems to imply that we need to include `setuptools` as a dependency of mypy (at least on Python 3.12 or later), or unbundle mypyc into a separate distribution on PyPI. Thoughts?

**Comment by eli-schwartz** [comment]
One possible alternative is to teach `mypyc` to emit the relevant sources without compiling them, so that people can integrate it into other build systems. :D

**Comment by hauntsaninja** [comment]
I think fine to include setuptools as a dependency. We could also have a mypyc extra that includes it, like we do for dmypy or reports.

**Comment by AlexWaygood** [comment]
> We could also have a mypyc extra that includes it, like we do for dmypy or reports.

I'd personally prefer this, but agree that having it as an unconditional dependency would also probably be fine

**Comment by nickdrozd** [comment]
I ran into this problem locally and in CI.
