### ISSUE TITLE
type checking evaluated strings?

### ISSUE THREAD

**Issue by eli-schwartz** [python/mypy#15581]
I don't know if this is possible, but if it was I think it would be pretty neat.
```python
import cProfile
import typing as T

variable: T.List[str] = []
print(f'{variable=}')

cProfile.runctx('variable = 1', globals(), locals()) # this is a silent error
print(f'{variable=}')

variable = None # this is a reported error
print(f'{variable=}')
```
cProfile is essentially exec(), and is likely done on a Literal string. Parsing it as source code instead of a blackbox function would be quite useful.

Example:
https://github.com/mesonbuild/meson/blob/77d4db533fabb3308074793d684f5a97727b707e/mesonbuild/msetup.py#L246-L251
```python
            if self.options.profile:
                fname = f'profile-{intr.backend.name}-backend.log'
                fname = os.path.join(self.build_dir, 'meson-logs', fname)
                profile.runctx('intr.backend.generate()', globals(), locals(), filename=fname)
            else:
                captured_compile_args = intr.backend.generate(capture, vslite_ctx)
```

(This code is actually flawed, the obvious way to fix it is to overwrite captured_compile_args as part of the exec'ed string, doing this cannot be typechecked the easy way although it is possible to do `runctx('saved = ...', ...); assert isinstance(saved, dict)` etc.)

**Comment by hauntsaninja** [comment]
I don't think mypy's going to implement this feature request. It would be complicated, unlikely to cover many use cases, and benefit is marginal.

Maybe you can set a norm of doing something like:
```
if TYPE_CHECKING: intr.backend.generate()
profile.runctx('intr.backend.generate()', globals(), locals(), filename=fname)
```
