### ISSUE TITLE
Tuple[..., fallback=T] isn't a subtype of T

### ISSUE THREAD

**Issue by rwbarton** [python/mypy#1558]
A program like this ought to type check, but doesn't:

``` py
from typing import NamedTuple

class A: pass
def f(x: A) -> None: pass

class B(NamedTuple('B', [('i', int)]), A): pass
f(B(1))  # E: Argument 1 to "f" has incompatible type "B"; expected "A"
```

(Fixing this wouldn't help with #1432 without adding the reverse subtyping relation as well, but it would fix #1485 as long as constraint inference is also updated accordingly.)

**Comment by elazarg** [comment]
There's no such error now. I think #2091 fixed this.

**Comment by ilevkivskyi** [comment]
Yes, it looks like this has been fixed.
