### ISSUE TITLE
Official EBNF Syntax Documentation

### ISSUE THREAD

**Issue by Varriount** [python/mypy#156]
Currently,  Mypy lacks any formal documentation specifying its alternate grammar. A document similar to the formal python grammar specification found at http://docs.python.org/3.4/reference/grammar.html should be constructed. 

Since this may be an ongoing thing,  edited by multiple people,  I have put up an initial copy of the python 3 grammar at https://gist.github.com/Varriount/5017660

If other reasoning is needed, having an ebnf file of the grammar means that we can use parser generators in the future instead of hard coded parsing.

**Comment by gvanrossum** [comment]
Let's close this, mypy's syntax is just Python's syntax. The form of types is specified by PEP 484.
