### ISSUE TITLE
NamedTuple no longer includes ellipsis for fields with default values

### ISSUE THREAD

**Issue by ericstarr** [python/mypy#15638]
**Bug Report**

In the past, stubgen would indicate NamedTuple fields with default values using an ellipsis. Now it does not indicate which fields have default values in any way. I don't know exactly what version I used to generate my old stubs, but it was about 2 years ago.

**To Reproduce**

Run stubgen on a python file containing the following

```
from typing import NamedTuple

class Spam(NamedTuple):
    a: int
    b: int = 1
```

**Expected Behavior**

The generated stub should look like

```
from typing import NamedTuple

class Spam(NamedTuple):
    a: int
    b: int = ...
```

**Actual Behavior**

The generated stub looks like

```
from typing import NamedTuple

class Spam(NamedTuple):
    a: int
    b: int
```

**Your Environment**

- Mypy version used: 1.4.1
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.9

**Comment by sobolevn** [comment]
This was not specific for named tuples, it was a general logic for all class level assigns: https://github.com/python/mypy/blob/v0.750/mypy/stubgen.py#L981-L982

But, I agree that it makes the difference for named tuples:

```python
from typing import NamedTuple

class A:
    x: int = 1
class B(NamedTuple):
    x: int

A()
B()  # E: Missing positional argument "x" in call to "B"
```
