### ISSUE TITLE
Bump `PYTHON3_VERSION_MIN`

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#15665]
**Feature**

Right now mypy says:

```
» mypy mypy/stubgen.py --python-version=3.2
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: argument --python-version: Python 3.2 is not supported (must be 3.4 or higher)
```

But, it does not look correct, because `typeshed` does not support `3.4` (currently it supports `3.7+`).

So, how mypy can check `3.4`?

I think that we need to bump it:
1. `3.4` is long gone
2. We don't actually plan any features with this support in mind
3. `typshed` does not support it
4. Users that need it can stay on older versions

Source: https://github.com/python/mypy/blame/2ebd51e881490f4d20635cde92ef9e3edbbad68c/mypy/defaults.py#L15-L15C20

**Pitch**

Let's use `3.7` as the minimal supported version. (Ideas about it are welcome)

After we decide the version info to be minimal, I will send a PR with the change :)

**Comment by kkirsche** [comment]
I think this is a great suggestion. I think it would make sense to intend to support all current active versions (leeway for new releases) and the last end-of-life version of Python.

That allows mypy to move forward without carrying the baggage of legacy code.

That would align with the suggestion of 3.7 per:
https://devguide.python.org/versions/

**Comment by hauntsaninja** [comment]
Good spot! Yeah, I'd go with whatever the vendored version of typeshed supports, so 3.7 currently.
