### ISSUE TITLE
How to describe types for an Enum with attributes

### ISSUE THREAD

**Issue by dkfellows** [python/mypy#15705]
**Bug Report** (or maybe **Feature Request**; I'm not sure at this point)

If I have this:
```python
import enum

class E(enum.Enum):
   A = (1, 2, 3)
   B = (4, 5, 6)
   C = (7, 8, 9)
   def __init__(self, val, foo, bar):
       self.val = val
       self.foo = foo
       self.bar = bar
```

Then I can access, say, `E.A.foo` and get the value `2` back. This is how the `enum` package works, and is great for when enum members have properties of various kinds. (We use this in quite a lot of places in various places, such as [the `DataType` class in one of our projects](https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/interface/ds/data_type.py); this style is very very helpful.)

However, *I can't find a good way to write the type annotations for this.* In the above example, the `val`, `foo`, and `bar` fields ought to be `int`, and that's easy enough to do by annotating `__init__`, but `A`, `B` and `C` need to be of type `E` or all chaos breaks loose with typing the rest of the codebase, and it would be great to check that the values provided actually match the ones expected.

I've resorted to doing things like this:
```python
class E(enum.Enum):
   A = typing.cast('E', (1, 2, 3))
```
but that's *awful* and provides no sort of safety at all. I guess I could also do a wrapper around that, but it's still terrible.

Can we please have something not so bad? Ideal would be saying just this and not needing to describe anything further while still getting correct types for `A` and so on:

```python
class E(enum.Enum):
   A = (1, 2, 3)
   B = (4, 5, 6)
   C = (7, 8, 9)
   def __init__(self, val: int, foo: int, bar: int):
       self.val = val
       self.foo = foo
       self.bar = bar
```

My use of `cast` in the workaround feels really nasty; it's telling lies to get the truth elsewhere rather than revealing information to the type checker that it can't quite work out.

----

This is with Mypy 1.4.1, but I've seen it with several versions.

**Comment by erictraut** [comment]
Your last code sample (the one that you said is "ideal") seems to work fine with mypy. 

```python
class E(enum.Enum):
    A = (1, 2, 3)
    B = (4, 5, 6)
    C = (7, 8, 9)

    def __init__(self, val: int, foo: int, bar: int):
        self.val = val
        self.foo = foo
        self.bar = bar


reveal_type(E.A)  # Literal[E.A]
reveal_type(E.A.value)  # tuple[Literal[1], Literal[2], Literal[3]]
reveal_type(E.A.value[0])  # Literal[1]
reveal_type(E.A.foo)  # int
reveal_type(E.A.x) # Error: No attribute "x"
```

Is this behavior different from what you expect?

**Comment by dkfellows** [comment]
Oh, I see the problem!  It's that we're actually assigning to `_value_`, and that got removed from the example. (It might be complicated by some other tool that isn't as understanding.) I'll have to think about this a bit more.

Minor suggestion: It'd be glorious if an example of this sort of thing were added to the docs.
