### ISSUE TITLE
`TypeGuard` not working in `or` operator

### ISSUE THREAD

**Issue by trim21** [python/mypy#15709]
**Bug Report**
mypy can't narrow type with on `TypeGuard` and `or`

for example, `v: X|Y = ...`, `def is_x(v) -> TypeGuard[X]` and `is_x(v) or reveal_type(v)` got `X | Y` instead `Y`, this is wrong.

But `isinstance(v, X) or reveal_type(v)` got `Y`, and is correct.

**To Reproduce**

```python
from __future__ import annotations

from typing import Any

from typing_extensions import TypeGuard


class _NotSetType:
    ...


def is_undefined(v: Any) -> TypeGuard[_NotSetType]:
    return isinstance(v, _NotSetType)


files: _NotSetType | dict[str, int | None] = {}

assert is_undefined(files) or all(
    element is None or isinstance(element, int) for element in files.values()
), files

# same semantic, but pass mypy checking
assert isinstance(files, _NotSetType) or all(
    element is None or isinstance(element, int) for element in files.values()
), files

```

**Expected Behavior**

This script should pass mypy type checking.

**Actual Behavior**

```text
a.py:19: error: Item "_NotSetType" of "Union[_NotSetType, Dict[str, Optional[int]]]" has no attribute "values"  [union-attr]
```

**Your Environment**

- Mypy version used: mypy 1.4.1 (compiled: yes)
- Mypy command-line flags: no flag
- Mypy configuration options from `mypy.ini` (and other config files): below
- Python version used: Python 3.10.11

```toml
[tool.mypy]
python_version = '3.7'
ignore_missing_imports = true
namespace_packages = true
check_untyped_defs = true
disallow_untyped_defs = true
```

**Comment by erictraut** [comment]
Mypy is correct in emitting an error here. `TypeGuard` does not narrow types in the negative ("else") case, whereas the built-in type guard for `isinstance` does narrow in the negative case. If you're interested in understanding why `TypeGuard` has this limitation, refer to [PEP 647](https://peps.python.org/pep-0647/).

**Comment by trim21** [comment]
Thanks @erictraut
