### ISSUE TITLE
Type Narrowing / Identity Clause inside Generators

### ISSUE THREAD

**Issue by Kartstig** [python/mypy#15708]
**Bug Report**

mypy misses type narrowing / identity clause inside generators. I'm not sure if this is a nuance in Python behavior and generator syntax, or if it is actually an issue. I would love to understand why this happens though.

**To Reproduce**

```python
from typing import Any, Dict, Generator, Iterable, TypeAlias, Tuple, Union

DictValue: TypeAlias = Union[bool, str, int, float]
MaybeDictValue: TypeAlias = Union[DictValue, None]


def mandatory_fields(
    check_keys: Tuple[str] | Generator[str, None, None], product_entry: Dict[str, DictValue]
) -> Iterable[DictValue]:
    return (
        product_entry.get(key)
        for key in check_keys
        if product_entry.get(key) is not None
    )


def mandatory_fields2(
    check_keys: Tuple[str] | Generator[str, None, None], product_entry: Dict[str, DictValue]
) -> Iterable[DictValue]:
    for key in check_keys:
        entry = product_entry.get(key)
        if entry is not None:
            yield entry

```

**Expected Behavior**

Since there is an identity guard around `None`, I expect the return typing to *not* include `None`

**Actual Behavior**

This error occurs on `mandatory_fields`, but `mandatory_fields2` is fine.
```
test.py:11: error: Generator has incompatible item type "str | int | float | None"; expected "str | int | float"  [misc]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: mypy==1.4.1
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]
python_version = 3.11
check_untyped_defs = True
disallow_any_generics = True
ignore_missing_imports = True
implicit_reexport = False
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
warn_unreachable = True
warn_no_return = True
disable_error_code = var-annotated
```
- Python version used: 3.10, 3.11

**Comment by erictraut** [comment]
A type checker cannot assume that calling a function twice will produce the same value. You're calling `product_entry.get(key)` in two different places. If you call it only once and assign the result to a temporary variable, your code will type check without errors (and your code will run faster as a side benefit!).

```python
return (x for key in check_keys if (x := product_entry.get(key)) is not None)
```

**Comment by Kartstig** [comment]
@erictraut  Ah that makes sense. Thanks for the explanation!

I'm closing this, as it doesn't indicate a bug in mypy.
