### ISSUE TITLE
Documented stub workaround breaks when imported & found from follow imports

### ISSUE THREAD

**Issue by micimize** [python/mypy#15718]
The workaround for `Queue[T]` types documented in [Using types defined in stubs but not at runtime](https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime) results in an "invalid type" error, _unless_ it's defining module is defined on the command line.

```python
# define in foo.common.types
import multiprocessing
from typing import Generic
from typing import TYPE_CHECKING
from typing import TypeVar
from multiprocessing.queues import Queue as QueueClass

T = TypeVar("T")

if TYPE_CHECKING:
    MultiprocessingQueue = multiprocessing.Queue[T]
else:
    # Workaround for Queue subscripting jankiness (the stub is generic, but the runtime class is not).
    # https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime
    class MultiprocessingQueue(Generic[T], QueueClass):
        pass

# imported in bar.other.module
IndexedQueue = MultiprocessingQueue[Tuple[int, T]]
queue: IndexedQueue[str]
#! mypy bar/other/module.py
#! error: Variable "bar.other.module.IndexedQueue" is not valid as a type

#! mypy foo/common/types.py bar/other/module.py
#! ok
```

`TypeAlias` mitigates the issue but must be used at every new  sub-type definition and leads to #14315, which I think also only occurs when the defining module is not included on the command line

- Mypy version used: `mypy` `1.2.0, 1.3.0, 1.4.1` although have not tried every permutation of my workaround ideas on every version. 
- Mypy command-line flags: `mypy --show-absolute-path --config-file ./mypy.ini $mypy_targets`
- Python version used: 3.9.5

<details>

<summary>mypy.ini:</summary>

```ini
[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_optional = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
cache_fine_grained = True
show_error_codes = True
follow_imports = skip
```
</details>

**Comment by hauntsaninja** [comment]
Global `follow_imports = skip` is evil and almost certainly not what you want. The idea of having a common types module makes no sense with global `follow_imports = skip`

**Comment by micimize** [comment]
@hauntsaninja thanks for the info – looks like that's the culprit. Somehow I missed that that line had slipped into our config recently.

The errors I was getting had a "See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases" line in them – can't find the line may make sense to add a similar warning that warns against `follow_imports = skip`
