### ISSUE TITLE
Bugs in the identity AST transformer (`mypy.treetransform.TransformVisitor`)

### ISSUE THREAD

**Issue by bzoracler** [python/mypy#15730]
**Bug Report**

 1. `mypy.nodes.AssignmentStmt` doesn't preserve the `new_syntax` (PEP 526) attribute during the transform, causing `typing.TypedDict` classes to error after transformation.
    ```python
    # test.py
    from typing import TypedDict

    class A(TypedDict):
        a: int  # mypy: Invalid statement in TypedDict definition; expected "field_name: field_type" [misc]
    ```
 3. `mypy.treetransform.TransformVisitor.visit_overloaded_func_def` crashes when a `@property` is defined with a `@setter` in a class.
    ```python
    # test.py
    class B:
        @property
        def prop(self) -> int: return 0
        @prop.setter
        def prop(self, val: int) -> None: pass
    ```
    ```shell
    $ mypy test.py
    Traceback (most recent call last):
      ...
      File "mypy/nodes.py", line 586, in accept
      File "mypy/treetransform.py", line 248, in visit_overloaded_func_def
    AssertionError
    ```

**To Reproduce**
```python
# test.py
from typing import TypedDict

class A(TypedDict):
    a: int

class B:
    @property
    def prop(self) -> int: return 0
    @prop.setter
    def prop(self, val: int) -> None: pass
```
```python
# plugin.py
import mypy.nodes
import mypy.plugin
import mypy.treetransform

class Plugin(mypy.plugin.Plugin):
    def set_modules(self, modules: dict[str, mypy.nodes.MypyFile]) -> None:
        transformer = mypy.treetransform.TransformVisitor()
        # `class A(TypedDict)`
        modules["test"].defs[1] = transformer.stmt(modules["test"].defs[1])
        # `class B` (uncomment to reproduce crash)
        # modules["test"].defs[2] = transformer.stmt(modules["test"].defs[2])
        super().set_modules(modules)

def plugin(version: str) -> type[Plugin]:
    return Plugin
```

**Proposed fixes**

1. In [`mypy.treetransform.TransformVisitor.duplicate_assignment`](https://github.com/python/mypy/blob/383137baaf36876dcf935c2f5be053b6419097d0/mypy/treetransform.py#L317-L326)
   ```diff
    def duplicate_assignment(self, node: AssignmentStmt) -> AssignmentStmt:
        new = AssignmentStmt(
            self.expressions(node.lvalues),
            self.expr(node.rvalue),
            self.optional_type(node.unanalyzed_type),
   +        node.new_syntax,
        )
        new.line = node.line
        new.is_final_def = node.is_final_def
        new.type = self.optional_type(node.type)
        return new
   ```
2. In [`mypy.treetransform.TransformVisitor.visit_overloaded_func_def`](https://github.com/python/mypy/blob/383137baaf36876dcf935c2f5be053b6419097d0/mypy/treetransform.py#L241-L257)
   ```diff
    def visit_overloaded_func_def(self, node: OverloadedFuncDef) -> OverloadedFuncDef:
        items = [cast(OverloadPart, item.accept(self)) for item in node.items]
        for newitem, olditem in zip(items, node.items):
            newitem.line = olditem.line
        new = OverloadedFuncDef(items)
        new._fullname = node._fullname
        new_type = self.optional_type(node.type)
   -    assert isinstance(new_type, ProperType)
   +    assert isinstance(new_type, ProperType) or (new_type is None)
        new.type = new_type
        new.info = node.info
        new.is_static = node.is_static
        new.is_class = node.is_class
        new.is_property = node.is_property
        new.is_final = node.is_final
        if node.impl:
            new.impl = cast(OverloadPart, node.impl.accept(self))
        return new
   ```

**Your Environment**

- Mypy version used: `1.4.1`
- Python version used: `3.10`

**Comment by A5rocks** [comment]
Do you want to send those proposed fixes in as a PR? (I'm not a maintainer but they look fine: proposed fix 2 feels really iffy but iirc the policy about crash fixes is "as long as it works it's good!")

**Comment by bzoracler** [comment]
I had a second look at this - I'm not sure how to test this using mypy's existing test suite, and now I'm thinking maybe I'm using this class outside of mypy's intended use case. If I understand correctly,
 - mypy's [own use of `TreeTransform`](https://github.com/python/mypy/blob/14e7768c3bd8d1164e887ce3becba3459ebcfaa4/mypy/checker.py#L7133) is during the type checking phase, and by this time semantic analysis of typed dictionaries would have already been completed and overloaded function types would have already been populated. It looks like I'm calling `TransformVisitor` too early (in `set_modules`), before semantic analysis has finished, which goes against [the description given in `TransformVisitor.__doc__`](https://github.com/python/mypy/blob/14e7768c3bd8d1164e887ce3becba3459ebcfaa4/mypy/treetransform.py#L112).
 - The [test suite is set up such that the transform visitor is called after mypy has already run](https://github.com/python/mypy/blob/14e7768c3bd8d1164e887ce3becba3459ebcfaa4/mypy/test/testtransform.py#L54) (`mypy.build.build` is already called).

Closing this for now - I can work around this.
