### ISSUE TITLE
functools.partial weirdness

### ISSUE THREAD

**Issue by berdario** [python/mypy#1574]
Another weird error while using partial:

```
partial(dict, **{'foo': '1'})()['foo']
```

yields

```
 a.py:3: error: Invalid index type "str" for "dict"
```

Btw, this idiom might look weird, but it's just a workaround that I'm using until #704 will be fixed

**Comment by gvanrossum** [comment]
I think this is just due to the general lack of support for partial, so closing in favor of #1484.
