### ISSUE TITLE
'Module "typing" has no attribute "_SpecialGenericAlias"' and 'Module "typing" has no attribute "_TupleType"'

### ISSUE THREAD

**Issue by gorkaerana** [python/mypy#15791]
**Bug Report**
I find myself needing to type `typing.Dict`, `typing.List`, `typing.Set`, `typing.Tuple` themselves, as in:
```python
from typing import Dict, List, Set, Tuple, _SpecialGenericAlias, _TupleType

dict[type, _SpecialGenericAlias | _TupleType]: {
    dict: Dict,
    list: List,
    set: Set,
    tuple: Tuple
}
```

The above code chunk executes to succession in Python 3.10, since both `typing._SpecialGenericAlias` and `typing._TupleType` exist. Nonetheless, `mypy` returns 

```bash
error: Module "typing" has no attribute "_SpecialGenericAlias"  [attr-defined]
error: Module "typing" has no attribute "_TupleType"  [attr-defined]
```

It could be that I am trying to type annotate `typing.Dict`, `typing.List`, `typing.Set`, `typing.Tuple` themselves wrongly. If so, would somebody be so nice of redirecting me to relevant documentation? I have not been able to find anything more specific than what described above, and both `typing.TypeVar` and `typing.TypeAlias` do not seem to be helpful.

**To Reproduce**
Write below code chunk to a Python file and execute `mypy` on it. (Actually, only the first line is necessary to reproduce the issue.)

```python
from typing import Dict, List, Set, Tuple, _SpecialGenericAlias, _TupleType

dict[type, _SpecialGenericAlias | _TupleType]: {
    dict: Dict,
    list: List,
    set: Set,
    tuple: Tuple
}
```

**Expected Behavior**

I would assume it should throw no error since both [`typing._SpecialGenericAlias`](https://github.com/python/cpython/blob/3de42bbf8cf372b2e6a59bb505b1c2c1544018db/Lib/typing.py#L1552) and [`typing._TupleType`](https://github.com/python/cpython/blob/3de42bbf8cf372b2e6a59bb505b1c2c1544018db/Lib/typing.py#L1646) exist.

**Actual Behavior**

```bash
error: Module "typing" has no attribute "_SpecialGenericAlias"  [attr-defined]
error: Module "typing" has no attribute "_TupleType"  [attr-defined]
```

**Your Environment**

- Mypy version used: `1.4.0` and `1.4.1`.
- Mypy command-line flags: none.
- Mypy configuration options from `mypy.ini` (and other config files): within `pyproject.toml`
```toml
[tool.mypy]
ignore_missing_imports = true
exclude = ["venv*/", "build/"]
```
- Python version used: 3.10

**Comment by JelleZijlstra** [comment]
The internal representations of these types in `typing` are not part of any public API and mypy is right to raise an error. The type system does not support types for these special forms, so you should use `Any` or possibly a custom protocol.
