### ISSUE TITLE
[ENH] Create an option `--warn-never-instance` such that creation of instances of `Never` is treated as an error.

### ISSUE THREAD

**Issue by randolf-scholz** [python/mypy#15818]
## Feature

Originally, `NoReturn` was introduced to type hint functions that raise an Exception unconditionally. In python 3.11, the [`typing.Never`](https://docs.python.org/3/library/typing.html#typing.Never) was introduced as

> The [bottom type](https://en.wikipedia.org/wiki/Bottom_type), a type that has no members.

Since the type has no member, a warning should be produced whenever an instance of `Never` is created. To not disrupt the alternative usage, this may be first introduced as an optional flag.

## Pitch

So why is this useful? A notorious example is that current type hinting has issues to represent the idea of a sequence of strings, because `str` itself is a subtype of `Sequence[str]`, but typically in such applications we do not want bare strings. (cf. https://github.com/python/typing/issues/256).

Raising an error on creation of instances of `Never` allows us to circumvent this problem, at least for the case of function arguments ([mypy-play](https://mypy-play.net/?mypy=latest&python=3.11&gist=e832f144c498aa61f3e31825f8f5d7e7)):

```python
from typing import Never, overload, Sequence

@overload
def foo(x: str) -> Never:...
@overload
def foo(x: Sequence[str]) -> str: ...

def foo(x):
    return " ".join(x)
    
x = foo("abc")
y = foo(["abra", "cadabra"])
reveal_type(x)  # <nothing>
reveal_type(y)  # str
```

With the `--warn-never-instance`, `mypy` would flag `x = foo("abc")` with a message like 

> function foo retuned `Never`, idindicating illegal usage

## What to do about the original intention of `NoReturn`?

I am not sure, but here are some ideas spitballed, but this is possibly better to discuss in [python/typing](https://github.com/python/typing/issues), or typing/ideas. As long as the flag is optional at first, it shouldn't matter too much.

- One could attempt to make `NoReturn` and `Never` two separate things again
- `Never` could be made generic such that one specialize `Never[TypeError]`, `Never[ValueError]`, `Never[SystemExit]`, etc. (or, introduce such a construct, e.g. `Raises[TypeError]`)Then, if say `foo(args)` is annotated as `ValueError`, a type-checker could decide to not raise if the instance creation happened within the context of an appropriate `try`-`except`-block.

**Comment by JelleZijlstra** [comment]
This isn't what `Never` is for. I think you want python/typing#1043.

**Comment by randolf-scholz** [comment]
@JelleZijlstra It isn't what the original `NoReturn` is for. But again the documentation states that `Never` is 

> The [bottom type](https://en.wikipedia.org/wiki/Bottom_type), a type that has no members.

Creating instances of a type that has no members must therefore be an error. Calling a callable `Callable[..., X]` returns an instance of `X`. Consequently, calling a function of signature `Callable[..., Never]` must be an error.
