### ISSUE TITLE
Using a generic class with inherited types causes [arg-type] error

### ISSUE THREAD

**Issue by ivan-gj** [python/mypy#15812]
**Bug Report**

Seems like, if I declare a generic object that is bound to a parent object, all children should be able to go through the same functions, as it is respecting the hierarchy. Maybe I am missing something. 

**To Reproduce**

```python
from dataclasses import dataclass
from typing import Generic, TypeVar


@dataclass
class Parent:
    a: int = 1


@dataclass
class Child(Parent):
    b: str = "asdf"


ParentT = TypeVar("ParentT", bound=Parent)

@dataclass
class Thing(Generic[ParentT]):
    person: ParentT


def do_something(input: Thing[Parent]) -> Parent:
    return input.person

thing = Thing[Child](person=Child())

do_something(thing)
```

**Expected Behavior**

Everything should be OK, the `Thing[Child]` should have at least the same interface as `Thing[Person]`, if I am getting things correctly. 

**Actual Behavior**
```
test.py:27: error: Argument 1 to "do_something" has incompatible type "Thing[Child]"; expected "Thing[Parent]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Environment**

- Mypy version used: v1.4.1
- Mypy command-line flags: (none)
- Mypy configuration options from `mypy.ini` (and other config files): (none)
- Python version used: v3.10.11

**Comment by hauntsaninja** [comment]
Thing is invariant in its type parameter. Try `ParentT = TypeVar("ParentT", bound=Parent, covariant=True)`

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generic-types
