### ISSUE TITLE
Taking into account an existence of a class docstring

### ISSUE THREAD

**Issue by m-aciek** [python/mypy#15825]
**Feature**

Let mypy introspect docstring of a class and use the information about existence of it to type `self.__doc__` attribute accordingly. Currently mypy always type `self.__doc__` as `str | None`.

**Pitch**

From user's perspective it's unexpected that existence of a docstring on a class is not recognized by mypy.

https://mypy-play.net/?mypy=latest&python=3.12&gist=47992ef1982edc7020ac319f4b04ce1f

Use cases for code like above are reusing the docstring content for some other mean (in this particular case it's an error message).

I would be willing to try to file a PR for it, although I am not (yet) familiar with mypy source code, so it may take time.

**Comment by ikonst** [comment]
What if a class derived from `ThrottlingError` has no docstring?

**Comment by m-aciek** [comment]
Fair point, thank you. Could we limit the scope of "the mypy wisdom" for this case to the instance only?

**Comment by ikonst** [comment]
For `ThrottleError.__doc__`, it sounds reasonable (or `self.__doc__` if `ThrottleError` was decorated with @final), just not sure how useful.

**Comment by Andrej730** [comment]
There is also `-OO` that might break the code, not sure how popular it is though.
```
$ python -OO
Python 3.12.0 (main, Oct 10 2023, 20:10:02) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def foo():
...     """Hmm"""
... 
>>> foo.__doc__ is None
True
>>> 
```

I've met the similar issue in pyright https://github.com/microsoft/pyright/issues/8006 but after awhile now I think it's probably not worth it solving for a type checker since it would actually makes sense indeed only for `final` classes in non `-OO` environment, so the simplest solution is probably just to use `__doc__ or ""`. 

Good thing about this solution that it will also work for functions, and functions are instances of `FunctionType` so taking into account their doc-strings for a type checker would result in need for even more special cases since usually it's not possible that instance can override the attribute type.

**Comment by erictraut** [comment]
As I mentioned in the linked pyright issue, `__doc__` is a writable attribute of a class and a function. It can be set to `None` or a new `str` value any time after the class or function is defined. It doesn't matter if it's a `@final` class.

It might be reasonable for us to all agree that if a class or function has a docstring at the time it is defined, then `__doc__` becomes read-only on that class or function, but that would deviate from the runtime. It would also probably require some agreement within the typing community — and an update to the Python typing spec to clarify this behavior.

In the meantime, if your code relies on `__doc__` not being `None`, I recommend adding an `assert` to validate that assumption. This will tell type checkers (and any linters or human readers of your code) about the assumption you're making.

**Comment by AlexWaygood** [comment]
> It might be reasonable for us to all agree that if a class or function has a docstring at the time it is defined, then `__doc__` becomes read-only on that class or function, but that would deviate from the runtime. It would also probably require some agreement within the typing community — and an update to the Python typing spec to clarify this behavior.

(I would oppose such a change. It's common practice when writing decorators to copy over the `__doc__` from one function or class to another, and that seems pretty reasonable and idiomatic to me. Albeit, many authors of decorators do not realise that they're doing so, as they simply use `functools.wraps` or `functools.update_wrapper` from the standard library; these functions do it for you.)

I don't think there's anything to do here.
