### ISSUE TITLE
mypy-lang.org front page needs updating

### ISSUE THREAD

**Issue by gwk** [python/mypy#15842]
The front page of mypy-lang.org has not been updated in three months; the "What's New" section was last updated for 1.3. This used to be an easy way to keep abreast of progress. If it is too much trouble to update this then perhaps "What's New" should  be replaced with links to more authoritative sources such as PyPI and the GitHub tags page. Just a suggestion!

**Comment by hauntsaninja** [comment]
I see 1.5 in the What's New. It looks like svalentin updated this 5 hours ago in https://github.com/JukkaL/mypy-website/commit/afabc29d5c1bd614fa3ee1db3702c86faf20aee7

**Comment by gwk** [comment]
I see it now too. I must have been seeing a cached version as I double checked while writing the issue out.

**Comment by ilevkivskyi** [comment]
Btw @svalentin it looks like this line in the blog post has broken formatting
```
a2: A = { a, b}  # OK (previously an error)
```
it looks like both `**` are missing, but `a,` part is shown in bold.

**Comment by svalentin** [comment]
Ah yes, when we released 1.4 we forgot to update the website. When I released the 1.5 version I added both versions to the website.

**Comment by svalentin** [comment]
Let me see if I can edit the blog post

**Comment by svalentin** [comment]
Fixed the blog post to show `**a, **b`. I think it was a problem when converting markdown to html
