### ISSUE TITLE
dmypy on 1.4.1 not working for Python 3.7

### ISSUE THREAD

**Issue by ezragoss** [python/mypy#15854]
Tested on two different instances of Windows 10, Python 3.7 pip installs of `mypy` result in the following error upon running `dmypy start`:
```
Traceback (most recent call last):
  File "mypy\dmypy\client.py", line 275, in main
  File "mypy\dmypy\client.py", line 325, in do_start
  File "mypy\dmypy\client.py", line 351, in start_server
  File "mypy\dmypy_server.py", line 35, in <module>
    from mypy.suggestions import SuggestionEngine, SuggestionFailure
  File "mypy\suggestions.py", line 86, in <module>
    class PyAnnotateSignature(TypedDict):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

I understand that version 1.5 dropped support for 3.7 but I would expect the versions prior to at least run. Any advice for folks who are still tied to 3.7 in production contexts?

I can't test this on a mac or linux but if anyone can confirm this is windows specific just let me know and I'll add more specificity to the title.

**Comment by AlexWaygood** [comment]
You'll need to pin `typing_extensions` to `<4.7.0` if you want dmypy to work with Python 3.7 and mypy 1.4.1.
