### ISSUE TITLE
Make it possible to run mypy-checked scrits in pre-3.5 Python without installing mypy

### ISSUE THREAD

**Issue by vadimcn** [python/mypy#1589]
While it is possible to put type annotations in comments, the script still needs to import types from the `typing` module.  This creates a dependency on mypy (except in Python 3.5+, of course) even though it isn't needed at runtime.
It would be nice if this import statement could also go into comments, e.g. `# mypy: from typing import Dict, List, Any`.

**Comment by gvanrossum** [comment]
We've considered this several times but each time we found that just putting imports in comments isn't enough -- there are many other things that you'd have to support (e.g. defining type variables, type aliases) and defining generic classes would still require the typing module (you can't very well put an entire class in a comment).

You don't need to install mypy though -- only the typing module: `pip install typing`.
