### ISSUE TITLE
Add support for tuples on except clauses

### ISSUE THREAD

**Issue by thiago-silva** [python/mypy#1590]
Mypy currently doesn't seem to like tuples of exception classes in `except` clauses.

Code:

```python
exs = (TypeError, IndexError, NameError)
try:
    [][1]
except exs as e:
    print(e)
```
Mypy Error:

```bash
test3/foo.py:4: error: Exception type must be derived from BaseException
```

**Comment by gvanrossum** [comment]
That should be a fairly straightforward addition. Do you think you're up to submitting a PR for this?

**Comment by thiago-silva** [comment]
Yep, I might give it a shot.

**Comment by pdmccormick** [comment]
I'm here in the sprint room and will be taking a look into this (I am `pdmccormick` on IRC `#python-mypy` .)

**Comment by pdmccormick** [comment]
I have corrected the behaviour regarding nested tuples and fixed the CI issue.

**Comment by pdmccormick** [comment]
This is being reworked to clean things up and build a union type (instead of a join.)
