### ISSUE TITLE
Enable --new-type-inference by default

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#15906]
I think we should be able to do this in mypy 1.7.0. After enabling this by default, new inference scheme will still be used as a fallback. And we can make it the main mechanism later on.

This is a follow-up for series started by https://github.com/python/mypy/pull/15287

**Comment by ilevkivskyi** [comment]
cc @JukkaL

**Comment by bukzor-sentryio** [comment]
Is there any way for me, as a plain-old user, to opt-in ahead of time? I see a commandline option, but didn't find anything in [the configuration reference](https://mypy.readthedocs.io/en/stable/config_file.html).

**Comment by ilevkivskyi** [comment]
I am not 100% sure, but you can try `new_type_inference = true` in the main section of config file. This flag is not supported for per-module configuration. But also I am going to make it default in master this or next week (and it will be released in 1.7.0).
