### ISSUE TITLE
Incompatible type reported for (supposedly valid) self-referential type

### ISSUE THREAD

**Issue by pfaion** [python/mypy#15901]
Hi everyone, thanks for creating and maintaining mypy! It's an awesome tool that I use a lot!

I think I found a potential issue with self-referential types, where mypy raises an error for a usage of that type that (I think) should be a valid use case. Please see the attached code. 

**To Reproduce**

[Playground link](https://mypy-play.net/?mypy=latest&python=3.11&gist=bffc6d307fe71c372d841dd314b44300)

```python
from typing import List, Union

FooType = Union[List["FooType"], None]

# works
valid: FooType = [[None]]

# works
valid_nested_FooType: FooType = [[valid]]

# this errors, but I think it shouldn't?
# note that adding FooType to data fixes the issue
data = [[None]]
valid_nested_data: FooType = [[data]]
```

I used double-nested lists everywhere to make sure that this is not just a simple issue with the self-referential type. Since double-nested lists work, mypy seems to correctly handle the self-reference in `FooType`.

**Expected Behavior**

I think mypy knows the type of `data` and should infer that it is compatible with `FooType`.

**Actual Behavior**

mypy shows this error:
```
List item 0 has incompatible type "list[list[None]]"; expected "list[FooType] | None"  [list-item]
```

**Your Environment**

The playground environment seems to be different, but I also got this in a local environment, with slightly different error message. Here are my local settings:

- Mypy version used: mypy 1.4.1 (compiled: yes)
- Mypy command-line flags: None
- Mypy configuration options from `pyproject.toml`
```toml
[tool.mypy]
ignore_missing_imports = true
python_version = "3.8"
```
- Python version used: Python 3.8.13

I just put the code in a file `tmp.py` and invoke mypy on that. This is the error on my local version:
```
❯ mypy tmp.py   
tmp.py:14: error: List item 0 has incompatible type "List[List[None]]"; expected "Optional[List[FooType]]"  [list-item]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by AlexWaygood** [comment]
This is because `list` is invariant. You don't provide an explicit annotation for `data`, so mypy does the best it can and infers the type as being `List[List[None]]`. Because `list` is invariant, `List[List[None]]` is not a subtype of `FooType`, so mypy correctly reports an error when you try to "implicitly upcast" `data` to `FooType`

https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance

https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generics

**Comment by AlexWaygood** [comment]
As you've already figured out, you can fix this by using an explicit annotation for `data`. You could also fix it by using a covariant container for `FooType` rather than `list`, e.g.

```python
from typing import Sequence, Union

FooType = Union[Sequence["FooType"], None]
data = [[None]]
valid_nested_data: FooType = [[data]]
```

https://mypy-play.net/?mypy=latest&python=3.11&gist=7649cf4141f1d998d94e2168462e2330

**Comment by pfaion** [comment]
Thanks for the great answer(s) and sorry for making unnecessary noise!

**Comment by AlexWaygood** [comment]
@pfaion no worries!
