### ISSUE TITLE
install library which uses `contextmanager` function treated as having no __enter__ or __exit__ method.

### ISSUE THREAD

**Issue by tacozMacleo** [python/mypy#15928]
**Bug Report**

When using the `contextmanager` in a library, mypy gives back an error:
```
"Iterator[None]" has no attribute "__enter__"; maybe "__iter__"?  [attr-defined]
```
**To Reproduce**
Make a library (let us call it my_lib) with:
```python
from contextlib import contextmanager
from typing import Iterator

@contextmanager
def talker() -> Iterator[None]:
    try:
        print("Starting...")
        yield
    finally:
        print("Ended.")
```
(and generate the stub with `stubgen`.)
Install the library, then import and use it like:

```python
from my_lib import talker

with talker():
    print('Hey!')
```
Then execute mypy on the file:

```bash
mypy test/test_mypy.py
```

**Expected Behavior**
No errors.
(Or at least the same amount of error as if it was not in a library.)

**Actual Behavior**
Mypy's output:
```
test/test_mypy.py:3: error: "Iterator[None]" has no attribute "__enter__"; maybe "__iter__"?  [attr-defined]
test/test_mypy.py:3: error: "Iterator[None]" has no attribute "__exit__"; maybe "__next__"?  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

Python 3.11
Mypy 1.5.1

CLI flags:
 * The default. (None set by user)
 * --strict --follow-imports=normal

**Comment by JelleZijlstra** [comment]
The bug here seems to be that stubgen doesn't generate the right stub. That's probably hard to fix as stubgen can't support arbitrary decorators. Mypy should work correctly if the stubs are correct (or if the library has py.typed so mypy looks at the runtime code).

**Comment by tacozMacleo** [comment]
Here are a repo with the test: [https://github.com/tacozMacleo/15928](Example Repo)

**Comment by JelleZijlstra** [comment]
That repo includes an incorrect stub file. If you have py.typed and inline annotations, you don't also need to generate stubs.

**Comment by tacozMacleo** [comment]
Oooh, the missing `@contextmanager`, I  did not think about checking that.
And did not know that the stubs was not need when having the `py.typed` file. :smile:
Thank.

I take it that it is a `Closed - Won't fix` then?!

**Comment by AlexWaygood** [comment]
> I take it that it is a `Closed - Won't fix` then?!

Yeah, I think so. As Jelle says, it would be pretty hard to add arbitrary decorator support to stubgen. But happily for your case, you don't even need stubgen, as you already have inline type annotations and a `py.typed` file :)
