### ISSUE TITLE
set[T] can't be passed to a function expecting set[T | U]

### ISSUE THREAD

**Issue by jgarvin** [python/mypy#15925]
It seems like this should obviously be allowed. Simple reproducer:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

def f(x: set[int | str]) -> None:
    return None

x = {1}
f(x)
```

`python3.11 -m mypy --strict test.py`

`test.py:8: error: Argument 1 to "f" has incompatible type "set[int]"; expected "set[int | str]"  [arg-type]`

- Mypy version used: 1.4.1
- Python version used: 3.11

**Comment by decorator-factory** [comment]
This is intentional because sets are _invariant_. This is what the function could do:
```py
def f(x: set[int | str]) -> None:
    x.add("hello")
```

https://mypy.readthedocs.io/en/stable/common_issues.html?highlight=invariant#invariance-vs-covariance
which would add a string to the set of integers.
