### ISSUE TITLE
Module 'typing_extensions' has no attribute 'Self'

### ISSUE THREAD

**Issue by gigabyterous** [python/mypy#15942]
**Bug Report**
`mypy` says that `Module 'typing_extensions' has no attribute 'Self'` even when installed in an environment with a version of `typing_extensions` that does have the attribute `Self`.

I am using `mypy==0.812` because of [this](https://mypy-lang.blogspot.com/2021/05/the-upcoming-switch-to-modular-typeshed.html).

**To Reproduce**
[mypy Playground](https://mypy-play.net/?mypy=0.812&python=3.8&gist=ca7a37380b1ec64602c270c92cf82c78)

or
```bash
python3.8 -m venv .venv
source .venv/bin/activate
pip install mypy==0.812
echo "from typing_extensions import Self" >> "tmp.py"
mypy tmp.py
```

**Actual Behavior**
```bash
<file-name.py> error: Module 'typing_extensions' has no attribute 'Self'
Found 1 error in 1 file (checked 1 source file)
```
**Your Environment**
- Mypy version used: 0.812
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8.16
- `pip list` output:
```bash
Package           Version
----------------- -------
mypy              0.812
mypy-extensions   0.4.4
pip               22.0.4
setuptools        56.0.0
typed-ast         1.4.3
typing_extensions 4.7.1
```

**Comment by gigabyterous** [comment]
OK, just found https://github.com/python/mypy/issues/12253, which seems to be the same issue. Is there any other solution other than "use `--custom-typeshed-dir` to point to an updated copy of typeshed"?

**Comment by AlexWaygood** [comment]
> Is there any other solution other than "use `--custom-typeshed-dir` to point to an updated copy of typeshed"?

No. We don't backport bugfixes to an older versions of mypy, I'm afraid, let alone versions as ancient as mypy 0.812. I recommend that you try to upgrade to an older version, though I do appreciate that the switch to a modular typeshed was a breaking change that makes that jump particularly difficult.
