### ISSUE TITLE
Strange error for overloaded get() method and Tuple key value

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1595]
This came up when I merged https://github.com/python/typeshed/pull/223.
I think I have a complete repo that doesn't depend on the stubs. Consider this:
```python
from typing import TypeVar, Generic, Tuple, overload

KT = TypeVar('KT')
VT = TypeVar('VT')

class A(Generic[KT, VT]):
    def get(self, arg: KT) -> VT:
        pass

a = A()  # type: A[Tuple[int, int], int]
a.get((0, 0))  # OK

class B(Generic[KT, VT]):
    @overload
    def get(self, arg: KT) -> VT:
        pass
    @overload
    def get(self, arg: KT, default: VT) -> VT:
        pass

b1 = B()  # type: B[int, int]
b1.get(0)  # OK
b2 = B()  # type: B[Tuple[int, int], int]
b2.get((0, 0))  # error here
```
I get an error on the very last line (`b2.get((0, 0)`):
```
x.py:24: error: No overload variant of "get" of "B" matches argument types [Tuple[builtins.int, builtins.int]]
```
But there's no error two lines above, on `b1.get(0)`. Also note that the same code with class A which does not overload `get()`) has no errors. I've got a feeling that there's a subtle bug in the handling of type variables that only shows up when a Tuple is matched against an overloaded method.

@rwbarton Any thoughts? Or @JukkaL ?

**Comment by JukkaL** [comment]
I looked at this and noticed that the `fallback` of tuple types are inconsistent. One of the tuple types it is `builtins.tuple[builtins.int]`, and the other it's just `builtins.tuple`. We should always have the first form. In addition, erasing tuple types was broken, as the fallback didn't get erased.
