### ISSUE TITLE
fcntl.ioctl() + strict equality bug

### ISSUE THREAD

**Issue by socketpair** [python/mypy#15956]
```python
from fcntl import ioctl

if ioctl(1, 2, b'qwe') == -1:
    print(42)
```

```
main.py:3: error: Non-overlapping equality check (left operand type: "bytes", right operand type: "Literal[-1]")  [comparison-overlap]
Found 1 error in 1 file (checked 1 source file)
```

https://docs.python.org/3/library/fcntl.html#fcntl.ioctl

![image](https://github.com/python/mypy/assets/1157412/f55e4850-75c8-41d8-916b-f0560ef16dba)

https://mypy-play.net/?mypy=master&python=3.11&flags=strict-equality&gist=7091f4483959422e5d023564c92c623a

**Comment by AlexWaygood** [comment]
This is a typeshed bug; please open an issue at https://github.com/python/typeshed/issues

**Comment by socketpair** [comment]
@AlexWaygood return type of the function depends on types of arguments. Is it still typeshed bug ?

**Comment by socketpair** [comment]
Seems, yes: https://github.com/python/typeshed/blob/main/stdlib/fcntl.pyi

**Comment by socketpair** [comment]
Sorry, that was a bug in my code. typeshed is OK.

**Comment by AlexWaygood** [comment]
Great!
