### ISSUE TITLE
Add "dummy import" to avoid cyclic import

### ISSUE THREAD

**Issue by JimChengLin** [python/mypy#1597]
If I simply want to import some classes to make proper type annotations, why should I deal with cyclic import issue? Cuz, the code involved is kind of "useless" i.e. deletion would not change anything.

So, I proposal that we can have a special mechanism, like `from a import A as A`.

Do you see the point? `import A as A`, which is totally meaningless. Anyone who has a brain would not do it and the interpreter will know this import is just for type annotations.

The change is fairly trivial.

**Comment by gvanrossum** [comment]
You can do this by using 'if False: import...'

**Comment by JimChengLin** [comment]
That is simpler. Maybe should put it into document.
