### ISSUE TITLE
Report error if self has explicit type

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#16]
For example, the following program should not be accepted:

```
class A:
    def f(self: Any): pass
```

**Comment by ashleyh** [comment]
@JukkaL: I can do this one.

**Comment by rwbarton** [comment]
Given the situation with #1586 I'm going to retag this as "needs discussion".

**Comment by gvanrossum** [comment]
I wonder if we could do something like this:
- If the first arg is named `self` we assume it's going to be called as an instance method (assuming there's no `@classmethod` or `@staticmethod`) and the type of self should be compatible with the class (whatever that means)
- If the first arg has another name, we're not sure; we allow any explicit type, but if there's no type we still assume it's an instance method (assuming the method is annotated at all)
- If the method is not annotated we assume nothing, except if `--check-untyped-defs` is used; then we use the same heuristic (whether the first arg is named `self`)

**Comment by elazarg** [comment]
I think we can close this issue.

**Comment by gvanrossum** [comment]
Whoops! Indeed.
