### ISSUE TITLE
INTERNAL ERROR -- Please try using mypy master on Github

### ISSUE THREAD

**Issue by deepika094** [python/mypy#16010]
Hi,
I am getting below error since yesterday-
models.py:281: error: INTERNAL ERROR -- Please try using mypy master on Github

I am using 0.812 version.
If i run with show traceback i get this-
 AttributeError: attribute 'mro' of 'TypeInfo' undefined

This was all working fine before. Any idea what could be the issue?
I tried to upgrade mypy versions earlier but i keep getting 'Library stubs' errors.

**Comment by hauntsaninja** [comment]
0.812 is an extremely old version of mypy. See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports for handling missing import errors
