### ISSUE TITLE
Incorrect type inference when NewType used with Any

### ISSUE THREAD

**Issue by Hnasar** [python/mypy#16021]
**Bug Report**

I created two NewTypes from a third party class which didn't have stubs. When using these NewTypes with a generic function, mypy infers the wrong result type, mixing up the two NewTypes.

**To Reproduce**

```python
from some_pkg import SomeCls

Right = NewType("Right", SomeCls)
Wrong = NewType("Wrong", SomeCls)
T = TypeVar("T", Right, Wrong)

def generic_fn(data_type: type[T]) -> T: ...
assert_type(generic_fn(Right), Right)  # error: Expression is of type "Wrong", not "Right"
```

https://mypy-play.net/?mypy=master&python=3.11&gist=adc223e9872d9a7cae12ada10634c014

**Expected Behavior**

Mypy should allow for NewTypes made from `Any` and treat them as separate types, like other NewTypes are. (pyright handles this correctly)

Since 3.11, mypy should treat [Any](https://docs.python.org/3/library/typing.html#typing.Any) as subclassable, and therefore usable with NewType. (Some past discussion here: https://github.com/python/mypy/issues/12840#issuecomment-1332682076) 

**Actual Behavior**

Mypy mixes up the NewTypes made from `Any`.

**Your Environment**

- Mypy version used: 1.2, 1.5.1, master
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.10, 3.11

**Non-solutions**
In https://github.com/python/mypy/issues/12757#issuecomment-1332663851 it was suggested to use NewType with object, but 

```Right = NewType("Right", cast(object, SomeCls))``` gives a `misc` mypy error, and also even if you do
```Right = NewType("Right", object)``` then although the generic typechecking will work, subsequent usages of the NewType instances lose all their attributes, when they should be usable like `Any`.

**Comment by erictraut** [comment]
@Hnasar, contrary to what you say above, pyright does not handle this case as you are hoping. Like mypy, pyright does not treat the types as distinct. When you derive a class from `Any`, many assumptions within a type checker no longer hold true.

If you want `Right` and `Wrong` to be treated as `Any`, you should avoid using the `NewType`. If you want them to be treated like distinct types (but not like `Any`), then you can use a pattern like this:

```python
if TYPE_CHECKING:
    Right = NewType("Right", object)
    Wrong = NewType("Wrong", object)
else:
    from some_pkg import SomeCls

    Right = NewType("Right", SomeCls)
    Wrong = NewType("Wrong", SomeCls)
```

I don't think there's a way to make them work both like distinct types and like `Any` at the same time.

**Comment by hauntsaninja** [comment]
Like Eric says, I'm not sure there's a way to something Any and distinct.

Maybe something like this could be a reasonable workaround for you? https://mypy-play.net/?mypy=latest&python=3.11&gist=e12cedd85e1d0ace0f287689961997f4
