### ISSUE TITLE
weird typeguard behavior in `inspect.getmembers` when `disallow-any-expr` is enabled

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#16025]
```py
import inspect

class Foo:
    pass


def foo(value: bool) -> None:
    for _, method in inspect.getmembers(
        Foo, predicate=lambda method: method in vars(Foo) # type:ignore[misc,arg-type]
    ):
        reveal_type(method)  # bool???
```
[playground](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-context%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-reexport%2Clocal-partial-types%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores%2Cno-implicit-optional&gist=8013db01d9cb0737901af142811130b0)

if i disable `disallow-any-expr`, the `arg-type` error goes away and the type of `method` changes from `bool` to `Any`

i don't think `disallow-any-expr` should change how types are inferred, or cause any new errors other than `Expression type contains "Any"`

**Comment by KotlinIsland** [comment]
I think #12729 would fix this

**Comment by KotlinIsland** [comment]
# Minified - (🐞) Incorrect overload matching with `TypeGuard` and `disallow-any-expr`
```py
# mypy: disallow_any_expr
from typing import overload, Any, TypeVar, Callable, TypeGuard

T = TypeVar("T")

@overload
def f(fn: Callable[[object], TypeGuard[T]]) -> T: ...
@overload
def f(fn: Callable[[Any], None]) -> object: ...
def f(fn: object = 1) -> object: ...

x = f(lambda _: None)
reveal_type(x)  # `None`j, with `allow_any_expr` we get `object`
```

**Comment by KotlinIsland** [comment]
- I've raised https://github.com/python/mypy/issues/16186 as a super issue of this issue

**Comment by DetachHead** [comment]
closing in favor of #16186
