### ISSUE TITLE
error when runing mypy in win10 with pythin files

### ISSUE THREAD

**Issue by akbzam** [python/mypy#16046]
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

```python
# Ideally, a small sample program that demonstrates the problem.
# Or even better, a reproducible playground link https://mypy-play.net/ (use the "Gist" button)
```

**Expected Behavior**

**Actual Behavior**

**Your Environment**

- Mypy version used:
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used:

hi
I use window 10 on my PC and Python 3.11.3
I saved my python files in D:\14020412_enteghal\akb_python\akb_py_projects
I wanted to use mypy with Python files. it took 3 days of my time and I had many arguement in https://python-forum.io/thread-40660-page-2.html

I wanted to run mypy by example1.py file but I could not. in the message that cmd was shown to me, it said that I report this bug, so I write here.
I must say if I create an env and then use mypy is okay.
below is what I saw in cmd:
Microsoft Windows [Version 10.0.19045.3324]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd/d D:\14020412_enteghal\akb_python\akb_py_projects

D:\14020412_enteghal\akb_python\akb_py_projects>mypy example1.py --show-traceback
D:\14020412_enteghal\akb_python\akb_py_projects\__init__.py: error: INTERNAL ERROR -- Please try us
tHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.5.1
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\akbar\AppData\Local\Programs\Python\Python311\Scripts\mypy.exe\__main__.py", line
    sys.exit(console_entry())
  File "mypy\build.py", line 2069, in wrap_context
  File "mypy\build.py", line 2176, in parse_file
  File "mypy\build.py", line 841, in parse_file
  File "mypy\parse.py", line 22, in parse
  File "mypy\fastparse.py", line 219, in parse
  File "mypy\fastparse.py", line 134, in ast3_parse
  File "C:\Users\akbar\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: source code string cannot contain null bytes
D:\14020412_enteghal\akb_python\akb_py_projects\__init__.py: : note: use --pdb to drop into pdb

D:\14020412_enteghal\akb_python\akb_py_projects>python
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by hauntsaninja** [comment]
mypy uses CPython's `ast.parse` to parse Python files. CPython's ast parser does not permit null bytes in the files it parses.

It's a little non-ideal that this raises a ValueError which mypy doesn't give a nice error for. But on Python 3.12 and newer, CPython raises a SyntaxError here.

I recommend removing the null bytes from your file.
