### ISSUE TITLE
Mypyc: Faster argument type-checking

### ISSUE THREAD

**Issue by nickdrozd** [python/mypy#16040]
**Feature**

**Faster compiled code** and also **less compiled code**, especially for union types.

**Pitch**

Mypyc executes runtime type-checks on function arguments. Here is an example of the C code that implements a check:

```c
    PyObject *arg_some_arg;
    if (PyLong_Check(obj_some_arg))
        arg_some_arg = obj_some_arg;
    else {
        arg_some_arg = NULL;
    }
    if (arg_some_arg != NULL) goto __LL1;
```

The jump at the end is the "good label", meaning that the check succeeded and the rest of the code can continue.

But this code is somewhat inefficient. If type-check function `PyLong_Check` succeeds, `arg_some_arg` gets the value `obj_some_arg`, and otherwise it gets `NULL`. Then `arg_some_arg` is unconditionally checked for `NULL`. But in the case that `PyLong_Check` has failed it will have just been explicitly set to `NULL`, so checking for `NULL` is extra work for nothing.

If I'm reading it right, this could be rewritten so that `NULL` is only checked when the type-check function succeeds:

```c
    PyObject *arg_some_arg = NULL;
    if (PyLong_Check(obj_some_arg)) {
        arg_some_arg = obj_some_arg;
        if (arg_some_arg != NULL) goto __LL1;
    }
```

The more types an argument can be, the more unnecessary `NULL` checks there will be. Consider an argument like `some_arg: int | str | float | list | dict`, for which Mypyc generates this type-checking code:

```c
    PyObject *arg_some_arg;
    if (PyLong_Check(obj_some_arg))
        arg_some_arg = obj_some_arg;
    else {
        arg_some_arg = NULL;
    }
    if (arg_some_arg != NULL) goto __LL1;
    if (PyUnicode_Check(obj_some_arg))
        arg_some_arg = obj_some_arg;
    else {
        arg_some_arg = NULL;
    }
    if (arg_some_arg != NULL) goto __LL1;
    if (CPyFloat_Check(obj_some_arg))
        arg_some_arg = obj_some_arg;
    else {
        arg_some_arg = NULL;
    }
    if (arg_some_arg != NULL) goto __LL1;
    if (PyList_Check(obj_some_arg))
        arg_some_arg = obj_some_arg;
    else {
        arg_some_arg = NULL;
    }
    if (arg_some_arg != NULL) goto __LL1;
    if (PyDict_Check(obj_some_arg))
        arg_some_arg = obj_some_arg;
    else {
        arg_some_arg = NULL;
    }
    if (arg_some_arg != NULL) goto __LL1;
```

The change I'm proposing here would result in faster compiled code and also less compiled code, and these benefits would more pronounced for union types.

(This is a small-scale optimization. I'm assuming that the type-checking code is mostly correct and necessary.)

**Comment by AlexWaygood** [comment]
This issue should probably be filed over at https://github.com/mypyc/mypyc/issues, which is a dedicated mypyc-specific issue tracker and the place where most mypyc feature development is discussed

**Comment by AlexWaygood** [comment]
closing in favour of https://github.com/mypyc/mypyc/issues/1012
