### ISSUE TITLE
Ternary expression of context managers is inferred as object

### ISSUE THREAD

**Issue by ringohoffman** [python/mypy#16055]
Related: #7738

A ternary expression of context managers is inferred as `object`, leading to an erroneous `attr-defined` errors about `object` not defining `__enter__` and `__exit__`.

**To Reproduce**

```python
class A:
    def __enter__(self) -> 'A':
        return self

    def __exit__(self, *args) -> None:
        pass

class B:
    def __enter__(self) -> 'B':
        return self

    def __exit__(self, *args) -> None:
        pass

def foo() -> bool:
    return True

a_or_b = A() if foo() else B()

reveal_type(a_or_b)  # Revealed type is "builtins.object"

with a_or_b:  # "object" has no attribute "__enter__" & "object" has no attribute "__exit__"
    ...

```

Gist URL: https://gist.github.com/mypy-play/8e363dcee24e9fab1c3abd89d1539635
Playground URL: https://mypy-play.net/?mypy=master&python=3.11&gist=8e363dcee24e9fab1c3abd89d1539635

**Expected Behavior**

I would expect that the type of "a_or_b" to be "A | B" and not raise an `attr-defined` error.

**Comment by erictraut** [comment]
This is because mypy uses a join operation rather than a union when unifying types. [Here](https://github.com/python/mypy/issues/12056) is the master bug for this issue, and you can search for all related issues using the [topic-join-v-union](https://github.com/python/mypy/labels/topic-join-v-union) tag.

**Comment by hauntsaninja** [comment]
Fixed in https://github.com/python/mypy/pull/17427
