### ISSUE TITLE
MyPy doesn't correctly bind typevar in callable

### ISSUE THREAD

**Issue by GRcharles** [python/mypy#16065]
**Bug Report**

 https://github.com/pola-rs/polars/issues/10929#event-10296764322

(A clear and concise description of what the bug is.)

**To Reproduce**

```python
# Ideally, a small sample program that demonstrates the problem.
from typing import TypeVar, Callable, overload

T = TypeVar("T")
R = TypeVar("R")


def pipe(x: T, f: Callable[[T], R]) -> R:
    return f(x)


def identity1(x: T) -> T:
    return x


y1: int = pipe(0, identity1)


@overload
def identity2(x: int) -> int:
    pass


@overload
def identity2(x: str) -> str:
    pass


def identity2(x: T) -> T:
    return x


y2: int = pipe(0, identity2)

# Or even better, a reproducible playground link https://mypy-play.net/ (use the "Gist" button)
```
https://mypy-play.net/?mypy=latest&python=3.11&gist=60bdf252ef60fcfe097a8409d377b9aa

**Expected Behavior**
identity1 and identity2 should have the same typing

**Actual Behavior**
identity1 without the overloads gives an error, wheras identity2 does not

main.py:15: error: Incompatible types in assignment (expression has type "T", variable has type "int")  [assignment]
main.py:15: error: Argument 2 to "pipe" has incompatible type "Callable[[T], T]"; expected "Callable[[int], T]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file

**Your Environment**
N/A, works in the playground

- Mypy version used:
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used:

**Comment by hauntsaninja** [comment]
Thanks for the report! This passes with the `--new-type-inference` flag (will become the default probably in mypy 1.7)
