### ISSUE TITLE
match/case doesn't perform overlapping equality checking

### ISSUE THREAD

**Issue by jgarvin** [python/mypy#16079]
Even with `--strict` this is accepted:

```
match 3:
    case "hello":
        pass
```

While this is rejected:

```
if 3 == "hello":
    pass
```

**Comment by socketpair** [comment]
Definitely not a bug. Because comparing patterns in match/case is not just comparing values. Pylint I think could say something about unreachability, but regarding types - MyPy is handling this case correctly.

**Comment by socketpair** [comment]
@JelleZijlstra close as "not a bug"

**Comment by JelleZijlstra** [comment]
I already removed the "bug" label :)

As the original report said, mypy warns you about `==` usages between two types with no overlap. It's a reasonable extension to also warn about `match` cases that do not overlap and therefore can never match.

**Comment by socketpair** [comment]
In principle... I agree. Okay.

**Comment by hauntsaninja** [comment]
mypy will complain about this with `--warn-unreachable`
