### ISSUE TITLE
The code `del func()` causes a syntax error

### ISSUE THREAD

**Issue by HongchengFan** [python/mypy#16091]
**Description**

When I code with `del func()`, mypy causes a syntax error.

Here is a minimal code snippet to reproduce the crash:
```
def x(t,a):
  pass
del x()
```

Print the code in the file.py and execute mypy file.py.

**The Actual Output**

```
folder_1/folder_3/cpython_89020_1093924769__5.py:3: error: cannot delete function call  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```

**The Expected Output**

Code execution won't be blocked and won't produce an errror prevented.

**Your Environment**

- Mypy version used:1.5.1
- Mypy command-line flags: mypy file.py --show-traceback
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9.0
- Operating system and version: Ubuntu 20.04.6 LTS

**Comment by AlexWaygood** [comment]
MyPy's behaviour is correct here. Your code fails with a syntax error at runtime.

> Here is a minimal code snippet to reproduce the crash:

This isn't a crash in mypy: mypy has detected the syntax error in your code, has informed you that it cannot reliably parse the rest of your code due to the syntax error, and has gracefully exited
