### ISSUE TITLE
Failing to account for types when using @attr and @dataclass decorators from lib attrs

### ISSUE THREAD

**Issue by gutogalego** [python/mypy#16118]
**Bug Report**

I'm running Mypy on pre-commit, it's giving me a `Unexpected keyword argument` error wrongfully. I suspect it's because of  `@attrs(auto_attribs=True, frozen=True)`  and `@dataclass(auto_attribs=True, frozen=True)`
![Screenshot 2023-09-15 at 11 22 15 AM](https://github.com/python/mypy/assets/31139680/1558f435-5c93-48b7-ad56-5a7fec2a687c)
![Screenshot 2023-09-15 at 11 32 53 AM](https://github.com/python/mypy/assets/31139680/df3b69c2-7cbf-4f63-b15a-84d66995053e)
![Screenshot 2023-09-15 at 11 33 03 AM](https://github.com/python/mypy/assets/31139680/37fa3202-e7f1-4309-98d8-495f77c174f2)

![Screenshot 2023-09-15 at 11 33 12 AM](https://github.com/python/mypy/assets/31139680/4448e8ec-b41a-4d3c-bb5f-0a0b5628b793)

might be relevante, I have created an alias for CustomError

```
from domain.lib.errors import (
    CustomError as DomainCustomError,
    ObjectType as DomainObjectType,
)
```

**To Reproduce**

```
from attr import dataclass, attrs

@dataclass(auto_attribs=True, frozen=True)
class CustomError:
    code: str
    message: str


@attrs(auto_attribs=True, frozen=True)
class SkuLineItemError(DomainCustomError):
    sku_line_item: str

SkuLineItemError(
    code="ErrorCode.VALIDATION_ERROR",
    message="message",
    sku_line_item="error_detail",
)
```

**Expected Behavior**

No errors

**Actual Behavior**

`Unexpected keyword argument`

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: ["--follow-imports", "skip", "--ignore-missing-imports"]
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9
- attrs==21.2.0

**Comment by ikonst** [comment]
I think you mean
```diff
-class SkuLineItemError(DomainCustomError):
+class SkuLineItemError(CustomError):
```

**Comment by ikonst** [comment]
Even with imports I couldn't reproduce the issue.

**Comment by JelleZijlstra** [comment]
> Mypy version used: 0.910

Please use the latest version. 0.910 is quite old by now.

**Comment by bugi14** [comment]
I have the same issue:

![image](https://github.com/python/mypy/assets/19555042/df7820c9-fdf0-41c9-ace3-6d2041515a8d)

![image](https://github.com/python/mypy/assets/19555042/a6b47a15-5f59-4f93-907b-7f4dbea383bb)

![image](https://github.com/python/mypy/assets/19555042/93c417ec-10a7-4cd4-b03a-0c7c512cd44d)

![image](https://github.com/python/mypy/assets/19555042/593b906d-4061-4c81-aa00-86a9a874608f)

![image](https://github.com/python/mypy/assets/19555042/596e1beb-d577-4f32-8263-0775a3bef008)
