### ISSUE TITLE
[Feature request] Fortran/ASN.1 syntax: contrained types

### ISSUE THREAD

**Issue by SamuelMarks** [python/mypy#16117]
**Feature**

Constrained types:

```py
# Normal integer
# Bring `MAX_INT` back or `2 ** (struct.Struct('i').size * 8 - 1) - 2`
C_Int = int[MIN_INT … MAX_INT]
# Normal floating pointer number
C_Float = float[MIN_FLOAT … MAX_FLOAT]
# Normal unsigned 64 bit integer
C_UInt64 = int[UINT64_MIN … UINT64_MAX]
# Positive signed; goes to MAX_INT
Pos = C_Int[0 …]
# Even integer number
PosEven = Pos[0, 2, 4, …]
# Odd integer number
PosOdd = Pos[1, 3, 5, …]
# Fibonacci sequence (ok maybe no need to go this far!!!)
Fib = uint[0, 1, 1, 2, 3, 5, 8, 13, …]
```

**Pitch**

In Fortran / ASN.1 and bunch of other languages (e.g., SQL) one can specify what range of numbers are permissible:

```
INTEGER(0..199)
```

Similarly for text:

```fortran
CHARACTER(LEN=20) :: word
```
```sql
VARCHAR(20)
```

Related work: https://docs.pydantic.dev/latest/usage/types/number_types/#constrained-types

It would be really handy when defining database column types in Python. It would also be handy when defining things in numpy / torch / tensorflow / jax; i.e., when types are being explicitly called of the `np.int32` style. I.e., this kind of code should work:
```py
# Pretend we don't need `INT16_MAX = np.iinfo(np.int16).max`
good_sized: int16 = INT16_MAX
# error
pretty_small: int8 = good_sized
```

Now obviously it won't work in all cases, but before runtime one should be able to trace quite a lot and figure out where incompatible types are being passed along.

Relationship between types could also be made, like the old C promotion hierarchy: https://en.cppreference.com/w/c/language/conversion#Integer_promotions

Anyway, I think a syntax like this could stop the whole `import world as np`; `import notnumpy as np` thing. Numpy was going to be part of CPython anyway!

**Comment by AlexWaygood** [comment]
Thanks for the feature proposal! This is a pretty similar idea to https://github.com/python/typing/issues/1304, so I suggest you join the discussion there :-)

In general, we discuss possible enhancements to the typing system over at https://github.com/python/typing/issues -- mypy generally only implements features that are part of draft or accepted typing PEPs :-)

**Comment by hauntsaninja** [comment]
Also note that mypy supports type checking mypyc's native integer types: https://mypyc.readthedocs.io/en/latest/using_type_annotations.html#native-integer-types

While these are designed for use with mypyc, they might work well for some use cases in interpreted programs too.

**Comment by SamuelMarks** [comment]
Thanks for the tips + link to other issue (I added to that other issue)
