### ISSUE TITLE
Add support for PEP 702 (`@deprecated`)

### ISSUE THREAD

**Issue by llucax** [python/mypy#16111]
**Feature**

Report where `@deprecated` symbols are used in the code.

**Pitch**

Python 3.12 is coming soon, and it introduces [PEP 702](https://peps.python.org/pep-0702/) (the `@deprecated` decorator).`mypy` should support it.

**Comment by hauntsaninja** [comment]
(Technically PEP 702 will not be in Python 3.12, the PEP has not been accepted. But yes, mypy should support the draft standard and its use via typing_extensions)

**Comment by Bendabir** [comment]
If some people are interested, I've wrotten a small plugin to support this until it's part of mypy directly : https://github.com/Bendabir/mypypp

I don't really know the internals so it's probably a bit hacky but it appears to work.

**Comment by hauntsaninja** [comment]
You could make a PR that incorporates this feedback: https://github.com/python/mypy/pull/17476#pullrequestreview-2161951407
