### ISSUE TITLE
Passed function argument name must match function parameters

### ISSUE THREAD

**Issue by jd-solanki** [python/mypy#16127]
Hi 👋🏻

> _I just started with ruff recently and I think ruff can implement a rule but later I thought this could be a candidate for mypy._

> **Note**
> Except issue title I might have interchanged the arguments & parameters

## Problem

ATM, if we pass arguments to function it's error prone:

```py
def greet(name: str, greeting: str):
    print(f'{greeting}, {name}')

name = 'john'
greeting = 'Hello'

greet(name, greeting) # Hello, john

# Issue 1: Passing arguments in the wrong order
greet(greeting, name) # john, Hello

# Issue 2: Have to be explicit
greet(name=name, greeting=greeting) # Hello, john
```

To avoid passing wrong arguments best way is to be explicit, but with three arguments code is less readable. For example here's FastAPI example:

```py
# Issue 1: Due to positional args we can pass wrong arguments
crud.create_user(db, user, fn_hash_pwd=hash.hash_pwd)

# Issue 2A: With keyword arguments we have to be explicit (more code) & less readable (one big line)
# Issue 2B: If we change single arg name or fn name, we get git diff for all arguments & function
crud.create_user(db=db, user=user, fn_hash_pwd=hash.hash_pwd)

# Issue 3: Perfect but more lines of code
crud.create_user(
    db=db,
    user=user,
    fn_hash_pwd=hash.hash_pwd
)
```

## Solution

We can implement a rule that checks passed argument must match the name of the function argument. If they don't match, we get an error.

```py
# Benefit 1: With this can be sure that we are passing arguments in the right order
# Benefit 2: Don't have to be explicit to avoid error
# Benefit 3: We can ensure function definition and function call are in sync
greet(name, greeting)

# If we pass arguments in the wrong order we get an error
greet(greeting, name) # Error: Passed argument name doesn't match function argument

# 
greet(user_name, greeting) # Error: Argument name doesn't match function argument
# Solution: greet(name=user_name, greeting=greeting)
```

With FastAPI example:

```py
# We are sure that db is the first argument and user is the second argument
crud.create_user(db, user, fn_hash_pwd=hash.hash_pwd)

# Even if author didn't provided the types, we can still catch the error
crud.create_user(user, db, fn_hash_pwd=hash.hash_pwd) # Error
```

We can catch more errors like if author of the function changes the name of the argument due to implementation changes with the same type.

```py
def greet(name: str, surname: str):
    print(f'Welcome {name} {surname}')

# With rule => We can catch this error and update our code
greet(name, greeting) # Error: Passed argument surname doesn't match function argument

# Without rule => We don't get any error and our code behaves unexpectedly
greet(name, greeting) # Welcome john Hello
```

**Comment by AlexWaygood** [comment]
Thanks for the feature request! Unfortunately, I think this is out of scope for mypy, which is a type checker rather than a linter — this kind of check would depend on slightly unreliable heuristics, whereas mypy generally tries to only produce errors if something is probably unsafe in some way.

However, note that you can sort-of already get something similar to what you're looking for by using `NewType`:

```py
from typing import NewType

Name = NewType("Name", str)
Greeting = NewType("Greeting", str)

def greet(name: Name, greeting: Greeting):
    print(f'{greeting}, {name}')

# at runtime these will still be strings,
# but the type checker treats `Name` and `Greeting` as distinct subtypes of `str`
name = Name('john')
greeting = Greeting('Hello')
surname = 'smith'

greet(name, greeting)  # passes
greet(greeting, name)  # errors
greet(name, surname)   # errors
```

https://mypy-play.net/?mypy=latest&python=3.11&gist=8608d57c0166828e4535e41a5d2b0fcb

**Comment by ikonst** [comment]
I think what OP actually wants is the JS property shorthand syntax but for Python kwargs.

**Comment by AlexWaygood** [comment]
> I think what OP actually wants is the JS property shorthand syntax but for Python kwargs. (That's a PEP, not a mypy feature.)

Sure. I wasn't trying to say what OP is trying to do is already possible; I was trying to offer an alternative way of tackling the problem that _is_ already possible :-)
