### ISSUE TITLE
stubtest: error for ABC class as default value

### ISSUE THREAD

**Issue by hamdanal** [python/mypy#16130]
**Bug Report**

stubtest reports an error if an ABC is set as a default value

**To Reproduce**

* file `t.py`:
```python
from abc import ABCMeta

class Base(metaclass=ABCMeta): ...
class Child(Base): ...

def f(x=Child) -> None: ...
```

* file `t.pyi`:
```python
from abc import ABCMeta

class Base(metaclass=ABCMeta): ...
class Child(Base): ...

def f(x: type[Base] = ...) -> None: ...
```

**Expected Behavior**

No error

**Actual Behavior**

```
error: t.f is inconsistent, runtime argument "x" has a default value of type abc.ABCMeta, which is incompatible with stub argument type Type[t.Base]
Stub: in file /tmp/t.pyi:6
def (x: Type[t.Base] =)
Runtime: in file /tmp/t.py:6
def (x=<class 't.Child'>) -> None
```

**Your Environment**

- Mypy version used: mypy 1.5.1 (compiled: yes)
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.10

**Comment by AlexWaygood** [comment]
Looks like this is probably another manifestation of #13316?

**Comment by hamdanal** [comment]
> Looks like this is probably another manifestation of #13316?

I swear I searched the tracker :P, don't know how I missed that.
