### ISSUE TITLE
Mypy not parsing .ini python_version correctly

### ISSUE THREAD

**Issue by kunalchandan** [python/mypy#16140]
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

`mypy.ini`
```ini
[mypy]
python_version = "2.7"
```
* I also tried changing to single quotes and version 3.7 inside the string.

`terminal`
```bash
$ mypy any_program.py 
mypy.ini: [mypy]: python_version: Invalid python version '"2.7"' (expected format: 'x.y')
```

Whereas when using an equivalent `pyproject.toml`
```toml
[tool.mypy]
python_version = "2.7"
```

`terminal`
```bash
$ mypy any_program.py 
```

**Expected Behavior**

Expect no error.

**Actual Behavior**

`terminal`
```bash
$ mypy any_program.py 
mypy.ini: [mypy]: python_version: Invalid python version '"2.7"' (expected format: 'x.y')
```

**Your Environment**
```bash
$ mypy --version
mypy 0.971 (compiled: yes)
$ python --version
Python 3.10.12
$ pip freeze
ignition-api-stubs==8.1.32
mypy==0.971
mypy-extensions==1.0.0
tomli==2.0.1
typed-ast==1.5.5
types-enum34==1.1.8
typing_extensions==4.8.0
```
Working inside a `venv` on WSL2.

Thank you for the amazing project, I love mypy <3

**Comment by JelleZijlstra** [comment]
I believe you need `python_version = 2.7`.
