### ISSUE TITLE
New type inference can't solve composition of generic functions

### ISSUE THREAD

**Issue by okhaliavka** [python/mypy#16145]
**Bug Report**
New type inference doesn't solve a pretty simple case of composition of generic functions:

```
# using pseudocode for brevity
rcompose :: (T -> T1) -> (T1 -> T2) -> (T -> T2)
wrap :: T -> Tuple[T]
unwrap :: Tuple[T] -> T

id_ = rcompose(wrap, unwrap)
reveal_type(id_)  # Revealed type is "def (Any) -> Any"
reveal_type(id_(1))  # Revealed type is "Any"
```

I considered this a feature request until I discovered that mypy correctly solves a more complex case involving `Concatenate` (see playground links below)

**To Reproduce**

Simpler, broken case: [playground link](https://mypy-play.net/?mypy=latest&python=3.11&flags=new-type-inference&gist=1b1ba11b6f02c4e29b93d60d04b764f3)

More complex case with `Concatenate` that works perfectly:  [playground link](https://mypy-play.net/?mypy=latest&python=3.11&flags=new-type-inference&gist=e2859b4f7c4c009385b4b15ab67a6d1f)

**Expected Behavior**

`reveal_type(id_(1))` should reveal `int`

**Actual Behavior**

`reveal_type(id_(1))` reveals `Any`

**Your Environment**

- Mypy version used: `1.5.1`
- Mypy command-line flags: `--new-type-inference`
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: `3.11`

**Comment by AlexWaygood** [comment]
@ilevkivskyi

**Comment by ilevkivskyi** [comment]
This is already fixed on master (try "mypy master branch" in the playground top menu).

**Comment by okhaliavka** [comment]
Nice. Thank you!
