### ISSUE TITLE
--exclude in CLI does not work at all

### ISSUE THREAD

**Issue by MichaelVoelkel** [python/mypy#16144]
Hi,

I think, problem is in front of the monitor, but I'm trying to use exclude but it does not work (macOS).

`python -m mypy --exclude '.*' myfile.py --check-untyped-defs --ignore-missing-imports`

I tried other wildcards, also not working.

It's `mypy 1.1.1 (compiled: no)` version (old Python, old Django, yeah, we cannot upgrade just now). But `--help` says exclude exists.

**Comment by hauntsaninja** [comment]
`--exclude` does not exclude files passed on the command line (nor does it affect mypy's import following). It's only use is preventing discovery of files.

https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-exclude

> Note that this flag only affects recursive directory tree discovery, that is, when mypy is discovering files within a directory tree or submodules of a package to check. If you pass a file or module explicitly it will still be checked. For instance, mypy --exclude '/setup.py$' but_still_check/setup.py.

> In particular, --exclude does not affect mypy’s [import following](https://mypy.readthedocs.io/en/stable/running_mypy.html#follow-imports). You can use a per-module [follow_imports](https://mypy.readthedocs.io/en/stable/config_file.html#confval-follow_imports) config option to additionally avoid mypy from following imports and checking code you do not wish to be checked.

**Comment by MichaelVoelkel** [comment]
Oh, so a classical `RTFM`. I'm sorry, I glimpsed and misread that, and found some misleading examples. All clear then!
Hm, seems simplest for many occasions to just `grep -v` my way

**Comment by hauntsaninja** [comment]
(off topic, but if you can use a compiled version of mypy and upgrade to 1.4.1 or newer, you'll find mypy to be probably an order of magnitude faster)

**Comment by MichaelVoelkel** [comment]
(I would like to but we are bound to Django 3.2 for now and django-stubs compatibility table does not seem to be happy with upgrading: https://pypi.org/project/django-stubs/
I went back the version history to find one where it says Django 3.2 is "really" supported and that led me to 1.1.1. Of course, any insides that go beyong a simple version compatibility table or allow me to still upgrade welcome!)

**Comment by hauntsaninja** [comment]
No insights into django-stubs, but it's possible you could use a compiled mypy 1.1.1

**Comment by MichaelVoelkel** [comment]
Hm, what does this mean? So I'm using the whl and would have assumed "python -m mypy" is potentially using a compiled version anyways? Or what am I missing?

**Comment by hauntsaninja** [comment]
mypy ships a pure Python wheel, but (for various architectures and Python versions) we also ship wheels for mypy that are compiled with mypyc. See https://pypi.org/project/mypy/#files. mypyc-compiled mypy is about 4x faster. You can check what you have using `python -m mypy --version`

**Comment by MichaelVoelkel** [comment]
UH, yes, not using compiled one. Very helpful insight, will switch for sure, thank you!
