### ISSUE TITLE
Overload signatures forgotten when bound method is assigned as object attribute

### ISSUE THREAD

**Issue by exoriente** [python/mypy#16150]
**Bug Report**

When assigning a bound method to an object as one of its attributes, `mypy` looses track of its overloads or narrows them down too much, losing valid overload signature options in the process.

**To Reproduce**

```python
from typing import Generic, TypeVar, overload


T = TypeVar("T")
S = TypeVar("S")


class Message(Generic[T]):
    @overload
    def send(self: Message[S | None]) -> None:
        ...

    @overload
    def send(self: Message[S], value: S) -> S:
        ...
    
    def send(self: Message[S], value: S | None = None) -> S | None:
        print(f"Sending {value}")
        return value


# int_message: Message[int]
# int_message.send(5)

# empty_message: Message[None]
# empty_message.send(None)
# empty_message.send()

# optional_message: Message[str | None]
# optional_message.send("spam")
# optional_message.send()


class Wrapper(Generic[T]):
    def __init__(self, message: Message[T]):
        self.send = message.send


wrapper: Wrapper[None]

wrapper.send()
```

https://mypy-play.net/?mypy=latest&python=3.11&gist=c5ce35c2951442c562d78ae28044d52a

Some explanation:

This example is a simplified and abstracted case we have in our company code. We have a `Message` with a generic type. It can be sent by the `send(value)` method. The overloads on the `Message.send` method allow us to use `send()` without arguments only if `None` is valid value for the type of `Message`.

`Wrapper` is a class that hides functionality and offers no access to the underlying message. It only exposes the `send` method of the wrapped `Message` object. It should behave in the same way. `Wrapper.send(` should expect a `value` argument, unless it wraps a `Message` that accepts `None` as send value. In that case `.send()` should also be fine.

**Expected Behavior**

I expect `mypy` to maintain its knowledge of the overloads of bound `send` method and apply is to when it's called via the `Wrapper` class.

**Actual Behavior**

`mypy` does not allow `send()` even for `Wrapper[None]`

```bash
main.py:41: error: Too few arguments  [call-arg]
```

**Your Environment**

Recreated in a `mypy` Playground with the following settings:

- Mypy version used: `latest (1.5.1)`
- Mypy command-line flags: `None`
- Mypy configuration options from `mypy.ini` (and other config files): `None`
- Python version used: `3.11`

**Comment by hauntsaninja** [comment]
mypy is actually correct. When type checking calls to overloads, type checkers only look at the overloads, not the implementation. The only reason your code appears to work is because of the default value for `value` in `send`, which isn't something that is captured by the overloads you've specified
