### ISSUE TITLE
No error when mutating ParamSpec `**kwargs`

### ISSUE THREAD

**Issue by kmurphy4** [python/mypy#16157]
**Bug Report**

Even though it fails at runtime, `mypy` doesn't complain if I mutate `ParamSpec.kwargs`.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=f5cea6637a9ea13c48b8ba75aa8d73dd

If I run this same code in an interpreter, I get
```python
Traceback (most recent call last):
  File "/tmp/repro.py", line 16, in <module>
    print(bar(foo))
  File "/tmp/repro.py", line 13, in bar
    return f(*args, **kwargs)
TypeError: foo() got an unexpected keyword argument 'ka'
```

**Expected Behavior**

I would expect this to trigger an error on line 12.

**Comment by huix11** [comment]
o

**Comment by AlexWaygood** [comment]
Note that previously people complained that they _couldn't_ mutate ParamSpec kwargs: https://github.com/python/mypy/issues/12386. I don't know that there's a foolproof way of catching all unsafe code here without emitting false positives on "safe" transformations of `ParamSpec.kwargs` objects.

**Comment by kmurphy4** [comment]
Yeah that makes sense -- the `::pop` use-case is pretty idiomatic.

It would be nice if an operation like `kwargs["ka"]` were able to return something with [`Concatenate[..., P]`](https://docs.python.org/3/library/typing.html#typing.Concatenate), but that seems tricky as well: we'd have to return a new object rather than mutate in-place (plus, I'm not sure it's even possible to `Concatenate` a kwarg...?).

In any case, I think I can work around this on my end.  Thanks for the response!

**Comment by AlexWaygood** [comment]
No worries! Not sure there's anything actionable here without changing the spec, so I'm closing this for now
