### ISSUE TITLE
Problems with Pydantic 

### ISSUE THREAD

**Issue by LukeSavefrogs** [python/mypy#16179]
## Problem
Pydantic works as expected, but only `mypy` checks fail.

- Python version: `3.10`
- Mypy version: `1.5.1`
- Pydantic version: `2.0.3`

Both the following code snippets show the same errors:
```python
import pydantic

class CustomModel(pydantic.BaseModel):                            # Name "pydantic.BaseModel" is not defined  [name-defined]
    """Base class for pydantic models."""
    prop1: str = pydantic.Field(alias="property1", frozen=True)   # Module has no attribute "Field"  [attr-defined]
```

```python
from pydantic import BaseModel, Field

class CustomModel(BaseModel):                            # Name "pydantic.BaseModel" is not defined  [name-defined]
    """Base class for pydantic models."""
    prop1: str = Field(alias="property1", frozen=True)   # Module has no attribute "Field"  [attr-defined]
```

I also have the `tools.mypy` configuration entry set:
```toml
[tools.mypy]
plugins = [
  "pydantic.mypy"
]
```

Tell me if you think this is a `pydantic` problem, so I'll open an issue there too.

**Comment by hauntsaninja** [comment]
I wasn't able to reproduce this

**Comment by LukeSavefrogs** [comment]
I don't know how, but I just checked and after a month things have fixed themselves... Maybe a temporary imcompatibility between `mypy` and `pydantic` caused this?
