### ISSUE TITLE
Mypy fails to extend the same semantics applied to standard typing classes to subclasses of those standard typing classes

### ISSUE THREAD

**Issue by tvdboom** [python/mypy#16172]
**Bug Report**

Mypy fails to extend the same semantics applied to standard typing classes to subclasses of those standard typing classes. If mypy accepts a function annotated by `typing.Literal[A, B]` for any valid literals `A` and `B`, then mypy should also accept the same function annotated by `YourLiteral[A, B]` for any subclass `YourLiteral(typing.Literal)`.

**To Reproduce**

Usecase: write a custom `Literal` class that is case-insensitive. I make use of the [beartype](https://github.com/beartype/beartype) library for this. The important thing to note here, is that my custom `CaseInsensitiveLiteral` class inherits the `typing.Literal` class.

```python
import typing
from beartype.typing import Annotated
from beartype.vale import Is

class CaseInsensitiveLiteral(typing.Literal):
    def __class_getitem__(cls, X: tuple[str]) -> Annotated[str, Is]:
        return Annotated[str, Is[lambda x: x.lower() in X]]
```
... but mypy complains, for example, when having a function like this

```python
def func(item: CaseInsensitiveLiteral["a", "b"] = "a"): ...
```

**Expected Behavior**

No error, like when using the `typing.Literal` class directly.

**Actual Behavior**

It raises error: `error: Incompatible default for argument "item" (default has type "str", argument has type "CaseInsensitiveLiteral")`. So mypy doesn't recognize my class `CaseInsensitiveLiteral` as a `str`, while this works for the original `typing.Literal`.

**Your Environment**

- Mypy version used: 1.5.1
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.11.2

**Comment by JelleZijlstra** [comment]
This is not supported; subclasses of Literal aren't part of the standard type system. Mypy is unlikely to gain support for such dynamic features.

**Comment by AlexWaygood** [comment]
Your code snippet also fails at runtime, FYI

```pycon
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing
>>> from beartype.typing import Annotated
>>> from beartype.vale import Is
>>> class CaseInsensitiveLiteral(typing.Literal):
...     def __class_getitem__(cls, X: tuple[str]) -> Annotated[str, Is]:
...         return Annotated[str, Is[lambda x: x.lower() in X]]
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python311\Lib\typing.py", line 456, in __mro_entries__
    raise TypeError(f"Cannot subclass {self!r}")
TypeError: Cannot subclass typing.Literal
```
