### ISSUE TITLE
Support `Traversable` in builtin `open` function

### ISSUE THREAD

**Issue by a-recknagel** [python/mypy#16194]
**Feature**

You can put a `Traversable`, which is e.g. returned by `importlib.resources.files`, in the `open` function and it will work:

```python
import importlib.resources

with open(importlib.resources.files("mypy") / "__init__.py") as f:
    print(f.read()) # prints: "# This page intentionally left blank"
```

But mypy complains about it:
```
foo.py:3: error: No overload variant of "open" matches argument type "Traversable"  [call-overload]
```

Or is there a reason why all the examples for `importlib.resources.files` use `traversable.open()` over `open(traversable)`?

**Comment by AlexWaygood** [comment]
This is a typeshed problem; please open an issue over at https://github.com/python/typeshed/issues. Thanks! :)
