### ISSUE TITLE
match/case (structural pattern matching) - can not guess type

### ISSUE THREAD

**Issue by socketpair** [python/mypy#16204]
```python
def fun(arg: str) -> None:
    print(arg)

match {"qwe": 42}:
    case {"qwe": int() as xxx}:
        pass
    case _:
        raise Exception('fail')

print(xxx)
```

MyPy latest (1.5.1) finds nothing wrong here. But type mistake is obvious here.

I tried to find something in issues about structural pattern matching, but did not find anything like this.

**Comment by erictraut** [comment]
I don't see any type violation in the code sample. Can you explain what behavior you expect to see from mypy in this case?

**Comment by socketpair** [comment]
Sorry, my mistake. Facepalm.

**Comment by socketpair** [comment]
Sorry, my mistake. Facepalm.

**Comment by socketpair** [comment]
Sorry, my mistake. Facepalm.
