### ISSUE TITLE
overloaded function loses its overloadedness when returned from a function

### ISSUE THREAD

**Issue by bwo** [python/mypy#16220]
**Bug Report**

If you define an overloaded function within another function, and return it, then it will be overloaded within the defining function's body, but not once returned.

**To Reproduce**

[mypy play link](https://mypy-play.net/?mypy=latest&python=3.11&gist=d6fca160a607bebe5b11556a36471891)

Note that it doesn't matter what order the overloads appear; mypy always seems to pick the same type for the function, which is (this is extra puzzling to me) not the type of the final, implementing function.

**Expected Behavior**

An overloaded function can be defined in one function and returned to another, or to the top level, while remaining overloaded.

**Actual Behavior**

`error: Too many arguments  [call-arg]`

**Your Environment**

you can see all this in the play link.

**Comment by ilevkivskyi** [comment]
This is not a bug, mypy simply uses the type you put in return annotation. You can use a callback protocol to give a more precise return type annotation.
