### ISSUE TITLE
Generic types are not narrowed based on attribute type checks

### ISSUE THREAD

**Issue by markedwards** [python/mypy#16222]
**Bug Report**

It appears that there is no narrowing of generic types based on type checks of their attributes.  Is this supported in some way, is it a bug, or is it not in the scope of python typing?

**To Reproduce**

```python
from typing import Generic, TypeVar

Bar_T = TypeVar("Bar_T", bound="Bar")


class Foo(Generic[Bar_T]):
    bar: Bar_T


class Bar:
    pass


class Baz(Bar):
    pass


class Bam(Bar):
    pass


def baz(foo: Foo[Baz]) -> None:
    pass


def bam(foo: Foo[Bam]) -> None:
    pass


def route(foo: Foo[Bar]) -> None:
    if isinstance(foo.bar, Baz):
        baz(foo)  # Argument 1 to "baz" has incompatible type "Foo[Bar]"; expected "Foo[Baz]"
    elif isinstance(foo.bar, Bam):
        bam(foo)  # Argument 1 to "bam" has incompatible type "Foo[Bar]"; expected "Foo[Bam]"
```

**Expected Behavior**

The `isinstance()` checks should narrow the type of `foo` so that there are no type errors.

**Actual Behavior**

Type errors, as indicated.

**Your Environment**

- Mypy version used: mypy 1.5.1 (compiled: no)
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files): strict = true, enable_error_code = "possibly-undefined"
- Python version used: 3.10.3

**Comment by erictraut** [comment]
Even if this type narrowing pattern were supported by mypy (which it's not), it wouldn't be safe to narrow `Foo[Bar]` to `Foo[Baz]` or `Foo[Bam]` in your example because the latter two types are not subtypes of `Foo[Bar]`. That's because `Bar_T` is marked as invariant, not covariant.

For narrowing behaviors like this that are not strictly type safe, PEP 647 can be used. Mypy supports this.

```python
def narrow_foo(foo: Foo[Bar], typ: type[Bar_T]) -> TypeGuard[Foo[Bar_T]]:
    return isinstance(foo.bar, typ)

def route(foo: Foo[Bar]) -> None:
    if narrow_foo(foo, Baz):
        baz(foo)
    elif narrow_foo(foo, Bam):
        bam(foo)
```

**Comment by markedwards** [comment]
Okay, thanks for the confirmation.
