### ISSUE TITLE
Pattern matching: case guards make match non-exhaustive

### ISSUE THREAD

**Issue by outring** [python/mypy#16223]
**Bug Report**

Looks like case guards make match non-exhaustive even when having wildcard case

**To Reproduce**

```python
def do_thing(s: str) -> str:
    match s:
        case str(x) if x == "something":
            return x
        case _:
            return ""
```

**Expected Behavior**

No error

**Actual Behavior**

```
error: Missing return statement  [return]
```

**Your Environment**

- Mypy version used: 1.5.1
- Mypy command-line flags: `--install-types --non-interactive`
- Mypy configuration options from `mypy.ini` (and other config files):
  ```
  [tool.mypy]
  python_version = "3.11"
  strict = true
  warn_unused_configs = true
  disallow_untyped_decorators = false
  ```
- Python version used: 3.11.4

**Comment by AlexWaygood** [comment]
Thanks for the bug report! This is already fixed on the master branch; it'll be included in an upcoming release. (I don't know if it will make 1.6 or not; I'm not sure exactly which commit fixed it. If not 1.6, it'll make it into mypy 1.7.)
