### ISSUE TITLE
Mypy and mypyc contributor online meetup: Tue Oct 17

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#16227]
**Update: Moved from Oct 10 to Oct 17**

We will be having our first mypy and mypyc contributor online meetup on **Tuesday October 17**, at 5pm UTC / 10am Pacific / 6pm UK time. It will be over Zoom. 

We will have 2 hours to discuss any topics related to mypy or mypyc development. We'll cover mypyc topics at the end (if time permits), so that anybody not interested in mypyc development can leave early.

Details:
* The meetup is open to all mypy, mypyc and typeshed contributors, and authors of typing PEPs.
* **Sign up by emailing me**. Find my email from the commit history. The Zoom link will be shared with everybody who's emailed me. (Signing up is optional for mypy maintainers -- I will send you the link if I have your email address.) This way I will have a general idea of how many people will join.
* Anybody can propose a topic for discussion (email me or leave a comment here). I'll share the list of topics here a day before the meetup. If there are too many topics, I will pick the ones that I think are the most interesting. You can also volunteer to give a short talk (up to 10 minutes), followed by a discussion. No need to prepare fancy slides or anything -- it will be informal.

Here are some initial discussion topics:
* Focus areas for mypy development
* Plans for low-level mypyc features
* Future mypy/mypyc (online) meetups

**Comment by JukkaL** [comment]
Moved to Oct 17, since Oct 10 overlaps with 2023 CPython Core Dev Sprint.

**Comment by KotlinIsland** [comment]
I'd like to talk about #15521

**Comment by JukkaL** [comment]
The meetup was a success, and we had many interesting discussions. Thank you everybody who were able to join! 

The consensus was that it would nice to have these meetups roughly twice a year, so the next meetup would be around April 2024.
