### ISSUE TITLE
Skip git-ignored files in test runner

### ISSUE THREAD

**Issue by gnprice** [python/mypy#1626]
Our test runner `runtests.py` finds files to run lint and other checks on by walking the whole filesystem under the `mypy/` tree, using `os.walk`, for any file with a `*.py` name.

This is too broad -- for example, @axitkhurana found that it caught up in its net Python files that his editor/IDE setup drops inside a config directory it creates -- which has a leading dot in its name and is ignored through `.git/info/exclude`, so it's doing all the right things to hide itself.

We should borrow a page from @timabbott's Zulip playbook (namely, https://github.com/zulip/zulip/blob/master/tools/lister.py ) and get our file list from `git ls-files` rather than `os.walk`.

**Comment by gvanrossum** [comment]
I like `git ls-files`, but I'm reluctant to tie our test runner to a specific VCS (even though we already have other dependencies on it -- I don't like those either). I don't know where that editor dropped files, but maybe runtests.py should limit itself to the mypy *subdirectory* (rather than the entire mypy repo)? There's not much elsewhere, or we could whitelist a few more subdirs.

**Comment by axitkhurana** [comment]
The editor creates hidden directories in each folder in which I edit python files. Would ignoring hidden folders (starting with .) or having a .mypyignore file be better?

**Comment by gvanrossum** [comment]
Hm... Hidden folders rarely contain the stuff you want to type-check (especially since they *can't* be package names). That sound right to me. And it would be a one-line diff:
```
diff --git a/mypy/test/testcheck.py b/mypy/test/testcheck.py
index 412693a..d215f54 100644
--- a/mypy/test/testcheck.py
+++ b/mypy/test/testcheck.py
@@ -159,6 +159,7 @@ class TypeCheckSuite(Suite):
     def find_module_files(self) -> Dict[str, str]:
         modules = {}
         for dn, dirs, files in os.walk(test_temp_dir):
+            dirs[:] = [d for d in dirs if not d.startswith('.')]
             dnparts = dn.split(os.sep)
             assert dnparts[0] == test_temp_dir
             del dnparts[0]
```

**Comment by gnprice** [comment]
Sounds like a fine plan. And it took me a minute to understand that example diff -- that's a useful `os.walk` feature I hadn't known about!

I think the code that needs to be changed for what was actually biting @axitkhurana is this in `runtests.py`:
```
def find_files(base: str, prefix: str = '', suffix: str = '') -> List[str]:
    return [join(root, f)
            for root, dirs, files in os.walk(base)
            for f in files
            if f.startswith(prefix) and f.endswith(suffix)]
```
but that will be a very similar change.

**Comment by gvanrossum** [comment]
@axitkhurana -- do you feel up to making this PR?

**Comment by ilevkivskyi** [comment]
git ignored files is probably not the best way to do this, also this complaint didn't appear for quite some time.
