### ISSUE TITLE
Improvements to "cheat sheet"

### ISSUE THREAD

**Issue by timabbott** [python/mypy#1627]
This issue is just to take notes on the things I think we should improve in the cheat sheet based on today's experiences:
- We should add an example with a docstring, since several folks asked about where to put annotations in functions that have docstrings
- We should document `reveal_type`
- We should add a bit more clarity about class methods (should be explicit they can ignore the "self")
- (we should fill in the TODOs)

**Comment by gvanrossum** [comment]
Check the latest version. a few of these were addressed already.

**Comment by timabbott** [comment]
Cool, yeah, I think all of these are done other than the TODOs (and maybe adding a comment to be explicit about the `self` issue).  A few more I got questions about are:
* A function that returns a tuple
* A generator
* How to annotate *args and **kwargs
* How to annotate a decorator
* Annotating a function that returns nothing (might want to add an earlier example)
* How to track down the type of an argument (Maybe worth describing in prose the workflow options of using `print type(x)`, looking at the caller, and discerning the type or using `reveal_type`)

It's likely that last bit should go in a separate but related guide with a title like "How to annotate your project", which could also discuss how you usually want to run mypy, using check-untyped-defs, discuss tooling like the Zulip lister.py setup, the coverage checking options available, etc., but I could see it going here since this page is kinda the docs for random users whereas the "How to annotate your project" seems like more the guide for a project maintainer.

**Comment by gvanrossum** [comment]
Also:

- A Python 3 version
- link to it from the other docs

--Guido (mobile)

**Comment by timabbott** [comment]
- Add something using bool (it's not currently referenced).

**Comment by gvanrossum** [comment]
I'm labeling this as difficulty/newcomer because newcomers can easily get started by adding *something* useful to the cheat sheet. I'm also adding difficulty/easy because there are several tasks here, some simpler than others. Folks, please don't close until everything here is done!

**Comment by nathanielksmith** [comment]
I propose merging the python 2 and 3 cheat sheets into a single document. Each topic header would have 2 and 3 examples, with additional examples added for further type syntax changes in python 3 point releases.

Having just audited a lot of the docs, I think it would be easier moving forward if there weren't copy and pasted swaths of examples across those two docs.

If others think this is wise, I can open a new issue (or consider it part of this issue).

**Comment by JelleZijlstra** [comment]
There is a tradeoff there between ease of maintenance (for people writing the docs, who'd rather not maintain two copies of almost the same docs) and ease of understanding (for people using the docs to learn mypy, who don't want to be distracted by irrelevant material). My assumption is that most people who are learning to use mypy are using either Python 2 or 3, not both at the same time, so they'd prefer to only see one syntax at a time. Given that this is an introductory cheatsheet, I think we should optimize for people reading the docs rather than for maintaining them, so I'd prefer to keep them separate.

**Comment by JukkaL** [comment]
I agree with @JelleZijlstra.

**Comment by nathanielksmith** [comment]
Totally reasonable. Nevermind :)

**Comment by gvanrossum** [comment]
So do you want to do the items that were mentioned earlier in this issue? I'd like to be able to actually close this (omnibus issues like this are a bit annoying because they're so open-ended :-).

**Comment by nathanielksmith** [comment]
I am happy to work on the other items. I checked the things mentioned in this against the current cheat sheet and can do these things for both 2 and 3:

- Explain "Need type annotation for variable" when initializing with None or an empty container
- Add TypeVar and a simple generic function
- A function that returns a tuple
- How to annotate a decorator
- How to track down the type of an argument (Maybe worth describing in prose the workflow options of using print type(x), looking at the caller, and discerning the type or using reveal_type)

**Comment by gvanrossum** [comment]
Go for it!

**Comment by hauntsaninja** [comment]
This has gotten pretty stale. Happy to look at docs improvement if people think the current cheat sheet can be improved
