### ISSUE TITLE
Specifying the type of class objects

### ISSUE THREAD

**Issue by suriya** [python/mypy#1628]
[PEP 484](https://www.python.org/dev/peps/pep-0484/#the-type-of-class-objects) mentions the ability to annotate a class object. However, the `Type` class mentioned in the PEP is not available in the `typing` module. I do not understand how to annotate a class object? Should I use `TypeVar`?

Appreciate your help and thank you all for your work on this project and Python.

**Comment by gvanrossum** [comment]
Sorry, `Type` will be out once Python 3.5.2 is released (next weekend). We'll update PyPI at the same time. Until then you can use `type` or `Any`.
