### ISSUE TITLE
Track parameter types in __init__ through the rest of the class

### ISSUE THREAD

**Issue by lovettchris** [python/mypy#16289]
**Feature**

Track the type info provided to an __init__ method in a subclass so that it can infer the correct type when a self.var reference is made later in the subclass.  For example this code fails mypy check:

```python
class Env:
    def __init__(self, name: str):
        self.name = name

class Experiment:
    def __init__(self, env: Env):
        self.env = env

class MyEnv(Env):
    def __init__(self, name: str):
        super().__init__(name)

    def my_method(self):
        print("my_method")

class MyExperiment(Experiment):
    def __init__(self, env: MyEnv):
        self.env = env

    def run(self):
        self.env.my_method()
```

Saying:
> error: "Env" has no attribute "my_method"  [attr-defined]

**Pitch**

Would be cool if it could remember that the `self.env` was initialized from a variable typed as `env: MyEnv` in this case.  I realize this kind of data flow analysis is probably hard to do, but it would be very useful and it would avoid having to do one of 2 cumbersome workarounds:

1. store and use another self.my_env variable that is typed as `env: MyEnv`
2. add `assert isinstance(self.env, MyEnv)` everywhere in my code that I want to use a `MyEnv` function.

**Comment by JelleZijlstra** [comment]
This would be unsound. An object of type `Experiment` has a writable attribute of type `Env`. That means that code that receives an object of type `Experiment` can set the attribute to an instance of `Env`. Inferring to be of type `MyEnv` on a subclass would break such code.

**Comment by lovettchris** [comment]
Fair enough, thanks for the answer.
