### ISSUE TITLE
Tuple of size zero do not parse

### ISSUE THREAD

**Issue by tharvik** [python/mypy#1629]
``` python
from typing import Tuple

a = tuple()  # type: Tuple[]
```

gives

```
asd.py:3: error: Parse error before ]
```

I encounter it will typing for [logging.handlers.SMTPHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.SMTPHandler). In `__init__`, the `secure` argument can be an empty `Tuple`.

**Comment by kirbyfan64** [comment]
FWIW this isn't valid syntax in Python, either. Maybe there should be some way to describe an empty tuple?

**Comment by gvanrossum** [comment]
I propose to make it possible to use Tuple[()].

--Guido (mobile)

**Comment by rwbarton** [comment]
Whatever syntax we choose here, we should also teach mypy to generate when displaying the type of an empty tuple (it currently displays `Tuple[]`).

**Comment by gvanrossum** [comment]
Using `# type: Tuple[()]` now works.

I actually looked into making the string displayed `Tuple[()]` but backed out because it looked ugly. But this makes me think we should just do this. It's easy.

**Comment by gvanrossum** [comment]
Hm, I think this can be closed now. The parser will never accept `Tuple[]`, the `repr()` at runtime of an empty `typing.Tuple` type is now `Tuple[()]`, and (having tried it) I don't want to change mypy's rendition of the empty tuple type, because it looks ugly.
