### ISSUE TITLE
Stubgen *.pyi not generated with "setter" 

### ISSUE THREAD

**Issue by anngokul** [python/mypy#16300]
I am having some class like 

```python
class MyClass:
    _proprty_a: int
    
    def __init__(self, a: int):
        self._proprty_a = a
    
    @property
    def property_a(self) -> int:
        return self._proprty_a

    @property_a.setter
    def property_a(self, property_a: int) -> None:
        self._proprty_a = property_a
```
On creating the stubgen pyi file, the setter is not available. 

If the implementing python code is having the 

```python
my_class = MyClass(10)
my_class.property_a = 19
```
Then mypy gives error as the property is read-only.
 error: Property "property_a " defined in "MyClass" is read-only  [misc]

**Expected Behavior**
Expected to have the setter in *.pyi 

**Actual Behavior**

On Creating stubgen for this, got the *.pyi with the following content
```python
class MyClass:
    def __init__(self, a: int) -> None: ...
    @property
    def property_a(self) -> int: ...
```

**Your Environment**

- Mypy version used: mypy 1.6.1 (compiled: yes)
- Python version used: 3.10.8

**Comment by hamdanal** [comment]
I just had the same issue.
This appears to be a regression in version 1.4 probably caused by #15232. I'll investigate and send a fix.
