### ISSUE TITLE
Enforcement of the name-starts-with-underscore-means-private convention

### ISSUE THREAD

**Issue by willhansen** [python/mypy#16314]
**Feature**

Title says it all.  There's an existing convention that if a method or member name starts with underscore, that means it should be treated like it's private.  Mypy could check that's not violated?

**Pitch**

New flag `--enforce-underscore-is-private`

**Comment by AlexWaygood** [comment]
This doesn't really have anything to do with type safety, which is mypy's primary domain. It also seems like a check that could easily be done by a flake8 plugin or pylint (there are probably already other linters that will do this for you). I don't think this really needs to be done by a type checker?

**Comment by erictraut** [comment]
I agree this falls in a gray area between type checkers and linters, so I can understand why this would be rejected by mypy maintainers.

FWIW, I chose to implement this feature in [pyright](https://microsoft.github.io/pyright/#/configuration?id=main-configuration-options). (It can be enabled with the `reportPrivateUsage` check.) Here's my justification for including it in a type checker: in most languages, this would be enforced by a type checker or compiler. Python doesn't support access control keywords like `private` or `protected`, so naming conventions are used instead.
