### ISSUE TITLE
no error when overriding method with different argument name

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#16328]
```py
from typing_extensions import override


class Foo:
    def asdf(self, value: int) -> None: ...


class Bar(Foo):
    @override
    def asdf(self, value2: int) -> None: ...


foo: Foo = Bar()

foo.asdf(value=1) # runtime error, no mypy error
```
[playground](https://mypy-play.net/?mypy=latest&python=3.11&enable-incomplete-feature=TypeVarTuple%2CUnpack&flags=strict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Clocal-partial-types%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=a5bc16a3a825c74ff0640aef18bfa6b6)

**Comment by tmke8** [comment]
Same as #6709 but with an explicit `@override` annotation.

As far as I know, the problem is that before Python 3.8, it wasn't possible to indicate a positional-only parameter, so mypy treats all parameters as positional-only which aren't keyword-only. When mypy drops support for Python 3.7 though, this can be made stricter.

**Comment by DetachHead** [comment]
closing as duplicate

**Comment by erictraut** [comment]
> it wasn't possible to indicate a positional-only parameter

Prior to [PEP 570](https://peps.python.org/pep-0570/) (which introduced an explicit syntax for positional parameters), it was a common practice to name positional-only parameters starting with a double underscore. Mypy supports this convention for versions of Python older than 3.8, so there's no need to wait for 3.7 support to be dropped.
