### ISSUE TITLE
Support pip's `--user` option when using `--install-types`

### ISSUE THREAD

**Issue by lsfischer** [python/mypy#16339]
**Feature**

Provide the alternative for `mypy` to pass `--user` down to `pip` when doing `mypy --install-types`.

**Pitch**

Mypy's `--install-types` will eventually call `python -m pip install <typing libraries>` to install missing type stubs. However there's cases where this installation fails due to permission denies. I understand a solution to this is to create a `venv` and run `mypy --install-types` under that `venv`, however I'm currently running into an issue with that workflow with `CircleCI's venv`

An example
```
+ mypy --check --install-types --non-interactive -p <redacted>
Installing missing stub packages:
/home/circleci/.pyenv/versions/3.8.18/bin/python3.8 -m pip install <typing libraries
...
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'LICENSE.txt'
Consider using the `--user` option or check the permissions.
```

For this particular issue the solution was to upgrade `pip`, however a more general feeling still stands: It could be interesting to have `mypy` support an option to pass in `--user` to `pip` for those who for some reason don't want or can't create a venv in which to run `mypy`.

If there's any interest in this let me know, I would also be happy to propose a solution :grin:

**Comment by hauntsaninja** [comment]
Closing as per https://github.com/python/mypy/pull/16606#issuecomment-2418748405
