### ISSUE TITLE
TypedDict incorrectly treated as class instead of dict when used as argument to Generic

### ISSUE THREAD

**Issue by lenzo202** [python/mypy#16360]
**Bug Report**
MyPy incorrectly treats a `TypedDict` as a normal class instead of a dict when used as an argument to `Generic` in the following sample.

**To Reproduce**

```python
from typing import TypeVar, TypedDict, Generic, Mapping, Sequence, Union, TypeAlias


JSON: TypeAlias = Union[Mapping[str, "JSON"] , Sequence["JSON"], str, int, float , bool , None]
T_JSON = TypeVar("T_JSON", bound=JSON)


class Base(Generic[T_JSON]):
    def func(self) -> T_JSON:
        raise NotImplementedError
    

SchemaAlias1: TypeAlias = dict[str, str | dict[str, int]]

class SubclassWorks0(Base[SchemaAlias1]):
    def func(self) -> SchemaAlias1:
        return {"name": "something", "data":{"val": 1}}

class SubclassWorks1(Base[SchemaAlias1]):
    def func(self) -> SchemaAlias1:
        return {"name": "something", "data":{"val": 3.1415}}


SchemaAlias2: TypeAlias = dict[str, object]


class SubclassWorks2(Base[SchemaAlias2]):
    def func(self) -> SchemaAlias2:
        return {"name": "something", "data":{"val": object()}}


class Schema(TypedDict):
    name: str
    data: dict[str, int]

# This also doesn't work  
# Schema =TypedDict("Schema", {"name": str, "data": dict[str, int]})

class SubclassInvalid(Base[Schema]):
    def func(self) -> Schema:
        return {"name": "something", "data":{"val": 1}}
```

**Expected Behavior**
I would expect no errors in the output of `mypy --strict .`  related to `SubClassInvalid`

**Actual Behavior**
Output of `mypy --strict .`

```
mypy --strict . 
recursive_types/main.py:21: error: Dict entry 0 has incompatible type "str": "float"; expected "str": "int"  [dict-item]
recursive_types/main.py:27: error: Type argument "dict[str, object]" of "Base" must be a subtype of "Mapping[str, JSON] | Sequence[JSON] | str | int | float | bool | None"  [type-var]
recursive_types/main.py:39: error: Type argument "Schema" of "Base" must be a subtype of "Mapping[str, JSON] | Sequence[JSON] | str | int | float | bool | None"  [type-var]
Found 3 errors in 1 file (checked 2 source files)
```
MyPy is fine with less precise type aliases.
- It correctly accepts `SubclassWorks0` as it is valid per `SchemaAlias0_1`. 
- It correctly flags the incompatible `float` in the return type in `SubclassWorks1.func` per `SchemaAlias0_1`. 
- It correctly flags the `SchemaAlias2` as an invalid argument to the `Base` in `SubclassWorks2` per the bounds of `T_JSON`.

I would expect to be able to use a more precise `TypedDict` in the same way I can use a `dict` type alias but MyPy flags this as an error saying the TypedDict must be a subtype of `JSON` even though `Mapping` is included in JSON.

**Your Environment**

- Mypy version used: mypy 1.6.1 (compiled: yes)
- Mypy command-line flags: --strict
- Mypy configuration options from `mypy.ini` (and other config files): strict=ture in pyproject.toml
- Python version used: Python 3.11.3
- Manjaro Linux
- vscode (same results from mypy plugin as with cli)

**Comment by erictraut** [comment]
Mypy is correct in rejecting this. `TypedDict` is a structural type, effectively a protocol. A value that is compatible with a `TypedDict` type is allowed to contain additional items beyond those defined in the `TypedDict`. That means a value that complies with the type `Schema` could have items with other keys beyond `name` and `data`. `Schema` is therefore a subtype of `Mapping[str, str | dict[str, int] | object]`. Note the addition of `object` here. The `object` subtype must be included to account for other items that may be present in the `TypedDict` value.

FWIW, [pyright emits the same errors](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgGoCGIANISQCYAiSAxjDQOLErEgs0Cy5BMnQ0AysQCOAVy7NiNAKookYFDSIJiAQQA2ScgGcAUKYBSYgPIA5AFy0teg4agBeKMtUoA2oOGo0b0MYaigAIgsbMIBdKHEpWRR5bwiraxiaYNDUNihgXTByfBoAIzAwXTioazViaOMCAH1I6zcHMkoACjCmlrDSsGkUOlcWgEpTY2ZdIxcAISNiTs5uXmZvXrTosdtjKH2oOmJgPKHmTsNiXWAxqABaAD5CZrTdg-eoEHIkS%2BqwGAAkthdMQIFwYMQ6ABREDgEB7A6mMTMAAWoPITiMAEZ7JodPojG06CwYEEQpkQlAAD6HElk7IoGDRepTGaGFxiaQlaazADquAA1oYAAydBaXbzItEQDEEwxY7ZvA5HE7AM4XK43e5PKXozHypUfT7EGDSEAoKAAbzCKHIYLC9jChkgJpRAX64ToRXIDutADdyLoHVAsQBfUOmHnsqCc7lswz8kBCrFixaS1F6uUKnYI-Yq05JDXXW6PGMZmX6nG5j4gE1mi3W232x3OsEwN3oD1hL0wH22f2B4MAZgAdFiACxYgCs4cmuorcoATLiSPqiXSsjQwCUAFbEVgs1mzGNcqMJwWGRepiXz2XOReK6v5tWFy7F7Vl6V3ozL6vvWumuaVo2naxDBk6Lrtu6NDdt6vphAGQb2Nue6sJ0YyzpG8afuinR4owJI5u8TbEPYWRPt69jEqw9I0DkLIAMSEG6LiBs6hxgMQhgoAA5PgADugr7MYTG3m4%2BFMGhYS3h6jagcGm6enBVEbuSmCMtEoYTEe0axmeAIoIhSB0NexDpl%2Bj7vM%2B6pvlqpa3oaNZ1kBcnNuErautBSm9vBiHBmGEZAA) as mypy.

Note that if you change the definition of `JSON` to include `object` in the union, this error no longer occurs.

Mypy's error message could arguably be clearer in this case.

You may be interested to learn that there is a draft [PEP 728](https://github.com/python/peps/pull/3441/files) in its early stages. The functionality proposed in this PEP would allow you to safely define `Schema` to indicate that it contain no additional items beyond what is specified. 

```python
class Schema(TypedDict):
    name: str
    data: dict[str, int]
    __extra__: Never
```

**Comment by lenzo202** [comment]
@erictraut thank for the the quick clarification. Is there somewhere I could join in the discussion and voice support for PEP 728. Happy to contribute if I can. It sounds like it's exactly what we need. 

Will close this bug as this behavior is actually expected with the current impl of TypedDict.
