### ISSUE TITLE
Cannot remove sql alchemy stubs - buried in mypy somewhere?

### ISSUE THREAD

**Issue by simon-norman** [python/mypy#16378]
**Bug Report**

We are using sql alchemy 2.0 and the latest mypy, but when running mypy to validate our code in our gitlab CI, mypy seems to think that one of the old sql alchemy stubs packages are installed. This results in either the following error if we include the sql alchemy plugin:

`Error importing plugin "sqlalchemy.ext.mypy.plugin": The SQLAlchemy mypy plugin in SQLAlchemy 2.0 does not work with sqlalchemy-stubs or sqlalchemy2-stubs installed, as well as with any other third party SQLAlchemy stubs.  Please uninstall all SQLAlchemy stubs packages.`

Or, if we remove that plugin (which is what we want to do), all the imports of, say, `mapped_column from sqlalchemy.orm` result in an import error, which given the above error with the plugin import suggests that some stubs are still present. 

When running `poetry remove` on either of the stubs packages right before the mypy check inside the virtual env, or even globally, it's reported that these packages aren't there. 

I've tried ignoring the mypy cache just in case, but no luck. 

I just wanted to check if there are any specific files within Mypy itself I might need to remove?

**Expected Behavior**

Mypy validates our code using the built-in sql alchemy 2.0 types.

**Actual Behavior**

Mypy uses stub files for sql alchemy, and therefore reports that module imports such as `mapped_column from sqlalchemy.orm` are wrong. 

**Your Environment**

- Mypy version used: 1.6.1
- Mypy command-line flags: --no-error-summary --config-file="${WORK_DIR}/app/shared-config/python/.mypy.ini"
- Mypy configuration options from `mypy.ini` (and other config files):
incremental = False
cache_dir = /dev/null
- Python version used: 3.11

**Comment by JelleZijlstra** [comment]
I don't think this is anything within mypy itself:

```
(py311) jelle@m2mb-jelle mypy % git grep -i sqlalchemy
(py311) jelle@m2mb-jelle mypy % 
```

**Comment by ilevkivskyi** [comment]
We do not (and I did not) vendor any sqlalchemy stubs with mypy.

**Comment by simon-norman** [comment]
OK thanks guys
