### ISSUE TITLE
Support expressing `(type[T]) -> T` but using `TypeVarTuple` and arbitrary number of `*types`

### ISSUE THREAD

**Issue by michaeloliverx** [python/mypy#16394]
Sorry for the title I didn't know how to explain it 😄 

**Feature**

I want to be able to express the following code
```python
from typing import TypeVar

T = TypeVar("T")


def get(svc_type: type[T]) -> T:
    ...
```

but using a `TypeVarTuple` instead of `TypeVar` to support an arbitrary number of *args:
```python
from typing import TypeVarTuple, Unpack

Ts = TypeVarTuple("Ts")


def get(*svc_types: Unpack[type[Ts]]) -> Unpack[T]:
    ...
```

Currently I don't think its possible to express passing an arbitrary number of types and returning instances.

**Pitch**

I want to be able to express this api:

```python
from typing import TypeVar, TypeVarTuple, Unpack, assert_type, overload

T = TypeVar("T")
Ts = TypeVarTuple("Ts")


@overload
def get(svc_type: type[T], /) -> T:
    ...


@overload
def get(*svc_types: Unpack[Ts]) -> tuple[Unpack[Ts]]:
    ...


def get(*svc_types: type) -> object:
    """
    Get services of *svc_types*.

    Instantiate them if necessary and register their cleanup.

    Returns:
            ``svc_types[0]`` | ``tuple[*svc_types]``: If one service is
            requested, it's returned directly. If multiple are requested, a
            tuple of services is returned.
    """
    ...


a = get(int)
assert_type(a, int)

a, b, c = get(int, str, bool)
assert_type(a, int)
assert_type(b, str)
assert_type(c, bool)
```

Gist URL: https://gist.github.com/mypy-play/dd8d60d46a5ddbec396a6e4e862641ab
Playground URL: https://mypy-play.net/?mypy=latest&python=3.11&enable-incomplete-feature=TypeVarTuple%2CUnpack&gist=dd8d60d46a5ddbec396a6e4e862641ab

**Comment by JelleZijlstra** [comment]
Agree. Closing as this needs a type system change, not a change in mypy only.
