### ISSUE TITLE
Mypy says "Cannot instantiate protocol class", but I can.

### ISSUE THREAD

**Issue by chrisimcevoy** [python/mypy#16390]
**Bug Report**

In CPython >= 3.11, creating an instance of a Protocol class is seemingly permitted at runtime if an initialiser is declared.

However, mypy still reports that the protocol class cannot be instantiated.

I am not sure if the bug lies with mypy or CPython, but, in this edge case, Protocol behaviour at runtime seems to have diverged from mypy's understanding somewhere between Python 3.10 and 3.11.

**To Reproduce**

```python
from typing import Protocol


class Spam(Protocol):

    def __init__(self):
        print("No TypeError here!")


s = Spam()
```

**Actual Behavior**

```
$ python spam.py 
No TypeError here!
$ mypy spam.py 
spam.py:10: error: Cannot instantiate protocol class "Spam"  [misc]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: `mypy 1.6.1 (compiled: yes)`
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.11.5

**Comment by erictraut** [comment]
[PEP 544](https://peps.python.org/pep-0544/#subtyping-relationships-with-other-types) (which introduced Protocols to the type system) is clear on this point:

> Protocols cannot be instantiated, so there are no values whose runtime type is a protocol.

So I think mypy is correct in reporting this error, at least according to the typing spec. Other type checkers like pyright report the same error here.

**Comment by hauntsaninja** [comment]
Yes, mypy is correct. For runtime behaviour, see (the last few comments of) https://github.com/python/cpython/issues/88970
