### ISSUE TITLE
MyPy does not coerce types correctly

### ISSUE THREAD

**Issue by noudin-ledger** [python/mypy#16396]
**Bug Report**

I was implementing a basic Abstract Syntax system and I encountered a miss in the coercion system of mypy.

**To Reproduce**

See : https://gist.github.com/mypy-play/8f1929869a588f8c4c19bdf800e5aa60 which raises

This code does not recognise variable `expr2` as `Expression` even though it's type `NegOperation` is a part of Union type `Expression`.

If I add the type hint of `Expression` to it, it types correctly : https://gist.github.com/mypy-play/e4c48148b5f112732d17b8fce3786227 .

**Expected Behavior**

mypy should be able to coerce the type NegOperation to Expression as it is part of the union type and the constraints enforce the type to be Expression.

**Actual Behavior**

```
$ mypy adt_compute_mwe.py
adt_compute_mwe.py:25: error: Incompatible types in assignment (expression has type "NegOperation | AddOperation | Value", variable has type "NegOperation")  [assignment]
```

**Your Environment**

- Mypy version used: 1.6.1 (also on 1.1.1
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.11.4 (also on 3.10.7)

**Comment by ilevkivskyi** [comment]
This works as expected. If you need help understanding how types work, there are some links in the README.
