### ISSUE TITLE
`typing.Self` does not work properly with class variables

### ISSUE THREAD

**Issue by McDic** [python/mypy#16410]
**Bug Report**

`typing.Self` does not work well with class variables.

**To Reproduce**

In Python 3.11, write and execute the same code from [here](https://github.com/python/typing/discussions/1502), which is

```python
import math
import typing


class Team:
    """
    Represent "team" in Minecraft.
    """

    _cache: dict[str, typing.Self] = {}

    def __init__(self, name: str):
        self._name = name
        if self._name in type(self)._cache:
            raise ValueError('Team "%s" already exists;' % (self._name,))
        else:
            type(self)._cache[self._name] = self

    @property
    def name(self):
        return self._name

    @classmethod
    def get_team(cls, name: str) -> typing.Self:
        """
        Use this method to create a team instead of calling constructor directly.
        """
        if name in cls._cache:
            return cls._cache[name]
        else:
            return cls(name)
```

**Expected Behavior**

There should be no error.

**Actual Behavior**

Mypy reports `Incompatible return value type (got "Team", expected "Self")` on `return cls._cache[name]`.

**Your Environment**

- Mypy version used: 1.1.6
- Mypy command-line flags: `mypy (filename)`
- Mypy configuration options from `mypy.ini` (and other config files): Nothing
- Python version used: 3.11.6

**Comment by cossor** [comment]
i think this is a minor issue, so i'm commenting only because i think we should minimize quoted string usage in type hints.

mypy 1.7.0 (Python 3.12) also emits a return-value complaint after checking a smaller example:
```
import typing


class Spam:
    @classmethod
    def instance(cls) -> typing.Self:
        return Eggs()


class Eggs(Spam):
    pass
```

in the first example, *cls* might not be Self so my example doesn't really change anything?
