### ISSUE TITLE
Reject more covariant overrides

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#16455]
Follow up to #3208. We should also reject things like:
```
from typing import TypeVar, Generic
T = TypeVar("T", covariant=True)
class Foo(Generic[T]):
    def __init__(self, value: T) -> None:
        self.foo = value
```

**Comment by ilevkivskyi** [comment]
Is this a duplicate of https://github.com/python/mypy/issues/735? In particular https://github.com/python/mypy/issues/735#issuecomment-1413401443
