### ISSUE TITLE
TypeVar with Generic class has incompatible type

### ISSUE THREAD

**Issue by gentlegiantJGC** [python/mypy#16459]
**Bug Report**

I have a TypeVar bound to a class.
I have a generic class based on the above TypeVar.
When a variable is typed using the generic type in the generic class it sometimes ignores the bound type and mypy raises an error that the typed variable is not an instance of the bound class.

**To Reproduce**

dict in __init__
https://mypy-play.net/?mypy=latest&python=3.11&gist=750696536094989d0c195622bed693cf

dict in a method
https://mypy-play.net/?mypy=latest&python=3.11&gist=17d1edd4dc8793e762037b9b50e43457

list in a method
https://mypy-play.net/?mypy=latest&python=3.11&gist=1c8c04a124c4a9d0603f6344951a6a5b

mapping in method
https://mypy-play.net/?mypy=latest&python=3.11&gist=e4f107003825f2b5e731ecfe7c4a8ed7

dict and mapping in method
https://mypy-play.net/?mypy=latest&python=3.11&gist=190dde68a41fd6407c37059a487b8aa8

**Expected Behavior**

I expect there not to be an error like in the following examples.

tuple in method
https://mypy-play.net/?mypy=latest&python=3.11&gist=7e7bd6bd458f4cde92e5575443158d5c

list+Sequence in method
https://mypy-play.net/?mypy=latest&python=3.11&gist=b46aa0b287a5c261fdb6dd13c93bb6b6

**Actual Behavior**

```
main.py:14: error: Argument 1 to "append" of "list" has incompatible type "dict[KeyT, Any]"; expected "dict[Key, Any]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

```
main.py:17: error: Argument 1 to "append" of "list" has incompatible type "dict[KeyT, Any]"; expected "dict[Key, Any]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.7
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.11

**Comment by ilevkivskyi** [comment]
This behavior is correct: list, dict, and mapping are invariant, while tuple and Sequence are covariant.
