### ISSUE TITLE
1.7.0: Cannot find implementation or library stub for module named "scribe"

### ISSUE THREAD

**Issue by mtelka** [python/mypy#16466]
While updating mypy package for OpenIndiana from version 1.6.1 to version 1.7.0 I noticed two new test failures:
```
___________________ testIgnoreImportIfNoPython3StubAvailable ___________________
data: $(BUILD_DIR)/test-data/unit/pythoneval.test:1567:
Failed: Invalid output ($(BUILD_DIR)/test-data/unit/pythoneval.test, line 1567)
----------------------------- Captured stderr call -----------------------------
Expected:
  _testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not installed for "docutils" (diff)
  _testIgnoreImportIfNoPython3StubAvailable.py:4: note: Hint: "python3 -m pip install types-docutils" (diff)
  _testIgnoreImportIfNoPython3StubAvailable.py:4: note: (or run "mypy --install-types" to install all missing stub packages) (diff)
  _testIgnoreImportIfNoPython3StubAvailable.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports (diff)
Actual:
  Traceback (most recent call last): (diff)
    File "/tmp/mypy-test-46a1te1g/tmp/_testIgnoreImportIfNoPython3StubAvailable.py", line 2, in <module> (diff)
      import scribe  # No Python 3 stubs available for scribe (diff)
  ModuleNotFoundError: No module named 'scribe' (diff)

Alignment of first line difference:
  E: _testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not...
  A: Traceback (most recent call last):...
     ^
Update the test output using --update-data -n0 (you can additionally use the -k selector to update only specific tests)
__________________________ testNoPython3StubAvailable __________________________
data: $(BUILD_DIR)/test-data/unit/pythoneval.test:1580:
Failed: Invalid output ($(BUILD_DIR)/test-data/unit/pythoneval.test, line 1580)
----------------------------- Captured stderr call -----------------------------
Expected:
  _testNoPython3StubAvailable.py:1: error: Cannot find implementation or library stub for module named "scribe"
  _testNoPython3StubAvailable.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
  _testNoPython3StubAvailable.py:3: error: Library stubs not installed for "docutils" (diff)
  _testNoPython3StubAvailable.py:3: note: Hint: "python3 -m pip install types-docutils" (diff)
  _testNoPython3StubAvailable.py:3: note: (or run "mypy --install-types" to install all missing stub packages) (diff)
Actual:
  _testNoPython3StubAvailable.py:1: error: Cannot find implementation or library stub for module named "scribe"
  _testNoPython3StubAvailable.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

Update the test output using --update-data -n0 (you can additionally use the -k selector to update only specific tests)
```

**Comment by mr-c** [comment]
We also saw this in Debian; I presumed it was due to the lack of internet connectivity on our build hosts.

https://salsa.debian.org/python-team/packages/mypy/-/commit/d43794178b2f0421654ad0ca2cb0eedd49cde6e0

**Comment by mtelka** [comment]
I'm pretty confident it is permanent issue, not related to internet connectivity.  Proof: testing of `1.6.1` always pass, testing of `1.7.0` always fails.

**Comment by mr-c** [comment]
@mtelka Could be! We never allow internet connections on our build hosts. I forcibly enabled internet access and `testIgnoreImportIfNoPython3StubAvailable` still failed so I guess you are right, this is something else.

The second failing test looks like what we experience in Debian with our [big package of the entire typeshed](https://packages.debian.org/sid/python3-typeshed): for us, `testNoPython3StubAvailable` fails because it is missing the extra errors due to the  `docutils` types already being installed locally.

**Comment by ilevkivskyi** [comment]
I think both failures are caused by `docutils` being already installed locally. The first one is less obvious, because of how `pythoneval` tests work: if the type-checking output is empty it tries to actually run the test case using Python interpreter. I am not sure why this is only specific to 1.7, but a random guess is that 1.7 looks for installed packages in more places.

**Comment by mtelka** [comment]
I just confirmed that when I uninstall `types-docutils` then both tests pass.  I can keep `docutils` installed; it does not affect those tests.  Now there are few questions left:

1. Why both tests passed with 1.6.1 even with `types-docutils` installed?
2. Is it possible to make both tests to pass again even with `types-docutils` installed?

**Comment by AlexWaygood** [comment]
> Now there are few questions left:
> 
> 1. Why both tests passed with 1.6.1 even with `types-docutils` installed?

The test was changed as part of https://github.com/python/mypy/commit/10dfafe089a75dc117586ebab35723da66309398

> 2. Is it possible to make both tests to pass again even with `types-docutils` installed?

Sure, yes, I just selected a random `types-*` package that's still actively maintained and isn't installed as part of mypy's CI. There are many such packages; the test could theoretically use any one of these. (That won't fix @mr-c's issue, though -- it'll be impossible for this test to pass if you have all of typeshed's `types-*` packages installed at once, since the premise of the test is that it's being run in an environment that does not have _all_ currently maintained typeshed packages installed into it.)

Ultimately, I feel the basic problem is that mypy's tests aren't guaranteed to pass if you create an environment that has extra packages etc. installed. I feel like we only guarantee the tests will pass if you create an isolated environment according to the instructions we give in https://github.com/python/mypy/blob/master/CONTRIBUTING.md#getting-started-with-development :)

**Comment by mtelka** [comment]
> > 2. Is it possible to make both tests to pass again even with `types-docutils` installed?
> 
> Sure, yes, I just selected a random `types-*` package that's still actively maintained and isn't installed as part of mypy's CI. There are many such packages; the test could theoretically use any one of these. (That won't fix @mr-c's issue, though -- it'll be impossible for this test to pass if you have all of typeshed's `types-*` packages installed at once, since the premise of the test is that it's being run in an environment that does not have _all_ currently maintained typeshed packages installed into it.)

Why it must be an _actively maintained_ `types-*` package?

> Ultimately, I feel the basic problem is that mypy's tests aren't guaranteed to pass if you create an environment that has extra packages etc. installed. I feel like we only guarantee the tests will pass if you create an isolated environment according to the instructions we give in https://github.com/python/mypy/blob/master/CONTRIBUTING.md#getting-started-with-development :)

Of course, you cannot guarantee interoperability with the whole world.  We just need some sort of interoperability with the small subset of that to make our packaging and testing working properly.  You do that well.  Thanks for that.  Some minor issues like this one are just small fee to achieve our goals.

**Comment by AlexWaygood** [comment]
> Why it must be an _actively maintained_ `types-*` package?

If you don't have stubs for `requests` installed, and you run mypy over a file that has `import requests` in it, mypy has a nice feature where it says "Maybe you want to install the stubs for `requests`?" Mypy generates these suggestions by hardcoding [a list of runtime packages](https://github.com/python/mypy/blob/c6cb3c6282003dd3dadcf028735f9ba6190a0c84/mypy/stubinfo.py#L19-L173) for which up-to-date typeshed stubs packages exist. The test we're talking about here checks that this feature is working correctly. The suggested stubs need to be hardcoded in mypy, and need to all be typeshed packages, for security reasons: we don't want to suggest to users that they install untrusted stubs. (If somebody uses mypy with the `--install-types --no-interactive` option, moreover, these suggested stubs packages might be _automatically_ installed, heightening the security risk here.)

Okay, let's say typeshed removes its stubs for `requests` tomorrow. Why might it do that? Here are some hypothetical reasons: It might do that because `requests` adds inline types, meaning typeshed's stubs are now out of date and redundant. It might do that because there are now stubs packages outside of typeshed that are higher quality than those in typeshed. Or, it might do that because the `requests` maintainers ask for them to be removed for some reason. If it's any one of these reasons, mypy probably should remove `types-requests` from the hardcoded list in `stubinfo.py`: it's probably not a stubs package that it should be suggesting to its users anymore.

The upshot of this all is that, yeah, all the packages hardcoded in `stubinfo.py` are actively maintained typeshed packages. As a result, the stubs package in the test we're discussing here has to also be an actively maintained typeshed stubs package.

**Comment by mtelka** [comment]
Okay, I think I understand.  Thanks for explanation.  I was about to suggest `typed-ast`/`types-typed-ast`, but maybe you'll remove it from `mypy` soon.

**Comment by AlexWaygood** [comment]
> I was about to suggest `typed-ast`/`types-typed-ast`, but maybe you'll remove it from `mypy` soon.

yes, we've already removed those stubs from typeshed; we shouldn't be recommending to users that they install the stubs package anymore, as it's no longer maintained. It's arguably a bug that it's still there in the `stubinfo.py` list in mypy :)

The trouble with a hardcoded list is that it's hard to keep it up to date ;)

**Comment by AlexWaygood** [comment]
FWIW, some reasons why `docutils` is a good package for this test from mypy's perspective:
1. It's a popular runtime package that's unlikely to go away anytime soon
2. I think they're unlikely to add inline types themselves anytime soon

**Comment by AlexWaygood** [comment]
> Then what about something like `types-pywin32`? Not sure about its popularity or other pros and cons, but at least we will (most likely) never have it installed on OpenIndiana.

Seems fine to me (though I'm not a maintainer here, just a triager and regular contributor :)

**Comment by mtelka** [comment]
For now I just [patched out both tests](https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/python/mypy/patches/02-test-types-docutils.patch) and I will wait for a better solution.  Thanks.

**Comment by JelleZijlstra** [comment]
I think the right solution (as Alex mentioned above) is to run mypy tests in an isolated environment. We don't and can't guarantee that the tests will pass when unknown other packages are installed.

**Comment by AlexWaygood** [comment]
> Then what about something like `types-pywin32`?

As discussed above, this change would just be papering over the underlying issue, which is that we do not and cannot guarantee our test suite will succeed if it isn't run in an isolated environment. However, if you want to propose a PR for this change, I think we'd be happy to consider it; `types-pywin32` probably works just as well for us here as `types-docutils`.

There's no bug in mypy's test suite here, though, so there's nothing actionable for us. As such, I'm closing this issue.

**Comment by mtelka** [comment]
@AlexWaygood, it looks like the root cause is something different.  I just tried the following patch:
```
--- mypy-1.7.0/test-data/unit/pythoneval.test.orig      2023-11-17 11:49:58.699810737 +0100
+++ mypy-1.7.0/test-data/unit/pythoneval.test   2023-11-17 11:53:37.896619424 +0100
@@ -1568,24 +1568,24 @@
 # flags: --ignore-missing-imports
 import scribe  # No Python 3 stubs available for scribe
 from scribe import x
-import docutils  # Python 3 stubs available for docutils
+import pywin32  # Python 3 stubs available for pywin32
 import foobar_asdf
 import jack  # This has a stubs package but was never bundled with mypy, so ignoring works
 [out]
-_testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not installed for "docutils"
-_testIgnoreImportIfNoPython3StubAvailable.py:4: note: Hint: "python3 -m pip install types-docutils"
+_testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not installed for "pywin32"
+_testIgnoreImportIfNoPython3StubAvailable.py:4: note: Hint: "python3 -m pip install types-pywin32"
 _testIgnoreImportIfNoPython3StubAvailable.py:4: note: (or run "mypy --install-types" to install all missing stub packages)
 _testIgnoreImportIfNoPython3StubAvailable.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
 
 [case testNoPython3StubAvailable]
 import scribe
 from scribe import x
-import docutils
+import pywin32
 [out]
 _testNoPython3StubAvailable.py:1: error: Cannot find implementation or library stub for module named "scribe"
 _testNoPython3StubAvailable.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
-_testNoPython3StubAvailable.py:3: error: Library stubs not installed for "docutils"
-_testNoPython3StubAvailable.py:3: note: Hint: "python3 -m pip install types-docutils"
+_testNoPython3StubAvailable.py:3: error: Library stubs not installed for "pywin32"
+_testNoPython3StubAvailable.py:3: note: Hint: "python3 -m pip install types-pywin32"
 _testNoPython3StubAvailable.py:3: note: (or run "mypy --install-types" to install all missing stub packages)
 

```
and both tests failed with (almost) the same error:
```
___________________ testIgnoreImportIfNoPython3StubAvailable ___________________
data: $(BUILD_DIR)/test-data/unit/pythoneval.test:1567:
Failed: Invalid output ($(BUILD_DIR)/test-data/unit/pythoneval.test, line 1567)
----------------------------- Captured stderr call -----------------------------
Expected:
  _testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not installed for "pywin32" (diff)
  _testIgnoreImportIfNoPython3StubAvailable.py:4: note: Hint: "python3 -m pip install types-pywin32" (diff)
  _testIgnoreImportIfNoPython3StubAvailable.py:4: note: (or run "mypy --install-types" to install all missing stub packages) (diff)
  _testIgnoreImportIfNoPython3StubAvailable.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports (diff)
Actual:
  Traceback (most recent call last): (diff)
    File "/tmp/mypy-test-m1vxtsm2/tmp/_testIgnoreImportIfNoPython3StubAvailable.py", line 2, in <module> (diff)
      import scribe  # No Python 3 stubs available for scribe (diff)
  ModuleNotFoundError: No module named 'scribe' (diff)

Alignment of first line difference:
  E: _testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not...
  A: Traceback (most recent call last):...
     ^
Update the test output using --update-data -n0 (you can additionally use the -k selector to update only specific tests)
__________________________ testNoPython3StubAvailable __________________________
data: $(BUILD_DIR)/test-data/unit/pythoneval.test:1580:
Failed: Invalid output ($(BUILD_DIR)/test-data/unit/pythoneval.test, line 1580)
----------------------------- Captured stderr call -----------------------------
Expected:
  _testNoPython3StubAvailable.py:1: error: Cannot find implementation or library stub for module named "scribe"
  _testNoPython3StubAvailable.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
  _testNoPython3StubAvailable.py:3: error: Library stubs not installed for "pywin32" (diff)
  _testNoPython3StubAvailable.py:3: note: Hint: "python3 -m pip install types-pywin32" (diff)
  _testNoPython3StubAvailable.py:3: note: (or run "mypy --install-types" to install all missing stub packages) (diff)
Actual:
  _testNoPython3StubAvailable.py:1: error: Cannot find implementation or library stub for module named "scribe"
  _testNoPython3StubAvailable.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
  _testNoPython3StubAvailable.py:3: error: Cannot find implementation or library stub for module named "pywin32" (diff)

Alignment of first line difference:
  E: ...ailable.py:3: error: Library stubs not installed for "pywin32"...
  A: ...ailable.py:3: error: Cannot find implementation or library stub for m...
                             ^
Update the test output using --update-data -n0 (you can additionally use the -k selector to update only specific tests)
```
And no, I have no `types-pywin32` installed. :-)

**Comment by mtelka** [comment]
Ah, the patch I tried was wrong.  Sorry for noise.

**Comment by AlexWaygood** [comment]
> Ah, the patch I tried was wrong. Sorry for noise.

yes, `pywin32` is the name of the distribution you install from PyPI, but it's not actually a package that's available at runtime :-)

**Comment by mtelka** [comment]
Exactly,  I replaced it by `pythonwin`, but I still see the first test to fail.  Strange...

**Comment by mtelka** [comment]
The current version of the patch:
```
--- mypy-1.7.0/test-data/unit/pythoneval.test.orig      2023-11-17 11:49:58.699810737 +0100
+++ mypy-1.7.0/test-data/unit/pythoneval.test   2023-11-17 11:53:37.896619424 +0100
@@ -1568,24 +1568,24 @@
 # flags: --ignore-missing-imports
 import scribe  # No Python 3 stubs available for scribe
 from scribe import x
-import docutils  # Python 3 stubs available for docutils
+import pythonwin  # Python 3 stubs available for pythonwin
 import foobar_asdf
 import jack  # This has a stubs package but was never bundled with mypy, so ignoring works
 [out]
-_testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not installed for "docutils"
-_testIgnoreImportIfNoPython3StubAvailable.py:4: note: Hint: "python3 -m pip install types-docutils"
+_testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not installed for "pythonwin"
+_testIgnoreImportIfNoPython3StubAvailable.py:4: note: Hint: "python3 -m pip install types-pywin32"
 _testIgnoreImportIfNoPython3StubAvailable.py:4: note: (or run "mypy --install-types" to install all missing stub packages)
 _testIgnoreImportIfNoPython3StubAvailable.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
 
 [case testNoPython3StubAvailable]
 import scribe
 from scribe import x
-import docutils
+import pythonwin
 [out]
 _testNoPython3StubAvailable.py:1: error: Cannot find implementation or library stub for module named "scribe"
 _testNoPython3StubAvailable.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
-_testNoPython3StubAvailable.py:3: error: Library stubs not installed for "docutils"
-_testNoPython3StubAvailable.py:3: note: Hint: "python3 -m pip install types-docutils"
+_testNoPython3StubAvailable.py:3: error: Library stubs not installed for "pythonwin"
+_testNoPython3StubAvailable.py:3: note: Hint: "python3 -m pip install types-pywin32"
 _testNoPython3StubAvailable.py:3: note: (or run "mypy --install-types" to install all missing stub packages)
 
 

```
Test results:
```
============================= test session starts ==============================
platform sunos5 -- Python 3.9.16, pytest-7.4.3, pluggy-1.3.0 -- $(BUILD_DIR)/.tox/py39/bin/python
cachedir: .tox/py39/.pytest_cache
rootdir: $(BUILD_DIR)
configfile: pyproject.toml
plugins: xdist-3.4.0
collecting ... collected 2 items

mypy/test/testpythoneval.py::PythonEvaluationSuite::pythoneval.test::testIgnoreImportIfNoPython3StubAvailable FAILED [ 50%]
mypy/test/testpythoneval.py::PythonEvaluationSuite::pythoneval.test::testNoPython3StubAvailable PASSED [100%]

=================================== FAILURES ===================================
___________________ testIgnoreImportIfNoPython3StubAvailable ___________________
data: $(BUILD_DIR)/test-data/unit/pythoneval.test:1567:
Failed: Invalid output ($(BUILD_DIR)/test-data/unit/pythoneval.test, line 1567)
----------------------------- Captured stderr call -----------------------------
Expected:
  _testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not installed for "pythonwin" (diff)
  _testIgnoreImportIfNoPython3StubAvailable.py:4: note: Hint: "python3 -m pip install types-pywin32" (diff)
  _testIgnoreImportIfNoPython3StubAvailable.py:4: note: (or run "mypy --install-types" to install all missing stub packages) (diff)
  _testIgnoreImportIfNoPython3StubAvailable.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports (diff)
Actual:
  Traceback (most recent call last): (diff)
    File "/tmp/mypy-test-um6ylvle/tmp/_testIgnoreImportIfNoPython3StubAvailable.py", line 2, in <module> (diff)
      import scribe  # No Python 3 stubs available for scribe (diff)
  ModuleNotFoundError: No module named 'scribe' (diff)

Alignment of first line difference:
  E: _testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not...
  A: Traceback (most recent call last):...
     ^
Update the test output using --update-data -n0 (you can additionally use the -k selector to update only specific tests)
=========================== short test summary info ============================
FAILED mypy/test/testpythoneval.py::PythonEvaluationSuite::pythoneval.test::testIgnoreImportIfNoPython3StubAvailable
========================= 1 failed, 1 passed in 18.78s =========================
```
Any suggestion?

Thank you.

**Comment by AlexWaygood** [comment]
Oh -- for the first of the two tests, it needs to be an import that's included in the first of [these two dictionaries](https://github.com/python/mypy/blob/8c8aa10e2976612ca0ca1fa1e5655fbd535de6f7/mypy/stubinfo.py#L19-L173). Try this patch instead:

```patch
--- a/test-data/unit/pythoneval.test
+++ b/test-data/unit/pythoneval.test
@@ -1568,24 +1568,24 @@ note: A user-defined top-level module with name "typing" is not supported
 # flags: --ignore-missing-imports
 import scribe  # No Python 3 stubs available for scribe
 from scribe import x
-import docutils  # Python 3 stubs available for docutils
+import waitress  # Python 3 stubs available for waitress
 import foobar_asdf
 import jack  # This has a stubs package but was never bundled with mypy, so ignoring works
 [out]
-_testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not installed for "docutils"
-_testIgnoreImportIfNoPython3StubAvailable.py:4: note: Hint: "python3 -m pip install types-docutils"
+_testIgnoreImportIfNoPython3StubAvailable.py:4: error: Library stubs not installed for "waitress"
+_testIgnoreImportIfNoPython3StubAvailable.py:4: note: Hint: "python3 -m pip install types-waitress"
 _testIgnoreImportIfNoPython3StubAvailable.py:4: note: (or run "mypy --install-types" to install all missing stub packages)
 _testIgnoreImportIfNoPython3StubAvailable.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

 [case testNoPython3StubAvailable]
 import scribe
 from scribe import x
-import docutils
+import pythonwin
 [out]
 _testNoPython3StubAvailable.py:1: error: Cannot find implementation or library stub for module named "scribe"
 _testNoPython3StubAvailable.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
-_testNoPython3StubAvailable.py:3: error: Library stubs not installed for "docutils"
-_testNoPython3StubAvailable.py:3: note: Hint: "python3 -m pip install types-docutils"
+_testNoPython3StubAvailable.py:3: error: Library stubs not installed for "pythonwin"
+_testNoPython3StubAvailable.py:3: note: Hint: "python3 -m pip install types-pywin32"
 _testNoPython3StubAvailable.py:3: note: (or run "mypy --install-types" to install all missing stub packages)
```

**Comment by mtelka** [comment]
Then I'll probably go with the `python2`/`types-six` pair (`waitress` is too active and we already have it packaged, even there is no `types-waitress` her, yet).  Both tests pass for `python2` even I do have `types-six` installed (but there is apparently no `python2` around so I should be okay).
