### ISSUE TITLE
[1.7] Regression with decorator on overload

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#16481]
**Bug Report**

```
aiomcache/client.py:210:6: error: Argument 1 to "acquire" has incompatible type
"Callable[[FlagClient[_T], Connection, bytes, _U], Coroutine[Any, Any, Union[bytes, _T, _U]]]";
expected
"Callable[[Never, Connection, VarArg(Never), KwArg(Never)], Awaitable[Never]]" 
[arg-type]
        @acquire
         ^
aiomcache/client.py:215:6: error: Argument 1 to "acquire" has incompatible type
"Callable[[FlagClient[_T], Connection, bytes, Optional[_U]], Coroutine[Any, Any, Union[bytes, _T, _U, None]]]";
expected
"Callable[[Never, Connection, VarArg(Never), KwArg(Never)], Awaitable[Never]]" 
[arg-type]
        @acquire
         ^
aiomcache/client.py:215:6: error: Overloaded function implementation does not
accept all possible arguments of signature 1  [misc]
        @acquire
         ^
```

https://github.com/aio-libs/aiomcache/actions/runs/6854046166/job/18636163359?pr=359

For some reason, the errors only appear on 1 method, despite the decorator being used in a similar way on several other methods. Which means it's probably difficult to get a minimal reproducer, though the project itself is pretty small.

**To Reproduce**

Checkout: https://github.com/aio-libs/aiomcache/pull/359
Run: `mypy`

**Comment by AlexWaygood** [comment]
Fixed earlier today in https://github.com/python/mypy/commit/fbb77c31ad48e08105b5d02c2888d803bdcd6fc5

**Comment by AlexWaygood** [comment]
@hauntsaninja, would it be worth it to add `aiomemcache` to mypy_primer?

**Comment by Dreamsorcerer** [comment]
I did also mention some other candidates before, which included aiohttp-admin which is also seeing a regression (#16482):
https://github.com/python/mypy/issues/15489#issuecomment-1602972868

**Comment by Dreamsorcerer** [comment]
I highlighted aiohttp-admin as it is doing a lot of introspection on sqlalchemy, so it probably has some interesting edge cases for typing that not many other projects will see. The other libraries I mentioned are all very small, so shouldn't add much overhead, but also strictly typed, so there's a chance they may find a regression.
