### ISSUE TITLE
Docs build is broken on master 

### ISSUE THREAD

**Issue by AlexWaygood** [python/mypy#16518]
**Documentation**
See e.g. https://github.com/python/mypy/actions/runs/6916132945/job/18815845352

**Comment by AlexWaygood** [comment]
> Warning, treated as Error
> /home/runner/work/mypy/mypy/docs/source/config_file.rst:257:Could not lex literal_block '[tool.mypy]\nexclude = [\n    "^one\\\\.py$",  # TOML\'s double-quoted strings require escaping backslashes\n    \'two\\.pyi$\',  # but TOML\'s single-quoted strings do not\n    \'^three\\.\',\n]' as "toml". Highlighting skipped.

I'm guessing this is due to a new release of a transitive dependency somewhere, but haven't investigated at all yet

**Comment by AlexWaygood** [comment]
Guessing https://github.com/pygments/pygments/releases/tag/2.17.0 is the cause, since the error message mentions a failure to lex

**Comment by ilevkivskyi** [comment]
And, that release includes https://github.com/pygments/pygments/pull/2576 which changed a lot in `toml`.

**Comment by ilevkivskyi** [comment]
And I think I found a bug in that PR https://github.com/pygments/pygments/pull/2576/files#r1398277842

**Comment by AlexWaygood** [comment]
Fixed by the latest pygments release! https://github.com/pygments/pygments/releases/tag/2.17.1
