### ISSUE TITLE
1.7.0 Broken explicit-override for pydantic 1.10

### ISSUE THREAD

**Issue by zoola969** [python/mypy#16548]
**Bug Report**

After updating mypy from 1.6.1 to 1.7.0 I faced the issue with `explicit-override` option for pydantic models

**To Reproduce**
`example.py`
```python
from pydantic import BaseModel

class M(BaseModel):
    a: int
```

**Expected Behavior**

No errors

**Actual Behavior**
`mypy --enable-error-code explicit-override example.py`

`error: Method "__mypy-replace" is not using @override but is overriding a method in class "pydantic.main.BaseModel"  [explicit-override]`

**Your Environment**

- Mypy version used: 1.7.0
- Pydantic version used: 1.10.13
- Mypy command-line flags: --enable-error-code explicit-override
- Python version used: 3.11

**Comment by AlexWaygood** [comment]
Looks like the same basic thing as #16454; it's possible @ikonst's PR https://github.com/python/mypy/pull/16524 would also fix this issue

**Comment by ikonst** [comment]
It's probably a dup of #16452. My PR might address it inadvertently but the real fix is not to check overrides in private attributes since they're by definition not overriding.

**Comment by zoola969** [comment]
Works fine in 1.7.1
