### ISSUE TITLE
Segmentation Fault After Update from 1.6.1 to 1.7.1

### ISSUE THREAD

**Issue by gaotako** [python/mypy#16592]
**Bug Report**

After update from 1.6.1 to 1.7.1, mypy raises segmentation fault with no other messages:
```
$ mypy src --strict --show-traceback
zsh: segmentation fault  mypy src --strict --show-traceback
```

**To Reproduce**

Since there is no detailed message, I have no idea which line of my code causes the bug, so I only attach verbosed log here:
[mypy.log](https://github.com/python/mypy/files/13517482/mypy.log)

**Expected Behavior**

It should have no error as 1.6.1 did.

**Actual Behavior**

It raises segmentation fault without any other information.

**Your Environment**

- Mypy version used: 1.7.1
- Mypy command-line flags: `mypy src --strict --verbose &> mypy.log`
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.8

**Comment by AlexWaygood** [comment]
Is your code open-source? If not, are you able to try to minimize the crash in any way?

If you try using uncompiled mypy from the master branch, you might be able to get a stack trace for us.

With the information you've given us currently, there's no way for us to debug this, I'm afraid.

**Comment by AlexWaygood** [comment]
Without a minimal repro, access to your source code or a stack trace using uncompiled mypy, it's impossible for us to try to debug this. If you're able to supply one or more of those, I'm happy to reopen this :)
