### ISSUE TITLE
mypy needs a logo

### ISSUE THREAD

**Issue by developomp** [python/mypy#16636]
Currently, there are many "logos" used by mypy (e.g. README and twitter). As a result, there is an ambiguity as to which image people should use. To fix this, mypy needs to define a official brand logo that people can use.

- This conversation started [here](https://github.com/simple-icons/simple-icons/issues/7151)

**Comment by JelleZijlstra** [comment]
The logo is the one in the README: https://github.com/python/mypy/blob/master/docs/source/mypy_light.svg

This was discussed in #383.
