### ISSUE TITLE
Can error reporting on a package that can't be opened be improved?

### ISSUE THREAD

**Issue by gmc444-b** [python/mypy#16634]
**Feature**

When `mypy` is run against a package that's installed but isn't PEP-561 compliant, it will report that it can't find the package.

It would be better to state that the package is there, but it's not PEP-561 compliant.

**Pitch**

The "package not found" message is extremely confusing the first (and even the fifth) time it's encountered. Developers can waste a lot of time trying to figure out why mypy can't find the package because "it's right there! I just installed it! I can import it!"

**Comment by hauntsaninja** [comment]
mypy does do this, the error message is: `Skipping analyzing "xyz": module is installed, but missing library stubs or py.typed marker` and uses the `import-untyped` error code.
