### ISSUE TITLE
Add a TypeVar / generic function example to cheat sheet

### ISSUE THREAD

**Issue by gnprice** [python/mypy#1665]

**Comment by ilevkivskyi** [comment]
This is quite important, since users are often confused by these features.

**Comment by JukkaL** [comment]
I don't think that this is important, since an example is not enough to document these properly and may actually increase confusion.

**Comment by JukkaL** [comment]
We now have a decorator example that uses a type variable: https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#decorators
