### ISSUE TITLE
MyPy fails to detect float / decimal divisions within function definitions

### ISSUE THREAD

**Issue by Klim314** [python/mypy#16676]
**Bug Report**
Mypy fails to detect typing errors within 

**To Reproduce**

https://gist.github.com/mypy-play/7062b993208f0ac52b9fb4f016328e73
```python
from decimal import Decimal


class Foo:
    def bar(self):
        # Fails to catch this
        return 50.0 / Decimal(50)


def bar():
    # Fails to catch this
    x = 50.0 / Decimal(50)
    return x


a: Decimal = Decimal(20)
# Catches this
float(a) / Decimal(50)

```

**Expected Behavior**

All three `50.0 / Decimal(50)` invocations should have been detected

**Actual Behavior**

Only the invocation in the global namespace is properly caught
```
main.py:18: error: Unsupported operand types for / ("float" and "Decimal")  [operator]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.7.0, 1.7.1
- Python version used: 3.8

**Comment by AlexWaygood** [comment]
(https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code)
