### ISSUE TITLE
Ignoring type annotations

### ISSUE THREAD

**Issue by a4168048** [python/mypy#16714]
**He should have thrown an error because the variable contains a number, but he ignored it**
**Your Environment**

- Mypy version used: 1.8.0
- Mypy command-line flags: -V
- Mypy configuration options from `mypy.ini` (and other config files): 
- Python version used:

![image](https://github.com/python/mypy/assets/139621912/bdbcadf5-7838-4dcd-8bca-4474e8a9c4c9)

**Comment by ruslansenatorov** [comment]
@a4168048 good job!

**Comment by hauntsaninja** [comment]
mypy doesn't support checking ipynb. You're probably just getting unlucky that the json within an ipynb happens to parse as a valid python dictionary

**Comment by a4168048** [comment]
I see. Thank you so much for your reply @hauntsaninja
