### ISSUE TITLE
TypeVarTuple equality checks not implemented

### ISSUE THREAD

**Issue by cdce8p** [python/mypy#16739]
**Bug Report**
PEP 646 mentions equality checks for TypeVarTuples inside the same signature. These don't seem to be implemented yet.
https://peps.python.org/pep-0646/#type-variable-tuple-equality

/CC: @ilevkivskyi

**To Reproduce**

These examples are from the PEP itself
```python
from typing import Generic, TypeVarTuple
Ts = TypeVarTuple("Ts")

class Array(Generic[*Ts]): ...

def pointwise_multiply(x: Array[*Ts], y: Array[*Ts]) -> Array[*Ts]: ...

def a1(x: Array[int], y: Array[str], z: Array[int, str]) -> None:
    pointwise_multiply(x, x)  # Valid
    pointwise_multiply(x, y)  # Error
    pointwise_multiply(x, z)  # Error


# ---
def foo(arg1: tuple[*Ts], arg2: tuple[*Ts]) -> None: ...

def a2(a: tuple[int], b: tuple[str]) -> None:
    foo(a, b)  # Error
```

An additional example
```py
def func(x: Array[*Ts], *args: *Ts) -> None:
    ...

def a3(x: Array[int, str]) -> None:
    func(x, 2, "Hello")  # Valid
    func(x, 2)                  # Error
    func(x, 2, "Hello", True)   # Error
```

**Your Environment**

- Mypy version used: `mypy 1.9.0+dev.a1b4e32785b69291748579d97cb9456e1198ec21`
- Python version used: `3.11`

**Comment by erictraut** [comment]
This isn't a bug. Mypy is working as expected here.

It is not supposed to perform "tuple equality checks".  It is supposed to "find a solution for `Ts` that meets all of the constraints", and it's doing so. When calling `foo(a, b)`, for example, the solution for `Ts` is `tuple[int | str]`.

**Comment by cdce8p** [comment]
> This isn't a bug. Mypy is working as expected here.

Please run all the code with both `Mypy` and `pyright`. You only mentioned the one example, which the PEP explicitly mentions as forbidden btw. You would notice that Mypy doesn't recognize any of these while pyright does (all except the one).

**Comment by erictraut** [comment]
Ah yes, my bad. Mypy is missing some cases in `a1` and `a3` that should be reported as type errors.

**Comment by cdce8p** [comment]
Opened #16759 to fix this issue. It seems for the initial implementation `TypeVarTuple` was implemented as `covariant` when it should have been `invariant`.

@erictraut The `foo(a, b)` example still fails (no error) even with this change. Both pyright and mypy are able to resolve this. Mypy to `tuple[object]` and pyright to `tuple[int | str]` respectively. That might indeed be something that should be changed in the tying spec as you suggested, rather than "fixed".
