### ISSUE TITLE
Type narrowing not working with a lambda callback

### ISSUE THREAD

**Issue by llucax** [python/mypy#16743]
**Bug Report**

Type narrowing doesn't seem to be working when the narrowed variable is passed inside a `lambda` as a callback to another function.

**To Reproduce**

https://mypy-play.net/?mypy=1.8.0&python=3.11&gist=11343b6a915200f0333b213d2ef93788

```python
from datetime import datetime
from typing import Callable

x: int | None = None if datetime.now().second % 2 == 0 else 1

def f(x: int) -> None:
    ...

def g(f: Callable[[], None]) -> None:
    ...

assert x is not None
reveal_type(x)
g(lambda: f(x))  # error: Argument 1 to "f" has incompatible type "int | None"; expected "int"  [arg-type]

x2 = x  # Just binding to a different name makes it work
g(lambda: f(x2))  # OK
```

**Expected Behavior**

No error in the above code.

**Actual Behavior**

```
main.py:15: error: Argument 1 to "f" has incompatible type "int | None"; expected "int"  [arg-type]
```

**Your Environment**

- Mypy version used: 1.8.0
- Mypy command-line flags: none (as per the mypy playground)
- Mypy configuration options from `mypy.ini` (and other config files): none (as per the mypy playground)
- Python version used: 3.11 (as per the mypy playground)

**Comment by hauntsaninja** [comment]
mypy is correct to error here: https://mypy.readthedocs.io/en/stable/common_issues.html#narrowing-and-inner-functions

**Comment by llucax** [comment]
I see, I suspected I might be missing something with name binding. I asked in Gitter but nobody replied so I thought better to report the bug just in case. Sorry for the noise!
