### ISSUE TITLE
Use self-type in `__init__` to add extra generic types

### ISSUE THREAD

**Issue by A5rocks** [python/mypy#16752]
**Feature**

Allow using self-types to add intermediate generic types for `__init__`.

**Pitch**

This would make https://github.com/python-trio/trio/pull/2898 possible to type well without the awful hacks we had to do. Specifically making sure `RaisesGroup(RaisesGroup(ValueError))` is `RaisesGroup[ExceptionGroup[ValueError]]`.

Perhaps a code sample would make more sense:

```py
from typing import Generic, TypeVar, overload

E = TypeVar("E", bound=BaseException)
E2 = TypeVar("E2", bound=BaseException)

class RaisesGroup(Generic[E]):
    @overload
    def __init__(self, a: type[E]):
        ...
    
    @overload
    def __init__(self: "RaisesGroup[BaseExceptionGroup[E2]]", a: "RaisesGroup[E2]"):
        ...
    
    def __init__(self, a: object):
        ...


RaisesGroup(RaisesGroup(ValueError))  # currently: Argument 1 to "RaisesGroup" has incompatible type "RaisesGroup[ValueError]"; expected "RaisesGroup[Never]"
```

**Comment by erictraut** [comment]
We should try to formally define the intended behavior for this construct. All of the major type checkers treat the `self` parameter in the `__init__` method specially, but the behavior has never been formally spec'ed. It's therefore not surprising that we see different behaviors between type checkers. For example, pyright accepts the above code and works they way you'd like. 

If you would like to see this become part of the official typing spec, I encourage you to write a mini spec and post it in the [python/typing forum](https://discuss.python.org/c/typing/32) for feedback. My sense is that this probably doesn't require a full PEP. If the spec is relatively straightforward and uncontroversial, it's something that the recently-formed Typing Council could ratify and incorporate into the typing spec.

**Comment by A5rocks** [comment]
I'll see if I can express this in a formal manner, though I'm not sure I'm able to. For reference, this was a 1 line (... ok maybe technically +2-1) change in https://github.com/python/mypy/pull/16753

**Comment by A5rocks** [comment]
This works in mypy nowadays (or at least my initial example does), as of 83d54ffb01af9cba76a36d2ec0938acc7dfa2197

Thanks @ilevkivskyi!
