### ISSUE TITLE
No name 'override' in module 'typing'

### ISSUE THREAD

**Issue by mRcSchwering** [python/mypy#16800]
It seems typing does not export `override` as documented in mypy.readthedocs.

**Bug Report**

I am following [this tutorial](https://mypy.readthedocs.io/en/stable/class_basics.html#overriding-statically-typed-methods) which uses `override`:

```python
from typing import override

class Base:
    def f(self, x: int) -> None:
        ...
    def g_renamed(self, y: str) -> None:
        ...

class Derived1(Base):
    @override
    def f(self, x: int) -> None:   # OK
        ...

    @override
    def g(self, y: str) -> None:   # Error: no corresponding base method found
        ...
```

**Expected Behavior**

However I can't import `override`: `No name 'override' in module 'typing'`

**Your Environment**

- Mypy version used: `mypy==1.8.0`
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):  `namespace_packages = False, disable_error_code = import-untyped, attr-defined`
- Python version used: 3.10
- Typing extensions `typing_extensions==4.9.0`

**Comment by JelleZijlstra** [comment]
`typing.override` was only added in 3.12 (https://docs.python.org/3.12/library/typing.html#typing.override). On earlier versions, use `typing_extensions.override` instead.
