### ISSUE TITLE
Unable to typecheck an `Unpack`ed `TypedDict` when tightly coupled to a function

### ISSUE THREAD

**Issue by zevisert** [python/mypy#16804]
**Bug Report**

`Unpack` is great, but it in one of my projects, it would be nice if we could tightly couple the `TypedDict` with the function it's unpacked into, so that we can easily unpack it in other functions that accept-then-forward those same kwargs. 

**To Reproduce**

```python
# in one file
from typing import Unpack, TypedDict


class FooKwargs(TypedDict):
    bar: int
    baz: str

def foo(/, **kwargs: Unpack[FooKwargs]) -> int
    pass

foo.kwtypes = FooKwargs
```
```python
# in another file
from typing import Unpack
from .first_file import foo

                                    # ↙ It'd be nice if this worked
def qux(quux: bool, **kwargs: Unpack[foo.kwtypes]) -> int:
    return foo(**kwargs) if quux else -1
```

A ready to run, more thouroughly typed example: 
```shell
git clone git@github.com:zevisert/repro-unpack-kwargs
python -m venv .venv
poetry install
mypy -p unpack_kwargs
```

**Expected Behavior**

- No errors, the linked repo reproduces this; we would like to be able to attach a concrete TypedDict to a new `kwtypes` property on decorated functions. 
  - We have the decorator working fine, but this could be related to generics of #16525. 
  - In the repro the problem seems to exist even if we remove the `K` generic and use the `QueryKeywordArgs` type as a literal.

**Actual Behavior**

```console
$ mypy -p unpack_kwtypes
src/unpack_kwtypes/usage.py: error: Unpack item in ** argument must be a TypedDict  [misc]
src/unpack_kwtypes/usage.py:7: error: Name "query_db.kwtypes" is not defined  [name-defined]
```

<details>
<summary>Importing and using the TypedDict without the coupling is working fine.</summary>

See the linked repo: [@zevisert/repro-unpack-kwargs](https://github.com/zevisert/repro-unpack-kwargs)

```diff
diff --git a/src/unpack_kwtypes/usage.py b/src/unpack_kwtypes/usage.py
index cb343bb..e568ac4 100644
--- a/src/unpack_kwtypes/usage.py
+++ b/src/unpack_kwtypes/usage.py
@@ -1,10 +1,10 @@
 from typing import TYPE_CHECKING, Unpack
 
-from unpack_kwtypes.source import query_db, Movie
+from unpack_kwtypes.source import query_db, Movie, QueryKeywordArgs
 
 
 async def movie_titles_containing_word_the(
-    **kwargs: Unpack[query_db.kwtypes],
+    **kwargs: Unpack[QueryKeywordArgs],
 ) -> list[Movie]:
     return await query_db("the", **kwargs)
```

</details>

**Your Environment**

- Full nix environment in repo: [@zevisert/repro-unpack-kwargs](https://github.com/zevisert/repro-unpack-kwargs)
- Mypy version used: `mypy 1.8.0 (compiled: yes)`
- Mypy command-line flags: `-p unpack_kwtypes`
- Mypy configuration options from `mypy.ini` (and other config files): ``
- Python version used: `3.11.7`

**Comment by erictraut** [comment]
Mypy is behaving correctly here according to the typing spec and [PEP 692](https://peps.python.org/pep-0692/). What you're asking for is currently disallowed by the typing spec, so mypy is correctly reporting an error.

If you would like to propose changes or additions to the typing spec, the [Python typing discussion channel](https://discuss.python.org/c/typing/32) is a better forum than the mypy issue tracker.

**Comment by zevisert** [comment]
Thanks @erictraut!
