### ISSUE TITLE
mypy warns of redefinition of `InitVar`

### ISSUE THREAD

**Issue by paw-lu** [python/mypy#16816]
**Bug Report**

When using an `InitVar`

**To Reproduce**

[mypy playground link](https://mypy-play.net/?mypy=latest&python=3.11&gist=e53c7272afa4175658f1f36e5330655c&flags=strict)

```python
import dataclasses
from dataclasses import InitVar

@dataclasses.dataclass
class Foo:
    x: InitVar[int] = 1

    def __post_init__(self, x: int) -> None:
        self._x = x

    @property
    def x(self) -> int:
        return self._x

    @x.setter
    def x(self, x: int) -> None:
        self._x = x
```

```
main.py:11: error: Name "x" already defined on line 6  [no-redef]
```

**Expected Behavior**

Since this is essentially

```python
class Foo:
    def __init__(self, x: int) -> None:
        self._x = x

    @property
    def x(self) -> int:
        return self._x

    @x.setter
    def x(self, x: int) -> None:
        self._x = x
```

I _think_ this should be ok in principle. The `InitVar` doesn't get "saved" as an attribute, so it's not a real redefinition?

**Actual Behavior**

mypy warns that the property is a redefinition.

```
main.py:11: error: Name "x" already defined on line 6  [no-redef]
```

**Your Environment**

- Mypy version used: 1.8.0
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.11

---

To be transparent, this is a rough semi-continuation of an old issue I wrote up:

- https://github.com/python/mypy/issues/12877

**Comment by erictraut** [comment]
I think mypy is correct in generating an error here. You are redeclaring the type of the class-scoped symbol `x`, which isn't allowed. Pyright also generates an error for this condition.

If you would like to make the argument that this should be allowed, this would require a change to the [Python typing spec](https://typing.readthedocs.io/en/latest/spec/index.html). You could pitch your idea in the [Python typing forum](https://discuss.python.org/c/typing/32).

**Comment by paw-lu** [comment]
Like as an end user, it seems like mypy is inconsistent here on `InitVars`.

1. If you try to define an attribute with the same name as an `InitVar`, [mypy warns you that the class has no such attribute](https://github.com/python/mypy/issues/12877), treating it as if it doesn't "exist"
2. If you try to have a property of the same name (this issue), mypy warns you that you're refining it , treating it as if does "exist"

**Comment by erictraut** [comment]
@paw-lu, I think you have a reasonable argument to make, but it would be better to discuss this in the general typing forum rather than the mypy issue tracker. Such a change would ideally involve clarification in the typing spec and special-casing in type checker implementations. The typing spec is currently silent on the matter. Unless that's changed, I think type checkers are correct to treat `InitVar` like any other class-scoped symbol.
