### ISSUE TITLE
Enhanced Literal Detection: Allow string type narrowing to literals

### ISSUE THREAD

**Issue by CarliJoy** [python/mypy#16813]
**Feature**

It would be great if mypy could detect and type narrow strings to Literals if this is statically detectable.
I.e. if accessing TypedDict or Enum values

**Pitch**

```python
from typing import TypedDict

class Part(TypedDict, total=False):
    a: int
    b: int

class Full(Part, total=False):
    c: int

def make_part(full: Full) -> Part:
    part: Part = {}
    for k, v in full.items():
        if k in Part.__annotations__:
            part[k]=v  #  error: TypedDict key must be a string literal; expected one of ("a", "b")  [literal-required]
    return part 
```
[MyPy Play](https://mypy-play.net/?mypy=master&python=3.12&gist=43e45ecdb7a1dc1a5b8a664851865567)

Currently there is no way to type this kind of expression without a `# type: ignore`.

It would be nice if mypy could detect that `if k in Part.__annotations__` will narrow `k` to the Literal of all key of `Part`.
Also `if k == "a"` isn't working at the moment, but at least for this I am able to write a `TypeGuard`.

Also if Literals are explicitly defined, we loose this once we are with a loop

Even if the literal is defined explictly, it gets lost in a for loop

```python
def make_part_two(full: Full) -> Part:
    part: Part = {}
    keys: Final = ("a", "b")
    reveal_type(keys)  # tuple[Literal['a']?, Literal['b']?]
    ok = full[keys[0]]
    for key in keys:
        reveal_type(key) # str
        part[key] = full[key]  # literal-required
```

If explicitly given as `keys: tuple[Literal["a", "b"], ...]` it works also in the for loop but I don't want to duplicate these values...

**Comment by CarliJoy** [comment]
related to #13767

**Comment by JelleZijlstra** [comment]
This is a lot of different feature requests in one. You should probably open multiple issues. The one about `__annotations__` might be a step too far, the others are more likely to be OK.

**Comment by CarliJoy** [comment]
I will create different issues an link them here. After this I will close this issue.

**Comment by CarliJoy** [comment]
Opened three different Issues that should tackle this.

**Comment by CarliJoy** [comment]
Note this already works [in pyright](https://pyright-play.net/?pythonVersion=3.12&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgCYAiSAxjALABQDVANgIYDO7UACq3gBREEZSjQA0sMDFbMAvADEZ7YgEoAXAyhaorNZhR162qACM9qQ0zaco8gK7Nm-XngkwpMhUtUaj2quYGDAykxMBQEKwA1sQA%2Bgh8MPzADsx69o4qUAC0AHw8ib7GCXh6LviyUADeAL6a2sC4UFESAG76UCmOAHRIMMQQ7Pzq9cZaSOFRHeXdsbGsKCgeMEhgKOxzRWPbJTAA2lEAurLtUADEWsQg4CB6QiLU%2BDFwEXbs%2BCbEOlDvIKgYzD6VxkAG4oMQAB7CGhkKBrL5gcL8ABErGREmRJmRWSge0B-RAMmyIGIAEc7EgSaRDqMoCSYHYQCgoLsgA)

**Comment by bcmills** [comment]
https://github.com/python/mypy/issues/16813 is another specific case pertaining to this request.
