### ISSUE TITLE
Member Variable with Generic Type used in Structural Pattern Matching does not keep Generic

### ISSUE THREAD

**Issue by matgrioni** [python/mypy#16833]
**Bug Report**

I am trying to reduce memory usage in a python program by swapping out some `set` instances, with an optimized version (most of the instances are empty or have 1 element, so the storage overhead is unnecessary for most instances).

```python
class MyStorageOptimizedSet(MutableSet[T]):
    storage: None | T | set[T]

    def __init__(self, initial: Optional[AbstractSet[T]] = None) -> None:
        if initial is None:
            self.storage = None
        else:
            match len(initial):
                case 0:
                    self.storage = None
                case 1:
                    self.storage = next(iter(initial))
                case _:
                    self.storage = set(initial)

    # Many other methods implemented in-between

    def __contains__(self, obj: object) -> bool:
        match self.storage:
            case None:
                return False
            case set():
                reveal_type(self.storage)
                return self.storage.__contains__(obj)
            case _:
                return self.storage == obj
```

**Expected Behavior**

The expectation is that the revealed type should be only `builtins.set[T]`.

**Actual Behavior**

 Revealed type line actually outputs "note: Revealed type is "Union[builtins.set[Any], builtins.set[T`1]]"".

This actually works perfectly with a very similar class which tries to optimize dict and uses `storage: None | tuple[K, V] | dict[K, V]`. The same construction here with this other type will properly show the expected revealed type. It only appears to happen for set.

**Your Environment**

- Mypy version used: 1.8.0
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.11

**Comment by erictraut** [comment]
Mypy's behavior here is correct.

Within the `__contains__` method, the type of the match subject expression `self.storage` is initially `None | T | set[T]`. After the first `case` statement, this is narrowed to `T | set[T]`. The `set()` class pattern will be matched if the value is of type `set`. A value of type `set[T]` will always match against this pattern. A value of type `T` will also match against this pattern if `T` is a subclass of `set`. So the correct narrowed type in this case is `set[Any] | set[T]`, which is what mypy evaluates. Not surprisingly, pyright produces the same answer in this case.

**Comment by matgrioni** [comment]
I see that makes perfect sense, thanks for explaining.

It seems that type variables in Python only allow for expressing positive constraints rather than negative ones (i.e. cannot say T is anything but a set). So it seems one solution is to bound the TypeVar to Hashable which set obviously does not implement (and is technically more accurate modelling anyway).

I will go ahead and close.
