### ISSUE TITLE
`&`, `|`, and `^` bool stubs incorrect

### ISSUE THREAD

**Issue by jhance** [python/mypy#1684]
Not sure why this is, I would assume with the current code that `__and__` would be used as a fallback.

```
a = True
a &= True
```

should typecheck.

**Comment by gvanrossum** [comment]
Why is '&=' special? What's different with all other binary operators?

**Comment by jhance** [comment]
I just edited it after reading the code in not-11:30 mode, I agree completely now and am not sure why its broken for `&=`

**Comment by gvanrossum** [comment]
Seems the problem really is that `&`, `|` and `^` on bool arguments should be defined to return bools. This can be fixed in the stubs.

**Comment by JukkaL** [comment]
Maybe the methods will have to be overloaded or use a type variable, since when calling with an int argument the result is int, whereas when called with bool the result is bool (similar to int/float).

**Comment by gvanrossum** [comment]
Closing in favor of https://github.com/python/typeshed/issues/649
