### ISSUE TITLE
Update Trove classifiers

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1686]
In setup.py, there's currently this:

``` python
classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: POSIX',
    'Programming Language :: Python :: 3.2',
    'Programming Language :: Python :: 3.3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Topic :: Software Development',
]
```

I wonder if at least the dev status can be bumped up (to what?). We should also add Windows and Python 3.6.

I also wonder if Python 2.7 should be mentioned (IMO it's debatable whether this applies to the Python version you run or the Python version it analyzes).

**Comment by JukkaL** [comment]
Yeah, at least dev status (to alpha?) and windows support should be updated. I'd pick alpha because we have some pretty bad known issues (for example, handling of cyclic imports) and we are planning a pretty big breaking change (strict optional by default).

**Comment by ilevkivskyi** [comment]
The POSIX restriction, development status, and supported Python versions are now updated in `setup.py` so I think this can be closed. We can discuss separately when we want to update status to beta.
