### ISSUE TITLE
Provide a crude, rough-cut search for untyped call sites of a given function or module

### ISSUE THREAD

**Issue by gnprice** [python/mypy#1687]
One thing that can happen in the process of adopting static types on an existing codebase is that you study some code, write down what you think the types are, it passes the type-checker, and then later it turns out that some other code which doesn't have annotations is calling your code with types that you didn't expect. When you rely on the type annotations to understand how the newly-annotated code behaves and make changes to it, this can cause type errors at runtime because it undermines that understanding. This recently bit @tonygrue-dbx in the course of eagerly adopting static types inside a large existing codebase.

Because of this issue, it would be really useful to be able to tell whether a given function you've just annotated (or are studying with the help of its annotations), or even a whole module, has any call sites in untyped code, and if so where they are.

Untyped code can do arbitrarily inscrutable things, so there won't be a perfect solution to this short of applying `--disallow-untyped-defs` (and then some) throughout a codebase. But I think something straightforward could make a good 90% solution, which would still be quite useful!

Some specific thoughts below, mostly on what _isn't_ needed for a still-very-useful first cut.

---

Even something as crude as searching for an identifier that matches the name of the given function -- just filtering out any occurrences within code that has types, which is the bit that requires help from the type-checker -- would probably have a lot of value. It'd often find spurious matches, but so long as the SNR is reasonable, that's fine if you're looking at the output by hand.

A possible UI for invoking such a thing could be something like `mypy --find-untyped-refs=NAME FILES...`, to find references to the function/value with fully-qualified name NAME in files FILES -- in other words, to take whatever `mypy` invocation you'd normally use to type-check your codebase, and add a flag `--find-untyped-refs`. (That's a little clunky, and people may have better suggestions.)

In a very large codebase that's just beginning to adopt static types, where the normal `mypy` invocation may only include a subset of the files, you'd have to instead invoke it on more like the entire codebase. Even if the search takes a few minutes on such a codebase, though, it'd still often be useful, and it will get faster with the advance of `--incremental` and other performance work over time.

For a first cut at this, I think it'd be totally fine if it did all the normal work of type-checking and just also looked out for possible references to NAME, though unless `--check-untyped-defs` is already present it'd have to additionally do some processing of unannotated function bodies. As an optimization, we can probably skip most of the work (maybe stop after semantic analysis?) in this case. In a glorious future where everything we know about the codebase is stored in a [Kythe](https://www.kythe.io/docs/kythe-overview.html) database or in an [hh_server](https://blog.engineyard.com/2014/hhvm-hack-part-5)-like daemon, then we'd use that for a very fast lookup.

**Comment by ilevkivskyi** [comment]
It looks like this is not a high priority for now, we can re-open this later if further requests will appear.
