### ISSUE TITLE
mypyc/lib-rt/setup.py: distutils deprecated in python 3.12

### ISSUE THREAD

**Issue by bryango** [python/mypy#16889]
**Bug Report**

mypyc/lib-rt/setup.py still imports distutils which is removed in python 12.

https://github.com/python/mypy/blob/b956e6a57c4dd36d670097a3eccf7dc092348fec/mypyc/lib-rt/setup.py#L11-L12

This in turn causes test_external.py to fail:

https://github.com/python/mypy/blob/5c5f3ad412bcd0ea510f5918578ed24325829033/mypyc/test/test_external.py#L14-L19

**To Reproduce**

Pytest mypyc/test/test_external.py with python 3.12 and observe the failure.

**Expected Behavior**

The test passes.

**Actual Behavior**

The test fails with log:
```console
Traceback (most recent call last):
  File "/build/source/mypyc/lib-rt/setup.py", line 9, in <module>
    from distutils.core import Extension, setup
ModuleNotFoundError: No module named 'distutils'
```
Full log: https://hydra.nixos.org/build/248681160/nixlog/2

**Your Environment**

- Mypy version used: 1.5.1
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- **Python version used: 3.12**

Nix package build script: https://github.com/NixOS/nixpkgs/blob/e0ba6099df54fc2024053b43ce7522696a558446/pkgs/development/python-modules/mypy/default.nix

```[tasklist]
### Tasks
```

**Comment by AlexWaygood** [comment]
I think you need to install mypy with the "mypyc" extra if you want mypyc-related tests to pass:

https://github.com/python/mypy/blob/5c5f3ad412bcd0ea510f5918578ed24325829033/setup.py#L229

The `mypyc` extra adds `setuptools` as a dependency. With `setuptools` installed, `import distutils` should continue to work, even on Python 3.12.

**Comment by bryango** [comment]
> With `setuptools` installed, `import distutils` should continue to work, even on Python 3.12.

Oh, interesting! I _thought_ setuptools is already installed, but I will have to double-check; I will report back what I find! Thank you very much for the quick response!
