### ISSUE TITLE
(🐞) Modules don't really conform to `Protocol`s do they

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#16890]
test.py
```py
from typing import Protocol

import test2

class P(Protocol):
    def foo(self) -> None: ...

a: P = test2
reveal_type(type(a).foo)  # Revealed type is "def (self: test.P) -> None"
```

test2.py
```py
def foo() -> None: ...

**Comment by hauntsaninja** [comment]
Modules are allowed to conform to protocols! This is a pretty useful feature, Ivan added it in late 2022

**Comment by KotlinIsland** [comment]
> Modules are allowed to conform to protocols! This is a pretty useful feature, Ivan added it in late 2022

Did you have a look at the example in the OP? Protocols are classes, modules are instances. They don't correctly conform.

**Comment by hauntsaninja** [comment]
I did, maybe what should be banned is doing type on Protocol instance...
