### ISSUE TITLE
Python version check not recognized if sys not named sys

### ISSUE THREAD

**Issue by dssd96** [python/mypy#16927]
**Bug Report**

If the `sys` module is aliased as some other name, `sys.version_info` checks are ignored by mypy and lead to errors.

**To Reproduce**

```python
# testfile.py
import sys as something_else

if something_else.version_info >= (3, 10):
    from typing import TypeGuard
```

```shell
$ mypy testfile.py
test.py:5: error: Module "typing" has no attribute "TypeGuard"  [attr-defined]
test.py:5: note: Use `from typing_extensions import TypeGuard` instead
test.py:5: note: See https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-new-additions-to-the-typing-module
Found 1 error in 1 file (checked 1 source file)
```

**Expected Behavior**

This should not be an error since `TypeGuard` is available from `typing` starting at python 3.10.

**Your Environment**

- Mypy version used: 1.8.0
- Python version used: 3.8

**Comment by AlexWaygood** [comment]
PEP 484 [states](https://peps.python.org/pep-0484/#version-and-platform-checking):

> Type checkers are expected to understand simple version and platform checks, e.g.:
> 
> ```py
> import sys
> 
> if sys.version_info[0] >= 3:
>     # Python 3 specific definitions
> else:
>     # Python 2 specific definitions
> 
> if sys.platform == 'win32':
>     # Windows specific definitions
> else:
>     # Posix specific definitions
> ```
> 
> Don’t expect a checker to understand obfuscations like "".join(reversed(sys.platform)) == "xunil".

Emphasis here on "simple" :)

Mypy doesn't have an arbitrary understanding of constructs like this; it has to heavily special-case each version of this kind of condition that it supports. I think we're pretty unlikely to add support for aliasing `sys` in this way anytime soon, I'm afraid :)
