### ISSUE TITLE
There are problematic subtyping relationships with classes that inherit from Any

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1692]
In particular, they are considered to be subtypes of any other type.  This is probably salient elsewhere, but in particular I've seen this come up in the use of `make_simplified_union`.  Here's an example:

``` py
from typing import Any

MissingFromSilentImport = None  # type: Any

class C(MissingFromSilentImport):
    pass

reveal_type(1 and C())
reveal_type(C() and 1)
```

Boolean operators are supposed to return the Union of their input types (because the result could be either one).  But in this case, because `is_subtype(C, int)` is True, the output is just:

```
test.py:8: error: Revealed type is 'builtins.int'
test.py:9: error: Revealed type is 'builtins.int'
```

... which is quite wrong.

It's not obvious to me what the correct fix is here.  Unfortunately, this is a type system level bug, not an implementation one.

**Comment by JukkaL** [comment]
Hmm to be consistent with how `Any` work elsewhere, the union should likely just be `Any` instead of `int`.

**Comment by ddfisher** [comment]
The way `Any` works elsewhere isn't correct, though -- we should talk about that more.

**Comment by rwbarton** [comment]
@ddfisher, can you remind me why the current mypy behavior is wrong? From the point of view of "what can I do with this value", it seems like what I can do with `1 and C()` is anything I can do with both `1` and `C()`, and I can do anything with `C()` (since it inherits from `Any`--is this the real issue?) so that just reduces to what I can do with `1`.

**Comment by elazarg** [comment]
Now the output is 
```
test.py:8: error: Revealed type is 'test.C'
test.py:9: error: Revealed type is 'Union[test.C, builtins.int]'
```
Which looks fine to me.

**Comment by gvanrossum** [comment]
Agreed.
