### ISSUE TITLE
Subclassing generic class with contravariant member

### ISSUE THREAD

**Issue by Tinche** [python/mypy#16929]
Howdy.

Here's something I've been playing around with and I'm unsure if this is a bug or not.

Let's say we have a class with a lot of fields (for the purposes of this example pretend 2 is a lot, but in my specific case it's over 200):

```python
class A:
    a: int
    b: str
```

Now let's assume we have a generic class that requires only one of those fields. We want to statically ensure we don't mistype anything. We define a protocol:

```python
from typing import Protocol

class B(Protocol):
    @property
    def a(self) -> int:
        ...

# Works, since A is a subtype of B.
a: B = A()
```

All good so far. Now we want a base generic class, but the typevar needs to be contravariant since A is a subtype of B, not the other way around.

```python
AnyA_contra = TypeVar("AnyA_contra", bound=A, contravariant=True)


class BaseHandler(Generic[AnyA_contra]):
    settings: AnyA_contra
```

Still OK. Now we decide to subclass this, binding the typevar to the B protocol.

```python
class BHandler(BaseHandler[B]):
    pass
```

Now it doesn't work any more: `Type argument "B" of "BaseHandler" must be a subtype of "A"  [type-var]`. But since the typevar is contravariant, this should work, right? B should be checked to be a supertype of A?

**Comment by erictraut** [comment]
Mypy is correct in generating an error here.

The issue is not the variance of `AnyA_contra`. The problem is `AnyA_contra ` has an upper bound of `A`, which means that the type argument must be a subtype of `A`. `B` is not a subtype of `A`, so the constraint cannot be met.

Python (like most languages) has no way to specify a lower bound on a type variable.

**Comment by Tinche** [comment]
Thanks. I assumed the `bound` parameter would turn into a lower bound if the typevar was contravariant but there's no relation.

Guess this approach is dead in the water.
