### ISSUE TITLE
Mypy does not find lone module .pyi stubs in site-packages

### ISSUE THREAD

**Issue by pwschaedler** [python/mypy#16987]
**Bug Report**

Mypy does not seem to resolve modules that consist of single-file .pyi files that sit directly in site-packages.

For example, the project [pyodbc](https://github.com/mkleehammer/pyodbc) compiles to a single compiled module file, and its accompanying stub file sits with it in site-packages. However, mypy does not recognize this lone .pyi file and instead throws 'Cannot find implementation or library stub for module named "pyodbc"  [import-not-found]'.

**To Reproduce**

```sh
python -m venv .venv
source .venv/bin/activate
pip install mypy==1.8.0 pyodbc==5.1.0
mypy -c 'import pyodbc'
```

**Expected Behavior**

I expect mypy to recognize the module in the same way Python does.

**Actual Behavior**

```
<string>:1: error: Cannot find implementation or library stub for module named "pyodbc"  [import-not-found]
<string>:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.8.0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.12

```sh
$ ls .venv/lib/python3.10/site-packages
_distutils_hack       mypy_extensions-1.0.0.dist-info  __pycache__                  tomli                                                        distutils-precedence.pth                typing_extensions.py
mypy                  pip                              pyodbc-5.1.0.dist-info       tomli-2.0.1.dist-info                                        mypy_extensions.py
mypy-1.8.0.dist-info  pip-23.0.1.dist-info             setuptools                   typing_extensions-4.10.0.dist-info                           pyodbc.cpython-310-x86_64-linux-gnu.so
mypyc                 pkg_resources                    setuptools-65.5.0.dist-info  6c7190bc8b55ffe67f57__mypyc.cpython-310-x86_64-linux-gnu.so  pyodbc.pyi
```

**Comment by cinghiopinghio** [comment]
I have also encountered the same problem.

I have an environment managed by `poetry` (working environment), and
`mypy` is installed in it's own environment (as other tools such as `jedi`) separated from the working environment.
Even though the env is activated, `mypy` do not recognize packages installed in that env.

If I install `mypy` in the same environment, it works as expected.

**Comment by hauntsaninja** [comment]
Closing in favour of https://github.com/python/typing/issues/1333

**Comment by sharethewisdom** [comment]
> Closing in favour of [python/typing#1333](https://github.com/python/typing/issues/1333)

I'm not sure that's the only issue here. I kept getting the error `Cannot find implementation or library stub for module named X [import-not-found]`. The module contains a `py.typed` file, and is installed in the same venv's site-packages directory as mypy.  I then reluctantly added this to `mypy.ini` in the project root to solve the issue on linux:
```ini
[mypy]
mypy_path=${VIRTUAL_ENV}/lib/python3.13/site-packages/
```
But I want this to be portable to Windows.

Sorry if this is misplaced, I've been looking through other issues but could not find a relevant one.

**Comment by hauntsaninja** [comment]
Is mypy installed in that virtual environment? If not, you might need to pass `--python-executable /path/to/python`

(Not sure your thing is related to OP's issue. If what I mention^ isn't your issue and you think there's an actual bug you'll probably need to make a shareable repro)

**Comment by sharethewisdom** [comment]
sorry, it was an editor issue.

I had mypy in the venv, but neovim was using `~/.local/share/nvim/mason/packages/mypy/venv/bin/mypy`.
