### ISSUE TITLE
Feature Request: Ignoring Specific Packages Directly in pyproject.toml

### ISSUE THREAD

**Issue by nh916** [python/mypy#16990]
# Description:

Hello `mypy` Team and Community,

I've been using `mypy` for type checking in my Python projects and it's been an invaluable tool for maintaining code quality. However, I've encountered a situation where I frequently need to suppress type checks for specific third-party packages, such as `shopify`. Currently, to avoid `mypy` errors for these packages, I use `# type: ignore` comments after importing them.

I'm wondering if there's a way or a planned feature to specify ignored packages directly within `pyproject.toml`, like this:

```toml
[tool.mypy]
ignore_packages = ["shopify"]
```

This feature would allow for a cleaner and more centralized type checking configuration, especially for projects already utilizing `pyproject.toml` for other tooling configurations. It would also improve code maintainability by avoiding the need for `# type: ignore` comments throughout the codebase for imports and just have all untyped foo packages ignore just in one location and that is it.

**Comment by Hnasar** [comment]
Have you tried this?
```ini
[mypy-shopify.*]
ignore_errors = true
```

If that is still sufficient, this would prevent mypy from even looking at the files:
```ini
[mypy-shopify.*]
follow_imports = skip
```

**Comment by nh916** [comment]
I've tried this in `pyproject.toml`

```toml
[mypy-shopify.*]
ignore_errors = true
```

and every time I try to run mypy via `$ mypy src/` I get this warning in the terminal
`pyproject.toml: Invalid initial character for a key part (at line 78, column 15)`

**Comment by hauntsaninja** [comment]
Hnasar is right, but the config syntax they show is for mypy.ini

For pyproject.toml you can use
```
# do not look at shopify and turn anything originating from it into Any
[[tool.mypy.overrides]]
module = ["shopify.*"]
follow_imports = "skip"
```
as mentioned in the documentation
