### ISSUE TITLE
(🐞) `Callable`s are joined into `builtins.function`

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#17017]
```py
from typing import Callable

class C:
    def __init__(self, i: int=1): ...

c1: Callable[[], object] = C
c2: Callable[[int], object] = C
reveal_type(c1 if bool() else c2)  # Revealed type is "builtins.function"
```
It should be joined into... something else, either `object` or `Callable[..., object]` or something.

**Comment by hauntsaninja** [comment]
Duplicate of https://github.com/python/mypy/issues/10740

**Comment by KotlinIsland** [comment]
@hauntsaninja That issue is regarding joining `() -> int` and `(int =) -> int` into `() -> int`.

This issue is regarding how `Callable`s are joined into `function`. Which sometimes does make sense (i.e. when you are using functions), nut makes no sense when you are using some other type of `Callable`, like in my example where I am using `type`s
