### ISSUE TITLE
[Feature] Allow mypy run the code as typescript

### ISSUE THREAD

**Issue by redradist** [python/mypy#17011]
**Feature**

mypy is awesome typechecker, but it has drawback that I should first run mypy and then python command.
It would be useful to add possibility to run code using mypy, something like this:
```console
mypy run -m <module_name> <args>
```

Also it sometime required to has strictly typed module like in case of typescript *.ts file.
It is possible to do the similar thing in mypy by adding extension *.mypy or just simply *.my.

It would be the similar with TypeScript where *.ts are strictly checked, and *.js files only some annotated functions and classes

**Comment by AlexWaygood** [comment]
> mypy is awesome typechecker

Thanks! Really glad you're a fan :-)

> it has drawback that I should first run mypy and then python command. It would be useful to add possibility to run code using mypy, something like this:
> 
> ```
> mypy run -m <module_name> <args>
> ```

I'm afraid this is well out of scope for our project. We type check Python code; we never run Python code, and I don't think we'd ever consider doing so.

> Also it sometime required to has strictly typed module like in case of typescript *.ts file. It is possible to do the similar thing in mypy by adding extension *.mypy or just simply *.my.
> 
> It would be the similar with TypeScript where *.ts are strictly checked, and *.js files only some annotated functions and classes

Unlike with JavaScript and TypeScript, typed Python is the same language as untyped Python. This was a deliberate decision made in the early days of Python's typing system, and much of the ecosystem depends on easy interoperability between the two kinds of Python at runtime. This isn't something we'd ever consider, I'm afraid.

However, the good news for you is that mypy is very configurable! It's perfectly possible to have certain modules that are checked more strictly than other modules: https://mypy.readthedocs.io/en/stable/config_file.html#per-module-and-global-options

**Comment by redradist** [comment]
> *.mypy or just simply *.my

I suggest the *.mypy (*.my) only for more strict checking, just like it was done in TypeScript.
I know that typed and untyped python is the same language, but I suggest to add extension to have only typed code in *.mypy file and in *.py (mixed code, typed and untyped)

**Comment by AlexWaygood** [comment]
@redradist, feature proposals of that magnitude should really be discussed at https://discuss.python.org/c/typing/ rather than the mypy issue tracker. Mypy is just one of several Python type checkers, and a feature like this would impact all Python type checkers :-)
