### ISSUE TITLE
1.9 Regression: __hash__ method in attrs class is ignored

### ISSUE THREAD

**Issue by Hnasar** [python/mypy#17015]
**Bug Report**
mypy is ignoring a manually-written `__hash__` method in an attrs class.
Bisect points to 91be28552e062601adc2a07075263994c102d5cc causing the regression. cc @Tinche 
Possibly reported already in a comment here? https://github.com/python/mypy/pull/16556#issuecomment-1987116488

**To Reproduce**

```python
import attrs
from typing import reveal_type

@attrs.define()
class A():
    name: str = attrs.field()
    def __hash__(self) -> int:
        return hash(self.name)

reveal_type(A.__hash__)
```

**Expected Behavior**

```console

$ py -m mypy --strict foo.py  # 1.8
foo.py:10: note: Revealed type is "def (self: foo.A) -> builtins.int"
$ py foo.py
Runtime type is 'function'
```

**Actual Behavior**

```console
$ py -m mypy --strict foo.py  # 1.9
foo.py:10: note: Revealed type is "None"
$ py foo.py
Runtime type is 'function'
```

**Your Environment**

- Mypy version used: 1.9.0
- Mypy command-line flags: n/a
- Python version used: 3.12
- attrs version: 23.2.0

**Comment by Tinche** [comment]
I'll take this.
