### ISSUE TITLE
Mypy fails when the returned type is a class instance and the type annotation is a union

### ISSUE THREAD

**Issue by OmriTreidel** [python/mypy#17020]
**Bug Report**

Mypy fails when the returned type is a class instance and the type annotation is a union

(A clear and concise description of what the bug is.)

**To Reproduce**

```python
from typing import Type

class A:
    pass


class B:
    pass


def create_instance(input_class: Type[A | B]) -> A | B:
    return input_class()


def create_instance_of_A(input_class: Type[A | B]) -> A:
    instance_of_input = input_class()
    print(instance_of_input)
    instance_of_A = create_instance(A)
    print(type(instance_of_A))
    return instance_of_A

a = create_instance_of_A(B)
```
[gist](https://gist.github.com/mypy-play/2ccf14fdda3a22d7e2e90703cbb7aa1f)
[playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=6b81c4ab7b35c8a4d77783162709c2ef)

**Expected Behavior**
mypy should not have failed. The returned type is compatible type annotation 

**Actual Behavior**

**Your Environment**

mypy failed to detect that class A is in the union A |  B

main.py:20: error: Incompatible return value type (got "A | B", expected "A")  [return-value]

- Mypy version used: 1.9.0
- Mypy command-line flags: Gist online
- Mypy configuration options from `mypy.ini` (and other config files): Gist online
- Python version used: 3.12

**Comment by JelleZijlstra** [comment]
Mypy is correct here. Your type annotations indicate that the function can only return `A`, but also that it may return either `A` or `B`. A signature like `def create_instance(input_class: Type[A | B]) -> A | B:` does not mean that given an input `type[A]`, the function returns `A`; it means that the function accepts either `type[A]` or `type[B]` and returns either `A` or `B`, with no relation between the two.

You may want to use overloads or bound type variables, e.g.:

```
AB_T = TypeVar("AB_T", bound=Union[A, B])

def create_instance(input_class: Type[AB_T]) -> AB_T:
```

**Comment by OmriTreidel** [comment]
@JelleZijlstra  Thanks for the quick reply. The function `create_instance_of_A` can only return `A`  since the return type doesn't depend on the input at all. 

When I tried your suggestion mypy raised another error is `create_instance` [playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=e16a7b92b1e13989599fc8ced6fa59fc)

I also tried ```def create_instance(input_class: Type[AB_T]) -> Union[A | B]:``` which results in the same error as the original

**Comment by JelleZijlstra** [comment]
> The function `create_instance_of_A` can only return `A` since the return type doesn't depend on the input at all.

That's not what your type annotations say. It returns what `create_instance()` returns, and that function is annotated as returning `A | B`.

> When I tried your suggestion mypy raised another error is `create_instance` [playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=e16a7b92b1e13989599fc8ced6fa59fc)

That is unfortunate and possibly a bug. It works if you use a constrained TypeVar instead: https://mypy-play.net/?mypy=latest&python=3.12&gist=d551418a4bdd4c41c1b6a67de60a710e

**Comment by OmriTreidel** [comment]
@JelleZijlstra thanks a lot for your assistance. your recent suggestion work very well.
