### ISSUE TITLE
1.10.0 Release Tracking Issue 

### ISSUE THREAD

**Issue by svalentin** [python/mypy#17064]
Time for the next release of MyPy!
I will be cutting the release branch today and try to release by the end of the month.

Please comment here if there are any outstanding PRs you wish to ensure are in the release branch. I will cherry-pick them if they are not merged before I cut the branch.

**Comment by gdippolito** [comment]
Hello! thanks for the heads up. 
Would [this](https://github.com/python/typeshed/pull/11576) be included in the mypy 1.10 release? 
Thanks

**Comment by cdce8p** [comment]
> Would [this](https://github.com/python/typeshed/pull/11576) be included in the mypy 1.10 release?

Yes. The last typeshed sync was a week ago. The source commit is: https://github.com/python/typeshed/commit/ff7caa30e29d9c9467b1ba0007764c65c0b44a5c (merged 2024-03-16).
The typeshed bump for mypy: https://github.com/python/mypy/commit/cf221bdc2cefc539a0b278c10ed6bde0350f370e

**Comment by mr-c** [comment]
Cool! Feel free to @ mention me in future release planning issues, so I can do a test build in Debian prior to the release :-P Maybe that (and/or formal release candidates) can avoid some of the point releases

**Comment by mr-c** [comment]
@svalentin I would request that https://github.com/python/mypy/pull/17066 is included in 1.10.0; thanks!

**Comment by cdce8p** [comment]
Would be great if #17068 could be included as well.

**Comment by md384** [comment]
I'd appreciate if https://github.com/python/mypy/pull/16604 could be reviewed and included in an upcoming release (possibly this one).

**Comment by svalentin** [comment]
Hi everyone! Really sorry, I got carried away with other things. I'll move to doing the release from current master, commit `5161ac2e5b73dc7597536eb4444219868317e5d9` for the next release which will include all the PRs mentioned in the comments above.

**Comment by svalentin** [comment]
Release branch - https://github.com/python/mypy/tree/release-1.10

Version bumped on master to 1.11.0+dev in https://github.com/python/mypy/commit/d6d9d8cd4f27c52edac1f537e236ec48a01e54cb

**Comment by hauntsaninja** [comment]
Could be good to cherry pick https://github.com/python/mypy/pull/16604 :-)

**Comment by svalentin** [comment]
Merged https://github.com/python/mypy/pull/17150 with an initial draft for the changelog for release 1.10.
Please take a look or make changes if there's anything you like to point out in the blog post for the next release!

**Comment by tmke8** [comment]
I think #16926 is in the wrong section in the changelog. It's under "mypyc improvements" but I don't think it has anything to do with that. It might also be worthwhile to specifically highlight #16926 as a first step towards implementing PEP 695.

**Comment by svalentin** [comment]
Mypy 1.10 released!
https://mypy-lang.blogspot.com/2024/04/mypy-110-released.html

**Comment by svalentin** [comment]
Closing this as completed. Please leave a comment if there are any issues with the release and will reopen!

**Comment by hauntsaninja** [comment]
I'm planning on cutting a 1.10.1 that includes https://github.com/python/mypy/pull/17422
