### ISSUE TITLE
MyPy incorrectly evaluates a boolean expression as a union type.

### ISSUE THREAD

**Issue by govindrai** [python/mypy#17097]
**Bug Report**

MyPy incorrectly evaluates a boolean expression as a union type.

**To Reproduce**
```
from dataclasses import dataclass
import typing

@dataclass(frozen=True)
class A:
    a_property: typing.Optional[str] = None

@dataclass(frozen=True)
class B:
    b_property: typing.Optional[bool] = None
    
a = A()
b = B(b_property=a and a.a_property != "value")
```

[Playgound](https://mypy-play.net/?mypy=latest&python=3.9&gist=de8fc616154603c99594684108b23ca0)
[Gist](https://gist.github.com/mypy-play/de8fc616154603c99594684108b23ca0)

**Expected Behavior**
I expect mypy to not complain. The expression should evaluate to a bool only. 

**Actual Behavior**
```
main.py:12: error: Argument "b_property" to "B" has incompatible type "Union[A, bool]"; expected "Optional[bool]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.9.0
- Python version used: 3.9.18

**Comment by decorator-factory** [comment]
:thinking: If `a` is always truthy, why use it in `and`?

**Comment by govindrai** [comment]
My contrived example has this drawback, but that's a bit orthogonal to the issue. But you can imagine that a is not always truthy. I can update the code example, though.

**Comment by govindrai** [comment]
Updated the code example and playground/gist urls

**Comment by decorator-factory** [comment]
If `a` isn't always truthy, then `a and a.a_property != "value"` is sometimes a `bool` is sometimes an  `A`

**Comment by govindrai** [comment]
Could you explain more into how it's sometimes A?

**Comment by decorator-factory** [comment]
> If a is falsy (e.g., None, False, 0, an empty string, etc.), the expression will short-circuit and return False without evaluating a.a_property != "value". In this case, the result of the expression will be False.

A value of type `A` itself could be falsy. In that case, the expression will evaluate to `a` (it will not be converted to `False`)
```py
>>> class A:
...     def __bool__(self):
...         return False
... 
>>> A() and 42
<__main__.A object at 0x7cff8cf65c10>
>>> 
```

Here's another example:
```py
from dataclasses import dataclass

class A:
    a_property = "value"

@dataclass(frozen=True)
class B:
    b_property: bool | None = None

def f(a: A | None) -> None:
    b = B(b_property=a and a.a_property != "value")
    # error: Argument "b_property" to "B" has incompatible type "A | bool | None"; expected "bool | None"
```
`mypy` considers it possible here that a _subclass_ of `A` can redefine `__bool__` in such a way that it can be falsey. If `A` was defined as either of these, mypy wouldn't complain:
```py
# option 1
@final
class A: ...

# option 2
class A:
    ...
    def __bool__(self) -> Literal[True]:
        return True
```

**Comment by govindrai** [comment]
Ahhh, python evaluates expressions differently when the operands are boolean vs non boolean. Thanks for giving me this lesson in python. Been working with python for a loooong time and never realized this..

**Comment by decorator-factory** [comment]
It evaluates them in the same way, whether the operands are boolean or not:
```py
result = (expr_a) and (expr_b)
# same as
result = (expr_a)
if result:
    b = (expr_b)
    if b:
        result = b
```
