### ISSUE TITLE
Ternary and walrus operator (assignment expression) breaks Unpack

### ISSUE THREAD

**Issue by jaycle** [python/mypy#17104]
**Bug Report**

Noticed that Unpack + TypedDict was not type checking in every place where there was a call to this function when upgrading from mypy 1.4.1 (with Unpack feature). After seeking to minimally reproduce, I discovered that it was the body of the function containing an assignment expression together with an if/else expression that was breaking the behavior of `Unpack`. I realize that 1.4.1 is somewhat old, and I didn't bisect too far, but noticed that 1.8.0 and 1.9.0 exhibit this same behavior. The error(s) you end up with (error: Argument "a" to "fn" has incompatible type "int"; expected "ConfigA"  [arg-type]) made for some challenging troubleshooting, since this function body was quite large.

**To Reproduce**

```python
from typing import TypedDict, Unpack

class ConfigA(TypedDict):
    a: int
    b: str
    
def my_fn(i: int, **kwargs: Unpack[ConfigA]) -> int:
    reveal_type(kwargs)
    # if v := i:
    #    return v
    # return 0
    return v if (v := i) else 0

my_fn(1, a=1, b="two")
```

Playground: https://mypy-play.net/?mypy=master&python=3.12&gist=92996639a96739714a2a1ab0995be342
Gist: https://gist.github.com/mypy-play/92996639a96739714a2a1ab0995be342

**Expected Behavior**

- Should type check correctly.
- Reveal type should be `Revealed type is "TypedDict('__main__.ConfigA', {'a': builtins.int, 'b': builtins.str})"`
- Uncomment the if statement solution, and this works

**Actual Behavior**

- Function call fails due to incorrect arguments
- Reveal type shows `Revealed type is "builtins.dict[builtins.str, TypedDict('__main__.ConfigA', {'a': builtins.int, 'b': builtins.str})]"`

**Your Environment**

- Mypy version used: 1.8.0-1.9.0
- Python version used: 3.12

**Comment by ilevkivskyi** [comment]
Works on current master.
