### ISSUE TITLE
1.9.0: change in tagging convention?🤔

### ISSUE THREAD

**Issue by kloczek** [python/mypy#17116]
Looks like nev eversion has been tagged as `<version>` when all prev versions been tagged as `v<version>`.
Is it just mistake/typo or from now will be new tagging convention? 🤔
I'm asking because my automation relies on exact tagging convention ..

**Comment by tmke8** [comment]
related comment: https://github.com/python/mypy/issues/16843#issuecomment-1994342589

**Comment by JelleZijlstra** [comment]
cc @jhance as release manager.

I'm assuming this is an accident so I tagged v1.9.0 pointing to the same commit as 1.9.0 and pushed it to the repo (https://github.com/python/mypy/releases/tag/v1.9.0, https://github.com/python/mypy/releases/tag/1.9.0).
