### ISSUE TITLE
INTERNAL ERROR: maximum semantic analysis iteration count reached on self-referential union

### ISSUE THREAD

**Issue by kmurphy4** [python/mypy#17132]
**Crash Report**

Under some specific conditions, `mypy` crashes when creating type aliases for unions with self-referential variants.

Specifically, both of these work fine:
```python
X: ty.TypeAlias = ty.Union[
    ty.Set["X"],
    ty.Sequence["X"],
]

Y: ty.TypeAlias = ty.Union[
    ty.Sequence[ty.Optional["Y"]],
]
```
but this crashes:
```python
Z: ty.TypeAlias = ty.Union[
    ty.Set["Z"],
    ty.Sequence[ty.Optional["Z"]],
]
```
with
```python
main.py: error: INTERNAL ERROR: maximum semantic analysis iteration count reached
```

**To Reproduce**

https://mypy-play.net/?mypy=1.9.0&python=3.12&flags=show-traceback&gist=5f48179cab35cd594aca11d797bf530d

**Comment by ilevkivskyi** [comment]
It is interesting that it looks like a slightly different version
```python
Z = ty.Union[
    ty.Set[ty.Optional["Z"]],
    ty.Sequence[ty.Optional["Z"]],
]
```
hangs indefinitely, while eating memory.
