### ISSUE TITLE
Values of TypedDict typed as `object`

### ISSUE THREAD

**Issue by Garrett-R** [python/mypy#17146]
**Bug Report**

The values of a TypedDict are just typed as `object` it seems.

**To Reproduce**

[Mypy playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=9ce3f09d740d30320fab4fe30b046169), but repeated here for convenience:

```py
from typing import TypedDict

class _Foo(TypedDict):
    a: int
    b: int

xx: _Foo = {'a': 1, 'b': 2}
yy: list[int] = list(xx.values())
```

**Expected Behavior**

It would be nice if Mypy could recognize that the values are a union of the data types.  In this case, there's just `int`, so I'd expect `list(yy.values())` to have type `list[int]`.

**Actual Behavior**

```py
main.py:8: error: Argument 1 to "list" has incompatible type "dict_values[str, object]"; expected "Iterable[int]"  [arg-type]
```

**Your Environment**

- Mypy version used: 1.9.0
- Mypy command-line flags: _(none)_
- Mypy configuration options: _(none)_
- Python version used: 3.12

**Comment by erictraut** [comment]
What you're suggesting wouldn't be type safe. A `TypedDict` is a structural type, and a value that is compatible with a `TypedDict` can have additional items that are not specified in the `TypedDict`'s definition. These additional items could have values of any type, so the type of `xx.values()` must be `object`.

There is a draft [PEP 728](https://peps.python.org/pep-0728/) that proposes to add the concept of a "closed" TypedDict to the type system. Such a TypedDict would enforce that no other items are present — or that any additional items must have a value whose type is limited to a specified upper bound constraint. This will allow a type checker to safely evaluate a narrowing return type for the `values` method.

**Comment by Garrett-R** [comment]
@erictraut ah got it, thanks for explaining!
