### ISSUE TITLE
Type of a function NOT allowed to raise an exception

### ISSUE THREAD

**Issue by tobiasBora** [python/mypy#17140]
**Feature**

It would be great to provide a mechanism to specify that a function is NOT allowed to raise an exception. For instance if we consider
```
def foo(a:int, b:int) -> float:
    return a / b
```
we might expect `foo` to always return a float… Yet sometimes it might return an Exception like in
```
foo(42, 0)
```

It would be great instead to specify that a function is NOT allowed to raise an exception. I'm not sure what syntax would be better, but maybe a syntax like:
```
def foo(a:int, b:int) -> !float:
    return a / b
```
or (maybe more compatible with python's syntax) via something like: 
```
from typing import NewType

def noException(t):
    return t

def foo(a:int, b:int) -> noException(float):
    return a / b

foo(42, 0)
```

**Pitch**

Exceptions can easily be forgotten, and may completely crash a program (say, I assume that `foo["bar"]` always exists, but in a rare case it might not). Letting the programmer check that no exception can occur would be great.

This can be seen, I guess, as a particular case of https://github.com/python/mypy/issues/1773 that tries to list all exceptions that a function may raise.

**Comment by Viicos** [comment]
This discussion would be better suited in Python [typing discussion forum](https://discuss.python.org/c/typing/32) (in particular, see [this thread](https://discuss.python.org/t/extend-type-hints-to-cover-exceptions/23788)) or https://github.com/python/typing/discussions
