### ISSUE TITLE
Error when using Tuple[Any] as a parameter type, but ok for List[Any] and Sequence[Any]

### ISSUE THREAD

**Issue by SizzlingVortex** [python/mypy#1715]
The following causes mypy to give an error when I try to send a tuple with "any" type of values to a function that accepts a tuple with "any" type of values:

```python
from typing import Tuple, Any


def func(results: Tuple[Any]) -> None:
    pass


if __name__ == "__main__":
    my_tuple = (1, "2", 3, 4.0)
    func(my_tuple)
```
The error message I get from running the above code through mypy is:

> error: Argument 1 to "func" has incompatible type "Tuple[int, str, int, float]"; expected "Tuple[Any]"

Now when I change the logic to use a list, I successfully will not get any errors:

```python
from typing import List, Any


def func(results: List[Any]) -> None:
    pass


if __name__ == "__main__":
    my_list = [1, "2", 3, 4.0]
    func(my_list)
```

Also no errors for using a generic "sequence" as the parameter type and then passing a tuple as the argument:
```python
from typing import Sequence, Any


def func(results: Sequence[Any]) -> None:
    pass


if __name__ == "__main__":
    my_tuple = (1, "2", 3, 4.0)
    func(my_tuple)
```

**My Specs:**
Python 3.5.1
mypy-lang 0.4.2

**Comment by JukkaL** [comment]
`Tuple[Any]` is a single-item tuple with an arbitrary item. Have you tried using a variable-length tuple type: `Tuple[Any, ...]` (with literal `...`)?

**Comment by SizzlingVortex** [comment]
Hey JukkaL,

Thanks for your reply. It looks like I misunderstood the use of `Any` here, so as per your suggestion, I  successfully did not get any error messages when using `Tuple[Any, ...]`. However, that brings up the question of why changing `Tuple[Any]` to `List[Any]` and `Sequence[Any]` didn't raise any errors in the original example I posted?

**Comment by JukkaL** [comment]
`List[x]` and `Sequence[x]` are always variable-length. `Tuple` is the only fixed-length container.

**Comment by SizzlingVortex** [comment]
Got it now. Thanks for the clarification!
