### ISSUE TITLE
Mypy.parse needs error messages

### ISSUE THREAD

**Issue by dibrinsofor** [python/mypy#17190]
**Bug Report**

I am trying to parse some python code with `mypy.parse` but this current version does not seem to return compile errors or any errors in general, just an empty mypy file. I have had no issue using this to parse other blocks of code but this particular one fails and I am not sure why.

**To Reproduce**

```python

from mypy.options import Options
from mypy.errors import Errors
from mypy.parse import parse

deprecated_wrapper = '''
def deprecated(*, version: str, version_removed: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]:
    """Mark a function as deprecated.

    Using the decorated (old) function will result in a warning.
    """

    def __wrapper(func, *args, **kwargs):
        """Warn the user, and then proceed."""
        warnings.warn(
            "{:s}.{:s}\n\tDeprecated as of librosa version {:s}."
            "\n\tIt will be removed in librosa version {:s}.".format(
                func.__module__, func.__name__, version, version_removed
            ),
            category=FutureWarning,
            stacklevel=3,  # Would be 2, but the decorator adds a level
        )
        return func(*args, **kwargs)

    return decorator(__wrapper)
'''

options = Options()
errors = Errors(options)

def parse_str(stub: str):
    return parse(stub, '', None, errors, options)

## issue
print(parse_str(deprecated_wrapper)) ##returns an empty Mypyfile and I am not sure why
```

**Expected Behavior**

```python
MypyFile(...) # or some descriptive error message
```

**Actual Behavior**
```python
MypyFile:1(\n  )
```

**Your Environment**

- Mypy version used: mypy 1.8.0 (compiled: yes)
- Python version used: Python 3.11.5
- Operating system and version: MacOS Ventura 13.4

**Comment by dibrinsofor** [comment]
The errors object is modified on each call to parse, so I have modified parse_str

```python
def parse_str(stub: str) -> Union[MypyFile, str]:
    options = Options()
    errors = Errors(options)

    ast = parse(stub, 'test', None, errors, options)

    if 'test' not in errors.error_info_map:
        return ast, ''
    else:
        return ast, errors.error_info_map['test'][0].message
```

I get an "unterminated string literal" error message but each line in the source code seems to be terminated. I am not sure why.

**Comment by hauntsaninja** [comment]
With latest mypy, consider passing `raise_on_error=True`? Don't think mypy really promises any API here, but feel free to open a PR.

Your escaping is wrong, causing your string literal to be unterminated. This is just the error `ast.parse` will give you too, doesn't even need to involve mypy

**Comment by dibrinsofor** [comment]
@hauntsaninja would you mind pointing out where the wrong escaping happens?

**Comment by hauntsaninja** [comment]
\n

**Comment by JelleZijlstra** [comment]
Possible solution is to use a raw string. The `\n` inside the docstring inside the code sample gets expanded into a newline too early.
