### ISSUE TITLE
Call `tuple` on a known length `tuple[int, int]` would lose its length

### ISSUE THREAD

**Issue by DanielYang59** [python/mypy#17237]
**Bug Report**

Call `tuple` on a known length `tuple[int, int]` would lose its length.

**To Reproduce**

```python
old_tuple: tuple[int, int] = (1, 1)

assert len(old_tuple) == 2

new_tuple: tuple[int, int] = tuple(old_tuple)
```

**Expected Behavior**

I would expect calling `tuple` on a known-length tuple would maintain its length.

**Actual Behavior**

```
error: Incompatible types in assignment (expression has type "tuple[int, ...]", variable has type "tuple[int, int]")  [assignment]
```

**Your Environment**

- Mypy version used: v1.10.0 (pre-commit/mirrors-mypy)
- Mypy command-line flags: No
- Mypy configuration options from `mypy.ini` (and other config files): No
- Python version used: Python 3.12.3

**Comment by erictraut** [comment]
The `tuple` constructor is defined as follows in the `builtins.pyi` typeshed stub:

```python
class tuple(Sequence[_T_co]):
    def __new__(cls, iterable: Iterable[_T_co] = ..., /) -> Self: ...
    ...
```

It does not preserve the length of the original input tuple, so I think mypy is doing the right thing here.

The typeshed definition could be augmented with an overload for `__new__`.

```python
class tuple(Sequence[_T_co]):
    @overload
    def __new__[*Ts](cls: type[tuple[*Ts]], iterable: tuple[*Ts]) -> tuple[*Ts]: ...
    @overload
    def __new__(cls, iterable: Iterable[_T_co] = ..., /) -> Self: ...
```

**Comment by DanielYang59** [comment]
Thanks for your reply and the input!

Defining a `__new__` might be too overkill for my use case and I might just `cast` the proper type instead.
