### ISSUE TITLE
Support `Unpack` with `dict` for keyword arguments: `**kwargs: Unpack[dict[Literal["test"], ...]]`

### ISSUE THREAD

**Issue by intgr** [python/mypy#17241]
**Bug Report**

Mypy has support for declaring kwargs as `**kwargs: Unpack[SomeTypedDict]`.

However, sometimes for dicts with uniform value types, it's more convenient to declare them in terms of `dict[Literal["key", "another"], ...]`. Other times it's a pragmatic work-around to the lack of support for `@final` declaration for `TypedDict` (https://github.com/python/mypy/issues/7981).

**To Reproduce**

This should pass mypy checking:

```python
from typing import Literal, Unpack

def example(**kwargs: Unpack[dict[Literal["test"], int]]):
    #                        ^^^^
    pass

example(test=123)
```

[Playground link](https://mypy-play.net/?mypy=1.10.0&python=3.12&gist=2d2754972e5c3e34b2cf9f9e7f93642f)

**Actual Behavior**

Rejected by mypy with the following error:

> error: Unpack item in ** argument must be a TypedDict  [misc]

**Your Environment**

- Mypy version used: 1.10.0
- Python version used: 3.12.3

**Comment by intgr** [comment]
FWIW, Pyright also rejects this: https://pyright-play.net/?pyrightVersion=1.1.353&pythonVersion=3.12&pythonPlatform=Linux&strict=true&locale=en&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAySMApiAIYA2ANFAKooLkDGA1gFDsAmJwUJAD3LZKJABQAqCawDu5EGgDOALnqMWrANpckzGJqKkKlTQCJSimKYC6tVDGvWAlMvZR3UJosWdBwhKJiFjAAvACMAEwAzE7sQA

**Comment by intgr** [comment]
Also when implementing this, it might be useful to allow `Mapping/MutableMapping` in these contexts as well:

```python
from collections.abc import Mapping
from typing import Literal, Unpack

def example(**kwargs: Unpack[Mapping[Literal["test"], int]]):
    #                        ^^^^^^^
    pass

example(test=123)
```

**Comment by AlexWaygood** [comment]
I think you'd probably need to write a PEP if you want to expand the use of Unpack in this way

**Comment by erictraut** [comment]
What you're proposing here is not allowed by the [typing spec](https://typing.readthedocs.io/en/latest/spec/callables.html#callables) currently. If you want to see something like this, you would need to extend the typing spec, probably through a new PEP as @AlexWaygood  suggests. If you're interested in pursuing this, I recommend starting a discussion in the [Python typing forum](https://discuss.python.org/c/typing/32) to see if you can gain support and consensus for such an idea.

**Comment by intgr** [comment]
Posted to typing forum: https://discuss.python.org/t/proposal-support-unpack-dict-for-typing-keyword-arguments/53380
