### ISSUE TITLE
Not recognizing type definitions

### ISSUE THREAD

**Issue by miedzinski** [python/mypy#1724]
Consider quite simple program:

```
from typing import T, KT, VT, T_co, V_co, VT_co, T_contra
```

```
$ python bug.py
$ mypy bug.py
bug.py:1: error: Module has no attribute 'T'
bug.py:1: error: Module has no attribute 'KT'
bug.py:1: error: Module has no attribute 'VT'
bug.py:1: error: Module has no attribute 'T_co'
bug.py:1: error: Module has no attribute 'V_co'
bug.py:1: error: Module has no attribute 'VT_co'
bug.py:1: error: Module has no attribute 'T_contra'
```

`AnyStr` is defined the same way next to these definitions, but mypy handles it well.

I am running Python `3.5.0` and mypy feaabde9c7e28d5ad8c3392c839043173705053a checkout. `0.4.2` outputs this error as well.

**Comment by kirbyfan64** [comment]
Pretty sure typeshed prefixes all of those with underscores...

**Comment by miedzinski** [comment]
Indeed it does, but shouldn't mypy use typing module if available?

**Comment by gvanrossum** [comment]
This is intentional. As a comment in typing.py mentions, those type variables are not for export. Anything not defined by PEP 484 should not be considered part of the typing module.
