### ISSUE TITLE
Disable third party imports only

### ISSUE THREAD

**Issue by Ryang20718** [python/mypy#17257]
**Documentation**

Hi, is there a setting to disable all third party import checks but still follow imports on your repo code?

I found this page https://mypy.readthedocs.io/en/stable/running_mypy.html#following-imports, but it wasn't clear to me if there is such an option

**Comment by hauntsaninja** [comment]
No, I don't think so. You can always run mypy in a clean virtual environment though.

In general, I don't recommend futzing with follow imports settings. If you're interested in this for performance reasons, usually you can just change follow imports for one or two specific third party packages (using the per-module options in config file)
