### ISSUE TITLE
Claim the name "mypy" on the python package index?

### ISSUE THREAD

**Issue by haakenlid** [python/mypy#1725]
It would be nice if `pip install mypy` would actually install mypy instead of an abandoned wsgi framework, that has no documentation and (as far as I can tell) no users or maintainers. https://pypi.python.org/pypi/mypy/

It looks like it's possible to submit a claim for the name here https://sourceforge.net/p/pypi/support-requests/

**Comment by gvanrossum** [comment]
Believe me, we tried. PyPI is not affiliated with sourceforge.
