### ISSUE TITLE
cannot apply `@asynccontextmanager` to a function that uses `TypeVarTuple`

### ISSUE THREAD

**Issue by ZeeD** [python/mypy#17278]
I _think_ this is a bug in mypy.
[mypy-play.net](https://mypy-play.net/?mypy=latest&python=3.12&flags=strict&gist=b1a2a58ca58544f4ddab3f9451cf6d71)

I want to properly annotate a generic async context manager to preserve the types of the *args in the returned value.

```python
Ts = TypeVarTuple('Ts')

@asynccontextmanager
async def fun(*args: *Ts) -> AsyncIterator[tuple[*Ts]]:
    ...
```
but this snippet generate the following error

```txt
main.py:11: error: Argument 1 to "asynccontextmanager" has incompatible type "Callable[[VarArg(*Ts)], AsyncIterator[tuple[*Ts]]]"; expected "Callable[[VarArg(Never), KwArg(Never)], AsyncIterator[Never]]"  [arg-type]
```

The function types - without the `@asynccontextmanager` - seems to work correctly

**Comment by sterliakov** [comment]
Fun fact: don't use empty body for testing this, `asynccontextmanager` seems to reveal many independent bugs...

```python
from contextlib import asynccontextmanager
from typing import AsyncIterator, TypeVarTuple

Ts = TypeVarTuple('Ts')

@asynccontextmanager  # E: Argument 1 to "asynccontextmanager" has incompatible type "Callable[[VarArg(*Ts)], AsyncIterator[tuple[*Ts]]]"; expected "Callable[[VarArg(Never), KwArg(Never)], AsyncIterator[Never]]"  [arg-type]
async def fun(*args: *Ts) -> AsyncIterator[tuple[*Ts]]:
    yield args
    

@asynccontextmanager  # E: Argument 1 to "asynccontextmanager" has incompatible type "Callable[[int], Coroutine[Any, Any, AsyncIterator[int]]]"; expected "Callable[[int], AsyncIterator[Never]]"  [arg-type]
async def int_bad(arg: int) -> AsyncIterator[int]:  # E: Missing return statement  [empty-body]
    ...


@asynccontextmanager
async def int_good(arg: int) -> AsyncIterator[int]:
    yield arg
```

Compare `int_bad` and `int_good`. `missing-body` error apparently breaks unnesting double "async-ness" of `async def ... -> AsyncIterator[...]`. 

[Playground](https://mypy-play.net/?mypy=master&python=3.12&flags=strict&gist=8824b7f4eb6850e98db759aaae8daaa0)

**Comment by sterliakov** [comment]
#17340 seems to be related.
