### ISSUE TITLE
Empty tuple type is expanded in truthy check instead of narrowed.

### ISSUE THREAD

**Issue by Avasam** [python/mypy#17273]
**Bug Report**
When checking if a value is falsy, empty tuples get expanded from `tuple[()]` to `tuple[Any, ...]` instead of `Never`.

(A clear and concise description of what the bug is.)

**To Reproduce**

```python
def foo(bar: Union[str, tuple[()]]):
    if bar:
        reveal_type(bar)
```

```
mypy: Revealed type is "Union[builtins.str, builtins.tuple[Any, ...]]"
pyright: Type of "bar" is "str"
```

**Expected Behavior**
`bar` can only be a `str` in that example.

**Actual Behavior**
`bar` becomes `str | tuple[()]`

**Your Environment**

- Mypy version used: 1.10.0 (compiled: yes)
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files):
```ini
python_version = 3.8
strict = False
warn_unused_ignores = True
warn_redundant_casts = True
explicit_package_bases = True
```
- Python version used: 3.9.13

**Comment by hauntsaninja** [comment]
This only repros on Python 3.8. If you want this to work on Python 3.8, you'll need to use `from __future__ import annotations` or `typing.Tuple`.

**Comment by hauntsaninja** [comment]
https://mypy-play.net/?mypy=latest&python=3.8&gist=a2f36e390906518b0442859cfa17acdc

**Comment by Avasam** [comment]
A few alternate options I had required 3.9 anyway so I'll just consider it not feasible for 3.8. Thanks!
