### ISSUE TITLE
`Generator` return type and send type are treated as `None` under `allow-any-generics`

### ISSUE THREAD

**Issue by koogoro** [python/mypy#17286]
**Bug Report**
On the newest master, `Generator` is not the same as `Generator[Any, Any, Any]` with `allow-any-generics` enabled. This doesn't happen on 1.10.0.

**To Reproduce**
https://gist.github.com/mypy-play/16ab6e35d0fa38ee42cd9d40b3a7474d

**Expected Behavior**
No errors.

**Actual Behavior**
```
main.py:5: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
main.py:6: error: No return value expected  [return-value]
```

**Comment by hauntsaninja** [comment]
Looks like it bisects to #17246

**Comment by JelleZijlstra** [comment]
This seems like an expected consequence of PEP 696; the two type parameters now default to None.

**Comment by koogoro** [comment]
Oh nice. Seems like it's not a bug after all!
