### ISSUE TITLE
Consider keying the cache on a hash of the source instead of mtime+size

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1728]
This would enable saving a snapshot of the cache for later reuse.

The mtime+size should still be used as well, since os.stat() is still quite a bit faster than reading and hashing every file. However it would be nice if we could fall back on hashing if the mtime+size has changed -- and then update the mtime+size.

**Comment by ddfisher** [comment]
No point in hashing if the size changes, though. :)

**Comment by ilevkivskyi** [comment]
This is done now.
