### ISSUE TITLE
Multiple inheritance from namedtuple causes error on assignment

### ISSUE THREAD

**Issue by rbtying** [python/mypy#1729]
Code:

```
from collections import namedtuple
from typing import Dict


class A(object):
    pass


class B(A, namedtuple('bsuper', '')):
    pass

d = {}  # type: Dict[str, A]

d['hi'] = B()
d['hi2'] = A()
```

Error: 

```
demo.py:14: error: Incompatible types in assignment (expression has type "B", target has type "A")
```

Expectation is that no error is thrown, because B inherits from A.

**Comment by gvanrossum** [comment]
Yes, we are seeing a lot of namedtuple-related bugs. :-(

**Comment by ddfisher** [comment]
This _does_ appear to be a namedtuple problem (in that it goes away when you don't inherit from namedtuple).  The usage of dict isn't necessary to repro -- B doesn't appear to be regarded as a subclass of A.

**Comment by gvanrossum** [comment]
Shorter repro:
```
from collections import namedtuple
class A(object): pass
class B(A, namedtuple('bsuper', '')): pass
x = A()
x = B()  # E: Incompatible types in assignment (expression has type "B", variable has type "A")
```

**Comment by elazarg** [comment]
I believe this has been fixed. At least, the repro does not reproduce.

**Comment by gvanrossum** [comment]
Can you find the commit that fixed it using bisection?

--Guido (mobile)

**Comment by elazarg** [comment]
PR #2091, commit [590c15f](https://github.com/python/mypy/commit/590c15f53b105439a59088d3e6ffcfc0d84defa2)

**Comment by gvanrossum** [comment]
Great! One bug down
