### ISSUE TITLE
Return type of dict.get is wrong when using strict optional checking

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1732]
The revealed type in the following program is `int` though it should be `Optional[int]` when using `--strict-optional`:

```
d = {'x': 1}
a = d.get('y')
reveal_type(a)
```

This also needs a typeshed change, but I think that there was a mypy issue with overloaded functions that is related. It's worth having a separate issue to track this here.

**Comment by gvanrossum** [comment]
I think this is relevant: https://github.com/python/typeshed/pull/223#issuecomment-222538324

**Comment by ambv** [comment]
Currently landed PR for this feature in typeshed: python/typeshed#822. Contains a Union[] return type so might have to be fixed to simple `@overload`.

**Comment by ilevkivskyi** [comment]
It looks like this is fixed on master, I get:
```
Revealed type is 'Union[builtins.int*, builtins.None]'
```

**Comment by gvanrossum** [comment]
(Also, if you pass an explicit default of a different type, it becomes a union of int and that type, regardless of the `--strict-optional` setting. IIRC that was a problem in the past too.)
