### ISSUE TITLE
Failed to resolve the boundary type in a PEP 695 new style definition

### ISSUE THREAD

**Issue by danpascu** [python/mypy#17347]
The following code:

```py
class ComparableNumber[T: ComparableNumber](Protocol):
    def __lt__(self, other: T, /) -> bool: ...
    def __gt__(self, other: T, /) -> bool: ...
    def __int__(self) -> int: ...

```

Fails with:

```
_typing.py:15: error: Cannot resolve name "ComparableNumber" (possible cyclic definition)  [misc]
```

Pyright seems to accept it with no issue and python itself doesn't complain or raise any exception when this definition is loaded at runtime.

This is with the current head version from github with default configuration, no command line switches and with
 
`# mypy: enable-incomplete-feature=NewGenericSyntax`

being used in the file where this is defined.

**Comment by JelleZijlstra** [comment]
Works with non-PEP 695 syntax:

```
from typing import TypeVar, Protocol

T = TypeVar("T", bound="ComparableNumber", contravariant=True)

class ComparableNumber(Protocol[T]):
    def __lt__(self, other: T, /) -> bool: ...
    def __gt__(self, other: T, /) -> bool: ...
    def __int__(self) -> int: ...
```

I'll add a label for PEP 695 issues.

**Comment by danpascu** [comment]
Initially I thought that the problem might be because at that point `ComparableNumber` is not yet defined so it cannot be referenced yet, the same way as a type cannot be referenced within its own implementation without using `Self` or a string annotation, but this form:

```py
class ComparableNumber[T: "ComparableNumber"](Protocol):
    def __lt__(self, other: T, /) -> bool: ...
    def __gt__(self, other: T, /) -> bool: ...
    def __int__(self) -> int: ...
```

fails with the exact same error, so the issue must be somewhere else.
