### ISSUE TITLE
A Bug come from using the Customtkinter

### ISSUE THREAD

**Issue by limzhishen** [python/mypy#17366]
![image](https://github.com/python/mypy/assets/152234247/4be27b95-9316-4ed2-9837-73ae05ed0d42)

As from the picture can seen the function already detect by ide and shown,
But the mypy shown as an error
this is the customtkinter library, no sure why cannot be detect

**Comment by JelleZijlstra** [comment]
Could you give a full code sample that reproduces the bug?

Most likely the issue is in the types for this library, not in mypy itself.
