### ISSUE TITLE
Confusing description for --no-namespace-packages

### ISSUE THREAD

**Issue by rafalkrupinski** [python/mypy#17466]
**Bug Report**

in the built-in help, the description for `--no-namespace-packages` is reversed.

**To Reproduce**

```shell
$ mypy --help
```

**Expected Behavior**

```shell
[...]
Import discovery:
  Configure how imports are discovered and followed.

  --no-namespace-packages   Disable support for namespace packages (PEP 420, __init__.py-less) (inverse: --namespace-packages)
```

**Actual Behavior**

```shell
[...]
  --no-namespace-packages   Support namespace packages (PEP 420, __init__.py-less) (inverse: --namespace-packages)

```

Description suggests that the flag enables support for namespace packages. Namespace packages are enabled by default and the flag disables it.
https://github.com/python/mypy/blob/f297917fc9eba13cc2a5b7e2e276394d94c03c8d/mypy/main.py#L564C4-L570C6

**Your Environment**

- Mypy version used: 1.10.1
- Mypy command-line flags: --help

**Comment by hauntsaninja** [comment]
PR welcome

**Comment by rafalkrupinski** [comment]
dibs
