### ISSUE TITLE
Allow to write using builder pattern

### ISSUE THREAD

**Issue by rbuchmann77** [python/mypy#17489]
**Feature**

mypy should allow us to write code using builder pattern or documentation may suggest a way to do it.

**Pitch**

I tried several ways to write the code. One-liner works but... pylint will report "line too long" of course.

Here an example of builder pattern :  

`
builder = Builder()
               .setName("hello")
               .setWidth(320)
               .setPermission("RW")
               ...
`

mypy keep reporting "unexpected indent", no matter how I indent things.

I failed to find a way to write builder pattern style.

**Comment by JelleZijlstra** [comment]
This is a Python syntax issue, not a mypy issue. I would recommend using a formatter like [Black](https://github.com/psf/black) to format your code within a line length limit.
