### ISSUE TITLE
Behaviour of typing overloads in `Protocol`and their implementations?

### ISSUE THREAD

**Issue by farbodsz** [python/mypy#17480]
**Question / Bug Report?**

I have a `Protocol` which defines a method with possible overloads. There are multiple "implementations" of that protocol throughout my codebase.

**To Reproduce**

```python
from typing import Protocol, overload

from typing_extensions import override


# for example
class Foo: ...


class Bar: ...


class MyInterface(Protocol):
    @overload
    def do_something(self, a: str, b: int) -> Foo: ...

    @overload
    def do_something(self, a: str, b: None = None) -> Bar: ...

    def do_something(self, a: str, b: int | None = None) -> Foo | Bar: ...


class MyImplementation(MyInterface):
    @override
    def do_something(self, a: str, b: int | None = None) -> Foo | Bar:
        # Some implementation goes here
        raise NotImplementedError

# other implementations in other files 
```

**Expected Behavior**

I would expect this to type-check fine - the method in `MyImplementation` implements the definition of the protocol and the types look fine.

**Actual Behavior**

Mypy complains because the overloads are not present in the definition of the "implementation".

```
_example.py:25: error: Signature of "do_something" incompatible with supertype "MyInterface"  [override]
        def do_something(self, a: str, b: int | None = None) -> Foo | Bar:
        ^
_example.py:25: note:      Superclass:
_example.py:25: note:          @overload
_example.py:25: note:          def do_something(self, a: str, b: int) -> Foo
_example.py:25: note:          @overload
_example.py:25: note:          def do_something(self, a: str, b: None = ...) -> Bar
_example.py:25: note:      Subclass:
_example.py:25: note:          def do_something(self, a: str, b: int | None = ...) -> Foo | Bar
```

The error indeed goes away once I add the method overloads to `MyImplementation`.

**I guess I'm curious to know:**

1. **Is this the intended behaviour?**
2. **If it is, then I'd be curious to know the reason behind this decision?**

(To me, overloads are there to define a method's interface not its implementation, so it doesn't make sense to have to define them in an implementation class. At the same time, this behaviour is consistent with how any missing protocol method is treated by mypy so I'm not entirely surprised.)

**Your Environment**

- Mypy version used: `mypy 1.10.0 (compiled: yes)`
- Mypy command-line flags: NONE
- Mypy configuration options from `mypy.ini` (and other config files):

```toml
[tool.mypy]
files = ["src", "tests"]
strict = true
pretty = true
plugins = [
    "pydantic.mypy",
]
enable_error_code = [
    "explicit-override",
    "ignore-without-code",
    "truthy-bool",
    "truthy-iterable",
]
```

- Python version used: 3.10

**Comment by JelleZijlstra** [comment]
Yes, this behavior is correct. The protocol guarantees that if you pass an `int` as the second argument to the method, the method returns a `Foo`. Your implementation's type annotations do not provide that guarantee.
