### ISSUE TITLE
Generic param bound to `type` isn't valid as a type

### ISSUE THREAD

**Issue by max-muoto** [python/mypy#17494]
Cross-posting this from [Pyright](https://github.com/microsoft/pyright/issues/8313), as the same issue exists within MyPy.

A code example such as this:

```python
from typing import Any, TypeVar

T = TypeVar("T", bound=type[Any])

def klass_decorator(klass: T) -> T:
    # Expected type expression...
    class Wrapped(klass):
        ...

    return Wrapped
    
```

should be valid, since `klass` is a bound to a type, however in reality you end up with `Variable "klass" is not valid as a type`

[MyPy Playground
](https://mypy-play.net/?mypy=latest&python=3.12&gist=98af87392cbd255ed4738596b6686e5f)

**Your Environment**

- Mypy version used: 1.10.1
- Mypy command-line flags: None
- Python version used: 3.12

**Comment by erictraut** [comment]
Mypy disallows all dynamic types as base classes. I think this behavior is fine (as is pyright's behavior, which allows dynamic types as base classes). The typing spec doesn't specify whether this should be considered a typing error.

```python
def func(cls: type[int]):
    class Inner(cls): # Mypy generates error here, pyright does not
        ...
```

With this in mind, I think that mypy's behavior with the above code snippet is consistent with mypy's general behavior in this case, so it should probably not be considered a bug. The reason I considered it a bug in the linked pyright issue is that pyright is inconsistent in its behavior.

**Comment by max-muoto** [comment]
> Mypy disallows all dynamic types as base classes. I think this behavior is fine (as is pyright's behavior, which allows dynamic types as base classes). The typing spec doesn't specify whether this should be considered a typing error.
> 
> ```python
> def func(cls: type[int]):
>     class Inner(cls): # Mypy generates error here, pyright does not
>         ...
> ```
> 
> With this in mind, I think that mypy's behavior with your above code snippet is consistent with mypy's general behavior in this case, so it should probably not be considered a bug. The reason I considered it a bug in the linked pyright issue is that pyright is inconsistent in its behavior.

Thanks for clarifying, Eric. MyPy was fine with this:

```python
from typing import Any

def foo(t: type[Any]) -> Any:
    class MyClass(t):
        ...
    return MyClass
```

Which I think initially got me confused on this, let me close this one out.
