### ISSUE TITLE
Class with a classmethod named `list` fails when other methods use `list` in annotations

### ISSUE THREAD

**Issue by jacobtomlinson** [python/mypy#17517]
**Bug Report**

If a class has a method with the same name as a builtin mypy assumes that is the type in other method annotations.

**To Reproduce**

```python
#listmethod.py
class Foo:

    @classmethod
    def list(self) -> list:
        return [1, 2, 3]

    def bar(self, input: list) -> list:
        return input
```

**Expected Behavior**

Mypy lints with no errors.

**Actual Behavior**

```
$ mypy listmethod.py   
listmethod.py:7: error: Function "listmethod.Foo.list" is not valid as a type  [valid-type]
listmethod.py:7: note: Perhaps you need "Callable[...]" or a callback protocol?
Found 1 error in 1 file (checked 1 source file)
```

Changing the order so that `def list(...): ...` is at the end results in `mypy` passing.

**Your Environment**

- Mypy version used: `1.10.1`
- Mypy command-line flags: `mypy listmethod.py `
- Mypy configuration options from `mypy.ini` (and other config files): Defaults
- Python version used: `3.11.6`

**Comment by erictraut** [comment]
Mypy's behavior here is correct. The `list` type annotation in this case resolves to the symbol you're defining in the class body, and that's not a legal symbol to use in a type annotation.

You can see this is how the symbol is resolved by adding the line `print(Foo.bar.__annotations__)` and then running the program. It shows that at runtime, the annotations for `bar` reference the `list` method, not the `builtins.list`.

The best way to solve this is to avoid defining symbols in a class that shadow the names of builtin symbols. If this isn't feasible, then you can use techniques like this:

```python
_list: TypeAlias = list

class Foo:
    @classmethod
    def list(cls) -> _list:
        return [1, 2, 3]

    def bar(self, input: _list) -> _list:
        return input
```

**Comment by JelleZijlstra** [comment]
Agree with @erictraut, though as a workaround I'd prefer using `import builtins` and then use `builtins.list` in your annotations.

**Comment by jacobtomlinson** [comment]
Thanks @erictraut!
