### ISSUE TITLE
ï not dealt with properly

### ISSUE THREAD

**Issue by russel** [python/mypy#1754]
The signature:

``` python
def naïve_recursive(n: int) -> int:
```

is perfectly valid Python, but MyPy barfs on the ï.

```
XXX: note: In function "na":
XXX:27: error: Unrecognized character
XXX:27: error: Parse error before "int"
XXX: note: At top level:
XXX:27: error: Parse error before :
XXX:28: error: Inconsistent indentation
```

**Comment by JukkaL** [comment]
Non-ascii identifiers aren't supported by the default parser. @ddfisher has been working on an improved parser that will likely fix this.

**Comment by JukkaL** [comment]
Closing as duplicate of #586.

**Comment by rwbarton** [comment]
More specifically, this already works with `mypy --fast-parser`. You'll need the `typed_ast` package.

**Comment by gvanrossum** [comment]
I'm going to close this as a won't fix because the new parser will solve this and we're not going to put any work in the old parser/lexer.

**Comment by gvanrossum** [comment]
(Sorry for the noise. It was already closed.)
