### ISSUE TITLE
Optional argument favored over ** keyword arguments

### ISSUE THREAD

**Issue by tewe** [python/mypy#1755]
The typeshed stub for `xml.etree.ElementTree` looks correct:

    class Element(Sequence['Element']):
        def __init__(self, tag: Union[AnyStr, Callable[..., 'Element']], attrib: Dict[AnyStr, AnyStr]=..., **extra: Dict[str, AnyStr]) -> None: ...

And indeed these calls both run fine:

    Element('rss', dict(version='2.0'))
    Element('rss', version='2.0')

However the latter doesn't type check:

    Argument 2 to "Element" has incompatible type "str"; expected Dict[str, str]

**Comment by JukkaL** [comment]
Perhaps the annotation in the stub should look like `..., *extra: AnyStr) -> None: ...`? For `**kwargs`, we annotate the types of argument values (such as `AnyStr` for `'2.0'` in your example), not the type of `kwargs` within the function body.

**Comment by tewe** [comment]
> For **kwargs, we annotate the types of argument values

I see. I assumed the stub was correct because it still had the "generated by stubgen" comment at the top. Human editors should remove that. Will take it over to typeshed.
