### ISSUE TITLE
bool/int substitutions are valid only sometimes: x, y = False, True  # type int, int

### ISSUE THREAD

**Issue by cjwelborn** [python/mypy#1757]
Like the title says, this is okay in mypy:
```
mypy -c 'x, y = False, True  # type: int, int'
```

But the reverse is not:
```
mypy -c 'x, y = 1, 0  # type: bool, bool'
<string>:1: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
```

I first found it checking to see if mypy cares about `bool`/`int` where Python itself doesn't.
Python is okay with this because `bool` sub-classes `int`, and mixed arithmetic is okay:
```
(False, 0.0, 0, 1).count(False)
>> 3
[2, 1].index(True)
>> 1
```

mypy doesn't seem to care about this:
```
mypy -c 'l = [False, True, 0, 1]  # type: List[int]'
```

..but it cares about the opposite:
```
mypy -c 'l = [False, True, 0, 1]  # type: List[bool]'
<string>:1: error: List item 2 has incompatible type "int"
<string>:1: error: List item 3 has incompatible type "int"
```

Is this an actual bug, or is this documented somewhere? I know why Python does it, I just thought that mypy would say something about it.

**Comment by kirbyfan64** [comment]
I don't think this is a bug. In Python, because `bool` subclasses `int`, but not the other way around. For instance:

```python
x = True
print(isinstance(x, int)) # True
x = 0
print(isinstance(x, bool)) # False
```

**Comment by gvanrossum** [comment]
Indeed, I think the OP is confused by Python's accepting `if 0: ...` -- but that's not because ints and bools are interchangeable; it's because `if` doesn't require a bool at all, it takes any object and applies a "truth-finding" dunder method to it (`__bool__` or `__len__`).

**Comment by cjwelborn** [comment]
I can see the reasoning, that because `bool` is technically an `int` it type checks. I just thought that mypy would be a little stricter where python isn't (`sum([False, True, True])`, `x = ['a', 'b'][False]`).

**Comment by 0ion9** [comment]
@cjwelborn people aren't notified of comments after an issue is closed. If you want them to notice you have to @mention them like I did in this message.

**Comment by cjwelborn** [comment]
@0ion9, thanks. I should have done that.
