### ISSUE TITLE
type of expression "Literal['fred']" wrong

### ISSUE THREAD

**Issue by urnest** [python/mypy#17592]
(venv) xju@xjutv:~/mypy$ mypy --version
mypy 1.12.0+dev.e67decb91ea5aacbb1e126463b02d78ded680a90.dirty (compiled: no)

(venv) xju@xjutv:~/mypy$ cat ~/todo/cut.py
from typing import TypeVar, Literal
reveal_type(Literal['fred'])  # builtins.object ... should be type[Literal['fred']]

(venv) xju@xjutv:~/mypy$ mypy ~/todo/cut.py
/home/xju/todo/cut.py:2: note: Revealed type is "typing._SpecialForm"
Success: no issues found in 1 source file

... am fixing

**Comment by urnest** [comment]
hmm, I think 1.10 reported builtins.object, but later (as shown in ticket description) reports typing._SpecialForm
... shrug, they are both wrong

**Comment by hauntsaninja** [comment]
At runtime, Literal['fred'] is not an instance of type. See also the discussion surrounding TypeForm
