### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by onnokort** [python/mypy#1759]
Hi,

mypy told me to report a bug. I tried to reduce the test case as much as possible. The result is attached.

[bug.py.txt](https://github.com/python/mypy/files/338135/bug.py.txt)

EDIT: I might add this occurs with recent git, 9a92899e7c8416d43196d8bf424e7e2d86f27f0d

**Comment by gvanrossum** [comment]
Thanks for reporting! It looks like this has been reported before, as #1553. I'll close this one as a duplicate.
