### ISSUE TITLE
 Feature Request: Add configuration to disallow/warn about usage of blanket `# type: ignore`

### ISSUE THREAD

**Issue by nh916** [python/mypy#17598]
# Summary

I would like to request a feature in Mypy to disallow blanket/generic `# type: ignore` comments and enforce specifying the specific error code to ignore. This feature would help improve code quality and maintainability by preventing broad suppressions of type-checking errors.

## Background

Currently, Mypy allows the use of blanket/generic `# type: ignore` comments to suppress all type-checking errors on a single line. While this can be useful in some cases, it often leads to overlooked type issues and reduces code quality. By enforcing the specification of error codes, developers will be more aware of the specific issues they are suppressing, leading to better-maintained codebases and better quality code.

## Proposed Solution

Add a configuration option in Mypy to disallow or warn about blanket `# type: ignore` comments, requiring the specification of the error code to ignore. This can be similar to `warn_unused_ignores`. For specific cases where all type checking needs to be ignored on a single line, developers can maybe use `type: ignore[misc]` or `# type: ignore[suppress-all]` while in strict mode.

### Example

Given the following code:

```python
def example() -> int:
    return "string"  # type: ignore
```

With the proposed feature enabled, Mypy would raise an error with something like:

```
Blanket # type: ignore comments are not allowed, specify the specific error code to ignore
```

## Benefits

- **Increased Code Quality**: Developers will be more mindful of the specific issues they are suppressing.
- **Improved Maintainability**: Clearer suppression of type-checking errors makes it easier to address issues in the future.
- **Better Error Tracking**: Specific error codes help in tracking and resolving type-checking issues more effectively.

## Conclusion

Enforcing specific type ignore comments will lead to better code quality and maintainability. This feature would encourage developers to address type-checking issues more precisely, benefiting the overall health of Python projects.

Thank you for considering this feature request. I look forward to your feedback and any further discussion on this topic.

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-type-ignore-include-an-error-code-ignore-without-code :-)

**Comment by nh916** [comment]
Thank you so much!
