### ISSUE TITLE
Confusing error message when using incompatible type on '*args' style tuple argument

### ISSUE THREAD

**Issue by onnokort** [python/mypy#1765]
Hi,

for the attached file

[msg.py.txt](https://github.com/python/mypy/files/339109/msg.py.txt)

I get the following error message:

msg.py.txt: note: In member "fn" of class "SomeClass":
msg.py.txt:10: error: Argument 1 to "tuple" has incompatible type Set[int]; expected Iterable[...]

I was expecting something like "has incompatible type Set[int]; expected Iterable[_Callable_]". The "..." is confusing, as it seems to hint at Set[..] not following the Iterable[...] protocol.

**Comment by gvanrossum** [comment]
Please show examples inline. For posterity: here it is:
```python
from typing import Callable

class SomeClass(object):
    def __init__(self): #type: (SomeClass) -> None
        self.x=set() # type: Set[Callable]
        self.mx=set() #type: Set[int]
        
    def fn(self, *a): #type: (SomeClass, *Callable) -> None
        if not len(a):
            a=(tuple(self.x) + tuple(self.mx))        
```

**Comment by gvanrossum** [comment]
The reason is probably that mypy shortens the text of types occurring in error messages. I think there's already another issue asking to show the full type (or at least to make the limit much larger).

**Comment by gvanrossum** [comment]
See the discussion in #287.

**Comment by ilevkivskyi** [comment]
Mypy now shows the full type `Iterable[Callable[..., Any]]`, so this is fixed.
