### ISSUE TITLE
mypy crashes on syntax error caused by backslash

### ISSUE THREAD

**Issue by Diggsey** [python/mypy#1767]
Example:

```
{\rtf1}
```

The syntax error is correctly determined to be of type `INVALID_BACKSLASH`, but the error reporting code doesn't catch this enum variant, resulting in a `ValueError`.

(parse.py:1988)

**Comment by gvanrossum** [comment]
But with `--fast-parser` it gives a more reasonable error. Suggest to just
wait until that's become the default parser.

**Comment by gvanrossum** [comment]
Hopefully in 0.4.x we'll have the new parser on by default and this won't be an issue any more.

**Comment by gvanrossum** [comment]
I'm going to close this as a won't fix because the new parser will solve this and we're not going to put any work in the old parser/lexer.
