### ISSUE TITLE
Clarification on how to Run .test Files?

### ISSUE THREAD

**Issue by gnohgnailoug** [python/mypy#17687]
**Documentation**

I'm familiar with running Python test files using commands like pytest test_xx.py and running unit test cases with pytest testXxxx. However, I am unclear about how to execute tests in files with the .test extension. We couldn't find any documentation related to this. Could you please provide guidance on the correct approach or command to run these .test files?

**Comment by AlexWaygood** [comment]
There's some docs on how to run tests at https://github.com/python/mypy/blob/master/CONTRIBUTING.md#running-tests, and more detailed documentation at https://github.com/python/mypy/tree/master/test-data/unit#tests (which is linked to from the first link).

I think putting this information in `CONTRIBUTING.md` (where it currently is) is where most people would expect to find it. Did you look there? :-)

**Comment by gnohgnailoug** [comment]
> There's some docs on how to run tests at https://github.com/python/mypy/blob/master/CONTRIBUTING.md#running-tests, and more detailed documentation at https://github.com/python/mypy/tree/master/test-data/unit#tests (which is linked to from the first link).
> 
> I think putting this information in `CONTRIBUTING.md` (where it currently is) is where most people would expect to find it. Did you look there? :-)

Thank you, Alex. It seems that i miss some important information, i will try it later. You're so kind, hope you have a good day :)!

**Comment by AlexWaygood** [comment]
> hope you have a good day

you too!!

**Comment by gnohgnailoug** [comment]
@AlexWaygood
 Hi Alex,

I hope you're doing well! I have a follow-up question regarding .test files in the MyPy project. Specifically, how can we identify the corresponding test/test_xx.py file and the related test suite for a given .test file? For example, in the MyPy CONTRIBUTING.md example (pytest mypy/test/testcheck.py::TypeCheckSuite::check-dataclasses.test), how would we determine that check-dataclasses.test is linked to mypy/test/testcheck.py and TypeCheckSuite?

Thank you for your help!

**Comment by AlexWaygood** [comment]
I believe you use the prefixes of the test files. E.g. all test files starting with `check-*` are executed by `testcheck.py`; all test files starting with `semanal-*` are executed by `testsemanal.py`, etc.

**Comment by gnohgnailoug** [comment]
> I believe you use the prefixes of the test files. E.g. all test files starting with `check-*` are executed by `testcheck.py`; all test files starting with `semanal-*` are executed by `testsemanal.py`, etc.

Oh, i got it! Thanks again :)!
