### ISSUE TITLE
Assertion Error in StubtestUnit::test_protocol with Python 3.7 Environment

### ISSUE THREAD

**Issue by gnohgnailoug** [python/mypy#17695]
**Crash Report**

I'm encountering an issue while running pytest on mypy/test/teststubtest.py in a Python 3.7 environment： Assertion Error in StubtestUnit::test_protocol with Python 3.7 Environment

**Traceback**

============================= test session starts ==============================
collected 48 items

mypy/test/teststubtest.py .............................F................ [ 95%]
..                                                                       [100%]

=========================== short test summary info ============================
PASSED mypy/test/teststubtest.py::StubtestUnit::test_abstract_methods
PASSED mypy/test/teststubtest.py::StubtestUnit::test_abstract_properties
PASSED mypy/test/teststubtest.py::StubtestUnit::test_all_at_runtime_not_stub
PASSED mypy/test/teststubtest.py::StubtestUnit::test_all_in_stub_different_to_all_at_runtime
PASSED mypy/test/teststubtest.py::StubtestUnit::test_all_in_stub_not_at_runtime
PASSED mypy/test/teststubtest.py::StubtestUnit::test_arg_kind
PASSED mypy/test/teststubtest.py::StubtestUnit::test_arg_mismatch
PASSED mypy/test/teststubtest.py::StubtestUnit::test_arg_name
PASSED mypy/test/teststubtest.py::StubtestUnit::test_bad_literal
PASSED mypy/test/teststubtest.py::StubtestUnit::test_basic_good
PASSED mypy/test/teststubtest.py::StubtestUnit::test_coroutines
PASSED mypy/test/teststubtest.py::StubtestUnit::test_decorator
PASSED mypy/test/teststubtest.py::StubtestUnit::test_default_presence
PASSED mypy/test/teststubtest.py::StubtestUnit::test_default_value
PASSED mypy/test/teststubtest.py::StubtestUnit::test_dunders
PASSED mypy/test/teststubtest.py::StubtestUnit::test_enum
PASSED mypy/test/teststubtest.py::StubtestUnit::test_good_literal
PASSED mypy/test/teststubtest.py::StubtestUnit::test_has_runtime_final_decorator
PASSED mypy/test/teststubtest.py::StubtestUnit::test_metaclass_abcmeta
PASSED mypy/test/teststubtest.py::StubtestUnit::test_metaclass_match
PASSED mypy/test/teststubtest.py::StubtestUnit::test_missing
PASSED mypy/test/teststubtest.py::StubtestUnit::test_missing_no_runtime_all
PASSED mypy/test/teststubtest.py::StubtestUnit::test_mro
PASSED mypy/test/teststubtest.py::StubtestUnit::test_name_mangling
PASSED mypy/test/teststubtest.py::StubtestUnit::test_non_public_1
PASSED mypy/test/teststubtest.py::StubtestUnit::test_non_public_2
PASSED mypy/test/teststubtest.py::StubtestUnit::test_not_subclassable
PASSED mypy/test/teststubtest.py::StubtestUnit::test_overload
PASSED mypy/test/teststubtest.py::StubtestUnit::test_property
PASSED mypy/test/teststubtest.py::StubtestUnit::test_special_subtype
PASSED mypy/test/teststubtest.py::StubtestUnit::test_static_class_method
PASSED mypy/test/teststubtest.py::StubtestUnit::test_type_alias
PASSED mypy/test/teststubtest.py::StubtestUnit::test_type_var
PASSED mypy/test/teststubtest.py::StubtestUnit::test_types
PASSED mypy/test/teststubtest.py::StubtestUnit::test_var
PASSED mypy/test/teststubtest.py::StubtestUnit::test_varargs_varkwargs
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_allowlist
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_config_file
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_get_typeshed_stdlib_modules
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_ignore_flags
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_missing_stubs
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_module_and_typeshed
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_mypy_build
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_no_modules
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_only_py
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_output
PASSED mypy/test/teststubtest.py::StubtestMiscUnit::test_signature
FAILED mypy/test/teststubtest.py::StubtestUnit::test_protocol - AssertionErro...

**To Reproduce**

+ pytest --no-header -rA --tb=no -p no:cacheprovider -n0 mypy/test/teststubtest.py

**Your Environment**

- Mypy version used: 0.99,0.99,1.2
- Mypy command-line flags: 
- Mypy configuration options from `mypy.ini` (and other config files):

 Installed with: pip install -r test-requirements.txt && pip install -e .
Typing Extensions: 3.10.0
Pytest Extensons: 6.2.5
- Python version used:3.7

- Operating system and version: x86

**Comment by hauntsaninja** [comment]
mypy 0.991 is ancient. mypy dropped support for 3.7 in 1.5, so you're sort of on your own, although you could try 1.4

**Comment by gnohgnailoug** [comment]
> mypy 0.991 is ancient. mypy dropped support for 3.7 in 1.5, so you're sort of on your own, although you could try 1.4

Ok, thanks for your reply!
