### ISSUE TITLE
Raise errors when importing from the `typing` package instead of using the built-in types.  

### ISSUE THREAD

**Issue by JakeSummers** [python/mypy#17690]
**Feature**

Currently I have a bunch of code that does this:

```python
from typing import Dict
foo: Dict[str, str] = []
```

In Python 3.9+, it is preferable to use the built-in types ([source](https://mypy.readthedocs.io/en/stable/builtin_types.html#generic-types)):

```python
foo: dict[str, str] = []
Is there a way to configure mypy to raise an error/warning when my code uses Dict instead of dict?
```

**Pitch**

[PEP-585](https://peps.python.org/pep-0585/) suggests that type checkers, may warn about deprecated type usage: 

> Importing those from typing is deprecated. Due to [PEP 563](https://peps.python.org/pep-0563/) and the intention to minimize the runtime impact of typing, this deprecation will not generate DeprecationWarnings. *Instead, type checkers may warn about such deprecated usage when the target version of the checked program is signalled to be Python 3.9* or newer. It’s recommended to allow for those warnings to be silenced on a project-wide basis.

This would help make my code more uniform.  :)

**Comment by JelleZijlstra** [comment]
This is already implemented by linters such as Ruff (https://docs.astral.sh/ruff/rules/non-pep585-annotation/). That doesn't mean mypy can't also implement support for checks like this, but it does mean the return on investment for mypy to add this feature is lower.

**Comment by JakeSummers** [comment]
I suggest that we close this issue.  Thanks for the solution @JelleZijlstra .
