### ISSUE TITLE
Cannot import attribute from module of the same name within __init__.py

### ISSUE THREAD

**Issue by Diggsey** [python/mypy#1776]
Example:

``` python
# __init__.py
from .app import app
```

`mypy` will complain about `app` being defined twice.

**Comment by gvanrossum** [comment]
Yeah, I can confirm this, with `app.py` containing
```
class App:
    pass
app = App()
```
I'm not sure how easy this is to fix in mypy; I can suggest as a workaround to rename one of the two things named app.

NOTE: Even though this works in Python, it is definitely "skating on thin ice": normally when there's a package P with a submodule M, P's namespace contains a name M referencing the module M. What you're doing here is overwriting that M with another thing also named M and imported from P.M (in your case M == app).

**Comment by Diggsey** [comment]
If it was purely my own project, I'd avoid it as bad practice. However, this technique seems to be used widely throughout many python packages, including sqlalchemy.

**Comment by gvanrossum** [comment]
Implementing this will be somewhat tricky. :-(

**Comment by ilevkivskyi** [comment]
It looks like this is now fixed. I can't reproduce the error.
