### ISSUE TITLE
truthy-bool check does not check the `not` operator

### ISSUE THREAD

**Issue by komodovaran** [python/mypy#17769]
```python
class Foo:
    @property
    def prop(self) -> bool:
        return False


def bools_only(value: bool) -> bool:
    return value


bools_only(Foo().prop) # Standard behavior of properties
bools_only(Foo.prop) # Expected type 'bool', got 'property' instead 
bools_only(not Foo.prop) # no error after casting with `not`!
```

Python interprets `not object` as `not bool(object)` which doesn't seem to be covered by any checks.

Tested with Mypy 1.11.2 and Python 3.12

https://mypy-play.net/?mypy=latest&python=3.12&gist=1c5f3510b686dd0e2e04e0a9ef191a96

**Comment by JelleZijlstra** [comment]
This falls conceptually within the https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-expression-is-not-implicitly-true-in-boolean-context-truthy-bool code. However, it doesn't appear mypy checks for this at all in the `not` operator.

To fix this, https://github.com/python/mypy/blob/72c413d2352da5ce1433ef241faca8f40fa1fe27/mypy/checkexpr.py#L4258 needs to be changed to call a variation of https://github.com/python/mypy/blob/72c413d2352da5ce1433ef241faca8f40fa1fe27/mypy/checker.py#L5654.
