### ISSUE TITLE
strange path manipulations in build.py

### ISSUE THREAD

**Issue by edreamleo** [python/mypy#1777]
The following code appears in the build() method in build.py:

```
    if TEST_BUILTINS in flags:
        # Use stub builtins...
        lib_path.insert(0, os.path.join(os.path.dirname(__file__), 'test', 'data', 'lib-stub'))
    else:
        for source in sources:
            if source.path:
                # Include directory of the program file in the module search path.
                dir = remove_cwd_prefix_from_path(dirname(source.path))
                if dir not in lib_path:
                    lib_path.insert(0, dir)

        # Do this even if running as a file, for sanity (mainly because with
        # multiple builds, there could be a mix of files/modules, so its easier
        # to just define the semantics that we always add the current director
        # to the lib_path
        lib_path.insert(0, os.getcwd())

    # Add MYPYPATH environment variable to front of library path, if defined.
    lib_path[:0] = mypy_path()
```

This seems pretty strange.  Indeed, `remove_cwd_prefix_from_path` will often return '.', and this is unlikely to match any entry in lib_path.  And then `lib_path.insert(0, os.getcwd())` will add the equivalent (expanded) version of '.'.

For instance, here is the result: 

```
(Pdb) print('\n'.join(lib_path))
C:\Users\edreamleo\stubs    # from mypy_path
c:\leo.repo\make-stub-files # from lib_path.insert(0, os.getcwd())
.                           # from  remove_cwd_prefix_from_path
C:\Anaconda3\Lib\mypy\typeshed\stdlib\3.5
C:\Anaconda3\Lib\mypy\typeshed\stdlib\3.4
C:\Anaconda3\Lib\mypy\typeshed\stdlib\3.3
C:\Anaconda3\Lib\mypy\typeshed\stdlib\3.2
C:\Anaconda3\Lib\mypy\typeshed\stdlib\3
C:\Anaconda3\Lib\mypy\typeshed\third_party\3
C:\Anaconda3\Lib\mypy\typeshed\stdlib\2and3
C:\Anaconda3\Lib\mypy\typeshed\third_party\2and3
(Pdb)
```

This looks like something from the Department of Redundancy Department, but I have no idea whether any of this makes the slightest difference in practice.

Edward

**Comment by gvanrossum** [comment]
If you're suggesting that the call to  remove_cwd_prefix_from_path()
is unnecessary, I'll give you that. Can you submit a PR that removes
it? We should see if there are any tests that require it and what else
breaks. (Possibly some error messages will have a longer path. If
that's the case we should keep the call -- or move it to a later
phase, e.g. when errors are rendered.)

**Comment by edreamleo** [comment]
> If you're suggesting that the call to remove_cwd_prefix_from_path() is unnecessary, I'll give you that.

I'm not suggesting that the call to `remove_cwd_prefix_from_path()` is unnecessary.  Only `build()` calls it, and it would seem to be useful in general.  I only point out that `remove_cwd_prefix_from_path` returns '.' in some cases.  It would seem that returning `os.getcwd()` would eliminate a useless or redundant entry in lib_path.  Following this change, the trailing code that presently always inserts os.getcwd() at the start of the lib_path would be something like:

```
dir = os.getcwd()
if dir not in lib_path:
    lib_path.insert(0, dir)
```

The effect of this change could be real, if subtle.  It would alter the position of the cwd in lib_path in some situations.  I have no idea whether present unit tests would be sensitive to this change.

And there is another complication.  All tests like `dir in lib_path` assume that directory names are fully "normalized".  That is, all paths must have os.path.normpath/abspath applied to them, all paths must be converted to a single case (on Windows) and perhaps even calls to os.path.expanduser or os.path.realpath.  Failure to normalize in a consistent manner will again result in subtle differences in the order of files in lib_path.

Leo is no great model in this regard.  These kinds of details are hard to get just right everywhere.

EKR

**Comment by gvanrossum** [comment]
I am having a hard time understanding your proposal. Let's just close this issue. Can you submit a PR with proposed code instead? When the tests pass we can talk again.

**Comment by edreamleo** [comment]
On Fri, Jul 1, 2016 at 11:26 AM, Guido van Rossum <notifications@github.com>
wrote:

> I am having a hard time understanding your proposal. Let's just close this
> issue.
>
​I agree.  It's minor.​


> Can you submit a PR with proposed code instead? When the tests pass we can
> talk again.
>
​Yes. Playing with the tests is the next step.  I'm on it.

Edward
