### ISSUE TITLE
[PEP 695] Multiple nested classes don't work

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#17780]
#17776 fixed nested PEP 695 generic classes when there is only one level of nesting, but multiple nesting still doesn't work since `lookup_fully_qualified_or_none` doesn't support them properly.

**Comment by ChengPuPu** [comment]
I am interested in this issue, can I work on it?

**Comment by JelleZijlstra** [comment]
Note there is already an open PR, so it's probably better to find a different issue to work on.
