### ISSUE TITLE
Import cycles give confusing error messages

### ISSUE THREAD

**Issue by Diggsey** [python/mypy#1779]
```python
# a.py
import b
```

```python
# b.py

def do_something():
    import a

def do_something_else():
    pass
```

```python
# c.py

import b

b.do_something_else()  # error: module has no attribute do_something_else
```

It's not obvious that the error is caused by a cyclic import, and even if you can figure that out, there's no easy way to determine what's causing the cyclic import, as it could be in completely unrelated files.

**Comment by gvanrossum** [comment]
Is this still a problem with the latest rev from the repo on GitHub? I
recently landed a change that makes the behavior around import cycles more
predictable and in some cases better.

On Thu, Jun 30, 2016 at 9:56 AM, Diggory Blake <notifications@github.com>
wrote:

> # a.pyimport b
>
> # b.py
> def do_something():
>     import a
> def do_something_else():
>     pass
>
> # c.py
> import b
>
> b.do_something_else()  # error: module has no attribute do_something_else
>
> It's not obvious that the error is caused by a cyclic import, and even if
> you can figure that out, there's no easy way to determine what's causing
> the cyclic import, as it could be in completely unrelated files.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/mypy/issues/1779>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACwrMhdH0LOH3EH8LpFvsmZjST3KMqofks5qQ_UggaJpZM4JCXaz>
> .
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by JukkaL** [comment]
Hmm this seems unrelated to the recent changes (of if related, it was probably unintentional). Anyway, the cyclic import shouldn't cause a problem like this, I think. If this repros on master this looks like a bug.

**Comment by Diggsey** [comment]
Yeah, I can't reproduce on master, closing as fixed.
