### ISSUE TITLE
Document new type parameter syntax (PEP 695)

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#17810]
#15238 is about overall support for PEP 695.

**Comment by TeamSpen210** [comment]
This might be overcomplicating things, but Cython has a similar need to [display two code styles](https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html#primes), which they handle via the [`sphinx-tabs`](https://github.com/executablebooks/sphinx-tabs) extension. That allows only showing the variant you want to use, making the page a little easier to read. If these are sticking around for a while in docs, maybe Mypy should do the same?

**Comment by JukkaL** [comment]
An interesting idea. I don't have a strong opinion -- we'd need to experiment with it before making a decision. I'm not going to switch to tabs at the moment, but we can consider it in the future.

**Comment by cdce8p** [comment]
> This might be overcomplicating things, but Cython has a similar need to [display two code styles](https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html#primes), which they handle via the [`sphinx-tabs`](https://github.com/executablebooks/sphinx-tabs) extension. That allows only showing the variant you want to use, making the page a little easier to read. If these are sticking around for a while in docs, maybe Mypy should do the same?

Opened https://github.com/python/mypy/pull/18264 so we can decide if it's helpful.
