### ISSUE TITLE
`reveal_type` not displayed in if-false blocks.

### ISSUE THREAD

**Issue by jonathanslenders** [python/mypy#17824]
**Bug Report**

Run mypy over the following code. It won't show the type.

```python
if False:
    reveal_type("hello")
```

This is not hugely problematic. However, there are situations where the expression from the if-block is statically evaluated to `False`:

```python
a: str | None

if isinstance(a, int):
    reveal_type(a)  # Also not displayed.
```

This is not expected, especially, when dealing with  more complex situations.

**Expected Behavior**

I'd expect the type to always be revealed, when using `reveal_type`, even if the type is `Never`.

**Your Environment**

- Mypy version used: 1.11.2
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.11.10

**Comment by brianschubert** [comment]
This is https://mypy.readthedocs.io/en/stable/common_issues.html#unreachable-code

Mypy doesn't type check unreachable code (which includes visiting `reveal_type` and the like), but you can enable [`--warn-unreachable`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-warn-unreachable) to get an error when a block is (unexpectedly) determined to be unreachable.

**Comment by jonathanslenders** [comment]
Thank you! In that case I think this issue can be closed.
