### ISSUE TITLE
stubgen often generates incorrect imports

### ISSUE THREAD

**Issue by Diggsey** [python/mypy#1782]
In examples like the following:

``` python
from x import y
```

Stubgen will often lose the `from x`, and simply generate an import like:

``` python
import y
```

**Comment by JukkaL** [comment]
Can you give a full, self-contained example where this happens?

**Comment by Diggsey** [comment]
```python
# stubtest/__init__.py
```

```python
# stubtest/a.py
from . import interfaces

class X(interfaces.Y):
    pass
```

```python
# stubtest/interfaces.py
class Y:
    pass
```

`> stubgen stubtest.a`

```python
# out/stubtest/a.pyi

# Stubs for stubtest_1.a (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import interfaces

class X(interfaces.Y): ...
```

**Comment by rapilabs** [comment]
stubgen doesn't keep track of imports; [it simply adds "import foo"](https://github.com/python/mypy/blob/2ca2eb4306df1e798f3eaa620b06a8b0698e3458/mypy/stubgen.py#L352)

**Comment by gvanrossum** [comment]
If you have an idea on how to fix this, please submit a PR -- we'll gladly
review it!

**Comment by rapilabs** [comment]
Hmm… not sure that the reference above pinged anyone, so bump: #3704

**Comment by dmoisset** [comment]
I just checked and I think #3169 solved this

**Comment by ilevkivskyi** [comment]
Yes, it looks like this is fixed now.
