### ISSUE TITLE
Can mypy just load the stubs rather than the modules?

### ISSUE THREAD

**Issue by zarif98** [python/mypy#17854]
Pylance is able to load my stubs after adding a "typings" folder to my directory but mypy even after setting up my directory location with my nested stubs is unable to find anything. Is it possible to load the stubs using mypy and not check the modules since these stubs are generated from my Python DLLs and are meant to aid cross development between the two languages.

**Comment by JelleZijlstra** [comment]
If you put stubs next to the files themselves, mypy will use them. However, the `typings` directory is specific to pylance and mypy does not use it.

**Comment by zarif98** [comment]
All my stubs are in their own nested directory similar to how our C# codebase looks with a __init__.pyi. Is there no way to load them? And give me some type of output?

**Comment by hauntsaninja** [comment]
See e.g. MYPYPATH and https://mypy.readthedocs.io/en/stable/running_mypy.html#how-imports-are-found
