### ISSUE TITLE
dict incorrectly being detected as "object"

### ISSUE THREAD

**Issue by noisecapella** [python/mypy#1786]
I narrowed down the problem to this repro case:

    LOGGING = {
        'handlers': {
        },
        'loggers': {
            'django': {
            },
            'django.request': {
            },
            'urllib3': {
            }
        },
    }
    
    LOGGING['handlers'].pop('syslog')

When I run mypy 0.4.2 on this file (named test.py) I get this error:

    test.py:14: error: "object" has no attribute "pop"

Thanks for your help!

**Comment by gvanrossum** [comment]
I'd add a type annotation to the LOGGING variable, something like `# type: Dict[str, <whatever you want>]`.

Do note that mypy currently doesn't support different (fixed) keys of a dict having different types -- that's probably what's biting you. That and the empty dicts.

**Comment by noisecapella** [comment]
The type annotation addresses the warning I got. FYI I got another warning after adding the type annotation. Not sure if it's a known problem or not but adding it here in case it's helpful. Here is the updated input:

    LOGGING = {
        'handlers': {
        },
        'loggers': {
            'django': {
            },
            'django.request': {
            },
            'urllib3': {
            }
        },
       }  # type: Dict[str, Dict[str, str]]
    
    LOGGING['handlers'].pop('syslog')

Warning:

    test.py:4: error: List item 0 has incompatible type "Tuple[str, Dict[None, None]]"
    test.py:4: error: List item 1 has incompatible type "Tuple[str, Dict[None, None]]"
    test.py:4: error: List item 2 has incompatible type "Tuple[str, Dict[None, None]]"

**Comment by rwbarton** [comment]
It looks like your `LOGGING` variable actually has a type like `Dict[str, Dict[str, Dict[_, _]]]` for some `_`s.

**Comment by noisecapella** [comment]
Yes you're right. When I update the type annotation accordingly it fixes the problem
