### ISSUE TITLE
mypy plugin "get_attribute_hook" called for assignment

### ISSUE THREAD

**Issue by AnjoMan** [python/mypy#17878]
**Bug Report**

I encountered unexpected behaviour while trying to develop a mypy extension: one of the plugin hooks is behaving in a way i did not expect, and which the documentation says it shouldn't.

**To Reproduce**

Create a directory with the following files:

1. A mypy plugin defining a `get_attribute_hook`

```python
# mypy_plugin.py
from typing import Type
import mypy.plugin


def plugin(version: str):
    return CustomPlugin


class CustomPlugin(mypy.plugin.Plugin):
    def get_attribute_hook(self, fullname: str):
        if "CheckedClass" in fullname:
            return attr_access_hook
        return None


def attr_access_hook(ctx: mypy.plugin.AttributeContext) -> Type:
    ctx.api.fail(f"You shouldn't access attrs of CheckedClass", ctx.context)
    return ctx.default_attr_type  # type: ignore
```

2. Entry in pyproject.toml to have mypy integrate with the plugin
```toml
# pyproject.toml
[tool.mypy]
plugins = "mypy_plugin.py"
```
3. test code:

```python
# attr_access.py
class CheckedClass:
    name: int

obj_1 = CheckedClass()
obj_1.name = "sir phancalot"
name = obj_1.name  # `get_attribute_hook` should be called for this
```

I should then run mypy on the test code using the command `$ mypy attr_acces.py`

**Expected Behavior**

I expect two mypy errors:

* once for line 6 of `attr_access.py`, where i assign a string to an attribute that was declared as `int`
* once for line 7 of `attr_access.py`, where my code accesses the 'name' attribute of an instance of `CheckedClass`, triggering my hook

**Actual Behavior**

I get three errors

* once for the incorrect assignment
* once for line 7 where the code triggers my hook
* additionally for line 6 where i *assign* to the attribute. 
* 

This indicates that `get_attribute_hook` is called for attribute assignment, in addition to attribute access. This is surprising to me and runs counter to what the documentation on this function says: https://mypy.readthedocs.io/en/stable/extending_mypy.html#current-list-of-plugin-hooks

here is my console output when i run mypy against this file:
```
$ mypy attr_access.py
attr_access.py:6: error: You shouldn't access attrs of CheckedClass  [misc]
attr_access.py:6: error: Incompatible types in assignment (expression has type "str", variable has type "int")  [assignment]
attr_access.py:7: error: You shouldn't access attrs of CheckedClass  [misc]
Found 3 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.11.0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): see reproduce steps
- Python version used: 3.12.5

**Comment by brianschubert** [comment]
I wonder if this is a docs issue? Testing this in a debugger, it seems that `get_attribute_hook` is called on *both* assignments and method calls (contrary to what the current docs suggest), and have since at least v1.0.0.

Looks like the current wording about assignments and method calls was added in #6371 (cc @ilevkivskyi and @lincolnq). Maybe someone knows if there is more context to this

(can someone add https://github.com/python/mypy/labels/topic-plugins?)

**Comment by ilevkivskyi** [comment]
Yes, this is a docs issue. This plugin hook is called on both attribute access and attribute assignment. I don't think it should be called on method calls (it may be called on decorated methods for technical reasons). In any case, the "not assignments" parts should be removed from the docs.

This also make me think we can pass `is_lvalue` to `AttributeContext` for people who wants to know whether it an assignment, or an access.

**Comment by lincolnq** [comment]
Whew! This is a throwback... sorry I don't remember what I was thinking in 2019 or whether the doc I wrote was correct then, let alone now. Wish I could help more, but I am pretty far away from the mypy project now.

**Comment by AnjoMan** [comment]
> This also make me think we can pass is_lvalue to AttributeContext for people who wants to know whether it an assignment, or an access.

Ok, yes, this would address what I am trying to accomplish with my plug-in.  I did spend some time looking around to see if this is already available, but I can do a bit more digging to see what it would look like to pass this info in. Thanks!

**Comment by brianschubert** [comment]
> This also make me think we can pass is_lvalue to AttributeContext for people who wants to know whether it an assignment, or an access.

Happy to make a PR unless someone else is interested :)

Do you think there are any other `MemberContext` attributes that would be worth forwarding to `AttributeContext` as well while we're making changes? Like maybe `is_self`?

Also, since `AttributeContext` is a named tuple, do you think we need to worry about downstream users relying on its size/ordering?

**Comment by ilevkivskyi** [comment]
I am closing this as fixed by the above PR.
