### ISSUE TITLE
An edit button in docs does not work (gives 404)

### ISSUE THREAD

**Issue by hnykda** [python/mypy#17870]
**Documentation**

When clicking the edit button at the top of the page, it gives me 404. For example:

![image](https://github.com/user-attachments/assets/18d96ef1-a818-4857-899e-5377ff39fdb4)

leads to 

https://github.com/python/mypy/edit/789f02c83a5d5cb35f5e33ba91df46c8fea6b28e/docs/source/generics.rst

which doesn't exist.

**Comment by brianschubert** [comment]
I think this is because RTD's `stable` is picking up on the latest release tag, but GitHub only supports editing files from branches. 

The edit button works as expected if you switch the version to `latest`, which will bring you to an edit tab against the `master` branch.

**Comment by hnykda** [comment]
Yeah, sounds like that's the problem. Nevertheless, it's still a problem, is it not? 😁
