### ISSUE TITLE
TypedDict Generic Inheritance doesnt seem to work as expected

### ISSUE THREAD

**Issue by merc1031** [python/mypy#17887]
**Bug Report**

It seems that TypedDict Generic Inheritance doesnt work. So i can't reduce the boilerplate of typing my data.

**To Reproduce**

https://mypy-play.net/?mypy=1.11.0&python=3.10&gist=a46093294dd6ab73516a87f9bb6c8f08
```python
from typing import Any, Dict, TypedDict, Generic, TypeVar

class Inner(TypedDict):
    inner_field1: Dict[str, Any]
    inner_field2: Dict[str, Any]
    
T = TypeVar("T")


class OuterGeneric(TypedDict, Generic[T]):
    outer_field: str
    

def fn_generic(message: OuterGeneric[Inner]):
    rels = message["inner_field1"]  # main.py:15: error: TypedDict "OuterGeneric[Inner]" has no key "inner_field1"  [typeddict-item]
    event = message["outer_field"]

class Outer(TypedDict, Inner):
    outer_field: str
    
def fn(message: Outer):
    rels = message["inner_field1"]
    event = message["outer_field"]
```

**Expected Behavior**

I expect the generic version to work just like the hardcoded 2nd version. 

**Actual Behavior**

# main.py:15: error: TypedDict "OuterGeneric[Inner]" has no key "inner_field1"  [typeddict-item]

The inherited keys are not visible

**Your Environment**

- Mypy version used: 1.11.0
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10.11

**Comment by brianschubert** [comment]
Generic types don't inherit from their type parameters. Just as `list[int]` doesn't inherit from `int`, `OuterGeneric[Inner]` doesn't inherit from `Inner`.

If you want to inherit keys from `Inner`, you'll need to explicitly subclass it, as you did in `Outer`. Alternatively, you could include `Inner` via a field whose type is specified by the generic parameter:
```python
class OuterGeneric(TypedDict, Generic[T]):
    inner: T
    outer_field: str

def foo(x: OuterGeneric[Inner]):
    reveal_type(x["inner"])  # N: TypedDict('__main__.Inner', {'inner_field1': builtins.dict[builtins.str, Any], 'inner_field2': builtins.dict[builtins.str, Any]})
    reveal_type(x["inner"]["inner_field1"])  # N: Revealed type is "builtins.dict[builtins.str, Any]"
```

**Comment by merc1031** [comment]
Thanks for the answer.

I guess what im  trying to do is more like the following. I want to treat `OuterGeneric` as a envelope (add some keys, but extend from the `Inner` value generically



```
class Inner(TypedDict):
    inner_field1: Dict[str, Any]
    inner_field2: Dict[str, Any]
 

class DifferentInner(TypedDict):
    inner_field3: str
 
T = TypeVar("T")


class OuterGeneric(TypedDict, Generic[T]):
    outer_field: str

def fn_generic(message: OuterGeneric[Inner], message2: OuterGeneric[DifferentInner]):
    inner_field1 = message["inner_field1"]
    outer_field = message["outer_field"]
    
    inner_field3 = message2["inner_field3"]
    outer_field = message2["outer_field"]
```

**Comment by brianschubert** [comment]
This tracker is intended for mypy bugs. Since mypy is behaving as expected here, this probably isn't the right place to discuss.

For questions about Python and/or its type system, I'd recommend asking on https://discuss.python.org

**Comment by merc1031** [comment]
Sure.
Thanks for taking the time!
