### ISSUE TITLE
pre-commit not installed via test-requirements.txt

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#17902]
When I run `python runtests.py` in a freshly created venv where I've installed test-requirements.txt, I get this error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'pre-commit'
```
`pip install pre-commit` fixes this, but I think we should install it automatically in `test-requirements.txt`.

**Comment by gaurovgiri** [comment]
Hello @JukkaL, I would like to work on this issue. Could you assign this to me?

**Comment by JelleZijlstra** [comment]
Feel free to work on this issue and send in a PR!

**Comment by Donald-0017** [comment]
Hi, JukkaL,I am very interested in thsi issue,would you like to assign it to me ?Thank you. @JukkaL

**Comment by gaurovgiri** [comment]
@JukkaL and @JelleZijlstra, I have created a PR. Can someone review it and help me resolve the failed task in github actions. Your help would be much appreciated.
