### ISSUE TITLE
Mypy see invalid syntax about valid syntax in recent Python version

### ISSUE THREAD

**Issue by buxx** [python/mypy#17914]
**Bug Report**

Mypy report a syntax error what is not in Python3.12+ while `--python-version` arg is used.

**To Reproduce**

*This reproduction steps use `uv` to make python 3.12 install easier but got same result with standard tools*. 

```
➜  cd /tmp
➜  uv venv --python 3.12.6 venv                                              
Using Python 3.12.6
Creating virtual environment at: venv
Activate with: source venv/bin/activate
➜  . venv/bin/activate
(venv) ➜ uv pip install mypy
Resolved 3 packages in 139ms
Installed 3 packages in 22ms
 + mypy==1.11.2
 + mypy-extensions==1.0.0
 + typing-extensions==4.12.2
(venv) ➜  /tmp echo 'import typing               
import enum

class MyEnum(enum.Enum):
    ONE = "ONE"

    def name(self) -> str:
        match self:
            case self.ONE:
                return "1"
            case _:
                typing.assert_never(self)
' > test.py
(venv) ➜ mypy --python-version=3.12 test.py 
test.py:9: error: invalid syntax; you likely need to run mypy using Python 3.12 or newer  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```

**Expected Behavior**

mypy don't see syntax error at line 9.

**Actual Behavior**

mypy see syntax error at line 9.

**Your Environment**

- Mypy version used: `1.11.2`
- Mypy command-line flags: `--python-version=3.12`
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.12.6

**Comment by JelleZijlstra** [comment]
You are likely running a mypy executable that is based on an earlier version of Python. Try running `which mypy` to figure out where it came from.

**Comment by hauntsaninja** [comment]
Yes, or try `hash -r` before running mypy.

Although I don't actually see what the syntax error is here, so I think there's also something not right with the repro steps provided and can't repro any issue on any version combination myself

**Comment by JelleZijlstra** [comment]
Probably the match statement, meaning they're running mypy with Python 3.9 or earlier.

**Comment by hauntsaninja** [comment]
Ah I forgot that Python 3.9 ever existed

**Comment by hauntsaninja** [comment]
When I made this error message better, I wanted to also include the user's current version. But it made the testing complicated, so I didn't :-/

**Comment by buxx** [comment]
Hi, there is result of `wich` :

```
➜  /tmp uv venv --python 3.12.6 venv                 
Using Python 3.12.6
Creating virtual environment at: venv
Activate with: source venv/bin/activate
➜  /tmp . venv/bin/activate
(venv) ➜  /tmp uv pip install mypy
Resolved 3 packages in 150ms
Installed 3 packages in 20ms
 + mypy==1.11.2
 + mypy-extensions==1.0.0
 + typing-extensions==4.12.2
(venv) ➜  /tmp mypy --version
mypy 1.11.2 (compiled: yes)
(venv) ➜  /tmp which mypy
/home/user/.local/bin/mypy
```

So, executed mypy is not the venv mypy ... So two point : 

- (which not concern `python/mypy` source code) Why venv mypy is not used in prior
- mypy, when executed with old python (how to confirm taht ?) should work about indicated `--python-version` or fail if it can't

**Comment by hauntsaninja** [comment]
Like I said before, try `hash -r`

mypy is warning about old Python, that's what the "you likely need to run mypy using Python 3.12 or newer" is about.

**Comment by JelleZijlstra** [comment]
> How should I use `hash -r` ?

You should run this command. It clears your shell's cache that caches the location where it finds the `mypy` executable.
