### ISSUE TITLE
`dmypy status` reports as "stuck" when it's busy checking files

### ISSUE THREAD

**Issue by Redoubts** [python/mypy#18008]
I wanna use dmypy to help with checking my large company codebase. I've noticed on first check, or when checking a large number of files it will take a few dozen seconds to return (expected for my large repo). However, when I do `dmypy status` on it during this time, I see 

```
error                   :  timed out
Daemon is stuck; consider /usr/scratch/pthompson/junk/ops3venv11/bin/dmypy kill
```

I don't think this is correct. It's not "stuck", it's just busy and I'm fairly confident it will return an answer eventually. But I think this means `dmypy run` will attempt to start another daemon during this time (if I spam it with a for loop I can get into a funky state); and it might be harder to build tooling around a `check`/`start`/`stop` flow. Is there a way to get a better status than this?

**Comment by kcornw** [comment]
I find the following code:

```python
# mypy/dmypy/client.py

@action(status_parser)
def do_status(args: argparse.Namespace) -> None:
    ...
    response = request(
        args.status_file, "status", fswatcher_dump_file=args.fswatcher_dump_file, timeout=5
    )
    if args.verbose or "error" in response:
        show_stats(response)
    if "error" in response:
        fail(f"Daemon is stuck; consider {sys.argv[0]} kill")
    ...
```

It seems the current implementation sets a 5-second timeout for IPC communication to `dmypy` server, which is why you're seeing the "stuck" message. This timeout is intended to detect genuinely unresponsive states, but as you've observed, it doesn't account for scenarios where the daemon is just busy.
