### ISSUE TITLE
Allow function variants with different signatures to be conditioned on sys.version_info

### ISSUE THREAD

**Issue by elazarg** [python/mypy#1801]
Function signature may vary between versions, see e.g. dis.dis. But encoding it on typeshed is not supported by mypy:

    error: All conditional function variants must have identical signatures

**Comment by gvanrossum** [comment]
Actually this is a duplicate of #689.

**Comment by elazarg** [comment]
How so? 
"Implement `TypeVar(..., bound=<boundary_type>)`"

**Comment by gvanrossum** [comment]
Sorry, the correct issue is #698. I'll delete the irrelevant comments.
