### ISSUE TITLE
Type not being detected for instance member inside instance method

### ISSUE THREAD

**Issue by noisecapella** [python/mypy#1802]
According to [this documentation](https://mypy.readthedocs.io/en/latest/class_basics.html#instance-and-class-attributes) the type of an instance can be declared with a comment:

    class Clazz:
        number = None # type: int
        def __init__(self, number: int) -> None:
            self.number = number
    
    Clazz(3).number.format("")

When mypy is run on this file (I'm using 0.4.2 from pip) I get this warning which looks correct to me:

    test.py:6: error: "int" has no attribute "format"

If I move the last line inside the `__init__` function I get the same warning, as expected. However if I move it inside another method, it no longer produces the expected warning:

    class Clazz:
        number = None # type: int
        def __init__(self, number: int) -> None:
            self.number = number
    
        def format(self):
            self.number.format("")

I feel like it should output a similar warning here for the last line

**Comment by rwbarton** [comment]
In your last program `format` does not have a type signature, so mypy won't type check it by default. You can add a type signature or try `mypy --check-untyped-defs`.

**Comment by noisecapella** [comment]
Thanks, adding the type signature caused the warning to appear. `--check-untyped-defs` did not work here FYI

**Comment by rwbarton** [comment]
Oh right, that's because mypy doesn't assume that `format` is necessarily intended to be used as a method of `Clazz` objects. See #1598.
