### ISSUE TITLE
Support enums in unions per PEP 484

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1803]
See this PR for PEP 484: https://github.com/python/typing/pull/240

Because we know that Enum classes cannot be further subclassed, picking apart a value that could be a specific enum or some other type by comparing to all possible values of the enum should be enough to conclude that in the "else" clause the value cannot be an instance of that enum any more, so it must be the other type (examples in the linked PEP section).

**Comment by gvanrossum** [comment]
This should work for other singletons, specifically Ellipsis. (Though it's unclear how its type should be spelled since builtins.ellipsis only exists in the stubs, not in the actual runtime.)

**Comment by ilevkivskyi** [comment]
It looks like this would be easier to implement after we support literal types.
