### ISSUE TITLE
pre-commit.ci is not running on PRs

### ISSUE THREAD

**Issue by brianschubert** [python/mypy#18032]
A recent PR got a [CI failure](https://github.com/python/mypy/actions/runs/11502495483/job/32017596698#step:9:67) due to formatting issues instead of the usual auto-fix commit from \[pre-commit.ci\].

This looks like the same problem as https://github.com/python/typeshed/issues/12896

**Comment by hauntsaninja** [comment]
I clicked a button, we'll see if it did anything. Not sure if I have the right set of perms

**Comment by JelleZijlstra** [comment]
Verified this is fixed now by pushing a formatting change to #18018.
