### ISSUE TITLE
Upper-cased raw strings not supported

### ISSUE THREAD

**Issue by FichteFoll** [python/mypy#1804]
``` python
var = R"I'm a raw string"
```

```
E:\Temp>mypy upper_case_raw.py
upper_case_raw.py:1: error: Unterminated string literal
```

I believe this will be solved by the updated parser (https://github.com/python/mypy/issues/1353) but couldn't verify since I was unable to install the `typed-ast` pypi module on my Windows machine (no binary wheels and couldn't compile).

**Comment by gvanrossum** [comment]
Yeah, the new parser fixes this.

**Comment by ddfisher** [comment]
(And FYI we're working on making `typed-ast` work on Windows soon.)

**Comment by gvanrossum** [comment]
I'm going to close this as a won't fix because the new parser will solve this and we're not going to put any work in the old parser/lexer.
