### ISSUE TITLE
ignores follow_imports=skip

### ISSUE THREAD

**Issue by sezanzeb** [python/mypy#18041]
**Bug Report**

```
root@157d6a2f402c:/foo mypy --version
mypy 1.13.0 (compiled: yes)
```

```
root@157d6a2f402c:/foo cat mypy.ini 
[mypy]
disable_error_code=import,var-annotated,attr-defined
exclude=(.*simple_pid.*|.*.pyi)
follow_imports=skip

[mypy-simple_pid.*]
follow_imports = skip
```

```
root@157d6a2f402c:/foo mypy src/foo
src/simple_pid/PID.pyi:50: error: Name "output_limits" already defined on line 22  [no-redef]
```

still goes on to check `src/simple_pid/PID.pyi`

**To Reproduce**

**Expected Behavior**

to not check PID.pyi.

**Actual Behavior**

checks PID.pyi

**Your Environment**

- debian:bullseye-slim docker image
- Python 3.9.2

**Comment by hauntsaninja** [comment]
The verbose log redacts too much. You probably need `follow_imports_for_stubs = true`
