### ISSUE TITLE
Missing Liskov violation with generic subclass

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#18064]
```
# mypy: disable-error-code=empty-body
from typing import Any

class A: ...
class B(A): ...

class Map[Input, Output]:
    def map(self, x: Input) -> Output: ...

class Sub[A_t: A](Map[A_t, A_t]):
    def map[T: A](self, x: T) -> T: ...
    

# mypy gets it correct here
class MapSimple[Base]:
    def map(self, x: Base) -> None: ...
    
class SubSimple[A_t: A](MapSimple[A_t]):
    def map[T: A](self, x: T) -> T: ...
```

https://mypy-play.net/?mypy=latest&python=3.12&gist=7a18aaa2bcc4d8574dddf27b05df2308

**Comment by hauntsaninja** [comment]
```
# mypy: disable-error-code=empty-body
class Map[T]:
    def map(self, x: T) -> T: ...
    
class Sub[OT](Map[OT]):
    def map[T](self, x: T) -> T: ...
```

**Comment by sterliakov** [comment]
In your 2nd block `None` is a problem, not TypeVar compatibility. What exactly is violated here? Base contract of `Map` guarantees that and `Input` is converted to `Output`, which after substitution means `A_t` is converted to `A_t` (itself). The second signature does guarantee that as well, but also supports processing other `A` subtypes not assignable to `A_t` - the contract still holds, for any `x: T` `x` is also assignable to `A_t`. 

Could you clarify the violation here? Perhaps I'm already asleep, but this implementation looks sane for my eyes.

**Comment by hauntsaninja** [comment]
Thanks, you're right that this makes no sense. I must have confused myself and mypy does correctly infer invariance here when you try to check subtyping
