### ISSUE TITLE
Final works with Literal, but Final[str] don't

### ISSUE THREAD

**Issue by fjossandon** [python/mypy#18080]
**Bug Report**

I have a function where 1 of the arguments only supports 2 valid string values, for which I made constants that are used when the function is called, and added a raise inside the function in case the argument value was not one of the supported ones. Originally, I typed both the constants and the arguments as "str" and Mypy was fine with it. Then a colleague suggested that, since the argument only supported 2 strings, I should use "Literal" instead of "str" to clarify the valid values.
I added the Literal but Mypy now complained about the str constants being incompatible with the Literals.
```
error: Argument 2 to "foo" has incompatible type "str"; expected "Literal['origin', 'destination']"  [arg-type]
```
So after reading some more, I found that I could use `Final` to establish that the constants would never change their value (https://docs.python.org/3/library/typing.html#typing.Final), and the error disappeared. Made sense because using Final should be the same as hardcoding the string in the function call. But then I thought "I should add the type to Final" like in the documentation example (`TIMEOUT: Final[int] = 10`), and switched it to `Final[str]` and the incompatible error came back...

**To Reproduce**

```python
import typing as ty

ORIGIN_DB: ty.Final[str] = "origin"
DESTINATION_DB: ty.Final[str] = "destination"


def foo(
    input_str: str,
    database: ty.Literal["origin", "destination"],
) -> str:
    if database not in (ORIGIN_DB, DESTINATION_DB):
        msg = f"Unsupported database value: {database}"
        raise ValueError(msg)
    return f"{input_str}, {database}"

print(foo("input", ORIGIN_DB))
print(foo("input", DESTINATION_DB))

```

**Expected Behavior**

After reading about Final, I considered using it in all my constants, and I thought I should also add the type to Final for completeness, be it str, int, or else. So since Mypy was already fine with the use of Final and Literal, I expected that simply adding the type to it would still pass. But it seems that the use of `Final[str]` is somehow making Mypy treat it like the regular `str` typing, ignoring the `Final` part. If the `[str]` part is removed, the errors goes away. 

**Actual Behavior**

The incompatible error appears:
```
$ mypy --strict typing_issue.py 
typing_issue.py:16: error: Argument 2 to "foo" has incompatible type "str"; expected "Literal['origin', 'destination']"  [arg-type]
typing_issue.py:17: error: Argument 2 to "foo" has incompatible type "str"; expected "Literal['origin', 'destination']"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

I used `mypy --strict` command line, and have a pyproject.toml with a `[tool.mypy] ignore_missing_imports = true` line, but that should not be relevant here.
My versions:
```
$ pip list | grep mypy
mypy                       1.13.0
mypy-extensions            1.0.0

$ python -V
Python 3.11.6
```
Best regards!

**Comment by hamdanal** [comment]
Mypy is correct to emit an error here. You explicitly declare the type of these variables as `str` when you annotate them with `Final[str]` so they are not valid targets for `Literal[]`.

When you declare them with `Final` only, mypy is smart enough to infer their type as their literal value, thus they become valid for use as `Literal[]` targets. If you like to be explicit you can do `ORIGIN_DB: ty.Final[ty.Literal["origin"]] = "origin"` but this is redundant.

You can refer to the [python typing documentation](https://typing.readthedocs.io/en/latest/guides/libraries.html#literals) or the [mypy documentation](https://mypy.readthedocs.io/en/stable/literal_types.html) to read more on the topic.

**Comment by fjossandon** [comment]
Hello @hamdanal,
I see, thanks for the explanation and the links!
