### ISSUE TITLE
Mismatched parameter types not checked assigning `functools.partial()` to `Callable[]`

### ISSUE THREAD

**Issue by andersk** [python/mypy#18083]
**Bug Report**

When assigning `functools.partial(f, arg)` to `Callable[[OtherArgs], Ret]`, mypy doesn’t check that `[OtherArgs]` matches the remaining parameters of `f`.

**To Reproduce**

```python
from functools import partial
from typing import Callable

def f(x: int, y: int) -> None:
    print(x + y)

g: Callable[[str], None] = partial(f, 1)
g("s")
```

[Playground](https://mypy-play.net/?mypy=latest&python=3.12&flags=strict&gist=0297c94eb0e453274437df3a817f9782)

**Expected Behavior**

The assignment of `g` should be a type error. `partial(f, 1)` should only be assignable to `Callable[[int], None]`, not `Callable[[str], None`.

**Actual Behavior**

No error from mypy; the code crashes at runtime.

**Your Environment**

- Mypy version used: 1.13.0
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.12

**Comment by brianschubert** [comment]
Related / maybe duplicate: #17461

**Comment by andersk** [comment]
Sure, closing as duplicate of #17461.
