### ISSUE TITLE
variance inferred differently when instance attribute is assigned with a type annotation

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#18118]
```py
from typing import Never


class Foo[T]:
    def __init__(self, value: T) -> None:
        self.__a: T = value
        reveal_type(self.__a)  # T`1
        foo: Foo[object] = self  # no error


class Bar[T]:
    def __init__(self, value: T):
        self.__a = value
        reveal_type(self.__a)  # T`1
        foo: Foo[object] = self  # error: Incompatible types in assignment (expression has type "Bar[T]", variable has type "Foo[object]")  [assignment]
```
[playground](https://mypy-play.net/?mypy=latest&python=3.13&flags=show-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-reexport%2Clocal-partial-types%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=fe4fc933fe5a60d0e18f76230f68cf8c)

the behavior on the `Foo` class is correct (covariant) because `__a` is a private member therefore it should not contribute to the inferred variance of `T`

**Comment by hamdanal** [comment]
Mypy is working as expected here. If `Bar` inherits from `Foo` or the last line is changed to `foo: Bar[object] = self` the error goes away.

**Comment by DetachHead** [comment]
oops that was a mistake. there was an actual issue here that i was trying to minify but i guess i messed up in the process. will investigate further and raise another issue with a proper repro
