### ISSUE TITLE
Config to disallow global `# type: ignore` and force ignoring specific errors

### ISSUE THREAD

**Issue by HansAarneLiblik** [python/mypy#18127]
**Feature**

I'd like there to be a configuration option to disable usages of  `# type: ignore` and force developers to use error specific ignores, like `# type: ignore[assignment,misc]`

**Pitch**

Ignoring everything does not make sense and is prone to errors when something is to be refactored. 
In my opinion, most ignores should also contain a comment why this ignore is used. Having specific errors is also helpful for these scenarios for visibility

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-type-ignore-include-an-error-code-ignore-without-code

**Comment by HansAarneLiblik** [comment]
Thanks! Indeed this works like a charm
I thought it had to exist, but could not find it.

Keep up the awesome work
