### ISSUE TITLE
mypy doesn't flag continue/break/return in except*

### ISSUE THREAD

**Issue by jakkdl** [python/mypy#18123]
**Feature**
continue/break/return in except* is a syntax error, see https://peps.python.org/pep-0654/#forbidden-combinations. 

```python
def foo():
    for _ in range(5):
        try:
            ...
        except* Exception:
            continue
        except* ValueError:
            break
        except* TypeError:
            return
```
```sh
$ mypy --python-version=3.11 foo.py
Success: no issues found in 1 source file
$ mypy --version
mypy 1.13.0 (compiled: yes)
```

**Pitch**
mypy does give an error if you try to combine `except` and `except*`, and as far as I know it flags all other syntax errors as well, so should probably handle this too. It might also cause users to adjust code to avoid `unreachable code` needlessly, when in fact they have bigger problems to fix first.

**Comment by coldwolverine** [comment]
I'd like to work on this!

**Comment by brianschubert** [comment]
@coldwolverine great! You can check out [CONTRIBUTING.md](https://github.com/python/mypy/blob/master/CONTRIBUTING.md) and the [Developer Guides](https://github.com/python/mypy/wiki/Developer-Guides) for contributing guidelines and tips on where to start. 

I'm guessing this feature will involve adding some new state to the semantic analyzer to keep track of whether its currently inside an `except*` block. While working on this feature, be mindful of edge cases like nested try statements and function definitions or loops inside the  `except*` block.

**Comment by Ujjwal-Bajpayee** [comment]
I propose enhancing mypy to detect syntax errors involving continue, break, and return in except* blocks, as outlined in [PEP 654] Currently, mypy 1.13.0 doesn’t flag these issues, even though Python 3.11 treats them as syntax errors.
Suggested Enhancements:
Add Syntax Checks: Ensure mypy flags the use of control flow statements in except* blocks.
Clear Error Messages: Provide explanations to help developers understand why these statements are not allowed.
Benefits:
Consistency: Aligns mypy with Python’s syntax rules.
Early Issue Detection: Catches errors before runtime.
User Guidance: Helps developers correct code efficiently.
This would improve mypy’s reliability and support for Python 3.11+. Thoughts?
