### ISSUE TITLE
[1.13.0] `incompatible type "str | list[str]"; expected "str | int | list[str | int]"`

### ISSUE THREAD

**Issue by Jacobfaib** [python/mypy#18121]
**Bug Report**

`mypy` fails to deduce that `str | list[str]` is a subset of `str | int | list[str | int]`.

**To Reproduce**

```python
def foo(x: str | int | list[str | int]) -> None:
    pass


def passthru(x: str | list[str]) -> None:
    foo(x)
```

**Expected Behavior**

No type check error.

**Actual Behavior**

```sh
$ mypy mypy_bug.py
mypy_bug.py:14: error: Argument "x" to "foo" has incompatible type "str | list[str]"; expected "str | int | list[str | int]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: mypy 1.13.0 (compiled: yes)
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.12.7

**Comment by brianschubert** [comment]
Hi! This is https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance

Like most mutable generic collections, `list` is invariant, so `list[str]` is not a subtype of `list[str | int]`. Consider using a covariant collection type, like `Sequence[str | int]` or `Iterable[str | int]`.
