### ISSUE TITLE
Mypy crashes in 1.13.0 due to hybrid properties comparison

### ISSUE THREAD

**Issue by kylieatalan** [python/mypy#18120]
**Crash Report**

When running mypy on the following lines (error is on the `Job.inbox_id ==Inbox.inbox_id` line) : 
```
return Job.query.outerjoin(
        Inbox,
        Job.inbox_id ==Inbox.inbox_id
    )
```
I get the error: 
```
error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.13.0
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 5848, in accept
  File "mypy/nodes.py", line 2141, in accept
  File "mypy/checkexpr.py", line 3621, in visit_comparison_expr
  File "mypy/checkexpr.py", line 3775, in dangerous_comparison
  File "mypy/meet.py", line 580, in is_overlapping_types
AssertionError: <class 'mypy.types.Overloaded'> vs <class 'mypy.types.Overloaded'>
```
In the above code, both Job.inbox_id and Inbox.inbox_id are hybrid properties, which is I think what is causing the issue
**Traceback**

```
(Insert traceback and other messages from mypy here -- use `--show-traceback`.)
```

**To Reproduce**

(Write what you did to reproduce the crash.  Full source code is
appreciated.  We also very much appreciate it if you try to narrow the
source down to a small stand-alone example.)

**Your Environment**

- Mypy version used: 1.13.0
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used:
- Operating system and version:

**Comment by hauntsaninja** [comment]
Could you provide a full repro?

**Comment by emmatyping** [comment]
Closing as no response from reporter. If you are able to provide more code/context, or test if it is a regression, we can re-open.
