### ISSUE TITLE
Inconsistent mypy behavior with overloaded == operator in BoundedLinearExpression

### ISSUE THREAD

**Issue by KowalMar** [python/mypy#18130]
**Bug Report**

When using the == operator in combination with cp_model.BoundedLinearExpression in OR-Tools, mypy incorrectly infers the result type as bool instead of BoundedLinearExpression, resulting in a type error. However, other comparison operators (e.g., >=, <=) work without issues, suggesting an inconsistency in mypy's handling of overloaded == operators. This appears to be a bug, as the == operator should return a BoundedLinearExpression rather than a bool in this context.

**To Reproduce**

```python
from ortools.sat.python import cp_model

model = cp_model.CpModel()
i = model.NewIntVar(0, 10, 'i')
j = model.NewIntVar(0, 10, 'j')

# Causes a mypy error: Argument has incompatible type "BoundedLinearExpression | bool"; expected "BoundedLinearExpression"
expr: cp_model.BoundedLinearExpression = i + j == 5

# This works fine with other comparison operators
expr_ge: cp_model.BoundedLinearExpression = i + j >= 5
```

**Expected Behavior**

mypy should infer i + j == 5 as BoundedLinearExpression instead of bool, just as it does with other operators like >= and <=.

**Actual Behavior**

mypy raises an error for i + j == 5, incorrectly inferring a type of BoundedLinearExpression | bool and flagging it as incompatible with the expected BoundedLinearExpression.

**Your Environment**

- Mypy version used: 1.11.2
- Python version used: 3.11.7
- Ortools version used: 9.11.4210

**Comment by brianschubert** [comment]
Looks like this is an issue with ortools' stubs. 

The expression `i + j` has type `LinearExpr`, and `LinearExpr.__eq__` is [typed as](https://github.com/google/or-tools/blob/ed94162b910fa58896db99191378d3b71a5313af/ortools/sat/python/cp_model.py#L565):
```python
BoundedLinearExprT = Union["BoundedLinearExpression", bool]

class LinearExpr:
    # ...
    def __eq__(self, arg: LinearExprT) -> BoundedLinearExprT:
        ...
```
Mypy is correct to complain that `BoundedLinearExpression | bool` isn't assignable to `BoundedLinearExpression`. 

In order for mypy to be able to infer a return type of `BoundedLinearExpression`, `LinearExpr.__eq__` would need to use some overloads instead of returning a union. Something like the following:
```python

class LinearExpr:
    @overload
    def __eq__(self, arg: LinearExprT) -> BoundedLinearExpression: ...  # type: ignore[overload-overlap]
    @overload
    def __eq__(self, arg: object) -> Literal[False]: ...

```

**Comment by brianschubert** [comment]
Closing this issue since mypy is behaving as expected. I suggest opening an issue with `ortools` to see if the stubs can be improved.

In the meantime, you can use a `# type: ignore` comment or `cast("cp_model.BoundedLinearExpression", i + j == 5)` to make this code type check.

**Comment by KowalMar** [comment]
Thank you, raised this issue in ortools.
