### ISSUE TITLE
Change in inference of overloads involving `Hashable` and `slice` now that `slice` is generic

### ISSUE THREAD

**Issue by AlexWaygood** [python/mypy#18149]
**Bug Report**

Consider the following Python snippet, saved as `foo.pyi`:

```py
from typing import assert_type, overload, Hashable

class Foo: ...

class DataFrame:
    @overload
    def __getitem__(self, key: slice) -> DataFrame: ...
    @overload
    def __getitem__(self, key: Hashable) -> Foo: ...


df = DataFrame()
assert_type(df[1:], DataFrame)
assert_type(df[:2], DataFrame)
```

Prior to [the recent change to make `slice` generic in typeshed](https://github.com/python/typeshed/pull/11637), mypy used to emit no errors on this snippet. However, mypy on the `master` branch emits the following errors:

```
foo.pyi:7: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
foo.pyi:13: error: Expression is of type "Any", not "DataFrame"  [assert-type]
foo.pyi:14: error: Expression is of type "Any", not "DataFrame"  [assert-type]
```

The first error here seems reasonable to me, but it's unclear to me why mypy now infers `Any` as the result of the `df` subscriptions. This snippet is minimized from the sole new mypy_primer error reported in https://github.com/python/typeshed/pull/11637#issuecomment-2435268577.

**To Reproduce**

https://mypy-play.net/?mypy=master&python=3.12&gist=339ba7f72c9048770ce15d6dc75207a1

**Your Environment**

- Mypy version used: mypy 1.14.0+dev.2ebc690279c7e20ed8bec006787030c5ba57c40e (compiled: no)

**Comment by randolf-scholz** [comment]
I think this is because since python 3.12, slice is hashable, hence it satisfies both overloads and mypy performs a join of the return types.

**Comment by brianschubert** [comment]
> I guess there is some legacy code responsible for dealing with literal slices in `__getitem__` that's going haywire?

Indeed, this is actually hardcoded into the expression checker:

https://github.com/python/mypy/blob/2ebc690279c7e20ed8bec006787030c5ba57c40e/mypy/checkexpr.py#L5609-L5619

**Comment by brianschubert** [comment]
Actually, my previous comment wasn't as far from the mark as I thought :laughing: 

The difference between slices expression and non-literal slices does come down to the hardcoded analysis in the expression checker, specifically the return:

https://github.com/python/mypy/blob/2ebc690279c7e20ed8bec006787030c5ba57c40e/mypy/checkexpr.py#L5619

This erases any type information and makes all slice expressions be treated as `slice[Any, Any, Any]`.
