### ISSUE TITLE
Distribute in code type information

### ISSUE THREAD

**Issue by tharvik** [python/mypy#1816]
So, section "Storing and distributing stub files" in [PEP 484](https://www.python.org/dev/peps/pep-0484/#storing-and-distributing-stub-files) gives a way to distribute `*.pyi`. But how to package a project such that it's in-code type annotations are taken in consideration by mypy? Currently, I'm just installing the `*.py` directly, which keep the type annotations.

Setting MYPYPATH to `/usr/lib/python3.4/site-packages` will make it fail, so I guess there should be a fallback if a module is not found, to look for it directly in the `site-packages`. Or is there a flag I missed?

**Comment by JukkaL** [comment]
We've discussed this in #1190. Is it okay to move further discussion there? I'm going to write a follow-up comment with some ideas there.
