### ISSUE TITLE
Variables initialized to None and then to something else don't work with --strict-optional

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1819]
This works without `--strict-optional`:
```python
def foo() -> str:
    a = None
    a = ''
    return a
```
But with `--strict-optional` we get a complaint like this:
```
error: Incompatible return value type (got "Optional[str]", expected "str")
```
**[UPDATE: the rest is incorrect, please ignore]**
If I annotate the initial assignment again it works without `--strict-optional`:
```python
def foo() -> str:
    a = None  # type: None
    a = ''
    return a
```
But with `--strict-optional` I get this on the first assignment:
```
error: Incompatible types in assignment (expression has type None, variable has type "str")
```
I think both of these ought to work under `--strict-optional`.

I don't know if this requires changes to the binder or elsewhere or both.

**Comment by ddfisher** [comment]
The second example should definitely not work -- you're explicitly saying the type of `a` is `None`, and the only value that's a member of `None` is `None`.  Did you mean:
```py
from typing import Optional
def foo() -> str:
    a = None  # type: Optional[str]
    a = ''
    return a
```
This works fine with --strict-optional.

I agree that the first case should work, though.  I think that's related to partial types -- we probably don't add "`a` is a str" to the binder when turning the partial type into an optional type.  Might not be too difficult of a fix.

**Comment by gvanrossum** [comment]
Oh, forget about the second example. But the first should work.

**Comment by gvanrossum** [comment]
Do you recall if there's an issue for the opposite order? I.e.
```python
a = ''
a = None  # E: Incompatible types in assignment (expression has type None, variable has type "str")
```

IIRC while this is debatable it [occurs in real life](Incompatible types in assignment (expression has type None, variable has type "str")) and should really be treated symmetrically.

**Comment by rwbarton** [comment]
There's #1735.

**Comment by ddfisher** [comment]
My preference here would be to kill partial types and allow us to infer unions types in general.

(Also, the "occurs in real life" link is broken.)

**Comment by gvanrossum** [comment]
(Fixed the link.)
