### ISSUE TITLE
`type[Literal['']]` does not accept `str` as the type

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#18196]
I am not even sure that `type[Literal]` is correct :)

```python
from typing import Literal

def a(x: type[Literal['a']]):
    reveal_type(x)
    
a(str)  # Argument 1 to "a" has incompatible type "type[str]"; expected "type[Literal['a']]"  [arg-type]
```

https://mypy-play.net/?mypy=latest&python=3.12&gist=6b8a1d7e6f98c64e7f751c58d356bf16

**Comment by JelleZijlstra** [comment]
`type[Literal[...]]` is invalid and should be rejected.

**Comment by jorenham** [comment]
> `type[Literal[...]]` is invalid and should be rejected.

```pycon
>>> from typing import Literal
... class A(str):
...     def __new__(cls, /) -> Literal["a"]:
...         return super().__new__(cls, "a")
...      
>>> A()
'a'
```

**Comment by JelleZijlstra** [comment]
@jorenham I'm not sure what point you are making. `type[Literal[...]]` isn't meaningful under the typing specification. The upcoming `TypeForm` PEP will provide a way to express this type.

**Comment by jorenham** [comment]
Wow that was a quick response 😋.

`A` is a type that only produces `Literal["a"]`, so it appears to be compatible with a `type[Literal["a"]]`. And as far as I can tell, this isn't (potentially) type-unsafe. So I guess that I'm trying to say that I don't see why it's necessarily "invalid".

**Comment by KotlinIsland** [comment]
of course `type[Literal[...]]` is valid? why wouldn't it be?

**Comment by sobolevn** [comment]
Isn't `Literal[1]` is just `1` and `type(1)` is `int`?

**Comment by JelleZijlstra** [comment]
`type[]` represents an instance of `type`. It doesn't work with arbitrary type annotation objects.

**Comment by jorenham** [comment]
> Isn't `Literal[1]` is just `1` and `type(1)` is `int`?

I think it's more accurate to describe it as a [refinement type](https://en.wikipedia.org/wiki/Refinement_type), i.e. a `T: int` s.t. `T in {1}`

**Comment by jorenham** [comment]
> It is syntactic sugar for `type[S] | type[T]`.

yes, which doesn't describe *an instance* of `type`
