### ISSUE TITLE
Conditional expression with branches of type None and T should be Optional[T], not object

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1820]
Consider:
```python
def f(flag; bool) -> Optional[int]:
  a = (None if flag else 0)
  return a
```
When run with `--strict-optional` I get the error
```
error: Incompatible return value type (got "object", expected "Optional[int]")
```
It looks like the unification code is not understanding what's going on and falling back on `object`.

**Comment by ddfisher** [comment]
Related to #1863.  This is due to mypy's reluctance to make Union types.

**Comment by gnprice** [comment]
As discussed under #1863, we should go ahead and become willing to make Union types when one of the types to be combined is None. We might go back later and become less reluctant to make Union types more broadly, but there's more detailed discussion to be had there (see #1863.)
