### ISSUE TITLE
Proposal: get rid of notes like "note: In member "blah" of class "Blah":"

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1821]
When there's an error on a line it's pretty clear what function that is in, and the note clarifying that is not very useful. Let's get rid of such notes.

This would also make the unit tests a bit simpler -- we could use the `# E: ...` idiom more often.

**Comment by JukkaL** [comment]
This is at least worth experimenting with. The output from mypy is a little noisy. Having `In class "X":` may still be useful in the output, as classes can span multiple screenfuls.

**Comment by gvanrossum** [comment]
This is the block labeled `# Report context within a source file.` in render_messages() in errors.py. Possibly all you need to do is take it out, and then patch up the unit tests that expect the message (of which there may be hundreds...).
