### ISSUE TITLE
stubgen and tests shouldn't be part of mypy package

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1822]

**Comment by ethanhs** [comment]
I'm not sure moving the tests out of the repo is worth the extra hassle. As for stubgen a good first step toward this would be to identify where to move it *to*.

**Comment by gvanrossum** [comment]
Fair, let's not do this. I've since learned that having tests inside a package is one of several popular conventions.

**Comment by ethanhs** [comment]
Should we still leave this open for stubgen? I think it would be nice to separate stubgen from mypy (currently it doesn't even have a separate version flag!).

**Comment by gvanrossum** [comment]
Hm, stubgen is deeply intertwined with mypy -- it imports lots of internals.

**Comment by ethanhs** [comment]
Yes that is true. Alright, we can leave this closed then :)
