### ISSUE TITLE
make filename/line number attribution message on crash much easier to see

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1823]
Right now, most people miss the fact that mypy prints out the filename and line number that it crashes on when it crashes.  This is probably because there's a bit of output afterwards, so it gets lost in the spew.

**Comment by gvanrossum** [comment]
This should be a simple change to report_internal_error() in mypy/errors.py. Maybe duplicate the info both above and below the traceback?

**Comment by gvanrossum** [comment]
I consider this fixed now. We no longer print a stack track by default.
