### ISSUE TITLE
Unpack forces all optional args

### ISSUE THREAD

**Issue by alon-ba** [python/mypy#18243]
Tried to use this method to type my kwargs:
https://github.com/microsoft/pylance-release/issues/2541#issuecomment-1448576066

it produced some mypy bug:
https://github.com/microsoft/pylance-release/issues/2541#issuecomment-2517421890

I also opened a bug for pylance:
https://github.com/microsoft/pylance-release/issues/6732#issue-2717774122

**Comment by brianschubert** [comment]
As Eric explained in https://github.com/microsoft/pylance-release/issues/2541#issuecomment-2517597356, mypy is behaving correctly. You can mark the field as `NotRequired` or specify `total=False` if you want the field to not be required.
