### ISSUE TITLE
Parameters of the form type[typevar] cause issues with type refinement

### ISSUE THREAD

**Issue by Pluviolithic** [python/mypy#18277]
When defining a function with the type of a TypeVar as one of the parameters and a return value of that same TypeVar, Mypy incorrectly traverses type refinement branches and throws an incompatible return value type error.

**To Reproduce**

[Example A](https://mypy-play.net/?mypy=latest&python=3.12&gist=3e9130f25d7aa7213cf0db7ef3a16b25)
[Related variant Example B](https://mypy-play.net/?mypy=latest&python=3.12&gist=7482ebf797a3a1cbf429fbb97cac340f)
[Example C](https://mypy-play.net/?mypy=latest&python=3.12&gist=badc98532676c365b46b5ee91b00f144)

`Example A` at-a-glance:
```py
from typing import TypeVar, reveal_type

Test = TypeVar(
    "Test", int, str, bool
)

def get_test(t: type[Test]) -> Test:
    if isinstance(t, int):
        reveal_type(t)
        return 1
    elif isinstance(t, str):
        reveal_type(t)
        return "asdf"
    else:
        reveal_type(t)
        return True
```

**Expected Behavior**

I do not expect mypy to identify issues with the code. Even though the types are narrowed, they still return correctly in conjunction with what is passed in for `t`, which I believe to be technically correct.

**Actual Behavior**

```
main.py:15: note: Revealed type is "type[builtins.int]"
main.py:15: note: Revealed type is "type[builtins.str]"
main.py:15: note: Revealed type is "type[builtins.bool]"
main.py:16: error: Incompatible return value type (got "bool", expected "str")  [return-value]
Found 1 error in 1 file (checked 1 source file)
```

**Workaround**

A simple workaround is to just wrap the return value with a call to `t`. [Playground example here](https://mypy-play.net/?mypy=latest&python=3.12&gist=cfdb2037490590188494bbb1150e3b33). Even though the workaround is "simple," code modifications like this shouldn't be necessary to use a typechecker.

**Environment**

- Mypy version used: 1.13.0
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.12

**Comment by brianschubert** [comment]
Closing per the explanation given at https://github.com/microsoft/pyright/issues/9568#issuecomment-2533205021.

Also note that `bool` is a subclass of `int`. You should probably check for `bool` before `int` case in the fixed code to avoid taking the `int` branch in both cases.

**Comment by Pluviolithic** [comment]
Appreciate it, thanks.
