### ISSUE TITLE
Using type without actually importing?

### ISSUE THREAD

**Issue by dbr** [python/mypy#1829]
I'm trying to add type annotations to some existing code. The code lives in a module imported by various places, and looks somewhat like this:

```python
class Example(object):
    def mymod(self, cmd):
        # type: (mylib.Command) -> None
        cmd.set_name("example")
```

This (reasonably) makes mypy complain that `Name 'mylib' is not defined` - I could just `import mylib` however I don't want to import this in the shared module where this code lives

Is there a better workaround that just using `(Any) -> None`?

**Comment by gvanrossum** [comment]
You can put the import inside "if False:"

On Thursday, July 7, 2016, dbr <notifications@github.com> wrote:

> I'm trying to add type annotations to some existing code. The code lives
> in a module imported by various places, and looks somewhat like this:
>
> class Example(object):
>     def mymod(self, cmd):
>         # type: (mylib.Command) -> None
>         cmd.set_name("example")
>
> This (reasonably) makes mypy complain that Name 'mylib' is not defined -
> I could just import mylib however I don't want to import this in the
> shared module where this code lives
>
> Is there a better workaround that just using (Any) -> None?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/mypy/issues/1829>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACwrMj8cNC-KhAFqVZ9mtn0vcnWueMmwks5qTc-MgaJpZM4JHtZK>
> .
>


-- 
--Guido (mobile)

**Comment by dbr** [comment]
Ahh, yes, thanks! I realised just after submitting it is a similar issue to circular imports, so [this part of the docs](http://mypy.readthedocs.io/en/latest/common_issues.html#import-cycles) is relevant
