### ISSUE TITLE
Can not assign None to containers of None-typed elements

### ISSUE THREAD

**Issue by dmoisset** [python/mypy#1833]
When checking this

``` python
from collections import OrderedDict

class OrderedSet:

    def __init__(self) -> None:
        self.dict = OrderedDict()  # type: OrderedDict[str, None]

    def add(self, item: str) -> None:
        self.dict[item] = None
```

I get: 

```
fail.py:9: error: Incompatible types in assignment (expression has type None, target has type None)
```

This example comes (simplified) from the type stubs for a django module ( https://github.com/django/django/blob/stable/1.10.x/django/utils/datastructures.py )

A simpler example is:

```
l = []  # type: List[None]
l.append(None)  # error!
l[0] = None  # error!
```

but I wanted to show something coming from an actual, well known project.

**Comment by gvanrossum** [comment]
Even simpler:
```
a = None  # type: None
```
This gives:
```
error: Incompatible types in assignment (expression has type None, variable has type None)
```
IIUC this is related to the issue complaining that None is not a subtype of object.

**Comment by gvanrossum** [comment]
Update: I'm not sure about None vs. object, I can't repro that, but interestingly the examples here give different outcomes with `--strict-optional`. E.g. my one-liner passes with that, but Daniel's three-line example gives a complaint on the first line:
```python
l = []  # type: List[None]
```
The error there is
```
error: Incompatible types in assignment (expression has type List[object], variable has type List[None])
```

**Comment by ddfisher** [comment]
This is a `None` vs `Void` problem. Currently, all `None`s in types actually mean `Void`, which is a special type intended to prevent use of functions that return None.  `Void` is purposefully incompatible with pretty much everything, so saying (in effect) `x = None  # type: Void` is clearly an error.  But because we've decided to spell `Void` the same as `None` externally, the error is exceedingly confusing.

Strict optional checking actually fixes this: most `None`s in types will mean `NoneType`, like you'd expect.

**Comment by gvanrossum** [comment]
So should we ignore it until strict optional checking is the law, or is
there something we can do until then? (I think previously None could be
used in fewer places so the problem was different -- maybe the new
"halfway" situation is causing an attractive nuisance.)

**Comment by ddfisher** [comment]
The halfway solution hasn't changed this at all, actually.  This has been a problem for a long time...

**Comment by gvanrossum** [comment]
I thought that previously you couldn't write `# type: None` at all (i.e. on
a variable).

**Comment by JukkaL** [comment]
It hasn't been enforced consistently (or at all).

**Comment by ddfisher** [comment]
You just get this same error. (Or at least you have since well before --strict-optional.)

**Comment by jstasiak** [comment]
For more data points, just hit this issue with (code reduced to absolute minimum):

```python
def create(type=None):
    # type: (None) -> int
    print(type)
    return 1
```

I get:

```
% python -m mypy asd.py 
asd.py: note: In function "create":
asd.py:1: error: Incompatible types in assignment (expression has type None, variable has type None)
asd.py:3: error: Function does not return a value
```

**Comment by gvanrossum** [comment]
Yeah, until static optional is the default, using None as a type anywhere
except as a return type doesn't work.

**Comment by JukkaL** [comment]
This was fixed recently.
