### ISSUE TITLE
`types-networkx` is not installed by `mypy --install-types`

### ISSUE THREAD

**Issue by rentruewang** [python/mypy#18365]
**Bug Report**

`mypy --install-types` missing some libraries' type stubs.

**To Reproduce**

1. A project that imports and uses networkx.
2. `mypy --install-types .`
3. Does not install type stubs for `networkx`.

```python
import networkx
graph = networkx.Graph()
```

**Expected Behavior**

`mypy --install-types .` should install [`types-networkx`](https://github.com/python/typeshed/tree/main/stubs/networkx) like it does for many different libraries.

**Actual Behavior**

Does not

**Your Environment**

- Python version used: `3.12` (but doesn't work for lower versions as well)
- Mypy version used: Not working for both 1.13, 1.14
- Mypy command-line flags: `--install-types .`
- Mypy configuration options from `mypy.ini` (and other config files):
```
show_error_codes = true
exclude = "tests"
check_untyped_defs = true
```

**Comment by rentruewang** [comment]
@hauntsaninja Wow that is quick. However, I have verified that `types-networkx` is indeed still not installed when I tested a new virtualenv.

**Comment by hauntsaninja** [comment]
Works for me on latest master. Are you sure you installed mypy from latest master correctly? (Try `mypy --version`)

**Comment by rentruewang** [comment]
@hauntsaninja yes lol i have forgotten to pull. I'm wondering tho, where in the code is networkx included? I don't see it in your commit. Is it included by setuptools?

**Comment by hauntsaninja** [comment]
https://github.com/python/mypy/pull/18366/files#diff-763d174f76e98b28604493570aacbec6520095eb3135c0033e6961ad2ea12eebR176
