### ISSUE TITLE
Assigning ellipsis literal to multiple targets is not allowed

### ISSUE THREAD

**Issue by Glyphack** [python/mypy#18385]
**Bug Report**

Allow usage of ellipsis literal (`...`) in right hand side of assignments with multiple targets.

**To Reproduce**

Create a pyi file name `test.pyi` with this code:

```python
x, y = ...
```
<https://mypy-play.net/ mypy=latest&python=3.12&gist=3a35a8f1d93e64b60a63ff1fcd368a3a>

**Expected Behavior**

I expected this to run fine and infer x and y as unknown.
If I understand correctly [this part](https://typing.readthedocs.io/en/latest/spec/distributing.html#value-expressions) of spec is allowing usage of `...` all assignment statements.

**Actual Behavior**

```
test.pyi:1: error: "EllipsisType" object is not iterable  [misc]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.14.0
- Python version used: 3.13.0

**Comment by JelleZijlstra** [comment]
This isn't supposed to be supported. Ellipsis should only be supported for a single assignment. If you feel strongly about this, you can propose to amend the spec to make this explicit.
