### ISSUE TITLE
"from typing import Type" (works in Debian, not working under Arch)

### ISSUE THREAD

**Issue by ttsiodras** [python/mypy#1838]
I installed typing via pip3 in both my Debian and Arch environments, and see this:

Under Debian:

    $ pip3 freeze | grep typing
    typing==3.5.2.2

    $ python3
    Python 3.4.2 (default, Oct  8 2014, 13:14:40) 
    [GCC 4.9.1] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from typing import Type
    >>> 

Under Arch:

    $ pip3 freeze | grep typing
    typing==3.5.2.2
    
    $ python3
    Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
    [GCC 5.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from typing import Type
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'Type'
    >>> 

Have I messed up or is there some difference due to 3.4 -> 3.5?

P.S. In case there's a way around it - I use `Type`, because I have annotated code like this:

    U = TypeVar('U', int, float)

    def GetRange(newModule: Module, lineNo: int, nodeWithMinAndMax: Element, valueType: Type[U]) -> Tuple[U, U]:
        ...
        rangel = valueType(mmin)
        rangeh = valueType(mmax)
        return (rangel, rangeh)

...so I can create the appropriate type at runtime in my AST.

**Comment by kirbyfan64** [comment]
Python 3.5 comes with [its own version of `typing`](https://docs.python.org/3/library/typing.html), which was added *before* the introduction of `typing.Type`. In the latter example, Python is picking up the standard library version instead of the version from `pip`.

**Comment by ttsiodras** [comment]
I see!

Is there any way to "give priority" to the pip3-installed version under python 3.5?

**Comment by ttsiodras** [comment]
Never mind - got it:

   $ PYTHONPATH=$HOME/.local/lib/python3.5/site-packages python3
   Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
   [GCC 5.3.0] on linux
   Type "help", "copyright", "credits" or "license" for more information.
   >>> import sys
   >>> sys.path
   ['', '/home/ttsiod/.local/lib/python3.5/site-packages', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-linux', '/usr/lib/python3.5/lib-dynload', '/usr/lib/python3.5/site-packages']
   >>> import typing
   >>> typing.__file__
   '/home/ttsiod/.local/lib/python3.5/site-packages/typing.py'
   >>> from typing import Type
   >>>
