### ISSUE TITLE
Type[C] is not considered callable

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1846]
This simple example fails:
```python
from typing import Type, Any, Callable
def f(func: Callable[[], Any]) -> Any: return func()
class C: pass
f(C)  # This is okay
x = C()
f(type(x))  # E: Argument 1 to "f" has incompatible type Type[C]; expected Callable[[], Any]
X = C  # type: Type[C]
f(X)  # E: Argument 1 to "f" has incompatible type Type[C]; expected Callable[[], Any
```
This is actually present in the mypy test suite (test/test_random.py:49, the second argument to assertRaises()), so I'm treating this as a blocker.

**Comment by gvanrossum** [comment]
I can't figure out how to solve this, so I'm going to use the `# type: ignore` for the one place in the mypy test suite where this causes a problem ( in test-data/stdlib-samples/3.2/test/test_random.py).

**Comment by JukkaL** [comment]
#1670 is related.

**Comment by gvanrossum** [comment]
Closing as duplicate of https://github.com/python/mypy/issues/1670#issuecomment-224930406.
