### ISSUE TITLE
Tuple[int] (0, 0) is not considered Container[T]

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1851]
This program fails:
```python
from typing import *
T = TypeVar('T')
def foo(a: Container[T]) -> T: ...
foo((1, 2))  # E: Argument 1 to "foo" has incompatible type "Tuple[int, int]"; expected Container[None]
```
But without a type variable it works:
```python
from typing import *
def foo(a: Container[int]) -> int: ...
foo((1, 2))  # OK
```
The same program (with type variable) does work substituting Iterable[T]:
```python
from typing import *
T = TypeVar('T')
def foo(a: Iterable[T]) -> T: ...
foo((1, 2))  # OK
```
Explain?

**Comment by rwbarton** [comment]
See https://github.com/python/mypy/blob/master/mypy/constraints.py#L279. I imagine it just needs another case for `Container`, to match https://github.com/python/mypy/blob/master/mypy/subtypes.py#L174.

**Comment by gvanrossum** [comment]
Would also need a test. But still very easy.

**Comment by shreydesai** [comment]
@gvanrossum Working on this, but one question – where should I add the test? Should it be in `test-data/unit` or `mypy/test`?

**Comment by shreydesai** [comment]
@gvanrossum Working on it, but one question – where should I write the test? Should it be in `test-data/unit`?

**Comment by rwbarton** [comment]
It should go in one of the files under `test-data/unit`. Preferably next to a similar test for Iterable or Sequence etc., if you can find one.
