### ISSUE TITLE
Per argument args and kwargs type annotations cause syntax error

### ISSUE THREAD

**Issue by ajprax** [python/mypy#1854]
```
def f(
    *a # type: *int
):
    pass
```
and
```
def f(
    **kw # type: **int
):
    pass
```
both cause "error: syntax error in type comment"

**Comment by gvanrossum** [comment]
You're not supposed to put the `*` or `**` in the type when using this form. In PEP 484 we have:

>-  When using the short form, for ``*args`` and ``**kwds``, put 1 or 2 stars in front of the corresponding type annotation.

You are using the long form here.

**Comment by rwbarton** [comment]
This seems likely to cause confusion. Would it be possible to provide a more informative error message? Who is parsing the part after `type:`, mypy or typed_ast?

**Comment by gvanrossum** [comment]
> Who is parsing the part after type:, mypy or typed_ast?

Mypy feeds the comment into typed_ast, in parse_type_comment() in
mypy/fastparse.py.

I don't know if there's something we can do short of special-casing a
string that starts with '*'.
