### ISSUE TITLE
Why is overriding __getattr__ / __setattr__ asymmetrical?

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1857]
```python
from typing import *

class Namespace:
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

def f(a: Namespace):
    print(a.foo)
    a.bar = 42
```
I don't get an error on the `a.foo` reference, but I do get one on setting `a.bar`. Why is this not symmetrical?

**Comment by JukkaL** [comment]
`__setattr__` hasn't been implemented yet (#521). I think that somebody tried to do this but it turned out to be trickier than expected.
