### ISSUE TITLE
Typechecking a call to `traceback.format_exception` produces misleading output

### ISSUE THREAD

**Issue by speezepearson** [python/mypy#1858]
Mypy has strange ideas about `traceback.format_exception`'s signature:
1. It thinks `format_exception` requires more than 3 arguments.
2. It thinks the second argument should be a `List[str]`, rather than an `Exception`. (Maybe I'm wrong that it's supposed to be an `Exception`; but it definitely should not be a `list`.)

Short program to reproduce:
```python
import sys
import traceback

try:
  raise RuntimeError()
except RuntimeError:
  exc_type, exc_value, tb = sys.exc_info()

print(traceback.format_exception(exc_type, exc_value, tb))
```
And the output is:
```
temp.py:9: error: Too few arguments for "format_exception"
temp.py:9: error: Argument 2 to "format_exception" has incompatible type "BaseException"; expected List[str]
```
However, the program runs fine.

The first error goes away if I add two more arguments (`1` and `True`) to the call to `format_exception`, to fill in the arguments that have default values.

The second error goes away if I change the second argument to `[]`, but then a TypeError gets thrown at runtime because `[]` isn't hashable.

**Comment by JukkaL** [comment]
Mypy uses typeshed (https://github.com/python/typeshed) to type check standard library modules. Can you check the stub (for example, https://github.com/python/typeshed/blob/master/stdlib/3/traceback.pyi for Python 3) and send a PR with a fix, or file a typeshed issue?

**Comment by speezepearson** [comment]
Aha! You are completely correct; I believe typeshed just has an incorrect signature for `format_exception`. I'll submit a PR there.

Thank you for educating me!
