### ISSUE TITLE
--warn-unused-ignores also warns about typeshed

### ISSUE THREAD

**Issue by Herst** [python/mypy#1884]
Note sure whether that's expected or a workaround like for #1554 is needed:
```/usr/lib/mypy/typeshed/stdlib/2and3/logging/handlers.pyi:107: note: unused 'type: ignore' comment```

**Comment by gvanrossum** [comment]
That one is actually needed because of #698, and the ignore is not unused when `--strict-optional` is given. So I think we should just live with it until #698 is fixed and then we can remove it.

**Comment by ddfisher** [comment]
It's also worth putting in the same workaround as in #1554 for now.
