### ISSUE TITLE
Dynamically typed __init__ with argument types rejected

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#19]
If we introduce `__init__` with `def`, the compiler complains if an argument has an explicit type:

    class A:
        def __init__(self, int x): pass

    t.py: In member "__init__" of class "A":
    t.py, line 2: Cannot define return type for "__init__"

This should be valid, since it works for other methods and can be useful with overloading.

More generally, the return type of `__init__` should be allowed to be `void` or `any` only.

**Comment by gvanrossum** [comment]
This bug has expired.
