### ISSUE TITLE
have a concept of user code vs library code when typechecking

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1918]
Certain warning options shouldn't trigger on typeshed (and other library code).  See #1554 and #1884, for example.  This is currently handled with the `is_typeshed_stub` bool in TypeChecker.  Unfortunately, this doesn't work for other libraries and doesn't allow us to purposefully run these checks on typeshed.  Instead, we could have a concept of user code vs library code, where code mypy was specifically run on has these warnings enabled, and other code does not.

Down the line, we might also want to use this flag to avoid typechecking library code when it's referenced from user code -- we could limit ourselves to reading the types.

**Comment by gvanrossum** [comment]
Maybe there should be flags (in the setup file?) to specify patterns for what's considered to be in each category?

**Comment by ilevkivskyi** [comment]
I think this is now superseded by PEP 561.
