### ISSUE TITLE
Test runner performance regression

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1925]
Commit a4e36e8cd6a1130e451a12b07906ed21590c1d6c introduced a performance regression that slowed down running `runtests.py` with nothing to do by over 100% for me.

Repro (OS X, Python 3.5):

```
$ git checkout a4e36e8cd6a1130e451a12b07906ed21590c1d6c
$ time ./runtests.py unit-test -a "*xyz*"
...
real	0m3.813s
$ git checkout a4e36e8cd6a1130e451a12b07906ed21590c1d6c~1
$ time ./runtests.py unit-test -a "*xyz*"
...
real	0m1.447s
```

**Comment by gvanrossum** [comment]
Simple to fix by tuning the `time.sleep(0.25)` call in mypy/waiter.py. If I set it to 0.05 I regain most of the lost speed.
