### ISSUE TITLE
Use the same token and node class for all string-like literals

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#193]
It would reduce code duplication if the same class would be used for string and bytes literals (and unicode literals, after they have been implemented). This applies both to tokens and ast nodes.

**Comment by gvanrossum** [comment]
@ddfisher We discussed this idea last week...

**Comment by ddfisher** [comment]
Python 3 has separate Str and Bytes ast nodes, so I'm not sure that we want to make this change...

**Comment by gvanrossum** [comment]
I think the idea is to have a single node class with the data and a flag or enum giving what form of literal it was.

**Comment by ddfisher** [comment]
Yeah, that was what I gathered.  My guess is we'll want to move to Python 3's ast, though, which still has split Str/Bytes nodes.

**Comment by gvanrossum** [comment]
But we can still add flags to it I hope?

--Guido (mobile)

**Comment by gvanrossum** [comment]
Honestly I don't think this is causing much anguish. I'm just going to close it. The status quo is fine.
