### ISSUE TITLE
"unparseable" mypy nodes

### ISSUE THREAD

**Issue by thiago-silva** [python/mypy#1930]
One door that mypy / type-checking opens is the ability to create sophisticated code transformers. These can range from mutation testing tools to automated refactoring suites that take advantage of type information.

While this is possible in the current form, transforming code into ASTs and back to source while preserving equivalence of the text is not easy. This is important when one needs to reason about the transformations performed (e.g. using the diff) without having to go through a lot of noise caused by reformatting -- and without having to manually insert comments back in case the transformations are to be reincorporated into the software repository.

However, parsers and AST structures generally do not keep information about exact position of tokens and comments -- the former is usually ignored in ASTs and the later is usually skipped by the scanner. Currently, mypy nodes do not fully reflect the textual structure (in contrast to syntatic structure).

Would it be reasonable to go these extra steps in mypy's parsing machinery?

**Comment by gvanrossum** [comment]
Honestly that is not a goal for mypy except perhaps in the extremely distant future.

In particular, mypy is an application; making it into a library would constrain mypy's own development way to  much.

There are Python parsers that are better suited for preserving the full text while transforming the code, e.g. lib2to3 in the stdlib, and (IIUC) https://github.com/PyCQA/astroid.

**Comment by ilevkivskyi** [comment]
Currently mypy uses `typed_ast` (based on Python native `ast` module) and its original custom parser is removed, so I don't think this is relevant here anymore.

@thiago-silva Note that Python 3.8 AST contains end node position that makes "un-parsing" much easier.
