### ISSUE TITLE
Ability to inspect type hints of live objects using .pyi files

### ISSUE THREAD

**Issue by chadrik** [python/mypy#1934]
It would be very useful to be able to inspect the type annotations of live objects whose types are defined in pyi files.  Merging type annotation with `inspect.getargspec` would open up a word of possibilities in python, such as automatic UI generation for functions/classes.

As an experiment, I tried the following (yes I know `imp` is deprecated):

```python
from typing import get_type_hints

import imp
filepath = '/Users/chad/dev/mypy/typeshed/stdlib/2.7/itertools.pyi'

with open(filepath, 'r') as f:
    mod = imp.load_module('itertools', f, filepath, ('.pyi', 'r', 1))
print(get_type_hints(mod.repeat))
```

This failed because of the use of `@overload` in the pyi file.  Commenting these out got the test working.  So, there's at least two problems to solve:
- make live inspection of stubs reliable
- make `typing.get_type_hints` or a new utility in `mypy`automatically fallback to searching for .pyi files.   might be related to #1190

**Comment by gvanrossum** [comment]
Sorry, this just isn't going to happen any time soon. Apart from overload there are other reasons why the code in stubs just isn't importable (e.g. forward references).

Your request also blurs the line between mypy and runtime support.

**Comment by pirate** [comment]
For anyone reading this issue in 2018 looking for automatic runtime type inference, I found this helpful: https://github.com/dropbox/pyannotate helpful
