### ISSUE TITLE
Possible to distinguish between Sequence[str]/Iterable[str] and str?

### ISSUE THREAD

**Issue by jtatum** [python/mypy#1965]
If a function expects an iterable of strings, is it possible to forbid passing in a string, since strings are iterable? Seems like there are many cases where this would be an error, but I don't see an obvious way to check 't','h','i','s'.

**Comment by gvanrossum** [comment]
The PEP 484 type system currently can't express this, sorry. You'll have to start a discussion in the PEP 484 tracker: https://github.com/python/typing/
