### ISSUE TITLE
Mypy complains about os.scandir and the timeout argument of Popen

### ISSUE THREAD

**Issue by dveeden** [python/mypy#1970]
```
cmd = ['/usr/bin/ls', '/tmp']
with Popen(cmd, stdout=PIPE, stderr=PIPE) as oscmd
    stdout, stderr = oscmd.communicate(timeout=60)
```
Result:
error: Unexpected keyword argument "timeout" for "communicate" of "Popen"

```
for dir_entry in os.scandir(path='/tmp/'):
    pass
```
error: "module" has no attribute "scandir"

Note that os.scandir returns os.DirEntry but after importing this does not exist.
And type(dir_entry) says posix.DirEntry, but that also doesn't exist after importing posix...
This is with Python 3.5 and is somewhat fixed in Python 3.6
See also: https://bugs.python.org/issue27038

```
def foo(bar: str) -> os.DirEntry:
    pass
```
AttributeError: module 'os' has no attribute 'DirEntry'

So please:
* recognize the timeout argument for subprocess.Popen
* recognize the os.scandir() function
* try to find a solution for functions which return a dirEntry or accept one

**Comment by gvanrossum** [comment]
These are issues for https://github.com/python/typeshed. You can easily submit pull requests there if you know what to fix.
