### ISSUE TITLE
Recognize `callable` in conditional type binding

### ISSUE THREAD

**Issue by abarto-machinalis** [python/mypy#1973]
If I run mypy against the following code:

``` python
from typing import Callable, Union

SomeFieldType = Union[str, Callable[[str], int]]

class SomeClass(object):
    def __init__(self, some_field: SomeFieldType) -> None:
        self.some_field = some_field

    def do_something(self) -> None:
        if callable(self.some_field):
            self.some_field('foobar')
```

it complains about self.some_field not being callable:

```
test_mypy.py: note: In member "do_something" of class "SomeClass":
test_mypy.py:11: error: "str" not callable
```

Perhaps mypy could be made aware of the "callable(...)" statements? Thanks!

**Comment by gvanrossum** [comment]
I see. Normally unions can be disambiguated using isinstance(), but that doesn't really work for Callable.

**Comment by dmoisset** [comment]
If this is desirable, probably adding some more code to the `find_isinstance_check` analysis might resolve this
