### ISSUE TITLE
"Generic type is prohibited as a runtime expression" and __getitem__ in metaclass

### ISSUE THREAD

**Issue by aldanor** [python/mypy#1982]
```python
class Meta(type):
    __getitem__ = lambda cls, *args: cls(*args)

class Class(list, metaclass=Meta):
    pass

print(Class[int, float])
# error: Generic type is prohibited as a runtime expression (use a type alias or '# type:' comment)
```

Wonder if mypy could allow constructs like this, or is it a hard limitation of the current implementation?

**Comment by gvanrossum** [comment]
It is technically possible to allow it, but we're intentionally disallowing it because it constructs a new class object and that's really expensive.

**Comment by ddfisher** [comment]
Are you looking for `Type[C]`?  (See: https://www.python.org/dev/peps/pep-0484/#the-type-of-class-objects)  We support that!

**Comment by gvanrossum** [comment]
The question in this issue is unclear, and we are not getting any new information from the submitter, so I'm closing it. @aldanor if you still have a remaining question feel free to reopen or submit a new issue!
