### ISSUE TITLE
Argument ... has incompatible type "function"; expected Callable...

### ISSUE THREAD

**Issue by jstasiak** [python/mypy#1983]
I've looked for a similar report but couldn't find any - forgive me if there is one.

It seems to me that this code should pass type check:

``` python
from typing import Any, Callable


def fun() -> None:
    callbacks = [
        callback1,
        callback2,
    ]

    for c in callbacks:
        call(c, 1234)


def callback1(i: int) -> int:
    return i


def callback2(i: int) -> str:
    return 'hello'


def call(c: Callable[[int], Any], i: int) -> None:
    c(i)
```

mypy a284c48 doesn't like it:

```
test.py: note: In function "fun":
test.py:11: error: Argument 1 to "call" has incompatible type "function"; expected Callable[[int], Any]
```

**Comment by ddfisher** [comment]
Thanks for the bug report!  It looks to me like we're not computing the join of `Callable`s correctly.  This might be a quick fix -- I'll see if I can take a look in the next couple days!

**Comment by rwbarton** [comment]
You can make this program typecheck by adding an annotation `# type: List[Callable[[int], object]]` to the list. It does seem like mypy should probably be able to work that out itself, though.
