### ISSUE TITLE
Support using sys.version_info or sys.platform to define variables and checking those

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1990]
A follow-up task from #698, with low priority -- do we even need this?

This would allow people to write e.g.

``` python
WINDOWS = (sys.platform == 'win32')
if WINDOWS:
    <do things the Windows way>
else:
    <code for all other platforms>
```

Right now, if you want to benefit from mypy's `sys.platform` and `sys.version_info` awareness you have to write `if sys.platform == 'win32'` (etc.) each time.

FWIW PEP 484 does not require this (its examples use the explicit form). Also, for Python major version checks, if you assign to a variable named `PY2` or `PY3` (or use such a variable, e.g. the one defined in `six`), mypy assumes that these mean `sys.version_info[0] == 2` or `sys.version_info[0] == 3`, respectively.

**Comment by petsuter** [comment]
Would this be needed to make `subprocess.STARTUPINFO` etc. work? https://github.com/python/cpython/blob/master/Lib/subprocess.py#L125

**Comment by gvanrossum** [comment]
Well, mypy never reads the source of subprocess.py -- instead it reads the stub file from [typeshed](https://github.com/python/typeshed).

There's now also another feature (on master) that could be used here -- command-line flags `--always-true` and `--always-false`. See http://mypy.readthedocs.io/en/latest/command_line.html.

I'm closing this issue because I don't expect it's important enough to attempt to support it.
