### ISSUE TITLE
concurrent.futures not found

### ISSUE THREAD

**Issue by toejough** [python/mypy#1993]
When checking code using `concurrent.futures`, I'm getting `helpers.py:9: error: "module" has no attribute "futures"` when I run mypy, and I'm not sure why.

Code:
```python
"""Helper functions for the package."""

import concurrent
from typing import Any


def create_executor() -> Any:
    """Get an executor to run blocking functions in."""
    return concurrent.futures.ThreadPoolExecutor()
```

Command line:
```shell
> mypy helpers.py
helpers.py: note: In function "create_executor":
helpers.py:9: error: "module" has no attribute "futures"
>
```

python version:
```shell
> python3 --version
Python 3.5.2
>
```

mypy version:
```shell
> mypy --version
mypy 0.4.4-dev-72317c32c65cf318883a4c2ebec6ed9e065c2bfd
>
```

I've initialized the latest typeshed submodule:
```shell
> git submodule update --init typeshed
Submodule 'typeshed' (http://github.com/python/typeshed) registered for path 'typeshed'
Cloning into '/Users/joe/repos/third-party/mypy/typeshed'...
Submodule path 'typeshed': checked out '5de7bfe18552705a08d3f171971bca5614863af3'
>
```

typeshed does have concurrent.futures [defined](https://github.com/python/typeshed/tree/master/stdlib/3/concurrent/futures).

I've tried this with all the latest code from github and installed with setup.py and with pip.  I've tried in both the system level and in a virtual env.

This is my first attempt to use mypy - am I doing it wrong, or is there a bug?

**Comment by toejough** [comment]
Also, I'm using `Any` because what I first tried (`concurrent.futures.ThreadPoolExecutor`) resulted in `helpers.py:7: error: Name 'concurrent.futures.ThreadPoolExecutor' is not defined`

**Comment by Michael0x2a** [comment]
This is actually an error in Python as well, not just mypy. Running `python3 helper.py` results in:

```
Traceback (most recent call last):
  File "helper.py", line 7, in <module>
    a = create_executor()
  File "helper.py", line 5, in create
    return concurrent.futures.ThreadPoolExecutor()
AttributeError: module 'concurrent' has no attribute 'futures'
```

You probably want to change `import concurrent` to something like `import concurrent.futures` -- both mypy and Python will work once you do so. ([More info](http://stackoverflow.com/q/9303179/646543)).

Regarding `ThreadPoolExecutor` not being defined, I don't seem to be able to repro -- perhaps fixing the import also fixes this? The following typechecks for me:

```python
from concurrent.futures import ThreadPoolExecutor
from typing import Any

def create_executor() -> ThreadPoolExecutor:
    return ThreadPoolExecutor()

ex = create()
```

**Comment by toejough** [comment]
Hmmm, you're right.  Well, firstly, apologies for not actually running the code - this was a simplified version of the module I was type-checking - I didn't think my stripped down version changed this particular function (or the imports) significantly, but I should have checked.

If python doesn't run `concurrent.futures.ThreadPoolExecutor`, I don't expect mypy to, either.  Closing, with apologies for the noise.
