### ISSUE TITLE
Problem with difflib.get_close_matches()

### ISSUE THREAD

**Issue by kankri** [python/mypy#2011]
I just tried mypy the first time and it failed on a small correct 40-line script I had. I hope this isn't indicative of how it's like to use it every day.

I narrowed the problem to this:

```python
import difflib

word = 'foo'
possibilities = ['food', 'bar', 'fool', 'bool', 'baz']
print(difflib.get_close_matches(word, possibilities))
```

With mypy version ```0.4.3``` or ```0.4.4-dev-2e2a94e30724f061a835eb2f72a89115250a37ee``` this gives the following error for Python 2:

```
test.py:5: error: Argument 2 to "get_close_matches" has incompatible type List[str]; expected List[Sequence[str]]
```

and this for Python 3:

```
test.py:5: error: Argument 2 to "get_close_matches" has incompatible type List[str]; expected List[Sequence[Any]]
```
```difflib.get_close_matches()``` is [defined as](https://github.com/python/typeshed/blob/master/stdlib/2.7/difflib.pyi#L31):

```python
def get_close_matches(word: Sequence[_T], possibilities: List[Sequence[_T]],
                      n: int = ..., cutoff: float = ...) -> List[Sequence[_T]]: ...
```

```str``` is [defined as](https://github.com/python/typeshed/blob/master/stdlib/2.7/__builtin__.pyi#L278):

```python
class str(basestring, Sequence[str]): ...
```

To me the arguments match perfectly so this doesn't seem to be a ```typeshed``` problem.

I guess mypy can't properly handle the recursive definition of ```str```. However, I don't get how ```difflib.get_close_matches()``` passes the tests if this is the case...

**Comment by rwbarton** [comment]
Technically mypy is correct in giving an error here, and the stub is probably too restrictive. Let's look at mypy's logic.

```py
possibilities = ['food', 'bar', 'fool', 'bool', 'baz']
```

mypy infers the type `List[str]` here. (You can override this with a comment `# type: List[Sequence[str]]`, and then your program will type check. You shouldn't have to do that, though.)

```py
print(difflib.get_close_matches(word, possibilities))
```

Here `get_close_matches` expects to receive a `List[Sequence[str]]`. A list is a mutable data structure, so `get_close_matches` is entitled to insert any values of type `Sequence[str]` into the list it receives. So you can't pass in a `List[str]`, since after the call your list might not contain just `str`s but also arbitrary `Sequence[str]`s.

Presumably `get_close_matches` doesn't actually modify its argument, so hopefully it can be given a more general type that just requires something like `Iterable` or `Sequence` rather than `List`.

**Comment by kankri** [comment]
What's the fix for this, do I need to create an issue in ```typeshed```? Am I going to stumble into a lot of similar incorrect type annotations for standard functions? Are they not tested?

I wonder if overriding the type of ```possibilities``` would be the right workaround, it could cause problems when I use the variable with another function. I guess I'd rather override or mark to ignore the type specification for a problematic function. I'm not sure what would be a convenient way to do that, though.

It seems with ```get_close_matches``` you could avoid the problem by using ```Sequence``` instead of ```List```. This is maybe off topic, but I was wondering, what if the function actually wants to modify the argument. ```List[Sequence[_T]]``` does not work, because it wants actual ```Sequence```s in a list, not e.g. tuples. So it is never compatible with what the caller has. I tried to use ```_S``` with an upper bound of ```Sequence``` but that gave me the error ```Type variable "_S" used with arguments```. What is the way to specify this correctly?

**Comment by gnprice** [comment]
Thanks for reporting this! Yep, I'd recommend creating an issue in `typeshed` -- or just a PR, if you have a good idea of what the change there should be. Either way will be quite helpful in getting it right for the next person.

> Am I going to stumble into a lot of similar incorrect type annotations for standard functions? Are they not tested?

We generally try to write precise types in typeshed, but the nuances of the assumptions a stdlib function makes are often not quite documented, which makes that tricky. So in this early period where it's quite new for people to be running type-checkers on Python programs, you may run into other annotations that aren't quite right. It's less likely on the well-trafficked functions (though it can still happen if you use an unusual aspect of their API) than in relatively uncommonly-used areas like `difflib`.

For issues like this (or like it *looks* like is going on here) where the stub describes a more restricted type than the library actually permits, it's hard to really test short of adding types to a variety of code that uses the library. Which is effectively what's happening that is precisely how you discovered this issue, for example. :-)

**Comment by gvanrossum** [comment]
Closing, since this looks like a typeshed issue. You can file an issue or submit a PR there.
