### ISSUE TITLE
set.union not working correctly

### ISSUE THREAD

**Issue by za3k** [python/mypy#2013]
Code:
`a = set().union(*[[1],[2],[3]]) # type: Set[int]`

Expected:This should work fine
Result:

```
error: Argument 1 to "union" of "set" has incompatible type *List[List[int]]; expected Iterable[None]
error: Incompatible types in assignment (expression has type Set[None], variable has type Set[int])
```

I'm fairly new to mypy, so please let me know if this is user error.

**Comment by za3k** [comment]
Worth noting that this works:
```
base_set = set()  # type: Set[int]
a = base_set.union(*[[1],[2],[3]])```

**Comment by gnprice** [comment]
Thanks for the report! I think this is a case where our type inference within a statement/expression is a little too dependent on specific rules and consequently only able to reason through N layers of indirection but not N+1. We've talked about this before (/cc especially @ddfisher), but I'm not sure we have an issue squarely directed at it -- #1055 appears to be closest.

I'd certainly like to fix this kind of situation, preferably in a way that involves reducing the number of special cases, but I don't think we yet know precisely how to do that. For now, the workaround in your follow-up comment is the recommended approach -- fortunately it's usually not particularly cumbersome.

**Comment by djrochford** [comment]
Commenting in the hope of bringing attention to this open issue.

**Comment by AlexWaygood** [comment]
Can't reproduce on 0.940

https://mypy-play.net/?mypy=0.940&python=3.10&flags=strict&gist=40e9a86b91e4e4727bdf743b544847dd
