### ISSUE TITLE
--fast-parser not working on Cygwin either?

### ISSUE THREAD

**Issue by Herst** [python/mypy#2021]
You mention in your blog post that the `--fast-parser` is not working on Windows and I assumed this only applied to Python native to Windows but apparently it does not work under a Cygwin Python either. I am getting `gcc` compile errors when installing trying to install `typed-ast` package on a Python 3 install inside Cygwin:

```
    gcc -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.4.3-1.x86_64/build=/usr/src/debug/python3-3.4.3-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.4.3-1.x86_64/src/Python-3.4.3=/usr/src/debug/python3-3.4.3-1 -Iast27/Include -I/usr/include/python3.4m -c ast27/Python/mystrtoul.c -o build/temp.cygwin-2.6.0-x86_64-3.4/ast27/Python/mystrtoul.o
    gcc -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.4.3-1.x86_64/build=/usr/src/debug/python3-3.4.3-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.4.3-1.x86_64/src/Python-3.4.3=/usr/src/debug/python3-3.4.3-1 -Iast27/Include -I/usr/include/python3.4m -c ast27/Python/Python-ast.c -o build/temp.cygwin-2.6.0-x86_64-3.4/ast27/Python/Python-ast.o
    In file included from /usr/include/python3.4m/pytime.h:6:0,
                     from /usr/include/python3.4m/Python.h:65,
                     from ast27/Python/Python-ast.c:12:
    ast27/Python/Python-ast.c:478:27: error: initializer element is not constant
         PyVarObject_HEAD_INIT(&PyType_Type, 0)
                               ^
```

Maybe something worth mentioning as well.

**Comment by Herst** [comment]
It works on the new Ubuntu on Windows BTW.

**Comment by gvanrossum** [comment]
But Cygwin is still Windows underneath, isn't it? If the compiler isn't good enough to compile typed_ast, it may have to become an unsupported platform. If you think there's a simple enough fix for the error you quoted, please head over to the https://github.com/dropbox/typed_ast repo and submit a patch that makes it work!

**Comment by Herst** [comment]
Will do. BTW, the compiler is basically gcc 5.4, I suspect the problem has to do with certain wrong assumptions about certain `#defines` from what I read (`_WIN32` or such).
