### ISSUE TITLE
Type declarations of base class attributes not carried over to subclasses if `None` is present

### ISSUE THREAD

**Issue by Vgr255** [python/mypy#2022]
Simplest repro:

```
class BaseClass:
    my_attr = () # type: tuple

class Subclass(BaseClass):
    my_attr = None
```

Output:

```
testing.py: note: In class "Subclass":
testing.py:5: error: Need type annotation for variable
```

However, if `None` isn't the sole value but part of something else, this is likely not the desired behaviour. Consider this:

```
from typing import Tuple, Any

class BaseClass:
    my_attr = ( ("", None), ) # type: Tuple[Tuple[str, Any]]

class Subclass(BaseClass):
    my_attr = (
        ("one",  set ),
        ("two",  str ),
        ("three",None),
    )
```

Output:

```
testing.py: note: In class "Subclass":
testing.py:8: error: Need type annotation for variable
```

Changing `None` for anything else, adding a `# type: ignore` comment on the `("one",  set),` line (but not on any other line of the assignment) silences the error. This is somewhat related to #1338 (and, to a lesser extent, #1032).

**Comment by gvanrossum** [comment]
Yeah, definitely a bug. I think it's related to #1338, the type of class attributes is just not checked against the base classes at all (unlike methods).

**Comment by gvanrossum** [comment]
Looking into this again (now that #2510 has been merged) I think there's still something fishy here: I think the first example (in the absence of `--strict-optional`) should be silent, since it's essentially equivalent to
```python
x = None  # type: int
x = None
```
which is silent.

(However the second example contains an error, since the subclass uses `attr` instead of `my_attr`. Fixing that, the example correctly complains that the top-level Tuple type in the subclass (of three items) is incompatible with the type from the base class (of 1 item).)

**Comment by Vgr255** [comment]
Whoops, I probably messed up when I copied the repro over. Edited the comment to correct this. I sadly no longer have a use case for this, as the affected code is gone. I still think it's worth fixing, though, and I hope you figure it out. Cheers!

**Comment by AlexWaygood** [comment]
The example code [no longer causes a mypy error](https://mypy-play.net/?mypy=latest&python=3.10&flags=no-strict-optional&gist=49016fd53fd254b52d46ce1776a5356b) if you use the `--no-strict-optional` option (which was the default at the time of the bug being filed). If you don't use the `--no-strict-optional` option, you just need to change the annotations to this:

```python 
class BaseClass:
    my_attr = () # type: tuple | None

class Subclass(BaseClass):
    my_attr = None
```

And mypy is fine with it.
