### ISSUE TITLE
mypy claims that the `typing` module doesn't have `get_type_hints`

### ISSUE THREAD

**Issue by nicholasbishop** [python/mypy#2025]
Test case:
```
$ mypy --version && mypy -c 'from typing import get_type_hints'
mypy 0.4.3
<string>:1: error: Module has no attribute 'get_type_hints'
```

Importing that function within an interactive Python session works fine.

https://docs.python.org/3/library/typing.html#typing.get_type_hints

**Comment by ddfisher** [comment]
Thanks for the bug report!  This looks like an issue with the standard library stub files, which are managed in [typeshed](https://github.com/python/typeshed).  Would you mind filing this issue there?  (You could also submit a PR if you like -- fixing up this stub should be reasonably straightforward!)

**Comment by nicholasbishop** [comment]
Thanks, filed the new issue on typeshed.
