### ISSUE TITLE
When I omit the "return", mypy does not check

### ISSUE THREAD

**Issue by DKXXXL** [python/mypy#2033]
```
def p(a:int)->int:
    b = a+1
k = p(1)
```
p should be "int -> None" 
mypy 0.4.3 said nothing

**Comment by gvanrossum** [comment]
Yeah, that's a known issue. I believe it can only be resolved after we implement strict optional checking. Until then, this is probably the relevant issue, and I'm going to close you as a duplicate:
https://github.com/python/mypy/pull/1748
