### ISSUE TITLE
Cannot infer type argument when mixing int and float

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2035]
Mypy complains about this code, even though it looks fine to me:

```
from typing import Sequence, TypeVar

_T = TypeVar('_T')

def bisect_left(a: Sequence[_T], x: _T) -> int: ...

bisect_left([1, 2, 3], 5.391)  #  Cannot infer type argument 1 of "bisect_left"
```

This doesn't seem to be related to promotions, as it also happens with user-defined types:

```
class A: pass
class B(A): pass

bisect_left([B()], A())   # same error
```

**Comment by matthiaskramm** [comment]
Just out of curiosity: What is mypy *supposed* to do, when having

```
def f(x: _T, y: _T)
```

and a call

```
f(A(), B())
```

Should it try to "promote" either A to B or B to A? Or should it try to find a common base class between the two?

Or would the magic that makes bisect_left work not actually apply for the non-sequence case?

**Comment by JukkaL** [comment]
It looks for a value for `_T` that is compatible for all arguments. There are some additional rules, such as that we generally don't infer `Any` types, even though they would be valid everywhere, and we favor narrower types as results. It tries to look for common base classes and it also considers promotions such as `int` -> `float`. In your example, if `B` is a subclass of `A`, so we'd infer `_T = A`. `object` would also be a valid result, but since `A` is narrower we prefer that.

The non-sequence case should work already -- it's the sequence case that is broken.

**Comment by graingert** [comment]
any way of specifying type arguments to a function?

```python
class A: pass
class B(A): pass

bisect_left[A]([B()], A())   # same error
```

**Comment by JukkaL** [comment]
Not directly, but you can use `cast` within the arguments to make all argument types match exactly, so it's obvious what the value of a type argument will be. Example:

```py
from typing import cast

class A: pass
class B(A): pass

bisect_left([cast(A, B())], A())  # ok
```

**Comment by graingert** [comment]
@JukkaL here's an issue about what I mean https://github.com/python/mypy/issues/3096

**Comment by JukkaL** [comment]
Increasing priority since there was a user question that boils down to this issue and the fix seems simple.
