### ISSUE TITLE
`' '` is not accepted as a valid format specifier key name

### ISSUE THREAD

**Issue by cyang1** [python/mypy#2058]
When type-checking the following code:
```python
print("%( )s world" % {' ': 'hello'})
```
`mypy` gives the error:
```
error: Unsupported format character '('
```

Sounds like mypy doesn't currently accept spaces as the keys for format specifiers.

**Comment by gvanrossum** [comment]
Looks like it's not the '(' so much as that it doesn't believe that the
thing between '(' and ')' can contain whitespace?
