### ISSUE TITLE
Possible syntax for annotating 'with' clauses

### ISSUE THREAD

**Issue by johnthagen** [python/mypy#2064]
@gvanrossum @JukkaL

Maybe this belongs on python-ideas, but I'll post it here for now.

I noticed that [PEP 526](https://www.python.org/dev/peps/pep-0526/#where-annotations-aren-t-allowed) states:

> In addition, you cannot annotate variable used in a `for` or `with` statement

Just wanted to share that in PyCharm you **can** annotate the types of `with` clauses with a type comment, and having used type hints extensively since the release of Python 3.5, I have found it very useful.

```python
# Simple toy example focusing only on syntax, please ignore the obvious mistake.
with open('file.txt') as file:  # type: str
    file.capitalize()  # PyCharm infers the type of 'file' to 'str'
```

The example above is of course a toy, but there are times when using third party libraries that return a context manager that PyCharm is unable to infer the type.  I have run into this in practice with [`paramiko` `Channel`s](http://docs.paramiko.org/en/2.0/api/channel.html#paramiko.channel.Channel) for example.  By using a type comment, it makes the code much easier to maintain as PyCharm will do static analysis, autocomplete, etc on that variable within the `with` clause.

Pinging @vlasovskikh from the PyCharm team to make sure that was an intentional feature I have been using in PyCharm (which I personally really like and would like to stay).

Mypy currently errors out on such syntax:

```
a.py:2: error: Parse error before "str"
```

**Comment by gvanrossum** [comment]
The `# type: ...` syntax on a `with` statement is in PEP 484, so mypy should support it. This is already in the tracker under #892.
