### ISSUE TITLE
sys.exc_info is difficult to use under --strict-optional

### ISSUE THREAD

**Issue by ahaven** [python/mypy#2071]
Inside of an except block, `sys.exc_info()` returns a triple of non-None values unless `sys.exc_clear()` has been called. The following idiom should be safe:
```
try:
    f()
except something:
    reraise(OtherError, OtherError(), sys.exc_info()[2])
```
However, mypy gives the error
```
error: Argument 3 to "reraise" has incompatible type "Optional[TracebackType]"; expected "TracebackType
```
when run under `--strict-optional`.

**Comment by gvanrossum** [comment]
Honestly I think the stub for six.reraise() should just be changed to
accept a tb being None. That better matches the definition in six.py
anyways.

**Comment by ahaven** [comment]
Okay, here's a pull request: https://github.com/python/typeshed/pull/514

**Comment by gvanrossum** [comment]
Merged.
