### ISSUE TITLE
Parse error when using keyword expansion

### ISSUE THREAD

**Issue by hschafer** [python/mypy#2072]
```
mypy --silent-imports .
file.py: note: In function "_prepare_params":
file.py:97: error: Parse error before **
```
Line 97 has the line `params = {**default_params, **additional_params}` 

It's a nifty shorthand to combine two dictionaries but causes a parse error when running the `mypy` checker. If I remove that line, I can run mypy without fail so I'm fairly certain this syntax isn't supported yet.

**Comment by JukkaL** [comment]
Did you try it with `--fast-parser`?

**Comment by gvanrossum** [comment]
The fast parser supports this, so I propose to close this as "won't fix in old parser".

**Comment by hschafer** [comment]
It works with `--fast-parser`. Thanks so much!
