### ISSUE TITLE
Mypy treats type aliases of nested classes as invalid types

### ISSUE THREAD

**Issue by Michael0x2a** [python/mypy#2075]
Consider the following test case:

``` python
class Outer:
    class Inner:
        def make_int(self) -> int: return 1

Bar = Outer.Inner
x = Bar()  # type: Bar 
def produce() -> Bar:
    return Bar()
```

The expected output is for mypy to typecheck this without error, but instead it reports the following:

```
test.py:6: error: Invalid type "test.Bar"
test.py: note: In function "produce":
test.py:7: error: Invalid type "test.Bar"
```

As a side-note, I did some brief testing and it seems this error only happens when you use `Bar` where a type is expected. Mypy is perfectly happy with the following program, for example:

``` python
class Outer:
    class Inner:
        def make_int(self) -> int: return 1

Bar = Outer.Inner
x = Bar()  # type: Outer.Inner 
def produce() -> Outer.Inner:
    return Bar()
```

**Comment by gvanrossum** [comment]
If you want to play around with aliases, they are recognized in semanal.py,
function visit_assignment_stmt(), in the big else clause around line 1100.
