### ISSUE TITLE
Support for Import Whitelist?

### ISSUE THREAD

**Issue by rowillia** [python/mypy#2083]
As we start to investigate adopting mypy here, one open question is how to handle libraries that have type annotations on them, but are not in Typeshed.  For example, we have a number of internal Python modules that get installed into a venv in production, and I'd like to start adding types to those libraries and have the consumers of those libraries type check against those types.

What would be the best approach here?  I effectively want to use `-s` but whitelist a set of modules to actually analyze for types.

**Comment by msullivan** [comment]
It should be possible to whitelist using some combination of (possibly per-module) `follow_imports` and `ignore_missing_imports`

**Comment by JukkaL** [comment]
Also, PEP 561 will help with this (https://www.python.org/dev/peps/pep-0561/).

**Comment by internetimagery** [comment]
@msullivan (years later, sorry!) would you be able to elaborate on that?

I'm investigating mypy adoption into a small subset of a large codebase.
Unfortunately the codebase contains a lot of legacy stuff / c extensions / whatever else exists.
So I was hoping I could use a whitelist to get things started.

I was thinking something like the following might work, but I assume it's a misinterpretation of the configuration (as the follow_imports global setting doesn't seem to be overridden by the specified modules)?

```
[mypy]
follow_imports = skip
ignore_missing_imports = true

[mypy-whitelist1.*, whitelist2.*, ... ]
follow_imports = silent
ignore_missing_imports = false
```
Thanks a lot!
