### ISSUE TITLE
Fix namedtuple discrepancies

### ISSUE THREAD

**Issue by elazarg** [python/mypy#2090]
- [x] It should be possible to call `_make` on an instance, as a proper classmethod (?)
- [x] `_make` and `_replace` should bind to SelfType, depends on #1212
- [ ] `_asdict` should return closer match to `OrderedDict[str, Union[types]]`
- [ ] `_make` params `new` and `len` should be callable
- [ ] Handle locally defined namedtuple

**Comment by dlinnemeyer** [comment]
I'm working on trying out NamedTuple from typing with mypy, and I ran into an error claiming my tuple has no attribute "_replace" when I try to call _replace.

Is this what you're talking about here, or am I running into a different problem?

**Comment by elazarg** [comment]
What version of mypy do you use? This sounds like an old bug that should have been fixed. Can you post an example code?

**Comment by dlinnemeyer** [comment]
0.4.4. I'll work on some example code quickly.

**Comment by dlinnemeyer** [comment]
```python
from typing import NamedTuple

Foo = NamedTuple('Foo', [
    ('x', int),
    ('y', str)
])

def do_something(foo: Foo) -> Foo:
    return foo._replace(x=7)
```

I'm getting this error:

test.py: note: In function "do_something":
test.py:9: error: "Foo" has no attribute "_replace"

**Comment by gvanrossum** [comment]
Can you repro with the latest mypy version from the repro?

**Comment by elazarg** [comment]
No it was fixed but not released yet.

**Comment by gvanrossum** [comment]
Our policy is to close bugs when the fix lands in the repo. So if this issue is fixed in the repo it should be closed now. (As the originator you should be able to.)

**Comment by dlinnemeyer** [comment]
You were right. Installing directly from git doesn't give any errors.

**Comment by elazarg** [comment]
@gvanrossum please don't close this issue. It is about other problems, not yet solved.

**Comment by gvanrossum** [comment]
Sorry!

**Comment by emmatyping** [comment]
namedtuple is no longer an experimental mypy concept, I think this can be closed. Any work left belongs in python/typing or CPython :)
