### ISSUE TITLE
Augmented assignment leads to type complaints

### ISSUE THREAD

**Issue by JdeH** [python/mypy#2098]
Hi,

I am using mypy 0.4.4. It seems augmented assignments aren't yet dealt with correctly.

```
weight0 = 65.5
weight0 = 65
weight0 *= 0.5                  # Gives error, unsup operand types for * ("int" and "float")
```

```
weight1 = 65.5
weight1 = 65
weight1 = weight1 * 0.5    # Gives no error
```

**Comment by gvanrossum** [comment]
Wow. Good catch. Seems there's something strange going on indeed! We'll
investigate.

**Comment by elazarg** [comment]
The error is not directly related to augmented assignment, I think. Mypy assumes that the second assignment kills the first

    x = 65.5  # type: float
    reveal_type(x)  # E: Revealed type is 'builtins.float'
    x = 65
    reveal_type(x)  # E: Revealed type is 'builtins.int'

Just like any other case of compatible assignment. So how is that different from the simpler case

    x = 65
    x += 5.0  # E: Unsupported operand types for + ("int" and "float")

Allowing the latter (inferring float without any other hint) can easily miss real type errors.

**Comment by JdeH** [comment]
@elazarg:

If that were the case, why then is

```
weight1 = 65.5
weight1 = 65
weight1 = weight1 * 0.5    # Gives no error
```
considered correct?

**Comment by JukkaL** [comment]
It seems that `*=` doesn't rebind the variable type, unlike `=`. However, I think that it should.

`=` doesn't actually introduce new variable but it does introduce a new "type binding" for a variable. This means that the new binding must be compatible with the declared or inferred type of the variable -- mypy doesn't currently let you arbitrarily redefine a variable.

**Comment by JdeH** [comment]
Indeed from a 'user' point of view, the disparity between simple assignment and augmented assignment is hard to comprehend. At least for me it was... So if it could be avoided I think it would be an improvement.
