### ISSUE TITLE
Feature request: type_by_name pragma

### ISSUE THREAD

**Issue by elazarg** [python/mypy#2103]
In many cases, the name of an argument/variable implies its type; either because the operations are obvious from the name, or because the type is opaque and uniquely implied by the name. In these situations, repeating the type everywhere does not necessarily help the reader, and with the right assistance the checker won't need it too. This observation is obvious, but I give some examples below for concreteness.

I suggest experimenting with a scoped, mypy-specific pragma:

```
# mypy type_by_name (i: int) (path: str)
# mypy type_by_pattern (is_* -> bool) 
```

A more complex example would be typing visitor methods, but it might become cryptic.

Pros:
- With proper use, can help make cleaner function declarations
- Quick typing an untyped module
- Single place for deciding type, without introducing repetitive type name, e.g. `version: Version` everywhere (or worse, `version: T`)
- Easier generation of stubs

Cons:
- Obviously easy to abuse. When abused, it might degrade readability
- Omitting hints makes declarations look inconsistent ("why is that parameter typed while the other is not?"). But see Non-cons below.
- Existing IDE support is not always as helpful, with the suggested syntax

Non-cons:
- Text search still finds the type declaration
- This is not "evil global variable" since it's immutable
- Nothing is really implicit here
- It does not discourage using local type hints; It only enforces consistency of their use

There should be some way to maintain consistency across modules, and mypy can enforce compatibility across scopes in a single module (although I am not sure it's helpful when the scope is not global)

If the experiment goes well, a more plausible syntax can be supported, using an `Enum` or variable type declarations in a class.

---

Examples:

Simple examples are `pyversion` (the type is _almost_ opaque, in practice), the variance constants in mypy/nodes.py, `path: str`, `body: Block`, `node: Node` and perhaps `type: Type` to catch confusion with `builtin.type`.

There are other cases, in which the name has default meaning, and it must be compatible with it. In mypy it's `expr: Expression` (e.g. `ExecStmt.expr`), which is inconsistent with `WithStmt.expr: List[expr]`, 

There are patterns, of course: `is_*: bool`. Having defined `node`, it makes sense that `nodes` should be compatible with `Iterable[Node]` (of course I'm not suggesting a pattern like `*s -> Iterable`). 

---

I don't suggest implicit typing of names such as `blah` to be of type `Blah`; it would encourage bad naming.

I wouldn't suggest this pattern for statically typed language. I wouldn't suggest implicit inference by name as a standard practice in dynamically types language. Being explicit in an environment with strong conventions might make it useful.

I would suggest it in python-ideas, but I think that being an optional feature will help evaluating how useful this really is, before considering more heavy weight support.

**Comment by gvanrossum** [comment]
A somewhat similar idea was implemented in the form of a stub file
generator by Ed Ream, the creator of Leo:
https://github.com/edreamleo/make-stub-files. Maybe there are some useful
ideas there?

**Comment by elazarg** [comment]
Nice. There are certainly some ideas to borrow from it. And it has the advantage of being small and standalone.

I only took a glance, but I think it will be somewhat subsumed by my suggestion + the stub generator. And stubs are not the main point here, although important.

**Comment by gvanrossum** [comment]
OTOH that script works today, while you are proposing a lot of new
machinery for mypy and typed_ast.

**Comment by elazarg** [comment]
I agree with the first part. Both are serious advantages, but the
functionality and user experience are quite different.

I am in the hope that it's not "a lot" of machinery and changes.

>

**Comment by JukkaL** [comment]
Something like `make-stub-files` but with support for in-place transforming of files instead of stub generation seems like a more promising approach to me.

So the workflow would be something like this:
* Define type/name patterns, either as comments/docstrings/magic definitions in files or in external configuration files.
* Run the offline tool. It would add new annotations to the file for things that match a pattern but don't have an existing annotation.

This would arguably have these benefits over the proposed approach:
* This wouldn't require mypy or PEP changes. The tool could be maintained independently of mypy -- thus it wouldn't add any work to mypy developers.
* It would be easy to experiment with the tool features and support arbitrarily powerful patterns without having to reach agreement with Python or mypy devs.
* The tool would work with all PEP-484-conforming tools, not just mypy.
* There could be multiple tools tailored for different use cases.
* If the tool becomes popular, this would give justification for including the functionality in mypy (or Python). 

I'm a little hesitant to add more experimental mypy features without clear understanding of the cost/benefit ratio (where cost includes code review and maintenance effort). Mypy already has a pretty large features set, and new features should be pretty well justified, as we already have plenty of things that we *know* that we want and it makes sense to focus on the safer bets first.

**Comment by elazarg** [comment]
I don't want to automatically add annotations. I want to avoid the clutter
and the repetition when those are not needed.

As for being independent of mypy, some independence can be achieved if mypy
will have a plugin API that exposes scopes+types, and allow compatibility
queries. So at the vety least it can be added as a concrete use case and
wishlist from a future plugin API.

בתאריך יום א׳, 11 בספט' 2016, 21:54, מאת Jukka Lehtosalo ‏<
notifications@github.com>:

**Comment by elazarg** [comment]
Take mypy codebase for example. Changing integer values to enum touches many lines of code. Using this feature could make the hit much smaller, if it was typed-by-naming-convention all along.

**Comment by JukkaL** [comment]
You can already use type aliases for easier refactoring. Mypy will generally point out the type annotations that need to be changed after a refactoring. I don't personally see type annotations as clutter or mind the repetition -- I'd rather have things more explicit, as it makes things more readable for me.

Having this is as a plugin may be a reasonable alternative. I'll try to keep this use case in mind once we start discussing the plugin system seriously.

A few additional thoughts:

* If some annotations are implicit, it has the drawback of giving two meanings to an argument without annotations -- it can mean an implicit `Any` type or an arbitrary default type, depending whether there is a declaration somewhere else in the code, potentially far away form the use site. I suspect this will make it harder to review code. A strict mode that requires everything to have an annotation (even if it's implicit) would make this less of a problem.

* Another potential point against having this implicit is that it assumes very consistent naming conventions. Especially in code that is maintained by many programmers, it's easy to have minor deviations, and it's not clear whether enforcing clear conventions is worth it.

**Comment by elazarg** [comment]
Your first point is what I had in mind when I talked about abuse. Similarly the second point is about using this feature with good taste. Nobody wants names like "anInt" around (although there are "_list" and the like), and nobody wants to avoid intention-revealing names.

But the fact that a feature can be abused is not a a reason for avoiding it altogether. The question is the cost/value ratio, and it needs experimentation to get a vague feeling about it.

**Comment by boxed** [comment]
Can you declare types of local variables in stub files? If not then this feature request seems to be different from the stub tool mentioned above.

**Comment by JukkaL** [comment]
Yes, stub generation is a different (but related) problem. A similar approach could work for both stub generation and the annotation of non-stub code.

**Comment by hauntsaninja** [comment]
There hasn't been much demand for this feature. Explicit is better than implicit. You can use https://github.com/jelleZijlstra/autotyping/ to automatically add type hints of this nature

**Comment by boxed** [comment]
The demand is not a good argument. People are asking for a faster horse, we can give them a car. They are not expecting or demanding a car.
