### ISSUE TITLE
Document that types cannot depend on argument values

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2115]
We don't have dependent types. This came up in https://github.com/python/typeshed/issues/521. Maybe we could add an example of typical code using itertools.product(), and how it could be typed.

**Comment by nanjekyejoannah** [comment]
@gvanrossum I would love to work on this if no one is atm.

**Comment by ethanhs** [comment]
@nanjekyejoannah Feel free to do so!

**Comment by ilevkivskyi** [comment]
> We don't have dependent types.

Currently we do, and this is documented, so this issue can be closed.
