### ISSUE TITLE
Using `in` operator with an exception object as RHS

### ISSUE THREAD

**Issue by timabbott** [python/mypy#2118]
mypy flagged some code I had that read like this (simplified):

```
try:
    raise IOError("TEST")
except IOError as e:
    print('TEST' in e)
```

with `bots/check-mirroring:170: error: Unsupported right operand type for in ("IOError")`.

The code is certainly not how I'd want to write it, but `"TEST" in e` does actually return True, and it returns False with some other value, so it would appear that the code actually works.  Not sure what makes sense for mypy to do here, but it's an interesting case and I figured I'd send it to you folks :)

**Comment by kirbyfan64** [comment]
FWIW, this seems to be Python 2-only. `'TEST' in Exception(xyz)` seems to basically just be `TEST in xyz`, at least based on my reading of the CPython sources.

**Comment by gvanrossum** [comment]
So does this mean that Exception ought to be generic in its first argument?
(Doing that might break some code.)

**Comment by timabbott** [comment]
@kirbyfan64 I don't think that's quite right in Python 2, see below:

```
In [1]: 'EST' in 'TEST'
Out[1]: True

In [2]: try:
   ...:         raise IOError("TEST")
   ...: except IOError as e:
   ...:         print('TEST' in e)
   ...:     
True

In [3]: try:
        raise IOError("TEST")
except IOError as e:
        print('EST' in e)
   ...:     
False
```

**Comment by kirbyfan64** [comment]
@timabbott Oops, I misread the source code. Basically, `x in Exception(...)` is the same thing as `x in Exception(...).args`, or just `x in (...)`.

**Comment by JukkaL** [comment]
It seems fine to just support arbitrary `in` operations with `Exception` on the RHS. I doubt this is a very common use case, and trying to build anything fancy doesn't seem worthwhile, especially as other builtin types use `def __contains__(self, x: object) -> bool`.

**Comment by gvanrossum** [comment]
Shouldn't this be a typeshed bug? And it's only on Python 2 AFAICT.

**Comment by JukkaL** [comment]
Python 2 `BaseException` defines `__getitem__` (also `__getslice__`), and that seems to be the reason for it being an iterable, and thus it also supports `in` -- but it doesn't actually implement everything in `Iterable`. I think that mypy doesn't recognize this iteration protocol. Not sure what's the best way to do this. This may require a typeshed update and a mypy update, unless we cheat.

**Comment by gvanrossum** [comment]
I think you mean it doesn't implement everything in Sequence? Iterable just
has `__iter__` and that's just what the doctor ordered here. Maybe we
should just make it Iterable, Container, and define `__getitem__` and
`__getslice__`, since that covers what it supports most closely.

FWIW I didn't remember this behavior. :-(

**Comment by JukkaL** [comment]
It doesn't have `__iter__` so making it `Iterable` wouldn't be quite right either:

```
$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> e = Exception(1)
>>> e.__iter__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'exceptions.Exception' object has no attribute '__iter__'
```

**Comment by gvanrossum** [comment]
But nobody calls __iter__ -- they call iter(), which *does* work.

**Comment by JukkaL** [comment]
Yeah, calling `__iter__` directly seems sufficiently rare that adding an `Iterable[Any]` base class (+ `__getitem__` etc.) should be fine. Besides, the whole thing is pretty obscure.

**Comment by gvanrossum** [comment]
Closing, since this doesn't apply to Python 3.
