### ISSUE TITLE
Non-static-type expression in type annotation causes unhelpful parse error

### ISSUE THREAD

**Issue by elazarg** [python/mypy#2137]
I won't expect mypy to understand the following

``` python
def foo(a: type(1)) -> None:
    pass
```

But the overly verbose "parse error" is wrong:

```
$ mypy tmp.py
tmp.py: note: In function "foo":
tmp.py:1: error: Parse error before (
tmp.py:1: error: Parse error before "None"
tmp.py: note: At top level:
tmp.py:1: error: Parse error before :
tmp.py:2: error: Inconsistent indentation
tmp.py:5: error: Inconsistent indentation
```

This can swamp the terminal with "Inconsistent indentation" so the actual error (which is not an error at all) is not visible.

(And `tmp.py:5`? there are only 4 lines in the file :) )

**Comment by gvanrossum** [comment]
Did you try --fast-parser? It should do better.

--Guido (mobile)

**Comment by elazarg** [comment]
It does, thanks.

**Comment by gvanrossum** [comment]
I'm going to close this as a won't fix because the new parser will solve this and we're not going to put any work in the old parser/lexer.
