### ISSUE TITLE
NamedTuple._replace()

### ISSUE THREAD

**Issue by smessmer** [python/mypy#2143]
NamedTuple has some public functions starting with an underscore, see https://docs.python.org/2/library/collections.html

When I try to use them, mypy complains with 

    error: "MyType" has no attribute "_replace"

**Comment by gvanrossum** [comment]
This should be fixed in the repo already, in https://github.com/python/mypy/pull/1810. You should be able to install straight from the repo, like this:
```
pip3 install -U git+git://github.com/python/mypy.git
```

**Comment by smessmer** [comment]
Thanks, sorry didn't see that.
