### ISSUE TITLE
type comments referencing unimported types

### ISSUE THREAD

**Issue by samuelcolvin** [python/mypy#2152]
lets say I have:

foo.py:

``` python
class Foo:
    pass
```

and bar.py

``` python
import foo
things = []  # type: List[foo.Foo]
...
things = [foo.Foo() for whatever in whereever]
...
```

works fine.

But what happens if for some reason `import foo` is unnecessary (eg. `things` is populated somewhere else and `things = [foo.Foo()...` is removed)? 

If I keep `import foo` pep8/pycodestyle will quite rightly complain about an unused import. However there seems to be no way (I can find) to use `foo.Foo` or `Foo` in a type comment without the import?

Am I missing something, perhaps with `MYPYPATH`, or is this currently not possible?

If this currently isn't possible it makes type comments pretty hard to use as even things like `Union` aren't available unless they happen to be used in a type annotation somewhere else in the file and are therefore imported.

(Apologies if I've missed something obvious, this feel like a dumb question, but I can't see a way round currently.)

**Comment by elazarg** [comment]
Not really an answer, but the situation will naturally improve with the new variable annotation syntax ([PEP-526](https://www.python.org/dev/peps/pep-0526/)) in Python3.6.

**Comment by gvanrossum** [comment]
It's not a dumb question, but we consider this a deficiency in pep8 (now pycodestyle), not in mypy or PEP 484. At Dropbox we've developed an ugly hack to work around this but we're hesitant to publish it -- it's better to just change your pep8 configuration so it won't complain about this. (Mypy will tell you when you use something that you haven't imported.)
