### ISSUE TITLE
Support typing.TYPE_CHECKING

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2165]
This ought to replace `MYPY` as a special variable.

See https://www.python.org/dev/peps/pep-0484/#runtime-or-type-checking

**Comment by elazarg** [comment]
Anything more than adding to [semanal.py](https://github.com/python/mypy/blob/master/mypy/semanal.py#L3027-L3028)
```Python
        elif name == 'MYPY':
            result = ALWAYS_TRUE
+       elif name == 'TYPE_CHECKING':
+           result = ALWAYS_TRUE
    if negated:
```
?

(I don't think it should be looking for `typing.TYPE_CHECKING`. It's more flexible without it)

**Comment by gvanrossum** [comment]
Agreed, I have a patch ready.

**Comment by gvanrossum** [comment]
See https://github.com/python/mypy/tree/type_checking.
