### ISSUE TITLE
Deprioritize imports within a `if TYPE_CHECKING:` when processing import cycles

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2166]
If an import is ignored at runtime (due to being in an `if TYPE_CHECKING:` or `if MYPY:` block), it should always be considered to be of the lowest priority when sorting import cycles. This is important, in particular, since the imports could well be of form `from m import ...`, which are given the highest priority right now.

There is more discussion in #481.

**Comment by gvanrossum** [comment]
I tried this (#2167) and it didn't work very well. We may try again in the future but for now I think it's a dead end, so I'm closing this.

**Comment by gvanrossum** [comment]
Sorry, reopening, we need both this and the cross-module deferred processing of functions I proposed in https://github.com/python/mypy/issues/481#issuecomment-253254877.

**Comment by gvanrossum** [comment]
Fixed by #2167.
