### ISSUE TITLE
Cannot install the latest mypy (Python 3.5)

### ISSUE THREAD

**Issue by nait-aul** [python/mypy#2171]
```
$ pip install mypy  # or
$ pip install --no-cache-dir mypy
```

raises `ImportError` for the required package `dbutils`:

```
Python 3.5 is not supported by DBUtils.
```

**Comment by nait-aul** [comment]
Sorry,

bad installing. I forgot the `mypy-lang`.

**Comment by kirbyfan64** [comment]
This is literally the most duplicated issue on the planet. :O

**Comment by nait-aul** [comment]
Yep, I feel ashamed (haven't use mypy for almost 1 month and what's happened). Has anyone tried to contact the author of the `mypy` package to make a "deal" with him / her?

For me I would rather welcome renaming `mypy-lang` to something easier / memorable :stuck_out_tongue_closed_eyes:.

**Comment by gvanrossum** [comment]
The owner of mypy on PyPI doesn't respond to email and the PyPI admins
won't delete their project without their consent. Anybody want to hire a
private detective (in China!) to track him down and ask him nicely?

**Comment by kirbyfan64** [comment]
Hire someone to "convince" them. I may or may not know Italians with...*connections*... ;)

**Comment by gvanrossum** [comment]
LOL my name is Guido... But seriously, I'm sure that's not needed. They've
just stopped using the GMail account they had in 2011.
