### ISSUE TITLE
Strange error for NoneType

### ISSUE THREAD

**Issue by elazarg** [python/mypy#2173]
I have no idea what's going on, but:
```
x = None  # type: None
```
Result:
```
error: Incompatible types in assignment (expression has type None, variable has type None)
```
It feels like it's caused by something more serious than an uninteresting edge case. I arrived at it from #2172.

**Comment by gvanrossum** [comment]
This is due to the special treatment for None. It goes away if you use
--strict-optional. There are already several issues for this, please close
this one.

--Guido (mobile)
