### ISSUE TITLE
Cannot use cast(None, x) or cast(type(None), x) to assert a value is None

### ISSUE THREAD

**Issue by davidfstr** [python/mypy#2175]
(1) If I have code like:

```
class SomeDjangoModel(models.Model):
    deprecated_field = cast(None, models.CharField(...))
```

mypy complains with:

```
myapp/models.py:####: error: Cannot cast from "Any" to None
```

---

(2) Similarly, if I try to workaround with `type(None)` as a more explicit version of `None`:

```
class SomeDjangoModel(models.Model):
    deprecated_field = cast(type(None), models.CharField(...))
```

mypy still complains:

```
myapp/models.py:####: error: Cast target is not a type
```

---

My expectation is that mypy would accept `type(None)` as a valid first argument for `cast(...)`.

**Comment by gvanrossum** [comment]
This too, should work correctly when you specify `--strict-optional`.

**Comment by davidfstr** [comment]
I have verified that the following example program is sensibly flagged by mypy when passing `--strict-optional`:

```
from typing import cast

none = None
definitely_none = cast(None, none)
print(len(definitely_none))
```

This program is sensibly flagged with the error:

```
test_cast_to_none.py:8: error: Argument 1 to "len" has incompatible type None; expected "Sized"
```
