### ISSUE TITLE
Trouble merging {str, Optional[str]} -> Optional[str] during control flow

### ISSUE THREAD

**Issue by davidfstr** [python/mypy#2177]
Consider the following program:

```
import os
from typing import Optional

_LOGGING_ENABLED = True
if _LOGGING_ENABLED:
    _LOG_ROOT = '/var/log/django'  # type: str
    try:
        if not os.path.exists(_LOG_ROOT):
            os.makedirs(_LOG_ROOT)
    except PermissionError:
        _LOG_ROOT = None  # type: Optional[str]
else:
    _LOG_ROOT = None  # type: Optional[str]

# (I expect _LOG_ROOT to be treated as Optional[str] here)
```

If I typecheck with:

```
$ mypy --strict-optional test_merge_of_optional.py
```

Then I get the following errors:

```
test_merge_of_optional.py:8: error: Type argument 1 of "exists" has incompatible value "Optional[str]"
test_merge_of_optional.py:9: error: Type argument 1 of "makedirs" has incompatible value "Optional[str]"
test_merge_of_optional.py:11: error: Name '_LOG_ROOT' already defined
test_merge_of_optional.py:13: error: Name '_LOG_ROOT' already defined
```

mypy appears to be confused:

* On line 8 and 9 mypy should deduce that `_LOG_ROOT` has type `str` but it seems to think it is `Optional[str]`, perhaps due to future redefinitions of `_LOG_ROOT`.
* On line 11 and 13 mypy is rejecting the redefinition of type `_LOG_ROOT`, perhaps due to [this known issue].

Thoughts?

[this known issue]: http://mypy.readthedocs.io/en/latest/common_issues.html#redefinitions-with-incompatible-types

**Comment by davidfstr** [comment]
In case it's of interest, I was able to do the following as a workaround:

```
import os
from typing import Optional

_LOGGING_ENABLED = True
if _LOGGING_ENABLED:
    _DEFAULT_LOG_ROOT = '/var/log/django'
    try:
        if not os.path.exists(_DEFAULT_LOG_ROOT):
            os.makedirs(_DEFAULT_LOG_ROOT)
        _LOG_ROOT = _DEFAULT_LOG_ROOT  # type: Optional[str]
    except PermissionError:
        _LOG_ROOT = None
else:
    _LOG_ROOT = None

# (I expect _LOG_ROOT to be treated as Optional[str] here)
```

It would be nice if I didn't have to introduce the extra `_DEFAULT_LOG_ROOT` variable though.

**Comment by gvanrossum** [comment]
Mypy really doesn't like multiple type annotations for the same
variable (a # type comment applies to a variable, not to an
expression). The usual way to type such a program is to write

    _LOG_ROOT = '/var/log/django' # type: Optional[str]

at the first occurrence.

(This issue is actually why PEP 526 was created, but it has no
practical value yet.)

**Comment by davidfstr** [comment]
Understood.

When redefining the type of an existing variable I'll continue the workaround of splitting the original variable to two differently-typed variables, as shown in the second example.

(In the first example provided, it's not actually possible to type _LOG_ROOT as Optional[str] because os.path.exists won't accept it then.)
