### ISSUE TITLE
Update docs for "Import cycles" to refer to TYPE_CHECKING

### ISSUE THREAD

**Issue by davidfstr** [python/mypy#2178]
On the following page:

* http://mypy.readthedocs.io/en/latest/common_issues.html#import-cycles

It is mentioned:

> It is possible that in the future, mypy will change its dead code analysis and this trick will stop working. We will then offer an alternative, e.g. a constant defined by the typing module that is False at runtime but True while type checking.

The aforementioned constant now exists in the form of `typing.TYPE_CHECKING`. It might be useful to update the docs to refer to it, including in the example.

I could put a docs patch together if this is the correct approach.

**Comment by gvanrossum** [comment]
Oh, yes! Thank you for finding that. If you could send a PR to update the
docs that would be great!

**Comment by davidfstr** [comment]
PR: https://github.com/python/mypy/pull/2181

**Comment by ddfisher** [comment]
Fixed by #2181.
