### ISSUE TITLE
Rip out weak mode

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2213]
There's currently something called "weak mode" that's labeled experimental, is used by nobody (AFAICT), likely buggy, and confuses readers of the implementation. Nobody cares about owning it. Therefore I propose to rip this out.

This would also close:
- Weak type checking mode #1038
- Rethink detection of weakmode #925 

In its place, we can now specify various flags like `check_untyped_defs` or `disallow_untyped_defs` in glob-sections of `mypy.ini` (see http://mypy.readthedocs.io/en/latest/config_file.html#per-file-flags)

**Comment by JukkaL** [comment]
This sounds reasonable. There hasn't been recent user interest in the weak mode, and it increases mypy implementation complexity.

**Comment by gvanrossum** [comment]
Fixed by #2217.
