### ISSUE TITLE
join_types(UninhabitedType, t) should be t

### ISSUE THREAD

**Issue by rwbarton** [python/mypy#2227]
For some reason `join_simple` has logic to move `UninhabitedType` to the second argument but `join_types` does not.

**Comment by ddfisher** [comment]
I'm not sure why we haven't seen this cause any issues, but this definitely seems like a bug.  Should be straightforward to fix.

**Comment by rwbarton** [comment]
It came up in #1748 when type checking an expression like `a if False else b`. I changed that test to better reflect its original intent but after #1748 we'll have the wrong inferred type for that (admittedly unlikely) expression.

I forget why we have two `join_*` functions in the first place, though...

**Comment by ddfisher** [comment]
`join_simple` appears to only be used in one place: https://github.com/python/mypy/blob/de75f9bf73ed11cec3b25d7bd42ba6cce92ea8d2/mypy/binder.py#L145
It'd be good to kill it if possible...
