### ISSUE TITLE
clean Python generation

### ISSUE THREAD

**Issue by ror6ax** [python/mypy#2232]
This might be a mad idea, but I think many would love the safety of strong types in development while not actually using the superset of standard Python at runtime.

Is there a possibility to run a parser, which would generate a vanilla-python version of the code?

**Comment by kirbyfan64** [comment]
But all of mypy's code is technically valid Python...so it *is* vanilla-Python...

Am I misunderstanding what you're saying?

**Comment by Michael0x2a** [comment]
More specifically, the function annotations syntax was [added in Python 3.0](https://www.python.org/dev/peps/pep-3107/), and the typing module was [added in Python 3.5](https://www.python.org/dev/peps/pep-0484/) and is available as a library you can install from PyPi if you want to add types to codebases written for older versions of Python (including Python 2.7).

If you want to add types to a codebase that must be Python 2.7 compatible, see http://mypy.readthedocs.io/en/latest/python2.html for documentation on how to do so. 

I'm not entirely sure if there's a tool that'll convert a codebase using Python 3 function annotations into Python 2-compatible code, though.

**Comment by gvanrossum** [comment]
The codec that was ripped out recently actually contained code to convert Python 3 function annotations to Python2 (but uglified). See #2218. Other than that I think this request seems to be based on a misunderstanding (or maybe a confusion between Python 2 and 3) so I'm closing it. @ror6x If you disagree or we've misunderstood you, please comment and I'll reopen it.
