### ISSUE TITLE
Concatenation of tuples

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#224]
Concatenation of fixed-length tuples should be supported by the type checker. 

Arbitrary tuples could be concatenated. `Tuple[int, str] + Tuple[bool]` results in `Tuple[int, str, bool]`.

Concatenating two homogeneous tuples (`Tuple[T, ...]`) already works.

**Comment by bertrand-caron** [comment]
Hi @JukkaL, any update on this feature ? Currently, concatenating two fixed-lengths tuples results in a `Unsupported operand types for +` error and a messed up type as demonstrated by the example below:

```
a = (1,) # Tuple[int]
b = ('bob',) # Tuple[str]
c = a + b # Tuple[int, str]
reveal_type(a)
reveal_type(b)
reveal_type(c)
```

```
$ mypy a.py 
a.py:5: error: Unsupported operand types for + ("Tuple[int]" and "Tuple[str]")
a.py:13: error: Revealed type is 'Tuple[builtins.int]'
a.py:14: error: Revealed type is 'Tuple[builtins.str]'
a.py:15: error: Revealed type is 'builtins.tuple[builtins.int*]'
```

**Comment by JukkaL** [comment]
Unfortunately nobody is working on this and this is not in our near-term roadmap. Adding a priority label so that contributors may be more likely to pick this up.

**Comment by JukkaL** [comment]
Currently the concatenation of two tuples is accepted by mypy but the result has type `Tuple[Any, ...]`.

**Comment by ilevkivskyi** [comment]
This still give an error when mixing fixed length and homogeneous, see https://github.com/python/mypy/issues/6337

**Comment by doerwalter** [comment]
I would like to have support for that feature too. The following code:

``` python
from typing import *

def d2(x: int, y: int) -> Tuple[int, int]:
    return (x, y)

def d3(x: int, y: int, z: int) -> Tuple[int, int, int]:
    return d2(x, y) + (z,)
```

results in the mypy error: `Incompatible return value type (got "Tuple[Any, ...]", expected "Tuple[int, int, int]")`
