### ISSUE TITLE
Types of class member variables are not checked

### ISSUE THREAD

**Issue by kencoken** [python/mypy#2243]
Running mypy on the following class, using Python 3.6 support (PEP 526):
```
class TestClass:

    a: str = 9

    def __init__(self):

        self.b: str = 8
        self.b = 12

    def test_method(self):
        self.b = 50
```
Results in the following output:
```
another_test.py: note: In class "TestClass":
another_test.py:3: error: Incompatible types in assignment (expression has type "int", variable has type "str")
```
It seems as if the type of the member variable `b` is not checked.

**Comment by gvanrossum** [comment]
Try adding `-> None` to the signatures of both methods. Unannotated functions/methods are not checked at all.

**Comment by kencoken** [comment]
Works great – thanks for the pointer!

Is the behaviour you describe intentional? Wasn't able to find anywhere where this was discussed.

**Comment by kirbyfan64** [comment]
#2215 #1370 #1334

**Comment by JukkaL** [comment]
It's described in the documentation: https://mypy.readthedocs.io/en/latest/basics.html (maybe we should make the wording somehow more explicit, as users commonly miss this point).

**Comment by gvanrossum** [comment]
I've added a section on this to http://mypy.readthedocs.io/en/latest/common_issues.html (should be ready any minute now).
