### ISSUE TITLE
Should collections containing None require type annotations?

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2246]
Currently, collections containing only `None` require type annotations (in strict Optional -- they're meaningless otherwise).  For example:
```py
x = [None]  # E: Need type annotation for variable
```

As @dmoisset mentioned in #2230, this can be confusing.  We should consider whether or not we really want to require a type annotation.  And if we do, we should consider finding a more understandable error message.

**Comment by gvanrossum** [comment]
It's especially annoying because this doesn't seem to work with partial types. E.g. this works:
```python
x = None
x = 12
```
but this doesn't:
```python
x = [None]
x[0] = 12
```
The latter still gives the error `Need type annotation for variable`.

So I'm all for not making this an error and just inferring it as list-of-none.

**Comment by ddfisher** [comment]
That said, this will work:
```py
x = [None]
x.append(12)
```

We don't currently pay attention to assignments to disambiguating partial types.

**Comment by gvanrossum** [comment]
We discussed this offline, and ended up deciding that the type of `[None]`
isjust  `List[None]` (not a partial type), and if you want something else
you should add a type comment.

**Comment by JukkaL** [comment]
Sounds reasonable to me. Ultimately, as this will often result in an error, the important bit is to generate an understandable error message for code like this:

```
x = [None]
x.append(1)
```
