### ISSUE TITLE
try-except import results in error

### ISSUE THREAD

**Issue by RitwikGupta** [python/mypy#2251]
```python
try:
    # Python 3
    from urllib.request import urlopen
except ImportError:
    # Python 2
    from urllib2 import urlopen
```
results in `file.py:X: error: Name 'urlopen' already defined`

**Comment by JukkaL** [comment]
This looks like a special case of #1153. Currently you can add a `# type: ignore` on the line which mypy complains about.

**Comment by JukkaL** [comment]
Closing as a dupe. Any follow-up discussion can go to #1153.
