### ISSUE TITLE
'import cPickle as pickle' "already defined" error

### ISSUE THREAD

**Issue by Daenyth** [python/mypy#2253]
This python code generates an error. It's a common idiom and it would be good if mypy could check for it in some way.
```python
try:
    import cPickle as pickle
except ImportError:
    import pickle
```

```
$ mypy --py2 --silent-imports bad.py
bad.py:4: error: Name 'pickle' already defined
```

**Comment by gvanrossum** [comment]
Thanks -- this looks like a duplicate of #1153. Additional discussion can go there.
