### ISSUE TITLE
None gets dropped in ternary statement with lists

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2258]
```python3 -m mypy --strict-optional -c 'reveal_type([None] if bool() else [1])'
<string>:1: error: Revealed type is 'builtins.list[builtins.int]'```

**Comment by kirbyfan64** [comment]
Pretty sure this is basically just a duplicate of #2246. `is_valid_inferred_type` is `False` for `[None]` since it's technically invalid without a type annotation. Pretty sure fixing #2246 would also fix this.

**Comment by ddfisher** [comment]
Nice catch!  It looks that way to me too.  This makes me feel like our decision on #2246 is definitely right.
