### ISSUE TITLE
I wrote a mypy plugin for Pytest – thoughts?

### ISSUE THREAD

**Issue by dbader** [python/mypy#2263]
Hey there 👋 

Thanks for working on mypy – I think it's a great project and I had great fun (+caught bugs) adding typehints to some of my code bases :grinning: 

I've started working on a Pytest plugin for mypy (akin to `pytest-flake8`). Mostly as an experiment and [because someone on pytest-dev asked for it a while ago](https://mail.python.org/pipermail/pytest-dev/2016-April/003573.html). 

You can find pytest-mypy here: → **https://github.com/dbader/pytest-mypy** ← 

I'd love to hear your thoughts/feedback (personally I'm not 100% convinced yet that having a Pytest plugin for mypy even adds a lot of value).

Cheers,
Dan

**Comment by alexamici** [comment]
@dbader I'm the someone who asked for the plugin in the first place, just for reference I explained the rationale later in the same thread:

>> I stopped using pytest-{flakes,pep8,pep257,mccabe} myself and switched
>> back to flake8 again, as it's more powerful/configurable.
>>
>> So personally I'd prefer a flake8-mypy or running it directly.
>
> I see the point, but I consider pyflakes and mypy more in the "code
> correctness" league than the others, that really focus on long term
> maintainability, so I'd like to have mypy errors handled the same way as
> test failures.

**Comment by gvanrossum** [comment]
Personally I find it easier if pytest stuck to running unittests and
functional tests, and if other checks (linters, mypy, what have you) were
run separately. For CI you can have a script that calls them all but in the
day-to-day coding workflow I think I often run different tools at different
frequencies and with different expectations.

**Comment by gvanrossum** [comment]
Let's close this.

**Comment by gnprice** [comment]
Thanks for dropping us a line! Feel free to follow up (or make a separate issue) with more questions/discussion -- closed this because we think the immediate conversation is done, just to keep the tracker clean of loose ends.
