### ISSUE TITLE
Implicitly imported submodules are not always diagnosed

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2271]
Python has an annoying misfeature where if you write e.g. "import tornado" and then use "tornado.ioloop.IOLoop", it may or may not work depending on whether some other module has already imported "tornado.ioloop". (Here ioloop is a submodule of the tornado package, and tornado's `__init__.py` does _not_ import ioloop in any form.) Currently mypy duplicates that behavior, and this backfires in incremental mode. While we could fix that, we should consider instead always diagnosing this error.

(This came up in https://github.com/python/mypy/issues/2036#issuecomment-254326525.)

**Comment by JukkaL** [comment]
Closing this since there hasn't been any activity in a long time.
