### ISSUE TITLE
Add more test cases for --warn-no-return

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2276]
Here are some ideas for additional test cases (as follow-up to #1748):
- A try statement that returns almost everywhere but can fall through.
- Empty function with a literal `...` body, with or without a docstring.
-  For loops + missing return statements.
- `--warn-no-return` and `raise` or `assert False` as the last thing in a function.
- Nested try statements or loops.

(Sorry if some of these are already there.)

**Comment by msullivan** [comment]
It's been 3 years and it seems to work
