### ISSUE TITLE
Many uncalled functions

### ISSUE THREAD

**Issue by elazarg** [python/mypy#2279]
I wrote a [small script](https://gist.github.com/elazarg/bc9e5f326d718dcde827c13a3328a86b) that looks for `def`s that are not mentioned elsewhere. Nothing fancy or clever. 

Running it on `mypy/*.py mypy/test/*.py` yields 24 unused functions (output below). I have tried removing all of them except the 4 functions from `mypy/test/data.py`, and the tests pass swiftly. After removing some of them, the script finds some more.

I guess not everything is unnecessary (especially messages.py), but my guess is most of them are. And those that are needed are untested.

```
mypy/nodes.py :
        get_var_or_getter
        is_constructor
        has_writable_member
        all_base_classes
        get_var_or_setter
mypy/checker.py :
        check_type_equivalency
        wrap_generic_type
mypy/messages.py :
        incomplete_type_var_match
        incompatible_value_count_in_assignment
        type_expected_as_right_operand_of_is
        incompatible_array_item_type
        invalid_reverse_operator_signature
        function_variants_overlap
        type_incompatible_with_supertype
        not_implemented
        reverse_operator_method_with_any_arg_must_return_any
        boolean_return_value_expected
        incomplete_conversion_specifier_format
mypy/build.py :
        effective_path
mypy/semanal.py :
        is_instance_type
        add_var
mypy/treetransform.py :
        optional_types
        duplicate_inits
mypy/parse.py :
        expect_colon_and_break
mypy/test/data.py :
        reportinfo
        repr_failure
        runtest
        teardown
mypy/errors.py :
        mark_file_ignored_lines_used
        pop_import_context
        push_import_context
mypy/checkexpr.py :
        apply_generic_arguments2
        has_non_method
        is_boolean
```

[Edit: I have added another script there. It is more sophisticated and it finds more unused functions (41), but I did not verify its results in this project so it might have more false positives]

**Comment by elazarg** [comment]
@gvanrossum I thought you might like this

**Comment by gvanrossum** [comment]
Nice, though I had expected the implementation would somehow leverage
mypy's own static analysis. There are many ways that grepping for a string
doesn't necessarily reveal all calls...

**Comment by elazarg** [comment]
The script only misses dynamically-constructed names, which mypy does not track anyway and which this project tries to avoid. mypy can find _more_ uncalled function, but it can't avoid false positives (of which, to my knowledge, currently there are none; I admit that avoiding `test_*` is hardcoded in the script).

**Comment by gvanrossum** [comment]
FWIW, N small PRs that clean up one issue each are much quicker to review than one large PR that cleans up those same N issues.

**Comment by elazarg** [comment]
Looks like the script has amazingly small number of false positives, compared to more sophisticated ast-based versions such as `vulture` and my own. Yet it is effective. I find this interesting.

The script also warns about the following:
```
mypy/test/helpers.py: Unused function assert_string_arrays_equal_wildcards
mypy/util.py: Unused function array_repr
runtests.py: Unused function add_python2
runtests.py: Unused function add_mypy_string
runtests.py: Unused function add_python
```
But I am a bit hesitant about removing them.

**Comment by gvanrossum** [comment]
Originally mypy was written in itself (when mypy was a different language).
It was then a much simpler language than Python. So the code is relatively
unsophisticated, especially the older parts. So I am not surprised that
your script has few false positives.

Yet I would stop while you're ahead. :-)

**Comment by JukkaL** [comment]
Much of the codebase was actually written in Alore, which was an even simpler language than the old mypy language. I translated the Alore codebase to the mypy language using a tool, and this resulted in some interesting style issues that you might still find in some parts of the codebase, though most of those have been cleaned up by now.

**Comment by elazarg** [comment]
I still use [uncalled](https://libraries.io/pypi/uncalled) from time to time; it reveals some unused functions now and then, but this is no longer an real issue.
