### ISSUE TITLE
Mypy coverage reports appear to ignore type comments

### ISSUE THREAD

**Issue by rowillia** [python/mypy#2284]
I've got some code that is parsing a json blob into a strongly-typed object, and the coverage reports appear to ignore all of the type comments.  Repro below

test_foobar.py:
```
from typing import Any, Dict, List, Optional, Set  # noqa


class Foo(object):
    """Parse a json blob into a foo
    """
    def __init__(self, blob: Optional[Dict[str, Any]]) -> None:
        self.enabled = bool(blob and blob.get('enabled'))  # type: bool
        self.blarg = set(blob.get('blarg', []))  # type: Set[str]
```

mypy -s --fast-parser --txt-report build test_foobar.py
```
Mypy Type Check Coverage Summary
================================

Script: index

+-------------+-------------------+-------+
| Module      | Imprecision       | Lines |
+-------------+-------------------+-------+
| test_foobar |  33.33% imprecise | 9 LOC |
+-------------+-------------------+-------+
| Total       |  33.33% imprecise | 9 LOC |
+-------------+-------------------+-------+
```

<img width="589" alt="screen shot 2016-10-19 at 9 42 26 am" src="https://cloud.githubusercontent.com/assets/808798/19528346/7288f2ae-95e0-11e6-844b-ef25b2fa58a7.png">

**Comment by gvanrossum** [comment]
While IIUC the coverage report generator is considered permanently under construction, I've got a feeling that we can't blame it for this. These type comments should really be considered variable declarations/annotations (similar to PEP 526 but without custom syntax), and it's definitely true that e.g. `blob.get('enabled')` has type `Any`.

You could play with a few permutations of the sample code to see if you can understand how the report generator really looks at things, or you could read the code... I'm not sure it could do much better but perhaps there is a way.

**Comment by JukkaL** [comment]
A line is red if something on the line has type `Any`, as is the case here. Here it's pretty innocent, but it's difficult to determine when `Any` will not cause problems in general.

**Comment by gvanrossum** [comment]
So we don't think this is a bug. Closing.
