### ISSUE TITLE
Parse error when expanding keyword arguments from multiple sources

### ISSUE THREAD

**Issue by dokai** [python/mypy#2285]
The following simplified test case which expands keyword arguments from multiple sources

```
λ cat mypytest.py
a = {'a':1}
b = {'b':2}
c = dict(**a, **b)
```

produces a parse error as follows

```
λ ./bin/mypy mypytest.py
mypy_pytest.py:3:14: error: Parse error before **
```

**Comment by dokai** [comment]
With version `mypy_lang==0.4.5`

**Comment by kirbyfan64** [comment]
What if you pas `--fast-parser`?

**Comment by gvanrossum** [comment]
It passes with `--fast-parser`. Newer Python syntax always requires that flag. We consider this fixed.

**Comment by dokai** [comment]
Confirmed, thanks!
