### ISSUE TITLE
Type checking against abstract types (collections.abc) without subclassing from them

### ISSUE THREAD

**Issue by chadrik** [python/mypy#2292]
Hi, me again.  Still slogging my way through more real-world scenarios.  I hope this feedback is helpful and not annoying.

I expected the following to work:

```python
from typing import List, Sized

class Foo(object):
    def __len__(self):
        return 0

f = Foo()
assert isinstance(f, Sized)

c = []  # type: List[Sized]
c.append(f)
```

It seems that `Foo` must inherit explicitly from `Sized`.  I understand that the `isinstance` check works by virtue of a `__subclasshook__` on `collections.abc.Sized`, and that the results of this method are difficult or impossible to determine statically, but it would be incredibly handy if there were a way to make this work within mypy.  For large code-bases, the idea of reworking all of the class inheritance to get some of the key benefits of static type-checking lies somewhere between daunting and deal-breaker.

Essentially what we want is a way for a class using `ABCMeta` to indicate in a static fashion that "a class is a subclass of me if it implements all of my methods".  Perhaps it could be done with a subclass of `ABCMeta` (`ABCInterfaceMeta`?) that adds a boilerplate `__subclasshook__`.  Then mypy could know to engage this rule for any types that use this metaclass.

**Comment by gvanrossum** [comment]
That's https://github.com/python/typing/issues/11 -- I don't think we need a separate issue in mypy open for this. (Also, I don't think we should focus too much on ABCMeta and `__subclasshook__`. Those are runtime mechanisms. We should first design the ideal way to spell this as part of static declarations and then see how we can make runtime support for that design.)
