### ISSUE TITLE
Give a more specific error than '"module" has no attribute "blah"'

### ISSUE THREAD

**Issue by rwbarton** [python/mypy#2297]
If I accidentally write

```
import re
re.matc
```

I get a relatively unhelpful error

```
x/noattr.py:2: error: "module" has no attribute "matc"
```

It would be nice to provide an error more like

```
x/noattr.py:2: error: module "re" has no attribute "matc"
```

Bonus points for suggesting the correct name like we do for class attributes.

**Comment by rwbarton** [comment]
I took a look at implementing this, but it wasn't very simple as we don't have the original expression at hand when we fail to find the attribute.

**Comment by gvanrossum** [comment]
That explains why the message is unhelpful. :-( The "module" has always
bothered me too. Maybe someone else can think of a way.

**Comment by AlexWaygood** [comment]
In 0.940, the error message is now:

```
main.py:2: error: Module has no attribute "matc"; maybe "match"?
```

which seems much better to me.
