### ISSUE TITLE
Make doc. of --warn-redundant-casts and similar more clear 

### ISSUE THREAD

**Issue by Herst** [python/mypy#2301]
Make it more clear that in this case "cast" refers to `typing.cast` and not any direct constructor usage.

That means that the following won't cause a warning by `mypy --warn-redundant-casts`:
```py
foo = 42
foo = int(int(foo) + int(1))
bar = "baz"
bar = str(str(bar) + str("zab"))
```
The following will though:
```py
from typing import cast
foo = 42
foo = cast(int, foo)
bar = "baz"
bar = cast(str, bar)
```

**Comment by gvanrossum** [comment]
Will do, but I think you have your "C" programmer's hat on when you think of an operation like int(foo) as a "cast". We don't really call it that in the Python docs (we usually call that a conversion).

Do you want to give this a try yourself?

**Comment by gvanrossum** [comment]
Actually we think this is fine.
