### ISSUE TITLE
Support functional API for Enum creation

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2306]
The `enum.Enum` class (new in Python 3.4, also backported as enum34) supports several short forms of creating an Enum type, described under [functional API](https://docs.python.org/3/library/enum.html#functional-api):

``` python
A = Enum('A', 'x y z')
B = Enum('B', ('p', 'q'))
```

These are equivalent to

``` python
class A(Enum):
    x = 1
    y = 2
    z = 3
class B(Enum):
    p = 1
    q = 2
```

Some other syntactic variants are also allowed:

``` python
A = Enum('A', 'x,y,z')
A = Enum('A', 'x, y, z')
B = Enum('B', ['p', 'q'])
```

The values can also be expressed as a list of tuples:

``` python
[('cyan', 4), ('magenta', 5), ('yellow', 6)]
```

or a mapping:

``` python
{'chartreuse': 7, 'sea_green': 11, 'rosemary': 42}
```

**Comment by homeworkprod** [comment]
I've been checking out mypy for less than two minutes, stumbled upon the error (`Too many arguments for "Enum"`) with the first few files to check, searched the web, and followed a trail of issues to find out that this is at least known.

Yeah, I'd like to see this fixed rather sooner than later. This might drive new users away right at the start.

Until then, is there a way to suppress the error and keep mypy from exiting with a return code > 0 (for use in CI scripts)?

**Comment by JukkaL** [comment]
@homeworkprod The recommended fix is to refactor your code to use an alternative enum syntax. Is that not feasible for some reason? If not, I'd like to hear about your concerns. You can also try adding `# type: ignore` to silence the message. 

@gvanrossum What do you think about making this a high priority issue? Multiple users seem to be hitting this, and this shouldn't be hard to support (though the implementation will be pretty tedious to write).

**Comment by gvanrossum** [comment]
Agreed.

**Comment by homeworkprod** [comment]
@JukkaL Well, I highly prefer the (oftentimes) one-liner functional API to spreading the definition of a (smaller) enum over multiple lines *and* including distracting, somewhat error-prone numbers that are irrelevant for the business logic (in the cases in question). Why have (to read) half a page of code when three lines neatly do the trick?

The ignore hint works for me, so I'll go with that for now, thank you.

**Comment by homeworkprod** [comment]
Just a quick feedback: Works for me now (tested with Mypy 0.511). Thanks!

**Comment by anentropic** [comment]
mypy 0.540
```python
PictureSize = Enum('PictureSize', 'P0 P1 P2 P3 P4 P5 P6 P7 P8', type=str, module=__name__)
```
gives:
error: Too many arguments for Enum()
```
Later when trying to access a value from the enum:
```
error: "Type[Enum]" has no attribute "P0"
```
I understand if it won't be fixed, but I thought from previous comment maybe it had been?

**Comment by anentropic** [comment]
ah I see, removing the `type=str, module=__name__` extra kwargs gets rid of the second error too

I guess with this much working now it ought to be easy to add recognition of all the kwargs the constructor supports as detailed in the docs?https://docs.python.org/3/library/enum.html#functional-api

**Comment by JukkaL** [comment]
@anentropic Yeah, this is something mypy should be able to support pretty easily. Created #4184 to track the issue.

**Comment by rubendibattista** [comment]
Is this related? https://github.com/python/mypy/issues/4865

Because I'm hitting the same problem...
```
from enum import IntEnum
from typing import Collection


def list_to_enum(cls, fields: Collection[str]) -> IntEnum:
    """ Convert a list of textual fields to the class:`IntEnum` that needs
    to be stored in this class :attr:`fields` """

    return IntEnum(
        cls._FIELDS_ENUM_NAME, dict(zip(fields, range(len(fields))))
    )

```

From [here](https://docs.python.org/3/library/enum.html#functional-api)
> The second argument is the source of enumeration member names. It can be a whitespace-separated string of names, a sequence of names, a sequence of 2-tuples with key/value pairs, or a mapping (e.g. dictionary) of names to values. The last two options enable assigning arbitrary values to enumerations; the others auto-assign increasing integers starting with 1 (use the start parameter to specify a different starting value). A new class derived from Enum is returned.

**Comment by JukkaL** [comment]
@rubendibattista Your example is too dynamic for mypy to understand (see https://github.com/python/mypy/issues/4865#issuecomment-592560696).

**Comment by mvoitko** [comment]
Are there PRs, issues or at least plans to handle the case @rubendibattista metioned?
I have faced a similar problem:
```python
import enum


class StrAutoEnum(str, enum.Enum):
    def _generate_next_value_(name: str, start: Any, count: int, last_values: Any) -> str:  # type: ignore[misc, override] # noqa:E501
        return name


Target = StrAutoEnum('Target', {name: enum.auto() for name in load_forecast_model_names})  # type: ignore[call-overload]

```
