### ISSUE TITLE
Bug with `type: ignore` comment on import and incremental

### ISSUE THREAD

**Issue by kirbyfan64** [python/mypy#2308]
Still trying to get a test case. However, for now, I'll post the interesting parts:
- In `errors.py`, I have code like this:

``` python
import colorama  # type: ignore
```

For some reason, the cache for this file at some point didn't add `colorama` to the `suppressed` section, so the import started being an error.

**Comment by gvanrossum** [comment]
Hm, interesting. @Michael0x2a might have some insights.

**Comment by kirbyfan64** [comment]
Create the following files:

- `x.py`:

    ```python
    A = 0
    from y import B
    ```

- `y.py`:

    ```python
    import xyz  # type: ignore
    B = 0
    from x import A
    ```

Now, watch the following commands:

```
```

**Comment by kirbyfan64** [comment]
Workaround: `rm .mypy_cache/*/y.*.json`.

**Comment by gvanrossum** [comment]
Workarounds for incremental mode that requires deleting cache files are not
very useful. :-)

**Comment by kirbyfan64** [comment]
Well, I actually just realized that a much, much better workaround is to just do `touch y.py`... I don't know why I didn't think of that before...

**Comment by gvanrossum** [comment]
But it definitely is a bug.

**Comment by gvanrossum** [comment]
Is this still reproducible?

**Comment by kirbyfan64** [comment]
@gvanrossum Yup.
