### ISSUE TITLE
Setting module search path in the config file

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2323]
I wonder if we should support configuring the module search path (equivalent to `MYPYPATH`) in the mypy config file. I have a feeling that this was discussed before, but maybe we can revisit this. 

Here's one particular use case I'm thinking about: specifying a directory for custom stubs. For example, I could have a `stubs/` subdirectory in my repository for custom stubs that I've written. It seems reasonable to be able to add this directory to the search path automatically so I won't always have to use a script that sets `MYPYPATH` for running mypy correctly. If I use `--silent-imports`, a mypy run with accidentally missing search path items will pass without errors and can easily generate false negatives.

**Comment by megapctr** [comment]
Yes, please. There's too much work with submitting stubs for 3rd party libraries to typeshed.

I managed  to side-step this problem by adding `./stubs` to `MYPYPATH`. That said, the config file would be a much more convenient place for this setting.

Here's my use case:
-  I run `stubgen foo`
- Remove everything except for the things I use from the stub
- Commit the stub

**Comment by gvanrossum** [comment]
Yes, we should do this.

@megapctr Do you feel up to submitting a PR for this? If not we can try to do it.

**Comment by megapctr** [comment]
I'm on it 👍

**Comment by ddfisher** [comment]
I agree that we want this, but for working on typeshed `--custom-typeshed-dir` (which should be ready for merge in #1588) should be a bit more convenient.

**Comment by gvanrossum** [comment]
Closed by #2329.
