### ISSUE TITLE
"SupportsInt" doesn't work with Union types

### ISSUE THREAD

**Issue by sangsta** [python/mypy#2330]
The following shouldn't be an error:
`error: Argument 1 to "int" has incompatible type "Union[unicode, int]"; expected "SupportsInt"`

**Comment by ddfisher** [comment]
In particular, you can repro this for Python 2 with:
```py
from typing import Union
x = 0  # type: Union[int, unicode]
int(x)
```

**Comment by elazarg** [comment]
I would guess it is another example of #2128 and the general overloading/Union problem.

**Comment by nolanlum** [comment]
FYI this is still an issue in Python 3.6:

`error: Argument 1 to "int" has incompatible type "Union[int, str]"; expected "SupportsInt"`

**Comment by ethanhs** [comment]
Yes, this is an issue in mypy's union deduction checks, and is independent of Python version.

**Comment by ilevkivskyi** [comment]
This issue is now fixed (example correctly passes).
