### ISSUE TITLE
Variable assignment type doesn't support Union

### ISSUE THREAD

**Issue by GPHemsley** [python/mypy#2343]
```python
#!/usr/bin/env python3

import decimal
import typing

def foo(x: decimal.Decimal) -> typing.Union[decimal.Decimal, float]:
	if x == 0:
		return -0.0

	return decimal.Decimal(x)

def bar(y: bool) -> None:
    if y:
        z = decimal.Decimal()
    else:
        z = foo(decimal.Decimal())
```

This results in the error:
> Incompatible types in assignment (expression has type "Union[Decimal, float]", variable has type "Decimal")

**Comment by JukkaL** [comment]
Mypy infers the type of a variable from the first assignment (except for a few special cases). You can work this around by adding a type annotation:

```
    if y:
        z = decimal.Decimal()  # type: typing.Union[decimal.Decimal, float]
    else:
        z = foo(decimal.Decimal())
```

Alternatively, you can negate the condition of the if statement, and mypy picks the variable type from the union-type initializer:

```
    if not y:
        z = foo(decimal.Decimal())
    else:
        z = decimal.Decimal()
```
