### ISSUE TITLE
Automatically know that the function returns None if there is no yield/return

### ISSUE THREAD

**Issue by usercz** [python/mypy#2344]
This code is okay:

```
class Something:
    def __init__(self, param):
        pass
````

This code is not:

```
class Something:
    def __init__(self, param: int):
        pass
````

Because `__init__` now needs to explicitly specify that it returns None. However this would be easy to find automatically in the easy cases where there are no return statements at all.

So I'd like mypy to implicitly know the `-> None` in such cases.

**Comment by JukkaL** [comment]
There are a couple of reasons we don't do this:

* PEP 484 says that if you leave out an annotation, it defaults to `Any`. Mypy follows the spec.
* If you have a function with no arguments, there would be ambiguity around a function returning `None` and a function without a type annotation (the latter won't be type checked and implicitly returns `Any`). So you'd have to annotate no-argument functions anyway with an explicit `-> None`. But this would be inconsistent, as sometimes you have to add `-> None` but sometimes it's implicit. Here we've chosen consistency over conciseness, as the extra typing required for the `-> None` annotations is usually pretty minimal.
* It's a little easier to visually distinguish annotated functions if they generally have `-> ret_type` in their header. (But this is a pretty minor thing.)

What might be useful is to warn about a missing return type if a function has some argument annotations.

**Comment by rwbarton** [comment]
`__init__` is also special because it *must* have return type `None`, so when you annotate an argument but not the return type, the result is an error rather than an implicit `Any`.

Implicit `Any`s are not nice, so I like @JukkaL's idea about warning on missing return types.

**Comment by elazarg** [comment]
The interpretation of `-> None` as "please check" is awkward IMHO.

**Comment by JukkaL** [comment]
This has been discussed earlier, probably several times by now. Nobody has proposed a uniformly better approach that would still make type checking optional and gradual.
