### ISSUE TITLE
--warn-no-return Warns about functions that have no return statements if used in tandem with --strict-optional

### ISSUE THREAD

**Issue by rowillia** [python/mypy#2370]
UPDATED - This problem appears to happen when `--warn-no-return` is used in tandem with `--strict-optional`

test.py:
```python
class Foo():
    def __init__(self) -> None:
        self.x = 0
    def increment_x(self) -> None:
        self.x += 1
```

`mypy -s --fast-parser --warn-no-return --strict-optional test.py`

```
test.py: note: In member "__init__" of class "Foo":
test.py:2: note: Missing return statement
test.py: note: In member "increment_x" of class "Foo":
test.py:4: note: Missing return statement
```

**Comment by rwbarton** [comment]
This is just a bug caused by the fact that `--strict-optional` changes the meaning of returning `None` internally in mypy. It works fine without `--strict-optional`.

**Comment by rowillia** [comment]
Got it.  Thanks @rwbarton for figuring out what I meant even though I forgot to specify what my flags were.  Changed the title to reflect the actual problem.

**Comment by ddfisher** [comment]
So really this is just a problematic interaction between --warn-no-return and --strict-optional.
