### ISSUE TITLE
Idea: Single flag to enable all warnings/errors

### ISSUE THREAD

**Issue by FuegoFro** [python/mypy#2376]
I'm working on a code base where we have all the warning and error flags on, and want to keep our code as clean as possible. Recently, a new warning flag was added (`--warn-no-return`), which I only happened to find out about. It would be awesome if there was some rollup flag that new warnings/errors are added to (some sort of `--strictest` or `--all-warnings-errors`) so I could be confident that mypy is using the strictest checks it offers without having to continuously check back in on what flags are available.

**Comment by gvanrossum** [comment]
I think that would be a bad idea. Each new (stricter) flag has the opportunity of causing many new spurious errors that you may have to deal with. Also, some flags may go well beyond strictness and violate e.g. PEP 484. Some may even conflict with each other. So I'm going to close this.
