### ISSUE TITLE
Only list and tuple accepted in *args call

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#238]
Using a string in *args call is not accepted by the type checker, even though it's valid in Python:

    import typing
    def f(*x: str) -> None: pass
    f(*'foo') # error

**Comment by ashleyh** [comment]
The example works on master now. Close?

**Comment by ddfisher** [comment]
The example type checks, but that's actually wrong!  The real type of `x` is `Tuple[..., str]`.

**Comment by ddfisher** [comment]
Oops!  I was actually confused by the syntax.  An explicit `str` type on a *arg means `List[str]`, which isn't quite right, but is pretty close.

**Comment by gvanrossum** [comment]
I'm sure this issue was stale.

**Comment by ddfisher** [comment]
In further testing, *args do seem to be treated appropriately as tuples.  Not sure why my initial investigation showed otherwise.  Ah well.
