### ISSUE TITLE
Generic instance variable type is not inherited in generic type

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2385]
Suppose I have a generic class over T with an instance variable of type T:
```python
T = TypeVar('T')
class C(Generic[T]):
    def __init__(self, a: T) -> None:
        self.a = a
x = C(0)  # type: C[int]
reveal_type(x.a)  # correctly reports int
```
So far so good. Now let's subclass it:
```python
class D(C, Generic[T]):
    pass
y = D(0)  # type: D[int]
reveal_type(y.a)  # reports Any?!
```
Why is the type of `y.a` not `int`? (It inherits `__init__`.)

I can fix it by inheriting from `C[T]` but that's surprising.

**Comment by rwbarton** [comment]
I think it's because the superclass `C` means `C[Any]`. So for every `T`, `D[T]` inherits from `C[Any]`, so `a` has type `Any` (since `a` has type `T` in `C[T]`).

It is unfortunate that it's so easy to make this particular mistake and accidentally introduce `Any` though.

**Comment by gvanrossum** [comment]
You're right. I'll close this now. But it's good to be reminded of this here.

**Comment by JukkaL** [comment]
The original intention was to have a strict type checking mode where mypy would complain about things like `C` (as an alias for `C[Any]`. Maybe `--disallow-untyped-defs` could also warn about that? Having a separate option seems like an overkill at least when we don't yet have a generic interface for enabling/disabling particular warnings/checks.
