### ISSUE TITLE
issues with memoryview

### ISSUE THREAD

**Issue by jonmac** [python/mypy#2390]
Running into a couple of issues with memoryview annotations.

Consider the following python3 program:
```
def fn(packet: memoryview) -> bytes:
    if chr(packet[0]) == "\xff":
        return packet.tobytes()
    else:
        return b"fail"

print(fn(memoryview(b"\xffabc")))
print(fn(memoryview(b"\xfeabc")))
```

Which when run has the following output:
```
b'\xffabc'
b'fail'
```

Presently mypy gives the following errors for this program:
```
$ mypy tmp/test.py
tmp/test.py: note: In function "fn":
tmp/test.py:2: error: Value of type "memoryview" is not indexable
tmp/test.py:3: error: "memoryview" has no attribute "tobytes"
tmp/test.py: note: At top level:
tmp/test.py:7: error: Argument 1 to "memoryview" has incompatible type "bytes"; expected "bytearray"
tmp/test.py:8: error: Argument 1 to "memoryview" has incompatible type "bytes"; expected "bytearray"
```

Each of the errors claimed here is incorrect.

**Comment by gvanrossum** [comment]
Hi Jon!

This looks like it's really a typeshed bug: https://github.com/python/typeshed

Also it looks like the Python 2 stubs for memoryview are better than the Python 3 stubs, though there are still a few issues. I think I'll just whip up a PR now.

**Comment by jonmac** [comment]
Hi! 

Ok phew that makes a lot more sense, as I didn't find any references to memoryview in the mypy code.

**Comment by gvanrossum** [comment]
Can you do a quick test with the changed stubs from the PR? (Or manually review?)

**Comment by jonmac** [comment]
Yep, it passes now when I use --custom-typing set to the current version of that file. And otherwise looks correct.
