### ISSUE TITLE
Warn about always true/false isinstance tests

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2395]
These may result in code that mypy considers unreachable and silently doesn't type check. However, they may happen quite frequently in innocent things like `assert isinstance(x, str)` so finding a good heuristic for what to report can be tricky.

**Comment by rwbarton** [comment]
Initial reactions:

* Don't warn about an assertion that always passes

* Do warn about an assertion that always fails

* Do warn about a branch of an `if` that is unreachable

**Comment by ddfisher** [comment]
To add to Reid's comment: but don't warn about an assertion that always fails if it's an explicit `assert False`.

**Comment by kirbyfan64** [comment]
@ddfisher Or any false-y builtin constant, since I've seen `assert 0` and `assert None` before.

**Comment by gvanrossum** [comment]
@ilinum This issue might be interesting given your recent quest for flagging unreachable code.

**Comment by ilevkivskyi** [comment]
I have found five other issues on the tracker that are some variations of this, so I think this is high priority.

**Comment by ilevkivskyi** [comment]
Also from my experience there is definitely no need in a warning about an always True asserts. So 100% with @rwbarton [above](https://github.com/python/mypy/issues/2395#issuecomment-258235424).
