### ISSUE TITLE
Strange error message with variable type annotation

### ISSUE THREAD

**Issue by graingert** [python/mypy#2398]
```python
from typing import NewType

Ticker = NewType('Ticker', str)
SecurityID = NewType('SecurityID', str)


SYMBOLS = {
    'ham': '4a24ab25-766d-4d6c-99e2-337da6d0ba45',
    'spam': 'e8248888-b413-4def-b11a-763b10faf9c0',
}  # type: Dict[Ticker, SecurityID]

INDICES = {
    'eggs',
    'mayo',
}  # type: Set[Ticker]

TICKERS = INDICES | SYMBOLS.keys() # type: Set[Ticker]
```

Results in:

```
s.py:7: error: List item 0 has incompatible type "Tuple[str, str]"
s.py:7: error: List item 1 has incompatible type "Tuple[str, str]"
s.py:12: error: Argument 1 to <set> has incompatible type "str"; expected "Ticker"
s.py:12: error: Argument 2 to <set> has incompatible type "str"; expected "Ticker"
```

**Comment by graingert** [comment]
If you remove the comments, everything is checked as Any, if you use `# Type: ` everything type checks correctly

**Comment by graingert** [comment]
Where's the List? where's the Tuple[str, str] coming from?

**Comment by gvanrossum** [comment]
The List and Tuple are coming from the translation mypy does from dict literals to a call to the `dict()` function. It is type-checking the translated version, which is something like `dict([(key1, value1), (key2, value2), ...])`.  There's an existing issue about that: #304.

The reason you are getting type errors here is that you can't use string literals where a Ticker or SecurityId is expected. This version is clean:
```python
SYMBOLS = {
    Ticker('ham'): SecurityID('4a24ab25-766d-4d6c-99e2-337da6d0ba45'),
    Ticker('spam'): SecurityID('e8248888-b413-4def-b11a-763b10faf9c0'),
}  # type: Dict[Ticker, SecurityID]

INDICES = {
    Ticker('eggs'),
    Ticker('mayo'),
}  # type: Set[Ticker]
```

**Comment by rwbarton** [comment]
Indeed, the purpose of `NewType` is exactly to prevent code like this from type checking.

**Comment by graingert** [comment]
@gvanrossum do you think for literals a cast is nicer?

```python
from typing import NewType, cast

Ticker = NewType('Ticker', str)
SecurityID = NewType('SecurityID', str)


SYMBOLS = cast(Dict[Ticker, SecurityID], {
    'ham': '4a24ab25-766d-4d6c-99e2-337da6d0ba45',
    'spam': 'e8248888-b413-4def-b11a-763b10faf9c0',
})

INDICES = cast(Set[Ticker], {
    'eggs',
    'mayo',
})

TICKERS = INDICES | SYMBOLS.keys() # type: Set[Ticker]
```

**Comment by gvanrossum** [comment]
No, cast() doesn't check anything -- it would let through non-strings without errors.

**Comment by JukkaL** [comment]
This would be type safe:

```
_SYMBOLS = {
    'ham': '4a24ab25-766d-4d6c-99e2-337da6d0ba45',
    'spam': 'e8248888-b413-4def-b11a-763b10faf9c0',
}
SYMBOLS = {Ticker(ticker): SecurityID(id) for ticker, id in _SYMBOLS.items()}
del _SYMBOLS
```

**Comment by graingert** [comment]
@JukkaL that's nice but it's not very elegant

**Comment by JukkaL** [comment]
If you want to use `NewType`, you almost always have to write some extra code. The extra type checking precision doesn't come for free.

**Comment by graingert** [comment]
@JukkaL I think this usecase is worth a syntactical shortcut, as quite often when you want to use a dict as a table of data it will benefit from NewType

**Comment by JukkaL** [comment]
Feel free to suggest a better syntax (please create a new issue, as this was closed).
