### ISSUE TITLE
Self-type doesn't seem to work for properties

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2402]
I found this when trying to use self-type for pathlib (see PR python/typeshed#658). There are a few properties that have type PurePath and are repeated in the Path subclass. The stub uses plain attributes for these, but the implementation has properties, so I want to replace them with properties. However this doesn't seem to work. In particular I'm trying to add this to class PurePath:
```
    @property
    def parents(self: _P) -> Sequence[_P]: ...
    @property
    def parent(self: _P) -> _P: ...
```
Now I have an example class:
```
class MyPath(pathlib.PosixPath):
    def parity(self):
        return len(str(self)) % 2

root = MyPath('/')
reveal_type(root.parent)

```
This reveals MyPath as the type but *also* gives an error:
```
__tmp__.py:14: error: Revealed type is '__tmp__.MyPath*'
__tmp__.py:14: error: Invalid method type
```
If I remove the self-type, e.g.
```
    @property
    def parents(self) -> Sequence[PurePath]: ...
    @property
    def parent(self) -> PurePath: ...
```
the error goes away but the revealed type reverts back to (of course) PurePath.

@elazarg thoughts?

**Comment by elazar** [comment]
@gvanrossum I'm thinking you were intending to @ mention someone else. 😉 It would be my luck that, the one time I'm contacted by the creator of Python, it's by mistake.

**Comment by gvanrossum** [comment]
Yup, sorry for that. :-/

**Comment by elazarg** [comment]
I think it's just an overly-restrictive check. See the PR.
