### ISSUE TITLE
Deprecations support in mypy

### ISSUE THREAD

**Issue by NVishnya** [python/mypy#2403]
It is now possible in Python to show deprecation warnings at runtime. 

```
def func(): 
    warnings.warn("deprecated", DeprecationWarning)
```

But in this case you won’t know if a method is deprecated, until you run app. As mypy can check types, it might check deprecation in the same way.

Deprecation marking can be used on the same levels as docstrings. According to PEP 257:”A docstring is a string literal that occurs as the first statement in a module, function, class, or method definition”, so deprecation can be used  for a module, function, class, or method.

**Comment by gvanrossum** [comment]
Can you show a specific example of what code with a deprecation marker in a docstring would look like? I am somehow failing the imagination to understand what you are asking for.

**Comment by NVishnya** [comment]
For example we are working on a library. In version 1.6.7 we implemented a function new_func which had better functionality than old_func. So we decided to remove old_func in the future. We marked old_func as deprecated and stated the version, when it was deprecated, and the version, when it would be completely removed (1.7.0). We also stated, which function can be used instead of old_func.

```
def old_func():
   """
   deprecated:
      from: 1.6.7 
      expectedRemoval: 1.7.0
      alternative: package.module.new_func()
   """
    pass


def new_func():
    pass
```
When old_func is used, mypy should show a warning, that old_func is deprecated.

**Comment by gvanrossum** [comment]
I don't think it would be reasonable for mypy to just scan all docstrings for the word "deprecated" and then start parsing the text of the docstring from there (too many things can go wrong with the assumption that there is structured data following).

Before this can become a mypy feature we'd have to agree on some specific syntax that can be shared between many projects, and I don't think that what you showed here is it. Maybe you can propose a decorator for this purpose? But there are more issues yet -- e.g. what are the version numbers supposed to refer to? Or should the deprecation warning appear regardless of the version? From where should the decorator be imported?

Or perhaps you could do this as a structured comment, similarly to the way mypy and PEP 484 support `# type:` comments?

In any case I have to give you a fair warning: this does not look like something that we (mypy's core developers) are very interested in implementing. And it looks like it is going to take a lot of effort to propose and agree to a way to specify deprecation.

**Comment by kirbyfan64** [comment]
Seems like the perfect use for a decorator:

```python
@deprecated(from='1.6.7', removal='1.7.0', alt='new_func')
def old_func(): ...
```

**Comment by kirbyfan64** [comment]
Or:

```python
@deprecated(version='1.6.7', removal='1.7.0', use='new_func')  # If new_func was already defined, you can drop the quotes
def old_func(): ...
```

**Comment by gvanrossum** [comment]
Go on...

**Comment by NVishnya** [comment]
@kirbyfan64 
But how can we deprecate a module using a decorator?

**Comment by ethanhs** [comment]
I think this can safely be closed. 3.7 has some nice helpful things like `__getattr__` and `__dir__` at the module level one can use!

**Comment by tailhook** [comment]
> I think this can safely be closed. Python 3.7 has some nice helpful things like __getattr__ and __dir__ at the module level one can use!

Sorry, but it seems entirely unrelated. The original comment says that instead of throwing deprecation warnings at runtime we want deprecation notices checked by mypy statically.

So I believe this issue should be reopened.

**Comment by tailhook** [comment]
Speaking about the syntax: what about using [deprecation](https://pypi.org/project/deprecation/) package?

Example from the front page:
```python
import deprecation

@deprecation.deprecated(deprecated_in="1.0", removed_in="2.0",
                        current_version=__version__,
                        details="Use the bar function instead")
def foo():
    """Do some stuff"""
    return 1
```

**Comment by remdragon** [comment]
Is there no interest in this? I have had to resort to the following tactic:

```
class Foo:
   def new_method ( self ) -> None:
      do.something.here()

def Foo_old_method ( self: Foo ) -> None:
   warnings.warn (
      'Foo.old_method() deprecated - use Foo.new_method() now',
      DeprecationWarning,
      stacklevel = 2,
   )
   self.new_method()
setattr ( Foo, 'old_method', Foo_old_method )
del Foo_old_method

Foo().old_method() # <-- runtime deprecation warning / mypy error
```

This allows the old_method to still work and generate a deprecation warning at runtime, but prevents mypy from knowing old_method exists.

This is not ideal because mypy complains that old_method doesn't exist. It would be better if mypy could instead issue a warning that old_method was deprecated.

Perhaps mypy could attempt to import the deprecation package and enable support if that module is installed?

Alternatively it couldn't be too hard to add a simple deprecation decorator to types, though I assume this would require a PEP?

**Comment by Akuli** [comment]
maybe mypy should implement this https://github.com/python/typing/issues/609

**Comment by Akuli** [comment]
Terrible workaround for now: make deprecated methods untyped and run mypy with `--strict`. This way using a deprecated method emits a mypy error saying you can't call an untyped method from typed context.

Also, it would be very nice if deprecations could be marked in typeshed so that standard library functions could be marked as deprecated.
