### ISSUE TITLE
'"ClassName" expects no type arguments, but 1 given' while inheriting from Iterable

### ISSUE THREAD

**Issue by sametmax** [python/mypy#2425]
I have a class looking like this:

```
from collection import Iterable, Iterator
class IterableWrapper(Iterator, Iterable, BaseWrapper):
    ...
```

And a function type definition later going:

`# type: (...) -> IterableWrapper[tuple[T, T2]]`

Mypy complains:

`src/ww/wrappers/iterables.py:600: error: "IterableWrapper" expects no type arguments, but 1 given`

While:

`# type: (...) -> IterableWrapper` and `# type: (...) -> Iterable[tuple[T, T2]]` don't get any warning.

I was expecting that, inheriting from `Iterable,` I could do `IterableWrapper[tuple[T, T2]]` like I would do `Iterable[tuple[T, T2]]` and benefit from code checking on yielded elements.

**Comment by gvanrossum** [comment]
It looks like you want `IterableWrapper` to be generic. The way to do that is
```python
T = TypeVar('T')
class IterableWrapper(Iterator[T], Iterable[T], BaseWrapper, Generic[T]):
    ...
```
Also you shouldn't need Iterable[T] because Iterator already inherits from Iterable.

I am presuming your BaseWrapper is not generic.

**Comment by JukkaL** [comment]
Note that `Iterable`  means `Iterator[Any]` instead of `Iterator[T]`.

**Comment by sametmax** [comment]
Righ. Thanks for this explanation. I think I'm going to write a big tutorial on mypy in the coming months.

**Comment by sametmax** [comment]
Ooops. Forgot to ask: why do I have to inherit from Iterator[T] AND Generic[T]? Iterator[T] is not a generic already ?

**Comment by gvanrossum** [comment]
Oh, that's a separate issue. According to PEP 484 you shouldn't need the
Generic[T] unless you have multiple type variables and you want to specify
their order, but mypy currently always requires the Generic[T]. It's issue
#302.
