### ISSUE TITLE
Literal to NewType enforcement

### ISSUE THREAD

**Issue by graingert** [python/mypy#2448]
For me the biggest usecase of NewType in mypy programs is tabular data that are included in big tables of "universal data structures": list, dict, tuple, str.

When using NewTypes to enforce these simple types that can be instantiated via literals it would be great to make it easier to define large blocks at once:

The following should fail:
```python
from typing import NewType

Ticker = NewType('Ticker', str)
SecurityID = NewType('SecurityID', str)


SYMBOLS = {
    'ham': '4a24ab25-766d-4d6c-99e2-337da6d0ba45',
    'spam': 'e8248888-b413-4def-b11a-763b10faf9c0',
}  # type: Dict[Ticker, SecurityID]

INDICES = {
    'eggs',
    'mayo',
}  # type: Set[Ticker]

TICKERS = INDICES | SYMBOLS.keys() # type: Set[Ticker]
```
@gvanrossum 's suggestion is a bit too verbose for me:

```python
SYMBOLS = {
    Ticker('ham'): SecurityID('4a24ab25-766d-4d6c-99e2-337da6d0ba45'),
    Ticker('spam'): SecurityID('e8248888-b413-4def-b11a-763b10faf9c0'),
}  # type: Dict[Ticker, SecurityID]

INDICES = {
    Ticker('eggs'),
    Ticker('mayo'),
}  # type: Set[Ticker]
```

Using cast has no type safety:
```python
from typing import NewType, cast

Ticker = NewType('Ticker', str)
SecurityID = NewType('SecurityID', str)


SYMBOLS = cast(Dict[Ticker, SecurityID], {
    'ham': '4a24ab25-766d-4d6c-99e2-337da6d0ba45',
    'spam': 'e8248888-b413-4def-b11a-763b10faf9c0',
})

INDICES = cast(Set[Ticker], {
    'eggs',
    'mayo',
})

TICKERS = INDICES | SYMBOLS.keys() # type: Set[Ticker]
```

Using NewType instances as functions with a comprehension isn't too nicer either:
```python
_SYMBOLS = {
    'ham': '4a24ab25-766d-4d6c-99e2-337da6d0ba45',
    'spam': 'e8248888-b413-4def-b11a-763b10faf9c0',
}
SYMBOLS = {Ticker(ticker): SecurityID(id) for ticker, id in _SYMBOLS.items()}
del _SYMBOLS
```

It would be great if there were a safer cast function that would allow only literals that conform to the super type of types built from NewType.

```python
from typing import NewType, cast

Ticker = NewType('Ticker', str)
SecurityID = NewType('SecurityID', str)


SYMBOLS = newtype_literal(Dict[Ticker, SecurityID], {
    'ham': '4a24ab25-766d-4d6c-99e2-337da6d0ba45',
    'spam': 'e8248888-b413-4def-b11a-763b10faf9c0',
})

INDICES = newtype_literal(Set[Ticker], {
    'eggs',
    'mayo',
})

TICKERS = INDICES | SYMBOLS.keys() # type: Set[Ticker]
```

**Comment by JukkaL** [comment]
In an unrelated offline discussion I proposed a safe cast function that would only allow casting when the types are compatible at runtime. This could potentially be used to address this issue as an alternative to the more specific `new_type_literal` function:

```
INDICES = safe_cast(Set[Ticker], {  # ok, because Ticker objects are str instances at runtime
    'eggs',
    'mayo',
})
```

**Comment by graingert** [comment]
@JukkaL but this would not need a runtime check.

**Comment by graingert** [comment]
The stuff you have here:
```
>>> import sqlalchemy as sa
>>> sa.create_engine('redshift+psycopg2://username@host.amazonaws.com:5439/database')
Engine(redshift+psycopg2://username@host.amazonaws.com:5439/database)
```

redact your password though

**Comment by JukkaL** [comment]
@graingert The implementation of `safe_cast` would just return the argument. There would be no runtime check, similar to a regular cast. However, something like `safe_cast(int, 'x')` would be rejected by mypy, since `str` is not compatible with `int` at runtime. 

I don't understand your second comment.

**Comment by graingert** [comment]
Ah that's cool. I like it. 

Ignore that second comment it was for another thread

**Comment by JukkaL** [comment]
The `safe_cast` proposal may still be viable but the original proposal seems too narrow in scope. Closing this issue; `safe_cast` can be discussed elsewhere.
