### ISSUE TITLE
mypy is not finding classes defined in stub files

### ISSUE THREAD

**Issue by Svalorzen** [python/mypy#2457]
I have a large project using CPython that I'm trying to document with mypy. I'm heavily using stubs to prevent mypy from going around and importing tons of stuff that it's not ready to parse yet, and also to provide it with the interfaces with classes from CPython.

However, mypy seems to not be able to find classes which I have defined in a stub file. In particular, these classes are in a package called `db`. I have set my `MYPYPATH` to a specific folder where I'm storing all of my `.pyi` files, which contains a `db` folder, complete with `__init__.pyi` file.

If I write my stub classes directly into the `__init__.pyi`, the rest of the project seems to be able to find them. If, however, I write them into an auxiliary `_db.pyi` file (which should mirror the CPython module I'm documenting) and then inside the `__init__.pyi` file I do

    from __future__ import absolute_import

    from ._db import *
    # Other imports for other types that directly reference real project files. These seem to work.

Launching mypy with the `-v` option shows that my stub file is correctely parsed, although it is mentioned as `inherently stale` together with a bunch of others - I couldn't figure out what this means.

Unfortunately I was not able to create a small example reproducing the problem. I've tried researching exactly how the import process for mypy differs from the python one but I haven't found anything that seems to be connected with my problem.

If there's anything you think I can do in order to provide more information please let me know and I'll try my best to comply. Thanks in advance for your help.

**Comment by gvanrossum** [comment]
I expect this is because, *in stub files only*, imported items are not automatically considered exported. The reason for this is that stubs often just import other modules to use their classes as types, and those should not be exported.

To work around this you can use "from X import Y as Y" -- that is a signal that you meant Y to be exported. So in your case you will have to write "from ._db import A as A, B as B, ..." where A, B, ... are the classes.

**Comment by Svalorzen** [comment]
This works, thanks a lot!
