### ISSUE TITLE
Type check failed when returning with an inline if statement

### ISSUE THREAD

**Issue by CL-Jeremy** [python/mypy#2470]
Sorry if this has been brought up somewhere before, or I have overlooked some guidelines before posting this: I cannot manage to cope with typing when the value is contained in an **inline if statement** (what I think of as a ternary operator). I'm not sure if the case is limited to user-defined types or object types (I assume the built-in ones are not affected, but I have not yet tested) in general.

Consider the following code:
```python
def time_exec(f: Callable[[X], Y], *args: X) -> Tuple[Y, float]:
    start = time.time()
    res = f(*args)
    end = time.time()
    return res, end - start

def test_impls(
    f1: Callable[[X], Y],
    f2: Callable[[X], Y],
    *input: X
    ) -> Union[bool,Callable[[X], Y]]:

    # The following code raises this error message:
    # 'Incompatible return value type (got "object", expected "Union[bool, Callable[[X], Y]]")'
    return sorted({
        time_exec(f1, *input)[1]: f1,
        time_exec(f2, *input)[1]: f2,
        }.items())[0][1] if f1(*input) == f2(*input) else False
```
But once rewritten in block code it gets pass the type check just fine:
```python
def test_impls_block(
    f1: Callable[[X], Y],
    f2: Callable[[X], Y],
    *input: X
    ) -> Union[bool,Callable[[X], Y]]:

    # logically equivalent to the above variant
    dic = {
        time_exec(f1, *input)[1]: f1,
        time_exec(f2, *input)[1]: f2,
        }
    if f1(*input) == f2(*input):
        if list(dic)[0] <= list(dic)[1]:
            return f1
        else:
            return f2
    else:
        return False
```
I'm very new to the Python language and am generally little experienced in programming. Please kindly point out if I have missed something obvious. Thanks in advance.

**Comment by rwbarton** [comment]
Looks like this is because we don't take the context of a conditional expression into account, and just return the join of the two branches' types. I think there is another issue about this already.

**Comment by elazarg** [comment]
#622
