### ISSUE TITLE
Unicode module docstring in Python 2

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#2471]
In Python 2, docstrings are str by default, but unicode docstrings generally work. However, mypy disallows them:

```
$ cat unicodedoc.py 
from __future__ import unicode_literals
__doc__ = "documentation"
$ python3 -m mypy --python-version 2.7 unicodedoc.py 
unicodedoc.py:2: error: Incompatible types in assignment (expression has type "unicode", variable has type "str")
```

This makes it harder to prepare a codebase for 2/3 compatibility with the future import for unicode_literals.

It looks like this behavior is hardcoded at https://github.com/python/mypy/blob/8c6ba06add03487f62ccc0a5bb188c43e6ca5a4f/mypy/nodes.py#L78. I can prepare a patch if people agree that a change is needed.

**Comment by JukkaL** [comment]
Yeah, this looks like a mypy bug. We'd be happy to receive a PR -- this should be pretty easy to fix.
