### ISSUE TITLE
Unsupported format character 'b'

### ISSUE THREAD

**Issue by canassa** [python/mypy#2472]
Hello,

I have the following python code:

```python
a = b'%b' % b'123'
assert a == b'123'
```

Running mypy on it returns the following error:

```
teste.py:3: error: Unsupported format character 'b'
```

Which I guess is not correct since 'b' is a valid format for bytes:

https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting

This is my mypy.ini file:

```
[mypy]
python_version = 3.5
fast_parser = True
```

Currently using mypy 0.4.5

**Comment by JukkaL** [comment]
This is a mypy bug, and it's still present in 0.4.6.
