### ISSUE TITLE
Cannot use `classmethod` as a base class

### ISSUE THREAD

**Issue by Naddiseo** [python/mypy#2473]
I'm not 100% sure this is a bug, but, currently, `classmethod` cannot be used as a base class. There is a real-world [use case in Django](https://github.com/django/django/blob/1.10.3/django/utils/decorators.py#L13-L17) which will give output similar to the following:

> stubs/django/utils/decorators.pyi:9: error: Invalid type "builtins.classmethod"
stubs/django/utils/decorators.pyi:9: error: Invalid base class

Is there a better way for create a stub for that particular class?

**Comment by JukkaL** [comment]
Mypy treats `classmethod` as a special construct and thus it's pretty restricted what you can do with it. I'd suggest using aliasing (`classonlymethod = classmethod`) instead in a stub.

**Comment by hauntsaninja** [comment]
This no longer seems to be the case
