### ISSUE TITLE
Warn no return doesn't understand six.reraise

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2474]
As far as I can tell, mypy doesn't currently have any special knowledge of `six`, so it doesn't understand that `six.reraise` raises an exception.  If mypy having special understanding of six seems reasonable, we should add this.

**Comment by ddfisher** [comment]
Mypy also needs to be taught about other standard library functions which don't return, like `sys.exit`.

**Comment by JukkaL** [comment]
Marking this as high priority this seems to be a blocker for enabling `--warn-no-return` by default, which we'd like to do.

**Comment by ddfisher** [comment]
Planning on doing this after finishing up the fast parser default work.
