### ISSUE TITLE
"parse error" with PEP 448 unpacking

### ISSUE THREAD

**Issue by qdbp** [python/mypy#2478]
The following valid code gives a "parse error":

test.py:
`print({*{1, 2, 3}})`
`print({**{0: 'a', 1: 'b'}})`

when run as `mypy --python-version 3.5 test.py`:

`test2.py:1: error: Parse error before *`
`test2.py:3: error: Parse error before **`

This is supported syntax under [PEP 448](https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-448)

**Comment by kirbyfan64** [comment]
Try with `--fast-parser`.

**Comment by qdbp** [comment]
There is no error with --fast-parser.

**Comment by JukkaL** [comment]
Created #2479 to track the issue about lack of documentation on when `--fast-parser` is needed.
