### ISSUE TITLE
mypy internal error : Name '__builtins__' is not defined

### ISSUE THREAD

**Issue by snakescott** [python/mypy#2480]
mypy 0.4.6

$PATH/$FILENAME: error: Name '__builtins__' is not defined
$PATH/$FILENAME: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
Dropping into pdb
> /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/checker.py(2303)lookup_qualified()
-> n = self.modules[parts[0]]
(Pdb) bt
  /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/checker.py(243)accept()
-> typ = node.accept(self)
  /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/nodes.py(532)accept()
-> return visitor.visit_func_def(self)
  /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/checker.py(455)visit_func_def()
-> self.check_func_item(defn, name=defn.name())
  /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/checker.py(514)check_func_item()
-> typ = self.function_type(defn)
  /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/checker.py(2374)function_type()
-> return function_type(func, self.named_type('builtins.function'))
  /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/checker.py(2236)named_type()
-> sym = self.lookup_qualified(name)
> /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/checker.py(2303)lookup_qualified()
-> n = self.modules[parts[0]]

**Comment by gvanrossum** [comment]
What platform? How did you install it?

**Comment by snakescott** [comment]
Sorry for not including this in my original report!

MacOS Sierra 10.21.1

(mypy3) $ python --version
Python 3.5.2 # installed from binary at https://www.python.org/downloads/

(mypy3)$ pip freeze
lxml==3.6.4
mypy-lang==0.4.6
typed-ast==0.6.1

**Comment by snakescott** [comment]
Possibly a --custom-typeshed-dir problem?

```
➜  code mkdir testcode
➜  code cd testcode
➜  testcode mkdir -p pod/keystone
➜  testcode touch pod/__init__.py
➜  testcode touch pod/keystone/__init__.py
➜  testcode touch pod/keystone/runner.py
```

```
➜  testcode time mypy --py2 -v -v -v --fast-parser -s --custom-typeshed-dir /home/jhscott/code/typeshed --show-traceback --pdb pod/keystone/runner.py
LOG:  Mypy version 0.4.6
LOG:  Parsing pod/keystone/runner.py (pod.keystone.runner)
LOG:  Loaded graph with 1 nodes
LOG:  Found 1 SCCs; largest has 1 nodes
TRACE: Priorities for pod.keystone.runner:
LOG:  Processing SCC singleton (pod.keystone.runner) as inherently stale
LOG:  No fresh SCCs left in queue
LOG:  Build finished in 0.022 seconds with 1 modules, 0 types, and 4 errors
pod/keystone/runner.py: error: Name '__builtins__' is not defined
mypy --py2 -v -v -v --fast-parser -s --custom-typeshed-dir  --show-traceback   0.28s user 0.05s system 44% cpu 0.745 total
```

```
➜  testcode time mypy --py2 -v -v -v --fast-parser -s  --custom-typeshed-dir /home/jhscott/code/typeshed --show-traceback pod/keystone/runner.py
LOG:  Mypy version 0.4.6
LOG:  Parsing pod/keystone/runner.py (pod.keystone.runner)
LOG:  Loaded graph with 1 nodes
LOG:  Found 1 SCCs; largest has 1 nodes
TRACE: Priorities for pod.keystone.runner:
LOG:  Processing SCC singleton (pod.keystone.runner) as inherently stale
LOG:  No fresh SCCs left in queue
LOG:  Build finished in 0.011 seconds with 1 modules, 0 types, and 4 errors
pod/keystone/runner.py: error: Name '__builtins__' is not defined
mypy --py2 -v -v -v --fast-parser -s --custom-typeshed-dir  --show-traceback   0.25s user 0.02s system 49% cpu 0.558 total
```

**Comment by snakescott** [comment]
:(

This was caused by pass a --custom-typeshed-dir which did not exist.

**Comment by gvanrossum** [comment]
Great "rubber ducky" debugging! :-)

But maybe we could test for the existence of a few key files in the
typeshed before accepting the flag...

--Guido (mobile)
