### ISSUE TITLE
Sanity-check typeshed before accepting it

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2483]
See https://github.com/python/mypy/issues/2480 -- the root cause there was a non-existing directory passed to `--custom-typeshed`. That option should probably check for the existence of at least `stdlib/{2,3}/builtins.pyi` (depending on the python version selected) before accepting the flag.

We could even do the same for the default typeshed as a safety against a poorly installed typeshed.

(Another thing would be to make these fatalities not look like crashes -- there's no useful info in the traceback except that some fundamental module doesn't have valid stub. This also occurs with the typing module and possibly a few others.)

**Comment by hauntsaninja** [comment]
We do have some checks, which this very old issue probably predates
