### ISSUE TITLE
py2 pytz.UTC issue with mypy 0.4.6

### ISSUE THREAD

**Issue by snakescott** [python/mypy#2484]
This could be a typeshed issue? Feel free to let me know if I should open issues like this there instead.

Code:
```
from datetime import datetime
from pytz import UTC

print datetime.utcnow().replace(tzinfo=UTC)
```

Invocaton:
```
/Users/jhscott/.virtualenvs/mypy3/bin/mypy --fast-parser --silent-imports  --py2 mypy_bug.py
mypy_bug.py:4: error: Argument 1 to "replace" of "datetime" has incompatible type "UTC"; expected "Union[tzinfo, bool]"
```

Environment
```
(mypy_foo)➜  mypy_foo /Users/jhscott/.virtualenvs/mypy3/bin/python -m pip freeze
lxml==3.6.4
mypy-lang==0.4.6
typed-ast==0.6.1
```

**Comment by JukkaL** [comment]
This looks like a typeshed issue. Can you reopen the issue there?

**Comment by snakescott** [comment]
Will do!

**Comment by snakescott** [comment]
https://github.com/python/typeshed/issues/710

**Comment by rowillia** [comment]
@JukkaL The types look correct on `UTC`.  AFAICT it correctly inherits from `tzinfo`

https://github.com/python/typeshed/blob/master/third_party/2and3/pytz/__init__.pyi#L14

**Comment by rowillia** [comment]
Oh nevermind..it is a typeshed issue.  I have a fix.
