### ISSUE TITLE
Rename WhileStmt => While etc.

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#249]
We could simplify code by renaming WhileStmt => While, AssignmentStmt => Assignment, etc. without making the code any less clear. However, IntExpr => Int may not be a wise change, since Int is ambiguous: it can mean a literal or a type. Perhaps rename IntExpr => IntLiteral so improve clarity.

**Comment by elazarg** [comment]
PR #2095 addresses the *Stmt part.

**Comment by JukkaL** [comment]
This would introduce too much code churn now. I'm marking this 'postponed' just in case the situation changes. It's possible that this won't ever be worth it, but perhaps this can be implemented together with some another big refactoring that will touch most of the related code anyway for whatever reason.

**Comment by JukkaL** [comment]
This doesn't seem worth it.
