### ISSUE TITLE
TypedDict syntax variant with keyword arguments

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2492]
Support defining typed dicts like this:

```
Point = TypedDict('Point', x=int, y=int)
```

**Comment by davidfstr** [comment]
FYI: I've started work on this.

**Comment by davidfstr** [comment]
> FYI: I've started work on this.

Needless to say life has gotten busy on my end and I'm not expecting to resume work on this task in a reasonable timeframe.

I do have a partial patch that I started several months ago, but it may not be so useful since it is based on a very old version of the tree.

**Comment by JukkaL** [comment]
It's less clear if this is a good idea now that we also have the convenient class-based syntax, and we are going to use a keyword argument to specify that a typed dict may have missing items (see discussion at #2632).

**Comment by ilevkivskyi** [comment]
Some people might prefer the functional form. Both forms have their pluses and minuses, see the recent discussion in https://github.com/python/typing/issues/427 and subsequent idea https://github.com/python/mypy/issues/3520

@gvanrossum What do you think?

**Comment by gvanrossum** [comment]
The functional form works in all Python versions.

**Comment by JukkaL** [comment]
This doesn't seem feasible now that we have the `total=<bool>` keyword argument to `TypedDict`. Also, TypedDict is officially supported in Python and we want to avoid mypy-specific extensions.
