### ISSUE TITLE
Union of different-length Tuple types should agree for corresponding items

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2509]
See https://github.com/python/typeshed/pull/721#discussion_r90098017. The issue is that after
```python
T = Union[Tuple[int, int], Tuple[int, int, str]]
def f() -> T: pass
a = f()
reveal_type(a[0])
reveal_type(a[2])
```
the item types are considered to be Any. A better approach would be to understand that a[0] is always an int while a[2] is invalid without some check (however we can't do isinstance() checks on tuple lengths so that's problematic).

**Comment by JukkaL** [comment]
We could support `len(x)` checks for tuple unions: #1178

**Comment by rwbarton** [comment]
I'm a little surprised this doesn't go through the path for a method call on a union. For example, this works fine:
```py
class A:
    def f(self) -> int: pass

class B:
    def f(self) -> int: pass

U = Union[A, B]
def g() -> U: pass

b = g()
reveal_type(b.f())   # Revealed type is 'builtins.int'
```
It might just take some code reorganization (translate the IndexExpr into a `__getitem__` method call, then handle `__getitem__` on tuples in `check_op`).
