### ISSUE TITLE
"Incompatible index" message could be more informative

### ISSUE THREAD

**Issue by jboning** [python/mypy#2515]
```
from typing import Dict

def f(d):
    # type: (Dict[str, str]) -> None
    d[1] = 'hello'
```
results in
```
incompatible_index.py: note: In function "f":
incompatible_index.py:5: error: Invalid index type "int" for "dict"
```
This error would be more helpful if it indicated the expected type as well--as is, it seems like it might be saying that dicts can't have ints as keys.

**Comment by gvanrossum** [comment]
Agreed!

**Comment by jboning** [comment]
I'm taking a swing at this, though I'm not very confident in my understanding of the context.

**Comment by jboning** [comment]
How about this for an error message:

```
Index has incompatible type "int"; expected type "str" when indexing into "dict"
```

I was tempted to remove the mention of the type because it's not very helpful in this case. But when the index type isn't generic, it's more useful: `expected type "int" when indexing into "list"`. For the generic case, it might be better if we could show the whole type (`expected type "str" when indexing into "Dict[str, str]"`), but I don't think that's easily available.

**Comment by jboning** [comment]
I'm not completely committed to this message format in #2518. The lvalue/rvalue bit especially might be overly verbose, though in unusual cases (like some of the tests) it can be illuminating.

**Comment by ambv** [comment]
Yeah, the lvalue/rvalue bit is wordy. No current error messages do it. I see what you're trying to do but this is tricky in general (there can be multiple indexations on the R side or indexations on both sides). This is why you should `--show-column-numbers`.

I'd prefer a simple extension of the old message:
```
Invalid index type "C" for "A", expected type "B"
```
This is almost twice as short.

**Comment by jboning** [comment]
For the lvalue/rvalue wording I was motivated by testOperatorAssignmentWithIndexLvalue2, to clarify the different errors for `ac[b] += c` and `ac[c] += c`. But I imagine it's exceedingly rare to require different types for `__getitem__` and `__setitem__`.
