### ISSUE TITLE
Module 'types' has no attribute 'TracebackType'

### ISSUE THREAD

**Issue by AndreaCrotti** [python/mypy#2525]
In a virtualenv using Python3.5, I simply did

   pip install mypy-lang

Which installed *mypy-lang==0.4.6*

on this version of Python:

   Python 3.5.2 (default, Nov  7 2016, 11:31:36) 
   [GCC 6.2.1 20160830] on linux

$ mypy somefile.py

    /path/to/virtualenv//lib/mypy/typeshed/stdlib/3/builtins.pyi:11: note: In module imported here,
    immutable.py:1: note: ... from here:
    /path/to/virtualenv//lib/mypy/typeshed/stdlib/3/sys.pyi:10: error: Module 'types' has no attribute 'TracebackType'
    immutable.py:1: note: In module imported here:
    /path/to/virtualenv//lib/mypy/typeshed/stdlib/3/builtins.pyi:10: error: Module 'types' has no attribute 'TracebackType'

which is very strange, since actually in the same virtualenv doing this

    python -c 'from types import TracebackType'

wokrs perfectly fine.
I looked for this error around but noone seems to have reported it.
Any ideas?
Thanks

**Comment by AndreaCrotti** [comment]
Argh, sorry for the noise, the problem was simply that I stupidly called my module types.py, which obviously conflicts.
The error is a bit confusing but well it's normal really

**Comment by lynn** [comment]
This just bit me, also… Maybe the error could be made smarter somehow?

**Comment by gvanrossum** [comment]
Maybe the module name could be augmented with the filename in such error messages.
