### ISSUE TITLE
Warn no return doesn't respect asserts with a message

### ISSUE THREAD

**Issue by FuegoFro** [python/mypy#2528]
Running mypy with `--warn-no-return` on the following code works fine (no warnings):
```python3
def foo() -> str:
    assert False
```
However if you run it on this code, it fails saying that the function is missing a return:
```
def foo() -> str:
    assert False, "Look at it fail"
```

**Comment by rwbarton** [comment]
It works with `--fast-parser`. IIRC the mypy parser parses this construction as a tuple:
```py
def foo() -> str:
    (assert False), "Look at it fail"
```

**Comment by gvanrossum** [comment]
Is that with or without `--fast-parser`?
@ddfisher Thoughts?

**Comment by ddfisher** [comment]
Reid is correct.

I think we're basically not fixing bugs in the old parser at this point.
