### ISSUE TITLE
Returning A[X] from a function of return type A[Union[X, Y]] is invalid

### ISSUE THREAD

**Issue by TRManderson** [python/mypy#2531]
```python
from typing import List, Union
def fn() -> List[Union[str, int]]:
    x = [1] # type: List[int]
    return x
```
```
test.py: note: In function "fn":
test.py:4: error: Incompatible return value type (got List[int], expected List[Union[str, int]])
```

This also happens when using `Dict` and a subclass of `Generic[T]`, so I have assumed it's a general problem (though it might not be).

**Comment by TRManderson** [comment]
After stepping through the code myself to solve this, I now understand that this is due to the argument types of things like Dict and List being invariant.

I guess this means I'm suggesting special-casing `subtypes.check_type_parameter` for `Union`, which might be a bit much. If someone who actually has contributed to mypy before thinks that's reasonable, I'll submit a PR.

**Comment by TRManderson** [comment]
`subtypes.check_type_parameter` is the wrong thing to change. I think this is specific to return types.

**Comment by TRManderson** [comment]
After thinking about this some more, I've realised that what I'm asking for is an implicit cast on return types that include unions. I don't think that's actually mathematically justifiable so I'm going to close this issue.

**Comment by rwbarton** [comment]
Indeed it would be unsound for the usual reason. `fn` could store `x` in a global variable `g` of type `List[int]` before returning it. Then the caller of `fn` receives `x` as a `List[Union[str, int]]` so it is justified in appending a `str` to `x`. But `g` is `x` and now a third function can remove an element from `g` expecting it to be an `int`, but it is the `str` that was just appended.

**Comment by TRManderson** [comment]
Mutability strikes again. Thanks :)
