### ISSUE TITLE
Passing variable after *args cause parse error

### ISSUE THREAD

**Issue by k-saka** [python/mypy#2532]
```python
def print_args(*args):
    print(args)

print_args(*[1, 2, 3], 1)
```

```
mypy-test.py:4: error: Parse error before numeric literal
```

**Comment by gvanrossum** [comment]
Sorry, this is fixed when you use the `--fast-parser` flag. We're working on making that the default; until then, you have to add it or else there will be a large number of syntactic corner cases that aren't handled correctly. (The problem with making it default is Windows support for http://github.com/dropbox/typed_ast, in case you are wondering what the hold-up is.)
