### ISSUE TITLE
Consider disabling the str->unicode promotion in PY2 (with a flag)

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2533]
This came up in https://github.com/python/typing/issues/208#issuecomment-265468263. The automatic promotion from str to unicode in PY2 mode makes it impossible to catch cases where a function requires unicode and passing it a str instance is always wrong.

Just disabling this promotion would probably cause a lot of noise (also because many stubs in typeshed depend on this behavior), so it needs to be a flag (at least initially). Ideally it would be a per-file flag, with the default behavior corresponding to the current behavior.

**Comment by JukkaL** [comment]
Some other things may be useful for this to work well. For example, maybe `Union[str, Text]` can sometimes still be compatible with `AnyStr` (there's a separate issue discussing this, I think).

**Comment by msullivan** [comment]
I tried this once and it produces a billion errors and Python 2 is EOL anyway
