### ISSUE TITLE
Making it easier to use unicode_literals

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2536]
Currently using `from __future__ import unicode_literals` in Python 2 is kind of painful with mypy. Here are some potential issues:

* Some typeshed stubs declare things to only accept `str` arguments, when in reality they also accept at least ascii-only `unicode` objects.
* Mypy might not accept the implicit `unicode` literals in every context where a literal has a syntactic role (outside normal expressions), and `b'foo'` literals won't work in Python 3. String literal type escaping is an example.

It's fair to argue that using `unicode_literals` is a bad idea, but it's not uncommon to encounter real-world code using that, so getting mypy to work with it might be at least somewhat important.

**Comment by ddfisher** [comment]
FWIW string literal type escaping has already been fixed: https://github.com/python/mypy/pull/2516

After that fix I did a quick grep of the codebase looking for other similar errors, and the only one I found is fixed in https://github.com/python/mypy/pull/2519.

**Comment by JukkaL** [comment]
This is still rejected by mypy when using `--py2 --fast-parser`:

```
from __future__ import unicode_literals

def f(x: 'int') -> int:   # invalid syntax
    return x + 1
```

**Comment by JukkaL** [comment]
This doesn't seem worth fixing any more, since Python 2 reached it's EoL and gradually the amount of code using `unicode_literals` is likely to decrease.
