### ISSUE TITLE
Mypy not properly distinguishing different versions of the same module name?

### ISSUE THREAD

**Issue by smontanaro** [python/mypy#2557]
I was naive to think I could just set my gaze on Pandas. That very quickly dragged me down the numpy rabbit hole. numpy/__init__.py does this:
```
from .core import *
from .lib import *
```
Both numpy/{core,lib}/__init__.py do this:
```
from .shape_base import *
```
This appears to cause some heartburn for mypy, which complains, "Name 'shape_base' already defined" on the "from .lib" import line. Note that the two versions of the shape_base module (one in numpy.core, the other in numpy.lib) are not the same module. Nor do either of them explicitly define a name called "shape_base". I'm starting to think that mypy isn't keeping its shape_bases properly separated.

**Comment by ambv** [comment]
Ha, to the contrary, Mypy just found a bug in NumPy. Looking at 1.11.2.

`core/__init__.py` imports `shape_base` on line 40. `lib/__init__.py` implicitly imports `shape_base` on line 12. Mypy complains that the star imports in `numpy/__init__.py` import `shape_base` twice, one shadowing the other module.

**Comment by smontanaro** [comment]
Thanks. I'll go ahead and file a bug report with the numpy folks and let them sort it out. Mind if I use your text?

**Comment by smontanaro** [comment]
Never mind. I just went ahead and referenced this issue.
