### ISSUE TITLE
Experiment with descriptors used by Django

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2564]
Try to write some minimal stubs that simulate how Django uses descriptors, and see if we can type check code using them. Depending on the results, we may want to add some test cases that reflect these use cases, or improve the descriptor implementation.

Follow-up to #2266.

**Comment by ilevkivskyi** [comment]
There are now decent stubs for Django (that use descriptors extensively), and there were no bug reports so far, so I think this can be closed.
