### ISSUE TITLE
Experiment with descriptors used by SQLAlchemy

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2565]
Similar to #2564 but for SQLAlchemy.

**Comment by ilevkivskyi** [comment]
I think this issue can be closed now. We played with descriptors for SQLAlchemy for some time and this resulted in several PRs polishing corner cases: overloaded descriptors, union descriptors, `__get__` vs `__getattr__`, descriptor assignment on class vs instance, etc. There may be some patterns needed for Django, but we have a separate issue for this.
