### ISSUE TITLE
Parse error when passing keyword arguments after forwarding **args

### ISSUE THREAD

**Issue by z33ky** [python/mypy#2580]
```
def spam(x, y): pass

def ok(**kwargs) -> None:
    spam(x=1, **kwargs)  # OK

def err(**kwargs) -> None:
    spam(**kwargs, x=1)  # error: Parse error before "x"
```

I wouldn't think the order matters. The Python interpreter does not have an issue with it.

With `--fast-parser` I get `error: "spam" gets multiple values for keyword argument "x"` instead. Should I open a separate issue for this?

**Comment by JukkaL** [comment]
We won't fix any parser issues that can be worked around by using `--fast-parser`, since we hope to make that the default soon. The other problem may be new -- please go ahead and create a new issue for it.
