### ISSUE TITLE
"__getattribute__" undefined in superclass

### ISSUE THREAD

**Issue by z33ky** [python/mypy#2581]
```
class Foo():
    def __getattribute__(self, key) -> None:
        return super().__getattribute__(key)  # error: "__getattribute__" undefined in superclass
```

I guess this is caused by `object` not being modeled to have `__getattribute__`:
```
class Foo():
    def __getattribute__(self, key) -> None:
        return object.__getattribute__(self, key)  # error: "object" has no attribute "__getattribute__"
```

**Comment by gvanrossum** [comment]
Thanks for reporting this!

Can you file an issue (or better, a PR) for typeshed to add
`__getattribute__` to `object`?

We also need to special-case it in mypy (using similar rules as we use for
`__getattr__`), so this issue should remain open.

**Comment by gvanrossum** [comment]
Fixed by https://github.com/python/typeshed/pull/774.
