### ISSUE TITLE
Add --strict for opt-in to new features

### ISSUE THREAD

**Issue by alexjurkiewicz** [python/mypy#2585]
I have a codebase which is currently compatible with all the 'extra hard' checks:
`--strict-optional --warn-unused-ignores --warn-redundant-casts --check-untyped-defs --disallow-untyped-defs --disallow-untyped-calls`

I guess in future mypy will add future parameters like this, and I'd like our CI pipeline to automatically opt in to enabling them, so this functionality isn't missed.

Therefore, I'd like a `--strict` option which enables all the above options, and support for `--no-*` to disable specific options on a case-by-case basis if we find a new option isn't desirable.

Thanks!

**Comment by gvanrossum** [comment]
I don't think I'd want this for myself -- our CI would just break each time we were to upgrade mypy. But maybe someone who really wants this feature can submit a PR.
