### ISSUE TITLE
Mypy doesn't recognize objects implementing __iter__ as being Iterable

### ISSUE THREAD

**Issue by rowillia** [python/mypy#2598]
This might be in the category of issues around supporting protocol methods as a whole.

`test_iter.py`:
```python
from typing import Iterator

class Foo(object):
    def __iter__(self) -> Iterator[int]:
        yield 1
        yield 2

for x in Foo():
    print(x)
```

```
$ mypy test_iter.py
test_iter.py:8: error: Iterable expected
```

**Comment by afrieder** [comment]
This happens because Iterable is a distinct class, not an interface. To indicate to Python/Mypy that `Foo` is Iterable, you have to directly subclass `Iterable`:

```python
from typing import Iterator, Iterable

class Foo(Iterable):
    ....
```

then the rest of your code correctly type-checks.

**Comment by gvanrossum** [comment]
True, but we would all wish that it could work. https://github.com/python/typing/issues/11

I don't think we need to keep this open as a separate issue though.
