### ISSUE TITLE
Request: add man page

### ISSUE THREAD

**Issue by Alok** [python/mypy#2599]
[help2man](https://www.gnu.org/software/help2man/) makes this relatively painless, as I just got an OK man page by running:

```
help2man mypy > ~/tmp/man
man ~/tmp/man
```

**Comment by gvanrossum** [comment]
I'm not excited about this. You can just type `mypy --help`. We'd have to introduce an extra build/release step to update the man page, we'd have to add rules to setup.py to install the produced man page, and what would you do on platforms that don't use man pages?
