### ISSUE TITLE
Require annotation for variable initialized with ()

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2600]
I was just looking code that initializes a class variable with `()`. Example:

```
class A:
    x = ()
```

The type inferred for `x` is `Tuple[()]`. However, let's look at a derived class:

```
class B(A):
    x = (1, 2, 3)   # ouch, not compatible (once #2510 lands)
```

Probably the intended type for `x` was `Tuple[int, ...]` or perhaps `Sequence[int]`. Actually, it seems unlikely that a class variable would have type `Tuple[()]` by design, so maybe mypy should require an annotation for `x` in `A`, similar to how it already does it if the initializer is an empty list `[]`.

**Comment by gvanrossum** [comment]
Honestly I think this is debatable. The examples I've seen around this started out with non-empty tuples.

**Comment by ddfisher** [comment]
I'm somewhat against this.  I think the type error is understandable enough, and I think in general there should be a high bar to special-casing things.

**Comment by JukkaL** [comment]
Closing as there isn't really a good justification to special case this.
