### ISSUE TITLE
Multi-line Python 2 variable comments

### ISSUE THREAD

**Issue by smontanaro** [python/mypy#2601]
I see documentation about formatting multi-line function signatures for Python 2 code, but nothing about multi-line variable annotations. Is this possible? I have a variable which is a list of five-element tuples. The type annotation comment exceeds column 130. I'd like to rein that back in a bit.

**Comment by JukkaL** [comment]
PEP 484 doesn't support multi-line variable annotations. Often you can use type aliases to simplify annotations. Simple example:
```
Alias = Dict[VeryLongTypeName, Tuple[AnotherVeryLongName, YetAnother]]
long_variable_name = a_function_with_a_long_name(arguments)  # type: Optional[Alias]

```

**Comment by gvanrossum** [comment]
Closing this, we won't be doing anything about this. (Though maybe someone will want to submit a patch to doc/source/cheat_sheet.rst to add an example of a type alias?)
