### ISSUE TITLE
TypedDict doesn't respect subtypes or promoted types.

### ISSUE THREAD

**Issue by rowillia** [python/mypy#2610]
Repro:

test_typed_dict_return_value.py
```python
from mypy_extensions import TypedDict

TaggedPoint = TypedDict('TaggedPoint', {'type': str, 'x': float, 'y': float})

def create_tagged_point():
    # type: () -> TaggedPoint
    return TaggedPoint(type='2d', x=42, y=1337)
```

```bash
$ mypy test_typed_dict_return_value.py
test_typed_dict_return_value.py:9: error: Incompatible return value type (got "TypedDict(type=str, x=int, y=int)", expected "TaggedPoint")
```

As an aside, the error message above is fairly hard to decode.  It took me a few hours to realize what was going on.

The problem also exists with `Any` types:

```python
from mypy_extensions import TypedDict

TaggedPoint = TypedDict('TaggedPoint', {'type': str, 'x': int, 'y': int})

def create_tagged_point(some_value):
    # type: (Any) -> TaggedPoint
    return TaggedPoint(type=some_value.type, x=some_value.x, y=some_value.y)
```

**Comment by gvanrossum** [comment]
It took me some time to understand the bug report too... It seems that the failure (with `--py2` only) is due to `str` not being an exact match for `Text`?

(I wouldn't call that duck typing (mypy makes special allowances for `str` -> `Text` and `int` -> `float` called "type promotions"), so the subject didn't help me.)

**Comment by rowillia** [comment]
@gvanrossum Sorry for the obtuse bug report...it took me a bit to figure out what was going on.  I changed the example to not rely on the `--py2` flag.  The core of the issue is `SubtypeVisitor.visit_typeddict_type` was checking for type equivalence rather than a subtype - https://github.com/python/mypy/blob/master/mypy/subtypes.py#L214.  I have a PR that fixes this - https://github.com/python/mypy/pull/2621

**Comment by JukkaL** [comment]
https://github.com/python/mypy/pull/2621#issuecomment-270125052 describes an alternative way to fix this.
