### ISSUE TITLE
Add support for PEP 525 -- Asynchronous Generators

### ISSUE THREAD

**Issue by dbrattli** [python/mypy#2616]
Mypy (0.4.6) gives error: 'yield' in async function, even when specifying Python version as 3.6.

**Comment by ambv** [comment]
I can confirm this is a problem with master, too, ran with `--fast-parser --python=3.6`.

**Comment by JelleZijlstra** [comment]
I submitted pull requests to typing, typeshed, and CPython for some of the supporting infrastructure (https://github.com/python/typing/pull/346, https://github.com/python/typeshed/pull/815, http://bugs.python.org/issue29198) and I started working on implementing this in mypy, but it may take a little while longer for me to finish the patch.

**Comment by brettcannon** [comment]
Due to this not making it into 0.501, it might be good to weaken the wording on the "supports Python 3.6 features by default" on the site as I read that to mean **all** features instead of **some** features.
