### ISSUE TITLE
Mypy complains about os.environ in string formatting

### ISSUE THREAD

**Issue by smontanaro** [python/mypy#2639]
This kind of construct:

`"some silly string %(USER)s more silliness" % os.environ
`

provokes and error from mypy: 

`Format requires a mapping (expression has type "_Environ", expected type for mapping is Dict[Any, Any])
`

Should this usage really be flagged?

**Comment by JukkaL** [comment]
Requiring a `dict` instance for `%` seems unnecessarily restrictive.

From @dmoisset on gitter:

> for % formatting, it probably should be Mapping[str, Any]

It looks like `Mapping[unicode, Any]` and `Mapping[str, Any]` should both be accepted in Python 2 mode.

**Comment by smontanaro** [comment]
I should probably have mentioned, I live in a mostly Python 2 world...
