### ISSUE TITLE
Mypy can't find `collections.abc.Iterable`

### ISSUE THREAD

**Issue by lamenezes** [python/mypy#2641]
I've implemented something like the following code, but mypy checks returns the error in the title

```python
from collections import abc


class Foo(abc.Iterable, abc.Container):
    pass
```

The complete error output is:
```
example.py:4: error: Name 'abc.Iterable' is not defined
```

It seems mypy checks aren't considering the `collections.abc` module. Since `collections.Container` is found, but not `collections.abc.Iterable`.

Is this really an issue or am I missing something?

**Comment by gvanrossum** [comment]
This looks like something is missing from the https://github.com/python/typeshed/issues. Can you file a bug there?
