### ISSUE TITLE
Add size labels

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2644]
I am going to add labels to indicate the size of issues:
- size-large
- size-medium
- size-small

Again, I don't want more than three bins so that we don't agonize over size too much. Size can be an indication of the sheer amount of code that has to be (re)written, or the complexity of the problem, or even the amount of discussion that we have to have before deciding.

I'm not going to add size labels to existing issues, but I want to make that part of the new and improved triage process.

**Comment by ambv** [comment]
How about:
![size colors](https://dl.dropboxusercontent.com/u/4830253/size-colors.png)

small - #f8f8f8
medium - #c0c0c0
large - #404040

**Comment by gvanrossum** [comment]
Done, thanks!
