### ISSUE TITLE
Rename topic labels to topic-xxx-yyy

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2646]
Currently we use a variety of naming styles, e.g. "Import Cycle", "TypeVar", "namedtuple", "affects/strict-optional".

**Comment by gvanrossum** [comment]
Note that the following are *categories* not topics and will stay unchanged:

- bug (141 open, 341 closed) — a reproducible non-crash bug
- crash (7 open, 28 closed) — a reproducible bug causing a traceback
- documentation (22 open, 27 closed) — not a bug, nor a feature, but users need help
- feature (128 open, 270 closed) — not a bug; desired behavior change
- question (1 open, 18 closed) — often user thinks this is a bug
- refactoring (13 open, 33 closed) — not a bug; no behavior change

**Comment by gvanrossum** [comment]
Done.

What to do with "needs discussion" and "needs pep change"? The former is orthogonal to everything else, implying that the fate of the issue isn't decided yet. The latter is typically for something that should be kicked back to the typing repo first.

**Comment by ambv** [comment]
"needs discussion" can be left alone, it's most similar to "question". "needs pep change" is really "topic-depends-on-pep-change".
