### ISSUE TITLE
Make testCoberturaParser in cmdline.test work on Windows, or skip just this test

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2663]
When you run cmdline.test on Windows you get an error on testCoberturaParser.

- When lxml is *not* installed this [fails](https://ci.appveyor.com/project/gvanrossum/mypy/build/1.0.3/job/myna90p2o9vsj5xi) to find the expected output because this test is for the `--cobertura-xml-report` option which requires lxml, and such options are silently ignored when lxml is not installed.
- When lxml *is* installed this [fails](https://gist.github.com/ethanhs/db3617403e464781682dd18b97470e7e) because the expected output contains some UNIX-specific filenames.

We currently deal with this by skipping all "cmdline" tests in our Windows appveyor.yml, but that's sub-optimal because it means that the command line flags are not tested at all there.

We can either delete the test (but then the feature will probably rot without anyone noticing), or move it to a separate category that is skipped on Windows only (which is more work).

**Comment by alexandrul** [comment]
If it's ok to use some kind of a flag to signal that the test suite is executed under windows, it could be as easy as replacing `\` with `/` for the relative file path in `CoberturaXmlReporter.on_file`

**Comment by gvanrossum** [comment]
Detecting Windows is easy enough (`sys.platform == "win32"`). It's perhaps a little bit weird to normalize paths to using forward / on Windows, but all in all I think it's a reasonable compromise, so let's give it a try.

**Comment by alexandrul** [comment]
True, but I don't see a reason to use linux path sep under windows for usual operations.
I would make this change only for the tests, to keep the expected output unchanged.
 
How can I detect that the code is called as part of the tests?

**Comment by gvanrossum** [comment]
Heh, I see. That's problematic, perhaps we should change the test suite to
allow changing paths in expected/actual output? That's being done already
for paths in error output.

--Guido (mobile)

**Comment by alexandrul** [comment]
I've got it working. I have opened https://github.com/python/mypy/pull/2814 for adding lxml on AppVeyor (and running the reports tests), next step would be the PR for this fix.

**Comment by alexandrul** [comment]
Just opened https://github.com/python/mypy/pull/2815
