### ISSUE TITLE
NamedTuple subclass with default arguments doesn't type check

### ISSUE THREAD

**Issue by graingert** [python/mypy#2683]
```python
from typing import NamedTuple

Unit = str
Factor = str

_Spec = NamedTuple(
        '_Spec',
    [('unit', Unit), ('factor', Factor), ('source', str)],
)


class Spec(_Spec):
    def __new__(cls, unit, factor, source='derived'):
        return super().__new__(cls, unit, factor, source)


def foo() -> Spec:
    return Spec('ham', 'spam')
```

but this gets:
spec.py: note: In function "foo":
spec.py:18: error: Too few arguments for "Spec"

**Comment by elazarg** [comment]
I will see if this can be changed. At first glance it seems to be nontrivial.

(Personally I would prefer defining `Spec` as a namedtuple and use a `make_spec` function).

**Comment by elazarg** [comment]
The example is missing a `return` inside `__new__`

**Comment by graingert** [comment]
@elazarg still fails in the same way

**Comment by elazarg** [comment]
Perhaps we can improve the lookup in [checkmember,py#L443](https://github.com/python/mypy/blob/master/mypy/checkmember.py#L443) - look up for `__new__` first or otherwise mimic the runtime lookup.

**Comment by ilevkivskyi** [comment]
This now works correctly on master.
