### ISSUE TITLE
Flaw with type aliases containing type variables

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2690]
Reported by @mohabusama on [gitter](reveal_type) -- short version:
```python
from typing import *
T = TypeVar('T', List[int], Dict)
Processor = Callable[[T], None]
def output2(inp: T, processor: Processor) -> T:
    processor(inp)
def process_dict(inp: Dict) -> None:
    print(inp.keys())
output2([1, 2, 3], process_dict)
```
There should be an error on the last line, but there isn't. Surrounding the line with `reveal_type()` shows that the inferred value for `T` is `List[int]`.

If we expand the type alias `Processor` inline in the signature of `output2()` we get the expected error:
```
__tmp__.py:8: error: Argument 2 to "output2" has incompatible type Callable[[Dict[Any, Any]], None]; expected Callable[[List[int]], None]
```
This feels like a flaw in @ilevkivskyi's https://github.com/python/mypy/pull/2378 (which added support for type aliases containing type variables).

**Comment by ilevkivskyi** [comment]
In don't think this is a flaw. The function ``output2`` should be annotated as:
```python
def output2(inp: T, processor: Processor[T]) -> T:
    ...
```
Then everything works as expected. Note that that it is ``Processor[T]``, not ``Processor``, because plain generic alias ``Processor`` is treated as ``Processor[Any]``.

We discussed this some time ago and everyone agreed that generic aliases should use the same rules as generic types. This is how it is now documented in PEP 484, for example:
```python
Vector = Iterable[Tuple[T, T]]

def inproduct(v: Vector[T]) -> T:
    return sum(x*y for x, y in v)
```
and also in mypy and typing docs. Note it is ``Vector[T]`` not ``Vector``. I still believe this is the right way to do it.

**Comment by gvanrossum** [comment]
You're right I had forgotten this. But it's a subtle point!

--Guido (mobile)

**Comment by roganov** [comment]
I was also hit by this issue once or twice. I think I would make sense to a have a flag that disables implicit `Any` and forces to 'instantiate' all generics.

**Comment by mohabusama** [comment]
@gvanrossum @ilevkivskyi Thanks for the swift responses and explanations. 

The assumption came from the constrained type variable, which I guess one would assume `Any` won't be applied implicitly in that case.

Do you think it is possible for `mypy` to produce a warning in that specific case?

**Comment by ilevkivskyi** [comment]
@mohabusama @roganov 
In principle it is possible to add ``--disable-implicit-any`` and there is probably no conceptual difficulty. However, this will require many small changes in many places. In any case, if you would like to see this feature/flag, then I would recommend opening a separate issue.

**Comment by mohabusama** [comment]
@ilevkivskyi @roganov I have created an issue
