### ISSUE TITLE
Mypy thinks __doc__ may be unicode even when it's a str

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2709]
This outputs `Union[str, unicode]`, though the type should probably be `str`:

```
"""foo"""
reveal_type(__doc__)
```

This causes problems if `__doc__` is passed as an argument to a function that doesn't accept `unicode`.

Marking this as high priority since this is a regression (introduced by #2701).

**Comment by JukkaL** [comment]
This only affects Python 2 mode.

In this case `unicode` is fine:

```
u"""fooo"""
reveal_Type(__doc__)
```

**Comment by gvanrossum** [comment]
Should we roll back #2701? Or maybe the fix is to always set the type of
`__doc__` to `unicode`?

**Comment by JelleZijlstra** [comment]
That would also cause issues if `__doc__` is passed to a function that only accepts str, right? I can redo the patch from #2701 later today to address this.

**Comment by gvanrossum** [comment]
But if you pass some random object's `__doc__` attribute to a function that only accepts `str` then you *do* have a problem, because that `__doc__` *could* be a `unicode` instance.

**Comment by kirbyfan64** [comment]
@gvanrossum Closed by accident?

**Comment by gvanrossum** [comment]
Sorry, didn't mean to close.

**Comment by gvanrossum** [comment]
FWIW I found a few places that pass a __doc__ to
argparse.ArgumentParser(description=__doc__) -- maybe the argparse stub
should use Text? (Someone should also double-check that that works at
runtime.)

**Comment by JukkaL** [comment]
A reasonable fix would be to use the type of the literal to determine the type of `__doc__` for each module, but for module objects in general the type could be `unicode`. `Union[str, unicode]` is currently worse than `unicode` since it mostly means the same, but mypy has a bunch of union-related bugs that won't be triggered by plain `unicode`.

I'm currently working on an update to the argparse stub.

**Comment by JelleZijlstra** [comment]
Yes, ArgumentParser works fine with a unicode description in 2.7.

I think the type for module objects in general should actually be Optional, since __doc__ is None for a module without a docstring. (In fact, CPython 2.7 lets you put whatever type you want in a module's __doc__, but I'm pretty sure mypy shouldn't accept that.)

**Comment by gvanrossum** [comment]
OK, now that argparse is fixed we should be able to move forward with using
`unicode` for the docstring type.

**Comment by hauntsaninja** [comment]
What is Python 2?
