### ISSUE TITLE
api.run() does not have a way to report mypy's set exit status

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2727]
The api.run() call catches SystemExit but does not record the status it conveys. The exit status cannot be deduced easily by parsing the stdout or stderr strings.

I propose to change the API to
```python
def run(params: str) -> Tuple[str, str, int]:
```
where the 3rd value is the exit status (0 for success, 1 for most errors, 2 for command line errors).

**Comment by gvanrossum** [comment]
@JdeH thoughts?

**Comment by geatec** [comment]
Adding the information contained in the SystemExit exception to the return value is a good idea in my view. In general any information spit out by mypy if it's started from the command line should be available when running it "in-process" via the API.

Only it's not clear to me how to distinguish between 1 and 2. From the Python 3.6 docs:

> _exception_ **SystemExit**
> This exception is raised by the sys.exit() function. It inherits from BaseException instead of Exception so that it is not accidentally caught by code that catches Exception. This allows the exception to properly propagate up and cause the interpreter to exit. When it is not handled, the Python interpreter exits; no stack traceback is printed. The constructor accepts the same optional argument passed to sys.exit(). If the value is an integer, it specifies the system exit status (passed to C’s exit() function); if it is None, the exit status is zero; if it has another type (such as a string), the object’s value is printed and the exit status is one.
> 
> A call to sys.exit() is translated into an exception so that clean-up handlers (finally clauses of try statements) can be executed, and so that a debugger can execute a script without running the risk of losing control. The os._exit() function can be used if it is absolutely positively necessary to exit immediately (for example, in the child process after a call to os.fork()).
> 
>**code**
>The exit status or error message that is passed to the constructor. (Defaults to None.)

So from the docs it would appear that `code` field of `SystemExit` can only assume the values zero (OK) and one (something special is up).  How can one tell the difference between:  1 for most errors, 2 for command line errors. Is there something in `SystemExit` that contains this info? Can the `code` field indeed contain the values 0, 1, or 2 (different from what the docs of Python3.6 suggest) with meaning as you indicate, or can the `code` field only be 0 or 1, and should the destinction beween returning 1 or 2 as third element of the returned list be made using other information. If so, how can I obtain that information from mypy.

Kind regards
Jacques

**Comment by JdeH** [comment]
Sorry, was logged in under my company account, but its just me...

**Comment by gvanrossum** [comment]
The `code` attribute of the `SystemExit` exception contains the integer
exit status, i.e. 0, 1, 2 etc. -- the text that confused you probably
referred to the special case where `code` is not an int, then the process
exit code will be 1 or 0.

**Comment by JdeH** [comment]
OK, that should be simple.
I'll adapt it together with issue #2728.
