### ISSUE TITLE
Support copy constructor for TypedDict

### ISSUE THREAD

**Issue by davidfstr** [python/mypy#2738]
It should be possible to copy a TypedDict via a copy constructor like:

```
point2 = Point(point1)
```

Currently this is rejected by the type checker.

---

It *may* also be desirable to support the following:

```
point2d = Point2D(point3d)
```

...although I'd have to think about whether this is actually typesafe and consistent.

---

**Suggested tags for this issue:** feature, topic-typed-dict

**Comment by JukkaL** [comment]
`point2d = Point2D(point3d)` should be okay since we have structural subtyping for typed dicts.

**Comment by 97littleleaf11** [comment]
Currently mypy would generate this error:
```
error: Expected keyword arguments, {...}, or dict(...) in TypedDict constructor
```

**Comment by 97littleleaf11** [comment]
`point2d = Point2D(point3d)` would copy every field of `point3d` during runtime. Let's just focus on the same typeddict first.

**Comment by 97littleleaf11** [comment]
I just checked the [PEP589](https://www.python.org/dev/peps/pep-0589/#id16), non-keyword arguments are not allowed when TypedDict is used as a callable object:
> It can be used as a callable object with keyword arguments corresponding to the TypedDict items. Non-keyword arguments are not allowed.
