### ISSUE TITLE
TypedDict syntax variant with dict(...) argument

### ISSUE THREAD

**Issue by davidfstr** [python/mypy#2739]
Support defining typed dicts like this:

```
Point = TypedDict('Point', dict(x=int, y=int))
```

---

The above syntax is similar to the syntax in #2492:

```
Point = TypedDict('Point', x=int, y=int)
```

Supporting this syntax for defining a TypedDict type is consistent with our existing support for a similar syntax for instantiating a TypedDict:

```
point = Point(dict(x=42, y=1337))
```

**Comment by davidfstr** [comment]
FYI: I've started work on this.

**Comment by davidfstr** [comment]
> FYI: I've started work on this.

Needless to say life has gotten busy on my end and I'm not expecting to resume work on this task in a reasonable timeframe.

**Comment by 97littleleaf11** [comment]
We wouldn't going to support this syntax and we encourage users to use the class-based syntax since it has been officially supported by Python.
