### ISSUE TITLE
Support declaring TypedDict type with class-based syntax (for Python 3.6+)

### ISSUE THREAD

**Issue by davidfstr** [python/mypy#2740]
* [ ] Support basic declaration:

```
class Point2D(TypedDict):
    x: int
    y: int
```

* [ ] Support class-based inheritance as syntactic sugar for copying fields

```
class Point3D(Point2D):
    z: int
```

There is already support for the above syntaxes at runtime but the typechecker doesn't reconcognize it yet.

**Comment by ilevkivskyi** [comment]
@davidfstr I wanted to work on this soon. Do you prefer to do it yourself?

**Comment by davidfstr** [comment]
@ilevkivskyi Go for it. Help is definitely welcome, as my coding time outside work is highly constrained.

In case it's of interest the next item I'm working on is #2472 and #2489 (together).

**Comment by ilevkivskyi** [comment]
@davidfstr Here is the PR https://github.com/python/mypy/pull/2808 I promised.

**Comment by jonmcoe** [comment]
is it possible to inherit in python2?
