### ISSUE TITLE
Parse error when metaclass argument is a function call

### ISSUE THREAD

**Issue by sjaensch** [python/mypy#2745]
Example with mypy 0.470:

````python
def return_metaclass():
    return type

class ExampleClass(metaclass=return_metaclass()):
    pass
````

Example error: `mypy_metaclass_test.py:5: error: Parse error before (`
I don't expect mypy to deduct type information, but it shouldn't abort with an error.

With the option `--fast-parser` I get the error `mypy_metaclass_test.py:5: error: Dynamic metaclass not supported for 'ExampleClass'`, which I can ignore with the `# type: ignore` annotation.

**Comment by gvanrossum** [comment]
Yeah, you need to use the fast parser for this to work. We're going to make it the default setting in the next release and probably soon after that we'll delete the old parser.
