### ISSUE TITLE
Typing override not reconized ?

### ISSUE THREAD

**Issue by buxx** [python/mypy#2746]
I don't know if it's a feature or not but, for following code (python 3.4):

```
class ObjInterface(object):
    def __init__(self) -> None:
        self.attrA = 1


class MyObj(ObjInterface):
    def __init__(self) -> None:
        super().__init__()
        self.attrB = 2


class A(object):
    def __init__(self, obj: ObjInterface) -> None:
        self.obj = obj


class B(A):
    def __init__(self, obj: MyObj) -> None:
        super().__init__(obj)
        print(self.obj.attrB)
```

`mypy` say: 

> ex.py:21: error: "ObjInterface" has no attribute "attrB"; maybe "attrA"?

although `obj`, in class B __init__ has been typed as `MyObj`. Feature, bug ? Need to be implemented ?

Thank's

**Comment by gvanrossum** [comment]
This is a feature. The static type of `self.obj` is still `ObjInterface`. You may wan to look into generics: http://mypy.readthedocs.io/en/latest/generics.html.

**Comment by buxx** [comment]
Thank's for reply !
