### ISSUE TITLE
Fast parser associates wrong column number with calls to member functions

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2749]
For example:
```python
class A:
    def f(self, x): # type: (int) -> str
        pass
A().f('') # E:0: Argument 1 to "f" of "A" has incompatible type "str"; expected "int"
```

**Comment by ddfisher** [comment]
I don't think this is going to be easily fixable.  Here's the ast for the expression `A().f('')`:

```
Expr(value=Call(
    func=Attribute(value=Call(func=Name(id='A', ctx=Load(), lineno=1, col_offset=0), args=[], keywords=[], lineno=1, col_offset=0),
                   attr='f', ctx=Load(), lineno=1, col_offset=0)
    , args=[Str(s='', lineno=1, col_offset=6)], keywords=[], lineno=1, col_offset=0),
    lineno=1, col_offset=0)]
```

Notice that all we know about `f` is that it's the string portion of an attribute lookup.  It doesn't have any annotations (in the Python AST sense, i.e. line or col numbers) itself, aside from what's associated with the attribute lookup as a whole.  Unfortunately, the column number associated with the attribute lookup is the first column of the _value_ (in this case, `A()`), which starts in the 0th column.

**Comment by gvanrossum** [comment]
So I'm guessing this would require an update to typed_ast. Oh well. Low priority is fine.

**Comment by ddfisher** [comment]
And what the fix would look like is not obvious (at least not to me), unfortunately.

**Comment by ilevkivskyi** [comment]
(Raising priority in view of planned editor integration.)

**Comment by AlexWaygood** [comment]
I'm closing this issue: it [doesn't appear to be an problem](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-column-numbers&gist=443a966b485c656edd8e60bee2f39224) when mypy is run on 3.8+, as mypy uses the stdlib `ast` module on these newer versions of Python.

It seems unlikely to me that `typed_ast` will be updated to fix this issue, given that it is only really useful on Python <=3.7.
