### ISSUE TITLE
Getting CompileError for dictionary unpacking

### ISSUE THREAD

**Issue by x27lu** [python/mypy#2752]
Hello, I noticed that I run into a CompileError when I use dictionary unpacking to build dictionaries without mutation, for example:

a = {1: 2}
b = {3: 4}
c = {**a, **b}

When I run mypy against a file with the above code, I get a CompileError that says “error: Parse error before **”

I am using Python 3.5 with mypy 0.470

**Comment by ddfisher** [comment]
Thanks for the bug report!  This is a bug with mypy's old parser, which is being replaced.  Mypy will use the new parser by default in the next release, but for now you can use it explicitly with `--fast-parser`.
