### ISSUE TITLE
Use a different error code on early exit

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2754]
When running mypy from a script, it's sometimes nice to know when mypy successfully completed a full typechecking run vs exited early due to blocking errors.  Perhaps mypy could exit with exit code `2` when exiting due to blocking errors?

**Comment by gvanrossum** [comment]
Good idea. Then it should also exit 2 if it can't open a file and for other "early stage" errors. (It already uses exit 2 for command line parsing errors.)

**Comment by ddfisher** [comment]
Maybe there should be 3 error exit codes?

1) Typechecking ran to completion and there are some type errors.
2) The code could not be analyzed at all because e.g. the command line flags don't parse or a file cannot be opened.  This should indicate a major configuration error.
3) There was some code analysis, but it could not be completed because of a parse error or early semantic analysis error.

**Comment by gvanrossum** [comment]
Maybe, but the problem is that there's no standard for codes other than 0,
1, 2. So perhaps this not such a good idea after all? What's the use case
for distinguishing blockers?

**Comment by gvanrossum** [comment]
Whoops, I searched for exit status but didn't find this issue. Sorry! Maybe it's time to increase priority?

**Comment by ddfisher** [comment]
If you think there's a current need for this, sure!

**Comment by gvanrossum** [comment]
Mostly that I wish to remove certain code from an internal mypy integration script (you know the one).

**Comment by gvanrossum** [comment]
Also, note that parse errors are implicitly treated as blocking errors.
