### ISSUE TITLE
TypedDict tests don't typecheck

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2755]
Many of the TypedDict tests in `mypy/test/testextensions.py` don't actually typecheck, even under 3.6 with the eval'd code placed properly in the codebase.  This likely indicates a problem with the tests, as the constructs used are intended to typecheck.  This is also the only remaining part of mypy that isn't fully typechecked.

**Comment by ddfisher** [comment]
@ilevkivskyi, would you mind taking a look at this at some point?

**Comment by ilevkivskyi** [comment]
Yes, I will try to fix this.

**Comment by ilevkivskyi** [comment]
This depends on https://github.com/python/typeshed/pull/990 and https://github.com/python/mypy/issues/2492. After these two will be fixed, this one should be easy.

**Comment by 97littleleaf11** [comment]
It seems that we don't have `mypy/test/testextensions.py` any more. Has this issue been fixed already? @ilevkivskyi

**Comment by ilevkivskyi** [comment]
Yes, I think this is not relevant anymore.
