### ISSUE TITLE
Unions misbehaving? (got "Token", expected "Union[int, Token]")

### ISSUE THREAD

**Issue by danr** [python/mypy#2757]
We try to assign a `Token` to something of type `Union[int, Token]` here:

    from typing import *

    class Token:
        pass

    def test() -> Union[int, Token]:
        return Token

Now I am puzzled why I get this error:

    generator.py:7:4: error: Incompatible return value type
        (got "Token", expected "Union[int, Token]")

**Comment by kirbyfan64** [comment]
The error *message* could use improvement, but the error itself is correct. You probably want to do:

```python
    return Token()
```

Instead, you're returning the class itself.

**Comment by danr** [comment]
Oh, silly me... Thank you!

But yes, the error message is confusing: the type of Token surely cannot be Token? If we have type-in-type, it should be `Type` (akin to Haskell's `*`).

Should I close this and file a new issue for the poor error message?

**Comment by gvanrossum** [comment]
Sounds good.
