### ISSUE TITLE
Incompatible types in assignment with --strict-optional for a: Callable[..., None] = lambda *a, **k: None

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2764]
This is a residue of https://github.com/python/mypy/pull/2634#issuecomment-271392350

This snippet causes an error when using `--strict-optional`:
```python
def f(a: Callable[..., None] = lambda *a, **k: None): pass
```
Error:
```
__tmp__.py:7: error: Incompatible types in assignment (expression has type Callable[[StarArg(Any), KwArg(Any)], None], variable has type Callable[..., None])
```
However this snippet is fine -- the only difference being that the return type is not `None`:
```python
def f(a: Callable[..., int] = lambda *a, **k: 0): pass
```
So @elazarg's claim "[it's not about the the parameters but about the return type](https://github.com/python/mypy/pull/2634#issuecomment-271436422)" is incorrect here.

And yes, this did break one place in our codebase. As a workaround I am putting `cast(Callable, ...)` around the `lambda` expression:
```python
def f(a: Callable[..., None] = cast(Callable, lambda *a, **k: None)): pass
```

**Comment by elazarg** [comment]
I am confused. This *is* about the return type, isn't it?

**Comment by elazarg** [comment]
Well you are probably right. It is the TODO comment for the case of ARG_STAR and ARG_STAR2 which is not handled as a context, and therefore falls back to the "no context" case, which does not handle the return type good enough for this case.

**Comment by gvanrossum** [comment]
Still not fixed, since @2770 was reverted.
