### ISSUE TITLE
Mypy crashes if there is no 'function' or 'module' in builtins

### ISSUE THREAD

**Issue by vlasovskikh** [python/mypy#2765]
You can use `types.FunctionType` instead of `builtins.function`. See the original crash in the CI results here python/typeshed#876.

**Comment by vlasovskikh** [comment]
The same applies to `module` and `types.ModuleType`.

**Comment by JukkaL** [comment]
The reason mypy has these fake definitions in builtins is to get tidier error messages. We could instead translate `types.FunctionType` to `function` when generating messages. `module` is similar.

**Comment by vlasovskikh** [comment]
Having `function` and `module` in builtins results in false negatives where a type checkers accepts `function` and `module` in the user code as built-ins.

**Comment by ilevkivskyi** [comment]
The module part of this issue is fixed by #3107

**Comment by vlasovskikh** [comment]
I believe `function` is no longer an issue as well, since it has been renamed to `__function`.

**Comment by ilevkivskyi** [comment]
@vlasovskikh `class function: ...` is still defined here https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi#L876, there are some function arguments that has ben renamed to `__function` few month ago.

So I think this is something still worth fixing. I would prefer to use `types.FunctionType` as a fallback for functions (or other `types` classes depending on kind of callable we deal with, like bound method, unbound method, etc.). There is however subtle question of what should be the fallback for user declared `Callable`, see e.g. a hot discussion in https://github.com/python/mypy/issues/5958

**Comment by JelleZijlstra** [comment]
This is essentially the same as #8240 (thanks Alex for pointing me to it)
