### ISSUE TITLE
release tarballs on GitHub missing typeshed submodule, 0.470 source package missing from PyPI

### ISSUE THREAD

**Issue by mr-c** [python/mypy#2769]
Hello,

```
pip download --no-binary :all: --no-deps mypy
```
only downloads the source package for version 0.256 (from the old mypy package)

and

```
pip download --no-binary :all: --no-deps mypy-lang
```
only downloads the source package for version 0.4.6

This made the latest release invisible to Debian via manual downloads or on our PyPI redirector http://pypi.debian.net/mypy

When switching to the GitHub release I failed to notice that the git submodule for the typeshed wasn't included: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852819

Can the source package for 0.470 be uploaded to PyPI and/or the GitHub release tarball be updated? It doesn't make sense to offer them without the submodules included.

Thanks!

**Comment by JukkaL** [comment]
@gvanrossum Should we release PyPI source packages for future releases? Installing 0.256 is particularly troublesome. I assume that uploading source packages would be fairly simple?

**Comment by gvanrossum** [comment]
Sorry, I have absolutely no understanding of what those `pip` flags mean or
how pip decides which file to download and what to do with it. It's a black
box to me. Is a source pacakge whatever gets produced by `setup.py sdist`?
That should be easy to add using twine, I suppose.

**Comment by mr-c** [comment]
Hey @gvanrossum , yep the `setup.py sdist` output needs uploading :-)

**Comment by gvanrossum** [comment]
OK, I've done that now. Let me know if there is more to be done.

**Comment by mr-c** [comment]
@gvanrossum confirmed. Is this now part of the release process?

**Comment by gvanrossum** [comment]
Hm, we really need to write down the steps for the release process in a file contained in the project.

**Comment by mr-c** [comment]
@gvanrossum I take it back, looks like the uploaded source package was made from an checkout of `mypy` without the submodules -- so the `typeshed` directory is still missing which puts us back with the same problem I started :-P

**Comment by gvanrossum** [comment]
No, I did a clean checkout followed by `git submodule init` and `git submodule update`, then I ran `python3 setup.py dist`.

I don't recall changing any of that. Does mypy-lang 0.4.6 have the same problem?

**Comment by gvanrossum** [comment]
The big change to setup.py was switching from default distutils to setuptools. Maybe the change is a side-effect from that? I've verified that the global variable `data_files` is filled with the typeshed files, but somehow it is being ignored by setup()...

**Comment by ambv** [comment]
Guido, I cannot reproduce your problem neither on master nor on the v0.470 tag. The distribution I am producing does contain everything, checked by unpacking the .tar.gz in `dist/` (see [here for my output](https://gist.github.com/ambv/24506f208dbdc3d374cd2ca6c930c0ec)).

Sadly, we cannot re-upload the .tar.gz for this version so I deleted the broken one and re-uploaded z .zip file instead (for some reason .tar.bz2 and .tar.xz are no longer allowed, possibly @dstufft knows why).

I can confirm this installs a working mypy from the .zip by doing this:
```
$ pip install --no-binary :all: mypy
```

**Comment by mr-c** [comment]
Thank you @ambv and @gvanrossum for working on this. I can also confirm that the typeshed is now present in the source package.

**Comment by gvanrossum** [comment]
Thanks Lukasz. What a strange mystery. I suppose there might be different
versions of setuptools or Python be involved? I will try to experiment.

**Comment by dstufft** [comment]
@ambv See [PEP 527](https://www.python.org/dev/peps/pep-0527/).

**Comment by gvanrossum** [comment]
I think I have a clue. I ran `pip3 install -U setuptools` and it gave this output:
```
Collecting setuptools
  Using cached setuptools-34.1.0-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools)
  Using cached packaging-16.8-py2.py3-none-any.whl
Requirement already up-to-date: six>=1.6.0 in /Users/guido/v36/lib/python3.6/site-packages (from setuptools)
Collecting appdirs>=1.4.0 (from setuptools)
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools)
  Using cached pyparsing-2.1.10-py2.py3-none-any.whl
Installing collected packages: pyparsing, packaging, appdirs, setuptools
  Found existing installation: setuptools 29.0.1
    Uninstalling setuptools-29.0.1:
      Successfully uninstalled setuptools-29.0.1
Successfully installed appdirs-1.4.0 packaging-16.8 pyparsing-2.1.10 setuptools-34.1.0
```
After that, `python3 setup.py sdist` constructed a .tar.tg file containing typeshed/, runtests.py, test-data/, and mypy/test/. So I blame everything on an old version (29.0.1) of setuptools, or perhaps appdirs or packaging.

Gosh I hate dealing with this ecosystem.
