### ISSUE TITLE
Functions with same signature but different parameter names.

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/mypy#2777]
```python
def is_prime(n):
    # type: (int) -> bool
    return all(n % p != 0 for p in range(2, n))

def is_palindrome(m):
    # type: (int) -> bool
    return str(m) == ''.join(reversed(str(m)))

list1 = [is_prime, is_palindrome]
list2 = [is_prime, is_prime]

reveal_type(list1)
reveal_type(list2)
```

In this code, `is_prime` and `is_palindrome` have the same signature `def (builtins.int) -> builtins.bool` but different parameter names.

These are the revealed types:

* `list1`: `builtins.list[builtins.function*]`
* `list2`: `builtins.list[def (n: builtins.int) -> builtins.bool]`

I think the type of `list1` should have been `builtins.list[def (builtins.int) -> builtins.bool]`.

**Comment by sharmaeklavya2** [comment]
This behaviour was not present in mypy 0.4.6. In mypy 0.4.6, revealed type of `list1` was `builtins.list[def (m: builtins.int) -> builtins.bool]`, which was wrong.

**Comment by JukkaL** [comment]
This is a side effect of recent changes to callable types. The previous behavior was better for this example. In technical terms, mypy should be more clever about joins of callable types in general.

A simple workaround is to give `list1` an explicit annotation:

```
...
list1 = [is_prime, is_palindrome]  # type: List[Callable[[int], bool]]
```
