### ISSUE TITLE
Return type incompatible with supertype error should specify the types involved

### ISSUE THREAD

**Issue by joshuawarner32** [python/mypy#2797]
I'm a relatively new user to mypy, and I have a quick bit of feedback / suggestion:

(Tangentially related to #2783 and/or #2782)

I see this error message:

```
error: Return type of "__iter__" incompatible with supertype "Iterable"
```

It would be really helpful if the message specified what the return type is, and more helpfully, what mypy thinks it should be.

This is particularly helpful in the context of generic/templated types like `Iterable`, where reading the definition of the type doesn't immediately give you the answer.  In other words: "Oh no!  I have to think!" 😃

**Comment by joejuzl** [comment]
I would like to give this a go if that's ok.

**Comment by ilevkivskyi** [comment]
OK, great!
