### ISSUE TITLE
annotating type instance

### ISSUE THREAD

**Issue by tumb1er** [python/mypy#2799]
I'm trying to annotate simple class factory, but constantly getting "Invalid base class" error. Only annotating the result of `factory()` call with `Any` return type removes errors, but there is an interesting thing at line 26.
Revealed type for `class A` is a function that returns `A` instance, but you can't inherit from real function.
So, two questions:
* how to annotate `factory` to return something that is "valid base class"?
* may be mypy should distinguish `type` instance and class instance "constructor"?

```python
from typing import Any


class A:
    pass


def factory() -> Any:
    return A


base = factory()  # type: Any
# removing forced Any leads to invalid base class error

reveal_type(base)
# factory.py:15: error: Revealed type is 'Any'


class B(base):
    pass


var = A


reveal_type(var)
# factory.py:26: error: Revealed type is 'def () -> factory.A'


class C(var):
    pass
```

**Comment by ilevkivskyi** [comment]
Normally you would annotate a function that returns a class as
```python
def factory() -> Type[A]:
    return A

a = factory()() # a is correctly inferred to have type A
```
I think the problem is that mypy currently does not support expressions in base classes or other dynamic features see e.g. https://github.com/python/mypy/issues/1764

**Comment by tumb1er** [comment]
Found dynamic base classes in [unsupported features](https://github.com/python/mypy/wiki/Unsupported-Python-Features), so my questions are now about these features only. Without dynamic base classes, all annotations look reasonable.
