### ISSUE TITLE
How to insist that particular package and all symbols in it are well-typed?

### ISSUE THREAD

**Issue by gregory-nisbet** [python/mypy#2810]
I'm trying to add mypy annotations in `*.pyi` files to an existing flask application.

I've just gotten started, and don't have a `mypy.ini` config file or anything fancy.

To start off with I have a simple shell script that just invokes `mypy` and checks the `config.py`.

```
#!/bin/sh

check() {
    env MYPYPATH=/usr/local/lib/mypy /usr/local/bin/mypy --py2 "$@"
}

check config.py
```

Here's the first error I got.

`some_module/__init__.py:3: error: No library stub file for module 'flask'`

What's the preferred way to say that I trust a given module like `flask` and give the `flask` module objects the `Any` type annotation?

**Comment by kirbyfan64** [comment]
```python
import flask  # type: ignore
```

**Comment by ethanhs** [comment]
I'm pretty sure this can be closed :)

Between `# type: ignore`, `--ignore-missing-imports` and other options this can be handled.
