### ISSUE TITLE
Dynamic base classes

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2813]
Currently mypy isn't happy about dynamic base classes, even though these are not uncommon. Maybe mypy could do a better job.

Currently this works:

```py
base: Any = create_class()

class A(base): ...
```

However, these don't work:

```py
base2 = create_class()  # no annotation for base2 -> doesn't work
class B(base2): ...

class C(create_class()): ...  # function call as base class

base3: Type[A] = ...
class D(base3): ...
```

A plugin architecture (https://github.com/python/mypy/issues/1240) would help with commonly used libraries, but it wouldn't help with more ad-hoc uses of dynamic base classes.

**Comment by Danmou** [comment]
Another use-case for dynamic base classes is in class decorators. For example:
```python
from typing import ContextManager, Type

def decorator(cls: Type[ContextManager]) -> Type[ContextManager]:
    class Decorated(cls):
        pass
    return Decorated

@decorator
class TestClass(ContextManager):
    pass
```
This fails with:
```
test.py:4: error: Invalid type "cls"
test.py:4: error: Invalid base class
```

Even using a more generic annotation such as `Type` or `Any` doesn't work. The only workaround I've found to get rid of the error is:
```python
def decorator(cls: Type[ContextManager]) -> Type[ContextManager]:
    cls_: Any = cls
    class Decorated(cls_):
        pass
    return Decorated
```

**Comment by msullivan** [comment]
We've got a plugin system that supports this now and I doubt we'll do better
