### ISSUE TITLE
Metaclasses should inherit from type.

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#2818]
There is something missing in #2475: this code:
```python
class M:
    ...
class A(metaclass=M):
    ...
```
Passes without errors, but fails at runtime.

---------------------------------------------------
Btw, I have found two open issues that were fixed by #2475, I left comments referencing the #2475 in that issues.

**Comment by elazarg** [comment]
I am for fixing it. The reason I have allowed this behavior is the [documentation](https://docs.python.org/3/reference/datamodel.html#determining-the-appropriate-metaclass).

Quote:

The appropriate metaclass for a class definition is determined as follows:

* if no bases and no explicit metaclass are given, then type() is used
* if an explicit metaclass is given and it is _not_ an instance of type(), then it is used directly as the metaclass
* if an instance of type() is given as the explicit metaclass, or bases are defined, then the most derived metaclass is used

End quote.

What do you think?

**Comment by ilevkivskyi** [comment]
@elazarg I think the use case where metaclass is not an instance of ``type`` is quite rare, and (more importantly) this case could be difficult to typecheck. I think mypy could give an error message like: ``Metaclasses not inheriting from "type" are not yet supported.``

**Comment by elazarg** [comment]
I have a branch ready, but it requires multiple changes to typeshed before it can be merged.
