### ISSUE TITLE
Add Python 2 support for __metaclass__

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#2823]
Now that we have metaclasses, we should support them for Python 2 as well. While in Python 3 the metaclass is specified as a `metaclass=M` keyword arg in the class heading, for Python 2 the metaclass is given by a `__metaclass__ = M` assignment in the body of the class.

**Comment by TRManderson** [comment]
Metaclasses in Python 2 are also often defined using:
```python
class A(object):
    class __metaclass__(type):
        pass
```

**Comment by gvanrossum** [comment]
Ow, that's a terrible idiom... (And doesn't translate to Python 3.)

--Guido (mobile)

**Comment by TRManderson** [comment]
Agreed, but it's valid and it works and people do it :'( :'( :'(

**Comment by TRManderson** [comment]
I think I've got a non-terrible solution for the `__metaclass__ = M` case, but the inner class thing going to require a structural change WRT metaclasses to support, so I'd say it's probably better to have an error message saying "don't do this" instead of trying to support it.

**Comment by elazarg** [comment]
I think this issue can be closed by now
