### ISSUE TITLE
Update the behaviour of the `type` function for metaclasses

### ISSUE THREAD

**Issue by TRManderson** [python/mypy#2826]
Calling `type` on a class `A` yields `Type[A]`, even if `A` has a metaclass other than `type`. This leads to incorrectly typechecking interactions with `type(A)` when when attempting to use metaclass attributes.

**Comment by TRManderson** [comment]
Somewhat related to #2655

**Comment by elazarg** [comment]
Can you give a concrete example?
The interaction with other features might be interesting. Maybe it should work something like this
```Python
class M(Generic(T), Type[T]): pass  # maybe M(type) is a shorthand for this

T1 = TypeVar('T1', bound='A')

class A(metaclass=M):
    @classmethod
    def foo(cls: M[T1]) -> T1:
        return cls()

reveal_type(A)  # E: Revealed type is M[A]

class B(A): pass

reveal_type(B)  # E: Revealed type is M[B]
reveal_type(B.foo()) # E: Revealed type is B
```
All of this should be how things work right now, except that `M[B]` is written `Type[B]`. Where does this fail?

**Comment by elazarg** [comment]
I agree it should be possible to write `M[T]` for "a type whose metaclass is M".

**Comment by TRManderson** [comment]
```python
class Meta(type):
    x = 1

class A(metaclass=Meta): pass

print(type(A).x) # test2826.py:6: error: Type[] has no attribute "x"
```

**Comment by elazarg** [comment]
Thanks.

The culprit in my example seems to be that the type variable T is quantified over type constructors (`TypeInfo`) and not over types. Perhaps there is a workaround.
(Just thinking out loud).

**Comment by elazarg** [comment]
I have a fix for this particular issue, but the WiFi here is not working.

**Comment by gvanrossum** [comment]
> ..., but the WiFi here is not working.

Sounds like an updated version of Fermat's claim about his last theorem. :-)

**Comment by elazarg** [comment]
:D
