### ISSUE TITLE
Functions annotated to return None can't return function calls returning None

### ISSUE THREAD

**Issue by TRManderson** [python/mypy#2828]
Minimal example:
```python
def fn1() -> None:
    return None

def fn2() -> None:
    return fn1() # test.py:5: error: No return value expected
```

Sorry for the poor issue naming, not sure how else to describe this.

**Comment by TRManderson** [comment]
One of the tests explicitly disallows this, which is the cause for my PR #2829 failing. I've removed it in the PR, but is there a reason to have it there in the first place?

**Comment by JukkaL** [comment]
I have a feeling that this has been discussed earlier. Anyway, it's a matter of style -- the code is clearly correct. I wonder if @gvanrossum has an opinion whether `fn2` should be accepted.

**Comment by gvanrossum** [comment]
I'm torn, since I sometimes do this myself, but I do think it's a (very slight) code smell. I also think that `fn1()` and `fn2()` should either both be errors or both pass (both have a `-> None` and a `return EXPR` where `EXPR` is known to have the value `None`).

**Comment by ddfisher** [comment]
For what it's worth, this is allowed with `--strict-optional`.

**Comment by JukkaL** [comment]
If it's only a very slight code smell, mypy should perhaps not complain about it.

**Comment by gvanrossum** [comment]
Agreed.

**Comment by msullivan** [comment]
This is fixed
