### ISSUE TITLE
error: Argument 1 to "find" of "bytearray" has incompatible type "int"; expected "bytes"

### ISSUE THREAD

**Issue by 5j9** [python/mypy#2831]
Source code:
```
ba = bytearray('012}'.encode())
print(ba.find(125))
```

mypy error:
```
$ python -m mypy _test.py
_test.py:2: error: Argument 1 to "find" of "bytearray" has incompatible type "int"; expected "bytes"
```

Am I doing something wrong or is this some mypy (or maybe python) issue?

Thanks!

mypy 0.470
python 3.6

**Comment by gvanrossum** [comment]
Looks like a problem in the [typeshed](https://github.com/python/typeshed) repo. You should be able to submit a fix as a PR there. Thanks for reporting!
