### ISSUE TITLE
assert isinstance can widen types

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2840]
Here's an example:
```py
x = ""  # type: str
reveal_type(x)  # E: Revealed type is 'builtins.str'
assert isinstance(x, (int, str))
reveal_type(x)  # E: Revealed type is 'Union[builtins.int, builtins.str]'
```

We should limit `assert isinstance(...)` to strictly narrowing types instead.

**Comment by kirbyfan64** [comment]
Looking around at the source, is there a reason `is_proper_subtype` doesn't consider unions at all? Or was it just an oversight?

**Comment by ddfisher** [comment]
Likely to be an oversight.  I think `is_proper_subtype` was never really fully implemented...
