### ISSUE TITLE
Covariant type variables should be allowed in __init__

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#2850]
There are several issues about covariance, but I didn't find any discussion about ``__init__``. Currently, mypy complains about this code:
```python
from typing import Generic, TypeVar

T_co = TypeVar('T_co', covariant=True)

class C(Generic[T_co]):
    def __init__(self, x: T_co) -> None:
       # Error: Cannot use a covariant type variable as a parameter
       ...
```
Although this is normal in general, I believe this should be allowed for ``__init__``. Otherwise it would be difficult (if possible at all) to put something into a covariant (immutable) container on instantiation.

**Comment by JukkaL** [comment]
Yeah, this should be allowed. Not sure if there are some additional edge cases related to `__init__` we should handle differently once we allow this -- `x.__init__(...)` is already rejected, which is good.

**Comment by ilevkivskyi** [comment]
OK, here is a PR #2888 fixing this.

**Comment by steve-mavens** [comment]
I think I'm seeing a regression of this using Python 3.14 and mypy 1.18.2. This may be the wrong place to ask, but is it intentional?

**Comment by steve-mavens** [comment]
Actually, my case is slightly different and the change for Python 3.14 presumably is in `dataclasses`:

```
from typing import Generic, TypeVar
from dataclasses import dataclass

T_co = TypeVar('T_co', covariant=True)

@dataclass(frozen=True)
class C(Generic[T_co]):
    x: T_co  # error: Cannot use a covariant type variable as a parameter  [misc]
```

So, that isn't exactly a regression even though it does relate to the generated constructor. Sorry! I think my problem might be the synthesised `__replace__` method: because of this (undocumented) method, frozen generic dataclasses actually are not covariant.
