### ISSUE TITLE
Cannot subscript inner generic class

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#2856]
This code:
```python
from typing import TypeVar, Generic

T = TypeVar('T')

class A():
    class B(Generic[T]):
        pass

A.B[int]()
```
gives me a strange error ``The type B[T] is not generic and not indexable``. It looks like a bug.

**Comment by gvanrossum** [comment]
@elazarg Doesn't that error comes from your last PR?

--Guido (mobile)

**Comment by elazarg** [comment]
This is the new error message, but the problem has nothing to do with it. PR attached.

**Comment by elazarg** [comment]
Basically, A.B is not analyzed early enough to be considered generic.

**Comment by elazarg** [comment]
Related: #2075
