### ISSUE TITLE
Error message uses 1-based indexing

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#286]
Input::

    from typing import List, Tuple
    foo = [('x', 'x'),
           ('y', 1),
           ]  # type: List[Tuple[str, str]]

Errors::

    y.py, line 2: List item 2 has incompatible type "Tuple[str, int]"

**Comment by rwbarton** [comment]
This was fixed long ago by 89e60d0f.

**Comment by gvanrossum** [comment]
Heh. I guess GitHub only auto-closes issues if the phrasing is something like "fix ..." or "fixes ...", but not "fix for issue ...". Thanks for noticing this!

**Comment by kirbyfan64** [comment]
@gvanrossum https://help.github.com/articles/closing-issues-via-commit-messages/
