### ISSUE TITLE
mypy 0.470 and 0.471: with the --fast-parser flag can't detect typed_ast 1.0.0

### ISSUE THREAD

**Issue by mr-c** [python/mypy#2860]
```
~/cwltool$ . .env35/bin/activate
(.env35) ~/cwltool$ pip3.5 install typed_ast mypy
Collecting typed_ast
  Using cached typed_ast-1.0.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting mypy
  Using cached mypy-0.471-py3-none-any.whl
Installing collected packages: typed-ast, mypy
Successfully installed mypy-0.471 typed-ast-1.0.0
(.env35) ~/cwltool$ MYPYPATH=typeshed/2.7 mypy --py2 --disallow-untyped-calls  --warn-redundant-casts --warn-unused-ignores --fast-parser  cwltool
You must install the typed_ast package before you can run mypy with `--fast-parser`.
You can do this with `python3 -m pip install typed-ast`.
```

**Comment by mr-c** [comment]
Might be due to the new 1.0.0 release of `typed_ast`, as mypy 0.470 and typed_ast 1.0.0 also show the same problem.

Pinning `typed_ast` to the 0.6.3 release restores `--fast-parser`

**Comment by gvanrossum** [comment]
That's why we released mypy 0.471. It doesn't have this problem, because it pins the typed_ast version to < 0.7.0.

The root problem here is that mypy 0.480 (and current master) will only work with typed_ast 1.0.0, while 0.47[01] only work with the old typed_ast version. However in 0.470 the dependencies didn't express this correctly.

The *only* difference between 0.470 and 0.471 is the fixed dependency on typed_ast. Everything else is identical. (Hence there's no changelog.)

**Comment by mr-c** [comment]
Hey @gvanrossum , we are experiencing this problem with mypy 0.471 as shown in my transcript :-/

**Comment by mr-c** [comment]
For completeness, we are using `pip` 9.0.1 and `setuptools` 34.2.0`

Turns out that just `pip3.5 install mypy` does the right thing and pulls in the pre-1.0.0 release of `typed_ast`. I'll go file a bug on `pip` -- sorry for the noise

**Comment by gvanrossum** [comment]
OK looking.

**Comment by mr-c** [comment]
`pip` issued filed at https://github.com/pypa/pip/issues/4283, not `mypy`'s fault

**Comment by gvanrossum** [comment]
Hm, yes, that's weird. It seems pip doesn't honor the version requirement on typed_ast when you install it and mypy in the same run, or when typed_ast 1.0.0 is already installed. I hope we didn't get the requirement syntax wrong? `typed-ast >= 0.6.3, < 0.7.0`

**Comment by mr-c** [comment]
It looked it up, seems correct.
