### ISSUE TITLE
Incorrect error message "Function is missing a type annotation" when function def has # pylint: ...

### ISSUE THREAD

**Issue by jcrmatos** [python/mypy#2881]
Hello,

The incorrect error message returned by mypy is "receiver_svc.py:94: error: Function is missing a type annotation".
The following code returns the above incorrect error message when running mypy 0.471 on Windows 7 Pro SP1 x64 and Python 3.5.2 32 bits. Also tried running mypy 0.471 on a Linux Mint 18.1 x64 VM and Python 3.5.2 64 bits, but the result was the same.

    def SvcDoRun(self):  # pylint: disable=invalid-name
        # type: () -> None
        """Service start."""
        # LogMsg and LogInfoMsg go to Application log
        # self.ReportServiceStatus goes to System log
        ...

The command line used on both platforms was
mypy --strict-optional --warn-redundant-casts --disallow-untyped-defs --warn-unused-ignores --ignore-missing-imports --follow-imports skip receiver_svc.py

If I remove the # pylint: .... comment the mypy check runs without any error message.

Thanks,

JM

**Comment by ddfisher** [comment]
Thanks for the bug report!  This is a bug in the old mypy parser, which will be replaced by the fast parser in the next mypy release.  Until then, you should use the `--fast-parser` flag, as the new parser does not have this problem.
