### ISSUE TITLE
Importing generic type aliases

### ISSUE THREAD

**Issue by dmzkrsk** [python/mypy#2887]
`lib.py`:
```python
from typing import Callable, TypeVar, Tuple

T = TypeVar('T')
R = TypeVar('R')

Transform = Callable[[T, int], Tuple[T, R]]
```
`main.py`:

```python
from typing import Tuple
from lib import Transform


def int_tf(m: int) -> Transform[int, str]:  # Bad number of arguments for type alias, expected: 0, given: 2
    def transform(i: int, pos: int) -> Tuple[int, str]:
        a = (i + pos) % m  # Name 'T' is not defined Name 'R' is not defined
        return (a, 'ok')

    return transform
```

It works when an alias is defined in the same file

**Comment by dmzkrsk** [comment]
Looks like `T` and `R` are not _bound_ to `Transform`

`from lib import T, R` solves this issue, but it doesn't look valid
Defining `T` and `R` in `main.py` works too

**Comment by ilevkivskyi** [comment]
Thanks for reporting this! Indeed, this looks like a bug. I will take a look at this.

**Comment by JukkaL** [comment]
@ilevkivskyi Are you still working on this?

**Comment by ilevkivskyi** [comment]
Sorry, last weeks were busy, so I could not finish this. I actually wanted to spend next week less on reviewing PRs and more on fixing old assigned issues. Do you want to work on this one?

**Comment by JukkaL** [comment]
I'm reviewing github issues and trying keep the information about who's working on what up-to-date. This issue isn't particularly urgent among the high-priority issues.
