### ISSUE TITLE
Organizing stubs for different versions of supported libraries 

### ISSUE THREAD

**Issue by pkch** [python/mypy#2897]
The organization of typeshed folders is described in `build.py: default_lib_path`:

```
    # We allow a module for e.g. version 3.5 to be in 3.4/. The assumption
    # is that a module added with 3.4 will still be present in Python 3.5.
```

This is not 100% clear. It is very common for libraries (like `enum`) to be updated with addition of new methods or module level objects. How is the stub supposed to be updated? Adding `enum.auto` to the stub in `3.4/` subfolder doesn't seem right. Should a brand new `enum.pyi` be added to `3.6/` subfolder? If that's the case, almost every stub would have to appear in multiple subfolders, so why not make things simpler and require that each stub shows up in each version of python in which it exists?

Code duplication is annoying, of course. While we wouldn't worry that there is code duplication between python 3.4 and python 3.6, that's because version control takes care of that. On the other hand, these versioned stubs, while logically no different than the versions of the libraries they describe, are unfortunately not maintained in the same repos as the corresponding libraries, so they don't get the benefit of version control.

I don't know of a perfect solution to code duplication, but one option is allow incremental updates across versions. That is, let's say `3.4/enum.py` could be loaded first, and then (if appropriate) `3.6/enum.pyi` could be loaded - adding new and overwriting (or even deleting) old type definitions.

**Comment by JukkaL** [comment]
There already is some documentation in typeshed (https://github.com/python/typeshed/blob/master/CONTRIBUTING.md). If you think that the documentation is not clear enough, could you file a typeshed issue? Closing as this isn't specific to mypy but a typeshed issue.
