### ISSUE TITLE
Assigning a dict to explicitly typed variable fails in some cases

### ISSUE THREAD

**Issue by lnqs** [python/mypy#2903]
Assigning a dict literal (which may be empty) to a explicitly typed variable fails in some cases, if the type uses an union:

```python
#!/usr/bin/env python

from typing import Dict, Union

a: Dict[str, Union[int, float]] = {}  # Works
b: Dict[str, Union[int, bool]] = {}  # Works
c: Dict[str, Union[float, bool]] = {}  # Works
d: Dict[str, Union[int, float, bool]] = {}  # Doesn't work
```

```
% mypy --python-version 3.6 --fast-parser mypytest.py
mypytest.py:8: error: Incompatible types in assignment (expression has type Dict[str, float], variable has type Dict[str, Union[int, float, bool]])
```

I have no idea what's happening there, but I guess this isn't the expected behavior?

**Comment by JukkaL** [comment]
This looks like a bug related to union subtyping. Mypy doesn't recognize that `Union[int, float, bool]` is semantically equivalent to `float`. Thanks for reporting this!

**Comment by ilevkivskyi** [comment]
I think this another incarnation of https://github.com/python/mypy/issues/2861#issuecomment-279602468

**Comment by JukkaL** [comment]
@ilevkivskyi Yes, closing this as a duplicate.
