### ISSUE TITLE
Types should be promoted by issubclass

### ISSUE THREAD

**Issue by chadrik** [python/mypy#2909]
I expected types to be promoted to sub-types within an `issubclass` block, the same as instances within an `isinstance` block, but type-checking the following code results in the error `Type[Vehicle] has no attribute "wheels"`:

```python
from typing import Type

class Vehicle(object):
    name = ''

class Car(Vehicle):
    wheels = 4

def test_isinstance(x):
    # type: (Vehicle) -> None
    print(x.name)
    if isinstance(x, Car):
        print(x.wheels)

def test_issubclass(x):
    # type: (Type[Vehicle]) -> None
    print(x.name)
    if issubclass(x, Car):
        print(x.wheels)
```

Is this be possible or am I missing something?  I'm testing against the master branch.

**Comment by ilevkivskyi** [comment]
This would be an interesting feature. Also I think the implementation would be straightforward, since ``isinstance`` is already understood by mypy.

**Comment by JukkaL** [comment]
Yeah, this would be a reasonable thing to support, though you can currently work around the limitation pretty easily by using `cast(Type[Subclass], x)` after the `issubclass` check.
