### ISSUE TITLE
No config file option corresponding to --strict

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#2929]
`strict = True` in the config should enable the strict mode, but it doesn't work.

**Comment by ddfisher** [comment]
Closing this as per discussion on #2941.

**Comment by gvanrossum** [comment]
Looks like this is in such demand that we should just support it. I'm calling for PRs (or revival of the existing PR).

**Comment by msullivan** [comment]
Some work on this was done in #2941, which might be useful to anyone picking this up.

**Comment by msullivan** [comment]
This got fixed I believe

**Comment by briggySmalls** [comment]
If this is fixed, how do I use it? where is it documented @msullivan?

**Comment by rmorshea** [comment]
@briggySmalls looks like the PR for this was never merged.

**Comment by janverb** [comment]
This was merged in #8192. You can just put `strict = True` in a config file now.

**Comment by briggySmalls** [comment]
Oh nice! Thanks people 👏
