### ISSUE TITLE
mypy seems to ignore two-argument asserts

### ISSUE THREAD

**Issue by axch** [python/mypy#2937]
I found this pretty surprising:
```
def foo(x):
  # type: (object) -> None
  assert isinstance(x, int), "x is not an int"
  reveal_type(x)             # 'builtins.object'
  assert isinstance(x, int)
  reveal_type(x)             # 'builtins.int'
```

I would have expected mypy to infer that `x` was a `builtins.int` after the first assert to that effect, regardless of a message being associated therewith.

I am on Ubuntu 16.04, Python 2.7.6, mypy 0.470.

**Comment by ddfisher** [comment]
Thanks for the bug report.  This is a known bug in the old parser and will be fixed in the next release (scheduled for tomorrow).  For now, use `--fast-parser` to use the new parser.  (Note that you'll have to update to 0.471 so the correct version of typed-ast is installed.)
