### ISSUE TITLE
Duplicate `builtin.object`s in MRO

### ISSUE THREAD

**Issue by pkch** [python/mypy#2944]
For reasons that are not entirely clear to me, sometimes there's a duplicate `builtin.object` in the `info.mro` of a type. This violates the assumptions under which C3 MRO operates and results in `error: Cannot determine consistent method resolution order (MRO)` (not necessarily right away; this error may occur when continuing to build up the class hierarchy).

To replicate this, add the following definition to `typing.pyi`:

```
if sys.version_info >= (3, 6):
    class Collection(Sized, Iterable[_T_co], Container[_T_co]):
        pass
```

and check the `info.mro` when `info` is set to the `Collection` type parsed from `typing.pyi`. You will find that it contains `typing.Collection -> [<TypeInfo typing.Collection>, <TypeInfo typing.Sized>, <TypeInfo typing.Iterable>, <TypeInfo builtins.object>, <TypeInfo typing.Container>]` right after parsing, but then later it gets another `object` appended to the end, and so it changes to `typing.Collection -> [<TypeInfo typing.Collection>, <TypeInfo typing.Sized>, <TypeInfo typing.Iterable>, <TypeInfo builtins.object>, <TypeInfo typing.Container>, <TypeInfo builtins.object>]`. This happens in `SemanticAnalyzer.analyze_base_classes`:

```
        # If there are cyclic imports, we may be missing 'object' in
        # the MRO. Fix MRO if needed.
        if info.mro and info.mro[-1].fullname() != 'builtins.object':
            info.mro.append(self.object_type().type)
```

I believe the above code is necessary (at least I couldn't find a way to remove it without breaking MRO), and the only simple solution I found is to remove the duplicate `object` items by rewriting this code as follows:

```
        # If there are cyclic imports, we may be missing 'object' in
        # the MRO. Fix MRO if needed.
        # also, if 'object' appeared earlier in the list, remove it
        # (duplicate 'object' would break mro)
        object_type = self.object_type().type
        if info.mro and info.mro[-1] != object_type:
            info.mro = [t for t in info.mro if t != object_type] + [object_type]
```

This change is required in order to add Collections to `typing.pyi` (currently it is not recognized by mypy).

**Comment by gvanrossum** [comment]
We need to understand the root cause before adding such a band-aid. Maybe it's an import cycle?

**Comment by pkch** [comment]
Well the hierarchy that eventually results in duplicate `object` in `info.mro` is like this:

```
Collection --- Sized ------ object
             \_______Iterable ----object
             \_______Container
```

At first, the mro is created for is `[<TypeInfo typing.Collection>, <TypeInfo typing.Sized>, <TypeInfo typing.Iterable>, <TypeInfo builtins.object>, <TypeInfo typing.Container>]`. At this point, the structure is invalid (`object` should always be at the end). `SemanticAnalyzer.analyze_base_classes` tries to fix it by adding `object` as the last item in the mro, but it's not quite enough to fix it, since `object` now shows up twice.

At this point, there's no MRO error yet; the actual MRO error occurs later, when I try to define

```
class _Sequence(Collection[_T_co], Reversible[_T_co], Generic[_T_co]):
    pass
```

This is where C3 MRO ends up failing. It tries to linearize these sequences:

```
[<TypeInfo typing.Collection>, <TypeInfo typing.Sized>, <TypeInfo typing.Iterable>, <TypeInfo builtins.object>, <TypeInfo typing.Container>, <TypeInfo builtins.object>]
[<TypeInfo typing.Reversible>, <TypeInfo builtins.object>]
[<TypeInfo typing.Collection>, <TypeInfo typing.Reversible>]
```
and after a few steps ends up with:

```
[<TypeInfo builtins.object>, <TypeInfo typing.Container>, <TypeInfo builtins.object>]
[<TypeInfo builtins.object>]
```

Since it can't find the valid head, it fails with MRO error.

I don't know how to explain it precisely, but I think it is caused by the fact that `object` is not the last item in some types' mro, and by the time the attempt is made to fix it, it's too late. The fix happens after the mro is already created, it should have been done earlier, before linearization.

I was trying to do precisely that by adding:
```
if not defn.base_type_exprs:
    defn.base_type_exprs = [NameExpr('object')]
```
at the end of `semanal.SemanticAnalyzer.clean_up_bases_and_infer_type_variables`, but it didn't fix the problem (possibly because of cyclical imports).

So the only solution I found was to remove duplicate `object` items in `SemanticAnalyzer.analyze_base_classes`.

**Comment by gvanrossum** [comment]
If that is so, can you reproduce this without using the container hierarchy?

**Comment by pkch** [comment]
It seems this problem only happens when, inside `typing.pyi` I define a class whose base isn't defined until further down in `typing.pyi`. In particular, when I moved `Collection` definition to be after `Container` definition, the MRO Error disappeared. 

I'll try to replicate with other definitions though, just in case it's an issue that's worth fixing.

**Comment by gvanrossum** [comment]
Ah, yeah, that is definitely related to dependency cycles.

--Guido (mobile)

**Comment by pkch** [comment]
I'm closing this for now, since perhaps it's not something easily fixable and it's not urgent. If it comes up again, we can reopen this issue.
