### ISSUE TITLE
Variance of generics

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#295]
It should be possible to define a type variable as covariant. For example, the type variable of Iterable[t] could be covariant, and then Iterable[x] would a subtype of Iterable[y] if x is a subtype of y. Currently this is not the case, which is sometimes awkward, and this would even more awkward with union types.

Not sure about the syntax. Maybe something like this:

```
T = typevar('T', covariant=True)   
```

(Ouch, looks pretty technical.)

Covariant type variables must not appear within method argument types or instance variable types, i.e. they are only valid as return types. Also, only read-only properties can have types with covariant type variables.

**Comment by JukkaL** [comment]
#694 added basic support for covariance and contravariance, but there's some more work to be done. I'll add links to futher issues here.

**Comment by JukkaL** [comment]
Remaining subtasks: #734, #735, #736, #737

There may be more, but the above would cover a lot of interesting cases.

**Comment by JelleZijlstra** [comment]
Variance in typevars has been supported for a long time. Closing in favor of the more specific bugs Jukka linked to.
