### ISSUE TITLE
NoReturn-related issue with six.reraise in except clauses

### ISSUE THREAD

**Issue by timabbott** [python/mypy#2958]
After upgrading Zulip to mypy 0.501, I got this error running it on Zulip with our standard arguments:
`zproject/jinja2/backends.py:33: error: Missing return statement`

The function in question is this: https://github.com/zulip/zulip/blob/master/zproject/jinja2/backends.py#L34

I think this is a mypy bug, because it appears that `six.reraise` is correctly annotated as a `NoReturn` in typeshed.

I tried changing the return type to `Union[Template, NoReturn]`, but that didn't fix the error.

I'm out of time for mypy bugging for today, so I didn't try making a reproducer, but it seems like a pretty simple function, so should be doable...

**Comment by gvanrossum** [comment]
(Copying the offending code, since the line number already changed:)
```python
    def get_template(self, template_name):
        # type: (str) -> Any # should be Template, see https://github.com/python/mypy/issues/2958
        try:
            return Template(self.env.get_template(template_name),
                            self.context_processors,
                            self.debug)
        except jinja2.TemplateNotFound as exc:
            six.reraise(TemplateDoesNotExist, TemplateDoesNotExist(exc.args),
                        sys.exc_info()[2])
        except jinja2.TemplateSyntaxError as exc:
            six.reraise(TemplateSyntaxError, TemplateSyntaxError(exc.args),
                        sys.exc_info()[2])
```
Certainly looks like a bug! @ddfisher?

**Comment by ddfisher** [comment]
Strange.  I can't seem to reproduce if I boil it down at all.  Let me see if I can repro on the full zulip source.

**Comment by ddfisher** [comment]
Here's the issue:  this file is using `six` from `django.utils`.  There's no stub for `django.utils`, so it assumes the type for `six.reraise` is just `Any`.  I don't think we want to assume that functions returning `Any` are potentially `NoReturn`, so the fix here is to either 1) switch to importing from the standard `six`, 2) add `assert False` after the reraise statements, or 3) make a local alias to `six.reraise` and give it the correct type: 
```py
reraise = six.reraise  # type: Callable[Optional[Type[BaseException]], Optional[BaseException], Optional[types.TracebackType]], NoReturn]
```

**Comment by timabbott** [comment]
Yeah I think that's the right answer.  We'll switch to standard `six`; I didn't even know it had a weird copy under `django.utils`.
