### ISSUE TITLE
Tuple[...] should be compatible with Iterable[...] and Sequence[...]

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#296]
Currently, Tuple[int, int] is not compatible with Iterable[int] and Sequence[int], but it should obviously be. Also, update type join to support this (join of Tuple[int, int] and Tuple[int] should be Sequence[int]).

For example, this program is rejected:

```
from typing import Iterable
def f(x: Iterable[int]) -> None: pass
f([1,2])  # OK
f((1,2))  # Argument 1 to "f" has incompatible type "Tuple[int, int]"
```

See also #184 (it's very closely related).

**Comment by terrisgit** [comment]
It's 2018 and this problem still exists 

async def execute_update(query: str, query_args: Optional[Sequence[Any]]=None)->None:

await DbExecutor.execute_update(query, (message.id))

error: Argument 2 to "execute_update" has incompatible type "int"; expected "Optional[Sequence[Any]]"

**Comment by Michael0x2a** [comment]
@terrisgit -- `(5)` isn't actually a tuple -- that expression is equal to just 5.

If you instead pass in `(5,)`, everything typechecks.

**Comment by gvanrossum** [comment]
Gotta give points for the attitude.

**Comment by terrisgit** [comment]
Thanks for the education!

**Comment by user-name-name** [comment]
I have a next case: the result of one function is `Dict[str, Tuple[str, ...]]`, the argument of another one is `Dict[str, Sequence[str]]`. So when we use use the result of the first function as the argument of the second, we got "Argument has incompatible type Dict[str, Tuple[str, ...]]"; expected "Dict[str, Sequence[str]]". Is it valid?

**Comment by ilevkivskyi** [comment]
@user-name-name Mypy is correct, `Dict` is invariant https://mypy.readthedocs.io/en/latest/generics.html#variance-of-generic-types
