### ISSUE TITLE
It's impossible to use `--warn-unused-ignores` in a Python 2+3 codebase

### ISSUE THREAD

**Issue by timabbott** [python/mypy#2961]
If you use Python 2 and Python 3 in a codebase, and run mypy against it with both, `--warn-unused-ignores` will warn about issues present in only one or the other.

A reasonable fix might be to add a `type: ignore2`  / `type: ignore3` that one can use in this sort of situation?

**Comment by gvanrossum** [comment]
That's a known limitation of that flag, and I don't think we're going to fix it. Note that this is not limited to Python major versions either -- it can bite you for platform-specific code or minor-version-specific code too, if you run mypy with multiple profiles.

Your best option is to write a small post-processing tool that computes the intersection of the two sets of warnings.

**Comment by ddfisher** [comment]
For that reason, `--warn-unused-ignores` is not intended to be used in CI.  I thought we'd documented this somewhere, but I don't see it.  Maybe the takeaway here is we need to add documentation to that effect?
