### ISSUE TITLE
What remains to be done to get typing.Deque to work?

### ISSUE THREAD

**Issue by rhettinger** [python/mypy#2963]
Even after typing.Deque was added to 3.6.1rc1, there is still work that needs to be done to get Deque to work properly.

Given *demo.py*:

```
from typing import Deque
from collections import deque

d = deque()          # type: Deque[str]
d.appendleft('x')
d.append('y')
d.appendleft('w')
print(d)
```
A type check gives:

```
$ mypy demo.py
demo.py:4: error: Invalid type "typing.Deque"
demo.py:5: error: object has no attribute "appendleft"
demo.py:6: error: object has no attribute "append"
demo.py:7: error: object has no attribute "appendleft"
```

**Comment by ilevkivskyi** [comment]
The PR for this https://github.com/python/mypy/pull/2845 stays open for several weeks (although this is just 5 lines plus tests). @JukkaL @gvanrossum @ddfisher all seem to be busy now.

**Comment by gvanrossum** [comment]
Can you confirm that it works with mypy master now and if so close the issue?

**Comment by rhettinger** [comment]
This works with mypy master now.  Thanks.
