### ISSUE TITLE
show_error_context does not work in config file

### ISSUE THREAD

**Issue by tyehle** [python/mypy#2964]
Looks like the name was changed from `hide_error_context`, but was unchanged internally. Since the config file settings are copied directly into `options` the following ini will fail with `mypy.ini: [mypy]: Unrecognized option: show_error_context = True`

```
[mypy]
show_error_context = True
```

`hide_error_context = False` works as expected.

Possible fix: refactor the internal name to match the external one.

**Comment by gvanrossum** [comment]
Thanks, good catch. Do you feel comfortable sending a PR yourself?

**Comment by tyehle** [comment]
Probably, but from #2545 it looks like the name wasn't changed for backward compatibility.

**Comment by gvanrossum** [comment]
Hm, [this comment](https://github.com/python/mypy/pull/2548#issuecomment-266162319) suggests that we thought about changing it but then dropped the thought. The docs state that it's named `show_error_context`, and I think that should prevail, regardless of backwards compatibility.
