### ISSUE TITLE
Duck typing annotation

### ISSUE THREAD

**Issue by pkch** [python/mypy#2966]
[edit] To clarify: this is a question about a future mypy feature only briefly mentioned in the docs.

Should duck typing require annotation, or should mypy resolve it automatically?

1) No annotation

```python
def f(x: DuckType) -> int:
    return x.value()
```
Here the programmer provides no annotation apart from stating that the argument should be type checked using duck typing. mypy infers that `x` must provide a method `value` of type `Callable[[], int]`. mypy then complains if it cannot verify (again without any help from the programmer) that objects passed to `f()` meet that constraint:

```python
f('abc') # error
class X:
    def value(self):
        return 10
f(X()) # ok
```
2) Annotation

```python
class I_Value(DuckType):
    def value() -> int: ...

def f(x: I_Value) -> int:
    return x.value()
```

Here the only difference from the existing types is that comparison between types is based on the presence of methods, rather than the class hierarchy.

Or is it possible to support both (no annotation for simple cases, and annotation when mypy can't resolve the duck types)?

Annotation becomes rather involved very quickly. For example for `def f(x:DuckType) -> int: return x.value()*2+1`, the annotation seems to require this:

```python
T = TypeVar['T']
class I_Add(DuckType, Generic[T]):
    def __add__(rhs: T) -> T: ...

class I_Mult(DuckType, Generic[T]):
    def __mult__(rhs: T) -> T: ...

class I_Arithmetic(DuckType, I_Add[T], I_Mult[T]):
    pass

class I_Value(DuckType):
    def value() -> I_Arithmetic[int]: ...

def f(x: I_Value) -> int:
    return x.value() * 2 + 1
```

Am I missing something that would make annotation less cumbersome? AFAIU automatic duck type inference would have resulted in something even worse (because it's unnecessarily more specific to the code rather than to the mental model of the developer):

```python
T = TypeVar['T']
class _1(DuckType):
    def __add__(rhs: int) -> int: ...

class _2(DuckType):
    def __mult__(rhs: int) -> _1: ...

class _3(DuckType):
    def value() -> _2: ...

def f(x: _3) -> int:
    return x.value() * 2 + 1
```

OTOH, automatic duck typing output may only need to be read for debugging, while manual annotations will always create the additional noise.

**Comment by gvanrossum** [comment]
Hm, the discussion for this is mainly here: https://github.com/python/typing/issues/11

The "automatic" annotation is close to what [pytype](https://github.com/google/pytype) does.

I'm not excited about doing that in mypy though; it goes against mypy's general philosophy (which is to check usage against annotations, not to infer annotations from usage) and I expect that it's really hard except for very simple cases (as the complexity of pytype proves IMO).

**Comment by pkch** [comment]
Ah thanks for clarifying about automatic annotations. The rest of my question is a duplicate of python/typing#11 so I'm closing it.
