### ISSUE TITLE
error: "JSONDecodeError" has no attribute "{msg,doc,pos}"

### ISSUE THREAD

**Issue by wsanchez** [python/mypy#2981]
I'm seeing these errors from `mypy` which seem incorrect:

```console
src/util/json.py:71: error: "JSONDecodeError" has no attribute "msg"
src/util/json.py:71: error: "JSONDecodeError" has no attribute "doc"
src/util/json.py:71: error: "JSONDecodeError" has no attribute "pos"
```

The code in question is catching a `JSONDecodeError` and accessing the `msg`, `doc`, and `pos` attributes of the exception object, which are documented attributes of that exception type.

**Comment by gvanrossum** [comment]
This is probably some missing information in the typeshed stub for the stdlib json package.

**Comment by wsanchez** [comment]
I'm not seeing these any more; perhaps the stubs were fixed?

**Comment by ethanhs** [comment]
Yes, the stubs were fixed in https://github.com/python/typeshed/commit/397f99836842494de2e9561001d16cbe64b3b937
