### ISSUE TITLE
"Incompatible types in assignment" when using _ as throwaway variable

### ISSUE THREAD

**Issue by vors** [python/mypy#2982]
Should `_` get a special treatment?  
## Repro

```
import os

for _ in range(3): # throw-away _
    root, _ = os.path.split("C:\\123") # throw-away _
```

## Expected
No errors

## Actual
```
foo.py:4: error: Incompatible types in assignment (expression has type "str", variable has type "int")
```

**Comment by gvanrossum** [comment]
It's been proposed before, there may even be an open issue for it already, but GitHub can't seem to search for "_". If someone submits a PR I'm happy to review it.

**Comment by vors** [comment]
Oh, sorry I didn't search extensively before filling.

I aslo tried to work-around it with 

```
import os
from typing import Any

for _ in range(3):  # type: Any
    root, _ = os.path.split("C:\\123")
```

And that produces `foo.py:4: error: Parse error before "Any"` which seems like a separate issue.

**Comment by gvanrossum** [comment]
That parse error should be gone if you use the fast parser (which is
default in master and will soon be the only one).

**Comment by ilevkivskyi** [comment]
Here is the issue that Guido mentioned https://github.com/python/mypy/issues/465.
