### ISSUE TITLE
redirect mypy-lang to mypy on PyPI

### ISSUE THREAD

**Issue by graingert** [python/mypy#2983]
took a little while to find the 0.501 release, because it was moved to `mypy` on PyPI.

It would make my life easier if the long_description of the mypy-lang PyPI entry was just a big `<h1>` link to https://pypi.org/project/mypy/

**Comment by graingert** [comment]
And maybe add packages that on install print out the new package location.

**Comment by ethanhs** [comment]
I think this would be ok if we bump the major version in mypy-lang with an empty package that fails to install (so we don't leave cruft) and just give a notice it moved.

**Comment by graingert** [comment]
I believe there's a spec for deprecated packages somewhere

**Comment by msullivan** [comment]
Well we never did this but it has been years and I think it is pretty well-established as the package being mypy, so I'm just gonna close this...
