### ISSUE TITLE
List[subclass] is incompatible with List[superclass]

### ISSUE THREAD

**Issue by Stiivi** [python/mypy#2984]
When a function that is accepting a list of a base class (for example `class Base`) is passed and argument which is a list of subclass instances of the base class (for example `Thing(Base)`) mypy complains about incompatible type: ` Error: Argument 1 to "function" has incompatible type List[Thing]; expected List[Base]`.

Wrapping the argument with a cast to a list of the base class passes.

Code example:

```python
from typing import List, cast

class Base:
    pass

class Thing(Base):
    pass

def function(arg: List[Base]) -> None:
    pass

things:List[Thing] = [Thing()]

# Error: Argument 1 to "function" has incompatible type List[Thing]; expected List[Base]
function(things)

# Passes
function(cast(List[Base], things))
```

**Comment by gvanrossum** [comment]
This is as designed, please read up on Liskov.

**Comment by JukkaL** [comment]
You can often use `Sequence[x]` instead of `List[x]` to get code like your example working. This works because `Sequence` is covariant and doesn't let you set items in the list, unlike `List[x]` which is invariant and allows the mutation of the list.

**Comment by JelleZijlstra** [comment]
This is expected behavior and documented at http://mypy.readthedocs.io/en/latest/generics.html#variance-of-generic-types. Your example would fail with code like this:
```
things: List[Thing] = []

def function(arg: List[Base]) -> None:
    arg.append(Base())

function(things)

for thing in things:
    assert isinstance(thing, Thing)  # fails at runtime, but type checker detects no errors
```

If your function doesn't actually modify the list, you can get around this error by typing the argument as `Sequence[Base]` or even `Iterable[Base]` instead.

**Comment by randolf-scholz** [comment]
@JelleZijlstra What should I do in the case when I want to have a list of subclasses of some base class, but also need to use `append`? Do I really have to define a custom type for this very simple, very common case?

**Comment by randolf-scholz** [comment]
@JelleZijlstra So how should one type hint a `list` of subclasses of a base class, that is created using `append`? This seems like a very common case.

**Comment by eykamp** [comment]
Old issue, but here is a solution that works:

```python
from typing import List, TypeVar

class Base:
    pass

class Thing(Base):
    pass


T = TypeVar("T", bound=Base)


def function(arg: List[T]) -> None:
    pass


things: List[Thing] = [Thing()]

function(things)
```
