### ISSUE TITLE
Newbie Question on basic usage

### ISSUE THREAD

**Issue by lucidguppy** [python/mypy#2988]
I'm trying to wrap my head around mypy and it seems super easy except for actually using it seems difficult.

I've created a repo where I though the mypy test shell script would find issues I did with my tests. What do I need to change to get it to detect type errors?

https://github.com/lucidguppy/mypyquestions

**Comment by JelleZijlstra** [comment]
Your test functions aren't being checked by mypy because they don't have type annotations. Mypy only type checks functions with type annotations, unless you pass the `--check-untyped-defs` flag.

**Comment by lucidguppy** [comment]
@JelleZijlstra - adding the flag didn't help - the verbose output says the tests aren't even being parsed.

**Comment by JelleZijlstra** [comment]
That appears to be because test has no `__init__.py`, so mypy doesn't think it's part of the package.

**Comment by lucidguppy** [comment]
So it seems like you have to point directly at each test file in my code base - that seems to be a bit tedious.

**Comment by ethanhs** [comment]
@lucidguppy It seems you have added an `__init__.py` file, so you should be able to do `mypy -m foo` and it should type check the files in the `foo` module.

**Comment by lucidguppy** [comment]
@ethanhs - are you supposed to check tests with mypy - or is that not a basic usage?

**Comment by ethanhs** [comment]
Uh, I suppose you could. I think it may be a good idea to add running on directories that are not modules, but I cant think of a reason why you couldnt just put an `__init__.py` in the folder.

**Comment by lucidguppy** [comment]
I'm going to close this - but it just seems like there should be a guide on how to use mypy in a project properly.

**Comment by ethanhs** [comment]
It is documented here: http://mypy.readthedocs.io/en/latest/command_line.html 
Also, you might be interested in the option to use a file that lists each test file

**Comment by ethanhs** [comment]
sorry, the link to what I was talking about is here: http://mypy.readthedocs.io/en/latest/command_line.html#reading-a-list-of-files-from-a-file

**Comment by lucidguppy** [comment]
I tried using mypy.api - but I can't seem to import it.

>>> from mypy import api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'api'

**Comment by ethanhs** [comment]
Could you share what platform, python version and mypy version you are using? Also, you might consider asking on our gitter, where there is usually someome online.

**Comment by lucidguppy** [comment]
$ pip freeze
mypy-lang==0.4.6
typing==3.5.3.0

Python 3.5.2 (default, Nov 26 2016, 10:28:06) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by JelleZijlstra** [comment]
Try uninstalling `mypy-lang` and installing the latest version of `mypy`. The package was renamed.

**Comment by lucidguppy** [comment]
@JelleZijlstra many thanks!  👍 My script now works and I should be able to hack something together.
