### ISSUE TITLE
Confusing error message for Tuple in runtime context.

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#2989]
This code:
```python
from typing import Tuple

Tuple[int]
```
fails with a strange message.
```
Value of type "object" is not indexable
```
I believe this should not be an error at all.

**Comment by nathanielksmith** [comment]
I'm not able to reproduce this as of 38453c0ddfaa6660309f782b227bd40b8c4634ba in python 3.5.

**Comment by ilevkivskyi** [comment]
I still see the same error on the current master.

**Comment by nathanielksmith** [comment]
hm, here's what I'm doing:

```
(mypy) ➜  mypy git:(master) ✗ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
>>> from typing import Tuple
>>> Tuple[int]
typing.Tuple[int]
```

I'm happy to investigate more if you have suggestions on other ways to reproduce.

**Comment by ilevkivskyi** [comment]
You should save the above code in a file and check the file with mypy (runtime context here means that ``Tuple[int]`` is not an annotation here).

I can even say why this happens: ``Tuple`` is defined just as ``object()`` in ``typing.pyi`` (to prevent many possible illegal uses of ``Tuple``). I am not sure however what is the right way to fix this.

**Comment by nathanielksmith** [comment]
shit sorry, i misunderstood the original issue - i thought runtime context meant "when running the code." apologies!

**Comment by mistermocha** [comment]
Implementing a common base class with a `__getitem__` across `Tuple` and others in typeshed appears to correct this issue. Suggesting changes in https://github.com/python/typeshed/pull/1340 to address.

**Comment by ilevkivskyi** [comment]
This is now fixed by https://github.com/python/typeshed/pull/1340

**Comment by gvanrossum** [comment]
But it won't be effective in mypy master until the next typeshed sync right?

**Comment by ilevkivskyi** [comment]
> But it won't be effective in mypy master until the next typeshed sync right?

Yes, I tested this after checking out latest commit locally.
