### ISSUE TITLE
incorect error for namedtuple

### ISSUE THREAD

**Issue by noskill** [python/mypy#2996]
mypy finds error for namedtuple constructed from predefined list:

```
from collections import namedtuple
fields = ['a', 'b']
X = namedtuple('X', fields) # error: List or tuple literal expected as the second argument to namedtuple()
Y = namedtuple('Y', ['a', 'b']) # ok
x = X(1, 'x') # error: Too many arguments for "namedtuple"
y = Y(1, 'y')  # ok
```

**Comment by elazarg** [comment]
The first error is known, and there should be at least a warning; mypy does not do constant propagation yet.
The second error should be fixed IMO.

**Comment by gvanrossum** [comment]
The second error is just because the first error leaves the type definition without parameters. Though we may still want to fix it by returning Any in that case instead of a namedtuple with no fields.
