### ISSUE TITLE
reveal_type() inside unannotated function always shows "Any"

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#3001]
Repro:
```python
x = 1
reveal_type(x)
def f():
    reveal_type(x)
```
The first `reveal_type()` prints `int` for the type, but the second one prints `Any`. This is because `f()` is unannotated. But it's surprising. Maybe we should at least add some kind of note to the output of `reveal_type()` in an unannotated function to warn the user that the output is unreliable?

**Comment by matangover** [comment]
Seems like this issue can be closed? The note already exists:
```
test.py:8: error: Revealed type is 'Any'
test.py:8: note: 'reveal_type' always outputs 'Any' in unchecked functions
```
