### ISSUE TITLE
Argument 1 to "load" has incompatible type "HTTPResponse"; expected IO[str]

### ISSUE THREAD

**Issue by lithammer** [python/mypy#3007]
Python v3.6
Mypy v0.501

```python
# http.py
import http.client
import json

conn = http.client.HTTPConnection('example.com')
conn.request('GET', '/foobar.json')
response = conn.getresponse()
json.load(response)
```

Since `response` is a "file-like object" (i.e. has a `.read()` method). And `json.load(fp, ...)` operates on those according to the documentation (*"Deserialize fp (a .read()-supporting file-like object containing a JSON document) to a Python object"*) I expect this to work.

```bash
$ mypy http.py
http.py:8: error: Argument 1 to "load" has incompatible type "HTTPResponse"; expected IO[str]
```

**Comment by JelleZijlstra** [comment]
Mypy doesn't currently support structural typing, although there is an active proposal to add it (see python/typing#11 and python/peps#224). Once that's implemented we could add a Protocol that defines the `read` method, but until then I'm not sure there's any better workaround than using `cast()` or `# type: ignore`.

**Comment by ilevkivskyi** [comment]
The original example now passes without errors, so I assume it was fixed in typeshed.
