### ISSUE TITLE
Direct "super" call of type.__init__ complains about type of first arg

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#3010]
Repro:
```python
class M(type):
    def __init__(cls, name, base, attrs) -> None:
        type.__init__(cls, name, base, attrs)  # E: Argument 1 to "__init__" of "type" has incompatible type "M"; expected "type"
```
This appears to be a regression due to #2825 "Treat type equivalent to Type[Any]; fixes #2655" (@ilevkivskyi, reviewed by @ddfisher).

**Comment by ilevkivskyi** [comment]
Yes, I remember I updated my PR after https://github.com/python/mypy/pull/2837 was merged, but I missed this corner case, sorry.

Here is a fix #3012
