### ISSUE TITLE
invalid error when writing to an abstract property in an abstract class

### ISSUE THREAD

**Issue by funkyfuture** [python/mypy#3011]
i have this piece of code:

```python
class NamespacedXMLDocument(XMLDocumentBase, metaclass=abc.ABCMeta):

    @abc.abstractproperty
    def class_namespaces(self) -> Tuple[str]:
        pass

    @classmethod
    def register_xml_namespace(cls, namespace: str) -> None:
        cls.class_namespaces = cls.class_namespaces + (namespace,)
```

and mypy 0.501 yields this for the last line:

    Incompatible types in assignment (expression has type Tuple[str, ...], 
    variable has type Callable[[NamespacedXMLDocument], Tuple[str]])

my interpretation is, that `Callable` relates to `abc.abstractproperty`.

**Comment by gvanrossum** [comment]
I think this is also a repro:
```python
import abc
class C(metaclass=abc.ABCMeta):
    @abc.abstractproperty
    def foo(self) -> int: pass
    @classmethod
    def bar(cls) -> None:
        cls.foo = 0
```
This gives a similar error on the last line:
```
Incompatible types in assignment (expression has type "int", variable has type Callable[[C], int])
```
But is it really wrong? You're trying to dynamically patch the definition of the property in the class.

**Comment by funkyfuture** [comment]
my intent is to define an abstract property `class_namespaces` that must be defined in subclasses of the abstract class and to provide a non-abstract method inherited by all subclasses that controls that - then in the subclass' context non-abstract - property for each subclass. does that make sense?

**Comment by gvanrossum** [comment]
What you want is a *class* property. There's no stdlib support for those, but IIRC there are some hints on StackOverflow. I assume that what you tried doesn't work at runtime either.

**Comment by funkyfuture** [comment]
indeed i want an abstract class property. it does actually work that way, however it doesn't fail as expected if a subclass doesn't define that class property.
