### ISSUE TITLE
Enum has no attribute "__members__"

### ISSUE THREAD

**Issue by gopar** [python/mypy#3017]
Mypy spits out `error: "SomeEnum" has no attribute "__members__"` with the following code:

```python
from enum import Enum

class SomeEnum(Enum):
    ONE = 1
    TWO = 2

SomeEnum.__members__
```
`__members__` exists and is [documented in the py docs](https://docs.python.org/3/library/enum.html#supported-dunder-names)

Mypy version:  0.501
Python: 3.6.0

**Comment by JelleZijlstra** [comment]
I think this is being tracked in python/typeshed#854.

**Comment by gvanrossum** [comment]
Indeed. I should pick up my work on Enum.
