### ISSUE TITLE
Prohibit parameterized generics in isinstance

### ISSUE THREAD

**Issue by pkch** [python/mypy#3037]
As @ilevkivskyi commented (https://github.com/python/mypy/pull/3005#discussion_r106779110), it would be nice to fail type check on this code:

```
obj = 1
if isinstance(obj, Iterable[int]):
    1
```
because it fails in runtime with `TypeError`. 

I can easily see this situation inside `checker.py:get_isinstance_type()` by verifying that `len(type.items()[0].ret_type.args) == 0`; but is it the right place to message about type validation problems?

**Comment by ilevkivskyi** [comment]
Maybe the right place is in ``visit_call_expr`` in ``checkexpr.py``? If the name of function called is ``builtins.isinstance`` or ``builtins.issubclass``  and there is, for example, any ``CallableType`` argument with ``.is_class_obj()`` returning ``True`` and having type arguments, then you issue a warning.
