### ISSUE TITLE
SupportsDivmod

### ISSUE THREAD

**Issue by orenbenkiki** [python/mypy#3047]
There doesn't seem to be such a thing right now, so when I add __divmod__ to my class, mypy still complains:

    error: Type argument 1 of "divmod" has incompatible value "MyClassHere"

    error: Type argument 1 of "divmod" has incompatible value "SupportsInt"

For the same line (my class does SupportsInt).

**Comment by ilevkivskyi** [comment]
This problem will be fixed by protocols (structural subtyping) proposed by PEP 544 (and corresponding improvements to typeshed stubs).

**Comment by orenbenkiki** [comment]
Good - is there a temporary workaround though?
Right now I just place `# type ignore` on any line that uses `divmod` on my class (mercifully, it is very rare).

**Comment by ilevkivskyi** [comment]
I don't think anything could be done now from mypy side. typeshed stubs allow only arguments that explicitly inherit from ``int`` or ``float``. If you have an idea about how to improve stubs, then you could make a PR to [typeshed](https://github.com/python/typeshed).

**Comment by orenbenkiki** [comment]
Possibly related issue: if my class impements `__index__`, there seems to be no way to tell `mypy` that it is allowed inside `[...]` of unrelated types (There is no `SupportsIndex`). Again, `# type: ignore` to the rescure...

**Comment by orenbenkiki** [comment]
The final list of operations that `mypy` can't be convinced not to complain about is:

* `__divmod__`, which triggered opening this issue.

* `__index__`, which may be an unrelated issue?

* `__complex__`, which is strange, since my class derives from `typing.SupportsComplex`.

* `__reversed__`, which is also strange, since `mypy` accepts that normal iteration works.

I can live with `# type: ignore` these, as there is a trivial workaround (just wrap the value with `int(...)` (or `list(...)` for `__reversed__`).

Still, it isn't "nice" that there's no way to define a type-checked class that behaves "like an int" but doesn't derive from `int`.

**Comment by udifuchs** [comment]
> * __index__, which may be an unrelated issue?

Here is a code sample showing the issue. The following code runs fine:
```
class MyInt:
    def __init__(self, value: int) -> None:
        self.value = value

    def __index__(self) -> int:
        return self.value

l = ['foo', 'bar']
t = ('foo', 'bar')

print(hex(MyInt(7)))
print(l[MyInt(0)])
print(t[MyInt(1)])
```
mypy does not complain about the `hex` line, but it does complain about the next two lines:
```
t.py:11: error: No overload variant of "__getitem__" of "list" matches argument type "MyInt"  [call-overload]
t.py:12: error: Invalid tuple index type (actual type "MyInt", expected type "Union[int, slice]")  [misc]
```

**Comment by hauntsaninja** [comment]
Things are very different in 2022. We have protocols and typeshed uses them.

udifuchs example passes with list index with recent mypy. https://github.com/python/mypy/pull/13313 will make it also pass with tuple index
