### ISSUE TITLE
Weird error messages when mixing classes with instances

### ISSUE THREAD

**Issue by miedzinski** [python/mypy#3050]
```python
class A: pass
x: Tuple[A]
x = A,  # E: Incompatible types in assignment (expression has type "Tuple[A]", variable has type "Tuple[A]")
y: Tuple[Type[A]]
y = A,  # OK, expected
def f(x: Tuple[A]) -> None: return None
f((A,))  # E: Argument 1 to "f" has incompatible type "Tuple[A]"; expected "Tuple[A]"
reveal_type((A,))  # E: Revealed type is 'Tuple[def () -> x.A]'
z: A
z = A  # E: Incompatible types in assignment (expression has type "A" (type object), variable has type "A")
z = A,  # E: Incompatible types in assignment (expression has type "Tuple[A]", variable has type "A")
```

Looks like mypy formats class type in three ways: `T` (which is wrong), `T (type object)`, and `def () -> T`. In some cases these errors are unclear.

**Comment by ilevkivskyi** [comment]
Yes, I remember I noticed this around a year ago, last two formats are OK I think, but the first one is definitely misleading.

**Comment by ambv** [comment]
So the correct error message should be:
> E: Incompatible types in assignment (expression has type "Tuple[**Type[A]**]", variable has type "Tuple[A]")

**Comment by elazarg** [comment]
Example from #3372:
```python
class A: pass
class B(A): pass
def f(a: A): pass

f(B)  # E: Argument 1 to "f" has incompatible type "B"; expected "A"
a: A = B  # E: Incompatible types in assignment (expression has type "B", variable has type "A")
```

**Comment by elazarg** [comment]
I will submit a PR is there is agreement on the correct error message is.

I am +1 on `Type[A]` as @ambv suggested.

**Comment by elazarg** [comment]
I think the issue becomes even more confusing when dealing with metaclasses.

**Comment by ilevkivskyi** [comment]
I am also +1 on ``Type[A]``.

**Comment by gvanrossum** [comment]
Yup
