### ISSUE TITLE
Integration with PyCharm needed? (and other ide's editors)

### ISSUE THREAD

**Issue by flip111** [python/mypy#3053]
I read that pycharm [has some checking for types](https://blog.jetbrains.com/pycharm/2015/11/python-3-5-type-hinting-in-pycharm-5/) out of the box. Do i still need the mypy command line tool? How does it compare?

Before i was using sublime text and i saw this plugin https://github.com/fredcallaway/SublimeLinter-contrib-mypy

Wouldn't it be a nice addition for to the documentation to point to the various solutions of IDE's and editors?

**Comment by JukkaL** [comment]
As far as I know, mypy can do stricter type checking than PyCharm, especially if you use options like `--strict-optional`. Also, mypy is easy to run in continuous integration, and if you have multiple people working on a project, perhaps not all of them use PyCharm.

I hadn't seen the Sublime plugin before -- thanks for the link! 

It would be good to discuss IDE and editor integration in the documentation. In order for that to be useful, somebody would have to research and evaluate different tools, and that could take a fair amount of time to do properly.

**Comment by flip111** [comment]
Just that first paragraph you wrote is excellent and i think you can just copy paste that into the readme (nearly) as is.

> As far as I know, mypy can do stricter type checking than PyCharm, especially if you use options like `--strict-optional`. Also, mypy is easy to run in continuous integration, and if you have multiple people working on a project, perhaps not all of them use PyCharm.

Yeah i understand it would take some time to investigate all the tools. I close this issue because i know now that i still need to run mypy even though i use pycharm now.

By the way, is it also possible with mypy to get the inferred type signature? that way it can work as a possible hint to add types to your code.

**Comment by JukkaL** [comment]
Mypy can't infer type signatures. There's a prototype tool called pinfer in the mypy repo (under `pinfer/`) than can do some runtime type inference of signatures, but it hasn't been updated in a long time.

**Comment by flip111** [comment]
One more question if i may .. how do i check an entire project? I didn't see a recursive option, or is mypy suppose to be paired with other libraries that provide features like this?

**Comment by JukkaL** [comment]
`-p packagename` checks a package recursively.

(Github issues aren't a great medium for asking multiple questions. I'd suggest using the Gitter chat in the future if you have small questions. You'll likely receive a reply faster there.)

**Comment by gvanrossum** [comment]
> I'd suggest using the Gitter chat in the future if you have small questions.

Oh, maybe we should change the top of README.md to call this out? Currently it says

> Got a question? File an issue!
> ------------------------------

while the Gitter link is hidden in a small button above that.

**Comment by JukkaL** [comment]
Yeah, it would probably be better to recommend gitter as the default for questions.

**Comment by gvanrossum** [comment]
Done.

**Comment by ilevkivskyi** [comment]
Now there is a plugin that provides some basic integration https://github.com/dropbox/mypy-PyCharm-plugin

**Comment by leinardi** [comment]
I just want to point out also [this other new plugin](https://github.com/leinardi/mypy-pycharm) that offers a full integration with PyCharm, including real-time code inspection:
![image](https://user-images.githubusercontent.com/273338/44950556-0e454100-ae4b-11e8-96bb-e1a7ba80cc2f.png)
