### ISSUE TITLE
Error accessing named tuple defined within import cycle

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3054]
Mypy doesn't recognize access to a named tuple defined in another module within an import cycle, if the other module is processed later than the module that contains the reference to the named tuple. 

Example:

```py
# a.py
from collections import namedtuple
from b import f
N = namedtuple('N', 'a')
```
```py
# b.py
import a
def f(x: a.N) -> None: ...  # Invalid type "a.N"
```

A potential fix is to process references to types in a later phase of semantic analysis than type definitions.

This is related to #3016.

**Comment by ilevkivskyi** [comment]
The same is true for ``TypedDicts`` and probably for all other "made-up" ``TypoInfos`` created during the second pass (not during the first, like for normal classes).
