### ISSUE TITLE
Mypy accepts None for int parameter with default value.

### ISSUE THREAD

**Issue by gwk** [python/mypy#3072]
```
def f(i: int = 0):
  return i + 1
f(None)
```

Mypy fails to reject this, which fails at runtime. `i` is strictly an `int`, even when no argument is provided.

**Comment by gvanrossum** [comment]
Try again with `--strict-optional`. Without that flag `None` is considered a member of every type (like null in Java).

**Comment by gwk** [comment]
This is why I keep getting confused. I'm trying to debug problems in strict mode with experiments in lax mode.
