### ISSUE TITLE
Error reported when '__annotations__' is accessed

### ISSUE THREAD

**Issue by peterazmanov** [python/mypy#3075]
```python
class A:
    a: int = 0
    b: int = 1

print(A.__annotations__)
```
mypy output:
`error: "A" has no attribute "__annotations__"`

checked with mypy v0.501

**Comment by JelleZijlstra** [comment]
I'll work on a PR for adding this and other NamedTuple features today.

**Comment by JelleZijlstra** [comment]
Actually, the sample code isn't even on a NamedTuple, so this is an independent issue.
