### ISSUE TITLE
Single overload of overloaded function can't be overriden in child class

### ISSUE THREAD

**Issue by kirbyfan64** [python/mypy#3079]
e.g. given `bug.pyi`:

```python
from typing import overload

class A:
    @overload
    def f(self, x: str) -> str: ...
    @overload
    def f(self, x: int) -> int: ...

class B(A):
    def f(self, x: int) -> int: ...
```

mypy says:

```python
bug.pyi:10: error: Signature of "f" incompatible with supertype "A"
```

which is particularly nasty when trying to deal with auto-generated stub files.

**Comment by gvanrossum** [comment]
The subclass doesn't use `@overload` so it really overrides all of the base class overloads. So I think this error is correct. You could work around it by adding
```
@overload
def f(self, x: str) -> str: return super().f(x)
@overload
def f(self, x: int) -> int: ...
```

**Comment by kirbyfan64** [comment]
Well, yeah, but this is in a stub file and is just trying to describe the interface, so I would think it would work...

**Comment by gvanrossum** [comment]
Oh wait, you want to state that the subclass doesn't accept strings? That's a violation of Liskov, but if that's really what you want you can use `# type: ignore` and it'll believe you.

**Comment by JukkaL** [comment]
@kirbyfan64 Closing this now -- if you still have questions we can reopen this.
