### ISSUE TITLE
Invalide type error when generic type is used to annotate a variable

### ISSUE THREAD

**Issue by poros** [python/mypy#3082]
Mypy fails to recognize a generic type defined using `TypeVar` when used to explicitly annotate a variable.
It works fine if the generic type is used in a function definition 

I was able to reproduce it with the following file:
```python
  1 from typing import TypeVar
  2
  3 class A:
  4     pass
  5
  6 class B(A):
  7     pass
  8
  9 class C(A):
 10     pass
 11
 12
 13 T = TypeVar("T", B, C)
 14
 15 a = B()  # type: T
 16 b: T = B()
 17
 18
 19 def func(r: T) -> None:
 20     print(r)
 21
 22
 23 if __name__ == "__main__":
 24     func(B())
```

This is the output:
```
foo.py:15: error: Invalid type "foo.T"
foo.py:16: error: Invalid type "foo.T"
```
Python version is 3.6.0 and mypy version 0.501.

**Comment by gvanrossum** [comment]
That code is invalid. You can't use type variables in the type of a global -- only inside a generic class or a generic function. Read the docs, and ask around on gitter if you need more explanation.
