### ISSUE TITLE
Mypy doesn't correctly determine the length of lists in starargs

### ISSUE THREAD

**Issue by kvdveer** [python/mypy#3087]
python
```
def foo(a: int, b: int):
    print(a, b)


bar = [1]
foo(*bar, 1)
```

The code above is marked as invalid by mypy 0.501:

```
# mypy test.py 
test.py:5: error: Too many arguments for "foo"
```
This happens when `foo` is a list or a generator. When foo is a tuple, mypy handles the code correctly.

**Comment by kirbyfan64** [comment]
The error could be better, but mypy isn't wrong. Lists and iterators have variable length, so there's no guarantee it's the correct size.

**Comment by kvdveer** [comment]
I agree that lists can be of any length, and ignoring the declaration of the list, there is no guarantee that the call is correct, and hence the code is uncheckable.

However, mypy doesn't claim the code is uncheckable, but it claims that the code is wrong. Worse, it does that inconsistently; when the starargs is used as the last argument, mypy accepts the code. Correctly functioning code gets marked as invalid, and invalid code gets marked as valid. Some examples:

python
```
def foo(a: int, b:int):
    pass

def foo(a: int, b: int):
    assert a == b == 1

# Valid code, rejected by mypy
foo(*[1], 1)
foo(*tuple([1]), 1)
foo(*(x for x in range(4) if x == 1), 1)

# Invalid code, accepted by mypy
foo(1, *[1, 1])
foo(*[1, 1, 1])
foo(*tuple([1, 1, 1]))
foo(*range(4))
```
