### ISSUE TITLE
Prohibit use of names in annotations that are undefined in runtime

### ISSUE THREAD

**Issue by pkch** [python/mypy#3088]
This type checks, but crashes in runtime with `NameError`:

```
class A:
    def f(x: A) -> None:
        pass
```

I think it's better if mypy reported an error `Name "A" should be a forward reference`.

**Comment by gvanrossum** [comment]
Oh, that's weird. I didn't even know mypy accepts that! Agreed it would be better to flag as error. (Outside stubs, and not in type comments of course.)

**Comment by ethanhs** [comment]
Closing as a duplicate in favor of #948, which has a bit more information.
