### ISSUE TITLE
Document where typing constructs are allowed

### ISSUE THREAD

**Issue by pkch** [python/mypy#3089]
By typing constructs I mean all the stuff that's defined in `typing`. And I don't mean the full grammar, but just a brief summary.

For example, where can I use `Union[int, str]`? I _think_ only inside type annotations and type alias definitions. In particular, I can't use it as a base class, or as an argument to `isinstance`, etc.

Where can I use `Generic[T]`? I _think_ only as a base class.

Where can I use `List[int]`? I _think_ inside type annotations, type alias definitions, and as a base class.

Where can I use `Tuple[int]`? I _think_ inside type annotations and type alias definitions.

Where can I use `List`? I _think_ anywhere an abstract class name is allowed (including in isinstance, as an item in collections, passed as an argument, etc.).

(Strictly speaking, Python runtime would not complain if I use, say, `Union` in some other contexts, like `a.x = Union[int, str]`, or `lst = [Union[int, str]]`, but there's nothing useful that can be done with it afterwards, so it doesn't count.)

This can be easily summarized because there are only a few relevant contexts:

- type annotations
- RHS of type alias definitions
- base class
- anywhere an abstract class name is allowed

And there's only a few groups of typing constructs; so we can simply say which group can be used where.

**Comment by gvanrossum** [comment]
Good idea. I think it should also be clarified in PEP 484, which is supposed to be the spec (but which in practice touches upon many areas only lightly through one or two examples -- we should fix that when we see how).

**Comment by hauntsaninja** [comment]
There's also `cast`. I'm going to close this though, since it's four years old and there never seemed to be too much demand for this.
