### ISSUE TITLE
Suggestion: Please consider adding a parameter to require that all vars have an explicitly type defined

### ISSUE THREAD

**Issue by jcrmatos** [python/mypy#3093]
Hello,

I know it's not Pythonic, but I'm sure there are others like me that prefer to have explicit type definitions.
So I'd like to suggest adding a parameter to require that all vars have an explicitly type defined.

Best regards,

JM

**Comment by graingert** [comment]
@jcrmatos do you have an example of some code where without type annotations it would not be explicit.

**Comment by jcrmatos** [comment]
Hello,

I always use explicit typing (not Pythonic but my option) and find that it helps overall, but specially in cases with Union or Tuple/List with mixed types.
It isn't something that couldn't be found by reading the API or source of the function, but it sure is faster and double checks any wrong assumption or documentation, because if I use a function that returns Union[List[str], Tuple[int]] and it's changed (eg. by someone else on the team) to something else, I will get a warning from mypy.

Here is a simple example (it uses a stdlib function, but imagine it's a 3rd party function):

```
def script_is_running(script_name):
    # type: (str) -> int
    """Check if script is running.

    :param script_name: script name to check.
    :return: number of scripts found with given name.
    """
    assert isinstance(script_name, str) and script_name != ''

    count = run('wmic process where (name="python.exe") get commandline '
                + '2> nul | find /c /i "' + script_name + '"', shell=True,
                stdout=PIPE).stdout.strip()  # type: Union[str, bytes]
    return int(count)
```

The objective of my suggestion is for those who want it (it's an optional parameter), to be able to force mypy to require the explicit typing and return warnings for those vars that were not explicitly typed.

Best regards,

JM

**Comment by gvanrossum** [comment]
Assuming that with "parameter" here you mean "command line flag", maybe `--disallow-untyped-defs` or `check-untyped-defs` or just `--strict` is what you want?

See http://mypy.readthedocs.io/en/latest/command_line.html#additional-command-line-flags

Please close if that's what you're looking for, else clarify.

**Comment by jcrmatos** [comment]
Hello,

Yes command line parameter = command line flag.

I'm already using those flags.
My mypy command is
mypy --strict-optional --warn-redundant-casts --disallow-untyped-defs --warn-unused-ignores --ignore-missing-imports --follow-imports silent --fast-parser source_file.py

However none of these do what I suggest.

What I'm suggesting is a command line flag (optional of course) that would make mypy show warnings for every variable that didn't have an explicit type definition on the source code.

Best regards,

JM

**Comment by jcrmatos** [comment]
Hello,

Just tried with --strict and it too doesn't do what I suggest.

Best regards,

JM

**Comment by kirbyfan64** [comment]
Do you mean that something like this:

```python
a: int = 0  # OK; a was explicitly typed.
b = 0  # NOT OK; b needs an explicit type annotation.
```

**Comment by gvanrossum** [comment]
I would be against such an option. It is unpythonic to require that.

**Comment by graingert** [comment]
It seems a bit like:

```js
ArrayList<String> cities = new ArrayList<String>()
```

but when the type is blindingly obvious, why wouldn't you rely on the type checker? What information does it actually give?

```python
x = x_factory()  # type X
```

what advantage do you get by specifying that the output of x_factory is whatever x_factory returns?

**Comment by jcrmatos** [comment]
Hello,

kirbyfan64
Yes that is exactly what I mean.
And of course the old syntax of
`a = 0  # type: int             # OK; a was explicitly typed.`

Best regards,

JM

**Comment by jcrmatos** [comment]
Hello,

gvanrossum
Has I said it would be optional, just like defining types on the source code and using type checking is optional, but exists in Python.

Best regards,

JM

**Comment by msullivan** [comment]
I don't think we're going to do this. It would probably actually be kind of fiddly to implement for a feature I think very few people would want to use
