### ISSUE TITLE
Question: how to handle wrapper functions returning instance of private class?

### ISSUE THREAD

**Issue by sybrenstuvel** [python/mypy#3094]
Hello,

I'm using `myfile = tempfile.NamedTemporaryFile()` to create a named temporary file. I want to pass this file to some other function, which also uses the `myfile.name` attribute.

When annotating the parameter as `def somefunc(myfile: tempfile.NamedTemporaryFile)`, MyPy complains: `error: Invalid type "tempfile.NamedTemporaryFile"`

This is because `tempfile.NamedTemporaryFile` is not a class but a function, which returns an object of type `tempfile._TemporaryFileWrapper`. I can make MyPy happy by declaring my function using `def somefunc(myfile: tempfile._TemporaryFileWrapper)`, but then my IDE (PyCharm) complains that I'm accessing a protected member of a module.

What would be the best way to handle this case?

PS: I'm using Python 3.6 and MyPy 0.501.

**Comment by ilevkivskyi** [comment]
Currently you could do either of two:
* Ignore the IDE warning
* Use ``# type: ignore`` or ``Any``

And just a bit of advertising, this will be solved soon by adding protocols (structural subtyping).

**Comment by sybrenstuvel** [comment]
Thanks!

**Comment by zupo** [comment]
Now that protocols are around, how should one solve this today?

**Comment by ilevkivskyi** [comment]
> Now that protocols are around, how should one solve this today?

For original question one can just define a protocol with a name attribute.
