### ISSUE TITLE
per file global config flags

### ISSUE THREAD

**Issue by graingert** [python/mypy#3095]
Currently my project is structured as:

```
setup.py
foo/
    __init__.py
    app.py
    view.py
tests/
    test_app.py
    test_view.py
    extra/
        test_extra.py
        utils.py
    ...
```

Where pytest collects test_app and test_view as top level modules. Pytest specifically warns against adding a \_\_init\_\_.py to tests.

I have:

```
[mypy]
python_version = 2.7
[mypy-foo.*]
disallow_untyped_defs = True
[mypy-test_*]
disallow_untyped_defs = True
```

but that doesn't cover extra.test_extra or extra.utils

I would like to be able to configure:
```
[mypy]
python_version = 2.7
[mypy-foo.*]
disallow_untyped_defs = True
[mypy-./tests/*]
disallow_untyped_defs = True
```

Where containing a '/' distinguishes between a module glob and a file glob

**Comment by gvanrossum** [comment]
If you can submit a simple PR that implements this feature I might accept it. (There's currently some code that treats `/` the same as `.` but it's old backwards compatibility code that we can drop.)

**Comment by graingert** [comment]
>  I might accept it. 

I like your style

**Comment by msullivan** [comment]
Probably we won't do this
