### ISSUE TITLE
HTTPResponse is not recognized as a subtype of typing.IO

### ISSUE THREAD

**Issue by pkch** [python/mypy#3108]
From [SO](http://stackoverflow.com/questions/42234589/python-mypy-type-hinting-shutil-copyfileobj-has-incompatible-type-unionhttpr):

```
request = urllib.request.Request(get_file_url, headers=self.data_api_headers)

with urllib.request.urlopen(request) as response:
    with open(export_file_path, 'wb') as out_file:

        shutil.copyfileobj(response, out_file)
```

This fails with `Argument 1 to "copyfileobj" has incompatible type "Union[HTTPResponse, BinaryIO]"; expected IO[Any]` because `HTTPResponse` derives from `io.BufferedIOBase`, which (despite being a binary IO) does not derive from `typing.BinaryIO` (nor does `io.RawIOBase`; also `io.IOBase` does not derive from `typing.IO`). 

When I attempted to derive them as I thought would make sense, I got errors because `__enter__` and other methods are defined both in `io.IOBase` and in `typing.BinaryIO`.

Not sure how to solve it.

**Comment by ilevkivskyi** [comment]
I think this kind of problems could be solved by protocols. I have encountered many similar issues recently. I will probably submit a PR today or tomorrow.

(Note that extensive changes to typeshed may be required, replacing nominal types with corresponding protocols).

**Comment by JelleZijlstra** [comment]
The IO types are especially complicated; there are lots of different "file-like" types with subtly different sets of methods. Maybe somebody will need to spend the time to carefully review all file-like types in the standard library to come up with a good set of protocols.

**Comment by ethanhs** [comment]
This came up again in https://github.com/python/typeshed/pull/2188#issuecomment-394198950 it seems.

**Comment by JelleZijlstra** [comment]
This seems like a typeshed bug, not a mypy bug.

**Comment by asottile** [comment]
I've copied this issue to typeshed: https://github.com/python/mypy/issues/3108
