### ISSUE TITLE
New syntax for NamedTuple defaults not supported

### ISSUE THREAD

**Issue by serin-delaunay** [python/mypy#3109]
[Python 3.6.1](https://docs.python.org/3/library/typing.html#typing.NamedTuple) introduced this syntax for `typing.NamedTuple`s with default values:
```py
from typing import NamedTuple

class Employee(NamedTuple):
    name: str
    id: int = 3

employee = Employee('Guido')
assert employee.id == 3
```
It runs without error in Python 3.6.1.

When checking this code with mypy 0.501, the following errors are generated:
```
ntt.py:5: error: Right hand side values are not supported in NamedTuple
ntt.py:7: error: Too few arguments for "Employee"
```

This affects usage in a similar way to https://github.com/python/mypy/issues/2683, but the syntax used and the errors produced are different.

**Comment by ilevkivskyi** [comment]
Thank you for reporting! This is already fixed in master, so that I am closing this. The feature will be available in the next release in few weeks. Please feel free to re-open if you are still not happy with something.
