### ISSUE TITLE
Generic types converted to Any

### ISSUE THREAD

**Issue by pkch** [python/mypy#3119]
```
T = TypeVar('T')

def f(x: int) -> None: ...

class C(Generic[T]):
    def g(self):
        x: C[T] = C()
        reveal_type(x) # Any
        f(x) # passes type check
```

Why is `x` not `C[T]`? It's clearly incompatible with `int`, and I think type check should error on it.

**Comment by ilevkivskyi** [comment]
How about annotating ``g`` with ``-> None``? There is also ``--disalow-untyped-defs``.

IIRC, PEP 484 says that non-annotated functions are not checked.

**Comment by pkch** [comment]
My bad :)
