### ISSUE TITLE
Better documentation for coercing rules

### ISSUE THREAD

**Issue by pkch** [python/mypy#3124]
(Based on #3111)

Both me and someone who wrote `testTupleMethods` thought that this is a type error:

```
x: int
x = True
```

Apparently, it passes type check (even with `--strict-boolean`); I suppose it's fine since there are idioms that use this coercion (especially in numeric applications / numpy etc.), but maybe we should document which coercions are allowed by the type checker. 

Maybe It's enough to say that "any type coercion that's acceptable in runtime is also acceptable to mypy (for example, `bool` --> `int`, `int` --> `float`, etc.".  But it's probably worth clarifying that runtime only checks types (and therefore may need to coercion rules) only for arguments of builtin functions, while mypy checks types (and therefore uses coercion rules) also for assignment, for arguments of user-defined functions, etc.

**Comment by JelleZijlstra** [comment]
This is not a coercion: `bool` is a subtype of `int`.

**Comment by pkch** [comment]
Ah makes sense. How about this then:

```
def f() -> bool:
    pass
```

It passes type check with `--strict-boolean`.

**Comment by JelleZijlstra** [comment]
Is that because mypy doesn't type check functions with "trivial bodies"?

**Comment by pkch** [comment]
Hmm, so the only coercion mypy does is `int` -> `float`?

**Comment by JelleZijlstra** [comment]
int -> float, float -> complex in both py2 and 3, bytearray -> bytes in py3, and str -> unicode and bytearray -> str in py2. See the constants at the top of semanal.py.

**Comment by gvanrossum** [comment]
I think there are a few more, search the code for "promotions".

**Comment by pkch** [comment]
There's also this behavior:

```
a = 1.5
reveal_type(a) # float
a = 1
reveal_type(a) # int
a = 1.5
reveal_type(a) # float
```

where mypy doesn't coerce `int` to a `float`, but instead changes type of `a` from `float` to a special type `float that is temporary int`. It's not just a regular `int` type (even though it's printed like one) because if you delete the first assignment, it will fail type check:

```
a = 1
reveal_type(a) # int
a = 1.5  # E: Incompatible types in assignment (expression has type "float", variable has type "int")
```

**Comment by gvanrossum** [comment]
Let me see if I can adjust your mental model for you.

The first assignment, whether it is annotated or not, determines the type. If there is an annotation that's the type, if there's not, the inferred type of the expression determines the type.

The other part of the mental model that needs adjusting is the existence of mypy's "binder" which separately keeps track of what type a variable *currently* can have. It is mostly useful for things that are conditional on isinstance(), but it does its thing in unconditional code too.

So, for example:
```python
a = 1
# The type determined is int
a = 1.5  # Error, not a subclass of int
```
vs. 
```python
a = 1.5
# The type determined for `a` is float
if bool():  # That's a stand-in for some random condition
    a = 1  # Fine, int is a subclass of float
    # The binder knows `a` is an int in this block
    range(10)[a]  # OK (would fail with float)
# Here `a` is still considered a float
range(10)[a]  # Error (can't index with float)
```

There is actually debate about what should happen if the initial assignment has an annotation that is wider than the expression, like
```python
a = 1  # type: float
# Should `a` be considered int or float here?
```
There should be an issue for that, if you want to discuss it further please find it and read the comments there first (and respond there).

**Comment by pkch** [comment]
@JelleZijlstra  The code you mentioned in `semanal.py` does not distinguish promotions from subtyping:

> For example, `int` is considered a subtype of `float`, even though there is no subclass relationship. 

This makes things a lot cleaner.

@gvanrossum Totally makes sense, I just didn't realize binder might act outside `isinstance`.

As for the list of all "promotions" (i.e., special-cased subtype relationships), it would seem to be just the ones in `semanal.TYPE_PROMOTIONS*`. 

Of course, in addition there are numerous (and evolving) promotion rules:
- `X <: Y` if `X <: T <: Y`
- `X <: Y` if they correspond to a class and its base class 
- `X <: Union[X, Y]`
- `X[T] <: Y[U]` if `X <: Y` and `T <: U`
etc.
