### ISSUE TITLE
Indexing Enum type objects fails sometimes

### ISSUE THREAD

**Issue by jboning** [python/mypy#3137]
Assume this definition of `Color`:

```
from enum import Enum
class Color(Enum):
    red = 1
    green = 2
    blue = 3
```

`Color['red']` works, and 'val : Color = Color['red']` both work, but `val = Color['red']` does not work:
```
error: Name 'red' is not defined
error: "Color" expects no type arguments, but 1 given
```

Reference #741

**Comment by gvanrossum** [comment]
Whoops, yes, definitely a bug. Not sure yet how to fix it.
