### ISSUE TITLE
Creating an alias type for weakref.WeakValueDictionary in python 2

### ISSUE THREAD

**Issue by maffoo** [python/mypy#3142]
I have a class which has a class member that stores a cache of instances in a `weakref.WeakValueDictionary`. Mypy seems to expect a type of the form `weakref.WeakValueDictionary[A, B]` for this, which I can write in a `type:` comment like so:
```python
class ClassWithLongishName(object):
    cache = weakref.WeakValueDictionary()  # type: weakref.WeakValueDictionary[KeyType, ClassWithLongishName]
```
(The `KeyType` is unimportant for our purposes.) The problem with this is that the line is now too long; I'd like to shorten it but there doesn't seem to be any way to make this work:
- Option 1: wrap the comment. Mypy doesn't seem to allow this. Nor can I place the comment on the line before or after the variable declaration, AFAICT.
- Option 2: create an alias type. The expression `CacheType = weakref.WeakValueDictionary[KeyType, ClassWithLongishName]` is not valid in python 2, because the required `__getitem__` method does not exist; is there some other way to create this alias type?

I'd be fine with a solution to make option 2 work, though I do feel like situations could still arise where it would be nice to have a way to wrap or otherwise reformat  type comments as in option 1 above. Otherwise, one might have to add _yet more_ special comments to keep the linter from complaining about the long line...

**Comment by ilevkivskyi** [comment]
There is a possible solution/workaround for this:
```python
import weakref
from typing import TYPE_CHECKING

class KeyType: ...

if TYPE_CHECKING:
    Cache = weakref.WeakValueDictionary[KeyType, ClassWithLongishName]

class ClassWithLongishName(object):
    cache = weakref.WeakValueDictionary() # type: Cache
```
This code passes mypy from current master and gives no runtime errors. The ``TYPE_CHECKING`` constant is ``False`` at runtime, but PEP 484 specifies that all type checkers should treat it as being always ``True``.

Note that you will need to wrap the alias in string (as forward references) to use it in annotations (not in comments), since it actually does not exist at runtime:
```python
def clear(cache: 'Cahce') -> None:
    ...
new_cache: 'Cache' = old_cahce.copy() # in Python 3.6+
```

**Comment by maffoo** [comment]
Thanks, @ilevkivskyi, that works for me.
