### ISSUE TITLE
Type variables bounded by generic types cannot be used with `Type`

### ISSUE THREAD

**Issue by pkch** [python/mypy#3148]
```
T = TypeVar('T')
class X(Generic[T]): ...

U = TypeVar('U', bound=X[T])  # Invalid type "test.T"
def f(cls: Type[U]) -> U:  # Unsupported type Type["U"]
    return cls()
```

At first glance, this is a duplicate of #2756 . However, that issue is about the first error message, and this issue is about the second.

In #2756 (as here), the "Invalid type test.T" message goes away once we provide a concrete parameter for `X`, like `U = TypeVar('U', bound=X[int])`. The `"Unsupported type Type["U"]` message, however, never goes away as long as `X` remains generic.

I have a use case: `f` is supposed to convert some data into a `U`; the first argument is the class into which it is supposed to convert. The function uses some methods that are defined in `class X`, that's why I need to bound `U`.

**Comment by ilevkivskyi** [comment]
PEP 484 and ``typing`` docs currently allow only a class, a union of classes, and ``Any`` as arguments for ``Type[]`` and explicitly prohibit other constructs:

> The only legal parameters for ``Type`` are classes, unions of classes, and ``Any``.

I could see possible benefits for allowing also type variables, but I think this needs discussion.

**Comment by pkch** [comment]
[Here is](https://github.com/python/mypy/issues/2756#issuecomment-292771413) my use case for this feature.

BTW, if type variables are prohibited in `Type`, why does this type check?

    T = TypeVar('T')
    def f(cls: Type[T]) -> T:  # ok
        return cls()

**Comment by ilevkivskyi** [comment]
@pkch Good point, there is some contradiction in PEP 484, on one hand it prohibits anything except classes, unions of classes, and ``Any``, on the other hand it explicitly allows ``Type[T]`` as an annotation in the section on self-types.

**Comment by gvanrossum** [comment]
I guess we'll have to update that part of PEP 484.

**Comment by pkch** [comment]
Actually, type variables cannot be bound by (unparamtrized) generic types as discussed in #2756 . (The reason I thought they could was due to #3153; once that's fixed, this issue will disappear.)
