### ISSUE TITLE
"if PY{2,3} and X" doesn't ignore the X when run in other python version

### ISSUE THREAD

**Issue by euresti** [python/mypy#3156]
Simple example:
```
from six import PY2

if PY2 and any({'foo': 'bar'}.iterkeys()):  # error: Dict[str, str] has no attribute "iterkeys" when checking py3
    pass

if PY2:
    if any({'foo': 'bar'}.iterkeys()):  # No error
        pass
```
Note: The same thing applies to `PY3` when run with `--py2`

Sometimes it's cumbersome to split it when you have a series of `if, elif, else` cases, like this:

```
if isinstance(node, ast.Name):
    ...
elif isinstance(node, ast.Num):
    ...
elif PY3 and isinstance(node, ast.Starred):   
    ...
else:
    // unhandled node type!
```

**Comment by ilevkivskyi** [comment]
This applies not only to ``six.PY2``, direct use of ``sys.version_info[0] < 3`` behaves exactly the same way. It looks like #3158 take the right way to fix this.

**Comment by samertm** [comment]
Unless I'm missing something, I believe #3158 along with #3643 completely fix this issue.

**Comment by ilevkivskyi** [comment]
Yes, this issue is fixed on master.
