### ISSUE TITLE
Test format: [out], [out1] and [out2] are valid python expressions

### ISSUE THREAD

**Issue by elazarg** [python/mypy#3182]
I guess it's no big-deal, but it will be nice to replace them with a clear non-python expression: `[out pre]` and `[out post]`.
The gain is making the format easier to parse (using a simple, clear regex) and avoiding potential (rare) puzzling errors. It will also make the tests more readable: until recently I did not know that `[out2]` is a thing.

It is a big impact for such a small gain, but it can be easily automated.

**Comment by gvanrossum** [comment]
No, let's not do this. It's not your codebase.
