### ISSUE TITLE
--strict-boolean allows logical not to be applied to non-booleans

### ISSUE THREAD

**Issue by pkch** [python/mypy#3185]
```
a: str

if a:  # Condition must be a boolean
    1

if a and True:  # Condition must be a boolean
    1

if not a:  # No error
    1
```

The third `if` statement should also get the same error message.

**Comment by gvanrossum** [comment]
IMO the fix is to get rid of `--strict-boolean`. It is unPythonic. :-)

**Comment by pkch** [comment]
And, you're not even joking!! :) If I'm the only one using it, we should seriously get rid of it to lower maintenance.

**Comment by gvanrossum** [comment]
That needs to be negotiated with the OP who requested it and implemented it. Can you do a git blame/log to figure out who that was and which PR(s) to use to reach them?

**Comment by gvanrossum** [comment]
Oh, the blog post says it's Alex Frieder. @afrieder see comments ^^.

**Comment by afrieder** [comment]
I just implemented it on someone else's request. If people aren't using it I'm perfectly fine with reverting the commits.

**Comment by gvanrossum** [comment]
We should at least ask that person if they use it. IMO it makes `--strict` (which implies it) less useful, since nobody writes code that conforms to `--strict-optional` except people expecting Java.

**Comment by gvanrossum** [comment]
The original request is #1730 and the OP is @tigrfhluerh. See ^^

**Comment by Herst** [comment]
As mentioned in Gitter, I had a use case for it where I would temporarily enable it in order to find places where explicit `is [not] None` checks would be more appropriate, e.g. the return values of `re.match()`/`re.search()`.

**Comment by gvanrossum** [comment]
Hm, but a successful result of those types is never falsey.

**Comment by Herst** [comment]
Exactly, which is why checks like `if not reMatchReturnVal:` can be changed into `if reMatchReturnVal is not None:` and this what I used or rather repurposed `--strict-boolean` for.

**Comment by gvanrossum** [comment]
Eek. That looks worse than the original and surely there is no measurable speed-up even if that was all you did in a tight loop.

Let's close this and instead start a new issue "Drop --strict-boolean".

**Comment by pkch** [comment]
Before we proceed with this, I just wanted to clear up one thing based on the earlier discussion on gitter.

Would this flag become useful if it was restricted just to the cases where it's actually unsafe? Specifically the usage of non-boolean variable in a boolean context is unsafe only if it has more than 1 values that is interpreted as `False`:

```
def f(x: int) -> None:
  if x:  ... # safe
 
def g(x: int = None) -> None:
  if x:  ... # unsafe; is x 0 or None?
 
def h(x: set) -> None:
  if x: ... # safe

def i(x: set = None) -> None:
  if x: ... # unsafe; is x an empty set or None?

def j(x: Callable[[int], int] = None) -> None:
  if x: ... # safe

def k(x: bool = None) -> None:
  if x: ... # unsafe; is x False or None?

It seems very easy to identify unsafe cases, using the [truth value testing](https://docs.python.org/3/library/stdtypes.html#truth-value-testing) rules. The usage is unsafe if the variable type is a `Union` that includes more than one of the following types:

- `None`
- a numeric type
- a subtype of Sized
- a type that has `__bool__` method defined

Do you want me to check if restricting `--strict-boolean` to just these cases would make sense, perhaps using mypy own source code?

**Comment by gvanrossum** [comment]
Please continue the discussion in #3195.
