### ISSUE TITLE
Expected "Sized" for a class defining "__len__"

### ISSUE THREAD

**Issue by lopuhin** [python/mypy#3187]
This program:
```
class Class:
    def __len__(self):
        return 1

x = Class()

print(len(x))
```
gives the following error with mypy 0.501, Python 3.5:
```
$ mypy t.py
t.py:7: error: Argument 1 to "len" has incompatible type "Class"; expected "Sized"
```

I expected it to pass the check because ``Class`` has ``__len__`` defined.

**Comment by ilevkivskyi** [comment]
Thank you for reporting this! This is a known issue (see PR #3132 that will fix this).

In the meantime you could just add ``typing.Sized`` as an explicit base for ``Class``:
```python
from typing import Sized

class Class(Sized):
    def __len__(self) -> int:
        return 1

x = Class()

print(len(x))  # Now this works
```

**Comment by lopuhin** [comment]
Thanks, and it's great that the fix is on the way 👍

**Comment by gvanrossum** [comment]
Closing as a duplicate.
