### ISSUE TITLE
Enable AppVeyor rolling builds to speed up tests

### ISSUE THREAD

**Issue by pkch** [python/mypy#3188]
It seems that AppVeyor does not cancel the builds for commits that have been superceded on the same branch. Given that we are only allocated 1 VM, this results in a large queue when more than 1 commit is pushed to the same branch within ~15 min (the time it takes to complete the build).

We should consider enabling [Rolling Builds](https://www.appveyor.com/docs/build-configuration/#rolling-builds) option in AppVeyor settings that would automatically cancel any build on the same branch that related to a commit that's no longer the head of the branch.

I am not 100% sure but I think the [equivalent feature](https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation) of Travis CI is already enabled; if not, it's probably worth doing (although Travis builds are far faster than AppVeyor because we get 5 rather than 1 VMs; so the queueing up problem happens much less often).

**Comment by gvanrossum** [comment]
Well I turned something on (https://ci.appveyor.com/project/gvanrossum/mypy/settings, General, search for "Rolling builds". Let's see how it goes. Googling this topic I found several discussions of how it's not working very well. We'll need to keep an eye on it, and I am keeping this issue open until we know that it's reliable and useful.

**Comment by pkch** [comment]
I read the problem reports; the good news is that

- they all seem to experience failing builds rather than incorrectly passing builds (so it's very easy to spot a problem)
- they seem to involve limits to AppVeyor flexibility in handling more complex requirements, rather than due to any bugs in AppVeyor's promised behavior

That said, if anyone experiences weird behavior with CI, please post your concerns here, and I'll investigate.
