### ISSUE TITLE
Generic function as first argument to map fails

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3193]
From https://github.com/python/typeshed/issues/1178:

> `map(tuple, [ [2, 3] ])` throws
>
> `error: Argument 1 to "map" has incompatible type Tuple[_T_co, ...]; expected Callable[[List[int]], Tuple[_T_co, ...]]`
>
> However, this is valid python code.

Here's a more self-contained example that reproduces the problem:

```py
from typing import Callable, TypeVar

T = TypeVar('T')
S = TypeVar('S')

def f(fn: Callable[[T], S], x: T) -> None: pass
def g(x: T) -> T: pass

f(g, 1)  # Argument 1 to "f" has incompatible type Callable[[T], T]; expected Callable[[int], T]
```

**Comment by ilevkivskyi** [comment]
I think this is just a duplicate of https://github.com/python/mypy/issues/1317, passing one generic callable as an argument to another generic callable causes type variables leaking.
