### ISSUE TITLE
`re` match objects fail validation when using string as argument to `group`

### ISSUE THREAD

**Issue by posita** [python/mypy#3199]
This is probably a special case of #1141, but this usage is explicitly documented in the standard library. From the docs for `re` match objects for both [version 2](https://docs.python.org/2/library/re.html#re.MatchObject.group) and [version 3](https://docs.python.org/3/library/re.html#re.match.group) (**_emphasis_** added):

> If the regular expression uses the `(?P<name>...)` syntax, the _groupN_ arguments **_may also be strings_** identifying groups by their group name.

```py
# re_match_group.py
from __future__ import print_function
import re
m = re.search(r'^(?P<foo>bar)$', u'bar')
ms = m.group(u'foo')
print(ms)
```

Result fails in 2 …

```
$ mypy --version
mypy 0.501
$ python2.7 re_match_group.py
bar
$ mypy -2 re_match_group.py
re_match_group.py:5: error: No overload variant of "group" of "Match" matches argument types [builtins.unicode]
```

… and 3 …

```
$ python3.6 re_match_group.py
bar
$ mypy re_match_group.py
re_match_group.py:5: error: No overload variant of "group" of "Match" matches argument types [builtins.unicode]
```

**Comment by gvanrossum** [comment]
Can you file that in typeshed instead?

**Comment by posita** [comment]
Ah! Sorry. I knew better. 😞  It's already filed: python/typeshed#273. Apologies!
