### ISSUE TITLE
Require explicit return if return type is something other than Any or None

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#320]
Currently a function does not need an explicit return statement, since falling off the end of the function results in an implicit None return value, which is compatible with all types. This might be sometimes used for functions with empty bodies, but it should not be accepted at least for functions with non-empty bodies, since forgetting to return a value in some code paths is a fairly common programming error.

For example, this should not be accepted:

    def f(x: int) -> int:
        if x > 5:
            return 1

We could probably disallow a missing return for empty function bodies as well. For abstract methods, we'd require either raising NotImplementedError or providing a default implementation that returns a value.

**Comment by rwbarton** [comment]
I'm going to close this as a duplicate in favor of #1229, which has an active discussion.
