### ISSUE TITLE
Optional typing import

### ISSUE THREAD

**Issue by llchan** [python/mypy#3216]
I have some PY2+PY3 code that I'm adding mypy type annotations to, but the PY2 runtime environment does not have the `typing` backport module. The current workaround is to put a try/except around the typing import, but that looks a bit ugly, and even if the environment did have it, or if I were running in PY3, I dont know that I want that imported at runtime.

Can we support some sort of comment-based directive at the top of the file that mypy can parse?

Apologies if this has already been asked, I tried searching but there is a lot to sift through.

**Comment by JelleZijlstra** [comment]
This works:
```
$ mypy -c '''
if False: from typing import Any
x: Any = 0
'''
```

**Comment by llchan** [comment]
Neat, that sounds good enough for now. A directive might be more intuitive for a newcomer though, so if there's a wishlist for long term enhancements that might be something to consider.

**Comment by gvanrossum** [comment]
New comment-base directives have other friction though. The recommended pattern is
```
MYPY = False
if MYPY:
    import typing
    # OR: from typing import ...
```

**Comment by ArneBachmann** [comment]
How can the `MYPY` variable ever be `True` if set to `False`? How does it solve the problem of a missing typing module? I don't understand that solution.

**Comment by ethanhs** [comment]
@ArneBachmann See https://mypy.readthedocs.io/en/latest/command_line.html#platform-configuration for more. Essentially despite getting set to `False` for runtime, mypy considers `MYPY` to be `True` (This is just a decision made by mypy). This allows you to have mypy consider the typing module imported without actually importing it at runtime. (Hence your code will pass typecheck and run as well). Also please ask questions on our gitter https://gitter.im/python/typing.
