### ISSUE TITLE
Support for custom Enum base class

### ISSUE THREAD

**Issue by ambv** [python/mypy#3217]
Much of our internal Python code uses a custom Enum class as an optimization above the built-in Enum type. These should be treated the same as built-in enums in terms of the custom enum handling in mypy, but since mypy looks for `enum.Enum` as the base-class in order to trigger the `is_enum` behavior, we can't get this to trigger without monkey-patching mypy.

There's a variety of solutions that could help, a couple that could work:
1) Allow a list of additional Enum base classes to be passed in to mypy or specified in the `.ini` file, and use those in addition to `enum.Enum`.
2) Allow for an annotation on the custom `Enum` base class that opts that class and any subclasses into the `is_enum` behavior

We're happy to extend mypy with either of those options (or other suggested ones), but we wanted to get alignment here before starting work.

**Comment by gvanrossum** [comment]
Our own custom enums are so crusty that they don't work anyways. :-(

Maybe a better approach would be to use the EnumMeta class as a flag instead?

**Comment by ambv** [comment]
> Maybe a better approach would be to use the EnumMeta class as a flag instead?

Could we make this work with a C-based Enum implementation? The thing is, our optimized version is Cython, we wrote it for perf reasons.

**Comment by gvanrossum** [comment]
I don't understand enough about your problem to propose a solution. Can't you create a stub for it that pretends it derives from enum.Enum?

Alternatively, if we changed mypy so that instead of checking "is the type exactly enum.Enum (or a few others)" it checked "is this type's metaclass derived from enum.EnumMeta", *then* could you write a stub?

**Comment by carljm** [comment]
A stub with `from enum import Enum` works just fine for us. Thanks for the suggestion! Slightly embarrassed that none of us thought of that; guess I need to get used to thinking of stubs as a way to lie to mypy ;-)

**Comment by JukkaL** [comment]
@carljm Can we close this issue now that you have a workaround?

**Comment by carljm** [comment]
@JukkaL Yes, fine to close as far as I'm concerned.
