### ISSUE TITLE
Mypy 0.4.2 fails on a single line script importing module "pkg_resources"

### ISSUE THREAD

**Issue by ttsiodras** [python/mypy#3230]
Mypy version 0.4.2 generates this error in my machine...

    $ pip3 freeze | grep mypy-lang
    mypy-lang==0.4.2

    $ cat bug.py 
    import pkg_resources

    $ mypy bug.py 
    /home/assert/.local/lib/mypy/typeshed/third_party/3/pkg_resources/__init__.pyi:10: note: In module imported here,
    bug.py:1: note: ... from here:
    /home/assert/.local/lib/mypy/typeshed/stdlib/3/zipfile.pyi: note: In member "getinfo" of class "ZipFile":
    /home/assert/.local/lib/mypy/typeshed/stdlib/3/zipfile.pyi:21: error: The erased type of self 'builtins.str' is not a supertype of its class 'zipfile.ZipFile'
    
It could be a problem with my installation - or a bug in mypy...
Can anyone confirm?

**Comment by gvanrossum** [comment]
Does it also fail with the latest release? On master? 0.42 is really old. Also note it's now pip install mypy, no longer mypy-lang.

**Comment by ttsiodras** [comment]
Indeed, it doesn't - sorry about the noise, didn't realize the name had changed. 
Closing.
