### ISSUE TITLE
calling items() on Union of Dicts variable claims the return value is not iterable

### ISSUE THREAD

**Issue by tjltjl** [python/mypy#3240]
The code

        x : Union[Dict[int, int], Dict[str, str]] = dict(a='b')
        for a, b in x.items():
            print(a, b)

yields

error: 'Union[Tuple[builtins.int*, builtins.int*], Tuple[builtins.str*, builtins.str*]]' object is not iterable

Using just Dict[str, str] instead of the Union passes.

The code (naturally) runs in python, and both elements in the union are iterable...

**Comment by ilevkivskyi** [comment]
I just checked, it looks like this is another multi-assign from Union problem.
@elazarg I think this is an important feature, and it would be great if you will continue working on your PR.
