### ISSUE TITLE
Keyword arguments of __call__ are not interpreted correctly

### ISSUE THREAD

**Issue by Sterbic** [python/mypy#3241]
I looks like mypy drops all keyword arguments of the `__call__` function of a class and recognises only positional arguments.

Code example:

```
class Formatter:
    def __call__(
        self,
        message: str,
        *,  # same behaviour with and without 
        bold: bool = False,
    ) -> str:
        if bold:
            message = f"** {message} **"
        return message

formatter = Formatter()
print(formatter("test", bold=True))
```

Mypy error:
`test.py:13: error: Unexpected keyword argument "bold" for "__call__" of "Formatter"`

**Comment by gvanrossum** [comment]
Yes, confirmed and seems specific to `__call__`.

**Comment by ilevkivskyi** [comment]
Adding ``__call__`` to ``MAGIC_METHODS_ALLOWING_KWARGS`` in ``sharedparse.py`` fixes the issue. I wonder why it is not there now, do older versions of Python not allow kwargs in ``__call__``?

**Comment by gvanrossum** [comment]
I assume it was just an oversight. Do the tests pass with that one change? Then it's worth adding a test specifically for `__call__` with kwargs and push a PR.

**Comment by ilevkivskyi** [comment]
OK, here is the PR https://github.com/python/mypy/pull/3245
