### ISSUE TITLE
% formatting with a bytestring template given as a variable fails

### ISSUE THREAD

**Issue by cyang1** [python/mypy#3247]
Running mypy on the following code gives: `error: Unsupported left operand type for % ("bytes")`.
```
FORMAT = b'foo%s'
print(FORMAT % b'bar')
```
Note that `print(b'foo%s' % b'bar')` passes without error.

**Comment by gvanrossum** [comment]
Reproduced.

**Comment by JelleZijlstra** [comment]
I think this is a typeshed issue, there's no `__mod__` on bytes in builtins.pyi.

**Comment by gvanrossum** [comment]
Good call. Given that this is in part a mypy feature, let's use this issue to track it.

**Comment by gvanrossum** [comment]
Confirmed this is fixed by https://github.com/python/typeshed/issues/1212.
