### ISSUE TITLE
Signatures of overloaded methods are incompatible with supertypes, even if they really are

### ISSUE THREAD

**Issue by kirbyfan64** [python/mypy#3262]
e.g.

```python
from typing import overload

class A:
    @overload
    def f(self, x: str) -> str: ...
    @overload
    def f(self, y: int) -> int: ...

class B(A):
    @overload
    def f(self, x: str) -> str: ...
    @overload
    def f(self, y: int) -> int: ...
    @overload
    def f(self, z: bytes) -> bytes: ...
```

IMO in this case, it should still be compatible, since `B` supports `A`'s full API, just with another extra function.

**Comment by sixolet** [comment]
This looks like me, if somebody else doesn't get it first.

**Comment by kirbyfan64** [comment]
@sixolet I think you might be around 10 seconds too late... ;)

**Comment by gvanrossum** [comment]
@sixolet Can you review @kirbyfan64's review?

**Comment by sixolet** [comment]
Yep, though probably tomorrow.

**Comment by gvanrossum** [comment]
Did this get fixed or not?

**Comment by sixolet** [comment]
PR still out last I checked.
