### ISSUE TITLE
Can't create a type alias targeting None

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3269]
An alias that refers to `None` doesn't work:

```py
N = type(None)
NN = None
n: N  # Invalid type "t.N"
nn: NN  # Invalid type "t.NN"
```

**Comment by ilevkivskyi** [comment]
I think we could support one of these forms. The second one ``N = None`` looks much more like a variable assignment. The first one ``N = type(None)`` looks easy to support by a simple special casing, although this is not specified by PEP 484 and a bit arbitrary.
