### ISSUE TITLE
Use bytes and bytearray consistently in the library stubs

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#33]
The use of bytes and bytearray in the library stubs is inconsistent. Some modules do not properly support bytes objects (e.g. os) even though they work in Python. 

Also some Python functions accept only bytes objects, but others accept bytearrays as well. This needs to be reflected in the library stubs (however, Python documentation is not always explicit about this, which complicates the issue).

**Comment by gvanrossum** [comment]
See #1141. There's a lot to do here but we needn't keep this particular issue open.
