### ISSUE TITLE
mypy_extensions is listed as owned by David Foster

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#3311]
See https://github.com/python/mypy/blob/master/extensions/setup.py#L37

David Foster did indeed create the first version but I presume he doesn't want to be bothered about the subsequent additions?

We should probably change this to "The mypy developers" -- but where to point the email? Maybe it can be omitted. The url might also better point to GitHub.

Attn: @davidfstr

**Comment by davidfstr** [comment]
+1 to set the contact name & email more appropriately. I wasn't sure what to set it to when I created the package originally.
