### ISSUE TITLE
Type[X] not compatible with metaclass of X

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3326]
The second-to-last line should probably be accepted by mypy, but it currently generates an error because `Type[A]` isn't compatible with the metaclass of `M`:

```py
from typing import Type

class M(type): pass
class A(metaclass=M): pass

a: Type[A] = A
m: M = a    # error, but should be okay
m2: M = A   # no error
```

**Comment by elazarg** [comment]
This was introduced by me in #2837: the metaclass lookup is performed on the wrong side.

**Comment by elazarg** [comment]
What's more, in the same PR I've made M compatible with Type[A], even though it is demonstrably unsafe... I would like to fix this too, but EnumMeta is relying on it.
