### ISSUE TITLE
Code freeze pending review of bugfix release

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#3335]
It's possible we need to issue a bugfix release (0.511) on Monday or Tuesday, because there are at least two regressions that *may* be serious enough.

- #3333 
- #3332 

Until we've decided how to do this we should not commit anything to master. (I don't recall we have written down a process for bugfix releases yet.)

**Comment by ilevkivskyi** [comment]
As I understand this can be closed, since the feature freeze is over.
