### ISSUE TITLE
Strict optional: Any narrowing to None in a conditional gets "stuck" at None

### ISSUE THREAD

**Issue by lincolnq** [python/mypy#3338]
I think a code sample will explain:

```
from typing import Any, Optional

def narrow_any_to_none() -> None:
    """Broken case: If 'v' starts with type Any, then it gets "stuck" with type
    None after the if."""
    v = 1 # type: Any

    if v is None:
        reveal_type(v) # E: Revealed type is 'builtins.None'
        v = 2
        reveal_type(v) # E: Revealed type is 'builtins.None'
        v + 3 # E: Unsupported operand types for + (None and "int")


def narrow_optional_to_none() -> None:
    """Working as expected: If 'v' starts with an Optional type, then you can
    re-assign it no problem after the if."""
    v = 1 # type: Optional[int]

    if v is None:
        reveal_type(v) # E: Revealed type is 'builtins.None'
        v = 2
        reveal_type(v) # E: Revealed type is 'builtins.int'
        v + 3
```

In v0.510 and on the latest master, `mypy --strict-optional` on the above code produces the above errors. I expected the 2nd reveal_type to reveal 'builtins.int' and for the v + 3 line to pass type checking. (Without strict optional, everything works as expected.)

**Comment by gvanrossum** [comment]
@ddfisher Looks like a binder bug?

**Comment by lincolnq** [comment]
I just submitted PR #3361, which I think fixes this. However, attributing the problem to strict-optional was actually a red herring. So I created a new test case for which strict-optional isn't needed. Someone might want to remove the strict-optional tag.
