### ISSUE TITLE
Two crashes on recursive named tuples

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3340]
While working on #3322 I have found two more crashes:
```python
N = NamedTuple('N', [('x', N)])
n: N
```
crashes with ``RecursionError`` and
```python
class N(NamedTuple):
    x: N
class M(NamedTuple):
    x: M

n: N
m: M
lst = [n, m]
```
crashes with ``AssertionError`` in ``join_instances_via_supertype``. I didn't try ``TypedDict`` but most probably it will have similar problems.

There is actually a fundamental question here: what _should_ be the ``join(N, M)``? @JukkaL do you have any ideas? One possible option would be to detect recursive joins and just return ``object`` for them (maybe also ``UninhabitedType`` for recursive meets).

**Comment by JukkaL** [comment]
`object` would be consistent as the result of `join(N, M)`. A recursive type like `T` where `T = Tuple[T]` would perhaps also be a reasonable result, assuming we were able to represent them. (The only reasonable common use case where recursive types could be useful that I've seen is JSON, so this is not a valid motivating example for recursive types.)
