### ISSUE TITLE
Suggested improvement for wording of an error

### ISSUE THREAD

**Issue by KitB** [python/mypy#3341]
I recently had trouble understanding an error output along the lines of:

```
Type argument 1 of "<function name>" has incompatible value "<a type that doesn't fit the TypeVar>"
```

Would it be possible to output something more along the lines of:

```
TypeVar "T" cannot be a "<wrong type>" (from first argument to "<function name>")
```

**Comment by ilinum** [comment]
I think that's a great suggestion!
`TypeVar "<typevar name>" cannot be a "<wrong type>" (from argument 1 to "<function name>")`

@KitB are you interested in taking a stab at it yourself? If not, I can work on it.

**Comment by KitB** [comment]
I don't really have the time, go ahead.
