### ISSUE TITLE
`List[Union[...]]` is not always satisfied by valid inputs.

### ISSUE THREAD

**Issue by tomchristie** [python/mypy#3351]
When a list of unions is used, mypy will incorrectly error when a subset of the possible union types is used...

**example.py**:

```python
from typing import List, Union

def mean(numbers: List[Union[int, float]]) -> float:
    return sum(numbers) / len(numbers)

some_numbers = [1, 2, 3, 4]
mean(some_numbers)
```

**console**:

```
$ mypy --version
mypy 0.470
$ mypy example.py 
example.py:7: error: Argument 1 to "mean" has incompatible type List[int]; expected List[Union[int, float]]
```

Presumably the inferred `List[int]` ought to be able to satisfy `List[Union[int, float]]`, right?

**Comment by ilevkivskyi** [comment]
> Presumably the inferred ``List[int]`` ought to be able to satisfy ``List[Union[int, float]]``, right?

No, ``List`` is invariant, and therefore ``List[int]`` is not a subtype (not compatible with) ``List[Union[int, float]]``. (the latter actually is just ``List[float]``, see [PEP 484](https://www.python.org/dev/peps/pep-0484/#the-numeric-tower)). The reason is that lists are mutable and therefore it is _not safe_ to pass something of type ``List[int]``, where ``List[float]`` (or ``List[Union[int, float]]``) is expected.

See the [docs](http://mypy.readthedocs.io/en/latest/common_issues.html#invariance-vs-covariance) for such situations. In your case I would recommend annotating your function as:
```python
def mean(numbers: Sequence[float]) -> float:
```
(since you don't mutate ``numbers``.)

**Comment by tomchristie** [comment]
Thanks for the clarification. 😄 
(& apologies for the noise!)

**Comment by gvanrossum** [comment]
This should also be called out much earlier in the mypy docs. It's a very common "bug" report.

**Comment by ilevkivskyi** [comment]
I think what Jukka proposed in #3352 (including link to docs in error messages) will solve the problem.

**Comment by Ierezell** [comment]
Sorry for the necroBump but I'm not able to have a list from Literals (as the exemple here) and I guess it's the same topic. 

I Feel that something is possible but I cannot make the typing system satisfied with that

For exemple : 
```
MyListType = Literal['dogs', 'cats', 'crocodiles', 'ducks', 'bird', 'pony', 'fish'] # Tried with Union[Literal,Literal...] as well
my_list : List[MyListType] = ['cats', 'crocodiles', 'ducks'] # Tried with Sequence as well and putting all elements in the MyListType
```

**Comment by gvanrossum** [comment]
@Ierezell I don't get an error for that input. Please see Gitter for more help.

**Comment by Godsmith** [comment]
> > Presumably the inferred `List[int]` ought to be able to satisfy `List[Union[int, float]]`, right?
> 
> No, `List` is invariant, and therefore `List[int]` is not a subtype (not compatible with) `List[Union[int, float]]` (the latter actually is just `List[float]`, see [PEP 484](https://www.python.org/dev/peps/pep-0484/#the-numeric-tower)). The reason is that lists are mutable and therefore it is _not safe_ to pass something of type `List[int]`, where `List[float]` (or `List[Union[int, float]]`) is expected.

To explain why this is unsafe, to help people like me who have never heard the term invariant before, say that you have the following code:

```python
def add_float(numbers: List[Union[int, float]]):
    numbers.append(4.5)

ints = [1, 2, 3]  # type: List[int]
```

If you then do 

```python
add_float(ints)
``` 

you will end up with `ints` containing  `[1, 2, 3, 4.5]` even though in the type definition it says that `ints` should only contain integers! And _that_ is what they meant when they said passing the list into the method was "unsafe".
