### ISSUE TITLE
Support six.add_metaclass

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#3365]
Forked from #1764. I propose to give this less priority than `six.with_metaclass`, since the latter is more fundamental in some sense (it works for multiple bases with conflicting metaclasses where `add_metaclass` can't, see https://github.com/python/mypy/issues/1764#issuecomment-301077905).

**Comment by gvanrossum** [comment]
There's also the issue that mypy accepted this, which doesn't work at runtime:
```
@six.add_metaclass(ArcMeta)
class Arc(Generic[T_co], Destroyable):
```
To address this we ought to duplicate Python's metaclass compatibility check.

**Comment by elazarg** [comment]
The consistency of the metaclass structure is already handled, once we tell mypy what `add_metaclass` means.
