### ISSUE TITLE
Generic type aliases cause errors in Python 3.5

### ISSUE THREAD

**Issue by tyehle** [python/mypy#3368]
The example in the docs for generic type aliases type checks just fine, but crashes with `TypeError` when loaded in Python 3.5

```python
from typing import TypeVar, Tuple, Union, Callable
S = TypeVar('S')
TInt = Tuple[int, S]
UInt = Union[S, int]
CBack = Callable[..., S]

def response(query: str) -> UInt[str]:  # Same as Union[str, int]
    ...
# TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.

def activate(cb: CBack[S]) -> S:        # Same as Callable[..., S]
    ...
# TypeError: This Callable type is already parameterized.
```
I haven't seen anything like this in my googling, so I suspect I'm missing something obvious.

**Comment by JelleZijlstra** [comment]
You're probably using an old version of `typing`. This feature only works with recent versions of the typing standard library module.

As a workaround, writing `'UInt[str]'` (as a string) will likely work.

**Comment by tyehle** [comment]
That workaround does the trick, thanks!

Is there a version of `typing` newer than 3.6.1? When I upgraded to that I still get these errors (if I don't string the types).

```
$ pip3 show typing
Name: typing
Version: 3.6.1
Summary: Type Hints for Python
Home-page: https://docs.python.org/3/library/typing.html
Author: Guido van Rossum, Jukka Lehtosalo, Łukasz Langa
Author-email: jukka.lehtosalo@iki.fi
License: PSF
Location: /usr/local/lib/python3.5/dist-packages
Requires: 
$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    def activate(cb: CBack[S]) -> S:        # Same as Callable[..., S]
  File "/usr/lib/python3.5/typing.py", line 815, in __getitem__
    raise TypeError("This Callable type is already parameterized.")
TypeError: This Callable type is already parameterized.
```

**Comment by JelleZijlstra** [comment]
typing is part of the standard library in 3.5, and I think the one in the standard library gets precedence over whatever you install with pip.

**Comment by ilevkivskyi** [comment]
> typing is part of the standard library in 3.5, and I think the one in the standard library gets precedence over whatever you install with pip.

I have faced this problem several times. Is there a way to "override" a stdlib module with something installed by pip?

(As a dirty workaround, I just copy the ``typing`` module in my working directory, then it gets precedence over the stdlib one.)

**Comment by gvanrossum** [comment]
Another workaround is to point PYTHON PATH to the source directory. It is
an intentional feature but on this case definitely annoying...

**Comment by tyehle** [comment]
Thanks for all the help. Seems like there isn't anything to be done here, and there are three good workarounds. This issue can probably be closed.
