### ISSUE TITLE
Incorrect type signature for check_call

### ISSUE THREAD

**Issue by usercz** [python/mypy#3371]
```
    commands = (
        ('cmd', 'par1'),
        ('cmd', 'par1', 'par3'),
    )

    for command in commands:
        subprocess.check_call(command)
```

This works but fails type checking.

Due to the different size of the tuples.

**Comment by ilevkivskyi** [comment]
Mypy needs an explicit annotation in this situation, it just can't guess what is the type of ``commands`` (although maybe in future type inference can be improved for the case of nested tuples). Currently you can use something like:
```python
commands: Tuple[Tuple[str, ...], ...] = (
    ('cmd', 'par1'),
    ('cmd', 'par1', 'par3'),
)
```
Or another precise type depending on your actual needs.

**Comment by usercz** [comment]
It's basically what I did to make it validate :) thanks.

**Comment by gvanrossum** [comment]
Or you could use lists instead of tuples. For variable-sized values lists are more idiomatic in Python than tuples anyways.

**Comment by usercz** [comment]
Well I know I can use lists, but when I don't need stuff to mutate I tend to use tuples.

**Comment by ilevkivskyi** [comment]
I think that we can improve the join of tuples, currently ``join(Tuple[C, C], Tuple[C, C, C])`` is ``object``. I think we can make it at least ``Tuple[Any, ...]`` or even better ``Tuple[C, ...]``. (You can reopen if you think this is reasonable.)

**Comment by JukkaL** [comment]
It's a little unclear whether the join should be `Tuple[C, ...]`. `Tuple[Any, ...]` would be quite unsafe. Example illustrating why this is tricky:

```py
a = [('x, 'y', 'z'),
     ('a, b', 'c'),  # oops error
     ('q', 'w', 'e')]

for i, j, k in a:   # this will fail
    ...
```
     
The best option may be to generate an error and require an explicit annotation in cases like the original example.

**Comment by ilevkivskyi** [comment]
> The best option may be to generate an error and require an explicit annotation in cases like the original example.

Agreed. This idea already appeared few times in other contexts, so that probably this should be done "globally", not only for this particular case.
