### ISSUE TITLE
Same name for instance and type object may be confusing

### ISSUE THREAD

**Issue by elazarg** [python/mypy#3372]
A type object and an instance of that type are often printed in the same way:
```
$ mypy -c'True.x'
<string>:1: error: "bool" has no attribute "x"
$ mypy -c'bool.x'
<string>:1: error: "bool" has no attribute "x"
```
Most of the time this is OK, although when metaclasses are involved it becomes confusing. But even without metaclasses, simply forgetting to instantiate a class results in an error that does not make sense:
```python
class A: pass
class B(A): pass
def f(a: A): pass

f(B)  # E: Argument 1 to "f" has incompatible type "B"; expected "A"
a: A = B  # E: Incompatible types in assignment (expression has type "B", variable has type "A")
```
But of course "B" is compatible with "A". It's the type object "B" that is incompatible with "A".

In the above example, passing A to `f` gives a more explicit error saying that "B" is a type object, but this is done while trying to give distinct name for each type, so this does not solve the general problem.

**Comment by kirbyfan64** [comment]
I think this is a dup? I recall a very similar issue coming up before...

**Comment by elazarg** [comment]
I can't find it :\

**Comment by ilevkivskyi** [comment]
@elazarg 
Here is the issue https://github.com/python/mypy/issues/3050 could you please copy your example there? (I am closing this as a duplicate)

**Comment by elazarg** [comment]
Yes I just found it... I will. Thanks
