### ISSUE TITLE
Support forward references in aliases

### ISSUE THREAD

**Issue by jhrmnn** [python/mypy#3373]
The following code does not run in python 3.6, but passes mypy 0.511, which I believe is intended:
```python
from queue import Queue

def f(queue: Queue[int]) -> None:
    queue.put(4)
```
It can be solved by replacing `Queue[int]` with `'Queue[int]'`. (Is this documented somewhere? I saw it on stackoverflow, but nowhere else.) But Is there a way how to alias `Queue[int]`? Obviously neither `Alias = Queue[int]` nor `Alias = 'Queue[int]'` works.

**Comment by ilevkivskyi** [comment]
I think you may workaround this by writing (requires recent version of ``typing``, see [docs](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING)):
```python
from typing import TYPE_CHECKING:
    if TYPE_CHECKING:
        Alias = Queue[int]
    else:
        Alias = 'Queue[int]'
```
But I also think that we should support type aliases for "forward references".

**Comment by azag0** [comment]
Ah, cool. Should work for now. But yes, forward aliases would be nice.

(Also, it *is* documented as forward references, I missed that. Perhaps the docs could mention it also in the section about generics or stubs, or both.

**Comment by gvanrossum** [comment]
OK, if you want to use this issue for "forward aliases" please change the subject and provide a few examples of what you'd like them to look like (either Ivan or OP).

**Comment by azag0** [comment]
I think if the following snippet passed mypy, it would be already very useful:
```python
from queue import Queue

IntQueue = 'Queue[int]'

def f(queue: IntQueue) -> None:
    queue.put(4)
```

As a next step (beyond this issue), one could consider making the following work:
```python
IntAlias = 'int'
IntAliasQueue = 'Queue[IntAlias]'

q: IntAliasQueue = Queue()
q.put(1)
```

**Comment by ilevkivskyi** [comment]
These are straightforward to implement, but there is something where we need to be careful: generic aliases. This should be prohibited:
```python
T = TypeVar('T')
Alias = 'Tuple[int, Queue[T]]'
Alias[int]  # fails at runtime
```

**Comment by AlexWaygood** [comment]
These [are now supported](https://mypy-play.net/?mypy=latest&python=3.10&gist=c6115fda2af196ded42f9e48d85c3fd9) using `typing.TypeAlias` (or `typing_extensions.TypeAlias` on Python <3.10)
