### ISSUE TITLE
Unions do not understand inheritance

### ISSUE THREAD

**Issue by azag0** [python/mypy#3376]
I would expect that Unions understand inheritance, but they don't seem to (mypy 0.511):
```python
from typing import Union

class MyInt(int):
    pass

x: Union[MyInt, str]
x = 'a'
x = MyInt(3)
x = 3  # fails
```
This is responsible for python/typeshed#1202 and mandates [this workaround](https://github.com/python/typeshed/blob/master/stdlib/3.4/asyncio/tasks.pyi#L11) in asyncio.tasks.

**Comment by ilevkivskyi** [comment]
Either I am missing something or there is a mistake in your example, but mypy is right here -``int`` is a _supertype_ of ``MyInt`` so that the assignment is not safe (for nominal types).

**Comment by kirbyfan64** [comment]
e.g. this would fail:

```python
from typing import Union

class MyInt(int):
    def mymethod(self) -> int: return 0

x: Union[MyInt, str]
x = 3
print(x.mymethod())  # BOOM!!
```

**Comment by azag0** [comment]
Erm, yes, of course, apologies. I thought I had it the other way round. To my defense, the same logical mistake was done in python/typeshed#1202, and I just bought it. I'll follow there.
