### ISSUE TITLE
Better message if method incompatible with base class

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3379]
Currently if a method is incompatible with a base class, mypy just tells the name of the base class but doesn't actually give more details about the expected signature. This is a problem especially if the base class is defined in typeshed, since users may not know how to find the signature. There are a few things we could do about this:

1. Display the base class method signature as a note after the message.
2. Give a pointer to the file and line number where the base class method is defined.
3. Also highlight common specific issues with specialized messages, such as different number of arguments, argument type is narrower in subclass, etc.
4. Some combination (or all) of the above.

**Comment by ilevkivskyi** [comment]
Protocols already do (1) for incompatible types (but not for incompatible override in an explicit subclass). I think this is the most important one, (2) and (3) are also good to have, but are probably less important.

**Comment by markkohdev** [comment]
I'm looking into this one

**Comment by markkohdev** [comment]
If anyone wants to tackle this issue feel free to continue on my work from https://github.com/python/mypy/pull/3410 (unless I come back to this before someone else does)
