### ISSUE TITLE
Add github issue topic label for usability issues

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3380]
Maybe we should have a specific topic label for usability issues such as poor error messages. They are important but currently it's a little hard to prioritize them since they are spread out among hundreds of open issues.

**Comment by ilevkivskyi** [comment]
Big +1 from me. I have my own mypy "roadmap" (in addition to still unpublished roadmap mentioned by @ddfisher) and improving error messages is among top items there.

**Comment by gvanrossum** [comment]
+1; I've added the label "topic-usability". Go crazy adding it to relevant topics!

**Comment by ilevkivskyi** [comment]
OK, I did a quick pass, found 26 relevant issues.
