### ISSUE TITLE
Error on NamedTuple with methods (3.6.1)

### ISSUE THREAD

**Issue by benselme** [python/mypy#3381]
In Python 3.6.1, methods can be added to `NamedTuple`s:

```
class Post(typing.NamedTuple):
    name: str
    data: typing.Any
    attachments: typing.List[str]

    @property
    def date(self):
        return self.data.date
```

Mypy doesn't recognize this new syntax and fails with:

`error: Invalid statement in NamedTuple definition; expected "field_name: field_type"`

**Comment by ilevkivskyi** [comment]
Thanks! This is a known issue, it was fixed two days ago. Please try this on github master and reopen this issue if it still does not work.
