### ISSUE TITLE
Add a reveal_locals() function.

### ISSUE THREAD

**Issue by aisipos** [python/mypy#3387]
reveal_locals() would work similar to reveal_type() but give information for all local variables at the given context.

This could perhaps be useful for editor plugins to show the types for all local variables, rather than just one at a time.

As an example with this function:

```
def f(a: int, b: int) -> int:
    c = a + b
    reveal_locals()
    return c
```

Perhaps we could see this output:

```
sample.py:3: error: Revealed type of a is 'builtins.int'
sample.py:3: error: Revealed type of b is 'builtins.int'
sample.py:3: error: Revealed type of c is 'builtins.int'
```

**Comment by blueyed** [comment]
reveal_locals exists by now.
