### ISSUE TITLE
no error on import html; re.sub(r"x", "y", html)

### ISSUE THREAD

**Issue by unhammer** [python/mypy#3389]
The following gives no errors when run through mypy 0.470 (package from Ubuntu 17.04):
```
#!/usr/bin/python3

import re
import html


def fix(htm):
    return re.sub(r'x', 'y', html)


if __name__ == '__main__':
    print(fix('blah<br>meh'))

```
but of course crashes when run through python 3.5.  

It seems like mypy ought to catch it, unless modules are considered AnyStr, which sounds odd:
```
$ grep -w sub /usr/lib/mypy/typeshed/stdlib/3/re.pyi
def sub(pattern: AnyStr, repl: AnyStr, string: AnyStr, count: int = ...,
def sub(pattern: AnyStr, repl: Callable[[Match[AnyStr]], AnyStr],
def sub(pattern: Pattern[AnyStr], repl: AnyStr, string: AnyStr, count: int = ...,
def sub(pattern: Pattern[AnyStr], repl: Callable[[Match[AnyStr]], AnyStr],
```

**Comment by lincolnq** [comment]
If I correct your example to

```
def fix(htm: str) -> str:
    return re.sub(r'x', 'y', html)
```

then mypy 0.510 catches the example. If I run mypy with --check-untyped-defs, it catches the example. I don't have the older version lying around, but are you sure you intended to not annotate the fix function (which causes mypy with default arguments to ignore it)?

**Comment by ilevkivskyi** [comment]
Not checking non-annotated functions by default is PEP 484 specified semantics (to allow gradual annotation of existing code). You should use either ``--disallow-untyped-defs`` or ``--check-untyped-defs`` options.

**Comment by unhammer** [comment]
Doh, PEBKAC. Sorry for the noise, and thanks for the solutions :)
