### ISSUE TITLE
Install pinfer in setup.py

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#342]
Figure out some way to install pinfer in setup.py.

**Comment by yfyf** [comment]
Hi! First of all -- mypy is a super cool project, props to your for doing it all.

I thought I'd contribute something while learning more about `mypy` internals. How about we make `pinfer` into a standalone pip package which depends on `mypy-lang`? I'd be happy to contribute such a patch, however I don't fully understand the structure of `pinfer` / meaning of `p.py`:

* It seems to contain duplicate packages for python2 and python3, but it's not clear how they are used.
* Why does `p.py` require a test module? Why can't I just run typeinference without any testing?
* Perhaps `p.py` should gain a more reasonable name if it is to be exposed as an executable.

Let me know what your thoughts are.

**Comment by JukkaL** [comment]
Making pinfer a stand-alone package sounds like a good idea. Answers to your questions:

* Pinfer does the right thing at runtime, and imports the correct module depending on Python version (I think it works in both Python 2 and 3).
* Pinfer does runtime type inference. It intercepts calls to functions in the target module and records the types of arguments and return values. Using tests is an easy way of exercising your module and getting runtime type information. The p.py script is a helper for inferring runtime types based on unit tests, but pinfer can be used in other ways as well (by directly importing `pinfer`).
* Yes, p.py is not a great name.

Jared Pochtar implemented pinfer during Dropbox hack week last summer, based on a prototype that I had written a few years ago. It hasn't seem much further development since. In order to make it really useful, we'd probably need at least these things:

* Write documentation.
* Make the generated stubs closer to those generated by `mypy.stubgen` (the latter isn't documented yet either, though).
* Make it easy to discover, install and use.
* Do some more testing.

**Comment by JukkaL** [comment]
It doesn't look like we are going to continue improving pinfer so this isn't relevant any more.
