### ISSUE TITLE
Document pinfer

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#343]

**Comment by JelleZijlstra** [comment]
Is this still desired? At this stage it might be better to just remove pinfer from the codebase.

**Comment by ilevkivskyi** [comment]
We actually discussed this yesterday very briefly. I would vote for removal. IIRC @JukkaL is also for removal.

**Comment by gvanrossum** [comment]
I vote for removal too.

**Comment by JelleZijlstra** [comment]
Seems like we're all in agreement. I'll send a PR.
