### ISSUE TITLE
type: ignore doesn't work with multi-line statements

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/mypy#3448]
`file.py`:
```python
1 \
+ '2'  # type: ignore
```

gives output
```
file.py:1: error: Unsupported operand types for + ("int" and "str")
```
which is wrong IMO.

**Comment by ddfisher** [comment]
`#type: ignore` must be placed on the same line as the error. You won't be able to do that with backslash multi line statements, but those aren't considered good style anyway. If you need a type ignore on a multi line statement, use parens and place the type ignore on the line with the error.

**Comment by dumblob** [comment]
Unfortunately the suggested workaround doesn't work for

```python
from x import long, list, of, symbols, ... \
    wrapping, around, and, further, ... \
    ...
```
(e.g.
```
from flask_login import LoginManager, login_required, login_user, \
    logout_user, UserMixin, current_user  # type: ignore
```
)

Any ideas?

**Comment by JelleZijlstra** [comment]
You can put parentheses around your long list of imports instead of using backslashes.

**Comment by dumblob** [comment]
As I wrote, I can't make it work:
```python
from module_mypy_doesnt_know import ( a, b, \
    c, d, \
    e, f )  # type: ignore
```
```
test.py:1: error: Cannot find implementation or library stub for module named 'module_mypy_doesnt_know'
test.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

**Comment by JelleZijlstra** [comment]
Try 

```
from module_mypy_doesnt_know import ( a, b,  # type: ignore
    c, d,
    e, f )
```
The type ignore has to be on the physical line where the error is reported.

**Comment by dumblob** [comment]
>The type ignore has to be on the physical line where the error is reported.

Seems to work, thanks. Though I find it really nasty - any good reason to have it like that (except for "wasn't yet implemented, because python parsing is too rigidly line oriented")?
