### ISSUE TITLE
Allow class-based NamedTuple syntax in semantic analyzer for stubs in pre-3.6 mode

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#3464]
See https://github.com/python/typeshed/pull/1336#discussion_r118749396

Not very important, but would be nice if stubs could use
```python
class A(NamedTuple):
    x: int
    y: str
```
instead if
```python
A = NamedTuple('A', [('x', int), ('y', str)])
```

**Comment by srittau** [comment]
Had this come up in python/typeshed#3278.

**Comment by JukkaL** [comment]
This seems to be the relevant code (in `mypy/semanal_namedtuple.py`):

```py
    def check_namedtuple_classdef(
            self, defn: ClassDef) -> Optional[Tuple[List[str], List[Type], Dict[str, Expression]]]:
        """Parse and validate fields in named tuple class definition.

        Return a three tuple:
          * field names
          * field types
          * field default values
        or None, if any of the types are not ready.
        """
        if self.options.python_version < (3, 6):
            self.fail('NamedTuple class syntax is only supported in Python 3.6', defn)
            return [], [], {}
...
```

Also, there is `is_typeshed_stub_file()` in `SemanticAnalyzerInterface` which isn't quite what we need. A similar property could be added for `is_stub_file()`, and then the rest should be easy.

Anybody want to write a PR?

**Comment by srittau** [comment]
PR in #7646.

**Comment by gvanrossum** [comment]
Do we know if this is supported by type checkers other than mypy?

**Comment by srittau** [comment]
We checked this in python/typeshed#3321 and pytype, pyre, and pyright, PyCharm, and the Microsoft Language Server for Python all support this.
