### ISSUE TITLE
Omitted Generics Should Be Disallowed

### ISSUE THREAD

**Issue by ilinum** [python/mypy#3469]
Currently, if a generic type parameter is not specified, it is assumed to be Any (`List` becomes `List[Any]`).

Forgetting to provide a generic type is an easy mistake to make, which makes mypy less effective at typechecking as the generic type will be inferred as `Any`. We should make sure e.g. `List[Any]` is actually what user wants by making the user explicitly state `List[Any]` as the type.
If the generic parameter is not specified, mypy should output an error. 

There’s also the problem of `list`, `set`, etc. We should probably forbid these too and give a nice error message saying they should use `List`. However, this part of the proposal requires more consideration since, for instance, it’s possible that the user does not want to import `typing` module.

As a migration aid, we can provide a flag to allow implicit any from omitted generics but eventually we should remove it too.

**Comment by gvanrossum** [comment]
Well, to make this the default/only way, you would have to propose a change to PEP 484 and get pytype and PyCharm to agree. And there may be a lot of code to update.

**Comment by ilevkivskyi** [comment]
I am against making this the default. FWIW I have seen lots of code on GitHub that just uses plain ``list``, ``dict`` etc. in annotations. I could agree with emitting a note by default (like ``note: bare "MyGeneric" is interpreted as "MyGeneric[Any, Any]".``) but keeping the exit code 0 in this case, with an option to make this note an error. This would be similar to how many compilers work.

**Comment by ilinum** [comment]
yeah, these are good points. 
After some in person discussion with @gvanrossum, @JukkaL, and @ddfisher, we decided will add a flag (perhaps in https://github.com/python/mypy/pull/3141) to forbid it.
Then, we may or may not move forward with making omitted generics an error by default depending on how well the adoption of the new flag will go.

**Comment by ilinum** [comment]
@ilevkivskyi, I think that may be a good idea but at the same time it may flood the user's console with such errors. Of course, we can do what `javac` does: emit a line saying that there are unchecked operations and provide a flag for verbose output about these operations.

**Comment by ddfisher** [comment]
I think the right place in the tradeoff space may be to allow e.g. `list` (perhaps with a note on the console) but to disallow `List` (as you should just write `List[Any]` instead, because it's clearer and ensures you understand what it means).

**Comment by ilevkivskyi** [comment]
I think this is now fixed, since we have ``--disallow-any=generics``
