### ISSUE TITLE
AttributeError with abstract property setter and "# type: ignore"

### ISSUE THREAD

**Issue by dokai** [python/mypy#3491]
I noticed the following change in behavior after upgrading to `0.511`  from `0.501`.

Using the following minimal example
```
$ cat abstractproperty.py |nl -b a
     1	from abc import ABC
     2	from abc import abstractmethod
     3	from typing import List
     4
     5
     6	class Test(ABC):
     7
     8	    @property
     9	    def foo(self) -> List:
    10	        """Getter"""
    11
    12	    @foo.setter  # type: ignore
    13	    @abstractmethod
    14	    def foo(self, value: List) -> None:
    15	        """Setter"""
```
the new version of mypy gives the following error
```$ mypy abstractproperty.py                                                                                                                                                              
abstractproperty.py:14: error: Function is missing a type annotation for one or more arguments
```
While the error itself is a bit unclear in terms of what exactly is missing the type annotation, attempting to ignore line 14 with a `# type: ignore` comment 
```python
from abc import ABC
from abc import abstractmethod
from typing import List


class Test(ABC):

    @property
    def foo(self) -> List:
        """Getter"""

    @foo.setter  # type: ignore
    @abstractmethod
    def foo(self, value: List) -> None:  # type: ignore
        """Setter"""
```
results in an `AttributeError`
```
Traceback (most recent call last):
  File ".../bin/mypy", line 6, in <module>
    main(__file__)
  File ".../lib/python3.5/site-packages/mypy/main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File ".../lib/python3.5/site-packages/mypy/main.py", line 93, in type_check_only
    options=options)
  File ".../lib/python3.5/site-packages/mypy/build.py", line 188, in build
    graph = dispatch(sources, manager)
  File ".../lib/python3.5/site-packages/mypy/build.py", line 1595, in dispatch
    process_graph(graph, manager)
  File ".../lib/python3.5/site-packages/mypy/build.py", line 1838, in process_graph
    process_stale_scc(graph, scc, manager)
  File ".../lib/python3.5/site-packages/mypy/build.py", line 1946, in process_stale_scc
    graph[id].write_cache()
  File ".../lib/python3.5/site-packages/mypy/build.py", line 1576, in write_cache
    self.manager)
  File ".../lib/python3.5/site-packages/mypy/build.py", line 875, in write_cache
    data = tree.serialize()
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 284, in serialize
    'names': self.names.serialize(self._fullname),
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 2377, in serialize
    data[key] = value.serialize(fullname, key)
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 2325, in serialize
    data['node'] = self.node.serialize()
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 2176, in serialize
    'names': self.names.serialize(self.fullname()),
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 2377, in serialize
    data[key] = value.serialize(fullname, key)
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 2325, in serialize
    data['node'] = self.node.serialize()
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 414, in serialize
    'items': [i.serialize() for i in self.items],
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 414, in <listcomp>
    'items': [i.serialize() for i in self.items],
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 636, in serialize
    'func': self.func.serialize(),
  File ".../lib/python3.5/site-packages/mypy/nodes.py", line 579, in serialize
    'type': None if self.type is None else self.type.serialize(),
  File ".../lib/python3.5/site-packages/mypy/types.py", line 766, in serialize
    'fallback': self.fallback.serialize(),
AttributeError: 'NoneType' object has no attribute 'serialize'
```
My `mypy.ini` has the following
```ini
[mypy]
disallow_subclassing_any = false
disallow_untyped_defs = true
follow_imports = skip
ignore_missing_imports = true
incremental = false
show_column_numbers = true
strict_optional = true
warn_no_return = false
warn_redundant_casts = true
warn_unused_ignores = true
```

**Comment by gvanrossum** [comment]
Maybe it's that you are using List rather than List[something]?

**Comment by dokai** [comment]
Using `List[str]` instead raises `AttributeError` in the same way.

Here's a slightly smaller example which throws the exception.
```from abc import ABC
from abc import abstractmethod
from typing import Any


class Test(ABC):

    @property
    def foo(self) -> Any:
        """Getter"""

    @foo.setter  # type: ignore
    @abstractmethod
    def foo(self: Any) -> None:
        """Setter"""
```
What I'm mostly interested here is:
- what is the correct way to annotate abstract properties and is that currently expected to work?
- does the example expose a bug in mypy?

I tried with the current `master` branch and it has the same behavior.

**Comment by gvanrossum** [comment]
I suspect the crash has more to do with the ignore on the @foo.setter line.

Can you use @abstractproperty? It exists in abc.py.

**Comment by JelleZijlstra** [comment]
I think there's two (possibly related) bugs:
- You get `Function is missing a type annotation` despite not missing any type annotations.
- With the `# type: ignore`, mypy crashes. This crash happens in cache serialization. There's another related bug: `--pdb` doesn't work for crashes in serialization. The function it's crashing on serializing is the `setter` method.

As for the correct way to annotate this, from the code it looks like mypy expects you to annotate the getter, not the setter, with `@abstractmethod`. It also supports `@abstractproperty`, but that is deprecated.

**Comment by ilevkivskyi** [comment]
@dokai 
> does the example expose a bug in mypy?

Yes, practically every crash is a bug. (In some sense it is even more than bug, this is probably why label ``crash`` added to this issue has strong red color.)

**Comment by ilevkivskyi** [comment]
@dokai 
> what is the correct way to annotate abstract properties and is that currently expected to work?

From Python point of view the _current_ way is just to use two decorators, see https://docs.python.org/3/library/abc.html#abc.abstractproperty but I am not sure mypy supports this.

**Comment by JelleZijlstra** [comment]
I fixed the crash in #3493, but I was unable to reproduce the bug with the `Function is missing a type annotation` message.

**Comment by gvanrossum** [comment]
That error appears when you add `--disallow-untyped-defs`.

**Comment by dokai** [comment]
@gvanrossum I can use `@abstractproperty` for my use case and it does exhibit the same issue with `mypy`.

**Comment by gvanrossum** [comment]
OK, but we still need to figure out the reason for the spurious "Function is missing a type annotation" error.

**Comment by JelleZijlstra** [comment]
Turns out my PR also fixes that. Mypy was complaining about `self` not having an annotation, probably because it skipped semantic analysis on the method.
