### ISSUE TITLE
Subclassing stubbed generic classes

### ISSUE THREAD

**Issue by azag0** [python/mypy#3495]
I wasn't able to find a user-level way how to make a non-generic subclass of a generic stubbed class such as `OrderedDict`. Is there such a way? I was looking at how `typing.DefaultDict` is implemented, but it's too complex (for me).

I'd like to be able to create a subclass that would be equivalent to
```python
class D(OrderedDict[int, str]):
    pass
```
that is, if `typing.OrderedDict` existed.

**Comment by ilevkivskyi** [comment]
This depends on your version of Python, if you have the recent one, then this should work:
```python
if typing.TYPE_CHECKING:
    class D(OrderedDict[int, str]): ...
else:
    class D(OrderedDict):
        # actual implementation
        ...
```
for older versions you can define ``MYPY = False`` and use it instead of ``typing.TYPE_CHECKING``.

**Comment by azag0** [comment]
Ah, brilliant. This is the second time I asked something here and you recommended a solution with `typing.TYPE_CHECKING`. Haven't learned my lesson. Thanks.

**Comment by silviogutierrez** [comment]
@ilevkivskyi : should D implement any custom methods, I'm finding that you need both stubs on the first clause, and the implementations on the second clause. Is that correct?

Example:

```python
if typing.TYPE_CHECKING:
    class D(OrderedDict[int, str]):
        def foo() -> int: ...
else:
    class D(OrderedDict):
        def foo() -> int:
            return 5
```

Otherwise, mypy complains that "foo" is not a member when you try to use it. Or am I doing something wrong?

On that topic: is this still the only sanctioned way to make non-generic versions of generic stubs? I'm trying real hard to type Django's `QuerySet` to no avail.

**Comment by ilevkivskyi** [comment]
@silviogutierrez 
> should D implement any custom methods, I'm finding that you need both stubs on the first clause, and the implementations on the second clause. Is that correct?

In the situations with complex classes it is sometimes possible to have a separate implementation class like this:
```python
class _D:
    # Actual implementation goes here
    def foo() -> int:
        return 5
if typing.TYPE_CHECKING:
    class D(_D, OrderedDict[int, str]):
        pass
else:
    class D(_D, OrderedDict):
        pass
```
> On that topic: is this still the only sanctioned way to make non-generic versions of generic stubs? I'm trying real hard to type Django's ``QuerySet`` to no avail.

Currently yes. There is an issue to have special support for django via a plugin.
