### ISSUE TITLE
Error when using `socket.socket` as a context manager

### ISSUE THREAD

**Issue by adamtheturtle** [python/mypy#3496]
With pretty much the example code from https://docs.python.org/3/library/socket.html#example,
`mypy` gives an error.

I am using Python 3.6.1:

```
(mypy) Adam@Adams-MacBook-Pro ~/D/mypy> python
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

I have the latest `mypy` installed, as of the time of writing:

```
(mypy) Adam@Adams-MacBook-Pro ~/D/mypy> pip freeze
mypy==0.511
typed-ast==1.0.3
```

I have a very simple script:

```
(mypy) Adam@Adams-MacBook-Pro ~/D/mypy> cat example.py
import socket

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as new_socket:
    print('Working')
```

And this script works:

```
(mypy) Adam@Adams-MacBook-Pro ~/D/mypy> python example.py
Working
```

But mypy gives an error:

``` 
(mypy) Adam@Adams-MacBook-Pro ~/D/mypy> mypy example.py --show-traceback
example.py:3: error: "socket" has no attribute "__enter__"
example.py:3: error: "socket" has no attribute "__exit__"
```

**Comment by ilevkivskyi** [comment]
Thanks! This looks like a typeshed issue (not something specific to mypy). Could you please report this issue to https://github.com/python/typeshed/issues?

**Comment by ilevkivskyi** [comment]
(You can close this issue after reporting to typeshed.)

**Comment by adamtheturtle** [comment]
Thanks @ilevkivskyi - I have created https://github.com/python/typeshed/issues/1391.
