### ISSUE TITLE
`Cannot find module named <external library>`

### ISSUE THREAD

**Issue by vitaly-zdanevich** [python/mypy#3498]
`mypy 0.511`

Python 3

I do not use virtualenv, my code works but mypy out of the box can not handle external libs?

**Comment by ethanhs** [comment]
Hi, could you give more information about your directory structure? Also how are you importing it? MyPy should definitely pick up modules that you import out of the box, unless you are doing magic/dynamic imports.

**Comment by vitaly-zdanevich** [comment]
The directory structure is one python file.

For example `import boto3` generate this error.

**Comment by ilevkivskyi** [comment]
There are no stub files (type declarations) for this library in [typeshed](https://github.com/python/typeshed) yet. This does nor depend on mypy, someone needs to contribute these stubs. (Btw there are stubs for ``boto`` under ``2and3`` folder).

**Comment by vitaly-zdanevich** [comment]
ok, thank you.

**Comment by ilevkivskyi** [comment]
You can actually open an issue about this on typeshed tracker. As I understand ``boto3`` and ``boto`` are very similar, so that stubs can be made quite easily.

**Comment by ltworf** [comment]
I am actually having this issue on a module that has type informations… would it still require stubs?

**Comment by ltworf** [comment]
```
In [36]: import typedload

In [37]: typedload
Out[37]: <module 'typedload' from '/usr/lib/python3/dist-packages/typedload/__init__.py'>
```

**Comment by ethanhs** [comment]
>I'm guessing the package has type annotations but it does not have a py.typed marker file per PEP 561 yet?

This is my guess as well. @ltworf please read the relevant docs https://mypy.readthedocs.io/en/latest/installed_packages.html. Feel free to open a new issue if you have a question about it.

**Comment by ltworf** [comment]
Thanks, made a new release now, with the special file, it works now.

By the way, the module is to load json-like data into NamedTuple, and other typed data structures.
