### ISSUE TITLE
Additional TypedDict methods

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3518]
Some of these TypedDict methods might be worth special casing:

* `setdefault`
* `copy`
* `update`
* `pop` (disallowed for required keys)
* `popitem` (disallowed at least if there are required keys)

**Comment by JukkaL** [comment]
Closed in favor of #3843 since that issue has more methods.

**Comment by ethanhs** [comment]
Actually closing in favor of #3843. :)
