### ISSUE TITLE
Recognize dynamic creation of named tuples.

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3520]
This appeared in https://github.com/python/typing/issues/427

We can support something like this:
```python
base_fields = [('x', int), ('y', int)]
label = [('label', str)]
LabeledPoint3D = NamedTuple('LabeledPoint3D', base_fields + [('z', int)] + label)
```

**Comment by ilevkivskyi** [comment]
We can also do similar things for ``TypedDict`` and ``Enum`` functional APIs.

**Comment by elliott-beach** [comment]
This would also fix #4287.

**Comment by Dentosal** [comment]
Currently dynamically created enums also show errors, because mypy cannot resolve variants.

**Comment by msullivan** [comment]
I don't think we'll do this
