### ISSUE TITLE
Special case signature of subprocess.check_output

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3530]
Use the plugin system to special case the return type inference of `check_output` based on the `universal_newlines` keyword argument. Currently the return type in typeshed (Python 3) is `Any`, but we should be able to infer `bytes` or `str` pretty often.

**Comment by gvanrossum** [comment]
Do you want a separate issue for each function to special-case? I have another candidate or two, there's io.open() and _io.open() which behave similar to open(), and perhaps codecs.open().

**Comment by msullivan** [comment]
I did this in typeshed using literal types and overloads
