### ISSUE TITLE
Use plugin to support SQLAlchemy table definitions

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3538]
We'll also need stubs for SQLAlchemy as they were removed from typeshed some time ago. Current work on stubs is happening at https://github.com/JelleZijlstra/sqlalchemy-stubs.

**Comment by JukkaL** [comment]
This was originally discussed in #1240.

**Comment by JukkaL** [comment]
Once we have this we could also support type checking at least some SQLAlchemy queries.

**Comment by ilevkivskyi** [comment]
I think this can be closed, there is a separate repo where we track support for various SQLAlchemy features: https://github.com/dropbox/sqlalchemy-stubs.
