### ISSUE TITLE
Enum.value treated as Enum

### ISSUE THREAD

**Issue by matkuki** [python/mypy#3546]
Hi guys,

I couldn't find a similar issue, so apologies if there is a similar issue already open or closed.

Why doesn't this example show an error for wrong argument type in the last line:
```python
import enum

class TempEnum(enum.Enum):
    one = 1
    two = 2

def test_func(arg: TempEnum) -> None:
    print(arg)
 
test_func(TempEnum.one.value) # No error ?
```
Shouldn't this be an error as .value is an int?
I'm using Python 3.5 and mypy 0.511.

Matic

**Comment by ethanhs** [comment]
In the typing stub https://github.com/python/typeshed/blob/master/stdlib/3.4/enum.pyi#L25
`Enum.value` has type `Any`, as it can hold any value. MyPy can't narrow the type here.

**Comment by matkuki** [comment]
@ethanhs 
Thanks for the details. It just feels counter-intuitive. Hope it gets upgraded.
