### ISSUE TITLE
Add option to format the output messages

### ISSUE THREAD

**Issue by khyox** [python/mypy#3547]
This is a feature request for easing the integration of mypy in some IDEs. The flag (suggested: _abspath_) would output the full path of the file just before `":{line_number}:[{column_number}:] error: ..."`. Of course, a more comprehensive solution would be a full formatter of the output lines with this and other choices to achieve the desired format in each case.

**Comment by gvanrossum** [comment]
Wow, there are IDEs that cannot keep track of the directory where they run simple tools like mypy?

**Comment by khyox** [comment]
It's more concerned with the (in)ability to parse the output. There was a [similar feature request for pylama](https://github.com/klen/pylama/issues/36) that illustrates the issue (with PyCharm). 

Beyond that, and probably as a better general solution, I think that an option like [pylint's `--msg-template`](https://pylint.readthedocs.io/en/latest/user_guide/output.html) would be very convenient. For example, with `--msg-template="{abspath}:{line:04d}:{column:02d}: {msg_id} ({symbol}) {msg}"` the parsing problem is easily solved for pylint/PyCharm case.

**Comment by gvanrossum** [comment]
Well, I have run into this in the past with PyCharm, but IMO this is really a PyCharm bug. The generalized solution sounds like something I'd like to avoid for a few more years. In the meantime I'm sure you can write a little bash script that munges the output the way youwant.

**Comment by khyox** [comment]
Thanks! The bash script was written (awk at rescue): I cannot wait a few more years to integrate the useful mypy in the IDE 😉 . Anyway, that makes sense and I'll open an issue in PyCharm.

**Comment by wbkdef** [comment]
When I run mypy with the full file path from PyCharm, the full file path is included in the output (and can be turned into a link)

**Comment by mleonard87** [comment]
I couldn't get it to work as per @wbkdef 

For anyone else coming here looking for a solution to using this with PyCharm, You can use the following bash script to wrap mypy and munge the output.

```bash
#!/bin/bash

MYPY_BIN=/usr/local/bin/mypy

length=$(($#-1))
mypyargs=${@:1:$length}
basepath=${@:$length+1:$length+1}

$MYPY_BIN $mypyargs | awk -v basepath=$basepath '{print basepath"/" $0}'
```
Set up your PyCharm like this - note the additional argument on the end - this is used as a prefix to all output from mypy.
![screen shot 2018-06-08 at 10 27 33 am](https://user-images.githubusercontent.com/1535972/41132823-9a4f7b3a-6b06-11e8-9fba-2b7189743b7e.png)

**Comment by ilevkivskyi** [comment]
Yes, making it work requires some tricks, and even when it works I was not very happy with the ergonomics. There is an "official" mypy PyCharm plugin that works smoother (at least for me) https://github.com/dropbox/mypy-PyCharm-plugin

**Comment by wbkdef** [comment]
Something I didn't realize before, that helps make it work - I run it in a directory totally unrelated to my project.  I see @switchtrue is running it in the "ProjectFileDir", and so mypy uses a relative path.

Here's a screenshot of my setup (I'm also running mypy with a python script, that filters the output).

![image](https://user-images.githubusercontent.com/2389203/41814758-190a3dc8-770c-11e8-859b-dff10c02826a.png)

**Comment by pongo** [comment]
For pycharm you can use this "external tool" setup:

* arguments: `--cache-dir $ProjectFileDir$/.mypy_cache --ignore-missing-imports $FileDir$/$FileName$`
* working directory: `C:\temp` (unrelated to your project)
* output filters: `$FILE_PATH$:$LINE$:$COLUMN$:.*`

**Comment by Timmmm** [comment]
I've made a new task that's pretty closely related to this - to add JSON output support. That should allow robust output parsing by IDEs, etc.

See #10816.
