### ISSUE TITLE
Make it easier to force typeshed to take precedence over vendored source files

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3559]
Some projects may include vendored third party modules in their source tree. If some of the vendored modules have typeshed stubs, this may result in the stubs being ignored. A manual workaround is to point `MYPYPATH` to typeshed, but it's not very convenient since finding the installed location of typeshed is not trivial. There are also multiple typeshed directories that may need to be added to `MYPYPATH`.

Ideas to make this easier:
* Provide an option to move typeshed to the front of the the module search path.
* Support something like `export MYPYPATH="<typeshed>"`. Now `<typeshed>` will get replaced with the correct typeshed directories.
* Move typeshed earlier in the search path by default. Users would have to use `MYPYPATH` if they want local modules to take precedence over typeshed stubs.

**Comment by JukkaL** [comment]
This originally came up at https://github.com/pypa/pip/pull/4545.

**Comment by hauntsaninja** [comment]
There hasn't been much demand for this feature; this issue predates modular typeshed
