### ISSUE TITLE
False position of "Condition must be positive" for containers when --strict

### ISSUE THREAD

**Issue by DragonSA** [python/mypy#3572]
Mypy gives a false positive for the following code:
```
# cat test2.py
from typing import List
false = []  # type: List[str]
if false:
    print("Error")
# mypy --strict test2.py
test2.py:4: error: Condition must be a boolean
```
This is in contradiction to PEP 8:
```
For sequences, (strings, lists, tuples), use the fact that empty sequences are false.

Yes: if not seq:
     if seq:

No: if len(seq):
    if not len(seq):
```

**Comment by ilevkivskyi** [comment]
I tried an this doesn't happen on master. This behavior is deprecated (I see a deprecation warning when run with ``--strict-boolean``, see #3195) and will be completely removed soon. Please feel free to reopen if you think here is something more to do.
