### ISSUE TITLE
Incorrect scoping of variable in generator in Python 2

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#3573]
This is probably low priority, but I believe I found the following, a quirk of Python 2:

```python
x = 'test'
[x for x in [1,2,3]]
print(type(x))
reveal_type(x)
```
when run:
```bash
$ py -2 test.py
<type 'int'>
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    reveal_type(x)
NameError: name 'reveal_type' is not defined
$ mypy --py2 test.py
test.py:4: error: Revealed type is 'builtins.str'
```

The issue is that in Python 2 the variable is in the parent scope, not local to the comprehension expression.

**Comment by gvanrossum** [comment]
I would hope that we intentionally don't model that, it's an evil
misfeature.

**Comment by ethanhs** [comment]
Should I just close this then?
