### ISSUE TITLE
Specifics of callables sometimes lost in error messages

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3581]
The name of of the callable argument and the fact that it has a default value are not displayed
in the second error message generated when type checking this example:

```py
from typing import Callable, List
from mypy_extensions import Arg

a: List[Callable[[Arg(int, 'x')], None]]
reveal_type(a)  # Revealed type is 'builtins.list[def (x: builtins.int =)]'
a.x  # List[Callable[[int], None]] has no attribute "x"    <== Only "int"
```

**Comment by AlexWaygood** [comment]
I'm closing this issue, as these features from mypy_extensions [are deprecated](https://mypy.readthedocs.io/en/stable/additional_features.html?highlight=Mypy_extensions#extended-callable-types).

The error messages for callback protocols [aren't great](https://mypy-play.net/?mypy=latest&python=3.10&gist=192446453c20de971cb03420194b3d6a), but that seems like a separate issue.
