### ISSUE TITLE
mypy does not execute local module with a __main__.py

### ISSUE THREAD

**Issue by allan-simon** [python/mypy#3585]
Step to reproduce 

create a directory `/tmp/toto` , with inside an empty `__init__.py` , and a `__main__.py` 

inside the main.py put

```python
def main():
    print("pouet")
if __name__ == "__main__":
    main()
```

now go to `/tmp` and execute `python3 -m toto` you will see `pouet`

with mypy , it exits without priting nothing , nor returning any error

**Comment by ethanhs** [comment]
MyPy doesn't execute code, only checks that types are correct, reading the text of the sources (this is why it is called static analysis).
Since there are no typed functions, it doesn't check types, and furthermore, there are no errors even if you did `mypy --check-untyped-defs`

**Comment by ethanhs** [comment]
This can be closed unless @allan-simon you have any other questions related to this?

**Comment by allan-simon** [comment]
you can close it, I had a misunderstanding on how mypy was working , I thought it was a layer over the normal interpreter with an added check on type, and it's actually a static analyzer, which make sense now that I think about it. thanks for the explanation
