### ISSUE TITLE
error: Module 'jinja2' has no attribute 'select_autoescape'

### ISSUE THREAD

**Issue by AlexeyPetroff** [python/mypy#3589]
Hi! When I use mypy in my project I get the following error:
error: Module 'jinja2' has no attribute 'select_autoescape'

It says there is a problem in this line:
from jinja2 import Environment, FileSystemLoader, select_autoescape

Can You please help me, and maybe tell me what I am doing wrong, as You can see above there are no problems with Environment, FileSystemLoader, but there is with select_autoescape

Thanks in advance

**Comment by ethanhs** [comment]
You probably aren't doing anything wrong. It would seem that the stubs in typeshed are missing that particular function. If you could create an issue [over at typeshed](https://github.com/python/typeshed/issues) or even better submit a fix, it'd be appreciated.

**Comment by ilevkivskyi** [comment]
@AlexeyPetroff Also you can use ``# type: ignore`` to temporary silence this error (until the fix is merged in typeshed).
