### ISSUE TITLE
Type checking of None values

### ISSUE THREAD

**Issue by mvcisback** [python/mypy#359]
A common pattern in alot of functions is to use None to signify something alternative behavior.
It might be beneficial to include a convenience Maybe type that is a partial application of Union with None. 

I'm still familiarizing myself with the code and am not 100% what to do yet

**Comment by Dedoig** [comment]
Is the type ```None``` the same as the type ```Union[]``` i.e. Union of no types?

**Comment by gvanrossum** [comment]
No, when used as a type, None is a shorthand for type(None). Union [] is
invalid , and so is Union [()].

**Comment by Dedoig** [comment]
Thanks. 

It seems Union[…] is already implemented and working, but type None (as disjoint from every other type) is not yet implemented. I was wondering of treating type None as Union[] might make it easier to implement…

**Comment by gvanrossum** [comment]
Type None does not mean "not any type". It means "must be the value None". This is primarily useful to be explicit about the return value of a function that has no result (because it still returns None):
```
def greeting() -> None:
    print('Hello, world')
```
Without the `-> None` the body of the function won't be type-checked and its return value will be assumed to be `Any`.

**Comment by NYKevin** [comment]
Technically, `Union[()]` *could* be [a thing](http://en.wikipedia.org/wiki/Bottom_type), but I'm not sure how useful it would be in practice.

**Comment by JukkaL** [comment]
See the dupe issue #875 for more discussion.

**Comment by rwbarton** [comment]
The flag `--strict-optional` now exists. Is it useful to keep this ticket open?

**Comment by gvanrossum** [comment]
IMO the ticket should remain open until strict optional checking is the default.
