### ISSUE TITLE
Invalidate cache if plugins change

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3592]
If configured plugins change, type checking results may change and the mypy cache should become stale. Currently we don't track this and users may have to delete their cache manually when plugins change, which is a bad user experience.

It's unclear what's the best way to detect that plugins have changed. Here is a simple idea:
* Add a version string/tuple to all plugin objects. Assume that plugin authors update the version each time there is a plugin behavior change.
* Store information about the versions of all active plugins in cache files (except for the default plugin, which is tied to the mypy version).
* If the set of plugins or a version of any plugin changes, a cache file becomes stale.

**Comment by gvanrossum** [comment]
Maybe we should just hash all the plugin source files together and use that as a guard? It's less precise but safer than relying on developers manually updating version strings. We all start with the best of intentions, but it's easy to forget (unless there's a forcing function like PyPI's refusal to accept a new upload with an old version string).

**Comment by ilevkivskyi** [comment]
I think we should proceed with the hashing plugin code idea. I am going to work in this in next few days.
