### ISSUE TITLE
Packing/unpacking loses type data

### ISSUE THREAD

**Issue by qwertystop** [python/mypy#3594]
Sample:

```
def func(foo: Iterable[Tuple[int, int, str, str]]) -> Iterable[Tuple[Tuple[int, int], str]]:
    for *nums, str_one, str_two in foo:
        yield tuple(nums), str_one + str_two
```

Mypy claims that the yielded value is a `Tuple[Tuple[object, ...], str]`, apparently unable to derive the type of `nums` from the type of `foo` in this situation.

**Comment by gvanrossum** [comment]
The runtime type of `nums` here is `List[int]`, so it is correct that `tuple(nums)` is inferred as type `Tuple[int, ...]`. Mypy doesn't preserve the information that `nums` has length 2.

So I don't think this is a bug.

**Comment by qwertystop** [comment]
Ah.
Well, there's an idea... bit long-term, but collection-of-known-length might be a useful thing to put in `typing` if Mypy can't preserve it otherwise.

I might try to come up with an implementation. Probably not, admittedly.

**Comment by gvanrossum** [comment]
It's not in the planning. Before you try to implement this, please realize that mypy doesn't directly use typing.py -- it does a static analysis of your source code without running any of it.
