### ISSUE TITLE
Using bytes function with encoding parameter shows mypy error in Python 2 mode

### ISSUE THREAD

**Issue by bendtherules** [python/mypy#3597]
In mypy python 2 mode,
`bytes("anything", encoding="utf-8")`
raises error
`Unexpected keyword argument "encoding" for "str"`

As I understand, this is because `bytes` is mapped to `str` internally for python 2 mode
But the `bytes` function allows this encoding parameter, which `str` doesnt

**Comment by JukkaL** [comment]
I can't get Python 2 to accept the `encoding` keyword argument:

```
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> bytes("anything", encoding="utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: str() takes at most 1 argument (2 given)
```

`bytes` is just an alias of `str` at runtime, so it seems to me that mypy is correct:
```
>>> bytes is str
True
```

**Comment by bendtherules** [comment]
Hmm, you are correct. I didn't test properly.
Closing it.
