### ISSUE TITLE
Generic metaclasses impossible

### ISSUE THREAD

**Issue by rkr-at-dbx** [python/mypy#3602]
```
from typing import Generic, GenericMeta, TypeVar
import six

_T = TypeVar('_T')

class Meta(type, Generic[_T]): pass

class Class(six.with_metaclass(Meta[int])): pass
```

This results in:

`example.py:8: error: Dynamic metaclass not supported for 'Class'`

... even though the metaclass is known at typecheck-time.

**Comment by ilevkivskyi** [comment]
PEP 484 specifies: ``Generic metaclasses are not supported.`` So that this is not a bug. I am not sure this is an important feature.
