### ISSUE TITLE
Understanding the length of a map over a tuple

### ISSUE THREAD

**Issue by DGrady** [python/mypy#3623]
This seems like it should type check:

```python
import typing as T

def thing(data: T.Tuple[int, int]) -> T.Tuple[int, int]:
    return tuple(map(lambda x: x+1, data))
```

But mypy 0.501 reports `error: Incompatible return value type (got Tuple[int, ...], expected "Tuple[int, int]")`. Would it make sense for mypy to understand that, when `data` is a tuple, `map(..., data)` will have the same length as `data`?

**Comment by gvanrossum** [comment]
I don't think so -- the length of an iterator or sequence is not part of its type in the PEP 484 type system, and special-casing map() with a tuple argument isn't enough -- that would still just return an iterator (at least in PY3) so you'd have to special-case the combination tuple(map()). That just sounds extremely awkward to me.
