### ISSUE TITLE
List[Tuple[Union[...], Union[...]]] fails to type check

### ISSUE THREAD

**Issue by rowillia** [python/mypy#3624]
Repro:

```python
from typing import Any, Iterable, Union, Text, Tuple, List

KeyType = Union[Text, bytes, float, int]

def foo(a: KeyType, b: KeyType, c: Tuple[KeyType, KeyType], x: Iterable[Tuple[KeyType, KeyType]]) -> None:
    pass


def bar(x: List[Tuple[KeyType, KeyType]]) -> None:
    pass

x: List[Tuple[int, str]] = [(1, 'hello')]
foo(x[0][0], x[0][1], x[0], x)
bar(x)  # error: Argument 1 to "bar" has incompatible type List[Tuple[int, str]]; expected List[Tuple[Union[str, bytes, float, int], Union[str, bytes, float, int]]]
```

What's odd is that every element of `x` in the above example type checks correctly with `foo`, and it even works if we declare the parameter as a `Iterable`, but fails as soon as `x` is a `List`

**Comment by JelleZijlstra** [comment]
That's because of invariance. `List` is invariant in its type argument.

**Comment by ilevkivskyi** [comment]
Yes, I don't think this is a bug. There are already two issues for giving a better error message in such situations: #1115 and #3352.

**Comment by JukkaL** [comment]
Using`Mapping` instead of `List` may work, since the prior is covariant.
