### ISSUE TITLE
Error when accessing attribute of inner class

### ISSUE THREAD

**Issue by rowillia** [python/mypy#3635]
test_inner_class_attribute.py:
```python
class Foo:
    class Meta:
        name = 'Roy'

print(Foo().Meta.name)
```

Python executes the code just fine:

```bash
$ python3.6 test_inner_class_attribute.py
Roy
```

But mypy fails to typecheck

```bash
$ mypy test_inner_class_attribute.py
test_inner_class_attribute.py:5: error: Member "Meta" is not assignable
```

This pattern is super common in the [Django Rest Framework](http://www.django-rest-framework.org/api-guide/fields/#readonlyfield), [Marshmallow](http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.Schema.Meta), and [PynamoDB](http://pynamodb.readthedocs.io/en/latest/tutorial.html#defining-a-model) projects (Probably more that I don't know about as well 😄 )

**Comment by ethanhs** [comment]
Interesting. This will pass typechecking:
```
from typing import Any
class A:
    class B:
        pass
    b = B()
reveal_type(A().b)
reveal_type(A.B)
```
```
main.py:6: error: Revealed type is 'main.A.B'
main.py:7: error: Revealed type is 'def () -> main.A.B'
```
So the issue seems to be that B is being inferred as a function.

**Comment by rowillia** [comment]
@ethanhs yeah debugging that now.  The issue is when analyzing the member access the type is `TypeInfo` which then falls through here -
 https://github.com/python/mypy/blob/master/mypy/checkmember.py#L269

**Comment by ethanhs** [comment]
Yep, that makes sense. Shouldn't be too bad to fix if you add handling of member classes.
