### ISSUE TITLE
Problems using class type variable in class methods

### ISSUE THREAD

**Issue by LiraNuna** [python/mypy#3645]
Follow up from a discussion on gitter:

```python
from typing import *


T = TypeVar('T')
class Factory(Generic[T]):
    @classmethod
    def instance(cls) -> 'Factory[T]':
        return cls()

    def produce(self) -> T:
        raise NotImplementedError()

    @classmethod
    def get(cls) -> T:
        return cls.instance().produce()


class HelloWorldFactory(Factory[str]):
    def produce(self) -> str:
        return 'Hello World'


# factory.py:25: error: Incompatible return value type (got "T", expected "str")
def error_with_mypy() -> str:
    return HelloWorldFactory.get()
```

@ilevkivskyi mentioned this should not error and that this code is valid. I don't have the necessary context to understand how to classify this issue.

**Comment by ilevkivskyi** [comment]
I would simplify the example to show only the essential part:
```python
class Factory(Generic[T]):
    def produce(self) -> T:
        ...
    @classmethod
    def get(cls) -> T:
        return cls().produce()

class HelloWorldFactory(Factory[str]):
    def produce(self) -> str:
        return 'Hello World'

reveal_type(HelloWorldFactory.get())  # mypy should be able to infer 'str' here
```
On one hand, type variables are bound on instances, not on classes, but in case of a non-generic subclass I think the type variable can be bound on that class. The problem however is that we need to give a clear error message when this is not possible, something like (using above example):
```python
Factory.get()  # E: cannot bind type variable on class (use an instance or a non-generic subclass)
Facrory[int].get()   # E: cannot bind type variable on class (use an instance or a non-generic subclass)
```

**Comment by JukkaL** [comment]
Similar issues have come up previously, so this would perhaps be a reasonable feature to have eventually -- at least assuming the implementation isn't very complex.

**Comment by gvanrossum** [comment]
The `produce()` method is also irrelevant to the example. Shorter yet self-contained:
```py
from typing import Generic, TypeVar
T = TypeVar('T')
class Factory(Generic[T]):
    @classmethod
    def get(cls) -> T: ...
class HelloWorldFactory(Factory[str]): pass
reveal_type(HelloWorldFactory.get())  # mypy should be able to infer 'str' here
```

**Comment by rowillia** [comment]
@JukkaL Do you have any thoughts on what it would take to fix this?  It's blocking us here at Lyft.

**Comment by JukkaL** [comment]
@rowillia My recommendation is to use a regular method instead of a class method. Example:

```py
from typing import Generic, TypeVar

T = TypeVar('T')

class Factory(Generic[T]):
    def get(cls) -> T: ...

class _HelloWorldFactory(Factory[str]): pass

HelloWorldFactory = _HelloWorldFactory()  # This singleton is mostly for convenience

reveal_type(HelloWorldFactory.get())  # this is 'str'
```

You can avoid the singleton by using `HelloWorldFactory().get()` instead.

**Comment by JelleZijlstra** [comment]
That method returns an instance of `G[T]`.

**Comment by glyph** [comment]
According to `reveal_type` it returns an instance of `G[<nothing>]`.

**Comment by glyph** [comment]
More specifically: `G[int].m()` returns `G[<nothing>]`.

**Comment by JelleZijlstra** [comment]
Oh, I think in this case it's basically equivalent to a top-level function returning `G[T]`: there is nothing to constrain the value of the typevar, so mypy infers "<nothing>". I believe there's a separate issue about that.

**Comment by ilevkivskyi** [comment]
@glyph 
> If this is the case, then why is ... not itself an error?

Because it is not, it may be bound in a subclass as said few word later in the comment you quote, there is even a simple example just few comments above https://github.com/python/mypy/issues/3645#issuecomment-313237283

**Comment by LiraNuna** [comment]
@ilevkivskyi Thank you for fixing this issue!
