### ISSUE TITLE
Erroneous argument errors where os.PathLike is acceptable as of 3.6

### ISSUE THREAD

**Issue by OJFord** [python/mypy#3649]
In 3.6, [`subprocess.run`](https://docs.python.org/3/library/subprocess.html#subprocess.run) accepts an `os.PathLike` argument for `cwd`.

mypy says:

> Argument 2 to "run" has incompatible type _PathLike[Any]; expected "Union[bytes, str]"

Similarly `os.path.join`, and `os.listdir`. `os.makedirs` is fine though, which is what led me to assume that this is a bug rather than just not yet implemented.

In 3.6.1, [`ConfigParser.read`](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read) accepts an `os.PathLike` argument for `filenames`.

mypy says:

> Argument 1 to "read" of "RawConfigParser" has incompatible type "object"; expected "Union[str, Sequence[Str]]"

(`object`, I suppose, because I passed the return of `os.path.join` directly without hinting.)

**Comment by ilevkivskyi** [comment]
It seems to me this might be just a typeshed issue. You could submit a PR with updated function signatures here: https://github.com/python/typeshed

**Comment by JukkaL** [comment]
Yes, this sounds like a typeshed issue.
