### ISSUE TITLE
Protocols are too "eager" to match an overload

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3656]
This is a follow-up for #3132 (this does not happen on master).

Consider this example found by @JukkaL in #3132:
```python
from typing import Mapping, Any
import sqlite3

class dict_like_row(sqlite3.Row, Mapping[str, Any]):
    def f(self) -> None:
        d = dict(self)  # Need type annotation for variable   <--- wasn't required before
```

It looks like this problem appears because ``sqlite3.Row`` has an untyped ``__iter__`` and it is therefore considered a subtype of ``Iterable`` protocol and therefore matches another overload of ``dict`` constructor (annotating ``Row.__iter__`` fixes the problem).

It is not clear what is the right way here, maybe we can somehow tweak overload similarity in case of an unsuccessful inference (here e.g. ``Tuple[KT, VT]`` never matches ``Any``).

**Comment by ilevkivskyi** [comment]
> protocols are black magic to me tbh

Why??? They are so nice :-)

Just to give a bit more details the problem was that `dict` has an overloaded constructor that includes these two overloads:
```python
    @overload
    def __init__(self, map: Mapping[KT, VT], **kwargs: VT) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[Tuple[KT, VT]], **kwargs: VT) -> None: ...
```
before protocols, the class in example only matched the first overload, but after `Iterable` became structural, the class is also a structural subtype of `Iterable[Any]`, so it matches the second one too. Moreover, it was matched preferably, because IIRC structural matches were given higher similarity for other reasons. Then type inference failed when trying to find any constraints on variables from `Any <: Tuple[KT, VT]` causing this error. Since you removed the similarity concept, the problem has gone, now the first match is chosen. So yes, the problem is fixed.

**Comment by Michael0x2a** [comment]
> > protocols are black magic to me tbh
>
> Why??? They are so nice :-)

I mean the implementation :)

I have no idea how you got recursive Protocols working, for example.
