### ISSUE TITLE
Inconsistent return type when calling overloaded function with Any argument

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3662]
The results of type checking the following fragment are unexpected:

```py
from typing import Any, overload, Union

@overload
def f(x: int) -> int: ...
@overload
def f(x: Union[int, float]) -> float: ...
def f(x): pass

@overload
def g(x: int) -> int: ...
@overload
def g(x: float) -> float: ...
def g(x): pass

a: Any
reveal_type(f(a)) # Any   <--- okay
reveal_type(g(a)) # int   <--- unexpected
```

The correct result would arguably be `Any` for both of the calls. `Union[int, float]` should be equivalent to just `float`.

This seems to interact with the result type of `os.path.join` in Python 2 mode with #3300.

**Comment by ilevkivskyi** [comment]
On current master both of them return ``int``.

**Comment by ethanhs** [comment]
Interestingly, with `strict-optional` it reports 
```
main.py:4: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
main.py:16: error: Revealed type is 'Any'
main.py:17: error: Revealed type is 'builtins.int'
```

**Comment by ilevkivskyi** [comment]
Something strange happens, I just installed from master on another machine and it gives me:
```
tst22.py:16: error: Revealed type is 'Any'
tst22.py:17: error: Revealed type is 'builtins.int'
```
_both_ with and without ``--strict-optional``. I tried this twice, probably my previous comment is just wrong.

**Comment by ethanhs** [comment]
Strange. Just to avoid concerns about inconsistencies, I should have mentioned I was using 0.521, so it seems the overload issue was fixed in master.
