### ISSUE TITLE
Option for force mypy to treat a constant as always true or always false

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3668]
It's not uncommon to have constants such as `IS_MAC` or `IS_PROD` that are always true or false during a single program run, but the actual value depends on some potentially complex runtime check. Maybe mypy should provide a way of configuring the values of such constants. Example where this would be useful:

```py
...
if IS_MAC:  # only one of the definitions of Window should be type checked
    class Browser: ...  # mac-specific definition
else:
    class Browser: ...  # windows-specific definition
```

Mypy shouldn't generate `"Browser" redefined` errors for the second definition. It would be nice to be able to run mypy twice to type check both of the conditional definitions. Potential way to do it:

```
$ mypy --always-true=IS_MAC program.py
$ mypy --always-false=IS_MAC program.py
```

Some of these could be refactored into `sys.platform` checks that mypy already supports, but for existing code this can be a lot of work, and this doesn't work for non-platform checks such as dev vs. prod checks.

**Comment by ilevkivskyi** [comment]
(Raising priority back to high because it causes big troubles in some internal codebases.)

**Comment by gvanrossum** [comment]
Assuming we can do this in the same half-hearted way as we currently
support MYPY and TYPE_CHECKING, I can do this.
