### ISSUE TITLE
Enable `cast` usage in type comments

### ISSUE THREAD

**Issue by OddBloke** [python/mypy#3670]
I'm annotating a codebase that needs to run under Python 2.7, 3.4 and 3.5. As such, I'm putting the type annotations in comments. This has the convenient side effect that I don't have to ensure that `typing` is installed where the code is used, because the variables from typing are never actually used in the code. Specifically, I can just do this where needed:

```py
try:
    from typing import ...
except ImportError:
    pass
```

Unfortunately, if I get in to a situation where I need to cast a variable to another type, this side effect disappears; I have to be able to import `cast`, and whatever I'm using in the first argument to `cast`, for my script to run at all.

It would be great if I could do something like:

```py
pairs = [tuple(line.split(":", 1)) for line in lines]  # cast: List[Tuple[Text, Text]]
```

to avoid having to modify each environment where my codebase is used (which, in fact, will really mean that I have to either not annotate or have my types be a lot less useful).

**Comment by OddBloke** [comment]
Now, it's feasible that I could work around this to some extent (I haven't actually tested the below):

```py
try:
    from typing import cast, List, Text, Tuple
    PairType = List[Tuple[Text, Text]]
except ImportError:
    cast = lambda typ, val: val
    PairType = None

...
pairs = cast(PairType, [tuple(line.split(":", 1)) for line in lines])
...
```

I _think_ this would be a no-op in an environment without typing installed, but still give me the results I wanted during type-checking. But it is **fugly**.

**Comment by OddBloke** [comment]
(I've played around with this a bit more and the actual code I have working is:

```py
try:
    from typing import cast, Text, Tuple
    StringPair = Tuple[Text, Text]
except ImportError:
    cast = lambda typ, val: val  # type: ignore
    StringPair = None  # type: ignore

...
with open(...) as build_info:
    my_mapping = dict(
        cast(StringPair, line.strip().split('=', 1))
        for line in build_info.readlines() if '=' in line)
...
```)

**Comment by gvanrossum** [comment]
Sorry, this is not going to happen. The try/except solution should do it.

**Comment by leonardon473** [comment]
Please consider a cast syntax alternative 
```python
x1 = itertools.combinations('abc', 2)) # cast: Iterable[Tuple[str, str]] 

x2: Iterable[Tuple[str, str]] = itertools.combinations('abc', 2)) # type: cast

x3: Cast[Iterable[Tuple[str, str]]] = itertools.combinations('abc', 2))
```
https://stackoverflow.com/questions/55461519/python-type-hints-better-syntax-for-cast
