### ISSUE TITLE
Error: Cannot infer type argument 1 of "map"

### ISSUE THREAD

**Issue by yammesicka** [python/mypy#3682]
When trying to check the following code using mypy:

```
import itertools
from typing import Sequence, Union, List

DigitsSequence = Union[str, Sequence[Union[str, int]]]


def normalize_input(digits: DigitsSequence):
    return map(str, digits)  # <- The problem is here
```

The following error message occurs:

> calculate.py:16:17: error: Cannot infer type argument 1 of "map"

When changing `DigitalSequence` to be `Sequence[Union[str, int]]`, the problem is gone.

Setting `DigitalSequence` to `Sequence[int]` or to `str` solves the problem. Setting it to `Union[str, Sequence[int]]` does not.

You can see a question in StackOverflow [here](https://stackoverflow.com/questions/44988144/mypy-cannot-infer-type-argument-1-of-map). Thanks [Jacob Budin](https://stackoverflow.com/users/865601/jacob-budin) for helping me to analyzing the problem.

**Comment by gvanrossum** [comment]
Hm, it looks like mypy isn't smart enough to understand that it should just try to type-check the map() call twice (once for each arm of the outer union). Until the bug is fixed you could work around the problem like this:
```py
if isinstance(digits, str):
  return map(str, digits)
else:
  return map(str, digits)
```
(Mysterious, right? :-)

**Comment by ilevkivskyi** [comment]
This is now fixed on master (most likely by the old union math PR).
