### ISSUE TITLE
Catch accidentally abstract classes

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#3692]
We've had a series of typeshed issues where classes accidentally became abstract because an abstract method in a parent class wasn't overridden (see python/typeshed#1476). It would be nice if mypy could tell us about this sort of issue automatically, since for now we have to rely on bug reports from end users.

I'm not sure if there's a good programmatic way to distinguish between accidentally and intentionally abstract classes. Here are a few ideas:
- Warn if a class is abstract, but doesn't itself have any abstractmethods (all abstractmethods are inherited from a parent class).
- Require all intentionally abstract classes to specify ABCMeta as an explicit metaclass. This would be fairly disruptive.
- Don't do anything. This problem has repeatedly affected typeshed, but it's probably much easier to discover outside stubs, since the type checker will also see code using the class, not just its definition like in stubs.

**Comment by ilevkivskyi** [comment]
There was a similar question about protocols, and we basically decided to go with the third option (don't do anything). The only requirement is to always add a ``Protocol`` base if one wants a protocol. However we don't require implementing all abstract methods/variables to be implemented in an explicit subclass, we just create a _nominal_ abstract class. The motivation was the same as yours, this will be quickly caught in _non-typeshed_ code.

**Comment by Michael0x2a** [comment]
Just as a thought -- we could perhaps hold typeshed to a higher standard compared to user code and have mypy + related tools perform stricter checks. Basically, do either options 1 or 2 or both when parsing typeshed (so the errors are immediately caught), but leave those checks disabled by default for regular code?

We could perhaps hijack mypy's per-file options code in some way to do this relatively cleanly.

**Comment by gvanrossum** [comment]
I kind of like option (2), require an explicit ABCMeta (or something
derived from it?).

**Comment by graingert** [comment]
I don't think intentionally abstract classes need to define an ABCMeta if they inherit from one.

Would be better to use a noop decorator

**Comment by gvanrossum** [comment]
Now we're discussing personal preferences right? Or do you have some evidence or at least data you can point at to support your point?

**Comment by graingert** [comment]
@gvanrossum add the metaclass=ABCMeta changes the behaviour of the "intentionally abstract class"

**Comment by elazarg** [comment]
One possible way to avoid it is to have explicit instantiation for all classes in typeshed, as a test

**Comment by gvanrossum** [comment]
I [proposed](https://github.com/python/mypy/issues/3705#issuecomment-314810656) that previously. However this would require constructing correct arguments (at least for mandatory ones).

**Comment by elazarg** [comment]
Sorry, I didn't see it. Maybe it's possible to generate calls that cast None to something compatible to the declared argument, or just use `Any`s.
