### ISSUE TITLE
Imported objects and inline functions reveal_type() as Any

### ISSUE THREAD

**Issue by cricalix** [python/mypy#3695]
I may be doing something really wrong here with reveal_type(). I've skimmed through the issue list, and not seen anything that seems to match.

The attached files have a series of cases where reveal_type() says Any, despite a constant signature on every method/function.

A simple example where reveal_type() is correct:
```
# (imported.py)
def string_or_none(string: bool = True) -> Optional[str]:
    if string:
        return 'I am a string'
    else:
        return None


reveal_type(string_or_none())  # Union[str, None]
```

A simple example where reveal_type() says Any, not Union[str, None] (the bogus self doesn't affect the result):
```
def test_all_the_things(self):
    def inline_string_or_none(self, string: bool = True) -> Optional[str]:
        if string:
            return 'I am a string'
        else:
            return None
    reveal_type(inline_string_or_none())  # Any
```

If string_or_none() is defined in imported.py, then the reveal_type() result in the importing file will be Any:
```
# (test_imported.py)
import imported
reveal_type(imported.string_or_none())  # Any
```

[imported.txt](https://github.com/python/mypy/files/1139448/imported.txt)
[test_imported.txt](https://github.com/python/mypy/files/1139449/test_imported.txt)

**Comment by cricalix** [comment]
Hah, I forgot the version - mypy 0.520-dev

**Comment by ilevkivskyi** [comment]
The point is that per PEP 484 non-annotated functions are not checked (like your ``test_all_the_things``). If you still want to check them use ``--check-untyped-defs``.

**Comment by ilevkivskyi** [comment]
By the way you could update to 0.520 released recently, that introduces fine grained control over ``Any``, [see release notes](http://mypy-lang.blogspot.ch/2017/07/mypy-0520-released.html)

**Comment by cricalix** [comment]
Ok, it's a "you're doing it wrong" thing. I'll see about the 0.520 thing - that's upstream of me, I use what appears on my server :)

**Comment by cricalix** [comment]
Though, even if I fix the typing on test_all_the_things (or use --c-u-d), I get a reveal_type response of builtins.str, which doesn't seem quite right given the Optional[] use.

**Comment by ilevkivskyi** [comment]
> Though, even if I fix the typing on test_all_the_things (or use --c-u-d), I get a reveal_type response of builtins.str, which doesn't seem quite right given the Optional[] use.

For this you need to use ``--strict-optional`` (there is a plan to turn it on by default in future).
