### ISSUE TITLE
kwargs expansion does not work with union types

### ISSUE THREAD

**Issue by mikn** [python/mypy#3709]
Hi! So I'm new to trying out mypy, but I'm encountering an error when I try to do a kwargs expansion into a method with Union types as follows:
```python
from collections import NamedTuple
from typing import Dict, Union
class TestNamedTuple(NamedTuple):
    str_type: str
    int_type: int
d = None # type: Dict[str, Union[str, int]]
test = TestNamedTuple(**d)
```
A minimal repro case:
```python
from typing import Dict, Union
def test_case(self, str_type: str='', int_type: int=0) -> None: pass
d = None # type: Dict[str, Union[str, int]]
test_case(**d)  # error: Argument 1 to "test_case" has incompatible type **Dict[str, Union[str, int]]; expected "int"
```
This works splendidly:
```python
from typing import Dict
def test_case(self, str_type: str='', int_type: str='') -> None: pass
d = None # type: Dict[str, str]
test_case(**d)
```

I understand that the typing leaves no guarantee in terms of typing of the individual kwargs and I may well end up with a type error down the road with this, but I guess even if it isn't supposed to be supported that the error message could be more informative?

**Comment by gvanrossum** [comment]
Honestly I think this is as intended. The type for `d` in your first example, `Dict[str, Union[str, int]]`, allows values like `{'str_type': 42, 'int_type': 'abc'}` and using that in the call to `test_case(**d)` will fail at runtime.

Maybe you're looking for `TypedDict` though? http://mypy.readthedocs.io/en/latest/kinds_of_types.html#typeddict
