### ISSUE TITLE
pip install -e

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [python/mypy#3710]
Hi Mypy ppl,

I really like your package. Right now I'm having problems using it with a package that I have installed with `pip install -e some/path/to/package`.

**Comment by ethanhs** [comment]
Hello, Mypy is meant to be used on the source of your package. So you should be able to run `mypy some/path/to/package` and if that folder has a `__init__.py`, mypy will run over the sources in the folder. Note that Mypy does not check untyped functions by default.

**Comment by miedzinski** [comment]
There is no need for `__init__.py` file since Python 3. Mypy typechecks packages without that file.

```bash
(mypy-dev) ~/src/mypy [master] λ mkdir x
(mypy-dev) ~/src/mypy [master] λ echo "x: int = 'a'" > x/y.py
(mypy-dev) ~/src/mypy [master] λ mypy x
x/y.py:1: error: Incompatible types in assignment (expression has type "str", variable has type "int")
```
