### ISSUE TITLE
Not finding typeshed should produce an error

### ISSUE THREAD

**Issue by ilinum** [python/mypy#3715]
Currently, if mypy can't find the typeshed repo for some reason, it doesn't produce an error.
We probably should output an error and exit with some non-zero exit code.

**Comment by JukkaL** [comment]
Even worse, typically mypy will crash if it doesn't find typeshed for some reason.

**Comment by ethanhs** [comment]
Technically, it [should raise an error](https://github.com/python/mypy/blob/master/mypy/build.py#L258). However, I believe there are times where [this branch](https://github.com/python/mypy/blob/master/mypy/build.py#L214) resolves incorrectly, but to a valid path, and thus allows for the program to continue till we try to access builtins. I suggest we have a flag that helps debug this type of issue, by printing debug information based on the things done in `build.py`, so people can report what paths mypy _is_ looking for.

**Comment by gvanrossum** [comment]
Maybe just use `-v`? You'd have to add extra arguments to add access to the `Options` object, and you'd have to write a little `log()` function (I'm wondering if that should be a method on `Options` -- perhaps an odd place for logging but would make it easy to use). A new flag wouldn't make any of this easier (unless you want the flag always on -- then `-v` is too verbose).

**Comment by ethanhs** [comment]
#3862 should help with this. I'm not aware of other cases we don't handle.

**Comment by ethanhs** [comment]
Closing as we now report errors with finding typeshed.
