### ISSUE TITLE
Mypy skips `a.b.method(...)` for `import a.b` with --follow-imports=skip

### ISSUE THREAD

**Issue by m0sth8** [python/mypy#3716]
I have this structure 

```
└── a
    ├── __init__.py
    ├── b.py
    └── c.py
```

`__init__.py` is empty.

`cat b.py`
```
def method(val):
    # type: (dict) -> None
    print(val)
```
`cat c.py`
```
import a.b
from a.b import method

def main(val):
    # type: (str) -> None
    a.b.method(val) # line 6
    method(val)     # line 7

if __name__ == "__main__":
    main("data")
```
If I run mypy with option ` --follow-imports=skip`

Actual:
```
> mypy --follow-imports=skip ./a/b.py ./a/c.py
a/c.py:7: error: Argument 1 to "method" has incompatible type "str"; expected Dict[Any, Any]
```
Expected:
```
> mypy --follow-imports=skip  ./a/b.py ./a/c.py
a/c.py:6: error: Argument 1 to "method" has incompatible type "str"; expected Dict[Any, Any]
a/c.py:7: error: Argument 1 to "method" has incompatible type "str"; expected Dict[Any, Any]
```

For --follow-imports=normal it works as expected:
```
> mypy ./a/b.py ./a/c.py
a/c.py:6: error: Argument 1 to "method" has incompatible type "str"; expected Dict[Any, Any]
a/c.py:7: error: Argument 1 to "method" has incompatible type "str"; expected Dict[Any, Any]
```

**Comment by ethanhs** [comment]
I believe this should work the opposite of the way you would expect. [The docs](https://mypy.readthedocs.io/en/latest/command_line.html#following-imports-or-not) for skip say:
> - skip don't follow imports, silently replacing the module (and everything imported from it) with an object of type Any. (This option used to be known as --silent-imports and while it is very powerful it can also cause hard-to-debug errors, hence the recommendation of using silent instead.)

I believe _neither_ should give an error. I think the issue is that `from a.b import method` is not being `Any`'d. Modifying your main function:
```
def main(val):
    # type: (str) -> None
    # this is as expected
    reveal_type(mypytest.b.method)  # E: Revealed type is 'Any'
    # this is not
    reveal_type(method)  # E: Revealed type is 'def (val: builtins.dict[Any, Any])'
```

**Comment by hauntsaninja** [comment]
Stale, also I think we follow the import because it's passed on command line
