### ISSUE TITLE
Support Python 3.4 on Windows?

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#3722]
I recently made the changes needed to `typed_ast` (see https://github.com/python/typed_ast/pull/47) for VS 2010 compilation support, so that Python 3.3 and 3.4 work on Windows, for typed_ast and mypy.

The only other issue with support for these Python versions on Windows is lxml, which provides a wheel for 3.4 32 bit, but not 64 bit (this seems to be an oversight, I plan on filing a bug report). Wheels for 3.3 are provided.

I don't think it make sense to add support for 3.3 since its EOL is in just over 2 months.

For reference 3.4's EOL is in 2019.

**Comment by ilinum** [comment]
We should probably remove our dependency on `lxml` altogether but this is a complicated task (#909).

**Comment by JelleZijlstra** [comment]
lxml isn't actually an installation dependency though, since it's used only for a report. Perhaps we should support 3.4 on Windows except for the lxml report, which most users probably don't need anyway.

**Comment by ethanhs** [comment]
I think that would be okay. And if someone tries to use it they will get an import error and install it themselves, so I don't see it as a problem.

**Comment by ethanhs** [comment]
https://github.com/python/typed_ast/pull/47 was just merged, so I will start working on the changes, unless there is objection.

**Comment by ethanhs** [comment]
We now support this, so Im closing.
