### ISSUE TITLE
“expects {} type arguments,” reported on the wrong file

### ISSUE THREAD

**Issue by ProgVal** [python/mypy#3730]
Hi,

Mypy detects invalid type definitions when they are used, not when they are defined -- and uses the file name of the usage to report errors, but the line number of the definition.

As you can see:

```
$ cat --number foo.py
     1	from typing import *
     2	
     3	Foo = NamedTuple('Foo', [
     4	    ('tags', Dict[object]), # line 4
     5	    ])
$ cat --number bar.py
     1	from typing import *
     2	from foo import Foo
     3	#########
     4	# line 4
     5	#########
     6	
     7	def bar(f:Foo):
     8	    pass
$ mypy bar.py   
bar.py:4: error: "dict" expects 2 type arguments, but 1 given
```

The error should be on `foo.py:4`, not `bar.py:4`.

```
$ mypy --version
mypy 0.470
```

**Comment by ilevkivskyi** [comment]
Sorry for this experience (I could imagine your surprise to see an error on an empty line :-)
Fortunately, this is already fixed on master, so you just need to upgrade ``python3 -m pip install -U mypy``.
