### ISSUE TITLE
Release mypy 0.521

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#3732]
We're going to try and release a bugfix release for 0.520, dubbed 0.521. The plan is to do this relatively quickly, using a release branch forked from v0.520, **cherry-picking only essential fixes** for announced features and for regressions since 0.510. I am going to be the release manager. We will have a new blog post. I'm aiming to do the release on Monday 7/24.

I plan to *also* create a release branch for typeshed, so we can cherrypick typeshed commits as well.

If you have a mypy or typeshed bugfix (already merged on master) that should really go in please mention it here (I have a few in mind already).

**Comment by ilevkivskyi** [comment]
I think https://github.com/python/mypy/pull/3680 could go in. It fixes a high priority issue (probably because this is "incompleteness" in an announced feature).

**Comment by gvanrossum** [comment]
> I think #3680 could go in.

I'm not so sure, it's not even merged in master.

**Comment by ilevkivskyi** [comment]
> I'm not so sure, it's not even merged in master.

OK, sorry I misunderstood you, I thought you meant PRs that might go in.

**Comment by gvanrossum** [comment]
I do have a question for @ilevkivskyi. Should #3700 and its fix, #3719, go in? This fixes a crash (on something that was merely an error in 0.511); but the fact that the fix needed a fix is a bit worrysome.

**Comment by ilevkivskyi** [comment]
> Should #3700 and its fix, #3719, go in? This fixes a crash (on something that was merely an error in 0.511); but the fact that the fix needed a fix is a bit worrysome.

I would say rather yes than no. Although this touches a "fundamental" thing -- the lookup function.
Concerning the fix that needed a fix, yes first time I didn't really made a "semantically equivalent" transformation, my fault. Also note that the initial crash itself is caused by an assert in one of the ``--strict-optional`` PRs. I think we will see more crashes like this in nearest future that are subtle to fix, but this is probably how ``--strict-optional`` works in general -- adding asserts finds some corner cases in the logic.

**Comment by gvanrossum** [comment]
OK, makes sense. Added them.

**Comment by gvanrossum** [comment]
Also, note that this is *not* a feature freeze for master! Just perhaps don't land sweeping refactors since they might complicate cherry-picking bug fixes into the release branch.

**Comment by gvanrossum** [comment]
Two pending fixes that should go in:
- @JukkaL has a crash fix for TypedDict (but not yet made the PR).
- @ddfisher has a fix for strict-optional (https://github.com/python/mypy/pull/3686).

**Comment by JelleZijlstra** [comment]
From typeshed I think we should include only 7637549ced002ea121d2abde7d97203f666fbb87, which fixes a regression in csv.DictReader, python/typeshed#1475. I looked at commits since 0e26c1f, the version of typeshed that was released with 0.520.

**Comment by gvanrossum** [comment]
> From typeshed I think we should include only 7637549ced002ea121d2abde7d97203f666fbb87

Thanks, that was my conclusion too, and I've already cherry-picked it!

**Comment by graingert** [comment]
Also https://github.com/python/typeshed/commit/2bb7ea95951047257cdd20c98f38f6fe6cb3ad2a

**Comment by gvanrossum** [comment]
@graingert 
>Also python/typeshed@2bb7ea9

Hm, that's https://github.com/python/typeshed/pull/1478 -- is that also a regression? We're trying to exercise an abundance of caution here, so the default is not to cherry-pick anything unless it worked in 0.510 but is broken in 0.520.

**Comment by graingert** [comment]
I believe it was, I haven't had time to verify 100%

**Comment by graingert** [comment]
@gvanrossum yes this is a regression from 0.511

**Comment by gvanrossum** [comment]
OK I've cherrypicked it.

**Comment by graingert** [comment]
@gvanrossum ok great, thanks!

**Comment by gvanrossum** [comment]
Status update: the release is out on PyPI and tagged as v0.521. I'm keeping this issue open until we've updated the blog post, which will probably happen tomorrow.

**Comment by Deimos** [comment]
Could you please update the homepage at http://mypy-lang.org/ as well? I didn't realize there was a blog post for 0.520 since it isn't in the What's New section there and I didn't check the blog directly.

**Comment by gvanrossum** [comment]
Yes, we we're waiting for the 0.621 release.

**Comment by graingert** [comment]
@gvanrossum 0.521?

**Comment by gvanrossum** [comment]
Yeah, blame cell phones and my poor proofreading skills. ;-)

In retrospect I think we should've posted the 0.520 blog post to the website even though we realized soon there were some regressions. Jukka has long gone to bed (he's in Finland). Tomorrow (in the am US time) we'll upload a new (minimal) blog post and updated the website.

**Comment by gvanrossum** [comment]
Well, the blog post is up (http://mypy-lang.blogspot.com/2017/07/mypy-0521-released.html) and the website is updated (http://mypy-lang.org/), so I'm closing this. I'm still considering whether to merge #3762.

**Comment by graingert** [comment]
>  I'm still considering whether to merge #3762.

So you can see what this would look like, I created a merge commit using [git-reparent](https://github.com/MarkLodato/git-reparent): https://github.com/graingert/mypy/commit/7ad61331f8065dafe3886ab45949a758fd989a9a

**Comment by gvanrossum** [comment]
Glad that it turns out to be null merge (presumably because I cherry-picked the little doc update back). I then propose to not merge the branch, since release branches are, well, branches.
