### ISSUE TITLE
Subclasses of NamedTuple

### ISSUE THREAD

**Issue by ProgVal** [python/mypy#3739]
Hi,

I often use a subclass to a namedtuple to add optional arguments (and/or methods) to a namedtuple.

For instance, this gives this kind of code:

```python
     1	from typing import *
     2	
     3	_Foo = NamedTuple('_Foo', [
     4	    ('bar', str),
     5	    ('baz', str),
     6	    ])
     7	
     8	class Foo(_Foo):
     9	    def __new__(cls, bar, baz='z') -> 'Foo':
    10	        return _Foo.__new__(cls, bar, baz)
    11	
    12	def f() -> None:
    13	    print(repr(Foo('r')))
    14	
    15	f() # prints Foo(bar='r', baz='z')
```

which I think is completely valid Python.

However, Mypy raises the following errors:

```
foo.py:10: error: Too many arguments for "__new__" of "object"
foo.py:10: error: Argument 1 to "__new__" of "object" has incompatible type Type[Foo]; expected Type[object]
foo.py:13: error: Too few arguments for "Foo"
```

Is there something I am doing wrong?

Thanks!

**Comment by ProgVal** [comment]
I didn't know I could use `super()` in `__new__`, thanks.

I replaced `_Foo` with `super()`, and now I am only getting this:

```
foo.py:13: error: Too few arguments for "Foo"
```

**Comment by ilevkivskyi** [comment]
@ProgVal 
By the way, switching to Python 3.6 will give you ``typing.NamedTuple`` that supports optional arguments, methods, docstrings, and nice static typing (supported by mypy):
```python
from typing import NamedTuple

class Link(NamedTuple):
    """Represent a link between two nodes."""
    start: int
    end: int
    label: str = '<no name>'
    def weight(self) -> float:
        return abs(self.end - self.start)/2
```

**Comment by Daenyth** [comment]
Since you're on python3, you might want to use the syntax instead, like this:
```
class Foo(NamedTuple):
    bar: str
    baz: str = 'z'
```

I use this in my project and mypy deals with it just fine. It's also much more readable.

**Comment by ilevkivskyi** [comment]
Concerning ``__new__`` we already have https://github.com/python/mypy/issues/1279 so that this one can be closed
