### ISSUE TITLE
Do some type checking in functions without annotations

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#374]
Currently we don't type check functions without type annotations, even in modules that import `typing`. However, it might be better to run type checker for all functions. In functions without annotations every local variable (and argument) would have implicit `Any` types. This would let us catch some simple type errors within expressions, at least.

**Comment by sanxiyn** [comment]
> In functions without annotations every local variable (and argument) would have implicit `Any` types.

Can one assume types for `self` arguments in methods?

**Comment by JukkaL** [comment]
Closing this since `--check-untyped-defs` provides this functionality.
