### ISSUE TITLE
ClassVar marking not automatically inferred for subclasses

### ISSUE THREAD

**Issue by li-dan** [python/mypy#3748]
mypy emits an error for this code:

```python
from typing import ClassVar


class A:
    x: ClassVar[str] = "A"


class B(A):
    x = "B" # Cannot override class variable (previously declared on base class "A") with instance variable
```

I'd expect the type of `B.x` to be automatically inferred as `ClassVar[str]`, instead of requiring an explicit annotation.

**Comment by ilevkivskyi** [comment]
Thanks for reporting!

I am not sure we should do this. Since we can't be sure what is the user's intent. Maybe a user just forgot to remove the ``ClassVar`` annotation in ``A``? I think "explicit is better than implicit" works in this case, plus it is consistent with how method inheritance currently behaves (we require annotations even if the signature in a subclass is not changed).

**Comment by miedzinski** [comment]
I'm pretty sure this was discussed in `ClassVar` PR and we've decided that it should work that way. As long as there is clear error message I don't think there is any problem. All in all, explicit is better than implicit.

**Comment by li-dan** [comment]
I agree that this should fail:

```python
class A:
    x: ClassVar[str] = "A"

class B(A):
    x: str = "B"
```

But I don't like how the current behavior hinders gradual typing by requiring a type annotation in `B` if `A` has a type annotation.

> it is consistent with how method inheritance currently behaves (we require annotations even if the signature in a subclass is not changed).

If a superclass annotates a method, and a subclass overrides that method, the subclass is not forced to add type annotations to that method. (But the subclass's method won't be type checked and will get a signature with `Any`.) It is useful to be able to add type annotations to a class without being required to add annotations to all subclasses.

**Comment by miedzinski** [comment]
But `x = 'x'` will be inferred everywhere to be `str` and I think it should be the same when subclassing. Class hierarchy tends to be split across multiple files so being explicit here is a good thing. The error message from mypy is clear too.

**Comment by li-dan** [comment]
Okay; I will add explicit annotations to the subclasses.
