### ISSUE TITLE
mypy >=0.510 errors in pathlib

### ISSUE THREAD

**Issue by mykter** [python/mypy#3768]
When using mypy 0.501 I can successfully run it against my program.

With mypy 0.510 and 0.521 I get the following error:

```
/usr/local/lib/mypy/typeshed/stdlib/3.5/pathlib.pyi:6: error: TypeVar cannot have only a single constraint
/usr/local/lib/mypy/typeshed/stdlib/3.5/pathlib.pyi:6: error: "object" not callable
/usr/local/lib/mypy/typeshed/stdlib/3.5/pathlib.pyi:15: error: Name 'List' is not defined
/usr/local/lib/mypy/typeshed/stdlib/3.5/pathlib.pyi:17: error: Invalid type "pathlib._P"
/usr/local/lib/mypy/typeshed/stdlib/3.5/pathlib.pyi:22: error: Invalid type "pathlib._P"
<snip more of the same>
```

Ubuntu 16.04, mypy installed globally via pip, pythons 2.7.12, 3.5.2

You can reproduce it with a trivial program that consists solely of:
```python
from pathlib import Path
```

**Comment by ilevkivskyi** [comment]
Hm... Very strange, somehow you have got an old version of the pathlib stub there. What happens if you just rename ``pathlib.pyi`` to ``pathlib.pyi.old``? (I hope you should have a newer version somewhere, probably in 3.4 folder, so mypy should pick it up).

**Comment by ilevkivskyi** [comment]
A more permanent solution would be to just delete the whole ``typeshed`` wherever you can find it, and make a clean install of mypy

**Comment by mykter** [comment]
Thanks!
There was indeed an orphaned copy of mypy that pip didn't know about. Removing it and reinstalling mypy fixed it.

**Comment by lpasselin** [comment]
I had this problem when a dependency was installing mypy-lang while my project uses mypy. 
#2983

**Comment by Alok** [comment]
I have this problem too. Uninstalling and reinstalling mypy .530 doesn't help.

**Comment by ilevkivskyi** [comment]
@Alok have you searched and deleted all copies of ``typeshed`` after uninstalling?

**Comment by Alok** [comment]
Installing with `--no-cache` did the trick.
