### ISSUE TITLE
Move the typing module to a separate installation package

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#377]
The typing module could be more generally useful even outside mypy, such as for annotating code for documentation purposes. Also, other tools such as IDEs, documentation tools could more easily use it.

This discussion on python-ideas is relevant:

https://mail.python.org/pipermail/python-ideas/2014-August/028618.html

**EDIT**: Changed from 'separate project' to a 'separate installation package'

**Comment by JelleZijlstra** [comment]
This is long obsolete, since typing is now in the stdlib and being developed in github.com/python/typing.
