### ISSUE TITLE
Subclasses of a generic class are not permitted when a super class is specified in TypeVar

### ISSUE THREAD

**Issue by vbkaisetsu** [python/mypy#3774]
Example code:
```python
from typing import TypeVar, Generic, Any


T = TypeVar("T", bound="BaseCls")
def f(x: T, y: T) -> int:
    return x.a + y.a


class BaseCls(Generic[T]):
    def __init__(self, a: int) -> None:
        self.a = a

    def add(self, x: T) -> int:
        return self.a + x.a


class Sub1(BaseCls["Sub1"]): pass

class Sub2(BaseCls["Sub2"]): pass


a = Sub1(1)
b = Sub2(2)
result1 = a.add(b) # -> Error (Correct behavior)
result2 = f(a, b) # -> Error (Strange behavior)
```

mypy output:
```
test.py:24: error: Argument 1 to "add" of "BaseCls" has incompatible type "Sub2"; expected "Sub1"
test.py:25: error: Type argument 1 of "f" has incompatible value "object"
```

When "Any" is specified instead of Sub1 and Sub2, the error is not occured.
```python
class Sub1(BaseCls[Any]): pass

class Sub2(BaseCls[Any]): pass


a = Sub1(1)
b = Sub2(2)
result2 = f(a, b) # -> No error
```

**Comment by vbkaisetsu** [comment]
Sorry, this is correct behavior.
I have to use 2 TypeVars like this:

```
T1 = TypeVar("T1", bound="BaseCls")
T2 = TypeVar("T2", bound="BaseCls")
def f(x: T1, y: T2) -> int:
    return x.a + y.a
```

However, I can't understand the reason why subclasses are permitted when Any is specified in inheriting the super class.

**Comment by gvanrossum** [comment]
> Sorry, this is correct behavior.
> I have to use 2 TypeVars like this:
> 
> ```py
> T1 = TypeVar("T1", bound="BaseCls")
> T2 = TypeVar("T2", bound="BaseCls")
> def f(x: T1, y: T2) -> int:
>     return x.a + y.a
> ```

In this case you shouldn't be using type variables at all -- they don't have any effect except for obscuring your meaning. You should just write
```py
def f(x: "BaseCls", y: "BaseCls") -> int:
   ...
```
 
> However, I can't understand the reason why subclasses are permitted when Any is specified in inheriting the super class.

`Any` shuts up a variety of errors about proper typing and this is one of them.
