### ISSUE TITLE
Bad type analysis for instantiation of `Type`

### ISSUE THREAD

**Issue by LiraNuna** [python/mypy#3784]
mypy fails to recognize the conversion of `Type[T]` into `T` via instantiation.

Example code:
```python
from typing import Union, Type, TypeVar

T = TypeVar('T')
def upgrade_to_instance(x: Union[T, Type[T]]) -> T:
    if isinstance(x, type):
        x = x()

    return x
```

**Comment by elazarg** [comment]
Just to be clear:
```python
from typing import Union, Type, TypeVar

T = TypeVar('T')
def upgrade_to_instance(x: Union[T, Type[T]]) -> T:
    if isinstance(x, type):
        reveal_type(x())  # E: Revealed type is 'Any'
        x = x()
    return x
```

**Comment by JukkaL** [comment]
A slightly simpler example:

```py
from typing import Union, Type

def f(x: Union[str, Type[int]]) -> None:
    if isinstance(x, type):
        reveal_type(x)  # Revealed type is 'builtins.type'
```

The expected revealed type is `Type[builtins.int]`, not `builtins.type`.

A simple workaround is to use a cast:

```py
from typing import Union, Type, cast

def f(x: Union[str, Type[int]]) -> None:
    if isinstance(x, type):
        x = cast(Type[int], x)
        reveal_type(x)  # Revealed type is 'Type[builtins.int]'
```

**Comment by ilevkivskyi** [comment]
This is now fixed (most likely by the recent `Type[...]` PR). Jukka's example correctly passes. The original example still produces an error. This is correct because `T` can itself be a type. Adding a bound for example `T = TypeVar('T', bound=int)` (so that `T` can't be a type now) fixes the error.
