### ISSUE TITLE
Signature error with Counter

### ISSUE THREAD

**Issue by Daenyth** [python/mypy#3792]
mypy==0.521

```
from typing import *

c = Counter([('a','b','c'), ('a', 'b', 'c')])
duplicates = [(key, count) for key, count in c.most_common(1) if count > 1]
assert duplicates == [(('a','b','c'), 2)]
```

This file executes without errors, but mypy says
> c.py:4: error: Too many values to unpack (2 expected, 3 provided)

**Comment by ilevkivskyi** [comment]
Thanks for reporting! This looks like a purely [typeshed](https://github.com/python/typeshed) issue. Could you please report this issue there?

**Comment by Daenyth** [comment]
https://github.com/python/typeshed/issues/1511
