### ISSUE TITLE
disallow_subclassing_any should be configurable per-module

### ISSUE THREAD

**Issue by OddBloke** [python/mypy#3800]
I have a codebase that is annotated where I'm introducing an integration with an another project. This integration takes the form of subclassing a super-class from their codebase.

I don't want to allow subclassing of Any for my entire codebase, I really would like to just allow it for this specific module.

(Specifically, when I add the following to `setup.cfg`:

```
[mypy-jenkins_job_linter.jjb_subcommand]
disallow_subclassing_any = False
```

I see this in the output:

```
setup.cfg: [mypy-jenkins_job_linter.jjb_subcommand]: Per-module sections should only specify per-module flags (disallow_subclassing_any)
...
jenkins_job_linter/jjb_subcommand.py:14: error: Class cannot subclass 'TestSubCommand' (has type 'Any')
```
)

**Comment by gvanrossum** [comment]
This seems a simple change to `PER_MODULE_OPTIONS` in mypy/options.py. Can you give that a try?

**Comment by OddBloke** [comment]
Yep, trying that now!
