### ISSUE TITLE
Plugin behaviour dependent on third-party module version?

### ISSUE THREAD

**Issue by jstasiak** [python/mypy#3813]
I was looking at mypy plugin infrastructure the other day and I wondered what's the solution to the following issue (let's assume we have a third party module supermod):

* supermod version 1.1 has function superfun returning types X or Z, depending on some parameter
* supermod version 1.2 has function superfun returning types Y or W, depending on some parameter
* I'd like to have a mypy plugin that can handle both of those versions correctly

In order to do that a plugin would have to be able to inspect version of supermod installed I think... Alternatively the version could be provided in per-plugin options, like https://github.com/python/mypy/issues/3532 describes. What do you think about this?

**Comment by gvanrossum** [comment]
We should wait until https://github.com/python/typing/issues/84 is solved and then make the package version available to plugins.

**Comment by hauntsaninja** [comment]
Closing because stale
