### ISSUE TITLE
mypy cannot find attribute after update from 0.511 to 0.521

### ISSUE THREAD

**Issue by iavael** [python/mypy#3821]
After update of mypy from 0.511 versions these errors started to occur
```
error: Item "IPv4Address" of "Union[IPv4Address, IPv6Address]" has no attribute "reverse_pointer"
error: Item "IPv6Address" of "Union[IPv4Address, IPv6Address]" has no attribute "reverse_pointer"
```
python versions: 3.5, 3.6
mypy versions: 0.520, 0.521

**Comment by JelleZijlstra** [comment]
That seems like a typeshed issue. Is this the IPv4Address class from the ipaddress standard library module?

**Comment by iavael** [comment]
> Is this the IPv4Address class from the ipaddress standard library module

yep

**Comment by msullivan** [comment]
Just tested, seems fixed.

**Comment by ethanhs** [comment]
Yes this was fixed in https://github.com/python/typeshed/pull/1654
