### ISSUE TITLE
Safer treatment of @runtime protocols in isinstance()

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3827]
Currently, ``isinstance`` with protocols uses the same logic as with nominal classes, i.e. only erases the type variables, but sometimes this may be not safe (as discussed in PEP 544), for example:
```python
@runtime
class P(Protocol):
    attr: int

class C:
    attr = 'Hi!'

if isinstance(C(), P):
    # this branch is considered unreachable by mypy, but will be executed
```
The idea is to perform a "deeper" erasure (setting all attribute types to ``Any``) when considering ``isinstance()`` with protocols, thus mimicking the runtime behaviour.

**Comment by ilevkivskyi** [comment]
This is a follow-up for #3132

**Comment by gvanrossum** [comment]
I'm curious how far this should go. With the `@runtime` decorator IIUC an object with a method that has the same name as the protocol but a different signature may be considered an instance of that protocol. Are you proposing to erase this too? (I guess it's fine, but your example and wording aren't very clear about it -- "attributes" is sometimes assumed not to include methods.)

**Comment by ilevkivskyi** [comment]
> I'm curious how far this should go.

TBH I am not sure myself, this is why "discussion needed" label :-) One possible option is to erase types of all attributes (both methods and variables) completely. But maybe this is too radical, and we can for example only erase types of instance variables, but keep the fact that methods are callable (so that they will become ``Callable[..., Any]`` after erasure).

**Comment by AlexWaygood** [comment]
Mypy [no longer considers](https://mypy-play.net/?mypy=latest&python=3.10&flags=warn-unreachable&gist=57130636dba2d7d5610a4322097db65a) the code in the original example unreachable, so I'm closing this issue. (If there's more to be done, feel free to reopen.)
