### ISSUE TITLE
Implement better join and meet for protocols

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3830]
Currently, unrelated protocols give a non-trivial join _only_ if one is a subtype of another. This have several disadvantages. One of the main is the lack of associativity (ditto for meet).

Several ideas for better join were proposed in https://github.com/python/mypy/pull/3132#issuecomment-297415112 and https://github.com/python/mypy/pull/3132#issuecomment-297439663 

This is a follow-up issue for #3132

**Comment by ilevkivskyi** [comment]
Related issue https://github.com/python/mypy/issues/3257

**Comment by ilevkivskyi** [comment]
https://github.com/python/mypy/issues/7932 has an important example for this.

**Comment by JukkaL** [comment]
Closing this since the potential fix looks quite complicated, and the cases where it would help are relatively rare.
