### ISSUE TITLE
Use object as the fallback for various Callable types

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3831]
If a class with `__call__` can be a subtype of `Callable` (#3132 implements this behavior), the fallback of `Callable` types should probably be `object`. For function objects defined using `def`, it's perhaps still fine to use a different callback.

Additionally, callable protocol members should probably all have a `object` as the fallback, even those defined using `def`. A concrete subtype of a protocol could implement a method using an instance of a user-defined class with `__call__`, which could effectively have an arbitrary fallback type.

More discussion: https://github.com/python/mypy/pull/3132#discussion_r133249407

cc @ilevkivskyi

**Comment by ilevkivskyi** [comment]
It looks like we could use fallbacks to relatively easily allow subclassing ``Callable`` (same as for ``NamedTuple``s and ``TypedDict``s), see discussion in #2087. Note that this already correctly works at runtime.

**Comment by JukkaL** [comment]
I'm not convinced that this is worth the extra complexity.
