### ISSUE TITLE
Using strict-optional appears to not match with varargs

### ISSUE THREAD

**Issue by neiljp** [python/mypy#3834]
I just came across this issue while transitioning zulip to strict-optional (it passes fine without), and have narrowed down a test case to:
```
import requests
from typing import Any
def guard(*args, **kwargs):
    # type: (*Any, **Any) -> None
    raise Exception()  # May not be relevant
requests.request = guard
```
which then generates the following:
```
error: Incompatible types in assignment (expression has type Callable[[VarArg(Any), KwArg(Any)], None], variable has type Callable[[str, str, KwArg(Any)], Response])
```

Putting an explicit:
```
requests.request = lambda method, url, **kwargs: guard(method, url, **kwargs)
```
appears to work ok.

For reference, this has been discussed in zulip/zulip#6017.

**Comment by JelleZijlstra** [comment]
This isn't actually related to vararg; it's because the return type is different. `mypy --strict-optional` passes for me on your test case when I change the return annotation to `-> Any` or `-> NoReturn` instead of `-> None`.

**Comment by ilevkivskyi** [comment]
I agree with @JelleZijlstra, it looks like mypy is right here, the return types are incompatible. If the function is designed to never return, then its annotation should be ``NoReturn``, _not_ ``None``.

**Comment by ethanhs** [comment]
Closing as it seems mypy is doing the right thing.

**Comment by ethanhs** [comment]
@neiljp no worries, forgetting about bug reports happens :)
