### ISSUE TITLE
User-defined protocols

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3838]
This issue tracks the remaining things needed for making user-defined protocols work.

Now that #3132 was merged, mypy understand protocols. However, we still need runtime support for protocols (the `Protocol` class) and `Protocol` needs to be added to typeshed before protocols can actually be used in user code.

See also https://github.com/python/mypy/pull/3132#issuecomment-322860528.

Switching ABCs in `typing` to be protocols is a separate issue and requires coordination with other users of typeshed.

**Comment by JukkaL** [comment]
cc @ilevkivskyi

**Comment by ilevkivskyi** [comment]
OK, here is a PR with runtime implementation in ``typing_extensions`` https://github.com/python/typing/pull/464 and a PR with the corresponding stubs https://github.com/python/typeshed/pull/1564

**Comment by JukkaL** [comment]
This has been supported for a while now.
