### ISSUE TITLE
Mypy doesn't check for None checks

### ISSUE THREAD

**Issue by marmistrz** [python/mypy#3841]
Take this, obviously wrong code

```
from typing import Optional

def foo(x: Optional[dict]):
    return x.items()

foo(None)
```
Output:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 6, in <module>
    foo(None)
  File "/tmp/test.py", line 4, in foo
    return x.items()
AttributeError: 'NoneType' object has no attribute 'items'
```
If a type is an `Optional`, there should be a check if it's `None` or not, which is missing here. Code that fails to do so should be marked as invalid.

**Comment by elazarg** [comment]
Use `--strict-optional`:
```
$ mypy --strict-optional tmp.py
tmp.py:4: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "items"
```

**Comment by JelleZijlstra** [comment]
Yes, I'd recommend always using `--strict-optional` on new mypy-checked code. It will eventually become the default, but mypy itself isn't quite there yet.
