### ISSUE TITLE
TypedDict missing many dict methods

### ISSUE THREAD

**Issue by teepark** [python/mypy#3843]
mypy isn't recognizing methods of TypedDict.

- mypy 0.521
- mypy_extensions 0.3.0
- typeshed 0.0.1

```python
from mypy_extensions import TypedDict
D = TypedDict('D', {'a': int})

d = {'a': 4}  # type: D
d.copy()
d.get('a')
d.clear()
d.setdefault('b', 7)
d.has_key('a')
d.items()
d.keys()
d.values()
d.iteritems()
d.iterkeys()
d.itervalues()
d.pop('b', None)
d.popitem()
d.update({'f': 11})
d.viewitems()
d.viewkeys()
d.viewvalues()

"""
$ mypy -2 example.py
example.py:7: error: "D" has no attribute "copy"
example.py:9: error: "D" has no attribute "clear"
example.py:10: error: "D" has no attribute "setdefault"
example.py:11: error: "D" has no attribute "has_key"
example.py:18: error: "D" has no attribute "pop"
example.py:19: error: "D" has no attribute "popitem"
example.py:20: error: "D" has no attribute "update"
example.py:21: error: "D" has no attribute "viewitems"
example.py:22: error: "D" has no attribute "viewkeys"
example.py:23: error: "D" has no attribute "viewvalues"
"""
```

**Comment by teepark** [comment]
@dougas-treadwell

**Comment by teepark** [comment]
@douglas-treadwell

**Comment by JelleZijlstra** [comment]
This is already tracked in #3518, but you're listing more methods. A lot of these shouldn't be hard to do, so feel free to submit a PR.

I wonder if there's also a way to inherit them from the `dict` stubs somehow.

**Comment by teepark** [comment]
I did find that ticket, but since he marked it as a feature and not a bug I figured the "special casing" refers to adding special behaviors to the listed methods (like clear() is probably currently expected to return a `Dict[Any, Any]` but could return an instance of the current type).

**Comment by teepark** [comment]
It seems suspiciously like a mypy bug because [typeshed should be forcing it to produce a `Type[dict]`](https://github.com/python/typeshed/blob/master/third_party/2and3/mypy_extensions.pyi). I'm not sure what else the stubs could be doing to help.

**Comment by ilevkivskyi** [comment]
I think the root of the problem is that the fallback for TypedDicts is ``Mapping`` and not ``Dict``, and the former has much fewer methods. A hacky way to fix this would be to define a special subclass of ``Mapping`` that will define ``Dict`` methods that are safe to use for TypedDicts, and use it instead for fallbacks.

**Comment by JelleZijlstra** [comment]
Why isn't the fallback for TypedDict just Dict?

**Comment by ilevkivskyi** [comment]
IIRC this is because some methods of ``Dict`` are not safe since they can change dictionary items "en masse", while ``__getitem__``/``__setitem__`` are special-cased to allow only certain keys/types. Now I am not sure it was the best decision (although more safe/conservative).

**Comment by JukkaL** [comment]
A user just asked about how to `.copy()` a TypedDict, and apparently the most reasonable approach is to use a cast, which is unfortunate.

Note that some of the methods aren't always safe, such as `clear()` for a total typed dict.

**Comment by nguyenbathanh** [comment]
@JukkaL When can we release it? I didn't found it in latest version `v0.650`.

Thanks.

**Comment by ethanhs** [comment]
@nguyenbathanh releases are usually done every few weeks, but due to holidays I expect it will take a bit longer between `0.650` and `0.660`. For now you can use the development branch if you really need this fix. (e.g. `pip3 install git+https://github.com/python/mypy.git`).

**Comment by nguyenbathanh** [comment]
@ethanhs Thanks for your information! I will use the Dev version.
