### ISSUE TITLE
Make ClassDef.metaclass an Expression instead of str

### ISSUE THREAD

**Issue by elazarg** [python/mypy#3847]
Currently the metaclass node is assumed to be a string. This is inconsistent, requires workarounds such as passing `'<error>'` from the parser to the semantic analysis phase, and makes it awkward to handle metaclasses that come from different contexts (as in python2).

Making it an Expression works cleanly as far as I can tell, and reduces code duplication.

**Comment by ilevkivskyi** [comment]
Makes sense to me. But what are arguments in favour of strings, why metaclasses are implemented like this?

**Comment by elazarg** [comment]
It was introduced in [this commit](https://github.com/python/mypy/commit/1bd87200dec15a20a58952e95eacf08c7004821a#diff-9c10bc6d2837f870caed4b4b5a93fa0eR287) from 2013. I guess making it an expression at that time was too general.
