### ISSUE TITLE
Documentation of plugin interface

### ISSUE THREAD

**Issue by OddBloke** [python/mypy#3857]
At the moment, it's not 100% clear what a plugin file should look like without reading the code (and even then there isn't a clear comment/docstring that answers the question).

**Comment by gvanrossum** [comment]
The plugin interface is highly experimental and we're not ready to commit to the current API. Therefore we'd prefer it if not too many people started using it and if they are well aware that they will likely have to change there code several times in the future as the API evolves. Keeping it undocumented is one way to further that goal.

**Comment by ilevkivskyi** [comment]
Raising priority to normal. We (I?) should add at least some basic info (mentioning API is still provisional).

**Comment by ilevkivskyi** [comment]
We now have decent docs for the plugin system (see https://mypy.readthedocs.io/en/latest/extending_mypy.html#extending-mypy-using-plugins and below), so I think this can be closed now.
