### ISSUE TITLE
Support for generic TypedDict

### ISSUE THREAD

**Issue by dgoldstein0** [python/mypy#3863]
```
R = TypeVar("R")
FileCachedData = TypedDict('FileCachedData', {'mtime': float, 'size': int, 'value': R})
```

mypy complains about `R` in the `TypedDict` declaration.  I would expect that I could declare a generic TypedDict like this.

**Comment by gvanrossum** [comment]
Generic TypedDicts are not supported yet. (Though if there were, this would be a reasonable notations -- after all this is how you declare generic aliases.)

**Comment by dgoldstein0** [comment]
Well then, consider this a feature request.

**Comment by gwax** [comment]
To add a justification note, this feature would be useful for handling polymorphic JSON responses, such as a shared pager:

```python
class Item(TypedDict):
    type: str

class ValueItem(Item):
    value: int

T = TypeVar('T', bound=Item)

class ItemPager(TypedDict, Generic[T]):
    next_page: Optional[str]
    items: List[T]

def get_value_items() -> List[ValueItem]:
    value_items: List[ValueItem] = []
    url = "https://example.com/value_items"
    while url:
        response = requests.get(url)
        pager: ItemPager[ValueItem] = response.json()
        url = pager['next_page']
        value_items += pager['items']
    return value_items
```

**Comment by pawelrubin** [comment]
Hi! 
Are Generic TypedDicts/NamedTuples planned to be supported in the future versions of Python/mypy?
As @gwax mentioned, they would be super useful for annotating polymorphic JSON responses.

**Comment by gvanrossum** [comment]
I suggest filing a bpo issue for that.

**Comment by peterschutt** [comment]
@pawelrubin was a bpo issue created for this?

**Comment by AlexWaygood** [comment]
There's now a BPO issue for this [here](https://bugs.python.org/issue44863)

**Comment by graingert** [comment]
See also https://github.com/python/typing/issues/1174

**Comment by AlexWaygood** [comment]
> See also [python/typing#1174](https://github.com/python/typing/issues/1174)

To expand on this: generic `TypedDict`s are now supported by the runtime in 3.11, and will hopefully soon be backported to earlier Python versions via `typing_extensions`. mypy support for generic `TypedDict`s is still missing, however.

**Comment by JelleZijlstra** [comment]
We likely won't add this support to mypy-extensions. Retitling this to reflect the request that mypy adds support for generic TypedDicts in general.

**Comment by AlexWaygood** [comment]
@JelleZijlstra, could you add a link to this issue in #11753?
