### ISSUE TITLE
Should we sort the docs for config flags alphabetically?

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#3864]
Currently the docs for config flags are in no particularly useful order, and there are so many of them that we might as well sort them alphabetically (per section -- global and per-module flags need to stay separated).

**Comment by jwaixs** [comment]
I agree, I would like to claim this issue. (as first contribution)

**Comment by ilevkivskyi** [comment]
We had two major config flags overhauls recently, so I am not sure this issue is still relevant.

**Comment by gvanrossum** [comment]
Yeah, sorry, this is no longer relevant. I'm sure there are smaller improvements to the current docs for flags and options possible though.
