### ISSUE TITLE
Incorrect error Module 'signal' has no attribute 'SIGBREAK'`

### ISSUE THREAD

**Issue by jcrmatos** [python/mypy#3872]
Hello,

When importing SIGBREAK using
`from signal import SIGBREAK, SIGINT, SIG_IGN, signal`
mypy returns
`hash_checker.py:33: error: Module 'signal' has no attribute 'SIGBREAK'

Best regards,

JM

**Comment by ilevkivskyi** [comment]
But it looks like mypy is right, there is no ``SIGBREAK`` in the ``signal`` module. I tried this on both Python 2 and 3 and the import fails at runtime:
```
>>> from signal import SIGBREAK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SIGBREAK'
```

**Comment by jcrmatos** [comment]
Hello,

No it is not right.
I'm using Python 3.5.3 and it accepts the import, and the remaining code that uses signal and SIGBREAK works.
If you do a dir(signal) after import signal you will see SIGBREAK there (at least in Python 3.5.3).

Best regards,

JM

**Comment by jcrmatos** [comment]
Hello,

No it is not right.
I'm using Python 3.5.3 and it accepts the import, and the remaining code that uses signal and SIGBREAK works.
If you do a dir(signal) after import signal you will see SIGBREAK there (at least in Python 3.5.3).

I'm using mypy 0.521.

Best regards,

JM

**Comment by JelleZijlstra** [comment]
To be clear, this isn't a problem, but with github.com/python/typeshed. The fix should be in https://github.com/python/typeshed/blob/master/stdlib/3/signal.pyi (or the Python 2 version). Feel free to submit a PR!
