### ISSUE TITLE
What to do with mypy-lang on PyPI?

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3885]
I have noticed that download numbers for ``mypy-lang`` grow over last month. I would say this indicates that there are new people who find some mentions (maybe in blogs or forums) of the old ``mypy-lang`` package and install it. Maybe we could make a new release that is identical to the existing last release of ``mypy-lang`` except that it will always print a warning when ``mypy <something>`` is used (but still exiting with zero if there are no errors, so that we will not break any CIs).

**Comment by gvanrossum** [comment]
I think we should put a "tombstone" there that does nothing except print an error and exit 1. If we make it identical to the current release except for a warning that will just encourage people to keep using it, and then a few releases down the road it'll be out of date again.

**Comment by ethanhs** [comment]
I agree. If people pin mypy-lang, then they will keep getting mypy-lang. If people didn't, then they probably want the latest (or at least have said they want the latest) and thus CI _should_ break.

**Comment by JukkaL** [comment]
Ok let's do what @gvanrossum suggested. Created a new issue #3888, closing this in favor of it.
