### ISSUE TITLE
None should be a subtype of an empty protocol

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3906]
Currently this gives an incompatible type error with ``--strict-optional``, although it works with plain ``object``:
```python
class Empty(Protocol):
    pass

e: Empty
e = None  # Error

o: object
o = None # This is OK
```

**Comment by gvanrossum** [comment]
Should we have a topic-protocols label?

**Comment by JukkaL** [comment]
Yes. Do you want to add one?

**Comment by gvanrossum** [comment]
Created the label and added some issues. Ivan may want to double-check, there may be more issues to be categorized this way.

**Comment by ilevkivskyi** [comment]
Thanks! I added the label to few other issues.
