### ISSUE TITLE
Better message if Python 2 typing not available

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3907]
Mypy tests fail with `ImportError: No module named typing` in `python2eval.test` if `typing` has not been installed in Python 2. This is a common source of confusion. 

It would be nice to detect this error and produce a message such as this (at the end of the output from tests so that it will be hard to miss):

```
*************************************************
ERROR: Python 2 does not have "typing" installed
*************************************************

Some mypy test cases run code using the platform default Python 2 interpreter.
You need to manually run "pip install typing" using *Python 2 pip* to work around
the issue. (Python 3 is used for everything else beyond these test cases.)

More information here: <link to documentation>
```

**Comment by gvanrossum** [comment]
Why can't the tests be more hermetic? The test setup should just create a Python 2 virtualenv and install typing there. (Reuse the venv between tests and even between runs, just keep it up to date.)

**Comment by JukkaL** [comment]
Yeah, that would be better and shouldn't be too much work to implement. Closing in favor of #3908.
