### ISSUE TITLE
Automatically create Python 2 venv in tests with typing

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3908]
Currently we require Python 2 `typing` to be manually installed. The Python 2 tests should do this automatically. We can reuse the venv between test runs as long as we keep it up-to-date.

See also #3907 for context and an alternative (worse) solution.

**Comment by ethanhs** [comment]
This should also fail nicely if there is no Python 2 installed, which can happen on Windows often, and may happen on Arch Linux.

**Comment by JelleZijlstra** [comment]
`virtualenv` is a third-party package in Python 2, so this might just move the requirement for users from `python2 -m pip install typing` to `python2 -m pip install virtualenv`.

**Comment by ethanhs** [comment]
@JelleZijlstra I believe the idea is that the test scripts will handle this for the user, installing `virtualenv` as needed.

**Comment by JukkaL** [comment]
@JelleZijlstra We can add `virtualenv` as a Python 3 dependency in `test-requirements.txt` and use it to create the Python 2 virtualenv?
