### ISSUE TITLE
Ellipsis wierdness

### ISSUE THREAD

**Issue by rmcgibbo** [python/mypy#3909]
The behavior around the type of `...` in indexing notation and `Ellipsis` seems a little off. I guess this is a bit of the corner case of the language, but given that `key1 is key2` in the example below, shouldn't mypy infer them to have the same type?

```
$ cat example.py 
from typing import Tuple, Union, TypeVar
K = TypeVar('K')

class Container:
    def __getitem__(self, key):
        # type: (K) -> K
        return key

c = Container()
key1 = c[...]
key2 = c[Ellipsis]
assert key1 is key2  # passes at runtime
reveal_type(key1)
reveal_type(key2)

$ mypy -2 example.py 
example.py:13: error: Revealed type is 'builtins.object*'
example.py:14: error: Revealed type is 'builtins.ellipsis*'
```

**Comment by ethanhs** [comment]
Hi! What version of Mypy are you on? On 0.521 and master, I got `builtings.ellipsis*` for both, as expected.

**Comment by rmcgibbo** [comment]
I'm on 0.521 as well, installed from pypi.

**Comment by rmcgibbo** [comment]
Oh, I just realized that my mypy.ini config file was in effect. I only see this behavior with mypy using python 2 syntax. (i.e. `mypy -2 example.py`). Can you try again to reproduce?

**Comment by ethanhs** [comment]
I was able to repro that in Python 2 on 0.521 and master. It appears Mypy becomes confused on the TypeVar. Thanks for reporting this!

**Comment by gvanrossum** [comment]
May have something to do with the different status of `...` in PY2 -- it's
part of slice syntax rather than just being an expression.

**Comment by ethanhs** [comment]
I thought so too, but I have yet to find any difference in how it is parsed. I will look again.

**Comment by hauntsaninja** [comment]
What is PY2?
