### ISSUE TITLE
Call to overloaded function with Any argument results in too precise type

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3914]
The inferred type of `f(a)` below is `int`. It would be better to infer `Any`, since the correct type can't be predicted due to the `Any` argument type:

```py
from typing import overload, Any

@overload
def f(x: int) -> int: ...
@overload
def f(x: object) -> object: ...
def f(x): pass

a: Any
reveal_type(f(a))  # int (but should be Any)
```

This blocks PR #3300 from being merged, since the PR will expose additional cases where a too precise type is inferred.

**Comment by ilevkivskyi** [comment]
Isn't this just a duplicate of https://github.com/python/mypy/issues/3662?

**Comment by JukkaL** [comment]
Oops, this a dupe (though the example is slightly different).
