### ISSUE TITLE
Importing Modules for typing of nested objects (of the same type) raises an error

### ISSUE THREAD

**Issue by henryJack** [python/mypy#3923]
The following example throws a mypy error.
```
from typing import TYPE_CHECKING, List

if TYPE_CHECKING:
    from .my_module import Assembly  # Import the class Assembly from the file already in

Class Assembly:
    def __init__(self) -> None:
        self.sub_assemblies: List['Assembly'] = None
```

The resulting mypy error is  `Name 'Assembly' already defined (possibly by an import)`

Is there a procedure for using Classes for types for the class you're already in?

**Comment by gvanrossum** [comment]
Try leaving out the 
```py
if TYPE_CHECKING:
    from .my_module import Assembly
```
block.

**Comment by henryJack** [comment]
YES! Thanks so much, I finally have a clean mypy pass!

**Comment by henryJack** [comment]
Is there a way you can avoid the string for `'Assembly'` in this class:

```
Class Assembly:
    def __init__(self) -> None:
        self.sub_assemblies: List['Assembly'] = None
```
I've tried:
```
Class Assembly:
    def __init__(self) -> None:
        self.sub_assemblies: List[self] = None
```

and:
```
Class Assembly:
    def __init__(self) -> None:
        self.sub_assemblies: List[cls] = None
```

**Comment by ilevkivskyi** [comment]
If you don't like string literals then, please express your support for [PEP 563](https://www.python.org/dev/peps/pep-0563/) on python-ideas mailing list.

(and ``class`` doesn't have capital ``C``)
