### ISSUE TITLE
"isinstance" function has incompatible type

### ISSUE THREAD

**Issue by henryJack** [python/mypy#3925]
If I make a custom class...

```
class A:
    def __init__(self) -> None:
    self.random_int: int = 5
```

Then in my program, if I write:

```
from my_module import A

if isinstance(an_object, A):
```

I get the following error:

`error: Argument 2 to "isinstance" has incompatible type "A"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"`

Is this a known issue with mypy? Couldn't find any previous issue regarding this.

Thanks,
Henry

**Comment by gvanrossum** [comment]
I'm sorry, I cannot reproduce this. This should totally work. You've
probably made some other mistake, e.g. switched files.

**Comment by henryJack** [comment]
Ah, yes, you're right. I will try to make some actual reproducible code and raise the issue again if needs be. Thanks for looking into it anyway!
