### ISSUE TITLE
Is it possible to have TypedDict generator functions?

### ISSUE THREAD

**Issue by wilfreddenton** [python/mypy#3932]
For my use case, I am working with a schema language that is different from TypedDict's but contains similar information. I have a function that can convert the schema to the correct format. How can I then create the TypedDict for use in other files?

See example below.

```python
# file1.py

# Custom Schema
schema = {
    'prop': {'type': 'string'}
}

def create_typed_dict(name: str, schema: Dict[str,Any]) -> ??:
   return TypedDict(name, convert_custom_schema_to_typed_dict_schema(schema))

MyType = create_typed_dict('MyType', schema)
```

```python
# file2.py
from file1 import MyType

X = {'prop': 'hey'} # type: MyType
```

**Comment by wilfreddenton** [comment]
I'm guessing now because when I write something like

`TypedDict(name, schema)` I get a warning `TypedDict() expects a dictionary literal as the second argument`. I guess this is because mypy "reads" the file to get the types for each property in the dictionary?

**Comment by gvanrossum** [comment]
Yeah, you're probably going to have to write something that *generates* stub (.pyi) files containing the TypedDict definitions in the form mypy supports.

**Comment by wilfreddenton** [comment]
Thanks for the response. Do you think you could give me an example of this? I'm not sure how the stub file would help in this scenario and I couldn't find the stub representation of a TypedDict in the documentation.

**Comment by gvanrossum** [comment]
Stub files have the same syntax as regular Python files: http://mypy.readthedocs.io/en/stable/basics.html#library-stubs-and-the-typeshed-repo . For your example you would have to generate something like
```py
from mypy_extensions import TypedDict
schema = TypedDict('schema', {'type': str})
```

**Comment by wilfreddenton** [comment]
Ok I tried adding that manually but that didn't seem to work. I made sure to provide the path to my stub files to MyPy by setting the `MYPYPATH` env var. I feel like it has something to do with the return type of 

```
def create_typed_dict(name: str, schema: Dict[str,Any]) -> ??:
```

What return type should that be?

**Comment by JukkaL** [comment]
Instead of generating a stub file, you could generate `.py` a file with `TypedDict` definitions and then import the generated types from there. For example, you can generate a file like this:

```py
# mytypes.py -- automatically generated
from typing import TypedDict

MyType = TypedDict('MyType', {'prop': str})
```

Then you can use the type by importing it:

```py
from mytypes import MyType

def create() -> MyType:
    return {'prop': 'value'}
```

**Comment by wilfreddenton** [comment]
Thanks for the help. I was able to get this to work by manually creating the stub file. So eventually I'll put in the time to create the generation script.

**Comment by Emerentius** [comment]
I had the same need and ended up writing a quick and dirty generator some time ago. I've cleaned it up a bit and uploaded it here: https://github.com/emerentius/typed_dict_generator .
So far it only takes a single Json object and generates a typed dict for it. I plan to extend it, when I have need of it again, but it may already be useful to someone in its current state.
