### ISSUE TITLE
Problems with inherited classes and their types

### ISSUE THREAD

**Issue by henryJack** [python/mypy#3934]
Let's say I have the following 3 classes
```
class A:
    self.var_1 = 1

class B(A):
    self.var_2 = 2

class MyClass:
    self.a_or_b: A = None
```

if I then declare an object to be of type MyClass and use a attribute from an inherited class:
```
obj = MyClass()
obj.a_or_b.var_2
```
I get the following mypy error:

`error: Item "A" of "Optional[A]" has no attribute "var_2"`

even if I change the typings on `MyClass` to:
```
class MyClass:
    self.a_or_b: Union[A, B] = None
```
I still get the mypy error:

`error: Item "AbstractApplyType" of "Union[A, B, None]" has no attribute "var_2"`

Despite pycharm telling me everything is okay!

Any help, ideas, thoughts appreciated!

**Comment by JukkaL** [comment]
If you want to access an attribute defined in `B`, you'd usually use a variable annotated with type `B` or an `isinstance` check. For example:

```py
...

def f() -> A:
    return <may return A or B>

a_or_b = f()
if isinstance(a_or_b, B):
    a_or_b.var_2  # OK
```

PyCharm is more lenient than mypy in some ways. Accessing `var_2` would result in an exception if the variable happens to point to an `A` instance, and that's why mypy requires an `isinstance` check.

**Comment by henryJack** [comment]
Ah Okay, I'll give this a go. Thanks for your help! 

Are you looking for anymore mypy docs contributors? I have been creating an expanded cheat sheet over the last few days if you would like it?

**Comment by JukkaL** [comment]
Documentation updates are welcome. For larger changes please first create an issue to discuss it.

**Comment by JukkaL** [comment]
Also, sometimes you may want to use `cast(B, a_or_b).var2` (look up `cast` in the docs).

**Comment by AlexWaygood** [comment]
Seems like this question was answered a while ago.
