### ISSUE TITLE
dict(**{1: 2}) should be valid in Python 2 mode

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3940]
Mypy rejects `dict(**{1: 2})` (it expects string keys) though this actually works in Python 2:
```
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> dict(**{1: 2})
{1: 2}
```

The expressions fails in Python 3:
```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> dict(**{1: 2})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: keyword arguments must be strings
```

 It looks like mypy uses Python 3 rules in Python 2 mode, which is incorrect.

**Comment by elazarg** [comment]
It only works "by accident", right? Looks like an abuse of the ability to pass keyword arguments that are not strings, which is an implementation detail.

**Comment by ethanhs** [comment]
>Looks like an abuse of the ability to pass keyword arguments that are not strings, which is an implementation detail.

Yes, this doesn't work on PyPy 2, I believe it is an implementation detail.

**Comment by gvanrossum** [comment]
I'd be happy to reject this as "mypy actually found some questionable code".

**Comment by JukkaL** [comment]
Fair enough, let's close this.
