### ISSUE TITLE
No overload variant of "list" matches argument types [shlex.shlex]

### ISSUE THREAD

**Issue by klausweiss** [python/mypy#3941]
I am using `shlex.shlex` class [as in the documentation](https://docs.python.org/3/library/shlex.html#improved-compatibility-with-shells):

```python
list(shlex(string, posix=True, punctuation_chars=True))
```
but I get:
```
main.py:10: error: No overload variant of "list" matches argument types [shlex.shlex]
```

I'm running mypy with:
```bash
mypy main.py --ignore-missing-imports --python-version 3.6
```

OS X El Capitan 10.11.6
mypy 0.521

**Comment by gvanrossum** [comment]
Please file typeshed bugs in the https://github.com/python/typeshed project. You're also welcome to submit a PR without first filing a bug!
