### ISSUE TITLE
Unexpected keyword argument "punctuation_chars" for "shlex"

### ISSUE THREAD

**Issue by klausweiss** [python/mypy#3942]
I am using `shlex.shlex` class [as in the documentation](https://docs.python.org/3/library/shlex.html#improved-compatibility-with-shells):

```python
list(shlex(string, posix=True, punctuation_chars=True))
```
but I get:
```
main.py:10: error: Unexpected keyword argument "punctuation_chars" for "shlex"
/usr/local/lib/mypy/typeshed/stdlib/3/shlex.pyi:29: note: "shlex" defined here
```

I'm running mypy with:
```bash
mypy main.py --ignore-missing-imports --python-version 3.6
```

OS X El Capitan 10.11.6
mypy 0.521

**Comment by gvanrossum** [comment]
Please file typeshed bugs in the https://github.com/python/typeshed project.
