### ISSUE TITLE
Errors on StringVar

### ISSUE THREAD

**Issue by jcrmatos** [python/mypy#3944]
Hello,

I'm using Python 3.5.3 with mypy 0.521.
The program in question works fine.

When checking the following program mypy shows the following messages (which in my opinion are incorrect):

```
gui_license_creator.py:53: error: Item "None" of "Optional[StringVar]" has no at
tribute "get"
gui_license_creator.py:54: error: Item "None" of "Optional[StringVar]" has no at
tribute "set"
gui_license_creator.py:54: error: Item "None" of "Optional[StringVar]" has no at
tribute "get"
gui_license_creator.py:56: error: Item "None" of "Optional[StringVar]" has no at
tribute "set"
```

This is the program in question:

```
from tkinter import ACTIVE, StringVar, Tk
from tkinter.messagebox import showerror
from tkinter.ttk import Button, Entry, Label
from typing import Optional  # noqa: F401 # pylint: disable=unused-import


def start_gui():
    sn_tb_sv = None  # type: Optional[StringVar]
    lic_tb_sv = None  # type: Optional[StringVar]

    def create_license():
        if sn_tb_sv.get():  # This is line 53.
            lic_tb_sv.set(hash_list([sn_tb_sv.get()])[0])  # This is line 54.
        else:
            lic_tb_sv.set('')  # This is line 56.

    def create_vars():
        nonlocal sn_tb_sv, lic_tb_sv

        sn_tb_sv = StringVar()
        lic_tb_sv = StringVar()

    master = Tk()  # type: Tk

    create_vars()
    create_layout()  # Not shown.
    create_bindings()  # Not shown.

    master.mainloop()
```

Best regards,

João Matos

**Comment by ilevkivskyi** [comment]
> The program in question works fine.

This is not a sufficient argument, there are lots of programs that work, but will be rejected statically.
In this particular case I think mypy is right. If you know that at some point a variable typed as ``Optional`` will be not ``None`` you could either add ``assert var is not None`` of ``if var is not None: ...`` mypy understands both situations.

Finally, it looks like in your case the type does not need to be ``Optional``, just upgrade to Python 3.6 and write:
```python
def start_gui():
    sn_tb_sv: StringVar
    lic_tb_sv: StringVar
    ...
```

**Comment by jcrmatos** [comment]
Hello,

I can't initialize the vars at start_gui() function with StringVar because at that point Tk is not initialized and Python will return an error.
That is the reason why the vars must be initialized with None and only after starting Tk can I change it's type to StringVar.

Best regards,

JM

**Comment by jcrmatos** [comment]
Hello,

I can't initialize the vars at start_gui() function with StringVar because at that point Tk is not initialized and Python will return an error.
That is the reason why the vars must be initialized with None and only after starting Tk can I change it's type to StringVar.

Solved it by adding a check
`if sn_tb_sv and lic_tb_sv:`
before lines 53 to 56.

Best regards,

JM
