### ISSUE TITLE
No error if derived type is different from annotated type

### ISSUE THREAD

**Issue by henryJack** [python/mypy#3945]
Take this incorrectly annotated example:

```
x: bool = 5
```

Gives no mypy error. Surely if mypy knows that `Type(int)` is different to `Type(bool)`, we could have a new mypy warning of `Annotated type different to derived type`?

**Comment by JukkaL** [comment]
Is this within an annotated function? This works correctly for me when I type check a file containing just `x: bool = 5`:

```
t.py:1: error: Incompatible types in assignment (expression has type "int", variable has type "bool")
```

**Comment by henryJack** [comment]
Ah yes, sorry. It is inside an annotated function!

**Comment by JukkaL** [comment]
Can you give a more complete example and the mypy command line that you use that fails to generate the error? This should work.

**Comment by henryJack** [comment]
I get no error if I run `mypy` on the following code:
```
    def new_func(self):
        a: bool = 5
```
However, If I annotate it I get the following error -> `error: Incompatible types in assignment (expression has type "int", variable has type "bool")`:
```
    def new_func(self) -> None:
        a: bool = 5
```

**Comment by JukkaL** [comment]
Mypy doesn't type check functions that don't have a signature (in this case, `-> None`). This is clearly kind of confusing in case you have a variable annotation. You can use `--check-untyped-defs` to force mypy to type check all functions.

**Comment by ilevkivskyi** [comment]
IIUC this is tracked in #3948 so I am closing this now.
