### ISSUE TITLE
Mechanism and/or documentation for locally fixing missing stubs

### ISSUE THREAD

**Issue by kbauer** [python/mypy#3947]
On typeshed, some stubs are incomplete. 

## Current Behavior

Currently, the only consistent fix is to maintain a seprate copy of the stub files for the required *top-level* packages. 

For example, my code was using the `lxml.etree._Element.xpath()` and `lxml.etree._ElementTree.xpath()` methods, both of which are currently not included in the typeshed repository. In order to add these annotations, I had to add both `lxml/etree.pyi` and `lxml/__init__.pyi` to my `MYPYPATH`. 

This is undesirable, because it will shadow future updates to the typeshed repository. 

### 1. Clarification of documentation on this point

Currently I cannot find any documentation that discusses the edge-case of incomplete / incorrect stubs. As a consequence I had to solve some questions by trial-and-error:

1. Is there a solution without stub files? → Yes, but using 

        somevar : List[_Element] = elem.xpath(somepath) # type:ignore

    everywhere I used `xpath` is verbose and inconvenient, and as far as I can tell there is no valid annotation for a case like

        def somefunc() -> List[_Element]:
            return elem.xpath(somepath)

2. Is it enough to copy `lxml/etree.pyi` to my `MYPYPATH`? → No, because `lxml/__init__.pyi` is needed for the directory to be parsed. This can technically be understoof from the documentation, but it is open to misunderstandings.

3. Does the creation of my own `lxml` stub package hide the `lxml/objectify.pyi` shipped with mypy? → No, it doesn't. 

### 2. A more ad-hoc method?

For day-to-day work, sometimes a more ad-hoc solution would be desirable, e.g. the ability to monkey-patch type-annotations.

**Comment by ilevkivskyi** [comment]
Just wanted to mention a related discussion that may be interesting to you: [PEP 561](https://www.python.org/dev/peps/pep-0561/).

**Comment by hauntsaninja** [comment]
Closing because stale + PEP 561 is a thing
