### ISSUE TITLE
islice doesn't accept Generator typed iterators.

### ISSUE THREAD

**Issue by dpnova** [python/mypy#3953]
The error is: 
```
error: No overload variant of "islice" matches argument types [typing.Generator[datetime.date, builtins.None, builtins.None], builtins.None, builtins.None, builtins.int]
```

```
from datetime import date, datetime, timedelta
from itertools import islice
from typing import Generator, List

DateGen = Generator[date, None, None]


def generate_weekly(start_date: date) -> DateGen:
    yield start_date
    while True:
        next = start_date + timedelta(days=7)
        yield next
        start_date = next


def generate_biweekly(start_date: date) -> DateGen:
    return islice(generate_weekly(start_date), None, None, 2)
```

**Comment by dpnova** [comment]
Sorry should I have reported this in typeshed?

**Comment by ilevkivskyi** [comment]
I looks like you are running mypy with ``--strict-optional``. If yes, then this may be not because of ``Generator`` but because of second ``islice`` argument ``start``: it is written in typeshed that it can't be ``None``, but can be only ``int``.

**Comment by dpnova** [comment]
Thanks for the reply @ilevkivskyi - I'm still figuring out the specifics of typeshed, but I did just try this in python 2.7 (above example was 3.5) and the None is fine input for the second param, I'll open an issue over at typeshed.. thanks!

`list(itertools.islice(range(5), None, None, 2))`
