### ISSUE TITLE
Error for len or enumerate on array.array

### ISSUE THREAD

**Issue by Zac-HD** [python/mypy#3956]
[`array.array`](https://docs.python.org/3/library/array.html#array.array) objects are essentially efficient lists with a single element type.  They have a size and can be iterated over, but mypy doesn't seem to know this:

    floats.py:105: error: Argument 1 to "len" has incompatible type "array"; expected "Sized"
    floats.py:107: error: Argument 1 to "enumerate" has incompatible type "array"; expected Iterable[<nothing>]

[Source](https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/internal/conjecture/floats.py#L104-L105).

**Comment by gvanrossum** [comment]
Please file an issue with typeshed instead.

**Comment by Zac-HD** [comment]
Ah, sorry!
