### ISSUE TITLE
Use plugin to support Zope interfaces

### ISSUE THREAD

**Issue by wsanchez** [python/mypy#3960]
Subclasses of `zope.interface.Interface` have special semantics and need to be handled via a plugin.

**Comment by wsanchez** [comment]
This was originally discussed in #1240.

**Comment by kedder** [comment]
I started a mypy plugin for `zope.interface` and `zope.schema` here: https://github.com/Shoobx/mypy-zope.

**Comment by wsanchez** [comment]
@kedder That's fantastic, thank you.

**Comment by glyph** [comment]
@kedder Wow. This is amazing. I can't wait to try it out!

**Comment by ichard26** [comment]
Closing as a plugin for Zope interfaces is better suited to live as its own package on PyPI and [one already exists](https://github.com/Shoobx/mypy-zope). While it would be nice if the main mypy package could contain plugins for many popular third-party libraries, that would be unsustainable.

Thanks for opening an issue! It's good to have a place to redirect people looking for mypy support for Zope.

**Comment by glyph** [comment]
@ichard26 (or @wsanchez) it might be good to update the description to include this resolution so that folks searching for this will find the link faster

**Comment by ichard26** [comment]
Unfortunately, I don't have sufficient permissions to do that :(

@hauntsaninja could you update the description? Thanks!
