### ISSUE TITLE
Subclassing argparse.Action doesn't correctly detect superclass variables

### ISSUE THREAD

**Issue by matthchr** [python/mypy#3961]
I am relatively new to using MyPy, so it's entirely possible that everything below is just me missing some obvious command line option... I apologize in advance if that's the case, but I didn't see one that seemed to apply.

I have some relatively basic code:
```
from typing import Any
import argparse


class A(argparse.Action):
    def __call__(
            self,
            parser: Any,
            namespace: Any,
            values: Any,
            option_string: Any = None) -> None:
        foo = self.const or 'a'
        ...
```

Since `argparse.Action` has a variable named `self.const` I expect that I can use it, but MyPy complains, saying: `temp.py:15: error: "A" has no attribute "const"`

What's interesting to me, is that if I inherit instead from `Exception` or from a class that I define in the same module as `A`, everything works fine. There's something "special" about `argparse.Action` and I'm not sure what it is.

Is this a bug... or expected?

**note**: If I explicitly type `self: Any` in the signature, things work fine... but I'd really like to understand why they aren't working fine by default. Also interestingly `type: ignore` on `self` doesn't change the results at all.

**Comment by kirbyfan64** [comment]
The problem here is basically that [the stubs don't define any member variables](https://github.com/python/typeshed/blob/master/stdlib/2and3/argparse.pyi#L103).

As a workaround you could always just do `getattr(self, 'const')`?

**Comment by matthchr** [comment]
Thanks for the response @kirbyfan64 - does this mean that for stdlib stuff, mypy actually doesn't look at the code, it just looks at the stubs? Obviously for code I write, it seems to just process the code and find the property that way.

Is this something that should be fixed in the stubs? Or it's intentionally omitted?

**Comment by kirbyfan64** [comment]
Yeah, for the stdlib, mypy just looks at the stubs.

**Comment by matthchr** [comment]
Thanks -- I've worked around this for now.

It would be great if the stubs could be fixed (presuming this is a bug). Should I file an issue over at typeshed?

**Comment by kirbyfan64** [comment]
Yeah, that would be proper place for bugs like this one!

**Comment by matthchr** [comment]
Closing this in favor of [this](https://github.com/python/typeshed/issues/1612)
