### ISSUE TITLE
Problem with enums 

### ISSUE THREAD

**Issue by hanpari** [python/mypy#3969]
With that:
```
class Sample(Enum):
    one = 1
    two = 2


SampleTypeList = tp.List[Sample]
SampleList: SampleTypeList = [Sample.one, Sample.two] # Here is no problem
SampleListGenerated: SampleTypeList = list(Sample) # Here is problematic line
assert SampleList == SampleListGenerated, "It is same, but mypy says otherwise."
assert all(i is j for i, j in zip(SampleListGenerated,
                                  SampleList)), "The identical objects, indeed"
```

**mypy complaints:**

> [mypy] error:Argument 1 to "list" has incompatible type Type[Sample]; expected Iterable[Sample]

From my points of view those lists are identical.

**Comment by JelleZijlstra** [comment]
This works for me with this more minimal example:
```
import enum

class X(enum.Enum):
    a = 1

reveal_type(list(X))
```
The output is `Revealed type is 'builtins.list[enum.Enum*]'` with no other errors.

Are you using the latest version of mypy? We have made several fixes to enum in recent versions.

**Comment by hanpari** [comment]
Thank you. Yes, I have the latest version of mypy. To make it clear: My example is working for you correctly with no complaint from mypy? It seems to me that mypy is not able to understand that Enum type can be unpack as a iterable.

![mypy](https://user-images.githubusercontent.com/7354817/30560273-ad4f9756-9cb7-11e7-93ea-247bde644d6e.png)

**Comment by ilevkivskyi** [comment]
The original example is confirmed on master, but it looks like this is another manifestation of https://github.com/python/mypy/issues/3210 (a duplicate?)

@JelleZijlstra note that the revealed type shows ``builtins.list[enum.Enum*]``, while it should be ``builtins.list[__main__.Sample*]``.

**Comment by elazarg** [comment]
I'm pretty sure it's a duplicate.

**Comment by gvanrossum** [comment]
Agreed.
