### ISSUE TITLE
Refactor stubgen to do semantic analysis

### ISSUE THREAD

**Issue by dmoisset** [python/mypy#3982]
Currently stubgen just builds an AST and works mostly at a syntactic level. Given that, most type annotations during its executions are actually instances of `UnboundType` and forces stubgen to make some assumptions because of lack of information (for example in a type `X.Y.Z`, which part of that path is a module name, or if actually `X = Y` is a type alias or not)

This comes from https://github.com/python/mypy/pull/3169#discussion_r140481089

**Comment by ilevkivskyi** [comment]
Thus is now supported (and controlled by a flag, see https://mypy.readthedocs.io/en/latest/stubgen.html#specifying-how-to-generate-stubs)
