### ISSUE TITLE
stubgen does not preserv @abstractmethod decorator

### ISSUE THREAD

**Issue by dmoisset** [python/mypy#3984]
When a method is decorated by `abc.abstractmethod` stubgen does not preserved (this works for builtindecorators like `classmethod`, `staticmethod` or `property`)

Comes from https://github.com/python/mypy/pull/3169#discussion_r136646783

**Comment by hoefling** [comment]
Just passing by here, but I think this was added by #6256 already, so this issue can be closed...

**Comment by ilevkivskyi** [comment]
@hoefling Thanks, indeed.
