### ISSUE TITLE
bytes(obj) rejected even when obj implements __bytes__

### ISSUE THREAD

**Issue by bmerry** [python/mypy#3989]
Sample code:
```python
#!/usr/bin/env python3

class A(object):
    def __bytes__(self) -> bytes:
        return b'An A'

print(bytes(A()))
```
Output from mypy 0.521, Python 3.5.2:
```
test.py:7: error: No overload variant of "bytes" matches argument types [test.A]
```

Looking in typeshed, it has this overload:
```
class bytes(ByteString):
    @overload
    def __init__(self, o: SupportsBytes) -> None: ...
```
which doesn't seem to be matching.

**Comment by ilevkivskyi** [comment]
The problem is that ``SupportsBytes`` (and several other classes) is not yet defined as a protocol. This will be fixed by https://github.com/python/typeshed/pull/1220, a _temporary_ workaround is to explicitly inherit ``A`` from ``typing.SupportsBytes``.

**Comment by bmerry** [comment]
Unfortunately the workaround breaks using `isinstance` with the class:
```python
#!/usr/bin/env python3

import typing

class A(typing.SupportsBytes):
    def __bytes__(self) -> bytes:
        return b'An A'

print(bytes(A()))
assert isinstance(None, A)
```
at runtime gives
```
b'An A'
Traceback (most recent call last):
  File "./test.py", line 10, in <module>
    assert isinstance(None, A)
  File "/usr/lib/python3.5/typing.py", line 1269, in __instancecheck__
    raise TypeError("Protocols cannot be used with isinstance().")
TypeError: Protocols cannot be used with isinstance().
```

I managed to work around it by replacing `bytes(a)` with `bytes(cast(SupportsBytes, a))`.

**Comment by ilevkivskyi** [comment]
Concerning the ``isinstance()`` error, it looks like you are using an older version of ``typing``, this is fixed in latest version. You could try updating Python (or upgrading to 3.6), but your workaround (using ``cast``) is perfectly OK.

**Comment by bmerry** [comment]
It works with the current version of mypy (0.570), so closing.
