### ISSUE TITLE
No documentation for metaclass support

### ISSUE THREAD

**Issue by elazarg** [python/mypy#3999]
Metaclasses are only mentioned in passing in the docs:
* [Once](http://mypy.readthedocs.io/en/latest/generics.html#generic-class-internals) in the context of self-type (an orthogonal feature)
* [Once](http://mypy.readthedocs.io/en/latest/class_basics.html#abstract-base-classes-and-multiple-inheritance) where the use of `ABCMeta` is recommended - which IMHO is not the right way to go anyway

I'm actually not sure what there is to say about metaclasses, but it seems reasonable to dedicate to it a small section, accessible in the main page. I think it should also mention briefly what's _not_ supported.

**Comment by gvanrossum** [comment]
Let's first make an inventory of what to say. First there are the standard limitations that follow directly from mypy's general lack of understanding of dynamically computed types, for example

- dynamically computing a metaclass isn't supported
- a metaclass that dynamically modifies the class isn't supported

I believe there are also other limitations which could be classified as bugs, where in principle mypy could do the right thing but we currently don't have the code. But I haven't carefully thought through which those might be. Perhaps the loss of type when iterating over an Enum class is an example? It's fine to document those limitations as long as we classify them separately from the first category.

**Comment by ilevkivskyi** [comment]
In general I like the idea of having a separate subsection about metaclasses (probably in the section "Kinds of types").

Some additional thoughts:
* it looks like this page (referenced from RtD) is outdated: https://github.com/python/mypy/wiki/Unsupported-Python-Features
* also the first two items in this list are covered in the docs and can be removed http://mypy.readthedocs.io/en/latest/additional_features.html
* in the section about metaclass we can mention that ``six.with_metaclass`` and ``six.add_metaclass`` are supported.
* in addition to listing supported metaclass features we could show several examples of typical supported use cases.

**Comment by gvanrossum** [comment]
Sounds good. The RtD should probably not refer to the wiki for a list of
unsupported features.

**Comment by elazarg** [comment]
#4028
