### ISSUE TITLE
Properties used as default values will be wrongly inferred

### ISSUE THREAD

**Issue by axx-tahrioui** [python/mypy#4004]
Instead of inferring properties used as default values to the actual return value of the properties getter, we will get the internally used callable (to fetch the property's value of the current instance).

```
class A():

    def __init__(self):
        self._loop: Optional[asyncio.AbstractEventLoop] = None

    @property
    def loop(self) -> Optional[asyncio.AbstractEventLoop]:
        return self._loop

     async def doStuff(loop: asyncio.AbstractEventLoop = loop):
         pass

```
will throw an error like:

> ...has incompatible type "Union[AbstractEventLoop, Callable[[A], Optional[AbstractEventLoop]]]"; expected "AbstractEventLoop"

**Comment by ilevkivskyi** [comment]
Could you please post a more complete example showing an actual line where error happens?

**Comment by axx-tahrioui** [comment]
Sorry, this is was an incomplete example. Fixed accordingly.

**Comment by ilevkivskyi** [comment]
I think mypy is actually right here. At runtime, ``@property`` creates a descriptor, and when accessed directly from the class names space the property does not get "called". Therefore this code is not type safe. It should be refactored to always access ``loop`` via instance:
```python
class A:
    def __init__(self) -> None:
        self._loop: Optional[asyncio.AbstractEventLoop] = None

    @property
    def loop(self) -> Optional[asyncio.AbstractEventLoop]:
        return self._loop

    async def doStuff(self, loop: Optional[asyncio.AbstractEventLoop] = None):
        if loop is None:
            loop = self.loop
        ...
```

**Comment by gvanrossum** [comment]
Have you tried to run that code? It doesn't work -- the default value of the `loop` argument will be a property object, not an AbstractEventLoop. So the code is broken and mypy is right.
