### ISSUE TITLE
Enable configuration support through a config file

### ISSUE THREAD

**Issue by axx-tahrioui** [python/mypy#4012]
It should be possible to configure mypy through a file based in the project root.
Usecases would be at least:
- disable the usage of certain rules or for some sections of the code ( like automatically appending # type: ignore to the end of the lines).
- add granularity to the error levels -> support for not only errors but warnings etc.
- support enabling/disabling checking in different verbosity levels for different files/dirs which can be matched by a pattern

**Comment by ethanhs** [comment]
Mypy already has [config file support](http://mypy.readthedocs.io/en/latest/config_file.html). You can see mypy's own [self check config file](https://github.com/python/mypy/blob/master/mypy_self_check.ini) as an example.

There area already various issues open related to most of your suggestions. For adding a `# type: ignore` to the end of lines, you can configure mypy to silently follow imports and ignore any errors in that directory.
