### ISSUE TITLE
Spurious "No overload variant matches argument types"

### ISSUE THREAD

**Issue by chadrik** [python/mypy#4027]
I have an overloaded function that instantiates a class:

```python
from typing import Any, Type, TypeVar, overload
T = TypeVar('T')

@overload
def make(cls: Type[T]) -> T:
    pass

@overload
def make() -> Any:
    pass

def make(cls=None):
    if cls:
        return cls()
    return object()

c = make(int)

reveal_type(c)
```

Type checking with mypy (using latest from master branch) results in the error:

```
[out]
a.py:17: error: No overload variant of "make" matches argument types [Overload(def (x: typing.SupportsInt =) -> builtins.int, def (x: Union[builtins.str, builtins.bytes], base: builtins.int =) -> builtins.int)]
a.py:19: error: Revealed type is 'Any'
```

Removing the overload prevents the error:

```python
from typing import Type, TypeVar
T = TypeVar('T')

def make(cls: Type[T]) -> T:
    return cls()

c = make(int)
```

Is this a bug or user error?

thanks!

**Comment by JelleZijlstra** [comment]
Looks like a bug to me. I think it may be translating the type `int` to a callable incorrectly, so it no longer matches `Type`.

**Comment by ilevkivskyi** [comment]
``Overloaded`` actual for ``Type[...]``formal was just overlooked when implementing ``Type[...]``. This would be essentially just a two-line fix.

**Comment by ilevkivskyi** [comment]
As I promised here is a fix https://github.com/python/mypy/pull/4037

**Comment by chadrik** [comment]
Thanks!
