### ISSUE TITLE
Better error message for "Invalid type"

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4030]
There several situations where a quite terse error message is given: ``Invalid type "__main__.T"`` -- this could be an attempt to use a variable as a type, attempt to use function as a type, unsupported forward reference, maybe some other. I propose to make this error message more specific, or add a note:
```
error: Invalid type "__main__.f"
note: Functions can't be used as a type
```
and
```
error: Invalid type "__main__.Alias"
note: Variables can't be used as a type
```
The second can be also useful if someone accidentally created a variable instead of an alias. In this case we can even append a link to docs, if we detect that variable has type ``Type[...]``.

Another similar terse error message is ``Invalid base class``. We can say which base is invalid, this will be useful in case of multiple bases on the same line, and maybe also add a note in some cases explaining why it is invalid, like ``note: Union types can't be subclassed``, so that it is clear what went wrong.

**Comment by gvanrossum** [comment]
Also e.g.
```py
class C:
  A = int

a: C.A  # error: Invalid type "_.C.A"
```

**Comment by ilevkivskyi** [comment]
This case is actually quite important, especially until https://github.com/python/mypy/issues/3494 (document variables vs aliases) is not fixed.

**Comment by ilevkivskyi** [comment]
A rare case where adding "Invalid type" would be actually helpful is the error message for using subscriptable metaclasses in type context, see #6313.

**Comment by ilevkivskyi** [comment]
A similar example where we should give a better error message is (recently closed) https://github.com/python/mypy/issues/2477

**Comment by ilevkivskyi** [comment]
One more example is cast targets, see https://github.com/python/mypy/issues/6862
