### ISSUE TITLE
Cannot customize Counter type

### ISSUE THREAD

**Issue by davidblewett** [python/mypy#4032]
I had a situation where I wanted a collections.Counter that had string keys and Decimal values, but it appears that the current typing definition of it is set to Counter[str] with int values, and no way of specifying a different type for values.

```python
import typing
from collections import Counter
from decimal import Decimal


def test(foo:str) -> typing.Counter[str, Decimal]:
    bar: typing.Counter[str, Decimal] = Counter({'foo': Decimal('5.0')})
    bar[foo] += Decimal('5.0')
    return bar
```

returns:
```
counter_test.py:6: error: "Counter" expects 1 type argument, but 2 given
counter_test.py:7: error: "Counter" expects 1 type argument, but 2 given
counter_test.py:7: error: Dict entry 0 has incompatible type "str": "Decimal"
counter_test.py:9: error: Incompatible types in assignment (expression has type "Decimal", target has type "int")
```

I tried various approaches using typing.NewType , but couldn't figure out a combination to create a definition that could override the existing one for typing.Counter.

**Comment by davidblewett** [comment]
```python
import typing
from collections import Counter
from decimal import Decimal

DecimalCounter = typing.NewType('DecimalCounter', Counter)


def test(foo:str) -> DecimalCounter:
    bar: DecimalCounter = Counter({'foo': Decimal('5.0')})
    bar[foo] += Decimal('5.0')
    return bar
```

returns:
```

counter_test.py:9: error: Incompatible types in assignment (expression has type Counter[str], variable has type "DecimalCounter")
counter_test.py:9: error: Dict entry 0 has incompatible type "str": "Decimal"
counter_test.py:10: error: Incompatible types in assignment (expression has type "Decimal", target has type "int")

```

**Comment by davidblewett** [comment]
```python
import typing
from collections import Counter
from decimal import Decimal

DecimalDict = typing.Dict[str, Decimal]


def test(foo:str) -> DecimalDict:
    bar: DecimalDict = Counter({'foo': Decimal('5.0')})
    bar[foo] += Decimal('5.0')
    return bar
```

returns:
```
counter_test.py:9: error: Incompatible types in assignment (expression has type Counter[str], variable has type Dict[str, Decimal])
counter_test.py:9: error: Dict entry 0 has incompatible type "str": "Decimal"
```

**Comment by elazarg** [comment]
I don't think this is related to mypy or typing. You are asking for a different kind of Counter implementation; this issue should be filed elsewhere (maybe discussed in python-ideas mailing list).

What's wrong with simply using defaultdict?

**Comment by davidblewett** [comment]
The behavior of Counter has been very useful with other types of values than int. The docs even say:

> Note Counters were primarily designed to work with positive integers to represent running counts; however, care was taken to not unnecessarily preclude use cases needing other types or negative values. To help with those use cases, this section documents the minimum range and type restrictions.

**Comment by elazarg** [comment]
Your example do not require Counter. 

Adding another type argument will complicate the common use case. Besides, what should be the second type? It can't safely be some unbounded T. It will require some dedicated protocol.

**Comment by gvanrossum** [comment]
Either the stub needs to be extended to match the behavior of the actual implementation in the stdlib (I don't know, I've never used Counter myself). In that case, please file a PR with the typeshed project. Or this requires a change in the stdlib. In which case please take the discussion to bugs.python.org.

**Comment by ilevkivskyi** [comment]
When ``SupportsInt`` will be made a protocol in typeshed, then typeshed can probably define ``Counter`` as deriving from ``Dict[T, SupportsInt]`` instead of ``Dict[T, int]`` (however we need to be careful with invariance, there may be some underwater stones)

**Comment by JelleZijlstra** [comment]
I believe the last time I looked into this, I concluded that Counter isn't actually supposed to use other value types than `int`.
