### ISSUE TITLE
Drop support for Python 3.3

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#4036]
Python 3.3's End of Life is today. [relevant docs](https://docs.python.org/devguide/index.html#branchstatus). I believe in the past there was at least general consensus that we should drop support around the time it is EOL'd.

With an impending release, I believe it is the perfect time to stop supporting 3.3, however, we may want to support it for the 0.530 series, since the release is so soon.

Thoughts?

**Comment by gvanrossum** [comment]
Sounds like we should do this once 0.530 is released.

**Comment by elazarg** [comment]
(When it's done: #1243)

**Comment by deathaxe** [comment]
There are still some tools out there which use python3.3 and can't update soon. Dropping python 3.3 support would render this tool useless for developers contributing to such tools.

Sublime Text is one famous example.

**Comment by JukkaL** [comment]
@deathaxe It's possible to have multiple versions of Python 3 installed at the same time, so running mypy should only be slightly more complicated if users are stuck with Python 3.3. Do you think that the extra hassle of needing multiple installed Python 3 versions (and perhaps using virtualenv) is enough to alienate some users?

I agree that some users may want to continue using Python 3.3. Let's announce our intention to drop Python 3.3 in the release notes of 0.530 and link to this issue. If many users are worried about this, we can reconsider and keep 3.3 supported for now.

@elazarg I don't think that I want #1243 after all. I'll elaborate in #1243.

**Comment by deathaxe** [comment]
The question depends on what "dropping" means. I understand it as dropping support for checking legacy features/constructs which got obsolete in newer python versions.

If dropping targets the required python version to run mypy only, it's not that critical. Running different versions of python is no problem. Many people use virtualenv for isolated environments anyway.

**Comment by gvanrossum** [comment]
The intent as I understand it is to require at least 3.4 to run mypy. It can still analyze 3.2 and 3.3 code.

**Comment by JukkaL** [comment]
Even if mypy didn't officially support type checking 3.3 code, the differences between 3.3 and 3.4 are sufficiently minor that using the 3.4 target mode should be fine for most users. However, I don't see why we'd need to drop 3.3 as a type checking target, since the cost of maintaining it is minor -- mainly there may be some extra complexity in certain typeshed stubs.

**Comment by ethanhs** [comment]
Yes, the intention has always been to drop support for running mypy on 3.3. It should continue to analyze 3.3 code however, since 3.3 code should be valid 3.4 code.

**Comment by hugovk** [comment]
By the way, here's the pip installs for mypy from PyPI for the last month:
```
$ pypinfo --percent --pip mypy pyversion
python_version percent download_count
-------------- ------- --------------
3.6              63.9%         38,487
3.5              23.4%         14,107
3.4              10.1%          6,081
2.7               1.3%            763
3.3               0.8%            455
3.7               0.6%            364
2.6               0.0%              2
3.2               0.0%              1

```

**Comment by gvanrossum** [comment]
Oh, I think we forgot to do this for 0.540.

**Comment by hugovk** [comment]
Is this the file for the release notes? Is 0.550 next? 

http://mypy.readthedocs.io/en/latest/revision_history.html

**Comment by gvanrossum** [comment]
Yes and yes. But it looks like we also didn't merge the release branch back into master. I think the proper procedure should have been to make that change in master first and then cherry-pick it into the release branch, but we took a shortcut there.

**Comment by hugovk** [comment]
How about something like https://github.com/python/mypy/pull/4152?
