### ISSUE TITLE
Add support for custom `override_for_base` names

### ISSUE THREAD

**Issue by naufraghi** [python/mypy#4056]
We have a quite large codebase where the classes are created declaring a `setup` method in turn called by a shared `__init__`.

Is quite common to forward to the `super` class al the `**kwargs`, but mypy consider this an error:
```
Signature of "setup" incompatible with supertype ClassName
```
I've seen the code to allow the override is `checker.py:977`:
```python
    def check_method_or_accessor_override_for_base(self, defn: FuncBase,
                                                   base: TypeInfo) -> None:
        """Check if method definition is compatible with a base class."""
        if base:
            name = defn.name()
            if name not in ('__init__', '__new__', '__init_subclass__'):
                # Check method override
                # (__init__, __new__, __init_subclass__ are special).
                self.check_method_override_for_base_with_name(defn, name, base)
```
What is the best way to solve this error? Can we add a new name to the _special_ tuple? Are there better solutions to explain that `setup` is an `__init__` like method?

**Comment by ilevkivskyi** [comment]
> What is the best way to solve this error?

``# type: ignore``, or actually make the signatures compatible (e.g. by using ``Any`` in supertype).

**Comment by JukkaL** [comment]
A simple hack would be to use a custom mypy runner script that filters out specific messages from the output.

We could also extend the plugin interface to help here. One idea is to allow mypy plugins define custom rules for method override checks. Another idea is to let plugins to define error message filtering functions.

**Comment by naufraghi** [comment]
... `ignore` is what we are doing, perhaps I can better ignore that exact error as @JukkaL suggested.

I hope a day mypy will check if all the `**kwargs` are used :)

**Comment by gvanrossum** [comment]
> I hope a day mypy will check if all the `**kwargs` are used :)

Curious how you exect mypy to do that.

**Comment by naufraghi** [comment]
Not in all cases, but if no class is popping stuff from the dict, it may be possible to check if all the names / types are used. A possible syntax to formalize this common pattern could be:

```
class Base:
    def __init__(self, arg: int) -> None: ...

class Child(Base):
    def __init__(self, value: str, **kwargs: **KwArgs(Base)) -> None: ...
```

In this simple case `KwArgs(Base)` (or even `KwArgs(super)`) could expand in something like `NamedTuple('BaseKwArgs', [('arg', str)])`, to enforce we are not allowed to play with `kwargs`. An eventual `GrandChild` should expand recursively the expected names and types.

But perhaps I'm only dreaming :)

**Comment by JelleZijlstra** [comment]
The classes in mypy_extensions are different (although they use the same name as your proposal). `mypy_extensions.KwArg` lets you type a callable that takes arbitrary **kwargs as `Callable[[KwArg(Any)], None]`.

**Comment by naufraghi** [comment]
😢 I don't think I'll have enough time soon, but there are some pointers on:

1. it is possible to implement what I proposed?
2. if yes, there are some pointers on how to implement the feature? Some other parts in the code that do something before becoming a type?

**Comment by JukkaL** [comment]
Something like that you proposed may be implementable, but much depends on the specifics of how it would work. I was thinking about a related feature at one point, but it seemed difficult to implement in sufficient generality.

Before moving forward, we need data on how useful the feature would be in general. Sometimes a feature that works just fine for a single codebase doesn't generalize well to other codebases. Our typical process is to find potential use cases for a new feature from multiple large real-world codebases. We can then estimate how well the proposed feature works for typical code, how often the feature would be used, and whether the cost/benefit makes sense.
