### ISSUE TITLE
__import__ is incorectly typed for python 3.6.

### ISSUE THREAD

**Issue by igalic** [python/mypy#4060]
here's the function declaration:

```python
def __import__(name, globals=None, locals=None, fromlist=(), level=0):
```

and here's mypy's type hints:

```python
def __import__(name: str, globals: Dict[str, Any] = ..., locals: Dict[str, Any] = ...,
               fromlist: List[str] = ..., level: int = -1) -> Any: ...
```

and here's what that should look like:

```python
def __import__(name: str, globals: Optional[Dict[str, Any]] = ..., locals: Optional[Dict[str, Any]] = ...,
               fromlist: List[str] = ..., level: int = -1) -> Any: ...
```

**Comment by ilevkivskyi** [comment]
This is not mypy's problem (typeshed stubs are shared by several type checkers), could you please instead open this issue on [typeshed tracker](https://github.com/python/typeshed/issues)?

**Comment by igalic** [comment]
argh, of course. thank you.

**Comment by ethanhs** [comment]
@igakic There are plans for a release Friday.
