### ISSUE TITLE
self.__class__ is Any, unless I annotate __init__, in which case it is "type"

### ISSUE THREAD

**Issue by douglas-treadwell** [python/mypy#4065]
Wouldn't it be better if the type of self.__class__ was the current class?

`class Class(object):
    attr = None

    def __init__(self):
        # type: () -> None
        reveal_type(self.__class__)
        print(self.__class__.attr)
`

This way, the revealed type is:
Revealed type is 'builtins.type'

If I remove the # type annotation, the revealed type is:
Revealed type is 'Any'

**Comment by JelleZijlstra** [comment]
See python/typeshed#1549, which we'll hopefully reapply at some point.

**Comment by gvanrossum** [comment]
Also, the Any result is because without the annotation it's an untyped function. Newer mypy versions earn about reveal_type() in that context.
