### ISSUE TITLE
Refactor semantic analyzer

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4083]
The current semantic analyzer is hard to understand and modify. Here some ideas for how to  improve things:

* Create separate modules for the three different passes (say, `mypy.analyzer[123]`).
* Don't pass a `SemanticAnalyzer` instance to the first and third passes. Instead, move any shared functionality to a utility class (or functions), and put them in a separate module such as `mypy.analyzeutil`.
* Rename the passes to, say, `SemanticAnalyzerPass[123]`.

**Comment by ethanhs** [comment]
Should we close #3459 in favor of this? Or close this in favor of that?

**Comment by ilevkivskyi** [comment]
We can keep #3459 to track documenting part, which is not mentioned here, but I leave this up to @JukkaL to decide.

**Comment by elazarg** [comment]
Also
* We can try (again) to extract the creation of namedtuple, typeddict etc. to a separate module
* The analysis of a class can follow the interpreter: first analyzing the body, then passing the results to a "meta" function that constructs the class object. This will be cleaner, and a good plugin point (e.g. for special classes)

**Comment by ethanhs** [comment]
I think this issue could use an update since there has been a lot of progress on this :) I believe we still want to not pass the second pass' instance to the first pass, but are there other concrete steps left in this issue?

**Comment by JukkaL** [comment]
Here's what has been done:

* Semantic analysis passes have been moved to different modules and they have documentation.
* Named tuple, TypedDict, NewType and call-based Enum have been moved to new modules.

The main missing thing is getting rid of direct references between passes.

**Comment by JukkaL** [comment]
Closed in favor of #6204, which has a wider scope.
