### ISSUE TITLE
Replace `--disallow-any` flags with separate boolean flags.

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#4089]
The `--disallow-any` flags interact in unexpected ways with other flags and they make configuration more complicated. We should replace them with a set of simple boolean flags. See discussion in #4076.

**Comment by gvanrossum** [comment]
When we do this, we should get rid of `--disallow-any=unannotated` completely, since it would just be a synonym for `--disallow-untyped-defs`.

**Comment by JelleZijlstra** [comment]
#4076 already removes `unannotated`.

**Comment by gvanrossum** [comment]
Are you sure? It still looks supported. Maybe you forgot to push a commit?

**Comment by JelleZijlstra** [comment]
I think you're right. I'll submit another PR with the rest of my changes, probably not now though.

**Comment by ilinum** [comment]
I think it's important that the documentation for the new `disallow_any` flags is grouped so it is easier to find other `disallow_any` flags if you're looking at one.

@JelleZijlstra I can try to implement this if you want -- it should be pretty straightforward. But if you want to do it -- feel free to.
