### ISSUE TITLE
How to implement type 'wrappers'

### ISSUE THREAD

**Issue by xlevus** [python/mypy#4100]
I'm currently writing a library that's using type annotations to alter the behaviour of a function, and ideally I would like it to pass type checking.

Trivial example:

```
@wrap_deserialize  # Takes serialised data, deserializes it, and sticks it in the annotated type.
def feed_dog(dog: Dog) -> int:
    dog.hunger -= 10
    return instance.hunger

feed_dog("""{'breed': 'Corgi', 'name': 'Rex', 'hunger': 10}""")
```

I'd like to be able to annotate the annotations further. e.g.

```
@wrap_deserialize
def feed_dog(dog: X[Dog, 'Corgi']) -> int:
    global feed    
    feed -= 10
    dog.hunger -= 10
    return instance.hunger

@wrap_deserialize
def feed_dog(dog: X[Dog, 'GreatDane']) -> int:
    global feed
    feed -= 100
    dog.hunger -= 10
    return instance.hunger

feed_dog("""{'breed': 'Corgi', 'name': 'Rex', 'hunger': 10}""")
```

Is it possible to make class `X` that as far as the type-checker is concerned, is `Dog`, but the object in `__annotations__` is an `<X type=Dog, properties=('GreatDane',)>`?

I've tried messing with various approaches, but I'm starting to wonder if it's not possible.

**Comment by ilevkivskyi** [comment]
If you annotate ``X`` as ``Any`` then everything should pass, if this an acceptable solution for you.

**Comment by gvanrossum** [comment]
In your example it seems that Corgi and GreatDane are begging to be
subclasses of Dog, with feed methods.

**Comment by xlevus** [comment]
@ilevkivskyi It's not ideal, but it might have to be that way... I was really getting used to omnicompletion that actually works.

@gvanrossum I admit, my example isn't the best representation, of the problem. But subclasses are currently what I have implemented, but given the boundless nature of 'dog breeds', creating a class for each of them has become somewhat cumbersome.

I suspect a better approach would be to provide the annotations with decorators, instead of parameters on the annotation.

**Comment by gvanrossum** [comment]
It sounds like you have what you need to try and refactor your code to be better checkable by mypy. If you have no further questions can you close the issue?
