### ISSUE TITLE
Don't terminate on first misplaced type annotation

### ISSUE THREAD

**Issue by Wilfred** [python/mypy#4102]
Given the source code:

```python
def wrong1():
    "A docstring."
    # type: () -> int
    return 42


def wrong2():
    "A docstring."
    # type: () -> int
    return 42
```

mypy only shows the first misplaced type annotation:

```
$ mypy --py2 foo.py
foo.py:3: error: misplaced type annotation
```

It would be nice if mypy carried on and showed all the errors in the file.

**Comment by gvanrossum** [comment]
AFAIK this behavior is due to https://github.com/python/typed_ast, and you'd have to file the bug in that project.

**Comment by Wilfred** [comment]
Filed https://github.com/python/typed_ast/issues/59.

**Comment by ilevkivskyi** [comment]
OK, let us move the discussion there.
