### ISSUE TITLE
Complain if code is missing type annotations

### ISSUE THREAD

**Issue by mitar** [python/mypy#4107]
Currently, if code is missing type annotations, it is not type checked. I would prefer that in our project we would enforce that all code has type annotations. Would it be possible to add a switch to have mypy complain if code is missing those?

**Comment by ilevkivskyi** [comment]
mypy already has ``--disallow-untyped-defs``, see http://mypy.readthedocs.io/en/latest/command_line.html

**Comment by mitar** [comment]
Oh, how I missed this. Sorry for the noise.
