### ISSUE TITLE
mypy_path option does not work

### ISSUE THREAD

**Issue by conanfanli** [python/mypy#4121]
The documented `mypy_path` option (http://mypy.readthedocs.io/en/latest/config_file.html?highlight=mypy_path) does not work for me. My "setup.cfg" (also tried "my.ini") is

```
[mypy]
ignore_missing_imports = True
mypy_path = './stubs'
```
This does not pickup my stub files. However, if I ran `MYPYPATH='./stubs' mypy .`, it works as expected.

**Comment by gvanrossum** [comment]
The docs don't say that ~ expansion happens, so this is as expected.

**Comment by conanfanli** [comment]
@gvanrossum I don't think it was a problem of expansion as I changed `~/stubs` to `./stubs` and got the same behavior

**Comment by gvanrossum** [comment]
You don't seem to understand what ~ expansion means. "./stubs" is supported by the OS kernel. When you type "~/stubs" into the shell it's the *shell* that expands it, first to "$HOME/stubs" and then to whatever the "$HOME" variable is set to.

**Comment by conanfanli** [comment]
@gvanrossum,  thank you for your kind response. As a matter of fact, that's exactly how I understood expansion. If you could take a few extra seconds to read my description and comment, you would understand that my issue happens regardless of the usage of ~ expansion. The stub files are located in the current directory "./stub" unless you're telling me that relative paths don't work.

**Comment by gvanrossum** [comment]
Sorry, I indeed misread your second message. So your claim is that setting `mypy_path = ./stubs` in mypy.ini doesn't work.

I have tried to reproduce this and cannot reproduce the effect. Can you produce a small self-contained example and show all the details? It might also be useful to remove the `ignore_missing_imports = True` since with that flag on, missing imports will silently be replaced with something of type `Any`.

**Comment by gvanrossum** [comment]
It's been reported on Gitter too so I guess there's some way this is broken.

**Comment by krzysz00** [comment]
I've created a rather minimal example that produces the unexpected behavior for me. I expect both of the `mypy` invocations in `test.sh` to succeed, but the second one fails.

[testcase.tar.gz](https://github.com/python/mypy/files/1389240/testcase.tar.gz)

**Comment by ethanhs** [comment]
I can repro it on master on Windows based on @krzysz00's sample.

**Comment by conanfanli** [comment]
@gvanrossum @krzysz00 @ethanhs thank you all for the help but I think I got y'all fooled (unintentionally) :) 

I added a print statement at https://github.com/python/mypy/blob/64c8ca0fcb39d56e4bb9be98103a0f9e49b01f90/mypy/build.py#L174 and found out that I shouldn't have put quotes around the path. So instead of
```
mypy_path = './stubs'
```
it should be
```
mypy_path = ./stubs
```

So the option works after all but perhaps we could have better documentation or error message when the path is invalid. 🤷‍♂️

**Comment by gvanrossum** [comment]
Thanks for debugging your own mistake! Maybe you can submit a PR to update the docs to clarify the format? I think it's described here, with interpolation=False: https://docs.python.org/3/library/configparser.html

Or you could add validation that checks whether the path exists and is a directory.

**Comment by conanfanli** [comment]
I'm not familiar with this code base so wouldn't want to introduce risky changes. Validation could be tricky because I think you could technically have quotes in directory names.  

I'd be happy to make a small and low-risk contribution by adding a note in the documentation:
https://github.com/python/mypy/pull/4126
Feel free to approve or reject. 

Cheers
