### ISSUE TITLE
Empty return statement should be treated as return None

### ISSUE THREAD

**Issue by mkurnikov** [python/mypy#4123]
Currently, this 
```
from typing import Optional

def test_return(flag: bool) -> Optional[int]:
    if flag:
        return

    return 0
```
fails with 

```
return.py:6: error: Return value expected
```

With `return None` there are no errors, as expected. 

mypy 0.530, python 3.6.3.

**Comment by gvanrossum** [comment]
This is intentional. It's bad style to have some `return <expr>`, some `return` and some just falling off the end of the block in the same function. So either all returns must have an expression (and falling off the end is an error), or none of them.
