### ISSUE TITLE
"if isinstance" check to forward reference of union fails to refine block

### ISSUE THREAD

**Issue by Daenyth** [python/mypy#4124]
```
foo.py:5: error: Item "Bar" of "Union[Foo1, Foo2, Bar]" has no attribute "x"
foo.py:7: error: Item "Foo1" of "Union[Foo1, Foo2, Bar]" has no attribute "y"
foo.py:7: error: Item "Foo2" of "Union[Foo1, Foo2, Bar]" has no attribute "y"
```

```
from typing import *

def frob(a: 'U') -> int:
    if isinstance(a, (Foo1, Foo2)):
        return a.x
    else:
        return a.y

class Foo1(NamedTuple):
    x: int
class Foo2(NamedTuple):
    x: int
class Bar(NamedTuple):
    y: int
U = Union[Foo1, Foo2, Bar]
```

mypy==0.530

**Comment by gvanrossum** [comment]
This seems to be due to the forward references. Does it work for you to move the classes and the union before the first use? (Or to another module.)

**Comment by Daenyth** [comment]
If you move the classes (not even the union) before the function, it works.

**Comment by ilevkivskyi** [comment]
This is probably some remainder of the recent big ``ForwardRef`` PR (my guess is something still not fixed in the tuple fallbacks). I will take care.

**Comment by ilevkivskyi** [comment]
Currently only the last two errors are shown independently of where the union defined, before or after the function. So this is probably a meet problem for tuple types.

**Comment by ilevkivskyi** [comment]
This now works correctly.
