### ISSUE TITLE
"Signature incompatible with supertype" with no obvious difference

### ISSUE THREAD

**Issue by ttsiodras** [python/mypy#4129]
Given the fact that `IdenticalPerSMP2` is a class member, and the fact that `grep` shows this output...
  
    $ grep 'def Identical' dmt/commonPy/asnAST.py 
    def IdenticalPerSMP2(self, _: AsnNode, __: Lookup, ___: Lookup) -> bool:  # pylint: disable=no-self-use
    def IdenticalPerSMP2(self, other: AsnNode, _: Lookup, __: Lookup) -> bool:
    def IdenticalPerSMP2(self, other: AsnNode, _: Lookup, __: Lookup) -> bool:
    def IdenticalPerSMP2(self, other: AsnNode, _: Lookup, __: Lookup) -> bool:
    def IdenticalPerSMP2(self, other: AsnNode, _: Lookup, __: Lookup) -> bool:
    def IdenticalPerSMP2(self, other: AsnNode, _: Lookup, __: Lookup) -> bool:
    def IdenticalPerSMP2(self, other: AsnNode, mynames: Lookup, othernames: Lookup) -> bool:
    def IdenticalPerSMP2(self, other: AsnNode, mynames: Lookup, othernames: Lookup) -> bool:
    def IdenticalPerSMP2(self, other: AsnNode, mynames: Lookup, othernames: Lookup) -> bool:
    def IdenticalPerSMP2(self, other: AsnNode, mynames: Lookup, othernames: Lookup) -> bool:
    def IdenticalPerSMP2(self, other: AsnNode, mynames: Lookup, othernames: Lookup) -> bool:

...why would mypy complain that:

$ mypy  dmt/commonPy/asnAST.py 
    dmt/commonPy/asnAST.py:156: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"
    dmt/commonPy/asnAST.py:191: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"
    dmt/commonPy/asnAST.py:248: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"
    dmt/commonPy/asnAST.py:286: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"
    dmt/commonPy/asnAST.py:409: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"

What is the incompatibility that is detected here? Surely it can't be the names of the parameters (they don't have anything to do with the types). The underscores are used since the parameters are not used in the base class, and the code is also processed with other linters that complain otherwise.

Base class: https://github.com/ttsiodras/DataModellingTools/blob/master/dmt/commonPy/asnAST.py#L98

Derived class (line 156 in the report above): https://github.com/ttsiodras/DataModellingTools/blob/master/dmt/commonPy/asnAST.py#L156

Any help most welcome.

**Comment by elazarg** [comment]
Note that names of parameters _has_ something to do with the type.
```python
class A:
    def f(x: int): pass
class B(A):
    def f(y: int): pass

a: A = B() # supposedly fine
a.f(x=5)  # Typechecks, but gives runtime error
```
I'm not saying that's the issue here.

**Comment by ttsiodras** [comment]
@elazarg I see... If that is the case, then how would we mark parameters as unused for pylint? In the case of my report, there are plenty of subclasses that don't use all parameters - if I don't use the _"name parameters with underscores"_ convention, I will get warnings from pylint...

I am hoping this is not a case of  _"you can only please one analyzer".

**Comment by gvanrossum** [comment]
I don't feel the need to discuss pylint, but I am still curious why the original code gets an error when the tiny example that Elazar gave gives no mypy errors.

What mypy flags / config are you using?

**Comment by ttsiodras** [comment]
Verified - changing to use identical parameter names everywhere silences mypy.

I guess I'll do that and instruct pylint to ignore these lines - if I have to choose which analyzer to please, I prefer mypy.

**Comment by ttsiodras** [comment]
@gvanrossum No special arguments - you can try cloning the repo, and then reproduce with:

    $ mypy dmt/commonPy/asnAST.py 
    dmt/commonPy/asnAST.py:156: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"
    dmt/commonPy/asnAST.py:191: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"
    dmt/commonPy/asnAST.py:248: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"
    dmt/commonPy/asnAST.py:286: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"
    dmt/commonPy/asnAST.py:409: error: Signature of "IdenticalPerSMP2" incompatible with supertype "AsnNode"

**Comment by ttsiodras** [comment]
Oh, and just in case I am missing something obvious - I installed from pip:

    (master)$ pip3 freeze | grep mypy
    mypy==0.530
