### ISSUE TITLE
Confusing note if Mypy cannot find __init__ of a class

### ISSUE THREAD

**Issue by Zac-HD** [python/mypy#4132]
This is another entry in the genre of confusing interactions between Mypy and attrs, extracted from #2088 by request of @gvanrossum.  Let's start with an example:

```python
import attr
@attr.s()
class A:
    arg = attr.ib()
A(arg=1)
```

```bash
$ python -m mypy --ignore-missing-imports a.py
a.py:5: error: Unexpected keyword argument "arg" for "A"
Lib/mypy/typeshed/stdlib/3/builtins.pyi:39: note: "A" defined here
```

Mypy can't find `A.__init__`, so it points to the stub for `object.__init__`... but misreports it as the definition of `A`.

**Comment by elazarg** [comment]
This has nothing to do with attrs, since mypy knows nothing about it. Minimal repro:
```python
class A: pass
A(arg=1)
```

**Comment by Zac-HD** [comment]
> This has nothing to do with attrs, since mypy knows nothing about it. Minimal repro: <...>

Well, mypy gives an unhelpful message for both examples - the difference is that my example works at runtime, while yours raises `TypeError: object() takes no parameters`

**Comment by elazarg** [comment]
And this difference amounts to "mypy knows nothing about attrs" which is a feature request and not _this_ bug. Supporting attrs will not resolve this bug, while handling my example will.
(I admit I am not sure what are we discussing here).

**Comment by gvanrossum** [comment]
Most likely we are trying to correct Zac's mental model of how mypy
actually works, and how to understand its error messages. Knowing that mypy
doesn't know what attrs does (in this case, add a __init__ with a different
signature), we can understand that mypy will complain about A(arg=1)
because the __init__ it is aware of does not allow this.

**Comment by Zac-HD** [comment]
The error message for this case has been improved; as of mypy 0.610 it is 

    a.py:5: error: Unexpected keyword argument "arg" for "A"
