### ISSUE TITLE
Slow incremental run when single module has errors

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4135]
`mypy -i` is slower than expected in the following scenario:

* Check out fresh mypy repository
* Create tiny module `mypy.x` that generates an error: `echo '1 + ""' > mypy/x.py`
* Run `mypy -i mypy` 
  * This takes a while, generates an error for `mypy/x.py` as expected
* Run `mypy -i mypy`
  * This is as slow as the previous run, but caching should make this much faster

**Comment by JukkaL** [comment]
@gvanrossum  in https://github.com/python/mypy/pull/4130#issuecomment-337953730:

> The performance problem is apparently not new -- I can reproduce this with standard -i mode as well. No cache entries for the mypy package are written somehow -- perhaps because mypy.x precedes all other submodules of mypy. This could be due to an edge case in the topsort.

**Comment by gvanrossum** [comment]
Adding topic-daemon label because this impedes one of the important use cases for the daemon (quickly rechecking code with errors).

**Comment by JukkaL** [comment]
This is blocking progress in fine-grained incremental mode. ASTs can't be reused when there is an error. In fine-grained incremental mode we want to cache every module that has no blocking errors. I'll try to fix or work around this.

**Comment by JukkaL** [comment]
I've worked around this in my local branch (but have not fixed the underlying issue).

**Comment by gvanrossum** [comment]
I've got a clue about why this is happening: in BuildManager.write_cache(), on line 1943, there's a check for self.manager.errors.is_errors(). But this returns True when there was an error in any previous file! And then two lines down we actually call delete_cache().

What we actually need is a little different -- we want to check if the current SCC or any of its dependents has errors.
