### ISSUE TITLE
__spec__ incorrectly flagged as not existing in the global/module namespace

### ISSUE THREAD

**Issue by brettcannon** [python/mypy#4145]
If you have code in a module that wants to access a module's `__spec__` attribute through the global namespace, mypy claims that `error: Name '__spec__' is not defined`. E.g. `@unittest.skipIf(__spec__ is None, '__spec__ is None')`. This same issue doesn't come up for `__name__` or `__path__`.

**Comment by gvanrossum** [comment]
It's probably just missing `__spec__` in the typeshed stub for ModuleType
in types.pyi.

**Comment by ilevkivskyi** [comment]
I think this is similar to https://github.com/python/mypy/issues/1422, should be not hard to fix, but this requires an addition to ``implicit_module_attrs`` in ``nodes.py`` depending on Python version (IIUC they are not present in all versions).

**Comment by brettcannon** [comment]
@ilevkivskyi You're right, `__spec__` didn't show up until Python 3.4.
