### ISSUE TITLE
Avoid warning for correct return type conversion

### ISSUE THREAD

**Issue by ArneBachmann** [python/mypy#4147]
```
def func(name:Union[str, int]) -> int?:
  if type(name) is int: return name
```
gives `error: Incompatible return value type (got "Union[str, int]", expected "Optional[int]")`
```
def func(name:Union[str, int]) -> int?:
  if type(name) is int: return int(name)
```
gives `error: Argument 1 to "int" has incompatible type "Union[str, int]"; expected "SupportsInt"`
```
def func(name:Union[str, int, SupportsInt]) -> int?:
  if type(name) is int: return int(name)
```
doesn't help either. Ideas?

**Comment by gvanrossum** [comment]
Mypy is trained on `isinstance(x, C)` in those cases -- is there any reason you prefer `type(x) is C`? (There's a slight semantic difference, but it rarely matters.)

**Comment by JelleZijlstra** [comment]
Also, what's up with your `int?` annotation? That's not valid syntax.

**Comment by ArneBachmann** [comment]
Sorry, the annotation is from [Coconut](https://github.com/evhub/coconut/) and gets compiled down to `Optional[int]`.

Anyway in Python 3 it seems to be better to use `isinstance()` which is new to me but solves the problem.
