### ISSUE TITLE
Please remember to update mypy-lang.org "What's new" section (or just remove it)

### ISSUE THREAD

**Issue by Deimos** [python/mypy#4151]
Definitely not a major issue, but the "What's new" section on mypy-lang.org hasn't been updated for the last two releases and gives the impression that there hasn't been a release in 3 months.

Maybe it would be good to just replace that section with a link to the blog for info about releases, so there's one fewer thing that needs to be updated?

**Comment by gvanrossum** [comment]
I'll make a PR for https://github.com/JukkaL/mypy-website to implement the latter suggestion. (I'll keep older news.)
