### ISSUE TITLE
Item "type" of "Union[Type[Foo], Type[Bar]]" has no attribute "x"

### ISSUE THREAD

**Issue by Daenyth** [python/mypy#4155]
```
# mypy 0.530
foo.py:14: warning: Returning Any from function declared to return "int"
foo.py:14: error: Item "type" of "Union[Type[Foo], Type[Bar]]" has no attribute "x"
```

```python
from typing import *

class Foo(NamedTuple):
    a: int
    @classmethod
    def x(cls) -> int: return 1

class Bar(NamedTuple):
    a: int
    @classmethod
    def x(cls) -> int: return 1

def foo(t: Type[Union[Foo, Bar]]) -> int:
    return t.x()
```

If I make them usual classes instead of namedtuples, it works

**Comment by gvanrossum** [comment]
Good catch. Looks like the code that checks for class attributes doesn't handle unions yet.

**Comment by elazarg** [comment]
This has nothing to do with unions. Accessing x in `Type[FOO]` does not work either, specifically for NamedTuple. Probably something about the combination of TypeType and TupleType.

**Comment by gvanrossum** [comment]
You're so right! Relabeled.

**Comment by ilevkivskyi** [comment]
This seems similar to https://github.com/python/mypy/issues/3791. Also as discussed there, I think this is quite low priority, since one should prefer dataclasses for such complex cases.

**Comment by Daenyth** [comment]
I agree that dataclasses are preferable, but unless I'm mistaken they are not ready for production use. If they are I'll definitely look into them since it would simplify a great deal.

**Comment by ilevkivskyi** [comment]
@Daenyth 
> they are not ready for production use.

Yes they aren't yet.  They are planned for Python 3.7.

**Comment by JukkaL** [comment]
This also happens for classes that aren't named tuples:

```py
from typing import Tuple, Type

class C(Tuple[int, str]):
    @classmethod
    def f(cls) -> None: pass

t: Type[C]
t.f()  # "Type[C]" has no attribute "f"
```

I'm increasing priority to normal because the above example seems quite reasonable.
