### ISSUE TITLE
Warn about unannotated functions containing annotations

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4166]
I found some examples (https://bugs.python.org/issue28936) of functions that have no signature annotations but contain local variable annotations. These are currently ignored. I think we should actually warn whenever an annotation (either a type comment or PEP 526 style) occurs in an unannotated function, since it likely reflects some kind of misunderstanding about annotations.

Or at the very least we should have an option to warn about such things.

(IIRC we recently doused a similar source of confusion, but I can't recall the details.)

**Comment by ilevkivskyi** [comment]
Isn't this a duplicate of https://github.com/python/mypy/issues/3948? Or am I missing something?

**Comment by gvanrossum** [comment]
How quickly we forget. :-)
