### ISSUE TITLE
Properties, `setter`, and `Incompatible types in assignment`

### ISSUE THREAD

**Issue by nnadeau** [python/mypy#4167]
# Expected Behaviour
- Ability to use property `setter` with `Union[]`
- The intention is to overload the `setter`

# Actual Behaviour & Repro Case
## Python Code
```python
from typing import Union


class A:
    def __init__(self) -> None:
        self._foo = 0

    @property
    def foo(self) -> int:
        return self._foo

    @foo.setter
    def foo(self, value: Union[int, float]) -> None:
        self._foo = int(value)


if __name__ == '__main__':
    a = A()
    print(a.foo)

    a.foo = 123
    print(a.foo)

    a.foo = 456.789 # error thrown here
    print(a.foo)
```

## Stdout
```
0
123
456
```
(i.e., valid Python code)

## Mypy CLI
```
mypy --strict
```

## Result
```
error: Incompatible types in assignment (expression has type "float", variable has type "int")
```

# Notes
- `Mypy` seems to be type checking the assignment using the type declared in `def foo(self) -> int:` instead of the declared types in the `setter`: ` def foo(self, value: Union[int, float]) -> None:`

# Current Solution
- Silence the error with `# type: ignore`

**Comment by gvanrossum** [comment]
Your hunch is correct: for properties, mypy uses the type declared in the initial `@property` definition as the final type for the attribute, regardless of what the `@property.setter` does.

I suppose we could fix this though it might require a bunch of one-off changes in odd corners of the code since properties are unique in this respect.

**Comment by srittau** [comment]
This seems similar to issue #3004, which has more discussion.

**Comment by gvanrossum** [comment]
Oh, yeah, it's a duplicate.
