### ISSUE TITLE
Better message for invalid types like List(int)

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4172]
The error message "invalid type comment or annotation" isn't very helpful if a user writes `List(int)` instead of `List[int]` (or `Optional(int)`).  This seems to be a common error.

Example:

```py
from typing import List

def f():
    # type: () -> List(int)   # invalid type comment or annotation
    return [1]
```

A better message could be something like this:

```
program.py:3: error: Syntax error in type annotation
program.py:3:note: Suggestion: Use List[...] instead of List(...)
```

**Comment by paultgibbons** [comment]
Another example that's not immediately obvious is missing parens around input eg

```
def f(x):
    # type: List[int] -> Tuple[List[int], Optional[str]]
    ...
```
throws message `error: syntax error in type comment`,
but would be nicer if it was more like
```
error: syntax error in type comment
Suggestion: Expected ( found L at column 13
```
or 
```
error: syntax error in type comment
Suggestion: Wrap input in parans
```
or something else to highlight the issue

**Comment by gvanrossum** [comment]
Here's one that took a while to figure out:
```py
def update_state(conf,               # type: SourceConf
                 new_state,          # type: SourceState
                 tid,                # type: int
                 vid,                # type: int
                 update_ts=None,     # type: Optional[float],
                 ):         # type: (...) -> SourceConf
```
This gave `error: Invalid tuple literal type` on the `def` line.

**spoiler alert**

.

.

.

.

.

.

.

.

.

.

.

.

.

There's an extra comma after `Optional[float]`.

**Comment by ethanhs** [comment]
@gvanrossum Well, https://github.com/python/mypy/issues/3871 should help a bit in your case. I'd fix it but I'm currently occupied with my PEP.

**Comment by ilevkivskyi** [comment]
It looks like #4323 fixed only _part_ of the problems mentioned here, I am reopening this, just not to lose track.
