### ISSUE TITLE
Better message for invalid types like (int, str)

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4173]
The error message "Invalid tuple literal type" isn't very helpful if a user writes `(int, str)` instead of `Tuple[int, str]`.

Example:

```py
from typing import List

def f():
    # type: () -> (int, str)   # Invalid tuple literal type
    return (1, 'x')
```

A better message could be something like this:

```
program.py:3: error: Syntax error in type annotation
program.py:3:note: Suggestion: Use "Tuple[T1, ..., Tn]" instead of "(T1, ..., Tn)"
```

#4172 is closely related.

**Comment by elliott-beach** [comment]
Interested. Are you suggesting literally `(T1, ..., Tn)` or substituting in the types values used, as in, `(int, str)` in the error message? I think the later makes more sense, if slightly more complex to implement.

**Comment by ethanhs** [comment]
@Hnasar that is technically https://github.com/python/mypy/issues/4172, but these are, as Jukka said previously, closely related.
