### ISSUE TITLE
Infer return None in stubgen

### ISSUE THREAD

**Issue by chantisnake** [python/mypy#4181]
Is it possible that when a function don't have any return statement, mypy can infer that the return type is `None`?

Both Pycharm and Typescript has this feature.

**Comment by gvanrossum** [comment]
No, mypy's position is that the body must conform to the signature, not the other way around.

This would be a good feature for stubgen though.

**Comment by hoefling** [comment]
Hi, I added a proposal for this feature implementation, would be grateful for a review! I have doubts about the ellipsis case - should a function with ellipsis also have `None` return type?
