### ISSUE TITLE
Reporting "too many arguments" to __init__ for class which takes *args

### ISSUE THREAD

**Issue by anentropic** [python/mypy#4183]
Trying to add hints to this:

```python
class ValidationError(Exception):

    def __init__(self, message: str, log_level: int=logging.ERROR, *args, **kwargs) -> None:
        self.message = message
        self.log_level = log_level
        super().__init__(message, log_level, *args, **kwargs)
```
gives:
```
error: Too many arguments for "__init__" of "BaseException"
```

Well, `Exception.__init__` supposedly takes `*args, **kwargs` so how can this ever have "too many arguments"?

If I change my code to:
```python
class ValidationError(Exception):

    def __init__(self, message: str, log_level: int=logging.ERROR) -> None:
        self.message = message
        self.log_level = log_level
        super().__init__(message, log_level)
```
then no error reported.

I'm actually happy with this change to my code. But does it suggest an issue with mypy?

This also works:
```python
class ValidationError(Exception):

    def __init__(self, message: str, log_level: int=logging.ERROR, whatever: str='WTF') -> None:
        self.message = message
        self.log_level = log_level
        super().__init__(message, log_level, whatever)
```
So it seems the issue is not with any specific number of arguments, but of mypy not understanding that `*args` means 'any number'?

**Comment by JelleZijlstra** [comment]
This is a typeshed issue. The problem is that `BaseException.__init__` in stdlib/3/builtins.pyi is defined as `    def __init__(self, *args: object) -> None: ...`. This means it takes arbitrary args, but not arbitrary kwargs, and your code passes `**kwargs`. The fix is obvious; could you submit a PR or issue to https://github.com/python/typeshed to fix it?

**Comment by anentropic** [comment]
@JelleZijlstra thanks, have opened a PR against typeshed

**Comment by Callek** [comment]
For anyone who find this in a search - BaseException.__init__ doesn't take keyword args and this was reverted in https://github.com/python/typeshed/pull/2348
