### ISSUE TITLE
Support Enum keyword arguments

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4184]
`enum.Enum(...)` accepts keyword arguments such as `module`, but mypy complains about them. 

Example from https://github.com/python/mypy/issues/2306#issuecomment-341111694:

```py
from enum import Enum

# Error: Too many arguments for Enum()
PictureSize = Enum('PictureSize', 'P0 P1 P2 P3 P4 P5 P6 P7 P8', type=str, module=__name__)
```

Documentation: https://docs.python.org/3/library/enum.html#functional-api

**Comment by anentropic** [comment]
I made an attempt to fix this in typeshed, please review when you have time, thanks

**Comment by elazarg** [comment]
Related namedtuple issues: #2127 #2124

**Comment by 97littleleaf11** [comment]
Has been fixed!
