### ISSUE TITLE
Incremental checker script doesn't seem repeatable

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4189]
I got varying results when running the incremental checker script multiple times across the same range of commits in daemon mode. Maybe it doesn't stop the daemon at the beginning?

**Comment by gvanrossum** [comment]
Correct. The dmypy2 branch fixes this too.

**Comment by gvanrossum** [comment]
Repro:

- check out 8cd9dbec08a371222a89570dde02bb521c33a635
- python3 misc/incremental_checker.py --daemon -r $PWD last 20
- python3 misc/incremental_checker.py --daemon -r $PWD last 10

Some commits run much faster on the second run.
