### ISSUE TITLE
Daemon perf inconsistency

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4196]
Repro:

- check out 8cd9dbec08a371222a89570dde02bb521c33a635
- `python3 misc/incremental_checker.py --daemon -r $PWD last 20`
- `python3 misc/incremental_checker.py --daemon -r $PWD last 10`

Some commits run much faster on the second run.

**Comment by gvanrossum** [comment]
That particular commit is too far in the past, but I tried this recently (at fbd23bfd2) with "last 50" and "last 25" and while most runs are pretty close, there are some dramatic differences:
```
 Now testing commit 9779e1877: "Two optimizations for load_graph() (#4294)"
     Output matches expected result!
-    Incremental: 16.045 sec
+    Incremental: 12.824 sec
     Original:    22.124 sec
...
 Now testing commit 540dc5777: "Refactor dmypy to move daemonize and Server to a separate file (#4315)"
     Output matches expected result!
-    Incremental: 10.211 sec
+    Incremental: 0.432 sec
     Original:    20.283 sec
...
 Now testing commit 5f8aaf63e: "Fix new flake8 errors (presumably from bugbear) (#4347)"
     Output matches expected result!
-    Incremental: 9.187 sec
+    Incremental: 17.795 sec
     Original:    19.629 sec
 Now testing commit fbd23bfd2: "Some daemon code cleanup (#4341)"
     Output matches expected result!
-    Incremental: 10.794 sec
+    Incremental: 1.698 sec
     Original:    19.025 sec
```
I'll see if I can repro these results in a cleaner environment (this was just on my laptop).

**Comment by gvanrossum** [comment]
I see similar but not identical issues in a clean(er) Linux environment. E.g. in that environment, 9779e1877 is much *slower* in the second (last 25) run, the results for 540dc5777 and fbd23bfd2 are about the same (much faster in the second run), and for 5f8aaf63e the runtimes hardly differ. But a few other runs where there was not much difference on my Mac laptop there's a significant difference on the Linux box.

I'm not going to dive deeper into this, but I have a hypothesis -- could it be that the enormous GC threshold selected (50000) causes occasional runs to be hit by huge GC delays? In that case this would not be a very interesting problem (unless we care much about absolute timings rather than aggregate).

**Comment by gvanrossum** [comment]
Yeah, another test of both runs on the same Linux VM produces different outliers again. That doesn't prove anything -- it could also just be that there are occasional hiccups in the environment (totally understandable) but I don't think we're chasing a systematic error here.

**Comment by JukkaL** [comment]
I'd like to understand this issue, as this could cause us trouble with fine-grained incremental checking as well. At least this could make it hard to measure performance improvements reliably. I wonder if there is an easy way to subtract the time used by GC from the results?

**Comment by gvanrossum** [comment]
We could start by writing some overall times at the end, so we at least
know the aggregate time and can see how it varies. The GC times are
gathered but surfacing this to the script is going to require a lot of
extra plumbing...

**Comment by gvanrossum** [comment]
I added some crude statistics gathering but even when running the same 25 commits (in the same order) twice on the same laptop I see significant differences. The first run reported 119 secs total build time and 5.1 secs total gc time; the second run reported 142 and 9.7, respectively. I think the problem is that we're using the real-time clock, so any time the process gets preempted by something else the clock keeps ticking. I'll commit the changes to the script.

**Comment by JukkaL** [comment]
It would be nice to have a more predictable environment for running benchmarks. I'll try to figure out something.

**Comment by msullivan** [comment]
Closing since the old daemon is dead
