### ISSUE TITLE
super().__new__() in namedtuple subclass expects subclass.__new__ parameters

### ISSUE THREAD

**Issue by EvanKrall** [python/mypy#4197]
```
from collections import namedtuple

Base1 = namedtuple(
    'Base1', [
        "a",
    ],
)


class Base2(object):
    def __new__(_cls, a):
        return super(Base2, _cls).__new__(_cls)


class Subclass1(Base1):
    def __new__(cls, a):
        return super(Subclass1, cls).__new__(
            _cls=cls,  # error: Unexpected keyword argument "_cls" for "__new__"
            a=a,
        )


class Subclass2(Base1):
    def __new__(_cls, a):
        return super(Subclass2, _cls).__new__(
            _cls=_cls,  # This works.
            a=a,
        )


class Subclass3(Base2):
    def __new__(cls, a):
        return super(Subclass3, cls).__new__(
            _cls=cls,  # This works?
            a=a,
        )


class Subclass4(Base2):
    def __new__(_cls, a):
        return super(Subclass4, _cls).__new__(
            _cls=_cls,  # This works.
            a=a,
        )


Subclass1(a='a')
Subclass2(a='a')
Subclass3(a='a')
Subclass4(a='a')
```

In the above code, I've defined four different subclasses -- the first two subclass from a namedtuple, and the second two subclass from a class. Subclass1 and Subclass3's `__new__`s call their class parameter `cls`, whereas Subclass2 and Subclass4 call it `_cls`.

Mypy complains about Subclass1's call to `__new__` on its superclass (the namedtuple Base1). It appears that mypy seems to be checking the supplied arguments against `Subclass1.__new__`, rather than `Base1.__new__`: mypy doesn't complain about Subclass2, which is identical to Subclass1 except that the first parameter to its `__new__` is called `_cls` instead of `cls`, matching the name of the parameter on the namedtuple.

This failure doesn't show up in classes that subclass regular objects, as shown by Subclass3 and Subclass4.

Tested on Python 3.6.0, mypy 0.540

**Comment by msullivan** [comment]
Seems to be fixed in 0.600
