### ISSUE TITLE
Allow adding custom methods to TypedDict

### ISSUE THREAD

**Issue by mitar** [python/mypy#4201]
I would like to extend TypedDict with extra abstract methods into, for example, class MyParams, which would then allow that those who will be extending MyParams, will be able to both specify types of values they want to list as params, but also have to implement abstract methods.

Currently, if I do:

```python
class MyParams(TypedDict):
    @abstractmethod
    def compute(self):
        pass
```

A subclass like `Foo = MyParams('Foo', {'a': int})` fails because it seems `MyParams` lost its special power to initialize it in this way. If I use class-based syntax, it works, but method `compute` is still not available on the instance (nor required to be defined, but this is clear problem because metaclass is not abstract metaclass).

**Comment by ilevkivskyi** [comment]
The initial design has a strong requirement for ``TypedDict``s to be very fast and memory-efficient. This is why at runtime ``TypedDict`` instances are just normal ``dict``s:
```python
>>> from mypy_extensions import TypedDict
>>> class TD(TypedDict):
...     x: int
...     y: int
...
>>> td = TD({1: 1, 2: 2})
>>> type(td)
<class 'dict'>
```
therefore, you just can't call any additional methods. I therefore propose to close this, unless we want to re-design it. Maybe we can open an issue at ``typing`` tracker to give an informative error if someone tries to add methods to ``TypedDict``.

**Comment by JukkaL** [comment]
Yeah, this is out of scope for `TypedDict`. `TypedDict` has been designed for a very specific use case where the runtime representation is just a regular `dict` object. If you want to define methods, you have to use a real class, unfortunately.

**Comment by mitar** [comment]
Hm, but my own class will not have a nature that mypy will know which types are stored under which keys, and to check for totality? Does this mean I will also have to roll out my own mypy plugin to be able to type check such class?

**Comment by mitar** [comment]
I mean, ideally, I should be able to specify to `TypedDict` which base class (extending `dict`) it is used at runtime, instead of `dict`. But `dict` should be the default for sure.

**Comment by ilevkivskyi** [comment]
@mitar 
>Hm, but my own class will not have a nature that mypy will know which types are stored under which keys, and to check for totality? Does this mean I will also have to roll out my own mypy plugin to be able to type check such class?

This is just another request for ``Intersection`` and/or something like ``@apply_protocol`` discussed in https://github.com/python/mypy/issues/2087

**Comment by George-Ogden** [comment]
What about `@classmethod`s and `@staticmethods`? At runtime, a `TypedDict` class is still as class. Is that feasible to support?
