### ISSUE TITLE
Callable argument doesn't accept a type alias which is a list

### ISSUE THREAD

**Issue by lewis6991** [python/mypy#4210]
The following snippet does not work:
```
MappingFuncArgs = [str, str, str, str]
MappingFunc = Callable[MappingFuncArgs, str]
```
Gives error:
```
The first argument to Callable must be a list of types or "..."
```

I also tried:
```
MappingFuncArgs = [str, str, str, str]
MappingFunc = Callable[[*MappingFuncArgs], str]
```
Which gave error:
```
Invalid type alias
```

**Comment by JelleZijlstra** [comment]
This isn't supported by Python's typing syntax in general, because Callable is essentially treated as one unit, and implementing it might require a change in PEP 484.

I can see that this could occasionally be useful, but it also seems obscure enough that it isn't high priority to implement.

**Comment by gvanrossum** [comment]
PEP 484 doesn't endorse this.

**Comment by martmists** [comment]
What about generics though? Copying from elsewhere:

```python
CT = TypeVar("CT")  # Call args type
RT = TypeVar("RT")  # Return type

# Totally unrelated to any code, just an example to illustrate example usage
# Some people may want to use CT or RT separately here

def wrap(func: Callable[CT, RT]) -> Callable[[int], Callable[CT, RT]]:
    def thing(arg: int) -> Callable[CT, RT]:
        return func
    return thing
```

**Comment by JelleZijlstra** [comment]
This kind of thing could be useful yes, but there are already some open issues in this repo about it.

**Comment by gvanrossum** [comment]
Also this particular case is better written like this:
```py
F = TypeVar('F', bound=Callable)
def wrap(func: F) -> Callable[[int], F]:
    def thing(arg: int) -> F:
        return func
    return thing
```
