### ISSUE TITLE
Is there a way to represent an empty tuple type?

### ISSUE THREAD

**Issue by leandropls** [python/mypy#4211]
`logging.handlers.SMTPHandler` arg `secure` accepts something like this:

    Union[EmptyTuple, Tuple[str], Tuple[str, str]]

Is there a way to define the `EmptyTuple` part?

**Comment by elazarg** [comment]
Should be `Tuple[()]`

**Comment by leandropls** [comment]
@elazarg thanks!

**Comment by ethanhs** [comment]
I did not find any documentation of this, so it would be nice to add that.

**Comment by gvanrossum** [comment]
True, the only mention of `Tuple[()]` is in PEP 484.
