### ISSUE TITLE
Daemon mode optimal behavior when there are no module interface changes

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4212]
I'm recording an idea so that I won't lose track of it. It's possible be that this is how dmypy already works.

Assume that module `a` imports `b` and we are using dmypy. Assume that `a` is much larger than `b` (it could be many modules). Now we modify `b` so that the public interface doesn't change. We could consider `a` dirty and process it to ensure that there won't be any references to the old version of `b` in the in-memory cache. This would be expensive, however. An alternative would be to not process `a` but to just drop the module from the in-memory cache (while retaining the JSON cache file). This way any sequence of internal modifications to `b` would be very fast as they'd only require processing `b`.

@gvanrossum Please close this if this is how dmypy already works (or if this is a bad idea).

**Comment by gvanrossum** [comment]
I think the latest PR (dmypy3 branch) essentially [works this way](https://github.com/python/mypy/pull/4199/commits/3edeafd3e82de3bd894f86a2c3674765e16eaed8). I'll keep this open until I'm sure.

**Comment by JukkaL** [comment]
It looks like the dmypy3 branch works like this when there are no errors, but once there is an error, it'll process all dependencies. It would be great if this could be extended to handle errors.

**Comment by gvanrossum** [comment]
Ah yes, we need to do better when there are errors.

**Comment by gvanrossum** [comment]
I don't think I have the chops to fix this, so unassigning.

**Comment by JukkaL** [comment]
This should already work efficiently in fine-grained incremental mode, so I don't think that there's anything that needs to be done any more.
