### ISSUE TITLE
'error: Value of type "Exception" is not indexable'  when in Python 2 mode

### ISSUE THREAD

**Issue by moreati** [python/mypy#4215]
When checking in Python 2 mode mypy reports as an error that `Exception` values cannot be indexed. That is true in Python 3.x, but not in Python 2.x - as per [PEP 352](https://www.python.org/dev/peps/pep-0352/), `BaseException.__getitem__` was removed in Python 3.0. So I _think_ this is a bug, rather than intended behaviour.

Example: 
```
$ mypy --version
mypy 0.540
```
```
$ cat ex.py 
e = Exception('foo')
print(e[0])
```
```
$ mypy -2 --strict ex.py 
ex.py:2: error: Value of type "Exception" is not indexable
```
```
$ python3 ex.py 
Traceback (most recent call last):
  File "ex.py", line 2, in <module>
    print(e[0])
TypeError: 'Exception' object is not subscriptable
```
```
$ python2 ex.py 
foo
```

**Comment by gvanrossum** [comment]
This is a typeshed issue -- you can just submit a PR to typeshed that adds `__getitem__` to `BaseException`.
