### ISSUE TITLE
Type inference does not work for NamedTuple subclass instances appearing before the type definition.

### ISSUE THREAD

**Issue by joshstaiger** [python/mypy#4216]
Run mypy (0.540) on the following code:

```python
from typing import NamedTuple

def f() -> None:
    x = MyTuple()
    reveal_type(x)

class MyTuple(NamedTuple): ...

def g() -> None:
    y = MyTuple()
    reveal_type(y)
```

The `x` variable is inferred to have type `Any`, while the `y` variable is correctly inferred as a `MyTuple`.

Note that ordinary classes that do not inherit from Named Tuple do not seem to have this issue.

**Comment by ilevkivskyi** [comment]
Yes, this still happens. Probably just another problem with forward references. I will try to fix this.

**Comment by AlexWaygood** [comment]
This [no longer reproduces](https://mypy-play.net/?mypy=0.720&python=3.10&flags=warn-unreachable&gist=4acd1e918195e80ecd32e676ac7cbca5) on mypy 0.720+
