### ISSUE TITLE
 "Union[str, Path]" is incompatible with "Union[str, bytes, int, _PathLike[Any]]"

### ISSUE THREAD

**Issue by sametmax** [python/mypy#4222]
I have some code doing:

    def extract(path: Union[str, Path]) -> Generator:
        with open(path) as f:
       
Mypy complains:

     Argument 1 to "open" has incompatible type "Union[str, Path]"; expected "Union[str, bytes, int, _PathLike[Any]]"

But it seems to me that Union[str, Path] is an subset of Union[str, bytes, int, _PathLike[Any]], or am I mistaken ?

**Comment by sametmax** [comment]
Sorry I should have given more info up front. I should know better.

Shell session:

```
➤ mypy analyse.py 
/home/user/.local/lib/mypy/typeshed/stdlib/3.5/pathlib.pyi:15: error: Name 'List' is not defined
analyse.py:6: error: Argument 1 to "open" has incompatible type "Union[str, Path]"; expected "Union[str, bytes, int, _PathLike[Any]]"
user@laptop:~/B/docapost
➤ mypy --version
mypy 0.540
```

Minimal example:

```
from typing import Union
from pathlib import Path

def extract(path: Union[str, Path]):
    open(path)
```

So Python 3.5 64bits on Ubuntu 16.04 installed with --user and mypy 0.540.

I just tried with a mypy from Python 3.6 and the error is not here anymore.

**Comment by sametmax** [comment]
Sorry I should have given more info up front. I should know better.

Shell session:

```
➤ mypy analyse.py 
/home/user/.local/lib/mypy/typeshed/stdlib/3.5/pathlib.pyi:15: error: Name 'List' is not defined
analyse.py:6: error: Argument 1 to "open" has incompatible type "Union[str, Path]"; expected "Union[str, bytes, int, _PathLike[Any]]"
user@laptop:~/B/docapost
➤ mypy --version
mypy 0.540
```

Minimal example:

```
from typing import Union
from pathlib import Path

def extract(path: Union[str, Path]):
    open(path)
```

So Python 3.5 64bits on Ubuntu 16.04 installed with --user and mypy 0.540.

I just tried with a mypy from Python 3.6 and the error is not here anymore.

**Comment by JelleZijlstra** [comment]
I guess it's because there is no PathLike protocol on 3.5, so "_PathLike" there does not include Path.

There might be something weird going on with the error. In typeshed, `open` is defined as follows:
```
if sys.version_info >= (3, 6):
    # This class is to be exported as PathLike from os,
    # but we define it here as _PathLike to avoid import cycle issues.
    # See https://github.com/python/typeshed/pull/991#issuecomment-288160993
    class _PathLike(Generic[AnyStr]):
        def __fspath__(self) -> AnyStr: ...

    def open(file: Union[str, bytes, int, _PathLike], mode: str = 'r', buffering: int = -1, encoding: Optional[str] = None,
             errors: Optional[str] = None, newline: Optional[str] = None, closefd: bool = ...) -> IO[Any]: ...
else:
    def open(file: Union[str, bytes, int], mode: str = 'r', buffering: int = -1, encoding: Optional[str] = None,
             errors: Optional[str] = None, newline: Optional[str] = None, closefd: bool = ...) -> IO[Any]: ...
```
So on 3.5, `_PathLike` is not part of the accepted type for the `file` argument, but nevertheless mypy's error mentions `_PathLike`.

**Comment by JelleZijlstra** [comment]
I guess it's because there is no PathLike protocol on 3.5, so "_PathLike" there does not include Path.

There might be something weird going on with the error. In typeshed, `open` is defined as follows:
```
if sys.version_info >= (3, 6):
    # This class is to be exported as PathLike from os,
    # but we define it here as _PathLike to avoid import cycle issues.
    # See https://github.com/python/typeshed/pull/991#issuecomment-288160993
    class _PathLike(Generic[AnyStr]):
        def __fspath__(self) -> AnyStr: ...

    def open(file: Union[str, bytes, int, _PathLike], mode: str = 'r', buffering: int = -1, encoding: Optional[str] = None,
             errors: Optional[str] = None, newline: Optional[str] = None, closefd: bool = ...) -> IO[Any]: ...
else:
    def open(file: Union[str, bytes, int], mode: str = 'r', buffering: int = -1, encoding: Optional[str] = None,
             errors: Optional[str] = None, newline: Optional[str] = None, closefd: bool = ...) -> IO[Any]: ...
```
So on 3.5, `_PathLike` is not part of the accepted type for the `file` argument, but nevertheless mypy's error mentions `_PathLike`.

**Comment by JelleZijlstra** [comment]
I guess it's because there is no PathLike protocol on 3.5, so "_PathLike" there does not include Path.

There might be something weird going on with the error. In typeshed, `open` is defined as follows:
```
if sys.version_info >= (3, 6):
    # This class is to be exported as PathLike from os,
    # but we define it here as _PathLike to avoid import cycle issues.
    # See https://github.com/python/typeshed/pull/991#issuecomment-288160993
    class _PathLike(Generic[AnyStr]):
        def __fspath__(self) -> AnyStr: ...

    def open(file: Union[str, bytes, int, _PathLike], mode: str = 'r', buffering: int = -1, encoding: Optional[str] = None,
             errors: Optional[str] = None, newline: Optional[str] = None, closefd: bool = ...) -> IO[Any]: ...
else:
    def open(file: Union[str, bytes, int], mode: str = 'r', buffering: int = -1, encoding: Optional[str] = None,
             errors: Optional[str] = None, newline: Optional[str] = None, closefd: bool = ...) -> IO[Any]: ...
```
So on 3.5, `_PathLike` is not part of the accepted type for the `file` argument, but nevertheless mypy's error mentions `_PathLike`.

**Comment by JelleZijlstra** [comment]
I guess it's because there is no PathLike protocol on 3.5, so "_PathLike" there does not include Path.

There might be something weird going on with the error. In typeshed, `open` is defined as follows:
```
if sys.version_info >= (3, 6):
    # This class is to be exported as PathLike from os,
    # but we define it here as _PathLike to avoid import cycle issues.
    # See https://github.com/python/typeshed/pull/991#issuecomment-288160993
    class _PathLike(Generic[AnyStr]):
        def __fspath__(self) -> AnyStr: ...

    def open(file: Union[str, bytes, int, _PathLike], mode: str = 'r', buffering: int = -1, encoding: Optional[str] = None,
             errors: Optional[str] = None, newline: Optional[str] = None, closefd: bool = ...) -> IO[Any]: ...
else:
    def open(file: Union[str, bytes, int], mode: str = 'r', buffering: int = -1, encoding: Optional[str] = None,
             errors: Optional[str] = None, newline: Optional[str] = None, closefd: bool = ...) -> IO[Any]: ...
```
So on 3.5, `_PathLike` is not part of the accepted type for the `file` argument, but nevertheless mypy's error mentions `_PathLike`.

**Comment by JelleZijlstra** [comment]
To be clear, this means mypy found a real bug in your code—in Python 3.5, `open` does not accept `Path` objects.

**Comment by sametmax** [comment]
> To be clear, this means mypy found a real bug in your code—in Python 3.5, open does not accept Path objects.

Well not really. The code is Python 3.6. It just happens that mypy was installed with "python3.5 install --user mypy". 
Now I didn't realize that, and I'm pretty sure a lot of people won't. I have 6 versions of Python installed install on this machine. One other partition with more, and 2 more laptops. It's quite hard to keep track.
 Maybe we should print some info at the beginning of mypy's output, stating for what version of typing + Python + mypy we are checking against. And add a hook for IDE to get the info.

> So on 3.5, _PathLike is not part of the accepted type for the file argument, but nevertheless mypy's error mentions _PathLike.

Ok so there is some kind of bug. But given my setup, it's probably some weird interaction between all the Pythons stdlib, .local installs and pipsi virtualenvs. So maybe it's just me. Can your reproduce the mistaken  _PathLike mention ?

**Comment by JelleZijlstra** [comment]
You should probably be running mypy with `--python-version 3.6` then.

**Comment by JelleZijlstra** [comment]
And it doesn't repro for me in this setup:
```
$ mypy --python-version 3.5 bin/pathlike.py 
bin/pathlike.py:5: error: Argument 1 to "open" has incompatible type "Union[str, Path]"; expected "Union[str, bytes, int]"
$ mypy --version
mypy 0.550-dev-8895d18df9ee290ef9f872cd16b58fce8aa14824
$ python --version
Python 3.6.1
```

**Comment by gvanrossum** [comment]
The python version used to check against is independent from the Python
version used to run mypy. And the default is 3.6. I don't see a bug here.

**Comment by JelleZijlstra** [comment]
The potential bug is that the error message is incorrect (it talks about PathLike even though there is no PathLike on Python 3.5). But I can't reproduce that bug, so @sametmax any objections to closing this?

**Comment by ilevkivskyi** [comment]
@sametmax 
I am worried about this line in your output:
```
/home/user/.local/lib/mypy/typeshed/stdlib/3.5/pathlib.pyi:15: error: Name 'List' is not defined
```
It looks like you might have a broken installation.

**Comment by gvanrossum** [comment]
Note, `_PathLike` (with `_`) is defined in builtins.pyi for 3.6 only.

**Comment by sametmax** [comment]
@JelleZijlstra: I'm ok with closing it.

However, I'm expected many others to make the same mistake of running mypy with the wrong python interpreter, not realizing how important it is. Maybe we should open another ticket about printing some warning by mypy when not using explicitly "--python-version".

Something like "UserWarning: using mypy without '--python-version', the code will be implicitly checked against the python mypy is installed with: 3.5"

Or make the python version a mandatory positional argument.

Not only it will help people prevent them from making the same mistake that I did (or fix it quickly), but it will also save your time by avoiding other tickets like this one in the future.

**Comment by gvanrossum** [comment]
> "UserWarning: using mypy without '--python-version', the code will be
implicitly checked against the python mypy is installed with: 3.5"

But that's not how it works! What makes you think it works that way? It
defaults to 3.6 regardless what you run to install it.

**Comment by sametmax** [comment]
So it default to the last stable python version that was released when this particular mypy version went out ?
