### ISSUE TITLE
MyPy gives error “Missing return statement” even when all cases are tested

### ISSUE THREAD

**Issue by ostrokach** [python/mypy#4223]
I haven't received any answers to the [following StackOverflow post](https://stackoverflow.com/questions/47149154/mypy-gives-error-missing-return-statement-even-when-all-cases-are-tested), so I thought I'd also post it here. I'm not sure if it's an actual bug or if it's just considered good practice to always have something like `else: raise Exception` at the end of `if / elif ` block.

----

I am getting a MyPy error "Missing return statement", even when I check for all possible cases inside a function.

For example, in the following code, MyPy is still giving me an error `"9: error: Missing return statement"`, even though `color` can only be `Color.RED`, `Color.GREEN`, or `Color.BLUE`, and I test all those cases!

```python
class Color(enum.IntEnum):
    RED: int = 1
    GREEN: int = 2
    BLUE: int = 3


def test_enum(color: Color) -> str:
    if color == Color.RED:
        return "red"
    elif color == Color.GREEN:
        return "green"
    elif color == Color.BLUE:
        return "blue"
```

**Comment by elazarg** [comment]
This code is fragile; if `Color` will change, it will silently break. The right way IMO is to add `assert False` at the end. This will also silence mypy.

To the point, I don't think it's worth the special casing inside mypy. If we'll ever have singleton types, it might be possible to make it work out of the box.

**Comment by ilevkivskyi** [comment]
Just for reference, the relevant section is https://www.python.org/dev/peps/pep-0484/#support-for-singleton-types-in-unions

**Comment by ilevkivskyi** [comment]
I think we can now track this in https://github.com/python/mypy/issues/6366, which is a more general issue.
