### ISSUE TITLE
"Overloaded ... incompatible return types" error when one overloaded argument is a Tuple

### ISSUE THREAD

**Issue by joshstaiger** [python/mypy#4237]
Running mypy (0.550) on the following code:

```python
from typing import overload, Tuple, Any

class A: ...
class B: ...
class C: ...
class D: ...

@overload
def f(x: A) -> B: ...

@overload
def f(x: Tuple[C]) -> D: ...

def f(x: Any) -> Any:...
```

reports:

`error: Overloaded function signatures 1 and 2 overlap with incompatible return types`

I've tried a couple different types for the second overload and so far the error only seems to occur with `Tuple[...]` arguments.  For instance, I don't see the issue if I substitute `def f(x:List[C]) -> D: ...` as the 2nd overload.

**Comment by gvanrossum** [comment]
Yeah, this looks like a bug. I'm not sure where to look. Strangely it perseveres if I use `Tuple[C, C]` or `Tuple[Any]` but it is gone with `Tuple` or `tuple`.

**Comment by elazarg** [comment]
`is_overlapping_types()` does not check for tuple types, and

> We conservatively assume that non-instance, non-union, and non-TypeType types can overlap
any other types.

**Comment by gvanrossum** [comment]
Yeah, still looks like a bug. That comment is not a specification.

**Comment by elazarg** [comment]
Of course.
