### ISSUE TITLE
error: "object" has no attribute "update"

### ISSUE THREAD

**Issue by barrachri** [python/mypy#4239]
with mypy 0.55 and python 3.6

`data` is not annotated.

command
```bash
mypy app.py config.py events utils tests --ignore-missing-imports
```
errors
```bash
events/listener.py:107: error: "object" has no attribute "update"
events/listener.py:113: error: "object" has no attribute "update"
```
code
```python
    data = {
        "content": {
            "from": {
                "name": email_types[type_of_email]['name'],
                "email": email_types[type_of_email]['from']
            },
            "subject": email_types[type_of_email]['subject'],
        },
    }

    text = template.render(event)
    data['content'].update({"text": text})  # line 107

    template_html = env.get_template(
        f'emails/{email_types[type_of_email]["template"]}.html'
    )
    html = template_html.render(event)
    data['content'].update({"html": html})  # line 113
```

**Comment by gvanrossum** [comment]
This is as expected. Mypy tries to infer the type of the "content" dict and finds that t has string key but the value type is the meet of dict and str, and because those two types have nothing interesting in common, it becomes `object`.

**Comment by ilevkivskyi** [comment]
@barrachri 
In such cases an explicit annotation may help. (It is hard to infer the type of such a complex object)

**Comment by barrachri** [comment]
Thanks.

@ilevkivskyi using for example a [TypedDict](http://mypy.readthedocs.io/en/stable/kinds_of_types.html#typeddict)?

**Comment by ilevkivskyi** [comment]
@barrachri Yes, for example ``TypedDict`` may help, I can't help more. You could do it better since you know what your code is _intended_ to do.
