### ISSUE TITLE
Move mypy/git.py and mypy/version.py to a separate module?

### ISSUE THREAD

**Issue by elazarg** [python/mypy#4240]
These files do not seem related to the core functionality of mypy (though I might not understand all their uses).

**Comment by ethanhs** [comment]
git and version are used to provide a nice version for mypy distributions. I don't think they could be moved, unless we don't care about having a `mypy.version.__version__` (which relies on git).

**Comment by gvanrossum** [comment]
`__version__` is needed my `mypy -V`.
