### ISSUE TITLE
Mypy not detecting __dict__ ?

### ISSUE THREAD

**Issue by ruissalo** [python/mypy#4242]
Hi,

According to https://github.com/python/mypy/issues/1405 this should be fixed so I'm not sure if this is still an issue. Using the latest version from github I get the same error:

python3 -m pip install -U git+git://github.com/python/mypy.git

mypy --py2 helpers/utils.py --ignore-missing-imports

something/something.py:33: error: "MyObj" has no attribute "__dict__"

Thanks

**Comment by ilevkivskyi** [comment]
I can reproduce this only in Python 2 mode indeed. Maybe we can just apply the Python 3 fix, but I don't know well Python 2 to say for sure.

**Comment by gvanrossum** [comment]
If we're okay with adding `__dict__` to `object` in Python 3 then we should
be okay with it in Python 2 as well. It may not actually exist (if you use
`__slots__` or if it's a builtin class) but that same problem didn't stop
us for Python 3.

**Comment by ethanhs** [comment]
https://github.com/python/typeshed/pull/1746 once merged will fix this, so closing (its a typeshed issue anyway).
