### ISSUE TITLE
Incompatible signature with supertype

### ISSUE THREAD

**Issue by Gr1N** [python/mypy#4250]
Hi,

I'm new with typing in Python and stuck with `Signature of "update" incompatible with supertype "MutableMapping"`. 

Here is my code:
```
from collections import MutableMapping
from typing import (
    Any,
    Hashable,
)


class FrozenDict(MutableMapping):
    __slots__ = (
        '_frozen',
        '_items',
    )

    def __init__(self, *, items: dict = None) -> None:
        self._frozen = False
        self._items = items or {}

    def __getitem__(self, key: Hashable) -> Any:
        return self._items[key]

    def __setitem__(self, key: Hashable, value: Any) -> None:
        self.assert_frozen()
        self._items[key] = value

    def __delitem__(self, key: Hashable) -> None:
        self.assert_frozen()
        del self._items[key]

    def __len__(self) -> int:
        return len(self._items)

    def __iter__(self) -> Any:
        return iter(self._items)

    @property
    def frozen(self) -> bool:
        return self._frozen

    def assert_frozen(self) -> None:
        if self._frozen:
            raise RuntimeError('Cannot modify frozen dict')

    def freeze(self) -> None:
        self._frozen = True

    def update(self, items: dict) -> None:
        self.assert_frozen()
        self._items.update(items)

```

I'm trying to google and know that it violates the Liskov Substitution Principle. I don't want to use `# type: ignore`. But I want to understand is there are another option to write correct signature for my `update` method or I'm doing code in wrong way?

Thanks

**Comment by JukkaL** [comment]
The base class definition of `update` is in typeshed: https://github.com/python/typeshed/blob/master/stdlib/3/typing.pyi#L344. To avoid the error, you need to use an overloaded definition that is compatible with the base class definition.

**Comment by Gr1N** [comment]
@JukkaL could you please provide an example?

**Comment by JukkaL** [comment]
Maybe something like this (didn't verify it):

```py
    @overload
    def update(self, __m: Mapping, **kwargs: Any) -> None: ...
    @overload
    def update(self, __m: Iterable[Tuple[Any, Any]], **kwargs: Any) -> None: ...
    @overload
    def update(self, **kwargs: Any) -> None: ...

    def update(self, *args, **kwargs):
        <here comes the actual implementation>
```

To satisfy Liskov, you'll need to update the implementation to handle keyword arguments.

**Comment by Gr1N** [comment]
But I don't want to allow `kwargs` in signature...

**Comment by JelleZijlstra** [comment]
Well, then you gave yourself two incompatible constraints. MutableMapping allows something like `instance.update(a=1, b=2)`. You need to either allow that or break LSP and `# type: ignore` your override.

**Comment by Gr1N** [comment]
Understand, I will change my code. Thanks
