### ISSUE TITLE
feature request: differentiate parsing from typing failures

### ISSUE THREAD

**Issue by bwo** [python/mypy#4254]
Currently, failures encountering in parsing are reported the same way as errors encountered in the type-checking phase: the output format is the same and the exit code is the same.

I would like to be able to discriminate between these cases—either by being able to invoke mypy in a parse-only mode prior to doing the full run, or by exiting with a different non-zero error code, or by including some annotation indicating a parse failure in the error line (this seems like the worst option technically, but would likely be easiest to do).

Motivation: we have a large codebase to which we'd like to introduce types, and we'd like to run mypy as part of our tests. Running mypy right now gives many, many errors, which it would be a herculean effort to get to zero before making mypy failures a blocking test failure. So, we would like to make sure that the number of type errors at least never increases, by counting the lines of output. Since a single syntactic or arity error (or any of the other errors that can trigger a failure in parsing) will drastically reduce the number of reported errors, we want to be able to detect specifically this case, ideally more robustly than checking the output against strings like "too few arguments". (Also, it strikes me that as these are very different kinds of failures they should be more easily distinguishable in general.)

I'm willing to work on this if it's considered desirable in general and some one approach is preferred.

**Comment by JelleZijlstra** [comment]
We recently added a flag `--semantic-analysis-only` that is similar to what you are asking for, although semantic analysis is a slightly later stage than parsing. Does that work for you?

**Comment by bwo** [comment]
Probably! Is that out already in 0.550?

**Comment by JelleZijlstra** [comment]
I think so, but it's undocumented. It was added in #4188.

**Comment by bwo** [comment]
this does work, but something that did parsing *only* would still be nice, since running with `--semantic-analysis-only` when there are no syntactic errors still takes 30 seconds. Running the full analysis takes 3 minutes, though, so this is definitely feasible as a first pass. Thanks.

**Comment by gvanrossum** [comment]
I've long wanted two improvements to mypy's handling of "blocking errors"
(which include syntax errors and a few others):

1. If a blocking error occurs use exit status 2 (same as for command line
argument parsing errors)
2. Keep going looking for blocking errors in other files rather than
stopping at the first file with a blocking error

For (2) it should just stop doing the type checking for the remaining files.

**Comment by bwo** [comment]
actually on thinking about it some more `--semantic-analysis-only` isn't really appropriate: I don't want to fail fast on everything it catches, only on blocking errors. Exit status 2 would be ideal.

**Comment by bwo** [comment]
correct me if I'm wrong but I think this is now implemented?

**Comment by ethanhs** [comment]
Yes this has been done. Thank you for pointing it out @bwo !
