### ISSUE TITLE
error: "Type[Sequence[Any]]" has no attribute "register"

### ISSUE THREAD

**Issue by mitar** [python/mypy#4258]
I am trying to register Pandas dataframe as a Sequence:

```python
import pandas  # type: ignore
import typing
typing.Sequence.register(pandas.DataFrame)
```

MyPy returns the following error:

```
error: "Type[Sequence[Any]]" has no attribute "register"
```

But the code works because `Sequence` is an abstract class as well. So I think MyPy is confused in this case and the error is invalid.

**Comment by ilevkivskyi** [comment]
This may be just a typeshed problem, since it looks like ``Sequence`` (and many other ABCs) is not an instance of ``ABCMeta`` in typeshed.

**Comment by gvanrossum** [comment]
Also, a register() call isn't going to tell mypy anything -- it won't infer
statically that DataFrame is a Sequence (if that's what you're after).

**Comment by mitar** [comment]
Oh, it won't? Yes, this is what I was after (beyond also making it work with `isinstance`).

Is there a better way to define this then?

**Comment by gvanrossum** [comment]
You have to write a stub for Pandas where it does inherit from Sequence.

**Comment by ethanhs** [comment]
I wasn't able to repro the example error on master, 0.550, or 0.520. @mitar are you passing any flags when checking this code?

**Comment by ethanhs** [comment]
Closing as unable to repro and if this is an issue, it is as Ivan said, likely in typeshed.

**Comment by mitar** [comment]
I also cannot reproduce this, so I agree. Maybe it was some older Python version.
