### ISSUE TITLE
Verbosity about which branch for "missing return statement" error

### ISSUE THREAD

**Issue by dbr** [python/mypy#4269]
In the process of upgrading from mypy 0.4.6 to mypy 0.550.

With the new version, it is (correctly) producing these errors:
```
test.py:3: error: Missing return statement
test.py:9: error: Return value expected
```
..for this code:
```python
from typing import Optional, List, Any, Set

def _example(node):
    # type: (str) -> Optional[List[str]]
    if node in ["N1", "N2"]:
        return ["a", "b"]

    elif node in ["N2"]:
        return

    # elif [...and a bunch more...]

    elif node in ["N4"]:
        [...]
        if node:
            return ["a"]

    else:
        return None
```

The "Return value expected" error was obvious to fix (should be `return None` instead of bare `return`)

The `Missing return statement` however was difficult to spot in the longer function (which contains some other branching elsewhere).

It would be useful if the error could help narrow down which branch is missing a return, something like

`test.py:3: error: Missing return statement (from branch started on line [...])"`

**Comment by dbr** [comment]
...actually, having just posted this, I realised this may be an impossible feature to implement (as it'd involve MyPy magically knowing which branches I intended to return from..?)

**Comment by elazarg** [comment]
A missing return statement is always in the last line of the function
