### ISSUE TITLE
Check coulmn numbers in existing tests

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4276]
There are few tests that check column numbers of errors. I think it makes sense to update more existing tests to check them. Also, maybe we can additional "visual" format to simplify testing this, for example:
```
[case testArgColumn]
def func(arg: int) -> int:
    pass
func('whatever')  # E: Argument 1 to "func" has incompatible type "str"; expected "int"
     ^
[out]
```
(By the way currently it points to 0-th column, which is not optimal IMO.)

**Comment by gvanrossum** [comment]
Generally agreed. It's just that very few people care about column numbers, and even for those who do, the cases where without column numbers it's hard to diagnose an error is rare -- whereas whenever the line number is missing it's a terrible experience.

> (By the way currently it points to 0-th column, which is not optimal IMO.)

Not sure what you mean by this.

**Comment by ilevkivskyi** [comment]
@gvanrossum 
> It's just that very few people care about column numbers

One possible use case for column numbers is for IDEs that would highlight mypy errors. It would be nice to see e.g. a particular argument highlighted, instead of a whole function call.
> Not sure what you mean by this.

In the above example, if I use ``--show-column-numbers``, then mypy says:
```
tst.py:3:0: Argument 1 to "func" has incompatible type "str"; expected "int"
```
I would prefer this to be (note column) 
```
tst.py:3:6: Argument 1 to "func" has incompatible type "str"; expected "int"
```

**Comment by JukkaL** [comment]
We've added more tests for column numbers and fixed various issues with column number reporting.
