### ISSUE TITLE
In Python 2 mode, default relative import isn't implemented

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4289]
Consider a package `a` with three files:
```py
# __init__.py
# empty
```
```py
# sys.py
version = 0.0
```
```py
# foo.py
from sys import version
print(version)
reveal_type(version)
```
When we run `foo.py` with Python 3 (`python3 -m a.foo`), this ignores `a/sys.py` and prints the true `sys.version` (from the stdlib module). But when run with Python 2, the import is resolved relative to the package first, and finds `sys.py`, and prints `0.0`. That's not nice, but it's how Python 2 works. You can avoid it by adding `from __future__ import absolute_import`.

But mypy doesn't know about this quirk of Python 2, and in Python 2 mode reveals the type of `version` to be `str` (i.e. the type of the stdlib `sys.version`) rather than `float`.

We should implement this behavior (except when `from __future__ import absolute_imports` is present in a module). We might also have a flag that warns about such imports, since in large codebases they sometimes sneak in accidentally.

**Comment by hauntsaninja** [comment]
What is Python 2?
