### ISSUE TITLE
typing an init parameter causes wrong argument calculation

### ISSUE THREAD

**Issue by mckaysalisbury** [python/mypy#4290]
I've got a class which has a method that creates instances of the class.

    class Bar:
        @classmethod
        def create(cls, foo: int):
            return cls(foo)

        def __init__(self, foo: int) -> None:
            pass

When I run mypy against it, it says `mypytest.py:4: error: Too many arguments for "Bar"`

It seems like a bug to me, because this works fine

    class Bar:
        @classmethod
        def create(cls, foo):
            return cls(foo)

        def __init__(self, foo: int) -> None:
            pass

I don't understand why a class method which defines the type of a parameter should break the creation of an instance.

(see https://stackoverflow.com/q/47493293/8384 )

**Comment by gvanrossum** [comment]
This is because mypy processes definitions in order, and when it comes across `create()` in the first version it hasn't seen the `__init__()` signature yet. IIRC there's another issue open for this.

**Comment by JelleZijlstra** [comment]
Yes, this is #1727.

**Comment by mvoitko** [comment]
The same problem remains with SQLAlchemy models.
