### ISSUE TITLE
Mypy reports error "Cannot assign to a method" when using tkinter report_callback_exception

### ISSUE THREAD

**Issue by jcrmatos** [python/mypy#4298]
Hello,

When mypy sees tkinter exception handling like this
`root.report_callback_exception = mainloop_exc_handler`
where mainloop_exc_handler is a function or method to handle exceptions under tkinter mainloop, it reports the error "Cannot assign to a method".

I'm using mypy 0.521 with Python 3.5.4 32b on a Windows 7 SP1 x64.

Best regards,

JM

**Comment by elazarg** [comment]
Sounds like a typeshed issue

**Comment by jcrmatos** [comment]
Should I open the issue there?

**Comment by elazarg** [comment]
I believe so. The method defined [here](https://github.com/python/typeshed/blob/master/stdlib/3/tkinter/__init__.pyi) and there's no hint the it is an appropriate assignment target (should probably be a Callable field, assuming it meant to be assigned to and not overridden)

**Comment by elazarg** [comment]
I didn't find any evidence that this method should be assigned to, though.

**Comment by gvanrossum** [comment]
Hm, mypy treats methods specially, I wouldn't be so quick to claim this can
be solved in typeshed (though if you find a fix there please don't be shy).

**Comment by ilevkivskyi** [comment]
We already have an old issue https://github.com/python/mypy/issues/708 for this (note also the label "size-large"). I think we can close this one as a duplicate.
