### ISSUE TITLE
Better message for nested TypedDict

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4299]
An attempt to define a nested TypedDict results in a not very helpful message:

```py
from mypy_extensions import TypedDict

D = TypedDict('D', {
    'x': TypedDict('E', {  # Invalid field type
        'y': int
    })
})
```

A better message could be something like "Inline TypedDict types not supported; use assignment" statement to define a TypedDict".

**Comment by GuSuku** [comment]
Inlining seems to be supported now. Can close.

**Comment by FreCap** [comment]
@GuSuku do you mean that this should be supported now?
I tried to run it in MyPy but it still gives me the same error: 

MyPy Playground:
https://mypy-play.net/?mypy=latest&python=3.9&gist=29faabf0dd252d7772d2d9e01e8ce5a4
