### ISSUE TITLE
Document how to silence flake8 etc. using # noqa

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4305]
This is a common issue for people using type comments:

```py
from typing import List  # Linter complains about unused import
a = []  # type: List[int]
```

`# noqa` helps with flake8 (and maybe other linters):

```py
from typing import List  # noqa
a = []  # type: List[int]
```

Document this is common issues.

**Comment by JukkaL** [comment]
This came up in #4302 most recently but has been a common issue at Dropbox as well. At Dropbox we have custom lint hacks to make linters not complain about imports only used within type comments, but they aren't publicly available, as far as I know.

**Comment by tjerkw** [comment]
@JukkaL  how did you fix it at dropbox? Is there something out there we can use? I dislike the #noqa comments in the code.

**Comment by JukkaL** [comment]
@tjerkw I didn't work on that fix, but I have a vague recollection about adding a linter pass that looks for type comments and adds dummy references to every name used in a type comment to the end of the source file before actual linting. @gvanrossum may know more.
