### ISSUE TITLE
mypy can't infer the type of set()

### ISSUE THREAD

**Issue by warsaw** [python/mypy#4309]
With this code (in bar.py):

```python
x = set()
```

This happens

```
$ mypy bar.py
bar.py:1: error: Need type annotation for variable
```

**Comment by gvanrossum** [comment]
Yeah, that's by design. If you add something it will usually infer a type from that:
```py
x = set()
x.add(1)
reveal_type(x)
```
Reveals the type as `builtins.set[builtins.int]`.

**Comment by ilevkivskyi** [comment]
This is not a bug. We don't want to infer ``Set[Any]`` unless a user specifies this. There is a proposal to add a "lenient" mode, where this would be allowed https://github.com/python/mypy/issues/3507
