### ISSUE TITLE
Automatic conversion of type annotations

### ISSUE THREAD

**Issue by xoviat** [python/mypy#4310]
When existing code (compatible with Py2/3) drops support for Python 2, it would be nice to have mypy automatically convert old-style annotations to new-style annotations (with an optional flag). This would literally be moving the typing tokens into the functions.

Or maybe this should go into a separate tool?

**Comment by JelleZijlstra** [comment]
I think you want https://github.com/ilevkivskyi/com2ann.

**Comment by xoviat** [comment]
Nice!
