### ISSUE TITLE
Add import hints for errors like 'Any' undefined

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4317]
If new users forget to import `Any`, `List` or similar, it could be useful to add a hint such as this:

```
x.py:20: error: Name "Any" undefined
x.py:20: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Any")
```

We could do this for some common stdlib functionality as well, such as `collections`, `subprocess`, `re`, etc.

Even better, mypy could also give import hints for some user-defined classes and functions (that have unique definitions).

**Comment by gvanrossum** [comment]
Maybe also if they misspell it as `any`.

**Comment by cs-cordero** [comment]
I'm taking a look at this.

**Comment by ilevkivskyi** [comment]
The top five imported names are:
* `Optional`
* `Tuple`
* `Union`
* `Callable`
* `Any`
