### ISSUE TITLE
Optional strict checking of isinstance checks

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4332]
The current semantics of `isinstance` checks make some assumptions about inheritance, such as there being no multiple inheritance from certain classes. This is probably reasonable as a default, since it makes easier to annotate legacy codebases. However, we could provide an option to have safer and stricter checking of `isinstance` checks. The exact behavior of this mode is still not quite clear.

See discussion in #3605 for further context.

**Comment by ilevkivskyi** [comment]
Just for the reference here is the previous proposal https://github.com/python/mypy/issues/3603#issuecomment-311370857

**Comment by msullivan** [comment]
I don't think this meets the bar of adding a new flag and we're moving towards more intersection stuff
