### ISSUE TITLE
Optional strict checking of overloads

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4333]
Currently the type checking of overloads is unsafe. We could potentially make them safe through a configuration option, at the cost of some flexibility.

#4332 is a similar idea for `isinstance` checks, and some of the discussion there is also relevant here.

**Comment by ilevkivskyi** [comment]
Btw, now the overload treatment is much more strict than it used to be, so I am not sure such flag would be valuable now.

**Comment by JukkaL** [comment]
This flag doesn't seem worth it any more. @Michael0x2a's work on overloads has fixed some of the biggest issues, in particular.
