### ISSUE TITLE
Update docs to reflect the fact that Iterable etc. are now protocols

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4339]

**Comment by JukkaL** [comment]
@ilevkivskyi I'm working on this.

**Comment by ilevkivskyi** [comment]
OK, great! Note that I initially had some docs about this in the protocols PR, the section "Predefined protocols in typing module" was removed in https://github.com/python/mypy/pull/3132/commits/713db0ca5dd51913eda10785049d8b840259f24a you can take some text from there.

Sorry, I had not have time recently to work on these issues.
