### ISSUE TITLE
Var.is_ready remains false in some cases after type checking

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4346]
Example:
```py
a = 1 + 1
```
After typechecking, the Var representing `a` has is_ready still False. This currently affects the interface hash which is used to determine whether dependent modules need to be re-checked, so that when we change this to
```py
a = 2
```
or to
```py
a = 1 + 1  # type: int
```
(both of which set is_ready to True) all dependent modules end up being rechecked.

One fix would be to ignore this and just remove is_ready from Var.FLAGS (so it won't be serialized and hence won't affect the interface hash) but that might hide a latent error somewhere.

**Comment by AlexWaygood** [comment]
Any idea if this is still a problem, @gvanrossum? :)

**Comment by gvanrossum** [comment]
I have no way of checking anymore.
