### ISSUE TITLE
mypy can't find type defined inside a function.

### ISSUE THREAD

**Issue by asincero** [python/mypy#4349]
### Steps to reproduce

mypy can't seem to find a class defined inside a function.  For example:

```python
import typing

def foo() -> typing.Any:
    class Bar(typing.NamedTuple):
        member: str

    o = Bar(member='fee')
    return o
```

### Current behavior

I get the following when I run mypy on the above code (saved in a file named "t1.py"):

t1.py:4: error: Name 'Bar' is not defined
t1.py:7: error: Missing positional arguments "typename", "fields", "verbose", "rename", "kwargs" in call to "Bar"

### Expected behavior

No errors or warning from mypy.

### mypy --version output

mypy 0.540

**Comment by gvanrossum** [comment]
Good catch. It appears subclassing NamedTuple is only recognized at the module level, not inside a function. So your workaround would be to move Bar up to the module level.

**Comment by ilevkivskyi** [comment]
...or you can just use (less nice) functional form ``Bar = NamedTuple('Bar', [('member', str)])`` which works correctly.

This means that this bug should be easy to fix.

**Comment by gvanrossum** [comment]
My guess is the bug has to do with some pass not descending into function bodies. We've seen such errors before.

**Comment by elliott-beach** [comment]
There's a TODO referencing this specifically: https://github.com/python/mypy/blob/105b78e518f28903d5ff454d55a6fbb1326c70ca/mypy/semanal.py#L2297-L2300

**Comment by solomatov** [comment]
Are there any updates on this? 
I still have it in 0.660

**Comment by momohatt** [comment]
This doesn't reproduce in 0.782. Maybe it's already fixed?

**Comment by 97littleleaf11** [comment]
I cannot reproduce it in latest version. Seems it had been fixed.
