### ISSUE TITLE
mypy.ini is completely ignored if there is a duplicate section

### ISSUE THREAD

**Issue by CommanderPrS** [python/mypy#4350]
If the mypy.ini has duplicate sections (even if they are identical), mypy prints a warning error and, what is more important, **COMPLETELY** ignores the entire file. This means that if there are any black-listed modules, they start generating errors again and all type checking tests fail.

Just in case it matters, the specific example that I saw was this (although the duplicate sections were not next to each other). It is probably the same for other duplicates as well.

```
[mypy-foo.*]
ignore_errors = True

[mypy-foo.*]
ignore_errors = True
```

**Comment by gvanrossum** [comment]
What was the specific error you got?

**Comment by CommanderPrS** [comment]
> What was the specific error you got?

If you are asking about the duplicate section error, then it was this:

```
While reading from '.../mypy.ini' [line ...]: section 'mypy-foo.*' already exists
```

If you are asking about the errors that were generated after the content of `mypy.ini` was ignored, then those were regular type checking errors. Basically, if a module was black-listed due to some typing issues, then all those issues were printed according to whatever problem they were referring to, missing attributes, wrong types, etc.

**Comment by gvanrossum** [comment]
Oh, that error comes from configparser (the stdlib module we use to parse mypy.ini). It raises an exception and mypy doesn't get to see any of the contents of the file at all. So this is expected and we don't intend to fix this, sorry.
