### ISSUE TITLE
In TypedDictMeta, base classes override annotations in the current class

### ISSUE THREAD

**Issue by mitar** [python/mypy#4354]
[Looking at the code](https://github.com/python/mypy/blob/master/extensions/mypy_extensions.py#L62), it seems that the base classes override the annotations from the current class. I think this is the opposite of what MRO and expectations would be.

**Comment by ilevkivskyi** [comment]
It doesn't really matter since trying to override a ``TypedDict`` key is a static error. The subclassing syntax exists to extend/merge ``TypedDict``s, _not_ to override keys (I think the [docs](http://mypy.readthedocs.io/en/latest/kinds_of_types.html#class-based-syntax) are clear on this):
```python
class A(TypedDict):
    x: float

class B(A):
    x: int  # E: Cannot overwrite TypedDict field "x" while extending
```

**Comment by gvanrossum** [comment]
Even stronger you cannot repeat yourself either; if `B` had `x: float` it would still get the same error.
