### ISSUE TITLE
Port Python 3 'os' and 'os.path' stubs to Python 2

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#437]
There are no Python 2 stubs for `os` and `os.path`. The Python 3 variants should mostly be suitable after changing `str`/`bytes` to suitable Python 2 equivalents (`unicode`/`str`), but I remember that there might be some new definitions in the Python 3 stubs not present in Python 2 (can't remember exactly what, though).

First complete #436 and #435, which will simplify the process.

**Comment by Naruto0** [comment]
I think there already are stubs for os module in 2.7

**Comment by gvanrossum** [comment]
Oooh, this is way out of date. Thanks for the reminder!
