### ISSUE TITLE
Add tests that are expected to fail

### ISSUE THREAD

**Issue by elazarg** [python/mypy#4377]
Pytest supports `xfail`:
> A **xfail** means that you expect a test to fail for some reason. A common example is a test for a feature not yet implemented, or a bug not yet fixed. When a test passes despite being expected to fail (marked with `pytest.mark.xfail`), it’s an **xpass** and will be reported in the test summary.

It might be nice to add a `-fail` (similar to `-skip`) option to the tests, so "accidentally" fixing them will be noticed. These tests can be added immediately when an issue is reported.

**Comment by 97littleleaf11** [comment]
Fixed by https://github.com/python/mypy/pull/10635
