### ISSUE TITLE
Port Python 3 'time' stubs to Python 2

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#438]
There are no Python 2 stubs for the `time` module. It should be straightforward to port the Python 3 stubs to Python 2.

First refactor the Python 3 stubs: https://github.com/JukkaL/mypy/issues/434

**Comment by Naruto0** [comment]
Yes, there already is some "uncredited" stub file. I would recomend to remove old stub issues, as there is typeshed repository. And if somebody could label some of them "easy" that would be awsome too. As long as i'm beginner, it's easier and faster for me to build upon something on my level..

**Comment by gvanrossum** [comment]
Thanks again for helping with spring cleaning!

**Comment by Naruto0** [comment]
You're welcome. It was labeled easy.. so it was.
