### ISSUE TITLE
Install Mypy with --prefix

### ISSUE THREAD

**Issue by shoud** [python/mypy#4380]
Hello,

I want to install Mypy v0.550 in an external folder with this command (I use Python 3.6): 
`python -m pip install -U mypy --prefix=[PATH]/MYPY_test/mypy`
Then I add mypy in PYTHONPATH:
`export PYTHONPATH=[PATH]/MYPY_test/mypy/lib/python3.6/site-packages/mypy:$PYTHONPATH`
But when I launch Mypy, there is a AttributeError:

> Traceback
> 
>  (most recent call last):
>   File "./mypy", line 4, in <module>
>     import re
>   File "[PATH]/Python/Python3.6.2/lib/python3.6/re.py", line 122, in <module>
>     import enum
>   File "[PATH]/Python/Python3.6.2/lib/python3.6/enum.py", line 2, in <module>
>     from types import MappingProxyType, DynamicClassAttribute
>   File "[PATH]/MYPY_test/mypy/lib/python3.6/site-packages/mypy/types.py", line 3, in <module>
>     import copy
>   File "[PATH]/Python/Python3.6.2/lib/python3.6/copy.py", line 115, in <module>
>     types.BuiltinFunctionType, type(Ellipsis), type(NotImplemented),
> AttributeError: module 'types' has no attribute 'BuiltinFunctionType'
> 
Mypy and Python both have a file named "types.py". How can I avoid this error?

**Comment by ethanhs** [comment]
You should not add site-packages to your PYTHONPATH while using mypy. Wouldn't a virtualenv suit your needs?

**Comment by shoud** [comment]
Tank you. 
Effectualy I added in the PYTHONPATH:
`export PYTHONPATH=[PATH]/MYPY_test/mypy/lib/python3.6/site-packages/mypy:$PYTHONPATH`

And not just the site-packages folder: 
`export PYTHONPATH=[PATH]/MYPY_test/mypy/lib/python3.6/site-packages:$PYTHONPATH`

Use a virtualenv is a good idea.

**Comment by alenwesker** [comment]
Add this lines to the front of subgen.py also solve the problem

import sys
sys.path = sys.path[1:]

Just remove the current directory in the sys.path. 

Why using a file named types.py???!!!  It will keep conflict with the one in the python libs.
