### ISSUE TITLE
Make fine-grained incremental mode resilient to concurrent FS updates

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4391]
Currently the fine-grained incremental mode may access the same file system state multiple times during a single update, which could result in unpredictable results if there are concurrent file system updates during a build. At the very least it makes it hard to reason about correctness. A known example is doing `os.path.isfile` multiple files for a path in `mypy.server.update` -- and the current daemon prototype (not merged yet) also stats files in the daemon.

Ultimately it would be a nice property if fine-grained incremental mode was resilient to arbitrary concurrent file system updates. If the file system changes in the middle of an update, the results for that update might be unpredictable, but the next update should return mypy into a consistent state, assuming there are no more concurrent file system changes.

A potential, better approach would be to only read any state information at most once during an update, and ensure some ordering properties such as "always read the mtime of a file before reading the contents". Tricky bits include a file being deleted after we've noticed that it exists. 

Here is a strawman idea:
* Provide a single FS abstraction that implements whatever consistency properties we want in an encapsulated fashion instead of spreading the FS access code out across multiple places.
* Use the FS abstraction everywhere to access the FS instead of the `os` module, for example.
* At the beginning of a build decide what FS state has changed before actually doing any real work. Also read the contents of any changed files at this point. The goal is that after the initial FS scan the rest of the build will only access cached FS state (provided by the FS abstraction layer).

Whatever approach we choose we should ensure that it can be adapted to work with an implementation that uses file system events to detect which files have changed instead of just stat()ing files or doing a full directory tree traversal.

**Comment by msullivan** [comment]
I think we did this
