### ISSUE TITLE
Add better tests for various mypy features + fine-grained incremental mode

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4392]
These features don't have good (or any) test coverage (but they are expected to work to a certain extent):

- [x] `# type: ignore`
- [x] Partial types
- [x] Semantic analysis 3rd pass (and the "patching" pass)
- [x] Handle change of the kind of a definition in a symbol table (e.g. class -> module)
- [x] `NewType`
- [x] `TypedDict`
- [x] Nested classes
- [x] Nested functions
- [x] Overloaded functions
- [x] Strict optional (including per-file)
- [x] Decorators
- [x] `__new__`
- [x] Protocols
- [x] Metaclasses
- [x] Enums
- [x] Type variables 
- [x] Generic callables
- [x] Named tuples

**Comment by ilevkivskyi** [comment]
Everything from this list is implemented, so this can be closed now.
