### ISSUE TITLE
Unsupported type Type

### ISSUE THREAD

**Issue by mitar** [python/mypy#4405]
For the following program:

```python
import typing

T = typing.TypeVar('T')
L = typing.TypeVar('L', bound='List')

class List(typing.List[T]):
    def __init__(self, iterable: typing.Iterable = ()) -> None:
        super().__init__(iterable)

    def copy(self: L) -> L:
        return type(self)(self)
```

I get the following error:

```
test.py: error: Unsupported type Type["L"]
```

mypy 0.560

I do not see why it here an error?

**Comment by ilevkivskyi** [comment]
This is essentially a duplicate of https://github.com/python/mypy/issues/4300 modulo ``Tuple -> List``. Could you please copy your repro there, and close this one?

**Comment by mitar** [comment]
Copied. I am not sure if it is the same though.
