### ISSUE TITLE
mypy error regarding namedtuple

### ISSUE THREAD

**Issue by kdheepak** [python/mypy#4414]
I have the following code

```python
# status.py

from collections import namedtuple

dict_store = {
    "error": 1,
    "success": 0,
}

Status = namedtuple("NamedClass", dict_store.keys())

status = Status(**dict_store)

```

mypy throws the following errors. 

```
status.py:43: error: List or tuple literal expected as the second argument to namedtuple()
status.py:45: error: Incompatible types in assignment (expression has type "namedtuple", variable has type "Dict[str, int]")
status.py:45: error: Too many arguments for "namedtuple"
```

Is this expected behavior?

**Comment by ethanhs** [comment]
There are a few things going on.
First, you are not passing a literal to namedtuple, thus mypy has no way of inferring attributes of the namedtuple. You probably want to look at `typing.NamedTuple` as a better way to define namedtuples.
Second, your example is incomplete (please give minimal reproducible examples in future). Status is probably defined already before line 45, and thus the second error is thrown.
The third is because of the first- since mypy doesn't know how many attributes has, it doesn't know how many arguments the initializer takes.

**Comment by kdheepak** [comment]
Hi @ethanhs. Thanks for the swift reply. Yes you are correct, the second error is perhaps because of another reason.

Below is the log if I paste the above snippet into a separate file.

```
status.py:8: error: List or tuple literal expected as the second argument to namedtuple()
status.py:10: error: Too many arguments for "namedtuple"
```

I wanted to ensure this code would run in python 2.7, which is why I can't use typing at the moment. 

```python
from collections import namedtuple

Status = namedtuple("NamedClass", ["error", "success"])
status = Status(**dict(error=1, success=0))
```

Is there a way to tell mypy to ignore this error if there are keyword arguments passed to the namedtuple when it is not able to infer the arguments?

**Comment by ethanhs** [comment]
The following works:
```
from collections import namedtuple

Status = namedtuple("NamedClass", ["error", "success"])
status = Status(error=1, success=0)
```
I'm not sure why you keep using a dict, but if you really must for some other requirement,
```
from collections import namedtuple
dict_store = {
    "error": 1,
    "success": 0,
}
Status = namedtuple("NamedClass", dict_store.keys())  # type: ignore
status = Status(**dict_store)  # type: ignore
```

**Comment by kdheepak** [comment]
Thanks! To clarify, I have a large json file that I expect will change as the program evolves, and would like to make namedtuples from the data.

**Comment by AlexTereshenkov** [comment]
@kdheepak take a look at this https://github.com/brennv/namedtupled - I've been using this successfully to load `json` objects recursively into named tuples

**Comment by torayeff** [comment]
Adding the parameter nae `field_names` gives the `mypy` error `Too many arguments for "Point"`:
```
Point = namedtuple("Point", field_names=["x", "y"])
p = Point(11, 22)
```

The below works fine:
```
Point = namedtuple("Point", ["x", "y"])
p = Point(11, 22)
```

**Comment by dtrckd** [comment]
Hi,

Why mypy throw an error when the field names are passed as a (correctly typed) variable ?

```
cols : list[str] = ["x", "y"]
Point = namedtuple("Point", cols) --> Diagnostic: List or tuple literal expected as the second argument to "namedtuple()" [misc]

```
