### ISSUE TITLE
Invalid type when variable name is the same as the type

### ISSUE THREAD

**Issue by euresti** [python/mypy#4420]
This code:
```
from datetime import date
class A:
    date: date
reveal_type(A.date)
```

Leads to:
```
bar.py:5: error: Invalid type "bar.A.date"
bar.py:8: error: Revealed type is 'date?'
```

One workaround is:
```
import datetime
class A:
    date: datetime.date
reveal_type(A.date)
```
So it's not too bad.

**Comment by ethanhs** [comment]
I believe this is a duplicate of #3775. Essentially, mypy's name resolution rules are slightly different from CPython's, so the class namespace is searched before the global namespace.
