### ISSUE TITLE
Import of Protocol is broken aftre form typing import *

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4427]
This code:
```python
from typing import *
from typing_extensions import Protocol
```
leads to a weird error:
```
Incompatible import of "Protocol" (imported name has type "typing_extensions._SpecialForm", local name has type "typing._SpecialForm")
```

**Comment by elliott-beach** [comment]
This is because `_SpecialForm` is used in both `typing_extensions.py` and

**Comment by elliott-beach** [comment]
This happens because the typing stub exposes a `Protocol` type (https://github.com/python/typeshed/blob/fb2c7b34e27232198b7b742bca93640c5b77c26f/stdlib/3/typing.pyi#L22), even though the actual `_Protocol` class is internal to the typing module (not in `__all__`).

From reading (https://github.com/python/mypy/issues/452) this can be solved by changing the type to `_Protocol` in the stub. Would that work?

**Comment by ilevkivskyi** [comment]
> From reading #452, this can be solved by renaming ``Protocol`` to ``_Protocol`` in the stub, and also in semantic analysis when ``typing.Protocol`` is mentioned. Should I open a PR?

It also appears in several other places, so it will be hard to rename all of them. In addition, this is kind of intentional, as a first step of moving ``Protocol`` to ``typing``. I think a better solution may be to just add a line ``from typing import Protocol as Protocol`` to ``typing_extensions`` stub.

**Comment by mortoray** [comment]
What is the correct workaround to this problem?  I'm doing this now:

```py
from typing import *
from typing_extensions import Protocol #type: ignore
```

**Comment by ilevkivskyi** [comment]
Not using star imports is the best way. Also `Protocol` is in `typing` in Python 3.8, so you will not need the second line. Finally, there is a dirty trick:
```python
from typing import *
if not TYPE_CHECKING:
    from typing_extensions import Protocol
```

**Comment by GPHemsley** [comment]
Is there a way to avoid this error when writing something like the follow?

```Python
# Protocol is only available in Python 3.8+.
try:
    from typing import Protocol
except ImportError:
    from typing_extensions import Protocol
```

**Comment by eblume** [comment]
@GPHemsley I wrote that exact same snippet of code and landed on this page trying to fix the resulting typing error. I'm going to unstick myself by simply adding `# type: ignore` to each of those imports, and check back when my project can move to 3.8 properly.

**Comment by ethanhs** [comment]
@GPHemsley @eblume does using `sys.version_info` checks work? Mypy is better able to reason about things if you use version checks.

**Comment by unmade** [comment]
@ethanhs `sys.version_info` seems to works just fine. Thanks!

**Comment by TonyLHansen** [comment]
As @eblume intimated, this seems to be forward compatible AND eliminates the error message:

```
try:
    from typing import Protocol
except ImportError:
    from typing_extensions import Protocol # type: ignore
```

I did not put the `#type: ignore` on the first import because that one SHOULD be compatible.

Hopefully someone will find this explicit example helpful.

**Comment by hauntsaninja** [comment]
For all the random people landing up on this issue:
```
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol
```

As for the original issue, closing as won't fix. This doesn't happen often, it's tricky to fix the lie in typeshed, the problem will go away on its own next year
