### ISSUE TITLE
Add variable name to "Need type annotation for variable" error

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4431]
It would be nice if the error message "Need type annotation for variable" showed the variable name. This helps the user in case the mypy output was from a slightly outdated version of the file, and in general seems helpful/reassuring.

**Comment by ethanhs** [comment]
This is also useful because if one has:
`a, b = [], []`
mypy only gives
`test.py:1: error: Need type annotation for variable`

**Comment by JukkaL** [comment]
#2463 is related.
