### ISSUE TITLE
Need type annotation for explicitly initialized set

### ISSUE THREAD

**Issue by efimerdlerkravitz** [python/mypy#4435]
For someone who came from statically types languages, mypy is an amazing addition to the python family. Well done !

* Reporting a bug
```
users_to_add = set()  # <-- Getting 'error: Need type annotation for variable'
for group in found_groups:
    members_phone = set([member.readable_identifier for member in group.members.all()])
    logger.info(f'Group {group.name} has these members - {members_phone}')
    shared_members = members_phone.intersection(group_tuple.members_phone)
    if len(shared_members) > best_match_count:
        best_match_count = len(shared_members)
        best_match = group
        users_to_add = members_phone.difference(group_tuple.members_phone)
```
* I'm getting the following error from mypy: `error: Need type annotation for variable` for the first line in code

* I'm expecting no error to appear
* Using `mypy-0.560` with python 3.6. Happens also with the latest from git
* Using the following flags: `mypy --ignore-missing-imports --python-version 3.6 `

**Comment by ilevkivskyi** [comment]
Thank you for the report! Note that mypy sometimes can't determine the type of a variable initialized with an empty collection (this is what it tells you). In such cases you can use an explicit type annotation:
```python
users_to_add: Set[User] = set()
```
or a type comment on older Python versions. For more details, see http://mypy.readthedocs.io/en/latest/common_issues.html#types-of-empty-collections

If you don't have other questions, you can close this issue.

**Comment by efimerdlerkravitz** [comment]
Can'y mypy assume
