### ISSUE TITLE
"if type(x) == T" not being used for type narrowing

### ISSUE THREAD

**Issue by wizzardx** [python/mypy#4445]
Given this code:

```
import random

x = random.randint(1, 4)
if x == 0:
    y = None
elif x == 1:
    y = MyType()
elif x == 2:
    y = MyType2()
elif x == 3:
    y = MyType3()
else:
    assert x == 4
    y = None

if isinstance(y, MyType2):
    reveal_type(y)
    y.b()
```

Then as expected, mypy gives this output:

```
error: Revealed type is 'MyType2'
```

However, if we change this line:

```
if isinstance(y, MyType2):
```

Over to this line:

```
if type(y) == MyType2:
```

Then mypy gives this output:

```
error: Revealed type is 'Union[MyType, builtins.None]'
error: Item "MyType" of "Optional[MyType]" has no attribute "b"
error: Item "None" of "Optional[MyType]" has no attribute "b"
```

But I'd expect that in this case to get the same output as when using isinstance

As a workaround, I currently need to do this:

```
if type(y) == MyType2:
    assert isinstance(y, MyType2)
    reveal_type(y)
    y.b()
```

Which produces the expected mypy output:

```
error: Revealed type is 'MyType2'
```

I shouldn't need to use that workaround.

**Comment by JukkaL** [comment]
Yes, this is something mypy could support better.  Typically the test is written using `is` instead of `==`, but we could support both.

As `isinstance` is usually a better way to perform a runtime type check, and there is a simple enough workaround, this is not high priority.

**Comment by kahee** [comment]
May I try this?

**Comment by b-thebest** [comment]
Should I start working on this ?

**Comment by JelleZijlstra** [comment]
Any of you feel free to submit a PR! All contributions are welcome.

**Comment by basic-programmer-python** [comment]
can I take over this issue as I feel It has been a long time since Its been untouched ...

**Comment by NickHackman** [comment]
If no one else is working on this currently I'll be happy to pick it up. :slightly_smiling_face: 

I must admit though, I have no clue where to start so this may take a while.

**Comment by JelleZijlstra** [comment]
@NickHackman I'd start by looking for how type narrowing with `isinstance()` works (maybe grep for `"builtins.isinstance"`), and then trying to write something similar to make `type()` work.

**Comment by hauntsaninja** [comment]
Linking https://github.com/python/mypy/issues/7260

**Comment by PrasanthChettri** [comment]
Hi is this issue assigned ? , I'd like to take a crack at it's not currently pursued by anybody @JukkaL

**Comment by NickHackman** [comment]
@PrasanthChettri I've been bogged down by other things at the moment. Feel free to take it!

**Comment by JukkaL** [comment]
@PrasanthChettri Sounds good -- nobody seems to be working on this! Feel free to leave questions here if it's unclear what needs to be done.

**Comment by PrasanthChettri** [comment]
Where should I look to find the implementation for this, it would be helpful if someone could narrow it down for me

**Comment by neelsomani** [comment]
I took a peek at this - I think one difference is that `isinstance` is a function that takes both the value + the type to narrow for, while `type(x) == T` is a boolean expression. As someone who's not familiar with the codebase I'm not sure how to proceed from there since it's not a straightforward adaptation of the `isinstance` implementation. Is there a code overview somewhere? Thanks!

**Comment by srbhss** [comment]
Hey @JukkaL @msullivan, I would like to fix this. Please assign this issue to me.
