### ISSUE TITLE
Refactor current fine-grained target tracking

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4452]
Currently `mypy.errors.Errors` has too many responsibilities. Refactor current context and fine-grained dependency target tracking into a separate class, and have `Errors` just hold a reference to a context object. `Errors` shouldn't need to modify the context at all, I think.

Originally proposed in https://github.com/python/mypy/pull/4438#discussion_r160298225.

**Comment by msullivan** [comment]
Done
