### ISSUE TITLE
Question regarding Coroutine vs Awaitable

### ISSUE THREAD

**Issue by ojii** [python/mypy#4460]
Given this code:

```python
from typing import *
from collections import deque

Task = Coroutine[Any, None, Any]
tasks: Deque[Task] = deque()


async def foo() -> None:
    print('foo!')


def add_task(task: Task) -> None:
    tasks.append(task)


def run() -> None:
    task = tasks.popleft()
    try:
        task.send(None)
    except StopIteration:
        pass


add_task(foo())
run()
```

Versions:

```
$ mypy --version
mypy 0.560-51e044c4ecf2a52fc6c41ee63019723e0d3061e1-dirty
$ python --version
Python 3.6.4
```

Running `mypy --strict script.py` I get `script.py:24: error: Argument 1 to "add_task" has incompatible type "Awaitable[None]"; expected "Coroutine[Any, None, Any]"`, but changing `Task` to `Awaitable[None]` gives me `script.py:19: error: "Awaitable[None]" has no attribute "send"`. The code runs fine though.

What would be the proper type hints in this scenario?

**Comment by JelleZijlstra** [comment]
I think this is a bug in mypy. Adding `reveal_type(foo())` to your example gives `bin/coro.py:24: error: Revealed type is 'typing.Awaitable[builtins.None]'`, which I think is wrong; `foo()` returns a Coroutine.

This might be fairly easy to fix—if you are able to, feel free to submit a PR to fix the issue.

**Comment by ojii** [comment]
> This might be fairly easy to fix

The tricky thing is that `Coroutine` takes 3 arguments (like `Generator`) but `Awaitable` only one. How would the send and yield types of `Coroutine` be filled?
