### ISSUE TITLE
Are column numbers base-0 or base-1?

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4475]
IIUC Column numbers (as shown by `--show-column-numbers` are 0-based (as opposed to line numbers, which are 1-based). But in Emacs `*compilation*` mode, it seems column numbers (if present) are interpreted as 1-based, so the cursor is placed one character to the left of the actual error.

Do we know what other tools that understand/use column numbers do?

**Comment by ilevkivskyi** [comment]
Vim also has 1-based column numbering (at least this is what I always see by default on different machines where I work). The same is true for PyCharm. In general my impression is that 1-based column numeration is much more popular among text editors.

**Comment by gvanrossum** [comment]
Let's fix it.

**Comment by elliott-beach** [comment]
I would like to take this if you don’t mind?

**Comment by gvanrossum** [comment]
Go for it!
