### ISSUE TITLE
SMTPHandler typing is incorrect

### ISSUE THREAD

**Issue by pmatos** [python/mypy#4476]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?

Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
sh = SMTPHandler(mailhost=LOG_SERVER,
                 fromaddr=LOG_FROM,
                 toaddrs=LOG_EMAILS,
                 subject=LOG_EMAIL_SUBJECT,
                 credentials=(USER, PASS),
                 secure=())
```

* What is the actual behavior/output?
```
 error: Argument 6 to "SMTPHandler" has incompatible type "Tuple[]"; expected "Union[Tuple[str], Tuple[str, str], None]"
```

* What is the behavior/output you expect?

Passing a `Tuple[]` should be fine. According to the docs:
https://docs.python.org/3/library/logging.handlers.html

> To specify the use of a secure protocol (TLS), pass in a tuple to the secure argument. This will only be used when authentication credentials are supplied. The tuple should be either *an empty tuple,*...

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

Python 3.6.2, mypy 0.560
Haven't tried master.

* What are the mypy flags you are using? (For example --strict-optional)

```
--ignore-missing-imports --follow-imports=skip
```

* If mypy crashed with a traceback, please paste
  the full traceback below.

No crash.

**Comment by gvanrossum** [comment]
(Maybe we should add something to the template about filing such bugs with
typeshed?)
