### ISSUE TITLE
More useful behavior in known-bad fine-grained incremental cases

### ISSUE THREAD

**Issue by msullivan** [python/mypy#4479]
There are a handful of known bugs in fine-grained incremental that are unlikely to be fixed before we start alpha-testing in earnest (such as #4394). When we can detect situations in which we are likely to generate spurious errors, we should do something useful, such as alerting the user or automatically restarting the server.

**Comment by JukkaL** [comment]
Fine-grained incremental checking works well enough now that this doesn't seem important any more.
