### ISSUE TITLE
__annotations__ don't match mypy when Name is already defined

### ISSUE THREAD

**Issue by euresti** [python/mypy#4493]
* Are you reporting a bug, or opening a feature request?
This is more than likely a wont-fix bug but I noticed this discrepancy between what `__annotations__` says vs what mypy thinks are the types.

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```
class A:
    x: int
    x: str  # already defined
print(A.__annotations__)  # {'x': <class 'str'>}
reveal_type(A.x)  # int
```

* What is the behavior/output you expect?
I'd expect reveal_type to be `str`?  Although the already defined might mean all bets are off.  

* What are the versions of mypy and Python you are using?
master

* What are the mypy flags you are using? (For example --strict-optional)
None

**Comment by gvanrossum** [comment]
Ivan, what do you think? IMO this is undefined behavior in both cases; I don't think we want mypy to change here, and changing runtime behavior would also be tricky (an extra check could be added, but it would slow down everything for an error/corner case).

**Comment by ilevkivskyi** [comment]
@gvanrossum 
Ouch, just noticed this issue a year after it was opened. Yes, I think we don't need to change either runtime or mypy behavior.
