### ISSUE TITLE
Fine-grained: Redundant work after git operations

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4499]
Here's an example scenario where mypy daemon does a lot of unnecessary work in fine-grained incremental mode:

* I have daemon running on my git feature branch, and the daemon knows about all my latest changes. 
* I switch to an old branch, do a bit of work there (but don't invoke the daemon).
* I switch back to my original branch and invoke the daemon. 

Now the daemon thinks that a lot of files have changed. Checking out another branch touches file timestamps, and the daemon looks for file changes based on timestamps. However, there are actually no file content changes from the previous daemon update, since I'm back in the original branch. The daemon will process all files with changed timestamps, even though this work is redundant, and it can take a long time for a large codebase. It would be more efficient to recognize that the files actually have no changes and skip processing them.

(This would also work around some unreliability issues, since processing many files often triggers fine-grained incremental bugs.)

Here's an implementation sketch (similar to how the regular incremental mode already works):
* Keep track of file timestamps, sizes and sha1 hashes.
* If the timestamp and the size of a file hasn't changed, assume that it's unchanged (as an optimization).
* If the timestamp or the size of a file has changed, look at the hash of the file to determine if it has actually changed. Update the state of the file (timestamp, size and hash).

**Comment by gvanrossum** [comment]
Yeah, I would totally use the same machinery that the regular cache uses.
It has a function to has a file. FWIW it uses MD5 hashing (speed is more
important than security here).
