### ISSUE TITLE
Support multi-line # type: comments for inline types

### ISSUE THREAD

**Issue by stephenfin** [python/mypy#4511]
#1102 provided a way to split `# type:` comments over multiple lines for functions, however, there doesn't seem to be such a thing to split markup for inline attributes. For example:

```python
import collections
from typing import DefaultDict, List


def test(pools):
    really_long_attribute = collections.defaultdict(list)  # type: DefaultDict[str, List[str]]
    for pool in pools:
        pass  # meaningful stuff in here
```

**Comment by JukkaL** [comment]
Mypy follows PEP 484 in this respect. Changes should be proposed at https://github.com/python/typing/issues.

There are a few things that can help:

1) Define a type alias and use it as the type instead.

2) Split the assignment statement so that there is more space for the type annotation.

3) Declare the variable in a separate assignment statement with a dummy `None` initializer. Example:
```
really_long_attribute = None  # type: DefaultDict[str, List[str]]
really_long_attribute = collections.defaultdict(list)
```

Maybe we should add this to common issues in mypy documentation?

**Comment by stephenfin** [comment]
> Mypy follows PEP 484 in this respect. Changes should be proposed at https://github.com/python/typing/issues.

@JukkaL Thanks for the tip. I'll open the issue there shortly.

> Maybe we should add this to common issues in mypy documentation?

Yes, please. The way I've worked around this for now is by escaping the newline. However, this is ugly and should be unnecessary.

```python
def test(pools):
    really_long_attribute = collections.defaultdict(list) \
    # type: DefaultDict[str, List[str]]
    for pool in pools:
        pass  # meaningful stuff in here
```

**Comment by stephenfin** [comment]
Reported in python/typing#534

**Comment by gvanrossum** [comment]
Actually escaping the newline is a perfectly reasonable solution and avoids
the ambiguity of putting the type comment on a separate line (someone not
familiar with this convention might wonder if it applies to the previous
line or to the next).

**Comment by cristicbz** [comment]
Escaping the newline is not really a solution if the type signature by itself doesn't fit on one line though.

**Comment by cwhy** [comment]
> Escaping the newline is not really a solution if the type signature by itself doesn't fit on one line though.

Agree. In a lot of cases, the type signature would be very long, especially with Callables.

**Comment by hauntsaninja** [comment]
This is less of an issue now that all alive Pythons support PEP 526
