### ISSUE TITLE
Alternative to typing.Collection for Python prior 3.6

### ISSUE THREAD

**Issue by s-kostyuk** [python/mypy#4517]
Good day, I have a question regarding type annotations: 

What is the best way to annotate that function returns something that is Sized, Iterable and Container at the same time?

---------------------------------------------------------------------------------------------------------------------------------

I want to annotate that one of functions in abstract class returns values of some type that is an Iterable and Sized at the same time. This actually can be either a ValuesView, ItemsView, Sequence or a Set, regarding the implementation of an abstract class.

On a first glance, Collection type from Python typing package fits best for this purpose. But the problem is that Collection type was added only in Python versions newer that 3.6.

So, repeating the question: What is the best way to annotate that function returns something that is Sized, Iterable and Container at the same time? In Python versions prior 3.6.

An example of a desired result, if needed: https://gist.github.com/s-kostyuk/93bcc96273cb130b6eb17b7a89542c4f

**Comment by gvanrossum** [comment]
I believe you can define a Protocol for this purpose. You need to import it from typing_extensions (a separate pip package) so it's not tied to the version of typing in the Python stdlib (though IIRC it doesn't work with 3.6.0 -- however it should work with later 3.6.x versions).

**Comment by s-kostyuk** [comment]
If I understood correctly:
- Protocols, introduced in PEP 544, can't be used with Python versions prior 3.6, so version 3.5 is unsupported as well;
- Protocols can be used as a some alternative to Interfaces from C# and allows to define some atomic interfaces with even one method at all like Sized, Iterable and so on;
- Protocols should be considered as an alternative to Zope interfaces and interfaces from another languages like Java and C#;
- in current `typing` and `collections.abc` modules classes like Sized, Iterable and so on are not defined as protocols, they are just abstract classes for now;
- in Python 3.6 all collection-like classes are subclassed from Collection class, in Python 3.5 they are not;
- that's why in Python 3.5 and prior the only way to declare something similar to Collection that will enable type hinting and will pass static type checking is something like:
```
from typing import Union, Sized, Iterable, Container

MyCollection = Union[Sized, Iterable, Container]

some_example_dict = {'foo': 'bar'}

def return_collection() -> MyCollection:
    # and here, for example
    return some_example_dict.values()   # Actually returned ValuesView here
```

**Comment by gvanrossum** [comment]
Your premise is untrue -- Protocols *are* supported in earlier Python
versions (even 2.7!) as long as you import them from typing_extensions.

And a Union does the opposite from what you want (you need an Intersection,
not a union).

**Comment by s-kostyuk** [comment]
Understood. Thank you very much :)
