### ISSUE TITLE
"None" has no attribute "foo"

### ISSUE THREAD

**Issue by matthiaskramm** [python/mypy#4538]
Given

```
x = None
if x is not None:
  x.foo()
```

running `mypy file.py` reports:

```
file.py:3: error: "None" has no attribute "foo"
```

mypy version: `mypy 0.570-dev-8ec7046787f92bf7b00d0c70f570fcb5d75e4b53`

Passing `--strict-optional` makes the problem go away.

**Comment by bwo** [comment]
seems like this is related: https://github.com/python/mypy/issues/4520

**Comment by ethanhs** [comment]
I think this is in fact a duplicate of #4520, closing this as that issue has more discussion.
