### ISSUE TITLE
Function overloading example does not typecheck

### ISSUE THREAD

**Issue by tyrion** [python/mypy#4565]
The second code example given on the [function overloading documentation](http://mypy.readthedocs.io/en/latest/function_overloading.html)  gives the error (referred to the last definition of `__getitem__`): `Signature of __getitem__ incompatible with supertype Sequence`.

The whole snippet is:
```python
from typing import overload, Sequence, TypeVar, Union
T = TypeVar('T')

class MyList(Sequence[T]):
    @overload
    def __getitem__(self, index: int) -> T:
        pass  # Don't put code here

    @overload
    def __getitem__(self, index: slice) -> Sequence[T]:
        pass  # Don't put code here

    def __getitem__(self, index: Union[int, slice]) -> Union[T, Sequence[T]]:
        raise NotImplementedError
```

**Comment by ilevkivskyi** [comment]
I think this is because mypy checks the _implementation_ signature against base class (while it shouldn't). If I remove the implementation annotation the error goes away.
