### ISSUE TITLE
Use `any` and `all` to make collection non-optional

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4573]
I have seen patterns like this several times:
```python
def func() -> Optional[int]:
    pass

def test() -> List[int]:
    vals: Iterable[Optional[int]] = [func() for _ in some_list]
    if all(vals):
        return list(vals)  # None can't be in 'vals' here.
    return []
```
It would be convenient if binder could understand this for covariant collections.

**Comment by gvanrossum** [comment]
Clever and convenient, but we'd have to be sure we are okay with the
refined type of `vals` not being a subtype of its original type (because of
List invariance).

**Comment by ilevkivskyi** [comment]
> but we'd have to be sure we are okay with the
refined type of `vals` not being a subtype of its original type (because of
List invariance).

I think we should only allow narrowing if the original variable is annotated with something like `Iterable`, `Sequence` or `Container`. Invariant containers like `List` or `Dict` should stay as is (I think there is already somer code in binder that applies a restriction only if it is a subtype).

**Comment by gvanrossum** [comment]
Then your example won't work as written.

Also, I have a vague sense of "déjà vu" about this.

**Comment by ilevkivskyi** [comment]
> Then your example won't work as written.

OK, I will updated it.
> Also, I have a vague sense of "déjà vu" about this.

Because I proposed and implemented a similar feature for `if None not in some container`.

**Comment by msullivan** [comment]
I think if we only do this for covariant containers then it feels pretty niche and if we do it for invariant containers then it has problems, so I'm going to close this, but if somebody disagrees with me feel free to reopen
