### ISSUE TITLE
Support basic union math for overloaded functions

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4576]
I think this idea appeared in context of other issues (mostly related to strict optional), but I hit this few times in another context. Consider this example:
```python
Dictable = Union[Dict[str, str], Iterable[Tuple[str, str]]]
def do(arg: Dictable) -> None:
    converted = dict(arg)  # mypy errors here, although this is valid
```
The problem is that `dict.__init__` is defined as an overload. I think we should at least support matching simple cases like:
```python
@overload
def fun(x: A) -> B: ...
@overload
def fun(x: C) -> D: ...

arg: Union[A, C]

fun(arg)  # we infer Union[B, D]
```

**Comment by Michael0x2a** [comment]
I believe this is now fixed after a combination of https://github.com/python/mypy/pull/5255 and https://github.com/python/mypy/pull/5222.
