### ISSUE TITLE
Idea: allow calling NewType function on Optional

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4580]
E.g.
```py
A = NewType('A', int)
def f(a: Optional[int]) -> Optional[A]:
    return A(a)
```
This could be implemented by making the function representing `A()` at check time overloaded. It would still be precise if the argument didn't have an `Optional`, e.g.
```py
x: int
reveal_type(A(x))  # int
y: Optional[int]
reveal_type(A(y))  # Optional[int]
```

**Comment by gvanrossum** [comment]
I wouldn't think a flag or separate name is necessary; if the None is not
desirable in the context it will cause an error, and if it is acceptable,
well, that's my use case. :-)

**Comment by ilevkivskyi** [comment]
> if the None is not desirable in the context it will cause an error

But sometimes 30 function calls deeper/later rather than at the point if actual mistake. I have hit this few times too, but the trade-off is not so obvious to me.

**Comment by gvanrossum** [comment]
Since this is in mypy, not at runtime, I'm not sure how it could be 30 calls deep. Functions that are polymorphic with None like this are pretty common.
