### ISSUE TITLE
Union[List, Dict] simplifies to `Iterable` in Python 2, `Collection` in Python 3

### ISSUE THREAD

**Issue by rowillia** [python/mypy#4582]
I'm unsure if simplifies is the correct terminology here, but below is a repro:

test_union.py:
```python
from typing import *

def foo(a, b):
    # type: (List, Dict) -> None
    for x in (a, b):
        reveal_type(x)
        print(len(x))
```

Command Line:
```
mypy --py2 test_union.py
```

Output:
```
test_union.py:6: error: Revealed type is 'typing.Iterable[Any]'
test_union.py:7: error: Argument 1 to "len" has incompatible type "Iterable[Any]"; expected "Sized"
```

Command Line:
```
mypy test_union.py
```

Output:
```
test_union.py:6: error: Revealed type is 'typing.Collection[Any]'
```

**Comment by gvanrossum** [comment]
This is because it computes the nearest common base class, and in 3.6,
Container was inserted into the inheritance tree. Is there a problem with
this?

**Comment by rowillia** [comment]
@gvanrossum Ah, makes sense.  The issue is that this code is valid in both Python 2 and Python 3, but fails as `Iterable` doesn't implement `__len__` which is confusing our users who are hitting this.

**Comment by gvanrossum** [comment]
"Fixed in Python 3". 🤷‍♀️
