### ISSUE TITLE
Can't infer type of input (dict) and think it is an "object".

### ISSUE THREAD

**Issue by hvnsweeting** [python/mypy#4588]
* Are you reporting a bug, or opening a feature request?
Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
from typing import Dict

idata = {'a': 1, 'prices': {'first_50': 1230, 'from_51_to_100': 1530, 'above_100': 1786}}

def dictin(names):
    # type: (Dict) -> int
    return 5


if __name__ == "__main__":
    dictin(idata['prices'])
```

* What is the actual behavior/output?

```
$ mypy dictin.py
dictin.py:11: error: Argument 1 to "dictin" has incompatible type "object"; expected "Dict[Any, Any]"
```

* What is the behavior/output you expect?
Know that I passed a correct dict, thus no error.

If I remove the key:value `'a': 1`, the check passed without any error.

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
Latest one
```
 mypy --version
mypy 0.570-dev-b0af822a79465a93d55e67b5aea74551a63c08f4
```

**Comment by ilevkivskyi** [comment]
This is not really a bug, mypy can't infer such complex types. For this case you probably want to use `TypedDict`, see http://mypy.readthedocs.io/en/latest/kinds_of_types.html#typeddict. This is the only way to let mypy know that a given key has a specific value type.

**Comment by JukkaL** [comment]
This is a usability issue, however, and comes up pretty frequently. We have an existing issue (#3816) with an idea about how to improve this.
