### ISSUE TITLE
"Incompatible return value type" error with TypeVar

### ISSUE THREAD

**Issue by mikez302** [python/mypy#4590]
I am using Python 3.6.4 and the latest version of Mypy from master (mypy 0.570-dev-3545a71ba11576b08007f70d8407bf7924738886).

I have a file with the following code:
```python
from typing import TypeVar

T = TypeVar('T', int, str)

def foo() -> T:
    return 1
```

If I run it through Mypy, I get this error: `typevar_test.py:6: error: Incompatible return value type (got "int", expected "str")`.

If I make the function return a string, I get a similar error: `typevar_test.py:6: error: Incompatible return value type (got "str", expected "int")`.

If I make the function return something not specified by the TypeVar (such as a list, for example), I get two errors:
```
typevar_test.py:6: error: Incompatible return value type (got "List[int]", expected "int")
typevar_test.py:6: error: Incompatible return value type (got "List[int]", expected "str")
```

**Comment by gvanrossum** [comment]
That's not how type variables work. You seem to be looking for a type alias for a union, e.g.
```py
U = Union[int, str]
def foo() -> U:
    return 1
```
A type variable is used to create a generic function or class -- please read the docs:
http://mypy.readthedocs.io/en/latest/generics.html

**Comment by mikez302** [comment]
I read the documentation about generic functions, both for Mypy and for the typing module.

That was a toy example. I tried to come up with the simplest thing that would trigger the error. I know that in this case, I use a union to do the same thing.

Regardless of that, does a type variable, used in the return hint of a function, absolutely need to also be used in the hint of one of its parameters? If so, then I am doing something invalid. But I don't see anything in the Mypy docs, in the typing module docs, or in PEP 484 that mentions this.

And even if I am doing something invalid, I think the error messages could be made clearer. I think it is strange that if I use an int, I'm told that a string is expected, but if I use a string, I'm told that an int is expected. That is what made me suspect that this might be a bug in Mypy, and not (only) incorrect usage.

I wish I could work on this and try to improve it, but I feel that I am still not familiar enough with Mypy to feel that I could realistically do it myself.

**Comment by gvanrossum** [comment]
Even if you are using the type variable legitimately, you still cannot do what you have in your example.

There are indeed cases where the return type can contain a type variable without the arguments containing one, but the only use cases I'm familiar with are when returning a generic function, such as is done for certain decorators.

The problem with your example is that the type system doesn't have a way to describe the type of a value assigned from a call to `foo()`:
```py
x = foo()  # What is the type of x?
```
(Note that a variable cannot have a type variable in its type unless the type variable is bound in the containing generic class or function.)

I agree that the error is confusing though.

If you still don't understand what's illegal, please show a more complete example (it has to make sense at runtime too).

**Comment by mikez302** [comment]
Now I understand what is invalid about my example. Thanks for the explanation.

**Comment by gvanrossum** [comment]
Hm, we should probably improve the docs. Can you make a suggestion (e.g. by submitting a PR)?

**Comment by mikez302** [comment]
I will consider submitting a PR. Keep in mind that I am still somewhat unfamiliar with some of the details of this project (like how the docs are implemented), and I'm unsure how to explain the problem with my example in a simple way, so I can't make any promise that I'll get it done in any given amount of time.
