### ISSUE TITLE
Coverage issue when using getattr

### ISSUE THREAD

**Issue by ronf** [python/mypy#4591]
I recently began adding type annotations to a project and I'm running into an issue where I can seem to get coverage on a statement which is using getattr. In my actual code, getattr() is being called on a library loaded with ctypes.cdll.LoadLibrary(), but I was able to reproduce the problem with a much simpler example that just uses a simple class. Here's the example:

```python
class Foo:
    a = 1

a = getattr(Foo(), 'a') # type: int
```

I also tried this with the newer Python 3.6 syntax of:

```python
a: int = getattr(Foo(), 'a')
```

Both versions produced the same result, which was that the assignment of 'a' showed up in red (not covered) in the mypy coverage report.

I can understand why getattr() would not be able to determine the type of its return value, but with the explicit type in the getattr assignment, I was expecting the coverage error to go away. Instead, the coverage report still shows this line as not covered, even though the type is tracked properly for later code in the module (and so those lines show up as being covered).

I'm seeing this with mypy 0.560 on Python 3.6.4, with defaults to mypy flags. The only option I'm giving it is '--html-report' to generate the coverage report.

I haven't tried testing this against mypy from Git master yet. I thought I'd start here to see if I'm simply misunderstanding how this should be done. Any suggestions for how to get code like this show up as covered would be greatly appreciated!

**Comment by gvanrossum** [comment]
I'm a bit confused why you're using an example that is guaranteed to raise an exception at runtime:
```
AttributeError: 'dict' object has no attribute 'a'
```
Apart from that, the reason is probably that the type of `getattr()` is declared as `Any`, and the "coverage" report colors all expressions red that have type `Any`.

**Comment by ronf** [comment]
Sorry,  I should have checked my example better. I have updated it to use a class rather than a dict, which more closely matches what I'm seeing with the loaded library.

My basic question is how I can tell mypy not to report this as a coverage error. I was hoping "type: ignore" would work something like "pragma: no cover", but it doesn't. It just forces any line you mark with it as being "uncovered", and doesn't have a different color for ignored lines. While I can understand why it wants to treat such lines as uncovered, I'd really like to find a way to declutter my coverage report by eliminating reports like this. Is there some other gesture I can use to get the line to not show up in the report?

**Comment by gvanrossum** [comment]
There's no feature for this now. Please understand that the "coverage report" is still considered experimental and only barely supported -- I imagine you'll find other places where it's deficient.

I don't think it would be a good idea to give `# type: ignore` the additional semantics of suppressing the coverage "error" -- people would be putting `# type: ignore` all over the place, and `--warn-unused-ignore` would stop being useful.

So I'm stumped as to how a small change somewhere could make it do what you want. But if you think of a specific solution, don't be shy!

**Comment by ronf** [comment]
Thanks for the quick response, and good point about "--warn-unused-ignore".

I think it probably makes sense for this to be a separate directive. Perhaps we could add a "type: no cover" that would not suppress any type checking errors from being generated, but _would_ suppress the line from showing up as red or yellow in the coverage report. Ideally, this could show up as a different color (like grey, the way "# pragma: no cover" does in "coverage") so these lines can still be seen, but they wouldn't be counted against the "imprecision" percentage, allowing that to hit 0% and sho up as green in the file summary even if excluded lines are present.

I'm just barely getting started with mypy so I don't know how involved a change this would be, but once I've gotten a bit more familiar with it, I may take a closer look if you think this sounds like a reasonable approach.

**Comment by gvanrossum** [comment]
It would be a fairly complex change; first you'd have to change https://github.com/python/typed_ast to recognize the new pragma, then the comment-parser in mypy must be made to do the same, etc.

Another way would perhaps be a special comment that *doesn't* start with `# type:` -- mypy and typed_ast would just ignore this, but the coverage generation code (which has to read your source code anyways) could look for such a special comment.

Still, I personally don't think that a clean coverage report is so valuable, so I don't think this feature should happen. (There's also the worry that there will be too many special directives of this nature, causing untidy code.)

**Comment by JukkaL** [comment]
> Another way would perhaps be a special comment that doesn't start with # type: -- mypy and typed_ast would just ignore this, but the coverage generation code (which has to read your source code anyways) could look for such a special comment.

I think that this would be a reasonable way to do this. The coverage code might have to tokenize the source file to reliably find the comment (so that it could ignore comments within string literals).

Agreed that this is a low priority feature.

**Comment by ronf** [comment]
If you decide to go with a comment that doesn't start with "# type:", perhaps it would make sense to just support the existing "# pragma: no cover" for this.

**Comment by msullivan** [comment]
Yeah probably we aren't doing much work on the coverage report details
