### ISSUE TITLE
BUG: SupportsComplex doesn't seem to work

### ISSUE THREAD

**Issue by shoyer** [python/mypy#4592]
The following snippet triggers a mypy error:
```
from typing import SupportsComplex

class A(SupportsComplex):
    def __complex__(self) -> complex:
        return 1j

complex(A())
# No overload variant of "complex" matches argument types [test_simple.A]
```

I believe this is the right way to indicate that a class supports casting to complex values.

I'm using Python 3.6.4 and mypy 0.560. See https://github.com/numpy/numpy_stubs/pull/10 for context.

**Comment by gvanrossum** [comment]
Oh, this looks like a bug in typeshed. Both the Py2 and Py3 definition of class complex there are lacking several things -- a base class of `SupportsComplex` and an overload of the constructor to take a `SupportsComplex` value.

Can you submit a PR or issue there?

**Comment by shoyer** [comment]
OK, I'm still a little new to the typeshed/mypy, so I opened at issue rather than PR for now: https://github.com/python/typeshed/issues/1904

Closing this since it seems to be a typeshed rather than mypy issue.
