### ISSUE TITLE
Add support for collections.namedtuple

### ISSUE THREAD

**Issue by akaihola** [python/mypy#460]
namedtupletest.py:

```
from collections import namedtuple
```

Test:

```
$ mypy namedtupletest.py
/tmp/namedtupletest.py, line 1: Module has no attribute 'namedtuple'
```

**Comment by gvanrossum** [comment]
I don't see NamedTuple defined in the https://github.com/JukkaL/typing project yet. mypy's own typing.py seems to have deviated a bunch.

**Comment by Dedoig** [comment]
Mypy disallows usage of _replace() method from namedtuple. 

from collections import namedtuple
Person = namedtuple("Person", 'name')
p = Person("bob")
p._replace(name="sam")

==> "Person" has no attribute "_replace"

**Comment by JukkaL** [comment]
Yeah, the `namedtuple` implementation is missing a few things. Added a new issue: https://github.com/JukkaL/mypy/issues/661
