### ISSUE TITLE
@total_ordering support

### ISSUE THREAD

**Issue by srittau** [python/mypy#4610]
Please consider the following code:

```python
from functools import total_ordering
from typing import Any


@total_ordering
class Ord:

    def __eq__(self, other: Any) -> bool:
        return False

    def __lt__(self, other: "Ord") -> bool:
        return False


Ord() <= Ord()
```

mypy 0.560 (using Python 3.6.4, default flags) complains:

`test.py:15: error: Unsupported left operand type for <= ("Ord")`

It would be helpful if mypy would support `@total_ordering`.

**Comment by gvanrossum** [comment]
Perhaps the implementation of this could be a plugin. There are likely ideas to copy from the attrs plugin that David Euresti recently contributed (though that one has a wider scope).

**Comment by chadrik** [comment]
+1.  Just got hit by this one.

**Comment by gvanrossum** [comment]
Maybe someone can submit a PR.

**Comment by aldanor** [comment]
Can the implementation like https://github.com/pantsbuild/pants/pull/9525 be utilized in base mypy?

**Comment by JelleZijlstra** [comment]
@aldanor that seems reasonable, since this is a standard library function.
