### ISSUE TITLE
Binder doesn't work well with Type[...]

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4616]
This code:
```python
from typing import Union, Type

class C: ...

x: Union[C, Type[C]]

if isinstance(x, type) and issubclass(x, C):
    reveal_type(x)
```
Shows that the type of `x` is `builtins.type`. Ideally it should be `Type[C]`.

**Comment by andrewbaxter** [comment]
Is this the same as:

```
class A:
    x = 4


i: type = A
assert issubclass(i, A)
print(i.x)
```
which fails with:
```
7: error: "type" has no attribute "x"
```
?

mypy 0.590

It looks like `issubclass` doesn't imply anything AFAICT, unlike `isinstance`.

There's this workaround:
```
i: type = A
j: Type[A] = i
print(j.x)
```

but since this isn't in assertion format it seems more like a static check omission.

**Comment by ilevkivskyi** [comment]
Yes, this is the same bug.

**Comment by chadrik** [comment]
Just got bit by this one.

**Comment by ilevkivskyi** [comment]
(Removing unions tag since there are repros without unions, and increasing priority to high since this appeared several times again.)
