### ISSUE TITLE
mypy ignores annotated types in various circumstances

### ISSUE THREAD

**Issue by rotemdan** [python/mypy#4636]
Sorry if duplicate! (I wasn't sure what keywords to use to search this)
(using mypy `0.560`)

The following doesn't error:
```py
from typing import List

def main():
	test: List[List[int]] = []
	test[0]['abcd'] = 'hi' # <-- no error here?
```
but this does:
```py
from typing import List

def main():
	test: List[List[int]] = [[]]
	test[0]['abcd'] = 'hi' # <- does error here
```
And it gets even more bizarre:
```py
from typing import List

def f(a: List[List[int]]) -> List[List[int]]:
	# a.append([1,2,3]) # <-- uncommenting this line seems to have no effect as well
	return a

def main():
	test = f([])
	test[0]['abcd'] = 'hi' # <- doesn't error?
```
However:
```py
from typing import List

def f(a: List[List[int]]) -> List[List[int]]:
	return a

def main():
	test = f([[]])
	test[0]['abcd'] = 'hi' # <- does error
```
And if the argument to `f` has a type unknown to mypy, it doesn't error as well (this is the form which I originally discovered this behavior):
```py
from typing import List

def f(a: List[List[int]]) -> List[List[int]]:
	return a

def main():
	import someModule
	unknown = someModule.getSomething()
	test = f(unknown)
	test[0]['abcd'] = 'hi' # <- doesn't error
```

**Comment by JukkaL** [comment]
`main` is missing a type annotation so it doesn't get type checked. You should add a return type (`def main() -> None: ...`) and mypy will produce more useful results.

**Comment by rotemdan** [comment]
@JukkaL 

Thanks, adding the return type appears to help superficially (I've spent hours at trying to figure this out), 
but it still seems quite unexpected that some inferences work but some don't? I'm not sure how this relate to the return type of `main`?  (why can't it be inferred as `None` by default?)

I find it difficult to understand the logic of this?

Basically if the scoping function has no return annotation, things 'sort' of work, but strangely/incorrectly?

(In any case, If the return annotation is so critically important, it would be helpful if mypy would notify about it)

**Comment by JukkaL** [comment]
There is an open issues about this (#3948) with some discussion. The documentation could be a bit clearer about this. Mypy doesn't type check functions without annotations to avoid generating spurious errors for partially annotated legacy code.
