### ISSUE TITLE
Better type for self in untyped functions

### ISSUE THREAD

**Issue by gsalgado** [python/mypy#4637]
Running `mypy --check-untyped-defs` against the code below will give an error only for method `m2()`:

> /tmp/foo.py:6: error: "Dict[str, str]" has no attribute "unknown_method"

When in fact I'd expect a similar error for the `self.unknown_method()` line.

```
class Foo:
    def m(self):
        self.unknown_method()
    def m2(self):
        d = dict(foo='bar')
        d.unknown_method()
```
However, if I add a type annotation to method m(): `def m(self) -> None:`, I do get the error I expected:

> /tmp/foo.py:3: error: "Foo" has no attribute "unknown_method"
> /tmp/foo.py:6: error: "Dict[str, str]" has no attribute "unknown_method"

**Comment by JukkaL** [comment]
The type of `self` is `Any` if you don't have an annotation -- all unannotated arguments are given `Any` types. However, maybe `self` should be an exception and work similarly to annotated functions. The `cls` argument of class methods is also currently `Any` in unannotated methods even when using `--check-unyped-defs`.

**Comment by gsalgado** [comment]
Hmm, yeah, I think that'd make sense, in the same way that `self` gets assigned the correct type (`Foo`) when the method has just a return type annotation (`def m(self) -> None:`)

**Comment by gvanrossum** [comment]
Yeah, we should be able to set a better type for `self` and `cls`.
