### ISSUE TITLE
Empty argument list of a Callable is translated to <TypeList> in stub file

### ISSUE THREAD

**Issue by hoefling** [python/mypy#4638]
[PEP 484](https://www.python.org/dev/peps/pep-0484/#callable) mentions an example for typing a function with no arguments (I added sample function body to be able to pass it to ``stubgen``):

```python
from typing import Callable

def feeder(get_next_item: Callable[[], str]) -> None:
    return None
```
Now run ``stubgen`` over the file with the above code:

```sh
$ python -m mypy.stubgen spam
Created out/spam.pyi
```
The following stub file is generated:
```python
# Stubs for spam (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Callable

def feeder(get_next_item: Callable[<TypeList >, str]) -> None: ...
```
What confuses me is the ``<TypeList >`` instead of an empty list.

**Comment by gvanrossum** [comment]
Probably a simple bug in stubgen, hopefully you can fix it yourself and submit a PR.

**Comment by evhub** [comment]
As noted in #4640, this issue occurs with all TypeLists, not just empty ones.

**Comment by gvanrossum** [comment]
OK, closing this as a duplicate then.

**Comment by evhub** [comment]
@gvanrossum PR #4650 should fix both issues.
