### ISSUE TITLE
How to properly type a decorator which injects a parameter

### ISSUE THREAD

**Issue by ojii** [python/mypy#4643]
How would I properly type this code? 

```python
from functools import wraps
from typing import *

Params = TypeVar('Params')
Return = TypeVar('Return')


def decorator(f: Callable[Params, Return]) -> Callable[[str, *Params], Return]:
    @wraps(f)
    def wrapper(*args: Params):
        return f('injected', *args)
    return wrapper


@decorator
def func(injected: str, prefix: str, num: int) -> str:
    return prefix + (injected * num)


assert func('hello', 2) == 'helloinjectedinjected'
```

The `Callable[Params, Return]` and `Callable[[str, *Params], Return]` are the problem here.  Is there a way to type this?

**Comment by gvanrossum** [comment]
This is not currently possible. There's a proposal for an extension to PEP 484 that would allow such types to be expressed though: https://github.com/python/typing/issues/193

**Comment by johng** [comment]
Maybe this can be re-opened with PEP 646 ?

**Comment by JelleZijlstra** [comment]
[PEP 612](https://www.python.org/dev/peps/pep-0612/) provides `ParamSpec` and `Concatenate`, which will indeed fix this issue. Mypy doesn't implement it yet, but there's already some open issues about it so we can leave this issue closed.
