### ISSUE TITLE
Can't declare a property setter on a child class without declaring getter there as well

### ISSUE THREAD

**Issue by elvslv** [python/mypy#4644]
If I declare a property getter on a base class, I can't declare a setter on a child class without having to add a getter there as well.

For example,
```
class A(object):
    __metaclass__ = ABCMeta

    @property
    def prop(self):
        # type: () -> int
        return 1

class B(A):
    @A.prop.setter
    def prop(self, val):
        # type: (int) -> None
        pass
```
is a valid python code, but mypy fails with `"Callable[[A], int]" has no attribute "setter"`

**Comment by JukkaL** [comment]
Yes, it would be nice if mypy supported this idiom.

**Comment by AlexWaygood** [comment]
Closing in favour of #5936, which was filed after this issue, but has had more activity on it since.
