### ISSUE TITLE
Remove the 'replaced' attribute of TypeInfo

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4646]
Currently we create two TypeInfo objects for each class-based named tuple and typed dict. The first one is not the real TypeInfo and contains a reference to the real type info through a `replaced` attribute.  This seems unnecessarily complex and causes potential aliasing issues, and it's also pretty confusing. Maybe we can modify the original TypeInfo in place to become the new one? This would also help with fine-grained incremental checking.

The principle that applies here is that it's preferable to have a simple data model even if it makes construction a bit harder, since construction typically happens only once but we use the data in many places.

@ilevkivskyi What do you think?

**Comment by ilevkivskyi** [comment]
I am only for it. I think it may even simplify the forward reference treatment, IIRC we currently need to patch some types referring to wrong `TypeInfo`s in the third pass.
