### ISSUE TITLE
error: Cycle in inheritance hierarchy

### ISSUE THREAD

**Issue by fried** [python/mypy#4648]
I think this is a bug.

Examples:
https://github.com/pyca/pynacl/blob/master/src/nacl/exceptions.py#L30-L34
https://bitbucket.org/zzzeek/alembic/src/132ec8cf696ef9588599ae23d45ea349542197ce/alembic/util/compat.py?at=master&fileviewer=file-view-default#compat.py-248

Pretty much any time when this pattern happens
`class Name(Name): `

Where `Name` is some previously existing class.  I am currently fixing this with empty pyi files

**Comment by gvanrossum** [comment]
Because the way mypy looks at your source code, it doesn't like a definition that uses the name being defined as an input. (TBH as a human I find it a bit confusing to.)

The way to work around it is something like
``py
from <somewhere> import Name as _Name
class Name(_Name):
```

**Comment by kamahen** [comment]
This feels like a bug to me (not requiring a workaround), and it's similar problem to handling this kind of scoping:

```
x = [1,2,3]
print([x + 1 for x in x if x % 2 == 1])
```
