### ISSUE TITLE
Consider supporting sys.version_info.major (and .minor)

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4661]
It turns out there's a nicer notation than `sys.version_info[0]` -- `sys.version_info.major`. Consider supporting this too, as well as `.minor`. This is supported by Python 2.7, 3.1 and higher, so all Python versions that mypy supports.

A minor PEP 484 update would be required here: https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking

Note that we'd need buy-in from PyCharm and Google's pytype as well before we can start using this in stubs (where it's most useful).

**Comment by hauntsaninja** [comment]
Not worth the effort of coordinating all the other type checkers.

**Comment by ethanhs** [comment]
I think we could support this, but the issue should be in the typing repo I think
