### ISSUE TITLE
os.cpu_count - Unsupported operand types for * ("Optional[int]" and "int") in strict mode

### ISSUE THREAD

**Issue by hvnsweeting** [python/mypy#4670]
The signature of os.cpu_count is Optional[int], which might be not wrong because maybe in some OS, python cannot get the number and returns None.

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```
# cat cpucount.py
import os
os.cpu_count() * 5
```

* What is the actual behavior/output?

```
$ mypy cpucount.py  --strict
cpucount.py:2: error: Unsupported operand types for * ("Optional[int]" and "int")
```

* What is the behavior/output you expect?

Got the integer result

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

Python 3.5.2 mypy 0.560
and also latest mypy on master 
```
cmypy 0.570-dev-21dcd8081bd404b18305796651ecd2d6dd8950ef
```

* What are the mypy flags you are using? (For example --strict-optional)
`--strict`

Now I understand Optional[int] would accept None or int, all examples I found in doc just use Optional it in function argument, not using that var inside the function body.

I understand that to be `strict`, it would not allow None + int, but what if my code only run on OSX & Linux, what is the way to go for this error? Writing 

```
# $ cat cpu2.py
import os
cpus = os.cpu_count()
if cpus is None:
    value = 5
else:
    value = cpus * 5
```

is verbose, and redundant in my case. Or should I just tell mypy ignore it?

**Comment by JelleZijlstra** [comment]
This is a typeshed issue (https://github.com/python/typeshed); mypy is correctly processing the stub here.

I looked at the implementation of `os.cpu_count` and it can indeed return None, but I'm not sure in what practical circumstances that would happen.

**Comment by cpbotha** [comment]
I ran into this just now converting an existing codebase which uses the recommended `max_workers` formulation from https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor: `min(32, os.cpu_count() + 4)`

In order to work around it, I had to:

```python
# next line for mypy
cpu_count = cast(int, os.cpu_count() if os.cpu_count() is not None else 1)
worker_threads = min(32, cpu_count + 4)
```

I was surprised that mypy required the `cast()` in order to figure out that `cpu_count` is in fact an `int` due to the ternary.

**Comment by erictraut** [comment]
Mypy can't assume that a function that is called multiple times will return the same time each time. That might be true for `os.cpu_count()`, but it's not in general.

You could use one of the following alternatives:
```python
cpu_count = os.cpu_count() or 1
```

or
```python
cpu_count = x if (x := os.cpu_count()) is not None else 1
```

or
```python
cpu_count = os.cpu_count()
if cpu_count is None:
    cpu_count = 1
```

**Comment by cpbotha** [comment]
Aaah thank you @erictraut that makes sense (multiple function calls), and thank you for all the alternatives!
