### ISSUE TITLE
Having trouble writing a type signature for a subclass of LoggerAdapter

### ISSUE THREAD

**Issue by ronf** [python/mypy#4676]
I'm trying to subclass the standard library logging.LoggerAdapter, and I'm having trouble coming up with a signature that doesn't return the error:
```
Signature of "log" incompatible with supertype "LoggerAdapter"
```
I'd like to define my "log" method as:

```python
    def log(self, level: int, msg: str, *args: Any, **kwargs: Any) -> None:
```

There are some explicit keyword arguments in the superclass definition, but I currently just leave those untouched in **kwargs and pass them through to the superclass.

Part of what is making this difficult is that the type signature in typeshed for LoggerAdapter right now relies on a pretty complicated private type alias, and I really don't want to replicate all of that in my code:

```python
_SysExcInfoType = Union[Tuple[type, BaseException, TracebackType],
                        Tuple[None, None, None]]
if sys.version_info >= (3, 5):
    _ExcInfoType = Union[None, bool, _SysExcInfoType, BaseException]
else:
    _ExcInfoType = Union[None, bool, _SysExcInfoType]

def log(self,
                lvl: int, msg: Text, *args: Any, exc_info: _ExcInfoType = ...,
                extra: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> None: ...
```

Other than removing all the types here from the method definition, is there any way to get a signature which makes mypy happy? The code runs just fine despite the mypy error, but I'd really like to get rid of that without losing all of my type checking inside the function.

I'm having this problem with mypy 0.560 on Python 3.6.4, but I don't think it's really all that sensitive to the version. I just don't know how to specify a compatible type. Any suggestions would be appreciated!

**Comment by gvanrossum** [comment]
If you don't mind losing the typing for just the `exc_info` argument, you can probably solve this by copying the signature from typeshed but replacing `_ExcInfoType` with `Any`.

OT the definition of `_SysExcInfoType` annoys me -- I'm not sure if it's warranted by the actual implementation. It would be nicer if it could be `Tuple[Optional[Type[BaseException]], Optional[BaseException], Optional[TracebackType]]`. That wouldn't help you much (it would be even longer) but that marches the signature of `sys.exc_info()`.

**Comment by ronf** [comment]
Guido, thanks for the suggestion.

I tried this today and managed to get mypy to no longer complain, but that just led to pylint now complaining, as the signature in typeshed doesn't actually match what's in the logging module itself. In logging.LoggerAdapter, the actual implementation has the following signature:

```python
    def log(self, level, msg, *args, **kwargs):
```

It has no exc_info, stack_info, or extra arguments. Only the "_log" function in LoggerAdapter has them, and the same is true for the main Logger class. Given this, listing these extra arguments in typeshed seems wrong to me, and this is definitely causing pylint some heartburn.

In addition to log(), the same issue applies to all the other functions that call that, such as debug(), info(), warning(), etc.

I also ran into a different issue. Because I was now listing arguments like "extra" explicitly in my function signature and giving it a default value of None, that was not the same as the key not existing in kwargs at all, which other code of mine depended on. This wasn't hard to "fix", but it's another potential bad consequence of making arguments explicit in functions where they really aren't.

**Comment by jace** [comment]
I had the same issue with a custom logging formatter. Importing from the typeshed stub worked:

```python
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from logging import _SysExcInfoType

class CustomFormatter(logging.Formatter):
    def formatException(self, exc_info: _SysExcInfoType) -> str:
        ...
```

**Comment by vtgn** [comment]
Hi! Same problem by encapsulating the logger in a custom class overloading the logging methods. 

```Python
from logging import _ExcInfoType, getLogger # Pylint ERROR: No name '_ExcInfoType' in module 'logging' Pylint(no-name-in-module)
class CustomLogger:

    def __init__(self: Self, name: str):
        self.__logger = getLogger(name)

    def debug(
        self: Self,
        message: str,
        *args: object,
        exc_info: _ExcInfoType = None,
        stack_info: bool = False,
        stacklevel: int = 1,
        extra: Mapping[str, object] | None = None,
    ) -> None:
        pass
```

**Comment by vtgn** [comment]
> I had the same issue with a custom logging formatter. Importing from the typeshed stub worked:
> 
> ```python
> from __future__ import annotations
> 
> import logging
> from typing import TYPE_CHECKING
> 
> if TYPE_CHECKING:
>     from logging import _SysExcInfoType
> 
> class CustomFormatter(logging.Formatter):
>     def formatException(self, exc_info: _SysExcInfoType) -> str:
>         ...
> ```

What did you install with pip concretely? My typeshed doesn't contain these types for logging. :/

**Comment by jace** [comment]
> What did you install with pip concretely? My typeshed doesn't contain these types for logging. :/

Nothing installed. Mypy uses typeshed stubs automatically.

**Comment by hauntsaninja** [comment]
I think `exc_info: Any` here is fine (and if TYPE_CHECKING + import is serviceable too). Closing since there isn't a plan to change anything in mypy

**Comment by vtgn** [comment]
It's most of all a problem from the `logging` module: this type shouldn't be protected but public.

> If you don't mind losing the typing for just the `exc_info` argument, you can probably solve this by copying the signature from typeshed but replacing `_ExcInfoType` with `Any`.
> 
> OT the definition of `_SysExcInfoType` annoys me -- I'm not sure if it's warranted by the actual implementation. It would be nicer if it could be `Tuple[Optional[Type[BaseException]], Optional[BaseException], Optional[TracebackType]]`. That wouldn't help you much (it would be even longer) but that marches the signature of `sys.exc_info()`.

Yeah, it works too by defining your own types like this:

```python
from types import TracebackType
from typing import TypeAlias

SysExcInfoType: TypeAlias = (
    tuple[type[BaseException], BaseException, TracebackType | None] | tuple[None, None, None]
)
ExcInfoType: TypeAlias = None | bool | SysExcInfoType | BaseException
```

But finally I prefer the solution of @jace
