### ISSUE TITLE
Wrong typings for Manager

### ISSUE THREAD

**Issue by domoritz** [python/mypy#4678]
This code

```py
from multiprocessing import Manager

with Manager() as manager:
        d = manager.dict()
        pool = manager.Pool(processes=2)
```

Causes this error (`mypy test.py` assuming that the above code is in `test.py`)

```
error: "BaseManager" has no attribute "dict"
error: "BaseManager" has no attribute "Pool"
```

But it works fine in Python 3.

**Comment by ethanhs** [comment]
Hi, could you please give a bit more information? Are you checking Python 2 or 3? What is the manager you are referring to? Is it perhaps `multiprocessing`?

**Comment by domoritz** [comment]
@ethanhs I updated the description.

**Comment by gvanrossum** [comment]
This is a [typeshed](https://github.com/python/typeshed) issue. It looks like `Manager()` returns a `SyncManager`, which inherits from `BaseManager`, which inherits from `ContextManager[BaseManager]`. But that means that `with Manager() as manager` makes `manager` a `BaseManager` instance (as far as mypy is concerned), which doesn't have a `dict()` or `Pool()` method (those are defined by `SyncManager`).

I can't remember right now if this can be made generic -- if not, maybe adding `def __enter__(self) -> SyncManager: ...` to `SyncManager` might help?

**Comment by msullivan** [comment]
Closing as a typeshed issue
