### ISSUE TITLE
Seems impossible to correctly type out a decorated function that decorates a function that returns a generator

### ISSUE THREAD

**Issue by cburgdorf** [python/mypy#4709]
Consider this:

```Python
from typing import Callable, Dict


def to_dict(fn) -> Callable[[], Dict[str, int]]:
    def new_fn() -> Dict[str, int]:
        return dict(fn())

    return new_fn

@to_dict  
def yield_pairs() -> Dict[str, int]:
    yield 'one', 1

x = yield_pairs()

# prints <class 'dict'>
print(type(x))
```

Leaves us with

```
#test.py:10: error: The return type of a generator function should be "Generator" or one of its supertypes
```
Clearly the `to_dict` decorator is supposed to alter the type of `yield_pairs()` to `Callable[[], Dict[str, int]]` yet it seems impossible to type that out.

Mypy seems to insist that every function that contains a `yield` must have a "Generator-ish" return type. It doesn't seem to consider decorators altering the behavior.

Notice that in other scenarios decorators altering the signature of methods works just fine. So this seems to be specific to the usage of `yield` here.

Notice that in general `mypy` takes decorator into consideration just fine as seen in this trivial case.

```python
from typing import Callable, Tuple

def with_strlen(f: Callable[[int], str]) -> Callable[[int], Tuple[str, int]]:
    def ret(__i: int) -> Tuple[str, int]:
        r = f(__i)
        return r, len(r)
    return ret

@with_strlen
def lol(x: int) -> str:
    return "lol"*x

reveal_type(lol) # mypy knows lol returns Tuple[str, int]
```

**Comment by gvanrossum** [comment]
You should type the generator as it is (`-> Iterator[Tuple[str, int]]`); mypy will correctly infer the type of the result of decoration from the decorator's type.

**Comment by cburgdorf** [comment]
Oh shoot. You are correct. Sorry for the buzz.
