### ISSUE TITLE
Nested Protocols

### ISSUE THREAD

**Issue by iddan** [python/mypy#4711]
* Are you reporting a bug, or opening a feature request?

Feature request

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
from typing_extensions import Protocol

class Address(Protocol):
    street: str
    city: str
    country: str

class Person(Protocol):
    name : str
    address: Address

class Student:
    def __init__(self, name, address):
      self.name = name
      self.address = address

student : Person = Student('Dan', object())
```

* What is the actual behavior/output?

mypy ignores error

* What is the behavior/output you expect?

mypy to error for non matching nested type: `object() doesn't match protocol Address`

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

mypy: 0.57
Python: 3.6.2
I see the same issue after installing mypy from Git master

* What are the mypy flags you are using? (For example --strict-optional)

No flags

* If mypy crashed with a traceback, please paste
  the full traceback below.

**Comment by gvanrossum** [comment]
I notice you have no annotations on Student.__init__. This makes the types
of name and address Any. What happens if you properly annotate
Student.__init__?

**Comment by iddan** [comment]
Nothing. Until I type `Student.__init__()` arguments I get no errors.

**Comment by iddan** [comment]
Then it fails.

**Comment by iddan** [comment]
Is there another way with typing to define structure of nested objects? I'm familiar with structured types from languages like TypeScript and OCaml.

**Comment by gvanrossum** [comment]
So mypy is behaving as intended -- if you don't annotate `__init__` all its arguments are taken to be `Any` and then the instance attributes created from them also become `Any`.

I'm unclear on what your question is, and I don't know TypeScript or OCaml.

**Comment by ilevkivskyi** [comment]
So is this resolved? My understanding is that nested protocols work correctly. Also you can use dataclasses as implementations (although support of dataclasses in mypy is not yet done).

**Comment by gvanrossum** [comment]
iddan added a Thumbs Up so I assume this means they're satisfied.
