### ISSUE TITLE
Per-module options not respected when using `--shadow-file` option

### ISSUE THREAD

**Issue by msherry** [python/mypy#4712]
I maintain a plugin for Emacs' `flycheck` that uses mypy to provide type-checking while editing Python code. Due to the way flycheck is implemented, files are renamed while being rechecked and have "flycheck_" prepended to them (e.g. "myfile.py" becomes "flycheck_myfile.py"). This causes per-module options in mypy.ini to not be recognized correctly.

Per a [comment from Guido](https://github.com/msherry/flycheck-pycheckers/issues/2#issuecomment-370582591) on an issue, I looked into using the `--shadow-file` option as a way to solve this. However, it appears that the shadowed filename is not used when looking up options from the mypy.ini file.

**Filesystem:**
```
.
├── mypy.ini
└── test
    ├── __init__.py
    └── tt.py

```

**mypy.ini:**
```
[mypy]
warn_no_return = False

[mypy-test.tt]
warn_no_return = True
```

**tt.py:**
```python
def fun(a):
    # type: (int) -> int
    fun(2 * a)
```

Running mypy directly on the file produces an error, as expected:
```
msherry@msherry-mbp:$ mypy --config-file ~/mypy-repro/mypy.ini ~/mypy-repro/test/tt.py
~/mypy-repro/test/tt.py:1: error: Missing return statement
msherry@msherry-mbp:$
```

However, using the `--shadow-file` option does not (after copying the file `tt.py` to `flycheck_tt.py`, similar to how flycheck would):
```
msherry@msherry-mbp:$ mypy --config-file ~/mypy-repro/mypy.ini --shadow-file ~/mypy-repro/test/flycheck_tt.py ~/mypy-repro/test/tt.py ~/mypy-repro/test/flycheck_tt.py
msherry@msherry-mbp:$
```
(The documentation wasn't very clear to me, so I also tried swapping the `SOURCE_FILE` and `SHADOW_FILE` arguments to `--shadow-file`, with the same result.)

I believe that when using the `--shadow-file` option, mypy should apply the options for the shadowed file, not the actual file being typechecked.

**Comment by gvanrossum** [comment]
If your report is right that's definitely a bug. Though I don't see how this can be explained. The shadow file is used in very few places, all found by searching for `maybe_swap_for_shadow_path`, and in those places it doesn't seem the shadow file's path escapes into any other data structures used by mypy.

**Comment by msherry** [comment]
I suspect that the issue is that we're not using `maybe_swap_for_shadow_path` in *enough* places. e.g. when calling [`options.clone_for_module`](https://github.com/python/mypy/blob/master/mypy/build.py#L1603), I believe we should probably be using the shadow path here, rather than the original.

**Comment by gvanrossum** [comment]
Oh wait. You're supposed to invoke mypy as follows:
```
mypy --shadow-file flycheck_tt.py tt.py tt.py
```

**Comment by msherry** [comment]
I see! I was misreading the docs for the `--shadow-file` option. Using this ordering of file paths works for me -- I'll go ahead and close this issue.

Thanks for the quick response!
