### ISSUE TITLE
[Question] Is there an API to annotate the ast

### ISSUE THREAD

**Issue by sk-** [python/mypy#4713]
Is there an api to annotate the AST, I'm interested in knowing the type of all subexpressions.

For example in the code:

```python
min(3, 4)
'foo' * 2
def f(a: int, min: Callable[[int, int], int]) -> int:
  return min(a, 314)
```

I would like to know that 
```
min -> __builtin__.min
3 -> int
4 -> int
min(3, 4) -> int
'foo' -> str
2 -> int
'foo' * 2 -> str

# In function f
a -> int
314 int
min -> Callable[[int, int], int] not __builtin__.min
min(a, 314) -> int
```

and ideally the expression should have line number and offset information to match it with the AST nodes.

**Comment by gvanrossum** [comment]
Such a feature currently does not exist. But you can insert `reveal_type(x)` calls in your code and mypy will print the type of that specific expression.

**Comment by ethanhs** [comment]
Do we want to make this issue a feature request? There was an attempt before to do something similar in https://github.com/python/mypy/pull/2444, and I think it would be a nice thing to do. (Also I don't think there is another relevant issue open).

**Comment by JukkaL** [comment]
Something like this would potentially be useful, but we can't make any progress with this until we have an understanding of the use cases where this could be helpful. The specifics of use cases could have a major impact on implementation details (and complexity of implementation).

Here are some potential use cases I can think of (some of them are probably unrealistic, but including them here for completeness):
* Editor integration
* Code browsing tools
* Static analysis tools
* Compilers/transpilers
* Runtime type checkers

**Comment by kamahen** [comment]
On 5 April 2018 at 11:45, Sebastian Kreft <notifications@github.com> wrote:

> The other important use case is refactorings.
>
> Also note that reveal_type cannot be used everywhere, for example it
> cannot be used inside a comprehension.
>
> And that in unannotated functions reveal_type just returns Any (with the
> message note: 'reveal_type' always outputs 'Any' in unchecked functions).
>

​For unannotated functions, perhaps pytype
<https://github.com/google/pytype> would be helpful? Unfortunately, it
doesn't annotate variables AFAIK, and when I last looked, its internal form
wasn't suitable for deeper analysis because it uses the bytecodes rather
than source code.
​

**Comment by JukkaL** [comment]
> And that in unannotated functions reveal_type just returns Any (with the message note: 'reveal_type' always outputs 'Any' in unchecked functions).

Mypy doesn't record inferred types in unannotated functions so this feature would not help with this.

**Comment by gvanrossum** [comment]
Let's close this issue, it's formulated as a question, and as a feature request it's too general. For a specific use case please file a fresh issue describing the use case in more detail.
