### ISSUE TITLE
Type of variable after isinstance check with 'and'

### ISSUE THREAD

**Issue by spkersten** [python/mypy#473]
After a guard with `isinstance`, mypy should consider the variable to be of that type.

For example:
```python
def f(x: A) -> None:
    if isinstance(x, B) and x.value:
        pass

class A:
    pass
class B(A):
    value = 0
```
Here, mypy reports that `x` doesn't have a field `value`. This can of course be solved with a cast, but that is annoying to type and clutters the code. At least in simple case, mypy could infer that `x` is of type `B` in the rhs of the and-statement and in the block following the if-statement.

**Comment by rwbarton** [comment]
The original program here has worked since commit 0b151c69186f7f1a64a6900d0bb06baeaafa59c9. Also, Jukka's "another case" will be addressed by #1712, and the example with `Union[int, None]` already works under strict optional checking. So closing this as fixed.
