### ISSUE TITLE
Repeated --package arguments are ignored

### ISSUE THREAD

**Issue by eric-wieser** [python/mypy#4732]
<s>Running `mypy -m module1 -p package1 -p package2` results in only `module1` being checked.</s>

Running `mypy -p package1 -p package2` results in only `package2` being checked.

Ideally this would check all of them, but it should at least error, rather than silently passing and tricking me into thinking my annotations are valid in `package1`<s> and `package2`</s>

**Comment by gvanrossum** [comment]
Hm, we may be constrained by argparse here, but I thought it would keep the last one. Also IIRC there is a check that you pass exactly one of these -- I'm surprised that didn't fire here. Maybe you can have a look at the source?

**Comment by eric-wieser** [comment]
You're right, I extrapolated from the problem I had to what I thought the source code would also allow.

`mypy --package a --package b` is the failing invocation, which as you remark checks only the last package.

Is there any reason not to support an arbitrary mixture of these two arguments? I can put a patch together.

**Comment by gvanrossum** [comment]
Yeah, it should combine all forms of targets. Let's see if that's possible.
