### ISSUE TITLE
Wildcard for ignore missing imports?

### ISSUE THREAD

**Issue by sid-kap** [python/mypy#4737]
Is there a way to ignore missing imports for all packages that match a wildcard expression, or are a submodule of a given module? In other words, instead of writing:
```ini
[mypy-pandas.util.module_1]
ignore_missing_imports = True

[mypy-pandas.util.module_2]
ignore_missing_imports = True

...
```
I'd like something like:
```ini
[mypy-pandas.*]
ignore_missing_imports = True
```

**Comment by gvanrossum** [comment]
Does that not work? It's supposed to.

**Comment by sid-kap** [comment]
Here's a failing test case:

`mypy.ini`:
```ini
[mypy]

[mypy-testmodule.*]
ignore_missing_imports = True
```

`importTest.py`:
```python
import testmodule.stuff
```

`testmodule/__init__.py` is an empty file.

`testmodule/stuff.py`:
```
import sdfsdf
```
Running `mypy importTest.py` gives the error:
```
testmodule/__init__.py:1: error: Cannot find module named 'sdfsdf'
testmodule/__init__.py:1: note: (Perhaps setting MYPYPATH or using the "--ignore-missing-imports" flag would help)
```

**Comment by gvanrossum** [comment]
Curious (not a rebuttal but a possible workaround) -- does adding a section for `[mypy-sdfsdf]` work?

**Comment by sid-kap** [comment]
Yep, that works.
Doing that for every transitive dependency would be tedious, but I've managed to work around it for my project by adding `follow_imports = skip` to every module I'm depending on that was giving me these errors.

**Comment by gvanrossum** [comment]
Arguably it's more precise the way it currently works, don't you think?

If a given module A is missing you'd want it marked as missing regardless of where it's being imported from.

Conversely, if a module X is importing A and B, and A is known to be missing but B should exist, you don't want to say "ignore all missing imports from X" since then when at a later time B accidentally goes missing it won't be flagged -- it would silently be replaced with Any.

**Comment by sid-kap** [comment]
Yep, that makes sense to me. I had misunderstood the conversation at https://github.com/python/mypy/pull/3795 to mean that this ignores missing imports both **from** and **of** the wildcarded modules. But now I realize that it only ignores imports **of** those modules—which, I'm now convinced, is the right behavior. Thanks!
