### ISSUE TITLE
Feature request: access modifiers

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#4740]
Now that Python has type annotations, I suggest adding access modifiers.  “[Access modifiers](https://en.wikipedia.org/wiki/Access_modifiers) (or access specifiers) are keywords in object-oriented languages that set the accessibility of classes, methods, and other members.”  Like type annotations, access modifiers give the linter the opportunity to catch bugs early, and give the programmer a uniform way to specify invariants to readers.

Unlike type annotations, access modifiers probably wouldn't need any new syntax, but they should be well thought-out.  My rough idea is to have some decorator on methods and properties describing who is allowed to call those methods and access those properties.  The allowed caller list is a list of base classes, functions, or lists thereof (e.g., a list of friends).

This is better than the "public, protected, private" approach that C++ takes because it would make the [visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern) much nicer.  Otherwise, you need to either

- make visitors "friends" and have the methods they call be private, or
- worse yet, just make the methods that visitors call public.

With rich decorators you could specifically mark the part of the interface that visitors call for use by the visitor class.  If you had more than type of object interacting with a class, you could specify which parts of your interface you expect to be used by each type of object.

It would also be nice to mark methods for use by a particular test function.  That would make it readily apparent which methods were not covered (or at least called) by any test.

Small classes might not benefit from such annotations.  It's the large classes that are related to many parts of the code, that could take most of advantage of such a mechanism.

**Comment by ethanhs** [comment]
This sounds like a suggestion for either the typing bug tracker or better yet the python-ideas mailing list (as this isn't really mypy specific, but a language request). However, I will say that access modifiers have been suggested many times in the past and have not gone into the language. One of the tenets of Python is "we are all consenting adults", so making everything "public" isn't such a terrible thing. Furthermore it vastly simplifies interacting with an interface.

**Comment by NeilGirdhar** [comment]
@ethanhs I posted it on python-ideas, and was asked to post it here.  It does make sense that MyPy might be the kind of project that would absorb various kinds of annotations.

That said, I disagree with the consenting adults metaphor applying to access protection *annotations* since the annotations don't stop you from doing whatever you want.  They merely prevent bugs and express intent—just like they do in other languages.

**Comment by JukkaL** [comment]
@NeilGirdhar I think that access modifiers would fit in with other goals mypy (as an optional feature -- everything would be public by default), with the caveat that moving beyond a simple public/private/protected distinction would likely result in some pretty hard design decisions, and frankly I don't think that the mypy core team has the bandwidth for the discussion right now. This is something that is worth a deeper consideration some time in the future, but other things are more important right now. You can try moving the discussion to the typing tracker. It would help a lot if you had a concrete proposal instead of just a general idea.

**Comment by ilevkivskyi** [comment]
I agree with Jukka, since we don't have much time, a more detailed/concrete proposal (rather than just an idea) would help.

**Comment by AlexWaygood** [comment]
I agree with the others on this thread: feature requests for the typing system as a whole should go to the https://github.com/python/typing repo or the [typing-sig mailing list](https://mail.python.org/archives/list/typing-sig@python.org/).
