### ISSUE TITLE
Add tests that check that the cache is written

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4742]
A recent PR broke cache writing that lead to some performance regression. To avoid such situations, we need to add a test that verifies that the cache files are written, and that their content is as expected.

**Comment by JukkaL** [comment]
I think that we already have tests that test cache files in incremental mode. We'd need a test that verifies that usable cache files are written also in non-incremental mode.

**Comment by msullivan** [comment]
I'll take this one as pennance for breaking the cache
