### ISSUE TITLE
Configuration file recognizes dash as correct but results in broken config

### ISSUE THREAD

**Issue by chingc** [python/mypy#4753]
mypy doesn't seem to be able to recognize dashed-options as incorrect within the context of a config file.

For example, suppose we have the following files `nothing.py` and `mypy.ini`

```python
def nothing():
    pass
```

```
[mypy]
X = True
```

When `X` is:
- `disallow_untyped_defs`
    - Correctly reports `nothing.py:1: error: Function is missing a type annotation`
- `disallow_untyped_defs1`
    - Correctly reports: `mypy.ini: [mypy]: Unrecognized option: disallow_untyped_defs1 = True`
- `disallow-untyped-defs`
    - Doesn't tell me I'm missing a type annotation, nor that the option is incorrect.  No errors at all!

Python 3.6.4 and mypy 0.570 were used.

**Comment by gvanrossum** [comment]
Good observation! Can you dig in the source to see what's wrong? Something is presumably normalizing the dashes to underscore, but something else doesn't seem to use the normalized version...

**Comment by chingc** [comment]
Wow, I wasn't expecting such a quick response and fix.  Thank you!
