### ISSUE TITLE
(Some) Class variables have `Any` type in methods declared above them

### ISSUE THREAD

**Issue by msullivan** [python/mypy#4760]
The following test fails, producing no error messages:
```
[case testClassVariableOrdering]
def foo(x: str) -> None: pass

class Something:
    def run(self) -> None:
        foo(self.IDS[0])  # E: Argument 1 to "foo" has incompatible type "int"; expected "str"

    IDS = [87]
[builtins fixtures/list.pyi]
```
If `IDS` is declared *above* `run`, the test passes. If `IDS` is made just an `int` instead of an int list and the call is adjusted similarly, the test passes. A `reveal_type(self.IDS)` in `run` reports `Any`.

To make matters worse, this is a mismatch with fine-grained reprocessing of `run`. The following test that fine-grained behavior matches the regular mode also fails:
```
 [case testClassVariableOrderingRefresh]
from b import bar

def foo(x: str) -> None: pass

class Something:
    def run(self) -> None:
        bar()
        foo(self.IDS[0])

    IDS = [87]

[file b.py]
def bar() -> int: return 0
[file b.py.2]
def bar() -> str: return '0'
[builtins fixtures/list.pyi]
[out]
==
```
In fine-grained mode, type-checking passes in the first iteration, but fails in the second iteration, since the type of `IDS` is now available.

**Comment by JukkaL** [comment]
We could probably fix this by deferring `Something.run` since it accesses a variable without an inferred type, instead of inferring `Any` as the type. On the second type checking pass it would have a precise type for the class variable. Hopefully this is easy to fix since a slightly modified example already works correctly:

```py
[case testInstanceVariableOrdering]
def foo(x: str) -> None: pass

class Something:
    def run(self) -> None:
        foo(self.IDS[0])  # E: Argument 1 to "foo" has incompatible type "int"; expected "str"

    def bar(self) -> None:
        self.IDS = [87]
[builtins fixtures/list.pyi]
```

**Comment by JukkaL** [comment]
This works with the new semantic analyzer. I'll prepare a PR that adds test cases.
