### ISSUE TITLE
Feature request: better support for magic methods check

### ISSUE THREAD

**Issue by pawelswiecki** [python/mypy#4784]
I'm using `Python 3.6.4` and `mypy==0.570`.

I was studying `typing.Sequence` and (I hope correctly) found out that something is a Sequence if:

- it's a **Collection**, which means it's:
  - an **Iterable** == implements `__iter__`
  - a **Container** == implements `__contains__`
  - **Sized** == implements `__contains__`
- **Reversible** == implements `__reversed__`

So I've made such a class:

``` python

class MySequence:
    def __iter__(self):
        return iter([])

    def __contains__(self, item):
        return False

    def __len__(self):
        return 0

    def __reversed__(self):
        return []
```

Unfortunately on

``` python

from typing import Sequence

s: Sequence = MySequence()

```

I'm getting `1.py:16: error: Incompatible types in assignment (expression has type "MySequence", variable has type "Sequence[Any]")`.

It wound be great for MyPy to be able to dig deeper into classes and figure out that kind of stuff. Or is there something I'm doing wrong or not undestanding?

PS So far I love MyPy, thanks for all the hard work you are putting into it!

**Comment by ilevkivskyi** [comment]
This has been discussed before. First of all it was decided that only "small" ABCs in `typing` should behave as protocols (i.e. you don't need to list them as explicit base classes). Second, you can check in Python docs that `Sequence` implements more methods (8 in total IIRC), so your class is actually not a `Sequence`. The solution would be to just add `Sequence` as a base class:
```python
class MySequence(Sequence):
    ...
```

I would propose to close this issue unless @gvanrossum changed his mind and wants to make `Sequence` a proptocol.

**Comment by pawelswiecki** [comment]
Thank you for clarification and a tip about adding Sequence as base class. I should have study issue list more deeply. 

Again, thank you for your effort!

**Comment by gvanrossum** [comment]
Let's have that discussion (about making the remaining ABCs in typing.py Protocols) as part of the review discussion for PEP 544, which still requires some discussion (and IIRC there are one or two details I'd like to fix before we finalize it).

PS. It's "mypy", not "MyPy". :-)
