### ISSUE TITLE
FileSystemCache leaks memory via __traceback__

### ISSUE THREAD

**Issue by eric-wieser** [python/mypy#4807]
FileSystemCache caches exceptions, which I think means it also caches `__traceback__`. This is bad, because:

* `__traceback__` is a big memory leak (citation needed)
* The traceback is not representative of the actual failing call

This might be to blame for the OOM in #4693

**Comment by ethanhs** [comment]
Based on my comment [here](https://github.com/python/mypy/pull/4809#issuecomment-376747428), I think this can be closed. If you have data pointing to a memory leak, please feel free to open a new issue.
