### ISSUE TITLE
User-specific config file

### ISSUE THREAD

**Issue by OmeGak** [python/mypy#4815]
Feature request. According to my search-fu, it hasn't been discussed yet.

`mypy` with no `--config-file` specified will check for `mypy.ini` first, use to `setup.cfg` otherwise, and ultimately fallback to the built-in defaults if none of them are present. I would like to have a user-default config that would be used instead. Would it be too crazy to check for `~/.mypy.ini` before falling back to the built-in defaults?

I would find this useful for quick prototyping without having to copy&paste my preferred configuration from other projects. It's also quite a common pattern in other static analysis tools like linters.

**Comment by gvanrossum** [comment]
This looks like a simple project which you can probably do yourself in a
few lines -- just submit a PR.

**Comment by OmeGak** [comment]
Sure! Happy to tackle it.

**Comment by dsifford** [comment]
Nice work @OmeGak 

Curious what your thoughts are on adding to this commit to support the XDG base directory specification? 

[Details here](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support#XDG_Base_Directory_specification).
[Spec here](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

My home directory thanks you in advance :pray:

**Comment by OmeGak** [comment]
Not a strong opinion on XDG base directory. It wouldn't hurt complying with the specs, I guess. Maybe you could create a new issue proposing the idea for people to discuss it first?

**Comment by OmeGak** [comment]
Not a strong opinion on XDG base directory. It wouldn't hurt complying with the specs, I guess. Maybe you could create a new issue proposing the idea for people to discuss it first?
