### ISSUE TITLE
Consider switching to setuptools

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#482]
Switching to setuptools could have benefits, but it's not obvious how to do it because mypy has .py files as data.

This pull request contains more discussion:

https://github.com/JukkaL/mypy/pull/346

**Comment by ethanhs** [comment]
Might it be time to re-evaluate this? I was sitting down to work on the bytes interpolation bug and I ran `python setup.py develop` expected setuptools. Most of the discussion on this seems to be over 2 years old. I hope setuptools has progressed since then....

**Comment by ambv** [comment]
This is actually in the works by means of PR #2452. Currently blocked on somebody testing the PR on Windows.

**Comment by ethanhs** [comment]
As it would happen I dual boot, so I can check on my Windows part.

**Comment by gvanrossum** [comment]
That would be great. Can you build a distro under Linux and then test on
Windows? Be sure to test that it actually type checks some code and
produces some expected errors.

--Guido (mobile)

**Comment by ethanhs** [comment]
Of course. Probably can't do that now, but will make sure to do it today.

**Comment by ethanhs** [comment]
We are now using setuptools, so this can be closed.
