### ISSUE TITLE
complex does not SupportComplex

### ISSUE THREAD

**Issue by alanhdu** [python/mypy#4824]
In the following snippet of code:

```python
from typing import SupportsComplex

def f(x: SupportsComplex) -> complex:
    return complex(x)
f(3j)
```

`mypy` complains with:

```python
test.py:4: error: No overload variant of "complex" matches argument types [typing.SupportsComplex]
test.py:5: error: Argument 1 to "f" has incompatible type "complex"; expected "SupportsComplex"
```

I was running this with `mypy 0.580` on Python 3.6

**Comment by gvanrossum** [comment]
Looks ike a typeshed issue -- you can submit a PR yourself!

**Comment by ethanhs** [comment]
Should this be closed? Maybe a few tests of this and other numeric interactions wouldn't hurt?

**Comment by gvanrossum** [comment]
This issue can be closed if there's a replacement issue in typeshed or if
it's been fixed in typeshed. I don't think this would have been found if we
had had "a few tests of numeric interactions" so I'm not in favor of adding
such tests now.

**Comment by msullivan** [comment]
It's been fixed in typeshed
