### ISSUE TITLE
Better support for error/hint location

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4829]
In view of planned editor integration support I think there are two important things to do in addition to fixing relevant high-priority issues like https://github.com/python/mypy/issues/3871 that require updating `typed_ast`:
* Make a thorough walk through the code and fix all places where column is not set correctly, there are still quite a few such places I think, see also https://github.com/python/mypy/issues/4276.
* Design an API to quickly find a node object by file name, line number, and column. This will be needed at later stages when we will need to return type of a node (or some other info like accessible attributes) by request from the editor.

**Comment by JukkaL** [comment]
Column numbers are now set pretty reliably already (#7053). The second goal is no longer a priority (but it's possible that we'll revisit the idea at some point in the future).
