### ISSUE TITLE
Provide an option for more detailed error messaging.

### ISSUE THREAD

**Issue by glenjamin** [python/mypy#4835]
* Are you reporting a bug, or opening a feature request?
Feature Request

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

Sort of not applicable, but the code I'm currently using is https://github.com/ministryofjustice/git-secrets-ahoy/tree/de82eb2d91756c354bbabece6c2665be5cec8a97

* What is the actual behavior/output?
Error message for duplicate incompatible definition:
```
type-stubs/gitdb/__init__.pyi:6: error: Name 'base' already defined
```

Error message for incompatible with supertype
```
type-stubs/git/refs/reference.pyi:15: error: Signature of "iter_items" incompatible with supertype "Iterable"
```

* What is the behavior/output you expect?
Something along these lines for duplicate incompatible definition:
```
type-stubs/gitdb/__init__.pyi:6: error: Cannot defined name 'base' with type 'Any'. Name 'base' already defined with type 'str' in filename.pyi
```

Something along these liens for incompatible with supertype
```
type-stubs/git/refs/reference.pyi:15: error: Signature of "iter_items" (a: str) -> int incompatible with supertype "Iterable" (b: int) -> int
```

I brought this up in gitter and the general feeling was that at the moment error messages are intentionally succint to try and avoid scaring people off - but at the moment in some scenarios that succintness leads to errors which are difficult to action.

The suggestion was that perhaps more detailed error messages could be behind a flag, making them opt-in. Possibly something like `--detailed-errors`.

Some stuff that might be good to include in detailed mode:
* the types on each side of the mismatch
* the source file and line where each type was defined
* the source line where the type was imported into the current scope (maybe?)

I've used flow, a similar tool in JS quite a lot, and have found the way it handles error messaging quite approachable. Here's a sample

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKADwC4wB+bTAWwCMBTAJwEp6BnfF0LYA5mADeqMGEJQwNHpOkywXDvkxdS1ANwqAvivWbtYAEQATDlACGmGPjCDhY8-oNA

```
function foo(x: ?number): string {
  if (x) {
    return x;
  }
  return "default string";
}
```
```
    5:     return x;
                  ^ Cannot return `x` because number [1] is incompatible with string [2].
        References:
        3: function foo(x: ?number): string {
                            ^ [1]
        3: function foo(x: ?number): string {
                                     ^ [2]
```

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
mypy 0.580

* What are the mypy flags you are using? (For example --strict-optional)
```
strict_optional = True
```

**Comment by ilevkivskyi** [comment]
I think this is a good idea, especially taking into account that many people are still learning mypy and similar questions appear often on gitter. I think this is a relatively high priority. A possible way of implementing this would be to show more `note`s for most errors (as we currently do for some errors) but then only show them with the flag `--detailed-errors` (off by default). Also maybe we can find a better name for this flag (but I am already OK with this name).

**Comment by JukkaL** [comment]
I think that the current error messages are generally too terse, and we could just increase verbosity quite a bit by default (potentially by showing more notes as suggested by @ilevkivskyi). For example, showing the types in the subclass and base class would probably be okay, and also showing the location of the base class definition as a note would be fine as well. However, doing the exact equivalent of Flow may be a bit too much, at least for now, since we don't have easy access to required bits of information.

**Comment by ilevkivskyi** [comment]
I think this is something we can consider for PyCon sprints. This is a larger issue, but it is still suitable for someone already experienced in mypy development (or even mypy core team if someone doesn't want just review PRs :-))

**Comment by ilevkivskyi** [comment]
Me and @JukkaL had a short discussion and propose to postpone this for now. Instead we should try  to always show "right" amount of verbosity in error messages depending on context, like we do for protocol related errors.

**Comment by JukkaL** [comment]
I think that `--pretty` and improving existing messages to show more detail as needed is sufficient, so there's no need to keep this issue open,
