### ISSUE TITLE
No library stub file for module XXX

### ISSUE THREAD

**Issue by Elaoed** [python/mypy#4851]
Any one please explain to me why this error occur almost every import. 
What does library stub file means. And how can i fix them?

by the way. Im using python3.6 on macos

**Comment by gvanrossum** [comment]
Which modules specifically? Stubs are defined in typeshed.

**Comment by kornicameister** [comment]
Just hit me for `flask`, also wonder why exactly this is happening and what's the purpose. Would be great to understand ;-)

**Comment by gvanrossum** [comment]
Docs are here:
http://mypy.readthedocs.io/en/latest/basics.html#library-stubs-and-the-typeshed-repo

**Comment by vsvasya** [comment]
Link above does not work now, found docs here: http://mypy.readthedocs.io/en/latest/getting_started.html#library-stubs-and-typeshed
