### ISSUE TITLE
Throw error when assign string to dict like object

### ISSUE THREAD

**Issue by Semooze** [python/mypy#4859]
I run mypy with this code

from typing import Dict, Union

```
settings = dict()
settings['APP'] = {
    'HOST': '127.0.0.1',
    'PORT': 8080
}

settings['PLATFORM'] = 'http://localhost:8080'

settings['DATABASE'] = {
    'PGHOST': test1,
    'PGUSER': test2,
    'PGDBNAME': test3
}
```

with command

```
mypy directory/ --ignore-missing-imports
```

It show this error:

error: Incompatible types in assignment (expression has type "str", target has type "Dict[str, object]")

Does this mean mypy can not detect expression and target correctly ?

Python 3.6.3
mypy 0.580

Edited: 
Add settings = dict()

**Comment by ethanhs** [comment]
You don't show it, but I presume `settings` is a `Dict`. Mypy does its best to infer the type of the `Dict`, but sometimes, it is unable to do so, or doesn't infer what you want. In this case you need to annotate it to guide mypy. So I'm guessing (based on the code you have provided) that you probably want to do `settings = ...  # type: Dict[str, Any]` as a start. 

You may also want to read https://mypy.readthedocs.io/en/latest/common_issues.html#types-of-empty-collections and https://mypy.readthedocs.io/en/latest/dynamic_typing.html#any-vs-object for some background. 

`TypedDict`, which allows for finer typing of dictionaries seems apt here as well https://mypy.readthedocs.io/en/latest/kinds_of_types.html#typeddict

**Comment by Semooze** [comment]
Work well in this case and another case that I faced. Thank you.
