### ISSUE TITLE
Functional enum.IntEnum API does not accept List[Tuple[str, int]]

### ISSUE THREAD

**Issue by osandov** [python/mypy#4865]
The following code:

```
import enum
from typing import Any, List, Tuple


def f(members: List[Tuple[str, int]]) -> enum.IntEnum:
    return enum.IntEnum('Test', members)
```

Gives the following error:

```
test.py:6: error: No overload variant of "IntEnum" matches argument types [builtins.str, builtins.list[Tuple[builtins.str, builtins.int]]]
```

If I change the `members` argument annotation to Any, there is no error. Additionally, if I use `Enum` instead of `IntEnum`, there is no error.

This is on Python 3.6 and mypy 0.570 and latest git (0.590-dev-3346cfad75374c096b1dd8024df24ce50f18a35c).

**Comment by JukkaL** [comment]
This is too dynamic for mypy to figure out. Mypy needs to know the values inside the `members` list to do type checking. If you dynamically generate type objects, you won't generally get type checking there. You can use `Any` types and/or `# type: ignore` to silence mypy errors, though.
