### ISSUE TITLE
[Feature Request] Support for a type comment inside of a docstring

### ISSUE THREAD

**Issue by Kangaroux** [python/mypy#4870]
## Request
If a function is defined and includes a docstring as per PEP8/PEP257, and you wish to provide type checking in the form of a comment, then the type checking comment must come before the docstring. This can be difficult to read and violates the docstring recommendations. An improvement would be to allow the type comment to be defined inside the docstring.

## Example
Before:

```python
def add(a, b):
  # type: (int, int) -> int
  """ Returns the sum of two numbers """
  return a + b
```

After:

```python
def add(a, b):
  """ type: (int, int) -> int
  Returns the sum of two numbers
  """
  return a + b
```

**Additionally,** because the type comment must start with `type:`, it's reasonable to say that this could appear at any point in the docstring. Traditionally, docstrings that include info on params and return value will do so at the end of the docstring. With that being said, this should also be valid:

```python
def add(a, b):
  """ Returns the sum of two numbers
      
  type: (int, int) -> int
  """
  return a + b
```

**Comment by gvanrossum** [comment]
This is not going to happen. We debated various ways of parsing types from docstrings during the creation of PEP 484 and decided it's not going to happen. Sorry to disappoint.

**Comment by Kangaroux** [comment]
@gvanrossum That's understandable. May I ask why a decision was made to not go this route?
