### ISSUE TITLE
Installed stubs not always taking precedence in PEP 561 implementation

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4876]
I installed a package with inline type annotations using `python setup.py install` and installed the corresponding stubs package using `python setup.py install --user`. Mypy picked up the inline type annotations instead of the stubs, even though I'd expect that a stub package takes precedence. I suspect that this is caused by the package and the stubs being in different directories, and that the order in which we search through the directories may affect which types will be used by mypy.

@ethanhs Can you take a look at this?

**Comment by gvanrossum** [comment]
AFAIK this was intentional -- the search finds the first directory that has
either a .py or a .pyi file, and then prefers .pyi over .py -- but it
doesn't continue to search for .pyi files further down on the path if the
first hit has only a .py file.

Perhaps with PEP 561 we want to change this?

**Comment by JukkaL** [comment]
I guess either approach could be okay, as long as it's clearly documented. Also, it would be good to have a way for mypy to print out the full search path, in case mypy isn't finding the expected stubs/annotations. `mypy -v` could be modified to do this, for example.

**Comment by ethanhs** [comment]
The PEP is not specific here (see the section about this https://www.python.org/dev/peps/pep-0561/#type-checker-module-resolution-order), perhaps it should be. I think within the category of "installed packages" it shouldn't matter where they are installed. I have a simple patch which should fix this. (PR incoming)
