### ISSUE TITLE
Documenting TypeVars with Sphinx and autodoc

### ISSUE THREAD

**Issue by gpkc** [python/mypy#4882]
I'm using Sphinx to document a package, and there is an extension called [sphinx-autodoc-typehints](https://github.com/agronholm/sphinx-autodoc-typehints) that uses type annotations automatically. It works well for documenting common type hints, however, there is no clear way how one would document generics using TypeVars. For example:

```python
class MyBase:
    """MyBase Doc"""

T = TypeVar('T', bound='MyBase')

class OtherClass:
    """OtherClass Doc"""
    def create_T(cls: Type[T]) -> T:
        """create_T Doc"""
        return cls()
```
I have opened an issue in their repo, but we would like some input on how that could be accomplished:
https://github.com/agronholm/sphinx-autodoc-typehints/issues/39

**Comment by hauntsaninja** [comment]
Seems like there's much more discussion on the other issue and not any action for mypy
