### ISSUE TITLE
OrderedCounter copy method incompatible base class definitions

### ISSUE THREAD

**Issue by iliakur** [python/mypy#4891]
This is definitely not a feature request, though I'm not sure yet if it's a bug either, I'm new to type hints and may have missed something very basic.

We are using the `OrderedCounter` class exactly as defined [here](https://docs.python.org/2/library/collections.html#ordereddict-examples-and-recipes).
For convenience, here's the code from there again:

```
from collections import Counter
from collections import OrderedDict


class OrderedCounter(Counter, OrderedDict):
    """Counter that remembers the order elements are first seen"""
    def __repr__(self):
        return "%s(%r)" % (self.__class__.__name__, OrderedDict(self))

    def __reduce__(self):
        return self.__class__, (OrderedDict(self),)
```
This code is sitting in a file on its own and when I run `mypy` on this file, I get this error:
```
error: Definition of "copy" in base class "Counter" is incompatible with definition in base class "OrderedDict"
```

The question "am I doing something wrong here?" seems a bit odd in this context since I'm literally just using code from the documentation.
I haven't found anything helpful online, so I figured I'd ask here.

Bookkeeping:
* python version = 3.6.3
* mypy version = 0.580 
* I have also tried the git master version of `mypy`, got the same error.
* No extra flags

**Comment by JelleZijlstra** [comment]
I haven't looked at this in detail, but this is probably fixable in typeshed. My guess is we'll have to change some method definition to `def copy(self: _T) -> _T: ...`.
