### ISSUE TITLE
f-string with type error gets put at line number 1 sometimes

### ISSUE THREAD

**Issue by euresti** [python/mypy#4896]
I had a type error inside an f-string which marked the error as happening on line number 1. While trying to get a small repro I noticed it only happens some of the time:

```
def x(b:int) -> None:
    one = b.foo             # Good
    two = b.foo.bar         # Good
    three = f"{b.foo}"      # Good
    three = f"{b.bar}"      # Good
    three = f"{b.baz}"      # Good
    four = f"{b.foo.bar}"   # Error shows up on line 1
    five = f"{b.bar + b.baz}"   # Errors show up on line 1
```

Here are the errors that get shown:
```
tt.py:1: error: "int" has no attribute "foo"
tt.py:1: error: "int" has no attribute "bar"
tt.py:1: error: "int" has no attribute "baz"
tt.py:2: error: "int" has no attribute "foo"
tt.py:3: error: "int" has no attribute "foo"
tt.py:4: error: "int" has no attribute "foo"
tt.py:5: error: "int" has no attribute "bar"
tt.py:6: error: "int" has no attribute "baz"
```

It's odd that only certain type errors get sent to line 1.

Using mypy 0.580

**Comment by ethanhs** [comment]
This is a bug in the ast that @ambv fixed a while ago. This will be fixed when I complete updating typed_ast to the 3.7 version (I'm about halfway through). The tracking issue for this is https://github.com/python/typed_ast/issues/56

**Comment by ethanhs** [comment]
>multiline f-strings are still going to show a rather wrong location and that's tricky to fix.

Yes, sadly that is true. However, we want bug for bug compatibility, so this is the price we pay :)

**Comment by ambv** [comment]
Well, man, if you are able to fix multiline f-string locations, by all means submit a PR to CPython as well!
