### ISSUE TITLE
Confusing behavior with `raise Class`

### ISSUE THREAD

**Issue by bwo** [python/mypy#4897]
```python
from typing import Type, Mapping, TypeVar


class Foo(Exception):
    pass


class Bar(Foo):
    pass


m = {1: Bar, 2: Foo}  # Mapping[int, Type[Foo]]


def f(i):
    # type: (int) -> Type[Foo]
    return m[i]


def x():
    # type: () -> None
    reveal_type(f(1))
    raise f(1)


def y():
    # type: () -> None
    reveal_type(m[1])
    raise m[1]


# for completeness's sake
def huh(*args, **kwargs):
    # type: (*object, **object) -> Foo
    return Bar()


def z():
    # type: () -> None
    reveal_type(huh)
    raise huh
```

The first `reveal_type` shows that `f(1)` returns a `Type[Foo]`; `x()` does not typecheck, with the error "Exception must be derived from BaseException".

The second `reveal_type` shows that `m[1]` is `def (*args: builtins.object, **kwargs: builtins.object) -> foo.Foo`. `y()` typechecks.

The third `reveal_type` shows that `huh` is `def (*args: builtins.object, **kwargs: builtins.object) -> foo.Foo`. `z()` does not typecheck (same error as `x()`).

**Comment by gvanrossum** [comment]
Could you describe in English what you think is wrong and what you would
expect instead? It's a rather long example to try and understand.

**Comment by JelleZijlstra** [comment]
Here's a really short repro:
```
$ python3.6 -m mypy -c 'from typing import Type; X: Type[Exception]; raise X'
<string>:1: error: Exception must be derived from BaseException
```
`mypy -c 'raise Exception'` works fine though.

mypy seems to not realize that `Type[Exception]` is compatible with `raise`.

**Comment by bwo** [comment]
@gvanrossum sorry, though @JelleZijlstra has basically got it.

If I have a `Type[Exception]` (as returned by `f`), I ought to be able to raise it, but instead, mypy complains.

mypy does *not* complain if I just write `raise Bar`, but it also thinks (according to `reveal_type`) that `Bar` is a function type returning a an instance of `Bar`. It will, however, complain if I type `raise huh`, even though `reveal_type(huh)` and `reveal_type(Bar)` have identical output.

**Comment by bwo** [comment]
Sure, but I could do with a pointer as to where to start.

**Comment by Michael0x2a** [comment]
@bwo -- A good starting point is often to grep for the error message -- you can then see where it's called, attach a breakpoint, etc.

To save you a little bit of work, you'll probably want to start with the `type_check_raise` method in `mypy/checker.py`.
