### ISSUE TITLE
Ignore modules with parse errors

### ISSUE THREAD

**Issue by lrem** [python/mypy#491]
Currently mypy does not support full Python 3 syntax. When importing a module with unsupported syntax, it stops running. A better strategy could be to bail for the unparsable module, but continue for the importing one, marking everything imported as untyped.

**Comment by ethanhs** [comment]
I think we support all of Python 2 and 3 syntax now 🙃

I think this means we should bail on unparsable syntax, and that this issue should be closed, as we may not be able to resolve names, and it would ruin type checking.

**Comment by JukkaL** [comment]
Yeah, this doesn't seem important any more.
