### ISSUE TITLE
Instantiate Generic type

### ISSUE THREAD

**Issue by gpkc** [python/mypy#4914]
Is it possible to do something like this?
```python
T = TypeVar('T')

class MyClass(Generic[T]):
    def __init__(self):
        self.t_inst = T()

x = MyClass[list]()  # type(x.t_inst) = list
```
It would be similar to this example, from the documentation:
```python
T = TypeVar('T', bound='Friend')

class Friend:
    other = None  # type: Friend

    @classmethod
    def make_pair(cls: Type[T]) -> Tuple[T, T]:
        a, b = cls(), cls()
        a.other = b
        b.other = a
        return a, b
```
But without the need to pass in the class itself. Without this, the above example would have to be adapted to look like:
```python
T = TypeVar('T')

class MyClass(Generic[T]):
    def __init__(self, cls: Type[T]):
        self.t_inst = cls()

x = MyClass[list](list)  # type(x.t_inst) = list
```
Which is at least redundant because in `MyClass[list](list)` `list` must be repeated.

**Comment by ethanhs** [comment]
Fundamentally, runtime and static types aren't one to one. So don't pass runtime types using static typing constructs like `Generic` (which is what you are doing in your first example). With your `cls` example, I was able to instantiate `MyClass` without providing the generic type. Mypy is able infer from the argument to `__init__` what type `T` is.

So `x = MyClass(list)` works fine.

**Comment by ilevkivskyi** [comment]
All types are erased at runtime, moreover allowing this will require fundamental changes to how Python interpreter works.

All the static types are just _annotations_, i.e. roughly some kind of machine readable documentation, so that a type checker can verify that your intent is consistent with Python semantics.
