### ISSUE TITLE
--python-version broken on mypy 0.590

### ISSUE THREAD

**Issue by jreese** [python/mypy#4923]
With mypy 0.580 and python 3.6, I can run:

    $ mypy --python-version 3.5 <module>

This worked fine, and would catch things like use of f-strings that aren't back-compatible.

With mypy 0.590 however, this breaks with the following error:

    mypy: error: Error: failed to find a Python executable matching version (3, 5), perhaps try --python-executable, or --no-site-packages?

I am running this against latest master from https://github.com/jreese/aiosqlite

Full repro: https://gist.github.com/jreese/c20759267e08aa45b7ce4a29747f5337

**Comment by JelleZijlstra** [comment]
You need to add the `--no-site-packages` flag to run mypy for a specific version without an accessible executable.

**Comment by jreese** [comment]
Yep, that did it.  I saw that suggestion in the error message (on travis) and tried it on my local machine, but it claimed that didn't exist.  Turns out, I still had an old version of mypy installed locally when testing that fix, and didn't retest that fix while generating the repro.

Sorry for the noise.  Cheers!
