### ISSUE TITLE
Dict type does not work with TypeVar?

### ISSUE THREAD

**Issue by hexdump2002** [python/mypy#4928]
I'm trying to create a little service locator. All services are children classes of BaseService class. I use registerService method to register a service class type with its instance and it is stored in the _services Dict. Then you can get the service instance calling getService with the class type needed. Example:

```
    ServiceLocator.instance().registerService(LogService,LogService())
    logServiceInstance =ServiceLocator.instance().getService(LogService)
```

* Please insert below the code you are checking with mypy:
  ```
    E = TypeVar('E', bound=BaseService)


    class ServiceLocator(QObject): #type: ignore

        _instance = None;
        allServicesInited = pyqtSignal()

        def __init__(self) -> None:
            super().__init__()
            self._instance = self

            self._services: Dict[Type[E], E] = {} # This gives error: Invalid type "servicelocator.E"
    
        def registerService(self, t: Type[E], instance: E)->None:
            self._services[t]=instance
        def getService(self,service: Type[E])-> E:
            return self._services[service]
```
* What is the actual behavior/output?
I get error: Invalid type "servicelocator.E" at the line where the Dict annotation is added.

* What is the behavior/output you expect?
No errors

* What are the versions of mypy and Python you are using?
Python 3.6.4 and MyPy 0.590

* What are the mypy flags you are using? (For example --strict-optional)
--ignore-missing-imports --strict
```
Shouldn't this work correclty?

**Comment by noporpoise** [comment]
I think I'm having a similar issue, but with the `Type` as the dict value rather than key: 

    from typing import TypeVar, Type, Dict


    class A:
        pass


    class B(A):
        pass


    class C(A):
        pass


    T = TypeVar('T', bound=A)
    d = {}  # type: Dict[str, Type[T]]  # <-- line17: this line triggers the error


Getting the following error:

    $ mypy test.py
    test.py:17: error: Invalid type "test.T"

**Comment by gvanrossum** [comment]
@noporpoise No, that's unrelated -- you're using a type variable outside a generic class or function. If you need more help with that please use the Gitter channel (see project README).

**Comment by finswimmer** [comment]
Hey,

my issue seems to be similar. A `dict` should hold a Class as the key and an instance of this class as the value.

```py
from typing import TypeVar

_T = TypeVar("_T")


class RepositoryA:
    def __init__(self) -> None:
        ...

    def some_method(self) -> None:
        ...


class Service:
    def __init__(self, repositories: dict[type[_T], _T]) -> None:
        self.repositories = repositories

    def do_something(self) -> None:
        self.repositories[RepositoryA].some_method()


service = Service(repositories={RepositoryA: RepositoryA()})
```

`mypy` output is:

```
typehints.py:19: error: "_T" has no attribute "some_method"  [attr-defined]
typehints.py:19: error: Invalid index type "type[RepositoryA]" for "dict[type[_T], _T]"; expected type "type[_T]"  [index]
Found 2 errors in 1 file (checked 65 source files)
```

```
mypy --version            
mypy 1.4.1 (compiled: yes)
```

Is this somehow expected? If so what's the correct way to express it?

fin swimmer

**Comment by hauntsaninja** [comment]
I don't think any of the issues reported here are bugs. In particular, modern mypy provides a clearer error for OP's issue.

@finswimmer type variables only really make sense in the context of generic classes, functions or aliases that can bind them. While I think I get what you're trying to spell, allowing variables to bind type variables would probably end up being a footgun. Maybe worth asking on https://github.com/python/typing to see if people have more coherent takes. In the meantime, I think the best you can do with existing type checkers / existing type system is:
```
from typing import Any, Protocol, TypeVar

T = TypeVar("T")

class Repo(Protocol):
    def __getitem__(self, __o: type[T]) -> T: ...

class RepositoryA:
    def __init__(self) -> None: ...
    def some_method(self) -> None: ...

class Service:
    def __init__(self, repositories: dict[type, Any]) -> None:
        self.repositories: Repo = repositories

    def do_something(self) -> None:
        self.repositories[RepositoryA].some_method()

service = Service(repositories={RepositoryA: RepositoryA()})
```
