### ISSUE TITLE
Metaclass operators not respected by TypeVar bounds

### ISSUE THREAD

**Issue by alanhdu** [python/mypy#4929]
Using `mypy 0.590`, running `mypy` on the following code:

(EDIT: See https://github.com/python/mypy/issues/4929#issuecomment-383166651 for a smaller test case)

```python
import ctypes
from typing import Type, TypeVar

S = TypeVar("S", bound=ctypes.Structure)

def f(x: Type[ctypes.Structure]) -> ctypes.Array[ctypes.Structure]:
    return (x * 0)()
def g(x: Type[S]) -> ctypes.Array[S]:
    return (x * 0)()
```

fails with

```
test.py:9: error: Unsupported operand types for * ("Type[S]" and "int")
test.py:9: error: "int" not callable
```

But AFAICT, `g` should be perfectly valid -- because it has a bound of `ctypes.Structure` (which supports multiplication with integers), it should also support multiplication with integers.

**Comment by ilevkivskyi** [comment]
There is `__mul__` and `__rmul__` on a metaclass. This may be a real bug in mypy, operators are special cased (probably old code) instead of re-using `checkmember`, therefore corner cases (like access via bound via metaclass) is not treated correctly unlike the latter one. This needs some refactoring I think. I left a TODO in code while previously fixing a similar corner case, it looks like we need to implement that TODO.

**Comment by kamahen** [comment]
There are a lot of missing test cases for "magic" methods ... I'm putting together a PR for adding test cases, but it's not high on my priority list.

**Comment by alanhdu** [comment]
@JelleZijlstra @ilevkivskyi To be more precise, the inheritance looks like:

```python

class _CDataMeta(type):
    # By default mypy complains about the following two methods, because strictly speaking cls
    # might not be a Type[_CT]. However this can never actually happen, because the only class that
    # uses _CDataMeta as its metaclass is _CData. So it's safe to ignore the errors here.
    def __mul__(cls: Type[_CT], other: int) -> Type[Array[_CT]]: ...  # type: ignore
    def __rmul__(cls: Type[_CT], other: int) -> Type[Array[_CT]]: ...  # type: ignore
class _CData(metaclass=_CDataMeta): ...
class _StructUnionMeta(_CDataMeta): ...
class _StructUnionBase(_CData, metaclass=_StructUnionMeta): ...
class Structure(_StructUnionBase): ...
```

**Comment by alanhdu** [comment]
A more minimal reproduction:

```python
from typing import Type, TypeVar

class MetaClass(type):
    def __mul__(cls, other: int) -> str:
        return ""

class Test(metaclass=MetaClass):
    pass

S = TypeVar("S", bound=Test)

def f(x: Type[Test]) -> str:
    return x * 0
def g(x: Type[S]) -> str:
    return x * 0
```

returns

```
test.py:15: error: Incompatible return value type (got "int", expected "str")
test.py:15: error: Unsupported operand types for * ("Type[S]" and "int")
```
