### ISSUE TITLE
Auto-correct misspellings of module attribute names

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4934]
Mypy can suggest correct spellings for some attributes, but it doesn't seem to work for module attributes:

```py
from subprocess import popen  # Module 'subprocess' has no attribute 'popen'

import subprocess
subprocess.popen  # Module has no attribute "popen"

class Foobar:
    def do_it(self): pass
foobar  # Name 'foobar' is not defined

Foobar().doit()  # "Foobar" has no attribute "doit"; maybe "do_it"?
```

It would be better if mypy would suggest corrections for all of the cases in the above example.

Marking as high priority since this should be easy to fix and pretty high impact.

**Comment by JukkaL** [comment]
#4926 is an example where this would have been useful.

**Comment by gvanrossum** [comment]
I'm not sure I'd call this high priority, compared to all the other open high priority issues.

**Comment by JukkaL** [comment]
Fair enough, marking as normal priority.

**Comment by marcodoordash** [comment]
looking at this issue

**Comment by marcodoordash** [comment]
@JukkaL as per our conversation, I referenced this in #824 as they partially overlap - could you please close this one?

**Comment by ilevkivskyi** [comment]
Closing in favor of #824
