### ISSUE TITLE
Subtype incompatibility between Dict[str, Union[str, int]] and Dict[str, str]

### ISSUE THREAD

**Issue by macfreek** [python/mypy#4935]
The following code works fine, as expected:

    from typing import Dict, Union, Any
    
    my_var = 42  # type: Union[str, int]
    viking_var = "spam"
    my_var = another_var  # works fine

However, the following fails for mypy (tested with 0.590):

    my_dict = {"ham": "bacon", "eggs": 42}  # type: Dict[str, Union[str, int]]
    viking_dict = {"ham": "bacon", "eggs": "spam"}
    my_dict = viking_dict  # error

The error is: `error: Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "Dict[str, Union[str, int]]")`

I expected this to be a compatible assignment. Is this intentional behaviour or a known limitation of mypy? Is there a way to fix this (other than resorting to a `Dict[str, Any]` type)?

PS: I'm aware that the fix in this sample code is to simply set the type of `viking_dict` to `Dict[str, Union[str, int]]`. Unfortunately, in my actual code this is not possible, as `Dict[str, str]` is the designed return type of a function. Regretfully, there are no spam-chanting Vikings in my actual code.

**Comment by ilevkivskyi** [comment]
`Dict` is invariant in value type, please read http://mypy.readthedocs.io/en/latest/common_issues.html#invariance-vs-covariance and http://mypy.readthedocs.io/en/latest/generics.html#variance-of-generics
