### ISSUE TITLE
IntEnum "is not indexable"

### ISSUE THREAD

**Issue by alexmv** [python/mypy#4941]
```
from enum import IntEnum
Color = IntEnum('Color', 'red green blue')
Color['green']
```
...yields:
```
test.py:3: error: Value of type "Type[Color]" is not indexable
```

This example is more or less [straight out of the enum docs](http://cpython-test-docs.readthedocs.io/en/latest/library/enum.html#programmatic-access-to-enumeration-members-and-their-attributes) -- my expectation is that it should not be a type error.

Mypy version 025e3decfaa95f42c721c4662cdf2dd748db06a3

**Comment by ilevkivskyi** [comment]
Note that this problem is absent for a simple `Enum`. Also `IntEnum` fails the following code:
```python
for c in Color:  # E: not iterable
    reveal_type(c)
```
I thought this should be fixed by https://github.com/python/mypy/pull/4319 @elazarg what do you think?

**Comment by elazarg** [comment]
It only happens for functional api of non-`Enum` enums. I will look into it.

**Comment by aalvrz** [comment]
I am experiencing this with `mypy==0.780`, with similar errors:

```
"IntEnum" not callable
"IntEnum" is not indexable
```
When doing:
```python
val = self.enum_class(value)
val = self.enum_class[value.upper()]
```
