### ISSUE TITLE
Allow stricter list/tuple unpacking

### ISSUE THREAD

**Issue by pnachum** [python/mypy#4948]
The following code doesn't produce any type errors, but crashes at runtime. It would be great to have a flag for stricter requirements when unpacking lists and tuples.
```python
def foo(a: int, b: int) -> int:
    return a + b 

foo(*[])

nums: Tuple[int, ...] = ()
foo(*nums)
```

Tested using mypy 0.570 and python 3.6.4

**Comment by ilevkivskyi** [comment]
Unfortunately, I don't see an easy way to implement this, so marking this as low-priority taking into account out current bandwidth.

**Comment by JukkaL** [comment]
Arguably this is similar to how mypy accepts code like this:

```py
a = [1, 2]
for i in range(5):
    print(a[i])  # IndexError
```

Just catching lists/tuples with an invalid length in calls would be kind of ad hoc, and keeping track of lengths of lists (and maybe integer ranges) in general would a lot of work to implement, and would still only be helpful in a narrow set of cases when we can infer these things statically.

**Comment by JukkaL** [comment]
Ah got it. 

For consistency, this option should perhaps also apply to using a dictionary in `**kwargs` (`TypedDict` would be allowed).

**Comment by gvanrossum** [comment]
I worry that this would invalidate a lot of existing code. The length of
the array may not be statically determined but the code may still be
correct.

**Comment by pnachum** [comment]
Isn't that the case for most of the flags which introduce stricter checks? 

I think the guarantee that functions are called with the correct number of arguments is pretty common in statically typed languages, and makes refactoring easier. For example, if a new argument is added to `foo`, I would want mypy to catch all the incorrect call sites, and not miss the ones that unpack a list or tuple that used to be the correct length

**Comment by JukkaL** [comment]
We can't turn an option like this on by default, but some users might want to opt in (especially if they have a new codebase). 

Another open question is if `--strict` should enable this.

Anyway, this is low priority and not worth discussing in too much detail (at least yet).

**Comment by kamahen** [comment]
`pylint` did something like the proposed check and was really annoying because its heuristics weren't good enough. (This seems to have been fixed recently, at least for a simple example I tried out.)

**Comment by JukkaL** [comment]
Closing the issue as it seems too difficult to avoid false positives, and this is probably not important enough for a new strictness option.

**Comment by thomkeh** [comment]
Maybe it could be restricted to unpacking assignment. That is

```python
t: Tuple[int, ...] = (1, 2, 3)

a, *b = t  # ok
c, d = t  # doesn't type check; we don't know the length of `t`
x, y, z = t  # also doesn't type check even though it would work
```

Non-variable-length tuples would continue to work as they are:

```python
t: Tuple[int, int, int] = (1, 2, 3)
x, y, z = t  # ok
```

This would hopefully catch some `ValueError: too many values to unpack` errors.
