### ISSUE TITLE
Plugin hooks are not called or receive incorrect names for some dunder methods

### ISSUE THREAD

**Issue by dgelessus** [python/mypy#4964]
(Taken from #4869)

When certain dunder methods are called implicitly through language syntax, the plugin function/method hooks are called incorrectly or not at all. Specifically, the following cases cause problems:

* [ ] For some dunder methods (`__setitem__`, `__iter__`, `__next__`), `get_function_hook` is incorrectly called instead of `get_method_hook`, and the passed in method name is not fully qualified
* [ ] `get_method_signature_hook` is not called for some dunder methods (`__getitem__`, `__setitem__`, `__iter__`, `__next__`)
* [x] When a `Type[...]` expression is called (that is not a simple class name), the class name passed to `get_function_hook` is not fully qualified (this is not strictly related to dunder methods, it might be a separate problem, I'm not sure) (fixed in #5379)

To test this, I've added `print`s to `mypy.plugin.DefaultPlugin`'s methods `get_function_hook`, `get_method_signature_hook`, `get_method_hook`, and `get_attribute_hook` to show when each method is called with what argument. Then I ran `mypy` on the following code:

```python
# fixed
# * class name is not fully qualified ('list') (fixed in #5379)
seq = (list,)[0](("hello",))

# works
# * class name is fully qualified ('builtins.list')
seq = list(("hi",))

# buggy
# * name is not fully qualified ('__iter__ of list')
# * get_function_hook is called instead of get_method_hook
# * get_method_signature_hook is not called
for obj in seq:
    print(obj)

# buggy
# * get_method_signature_hook is not called
print(seq[0])

# buggy
# * name is not fully qualified ('__setitem__ of list')
# * get_function_hook is called instead of get_method_hook
# * get_method_signature_hook is not called
seq[0] = "bye"

# works
# * name is fully qualified ('builtins.list.clear')
# * get_method_signature_hook is called
seq.clear()
```

Output:

```
get_function_hook('builtins.list')
get_function_hook('builtins.list')
get_function_hook('__iter__ of list')
get_attribute_hook('typing.Iterator.__next__')
get_function_hook('__next__ of Iterator')
get_function_hook('builtins.print')
get_method_hook('builtins.list.__getitem__')
get_function_hook('builtins.print')
get_function_hook('__setitem__ of list')
get_method_signature_hook('builtins.list.clear')
get_method_hook('builtins.list.clear')
```

**Comment by ilevkivskyi** [comment]
Setting priority to high because this may block some plugins work.

**Comment by gvanrossum** [comment]
I've run into the one for Type[] as well.
