### ISSUE TITLE
Return types of List[Union[x, y]] not properly handled

### ISSUE THREAD

**Issue by TDHolmes** [python/mypy#4965]
Basically:
   - function 1 returns a list of object 1
   - function 2 returns a list of object 2
   - function 3 returns a list of either object 1 or 2 by calling either function 1 or function 2

mypy complains about this, which doesn't make sense to me

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
from typing import NamedTuple, Union, List


class TypeOne(NamedTuple):
    thing: int


class TypeTwo(NamedTuple):
    other: str


def type_one_maker() -> List[TypeOne]:
    t = TypeOne(thing=5)
    return [t]


def type_two_maker() -> List[TypeTwo]:
    t = TypeTwo(other="hi")
    return [t]


def type_maker(return_type_one: bool=True) -> List[Union[TypeOne, TypeTwo]]:
    if return_type_one:
        return type_one_maker()
    else:
        return type_two_maker()


type_maker(True)
type_maker(False)
```

* What is the actual behavior/output?
```
✗ mypy ~/Desktop/union_repro.py
/Users/tylerholmes/Desktop/union_repro.py:24: error: Incompatible return value type (got "List[TypeOne]", expected "List[Union[TypeOne, TypeTwo]]")
/Users/tylerholmes/Desktop/union_repro.py:26: error: Incompatible return value type (got "List[TypeTwo]", expected "List[Union[TypeOne, TypeTwo]]")
```

* What is the behavior/output you expect?
No errors

* What are the versions of mypy and Python you are using?
✗ mypy --version
mypy 0.590
Python 3.6.5 (default, Apr 12 2018, 16:21:40)

**Comment by JelleZijlstra** [comment]
This is expected behavior. See https://github.com/python/mypy/blob/master/docs/source/common_issues.rst#invariance-vs-covariance.

**Comment by ilevkivskyi** [comment]
This is not a bug, please read the docs. You should either use `Union[List[TypeOne], List[TypeTwo]]`, or use `Sequence` instead of `List`.
