### ISSUE TITLE
Wanted: documentation or other pointers to how/where TypeVars are quantified

### ISSUE THREAD

**Issue by BrentKnight** [python/mypy#4995]
I have a strong background in type theory and compiler stuff, but I keep getting stuck wondering how TypeVar instances are quantified in mypy.

I confess I have not read the code.

But I have read examples in the documentation, like `AnyStr`, that seem to imply a TypeVar must take on the same value when it appears at more than on position in a function signature (e.g., `concat()` in the example in the documentation).

But where does this stop?

If I use `AnyStr` in **another** function signature, is it required to be instantiated to the same concrete type as in `concat()`?

The documentation I've seen doesn't seem to touch on this issue, but it seems crucial to understanding the meaning of TypeVars.

I would be very interested to learn more, even if it's just some pointers into the code, or whatever.

I'm sure there is a very clear and concrete semantics for TypeVars -- I'd just like to know what it is!

**Comment by gvanrossum** [comment]
See here: http://mypy.readthedocs.io/en/latest/generics.html#generic-functions

Basically there are two uses for typevars: generic classes (aka generic types), where the entire class definition uses the same typevar; and generic functions, where the "scope" of the typevar is a single 'def'.
