### ISSUE TITLE
How I can to mark the function that raise exception?

### ISSUE THREAD

**Issue by ghost** [python/mypy#5006]
`mypy` does not report an error in the next code:
```
def test_v1(a: int) -> float:
	try:
		return 1 / a
	except ZeroDivisionError:
		raise Exception('Division by zero!')
```
...but it report an error here:
```
def raise_zero() -> None:
	raise Exception('Division by zero!')

		
def test_v2(a: int) -> float:
	try:
		return 1 / a
	except ZeroDivisionError:
		raise_zero()
```
It say: `Missing return statement`
How I can to mark the function that raise exception?

**Comment by mkurnikov** [comment]
Should be this one
http://mypy.readthedocs.io/en/latest/kinds_of_types.html#the-noreturn-type
