### ISSUE TITLE
Please start a changelog or record changes on github releases

### ISSUE THREAD

**Issue by samuelcolvin** [python/mypy#5008]
mypy seems fairly unusual among mature projects in not maintaining a changelog. The closest alternative seems to be the blog http://mypy-lang.blogspot.co.uk/.

It would be great if mypy could maintain a changelog file or put details of changes on github releases prior to pypi releases.

This is very useful both when checking for compatibility before upgrading to a new version of mypy; it's also a powerful way of telling people about new features.

**Comment by samuelcolvin** [comment]
I tried for some time to find this, it works be useful if you could:
* Link to this from your readme
* Make it available in a format that works with pyup

**Comment by gvanrossum** [comment]
Personally I find the carefully curated blog should satisfy the desire for a changelog -- if you want more check out the revision history.
