### ISSUE TITLE
Type a Callable Arg without typing the positional args before it

### ISSUE THREAD

**Issue by iddan** [python/mypy#5017]
* Are you reporting a bug, or opening a feature request? feature request
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
O = TypeVar('O')

def decorator(method : Callable[[O, VarArg(), KwArg()], Any]) -> Callable[[VarArg(), O, KwArg()], Any]:
    def x(*args, **kwargs):
        return method(args[-1], *args[0:-1], **kwargs)
    return x
```

* What is the actual behavior/output? 

Required positional args may not appear after default, named or var args

* What is the behavior/output you expect?

`VarArg()` or `...` to represent the positional args before `O`

* What are the versions of mypy and Python you are using? 0.600, Python 3.6.2
  Do you see the same issue after installing mypy from Git master? Git is the same as release
* What are the mypy flags you are using? (For example --strict-optional): No flags

**Comment by ilevkivskyi** [comment]
This is a known limitation, we have an existing proposal, but syntax that you propose here was not considered I think. This is relatively low priority on our roadmap, so labelling accordingly (unless it is very easy to implement as a temporary workaround).

**Comment by iddan** [comment]
I think it should be first decided what syntax and behaviour are expected then someone could more easily pickup and implement it

**Comment by ilevkivskyi** [comment]
See https://github.com/python/typing/issues/239 and https://github.com/python/typing/issues/264 for previous discussion.

**Comment by iddan** [comment]
I've stumbled upon them but couldn't find what was settled. Was there an agreed syntax?

**Comment by ilevkivskyi** [comment]
This is the problem :-) There is still not 100% on the preferred syntax.

**Comment by hauntsaninja** [comment]
VarArg, KwArg, etc are deprecated. PEP 612 now exists. Discussion on further features is best done at github.com/python/typing
