### ISSUE TITLE
Generator expression returned from a function is interpreted as an Iterator

### ISSUE THREAD

**Issue by gmolau** [python/mypy#5020]
I have a function like this:

```python
def foo(some_list: List[Any]) -> Generator[Any, None, None]:
    return (element for element in some_list)
```

This should be correct according to the documentation of [`typing.Generator`](https://docs.python.org/3/library/typing.html#typing.Generator), yet mypy complains that it got an Iterator as the return value:

    error: Incompatible return value type (got "Iterator[Any]", expected "Generator[Any, None, None]")

Question was originally posted on Stackoverflow [here](https://stackoverflow.com/questions/50273130/mypy-error-when-returning-a-generator-expression?noredirect=1#comment87617942_50273130). Versions are Python 3.6.4, mypy 0.600.

**Comment by JelleZijlstra** [comment]
Thanks for the report! This should be pretty easy to fix: the bad code is at https://github.com/python/mypy/blob/master/mypy/checkexpr.py#L2231. Would you be interested in sending a PR to fix it?

**Comment by gmolau** [comment]
You mean by adjusting the `typ = ...` lines?
