### ISSUE TITLE
Order-dependent "Cannot determine type" of module global str

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#5024]
This is a rather weird bug that showed up for us in production when I tried to upgrade to 0.600. The repro requires at least four files, so I decided to put it in its own little repo: https://github.com/JelleZijlstra/tmp-mypy-bug. Running `mypy baddir` (with mypy 0.600) reproes the bug there.

Basically, the test case has four files that import each other (`__init__` -> `ba` -> `b` -> `c`). `ba` additionally uses a name from `b` (defines as `LOCAL_HOSTNAME = socket.gethostname()`), and the usage of this name causes a "Cannot determine type" error. Various minor transformations (making `LOCAL_HOSTNAME` a string literal; removing `c.py`) make the error go away.

Interestingly, renaming `ba.py` to `a.py` (as in the `gooddir` in the repo) silences the bug. This suggests that this is somehow related to the alphabetical order of the files involved. The bug didn't appear in 0.590. I'm guessing it's somehow related to the various FileSystemCache changes that went into 0.600. https://github.com/python/mypy/blob/master/mypy/find_sources.py#L78 is suspicious in that it does a sort and was new in 0.600, although really I'm just guessing.

**Comment by gvanrossum** [comment]
Could you run it with -v or even -v -v and post the full log output from 0.590 and 0.600 somewhere?

**Comment by JelleZijlstra** [comment]
Sure, 0.600 output is at https://github.com/JelleZijlstra/tmp-mypy-bug/blob/master/baddir0600.txt and 0.590 output at https://github.com/JelleZijlstra/tmp-mypy-bug/blob/master/baddir0590.txt.

**Comment by msullivan** [comment]
Closing as a dupe/variant of #5015.
(This is fixed by #5016.)
