### ISSUE TITLE
Document how to get started with an existing codebase

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#5033]
It would be nice to have a tutorial for new users of mypy focused on how to get started with a large existing code base and how to gradually improve annotation coverage. The content could be similar to what was in Greg Price's talk at PyCon 2018 (https://www.youtube.com/watch?v=0c46YHS3RY8).

Here a some ideas:

* First get clean output for some subset of code (or all code if your code base is not too large). No need to annotate anything yet.
  * Use a mypy config file with suitable options (which ones?).
  * Use a mypy run script to decide which files to type check (and which to exclude).
  * Exclude files that generate many errors for now.
* Set up CI to ensure that no new type errors get introduced. Use the same settings in CI and when running locally.
* Enable check untyped defs and fix issues (optional for very large code bases).
* Annotate commonly imported library modules. Consider using MonkeyType or PyAnnotate.
* Require annotations for new code.
* Gradually add annotations to code, add more files to the build, and remove exclusions.
* If you have, say, 20k lines or more, consider using mypy daemon.
* If you have, say, 100k lines or more, consider configuring remote caching for faster cold mypy runs.

Also include links to further relevant information, such as the PyCon talk linked to above, Zulip's mypy blog post, etc.

**Comment by jacebrowning** [comment]
Here are some basic things that I would have found useful on the [getting started](http://mypy.readthedocs.io/en/latest/getting_started.html) page (i.e. things people helped my with at PyCon that I previously failed to figure out on my own).

---

Ensure `mypy` has been installed correctly by running it against your project:

```sh
$ mypy <your-package-name>
```

This will likely report warnings on libraries outside your control. Create a configuration file (`mypy.ini`) with the following contents:

```ini 
[mypy]

ignore_missing_imports = true
```

Run `mypy` again and add the type annotations it requests until you get a clean run. To start checking all of your code, add the following to the configuration file:

```
check_untyped_defs = true
```

After resolving each warning, gradually add type annotations to each function's arguments and return value.

**Comment by gvanrossum** [comment]
There's also a lot of useful advice here:
http://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/

I'm against recommending `ignore_missing_imports = true` on the getting
started page; this flag causes a lot of pain further down the road
(mysterious failures to report blatant bugs).

**Comment by gvanrossum** [comment]
This is usually dealt with by adding `# type: import` to the failing imports. (We might want to add *that* to the getting started doc.)

**Comment by msullivan** [comment]
It can also be handled by setting `ignore_missing_imports = True` for just the modules that can't be imported, which might be worth adding too. (It's less noisy if it is imported in a lot of modules.) So:
```
[mypy-freezegun]
ignore_missing_imports = True
```

**Comment by f0lie** [comment]
We should probably point out that using mypy on an existing project exists within the context of understanding the codebase in the first place. I tried to download nltk and toss into mypy. Obviously, that didn't work at all.

Maybe there should be a checklist to make sure people are in the right place. Something like:

- [ ] You are familiar with the codebase.

- [ ] You have been using the codebase and familiar with its libraries.

- [ ] You generally understand where to look for things.

**Comment by f0lie** [comment]
After type hinting one py file, I think I got a workflow that would work for everything else.

 1) -Pick a py file.
     -Doesn't really matter as long you start somewhere.
     -You could always make an issue about type hinting and ask for suggestions.
     -Generally, you would tag your core library as it's the most important.
 2) -Add tag hinting.
     -See the guide in the docs.
 3) -Run Mypy on the py file.
     -Read the error messages and figure out what to fix.
     -Highly recommend joining gitter to ask questions.
     -Mypy is evolving quickly so you need to ask questions for help.
 4) -Run the test suite.
     -Make sure you don't add compiler errors.
5) -Do some other file

**Comment by ethanhs** [comment]
@JukkaL is there anything that needs to be added to https://mypy.readthedocs.io/en/latest/existing_code.html ? Otherwise I think this can be closed.

**Comment by f0lie** [comment]
@ethanhs For "Mypy runner script" you should add a small mypy script that does what it mentioned. So if someone isn't familiar with how to do all of that, they aren't totally lost. For a starting guide, we should have minimal assumptions about the experience level of our readers.

**Comment by JukkaL** [comment]
This already exists in the mypy documentation, as mentioned above by Ethan.
