### ISSUE TITLE
Document `assert x.y is not None` in the cheat sheet

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#5037]
Asserting when the inferred type is `Optional[X]` but we expect just `X` is a common thing and may not be obvious to users.

**Comment by sp1rs** [comment]
This is already specified in the cheat sheet. This issue can be closed.
From cheat_sheet.rst
```
# Use Optional[] for values that could be None
x = some_function()  # type: Optional[str]
if x is not None:
   print x
```

**Comment by ilevkivskyi** [comment]
This is different. I think the idea of this issue is to document that there are _two_ ways (which is important): `assert x.y is not None` and `if x.y is not None`.
