### ISSUE TITLE
Function + @overload cause "Single overload definition, multiple required"

### ISSUE THREAD

**Issue by ikonst** [python/mypy#5047]
Assume a function like:
```py
def get_item(key: str, default: Optional[Item] = None) -> Optional[Item]:
   # implementation goes here
   ...
```

Now let's assume we want to enhance typing through an `@overload` by changing it to:
```py
@overload
def get_item(key: str) -> Item:
   ...

def get_item(key: str, default: Optional[Item] = None) -> Optional[Item]:
   # implementation goes here
   ...
```

mypy will complain with:
```
error: Single overload definition, multiple required
```

This check makes sense for a `.pyi` file where you would expect multiple `@overload`s on equal footing, but in this case the original declaration might as well serve as an "overload".

A workaround is obviously to add:
```py
@overload
def get_item(key: str, default: Optional[Item]) -> Optional[Item]:
   ...
```
which adds needless verbosity.

**Comment by Michael0x2a** [comment]
I'm a little bit confused about your type signature here: if 'default' is set to None, doesn't that mean the first overload alternative will always match? So, the only case where 'get_item' can return 'None' would be if 'default' is a non-None object?

Basically, I think your type signature is equivalent to the following:

    @overload
    def get_item(key: str, default: None = None) -> Item: ...
    @overload
    def get_item(key: str, default: Item) -> Optional[Item]: ...
    def get_item(key: str, default: Optional[Item] = None) -> Optional[Item]:
        # implementation goes here

In any case, I think you usually want your overload signatures to be "specializations" of the implementation signature. We don't really want to force users to have the implementation signature be a valid overload alternative in that case.

**Comment by gvanrossum** [comment]
I *suspect* that the OP intended something like this:
```py
@overload
def get_item(key: str) -> Optional[Item]: ...
@overload
def get_item(key: str, default: None) -> Optional[Item]: ...
@overload
def get_item(key: str, default: Item) -> Item: ...
def get_item(key: str, default: Optional[item]) -> Optional[Item]:
    # implementation goes here
```
In any case we don't have plans to make it easier to shoot yourself in the foot here.

**Comment by raabf** [comment]
If someone comes over this issue: The intended way of writing *two* different signatures, is to have them in two `@overload` signatures. And the actual function header for the implementation should be empty or should include the merge of all signatures with `Union`:

```
@overload
def get_item(key: str) -> Item:
   ...

@overload
def get_item(key: str, default: Optional[Item] = None) -> Optional[Item]:
   ...

def get_item(key, default = None):
   # implementation goes here
   ...
```

That's why there must be at least two `@overload` signatures and the error `error: Single overload definition, multiple required` will else arise. 

See also #72 , #1136 , and #3360 .

**Comment by audoh** [comment]
There's a good use case for single overloads in having a stricter signature than the actual implementation:

```py
from typing import Any, Dict, overload

@overload
def create_safe_thing(*, field_a: int, field_b: bool) -> Dict[str, Any]:
    ...

def create_safe_thing(**kwargs: Any) -> Dict[str, Any]:
    return dict(kwargs)

print(create_safe_thing(field_a=3,field_b=True))
# >>> {'field_a': 3, 'field_b': True}
```

**Comment by hoodmane** [comment]
I did this:

```py
@overload
def my_func(*, arg1: str, arg2: int, ...):
    ...

# Hack to prevent mypy error:
# "error: Single overload definition, multiple required"
class _EmptyType:
    __new__ = None # type: ignore

@overload
def my_func(a : _EmptyType):
    ...


def my_func(**kwargs):
   # implementation here.
```
I couldn't find any reference to a built in the typing or mypy docs.

**Comment by tachylatus** [comment]
> In 3.11 the `typing.Never` bottom type was implemented. This could perhaps be used to prevent static type-checkers from recommending these "empty" overloads. E.g.,

> At the time of writing, pyright (via pylance, vscode) seems only to ignore (not display to the user) overloads of methods with `Never` placed upon the `self` argument. The only case I can think of where this might be helpful is when writing a class with a method that wraps another method or function

For those who need a workaround prior to Python 3.11's `typing.Never`, annotating `self` with `typing.NoReturn` also seems to have the desired effect:
```python
class Taint(dict):
    @overload
    def __init__(self, *, key: str, value: Optional[str] = None, effect: Union[Effect, str]): ...
    @overload
    def __init__(self: NoReturn) -> NoReturn: ...  # workaround for mypy single overload definition error
    def __init__(self, **kwargs):
        # implementation
```

**Comment by JelleZijlstra** [comment]
`Never` and `NoReturn` should be perfectly equivalent, for what it's worth. (We generally think `Never` is a better name.)
