### ISSUE TITLE
Unexpected behavior regarding async generator

### ISSUE THREAD

**Issue by pawelswiecki** [python/mypy#5070]
Trying to get typing work in an asynchronous code and I don't understand mypy's behavior.

Let's say we have two coroutines typed in the following way:

```python
from typing import AsyncGenerator

async def gen1() -> AsyncGenerator[str, None]:
    pass
reveal_type(gen1)

async def gen2() -> AsyncGenerator[str, None]:
    yield 'tick'
reveal_type(gen2)
```
mypy:
```bash
$ mypy file.py
file.py:5: error: Revealed type is 'def () -> typing.Awaitable[typing.AsyncGenerator[builtins.str, builtins.None]]'
file.py:9: error: Revealed type is 'def () -> typing.AsyncGenerator[builtins.str, builtins.None]'

```

So the type of the first one gets wrapped in `Awaitable`. I don't fully understand why. I thought all `Async...` are Awaitables by definition. I did not find anything about it but here #3576, which is not enough for me to get it.

The same thing in case of methods:

```python
class BaseClass:
    async def gen1(self) -> AsyncGenerator[str, None]:
        pass
reveal_type(BaseClass.gen1)

class MyClass(BaseClass):
    async def gen1(self) -> AsyncGenerator[str, None]:
        yield 'tick'
reveal_type(MyClass.gen1)
```

mypy:

```bash
file.py:4: error: Revealed type is 'def (self: acm.workers.BaseClass) -> typing.Awaitable[typing.AsyncGenerator[builtins.str, builtins.None]]'
file.py:7: error: Return type of "gen1" incompatible with supertype "BaseClass"
file.py:9: error: Revealed type is 'def (self: acm.workers.MyClass) -> typing.AsyncGenerator[builtins.str, builtins.None]'
```

So now I cannot define abstract methods that are async generators, in a straightforward way.

**Versions**

Python 3.6.5
mypy==0.600

EDIT: I fixed a random typo @JelleZijlstra found and edited parts of the text based on the typo. Now the whole problem is clearer.

**Comment by ilevkivskyi** [comment]
The `if False: yield` trick is as old as Python probably is. I think the source of confusion here may be that type annotations are _completely ignored_ by Python runtime. Just by typing something as a generator it will not magically become a generator, you still need a `yield` somewhere.

There is unfortunately no simple solution, we may just document this in common issues.

**Comment by pawelswiecki** [comment]
Thank you both, now I get it. My typo (which I will correct in a second) only added to my confusion. I agree that this probably should be explained in docs somewhere.

**Comment by pawelswiecki** [comment]
Update: I started to use plain `yield` in those kind of abstract async generators and I can say I like it: it's just as succinct as `pass` (which is, in this context, equivalent to plain `return`) and informative for the user as well.

**Comment by hlovatt** [comment]
I too like the plain `yield` but think it needs to be documented, it took a bit of googling to find this page!

**Comment by ashb** [comment]
A slightly different case to this (that is still fixed by doing `if False: yield` is if your parent ABC class:

```python

class Base(abc.ABC):
    @abc.abstractmethod
    def run(self) -> AsyncIterator[int]:
        raise NotImplementedError("must implement run()")

class A(Base):
    def run(self) -> AsyncIterator[int]:
        while True:
            yield 1
```

This will fail with

> test.py:34: error: Return type "AsyncIterator[int]" of "run" incompatible with return type "Coroutine[Any, Any, AsyncIterator[int]]" in supertype "Base"  [override]

By making it a generator it passes

```python
    @abc.abstractmethod
    def run(self) -> AsyncIterator[int]:
        raise NotImplementedError("must implement run()")
        if False:
            yield 0
```

Even if the `raise NotImplementedError` isn't in the base function body the error remains the same. Should this ABC case be handed specially?

**Comment by pamelafox** [comment]
Sharing a similar example as the previous comment:

approach.py:

```python
from abc import ABC, abstractmethod
from typing import Any, AsyncGenerator


class ChatApproach(ABC):
    @abstractmethod
    async def run(self, history: list[dict[str, str]], overrides: dict[str, Any], should_stream: bool) -> AsyncGenerator[dict, None]:
        ...
```

chatreadretrieveread.py:

```python
from approaches.approach import ChatApproach

class ChatReadRetrieveReadApproach(ChatApproach):

    async def run(self, history: list[dict[str, str]], overrides: dict[str, Any], should_stream: bool=False) -> AsyncGenerator[dict, None]:
```

results in:

```
approaches/chatreadretrieveread.py:60: error: Signature of "run" incompatible with supertype "ChatApproach"  [override]
approaches/chatreadretrieveread.py:60: note:      Superclass:
approaches/chatreadretrieveread.py:60: note:          def run(self, history: list[dict[str, str]], overrides: dict[str, Any], should_stream: bool) -> Coroutine[Any, Any, AsyncGenerator[dict[Any, Any], None]]
approaches/chatreadretrieveread.py:60: note:      Subclass:
approaches/chatreadretrieveread.py:60: note:          def run(self, history: list[dict[str, str]], overrides: dict[str, Any], should_stream: bool = ...) -> AsyncGenerator[dict[Any, Any], None]
```

The "if False: yield" trick does work to remove the mypy errors.

**Comment by hauntsaninja** [comment]
This has been documented at https://mypy.readthedocs.io/en/stable/more_types.html#asynchronous-iterators for a couple months now

**Comment by ikonst** [comment]
Took a stab at adding contextual help in #15883.

(... Although, this wouldn't help https://github.com/python/mypy/issues/5070#issuecomment-1679276058 since it's a difference in more than just the return type...)
