### ISSUE TITLE
Valid namedtuple invocation determined invalid

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#5078]
I recently came accross the following snippet in the inspect module
```
FrameInfo = namedtuple('FrameInfo', ('frame',) + Traceback._fields)  # Traceback._fields is a Tuple[str, str])
```
It is falsely flagged as invalid since the second argument is not a tuple literal. I believe #3575 may help here.

**Comment by ilevkivskyi** [comment]
Isn't this essentially a duplicate of https://github.com/python/mypy/issues/3520? Or do you propose to just use less specific type when such code is found (i.e. treating this as `FrameInfo = Tuple[Any, ...]`)?

**Comment by ethanhs** [comment]
Ah, yes I missed that. Closing as duplicate of #3520 then!
