### ISSUE TITLE
__eq__, __neq__ invalid signature outside of class context

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#5082]
In unitest.mock there is something essentially:
```
def _get_eq(self):
    def __eq__(other):  # error:  Invalid signature "def (other: Any) -> Any"
        return None
    return __eq__
```
and the same for `__neq__`.

I believe we are incorrectly deciding to check these.

**Comment by ethanhs** [comment]
Actually this looks a lot like #4950. We should probably go through each function to make sure there aren't other dunder methods that befall this issue.

**Comment by 97littleleaf11** [comment]
Has been fixed!
