### ISSUE TITLE
Run pythoneval tests using --incremental

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#5083]
There is a simple idea how to speed-up `pythoneval.py` tests, that are currently very slow. After running the first test we can write cache and use it for the next test, so that we don't reprocess `builtins`, `typing`, etc.

**Comment by ethanhs** [comment]
I believe the tests are run without the `--no-incremental` flag, so they are run in incremental mode (since it is on by default now), but discard the cache on cleanup, no? So really we want to keep the created cache?

**Comment by ilevkivskyi** [comment]
> So really we want to keep the created cache?

Yes, this is what I mean.

**Comment by ilevkivskyi** [comment]
This is actually a duplicate of https://github.com/python/mypy/issues/1412
