### ISSUE TITLE
Incorrect name lookup when using package names in types

### ISSUE THREAD

**Issue by levsa** [python/mypy#5089]
When using package name prefix to a type, the package name lookup conflicts with method name if it is already declared in the class declaration.

E.g.:

```python
import signal

class SignalWrapper:
    def foo_signal(self, signalnum: signal.Signals, handler: signal.Handlers):
        return signal.signal(signalnum, handler)

    def signal(self, signalnum: signal.Signals, handler: signal.Handlers) -> signal.Handlers:
        return signal.signal(signalnum, handler)

    def bar_signal(self, signalnum: signal.Signals, handler: signal.Handlers):
        return signal.signal(signalnum, handler)

```
gives:
```
name_error.py:7: error: Invalid type "name_error.SignalWrapper.signal"
name_error.py:10: error: Invalid type "name_error.SignalWrapper.signal"
```

Python 3.62
mypy 0.560

**Comment by gvanrossum** [comment]
Well if you execute that code you would get an error on bar_signal, so the
ice is really thin here. I recommend renaming the signal method or using an
alias for the signal module.

**Comment by levsa** [comment]
Ok, that’s a better solution. But then mypy behavior with regard to lookup differs from python in this case? The first error on line 7 wouldn’t have been there otherwise. It would be better if they were more alike in my opinion.

**Comment by gvanrossum** [comment]
Mypy uses a multi-pass algorithm for static source code analysis and it cannot mimic all idiosyncracies of Python's dynamic lookup. It's also debatable whether mimicking Python in this respect would be better.
