### ISSUE TITLE
Overloads for property getter (instance vs. through owner)

### ISSUE THREAD

**Issue by ikonst** [python/mypy#5093]
The [docs for `object.__get__`](https://docs.python.org/3/reference/datamodel.html#object.__get__) specify that:
> `object.__get__(self, instance, owner)`
>
> ... _owner_ is always the owner class, while _instance_ is the instance that the attribute was accessed through, or None when the attribute is accessed through the _owner_.

The [typeshed for pynamodb](https://github.com/python/typeshed/blob/master/third_party/2and3/pynamodb/attributes.pyi) has:
```py
class NumberAttribute(Attribute[Number]):
    def __get__(self, instance: Any, owner: Any) -> Number: ...
```

This allowed us to use PynamoDB idiomatically so that `MyModel().my_number` is considered a `Union[int, float]` rather than an instance of `NumberAttribute`. The underlying implementation might not use properties, but superficially it works ;)

Recent versions of PynamoDB added a conditional query syntax like this:
```py
for my_model in MyModel.query(range_key_condition=MyModel.my_number > 42):
   ...
```

I've tried representing it like this:
```py
class NumberAttribute(Attribute[Number]):
    @overload
    def __get__(self, instance: object, owner: Any) -> Number: ...
    @overload
    def __get__(self, instance: None, owner: Any) -> NumberAttribute: ...
```
but mypy seems to ignore the latter override.

Test code:
```py
from pynamodb.attributes import NumberAttribute, ListAttribute
from pynamodb.models import Model


class MyModel(Model):
    my_number = NumberAttribute(hash_key=True)


reveal_type(MyModel.my_number)

m1 = MyModel()
reveal_type(m1.my_number)
```

Result:
```
pynamodb.py:9: error: Revealed type is 'Union[builtins.int, builtins.float]'
pynamodb.py:12: error: Revealed type is 'Union[builtins.int, builtins.float]'
```

**Comment by JelleZijlstra** [comment]
Does it work if you reverse the order of the overloads?

**Comment by ikonst** [comment]
```
class NumberAttribute(Attribute[Number]):
    @overload
    def __get__(self, instance: None, owner: Any) -> 'NumberAttribute': ...
    @overload
    def __get__(self, instance: object, owner: Any) -> Number: ...
```
results in:
```
# reveal_type(MyModel.my_number)
Revealed type is 'Any'
# reveal_type(m1.my_number)
Revealed type is 'Union[builtins.int, builtins.float]'
```

**Comment by Michael0x2a** [comment]
This should hopefully be fixed sometime in the near future: we're currently in the process of overhauling how mypy handles overloads in general, and the plan is to fix this along the way.

(Well, it's not so much "fix" as it is "special-case overloading descriptors to allow this", but whatever.)

There's also some related discussion here: https://github.com/python/mypy/issues/3757.

**Comment by Michael0x2a** [comment]
I'm pretty certain this ought to be fixed on master now, though I'm not very familiar with the pynamodb stubs so can't say for certain. 

@ikonst -- can you confirm?

**Comment by ikonst** [comment]
This definition works:
```
class NumberAttribute(Attribute[float]):
    @overload
    def __get__(self, instance: Model, owner: Any) -> float: ...
    @overload
    def __get__(self, instance: None, owner: Any) -> NumberAttribute: ...
```

This one also works:
```
class NumberAttribute(Attribute[float]):
    @overload
    def __get__(self, instance: None, owner: Any) -> NumberAttribute: ...
    @overload
    def __get__(self, instance: object, owner: Any) -> float: ...
```
(note the `None` variant being first)

**Comment by ilevkivskyi** [comment]
OK, so as I understand this one can be closed now.
