### ISSUE TITLE
Bad typing for Python 2.7 with `unicode_literals`

### ISSUE THREAD

**Issue by ikonst** [python/mypy#5098]
Consider:
```py
from __future__ import unicode_literals
import sys

print(sys.modules['sys'])
```

`mypy --py2 unicode_literals.py` results in:
```
unicode_literals.py:4: error: Invalid index type "unicode" for "Dict[str, Any]"; expected type "str"
```

However, `python2.7 unicode_literals.py` results in:
```
<module 'sys' (built-in)>
```

**Comment by gvanrossum** [comment]
Did I mention that from __future__ import unicode_literals is a bad idea?

**Comment by Michael0x2a** [comment]
I believe mypy currently doesn't support unicode_literals: there's some related discussion [here](https://github.com/python/mypy/issues/3619) and [here](https://github.com/python/mypy/issues/2536).

Maybe there's an opportunity to do some usability enhancement here? If we're not planning on supporting unicode_literals any time soon, maybe we can have mypy report a warning when it detects some code using it/link to something in the docs.

**Comment by gvanrossum** [comment]
Oh, that is a great idea!
