### ISSUE TITLE
@overload and Type[bool]

### ISSUE THREAD

**Issue by srittau** [python/mypy#5116]
Consider the following file:

```python
from typing import Any, Type, TypeVar, overload

_T = TypeVar("_T", float, bool)

@overload
def foo(x: None) -> None: ...
@overload
def foo(x: Type[_T]) -> _T: ...
def foo(x: Any) -> Any: pass

foo(bool)
```

When checking this with mypy 0.600 and python 3.5.5, I get the following error:

```
foo.py:11: error: No overload variant of "foo" matches argument types [def (o: builtins.object =) -> builtins.bool]
```

When replacing `float` in the type var with something else (like `str` or `int`) this works. Same when I add an extra overload:

```python
@overload
def foo(x: Type[bool]) -> bool: ...
```

**Comment by gvanrossum** [comment]
Perhaps this is because bool is a subtype of int and int is promoted to
float by mypy; the overload resolution could be confused by this. I assume
foo(float) is fine too?

**Comment by ilevkivskyi** [comment]
Hopefully one of @Michael0x2a's PRs will fix this.

**Comment by Michael0x2a** [comment]
I can confirm this appears to be fixed in master -- most likely due to https://github.com/python/mypy/commit/f61c2baac5915ab680c2f1a9858b7f608262a00e.
