### ISSUE TITLE
Separate plugin API and implementation

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#5117]
Currently plugin API and implementation (the `DefaultPlugin` class) live in the same module `plugin.py`. This leads to import cycles for specific plugins, e.g. `plugin -> plugins.attrs -> plugin`. This will happen for all plugins that we would like to be maintained in mypy. A possible solution is to just separate plugin API definition to a separate module.

**Comment by JukkaL** [comment]
A good idea! Additionally we could separate the `attrs` plugin from the default plugin to make things a bit more modular. The default plugin would only cover simple stdlib functionality.

**Comment by ilevkivskyi** [comment]
@JukkaL Now that you added `plugins/default.py` is something left here, or this can be closed? It looks like we can move out method level imports to the top of modules, since there should be no import cycle there anymore, or am I missing something?

**Comment by JukkaL** [comment]
I can't see any import cycles any more so I think that this can be closed.
