### ISSUE TITLE
error while using rasa

### ISSUE THREAD

**Issue by ironside007** [python/mypy#5127]
error:
from typing import Text, List, Optional, Callable, Any, Dict, Union
ImportError: cannot import name 'Text

**Comment by ethanhs** [comment]
Hi, for general typing issues you probably want to report them to https://github.com/python/typing or https://bugs.python.org, but in this case, it is likely you are using Python 3.5.0 or 3.5.1, which don't have `typing.Text`. You may want to read the docs https://docs.python.org/3/library/typing.html#typing.Text

Additionally, in future *please* give more context. I am guessing that you are on Python 3.5.0 or 3.5.1, but with what you have given, I have no other ideas, and I cannot really help you.
