### ISSUE TITLE
Support for Embedded C++ Modules?

### ISSUE THREAD

**Issue by Skeltpr** [python/mypy#5140]
My Python application is a C++ program that exposes some of the C++ classes/functions to the Python interpreter using [Pybind11](https://github.com/pybind/pybind11) as a custom module and interprets an external Python file. This interpreted Python file has access to the module simply using an import statement.

However, as a result, there's no way (from what I can tell) for MyPy to be able to find/read this module since it's embedded into the application. Is there anyway for me to insert custom data/information regarding this module directly into MyPy?

**Comment by msullivan** [comment]
You can write a stub file containing types for the module written in C++: https://mypy.readthedocs.io/en/latest/basics.html#library-stubs-and-the-typeshed-repo
