### ISSUE TITLE
assign value to UserDict.data thow Unsupported target for indexed assignment

### ISSUE THREAD

**Issue by Hanaasagi** [python/mypy#5141]
mypy version 0.600. 
Run following code and it throws `t.py:7: error: Unsupported target for indexed assignment`

```Python
from collections import UserDict


class Config(UserDict):

    def t(self) -> None:
        self.data['x'] = 'y'  # line 7
```

If I use `self['x'] = 'y'`, It will be ok. I have see the [issue 2900](https://github.com/python/mypy/issues/2900), but I don't think I make a heterogeneous dict.

**Comment by JelleZijlstra** [comment]
Fixed in typeshed.
