### ISSUE TITLE
ignore errors with pattern no longer work in version 0.600

### ISSUE THREAD

**Issue by bmoelans** [python/mypy#5143]
I have in mypy.ini
```
[mypy-app.*.migrations.*]
ignore_errors = True
```
And this excluded with success the migrations folder in version 0.590

But after migrate to 0.600 I get `mypy.ini: [mypy-app.*.migrations]: Invalid pattern. Patterns must be 'module_name' or 'module_name.*'`

**Comment by ilevkivskyi** [comment]
This is already fixed in master by https://github.com/python/mypy/pull/5120
