### ISSUE TITLE
Falsy (not x) expression does not narrow Optional type 

### ISSUE THREAD

**Issue by daviskirk** [python/mypy#5145]
* Are you reporting a bug, or opening a feature request?

From my perspective it is a Bug, but I am happy to learn the reasoning behind a design decision I might have missed.

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

Running this code through mypy using the command `mypy x.py` 

```python
from typing import Optional

this: Optional[str]
that: Optional[int]

if not this:
    this += 'random string'

if not that:
    that += 1
```

* What is the actual behavior/output?

```
x.py:7: error: Revealed type is 'Union[builtins.str, None]'
x.py:8: error: Unsupported left operand type for + (some union)
x.py:11: error: Revealed type is 'Union[builtins.int, None]'
x.py:12: error: Unsupported operand types for + ("Optional[int]" and "int")
```

* What is the behavior/output you expect?

Intuitively, I would have thought that the `not this`/`not that` clauses would make a `None` type impossible, thus narrowing the type to a string or integer.

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

Using python 2.6 and mypy 0.600 (so strict Optional is on by default).
Using the git master version (`mypy==0.610+dev.eb1bb064d707ce05735ff6795df82126e75ea6ea` ) produces the same result.

* What are the mypy flags you are using? (For example --strict-optional)

No flags used. Command is just `mypy x.py`

**Comment by JelleZijlstra** [comment]
I think your logic is reversed. In `if not this: this += 'integer'`, where `this: Optional[str]`, `this` can be None inside the if block, and `None += 'integer'` is invalid.

**Comment by ethanhs** [comment]
Furthermore, the reversed does work.
```
from typing import Optional

x: Optional[int]

if x:
    reveal_type(x)  # error: Revealed type is 'builtins.int'
    x += 1
```

I also think this is also a good example of why using `if x is not None` or `if x is None` is better/clearer than `if x` or `if not x`.

**Comment by daviskirk** [comment]
This is embarrassing.  Sorry for wasting time!
