### ISSUE TITLE
dunder parameter: Unexpected Keyword Argument

### ISSUE THREAD

**Issue by dfee** [python/mypy#5156]
Consider the following:

```python
def func(*, __param__=False):
    return __param__

assert func(__param__=True) is True
```

mypy complains: `"error: Unexpected keyword argument for "__param__" for "func"`. This can be experienced directly by looking at `inspect.Signature` and supplying the an argument for the keyword-only parameter `__validate_parameters__`.

This appears(?) to be related to a mis-implementation of the following: https://github.com/python/typing/issues/336

**Comment by JelleZijlstra** [comment]
I'm not sure this is a misimplementation: it's behaving exactly as described in the linked issue.

To accommodate the inspect.Signature use case, perhaps we can *not* treat the param as positional-only if its name also ends with `__`, or if it is already keyword-only.

**Comment by dfee** [comment]
Either the PEP revision was accepted without enough consideration, or the implementation of ``inspect.Signature`` is non-compliant.

You are correct that it follows the letter of the implementation of python/typing#336. I either misunderstand the spirit of that revision – Python distinguishes between a leading and a surrounding `__` – or (I'd suggest) the revision is an anti-pattern.

**Comment by gvanrossum** [comment]
This was an oversight in the spec! We meant to use the same naming convention as Python uses for `__private` names, from which `__dunder__` names are explicitly excluded. If you could submit a PR for mypy and another for PEP 484 I'd be happe to review them.

**Comment by JelleZijlstra** [comment]
I'll fix it.

**Comment by dfee** [comment]
Awesome. Thanks for the quick resolution @gvanrossum
