### ISSUE TITLE
Representing functions that take no keyword arguments

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#516]
Many Python built-in functions accept no keyword arguments:

``` python
>>> ord(c='c')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ord() takes no keyword arguments
```

Currently there is no way to represent this in stubs. I propose using the convention of prefixing all argument names with an underscore for functions that can't be called using keyword arguments. Here is an example for `ord`:

``` python
# can only call using positional args!
def ord(_c: Union[str, bytes, bytearray]) -> int: pass
```

The implementation would be in two phases:
1. Disallow names starting with `_` as keyword arguments, and report errors such as `"foo" takes no keyword arguments` when trying to pass keyword arguments to a function that has all arguments prefixed with `_`.
2. Update stubs to use `_` argument name prefixes when it makes sense.

This has a problem with calls to functions which legitimately take arguments with a `_` prefix. To address this, we could only use this convention for stub files. For regular Python files, argument names with a `_` prefix would be fine. For stubs, we could also use **two** underscores to represent argument names which should have a `_` (single underscore) prefix but should still be valid as keyword arguments. However, we can implement these refinements only later, and only if there seems to be an actual need for them.

**Comment by sixolet** [comment]
I think we can close this now that https://github.com/python/mypy/pull/2497 is landed.
