### ISSUE TITLE
mypy complains about attrs' __init__ when using @attrs/attrib, but not @attr.s/attr.ib

### ISSUE THREAD

**Issue by dcrosta** [python/mypy#5162]
I have the following minimal example that reproduces consistently for me:

_test.py_
```python
from attr import attrs, attrib
import attr

@attr.s
class ThingOne:
    a: str = attr.ib()

@attrs
class ThingTwo:
    a: str = attrib()

@attr.s
class ThingThree:
    a: str = attrib()

@attrs
class ThingFour:
    a: str = attr.ib()

a = ThingOne("a")
b = ThingTwo("b")
c = ThingThree("b")
d = ThingFour("b")
```

If I run mypy, it complains that there are too many arguments for `ThingTwo`'s `__init__`:

```
$ MYPYPATH=env/lib/python3.6/site-packages env/bin/mypy --follow-imports=silent test.py
test.py:22: error: Too many arguments for "ThingTwo"
test.py:23: error: Too many arguments for "ThingThree"
test.py:24: error: Too many arguments for "ThingFour"
```

(Running with `--follow-imports=silent` just quiets down a lot of noise about mypy not being able to make sense of attrs itself -- the relevant errors are the same with or without that flag)

I have these versions of things:

```
$ env/bin/python -m pip list
Package    Version
---------- -------
attrs      18.1.0
mypy       0.600
pip        10.0.1
setuptools 39.2.0
typed-ast  1.1.0
wheel      0.31.1
$ env/bin/python --version
Python 3.6.4
$ system_profiler SPSoftwareDataType | grep "System Version"
      System Version: macOS 10.13.5 (17F77)
```

From everything that I've read, I think mypy _should_ treat these the same -- I am under the impression that it understands both `@attrs` and `@attr.s` via the attrs plugin. It seems to work only if I use both `attr.s` and `attr.ib` (the `ThingOne` case in my test script).

**Comment by ilevkivskyi** [comment]
Hm, this is weird, I just tried on master all four options work for me without errors. Can you try installing from GitHub master? Maybe it was just fixed recently?

**Comment by dcrosta** [comment]
With master (`0.610+dev`) I get

```
$ MYPYPATH=env/lib/python3.6/site-packages env/bin/mypy --follow-imports=silent test.py
test.py:1: error: Cannot find 'builtins' module. Typeshed appears broken!
```

Not sure if that's expected, but at least the attrs issue is gone.

**Comment by ethanhs** [comment]
You aren't supposed to add `site-packages` to your `MYPYPATH`. Try again without that and it should work.

**Comment by dcrosta** [comment]
Without setting `MYPYPATH`, I get:

```
 $ env/bin/mypy --follow-imports=silent test.py
test.py:1: error: Cannot find module named 'attr'
test.py:1: note: (Perhaps setting MYPYPATH or using the "--ignore-missing-imports" flag would help)
test.py:1: error: Cannot find 'builtins' module. Typeshed appears broken!
```

**Comment by ilevkivskyi** [comment]
First of all this `MYPYPATH=env/lib/python3.6/site-packages` is a bad idea for many reasons. Second, if you installed mypy in a venv it is better to just activate that venv and just call `mypy test.py`.

**Comment by ilevkivskyi** [comment]
Finally, how did you install it? Have you followed the instructions in docs?

**Comment by ilevkivskyi** [comment]
http://mypy.readthedocs.io/en/latest/getting_started.html#installing-from-source

**Comment by ilevkivskyi** [comment]
> That is very surprising that activating the virtualenv makes a difference. Why is that?

This is how virtual envs are are intended to be used. If you do otherwise, you are on your own. It is still possible to make mypy (and other things) work, but it requires some efforts.

**Comment by ilevkivskyi** [comment]
Also it may be that even the 0.600 release will work if you run it this way (no `MYPYPATH`, activated virtual env).

**Comment by dcrosta** [comment]
Yeah it seems to.

This is all surprising to me, because activating a virtualenv really does kind of nothing. It updates `PATH` so that the env's binaries come first, it sets a few other env vars related to virtualenv itself, and aliases `pydoc`. I'm not sure why any of that would change how mypy finds third party modules, or especially why it changes how it would typecheck this small example file.

**Comment by ilevkivskyi** [comment]
OK, so then issue resolved!

Re why, my guess is that having correct `PATH` allows mypy to locate typeshed, where all actual type definitions live (including attrs), most 3rd party libraries are still typed using typeshed, only few use PEP 561 to distribute types via PyPI.

**Comment by dcrosta** [comment]
`PATH` is just the location for executables, how is that involved in finding typeshed?

Anyway, thanks for your help here!

**Comment by JukkaL** [comment]
If running without activating virtualenv breaks mypy, we should detect that and produce an error (or make it work somehow) instead of producing incorrect results.
