### ISSUE TITLE
Better error message for "need type annotation for variable"

### ISSUE THREAD

**Issue by warsaw** [python/mypy#5167]
I'm sure I'm not the first person to report this, but searching the open issues didn't land me on a relevant ticket.  Apologies for any duplicates.

Sometimes mypy 0.600 doesn't notice that initializing a variable with `set()` should inference the variable as a `typing.Set`.  E.g. This code:

```
def fill_python_versions(graph: DiGraph) -> None:
    by_version = get_python_usage()
    python2_support = set()
    python3_support = set()
```

produces this error:

```
graph.py:138: error: Need type annotation for 'python2_support'
graph.py:139: error: Need type annotation for 'python3_support'
```

This forces me to add:

```
def fill_python_versions(graph: DiGraph) -> None:
    by_version = get_python_usage()
    python2_support: Set = set()
    python3_support: Set = set()
```
and of course `from typing import Set`.  This latter then generates a flake8 error:

```
graph.py:35:1: F401 'typing.Set' imported but unused
```

which I now have to annotate with `# noqa: F401`

I've tried to reproduce this with a smaller test case, but haven't been able to provoke the same behavior, so I'm not sure what's going on.  I'm using Python 3.6.

**Comment by JelleZijlstra** [comment]
What mypy wants you to do here is say something like `Set[str]` to indicate what kind of object you're storing in the set. Maybe there's a way we can say that more clearly in the error message. If you use the right strictness option, you'll also get an error for saying `Set` that tells you that you're missing a type argument.

The flake8 error seems like a bug in flake8: it should recognize that names used in local variable annotations are used.

**Comment by warsaw** [comment]
Ah, that makes sense!  Yes, a better error message would definitely help.  I'll file any necessary bug with flake8.

**Comment by hauntsaninja** [comment]
At some point in the last three years, mypy added a hint to this error message suggesting the generic
