### ISSUE TITLE
dmypy issue with `mypy.ini` 

### ISSUE THREAD

**Issue by timabbott** [python/mypy#5168]
In http://github.com/zulip/zulip/, we've been running `dmypy` with this commit from master: https://github.com/python/mypy.git@6a934d32124991a77ea433856cf2d62871ceb632#egg=mypy==0.610+dev.6a934d32124991a77ea433856cf2d62871ceb632

Generally, it's been great, but we've been prevented from turning it on by default because I've been seeing it throw occasional errors like this (generally shows up after a lot of rebasing; I switch branches dozens of times a day as part of merging things):

```
(zulip-py3-venv) tabbott@zaset:~/zulip$ ./tools/run-mypy -d
zproject/test_settings.py:22: error: Need type annotation for 'REALM_HOSTS'
zproject/test_settings.py:43: error: Incompatible types in assignment (expression has type "None", variable has type "str")
zproject/test_settings.py:61: error: Incompatible types in assignment (expression has type "Tuple[str, ...]", variable has type "Tuple[str, str, str, str]")
zproject/test_settings.py:80: error: Dict entry 2 has incompatible type "str": "int"; expected "str": "Union[Dict[str, int], str, None]"
zproject/test_settings.py:80: error: Dict entry 3 has incompatible type "str": "int"; expected "str": "Union[Dict[str, int], str, None]"
zproject/test_settings.py:152: error: Need type annotation for 'PUSH_NOTIFICATION_BOUNCER_URL'
```

but this shouldn't be happening, since we have this in our `mypy.ini`:

```
[mypy-zproject.test_settings]                                                                                                            
ignore_errors = True                                                                                                                     
```

I have it reproduced currently in my laptop, so if there's something I can do to dump data from `dmypy` or otherwise help debug, I'd love to do that.

As a sidenote, why `dmypy` instead of `mypyd`?  I feel like the latter is the traditional UNIX name :)

**Comment by ilevkivskyi** [comment]
@msullivan might have some ideas about why this can happen.

**Comment by msullivan** [comment]
It looks like we don't use the per-module options when rechecking module top levels due to a trigger!
Both of these tests fail with errors in the second stage:
```
[case testRefreshIgnoreErrors]
[file mypy.ini]
[[mypy]
[[mypy-b]
ignore_errors = True
[file a.py]
y = '1'
[file a.py.2]
y = 1
[file b.py]
from a import y
x = None
[out]
==
```
and
```
[case testRefreshOptions]
[file mypy.ini]
[[mypy]
disallow_any_generics = True
[[mypy-b]
disallow_any_generics = False
[file a.py]
y = '1'
[file a.py.2]
y = 1
[file b.py]
from typing import List
from a import y
x = []  # type: List
[builtins fixtures/list.pyi]
[out]
==
```

I can take a look at fixing this tomorrow, it probably will be simple.

This bug falls into the annoying category of "bad enough that I wish it was going to be fixed in the release going out tomorrow" but "not bad enough to be worth cherry-picking a fix at this point". Sigh.
