### ISSUE TITLE
[Feature request] Allow pipe ( "|" ) to be used as a shortcut for Union 

### ISSUE THREAD

**Issue by ksamuel** [python/mypy#5178]
Union are a very common situation when typing code, but they require an import every time. I usually can get away with `str`/`int`/`float` or my own classes for most of the code, but end up making an import just for `Union`, `Dict` and `List`.

The idea would be to allow Union to be expressed with a "`|`", replacing the `Union`:

```
from typing import Union

def multiply(*values: Union[int, float]) ->  Union[int, float]:
```

Would become:

```
def multiply(*values: int|float) ->  float|int:
```

**Comment by ethanhs** [comment]
This would normally be a discussion for the [typing tracker](https://github.com/python/typing/issues), but it has been rejected [several](https://github.com/python/typing/issues/387) [times](https://github.com/python/typing/issues/497). Closing as not about mypy.
