### ISSUE TITLE
Unable to infer attribute type from constructor `__init__`

### ISSUE THREAD

**Issue by jcrada** [python/mypy#5182]
There is a bug when attempting to infer type of attribute defined in the constructor `__init__`.

In example below, check type of Testing.value.

```python
# file testing.py
class Testing(object):
    def __init__(self, value: float = 1.0) -> None:
        self.value = value

# file test.py
import testing
def test(x: float, error: typing.Optional[float] = None) -> bool:
    if error is None:
        error = testing.Testing().value
    return x < error  # line 35
```
Actual behaviour:
`fuzzylite/operation.py:35: error: Unsupported operand types for < ("float" and "Optional[float]")`

Expected behaviour:
No error because Testing.value is a `float`

Hack-y fix: re-declare `self.value: float = value` in `Testing`

Python: Python 3.6.5
mypy: mypy 0.610 
mypy-master: different error `fuzzylite/__init__.py:1: error: Cannot find 'builtins' module. Typeshed appears broken!`

* What are the mypy flags you are using? (For example --strict-optional)
mypy --strict

**Comment by gvanrossum** [comment]
Can you add reveal_type(testing.Testing().value)? Given this error I'd
expect Optional[float], which isstrange. (Though I suspect you didn't run
exactly the code you showed, since your error shows
"fuzzylite/operation.py:35". :-)

**Comment by jcrada** [comment]
@gvanrossum thanks for your message.
I have committed my particular case to my repo, which you can see running `mypy fuzzylite --strict` from its root. 
The output of the `reveal_type` is consistent to what we expect, but the error still appears.
Please, take a look at https://github.com/fuzzylite/pyfuzzylite/blob/master/fuzzylite/operation.py#L32. The errors below are corresponding to each of the line numbers.

```
fuzzylite/operation.py:33: error: Revealed type is 'Union[builtins.float, None]'
fuzzylite/operation.py:36: error: Revealed type is 'fuzzylite.library.Library'
fuzzylite/operation.py:37: error: Revealed type is 'builtins.float'
fuzzylite/operation.py:38: error: Revealed type is 'builtins.float'
fuzzylite/operation.py:39: error: Revealed type is 'builtins.float*'
fuzzylite/operation.py:41: error: Unsupported operand types for < ("float" and "Optional[float]")
```

Shortcuts of other lines involved: https://github.com/fuzzylite/pyfuzzylite/blob/master/fuzzylite/__init__.py#L39
https://github.com/fuzzylite/pyfuzzylite/blob/master/fuzzylite/library.py#L29

**Comment by gvanrossum** [comment]
Oh, there's more here than meets the eye. At [this line](https://github.com/fuzzylite/pyfuzzylite/blob/c897d027da9d02bc4bd2b2dd0cc3d0dabb0a908b/fuzzylite/__init__.py#L39) an ambiguity is introduced, which may be the cause of the problem: it overrides `fuzzylite.library` (a submodule) with an instance of `Library`.

**Comment by jcrada** [comment]
Thanks for taking a look. 

I have removed the ambiguity and committed, but the problem still persists.
Links are still valid, plus new one: https://github.com/fuzzylite/pyfuzzylite/blob/master/fuzzylite/library_.py#L28

Errors:
```
fuzzylite/operation.py:28: error: Revealed type is 'Union[builtins.float, None]'
fuzzylite/operation.py:31: error: Revealed type is 'fuzzylite.library_.Library'
fuzzylite/operation.py:32: error: Revealed type is 'builtins.float'
fuzzylite/operation.py:34: error: Revealed type is 'builtins.float'
fuzzylite/operation.py:36: error: Unsupported operand types for < ("float" and "Optional[float]")
```

**Comment by gvanrossum** [comment]
OK, fair enough. It's a lot of import * though. Can you boil it down to a
much simpler example (like what you pasted originally, but actually show
that it's still got the same error)?

**Comment by jcrada** [comment]
I was not able to reproduce it deleting all the classes except for those ones involved. I did clean up my `import *` from `__init__.py` (https://github.com/fuzzylite/pyfuzzylite/blob/master/fuzzylite/__init__.py), but the issue persists. It might be related to circular references in my library, but I am just speculating. My workaround was to re-specify the type of the variable, which seems to work just fine.
 
See: https://github.com/fuzzylite/pyfuzzylite/blob/master/fuzzylite/library.py#L29

Let me know if I can try anything else. Thanks!

**Comment by gvanrossum** [comment]
If you're looking for a work-around, you've got it. If you're looking to
find the root cause, we really need a smaller example. You're right that
it's probably due to a circular import -- perhaps you should analyze your
internal dependencies and try to reimagine them as a DAG.

**Comment by jcrada** [comment]
Oh, I would be keen in helping find this one out, but tried creating a smaller example without success.
Is there any tool to visualise circular references? 
Is there an easy way to debug mypy on my project? 
Is there some good practices on circular references or importing modules that I am missing? Thanks!

**Comment by 97littleleaf11** [comment]
Had been fixed!
