### ISSUE TITLE
Bogus overlapping incompatible return types for overloads

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#5188]
I believe this is a bug in the overload implementation. 

I just ran the mypy tests in typeshed with mypy 0.610 installed. When it checked https://github.com/python/typeshed/blob/master/stdlib/3.7/dataclasses.pyi#L34 it reported:
```
stdlib\3.7\dataclasses.pyi:37: error: Overloaded function signatures 1 and 3 overlap with incompatible return types
stdlib\3.7\dataclasses.pyi:42: error: Overloaded function signatures 2 and 3 overlap with incompatible return types
```
AIUI `Any` should be compatible here.

I was able to simplify the example to this:
```
from typing import overload, TypeVar, Any, Union

T = TypeVar('T')

@overload
def f(*, a: T) -> T: ...  # error: Overloaded function signatures 1 and 3 overlap with incompatible return types

@overload
def f(*, b: T) -> T: ...  # error: Overloaded function signatures 2 and 3 overlap with incompatible return types

@overload
def f(*, c: bool) -> Any: ...
```
Interestingly, removing `c: bool` from the third overload and only passing `*args` makes the error go away.

@Michael0x2a thoughts?

**Comment by Michael0x2a** [comment]
@ethanhs -- just to confirm, this happens when using mypy 0.610 but not when using master? The former basically has the old overloads impl, the latter has the new.

(I'm not on my computer atm so can't check for myself).

**Comment by ilevkivskyi** [comment]
It was already fixed and works on master, recent overload work is not in the release.

**Comment by ethanhs** [comment]
D'Oh, I thought that had made it into the release. Thanks @ilevkivskyi.
