### ISSUE TITLE
Support for pyproject.toml

### ISSUE THREAD

**Issue by pslacerda** [python/mypy#5205]
PEP518 says that `pyproject.toml` is to support the minimum build requirements. I want to consider mypy as part of the minimum build on my package.

For example Pip uses a `[tool.towncrier]` section on `pyproject.toml` to generate a correctly updated `NEWS.rst` as part of its build. One can considers typing correctness as important to the distributed source pakcage as an well documented `NEWS.rst`. Other example is Black that also has it section on `pyproject.toml`.

Maybe you think that this is a silly feature request and that `setup.cfg` must be used instead, Pip or Flit or whatever can setup mypy after all. But an TOML module will be added to the standard library sooner or later, than could mypy accept this feature and antecipate TOML supporting `pyproject.toml` today?

**Comment by ilevkivskyi** [comment]
PEP 518 is accepted and specifies that `pyproject.toml` is preferred over `setup.cfg`, so I think we should support whatever the PEP specifies.

**Comment by gvanrossum** [comment]
Does adding pyproject.toml mean that we can remove other config files?
Until that point I'm not excited.

**Comment by pslacerda** [comment]
I think that removing other config files would simplify config parsing even more. I would be very glad to change `mypy.main.parse_config_file()` accordingly.

If you agree that `mypy==0.620` it is still in its early ages, would be exciting to remove the other config files. Otherwise I'm already coding the unexciting changes to support both legacy and `pyproject.toml`.

There is already lots of deprecated options:

```
--disallow-any
--strict-boolean
--dirty-stub
--use-python-pat
--silent-import
--almost-silen
--fast-parser
--no-fast-parser
``` 

So legacy config files (`mypy.ini`, `setup.cfg` and `~/.mypy.ini`) could also be one of them.

**Comment by gvanrossum** [comment]
Note that mypy.ini serves a completely different purpose from setup.py, setup.cfg, and pyproject.toml. The mypy.ini file is read by mypy when it is about to type-check another program. The other files (IIUC) are used to build mypy itself. I don't think we can change mypy.ini much, though we *can* start removing deprecated flags (after they have been printing a warning for 1-2 release cycles). Please do that in a separate PR.

**Comment by pslacerda** [comment]
Even if `setup.cfg` was created originally for distutils or setuptools, everybody else seems to use it as an generic configuration file. PyTest for example don't care if is running from `setup.py` or whatever, it simply reads `setup.cfg` if it is found; many tools seems to do it (eg flake8, isort and even mypy).

If you are talking about to replace `setup.py` by `pyproject.toml`, yes it is indeed an legibility win.

Now taking about mypy config files when type-checking other programs, they are all equivalents and fallbacks of the next one (`--config-file` -> `mypy.ini`  -> `setup.cfg` ->  `~/.mypy.ini`; http://mypy.readthedocs.io/en/latest/config_file.html. I'm talking to deprecate these ini-like config files and use toml, it is even more typed!

I will submit a PR  to remove that flags later on.

**Comment by pslacerda** [comment]
To put it clear: enable sections like `[tool.mypy]` or `[tool.mypy-somepackage]` in `pyproject.toml`.

**Comment by gvanrossum** [comment]
Switching mypy.ini to a toml thing sounds like scope creep and we won't have the time and motivation to review PRs related to this, so please don't start on that. The rest is fine of course.

**Comment by pslacerda** [comment]
Seems that I misunderstood that to remove others would be necessary to the overral comunity need to target the same. Sorry.

> Does adding pyproject.toml mean that we can remove other config files? Until that point I'm not excited.

**Comment by JelleZijlstra** [comment]
So what exactly is being proposed here?

There's a few things I can think of:
- Add support for reading mypy's configuration out of `pyproject.toml`. In addition, we should still support reading configs out of `setup.cfg` and `mypy.ini` for backward compatibility. We could perhaps deprecate `setup.cfg` support though.
- Move configurations within mypy's own repo to `pyproject.toml`. This could replace the current `pytest.ini` and `setup.cfg` files. Not sure whether all current tools that read these config files support `pyproject.toml` yet though.

**Comment by ethanhs** [comment]
Pytest seems to be stalled until someone works on it https://github.com/pytest-dev/pytest/issues/1556

An issue for flake8 was opened yesterday https://gitlab.com/pycqa/flake8/issues/428

And the same for coverage https://bitbucket.org/ned/coveragepy/issues/664/allow-configuration-via-pyprojecttoml

I think we should add support for reading mypy's configuration from pyproject.toml, but it looks like we will need to wait to use it for our own config.

**Comment by pslacerda** [comment]
@JelleZijlstra 

The first option. IMHO were some convergence towards `each_project.ini` then `setup.cfg` and now towards `pyproject.toml`. The messy that was tooling configuration seems to be finally ending. Indeed I have some sort of working code, a TOML library was required but pretty much can be packed together instead.

https://github.com/python/mypy/compare/master...pslacerda:feature/pep518

But also the second option. 

@ethanhs, seems that as more and more projects adopt it, more sense has to put all that config files centralized. There is divergent opinions for projects with very large `pytest.ini`, `flake8.ini` and so on. So maybe individual config files should continue where they are.

**Comment by pslacerda** [comment]
Maybe that branch isn't so rudimentary and maybe you allow I submmit this PR.

**Comment by gvanrossum** [comment]
If you do want to continue this discussion please do submit the PR. Please understand that doesn't mean it will be accepted.

**Comment by gvanrossum** [comment]
Thanks -- I finally understand that TOML is meant as an alternative to mypy.ini. My apologies for not understanding this earlier. There is no particular urgency for this, is there? The PR is nice to have but we'll need to find time to review it carefully. Also, did you add tests?

**Comment by pslacerda** [comment]
Take your time to review, there is no urgency. I adapted some tests and also put my opinions on the PR.

**Comment by gvanrossum** [comment]
I've rejected the PR, and I'm going to close this issue. I don't think this solves a real problem for mypy. Sorry!

**Comment by pslacerda** [comment]
I'm saying that mypy is a build/test time requirement in my projects.

**Comment by gvanrossum** [comment]
PEP 518 doesn't say that all build/test requirements must use pyproject.toml for their own configuration. It only says that the list of packages to be installed must be specified there (as opposed to in a parameter to the setup() call in setup.py).

**Comment by and-semakin** [comment]
Hey, it would be nice to remove `setup.cfg` and completely switch to using fresh modern `pyproject.toml` but we can't do this because of `mypy` :disappointed:

**Comment by JelleZijlstra** [comment]
There's actually some risk in doing that. [http://github.com/python/black](Black) only supports `pyproject.toml` as its configuration file, but this has caused grief for various users because the mere presence of `pyproject.toml` causes some versions of pip to process packages differently, even if `pyproject.toml` contained only Black configuration files.

**Comment by cmcarey** [comment]
> 
> 
> There's actually some risk in doing that. [http://github.com/python/black](Black) only supports `pyproject.toml` as its configuration file, but this has caused grief for various users because the mere presence of `pyproject.toml` causes some versions of pip to process packages differently, even if `pyproject.toml` contained only Black configuration files.

I don't think that's a reasonable concern.  PEP 518 indicates that `pyproject.toml` is "the way forward".  That some tools fail to parse it correctly is on them, it shouldn't be used as evidence that implementing support for `pyproject.toml` is a bad thing.

**Comment by cmcarey** [comment]
> 
> 
> I've rejected the PR, and I'm going to close this issue. I don't think this solves a real problem for mypy. Sorry!

Perhaps not for mypy, but I think having a *good* standard format and place to store config for tools that are used during development is a boon.  PEP 518 [does specify](https://www.python.org/dev/peps/pep-0518/#tool-table) a `[tool]` section, and comments on it:

> The [tool] table is where any tool related to your Python project, not just build tools, can have users specify configuration data as long as they use a sub-table within [tool], e.g. the flit tool would store its configuration in [tool.flit]

**Comment by cmcarey** [comment]
@gvanrossum 

> I've rejected the PR, and I'm going to close this issue. I don't think this solves a real problem for mypy. Sorry!

Perhaps not for mypy, but I think having a *good* standard format and place to store config for tools that are used during development is a boon.  PEP 518 [does specify](https://www.python.org/dev/peps/pep-0518/#tool-table) a `[tool]` section, and comments on it:

> The [tool] table is where any tool related to your Python project, not just build tools, can have users specify configuration data as long as they use a sub-table within [tool], e.g. the flit tool would store its configuration in [tool.flit]

**Comment by prokher** [comment]
@gvanrossum 
> I've rejected the PR, and I'm going to close this issue. I don't think this solves a real problem for mypy. Sorry!

Indeed, MyPy's support of `pyproject.toml` does not solve a real problem now. But taking into account the inter-language competition we have (Python vs JS vs Go vs TypeScript vs ...) everything matters. Especially if we recall that the population of software engineers grow at a very high rate and languages we basically fight for newcomers. I think that today the beauty of the ecosystem is as important as the beauty of the language itself. Python is a beautiful and expressive language, but why should I have all this configuration-management-related files in the root of every Python project I work on (`.pylintrc`, `.mypyrc`, `setup.py`, `setup.cfg`, `isort.cfg`, ...)? It just looks ugly IMHO. I agree, it is not a serious problem to fight against, but `pyproject.toml` is already here and it is seems not to be a big deal to support it in MyPy. Moreover this could be a good example for other Python tools to follow. So one day we can end with a single configuration file for every Python project, it would be nice.

Just sharing.

**Comment by cmcarey** [comment]
@prokher 

> but `pyproject.toml` is already here and it is seems not to be a big deal to support it in MyPy

Indeed, and someone already has a working PR ...

**Comment by pslacerda** [comment]
Don't really belong here, but just remembering the situation right now.

![image](https://user-images.githubusercontent.com/149358/62793025-f8062300-baa6-11e9-9288-57988f276efa.png)

**Comment by PgLoLo** [comment]
Please, add pyproject.toml support

**Comment by NargiT** [comment]
> PEP 518 doesn't say that all build/test requirements must use pyproject.toml for their own configuration. It only says that the list of packages to be installed must be specified there (as opposed to in a parameter to the setup() call in setup.py).

Allow me to disagree. source: https://www.python.org/dev/peps/pep-0518/#tool-table

> The [tool] table is where any tool related to your Python project, not just build tools, can have users specify configuration data as long as they use a sub-table within [tool], e.g. the flit tool would store its configuration in [tool.flit].
> 
> We need some mechanism to allocate names within the tool.* namespace, to make sure that different projects don't attempt to use the same sub-table and collide. Our rule is that a project can use the subtable tool.$NAME if, and only if, they own the entry for $NAME in the Cheeseshop/PyPI.

As an example, tox plan to also support fully pyporject.toml "https://tox.readthedocs.io/en/latest/example/basic.html#pyproject-toml-tox-legacy-ini".

**Comment by JukkaL** [comment]
There seems to be quite a bit of interest in adding pyproject.toml support. We can reconsider accepting a PR, but I'd like to understand this a bit better first. Hopefully somebody can help with these questions:

1. Which notable developer tools currently (Aug 2019) support storing their configuration in pyproject.toml files in `[tool.foo]` sections?
2. Which notable open source Python projects use the `[tool.foo]` sections in their pyproject.toml files?

I'm basically trying to understand how mature and widespread the use of the `[tool]` section is at the moment.

We would still continue to support `mypy.ini` files, as requiring every user to migrate to pyproject.toml would be too disruptive.

**Comment by impredicative** [comment]
@JukkaL `black` is the only notable tool I am aware of in static analysis (and/or autoformatting) circles that meets #1. Many more including mypy support `setup.cfg` and that is good and important. I don't think anyone should have to migrate to pyproject.toml in the short to medium term, but all of these tools do need to come together and use a single file. It's atrocious the number of such files I have to have in a project.

In general I see no harm in adding support, but right now it won't help me until other setup.cfg supporting tools like coverage, pycodestyle, and pytest also do the same. Thanks.

**Comment by cmcarey** [comment]
@JukkaL 

Tox currently has a naive implementation but plans to implement full support soon - https://tox.readthedocs.io/en/latest/example/basic.html#pyproject-toml-tox-legacy-ini

Black uses `pyproject.toml` for config exclusively - https://black.readthedocs.io/en/stable/pyproject_toml.html

Flit uses `pyproject.toml` (soon exclusively) - https://flit.readthedocs.io/en/latest/pyproject_toml.html

isort uses `pyproject.toml`.

Those are some of the most known tools I can find that use it.  Flake8 has a [well supported](https://gitlab.com/pycqa/flake8/issues/428) issue open about supporting `pyproject.toml`

**Comment by pslacerda** [comment]
Many projects uses pyproject.toml, some exclusively (which is too much for most of us). Both are required  for most projects keep going. A deprecation warning could stimulate the adoption of pyproject.toml.

**Comment by prokher** [comment]
I would also mention Poetry: https://poetry.eustace.io

**Comment by cmcarey** [comment]
@JukkaL any chance we could get this issue re-opened?

**Comment by JukkaL** [comment]
I'm reopening the issue for discussion, but we are not committing to any timeline yet.

**Comment by ethanhs** [comment]
By the way, if we do go ahead with this, I'm happy to help review/maintain the code, if that helps.

**Comment by DaniGuardiola** [comment]
Managed to remove a bunch of python configuration files thanks to `pyproject.toml`. The only remaining file is `setup.cfg` because of mypy. I can live with it, but it is pretty annoying. Just my two cents. Would really appreciate support for `pyproject.toml`.

**Comment by pslacerda** [comment]
@DaniGuardiola Some years ago I thought that require `pyproject.toml` was too much. Only one project I was trying out (Black) required it, all other tools accepted `setup.cfg`. It was too much ahead and I had a similar annoying felling but in the reverse. Now the situation changed and more projects started to adopt `pyproject.toml`, Tox for instance. I miss pytest.

TOML has a so better syntax and typing that could alleviate user configuration bugs if adopted I guess. Its syntax is easy but more complex than ini files and because of this not everybody can support it into their own programs (myself for instance) without a library. However it isn't that much of a problem because there is a library for that.

I'd love to have my PR accepted. It worked well for me last year but if @ethanhs deem it unsuitable wouldn't be that hard for someone to do another PR.

The conversion of user files from `setup.cfg` to `pyproject.toml` is so trivial (at least in all files I saw) that a Github bot can scan projects that use Mypy, Tox, isort and so on do the PRs itself.

I hope that this issue get resolved soon and some pull request get merged (hopefully mine) because not only is a demanded that will reduce annoy but also because maybe it will reduce bugs.

**Comment by flying-sheep** [comment]
PEP 518 was accepted and its “Rejected ideas” section contains [“sticking with setup.cfg”](https://www.python.org/dev/peps/pep-0518/#sticking-with-setup-cfg), which means that setup.cfg is deprecated as a place to put project-wide static tool configuration.

Therefore I think reopening #5208 and eventually deprecating and then removing setup.cfg support everywhere would make sense.

**Comment by ethanhs** [comment]
Hi, I have no objections to the PR at face value, but the team would like to have more discussion on this.

I personally would like to see this happen but I cannot speak for the team as a whole.

Adding another config format would make maintenance harder, which we want to avoid.

That being said, if @flying-sheep's interpretation of the PEP is correct, then we can probably kill setup.cfg support and support pyproject.toml. However based on my understanding, it is not correct. I will ask on discuss.python.org for suggestions from the packaging folks.

**Comment by flying-sheep** [comment]
I understand your concerns. As a maintainer myself, I know the pains of slowly transitioning to “the new way” in terms of maintenance. However (not that I imply you proposed this): I don’t think it’s fair to have the stance “we’ll switch last, if adoption gets high”. That’s a self-fulfilling prophecy if many think this way. I think the only way to be a good open source citizen is to switch early, support both ways until many have switched, and then remove the old way.

**Comment by danieljanes** [comment]
@JukkaL as of Dec 2019, amongst the major tools we use, 3/5 have support for `pyproject.toml`:

Support:
- Black: https://black.readthedocs.io/en/stable/pyproject_toml.html
- isort: https://pypi.org/project/isort/ (mentioned under "Configuring isort")
- Pylint: Will add support in the 2.5 release https://docs.pylint.org/en/latest/whatsnew/2.5.html

No support:
- mypy
- Pytest (but: Pytest uses pyproject.toml internally: https://github.com/pytest-dev/pytest/blob/master/pyproject.toml)

**Comment by JukkaL** [comment]
It looks like pyproject.toml is gaining enough traction that we can accept a PR that adds support for it.

**Comment by cmcarey** [comment]
@JukkaL There was a PR for this previously - https://github.com/python/mypy/pull/5208

But Guido closed it.

**Comment by JukkaL** [comment]
Maybe the original PR can be resurrected?

**Comment by JukkaL** [comment]
I've reopened #5208.

**Comment by pslacerda** [comment]
How to options specific to package/module?

```toml
[mypy]
some_opt = 1

# is it acceptable?
[mypy."specific.*.module"]
some_opt = 2
```

**Comment by flying-sheep** [comment]
As @layday said, I’d think

```toml
[mypy.overrides."specific.*.module"]
some_opt = 2
# or
[mypy.specific."*".module]
some_opt = 2
```

**Comment by layday** [comment]
Note that the latter example expands into

```py
{'mypy': {'overrides': {'specific': {'*': {'module': {'some_opt': 2}}}}}}
```

which is almost certainly not what we want.

**Comment by pslacerda** [comment]
I'm now aware. Handy in case someone needs to parse the file by themselves (like a GitHub bot that converts setup.cfg into pyproject.toml).

```toml
[mypy.overrides."specific.*.module"]
some_opt = 2
# or
[mypy.overrides."other.*.package"]
some_opt = 2
```

**Comment by chadgh** [comment]
Here is the [awesome-pyproject](https://github.com/carlosperate/awesome-pyproject/) list. It would be helpful if and when mypy supports pyproject.toml to notify the list maintainer or submitting a PR to update the list indicating that mypy supports the file now. Just FYI. :)

**Comment by victorusachev** [comment]
For a number of tools, you have to specify the same parameters in several files, it would be convenient to see them side by side, as well as not have a bunch of files in the root of the project. So, So, I definitely need a configuration in one place.

**Comment by brettcannon** [comment]
FYI I wrote a [blog post recently explaining `pyproject.toml`](https://snarky.ca/what-the-heck-is-pyproject-toml/). I thought it might be useful to share here as at least early on in the discussion here there were some misunderstandings over the purpose of the file.

And selfishly, mypy is the one tool I used on all of my projects, app and package alike, which does **not** support `pyproject.toml` as an option (Black and coverage.py being the other projects). 😁

**Comment by ffe4** [comment]
Not sure what the status is on this issue, but it seems pytest will also start supporting `pyproject.toml` for configuration. The PR has already been merged ([#7242](https://github.com/pytest-dev/pytest/pull/7247))

**Comment by johnthagen** [comment]
[pytest `pyproject.toml` support has now been released in 6.0.0rc1](https://docs.pytest.org/en/latest/changelog.html#features).

**Comment by fgimian** [comment]
> FYI I wrote a [blog post recently explaining `pyproject.toml`](https://snarky.ca/what-the-heck-is-pyproject-toml/). I thought it might be useful to share here as at least early on in the discussion here there were some misunderstandings over the purpose of the file.
> 
> And selfishly, mypy is the one tool I used on all of my projects, app and package alike, which does **not** support `pyproject.toml` as an option (Black and coverage.py being the other projects). 😁

Just FYI to anyone who is unaware, Black supports pyproject.toml now too: https://black.readthedocs.io/en/stable/pyproject_toml.html

**Comment by elgalu** [comment]
I've just created myself an [AnkiDroid flashcard](https://play.google.com/store/apps/details?id=com.ichi2.anki&hl=en&gl=US) to remember the fact that, as of 2021, only {{c1::flake8}} and {{c1::mypy}} are still missing pyproject.toml support.

**Comment by flying-sheep** [comment]
Since [PEP 631](https://www.python.org/dev/peps/pep-0631/) is accepted (Dependency specification in pyproject.toml), it seems like pyproject.toml is cemented as *the* way to do project configuration and setup.cfg is going the way of the dodo.

@ethanhs since you said you’d maintain this if it’s accepted: what’s the decision of the team regarding this in 2021?

**Comment by ethanhs** [comment]
I don't think I can still make that offer considering the other time demands I have. I'm happy to *help* in review and maintenance, but I am too busy to be the sole maintainer. It would be great for mypy to support pyproject.toml for configuration, but I think someone will have to step forward to implement support for it, and that simply hasn't happened.

**Comment by uranusjr** [comment]
> Since [PEP 631](https://www.python.org/dev/peps/pep-0631/) is accepted (Dependency specification in pyproject.toml), it seems like pyproject.toml is cemented as _the_ way to do project configuration and setup.cfg is going the way of the dodo.

PyPA’s position has always been, and likely will be that `pyproject.toml` is only cemented as the way to *declare packaging metadata*. We do not encourage projects to store non-packaging-related configuration in `pyproject.toml` (although we don’t stop projects if they insist). It would be perfectly appropriate if Mypy decides to not support configuring with `pyproject.toml` at all.

It is also not accurate to say `setup.cfg` is going to be obsolete. Packaging tools are still free to use their own configuration file for things specific to themselves (i.e. things not relevant to any other packaging tools), and I can see setuptools continuing to support `setup.cfg` for those usages even after they implement PEP 631. The thing that might loose popularity is *using `setup.cfg` as the de-facto stadard project-level configuration file*. Mypy can choose to drop support to `setup.cfg` (because using `setup.cfg` in this way will no longer be popular), support `pyproject.toml` (because it’s okay to do it and people want it), or do neither or both.

**Comment by johnthagen** [comment]
> We do not encourage projects to store non-packaging-related configuration in `pyproject.toml`

I'm not disagreeing with anything you said, but I do think it's worth pointing out that [PEP 518 explicitly defines the `[tool]` table](https://www.python.org/dev/peps/pep-0518/#tool-table) as an official mechanism for tools to define non-packaging-related configuration in `pyproject.toml`. To me that is at least an implicit nod towards projects doing this if they wish.

**Comment by uranusjr** [comment]
An earlier version of PEP 518 actually says `tool` is for packaging tools, but that led to a lot of finger-pointing when Black and Towncrier starts to use it, so the language is soften to stop the argument. But PyPA’s stance does not change much.

**Comment by lig** [comment]
Let's face it the "PyPA’s stance" is just an opinion of a small number of community members which clearly contradicts the process actually happening in the community and the request for that being highly spread.

**Comment by brettcannon** [comment]
I think a better way to phrase it is the PyPA is not _mandating_ tools use `pyproject.toml`, but the support for doing so is definitely there and available for tools that _want_ to use it (hence the "do not encourage" from @uranusjr ; it's not the same as "discourage", just that the PyPA is not taking a stance since it's way beyond any mandate or purview of PyPA to do so).

Personally, I want tools to use it. 😉

**Comment by Jasha10** [comment]
Ok there has been much talk about this issue, and since it is re-opened, I'm guessing that the mypy maintainers would be willing to humor pull-requests from the community.

So, maybe it's time to shift the discussion from "gosh I wish this feature were implemented" to "how can this feature be implemented".

**Comment by JelleZijlstra** [comment]
Exactly. The next step here should be a pull request. I'll try to make time to review it, but first we need a pull request.

**Comment by Jasha10** [comment]
I am not familiar with mypy internals. Does mypy have some sort of config IR that is used as a destination for both `mypy.ini` files and command line arguments?
(I'm thinking that, if so, this config IR could be a destination for `pyproject.toml` too)

**Comment by hauntsaninja** [comment]
Refer to https://github.com/python/mypy/pull/5208#pullrequestreview-511175639

**Comment by patrickelectric** [comment]
Any plan to do a release with this feature ?

**Comment by JukkaL** [comment]
Hopefully there's a new release within the next month (as always, no promises).

**Comment by kthy** [comment]
I hope so, because the docs are already updated and as a new user I've just spent an hour wondering why I couldn't get it to work. Then I found this issue. :clown:

**Comment by jeffnyman** [comment]
I understand this is closed but I'm trying to understand why something I used before doesn't work. I was at least able to do this before:

```
poetry run mypy --config-file pyproject.toml tests
```

In my `pyproject.toml` I would have:

```
[mypy]

[mypy-expects]
ignore_missing_imports = true
```

This would work. The message about missing imports would be gone for the expects library. It no longer does when I'm using 0.910. In fact, it looks like it stopped working in 0.900. If I go back to 0.812, it works fine.

I was just calling this out to make sure if this was a deliberate change.

**Comment by Tinche** [comment]
> I understand this is closed but I'm trying to understand why something I used before doesn't work. I was at least able to do this before:
> 
> ```
> poetry run mypy --config-file pyproject.toml tests
> ```
> 
> In my `pyproject.toml` I would have:
> 
> ```
> [mypy]
> 
> [mypy-expects]
> ignore_missing_imports = true
> ```
> 
> This would work. The message about missing imports would be gone for the expects library. It no longer does when I'm using 0.910. In fact, it looks like it stopped working in 0.900. If I go back to 0.812, it works fine.
> 
> I was just calling this out to make sure if this was a deliberate change.

The syntax in pyproject.toml is a little different, you need to use `[[tool.mypy.overrides]]` sections. It's in the docs somewhere.

**Comment by jeffnyman** [comment]
> The syntax in pyproject.toml is a little different, you need to use `[[tool.mypy.overrides]]` sections. It's in the docs somewhere.

Ah! Much thanks. Yes, I did find it here: https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file
