### ISSUE TITLE
Support __setattr__

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#521]
See https://github.com/JukkaL/mypy/issues/520

**Comment by gvanrossum** [comment]
This is blocking some typeshed improvements, e.g. [threading.locals](https://github.com/python/typeshed/blob/master/stdlib/2and3/threading.pyi#L44) and https://github.com/python/typeshed/blob/master/stdlib/2and3/argparse.pyi#L115 (the latter doesn't actually work!).

**Comment by gnprice** [comment]
Specifically, if I understand this right, the idea is to make it so that if a type has a `__setattr__`, we'll allow setting any attribute with a value of a type compatible with the `__setattr__` parameter type.

**Comment by gvanrossum** [comment]
This is now the oldest high priority issue...

**Comment by ilevkivskyi** [comment]
This was fixed by #3451
