### ISSUE TITLE
Double underscore name mangling in classes to allow independent types

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#523]
Mypy should perform name mangling in classes.

**Comment by marmistrz** [comment]
A simple example, exposing the behavior:
```
class foo:
    def __bar(self) -> None:
        print("xD")

foo()._foo__bar()
```

```
/tmp/test.py:5: error: "foo" has no attribute "_foo__bar"
```

**Comment by gvanrossum** [comment]
That looks intentional. You shouldn't be accessing private attributes like that.

**Comment by marmistrz** [comment]
@gvanrossum in production code not. But in tests you sometimes need to access the internal state of the object to validate what happened.

**Comment by JukkaL** [comment]
You can use `getattr(foo(), '_foo__bar')()` in tests. The main issue is allowing multiple classes in a class hierarchy use the same `__foo` attribute with independent types.

**Comment by marmistrz** [comment]
@JukkaL, yes, but it's less readable

**Comment by kwvanderlinde** [comment]
The fact of the matter is that `foo` does have the attribute `_foo__bar` and we all know it. The error message is a blatant lie and a source of confusion.

**Comment by gvanrossum** [comment]
Thank you for your encouragement. You should just use `# type: ignore` and move on. If you do this a lot, clearly something is wrong in your application or API design and mypy should not endorse that.

**Comment by ilevkivskyi** [comment]
@gvanrossum 
> You should just use ``# type: ignore`` and move on. If you do this a lot, clearly something is wrong in your application or API design and mypy should not endorse that.

As @JukkaL mentioned the original issue is _not_ about allowing ``Foo()._Foo__foo``, this is issue is about allowing things like:
```python
class B:
    __foo: int
class C(B):
    __foo: str
```
which is type safe but currently prohibited.

**Comment by gvanrossum** [comment]
Ouch, sorry, I read too quickly.

**Comment by rafaelcaricio** [comment]
I'm looking into this one.
