### ISSUE TITLE
Running the PEP 561 tests causes FileNotFoundErrors on Windows

### ISSUE THREAD

**Issue by Michael0x2a** [python/mypy#5234]
I'm currently getting a few `FileNotFoundError` test failures when I try running the mypy tests from master -- I'm guessing [this PR](https://github.com/python/mypy/pull/5225) is most likely the culprit?

The test outputs are a little long, so I included them in this gist: https://gist.github.com/Michael0x2a/5d022c29a305dab2f028bab84271b213

I'm currently running mypy on Windows 10. Also, I'm not sure if any of this matters or not, but I can also confirm I get the same results whether or not I use powershell or cmd, whether or not I'm running in administrator mode... I'm happy to run more experiments to help narrow down the issue if needed.

@ethanhs -- any ideas?

**Comment by ethanhs** [comment]
Did you pull master since https://github.com/python/mypy/pull/5225 ?

**Comment by Michael0x2a** [comment]
Yeah -- I pulled about 10-15 min ago.

**Comment by ethanhs** [comment]
Ah, I missed that the first time looking at the output. I will take a closer look soon.

**Comment by ethanhs** [comment]
Hm, that is unfortunate. Would either of you be able to drop into pdb before this line https://github.com/python/mypy/blob/master/mypy/test/testpep561.py#L65 and tell me if the path in `python_executable` actually exists on disk?

**Comment by Michael0x2a** [comment]
It seems apparently not. The temp folder itself exists, but appears to be empty. (So, `C:\Users\Michael\AppData\Local\Temp\tmpw5ox88q1` exists, but not `C:\Users\Michael\AppData\Local\Temp\tmpw5ox88q1\Scripts` or `C:\Users\Michael\AppData\Local\Temp\tmpw5ox88q1\Scripts\python`.

**Comment by Michael0x2a** [comment]
Out of curiosity, I tried modifying the `virtualenv` function directly so it prints the output of `run_command` if the return code isn't zero -- it seems the issue was that I didn't have the `virtualenv` package installed. I tried pip-installing it, and everything is working again!

So I guess this is really my fault -- that package is apparently listed in `test-requirements.txt` and I admittedly haven't looked at that file in a long while...

It might be nice if we added a custom error message though or maybe add the missing error code check in the `virtualenv` function.

**Comment by gvanrossum** [comment]
Also (OT) virtualenv is no longer needed, use venv instead, it's in the
stdlib.

**Comment by ethanhs** [comment]
>Also (OT) virtualenv is no longer needed, use venv instead, it's in the
stdlib.

AIUI, venv cannot create a virtualenv for another python executable, which is needed for the Python 2 tests :/

I will make a PR to print errors for the virtualenv creation.

**Comment by ethanhs** [comment]
Sorry all for the trouble!

**Comment by gvanrossum** [comment]
> venv cannot create a virtualenv for another python executable, which is needed for the Python 2 tests

Oh, wow, I did not know it could do that. Makes sense then.
