### ISSUE TITLE
Wrong overload item picked when strict optional disabled

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#5238]
When type checking the following two files, the revealed type is `unicode` though I'd expect `str` -- but only when using `-2 --no-strict-optional`:

```py
# t.py
from typing import Optional
from m import relpath
a = '' # type: Optional[str]
reveal_type(relpath(a))  # unicode
```

```py
# m.py
from typing import overload
@overload
def relpath(path: str) -> str: ...
@overload
def relpath(path: unicode) -> unicode: ...
```

The issue also happens with `os.path.relpath`.

To reproduce:

```
$ mypy -2 --no-strict-optional t.py
t.py:4: error: Revealed type is 'builtins.unicode'
```

The issue seems to be related to using an optional type in a file which doesn't use strict optional checking.

**Comment by ilevkivskyi** [comment]
I am working on this now.
