### ISSUE TITLE
mypy cannot find module inside folder without "__init_.py" file

### ISSUE THREAD

**Issue by bySabi** [python/mypy#5262]
In a Python 3 project import a module inside a folder without `__init__.py` file, `mypy` was unable to find it.

Setting root `mypy.ini` file to:
```
[mypy]
python_version = 3.6
```
Does not solved it

**Comment by gvanrossum** [comment]
Duplicate, there is already another issue for namespace packages.

**Comment by bySabi** [comment]
I did a quick search and don't found it.
sorry

I close here

**Comment by gvanrossum** [comment]
See https://github.com/python/mypy/issues/1645 and https://github.com/python/mypy/issues/1645
