### ISSUE TITLE
Generic subclass. ABCMeta object is not subscriptable

### ISSUE THREAD

**Issue by cburgdorf** [python/mypy#5264]
Please provide more information to help us understand the issue:

I'm trying to write the following

```
class ServiceContext(UserList[BaseService]):
...
```
However, that leaves me with 

```
TypeError: 'ABCMeta' object is not subscriptable
```

I know that for simple type annotations I can simply define the type in strings in cases like this. However, that clearly doesn't apply in the inheritance case.

The only solution that I found to that [seems very hacky](https://stackoverflow.com/questions/45414066/mypy-how-to-define-a-generic-subclass/48554601#48554601).

Since I want to enable `--disallow-any-generics` I need to specify the type parameter for [UserList](https://docs.python.org/3/library/collections.html#collections.UserList).

I'm wondering if there's any other alternative to that?

**Comment by ilevkivskyi** [comment]
This is a known limitation of Python standard library classes. There is a slightly less hacky solution:
```python
if TYPE_CHECKING:
    QueueBase = queue.Queue
else
    class _Queue:
        def __getitem__(*args):
            return queue.Queue
    QueueBase = _Queue()
```
In addition, for your particular use case (non-generic subclass) you can simply write:
```python
if TYPE_CHECKING:
    Base = UserList[BaseService]
else:
    Base = UserList
```
But the latter solution will work only if you don't have type variables.

**Comment by cburgdorf** [comment]
Ah, that's it! Thanks for clarifying. I think this should be part of the docs (or maybe at least reference to this answer or something).

Closing the issue.

**Comment by sultaniman** [comment]
I ended up doing sth similar to what @ilevkivskyi did, found this in mypy docs

```
T = TypeVar("T")

if TYPE_CHECKING:
    class _Queue(Queue[T]):
        pass
else:
    class _Queue(Generic[T], Queue):
        pass


class BaseQueue(_Queue[T]):
    pass
```
