### ISSUE TITLE
Allow passing a sys path to mypy 

### ISSUE THREAD

**Issue by Kronuz** [python/mypy#5268]
### Feature Request

I propose adding `--sys-path` so imports get properly resolved when a user has modules in custom paths.

**Comment by JelleZijlstra** [comment]
I think you want https://mypy.readthedocs.io/en/latest/installed_packages.html or the $MYPYPATH environment variable.

**Comment by Kronuz** [comment]
Yes, similar to the environment variable, but received by the command, as I can’t set the environment variable; I’m using it as a pyls plugin, and I need a way to pass that as part of the command: https://github.com/Kronuz/pyls-mypy/blob/0.1.3/pyls_mypy/plugin.py#L44

**Comment by JelleZijlstra** [comment]
Why can't you just change `os.environ` there?

**Comment by Kronuz** [comment]
Well, I could, but other thread could also change it, messing things up in a race condition, and at the end I’d have to restore the old environment variable.

**Comment by gvanrossum** [comment]
So wrap it in a script.

**Comment by gvanrossum** [comment]
Or set mypy_path in mypy.ini.
