### ISSUE TITLE
"Tagged" types

### ISSUE THREAD

**Issue by ikonst** [python/mypy#5272]
I've been taking a stab at typing [pynamodb](http://pynamodb.readthedocs.io/en/latest/), and haven't been able to type [MapAttribute](http://pynamodb.readthedocs.io/en/latest/attributes.html#map-attributes).

Consider the following code:
```py
from pynamodb.attributes import MapAttribute, NumberAttribute
from pynamodb.models import Model

class MyMapAttribute(MapAttribute):
   foo = NumberAttribute()
   bar = NumberAttribute()

class MyModel(Model):
   my_map = MyMapAttribute()
```

If we try to inspect this, we see:
```py
>>> MyModel.my_map
<__main__.MyMapAttribute object at 0x10adfcb38>
>>> my_model = MyModel()
>>> my_model.my_map = MyMapAttribute(foo=1, bar=2)
>>> my_model.my_map
<__main__.MyMapAttribute object at 0x10adfcd30>
```

In our code, the MapAttribute-derived type has two instances - the first serves as a "descriptor" and the second serves as the instance. Both instances contain "foo" and "bar" members, but for different purpose.

```py
>>> type(my_model.my_map) is type(MyModel.my_map)
True
>>> my_model.my_map is MyModel.my_map
False
>>> my_model.my_map.foo
1
>>> MyModel.my_map.foo
<pynamodb.attributes.NumberAttribute object at 0x10adfccc0>
```

I understand that this is somewhat contrived, but I think I could express this typing mechanism if there was a way to somehow produce a "tagged" variant of an existing type:
```py
class MapAttribute(...):
    @overload
    def __get__(self: _MT, instance: Model, owner: Any) -> Tagged[_MT, "instance"]: ...
    @overload
    def __get__(self: _MT, instance: Type[Model], owner: Any) -> Tagged[_MT, "class"]: ...

class NumberAttribute(...):
    @overload
    def __get__(self, instance: Model, owner: Any) -> float: ...
    @overload
    def __get__(self, instance: Type[Model], owner: Any) -> NumberAttribute: ...
    @overload
    def __get__(self, instance: Tagged[MapAttribute, "instance"], owner: Any) -> float: ...
    @overload
    def __get__(self, instance: Tagged[MapAttribute, "class"], owner: Any) -> float: ...
```

This is, however, just one approach, and I'm not sure how viable or reasonable it is. I'd appreciate any other advice and suggestions.

**Comment by gvanrossum** [comment]
Perhaps NewType will work?

**Comment by ikonst** [comment]
NewType is similar in spirit, but I'd need the new type definition to be dynamic, i.e. in the typeshed:
```
class MapAttribute(...):
  def __get__(self: _MT, instance: Type[Model], owner: Any) -> NewType[MT.__name__ + '-instance', MT]: ...
```

**Comment by ilevkivskyi** [comment]
I don't think it is currently possible to express this. There are two possible workarounds:
* write fake stub for `MapAttribute` that returns `Type[_MT]` for second overload (this will probably work in 95% of cases).
* write a mypy plugin (this will require two dummy classes `_Class` and `_Instance`, a plugin can make every subclass of `MapAttribute` generic, and then add `__get__` definition that returns an equivalent of `_MT[_Class]` or `_MT[_Instance]`)

**Comment by ikonst** [comment]
I'll try those suggestions.

**Comment by ikonst** [comment]
@ilevkivskyi To resurrect this old thread, I'm still trying to figure out a good approach for my first goal with pynamodb-mypy, which is to support nullable and non-nullable attributes.

It looks like:
```py
class MyModel(Model):
  my_attr1 = UnicodeAttribute()
  my_attr2 = UnicodeAttribute(null=True)

MyModel().my_attr1  # should be builtins.str
MyModel().my_attr1  # should be typing.Optional[builtins.str]
```

My initial approach was to add a "wrapper" class to the type stub:
```py
_T = TypeVar('_T')
_AT = TypeVar('_AT', bound='Attribute')

class _NullableAttribute(Generic[_AT, _T], _AT):
    @overload
    def __get__(self, instance: Model, owner: Any) -> Optional[_T]: ...
    @overload
    def __get__(self: _NT, instance: None, owner: Any) -> _NT: ...
```
This approach doesn't work since you cannot have a "typevar" as a base (even in a type stub).

I could remove the inheritance, keeping it as:
```
class _NullableAttribute(Generic[_AT, _T]):
   ...
```
but I'd like a `_NullableAttribute[UnicodeAttribute, str]` to have all the methods of `UnicodeAttribute` (i.e. to derive from it), but an `Instance` doesn't have its own MRO, so there's no opportunity there.

I'm considering somehow cloning `TypeInfo`s entirely in runtime, e.g. `pynamodb.attributes.UnicodeAttribute` will get a paired `NullableUnicodeAttribute` but this seems heavy-handed.

Do you have any ideas or things for me to investigate?

**Comment by ilevkivskyi** [comment]
Defining "proxy types" is a long requested feature, see e.g. https://github.com/python/mypy/issues/5523. But it requires some effort to implement.

There is a similar problem in SQLAlchemy with `InstrumentedAttribute`, and it was "solved" with just using the underlying (proxied) type. Then the plugin returns either `Column[Optional[str]]` or `Column[str]`, for `Column(Unicode, nullable=False)` or `Column(Unicode)`.

In your case I would propose to just use:
```python
_T = TypeVar('_T')
_AT = TypeVar('_AT', bound='Attribute')

class _NullableAttribute(Generic[_AT, _T]):
    @overload
    def __get__(self, instance: Model, owner: Any) -> Optional[_T]: ...
    @overload
    def __get__(self, instance: None, owner: Any) -> _AT: ...
```
It will be technically a lie (this is not what happens at runtime), but this is a case where practicality beats purity. There are some ways to do the "copying" as you proposed in the plugin, but they are all heavy-handed.

**Comment by ikonst** [comment]
Ha, I realized the same this morning and implemented [this exact thing](https://github.com/pynamodb/PynamoDB/pull/579). As you say, practicality beats purity.

**Comment by ikonst** [comment]
Btw, thanks again for all your help!

After I'm done with this, I'd try to implement proper signatures for models' `__init__` (that accept typed and named attributes). This seems to have a clear precedent in attrs etc. so I hope it'll be easy.

**Comment by hauntsaninja** [comment]
Any future discussions would be better at https://github.com/python/typing
