### ISSUE TITLE
Trying to generate .pyi from .pyd raises UnicodeDecodeError

### ISSUE THREAD

**Issue by AlexArcPy** [python/mypy#5283]
* Windows 10, Python 3.5.4
* Bug
* I run `stubgen Dummy` in the command line where `Dummy` is the compiled extension module `Dummy.pyd`
* I get the `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte` error
* I expect to have a `.pyi` file produced
* mypy 0.610  
* The full traceback is below:

> 
> Traceback (most recent call last):
>   File "c:\users\user\appdata\local\continuum\anaconda2\envs\gdbeepy35\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\user\appdata\local\continuum\anaconda2\envs\gdbeepy35\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\user\AppData\Local\Continuum\Anaconda2\envs\GDBeePy35\Scripts\stubgen.exe\__main__.py", line 9, in <module>
>   File "c:\users\user\appdata\local\continuum\anaconda2\envs\gdbeepy35\lib\site-packages\mypy\stubgen.py", line 903, in main
>     raise e
>   File "c:\users\user\appdata\local\continuum\anaconda2\envs\gdbeepy35\lib\site-packages\mypy\stubgen.py", line 900, in main
>     include_private=options.include_private)
>   File "c:\users\user\appdata\local\continuum\anaconda2\envs\gdbeepy35\lib\site-packages\mypy\stubgen.py", line 132, in generate_stub_for_module
>     pyversion=pyversion, include_private=include_private)
>   File "c:\users\user\appdata\local\continuum\anaconda2\envs\gdbeepy35\lib\site-packages\mypy\stubgen.py", line 211, in generate_stub
>     source = mypy.util.decode_python_encoding(data, pyversion)
>   File "c:\users\user\appdata\local\continuum\anaconda2\envs\gdbeepy35\lib\site-packages\mypy\util.py", line 86, in decode_python_encoding
>     source_text = source.decode(encoding)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

**Comment by gvanrossum** [comment]
You're right, this is a bug in stubgen. You should be able to fix it by modifying this function
```py
def is_c_module(module: ModuleType) -> bool:
    return '__file__' not in module.__dict__ or module.__dict__['__file__'].endswith('.so')
```
in mypy/stubutil.py -- clearly it should also allow files ending in `pyd`. If you get it to work please submit a PR!

**Comment by AlexArcPy** [comment]
Thanks, Guido, got it working and submitted a PR https://github.com/python/mypy/pull/5284

**Comment by AraHaan** [comment]
I feel like at this point might also include dylib as well so macos users are not left out.
