### ISSUE TITLE
Program-flow information doesn't propagate to finally-block of a try-block

### ISSUE THREAD

**Issue by z33ky** [python/mypy#5286]
Example:

```
from typing import Optional

def get() -> Optional[int]: ...
def put(x: int) -> None: ...

try:
    x = get()
    assert x is not None
except:
    x = 0
finally:
    put(x)
```

* What is the actual behavior/output?

`try-opt.py:12: error: Argument 1 to "put" has incompatible type "Optional[int]"; expected "int"`

* What is the behavior/output you expect?

No error.

* What are the versions of mypy and Python you are using?

I tested both mypy 0.610 and mypy 0.620+dev-f7f3887f2d3ade7d46df30c1d2448b282e46b3dd with Python 3.6.5; behavior is identical.

**Comment by gvanrossum** [comment]
I'm not sure it is reasonable to expect this. If you change the code in the `except` code even slightly the code might no longer guarantee that `x` is never None.

**Comment by z33ky** [comment]
Couldn't the same argument be made for an if-else-block?

The control-flow doesn't look much different to
```
if foo:
    x = get()
    assert x is not None
else:
    x = 0
put(x)
```

**Comment by gvanrossum** [comment]
The difference is that there's a conditional 'goto' from *every* line, expression and subexpression in the `try` block to the `except` block.

**Comment by z33ky** [comment]
Well, this issue is for the `finally`-block, so to "goto"s to `except` wouldn't effect the outcome (wrt typing), at least in this simple case.
It'd be more difficult if the `except`-block has conditional behavior that depends how much the `try`-block was executed. I'm guessing you're worried that people would expect these more complex cases to work if this simpler case also works?

**Comment by gvanrossum** [comment]
Yeah, it's exceedingly difficult to decide whether you have a "simple" case at hand or not. I don't see a future for this feature request.
