### ISSUE TITLE
Nested Iterable

### ISSUE THREAD

**Issue by borsden** [python/mypy#5304]
Hi, guys. What's happening in this code?
```
from typing import Iterable, Dict, List, Sequence

# error: Incompatible types in assignment (expression has type "Tuple[List[Tuple[str, str]]]", variable has type "Iterable[List[Iterable[str]]]")
fields1: Sequence[List[Sequence[str]]] = ([('one', 'two')],)

# error: Incompatible types in assignment (expression has type "Tuple[Dict[str, Tuple[str, str]]]", variable has type "Iterable[Dict[str, Iterable[str]]]")
fields2: Sequence[Dict[str, Sequence[str]]] = ({'fields': ('one', 'two')},)

# It work normal
fields3: Sequence[Sequence[str]] = (('one', 'two'),)

# It also work normal
fields4: Dict[str, Sequence[str]] = {'fields': ('one', 'two')}

```
Same errors when i use Iterable instead of Sequence.
mypy==0.610

**Comment by ilevkivskyi** [comment]
It looks like mypy tried too hard to infer a more precise type for the right hand side. I think this is a bug. A workaround is to use covariant containers all the way down in such deeply nested cases. For example:
```python
fields: Sequence[Sequence[Sequence[str]]] = ([('one', 'two')],)
```
works correctly. The second example should also work if you replace `Dict` with `Mapping`. If you need mutable containers, then just silence the error with `# type: ignore`.

**Comment by erictraut** [comment]
This bug appears to have been fixed at some point. Mypy no longer generates any errors for the original code sequence.
