### ISSUE TITLE
Type annotation on self is not enforced correctly for generic classes

### ISSUE THREAD

**Issue by pnachum** [python/mypy#5305]
This code doesn't produce any type errors, but will crash at runtime when calling `len` with an int. 
```python
T = TypeVar('T')

class Box(Generic[T]):
    
    def __init__(self, val: T) -> None:
        self.val = val
		
    def foo(self: 'Box[str]') -> 'int':
        return len(self.val)

Box(1).foo()
```

Calling the `foo` method like this does result in a type error
```python
Box.foo(Box(1))
```

**Comment by ilevkivskyi** [comment]
Hm, interesting. I think annotations on `self` apart from self-type-like (capturing type variable) should be prohibited.

**Comment by pnachum** [comment]
I guess that would make this scenario impossible to express until https://github.com/python/mypy/issues/2354 is resolved?

**Comment by elazarg** [comment]
@ilevkivskyi I think it should be allowed as long as the overloads are exhaustive.
