### ISSUE TITLE
Rethink how we package typeshed

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#5307]
Currently, we have a rather complicated method of finding data files. The current method we use to distribute typeshed is [ripe](https://github.com/python/mypy/issues/5300) [for](https://github.com/python/mypy/issues/5121) [issues](https://github.com/python/mypy/issues/5022) [with](https://github.com/python/mypy/issues/4852) [finding](https://github.com/python/mypy/issues/3988) [the](https://github.com/python/mypy/issues/3761) [files](https://github.com/python/mypy/issues/3211).

I think we should stop playing whack-a-mole with issues and ship typeshed differently. Here are two ideas:

1. Ship typeshed as a subpackage of mypy, while still keeping it a module. I originally proposed this in https://github.com/python/mypy/issues/4143 but was hung up on the symlinks in typeshed (which no longer exist). This would involve:
    - moving the submodule into the mypy package.
    - updating setup.py to use package_data
    - adding these files to MANIFEST.in to be picked up in sdists
2. Release typeshed as its own package and pin to a particular version. This was attempted in https://github.com/python/typeshed/pull/2025 but it was abandoned.

I have no particular preference for one over the other, but I think both are better than the current method.

**Comment by ethanhs** [comment]
This came up again in #5319 so I am raising priority to high.

**Comment by ethanhs** [comment]
I think I will go ahead with option 1, unless anyone objects. It shouldn't be too hard to adopt option 2 later if typeshed becomes a package.

**Comment by JukkaL** [comment]
I also prefer option 1, at least for now (unless there are some major unforeseen issues with this approach, perhaps).

**Comment by ilevkivskyi** [comment]
OK, lets go with option 1. This way we can even be more flexible (no need to depend on typeshed releases).

**Comment by ethanhs** [comment]
Okay, I submitted #5517, which implements option 1. Hopefully this will mean fewer broken installs!

**Comment by TheKevJames** [comment]
I have no particular input on whether option 1 or 2 is nicer/simpler/better/whatever, but if we're picking anything other than option 2 its probably worth cleaning up [the PyPI typeshed package](https://pypi.org/project/typeshed/) to avoid cases where someone accidentally gets the wrong version of `typeshed` by mistakenly installing the `pypi` version.

Maybe release a `typeshed==1.0.0` with just a `README.md` saying "don't install this"?

**Comment by ethanhs** [comment]
@TheKevJames that isn't a problem. In my implementation in #5517 typeshed is never imported, so installing the typeshed package will not interfere.

**Comment by TheKevJames** [comment]
@ethanhs Ah, good point. Might be nice to clean up the released package anyway since its unused / potentially confusing, but it does indeed look like it won't interfere. :+1:
