### ISSUE TITLE
Finish remaining tasks for PEP 544

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#5322]
I don't have any energy/desire to work on this in foreseeable future. @JukkaL @ambv do you have time/desire to finish the remaining things?

**Comment by JukkaL** [comment]
I can move this forward (will likely have to wait until after my summer vacation though). I don't think that it's urgent to get this finished soon. Is module objects as instances of protocols the main thing missing? This looks like something that will take some effort to implement in mypy.

**Comment by ilevkivskyi** [comment]
> I can move this forward

Great, thanks!

> Is module objects as instances of protocols the main thing missing? 

Yes, this and also https://github.com/python/mypy/issues/3827 plus several smaller things, I will add a list now.

**Comment by ilevkivskyi** [comment]
Here is a more complete list of tasks:
- [ ] rename `@runtime` to `@runtime_checkable` in typeshed and in mypy itself
- [ ] Allow subclassing builtin protocols (like `Iterable`), currently this crashes at runtime because of a bug (also we probably need to say explicitly in the PEP that this is allowed)
- [ ] Add support for class objects and modules as protocol implementations and then merge the corresponding PR to the peps repo
- [ ] Move `Protocol` and `@runtime_checkable` to `typing`
- [ ] Get rid of the `ProtocolMeta` on Python 3.7 and 3.8 to avoid metaclass conflicts (edited)
- [ ] Resolve https://github.com/python/mypy/issues/3827 to match the current version of the PEP text

**Comment by gvanrossum** [comment]
Thanks for the task list. Does acceptance of the PEP need to wait for the implementation to be finished? That's not a requirement of the PEP process (there are actually separate states "Accepted" and "Final", where the latter means there is no more work to be done in the reference implementation). Which of the above tasks require updating the PEP text?

**Comment by ilevkivskyi** [comment]
> Does acceptance of the PEP need to wait for the implementation to be finished?

I reshuffled the tasks in a more logical order. I think the last two are optional w.r.t. to acceptance. But the first four are better to have before, there is a chance (although little I think) we might want to adjust some details.

**Comment by ilevkivskyi** [comment]
I think this can be closed now. The remaining tasks can be tracked in individual issues (they already exist).
