### ISSUE TITLE
[Feature request] Allow dynamic annotations

### ISSUE THREAD

**Issue by ksamuel** [python/mypy#5328]
If I do:

```
def bar():
    return str

def foo(a: bar()):
    return a
```

Mypy complains that it's an invalid type comment or annotation.

However, it's perfectly syntactically valid annotation. Also, I could want to be able to declare my type at runtime. 

E.G:

- if I already have a lib checking regularly if a licence server tells me the customer has the right to use this type a mypy daemon.

- if I want to define my own type that have syntaxic sugar to do `Foo | Bar` and get `Union[Foo, Bar]`.

- if I have a type hierarchy and want to automate typing by doing `Foo.children()` and get `Union[Child1, Child2, Child3, ...]`

- type depends of a side effect: a plugin is installed or not, a settings is set or not, and we support the plugin the be installed at runtime. All the code base use the callable to determine the next instantiation.

**Comment by JelleZijlstra** [comment]
We're unlikely to support this. Mypy is meant for static typing; deciding at runtime what your types are going to be goes against that principle, and also makes your types less useful.

In fact, Python is moving in the opposite direction of never evaluating annotations by default; see https://www.python.org/dev/peps/pep-0563/ .
