### ISSUE TITLE
Problems with using backported dataclasses in Python 3.6.5

### ISSUE THREAD

**Issue by pawelswiecki** [python/mypy#5342]
**Versions**

- `Python 3.6.5`

- `mypy==0.620+dev.bc0b551d8df2baadc44f0c3b0b801fcc12119658`

- `dataclasses==0.6` (https://github.com/ericvsmith/dataclasses)

**What's wrong**

```
$ cat f2.py 
from dataclasses import dataclass
print('works!')
$ python f2.py 
works!
$ mypy f2.py 
f2.py:1: error: Cannot find module named 'dataclasses'
f2.py:1: note: (Perhaps setting MYPYPATH or using the "--ignore-missing-imports" flag would help)
```
This is not the case when I use Python 3.7.0 (as reported here https://github.com/python/mypy/issues/5341).

So the natural way is to use MYPYPATH. The problem is `dataclasses` package is installed directly in `site-packages` (`virtual_env_path/lib/python3.6/site-packages/dataclasses.py`). Can I point mypy to include only this particular file? I really wouldn't like to reinstall the package in dedicated directory (which might be not straightforward, I'm using pipenv).

**Comment by JelleZijlstra** [comment]
The backport package can fix this by including stubs (presumably the same ones that are in typeshed) and marking itself as typed by using `py.typed`.

**Comment by pawelswiecki** [comment]
I see, I will notify author of the package. Thanks!
