### ISSUE TITLE
Flag to run a test only in Python 2?

### ISSUE THREAD

**Issue by sid-kap** [python/mypy#5344]
I'm thinking about tackling https://github.com/python/mypy/issues/4289, but in order do that we need a way to run certain test cases only in Python 2. Would you guys be open to adding this feature to the test suite?

If so, what would be the best way to do it? Some ideas:
* include `_python2_only` (or something similar) in the test case name
* include `_python2_only` in the filename of the `.test` file
* make a separate blacklist file somewhere in `test-data/`

**Comment by JelleZijlstra** [comment]
This already exists: you can add `flags: --py2` at the beginning of the test, or add `_python2` to the test case name.

**Comment by sid-kap** [comment]
Never mind, I see you have done something like this in https://github.com/python/mypy/blob/master/mypy/test/helpers.py and https://github.com/python/mypy/blob/master/mypy/test/testparse.py.

**Comment by sid-kap** [comment]
Thanks, sorry for the noise.
