### ISSUE TITLE
Error messages about stdlib modules not consistent

### ISSUE THREAD

**Issue by ysangkok** [python/mypy#5351]
Using mypy from master, reporting a usability bug.

Mypy seems to recognize standard library imports:

    /usr/local/lib/python3.6/dist-packages/dns/entropy.py:23: error: No library stub file for standard library module 'dummy_threading'

But when I got an error message about "encodings.idna", I didn't think it was a stdlib module since Mypy used a different wording:

    /usr/local/lib/python3.6/dist-packages/dns/name.py:23: error: Cannot find module named 'encodings.idna'

But encodings.idna is in Python! See https://github.com/python/cpython/blob/master/Lib/encodings/idna.py

Thank you for your patience, I hope the bug report is good, please let me know if you need further information.

**Comment by Michael0x2a** [comment]
Hmm, it looks like the `encodings` module is missing from the list of standard library modules located here -- probably an oversight?

https://github.com/python/mypy/blob/master/mypy/moduleinfo.py

In any case, do you want to try submitting a PR for this? I think the only change you'll need to make is adding the string `"encodings"` to the appropriate list.

(Or alternatively, if you're feeling up to it, you could try contributing stubs for the `encoding` module [to typeshed](https://github.com/python/typeshed). That's a much bigger task though.)
