### ISSUE TITLE
Incompatible signature with superclass with variadic arguments when overriding with definite arguments

### ISSUE THREAD

**Issue by scolby33** [python/mypy#5364]
I have two classes defined like so:
```python
# test.py
from typing import Any

class MyBase:
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        self.override_me(*args, **kwargs)

    def override_me(self, *args: Any, **kwargs: Any) -> None:
        pass


class MyHeir(MyBase):
    def override_me(self, message: str) -> None:
        print(message)
```

And the corresponding mypy output:
`test.py:13: error: Signature of "override_me" incompatible with supertype "MyBase"`

Now, I'm a bit new to this typing thing and don't have a background in type theory, but in my mind, these signatures are compatible, even though I can see why mypy would disagree.

Is there a better way to notate the types here? Is there a way to override this in mypy except for preventing all type checking on the "wrong" lines?

**Comment by ilevkivskyi** [comment]
> Now, I'm a bit new to this typing thing and don't have a background in type theory, but in my mind, these signatures are compatible

They are not, no need to know "type theory" to see this. A call `MyBase().override_me('a', 'b', 'c')` is valid, while `MyHeir.override_me('a', 'b', 'c')` is not.

> Is there a way to override this in mypy except for preventing all type checking on the "wrong" lines?

Use `# type: ignore` to silence errors.

In general, it is better to first read the docs before opening an issue, or ask on Gitter.

**Comment by scolby33** [comment]
I didn’t think about it in that direction! All I saw was that `MyBase(‘a’)` would be valid and so it couldn’t be wrong. Thanks for concisely showing me my mistake.

**Comment by oakkitten** [comment]
if i have many “heir” classes, is it possible to put the ignore bit on the base method?
