### ISSUE TITLE
Erorr when defining types for generic class from collections.abc

### ISSUE THREAD

**Issue by scolby33** [python/mypy#5365]
```python
>>> from collections.abc import Generator
>>> class MyGenerator(Generator[None, None, None]):
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'ABCMeta' object is not subscriptable
```

I think this is a bug in `collections.abc`, but is there an alternative method that will work with mypy? Should I open a bug with CPython about this?

**Comment by ilevkivskyi** [comment]
Use `typing.Generator`

**Comment by scolby33** [comment]
I originally tried to use from `collections.abc` so I could get the abstract class functionality as well. I see now that `typing.Generator` is an `_alias()` for that. Does this mean the ABC functionality is passed through? Is that documented somewhere and I missed it?

**Comment by ethanhs** [comment]
Many, dare I say most types that are generic versions of an abc say so in the docs: https://docs.python.org/3/library/typing.html

It seems that the classes such as Generator that have an explanation could point to the abcs as well.

**Comment by scolby33** [comment]
Yes, comparing the docs and the code now I see that they happen in the same way, but at first I assumed the ones that didn’t link to the ABC weren’t ABCs. Problems at both ends of the communication!

Thanks :)
