### ISSUE TITLE
Hierarchy of callable middleware classes confuses MyPy, results in invalid errors

### ISSUE THREAD

**Issue by beamerblvd** [python/mypy#5368]
* Are you reporting a bug, or opening a feature request?
  _I'm reporting what I believe is a bug._
* Please insert below the code you are checking with mypy, or a mock-up repro if the source is private. We would appreciate if you try to simplify your case to a minimal repro.
  _See below._
* What is the actual behavior/output?
  _See below._
* What is the behavior/output you expect?
  _See below._
* What are the versions of mypy and Python you are using?
  _MyPy 0.610, CPython 3.6.4_
* Do you see the same issue after installing mypy from Git master?
  _Tried it (`mypy -V` resulted in `mypy 0.630+dev-c52fabf4398d2ad263aa69cca33e0e39a572f554`) and got the exact same results outlined below._
* What are the mypy flags you are using? (For example --strict-optional)
  _None_
* If mypy crashed with a traceback, please paste the full traceback below.
  _Not applicable._

I have a set of callable middleware classes that all inherit from `AbstractMiddleware`:

```
class AbstractMiddleware(metaclass=abc.ABCMeta):
    def __init__(self, get_response: Callable[[HttpRequest], HttpResponseBase]) -> None:
        self.get_response = get_response

    @abc.abstractmethod
    def __call__(self, request: HttpRequest) -> HttpResponseBase:
        pass
```

In another abstract class called `AbstractRouter`, I have a class-level attribute that inheriting classes can override to define middleware classes:

```
    middleware = []  # type: List[Type[AbstractMiddleware]]
```

This is overridden in an inheriting class as follows, and MyPy finds no errors here:

```
    middleware = [
        SessionMiddleware,
        AuthenticationMiddleware,
    ]
```

Now I use all of this in the following code within a method in `AbstractRouter` (prefixed with line numbers for reference):

```
111    def process_request(self, request: HttpRequest, path: str) -> HttpResponseBase:
           ...

146        def get_response(inner_request: HttpRequest) -> HttpResponseBase:
147            return self._get_response(inner_request, path, request.api_response_headers)
148
149        for middleware_class in self.middleware:
150            get_response = middleware_class(get_response)
151
152        response = get_response(request)
```

This results in the following MyPy error and note (the only error in my project):

```
routers.py:150: error: Incompatible types in assignment (expression has type "AbstractMiddleware", variable has type "Callable[[Any], Any]")
routers.py:150: note: "AbstractMiddleware.__call__" has type "Callable[[Arg(Any, 'request')], Any]"
```

This, albeit not exactly right (From where did the `Any` types come!? It should not be `Any`.), makes sense, because `def get_response` is originally defined as a callable, so I tried changing the definition of the list of middleware to make it more flexible:

```
MiddlewareCallableType = Callable[[HttpRequest], HttpResponseBase]
...
    middleware = []  # type: List[Callable[[MiddlewareCallableType], MiddlewareCallableType]]
```

I still have one error, but it's different:

```
routers.py:150: error: Incompatible types in assignment (expression has type "Callable[[Any], Any]", variable has type "Callable[[Arg(Any, 'inner_request')], Any]")
```

Again with the `Any` types. But how are those incompatible? They're definitely not incompatible. If I change the code using all of this as follows, the error goes away, and my project has no errors:

```
111    def process_request(self, request: HttpRequest, path: str) -> HttpResponseBase:
           ...

146        def _get_response(inner_request: HttpRequest) -> HttpResponseBase:
147            return self._get_response(inner_request, path, request.api_response_headers)
148
149        get_response = _get_response  # type: MiddlewareCallableType
150        for middleware_class in self.middleware:
151            get_response = middleware_class(get_response)
152
153        response = get_response(request)
```

Notice `def get_response` is now `def _get_response` and it's aliased as `get_response` with a type comment. But this should not be necessary. `def get_reponse` is already compatible with the definition of `MiddlewareCallableType`.

**Comment by ilevkivskyi** [comment]
Thanks for reporting! I think this is not a bug, although the error is not very clear:
* The `Any` types are likely because you are importing some types from a library that has incomplete typeshed stubs.
* The `Callable` types incompatibility is because of the argument name. I think you can either use name prefix in argument names, like `__request` (by agreement mypy treats such arguments as "anonymous" i.e. positional-only), or use the extended callable types, see http://mypy.readthedocs.io/en/latest/additional_features.html#extended-callable-types to specify the argument names in your callable types. (The syntax is a bit ugly, but should be OK as a workaround).
