### ISSUE TITLE
Mypy forgets type information after a nested if-statement.

### ISSUE THREAD

**Issue by PetterS** [python/mypy#5378]
Mypy forgets type information after a nested if-statement. Small example:

    class Base:
        pass

    class B(Base):
        def __init__(self):
            self.args = []

    class C(Base):    
        def __init__(self):
            self.args = []

    def check(x: Base):
        if isinstance(x, (B, C)):

            print(x.args)  # No error here.

            if isinstance(x, B):
                print("B")
            elif isinstance(x, C):
                print("C")

            print(x.args)  # error: "Base" has no attribute "args"

Mypy 0.620 correctly infers that x has a member args for the first print statement, but after the nested if statement, it has forgotten about that and throws an error.

**Comment by gvanrossum** [comment]
Yeah, this does look like a bug. I somehow thought that the "binder" (the part of mypy that handles this) uses a stack, but here it appears it has popped too much off the stack.

Does this also occur with older mypy versions?

**Comment by PetterS** [comment]
When I encountered this, I had 0.610.

**Comment by PetterS** [comment]
I wonder how easy this would be to fix? I would be happy if I could fix it, but I haven't had the time to study the mypy code yet.

**Comment by PetterS** [comment]
This bug still happens in 1.7.1.

**Comment by hauntsaninja** [comment]
This passes after https://github.com/python/mypy/pull/18138 from @sterliakov :-)
