### ISSUE TITLE
typing.NamedTuple: type-checking error when "index" used as member

### ISSUE THREAD

**Issue by campkeith** [python/mypy#5380]
Find the test case below:

```
from typing import NamedTuple

class Foo(NamedTuple):
    alpha: int
    index: int
```

This results in the following error when run through type-checking with mypy:

```
% mypy --version
mypy 0.620
% mypy go.py
go.py:5: error: Incompatible types in assignment (expression has type "int", base class "tuple" defined the type as "Callable[[Tuple[int, ...], Any, int, int], int]")
```

When I instantiate this class in the python interpreter, I have no problem accessing the "index" member, so I suspect this is a bug in the type checker.

**Comment by ilevkivskyi** [comment]
This is not a bug but a legitimate error. This is a clear violation of https://en.wikipedia.org/wiki/Liskov_substitution_principle

**Comment by campkeith** [comment]
Oh, I see that `index` is a method of `tuple` (which is what the error message is trying to say). Looks like I missed this because of the indirection in NamedTuple; my bad.
