### ISSUE TITLE
Assertions are incorrectly applied to variables with same name in comprehensions

### ISSUE THREAD

**Issue by campkeith** [python/mypy#5400]
Here's an example:

```
from typing import Sequence

def process_elems(elems: Sequence[float]):
    for elem in elems:
        pass
    assert isinstance(elem, int)
    elems_odd = [elem & 1 for elem in elems]
```

It seems that the assertion is incorrectly applied to the `elem` variable in the following list comprehension (which shadows the local version of the variable):

```
% mypy --version
mypy 0.620
% mypy foo.py
%
```

I can get the correct error message (`Unsupported operand types for & ("float" and "int")`) by doing any of the following:

- Remove the asssertion
- Change the name of the list comprehension variable
- Put the assertion inside the scope of the `for` loop above (although theoretically there should be no error in that case...).

**Comment by erictraut** [comment]
I think this bug was fixed somewhere along the way. Mypy now correctly emits an error in this case.
