### ISSUE TITLE
Compatible container annotations flagged as error during assignment

### ISSUE THREAD

**Issue by jonapich** [python/mypy#5412]
```
from typing import List, Union

def returns_strings() -> List[str]:
    return ['1']

def returns_ints() -> List[int]:
    return [1]

i_can_take_both: List[Union[str, int]] = returns_strings()
i_can_take_both += returns_ints()
```

In the above code, mypy complains about `Incompatible types in assignment (expression has type "List[str]", variable has type "List[Union[str, int]]")`.

Is this a normal behavior? Shouldn't mypy consider `List[str]` a valid input for a `List[Union[str, int]]` container?

The error happens only when using a direct assignment; when going through `add`, mypy stops complaining:

```
i_can_take_both: List[Union[str, int]] = []
i_can_take_both += returns_strings()
i_can_take_both += returns_ints()
```

I would expect the `=` behavior to be similar to the `+=` behavior:

```
from datetime import datetime

def returns_datetime() -> List[datetime]:
    return [datetime.now()]

i_can_take_both += returns_datetime()
```

The above correctly outputs `Argument 1 to "__iadd__" of "list" has incompatible type`. I was hoping that mypy would follow a similar code path on `=`?

**Comment by ilevkivskyi** [comment]
This is intended, please read http://mypy.readthedocs.io/en/latest/common_issues.html#invariance-vs-covariance

**Comment by jonapich** [comment]
Oh :man_facepalming: Thanks. I did read that part several times before (including before filing the bug) and didn't realize it applied to this scenario because it seemed to deal with class inheritance and not a Union of valid types inside a container.

If you get this kind of question often, I suggest adding a dedicated section about 'Dict/List' vs 'Mapping/Sequence'.

**Comment by ilevkivskyi** [comment]
Maybe just adding one more example (with a union) to the docs would be enough. (Also feel free to make a docs PR if you think you can improve some wording/examples).
