### ISSUE TITLE
cache bug switching to disallow_incomplete_defs = true

### ISSUE THREAD

**Issue by asottile** [python/mypy#5413]
### version info

```console
$ mypy --version
mypy 0.620
```

### reproduction script

```bash
#!/usr/bin/env bash
set -euxo pipefail

mypy --version
rm -rf .mypy_cache

: should pass, no special setting
echo -e 'def f(x) -> str:\n    return ""\n' > t.py
echo -e '[mypy]\n' > mypy.ini
mypy t.py

: should fail, does not
echo -e '[mypy]\ndisallow_incomplete_defs = true' > mypy.ini
mypy t.py

: now it properly fails
rm -rf .mypy_cache
mypy t.py
```

### reproduction output

```
+ mypy --version
mypy 0.620
+ rm -rf .mypy_cache
+ : should pass, no special setting
+ echo -e 'def f(x) -> str:\n    return ""\n'
+ echo -e '[mypy]\n'
+ mypy t.py
+ : should fail, does not
+ echo -e '[mypy]\ndisallow_incomplete_defs = true'
+ mypy t.py
+ : now it properly fails
+ rm -rf .mypy_cache
+ mypy t.py
t.py:1: error: Function is missing a type annotation for one or more arguments
```

#### before

```ini
[mypy]
```

```python
def f(x) -> str:
    return ""
```

#### after

```ini
[mypy]
disallow_incomplete_defs = true
```

```python
def f(x) -> str:
    return ""
```

**Comment by gvanrossum** [comment]
Confirmed. Manual repro instructions: with the t.py file above, and starting with an empty .mypy_cache:

- run mypy t.py --disallow-untyped-defs (gives an error)
- run mypy t.py (no error)
- run mypy t.py --disallow-untyped-defs (no error!)

It seems that when the flag value changes the cache is not ignored. A possible fix would be to add "disallow_incomplete_defs" to the list of per-module options (PER_MODULE_OPTIONS) in mypy/options.py (thus also causing it to be added to OPTIONS_AFFECTING_CACHE), though I'm not sure why this option is currently not per-module.
