### ISSUE TITLE
Question about defining type of (multiple) sentinel objects

### ISSUE THREAD

**Issue by pawelswiecki** [python/mypy#5424]
- Python 3.6.5

- mypy==0.620.

Use case -- defining type of a `missing` sentinel object:

```python

from typing import Optional

missing = object()

def replace_with_missing(item: Optional[str]):
    if item in {None, '', 'null', 'NULL'}:
        return missing
    return item
```

**1.** How do I introduce the MissingType? Is this correct (and idiomatic)?

```python
from typing import cast, NewType, Union, Optional

MissingType = NewType('MissingType', object)
missing = cast(MissingType, object())

def replace_with_missing(item: Optional[str]) -> Union[str, MissingType]:
    if item is None:
        return missing
    if item in {'', 'null', 'NULL'}:
        return missing
    return item
```

No mypy error, so it seems correct. 

(I've put `if item is None: ...` in a distinct line to explicitly tell mypy that None is excluded. Otherwise, when I put it in the set I'm getting `Incompatible return value type (got "Optional[str]", expected "Union[str, MissingType]")`)

**2.** Is there a function/syntactic sugar to define a Union of multiple one-valued types?

I think it boils down to "explicitly listing all values". It's the first way of defining a type from [PEP-483](https://www.python.org/dev/peps/pep-0483/#background) -- The Theory of Type Hints:

> There are several ways to define a particular type:
> - By explicitly listing all values. E.g., True and False form the type bool.
> - By specifying functions which can be used with variables of a type [...]
> - By a simple class definition [...]
> - There are also more complex types [...]

So can I easily define a type by explicitly listing all values?

**Comment by pawelswiecki** [comment]
OK, let me answer my own question (StackOverflow style). Just had a quick illumination.

```python
from typing import Union, Optional                                             
                                                                               
class Missing:                                                                 
    pass                                                                       
                                                                               
missing = Missing()                                                            
                                                                               
def replace_with_missing(item: Optional[str]) -> Union[str, Missing]:          
    if item is None:                                                           
        return missing                                                         
    if item in {'', 'null', 'NULL'}:                                           
        return missing                                                         
    return item                      
```

To introduce a Union of multiple of those just use Union of all the classes.

Now:

- Is this the correct and idiomatic way?

- Should there be a way to quickly define a type by listing all values, after all?

**Comment by ilevkivskyi** [comment]
First, in your first post there is no need to use a cast, newtypes are typically used like this:
```python
MissingType = NewType('MissingType', object)
missing = MissingType(object())
```
Second,
> Is there a function/syntactic sugar to define a Union of multiple one-valued types?

Yes, it is called `enum.Enum`

Third,
> Is this the correct and idiomatic way?

Unfortunately, there is no 100% agreement about this in Python community (probably because enums are appeared to late in the language). You can use whatever pattern you like more, my personal preference is to use an enum.

Finally,
> Should there be a way to quickly define a type by explicitly listing all values, after all? (Like a type of `<'', None, 'NULL', 'Null'>`, which could be helpful in a different approach to cleaning data.)

Yes, this is called literal types. The support is planned in next few months.

(Please close the issue when you think your questions have been answered.)

**Comment by pawelswiecki** [comment]
Right, Enums. They never really clicked with me. It's probably a good time to change that.

All my questions were answered, thank you. Looking forward to literal types! (It is great Python typing is being so actively developed. It's very interesting to watch that, too.)
