### ISSUE TITLE
How to specify type signature of collections.abc.Mapping subclass?

### ISSUE THREAD

**Issue by bmerry** [python/mypy#5446]
* Are you reporting a bug, or opening a feature request?

Bug (I think - maybe I'm just holding it wrong)

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

My goal is to use the mixin functionality provided by `collections.abc.Mapping` to define a custom mapping type without implementing all the methods. My subclass is intended to be used with specific key and value types rather than being a generic class. Here's a minimal version of that:
```
#!/usr/bin/env python3

import collections.abc
import typing


class MyMapping(collections.abc.Mapping, typing.Mapping[str, str]):
    def __init__(self, data: typing.Mapping[str, str]) -> None:
        self._data = data

    def __getitem__(self, key: str) -> str:
        return self._data[key]

    def __iter__(self) -> typing.Iterator[str]:
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)


a = MyMapping({})
b = a.get('foo', 'bar')
print(b)
```

* What is the actual behavior/output?

```
mymapping.py:7: error: Duplicate base class "Mapping"
```

* What is the behavior/output you expect?

No error from mypy or at runtime and `b` is inferred as type `str`. If I remove `collections.abc.Mapping` from the base class list then it fails at runtime because `typing.Mapping` doesn't supply the `get` mixin. If I remove `typing.Mapping[str, str]` then there are no errors but `b` becomes `Any` because mypy doesn't know the type of the mapping.

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

Python 3.5.2, mypy 0.620 and master (fb657ea).

* What are the mypy flags you are using? (For example --strict-optional)

None.

**Comment by ilevkivskyi** [comment]
I think there is unfortunately nothing we can do here. You have two options:
1. (Recommended) switch to Python 3.7 where you can just use a single base `typing.Mapping[str, str]` (which is automatically translated to `collections.abc.Mapping` at runtime, while is also correctly understood by mypy during type checking).
2. Use
```python
if typing.TYPE_CHECKING:
    BaseMapping = typing.Mapping[str, str]
else:
    BaseMapping = collections.abc.Mapping
```
to have different base classes at type checking time, and at runtime.

**Comment by bmerry** [comment]
Thanks, a workaround is okay. I'll give it a try.
