### ISSUE TITLE
Doc on "Creating stubs for Python modules"

### ISSUE THREAD

**Issue by rpgoldman** [python/mypy#5451]
In this doc we see: "The unittest module stubs contain a good example of a stub for a class:" followed by the stub.

But, with all due respect, this is **not** a good example, because it doesn't show the reader how to declare types for the data properties in the class, only for methods.  Would it be possible to add an example that illustrates this?

An extra bonus would be if we could have an example of using a type variable to show how a generalized type (a type from which other types inherit) could use a "self type" `TypeVar` to indicate (a) that it has methods that will return an object of the same type and (b) that it has properties that point to an object of the same type.  (I think I know how to do the former, but I have no idea how to do the latter)

**Comment by hauntsaninja** [comment]
https://typing.readthedocs.io/en/latest/ is the new place for this kind of thing
