### ISSUE TITLE
Functions can't be passed as callable protocol

### ISSUE THREAD

**Issue by srittau** [python/mypy#5453]
This came up in python/typeshed#2379. Consider the following code:

```python
from typing import Protocol

class Caller(Protocol):
    def __call__(self) -> None: ...

def call() -> None:
    pass

def func(caller: Caller) -> None:
    pass

func(call)
```

Currently, mypy 0.620 rejects this:

```
foo.py:12: error: Argument 1 to "func" has incompatible type "Callable[[], None]"; expected "Caller"
```

I believe that mypy should actually allow this, because `call` is actually an object that fulfills the protocol. This would also open up the opportunity to create callback signatures of any complexity (for example, default and keyword-only arguments) without the need for additional features for `Callable`.

**Comment by ilevkivskyi** [comment]
This is a great idea! And it is easy to implement. TBH I never liked `NamedArg`, `KwArg`, etc. This will look much cleaner and flexible (because we can even express overloads as callbacks).

**Comment by srittau** [comment]
Credit for this idea goes to @podhmo. Interestingly, typescript does something similar. While it is possible to define callables just using `(foo: number) => string` or similar, you can define overloaded functions like this:

```typescript
interface MyCallback {
    () => number;
    (foo: number) => string;
}
```
