### ISSUE TITLE
The overload documentation leaves me confuzzled

### ISSUE THREAD

**Issue by funkyfuture** [python/mypy#5466]
reading the documentation of CPython and mypy leaves me with the impression that they are contradictory regarding the `overload` decorator to some degree. the [CPython docs](https://docs.python.org/3/library/typing.html#typing.overload) say 

> The @overload-decorated definitions are for the benefit of the type checker only, since they will be overwritten by the non-@overload-decorated definition, *while the latter is used at runtime but should be ignored by a type checker*.

and an according example is given.

while the [mypy docs](https://mypy.readthedocs.io/en/latest/more_types.html#function-overloading) are more ambiguous:

> It may or may not have type hints. If it does, mypy will check the body of the implementation against the type hints.

(i think not putting this in the example code would be favorable.) an example where the implementation is annotated with the unions of the variants is given.

now, with my actual code:

```python
@overload
def __getitem__(self, item: ErrorDefinition) -> Optional[ValidationError]: ...

@overload
def __getitem__(self, item: FieldName) -> Optional['ErrorTreeNode']: ...

def __getitem__(self, item):
    if isinstance(item, ErrorDefinition):
        ...
    else:
        ...
```

mypy will report `error: Function is missing a type annotation`. providing unions of the overloading annotations does solve this.

(sorry for the issue description, i'm not sure what it actually is.)

this is the config for the module:
```
disallow_subclassing_any = True
disallow_untyped_defs = True
```

**Comment by ilevkivskyi** [comment]
The mypy documentation is correct here, and the Python docs should be improved. I will close this issue for now, could you please open one on https://bugs.python.org?

**Comment by funkyfuture** [comment]
i can do this. but the wording is copied from PEP 484.

**Comment by Murtagy** [comment]
Might be relevant to someone https://stackoverflow.com/a/67225994/10187000
