### ISSUE TITLE
Mypy does not seem to understand custom properties after the descriptor refactor

### ISSUE THREAD

**Issue by Michael0x2a** [python/mypy#5471]
Consider the following program:

```python
class classproperty:
    def __init__(self, getter):
        self.getter = getter

    def __get__(self, instance, instance_type):
        return self.getter(instance_type)

class Foo:
    @classproperty
    def foo(cls) -> str:
        return "something"

reveal_type(Foo.foo)
print(Foo.foo)
```

If we run mypy on this program, we incorrectly reveal a type of `classproperty` -- but the actual runtime type is `str`.

After doing a git bisect, it looks like this regression was introduced by https://github.com/python/mypy/commit/f47bc236a089b12790334d01eb2f42469f1b530a, if that helps?

**Comment by ilevkivskyi** [comment]
Good catch!
