### ISSUE TITLE
Docstring for enum is not inferred as string.

### ISSUE THREAD

**Issue by qria** [python/mypy#5483]
Docstring for `enum.Enum` is inferred as the enum class itself, instead of `str`.

```
import enum

class A(enum.Enum):
    """Docstring"""

reveal_type(A.__doc__)   # <string>:7: error: Revealed type is '__main__.A'
```

Tested with mypy 6.2.0, python 3.6.1

**Comment by 97littleleaf11** [comment]
Currently the revealed type is `Union[builtins.str, None]`

**Comment by emmatyping** [comment]
[object defines `__doc__` as `str | None`](https://github.com/python/typeshed/blob/773b493b2b088fdeb3347c2ec9b1aab2cb4b4e33/stdlib/builtins.pyi#L103), so this is working as expected now.
