### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SCREAM2017** [python/mypy#5484]
Hello, Today's question is ,,

**How to install _**tools**_  Python  with all its **

with the click of a button

Because the connection system comes and is devoid of tools!

I mean _**tools**_ python such as:

> **[ python-devel , python-dev , python-pip , python-nmap , python-xml ]** **And very many of them**

<< 

If you want to install every one

It took a lot of time

And some Python tools do not write what you need them and then the error appears!

Cause: Because one of these  _**tools**_  Python is not installed, for example:

`**[ python-devel, python-dev, python-pip, python-nmap, python-xml ]**  **And very many of them**`

**Comment by ilevkivskyi** [comment]
This is of-topic.

**Comment by SCREAM2017** [comment]
@ilevkivskyi I did not understand you !

**Comment by SCREAM2017** [comment]
@ilevkivskyi I'm sorry I'm new, take me to the right place!

**Comment by ilevkivskyi** [comment]
You can try posting to python-list@python.org
