### ISSUE TITLE
Overloads with default arguments do not work properly

### ISSUE THREAD

**Issue by padix-key** [python/mypy#5486]
I have the follwoing stub file (`test.pyi`):

```
from typing import overload

@overload
def func(
    param: None = ...
) -> int: ...

@overload
def func(
    param: int = ...
) -> str: ...
```

When I run `mypy test.pyi`, *mypy* shows the following error:
`test.pyi:4: error: Overloaded function signatures 1 and 2 overlap with incompatible return types`
The parameter `param` clearly has two different types. Hence, the functions should not overlap to my understanding.

*mypy* 0.620 has been used.

**Comment by srittau** [comment]
The problem here is that both overloads match a call of `func()`. Removing the default from the second overload should fix your problem:

* `func()` matches (only) the first overload
* `func(None)` matches the first overload
* `func(42)` matches the second overload

**Comment by padix-key** [comment]
Unfortunately, I cannot simply remove the default value from the second overload, because in my actual problem there are default parameters before this parameter, like

```python
from typing import overload

@overload
def func(
    param1: str = "foo",
    param2: None = ...
) -> int: ...

@overload
def func(
    param1: str = "foo",
    param2: int = ...
) -> str: ...
```
Is there a way to fix this problem?

**Comment by ilevkivskyi** [comment]
This is not a bug, mypy shows an actual error. As @srittau mentioned, what is the type of `func()` (no args)? Is it `int` or `str`, because it matches both overloads. You should remove the default value (i.e. `...`) from at least one of the overloads. Also please read the docs https://mypy.readthedocs.io/en/latest/more_types.html#function-overloading

**Comment by ilevkivskyi** [comment]
@padix-key you can just add more overloads that match runtime semantics of your function.

**Comment by JelleZijlstra** [comment]
Specifically, in overload 2 you can mark `param2` as a required keyword-only argument by doing `*, param2: str`.

**Comment by henribru** [comment]
> Specifically, in overload 2 you can mark `param2` as a required keyword-only argument by doing `*, param2: str`.

@JelleZijlstra But then Mypy no longer allows you to call the function as `func("foo", 3)`, you have to do `func("foo", param2=3)` even though passing them as positional arguments are fine at runtime.

**Comment by henribru** [comment]
Okay, after reading https://mail.python.org/archives/list/typing-sig@python.org/thread/3P36ZCFAMOKFJMHFULTPGRNRSGTHTOLX/ I realize this workaround actually requires three overloads to avoid the problem I mentioned:

```py
from typing import overload

@overload
def func(
    param1: str = "foo",
    param2: None = ...
) -> int: ...

@overload
def func(
    param1: str = "foo",
    *,
    param2: int
) -> str: ...

@overload
def func(
    param1: str,
    param2: int
) -> str: ...
```

It feels a bit esoteric and unintuitive. Would a PR to better document the interaction between overloads and default values be welcome?

**Comment by bashtage** [comment]
> It feels a bit esoteric and unintuitive. Would a PR to better document the interaction between overloads and default values be welcome?

I think a tutorial/extended help page on complex `overload`ing would be a great addition.
