### ISSUE TITLE
Call to untyped function that's an exception with types defined in typeshed repo.

### ISSUE THREAD

**Issue by kornicameister** [python/mypy#5502]
Hello,

this is my first issue here, after a lot of googling I couldn't find any useful information, so that's my last resort to try and understand what is it that I am doing wrong. 

Ok, let's hit it.

I'm trying to use `werkzeug`, in particular, its exceptions in my application. However `mypy` is not quite happy with it as I am. That's quite surprising because there are typings in typeshed for `werkzeug`. That's also the reason why reporting this bug here.

Some useful details:

`mypy --version`: `mypy 0.630+dev-402d734c4b8ceffdc04478eb49fc196dd2a3a785`
`mypy.ini`:

```
[mypy]
python_version = 3.7

# error control
show_column_numbers = True
show_error_context = True

# import handling
# must be disabled because not every 3rd part library
# contains types
follow_imports = normal
ignore_missing_imports = True

# no imports, no cache
cache_dir = /dev/null

# because we ignore imports
disallow_untyped_calls = True
warn_return_any = False

# force types
disallow_untyped_defs=True
check_untyped_defs=True

# treat Optional per PEP 484
strict_optional = True

# ensure all execution paths are returning
warn_no_return = True

# lint-style cleanliness for typing needs to be enabled
warn_redundant_casts=True
warn_unused_ignores=True
warn_unused_configs=True
warn_incomplete_stub=True
```

piece of code that passes only after adding `type: ignore`, which I would really like to avoid.

```
from werkzeug import exceptions


def foo() -> None
  # a lot of code here
  raise exceptions.RequestTimeout(description=f'{base_error}. Request timeout') 
  # line above is reported as error
```

an error:

```
[mypy] Call to untyped function "RequestTimeout" in typed context [E]        
```

Now, as I wrote above, I am quite puzzled. By reading the docs I got the impression that `mypy` will be able to locate the stuff [here](https://github.com/python/typeshed/tree/master/third_party/2and3/werkzeug).

And yeah, by the limited options, I am reporting this as a bug. Couple hours of researching and that's the only conclusion I have.

Thank you in advance. 

PS. If that should be reported to the `typeshed` library, let me know.

**Comment by ilevkivskyi** [comment]
I believe this is a typeshed issue. `HTTPException.__init__` (and few other `__init__`s) in that file are _completely_ untyped. So mypy is right here: instantiating a class translates to a call to `__init__` which is indeed untyped (and you have `disallow_untyped_calls = True`).

I would prose that you move this issue to typeshed.

**Comment by kornicameister** [comment]
Thx @ilevkivskyi . I will create an issue there and link this one there.

**Comment by kornicameister** [comment]
@ilevkivskyi do you think it'd be possible to get a sync for typeshed? https://github.com/python/typeshed/pull/2405 has been just merged and I'd appreciate not having the `type: ignore` bits in the code.

I can submit the PR, if you prefer it that way.

**Comment by kornicameister** [comment]
Cool, thx 😄
