### ISSUE TITLE
Make mypy directory structure more tree-like?

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#5503]
Currently we have these files:
```
semanal.py
semanal_enum.py
semanal_namedtuple.py
semanal_newtype.py
semanal_pass1.py
semanal_pass3.py
semanal_shared.py
semanal_typeddict.py
```
I think they would look more naturally as
```
semanal/enum.py
semanal/namedtuple.py
semanal/newtype.py
semanal/pass1.py
semanal/pass2.py
semanal/pass3.py
semanal/shared.py
semanal/typeddict.py
```
Another ideas for refactoring may be moving all visitors/traversers to a separate sub-package. Also, we can have a `typeops` sub-package to hold the following things dealing with types only:
```
typeops/applytype.py
typeops/erasetype.py
typeops/expandtype.py
typeops/join.py
typeops/maptype.py
typeops/meet.py
typeops/sametypes.py
typeops/subtypes.py
```
I think you get the idea. We can do this to also some other modules to better reflect "big parts" of mypy machinery:
* fundamentals: nodes and types
* visitors for the above
* parsing
* semantic analysis
* type checking
* type system
* type inference (kind of "independent" from the above)
* server
* plugins
* top-level build & dispatch
* top-level helpers

This is of course an extremely large refactoring. So it requires discussions and quite time to avoid invalidating all PRs. Therefore marking this as low-priority.

**Comment by elazarg** [comment]
related: #1129

**Comment by ilevkivskyi** [comment]
@elazarg It seems to me #1129 is safest among al these (would probably cause less merge conflicts), so I would start with it.

**Comment by JukkaL** [comment]
I actually don't think that is a particularly large task -- it mostly just involves moving files around and fixing imports. This is tedious without refactoring tools but can be done pretty quickly in small increments.

**Comment by gvanrossum** [comment]
Large or small task, I personally prefer the current (flat) hierarchy. There's a Zen of Python line about it, and I don't like files hiding out of view when e.g. I open the mypy package directory on GitHub. I'd even like to move things out of server/ into its parent. (And yes, move test/ out of mypy/, per #1129.)

**Comment by JukkaL** [comment]
I don't have a strong opinion either way, but I'm reasonable happy with the current hierarchy. Moving lots of files around would be a distraction, though. And it will still take a non-trivial amount of work even if it's not a huge project.

**Comment by ilevkivskyi** [comment]
@gvanrossum 
> There's a Zen of Python line about it

Isn't this pushing it a bit to extreme in the situation where we have files named:
```
semanal_enum.py
semanal_namedtuple.py
semanal_newtype.py
semanal_pass1.py
semanal_pass3.py
semanal_shared.py
semanal_typeddict.py
```
Especially in view of upcoming big refactoring of the semantic analyzer, when we will likely keep both new and existing one for some time.

**Comment by gvanrossum** [comment]
I agree those names are not optimal. But replacing the `_` with `/` doesn't necessarily make them better -- I don't love a future where we write `from semanal import enum, namedtuple, newtype, pass1, pass3` and then write `enum.foo()`, `namedtuple.bar()` etc.

**Comment by ilevkivskyi** [comment]
> I don't love a future where we write `from semanal import enum, namedtuple, newtype, pass1, pass3` and then write `enum.foo()`, `namedtuple.bar()` etc.

Why would we do this? I expect that
```python
from mypy.semanal_namedtuple import NamedTupleAnalyzer, NAMEDTUPLE_PROHIBITED_NAMES
from mypy.semanal_typeddict import TypedDictAnalyzer
from mypy.semanal_enum import EnumCallAnalyzer
from mypy.semanal_newtype import NewTypeAnalyzer
```
will be simply translated to
```python
from mypy.semanal.namedtuple import NamedTupleAnalyzer, NAMEDTUPLE_PROHIBITED_NAMES
from mypy.semanal.typeddict import TypedDictAnalyzer
from mypy.semanal.enum import EnumCallAnalyzer
from mypy.semanal.newtype import NewTypeAnalyzer
```
We can just follow the current style guide to only import modules instead of classes/functions only when really needed (e.g. there is an import cycle).

**Comment by gvanrossum** [comment]
So then in the source code it makes no difference. When browsing the filesystem I would still prefer the flat hierarchy. I'll leave it up to Jukka though.

**Comment by JukkaL** [comment]
Let's keep the hierarchy flat.
