### ISSUE TITLE
Conditional expression in "with" statement inferred as 'object', lacking __enter__ and __exit__

### ISSUE THREAD

**Issue by chkno** [python/mypy#5512]
from tempfile import TemporaryDirectory, TemporaryFile
    import sys
    
    use_file = 'directory' not in sys.argv
    
    with (TemporaryFile() if use_file else TemporaryDirectory()) as thing:
        print(thing)

Mypy infers the type of the conditional expression as `object` rather than `Union[IO,TemporaryDirectory]`

    $ mypy multi_with.py

    multi_with.py:6: error: "object" has no attribute "__enter__"
    multi_with.py:6: error: "object" has no attribute "__exit__"

Explicitly typing the result of the conditional expression makes the error messages go away:

    named_intermediate: Union[IO, TemporaryDirectory] = (TemporaryFile() if use_file else TemporaryDirectory())

    with named_intermediate as thing:
        print(thing)

I observe this in both mypy versions I tried: 0.600 and 0.620

These past issues and pull requests look relevant:
https://github.com/python/mypy/issues/3487 Type of conditional expression is join instead of union
https://github.com/python/mypy/pull/5041 Fix type of conditional statement to Union and not Join.
https://github.com/python/mypy/pull/5095 Don't always infer unions for conditional expressions

**Comment by ilevkivskyi** [comment]
Yes, one option is to infer a union for conditional expression. Another option however is to still use join, but fix https://github.com/python/mypy/issues/3830 (at leat for the situation where we have a protocol context, like `ContextManager` in this case, which should be pretty straightforward)

**Comment by indigoviolet** [comment]
This bug still seems to be open in mypy 0.812: https://mypy-play.net/?mypy=latest&python=3.9&gist=35daf188cbaa119b95c77522250a6081

I don't quite understand why 
- typing the expression as `ContextManager[None]` doesn't suffice
- why assigning in an `if` block instead of the `if else` expression is different

Anyway,  @ilevkivskyi's https://github.com/python/mypy/issues/5512#issuecomment-415391131 doesn't seem to be relevant any longer.

**Comment by MattiasMartens** [comment]
Still open as of 0.942.

For reference of contemporary Googlers, the specific error message has changed:

```
error: "Iterator[None]" has no attribute "__enter__"; maybe "__iter__"?
```

**Comment by ilevkivskyi** [comment]
The original example now works on master.

**Comment by ar4hc** [comment]
Variation that still fails, with mypy 1.19.1:
```
with TemporaryDirectory() if is_foo else nullcontext() as temp_dir:
```

has to be
```
named_intermediate: nullcontext | TemporaryDirectory = TemporaryDirectory() if is_foo else nullcontext()
    with named_intermediate as temp_dir:
```

**Comment by ilevkivskyi** [comment]
@ar4hc I can't reproduce this with mypy 1.19.1. I just tried
```python
from tempfile import TemporaryDirectory, TemporaryFile
from contextlib import nullcontext
import sys

use_file = 'directory' not in sys.argv

with TemporaryDirectory() if use_file else nullcontext() as temp_dir:
    reveal_type(temp_dir)
```
and I am getting
```
tstfoo.py:8: note: Revealed type is "builtins.str | None"
Success: no issues found in 1 source file
```
which is what I would expect.
