### ISSUE TITLE
mypy doesn't find the `_tests` attribute of unittest.TestSuite

### ISSUE THREAD

**Issue by lbenezriravin** [python/mypy#5516]
I don't believe this is an issue with the signature. Please let me know if this better belongs in typeshed.

* Are you reporting a bug, or opening a feature request?
It's a bug
* Minimal repro:
```
import unittest

foo = unittest.TestSuite()
foo._tests
```
* What is the actual behavior/output?
`"TestSuite has no attribute "_tests"`
* What is the behavior/output you expect?
That attribute most certainly exists: https://github.com/python/cpython/blob/master/Lib/unittest/suite.py#L22
* What are the versions of mypy and Python you are using?
 ```
$ pipenv run mypy --version
mypy 0.620
$ pipenv run python --version
Python 3.7.0
```
  Do you see the same issue after installing mypy from Git master?
yes
* What are the mypy flags you are using? (For example --strict-optional)
none

Thanks for your work here!

**Comment by ilevkivskyi** [comment]
It is a typeshed issue (but I am not sure if they will add the attribute either). The policy is to allow access to private (i.e. underscore prefixed) attributes only if they are explicitly documented.

Feel free to open a typeshed issue if you believe this attribute should be added.
