### ISSUE TITLE
Possible bug: Value of type variable "_Number" of "median" cannot be "timedelta"

### ISSUE THREAD

**Issue by pawelswiecki** [python/mypy#5521]
**versions**

Python 3.6.5

mypy 0.620

**the code:**

```python
from statistics import median
from datetime import datetime


delta = datetime.now() - datetime.now()

median([delta, delta])
```

**mypy behavior:**

```
$ mypy f.py 
f.py:7: error: Value of type variable "_Number" of "median" cannot be "timedelta"
```

**expected behavior:**

No error.

Let me know if it's a typeshed issue and I will resubmit it there.

**Comment by JelleZijlstra** [comment]
This is a typeshed issue.

I'm not entirely sure we should fix it though. `statistics.median` is documented to work with "numbers" and I don't think a timedelta is a number. The current implementation happens to support timedeltas, but a future version may use a different algorithm that could blow up on timedeltas.

**Comment by pawelswiecki** [comment]
I see, thanks.

**Comment by ilevkivskyi** [comment]
I think this can be closes here. I you want, you can create an issue at typeshed.
