### ISSUE TITLE
Assert not None not correctly identified for Optional

### ISSUE THREAD

**Issue by hros** [python/mypy#5528]
According to previous topics mypy should recognize that and Optional is not None following an assertion.
This does not work properly for containers of Optional, as demonstrated by the following code:
```python
from typing import Optional, List

def f1(a: Optional[int], b: int)->int:
    assert a is not None
    b = a
    return b

def f2(a: List[Optional[int]], i: int, b: int)->int:
    assert a[i] is not None
    b = a[i]
    return b

def f3(a: List[Optional[int]], i: int, b: int)->int:
    ai = a[i]
    assert ai is not None
    b = ai
    return b
```

in `f2` mypy gives an error about incompatibility of Optional[int] and int, whereas in `f1` it correctly infers that the Optional is not None. 
adding an assignment `ai=a[i]` in function `f3` "solves" the problem.
can't mypy infer that the index `i` is not being modified and understand the `assert a[i] is not None`?

**Comment by ilevkivskyi** [comment]
This is kind of a huge change. Mypy doesn't track any kind of "state" of variables apart from type. For example, it is totally fine when the index is a literal:
```python
x: List[Optional[int]]

assert x[0] is not None
reveal_type(x[0])  # Revealed type is 'builtins.int'
```

Our policy is to keep feature requests open, but not to give any false hope, this is very low priority.

**Comment by andredasilvapinto** [comment]
it also doesn't seem to understand this:
```
def f4(a: Optional[int], b: Optional[int]) -> int:
    assert a or b
    return a if a else b
```

**Comment by hauntsaninja** [comment]
None of these are going to be supported; I'm not aware of any other Python type checker that does
