### ISSUE TITLE
Move MRO calculation to a later stage

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#5536]
Currently we first calculate MROs in the second pass, and then recalculate them in the third pass. This however is error-prone and is nor correct, since MROs are incorrect in the second pass in case of import cycles. This can cause abstract status to be inferred incorrectly, maybe there are other problems.

Unfortunately, moving MRO calculation to the third pass is hard because it is currently used (implicitly via `a_typeinfo.get(a_name)`) for two important things during the second pass:
* `analyze_member_lvalue`, where we need to know whether a name is defined in a superclass to decide whether we need to create a new `Var` after an assignment to `self`.
* `lookup_qualified`, where we need to know MRO to resolve references (for example to nested classes).

Moreover, the above uses show that we have a vicious circle: we need to know MROs to resolve references, and we need references resolved to calculate MROs. A possible solution maybe to have something like "deferred nodes" in type checking.

**Comment by ilevkivskyi** [comment]
See https://github.com/python/mypy/issues/5527 as a recent example of bug caused by this.

**Comment by JukkaL** [comment]
This may be fixed by the new semantic analyzer. Can we close this?

**Comment by ilevkivskyi** [comment]
Yes, we can close this. If some remaining bugs will be found for new analyzer, then we can open new issues.
