### ISSUE TITLE
mypy can't reference a module if a class member has the same name

### ISSUE THREAD

**Issue by ttyridal** [python/mypy#5539]
If a module has the same name as a member function in a class, it's not possible to reference tings in the module as types.

```
# foo.py
class A: pass

#main.py
import foo

class B:
   def foo(self) -> None: pass
   def bar(self, a: foo.A) -> None: pass
```

The above example will fail:
```
~$ mypy main.py
main.py:5: error: Invalid type "main.B.foo"
```

replace with `import foo as foobar` and `foobar.A`, passes without errors, as expected

tested to fail with git-master, 0.610 and 0.620

**Comment by ilevkivskyi** [comment]
It will as well fail at runtime with:
```
AttributeError: 'function' object has no attribute 'A'
```
I just tried this. So mypy is right here, it just follows Python name resolution rules here.
