### ISSUE TITLE
attrs plugin error: "The erased type of self '...*' is not a supertype of its class" on class definition with a generic using a constrained type variable, but then seems to work fine after definition

### ISSUE THREAD

**Issue by glyph** [python/mypy#5542]
Consider the following example:

```python3
from typing import TypeVar, Generic
import attr

class V:
    pass

class W:
    pass

T = TypeVar("T", V, W)

@attr.s(auto_attribs=True)
class A(Generic[T]):
    v: T

reveal_type(A(W()))
```

My expectation here would be a revealed type of `A[W*]`, which I *do* get.

But I also get an error on the `@attr.s` definition:
```
The erased type of self 'V*' is not a supertype of its class 'A[T`1]'
The erased type of self 'W*' is not a supertype of its class 'A[T`1]'
```

if I remove the constraints on `T`, (i.e. `T = TypeVar("T")`) then the errors go away.

**Comment by gvanrossum** [comment]
Maybe the attrs plugin author (@euresti) can shed some insight?

**Comment by ilevkivskyi** [comment]
This may be related to https://github.com/python/mypy/issues/5263 (if not a duplicate).

**Comment by ilevkivskyi** [comment]
Just to clarify, both issues may be caused by bad interaction of patched `self`/`cls` with `checkmember.bind_self()`.

**Comment by euresti** [comment]
Actually. I can repro with dataclasses too.  

```
from typing import TypeVar, Generic
import attr
from dataclasses import dataclass

class V:
    pass

class W:
    pass

T = TypeVar("T", V, W)

@dataclass(order=True)
class A(Generic[T]):
    v: T

reveal_type(A(W()))
```

So it's related to the added `__cmp-ish__` methods

**Comment by euresti** [comment]
Would the solution just be to make the id `-1`?  It seems to me like -1 should never be used at this point because negative numbers are used for methods/functions and I'm at this point creating it right?  Or are the id's global in scope?

**Comment by ilevkivskyi** [comment]
After some thinking it seems to me just using `-1` should be fine since the methods are auto-generated anyway. Btw, I have found that `senamal_namedtuple` also uses `1` instead of `-1`. Could you please try replacing it by `-1` in both plugins and in named tuple code and play with it trying to break (try some nested classes within generic functions, maybe some scenarios with type inference)?
