### ISSUE TITLE
mypy attrs tests fail because attrs 18.2.0 was just released

### ISSUE THREAD

**Issue by euresti** [python/mypy#5553]
This morning I tried running the unit tests in a fresh venv with a clean master.  All the attrs test failed.
After much looking around I discovered that:
A) The mypy test-requirements.txt installs the `attrs` package (because it's used by some pytest module) 
B) Attrs 18.2.0 "now ships its own PEP 484 type hints. Together with mypy’s attrs plugin, you’ve got all you need for writing statically typed code in both Python 2 and 3!"
C) The mypy tests load the real stubs instead of the ones instead of the ones in `lib-stub`.

This causes almost every attr test to fail with "Could not find builtin symbol 'dict'. (Are you running a test case? If so, make sure to include a fixture that defines this symbol.)"

I could go into every test and add the correct fixtures but should the tests be loading the real stubs?

cc: @hynek

**Comment by ilevkivskyi** [comment]
> should the tests be loading the real stubs?

No, this will make tests much slower. We need to find a way to use fixtures in this case (maybe there is a bug in test runner?).

**Comment by ilevkivskyi** [comment]
This is actually high priority (assuming your diagnosis is right).

**Comment by euresti** [comment]
The quick workaround is:
```
diff --git a/test-requirements.txt b/test-requirements.txt
index ba3e1a49..3d946ac4 100644
--- a/test-requirements.txt
+++ b/test-requirements.txt
@@ -1,4 +1,4 @@
-attrs>=18.0
+attrs==18.1.0
 flake8
 flake8-bugbear; python_version >= '3.5'
 flake8-pyi; python_version >= '3.6'
```

**Comment by ilevkivskyi** [comment]
Thanks! I am working on a more permanent solution now. I think we can just skip installed stuff if `options.use_builtins_fixtures` is `True`. If it will not work, I will just pin the version as you suggest.

**Comment by ilevkivskyi** [comment]
Here is what I propose https://github.com/python/mypy/pull/5554
