### ISSUE TITLE
When scanning multiple files, some error prevent the scan of the rest of the files.

### ISSUE THREAD

**Issue by leinardi** [python/mypy#5564]
Please provide more information to help us understand the issue:
* Are you reporting a bug, or opening a feature request? 
Not sure if is a bug or missing feature
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private:
 I currently don't have one, let me know if is necessary, I will create one.
* What is the actual behavior/output? 
The validation is interrupted, the rest of the files are ignored
* What is the behavior/output you expect?
 The rest of the files are validated independently from the result of the previous files
* What are the versions of mypy you are using? 
`mypy 0.620`
* What are the mypy flags you are using? 
`--show-column-numbers --follow-imports skip`

If I try to scan multiple files with `mypy` sometimes the scan just stops if one file has some specific error (e.g. invalid type comment or annotation).
This is a problem if you would like to collect the violations for all the files, running `mypy` just once.

I recently release a plugin for PyCharm that adds `mypy` code inspection and I just got a bug report due to this behavior: https://github.com/leinardi/mypy-pycharm/issues/3

**Comment by ilevkivskyi** [comment]
These are called blocking errors, or blockers. Many of them are practically impossible to fix (what should mypy do if it can't compute an MRO?) for other we have issues  (like invalid type comments/annotations can be non-blockers).

**Comment by leinardi** [comment]
> what should mypy do if it can't compute an MRO?

I can understand that the file with the blocking error cannot be scanned any further, but what about the other files? If the other files don't have any blocker, mypy could still validate them, don't you agree?

**Comment by ilevkivskyi** [comment]
> don't you agree?

I don't. If we don't know MROs for at least some classes we don't have a coherent nominal type system, it means that the results of type checking in other files can be arbitrary.

**Comment by leinardi** [comment]
I see, thanks for the clarification. Is there a way to check if an error is a blocker? Maybe some specific `exit_status` of the process? I would like to give the user a feedback that the scan interrupted prematurely (I tried to [search for "blocker](https://mypy.readthedocs.io/en/stable/search.html?q=blocker&check_keywords=yes&area=default)" inside the doc but without luck).

**Comment by ilevkivskyi** [comment]
Yes, this task is tracked here https://github.com/python/mypy/issues/3850, @anlorn started working on it but never submitted a PR IIRC, I assume he doesn't have time for this anymore.

**Comment by leinardi** [comment]
Thanks! I will try with the `--verbose` parameter :+1:.
