### ISSUE TITLE
Daemon should respect the rule that stubs are normal even with follow-imports=skip

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#5566]
Currently this test fails, presumably because the daemon applies `--follow-imports=skip` to stub files as well (while it shouldn't):
```
[case testFineFollowImportSkipInvalidatedOnAddedStub]
# flags: --follow-imports=skip --ignore-missing-imports
# cmd: mypy main.py
[file main.py]
import other
x: str = other.x
[file other.pyi.2]
x = 1
[stale main, other]
[rechecked main, other]
[out]
==
main:2: error: Incompatible types in assignment (expression has type "int", variable has type "str")
```
This was found in https://github.com/python/mypy/pull/5556

@msullivan do you have any ideas why this may happen?

**Comment by ilevkivskyi** [comment]
It looks like same happens with `--bazel` incremental build.

@gvanrossum could you give some hints about why this might happen?

**Comment by gvanrossum** [comment]
(The thing we saw internally with Bazel has a completely different cause, unrelated to this issue.)

**Comment by ilevkivskyi** [comment]
Yes, I just tried to look a bit more at this, and it looks like the root cause is simple actually: daemon _never_ supposed to work with `follow_imports=normal`, but apparently it should _always_ do this for stubs.

@JukkaL what do you think about this?

Also it looks like I had some misunderstanding about how fine-grained tests work, it seems to me now that by default at every test step all the modules currently present are passed to `Server.check()`. This means I have previously added many tests like `[case testFineAddedMissingStubs]` that don't test what I wanted.

**Comment by JukkaL** [comment]
@ilevkivskyi Hmm this is pretty unfortunate. On the other hand, this has been around for a long time before this got reported, so it doesn't seem that an urgent fix is needed. We can look at this in a few weeks when the core team will have a bug fixing spree.

**Comment by msullivan** [comment]
I've looked into this some and it is no easier to properly support `follow_imports=normal` for stubs alone than it is to support it in general. That makes this a sub-issue of the newly opened #5870.

**Comment by msullivan** [comment]
This might be easier to fix now with the new follow-imports=normal stuff?

**Comment by JukkaL** [comment]
This might be easier now, though I can't say how easy exactly without spending some time on this.

**Comment by JukkaL** [comment]
This works now.
