### ISSUE TITLE
Binder doesn't infer type restrictions for "parent" expressions

### ISSUE THREAD

**Issue by zxygentoo** [python/mypy#5579]
Hi guys, I've been using mypy for a while and quite like it. Today I run into a case that won't type check, the logic boiled-down to something like this:

```
from typing import List, Tuple, Union


Nested = Union[
    List[str],
    List[List[str]]
]

FlatWithCoordinates = Union[
    List[Tuple[str, int]],
    List[Tuple[str, int, int]],
]


def f(a: Nested) -> FlatWithCoordinates:

    if not isinstance(a[0], List):
        return [
            (s, x)
            for x, s in enumerate(a)
        ]
    else:
        return [
            (s, x, y)
            for x, ss in enumerate(a)
            for y, s in enumerate(ss)
        ]


# test

assert f(['a', 'b', 'c']) == [('a', 0), ('b', 1), ('c', 2)]
assert f([['a', 'b', 'c'], ['x', 'y', 'z']]) == [
    ('a', 0, 0),
    ('b', 0, 1),
    ('c', 0, 2),
    ('x', 1, 0),
    ('y', 1, 1),
    ('z', 1, 2)
]
```

type check fail with

$ demo.py:20: error: Cannot infer type argument 1 of "enumerate"
$ demo.py:25: error: Cannot infer type argument 1 of "enumerate"

tested on python 3.6.5 and mypy 0.620

Any idea how to type check this? Thanks!

**Comment by ilevkivskyi** [comment]
There are actually two problems with mypy here. One is that `isinstance(a[0], list)` currently only adds type constraints on `a[0]`, but doesn't add type constraints on `a` itself. If you add `reveal_type(a)` then you will see it is still a union in both branches. Solving this would require some special-casing in binder, but I think it makes sense (although low priority).

Another problem is that mypy doesn't have good type inference for unions, a simple example:
```python
a: Union[List[int], List[str]]

enumerate(a)  # Same error here, but it can be 'Union[enumerate[int], enumerate[str]]'
```
This I think is a more important problem but it is also much harder to solve.

As a workaround you can just use `cast(List[str], a)` for now.

**Comment by zxygentoo** [comment]
@ilevkivskyi thanks for the explanation~ I'm no type-geek, but I can get that consider the design of python and mypy, union type inference should be a hard problem.

**Comment by ilevkivskyi** [comment]
The union inference part is now fixed by union math. The original example still gives an error because mypy can't figure out the consequence of `isinstance(a[0], list)` for the type of `a` itself (not just `a[0]`).

This is however, low priority.

**Comment by zxygentoo** [comment]
Noted. Thanks for the follow up :+1:
