### ISSUE TITLE
Weird, but legal ** syntax not accepted

### ISSUE THREAD

**Issue by warsaw** [python/mypy#5580]
I saw this in real code, although I don't really understand the reason why this is done.  Still, even though it's a bit weird, it's legal and I think mypy should allow it:

```
class Foo:
    def __init__(self, a=1, b=2):
        self.a = a
        self.b = b


Foo(**{})
```

```
$ mypy foo.py
foo.py:7: error: Keywords must be strings
```

**Comment by gvanrossum** [comment]
Agreed -- the dict could be type-checked here with a context of `Mapping[str, Any]` and that would make the empty dict have the type `Dict[str, Any]` rather than `Dict[<nothing>, <nothing>]`.

Low priority though.
