### ISSUE TITLE
@sys.meta_path.append type error

### ISSUE THREAD

**Issue by warsaw** [python/mypy#5589]
I'm not sure if this is a bug in Python or in mypy, or there is no bug at all.  It seems a bit weird given the contents of `sys.meta_path` and my grep-fu must suck because I can't find where the signature is defined.  Here's the code:

```python
import sys


@sys.meta_path.append
class LostFinder:
    @staticmethod
    def find_spec(*args, **kws):
        return None
```

and the error:

```bash
$ mypy foo.py 
foo.py:4: error: Argument 1 to "append" of "list" has incompatible type "Type[LostFinder]"; expected "MetaPathFinder"
```

and the contents of `sys.meta_path` on a vanilla Python:

```bash
$ python3.7 -I -c "import sys; print(sys.meta_path)"
[<class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>]
```

**Comment by msullivan** [comment]
The type of `sys.meta_path` is defined in the typeshed stub: https://github.com/python/typeshed/blob/master/stdlib/3/sys.pyi#L42

The class is defined here: https://github.com/python/typeshed/blob/master/stdlib/3/importlib/abc.pyi#L55

Subclassing from it should fix the error.

I don't think there is any bug here?

**Comment by msullivan** [comment]
(Feel free to reopen if you disagree)

**Comment by jaraco** [comment]
Perhaps it's a bug in typeshed... and the spec should be more lenient, to allow for `MetaPathFinder` or `Type[MetaPathFinder]` or maybe any other class that duck types a MetaPathFinder (because even the stdlib `<class '_frozen_importlib.BuiltinImporter'>` is not an instance of MetaPathFinder.

**Comment by ilevkivskyi** [comment]
Yes it is a typeshed bug, not mypy bug. @msullivan's suggestion should fix it in typeshed.
