### ISSUE TITLE
getting errors trying to perform mathematical operations on Unions

### ISSUE THREAD

**Issue by remdragon** [python/mypy#5590]
* Are you reporting a bug, or opening a feature request?

BUG

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
from __future__ import division, print_function

MYPY = False
if MYPY:
	from typing import Union
	Number = Union[int,float]

a = 2 # type: Number
b = 1.0 # type: Number

print ( a + b ) # error: Unsupported operand types for + ("Union[int, float]" and "Union[int, float]")
print ( a - b ) # error: Unsupported operand types for - ("Union[int, float]" and "Union[int, float]")
c = 0
c += a # error: Incompatible types in assignment (expression has type "float", variable has type "int")
c -= b # error: Incompatible types in assignment (expression has type "float", variable has type "int")
print ( c )
```

* What is the actual behavior/output?

```
test.py:11: error: Unsupported operand types for + ("Union[int, float]" and "Union[int, float]")
test.py:12: error: Unsupported operand types for - ("Union[int, float]" and "Union[int, float]")
test.py:14: error: Incompatible types in assignment (expression has type "float", variable has type "int")
test.py:15: error: Incompatible types in assignment (expression has type "float", variable has type "int")
```

* What is the behavior/output you expect?

Code should not generate any mypy errors

* What are the versions of mypy and Python you are using?

mypy 0.620
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32

* Do you see the same issue after installing mypy from Git master?

I have not tried Git master.

* What are the mypy flags you are using? (For example --strict-optional)

```
mypy %1 --ignore-missing-imports --strict
mypy %1 --ignore-missing-imports --strict --py2
```

**Comment by ilevkivskyi** [comment]
> I have not tried Git master

It is already fixed. (Except for the last examples with `c` which are actual type errors.)
