### ISSUE TITLE
Unsupported operand types for &

### ISSUE THREAD

**Issue by twk** [python/mypy#5600]
Mypy fails with `error: Unsupported operand types for & ("KeysView[Wrapper]" and "List[Wrapper]")` when I try to do this:

```
class Wrapper:
    def __init__(self, val):
        # type: (int) -> None
        self.val = val

def demo():
    # type: () -> None
    a = {Wrapper(1): 1, Wrapper(2): 2}
    b = [Wrapper(1)]

    a.keys() & b
```

My code that uses this functionality works, so perhaps this is a bug in mypy?

**Comment by msullivan** [comment]
This seems like a bug in https://github.com/python/typeshed, the collection of types for the stdlib

**Comment by twk** [comment]
Thanks, I'll go file it there.
