### ISSUE TITLE
Tuple[int] not regarded as Sequence[int] when the key of a dictionary

### ISSUE THREAD

**Issue by gappleto97** [python/mypy#5601]
Platform: Windows 10 (64-bit)
Python: CPython 3.6.5
Mypy: 0.620

Offending code:

```python
from typing import Any, Dict, Sequence, Tuple


def test(ex: Dict[Sequence[int], Any]) -> None:
    pass


def test2(ex: Sequence[int]) -> None:
    pass


var: Dict[Tuple[int], Any] = {}
var2: Tuple[int] = (3, )
test(var)  # error
test2(var2)  # no error
```

In particular, the error reported is:

`error: Argument 1 to "test" has incompatible type "Dict[Tuple[int], Any]"; expected "Dict[Sequence[int], Any]"`

There is probably a more minimal example, but this is what I have found thus far.

**Comment by JelleZijlstra** [comment]
This looks like an invariance issue. See https://mypy.readthedocs.io/en/latest/common_issues.html#invariance-vs-covariance.

**Comment by msullivan** [comment]
Yeah, that is what it is. In many cases (though unfortunately not this one), we print out a more helpful error message pointing to this fact. If `test` only needs to read from the dictionary, consider having it take a `Mapping` instead.

**Comment by gappleto97** [comment]
That does not seem to fix it:

```python
from typing import Any, Dict, Mapping, Sequence, Tuple


def test(ex: Mapping[Sequence[int], Any]) -> None:
    pass


def test2(ex: Sequence[int]) -> None:
    pass


var: Dict[Tuple[int], Any] = {}
var2: Tuple[int] = (3, )
test(var)  # error
test2(var2)  # no error
```

Error message: `error: Argument 1 to "test" has incompatible type "Dict[Tuple[int], Any]"; expected "Mapping[Sequence[int], Any]"`

**Comment by JelleZijlstra** [comment]
The key argument to `Mapping` is still invariant; it's just for the value argument that switching to Mapping helps, because the value argument is covariant for mapping but invariant for dict.

**Comment by gappleto97** [comment]
Is there any way to denote that you are willing to take a mapping of anything that supports the Sequence API? The method inspiring this translates everything to a sorted tuple anyways, so it does not care about what type the keys are originally, so long as they support the Sequence API.

**Comment by JelleZijlstra** [comment]
I think you could define a custom covariant Protocol as the argument type for your function that declares the methods you need.

**Comment by gappleto97** [comment]
So this is still leaving the same unhelpful error message pointed out by @msullivan, and is still, at least to me, wildly unintuitive. Even ensuring that all types are immutable does not fix this, though the relevant documentation seems to indicate it's a problem with mutability. I would greatly appreciate it if you could clarify for me what is actually happening here.
