### ISSUE TITLE
Invalid syntax for "await" expression in f-string

### ISSUE THREAD

**Issue by tausackhn** [python/mypy#5602]
Checking the next code with `mypy --python-version 3.7 test.py` cause `error: invalid syntax`.
```python
#test.py
import asyncio

async def g():
    return 'a'

async def f():
    print(f'{await g()}')
```
`await` expressions are allowable syntax in f-strings since Python 3.7 (https://bugs.python.org/issue28942)

**Comment by ethanhs** [comment]
This is because we are currently using a modified version of the parser for Python 3.6 (typed_ast). You can follow https://github.com/python/typed_ast/issues/60 for more on accepting Python 3.7 syntax. Since this is a typed_ast feature request, I will close this.
