### ISSUE TITLE
How to ensure that MyPy also includes packages that are already typed?

### ISSUE THREAD

**Issue by takeda** [python/mypy#5610]
Apologies if this was already answered, but I spent few hours and couldn't find answer.

Basically I'm doing the following:

- installed mypy on python 3.7
- I created a Python 2.7 virtualenv
- entered directory of the application I'm about to check
- run `../venv/bin/pip install -e .`
- run `mypy --python-executable ../venv/bin/python --python-version 2.7 -p packageA`

In the output I still see many import errors, which is normal (I purposefully did not use `--ignore-missing-imports` to make sure things work correctly), but I also see `error: Cannot find module named packageB`. the thing is that `packageB` is a direct dependency and is installed in the virtualenv, `packageB` also has types to all objects that it defines.

How can I make sure that mypy will include `packageB` in the analysis? I tried using MYPYPATH and learned that you not supposed to include site-packages that way.

Am I doing something wrong or is this a bug? BTW: I tried 0.620 as well as latest version in the repo right now.

**Comment by JelleZijlstra** [comment]
You need to add `py.typed` in `packageB`. See PEP 561 and https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages.

**Comment by takeda** [comment]
That was it, thank you.
