### ISSUE TITLE
Support invoking mypy from setuptools (feature request)

### ISSUE THREAD

**Issue by eric-wieser** [python/mypy#5611]
It would be great if mypy (or some external tool, `mypy-setuptools` or something) could provide an easy way to run mypy against just the files in a distribution.

There was some work done on this in #994 (to close #992) by @rowillia, but it was reverted without comment in 964a17587231c6f09ba24f6dd19648586ea3d655 by @JukkaL.

Given the python-3.6+ dependence of mypy, and the fact it can check older python versions, I think it would make sense for this setuptools plugin to ultimately just invoke `subprocess.check_call(['mypy', ...])`, which would allow it to be used on python2 projects too. For this reason, it would make sense for it _not_ to live in the mypy repo, as it would need to be installable within python instances where mypy is not.

One difficulty here is how exactly to test only the files in a distribution. Some options are:
* Running against the source - this doesn't respect the `package_dir` argument in setuptools.
* Collecting `distribution.modules` and `distribution.packages` - this will end up checking the full contents of any namespace package partially provided by this distribution
* Inspecting an egg or wheel somehow, and letting mypy take one of these as an argument?

**Comment by msullivan** [comment]
I think this would need to be an external tool
