### ISSUE TITLE
Feature request: allow for class variables in the class syntax variant of NamedTuple

### ISSUE THREAD

**Issue by jhbuhrman** [python/mypy#5613]
Allow for adding class variables when using the "class syntax" variant of `NamedTuple` (as opposed to the "function call syntax").

The following example should clarify it:
```python
from typing import ClassVar, List, NamedTuple

class Employee(NamedTuple):
    """Represents an employee."""
    some_list_classvar: ClassVar[List] = []  # <- Doesn't work
    name: str
    id: int = 3
```

@ilevkivskyi suggested that I could open a feature request for this. Please check out the conversation on https://gitter.im/python/typing?at=5b9a26b1b9531f2dfa5d9782 for more details, including a suggestion on how to implement this.

**Comment by AlexWaygood** [comment]
Nowadays we prefer changes like this, which would affect the typing system as a whole rather than just mypy, to be discussed on the https://github.com/python/typing issue tracker (or the typing-sig mailing list). So I'm closing this for now — but thank you for the feature request!
