### ISSUE TITLE
Mypy should infer result of `x in y` as a `bool`

### ISSUE THREAD

**Issue by TV4Fun** [python/mypy#5656]
Python always casts the value of an `in` test to `bool`, so `a in b` will be a `bool` regardless of what the return type of `b.__contains__` is. Mypy does not internalize this idea though. So for example, the following code:
```python
class MyClass:
    def __contains__(self, x: object) -> int:
        return 42

    def my_func(self) -> bool:
        return 1 in self
```
Generates this error from Mypy:
```
test.py:6: error: Incompatible return value type (got "int", expected "bool")
```
Though actually, this should be fine, as even though `MyClass.__contains__` returns `42`, `1 in self` will evaluate to `True`. This is an artificial example, though I came across this error when using a container type that Mypy did not have the import file for, and so assumed a return value of `Any` for my `in` test. This generated a warning when run with `--strict`.

**Comment by gvanrossum** [comment]
Interesting. Confirmed this is the case. Note that `__contains__` is unique here -- overriding e.g. `__lt__` as returning `int` does not cast the return value to `bool`. (Probably because of "rich comparisons".)
