### ISSUE TITLE
Overload variant notes are sometimes printed multiple times

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#5661]
I don't have a simple repro for this, but I have seen this problem recently. For certain complex overloads, bad call results in the following being printed:
```
file.py:19: note: Possible overload variants:
file.py:19: note:     def [T] g(x: Dict[T, int]) -> Dict[T, int]
file.py:19: note:     def [T] g(x: List[T]) -> List[T]
file.py:19: note:     def [T] g(x: Dict[T, int]) -> Dict[T, int]
file.py:19: note:     def [T] g(x: List[T]) -> List[T]
```
The original function had only two overloads.

**Comment by gvanrossum** [comment]
What was the definition of `T`? Did it happen to be of the form `TypeVar('T', xxx, yyy)`?

**Comment by ilevkivskyi** [comment]
Oh, sorry, I lost track of this, I don't have a repro for this. I don't remember what was the variable, but I remember this happened for calling a generic overload with another generic overload, like `f(g(x))`.

**Comment by AlexWaygood** [comment]
I'm closing this issue, since it's nearly 4 years on and there's no reproducible example
