### ISSUE TITLE
Surprisingly swapped order of type variables with multiple inheritance of generic types

### ISSUE THREAD

**Issue by wkschwartz** [python/mypy#5668]
I'm using Python 3.7.0 and mypy 0.630. Input file `mypy-test.py`:

```python
from typing import TypeVar, Generic

T = TypeVar('T')
S = TypeVar('S')

class A(Generic[T]):
	def t(self, x: T) -> T:
		return x
class B(A[T], Generic[S, T]): pass
b: B[str, float]
reveal_type(b.t)

class C(A[T]): pass
class D(C[T], B[S, T]): pass
d: D[str, float]
reveal_type(d.t)
```

Output of `mypy mypy-test.py`:

```
mypy-test.py:11: error: Revealed type is 'def (x: builtins.float*) -> builtins.float*'
mypy-test.py:16: error: Revealed type is 'def (x: builtins.str*) -> builtins.str*'
```

This surprises me because I would expect `D` to have exactly the same type signature as its superclass `B`, binding `S` to `str` and `T` to `float`. However, despite the same type input, `B.t` expects and returns a `float` whereas `D.t` expects and returns a `str`.

This is not technically a bug because it's working as [documented](https://mypy.readthedocs.io/en/stable/generics.html#defining-sub-classes-of-generic-classes):

> - If Generic[...] is present, then the order of variables is always determined by their order in Generic[...].
> - If there are no Generic[...] in bases, then all type variables are collected in the lexicographic order (i.e. by first appearance).

Using those rules, I can work around this problem by making :

```diff
 class A(Generic[T]):
 	def t(self, x: T) -> T:
 		return x
-class B(A[T], Generic[S, T]): pass
-b: B[str, float]
+class B(A[T], Generic[T, S]): pass
+b: B[float, str]
 reveal_type(b.t)
 
 class C(A[T]): pass
-class D(C[T], B[S, T]): pass
-d: D[str, float]
+class D(C[T], B[T, S]): pass
+d: D[float, str]
 reveal_type(d.t)
```
produces
```
mypy-test.py:11: error: Revealed type is 'def (x: builtins.float*) -> builtins.float*'
mypy-test.py:16: error: Revealed type is 'def (x: builtins.float*) -> builtins.float*'
```
However, I think this work around requires that `B` knows in advance how `D` will subclass it later. (I'm not sure, but I think that, in particular, `B` would need to know that `D` will want to inherit from a subclass `C` of `A` _first, before_ inheriting from `B`.)

I ran into it because I was getting very strange type compatibility errors about overriding a method of `B` in `D` that were hard to track down until I read the above section of the documentation. In my case, I can probably work around this problem as I wrote above, but I'm not sure that would remain true if my `A` needed more type variables, or if I needed to subclass `D` later.

**Upshot**: I'm not sure if this is a bug report, question, or documentation request. Does this behavior surprise anyone else?

**Comment by gvanrossum** [comment]
As you state, this is all working as documented. If you want to control the order of type variables you should just add `Generic[S, T]` or `Generic[T, S]` to the base classes of `D`.

Perhaps it is helpful to know that the names of the type variables is irrelevant across classes? That is, if you consistently rename (or swap) all occurrences of `S` and `T` in a given class, the meaning is unchanged.

**Comment by ilevkivskyi** [comment]
Looking at the two lines:
```
class D(C[T], B[S, T]): pass
D[str, float]
```
I don't see how this is surprising, you just literally substitute variables one by one:
```
class <hm, what is D[str, float]> (C[str], B[float, str]): ...
```
how else can one substitute them?

If you want, you may add your example to the docs, otherwise I would just close this.

**Comment by wkschwartz** [comment]
Thanks, guys. Perhaps I was just being obtuse. I'll close the ticket.

Flag me down if someone files a similar ticket in the future. Maybe extra documentation would be appropriate at that point.
