### ISSUE TITLE
Handling "default" methods in class hierarchies

### ISSUE THREAD

**Issue by rpgoldman** [python/mypy#5669]
feature request

See the directory `test-data/default-methods/` in my branch: https://github.com/rpgoldman/mypy/tree/default-method-example

```
cd mypy/test-data/default-methods/code
mypy example.py
```

Complains that the `SubClass` method signature contradicts the one at `SuperClass` (which has a vacuous parameter list):

```
../stubs/example_classes.pyi:13: error: Signature of "example_method" incompatible with supertype "SuperClass"
```

Ideally, mypy should recognize that a method definition whose signature is:
```
(self, *args: Any, **kwargs: Any)
```
does not constrain any subclass's implementations of that method.

* What are the versions of mypy and Python you are using?
```
mypy 0.640+dev-b923c587a3eaa6cb55d9908be5344b2d9a574b33
```
Python 3.6

* What are the mypy flags you are using? (For example --strict-optional)

none

**Comment by rpgoldman** [comment]
P.S. in the PyMC3 code base I see these vacuously-parameterized methods used for delegation and for raising exceptions where a method is not implemented, but should be.  I think there is probably a better mechanism for the latter, but I'm not as sure about the former.

**Comment by ilevkivskyi** [comment]
As a random suggestion, we can maybe make it a strictness flag, like in https://github.com/python/mypy/pull/5670 instead of adding a special decorator or similar.

**Comment by hauntsaninja** [comment]
Modern mypy is more unsound in its handling of `*args: Any, **kwargs: Any`
