### ISSUE TITLE
Support for the multiprocessing module

### ISSUE THREAD

**Issue by orenbenkiki** [python/mypy#5676]
A file with a single line:

```python
from multiprocessing import Array
```

Fails to typecheck with the error:
```
example.py:1: error: Module 'multiprocessing' has no attribute 'Array'
```

This happens with both Python 3.6.3 and 3.7.0, using `mypy` version 0.630 which is currently the latest version.

Is there a way to use `mypy` to typecheck `multiprocessing` code?

**Comment by ethanhs** [comment]
Hi Oren, this appears to be a [typeshed](https://github.com/python/typeshed) issue. Please open an issue there about this error. With a quick look, it seems the Python 2 stubs are out of sync with the Python 3 stubs in this case.
