### ISSUE TITLE
Dataclass inheritance: Missing override.

### ISSUE THREAD

**Issue by guboi72** [python/mypy#5681]
### Description
The problem seems to be that mypy derived classes do not override base classes. Looking at the dataclass plugin `collect_attributes` method, it is not clear that it does a reverse MRO lookup as mentioned in the dataclass spec (https://docs.python.org/3/library/dataclasses.html#inheritance). Let me know if you would like me to suggest a pull request.

### To reproduce
```from typing import Any, Dict

from dataclasses import dataclass


@dataclass
class Base:
    some_int: Any
    some_str: str = 'foo'


@dataclass
class C(Base):
    some_int: int
```

> error: Attributes without a default cannot follow attributes with one

**Comment by csabaszilveszter** [comment]
I think this might be related...

`from dataclasses import dataclass
from typing import Any


@dataclass
class Base:
    some_int: Any
    some_str: str = 'foo'


@dataclass
class C(Base):
    some_other_int: int
    some_str: str = 'bar'
`

still throws:
`:13:5: error: Attributes without a default cannot follow attributes with one`
