### ISSUE TITLE
Mixing python functions and predicate objects raises error

### ISSUE THREAD

**Issue by Achimh3011** [python/mypy#5698]
A Callable and a predicate object implementing the same behavior should be assignable to the same variable without mypy raising an error.

* Are you reporting a bug, or opening a feature request?
bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

https://gist.github.com/Achimh3011/262acb8bf6d1b61ee7da6c574b662bd1

* What is the actual behavior/output?

````$ mypy sample.py
sample.py:39: error: Incompatible types in assignment (expression has type "Callable[[Path], bool]", variable has type "matching_suffix")
````

* What is the behavior/output you expect?

no error

* What are the versions of mypy and Python you are using?

````mypy==0.630
mypy-extensions==0.4.1
typed-ast==1.1.0
````
* Do you see the same issue after installing mypy from Git master?

yes

* What are the mypy flags you are using? (For example --strict-optional)

none

**Comment by JelleZijlstra** [comment]
You probably need to pre-declare `file_filter` (e.g., with `file_filter: Callable[[Path], bool]`). Mypy basically goes with the first assignment otherwise.

**Comment by ilevkivskyi** [comment]
This is not a bug. `matching_suffix` is a narrower type than just `Callable[[Path], bool]` (for example you can access `suffixes` on it). You therefore need to either give an annotation or switch order of branches.

To clarify, this is an error from mypy's point of view:
```python
if cond():
    x = 'hi'
else:
    x = 42
```

**Comment by ilevkivskyi** [comment]
Also FYI there is an existing proposal to allow this and automatically infer a union https://github.com/python/mypy/issues/2611
