### ISSUE TITLE
Provide more context about why incompatible with supertype is an error

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#5705]
Users often don't realize that overriding a method with an incompatible signature is unsafe from a type checking perspective; see #1237 for an example. We could generate some more descriptive notes with the error message, perhaps with a link to mypy documentation what contains a detailed discussion of Liskov Substitution Principle. We could also discuss how to work around the issue.

#5704 and #5025 are related issues.

**Comment by ckarnell** [comment]
@JukkaL I would be happy to take a stab at this if I get a couple extra cycles soon, if were a little more clear exactly what we want here. What should the notes be exactly? Or should I just wing it?

**Comment by lladhibhutall** [comment]
Hey @ckarnell are you still working on it?

**Comment by JukkaL** [comment]
Here's a proposal for the notes that could be added:

```
prog.py:7: error: Argument 1 of "f" is incompatible with supertype "C"; supertype defines the argument type as "Optional[int]"
prog.py:7: note: This violates the Liskov substitution principle
prog.py:7: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
```

**Comment by ckarnell** [comment]
Hi, just want to drop a note that I haven't gotten a chance to work on this.

**Comment by ChetanKhanna** [comment]
Hi, if no one's working on it, maybe I can?
And jump-starting to it, can someone let me know which file should define these new error/note messages? Is it one of the functions in `mypy/messages.py` that needs to be edited?

**Comment by msullivan** [comment]
Yeah, feel free to take a shot. Probably the messages are in mypy/messages.py, yeah. It is possible that you'll need to gather more information from the call sites (probably in `checker.py`) to produce a good message.

**Comment by ChetanKhanna** [comment]
> Here's a proposal for the notes that could be added:
> 
> ```
> prog.py:7: error: Argument 1 of "f" is incompatible with supertype "C"; supertype defines the argument type as "Optional[int]"
> prog.py:7: note: This violates the Liskov substitution principle
> prog.py:7: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
> ```

I made a PR with the notes suggested here
