### ISSUE TITLE
Chatty Init signature of derived types function!?

### ISSUE THREAD

**Issue by ocehugo** [python/mypy#5713]
* Are you reporting a bug, or opening a feature request?

I think it's a bug , given I don't see utility as actual user of the code. But not sure if it's a mypy bug or an ipython bug: I don't know which one is responsible for setting the init_signature field.

* Please insert below the code you are checking with mypy,
```python
from typing import Union

from mypy_extensions import TypedDict


class Orequest(TypedDict):
    origin: str


class Drequest(TypedDict):
    dest: str


Urequest = Union[Orequest, Drequest]


class Server(object):
    def __init__(self, adict: Urequest) -> None:
        pass
```
* What is the actual behavior/output?
```ipython
In [1]: from test import Server
In [2]: Server?
Init signature: Server(adict:Union[importlib._bootstrap.Orequest, importlib._bootstrap.Drequest]) -> None
Docstring:      <no docstring>
...
```
* What is the behavior/output you expect?
```
In [2]: Server?
Init signature: Server(adict:Union[Orequest,Drequest]) -> None
Docstring:      <no docstring>
...
```

* What are the versions of mypy and Python you are using?
python 3.6.5
mypy 0.6

* Do you see the same issue after installing mypy from Git master?
Yes

* What are the mypy flags you are using? (For example --strict-optional)
None
* If mypy crashed with a traceback, please paste
  the full traceback below.

I would expect a clean init signature, without the importlib._bootstrap. Maybe this is useful for debug purposes only?

**Comment by kirbyfan64** [comment]
FWIW I believe this would be a bug in python/typing and not here, though this seems flat-out incorrect.

**Comment by ethanhs** [comment]
Yes this appears to be a bug for the [`typing module bug tracker`](https://github.com/python/typing). Please open this there.

**Comment by ilevkivskyi** [comment]
I think this is not a bug in `typing` either. The built-in `help()` function works correctly with this:
```
Help on class Server in module __main__:

class Server(builtins.object)
 |  Methods defined here:
 |  
 |  __init__(self, adict:Union[__main__.Orequest, __main__.Drequest]) -> None
 ...
```

**Comment by ocehugo** [comment]
@ilevkivskyi, good catch on using the help...I'm spoiled by ipython magics. So I got stuck:
report to typing or ipython/somewhere else?

**Comment by ilevkivskyi** [comment]
I think try IPython first.

**Comment by carljm** [comment]
I believe that this is a bug in `mypy_extensions`: https://github.com/python/mypy_extensions/issues/2
