### ISSUE TITLE
Type declaritions in for loop

### ISSUE THREAD

**Issue by midnio** [python/mypy#5716]
```python
a: List[int] = [1, 5, 3]
for n: int in a:
    print(n)
```

This code doesnt work. Is there a possible way to do it?

**Comment by midnio** [comment]
Actually i realized this is the repo.

**Comment by ilevkivskyi** [comment]
I replied to you in typing repo. This was rejected in PEP 526, see relevant section in https://www.python.org/dev/peps/pep-0526/#rejected-postponed-proposals for motivation (basically we didn't want to complicate Python's parser).

**Comment by midnio** [comment]
Ok, thanks.
