### ISSUE TITLE
Allow overriding type annotations with type hint comments

### ISSUE THREAD

**Issue by Dentosal** [python/mypy#5724]
This is a feature request.

I suggest adding a config option or a per-file toggle that would allow overriding type annotations with comments, instead of producing an error message.

# Repro / example use case

[Hug](https://github.com/timothycrosley/hug) uses function return annotation to convert return value to http response. It requires a function (usually a type constructor), so using something like `typing.Dict[str, int]` causes an error. However, It would be useful to be able to annotate the real return type.

```python
import hug

@hug.get("/endpoint")
def endpoint() -> dict: # type: () -> Dict[str, int]
    return {"a": 1}
```

## Actual behavior

```
test.py:4: error: Function has duplicate type signatures
```
## Expected behavior

No output. Type signature in comment overrides the in-code annotation.

# Versions & Config
* Python 3.7.0
* mypy 0.620 and master (commit fdc7fccea61be4b800cb9ff2563d64233ae467cf) (output identical)

## mypy.ini

```ini
[mypy]
warn_redundant_casts = True
warn_unused_ignores = True
incremental = True

follow_imports = normal
ignore_missing_imports = True
disallow_untyped_calls = True
disallow_untyped_defs = True
check_untyped_defs = True
warn_return_any = True
warn_no_return = True
no_implicit_optional = True
strict_optional = True
```

**Comment by gvanrossum** [comment]
Wouldn't it be better to fix this in hug? Type comments are eventually going away completely, so really hug is impeding progress here, and should be fixed.

**Comment by msullivan** [comment]
I don't think we're going to do this.
