### ISSUE TITLE
How do I get mypy to use an absolute import instead of a relative import

### ISSUE THREAD

**Issue by scottbelden** [python/mypy#5725]
* Are you reporting a bug, or opening a feature request?

Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

Create a directory with the following three files:

 `__init__.py`
```python
# Blank file
```
 
`operator.py`
```python
# Blank file
```

`test.py`
```python
from operator import itemgetter
```

* What is the actual behavior/output?

```
$ mypy test.py
test.py:1: error: Module 'operator' has no attribute 'itemgetter'
```

* What is the behavior/output you expect?

I am running python 3.7 so mypy should use the definition in typeshed rather than trying to use a definition that doesn't exist in the local `operator.py`

* What are the versions of mypy and Python you are using?

mypy 0.620
python 3.7.0

* Do you see the same issue after installing mypy from Git master?

Have not tried this yet

* What are the mypy flags you are using? (For example --strict-optional)

No flags

**Comment by gvanrossum** [comment]
You are invoking mypy from inside the directory. It doesn't recognize this as a package, so it sees operator.py as a module with higher priority than the buildin one (same as Python itself would do in this case).

The solution would be `cd ..; mypy <directory>/test.py`.

**Comment by scottbelden** [comment]
Thanks!
