### ISSUE TITLE
Let's retire --quick-and-dirty

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#5728]
This flag was a hack attempted to create a faster incremental mode. We've now got daemon mode, which is much better. (Exception: daemon mode isn't supported on Windows.)

**Comment by ilevkivskyi** [comment]
I like this idea. We can start emitting a warning as soon as in the coming release, and then remove the flag when we add Windows support for daemon.

**Comment by JukkaL** [comment]
Agreed, let's do this.
