### ISSUE TITLE
Additional keyword args in class declaration not supported

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#573]
In Python 3 you can have arbitrary keyword args in a class declaration, as follows:

```
class C(metaclass=MyMeta, extra=42):
    ...
```

Here, mypy reports a syntax error at the comma.

**Comment by JukkaL** [comment]
Ah, I didn't know about that!

**Comment by JukkaL** [comment]
Bumping priority since I want to work towards full Python 3 syntax support.

**Comment by JelleZijlstra** [comment]
This is fixed; there are tests in test-data/unit/parse.test that do `class Foo(metaclass=Bar, _root=None): pass`.
