### ISSUE TITLE
Value of type "object" is not indexable. When accessing indexable value contained in a "dict"

### ISSUE THREAD

**Issue by yoeo** [python/mypy#5751]
Information to help understand the issue:

* Are you reporting a bug, or opening a feature request?
I'm reporting a bug.

* Please insert below the code you are checking with mypy,
```python
dictionary = {
    'int_value': 1,
    'list_values': [2]
}

item = dictionary['list_values'][0]
```

* What is the actual behavior/output?
```sh
$ mypy example.py 
.../example.py:6: error: Value of type "object" is not indexable
```

* What is the behavior/output you expect?
```sh
$ mypy example.py
```
No error message shown.

* What are the versions of mypy and Python you are using?
```sh
$ mypy --version
mypy 0.630
$ python --version
Python 3.6.6
```

* Do you see the same issue after installing mypy from Git master?
Yes.
```sh
$ mypy --version
mypy 0.640+dev.e12be3ba9e6be3e9242e3a81ffaa9b3a136876fe
$ mypy example.py
.../example.py:6: error: Value of type "object" is not indexable
```
If you have any question, I will be glad to answer them.

Thanks.

**Comment by ilevkivskyi** [comment]
This is not a bug. `Dict[str, object]` is a best type mypy can infer for this literal. If this is intended to be a `TypedDict` you should explicitly annotate it as such.
