### ISSUE TITLE
Documentation should be updated to for new namespace pkg support

### ISSUE THREAD

**Issue by macbeth322** [python/mypy#5757]
https://github.com/python/mypy/pull/5691 and https://github.com/python/mypy/pull/5591 added support for importing type hints from namespace packages according to pep 561 but the documentation hasn't been updated to reflect it https://mypy.readthedocs.io/en/latest/installed_packages.html#using-pep-561-compatible-packages-with-mypy

Specifically :
> Note that mypy does not support some more advanced import features, such as zip imports, namespace packages, and custom import hooks.

I suggest simply updating the docs to:
> Note that mypy does not support some more advanced import features, such as zip imports, ~~namespace packages,~~ and custom import hooks.

**Comment by gvanrossum** [comment]
See #5749.

**Comment by macbeth322** [comment]
I was specifically referring to this part of the documentation. https://github.com/python/mypy/blame/master/docs/source/installed_packages.rst#L28 which was not touched by #5749

**Comment by gvanrossum** [comment]
Ah, good call! Thanks for the reminder.

**Comment by gvanrossum** [comment]
Done, rev 9fcb9db4 (and rev 15d26685 in the release branch).
