### ISSUE TITLE
mypy-0.630's extensions does not satisfy its own runtime requirements

### ISSUE THREAD

**Issue by ikelos** [python/mypy#5763]
Hiya,

I've installed mypy-0.630 which features the following:

[setup.py's runtime requirements](https://github.com/python/mypy/blob/release-0.630/setup.py#L105): mypy_extensions >= 0.4.0, < 0.5.0
[extension's setup.py version number](https://github.com/python/mypy/blob/release-0.630/extensions/setup.py#L5): 0.5.0-dev

This is still the case on master as of `e170f6b`.

Unfortunately, `0.5.0-dev` does not appear to be `< 0.5.0` according to the distutils version checking, meaning that the extensions shipped in the release tarball do not meet the requirements of the release itself (meaning people may have to download a previous release tarball to get this version to run).  This appears to have been a very recent change (since 0.620 did not require the extensions).

Possible solutions would be that if the extensions module is to be treated as an independent package (with its own setup.py, which it appears to be as of 0.630) that it be moved to its own repository, ensuring that the versions do not need to be synchronized and can be released out of step with each other.  If the extensions are not large enough to be their own package, and are a hard requirement of mypy, then perhaps they should simply be made part of the distribution?

The solution to this issue may also affect #5592

**Comment by ilevkivskyi** [comment]
> Unfortunately, `0.5.0-dev` does not appear to be `< 0.5.0` according to the distutils version checking

Hm, this is a bit weird. Is there any way in distutils to indicate a dev version (that is "less" that corresponding release)? If yes, maybe we can just switch versioning scheme for `mypy_extensions`?

**Comment by ethanhs** [comment]
@ilevkivskyi I suppose we could switch to using any of these pre-release spellings: https://www.python.org/dev/peps/pep-0440/#pre-release-spelling. Then it should handle things correctly (though I have not tested this yet).

**Comment by ikelos** [comment]
I think it is already 0.5.0.dev0 when being processed (I've seen the dot rather than hyphen somewhere), but as I say, in its current form it doesn't work.

**Comment by ilevkivskyi** [comment]
> I think it is already 0.5.0.dev0 when being processed (I've seen the dot rather than hyphen somewhere), but as I say, in its current form it doesn't work.

But if `distutils` believes that `0.5.0.dev0 < 0.5.0` is not satisfied, isn't it a bug in `distutils`?

**Comment by ikelos** [comment]
PEP 440 discourages public release of development releases (and cites that pre-releases can have development releases too, such as `0.5.0a0.dev0).  It sounds as though the code should have been versioned `0.5.0a0` or `0.5.0b0` if it were a public prerelease (and looking at the `distutils` code, it should handle that as expected).

I'll continue on issue #5592 about whether this package should be separate or not.

**Comment by ikelos** [comment]
Having said that, apparently a version of `0.5.0a0` doesn't pass `0.5.0a0 < 0.5.0` (nor does `0.5a0 < 0.5.0` so I'll be digging into it further to check whether there is an issue with `distutils` version checking...

**Comment by ikelos** [comment]
Alright, it turns out `distutils` isn't used for requirements when `mypy`'s run, but actually it's `pkg_resources` which makes use of `packaging`.  It turns out `packaging` does versioning by removing all trailing `0`s and then comparing packages.  `0.5.0a0` (and `0.5.0.dev0`) are both `< 0.5.0`, but apparently the `packaging` package has the [following addition](https://github.com/pypa/packaging/blob/master/packaging/specifiers.py#L472):

```
# This special case is here so that, unless the specifier itself
# includes is a pre-release version, that we do not accept pre-release
# versions for the version mentioned in the specifier (e.g. <3.1 should
# not match 3.1.dev0, but should match 3.0.dev0).
if not spec.is_prerelease and prospective.is_prerelease:
    if Version(prospective.base_version) == Version(spec.base_version):
        return False
```

So it seems as though it's by design and (from their perspective) not a bug.

**Comment by ikelos** [comment]
This problem is still present in the 0.641 release.  What needs to happen to get the dependencies fixed, so that the packages can install successfully?

**Comment by msullivan** [comment]
OK, mypy_extensions has been split out into its own source project https://github.com/python/mypy_extensions. There are tags for `0.4.0` and `0.4.1` (which due to some sort of miscommunication, differ only by version number :P).

The extensions directory will be deleted in #6191.
