### ISSUE TITLE
Add a test for #5758 part two

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#5767]
See https://github.com/python/mypy/pull/5762#issuecomment-428755257

**Comment by macbeth322** [comment]
I can work on this over the next week unless you were already on planning working on it.

**Comment by gvanrossum** [comment]
> I can work on this over the next week

Please do!

**Comment by gvanrossum** [comment]
Had we had this test, then this bug would (hopefully) have been found before releasing 0.640: https://github.com/python/mypy/issues/5784
