### ISSUE TITLE
Add option (if it doesn't already exist) to ignore missing type annotations

### ISSUE THREAD

**Issue by kovasap** [python/mypy#5772]
I've been using type annotations in my projects mainly to make functions easier to understand/read, by making their input and output very clear.  However, I haven't been annotating the types of different variables i create, and not all my functions have type annotations.  Is it possible to have mypy ignore these cases (basically only warn me when i actually wrote an annotation AND it is incorrect)?

**Comment by gvanrossum** [comment]
Can you give a small example of a situation where mypy currently gives an error that you would like to suppress? I'm not quite sure of the situation from your description.

**Comment by kovasap** [comment]
Yes!  Two cases where I use this are shown in the example code below. 

```
class Thing(BaseThing):

    # CASE 1
    @custom_prop(attribute_tag1=val1, attribute_tag2=val2)
    def attribute(self) -> int:
        """documentation for this attribute"""
        # maybe do some stuff on set of this attribute here, but without using type annotations
        return self._attribute

    # CASE 2
    def method(self, arg: int, kwarg: bool=False) -> Dict[int, str]:
        # do some untyped stuff here
        return rvalue
```

**In case 1**, I have a system set up where I can define attributes of my classes as properties and use the type annotations to tag them with types.  This is useful for one type related reason:

1. The type of the attribute is stored by the class and can be readily accessed via introspection (e.g. by serialization code that stores different types in different ways)

And two other reasons:

2. I can tag the attribute with other properties of its own in the decorator i wrote (e.g. how it should be serialized, or if it should be serialized at all)
3. I can easily document the attribute using a docstring


**In case 2**, I usually write methods/functions with a fully typed out signature.  This is useful when I want to use the method later so I know exactly what types I should be expecting to pass it, and what type I should expect to get back.  I guess I'm basically using the type system as more visible documentation, but would also like to use it to check types as well when possible.  


In both cases, I tend to not fully type out the function bodies, since the code inside usually isn't too complicated and IMO type annotations would make it overly verbose.  The mypy errors I would like to suppress happen in these function bodies.  I additionally have a bunch of untyped code in the codebase that I would like to ignore by default, without going through and tagging it all as untyped.

**Comment by gvanrossum** [comment]
I'm sorry, it's still not clear to me. Are you saying that in the bodies of these functions you want to be able to write badly typed code like `'abc' + 42` without mypy reporting an error?

When I asked for specifics I was hoping that you would show an actual function or method with an actual error reported by mypy that you don't think is helpful. I am still in the dark guessing what you are putting in your function body that triggers unwanted mypy errors.

Or perhaps you are looking for the `@typing.no_type_check` decorator?

**Comment by kovasap** [comment]
Sorry for the vague response!  Here is a concrete example of my question:

```
from typing import Dict, Iterable

def func(arg: Dict[str, int], scale: int) -> Dict[str, int]:
    d = {}
    for symbol, number in arg.items():
        d[symbol] += scale * number
    return d
```

mypy returns:

```
mypytest.py:5: error: Need type annotation for 'd'
```

In my case, I'm interested in if there is a way for mypy to ignore the fact that i didn't annotate d even thought the function signature has type annotations (if I remove them the mypy error goes away).  

I think the broader question I have is really if mypy categorizes the errors it logs, and if I can filter those categories somehow.  Kind-of like how some PEP8 linters have error codes for different style violations, and you can tell them to ignore, for instance, the "E401 multiple imports on one line" error using a command line arg like --ignore E401.  Does this make sense with mypy?

**Comment by kovasap** [comment]
It looks like my last point has already been discussed here: https://github.com/python/mypy/issues/2417.

**Comment by kovasap** [comment]
Oh I'm sorry; it looks like a made a mistake while simplifying the code that contained the issue.  Here's a better, working example:

```
from typing import Dict


# same mypy error if this function is annotated or not!
def get_dict() -> Dict[str, int]:
    return {'h': 1}


def func(scale: int) -> Dict[str, int]:
    d = {}  # get "Need type annotation for 'd'" mypy error here
    ad = get_dict()
    for symbol, number in ad.items():
        if symbol not in d:
            d[symbol] = 0
        d[symbol] += scale * number
    return d


# same function, no annotations -> no mypy error
def func2(scale):
    d = {}
    ad = get_dict()
    for symbol, number in ad.items():
        if symbol not in d:
            d[symbol] = 0
        d[symbol] += scale * number
    return d


if __name__ == '__main__':
    assert func(4) == {'h': 4}
    assert func(2) == {'h': 2}
    assert func(0) == {'h': 0}
```

Here, I'm wondering the the mypy error in func can be suppressed somehow, or if there's another error in my code!

**Comment by srittau** [comment]
I wonder why you are using mypy at all if you don't want to check your function bodies? What errors would you expect mypy to catch?

**Comment by kovasap** [comment]
Good question.  Currently I am just using the type annotations as a form of documentation and have very recently starting playing with mypy itself.  My thought was, since I already have a bunch of annotations for my functions, it would be cool if mypy could spot things that are obviously wrong given the information it has.  But in the (many) cases in my code where the complete information mypy needs to tell me my code is incorrect is missing, I'd prefer not to see any errors.  Does this make sense?

**Comment by gvanrossum** [comment]
I don't think there's something actionable here for the mypy project. It looks like you're asking for a flag they lets mypy suppress errors in the body of all functions; but then you might as well not have them checked at all. If you only want to suppress specific errors you can add `# type: ignore` annotations to the lines where you get errors (like `Need type annotation for 'd'`). You can also mark classes or functions with `@no_type_check`. I very much doubt that in real code you would only get a specific error (like `Need type annotation for ...`), so even if we had numbered error message types that wouldn't really help you. Sorry.
