### ISSUE TITLE
Documentation for using --strict or --no-implicit-optional for checking against stub files at cli

### ISSUE THREAD

**Issue by EvanKepner** [python/mypy#5786]
Hi - I've found the following behavior when using stub files which was not clear
in the documentation. I'd like to offer to PR a change to the docs for running
at the command line to explain the behavior (and potentially in the command line
argument help attribute). Please let me know if this following is the expected
behavior, and I'll submit a PR with the documentation changes for review. Thanks!

## Version info

Python version: 3.7.0
MyPy verson: 0.630

MyPy installed with `pip install mypy` in a virtual environment created with `conda`.

## Setup

I have the following setup for testing / reproducing.

```
.
└── foo
    ├── __init__.py
    ├── internal_types.py
    ├── stub_types.py
    └── stub_types.pyi
```

The contents of `internal_types.py`is:

```python
from typing import Optional

# expected pass
def strlen_pass(s: Optional[str] = None) -> Optional[int]:
    return len(s) if s else None

# expected fail
def strlen_fail(s: float = None) -> Optional[int]:
    return len(s) if s else None
```

The contents of `stub_types.py` is:

```python
# expected pass
def strlen_pass(s = None):
    return len(s) if s else None

# expected fail
def strlen_fail(s = None):
    return len(s) if s else None
```

The contents of `stub_types.pyi` is:

```python
from typing import Optional

def strlen_pass(s: Optional[str] = None) -> Optional[int]: ...

def strlen_fail(s: float = None) -> Optional[int]: ...
```

## Generating behavior

Running `mypy` with no additional arguments will catch the type-error on the
`internal_types.py` file:

```
$ mypy foo/
foo/internal_types.py:9: error: Argument 1 to "len" has incompatible type "float"; expected "Sized"
```

You need to enable either the `--no-implicit-optional`, or `--strict` which includes
that argument, to have `mypy` check against the stub file:

```
$ mypy --no-implicit-optional foo/
foo/internal_types.py:8: error: Incompatible default for argument "s" (default has type "None", argument has type "float")
foo/internal_types.py:9: error: Argument 1 to "len" has incompatible type "float"; expected "Sized"
foo/stub_types.pyi:6: error: Incompatible default for argument "s" (default has type "None", argument has type "float")
```

```
$ mypy --strict foo/
foo/internal_types.py:8: error: Incompatible default for argument "s" (default has type "None", argument has type "float")
foo/internal_types.py:9: error: Argument 1 to "len" has incompatible type "float"; expected "Sized"
foo/stub_types.pyi:6: error: Incompatible default for argument "s" (default has type "None", argument has type "float")
```

If the `internal_types.py` file is removed from the `foo` folder the same behavior is observed.

**Comment by gvanrossum** [comment]
This looks like mostly a request for help. Our Gitter channel is more likely to be able to help you quickly. https://gitter.im/python/typing

**Comment by EvanKepner** [comment]
Hey thanks for the response, I think I was operating under the assumption that `.pyi` files that matched the name of another associated file were checked against it e.g. `stubs_types.pyi` is checked against `stub_types.py` but with closer inspection it looks like they are checked independently. I'll close this issue since I think this answers the question.
