### ISSUE TITLE
Using enums with `--disallow-any-expr` always results in an error

### ISSUE THREAD

**Issue by Michael0x2a** [python/mypy#5788]
Consider the following program:

```python
from enum import Enum

class Test(Enum):
    FOO = 1
    BAR = 2
    BAZ = 3

enum_value = Test.FOO
```

This program typechecks perfectly fine under normal conditions. 

However, if you run mypy with the `--disallow-any-expr` flag, it'll report a spurious `Expression type contains "Any" (has type "Type[Test]")` error on the final line. This is the case even if I do `enum_value: Test = Test.FOO` or other similar variations.

(There are several weird things here -- why does mypy think there's any 'Any'? Why is the reported type `Type[Test]` instead of `Test`?)

**Comment by gvanrossum** [comment]
To debug this, put `import pdb; pdb.set_trace()` in the function that prints this error (`disallowed_any_type()` in messages.py) and go up 1-2 stack frames. You'll find this code:
```py
        if (self.chk.options.disallow_any_expr and
                not always_allow_any and
                not self.chk.is_stub and
                self.chk.in_checked_function() and
                has_any_type(typ)):
            self.msg.disallowed_any_type(typ, node)
```
Something there triggers incorrectly.

The `Type[Test]` is a hint that the expression that triggers it is the subexpression `Test` (which is a class, so its type is indeed `Type[Test]`). The bug could be in `has_any_type(typ)`.

**Comment by noyainrain** [comment]
Hey everyone, first of all, thanks for your work on mypy, it's a really nice tool! :smile: 

I've also run into a problem with `--disallow-any-expr` reporting spurious errors, which might be related to this issue. (If you think it has a different cause, I will gladly open another ticket)

Consider the following file `any.py`:

```python3
def access_before_declaration(self) -> None:
    obj = Object('foo')
    obj.value
    x = 1

    reveal_type(x) # Revealed type is 'builtins.int'
    x = x + 1 # Expression has type "Any"

class Object:
    def __init__(self, value: str) -> None:
        self.value = value

def access_after_declaration(self) -> None:
    obj = Object('foo')
    obj.value
    x = 1

    reveal_type(x) # Revealed type is 'builtins.int'
    x = x + 1
```

Running mypy on it produces:

```
$ python3 -m mypy --version
mypy 0.641
$ python3 -m mypy --disallow-any-expr any.py
any.py:6: error: Revealed type is 'builtins.int'
any.py:7: error: Expression has type "Any"
any.py:18: error: Revealed type is 'builtins.int'
```

What we see is that `x` is correctly identified as `int` in `access_after_declaration`, but incorrectly as `Any` in `access_before_declaration`. The error is only triggered in very specific circumstances:

* There is a class defined **after** the inspected line
* An attribute of an instance of that class is accessed **before** the inspected line

If you need more information or if there is anything I can do to help fix this, just let me know. :slightly_smiling_face:

**Comment by gvanrossum** [comment]
Hm, yea, I see this too. Commenting out the `obj.value` makes the error go away. It seems there's a bug in the processing of `--disallow-any-expr`.

**Comment by gvanrossum** [comment]
I'm not sure it's got the same cause though. Maybe you can use the debugging technique I suggested a few comments up?

**Comment by Michael0x2a** [comment]
As an update, my bug report was resolved by a typeshed tweak: https://github.com/python/typeshed/pull/2539

I'm pretty sure the bug @noyainrain brought up has a different root cause though -- not sure if the correct thing to do is keep this issue open or file a new one.

**Comment by gvanrossum** [comment]
This issue should be closed and @noyainrain should create a new issue.
