### ISSUE TITLE
Too many arguments for "__setattr__" of "object" on valid code

### ISSUE THREAD

**Issue by tavianator** [python/mypy#5794]
This code is a reasonable pattern for initializing "immutable" objects:

```python
class Foo:
    def __new__(cls, bar: int):
        ret = super().__new__(cls)
        super().__setattr__(ret, "bar", bar)
        return ret
```

But mypy complains

    foo.py:4: error: Too many arguments for "__setattr__" of "object"

**Comment by gvanrossum** [comment]
This is another special case for `__new__` that mypy misses -- in `__new__`, `super()` is a class object (its type is something like `Type[B]` where `B` is the base class -- if there are multiple base classes the type becomes more problematic).

In the grand scheme of things it doesn't feel like it's a big priority, though if you come up with a fix we'll take it!

**Comment by tavianator** [comment]
This is actually broken for things other than `__new__` too:

```
class Foo:
    @classmethod
    def create(cls, bar: int) -> "Foo":
        ret = cls.__new__(cls)
        super().__setattr__(ret, "bar", bar)
        return ret
```

I'll try to find a fix.
