### ISSUE TITLE
Checking functions that accept Ellipsis arguments

### ISSUE THREAD

**Issue by t-vi** [python/mypy#5796]
I have a function (`__getitem__`) that accepts integers or ellipsis arguments.
I haven't found a way to specify this in a stub (pyi) file so that mypy will like it.
```python
class X:
    def __getitem__(self, idx: Union[int, ???]) -> 'X': ...
```
but what to write in place of `???`.
One solution would be None-style `Ellipsis`, but that doesn't work currently.
(numpy ndarrays would have the same issue, but I haven't found a stub file for them.)

I would greatly appreciate any hint how this works and if there is a way this works, my feature request would be to add a hint in the documentation, too.

**Comment by gvanrossum** [comment]
Duplicate of #4791.

**Comment by t-vi** [comment]
Ah, sorry. Thank you for pointing to #4791.
