### ISSUE TITLE
got "YieldType", expected "YieldType"

### ISSUE THREAD

**Issue by toejough** [python/mypy#5801]
> * Are you reporting a bug, or opening a feature request?

Bug.

> * Please insert below the code you are checking with mypy.

*example-yield.py*
```python
# [ Imports:Python ]
import typing


# [ Types ]
SendType = typing.TypeVar('SendType')
YieldType = typing.TypeVar('YieldType')


# [ Classes ]
class Coro:
    def __init__(self, arg1: YieldType, arg2: SendType) -> None:
        self.coro: typing.Coroutine[YieldType, SendType, None]

    def send(self, value: SendType) -> YieldType:
        return self.coro.send(value)
```

> * What is the actual behavior/output?

*shell*
```fish
> mypy example-yield.py
example-yield.py:20: error: Incompatible return value type (got "YieldType", expected "YieldType")
example-yield.py:20: error: Argument 1 to "send" of "Coroutine" has incompatible type "SendType"; expected "SendType"
```

> * What is the behavior/output you expect?

I expect a pass.

> * What are the versions of mypy and Python you are using?

* Python: 3.7.0
* Mypy: 0.610

> * Do you see the same issue after installing mypy from Git master?

Yes.  I tried with version `0.650+dev.47c25263694bae2a577c15d70d2988db2e8e8584`

> * What are the mypy flags you are using? (For example --strict-optional)

I've tried with just `mypy` and `mypy --strict`, with the same results.

Generally very happy with mypy - things keep getting better, and I keep trying to get better at using it (and the mypy-extensions!).  

Let me know if you'd like me to try anything, or if I'm just straight-up doing something wrong.

It seems like at the very least, though, `mypy` shouldn't be erroring by telling me that it found what it expected to.

FWIW, if I don't define the send type, there are no problems:

*example-yield.py*
```python
# [ Imports:Python ]
import typing


# [ Types ]
YieldType = typing.TypeVar('YieldType')


# [ Classes ]
class Coro:
    def __init__(self, arg1: YieldType) -> None:
        self.coro: typing.Coroutine[YieldType, None, None]

    def send(self, value: typing.Any) -> YieldType:
        return self.coro.send(value)
```

*shell*
```fish
> mypy example-yield.py
>
```

**Comment by toejough** [comment]
same results for `typing.Generator` and whether I specify the types as code (`YieldType`) or as strings (`"YieldType"`)

**Comment by gvanrossum** [comment]
Did you mean to define a non-generic class with two independently generic methods? Or did you mean the class `Coro` to be generic? If the latter, change the heading to
```py
class Coro(Generic[YieldType, SendType]):
```

**Comment by toejough** [comment]
well, that's a good question.  I didn't explicitly mean to make it generic, but I also don't think I mind making it so.  

My point was just to be able to correctly specify the types that the `send` function would take/return, based on the type of the coroutine stored at `self.coro`.

oHHHHHHH.  OH I see it now.  Wow, ok.  Thank you for the snappy response time and the clarity it gave me!

Well shoot.  Now I understand what's happening, and that's awesome, but I'm not sure what to suggest for a clearer error message to help others.  Maybe catch that the text in the message is the same for expected/actual and suggest that the author tie them together in the class def line like you did for me?

Regardless, thank you again.  Got a solution and I had my mypy worldview corrected, which is fantastic.  Happy to close the issue or leave it open for the error message, whichever you'd prefer.

**Comment by gvanrossum** [comment]
You're welcome! I haven't seen this particular confusion before, so I think I'll just close the issue for now.

**Comment by toejough** [comment]
Ha, fair enough :-)
