### ISSUE TITLE
TypeVar order matters

### ISSUE THREAD

**Issue by mgilson** [python/mypy#5805]
It seems that when matching types in a `TypeVar`, mypy will choose the last matched type:

```py
# ~/sandbox/identity.py
from typing import TypeVar
import numpy as np

_T = TypeVar("_T", 'MyType', np.ndarray)

class MyType:
    pass

def identity(item: _T) -> _T:
    if not isinstance(item, (MyType, np.ndarray)):
        raise TypeError("bad")
    return item

reveal_type(identity(MyType()))
reveal_type(identity(np.array([1, 2, 3])))
```

If I run this:

```sh
$ mypy --strict --ignore-missing-imports ~/sandbox/identity.py
.../sandbox/identity.py:15: error: Revealed type is 'Any'
.../sandbox/identity.py:16: error: Revealed type is 'Any'
```

If I flop the definition order of my `TypeVar`:

```py
_T = TypeVar("_T", np.ndarray, 'MyType')
```

I get something that seems more sensible:

```sh
$ mypy --strict --ignore-missing-imports ~/sandbox/identity.py
.../sandbox/identity.py:15: error: Revealed type is 'identity.MyType*'
.../sandbox/identity.py:16: error: Revealed type is 'Any'
```

I'm not sure that I understand mypy/typing's contravariant/covariant enough to know if there is a resolution by using those.  However, it seems to me that `mypy` should pick the closest matching type from the TypeVar (though I guess the pushback is that it's not trivial to define "closest").  In any case, it should at least not let `Any` override a previously matched type?

Python 3.6.6
mypy 0.641  (The required ordering here seems to have flip-flopped between 0.630 and 0.641 which is why I noticed)

**Comment by gvanrossum** [comment]
This is because `np` and `np.ndarray` have type `Any`. If you install the [numpy stubs](https://github.com/numpy/numpy-stubs) you get the right answer.
