### ISSUE TITLE
Can we drop the revision_history.rst file in the docs?

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#5807]
The docs have a purported revision history which is not very useful (it only marks major updates to the docs, not to actual mypy functionality) and a pain to maintain. Can we just drop it?

**Comment by Michael0x2a** [comment]
👍 -- maybe we can replace it with a link to the blog instead?

**Comment by ilevkivskyi** [comment]
I am fine with dropping it. I am also fine with keeping it (it has some history about early days of mypy), but put a "tombstone" at the top, like this:
```
************************************
THIS FILE IS NOT MAINTAINED, SEE ...
************************************
```

**Comment by ethanhs** [comment]
@ilevkivskyi I mean it will remain in git history, so I don't see a problem with deleting it.

**Comment by ilevkivskyi** [comment]
OK.
