### ISSUE TITLE
Feedback for name2type mapping

### ISSUE THREAD

**Issue by guettli** [python/mypy#5841]
Dear mypy developers,

I am looking for feedback for this little idea:

https://github.com/guettli/python-name2type-mapping

Please tell me what you think.

Python name2type mapping
=========================

In October 2018 on the mailing list python-ideas some developers encouraged me, that the idea of a name2type mapping would be usefull.

Goal:

* Better type-hints in IDEs.
 
This is not the goal:

* Type-hints which get used during run-time.
 
 
Syntax Proposal
===============
 
The name2type mapping is defined in the docstring of a Python file.
 
The general syntax is "name2type:" followed by a comma sperated list of variable names. Then ":", then the type hint.
 
Examples::
 
     """
     name2type: my_int, my_number, ....: int
     name2type: request*: django.http.HttpRequest
     """"
 
If the docstring is in a file called `__init__.py`, then the type hints get specified for all files below this directory (recursively).

**Comment by ilevkivskyi** [comment]
I think this belongs rather to stubgen (maintained here), or to PyAnnotate (in a separate repo), rather than to mypy itself. Otherwise such feature might have some weird action at a distance. Also explicit is better than implicit.

**Comment by gvanrossum** [comment]
Yeah, there is now a whole repo dedicated to discussion of this idea, no need to have a separate discussion in any of the mypy projects.
