### ISSUE TITLE
distutils.dist.Distribution stub missing attributes

### ISSUE THREAD

**Issue by erdincmutlu** [python/mypy#5848]
When working on 
https://github.com/pypa/pip/issues/4748
for pip._internal.locations
I am getting following errors

src\pip\_internal\locations.py:166: error: Revealed type is 'distutils.dist.Distribution'
src\pip\_internal\locations.py:167: error: "Distribution" has no attribute "parse_config_files"
src\pip\_internal\locations.py:168: error: "Distribution" has no attribute "get_command_obj"
src\pip\_internal\locations.py:188: error: "Distribution" has no attribute "get_option_dict"

Please make those stubs in typeshed

**Comment by ilevkivskyi** [comment]
Yes, this is a typeshed issue, not mypy.
