### ISSUE TITLE
reveal_type() infers incorrectly even with annotations. Union causing int, bool, float to merge?

### ISSUE THREAD

**Issue by AgarwalPragy** [python/mypy#5857]
* Bug?
* 
    ```python3
    from typing import Union
    
    T = Union[str, int, float, bool, None]
    
    x: T
    reveal_type(x)
    
    class Foo:
        y: T
    
        def __init__(self, y: T) -> None:
            self.y: T = y
            reveal_type(y)
            reveal_type(self.y)
    ```
* Actual output
    ```python3
       trial.py:6: error: Revealed type is 'Union[builtins.str, builtins.int, builtins.float, builtins.bool, None]'
       trial.py:13: error: Revealed type is 'Union[builtins.str, builtins.int, builtins.float, builtins.bool, None]'
       trial.py:14: error: Revealed type is 'Union[builtins.str, builtins.float, None]'
    ```

* Expected output
    ```python3
       trial.py:6: error: Revealed type is 'Union[builtins.str, builtins.int, builtins.float, builtins.bool, None]'
       trial.py:13: error: Revealed type is 'Union[builtins.str, builtins.int, builtins.float, builtins.bool, None]'
       trial.py:14: error: Revealed type is 'Union[builtins.str, builtins.int, builtins.float, builtins.bool, None]'
    ```
* Python 3.7.0
    mypy 0.641

* Happens both with and without `--strict`
* Do you see the same issue after installing mypy from Git master?
    yes

It seems as if `int`, `bool` are getting merged into `float`.
If we set `T = Union[str, int, bool, None]`, we get `trial.py:14: error: Revealed type is 'Union[builtins.str, builtins.int, None]'`. Since every `bool` is also an `int`, this might be happening due to `Union` being covariant. Not sure about why `float` takes over when it's added though.

Order inside `Union[]` has no effect.

**Comment by gvanrossum** [comment]
Since `float` is a superclass of `int`, it makes sense that they get merged. I'm not sure why it only does this for `self.y` and not for `x` and `y` though.

**Comment by AgarwalPragy** [comment]
> Since `float` is a superclass of `int`, it makes sense that they get merged. I'm not sure why it only does this for `self.y` and not for `x` and `y` though.

Sorry, python noob here. That was my first guess but I tried the following
```
>>> isinstance(1, float)
False
```

**Comment by gvanrossum** [comment]
There's a difference between runtime and type-check time. At runtime `float` is not a superclass of `int`, but in mypy's mind it is. I think there's nothing wrong here.

**Comment by gvanrossum** [comment]
> Is it okay to leave the varying behavior of reveal_type() as is?

Yes.
