### ISSUE TITLE
Support non-ascii identifiers

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#586]
We should support non-ascii (unicode) identifiers as variable names, etc.

**Comment by o11c** [comment]
I'm actually not sure how to support this since it is defined in terms of unicode classes, which are not supported by python's regex engine, and there is no efficient way to enumerate the characters in each category (let alone DTRT for the particular version of unicode supported by any given python3 release).

Really seems like more of a misfeature than a feature to me.

**Comment by JukkaL** [comment]
Hmm. I haven't actually looked into this in much detail. We should still be able to implement this in an efficient manner for the 99% of code that doesn't use unicode identifiers. It's fine if using unicode identifiers slows down parsing, but it's not okay if this feature slows down parsing everything else.

Maybe something like this:

Have a separate case in the lexer for all non-ascii characters outside string literals and comments (character code >= 128). Fall back to a possibly slow implementation that can do whatever needed to get this working when we hit this, but skip this code path altogether for code that doesn't use any unicode identifiers.

Also, the `unicodedata` module could be useful.

**Comment by gvanrossum** [comment]
I'm going to close this as a won't fix because the new parser will solve this and we're not going to put any work in the old parser/lexer.

**Comment by vedgar** [comment]
May I ask what's the status of that New Parser? Maybe I can even work on it, if it's Python-only. I was extremely surprised to learn that mypy still doesn't understand Python naming rules. PEP 3131 is almost a decade old. :-o

**Comment by gvanrossum** [comment]
The new parser will be the default on the next mypy release (and is already
on the GitHub master).

--Guido (mobile)
