### ISSUE TITLE
What is the proper way to ignore “missing attribute” errors in mixins?

### ISSUE THREAD

**Issue by kurtgn** [python/mypy#5868]
I cannot get mypy to work properly with mixins: it keeps complaining that my mixins reference missing attributes. Consider this example:

    
    
    class PrintValueMixin:
        """A mixin that displays values"""
    
        def print_value(self) -> None:
            print(self.value)
    
    
    class Obj(PrintValueMixin):
        """An object that stores values. It needs a mixin to display its values"""
    
        def __init__(self, value):
            self.value = value
    
    
    instance = Obj(1)
    instance.print_value()

If I run mypy on this file, I get an error:

    error: "PrintValueMixin" has no attribute "value"

Of course it has no attribute "value". It is a mixin, it should not have its own attributes.

So what is the proper way to deal with typechecking mixins?

**Comment by ethanhs** [comment]
This was actually recently asked and answered here: https://github.com/python/mypy/issues/5837

I think we should probably add something in the docs (maybe `common_issues.rst` since this seems to be a frequent problem.

**Comment by JukkaL** [comment]
Agreed, this is worth documenting. I'm increasing priority this is something I'd be happy to accept as a contribution.

**Comment by AndrewUshakov** [comment]
Why solution below (define mixin class as an abstract class) is unacceptable? Pycharm also will not generate warning. Without such modification attempt to directly instantiate mixin class will generate run time error and both mypy and Pycharm  properly warn about this possibility.

```Python
from abc import ABC, abstractmethod


class PrintValueMixin(ABC):
    """A mixin that displays values"""

    @abstractmethod
    def __init__(self):
        self._value = None

    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, value):
        self._value = value

    def print_value(self) -> None:
        print(self.value)


class Obj(PrintValueMixin):
    """An object that stores values. It needs a mixin to display its values"""

    def __init__(self, value):
        super().__init__()
        self.value = value


if __name__ == '__main__':

    instance = Obj(1)
    instance.print_value()
```

**Comment by kurtgn** [comment]
Looks like this would work - but imagine the amount of boilerplate you should write if there are several mixins manipulating several values.  A simple example - one mixin displaying the value and another one changing the value. Do they both need setters and getters for the `value` property?

**Comment by kurtgn** [comment]
There's another suggestion from [stackoverflow](https://stackoverflow.com/questions/53120262/mypy-how-to-ignore-missing-attribute-errors-in-mixins/53228204#53228204) which I like for its brevity - :just declaring property type on the mixin class:

```
class PrintValueMixin:
    """A mixin that displays values"""

    value: int

    def print_value(self) -> None:
        print(self.value)


class Obj(PrintValueMixin):
    """An object that stores values. It needs a mixin to display its values"""

    def __init__(self, value):
        super().__init__()
        self.value = value

    def change_value(self):
        self.value = 'changed'


if __name__ == '__main__':

    instance = Obj(1)
    instance.print_value()

```

**Comment by ziima** [comment]
@kurtgn: declaring attribute is fine, when there is just few of them. I gets annoying a lot with the growing number of attributes. And the same problem applies to methods.
