### ISSUE TITLE
Infer type of empty collection from sibling

### ISSUE THREAD

**Issue by lincolnq** [python/mypy#5871]
The following example makes it clear:

```py
my_dict = {
    'a': [1,2],
    'b': []
}
reveal_type(my_dict)  # error: Revealed type is 'builtins.dict[builtins.str*, builtins.object*]'
```

I expected my_dict to have type `Dict[str, List[int]]` rather than `Dict[str, object]`. 

Possibly related to #1055.

**Comment by ilevkivskyi** [comment]
This may be not as easy as it looks, mypy's inference is already exponentially complex, see https://github.com/python/mypy/issues/3796 so we need to be careful not to slow it down even more. Potentially we can special case built-in collections and their "literals".

**Comment by ilevkivskyi** [comment]
Oh, yes, this is a duplicate.
