### ISSUE TITLE
Make any callable compatible with (*args: Any, **kwargs: Any)?

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#5876]
Perhaps a callable that accepts arbitrary arguments by having `(*args: Any, **kwargs: Any)` could be treated similarly to `Callable[..., X]` (with explicit `...`), i.e. a callable with arbitrary arguments would be compatible with it.

The reason for this is that there's no easy way to annotate a function so that the type would be `Callable[..., X]`, even though this seems to be a somewhat common need. Users sometimes assume that using `(*args: Any, **kwargs: Any)` will work for this purpose and are confused when it doesn't. https://github.com/python/typing/issues/264#issuecomment-436525286 is a recent example.

Example:

```py
from typing import Any

class A:
    # A method that accepts unspecified arguments and returns int
    def f(self, *args: Any, **kwargs: Any) -> int: pass

class B(A):
    def f(self, x: int) -> int: pass  # Should be okay
```

We could perhaps extend this to handle decorators as well:

```py
from typing import Any, Callable, TypeVar

T = TypeVar('T', bound=Callable[..., Any])

def deco(f: T) -> T:
    def wrapper(*args: Any, **kwargs: Any) -> Any:
        print('called')
        return f(*args, **kwargs)
    return wrapper  # Maybe this should be okay
```

**Comment by ilevkivskyi** [comment]
I actually like this idea, I have seen this confusion several times, and although it is a bit unsafe, most of the time when people write `(*args, **kwargs)` it means "don't care", rather than "should work for all calls".

**Comment by gvanrossum** [comment]
Agreed, this is a case where practicality beats purity.

**Comment by ckyoog** [comment]
I do read the following words in [mypy docs](https://mypy.readthedocs.io/en/latest/kinds_of_types.html#callable-types-and-lambdas)

> Mypy recognizes a special form **Callable[..., T] (with a literal ...)** which can be used in less typical cases. It is compatible with arbitrary callable objects that return a type compatible with T, independent of the number, types or kinds of arguments. Mypy lets you call such callable values with arbitrary arguments, without any checking – in this respect they are **treated similar to a (\*args: Any, \*\*kwargs: Any) function signature**. 

Does it mean this issue has been resolved? Correct me if I am wrong.

**Comment by jonapich** [comment]
@ckyogg: no, the issue here is to be able to enforce partial signatures to improve duck typing possibilities. Your excerpt is asking for "any callback whatsoever" but i want to define "a callback with a quit flag as first argument and anything else after"

**Comment by jlaine** [comment]
Has anyone found a good solution for this? My usecase is exactly the same as @jonapich I want to enforce the first argument and allow anything afterwards.

**Comment by chadrik** [comment]
+1.  It seems like the only solution right now is to create a union type alias covering all cases, which is obviously something I'd like to avoid doing!

```python
class CallbackWithKwargs1(Protocol[T_contra, T_co]):
    def __call__(self, __element: T_contra, __arg1=...) -> T_co:
        pass

class CallbackWithKwargs2(Protocol[T_contra, T_co]):
    def __call__(self, __element: T_contra, __arg1=..., __arg2=...) -> T_co:
        pass

...

CallbackWithKwargs=Union[
    CallbackWithKwargs1, CallbackWithKwargs2, ...]
```

**Comment by antonagestam** [comment]
Another common real-world example is trying to create a type for a functional view in Django, where the first argument is always a `Request` and there might be more arguments for URL parameters.

**Comment by rmorshea** [comment]
Perhaps this proposal could resolve this issue?

https://github.com/python/mypy/issues/8263

**Comment by kevlarr** [comment]
This would be such a great addition. I had hoped that `VarArg` and `KwArg` from [mypy_extensions](https://mypy.readthedocs.io/en/stable/additional_features.html#extended-callable-types) would be the answer, but sadly those aren't useful here..

**Comment by jmehnle** [comment]
**I** really just care about typing a function (in a prototype) with *arbitrary* arguments (except for perhaps `self`), and `def foo(self, *args: Any, **kwargs: Any) -> Any: ...` just doesn't work. What am I to do?

**Comment by JelleZijlstra** [comment]
@jmehnle does something like `foo: Callable[..., Any]` work?

**Comment by rmorshea** [comment]
Tip for achieving this at present:

```python
from typing import Callable, Any


class Parent:

    method: Callable[..., int]
    def method(  # type: ignore
        self, *args: Any, **kwargs: Any,
    ) -> int:
        ...

class Child(Parent):
    def method(self, x: str) -> int:
        ...
```

Try it: https://mypy-play.net/?mypy=latest&python=3.8&gist=ba254920ee62608c5696c29610b2a379

**Comment by jmehnle** [comment]
> @jmehnle does something like `foo: Callable[..., Any]` work?

Alas, no. I get: `note: Protocol member Connection.cursor expected settable variable, got read-only attribute`.

And unfortunately @rmorshea's trick still generates that very same message (see also https://github.com/python/mypy/issues/9560).

**Comment by hauntsaninja** [comment]
Doesn't Guido's trick in #9560 work?

**Comment by jmehnle** [comment]
It does. I saw that only just now. I'm going to use that for the time being, but of course that still doesn't make any callable match the `(*args: Any, **kwargs: Any)` type (*this* issue).

**Comment by Timtam** [comment]
I've got the same issue here, currently writing an interface that accepts a callback that has at least one specific parameter, the others are optional and can be handed to a registering function beforehand. I thus defined my protocol as follows:
```
from typing import Any

from typing_extensions import Protocol

class Callback(Protocol):
    def __call__(self, gain: bool, *args: Any, **kwargs: Any) -> None:
        ...
```

But now, every function passed with type Callback needs to explicitly have the structure 
```
def func(param: bool, *args: Any, **kwargs: Any)
```
although a function
```
def func(param: bool)
```
is totally valid as long as no additional arguments were supplied to the registering function before.
Is there any solution to this problem yet?

**Comment by leandropls** [comment]
@Timtam I don't see `def func(param: bool)` as compatible. IMV, an object that satifies the given Callback protocol must accept a sequence of arguments and keyword arguments without raising a TypeError.

**Comment by rmorshea** [comment]
@Timtam I think that use case might be addressed here: https://github.com/python/typing/issues/696

**Comment by jkb0o** [comment]
The working workaround solution for now is to enumerate all possible calls. This works for me:

```python
from typing import Protocol, TypeVar, Callable, cast

class IRequest(Protocol):
    body: str
    
class IResponse(Protocol):
    code: int

Handler0 = Callable[[IRequest], IResponse]
Handler1 = Callable[[IRequest, str], IResponse]
Handler2 = Callable[[IRequest, str, str], IResponse]
Handler = TypeVar('Handler', Handler0, Handler1, Handler2)
    

def route(path: str) -> Callable[[Handler], Handler]:
    def wrapper(handler: Handler) -> Handler:
        return handler
    return wrapper

@route("/users") # <---------- pass
def api(req: IRequest) -> IResponse:
    return cast(IResponse, None)

@route("/user/{name}") # <---------- pass 
def user_by_name(req: IRequest, name: str) -> IResponse:
    return cast(IResponse, None)

@route("/user/{uid}") # <---------- fail
def user_by_id(req: IRequest, uid: int) -> IResponse:
    return cast(IResponse, None)
```
```zsh
➜ python -mmypy test.py
test.py:28: error: Value of type variable "Handler" of function cannot be "Callable[[IRequest, int], IResponse]"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by NeilGirdhar** [comment]
Doesn't the recently-added `ParamSpec` cover the decorator case in the original issue?  Is there still a significant need for this?

**Comment by hauntsaninja** [comment]
It's still an issue for subclasses, which is the main thing in the original post. This is one of mypy's most reacted-to open issues, so definitely some real usability issues here.

**Comment by NeilGirdhar** [comment]
> It's still an issue for subclasses, which is the main thing in the original post. 

Are there good examples of when a base class would want to expose a member that accepts arbitrary parameters?

> This is one of mypy's most reacted-to open issues, so definitely some real usability issues here.

Some of that reaction may have preceded the addition of `ParamSpec`, and may be focused on the decorator example, which is extremely important.  There's no way to gauge how many people really want base methods with arbitrary parameters that are constrained in derived classes.  To my eyes, that is a bad pattern that should be avoided.

**Comment by hauntsaninja** [comment]
Check out some of the issues that link to here. Yes, this is obviously unsafe, which is why this hasn't been done yet. The change itself is trivial, see #11203

**Comment by NeilGirdhar** [comment]
@hauntsaninja Yeah, I looked at a few.  I think MyPy is correct.  These are LSP violations an indicative of poor code.  It would be better in my opinion to just expand the documentation to explain workarounds.  For example, in #9174, the methods `do_something` on each class should simply have three different names.  There was no reason to give them the same name since they can't be used polymorphically.

**Comment by hauntsaninja** [comment]
Since this has been merged and I got a question about it already, if your parent class actually accepts everything, use `object` instead of `Any` to ensure you get LSP errors.

**Comment by gandhis1** [comment]
> I've got the same issue here, currently writing an interface that accepts a callback that has at least one specific parameter, the others are optional and can be handed to a registering function beforehand. I thus defined my protocol as follows:
> 
> ```
> from typing import Any
> 
> from typing_extensions import Protocol
> 
> class Callback(Protocol):
>     def __call__(self, gain: bool, *args: Any, **kwargs: Any) -> None:
>         ...
> ```
> 
> But now, every function passed with type Callback needs to explicitly have the structure
> 
> ```
> def func(param: bool, *args: Any, **kwargs: Any)
> ```
> 
> although a function
> 
> ```
> def func(param: bool)
> ```
> 
> is totally valid as long as no additional arguments were supplied to the registering function before. Is there any solution to this problem yet?

How did you end up resolving this issue? The PR appears to have only solved the case when the entirety of your function signature is `args`/`kwargs`, not when you have a partial signature as your example is.

**Comment by NeilGirdhar** [comment]
> How did you end up resolving this issue?

I don't think you're going to be able to get this to work.  This pull request that closed this issue was really about providing some notation for `Callable[..., Any]`.  What you're asking for doesn't exist.

Can I suggest you choose a design that doesn't have LSP errors?  How about:
```python
class PreFuncExtra: ...

class PreFunc(Protocol[A_co]):
    def __call__(self, length_table: int, pre_func_extra: PreFuncExtra) -> A_co:
        ...
```
And then you can simply derive from PreFuncExtra in your derived classes to add data members.  Your derive classes should all accept `PreFuncExtra`, but assert that the correct subtype has been passed in.

Even if you were able to use the arbitrary args/kwargs solution that you want, you would have to assert on types, and  you would end up asserting on many more types rather than a single instance of PreFuncExtra.

**Comment by gandhis1** [comment]
> For your problem, is it possible to use ParamSpec?

It certainly is possible - as I noted above, using `ParamSpec` and `Concatenate` to do this works as expected in Pyright. It does not work in MyPy. Does MyPy have robust `ParamSpec`/`Concatenate` support? It was difficult to ascertain this from the various issues/PRs in this repo.

Making a separate sub-class annotation for every variant of arguments is not really a practical solution for me. This is a decorator that needs to be usable by anyone, anywhere, as long as their function accepts an `int` first argument and returns a sub-class of `A`. All other arguments to the decorated function are passed down verbatim. My real example uses totally different types and has a real purpose behind it, the code was just a minimal test case that paraphrased the issue.

**Comment by NeilGirdhar** [comment]
> This is a decorator that needs to be usable by anyone, anywhere, as long as their function accepts an int first argument 

In the case of annotating a decorator, you should use `ParamSpec`.  I think MyPy support is advancing quickly, but it might not be complete yet.  You can track its progress using its topic: https://github.com/python/mypy/issues?q=is%3Aissue+is%3Aopen+paramspec+label%3Atopic-paramspec.

Using `PreFuncExtra` is just a design pattern to avoid LSP errors and the accompanying design problems in your own class hierarchy.
