### ISSUE TITLE
Can't make partial stub selectively override typeshed

### ISSUE THREAD

**Issue by AmesCornish** [python/mypy#5880]
This is a bug or my misunderstanding of the usage.  I'm trying to create a [partial stub](https://www.python.org/dev/peps/pep-0561/#partial-stub-packages) according to PEP 561.  I'm expecting mypy to use my local stub for some functions, and then fall back to typeshed for the rest.

My code:
```
import os

cwd = os.getcwd()
pid = os.getpid()
```
My local stubs:
```
stubs/
└── os
    ├── __init__.pyi
    └── py.typed
```
\_\_init__.pyi:
```
from typing import NewType

Path = NewType('Path', str)
FullPath = NewType('FullPath', Path)

def getcwd() -> FullPath: ...
```
py.typed:
```
partial

```
What I got:
```
$ MYPYPATH=./stubs/ mypy mycode.py 
mycode.py:4: error: Module has no attribute "getpid"
```
I was hoping for no errors -- `getpid` should be looked up in typeshed.

FYI, my use case is to get mypy to flag where I've used a plain str for a (possible relative) pathname, and ensure all relative paths are converted to full paths, because getcwd() and chdir() are not thread-safe.  I don't want to have to re-stub all of the os module.

Python 3.6.6
mypy 0.641
no mypy.ini

Thanks for your help!

**Comment by ilevkivskyi** [comment]
@ethanhs is probably the best person to ask about this.

**Comment by gvanrossum** [comment]
PEP 561's "partial" feature refers to having a stubs package with stubs for certain submodules missing. It will then fall back to the corresponding module in the "real" package. But it only does this at the file level, not at the function level. We have no intention to support the latter, so I'm closing this issue.
