### ISSUE TITLE
Some unioned types in Sequence disappears in error message

### ISSUE THREAD

**Issue by okapies** [python/mypy#5886]
I tried to encode a `Sequence` which contains an `Union` type as an element:

```python
from typing import Sequence, SupportsInt, Tuple, Union

IntLike = Union[str, bytes, SupportsInt]

ShapeLike = Sequence[Union[int, IntLike]]

def f(a: int, b: ShapeLike) -> int:
    return a + sum([int(v) for v in b])

print(f(1, [None]))  # None type is mismatched
```

But it claims that the expected type is an `Union[str, SupportsInt]` not a `Union[int, str, bytes, SupportsInt]`.

```
$ mypy foo.py 
foo.py:10: error: List item 0 has incompatible type "None"; expected "Union[str, SupportsInt]"
```

It seems that `SupportsInt` overrides `int` and `bytes` incorrectly:

```python
IntLike = Union[str, bytes]
```

```
work/bar.py:10: error: List item 0 has incompatible type "None"; expected "Union[int, str, bytes]"
```

**Comment by ilevkivskyi** [comment]
> It seems that `SupportsInt` overrides `int` and `bytes` incorrectly

What do you mean by incorrectly? Both `int` and `bytes` are subtypes of `SupportsInt` (at least according to typeshed), so there is no point in keeping the former in the union.

**Comment by gvanrossum** [comment]
I'd say this is definitely surprising (I had to experiment to remind myself
how bytes supports int :-). I wonder if union normalization should not
collapse a class and a protocol supported by that class?

**Comment by okapies** [comment]
Sorry, I misunderstood that `int` doesn't have `__int__`. But `bytes` actually doesn't have `__int__`:

```python
>>> dir(bytes)
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'center', 'count', 'decode', 'endswith', 'expandtabs', 'find', 'fromhex', 'hex', 'index', 'isalnum', 'isalpha', 'isdigit', 'islower', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
```

And if I remove `Sequence` from `ShapeLike`, it produces the following error including `int` and `bytes`. I think it is an inconsistent behavior.

```
from typing import SupportsInt, Tuple, Union

IntLike = Union[str, bytes, SupportsInt]

ShapeLike = Union[int, IntLike]

def f(a: int, b: ShapeLike) -> int:
    return a + int(b)

print(f(1, [None]))
```
```
$ mypy work/bar.py 
work/bar.py:10: error: Argument 2 to "f" has incompatible type "List[None]"; expected "Union[int, str, bytes, SupportsInt]"
```

And I saw `builtins.py` in typeshed. It specifies it has a signature `x: Union[str, bytes, SupportsInt]` but it is weird if `bytes` is a subtype of `SupportsInt`.

https://github.com/python/typeshed/blob/1a42a2c3eafbd582462962c664bf09b2fea7f10a/stdlib/3/builtins.pyi#L108-L112

**Comment by AlexWaygood** [comment]
The [error message on 0.941](https://mypy-play.net/?mypy=latest&python=3.10&gist=7bae4301ac6dc454737b9cf740facc9c) is now:

```
List item 0 has incompatible type "None"; expected "Union[str, bytes, SupportsInt]"
```

This seems correct to me, so I'm closing this issue.
