### ISSUE TITLE
"StreamHandler" has no attribute "setStream"; maybe "stream"?

### ISSUE THREAD

**Issue by ferenczy** [python/mypy#5888]
I believe I have found a bug. Or I'm doing something wrong. Please let me know if it rather should be reported in the [typeshed tracker](https://github.com/python/typeshed/issues).

Consider this very simple piece of code:

    import logging
    import sys

    handler = logging.StreamHandler()
    handler.setStream(sys.stdout)

The code itself is working properly. But mypy is complaining that `StreamHandler` has no attribute `setStream`:

> error: "StreamHandler" has no attribute "setStream"; maybe "stream"?

The class `StreamHandler`, defined in the module `logging` (file `lib/logging/__init__.py`), has the method `setStream`, of course.

I'm running mypy with all settings default simply by running `mypy logging_test.py`.

Am I doing anything wrong or is it a bug of mypy?

Python version: 3.7.0
mypy version: 0.610 (and it behaves the same when installed from `master`)

**Comment by gvanrossum** [comment]
Please report this in the typeshed tracker -- if you do a little investigation there you'll probably find that this method is missing there. However before going there I'd upgrade to mypy 0.641 -- perhaps it's been fixed.
