### ISSUE TITLE
Weird type error with asyncio.as_completed and function declaration

### ISSUE THREAD

**Issue by Summon528** [python/mypy#5889]
I have a piece of code like this
``` python
import asyncio
from typing import List


def func() -> None:
    aws: List = [asyncio.sleep(1)]
    for i in asyncio.as_completed(aws):
        await i


func()
```
The peice of code run fine, however mypy tells me  
`> mypy test.py`
 `test.py:8: error: Incompatible types in "await" (actual type "Generator[Any, None, Any]", expected type "Awaitable[Any]")`

The weird thing is, if I remove the `-> None` part from the code, mypy will report no error.
```python
import asyncio
from typing import List


def func():
    aws: List = [asyncio.sleep(1)]
    for i in asyncio.as_completed(aws):
        await i


func()
```

Environment information
`Python 3.7.1`
`mypy 0.641`
`Windows 10`

**Comment by ilevkivskyi** [comment]
This not a mypy issue, but likely an issue in typeshed. This function is annotated as:
```python
def as_completed(fs: Sequence[_FutureT[_T]], *, loop: AbstractEventLoop = ...,
                 timeout: Optional[float] = ...) -> Iterator[Generator[Any, None, _T]]: ...
``` 
So mypy gives an error since you cannot await a generator, if the function actually returns an iterable of awaitables, please open an issue on typeshed (or better4 just make a PR).
