### ISSUE TITLE
Add integration tests for daemon

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#5891]
Currently we only have unit tests for fine grained mode, but no integration tests for the daemon itself. This is in particular important for `dmypy run` that has some non-trivial restart logic.

Related https://github.com/python/mypy/issues/5002

**Comment by gvanrossum** [comment]
If you want me to I can give this a shot.

**Comment by ilevkivskyi** [comment]
> If you want me to I can give this a shot.

Thanks! This would be great.

**Comment by gvanrossum** [comment]
I now have a simple framework. Suggestions for more tests would be welcome.
