### ISSUE TITLE
strange behavior while validating lists of subtypes

### ISSUE THREAD

**Issue by kurtgn** [python/mypy#5896]
I have a generic class and several subclasses of this class:

    from typing import List
    
    
    class GenericMessage:
    
        """Generic message class with common methods"""
    
        def display_text(self):
            print('message text')
    
    
    class TextMessage(GenericMessage):
        pass
    
    
    class ImageMessage(GenericMessage):
        pass
    
    
I want to create a function that iterates over the instances of subclasses firing a common method for all instances (defined in a parent class):

    def display_message_texts(messages: List[GenericMessage]) -> None:
        for message in messages:
            message.display_text()
    
    
    same_messages = [
        TextMessage(),
        TextMessage()
    ]
    display_message_texts(same_messages)
    
    varying_messages = [
        TextMessage(),
        ImageMessage()
    ]
    
    display_message_texts(varying_messages)

So, when typechecking, `mypy` errors at `display_message_texts(same_messages)` but does not do so at `display_message_texts(varying_messages)`.

the error message is:

    _devtools/get_orphan_nodes.py:29: error: Argument 1 to "display_message_texts" has incompatible type "List[TextMessage]"; expected "List[GenericMessage]"
    _devtools/get_orphan_nodes.py:29: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
    _devtools/get_orphan_nodes.py:29: note: Consider using "Sequence" instead, which is covariant

Okay, I get it about the covariance; but why does it warn about it only in one case and not the other?

**Comment by ilevkivskyi** [comment]
> but why does it warn about it only in one case and not the other?

Why should it? For `varying_messages` mypy infers the list of a common most derived base (a.k.a. join), which is exactly what the function accepts.

There is of course an eternal question of inferring union vs join, but this issue adds nothing new to the table. For future, in such cases it is better to first ask a question on Gitter, before opening an issue.
