### ISSUE TITLE
Add conversion from Python AST to MyPy AST

### ISSUE THREAD

**Issue by kirbyfan64** [python/mypy#590]
This could be really neat and useful. For instance, one could add mypy support to [Hy](http://docs.hylang.org) with this.

It would also allow other linting tools to integrate with mypy.

**Comment by gvanrossum** [comment]
I don't think this will ever happen, so closing. However, note that @ddfisher is working on converting mypy to use (almost) the official Python ast (however, extracted into a separate 3rd party module and augmented to preserve `# type: ...` comments in the tree). (@ddfisher, is there an issue where this is being tracked?)

**Comment by ddfisher** [comment]
There is now!  See #1353.
