### ISSUE TITLE
MYPYPATH results in AssertionError: ImportedName(_collections.defaultdict)

### ISSUE THREAD

**Issue by astronouth7303** [python/mypy#5901]
If I leave something extra in `$MYPYPATH` (I'm not sure I understand what exactly), I get this error:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/main.py", line 92, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/build.py", line 155, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/build.py", line 204, in _build
    graph = dispatch(sources, manager)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/build.py", line 2172, in dispatch
    process_graph(graph, manager)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/build.py", line 2469, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/build.py", line 2582, in process_stale_scc
    manager.semantic_analyzer.add_builtin_aliases(typing_mod)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/semanal.py", line 3415, in add_builtin_aliases
    target = self.named_type_or_none(target_name, [])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/semanal.py", line 1369, in named_type_or_none
    assert isinstance(node, TypeInfo), node
AssertionError: ImportedName(_collections.defaultdict)
```

**Comment by gvanrossum** [comment]
Probably the extra thing you have in `$MYPYPATH` overrides a basic stdlib module (e.g. `typing`). We can't help you further unless you show the contents of `$MYPYPATH`.

**Comment by astronouth7303** [comment]
Ok, from my travis experiments:

* [`/home/travis/virtualenv/python3.6.3/lib/python3.6:/home/travis/build/ppb/pursuedpybear`](https://travis-ci.org/ppb/pursuedpybear/jobs/455884898)
* [`/home/travis/virtualenv/python3.6.3/lib/python3.6:/opt/python/3.6.3/lib/python3.6:/home/travis/build/ppb/pursuedpybear`](https://travis-ci.org/ppb/pursuedpybear/jobs/455883555)
* [`/home/travis/virtualenv/python3.6.3/lib/python3.6:/home/travis/build/ppb/pursuedpybear`](https://travis-ci.org/ppb/pursuedpybear/jobs/455881071)
* [`/home/travis/virtualenv/python3.6.3/lib/python3.6:/home/travis/virtualenv/python3.6.3/lib/python3.6/lib-dynload:/home/travis/build/ppb/pursuedpybear`](https://travis-ci.org/ppb/pursuedpybear/jobs/455879445) (Also [1](https://travis-ci.org/ppb/pursuedpybear/jobs/455879445))
* [`/home/travis/virtualenv/python3.6.3/lib/python36.zip:/home/travis/virtualenv/python3.6.3/lib/python3.6:/home/travis/virtualenv/python3.6.3/lib/python3.6/lib-dynload:/opt/python/3.6.3/lib/python3.6:/home/travis/build/ppb/pursuedpybear`](https://travis-ci.org/ppb/pursuedpybear/jobs/455875296)

These are insufficient, as mypy doesn't discover pip installed modules:
* [`/home/travis/build/ppb/pursuedpybear`](https://travis-ci.org/ppb/pursuedpybear/jobs/455882880) (Also [1](https://travis-ci.org/ppb/pursuedpybear/jobs/455882880) [2](https://travis-ci.org/ppb/pursuedpybear/jobs/455876609))
* (Unset)

**Comment by astronouth7303** [comment]
I was about to write a big long thing about how it's a library that I contribute to and I've been working very hard to make it happy with both subclassing and mypy.

And then I realized that none of that work had actually been released to pypi yet, so what travis and mypy are seeing is a completely unannotated library.

Would it be possible to distinguish between "This library exists, but has no annotations" and "No, sorry, it's just not here at all"? The error message implies the latter, when in this case, the former seems to have happened.

**Comment by ilevkivskyi** [comment]
> Would it be possible to distinguish between "This library exists, but has no annotations" and "No, sorry, it's just not here at all"? The error message implies the latter, when in this case, the former seems to have happened.

We already have an issue for a better error message https://github.com/python/mypy/issues/4542
