### ISSUE TITLE
Stubgen: Wrong placement of decorators for methods with instance field declarations

### ISSUE THREAD

**Issue by hoefling** [python/mypy#5903]
Consider the following snippet:

```python
class A:
    @property
    def x(self):
        self.y = 'y'
        return 'x'

class B:
    @property
    def x(self):
        return 'x'

    @x.setter
    def x(self, value):
        self.y = 'y'
```

The stub generated via `stubgen` contains:

```python

# Stubs for tests.m (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class A:
    @property
    y: str = ...
    def x(self): ...

class B:
    @property
    def x(self): ...
    @x.setter
    y: str = ...
    def x(self, value: Any) -> None: ...
```

Notice the instance field type declarations are being placed between the decorator and the function declaration lines.

I can reproduce this issue using the latest `mypy` installed from the `master` branch:
```sh
$ pip show mypy | grep Version
Version: 0.650+dev.9459c7544f9adedb509d92e211f300e573cb6844
```

**Comment by ilevkivskyi** [comment]
Oh yes, this is a weird bug, `stubgen` definitely needs more attention (and we are going to devote some time to it next month). Also you are welcome to submit a PR!

**Comment by BuongiornoTexas** [comment]
I think the following is either a symptom of the same bug or is closely related (and had me going in circles for a quite a while):

```python
from typing import Dict

class Circus:

    _db_config: Dict[str, str]

    @property
    def input_file(self) -> str:
        return self._db_config.setdefault("Input", "")

    @input_file.setter
    def input_file(self, value: str) -> None:
        self._db_config["Input"] = value

    @property
    def user_id(self) -> str:
        return self._db_config.setdefault("User", "")

    @user_id.setter
    def user_id(self, value: str) -> None:
        # the next line triggers useful side effects in my code.
        self.player_profile = "" 
        self._db_config["User"] = value

    @property
    def player_profile(self) -> str:
        return self._db_config.setdefault("Player", "")

    @player_profile.setter
    def player_profile(self, value: str) -> None:
        self._db_config["Player"] = value

    def __init__(self) -> None:
        self._db_config = dict()

        # this looks like a non-op, but triggers side effects in my code
        self.user_id = self.user_id

    def sell_cheese(self) -> None:
        self.input_file = 'test.xml'
```

Sorry for the long sample, but I'm not sure which parts are important (I'm pretty  new at python).

Stubgen yields:

```python
# Stubs for song_list_creator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Dict

class Circus:
    _db_config: Dict[str, str]
    @property
    def input_file(self) -> str: ...
    @input_file.setter
    def input_file(self, value: str) -> None: ...
    @property
    def user_id(self) -> str: ...
    @user_id.setter
    player_profile: str = ...
    def user_id(self, value: str) -> None: ...
    @property
    def player_profile(self) -> str: ...
    @player_profile.setter
    def player_profile(self, value: str) -> None: ...
    user_id: Any = ...
    def __init__(self) -> None: ...
    input_file: str = ...
    def sell_cheese(self) -> None: ...
```

I've got no problems with instance field types (declared), and I've also declared the property types. However, stubgen goes its own way and adds new declarations for the properties player_profile, user_id and Input_file as if they were instance fields. The same behaviour occurs if I delete all of the property type declarations (which is how I found the issue).

I'd offer to help resolve this, but I think I need quite a bit more experience before I could do anything useful.

**Comment by ilevkivskyi** [comment]
@BuongiornoTexas Yes, I think this is the same issue.

In general, I would expect this to be not hard to fix from the point of view of knowing mypy internals. But this will require a good knowledge of Python.

**Comment by aaalex5** [comment]
If @BuongiornoTexas is not interested in working on this issue, would it be possible for me to work on this issue? This would be a first time collaboration on this project for me.

**Comment by BuongiornoTexas** [comment]
@aaalex5 No objections from me! I'm going to busy with other things for a few weeks, but I'm happy to help with testing/review if it will be helpful.

**Comment by aaalex5** [comment]
@BuongiornoTexas Great thanks! I'll get right on it. I will inquire if/when I need some help.
