### ISSUE TITLE
Undefined name error when using late wildcard imports

### ISSUE THREAD

**Issue by IwoHerka** [python/mypy#5908]
Hello,

I've encountered a bug (or I think so) when using late wildcard imports. It can be reproduced as follows:

*file1.py*
```python
def foo() -> int:
    return bar()

from file2 import *
assert foo() == 1
```

*file2.py*
```python
def bar() -> int:
    return 1
```

This yields:
```bash
file1.py:2: error: Name 'bar' is not defined
```

Version with 
```python
from file2 import bar
```
works fine (i.e. no errors are thrown).

This version works too:
```python
from file2 import *

def foo() -> int:
    return bar()

assert foo() == 1
```

I'm using version `0.641` installed from PyPI. I encounter the same behaviour when installed from Git master (as of `2680c3`).

I'm not using any options (just `mypy file1.py`).

Python version is `3.6.6`.

**Comment by ilevkivskyi** [comment]
We are planning a major redesign of our semantic analyzer in next months that will likely solve this kind of issues. For now you can use the workarounds you found.

**Comment by JukkaL** [comment]
The underlying problem is that mypy currently doesn't support forward references to a star import. `from x import *` is processed at a later stage of analysis than other imports, which breaks forward references. Forward references to imported names in general are problematic at the moment though; #4687 is a related issue.

**Comment by arquolo** [comment]
Another bug with wildcard imports (typical code from `asyncio.__init__`):
```python
from .submodule import *
__all__ = submodule.__all__
```
Mypy `0.740` yields:
```file.py:2: error: Name `submodule` is not defined```

**Comment by msullivan** [comment]
Looks like this was fixed by the new semantic analyzer
