### ISSUE TITLE
Specify files/directories in `mypy.ini`

### ISSUE THREAD

**Issue by samuelhwilliams** [python/mypy#5909]
I'm posting this issue to gather some feedback around whether a feature I'd like would be accepted/well-received.

I'd like to be able to specify target files/directories as part of the `mypy.ini` config file, and I can't see a way to do this at the moment (if I'm missing something, hopefully this can be cleared up quickly 😄 ). This would, in my opinion, reduce the need to have a separate script that runs `mypy` with the correct arguments, as it should be easier to just rely on the settings in the config file.

I would propose something along the lines of a `files` key in the main `mypy` section, but I'm not sure if this is in line with how it works under the `special_opts` namespace. Open to any recommendation around the best section for this to sit in, if something else makes more sense.

Would a PR implementing this feature be merged/are there any reasons why this feature doesn't exist? I asked quickly in the `typing` slack and it wasn't shot down, so hoping to get more of a discussion here.

Cheers.

**Comment by gvanrossum** [comment]
You can’t expect a promise that your PR will be accepted. But a ‘files’
option in mypy.ini, only used when no files are given on the command line,
makes sense. Would it also include globbing?
-- 
--Guido (mobile)

**Comment by samuelhwilliams** [comment]
Wasn't expecting a promise, definitely - more just clarification that there wasn't a specific reason it *wouldn't* be accepted.

I'd intend to replicate the same treatment as the `files` argument on the command line (overridden by the command-line, as you say). The CLI does globbing, so yes, I would intend to make the config file do the same.

**Comment by gvanrossum** [comment]
Technically the CLI does no globbing,the shell does. (Except on Windows
IIRC.) But yes, this makes sense.
-- 
--Guido (mobile)

**Comment by samuelhwilliams** [comment]
Yep, I was a bit loose with my terminology there.

I will start work on putting a PR together.

Cheers.

**Comment by Michael0x2a** [comment]
I remembered this only recently, but we have a [`mypy_path`](https://mypy.readthedocs.io/en/stable/config_file.html#config-file-import-discovery-global) config file option that's intended to serve as a replacement for editing the MYPYPATH environment variable.

Would specifying the files you want to type check there solve your use case? If so, we should probably do a better job of documenting it. If not, it might at least serve as a good foundation for your PR.

**Comment by hmoravec** [comment]
@samuelhwilliams Any updates on the PR? E.g. Pytest has [similar functionality](https://docs.pytest.org/en/latest/reference.html#confval-testpaths) and it would be very convenient to have in Mypy too.

**Comment by gvanrossum** [comment]
I used to think this to be a silly feature, but I realize it’s actually pretty useful. Maybe someone else can create a PR.

**Comment by samuelhwilliams** [comment]
I dropped the ball on this. Sorry. I'll start looking at doing this again now.

**Comment by samuelhwilliams** [comment]
^ Did not realise it would do that 🤦‍♂️ Regardless; PR is up now. Hopefully it's not far off.
