### ISSUE TITLE
Can't redefine name imported from another module

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#591]
It should be possible to redefine a name imported from another module, at least in stubs. Currently mypy complains about the redefinition (at least often). We can treat this as an assignment and just verify that the types are compatible.

**Comment by gvanrossum** [comment]
(Another one related to #649.)

**Comment by JukkaL** [comment]
I couldn't easily come up with an example that would fail, so I'm closing this. If some special case is still failing we can create a separate issue about that special case.

**Comment by DanAlbert** [comment]
Actually after commenting I see the case I'm running into is slightly different:

```python
try:
    from rich.progress import TaskID

    def foo(task_id: TaskID) -> None:
        ...

except ModuleNotFoundError:
    def foo(task_id: int) -> None:
        ...
```

Which yields "All conditional function variants must have identical signatures", which is the same error, but possibly not the same problem.
