### ISSUE TITLE
`get_attribute_hook` for unknown attributes

### ISSUE THREAD

**Issue by mkurnikov** [python/mypy#5910]
How do I intercept type inference of the `settings.ROOT_DIR` here? 
```
from django.conf import settings
settings.ROOT_DIR
```

I wasn't able to get it working neither with `get_attribute_hook`, nor with others. `settings` is specified as 
```
# in django/conf/__init__.pyi
class LazySettings(object):
    pass
settings = LazySettings()
```

From the implementation, it looks like hooks's only called if attribute is present on the object (is a Var)
https://github.com/python/mypy/blob/master/mypy/checkmember.py#L280

Another solution for this problem could be to augment the AST with an additional settings dynamically somewhere in the plugin, but for that I need an initialization hook.

**Comment by ilevkivskyi** [comment]
You can stuff various dummy names in the class symbol table using `get_class_decorator_hook()`, `get_metaclass_hook()` and `get_base_class_hook()` (plus something in stubs). But I think it probably makes sense to call the hook in more cases there (e.g. if it comes from `__getattr__()` etc.)

**Comment by ilevkivskyi** [comment]
Fixed by https://github.com/python/mypy/pull/6371
