### ISSUE TITLE
0.641 can't find my python27 install but 0.630 can

### ISSUE THREAD

**Issue by remdragon** [python/mypy#5912]
* Are you reporting a bug, or opening a feature request?

```
bug
```

* What is the actual behavior/output?

```
mypy: error: failed to find a Python executable matching version (2, 7), perhaps try --python-executable, or --no-site-packages?
```

* What is the behavior/output you expect?

```
it should be able to find my python27 install just like the 0.630 version can.
```

* What are the versions of mypy and Python you are using?
```
already reported the mypy versions above. 0.630 works find, 0.641 has problems
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
```
Do you see the same issue after installing mypy from Git master?
```
I uninstalled mypy and ran the following:

python -m pip install -U git+git://github.com/python/mypy.git

mypy version now reported as:

mypy 0.650+dev.2680c3fb4582f3eb8f823208014a4b58bc1f734b

and it is still failing to find my python 27 install.
```

* What are the mypy flags you are using? (For example --strict-optional)
```
--ignore-missing-imports --strict --py2
```

**Comment by gvanrossum** [comment]
@ethanhs Do you have any idea what could cause this?

**Comment by ethanhs** [comment]
Oops, I seem to have missed that message. I believe this was fixed in https://github.com/python/mypy/pull/5619, @remdragon let me know if this does not work with 0.650.
