### ISSUE TITLE
AsyncIterator has no attribute "asend"

### ISSUE THREAD

**Issue by xNinjaKittyx** [python/mypy#5921]
I have an asynchronous iterator using the `asend()` call from Asynchronous Iterators in [PEP 525](https://www.python.org/dev/peps/pep-0525/)

I'm using `Optional[AsyncIterator]`, but it reports the following:
`error: Item "AsyncIterator[Any]" of "Optional[AsyncIterator[Any]]" has no attribute "asend"`

Unless I'm incorrect in using the AsyncIterator Type, AsyncIterators should have an asend() attribute.

Python Version: 3.6.6
mypy Version: 0.641

**Comment by ilevkivskyi** [comment]
No, only `AsyncGenerator` has `asend()`.
