### ISSUE TITLE
Update travis ci script to check all module stubs

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#594]
Currently the `travis.sh` script only checks some package stubs, which is bad. It should look for all modules within packages under `stubs/`.

**Comment by o11c** [comment]
Handled in #721

**Comment by JukkaL** [comment]
The new location for stubs is `typeshed/`. We now check all Python 3 stubs, but we still don't check Python 2 stub files.

**Comment by gvanrossum** [comment]
Actually this is as fixed as it can be -- in ddf43e3bdbc72a6cb22cec44b50af9715ea8fea1 (in typeshed) I made several fixes to the runtests.py script. The only thing keeping us from perfection is that the sqlalchemy stubs are quite broken.

**Comment by gvanrossum** [comment]
To be clear, the typeshed's .travis.yml file now tests all stubs against mypy's master/HEAD, running mypy itself with Python 3.5, but passing --python-version flags values in [2.7, 3.2, 3.3, 3.4, 3.5].
