### ISSUE TITLE
Tabs replaced by '?' in HTML/XML reports

### ISSUE THREAD

**Issue by mthuurne** [python/mypy#5942]
When I generate an HTML or XML report with mypy, in the annotated code all tabs have been replaced by question marks. It is not just the web browser showing a question mark for an unknown character: there are literal question marks (ASCII 63) in the output.

The progress message says HTML reports are generated via XSLT, so I guess the HTML reports inherit this behavior from the XML reports.

I know that PEP8 states spaces should be used for new code, but it would be nice if mypy could be used on legacy code bases as well.

I'm using a mypy dev snapshot (0.650+) on Python 3.6.5.

**Comment by mthuurne** [comment]
PR created: #5945

**Comment by gvanrossum** [comment]
Thanks for the fix! (Next time put "Fixes #5942" in the commit message, instead of in the title.)
