### ISSUE TITLE
Combination of collections where element types are compatible only works left-to-right

### ISSUE THREAD

**Issue by PeterJCLaw** [python/mypy#5948]
Currently mypy supports combining a list of integers to a list of floats:
``` python
y = [float('inf')] + list(range(10))
```
and the resulting type is `builtins.list[builtins.float*]`.

It would be great if this worked with the collections in the reverse order:
``` python
x = list(range(10)) + [float('inf')]
```
Currently the latter errors with `List item 0 has incompatible type "float"; expected "int"`.

I'm not sure whether this is a limitation of general support for combining generic collections, or there's something special for extending lists of floats by lists of integers.

Either way, it might also be good if this was a general thing for all collections of compatible generics.

Currently I'm using a `cast` so that my code checks ok, though I'd like to be able to remove that.

**Comment by ilevkivskyi** [comment]
We actually already have a fix for this, see https://github.com/python/mypy/pull/5873, but it triggers another issues.

@JukkaL will you have time to look if there is a simple solution fo this?

**Comment by PeterJCLaw** [comment]
Aha, thanks. I missed that. I'm happy to consider this a duplicate of https://github.com/python/mypy/issues/5492.
