### ISSUE TITLE
Improve message when function is missing return type

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#5952]
If a function takes no arguments (or only `self`) and `--disallow-untyped-defs` is enabled, the error message "Function is missing a type annotation" is not very helpful. Here's an idea for a better message:

```
foo.py:2: error: Function must have a return type annotation ('disallow_untyped_defs' enabled)
foo.py:2: note: Use "-> None" if function does not return a value
```

The error message could be further specialized for `__init__`.

See #5943 for a related issue.

**Comment by allisonking** [comment]
I'll work on this one!
