### ISSUE TITLE
Bogus "Function is missing a type annotation for one or more arguments" with attrs

### ISSUE THREAD

**Issue by The-Compiler** [python/mypy#5954]
When checking this file with mypy (0.641 or git master) and `--disallow-incomplete-defs`:

```python
import attr

@attr.s
class A:
    a = attr.ib()
```

I get an unexpected:

```
at.py:3: error: Function is missing a type annotation for one or more arguments
```

(line 3 being the `@attr.s` decorator). If I'm interpreting [what `--disallow-incomplete-defs` does](https://mypy.readthedocs.io/en/latest/command_line.html#untyped-definitions-and-calls) correctly, it should only warn if there's a partial type annotation (as opposed to none at all, which `--disallow-untyped-defs` would warn about).

Also, the error message is confusing - I don't define a function at all there. With `--show-error-context`, it says:

```
at.py: note: In member "__init__" of class "A":
```

FWIW, I (finally) started using mypy with a rather big project ([qutebrowser](https://qutebrowser.org/)) and I'm quite happy with it so far - the approach of gradual typing and the awesome documentation make it very easy to get a benefit without having to annotate the entire codebase at once.

**Comment by euresti** [comment]
Hmm. The issue here is that the generated `__init__` method **is** only partially annotated.  Because it  looks like this:

```
def __init__(self, a) -> None:
   ...
```

I'm not sure how one would fix the plugin to work around this.  (Is this also an issue with `dataclasses`?)

**Comment by euresti** [comment]
Oh and feel free to add the attrs label to this bug.

**Comment by ilevkivskyi** [comment]
OK, I think this line in `plugins/attrs.py` may cause it:
```python
init_type = AnyType(TypeOfAny.unannotated)
```

**Comment by ilevkivskyi** [comment]
Hm, but the actual problem is that `-> None` is always set. So it is actually not so trivial decision (sorry for thinking out loud).

**Comment by ilevkivskyi** [comment]
Maybe conditionally use `AnyType(TypeOfAny.unannotated)` for the return of `__init__` if none of the arguments is annotated?

**Comment by The-Compiler** [comment]
Just took a quick look at the plugin, and like you say, I see various solutions:

- Using something other than `TypeOfAny.unannotated` for the generated arguments - perhaps `TypeOfAny.implementation_artifact`? ("Does this Any come from an implementation limitation/bug?")
- Using `AnyType(TypeOfAny.unannotated)` for the return if no arguments are annotated (like you say) - after all, the return type annotation for `__init__` probably isn't really significant anyways (i.e., the things mypy checks don't get any worse by this being `Any` rather than `None`).
- Somehow suppressing that error message in this case, if possible.

Though I wonder if the same will also happen for more generated methods (say, `__lt__` and such) after fixing it for `__init__`.

**Comment by euresti** [comment]
The first one is not really an option, because the following code is unannotated and we don't want it to be magically marked as fully annotated:
```
import attr

@attr.s
class A:
    a = attr.ib()
```

Whereas this is fully annotated.
```
import attr

@attr.s
class A:
    a: Any = attr.ib()
```

It's the difference between saying
```
def foo(a):
   pass
```
and 
```
def foo(a: Any) -> None:
   pass
```

I don't know if I'll have time until December to work on this though.

**Comment by ethanhs** [comment]
>The first one is not really an option, because the following code is unannotated and we don't want it to be magically marked as fully annotated

Perhaps this is okay if the plugin tells the user that the class attribute is unannotated? It seems that would make understanding the error a lot easier.

**Comment by The-Compiler** [comment]
> > The first one is not really an option, because the following code is unannotated and we don't want it to be magically marked as fully annotated
> 
> Perhaps this is okay if the plugin tells the user that the class attribute is unannotated? It seems that would make understanding the error a lot easier to understand.

That's already done with `--disallow-untyped-defs`:

```
at.py: note: In member "__init__" of class "A":
at.py:3: error: Function is missing a type annotation for one or more arguments
at.py: note: In class "A":
at.py:5: error: Need type annotation for 'a'
```

but with `--disallow-incomplete-defs` and no annotations at all, I'd expect no warning/error.

**Comment by euresti** [comment]
Actually I was wrong.  The actual message comes from this check:

```
        def is_unannotated_any(t: Type) -> bool:
            return isinstance(t, AnyType) and t.type_of_any == TypeOfAny.unannotated

        has_explicit_annotation = (isinstance(fdef.type, CallableType)
                                   and any(not is_unannotated_any(t)
                                           for t in fdef.type.arg_types + [fdef.type.ret_type]))
```

So the actual problem is that I'm technically generating
```
def __init__(self, foo: Any(unannotated)) -> None:
    ...
```

(You can't set the return value to anything other than `None` or you trigger another error.)

The simple solution is to set the `type_annotation` of the args to `AnyType(TypeOfAny.implementation_artifact)` if they are all unannotated, but that feels weird.

The correct solution is to generate the following code: 
```
def __init__(self, foo):
   ...
```
which means `fdef.type` is `None` and `arg.type_annotation` is `None`.  That does require a bit more changes to the `add_method` method.

**Comment by josh-theorem** [comment]
Is this still being looked at?

**Comment by ilevkivskyi** [comment]
AFAICT, no. I think it is OK, if you want to try fixing it. Otherwise, hopefully @euresti will have time to do this at some point.

**Comment by MatrixManAtYrService** [comment]
@euresti asked, four years ago:
> I'm not sure how one would fix the plugin to work around this. (Is this also an issue with dataclasses?)

Today I'm here to say: yes, it is.  I couldn't replicate it when I tried to simplify the file, but mypy says:

> src/turbulence/resources/abstract.py:47: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]

about this file: 

https://gist.github.com/MatrixManAtYrService/cd21c1e1f4375c6a4affeb84d9dbcf64#file-abstract-py-L47
