### ISSUE TITLE
Small bug: `if` expression doesn't short circuit for --always-false/--always-true

### ISSUE THREAD

**Issue by samertm** [python/mypy#5963]
`if` expressions don't correctly short-circuit for variables that are set as "always true/false" constants with the `--always-false` and `--always-true` flags, even though they work for other "always true/false" conditions, like ones that use `sys.platform`.

Here's a test case:
```
# flags: --platform linux --always-false IS_THING
import sys

if sys.platform == 'darwin':
    darwin_only = 1

if sys.platform == 'darwin' and darwin_only:
    # This works because `sys.platform == 'darwin'` is inferred as `ALWAYS_FALSE`, and
    # that causes the short-circuit logic to run.
    pass

IS_THING = False

if IS_THING:
    thing_only = 1

if IS_THING and thing_only:
    # Blows up with the error `error: Name 'thing_only' is not defined` since
    # IS_THING is inferred as `MYPY_FALSE`, so the short-circuiting logic
    # doesn't run
    pass
```

The short-circuit logic is scattered throughout the codebase, but here's an [example](https://github.com/python/mypy/blob/3c311c24323d20bbf7e13084ba16bcb99e8934d7/mypy/semanal.py#L3074):

```
        if expr.op in ('and', 'or'):
            inferred = infer_condition_value(expr.left, self.options)
            if ((inferred == ALWAYS_FALSE and expr.op == 'and') or
                    (inferred == ALWAYS_TRUE and expr.op == 'or')):
                expr.right_unreachable = True
                return
            elif ((inferred == ALWAYS_TRUE and expr.op == 'and') or
                    (inferred == ALWAYS_FALSE and expr.op == 'or')):
                expr.right_always = True
```

Notice that it checks for ALWAYS_FALSE and ALWAYS_TRUE, but not MYPY_FALSE or MYPY_TRUE>

And the --always-true/false flags are translated to MYPY_TRUE/FALSE [here](https://github.com/python/mypy/blob/3c311c24323d20bbf7e13084ba16bcb99e8934d7/mypy/semanal.py#L3856).

There are two potential fixes:

1. Include two MYPY_TRUE/FALSE in all of the `if` short circuit checks.

I think that works, because even when using the MYPY variable directly, it's probably surprising that it doesn't short-circuit.

2. Use ALWAYS_TRUE/FALSE with the --always-true/false flags instead of MYPY_TRUE/FALSE.

@gvanrossum might have more context on why the --always-* flags use the MYPY_* constants instead of the ALWAYS_* constants, since he added them. FWIW, using ALWAYS_* makes more semantic sense to me, since I'm using the flags for variables that will have the same value at runtime. (e.g. I'm setting `--always-true=IS_WINDOWS` to typecheck my app for windows, so IS_WINDOWS will also be true at runtime.) That's distinct from how `MYPY` works, where it's always False at runtime and always True for typechecking.

Thoughts?

* What are the versions of mypy and Python you are using?

python 3.5.2, latest master for mypy

**Comment by samertm** [comment]
I think this is the only other place where there's a distinction between MYPY_TRUE and ALWAYS_TRUE:
https://github.com/python/mypy/blob/3c311c24323d20bbf7e13084ba16bcb99e8934d7/mypy/semanal.py#L3792

It looks like we use it to set a different priority for mypy-only imports.

**Comment by gvanrossum** [comment]
Huh, how quickly we forget. :-)

It sounds like a fix might be straightforward: just make sure both are tested everywhere else.
