### ISSUE TITLE
Type ignore comment has no effect after argument type comment

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#5967]
This program generates an error on the first line even though there is a `# type: ignore` comment:

```py
def f(x,  # type: x  # type: ignore
      ):
    # type: (...) -> None
    pass
```

Similarly, this generates an error even though it shouldn't:

```py
def f(x=y,  # type: int  # type: ignore  # Name 'y' not defined
      ):
    # type: (...) -> None
    pass
```

**Comment by ethanhs** [comment]
For your first example, here is the AST as parsed by typed_ast:
```
Module(
    body=[
        FunctionDef(
            lineno=2,
            col_offset=0,
            name='f',
            args=arguments(
                args=[arg(lineno=2, col_offset=6, arg='x', annotation=None, type_comment='x  # type: ignore')],
                vararg=None,
                kwonlyargs=[],
                kw_defaults=[],
                kwarg=None,
                defaults=[],
            ),
            body=[Pass(lineno=5, col_offset=4)],
            decorator_list=[],
            returns=None,
            type_comment='(...) -> None',
        ),
    ],
    type_ignores=[],
)
```
Notice the `type_comment='x  # type: ignore'`.
We generally ignore comments after the first type comment, but it should be easy to make an exception for `#\s+type:\s+ignore` and add that line to the list of lines to ignore.

**Comment by JukkaL** [comment]
This happens also with variable type comments:

```py
x = 1 # type: str # type: ignore
```

**Comment by JukkaL** [comment]
Increasing priority since it's not at all obvious how to work this around in general.

**Comment by ethanhs** [comment]
I believe I have hacked together a general implementation in fastparse. I just do a regex search for a `# type: ignore` when parsing the type comment and keep track of these additional type ignores in the Ast converter class, then add them to the set of ignores when visiting the `Module` node.

Though this likely should be implemented in typed_ast itself...
