### ISSUE TITLE
variable types are not updated after null value

### ISSUE THREAD

**Issue by boompig** [python/mypy#5969]
I am getting an error running `mypy` on the code below:

```
import smtplib
import logging

class Foo:
    def __init__(self) -> None:
        self._server = None

    @property
    def server(self) -> smtplib.SMTP:
        # perform server connection only once
        if self._server is None:
            self._server = smtplib.SMTP("smtp.gmail.com", 587)  # type: smtplib.SMTP
        return self._server
```

> example.py:12: error: Incompatible types in assignment (expression has type "SMTP", variable has type "None")
> example.py:13: error: Incompatible return value type (got "None", expected "SMTP")

using mypy 0.630, Python 3.6.5

If I change line 5 to `def __init__(self):` (take out the `-> None`), the error disappears. The type annotation in comments on line 12 does not help, and the error persists without it.

What's going on?

**EDIT** just tested with mypy 0.641 and get same issue

**Comment by ilevkivskyi** [comment]
If you remove `-> None` on `__init__` it becomes unannotated, and therefore everything in it becomes `Any`.

To fix the error, add an annotation for `self._server` in `__init__`, currently it is inferred as `None`.
