### ISSUE TITLE
Support copying a Mapping to a MutableMapping

### ISSUE THREAD

**Issue by mcintyre94** [python/mypy#5970]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
Feature request

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

I'd like to be able to write the following function, which would give me a guarantee that I can't modify the input Mapping - but allow me to modify a copy of it.

```
def modify_a_copy(some_map: Mapping):
    some_copy: MutableMapping = copy.deepcopy(some_map)
    some_copy['key'] = 'value'
    return some_copy
```

* What is the actual behavior/output?
`error: Argument 1 to "deepcopy" has incompatible type "Mapping[Any, Any]"; expected "MutableMapping[Any, Any]"`

* What is the behavior/output you expect?
To succeed, since I haven't and won't modify the original `some_map`, only `some_copy` which I've typed as MutableMapping

* What are the versions of mypy and Python you are using?
mypy 0.641
Python 3.7.0

* What are the mypy flags you are using? (For example --strict-optional)
Only

```
[mypy]
follow_imports=skip
```

**Comment by JelleZijlstra** [comment]
I think you should use `some_copy = dict(some_map)` instead. `Mapping` is an immutable type, and copying it does not magically make it mutable. (In practice, of course, it is most likely a `dict` instance and therefore mutable, but it could also be some user-defined mapping type that is really immutable.)

**Comment by ilevkivskyi** [comment]
Yes, the original code is not type safe, use the recipe the Jelle suggested instead.
