### ISSUE TITLE
Expand on 'Cannot find module named' error

### ISSUE THREAD

**Issue by jewelpit** [python/mypy#5986]
* **Are you reporting a bug, or opening a feature request?**
  Feature request?  I'd like to change the text of an error message, and I'm willing to do the work myself.
* **Minimal repro**
```
package/
  handlers/
      __init__.py
      pics.py
  __init__.py
  main.py
```

In `main.py`:
```
import handler.pics
```

Then running `mypy --strict -p package`.
* **What is the actual behavior/output?**
  `Cannot find module named 'handlers.pics'`
* What is the behavior/output you expect?
  `Cannot find module named 'handlers.pics'. If you're doing a relative import, prefix it with your package name`
  (or something)
* **What are the versions of mypy and Python you are using?**
  mypy 0.641, Python 3.6.7
* **What are the mypy flags you are using? (For example --strict-optional)**
  `--strict`

I had a relative module import that wasn't preceded by my package name, and since Python would still happily import the module and run the program, I didn't realize that that wasn't valid import syntax.  When I tried to run mypy over my package, it would complain that it couldn't find the module, since I had written `import handler.pics` instead of `import package.handler.pics`.

I'm okay with this behavior, especially after finding out that it's a best practice (it's been a **long** time since I've written Python, ha), but I do wish the error message pointed out that it could be the reason that the module couldn't be found.  I was having a lot of trouble googling for an answer to this problem, since all the results I found were for people who were having trouble finding third party libraries rather than modules inside their package.

I think there might be another area where mypy gives more info on the error (I think it mentions a MYPYPATH?), so if you think that would be a more appropriate place to put it that would make sense.

**Comment by gonzaloamadio** [comment]
I have same error. But I could not make it work.

My layout

```
~/Playground/classroom/
    __init__.py
    app/
        quizzes.py
        utils.py
        __init__.py

```
        
Inside quizzes.py I have `from classroom.app.utils import myfoo`

And when I run (inside classroom folder) `$ mypy app/quizzes.py`

I got the error `app/quizzes.py:13: error: Cannot find module named 'classroom.app.utils'`

**Comment by hauntsaninja** [comment]
This error is very stale, a lot has changed
