### ISSUE TITLE
Add things missing from Python 2 builtins stubs

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#600]
These are missing from Python 2 builtins stubs:

```
BufferError
Ellipsis
apply
basestring
buffer
coerce
compile
copyright
credits
eval
execfile
file
help
license
reduce
```

**EDIT:** Add `file`

**Comment by ecprice** [comment]
also 'file', which is also missing from python 3 builtins stubs.

**Comment by o11c** [comment]
`file` doesn't exist in Python3. Instead, all the classes are in the `io` module.

**Comment by JukkaL** [comment]
`file` is missing from Python 2 builtin stubs, bowever.
