### ISSUE TITLE
Using mypy to test/compare stub package/distribution?

### ISSUE THREAD

**Issue by wcooley** [python/mypy#6008]
* _Are you reporting a bug, or opening a feature request?_
Uncertain; it's a bug if I'm trying to do something that should work or a feature request if I'm trying to do something unexpected. Or maybe it's a support request, to tell me what I'm doing wrong or if it's even possible to do what I am trying to do?
* _What are the versions of mypy and Python you are using?_
  mypy: 0.641
  Python: 3.6.5 built with pyenv on macOS 10.13.6
  _Do you see the same issue after installing mypy from Git master?_
  Yes, I installed "0.650+dev.2b1bb6e..." and tried cases 1.i and 1.ii below. Same result.
* _Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro._
  The library and stub repos are linked below; I am using the current _master_ of each.
* _What is the actual behavior/output?_
* _What is the behavior/output you expect?_
* _What are the mypy flags you are using? (For example --strict-optional)_

I am attempting to make a [stub package & distribution](wcooley/python-boltons-stubs) for the [boltons](mahmoud/boltons) library. It's working for regular client code that uses a module from _boltons_ (see below), but I would like to use _mypy_ to audit the _boltons_ package itself to tell me what stubs are lacking. **Should I be able to do this?**

### Baseline (what works)

I can build and install the dist as _boltons-stubs_ as package _boltons-stubs_.

I can write a test script with the wrong type for a class from a boltons module:
```python
from boltons.cacheutils import LRU
LRU(max_size=10, values={'one': 1, 'two': 2},
        on_miss=False)  # on_miss declared Optional[Callable[[str], int]]
```
And _mypy_ produces the error I expect:
```
$ mypy client-test/test.py
client-test/test.py:3: error: Argument "on_miss" to "LRU" has incompatible type "bool"; expected "Optional[Callable[[str], int]]"
```
And then fix it and get no error, as expected.

### What I have tried that does not work

It's a little hard to enumerate exactly every combination of parameters and setups that I've tried; if there is one that _should_ and _does_ work that I have not tried, then maybe it should be documented more clearly or the CLI flags should be more obvious?

In general, I've tried CLI parameters:
  * with or without `--warn-incomplete-stub`.
  * with either `--strict` or `--disallow-untyped-defs`.
  * with `--show-error-context` (so I can see if my representative case of "Function is missing a type annotation" for `LRU.__init__` shows up or not without having to remember line numbers or check the source).
  * with `-v` or `-vvvv` or none.
  * with or without `--no-silence-site-packages`.

I get either no output or errors, including the following:
```
boltons/cacheutils.py: note: In member "__init__" of class "LRU":
boltons/cacheutils.py:107: error: Function is missing a type annotation
```

1. Installing both _boltons-stubs_ and _boltons_ into a virtualenv and running _mypy_ on _boltons_ (from a clean directory, so I am not accidentally picking up either in '.'):
    1. I get "Can't find package 'boltons'" if I run `mypy ... -p boltons`:
        ```
        $ cd /tmp; mypy --no-silence-site-packages --show-error-context --disallow-untyped-defs --warn-incomplete-stub -p boltons
        Can't find package 'boltons'
        ```
    1. I get no output when I run `mypy ... -m boltons.typeutils`.  The stub for `boltons.typeutils` is empty, so I know it is missing some declarations. If I examine the cache files `.mypy_cache/3.6/boltons/typeutils.{data,meta}.json`, it refers to the stub file in _path_, so I know it's seeing it:
        ```
        $ cd /tmp; mypy --no-silence-site-packages --show-error-context --disallow-untyped-defs --warn-incomplete-stub -m boltons.typeutils
        ```
    1. I get the following if I attempt to refer directly to the installed `boltons/cacheutils.py`:
        ```
        $ cd /tmp; mypy --no-silence-site-packages --show-error-context --disallow-untyped-defs --warn-incomplete-stub /my/virtualenv/python-boltons-stubs/lib/python3.6/site-packages/boltons/cacheutils.py
        /my/virtualenv/python-boltons-stubs/lib/python3.6/site-packages is in the PYTHONPATH. Please change directory so it is not.
        ```
2. Installing only _boltons-stubs_ and pointing _mypy_ at a working copy of the _boltons_ repo (I have to remove the latter from the former's _install_requires_):
    1. `mypy ... -m boltons.cacheutils`:
    ```
    $ cd ~/src/boltons; mypy --no-silence-site-packages --show-error-context --disallow-untyped-defs --warn-incomplete-stub -m boltons.cacheutils
    ...
    boltons/cacheutils.py: note: In member "__init__" of class "LRU":
    boltons/cacheutils.py:107: error: Function is missing a type annotation
    ...
    ```
    2. `mypy ... -p boltons`: Same as 2.i.
    3. `mypy ... boltons/cacheutils.py`: Same as 2.i.
3. Uninstall _boltons-stubs_ and _boltons_ and manually copy the _.pyi_ files into the _boltons_ source: Same as 2.i.
4. Symlink the _boltons-stubs_ package directory as _boltons_ and set `MYPYPATH` to the path: Same as 2.i.

**Comment by davidism** [comment]
I have been typing Werkzeug, and ran into this issue as well. I had to use a stub `pyi` file for one module, since `Generic` makes instantiation slow until Python 3.9. However, mypy now ignores the code and only considers the stub file. So I can't both type check the Werkzeug code and provide the benefits of generic types to users.

**Comment by hauntsaninja** [comment]
I think the original issue is somewhat covered by stubtest and davidism's issue is better represented by https://github.com/python/mypy/issues/5028, so closing
