### ISSUE TITLE
mypy is not looking inside Python's any()

### ISSUE THREAD

**Issue by alkamid** [python/mypy#6024]
(mypy-0.641, Python 3.6.7)

```python
from typing import Optional

def test_1(inp1: Optional[int] = None, inp2: Optional[int] = None) -> None:
    if any(attribute is None for attribute in (inp1, inp2)):
        pass
    else:
        if inp1 <= 0:
            print('<=0')
```

I am expecting type checking for the above function to work the same as for the one below:
```python
def test_2(inp1: Optional[int] = None, inp2: Optional[int] = None) -> None:
    if inp1 is None or inp2 is None:
        pass
    else:
        if inp1 <= 0:
            print('<=0')
```
i.e. in the `else` block, the `None` case should be excluded and `inp1` type should be inferred as `int`. Instead, `mypy` says (only for `test_1()`):
```
mypytest.py:7: error: Unsupported operand types for >= ("int" and "None")
mypytest.py:7: note: Left operand is of type "Optional[int]"
```

Is this something which should be easily fixed, or am I overlooking some edge cases?

**Comment by ilevkivskyi** [comment]
This is similar to https://github.com/python/mypy/issues/2980, and probably also low priority, since this form is not used often.

Also https://github.com/python/mypy/issues/4573 is related.
