### ISSUE TITLE
Infer more specific type after equality or membership check

### ISSUE THREAD

**Issue by jackriccomini** [python/mypy#6027]
```python
from typing import Union

def foo(bar: Union[str, int]):
	if bar in ["a", "b", "c"]:
                # to a human, bar is clearly a str. mypy still thinks it's a Union[str, int]
		return bar.upper()
	else:
		return bar
```
```
$ mypy test.py 
test.py:5: error: Item "int" of "Union[str, int]" has no attribute "upper"
```

The same thing happens if the condition is, for example, `bar == "a"`.
* Are you reporting a bug, or opening a feature request?

Feature request

* What is the behavior/output you expect?

Mypy to understand the effect of conditions like `bar == "a"` or `bar in ["a"]`, like it already does with `isinstance` checks

**Comment by ilevkivskyi** [comment]
This is not as safe as it looks because of tricky things like:
```
>>> Decimal(1) in [1, 2, 3]
True
```
We can probably special-case _some_ builtin types, but this looks like relatively low priority.

**Comment by msullivan** [comment]
I think we're probably not going to do this
