### ISSUE TITLE
Is it OK to use a type hint on an existing variable?

### ISSUE THREAD

**Issue by oTree-org** [python/mypy#6051]
I've got a module 'base.py':

    class BaseA:
        @property
        def b(self):
            ''' returns a BaseB object '''
            ...
    
    class BaseB:
        pass

And a child.py that imports from that module:

    from base import BaseA, BaseB
    
    class B(BaseB):
        pass
    
    class A(BaseA):
        b: B

Because the exact return type of `A.b` is only defined in child.py, so I have put a type hint there without assigning any value. Is there any problem with doing this, such as somehow "overwriting" the attribute? (Which is actually a property)

This seems to execute fine, but I just want to be sure because I have only seen it the other way around, the variable being assigned after the type declaration.

**Comment by ilevkivskyi** [comment]
> Is there any problem with doing this, such as somehow "overwriting" the attribute? 

This is totally fine, Python will not put anything in the class namespace if there is no right hand side, it will only update `A.__annotations__`.

Also you can put the annotation directly on the property (as a return type) using `if typing.TYPE_CHECKING: from child import B` and using a string escape for `B` in the annotation (or `from __future__ import annotations`). `TYPE_CHECKING` is a "magic" constant that is false at runtime, but is treated as true by type checkers.

**Comment by oTree-org** [comment]
Thanks!
