### ISSUE TITLE
Support class type hinting without run-time side effects

### ISSUE THREAD

**Issue by PoggledOats** [python/mypy#6052]
I propose actual type annotations for classes instead of affecting the runtime types.
```
class MyClass(BaseClass): # type: annotation
```
Eventually, it would be nice to have support for
```
class MyClass(BaseClass: annotation):
```
but that would require a change to python syntax similar to the recent changes for type annotations. So one step at a time.

As noted in
https://mypy.readthedocs.io/en/latest/common_issues.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime
sometimes there is a need to give type hinting to a class without affecting the runtime definition.  
This current workaround feels hacky as it goes beyond just annotating the code to changing the code. Also, this currently does not work with Generic[T].

It appears the root issue is that type annotates for classes have become entangled with actual runtime class definition changes.

To give a concrete example of how this feature would work, here is the current workaround in the above link:
```
if TYPE_CHECKING:
    BaseQueue = Queue[str]  # this is only processed by mypy
else:
    BaseQueue = Queue  # this is not seen by mypy but will be executed at runtime.

class Tasks(BaseQueue):  # OK
    ...
```
With the proposed features this would become
```
class Tasks(Queue): # type: Queue[str]
    ...
```
This should allow getting around the run-time limitations of the old workaround, and thus provide a path for Generic[T] type hints which currently is not possible even with the workaround.

It is my understanding that the community has decided:  
Type hints are not enforced at runtime, and are primarily for linters or other tools that need analysis like maybe jitters.

With the implication being that type hinting should strive to not affect runtime behaviors.  
Thus there is also an principled reason for wanting this feature.  
We should allow the separation of the type annotation information from runtime class hierarchies. The desire for this separation becomes clearer when considering protocols, structural subtyping, and generics.

----

Another motivation I have for this, is that Generic[T] does have runtime speed implications. I have seen slow downs in heavy graph manipulation code. I wish to avoid discussion of the details of this, because details aside, it fundamentally comes from type annotations for classes actually changing the class heirarchy at runtime, when I feel this should be entirely avoidable. Hence this suggested feature: allow a way to type hint classes without changing their runtime hierarchy.

**Comment by hauntsaninja** [comment]
PEP 585 is the way Python has chosen to go to solve this issue
