### ISSUE TITLE
Feature request: Support XDG standard in configuration file

### ISSUE THREAD

**Issue by rpdelaney** [python/mypy#6065]
From docs[[1]]:

> By default [mypy] uses the file mypy.ini with fallback to setup.cfg in the current directory, or .mypy.ini in the user home directory if none of them are found; the --config-file command-line flag can be used to read a different file instead (see --config-file).

Please consider adding support for the XDG base directory specification by reading the configuration file from `$XDG_CONFIG_HOME/mypy/config` and then `$HOME/.config/mypy/config` before falling back to `$HOME/.mypy.ini`.

Further reading from freedesktop.org[[2]]:

> There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME.

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

[1]: https://mypy.readthedocs.io/en/latest/config_file.html#config-file
[2]: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by gvanrossum** [comment]
If you submit a PR we could consider it.

**Comment by rpdelaney** [comment]
Ok, I'll have a look when I get some time. Thanks.
