### ISSUE TITLE
[QUESTION] Relative import climbs too many namespaces

### ISSUE THREAD

**Issue by nasyxx** [python/mypy#6070]
I met this error when I tried to import packages in emacs with pyls-mypy like this:

```
# File console.py
from ..template import to_str
```

My folder tree:
```
napy-root:
napy
├── __init__.py
├── console
│   ├── __init__.py
│   └── console.py
└── template
    ├── __init__.py
    └── template.py
```

But when I use mypy directly in napy-root with `mypy --strict napy`, this error doesn't appear.

**Does this error (Relative import climbs too many namespaces) only happen when trying to relative import packages with two ".."?**

**How can I disable it or avoid it?**

**Comment by gvanrossum** [comment]
I don't know that emacs package, but I'm guessing that it invokes mypy one file at a time from the directory containing the file. Please complain to the authors of pyls-mypy.

**Comment by nasyxx** [comment]
> but I'm guessing that it invokes mypy one file at a time from the directory containing the file.

Thank you very much. I have found the reason now.

Here is a simple test of mine. If someone encounters it later, I hope it will help.

`tree .`
```
.
└── tpkg
    ├── __init__.py
    ├── tpkg_s1
    │   └── __init__.py
    └── tpkg_s2
        └── __init__.py
```

File `tpkg/tpkg_s1/__init__.py`

```
AA = 12
```

File `tpkg/tpkg_s2/__init__.py`

```
from ..tpkg_s1 import AA
```

Run mypy:

+ No error.
```
>>> from mypy import api
>>> path = "tpkg/tpkg_s2/__init__.py"
>>> args = ('--incremental',
            '--show-column-numbers',
            '--follow-imports', 'silent',
            path)
>>> api.run(args)
('', '', 0)
```

+ Error
```
>>> args = ('--incremental',
            '--show-column-numbers',
            '--follow-imports', 'silent',
            '--command', open(path).read())
>>> api.run(args)
 ('<string>:1:1: error: Relative import climbs too many namespaces\n', '', 1)
```
