### ISSUE TITLE
Understand arbitrary NAME = True/False flags

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#609]
In this example, only the else block should be processed by mypy:

```
DEBUG = False

if DEBUG:
    def warn(x): ...
else:
    def warn(x): pass
```

**Comment by gvanrossum** [comment]
Well, maybe. :-)

On the one hand, this pattern may be used to disable code that doesn't work (so it's not very surprising when it doesn't type-check :-). On the other hand, checking both branches might be helpful in case this is a flag that the developer wants to change on a whim.

**Comment by msullivan** [comment]
We support this in a configurable way now via the `always_true` and `always_false` configuration flags
