### ISSUE TITLE
# type: ignore not taking effect

### ISSUE THREAD

**Issue by maxandersen** [python/mypy#6090]
* Are you reporting a bug, or opening a feature request? bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

In https://github.com/python/typeshed/issues/2678 I reported
that this code was broken: 

```
from typing import List, Tuple

import click

def autoentities(args: str, incomplete: str) -> List[Tuple[str, str]]:
    """bogus function."""
    return []


@click.argument(
    'entity', autocompletion=autoentities  
)
def clix():
    pass
```

This is because type info is missing - BUT now I want to tell mypy to ignore it but I just can't make it work.

doing this:

```
@click.argument(
    'entity', autocompletion=autoentities  # type: ignore
)
def clix():
    pass
```

results in:

```
homeassistant_cli/plugins/test.py:10: error: Unexpected keyword argument "autocompletion" for "argument"
homeassistant_cli/plugins/test.py:11: note: unused 'type: ignore' comment
```

trying to make it on its own line or any other combination result in similar behavior.

* What is the behavior/output you expect?

I would expect mypy to ignore that one error but it does not.

* What are the versions of mypy and Python you are using?

mypy 0.650
python 3.7

*  Do you see the same issue after installing mypy from Git master?

Have not tried - what is the easiest way to do that ?

**Comment by JelleZijlstra** [comment]
You should put the type ignore on the line where the error is reported (line 10 in this case). Have you tried that?

**Comment by maxandersen** [comment]
gawd - can't believe I missed that. that worked. sorry for the noise.
