### ISSUE TITLE
Exception handling not working.

### ISSUE THREAD

**Issue by sp1rs** [python/mypy#6091]
```
from typing import Union

def post(path: str) -> Union[requests.models.Response, ManualException]
      try:
            return requests.post(path)
      except:  
            raise ManualException 


def call() -> List:
        try:
              resp = post('path')
        except ManualException:
               return []

        return resp.content

```

On running mypy

```
Item "ManualException" of "Union[Response, ManualException]" has no attribute "content"
```

Ideally mypy should not raise any error, because I am handling the case when exception is raised.

**Comment by JelleZijlstra** [comment]
Exceptions should not be included in the return type. Your `post` function should simply return `requests.models.Response`.

The Python type system doesn't provide a way to specify what exceptions may be raised from a function.

**Comment by sp1rs** [comment]
@JelleZijlstra There are lots of places where we raise exception. This is common practice. Any work around? In django codebase, raising exception is a common thing.

**Comment by JukkaL** [comment]
Mypy can't check that exceptions are correctly caught or annotated, so your best is to document them in a docstring or invent some custom way of annotating them (but that won't be checked by mypy).
