### ISSUE TITLE
Treat __debug__ as a True constant

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#610]
This is specified in PEP 484.

Only type check the if block in this example (ignore else block):

```
if __debug__:
    class Tracer: ...
else:
    class Tracer: ...
```

**Comment by gvanrossum** [comment]
While I have defended this on python-ideas, I'm not sure how much thought went into that sentence in the PEP (I think it was Łukasz's). Does mypy currently does something that's more useful?

**Comment by JelleZijlstra** [comment]
This doesn't seem to be in PEP 484's current text. I think this issue can be closed.
