### ISSUE TITLE
Possible bug with identifying a Callable defined as a class attribute

### ISSUE THREAD

**Issue by pawelswiecki** [python/mypy#6103]
**Are you reporting a bug, or opening a feature request?**

Bug.

**Please insert below the code you are checking with mypy**

```python
class MyClass: ...

class AnotherClass:
    my_class: MyClass  # or `my_class: MyClass = MyClass`

    def my_class_factory(self) -> MyClass:
        return self.my_class()
```
**What is the actual behavior/output?**

```bash
$ mypy 1.py 
1.py:8: error: "MyClass" not callable
```

**What is the behavior/output you expect?**

No mypy message.

**What are the versions of mypy and Python you are using?**

Python 3.7.1, mypy 0.650.

**Comment by ethanhs** [comment]
This is not a bug. You need to annotate `my_class` as `Type[MyClass]`. My even helpfully tells you are wrong if you try `my_class: MyClass = MyClass` with `error: Incompatible types in assignment (expression has type "Type[MyClass]", variable has type "MyClass")`. You may want to read the relevant docs https://mypy.readthedocs.io/en/latest/kinds_of_types.html#the-type-of-class-objects.

**Comment by pawelswiecki** [comment]
Right, my bad. Thanks!

**Comment by ethanhs** [comment]
>Right, my bad, silly mistake.

Happens to everyone :)
