### ISSUE TITLE
Invalid syntax at the end of code

### ISSUE THREAD

**Issue by yanjijinxiao** [python/mypy#6105]
I wrote a simple code about matplotlib and mypy always pointed out I have a invalid syntax.

![image](https://user-images.githubusercontent.com/5549530/50418930-0e89a200-0869-11e9-89e5-9117835e2941.png)

And the most weird thing is that it seems that no matter what I type at the end of line, there is always a invalid syntax error.

![image](https://user-images.githubusercontent.com/5549530/50419021-8a83ea00-0869-11e9-9433-183512308822.png)

I'm using spacemacs in MacOS High Sierra(10.13.6) 
My emacs's version is 26.1 and my spacemacs's is 0.300.0 (I'm using develop branch)

Is there anyone know something about this error? Thanks a lot.

**Comment by JelleZijlstra** [comment]
This sounds like a bug in whatever plugin/editor integration you are using. You didn't tell us what that integration is though.
