### ISSUE TITLE
make it possible to annotate return values without assigning to names

### ISSUE THREAD

**Issue by bwo** [python/mypy#6109]
I have been getting errors of the form `error: Cannot infer type argument 2 of "map" of "RecordNode"` in a call that looks something like this:

`node.map(f)`

Where `RecordNode` is a generic parameterized by a type `T` and `map` has a type like `(Callable[[T], A]) -> RecordNode[A]`. `f` has the type `(Callable[[T], None])`

AFAICT the type of `f` should be sufficient to infer the type argument, but it doesn't; at any rate, I tried this:

`node.map(f)  # type: RecordNode[None]`

I still get the error with that.

But if I do this:

`_ = node.map(f)  # type: RecordNode[None]`

then *that* works, because, I guess, it understands that I'm annotating `_`. It would be great if this weren't necessary!

(I can try to get a reduced full example if that would be helpful)

**Comment by ilevkivskyi** [comment]
Could you please provide a self-contained repro?

Is this specific to situations when `f` returns `None`, or it can't infer the type parameter in other situations too?

Allowing annotations of arbitrary expressions is non-trivial as this would require extensive changes to `typed_ast`.

**Comment by bwo** [comment]
here you go:

```python
from typing import Callable, TypeVar, Generic

S = TypeVar('S')
T = TypeVar('T')


class Spam(Generic[S]):
    def __init__(self, s):
        # type: (S) -> None
        self.s = s

    def map(self, f):
        # type: (Callable[[S], T]) -> Spam[T]
        return Spam(f(self.s))


def test():
    # type: () -> None
    x = Spam("a")
    # cannot infer type argument 1 of "map" of "Spam"
    x.map(lambda _: None)  # type: Spam[None]

    # this works
    z = x.map(lambda _: None)  # type: Spam[None]

    # this *also* works
    x.map(lambda _: 1)
```

The answer to your question is that it's only when `f` returns `None`. I guess this is probably because `None` is a subtype of all types (though running with `--strict-optional` didn't help).

**Comment by ilevkivskyi** [comment]
> The answer to your question is that it's only when `f` returns `None`.

Great, thanks! Probably we just need to remove some special-casing for `None` when `--strict-optional` is `True`.

**Comment by AlexWaygood** [comment]
FWIW the repro [doesn't reproduce](https://mypy-play.net/?mypy=0.780&python=3.10&gist=ba5a76fa8dd696e6c4ea39c05c815f2f) on mypy 0.780+.

Not sure if this should be closed, though, as strictly speaking the feature request is for a general solution to this problem rather than a specific solution to solve the repro.
