### ISSUE TITLE
Add full stub for std lib module 'types', use these types in other stubs when relevant

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#611]

**Comment by gvanrossum** [comment]
(What's this?)

**Comment by JukkaL** [comment]
Updated the title. The idea is that we could use `types.ModuleType` for the type of a module object, etc. Some std lib function signatures could be represented more precisely using types from module `types`.

**Comment by gvanrossum** [comment]
Makes sense.

**Comment by gvanrossum** [comment]
Closing. We do have reasonable looking stubs for types in typeshed; this issue doesn't point out specifics so I prefer to just close it rather than migrate it to the typeshed's tracker.
