### ISSUE TITLE
Treat bool as equivalent to Literal[True, False] to allow better type inference

### ISSUE THREAD

**Issue by ahmedsoe** [python/mypy#6113]
Similar to this https://github.com/python/mypy/issues/6027, but more basic use case.

```python
from typing import Collection, Union, List


def foo(bar: Union[bool, Collection[int]]) -> Union[int, List[int]]:
    if bar is False:  # or   if not bar:
        return 10

    if bar is True:
        return 20

    # otherwise, bar must be a collection (list, tuple, ...)
    return [i*2 for i in bar]


print(foo(True))
print(foo(False))
print(foo([1, 2, 3]))
print(foo((1, 2, 3,)))
```

Mypy is giving the error

```error: Item "bool" of "Union[bool, Collection[int]]" has no attribute "__iter__" (not iterable)```

But it should be able to infer that it can't be a `bool`?
using if / elif /else also gives the error.

**Comment by ilevkivskyi** [comment]
I think this can be done using literal types: essentially we can treat `bool` as `Union[Literal[True], Literal[False]]`.

cc @Michael0x2a

**Comment by ilevkivskyi** [comment]
This appeared again so raising priority to normal.

**Comment by ethan-leba** [comment]
Would like to take a stab at this if no one's picked it up already!

**Comment by srittau** [comment]
Another use case:

```python
from typing import Literal, overload

@overload
def foo(x: Literal[False]) -> int: ...
@overload
def foo(x: Literal[True]) -> str: ...
def foo(x): pass

b: bool = True
foo(b)
```

Gives us:

```
foo.py:10: error: No overload variant of "foo" matches argument type "bool"
foo.py:10: note: Possible overload variants:
foo.py:10: note:     def foo(x: Literal[False]) -> int
foo.py:10: note:     def foo(x: Literal[True]) -> str
foo.py:10: note: Revealed type is 'Any'
Found 1 error in 1 file (checked 1 source file)
```

It would be great if this could infer `foo(x: bool) -> str | int: ...` like it does in other kinds of overloads. python/typeshed#5471 contains a case where we can't work around this by using a third overload.

**Comment by matangover** [comment]
This issue is marked as fixed but the last two comments about the fallback overload being needed are not resolved. Is this by design?

**Comment by Newbytee** [comment]
Given that this issue is marked as closed, why does this example still not work:
```python
from typing import overload, Literal


@overload
def something(return_string: Literal[True]) -> str: ...
@overload
def something(return_string: Literal[False]) -> int: ...

def something(return_string: bool) -> int | str:
    if return_string:
        return "ten"
    else:
        return 10


something_type = True
value_int = something(something_type)
something_type = False
value_str = something(something_type)
print(value_str.upper())
```

This is the output I get from mypy 1.13.0:
```
literal.py:17: error: No overload variant of "something" matches argument type "bool"  [call-overload]
literal.py:17: note: Possible overload variants:
literal.py:17: note:     def something(return_string: Literal[True]) -> str
literal.py:17: note:     def something(return_string: Literal[False]) -> int
literal.py:19: error: No overload variant of "something" matches argument type "bool"  [call-overload]
literal.py:19: note: Possible overload variants:
literal.py:19: note:     def something(return_string: Literal[True]) -> str
literal.py:19: note:     def something(return_string: Literal[False]) -> int
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by cdce8p** [comment]
> Given that this issue is marked as closed, why does this example still not work

When you assign `something_type = True`, it's inferred as `bool`. That's similar to any other literal value, e.g. `s = "Hello World"` (-> `str`) or `i = 2` (-> `int`).

If mypy would infer the type as `Literal[True]`, your second assignment to `False` would fail instead. In which case you'll probably end up annotating it as `bool` explicitly.

The exception here is if you use `Final` for the assignment, in which case it's inferred as `Literal[True]`.

**Comment by hauntsaninja** [comment]
See #2008 , we'll eventually change behaviour in that example
