### ISSUE TITLE
Treat annotations more opaquely (proposal)

### ISSUE THREAD

**Issue by valtron** [python/mypy#6147]
Python allows annotations to be any expression, but if you use MyPy on your project, you can't use annotations for anything other than types (MyPy will error "Invalid type ...").

This issue proposes the following solution:

- provide class `typing.Annot` (name for the purposes of this discussion):
```
class Annot:
    def __init__(self, type_=None, **kwargs):
        self.type = type_
        self.kwargs = kwargs
```
- during typechecking, MyPy treats annotations that are instances of `Annot` as if they were their `type` property

## Benefits/Use cases

MyPy/other tools (including runtime inspection) also have extra info in `kwargs` available, if they know how to use it. For example, [dataclasses](https://docs.python.org/3/library/dataclasses.html) (and [attrs](http://attrs.org), and [this concept](https://www.willmcgugan.com/blog/tech/post/adding-type-hints-to-the-django-orm/)) store extra field information in the value of the attribute:

```
@dataclass
class C:
    z: int = field(repr=False, default=10)
```

...which is a workaround. With general-purpose annotations, it could look like this:

```
@dataclass
class C:
    z: Annot(int, repr=False, default=10)
```

This could also subsume [class attribute annotations](https://mypy.readthedocs.io/en/latest/class_basics.html#class-attribute-annotations) and [Final annotations](https://mypy.readthedocs.io/en/latest/final_attrs.html):

```
class A:
    x: Annot(int, classvar=True) = 0
    y: Annot(final=True) = ''
```

But the main benefit is that with this in place, it will be possible to add annotations **as well as, or instead of,** plain type info, without foregoing MyPy, paving the way for more tooling.

**Comment by Michael0x2a** [comment]
You may be interested in [this proposal](https://github.com/python/typing/issues/600) in the "typing" github repo, which proposes an idea similar to yours.
