### ISSUE TITLE
Multiple protocol related errors on the same line formatted inconsistently

### ISSUE THREAD

**Issue by nbraud** [python/mypy#6151]
In ppb/ppb-vector#104 (last 2 commits), I ran into an issue: the Vector2 class seemingly implements the [mapping protocol] correctly, yet [type-checking fails]:
```
$ mypy ppb_vector tests
tests/test_convert.py:27: error: Argument 1 to "dict" has incompatible type "Vector2"; expected "Iterable[Tuple[<nothing>, <nothing>]]"
tests/test_convert.py:27: note: Following member(s) of "Vector2" have conflicts:
tests/test_convert.py:27: note:     Expected:
tests/test_convert.py:27: note:         def __iter__(self) -> Iterator[Tuple[<nothing>, <nothing>]]
tests/test_convert.py:27: note:     Got:
tests/test_convert.py:27: note:         def __iter__(self) -> Iterator[float]
tests/test_convert.py:27: error: Argument 1 to "dict" has incompatible type "Vector2"; expected "Iterable[Tuple[Any, Any]]"
tests/test_convert.py:27: note:     Expected:
tests/test_convert.py:27: note:         def __iter__(self) -> Iterator[Tuple[Any, Any]]
tests/test_convert.py:27: note:     Got:
tests/test_convert.py:27: note:         def __iter__(self) -> Iterator[float]
tests/test_convert.py:27: note:     Expected:
tests/test_convert.py:27: note:         def __iter__(self) -> Iterator[Tuple[<nothing>, <nothing>]]
tests/test_convert.py:27: note:     Got:
tests/test_convert.py:27: note:         def __iter__(self) -> Iterator[float]
```

Apologies in advance if this isn't a mypy bug, but:
- [The tests] seem to confirm that the implementation is correct.
- That specific protocol isn't listed in [the mypy documentation].

[The tests]: https://github.com/ppb/ppb-vector/blob/1f9985992515afe24e286b38936afdb85e1c2520/tests/test_convert.py#L25-L33
[mapping protocol]: https://docs.python.org/3/reference/datamodel.html#emulating-container-types
[type-checking fails]: https://travis-ci.org/ppb/ppb-vector/jobs/475839394#L522
[the mypy documentation]: https://mypy.readthedocs.io/en/latest/protocols.html

**Comment by srittau** [comment]
It seems that the problem is that mypy does not use the second overload of the dict constructor, but the third:

https://github.com/python/typeshed/blob/eb6dbe510df2914b453d0ac692df922bb4601133/stdlib/2and3/builtins.pyi#L922-L930

You could try to comment out the third overload in the `dict` definition shipped with mypy's typeshed to try to pinpoint the problem.

**Comment by nbraud** [comment]
@ilevkivskyi Why is this not a bug?  (Error formatting notwithstanding.)

**Comment by nbraud** [comment]
If I make `Vector2` inherit from `typing.Mapping[str, float]`, I get type errors because it's now expected to be an `Collection[str]`, whereas it is (currently, and previously) an `Iterable[float]`:
```
$ mypy ppb_vector tests/
ppb_vector/vector2.py:195: error: Return type of "__iter__" incompatible with supertype "Iterable"
tests/test_vector2_reflect.py:36: error: Argument 1 to "map" has incompatible type "Callable[[SupportsFloat], bool]"; expected "Callable[[str], object]"
```

Is there a type weaker than `Mapping` that I could annotate `Vector2` with?

**Comment by hauntsaninja** [comment]
This issue is quite stale, so having a hard time figuring out what the current state is 4 years later.

You could maybe try something like: https://github.com/python/typeshed/blob/f66769a6f5c1f335e566d48c67d179974996a352/stdlib/_typeshed/__init__.pyi#L120
