### ISSUE TITLE
Unclear why --namespace-packages isn't enabled by default

### ISSUE THREAD

**Issue by russelldavis** [python/mypy#6161]
Why isn't the behavior enabled by `--namespace-packages` on by default? Is it because it's new/unstable, and will eventually become the default? (If so, can the docs be updated to reflect that?)

**Comment by gvanrossum** [comment]
It has some downsides too, e.g. it means mypy can't resolve the package to which a file belongs when it's a namespace package (because there's no `__init__.py` to recognize it as a package). So it's not going to become the default.

**Comment by russelldavis** [comment]
Got it, thanks. Can the docs be updated to explain the downsides?

**Comment by gvanrossum** [comment]
Can you suggest a PR?

**Comment by russelldavis** [comment]
For posterity, here's the proposal for enabling this by default: https://github.com/python/mypy/issues/8584
