### ISSUE TITLE
Inconsistency in Union/promotion interactions

### ISSUE THREAD

**Issue by msullivan** [python/mypy#6168]
In the following test
```
from typing import Union

class A:
    x: Union[int, float]

def foo(x: Union[int, float], y: A) -> None:
    reveal_type(x)
    reveal_type(y.x)
```
we emit:
```
lol.py:8: error: Revealed type is 'Union[builtins.int, builtins.float]'
lol.py:9: error: Revealed type is 'builtins.float'
```

That is to say, class attributes have unions simplified using promotions while arguments (and locals) do not.

Probably they ought to have the same behavior?
(And probably the behavior ought to be to *not* simplify, especially because of #6114)

**Comment by ilevkivskyi** [comment]
> And probably the behavior ought to be to _not_ simplify

Yes, I think we should never use promotions in union simplification. Also this looks like something that may be easy to fix. We just need to use `ignore_promotions=True` in `UnionType.make_simplified_union()`.

**Comment by ilevkivskyi** [comment]
Added usability label because this can cause confusion, see https://github.com/python/mypy/issues/7241.

**Comment by hauntsaninja** [comment]
These currently have the same type
