### ISSUE TITLE
Add support for outputting warnings messages to log file

### ISSUE THREAD

**Issue by henryborchers** [python/mypy#6177]
I want to easily parse warnings with Jenkins's Warnings Next Generation Plugin. It's super helpful for keeping my projects clean.

Right now, I have to do something like this on Windows to get a file which the Warnings parser can use.

```
mypy -p pykdu_compress > ${WORKSPACE}\\logs\\mypy.log
```

This works most of the time. However, I cannot use tee when testing on Windows machines. For this reason,  if I want see the warnings data produced, I either have archive the log file and open it again or add another step that prints the contents of the file to the console. Anyways, it seems like there should be an easier way.

flake8 does some to accommodate this. 

```
flake8 pykdu_compress --tee --output-file=${WORKSPACE}\\logs\\flake8.log"
```

This makes it possible but I think it could be simpler in mypy. For example:

```
mypy -p pykdu_compress --warning-messages  ${WORKSPACE}\\logs\\mypy.log
```

**Comment by ethanhs** [comment]
>However, I cannot use tee when testing on Windows machines.

Powershell has a `tee` FWIW.

I think this might be a nice thing to have regardless. I would prefer to name it `--tee` as that seems easier to remember, but I don't have strong preferences.

**Comment by henryborchers** [comment]
@ethanhs You are right about Powershell having tee. However, it seems to do something weird when I use it in a Jenkins pipeline. The file teen generates seems to be the same but for some reason the warnings parser is unable to parse it. ¯\_(ツ)_/¯

Nevertheless, having a function named --tee would be perfectly fine with me.

**Comment by msullivan** [comment]
This falls into a category of "I guess I would probably review a PR for it" but I also think it doesn't really make sense.
