### ISSUE TITLE
Variable is <nothing> when name is reused in list comprehension

### ISSUE THREAD

**Issue by andy-hanson** [python/mypy#6193]
* Are you reporting a bug, or opening a feature request? **Bug**
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```py
from typing import Optional, Sequence


def f(s: Optional[str]) -> Sequence[str]:
    if s is None:
        return [s.capitalize() for s in ["a", "b"]]
    else:
        return [s]
```

* What is the actual behavior/output?

`a.py:6: error: <nothing> has no attribute "capitalize"`

* What is the behavior/output you expect?

No error.

* What are the versions of mypy and Python you are using?

`python --version`: 3.7.2
`mypy --version`: 0.660+dev.97d7760dca6d95806a97b02992ae88a082898a0e

  Do you see the same issue after installing mypy from Git master? **Yes**

* What are the mypy flags you are using? (For example --strict-optional) **None**

Note, there is no error if you change the offending line to:
```py
for s in ["a", "b"]: s.capitalize()
return []
```

**Comment by comaniac** [comment]
I would like to push this issue since I'm facing the same problem:

```python
from typing import Dict, Optional

class T:
    def __init__(self, v: int) -> None:
        self.v = v

a = {} # type: Dict[str, Optional[T]]
a['a'] = T(3)
a['b'] = None
print ({x: a[x].v if isinstance(a[x], T) else -1 for x in a})
```
And mypy complains:
`error: Item "None" of "Optional[T]" has no attribute "v"`

I conclude that this may be due to the attribute accessing (`.v`) in list comprehension. Like @andy-hanson , I could get rid of the error by changing the last line to
`print ({x: a[x] if isinstance(a[x], T) else -1 for x in a})`

**Comment by ilevkivskyi** [comment]
I just checked and this still happens on master. Most likely mypy is confused by reuse of the variable inside comprehension.

**Comment by and-semakin** [comment]
It happened for me when I reused variable name in different context managers with `mypy==0.701`

**Comment by TH3CHARLie** [comment]
The code by @andy-hanson no longer generates errors in the latest mypy, therefore, this issue may be solved by some merged PRs and is now safe to close. @ilevkivskyi @ethanhs
