### ISSUE TITLE
Unicode strings can not be handled

### ISSUE THREAD

**Issue by yuslepukhin** [python/mypy#6198]
Note: if you are reporting a wrong signature of a function or a class in
the standard library, then the typeshed tracker is better suited
for this report: https://github.com/python/typeshed/issues

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
Bug
* Please insert below the code you are checking with mypy,
>import numpy as np  # type: ignore
input = np.array([u'monday', u'tuesday', u'Besançon', u'École élémentaire', u'Понедельник', u'mit freundlichen grüßen', u'中文']).astype(np.object)

The problem persists even if the code is commented out!
* What is the actual behavior/output?
>mypy: can't decode file '.\onnx\backend\test\case\node\stringnormalizer.py': 'ascii' codec can't decode byte 0xc3 in position 3002: ordinal not in range(128)
Warning: unused section(s) in setup.cfg: [mypy-tools.*], [mypy-setup]

* What is the behavior/output you expect?
Just work

* What are the versions of mypy and Python you are using?
mypy 0.650
Python 3.6.5

*  Do you see the same issue after installing mypy from Git master?
Don't know but that would not do anyway

* What are the mypy flags you are using? (For example --strict-optional)

* If mypy crashed with a traceback, please paste
  the full traceback below.
None

**Comment by msullivan** [comment]
Are you checking in python2 or python3 mode? In python 3, this should't happen, since the default encoding is 'utf-8'. In python 2, this is the correct behavior, and matches what the python interpreter does.

In either case, the default encoding can be overridden in the source file: https://www.python.org/dev/peps/pep-0263/

**Comment by yuslepukhin** [comment]
Thanks!
