### ISSUE TITLE
Show used config settings in verbose mode

### ISSUE THREAD

**Issue by ezyang** [python/mypy#6205]
Steps to reproduce:
1. Create `mypy.ini` with:
```
[mypy]
python_version = 2.7
```
2. Create a test file that uses Python 3 only type syntax, e.g.:
```
def f(x : int) -> int:
  return x
```
3. Run `python -mmypy test.py` where `python` in PATH is Python 3.

What I expected was for Python 3 to be used to typecheck the file. What actually happened was mypy somehow found a Python 2 executable on my system, and used that instead to typecheck the file. I thought this was unexpected, because I specifically ran mypy as `python -m mypy` so that it knew to use that python interpreter. Now, I know why this happened; because mypy is respecting the requested python version when it runs the typechecking. It would have been easier to debug if mypy by default emitted information about which Python it was using when it wasn't using the default.

Note: in the actual sequence of events, I didn't do (1), and didn't realize the file existed until I started digging.

**Comment by ilevkivskyi** [comment]
Mypy never "selects" an interpreter to be interpreted (what would that even mean). Also the files are never executed by mypy (e.g. you don't need Python 2 interpreter to check Python 2 code).

However, mypy parses your code according to the syntax/grammar of Python version specified in the config file. And your example is not a valid Python 2.7.

**Comment by ilevkivskyi** [comment]
Actually on the second thought, it seems to me we should show more info in verbose mode (currently it mostly useful for incremental mode).

**Comment by ezyang** [comment]
I don't know too much about how mypy is implemented internally, so I was mostly guessing based on behavior. What I noticed is that if I run `python -mmypy test.py` it respects `python_version` in the config file, but when I run `python -mmypy --python-executable python3` it ignores `python_version` and parses the file as Python 3.

**Comment by JelleZijlstra** [comment]
Yes, that's expected behavior; command-line flags override config file settings.

**Comment by ezyang** [comment]
Sure. What's unexpected/confusing is the fact that they're different flags. `--python-executable` is documented to set `--python-version` if it is not already set, but a config file python-version doesn't count for th epurposes of determining "if it's already set."

**Comment by gvanrossum** [comment]
Is that still true in mypy 0.660? AFAIK we rationalized the behavior here. Perhaps the docs need tweaking?
