### ISSUE TITLE
mypy fails suddenly with No module named '_sqlite3'

### ISSUE THREAD

**Issue by vseguin** [python/mypy#6207]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

Very minimal mypy test:
```
import unittest

from mypy import api


class TypeChecker(unittest.TestCase):
    def test_check_type_for_all_modules(self):
        stdout, stderr, exit_code = api.run(
            ['--strict', 'api', 'producer', 'i18n_extractor', 'services', 'database', 'main']
        )
        self.assertEqual(exit_code, 0, f'mypy validation failed\r\nType errors:\r\n{stdout}\r\nErrors:\r\n{stderr}')

```

* What is the actual behavior/output?
It just explodes with the following stack trace:

```
Traceback (most recent call last):
  File "/tmp/pythonproject/tests/test_mypy.py", line 8, in test_check_type_for_all_modules
    stdout, stderr, exit_code = mypy.api.run(['--strict', 'api', 'main', 'services', 'session', 'system_test'])
  File "/tmp/pythonproject/venv/lib/python3.6/site-packages/mypy/api.py", line 73, in run
    from mypy.main import main
  File "/tmp/pythonproject/venv/lib/python3.6/site-packages/mypy/main.py", line 14, in <module>
    from mypy import build
  File "/tmp/pythonproject/venv/lib/python3.6/site-packages/mypy/build.py", line 55, in <module>
    from mypy.metastore import MetadataStore, FilesystemMetadataStore, SqliteMetadataStore
  File "/tmp/pythonproject/venv/lib/python3.6/site-packages/mypy/metastore.py", line 12, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

```

* What is the behavior/output you expect?

That it works as before :)

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

mypy 0.660, Python 3.6.0

* What are the mypy flags you are using? (For example --strict-optional)

--strict

* If mypy crashed with a traceback, please paste
  the full traceback below.

See stack trace already posted :point_up: 

(You can freely edit this text, please remove all the lines
you believe are unnecessary.)

Thank you!

**Comment by msullivan** [comment]
Something seems busted about your python install. `sqlite3` is part of the python standard library.

Looking around it seems that if the sqlite headers aren't found while configuring a python build, the `_sqlite3` module will get left out?

**Comment by vseguin** [comment]
@msullivan that's what I thought at first - but I reverted to mypy 0.650 and it works perfectly, and as soon as I use 0.660 it fails with this error... so it's pretty suspicious.

**Comment by msullivan** [comment]
That's because we didn't ever try to use `sqlite3` in mypy 0.650. That was added in https://github.com/python/mypy/pull/6023
