### ISSUE TITLE
Regression in 0.660 regarding StopIteration

### ISSUE THREAD

**Issue by boustrophedon** [python/mypy#6209]
I'm not really sure if this is a regression or if this is mypy picking up something new, but if so I don't understand why.

The [documentation for StopIteration](https://docs.python.org/3.7/library/exceptions.html#StopIteration) says that "The exception object has a single attribute `value`, which is given as an argument when constructing the exception, and defaults to None." I don't get an error that I'm using the optional as a non-optional in my original code with 0.650, so probably something is wrong there anyway.

```python
def main() -> None:
    s = StopIteration("hello")
    print('value' in dir(s))
    print(s.value)

if __name__ == '__main__':
    main()
```
commands to reproduce:
```shell
python --version
# Python 3.7.1
python -m venv .
source bin/activate
pip install --upgrade pip # not necessary for reproduction
pip install mypy==0.650
mypy test.py
# no output
pip install mypy==0.660
mypy test.py
# test.py:4: error: "StopIteration" has no attribute "value"`
```

However, running `python test.py` shows that StopIteration definitely has a value attribute:
```shell
python test.py
# True
# hello
```

**Comment by JelleZijlstra** [comment]
Looks like this was introduced in python/typeshed#2533. I will submit a fix to typeshed now.
