### ISSUE TITLE
Lambda with exponentiation return any warning

### ISSUE THREAD

**Issue by alanhdu** [python/mypy#6210]
Using mypy 0.660 and Python 3.7, running `mypy --warn-return-any` on:

```python
output = filter(lambda x: 2**x < 6, [1, 2, 3, 4])
```

returns

```
lambda.py:1: warning: Returning Any from function declared to return "object"
```

This only occurs when there's the exponentiation (`**`) in the lambda: if I change it to a `+` or `*`.

**Comment by JukkaL** [comment]
`float` return type would be technically true, but that would cause a lot of issues with code that (correctly) wants to assume that `x ** y` is an integer. The convention in typeshed is to use `Any` as the return type if the return type depends on the value (not the type) of an argument. If you want a precise type, you can create a helper function (or alias `pow`) and explicitly annotate it.

**Comment by jonasrauber** [comment]
This also happens for `map(lambda x: x.shape, xs)` (where xs is a list of numpy arrays).
