### ISSUE TITLE
Conditional import incorrectly processed within method

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6216]
The first import generates an error, even though it's unreachable:

```py
import sys

class A:
    def f(self) -> None:
        if sys.platform == 'xxx':
            import bad  # Error


def g() -> None:
    if sys.platform == 'xxx':
        import bad2  # No error
```

I found this bug when reading `mypy/semanal_pass1.py`. We don't process conditional imports during semantic analysis pass 1 in methods, but we process them inside module-level functions.

**Comment by hauntsaninja** [comment]
This got fixed at some point
