### ISSUE TITLE
Inconsistent type reporting of dicts with values that are subclasses

### ISSUE THREAD

**Issue by radkujawa** [python/mypy#6228]
I've run into an issue with subclasses used as a dict value. I cannot add a type hint that use a base class to a dict that contains a subclass, if there is only one type of a subclass currently used in the initialization:

test_dict_typing.py:
```
from typing import Dict

class A: pass
class B(A): pass
class C(A): pass

d1 = {'k' : B()}
d2 = {'k1' : B(), 'k2' : C()}

D1: Dict[str, A] = d1
D2: Dict[str, A] = d2
D3: Dict[str, A] = {'k' : B()}
D4: Dict[str, A] = {'k1' : B(), 'k2' : C()}
```

I've got:
```
$ mypy test_dict_typing.py 
test_dict_typing.py:10: error: Incompatible types in assignment (expression has type "Dict[str, B]", variable has type "Dict[str, A]")
$
```

I would expect no error (after some resist I would also agree on reporting the same error on both assignments to D1 and to D3).

I use:
* `mypy 0.650`
* `python 3.6.7`

I've checked that `mypy 0.670+dev.d5cf72b141ce93108c28864ef084c936964ae152` (which is current master) has the same behaviour as `mypy 0.650`.

**Comment by ilevkivskyi** [comment]
This is expected behavior, please read https://mypy.readthedocs.io/en/latest/common_issues.html#invariance-vs-covariance

Mypy infers `Dict[str, B]` for `d1` which is not a subtype of `Dict[str, A]` due to invariance. Adding an explicit annotation is the correct solution.
