### ISSUE TITLE
Idea: use inferred types for documentation

### ISSUE THREAD

**Issue by dimaqq** [python/mypy#6238]
It would be really cool to "see" the types that mypy infers.

There's a project to use type hints for generated documentation: https://github.com/agronholm/sphinx-autodoc-typehints

Perhaps something like this could be done with types inferred by mypy instead of explicit type hints?

**Comment by ilevkivskyi** [comment]
I have a local branch that does some overhaul to `stubgen` (a script that generates type stub files from source code). If everything will be OK, I will make a PR this evening. On top of that branch, one can easily implement converting inferred types into explicit annotations. But I am a bit worried that inferred types may be misleading in untyped code.

**Comment by msullivan** [comment]
I don't think we're going to have this as a built-in mypy feature, though it could be done by an external project calling into mypy
