### ISSUE TITLE
argument of method incompatible with supertype

### ISSUE THREAD

**Issue by mnowotka** [python/mypy#6248]
This is my first issue in mypy so sorry if I cause any troubles. I have a following example (mypy_test.py):

```
import typing

class Base:
   def fun(self, a: str):
       pass

SomeType = typing.NewType('SomeType', str)

class Derived(Base):
    def fun(self, a: SomeType):
        pass
```

And after invoking ` mypy mypy_test.py` I'm getting an error:

`mypy_test.py:10: error: Argument 1 of "fun" incompatible with supertype "Base"`

Is that a bug?

**Comment by ilevkivskyi** [comment]
This is not a bug, the code is actually unsafe, please read about Liskov substitution principle for methods.

**Comment by mnowotka** [comment]
OK, then why this works without a problem?

```
import typing

class Base:
   def fun(self, a: typing.Any):
       pass

SomeType = typing.NewType('SomeType', str)

class Derived(Base):
   def fun(self, a: SomeType):
       pass
```

**Comment by ilevkivskyi** [comment]
Because `Any` is special, it is a supertype and and a subtype of all types (it is not the same as `object`).
Please, read the docs.

**Comment by mnowotka** [comment]
OK then. Any hints how can I make my code work without typing errors?

**Comment by ilevkivskyi** [comment]
I don't have all context to make a good advice, but my first guess is using `Any` in the supertype is just fine (especially if that method is abstract in the supertype).
