### ISSUE TITLE
Errors when calling a member of Optional[List[...]] types

### ISSUE THREAD

**Issue by alextretyak** [python/mypy#6254]
When I run mypy for [this Python file](https://bitbucket.org/11l-lang/python_to_11l/src/04082b2899fe3518f69f323662cde2f486f6fdf0/tokenizer.py?at=default#lines-127), I get the following errors:
`tokenizer.py:127: error: Item "None" of "Optional[List[int]]" has no attribute "append"`
`tokenizer.py:139: error: Item "None" of "Optional[List[Tuple[int, int]]]" has no attribute "append"`

**Comment by Michael0x2a** [comment]
The correct idiom in Python for checking whether some variable is None or not is to do `if foo is None` or `if foo is not None`. Try doing that instead -- I believe that should fix your problem.

Doing `if foo == None` or `if foo != None` is pretty uncommon/non-standard, so afaik mypy doesn't try and do any special inference there.

**Comment by ilevkivskyi** [comment]
I would propose to just close this. It is unlikely we will ever support `== None`.

**Comment by alextretyak** [comment]
@Michael0x2a 
Thanks, with `is not None` there are no errors anymore.
