### ISSUE TITLE
Does not find non local variable for inner (dynamic) class

### ISSUE THREAD

**Issue by kaste** [python/mypy#6264]
mypy doesn't find the non local variable in the following example:

```
> mypy -V
mypy 0.660
```

```
def outer():
    class Foo:
        def inner(self):
            return theValue
                   ^^^^^^^^ Name 'the Value' is not defined 
    theValue = 1
    return Foo
```

I'm super new to mypy so feel free to shred me. I set `check_untyped_defs = True` for the code example. (I actually wouldn't know how to annotate the return type either, but in the real code Foo actually subclasses an available global class.)

**Comment by ilevkivskyi** [comment]
I was going to say that this is a weird pattern, but then realized that I am going to work very soon (probably tomorrow) on something that will likely allow this :-)

Anyway, this use case is rare, so setting priority to low.

**Comment by erictraut** [comment]
This appears to have been fixed. The latest version of mypy no longer emits an error.

**Comment by JelleZijlstra** [comment]
Thanks for checking all these old bugs @erictraut!
