### ISSUE TITLE
A list is identified as general collection

### ISSUE THREAD

**Issue by efimk-lu** [python/mypy#6267]
* Are you reporting a bug, or opening a feature request?
A bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate if you try to simplify your case to a minimal repro.
```
 return_value = {"node": run_over_node(node), "children": []}
        for node in node.children:
            return_value["children"].append(recursive_loop(node)) <-- Error here
```

* What is the actual behavior/output?
 `error: "Collection[Any]" has no attribute "append"`
* What is the behavior/output you expect?
No error to appear.
* What are the versions of mypy and Python you are using?
0.660 mypy
3.7.1 python
  Do you see the same issue after installing mypy from Git master?
I'm using pre-commit hooks, so it's a bit problematic for me to use the latest.
* What are the mypy flags you are using? (For example --strict-optional)
No flags
* If mypy crashed with a traceback, please paste
  the full traceback below.
No

**Comment by ilevkivskyi** [comment]
In mypy, individual dictionary keys can't have separate types, it is just `Dict[str, <common supertype>]` in your case. If you want individual types for different keys use `TypedDict`s.
