### ISSUE TITLE
typeshed directory empty 

### ISSUE THREAD

**Issue by timsoftgit** [python/mypy#6279]
* Are you reporting a bug, or opening a feature request? bug
* What are the versions of mypy and Python you are using? 0.660 and 3.6.7
typeshed directory in tar.gz source is empty in release 0.660
is that intentional? It may be a git bug as it looks like typeshed is a link to typeshed project, the contents used to be included in the source - see release 0.650 source tar.gz but is now missing. How can I work around it?

**Comment by timsoftgit** [comment]
my work-around:
version on https://files.pythonhosted.org/packages/a4/f6/032e015285905243cff94625367c7a20ba0acbae8e802b740c8a876b2f39/mypy-0.660.tar.gz
is ok (contains typeshed files). it is still worth finding out why github source tar.gz is missing the files though.

**Comment by ethanhs** [comment]
Github does not include submodules in their source snapshots. I do not recommend trying to use those, instead use the source package from PyPi. I believe Github would have to change its behavior, which is out of our control.

**Comment by timsoftgit** [comment]
thanks for the reply. I'll stick with mypy for source downloads then, and only use github for version checking.
