### ISSUE TITLE
`x = tuple()  # type: Tuple[()]` Incompatible types in assignment

### ISSUE THREAD

**Issue by asottile** [python/mypy#6283]
I understand this is a silly example, but figured I'd report it anyway.

I can't find a way (other than `# type: ignore`) to silence mypy for this line:

```python
x = tuple()  # type: Tuple[()]
```

I found #4211 (which is how I got to `Tuple[()]`

mypy 0.660 errors with:
```
testing/resources/builtin_constructors.py:13: error: Incompatible types in assignment (expression has type "Tuple[<nothing>, ...]", variable has type "Tuple[]")
```

**Comment by gvanrossum** [comment]
I don't think this is a bug. Every `tuple` call returns a `Tuple[T, ...]` for some `T`, which is not the same as an empty tuple -- it is a tuple containing an arbitrary number of `T`s.

Unless you have an actual use case I don't think we should try to special-case calling `tuple()` without arguments. (It's a class constructor, not a function, so you can't use standard overload syntax to say it returns an empty tuple when called without arguments.)

**Comment by JelleZijlstra** [comment]
`x = ()  # type: Tuple[()]` works fine. I don't think this is worth any special casing in mypy. We're discussing adding a special case in typeshed instead, though I'm skeptical about that too.
