### ISSUE TITLE
New semantic analyzer: dummy alias definitions in typing stub (List etc.)

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6297]
Support definitions for built-in type aliases `List`, `Set` in the stub for `typing`. Currently these don't work, which is a problem since typeshed includes these, whereas test fixtures don't.

**Comment by ilevkivskyi** [comment]
FWIW I just whitelisting some test cases to the new semantic analyzer, and it looks like many of them are blocked by this:
```
Actual:
  tmp/builtins.pyi:1: error: Module 'typing' has no attribute 'List' (diff)
  tmp/builtins.pyi:1: error: Module 'typing' has no attribute 'Set' (diff)
```
I will work on this next to unblock the situation.

**Comment by JukkaL** [comment]
Note that my current working branch makes changes to how the aliases are handled.
