### ISSUE TITLE
New semantic analyzer: conditionally defined functions

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6318]
Support conditionally defined functions was dropped at some point when implementing the early versions of the new semantic analyzer. It's probably worth implementing this from scratch since the old implementation was pretty messy.

This issue applies to functions where multiple definitions are considered reachable by mypy. Cases involving platform and Python version checks where only one implementation is reachable already work. Example where this applies:

```py
if cond():  # Condition determined at runtime!
    def foo() -> None:
        ... # something; will be checked
else:
    def foo() -> None:
        ... # something else; will also be checked
```

**Comment by ilevkivskyi** [comment]
A clean solution for this may be non-trivial. In general we might need to switch from `node.node` to `node.nodes`, this will also allow us to support conditional definition of variables, conditional imports etc., but this is a big change. It seems to me there is a whole bunch of issues around conditional definitions and it would make sense to discuss/fix them together.

**Comment by JukkaL** [comment]
I was thinking of just cleaning up the implementation a bit now, without changing their behavior or general implementation strategy.

**Comment by ilevkivskyi** [comment]
We also will need to support something like this:
```python
if cond():
    func: Callable[[str], Sequence[int]] = ...
else:
    def func(spec: str) -> Sequence[int]:
        ...
```
This is supported by old analyzer, and there are examples of this in our internal code (currently this causes a crash).
