### ISSUE TITLE
pip install mypy :  fails with Python 3.4 install

### ISSUE THREAD

**Issue by Dedoig** [python/mypy#632]
I get this:
ImportError: Python 3.4 is not supported by DBUtils.

OSX 10.9.4, anaconda with Python 3.4

Any suggestions? ...

**Comment by kirbyfan64** [comment]
To install mypy with pip, you need to install the package labeled `mypy-lang`, not `mypy`. The latter is 100% unrelated.

@JukkaL You should put a notice saying the packages are different. This is the third time I've seen an issue related to installing the wrong package.

**Comment by Dedoig** [comment]
Ah, thanks. Sorry I had not read that carefully.

Any idea if the current mypy-lang install follows python's paths to resolve imports etc. before doing the type check?

**Comment by kirbyfan64** [comment]
@Dedoig 

1. I'm not sure if mypy respects PYTHONPATH, but I do know that it has its own MYPYPATH.
2. Again, no clue. I don't think so.

**Comment by rbtcollins** [comment]
You can pass --use-python-path according to mypy -h.
