### ISSUE TITLE
New semantic analyzer: abstractness calculations

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6322]
It's not clear if abstractness related properties can be calculated during the main pass. MROs will be complete, but namespaces of some base classes currently may be incomplete. One option would be to defer subclasses until all base classes have complete namespaces. This takes advantage of the fact that function decorators are analyzed as part of class top levels.

**Comment by ilevkivskyi** [comment]
I think this one should also be high priority, since the solution might affect larger scale logic (an additional pass?)

**Comment by JukkaL** [comment]
Agreed.
