### ISSUE TITLE
New semantic analyzer: way to use existing tests

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6327]
Make it possible to use existing tests with the new semantic analyzer. Not sure what's the best way to do this. Here are some random ideas:
* Provide a command line flag or environment variable to run arbitrary tests with the new semantic analyzer.
* Make it possible to opt in some tests into being run using the new semantic analyzer (along with the normal semantic analyzer). One idea is to keep a separate list of `.test` files that pass with the new semantic analyzer.

It would be nice to also run (selected) existing tests with the new semantic analyzer in CI, but that's not absolutely necessary at first.

**Comment by ilevkivskyi** [comment]
I think we should have a list of `.test` files, and gradually move them if they are clean. I would propose to start adding them in the next few days. I can take care of this after I finish named tuples and typed dicts.

**Comment by ilevkivskyi** [comment]
This is fixed by https://github.com/python/mypy/pull/6335
