### ISSUE TITLE
Missing Attribute Error on pytest.fixture

### ISSUE THREAD

**Issue by MisterBianco** [python/mypy#6331]
Please provide more information to help us understand the issue:

This is potentially both a bug and a feature request.
```python3
@pytest.mark.incremental
@pytest.mark.usefixtures("driver")
class TestNeatLogin(object):
    def test_hello(self) -> None:

        self.driver << Neat().home_page
        assert "hi" in self.driver.url
```
self.driver is the pytest fixture from a conftest file and is just a wrapper for selenium (unimportant)

Output of mypy --disallow-untyped-defs --ignore-missing-imports test_neat.py:
```
test_neat.py:18: error: "TestNeatLogin" has no attribute "driver"
```

I was hoping it would detect the fixture and move on

Environ:
```
    mypy: 0.660
   python: 3.7
```

I can try installing from master if anyone feels like that will fix the issue, just curious what I can do to either: fix the issue or ignore these particular errors.

**Comment by ilevkivskyi** [comment]
There is no way mypy can detect this. Potentially, one can write a mypy plugin (but again mypy core team has no bandwidth for this). Your best choice for now is just to use `# type: ignore` to silence the error.

**Comment by MisterBianco** [comment]
Ok thank you, I assume the comment is put at the top of the source file?

**Comment by ilevkivskyi** [comment]
On the line with error.

**Comment by MisterBianco** [comment]
Is there a way to ignore all instances of the same error?
Since it generates like 40 errors of the same type?

**Comment by ilevkivskyi** [comment]
Ignoring part of a file is not implemented yet, see https://github.com/python/mypy/issues/626. You can however just add `ignore_errors = True` for that file(s) in `mypy.ini` (some people do this for tests, because fixtures and mocks cause many false positives).

**Comment by JukkaL** [comment]
It may also be helpful to explicitly declare the attribute that mypy thinks is missing in the class body.
