### ISSUE TITLE
Cannot find internal library

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [python/mypy#6343]
(I'm using Python 3.6.4 and MyPy version 0.660.)

When I run MyPy it complains that it can't find a module. According to [the MyPy docs](https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports), I should be able to add the relevant directories to the `MYPYPATH` variable. Here's how I've done that:

(base) root@127:/mnt# pwd
/mnt
(base) root@127:/mnt# MYPYPATH=.:python:python/build:./python:./python/build:/mnt:/mnt/python:/mnt/python/build

(I'm running this code in a Docker container, which is why everything is rooted at `/mnt`.) Note that I've added every directory I can imagine is relevant in both relative and absolute terms. I even added them relatively in two different ways: one preceded by ./, the other not so.

Here is the error that I get:

```
(base) root@127:/mnt# mypy python/build/common.py
python/build/common.py:2: error: Cannot find module named 'python.build.classes'
python/build/common.py:2: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

I checked for typos and don't see any: Here is the file I'm trying to typecheck:

```
(base) root@127:/mnt# head python/build/common.py
import sys
from python.build.classes import Correction
import numpy as np
import pandas as pd

[skip a few lines]

(base) root@127:/mnt#
```

and here is the head of the file MyPy says it can't find:

```
(base) root@127:/mnt# head python/build/classes.py
import numpy as np
import math

class File:

[skip a few lines]

(base) root@127:/mnt#
```

**Comment by hauntsaninja** [comment]
Closing since stale (mypy 0.660 was a long time ago)
