### ISSUE TITLE
mypy only checking dataclass usage in global scope

### ISSUE THREAD

**Issue by yang** [python/mypy#6352]
* Are you reporting a bug, or opening a feature request?

Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
from dataclasses import dataclass, field
@dataclass
class C:
    a: int
    b: int
C(a=0) # correctly get an error
def f():
    C(a=0) # no error for this line
```

* What is the actual behavior/output?

Only get an error for the first call to C().

* What is the behavior/output you expect?

Error for each of the calls to C().

* What are the versions of mypy and Python you are using?

mypy 0.660
Python 3.7.2

* Do you see the same issue after installing mypy from Git master?

Yes

* What are the mypy flags you are using? (For example --strict-optional)

```
mypy .
```

**Comment by ilevkivskyi** [comment]
This is not specific to dataclasses, mypy doesn't check untyped functions at all, unless you pass `--check-untyped-defs`

**Comment by yang** [comment]
Oops, yep that was it. Thanks.
