### ISSUE TITLE
Runtime type checking of Literal types / accessing Literal type values at runtime

### ISSUE THREAD

**Issue by yang** [python/mypy#6353]
Is there a way to access the values in a Literal at runtime? Or otherwise get runtime checks for literals without repeating the literal values in your code?

For instance, if you have:

```
Month = Literal[
    'January',
    'February',
    ...
]
```

You could write a function by hand:

```
def ensure_month(x: str) -> Month:
  return x in ['January','February',...] # Would be neat to simple say something like Month.values
```

**Comment by ilevkivskyi** [comment]
On some Python versions you can access them as `Month.__args__` but this is undocumented API. Also please don't open issues with questions there is Gitter chat for this.

**Comment by marwan116** [comment]
@ilevkivskyi thank you for your amazing efforts on mypy,

I must say that reading this github issue helped me resolve my problem of accessing Literal type values at runtime. It makes me skeptical of gitter given it doesn't lend itself nicely to search engines like google. Curious to hear your thoughts on it if you ever get the chance

**Comment by JelleZijlstra** [comment]
@marwan116 for what it's worth, we now provide https://github.com/python/typing/discussions for typing-related questions.

**Comment by ilevkivskyi** [comment]
I used to be quite active on Gitter couple years ago, but I now rarely even open it. FWIW it is much higher chance to find me in Github issues (but it still may take time for me to respond).

**Comment by marwan116** [comment]
I see - thank you @JelleZijlstra and @ilevkivskyi for taking the time to respond!
