### ISSUE TITLE
Run against all of Python standard library modules and report issues

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#636]
Run mypy against all Python 3.7 standard library modules (that are implemented in Python and have no missing C extension dependencies) and file bogus errors that mypy reports as bugs.

**Comment by JukkaL** [comment]
I think that we should do this in the near future, maybe as part of a more general project to fix false positives.

**Comment by ethanhs** [comment]
I went ahead and did this on my flight home. I'll start filing issues, but my raw notes are here: https://gist.github.com/ethanhs/ccab320935ba8705949472190d77a4b7

**Comment by ethanhs** [comment]
Okay I filed issues for everything there doesn't already seem to be an issue for. Let me know if there are further questions/concerns.

**Comment by ilevkivskyi** [comment]
Since individual issues are opened now, should we close this one?

**Comment by JelleZijlstra** [comment]
@ethanhs this is great! Are you also going to report the typeshed issues you found?

**Comment by ethanhs** [comment]
Closing as I've opened issues for the bugs in mypy and https://github.com/python/typeshed/issues/2149 for typeshed.

**Comment by JukkaL** [comment]
@ethanhs Thank you for doing this! Fixing bogus errors generated from unannotated code is important, since this is the first thing many users experience when trying out mypy, and we want the first impression to be a good one :-)
