### ISSUE TITLE
Errors not raised within class methods

### ISSUE THREAD

**Issue by vivaldus** [python/mypy#6373]
* Are you reporting a bug, or opening a feature request?
Bug

* What is the actual behavior/output?
No errors caught within class methods

* What is the behavior/output you expect?
Error raised within class method

* What are the versions of mypy and Python you are using?
mypy version 0.660
python version 3.7.2

* Please insert below the code you are checking with mypy:

Example:

```python
class TestClass:
    def __init__(self):
        print('instance created')

    def some_method(self):
        print('xxx')
        aaa: int = 1.2   # No type error raised in class method

aaa: int = 1.2   # Type error raised outside of class scope
```

**Comment by msullivan** [comment]
This is expected behavior. mypy only typechecks functions that have type annotations.

**Comment by vivaldus** [comment]
Ah, OK. Thanks for explanation.

**Comment by vivaldus** [comment]
For others interested in having this (and other stricter type checks), you can enable such checks by supplying a `mypi.ini` configuration file and adding the rule `check_untyped_defs = True`. See here for further details: https://mypy.readthedocs.io/en/latest/config_file.html#per-module-and-global-options
