### ISSUE TITLE
Mypy and Asyncio import cannot be skipped

### ISSUE THREAD

**Issue by Mulugruntz** [python/mypy#6383]
As it seems to be an issue on mypy and on asyncio, I've reported it on [both sides](https://bugs.python.org/issue35987), even though I'm not sure exactly where the problem(s) is(are).

Some asyncio modules cannot be found with mypy. And cannot be silenced/skipped by mypy.

Have the following 3 files:
```python
# example1.py
from asyncio import BaseEventLoop  # Module 'asyncio' has no attribute 'BaseEventLoop'
from asyncio import Semaphore  # OK
import aiostream  # gets skipped correctly
import asyncio  # OK
asyncio.windows_events.WindowsProactorEventLoopPolicy()  # Module has no attribute 'windows_events'
asyncio.WindowsProactorEventLoopPolicy()  # Module has no attribute 'WindowsProactorEventLoopPolicy'
```

```python
# mypy.ini
[mypy]
python_version = 3.7

[mypy-asyncio,aiostream]
follow_imports = skip
ignore_missing_imports = True
```

```python
# Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
mypy = "==0.670"
aiostream = "==0.3.1"

[requires]
python_version = "3.7"
```

```
$> pipenv install
#...
$> pipenv run python -m mypy --config-file mypy.ini example1.py
example1.py:1: error: Module 'asyncio' has no attribute 'BaseEventLoop'
example1.py:5: error: Module has no attribute "windows_events"
example1.py:6: error: Module has no attribute "WindowsProactorEventLoopPolicy"
```

Why Semaphore (and others) works and BaseEventLoop (among others) doesn't work... no idea.
But it completely breaks mypy that it somehow cannot be skipped nor silenced.

**Comment by tirkarthi** [comment]
This is be a typeshed issue. Please see : https://github.com/python/typeshed/issues/2313

**Comment by ilevkivskyi** [comment]
Yes, this is a typeshed issue. Also `ignore_missing_imports` ignores missing modules (absent stubs), not module attributes (incomplete stubs).

> But it completely breaks mypy that it somehow cannot be skipped nor silenced.

Have you heard about `# type: ignore`?

**Comment by Mulugruntz** [comment]
@ilevkivskyi Yes, in the meantime I've used (and abused of) `# type: ignore`... which was what I was trying to avoid ;-)
Thanks for the info.
