### ISSUE TITLE
Annotating a type you don't have direct access to

### ISSUE THREAD

**Issue by SKHecht** [python/mypy#6402]
This is a very specific use case of mypy, but I am trying to type a project that is using an untyped package. The package defines a class/variable like this:
```
# package/token.py
class NullToken(object):
    ...
NullToken = NullToken()
```
which I wrote a stub for like this:
```
# stubs/package/token.pyi
class _NullToken(object):
    ...
NullToken: _NullToken
```
I'm trying to declare a type alias for a callable that takes in a union containing that type:
```
# my_project.py
F = Callable[[Union[int, type(NullToken)]], None]
```
This code runs fine, but mypy says "Invalid type alias". The problem is that I can't reference the class `NullToken` directly in python, because it is overwritten by `NullToken = NullToken()`. I also can't reference `_NullToken` in my project because it will cause python to crash (because it is only defined in the stub). I also can't use `Type[NullToken]` because `NullToken` isn't a type.

I understand why using `type` doesn't work, given that it is a function that evaluates at runtime.  But would it be possible for mypy to evaluate `type(NullToken)` to the class that `NullToken` instantiates?

Here's a single file that shows the problem at hand:
```
class _NullToken(object):
    pass
NullToken = _NullToken()

from typing import Callable, Union

reveal_type(NullToken)
F = Callable[[Union[int, type(NullToken)]], None]
```
and here's the mypy output for it:
```
test.py:7: error: Revealed type is 'test._NullToken'
test.py:8: error: Invalid type alias
```
As we can see, mypy does know the type of `NullToken`, I just need to be able to use that type in an annotation. I'll admit there very well may be issues with making type(<var>) a valid type annotation that haven't occurred to me, but it seems like a reasonable solution.

**Comment by ilevkivskyi** [comment]
Use this:
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from package.token import _NullToken

F = Callable[[Union[int, '_NullToken']], None]
```
