### ISSUE TITLE
ignoring errors not working (# type: ignore)

### ISSUE THREAD

**Issue by squarewave24** [python/mypy#6410]
I searched through existing issues, and saw the ```# type: ignore``` method, but doesn't seem to work: 

```
from flask import Flask  # type: ignore

app = Flask(__name__)

log = config.configure_logging(app)
log.info('Starting Flask Demo with environment {0}'.format(config.ENVIRONMENT))
app.config.from_object(config)
app.config.from_envvar('APP_SETTINGS', silent=True)

app.config.from_object(config)
app.config.from_envvar('APP_SETTINGS', silent=True)
```

> api/app.py:22: error: "Dict[str, Any]" has no attribute "from_object"
> api/app.py:23: error: "Dict[str, Any]" has no attribute "from_envvar"

**Comment by ilevkivskyi** [comment]
1. This is a typeshed issue, not mypy issue
2. It is already fixed in typeshed, wait for next release
3. `# type: ignore` should be put on the line where error appears.

**Comment by squarewave24** [comment]
thanks that worked, 

this was the referenced thread, and # type ignore is on the import 

https://github.com/python/mypy/issues/500

**Comment by abij** [comment]
Note its`# type: ignore` (with the colon) as described in [PEP-484](https://www.python.org/dev/peps/pep-0484/#compatibility-with-other-uses-of-function-annotations)
