### ISSUE TITLE
Speed-up tests by reorganizing fixtures to not import typing when not needed

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#6428]
#6427 added typing import to `lib-stub/builtins.pyi` and `lib-stub/__builtins__.pyi`. This causes some slow down for tests (up to 9% for fast tests). We need to figure out how to speed-up tests without losing correctness (like `tuple` should be generic).

**Comment by JukkaL** [comment]
Using a custom fixture for `tuple` would likely get us close to the original performance, at the cost of having to modify over 400 test cases. We can probably script the update, though, so it does not need to be a big deal.

Increasing priority since this is a regression.

**Comment by JukkaL** [comment]
Updating `__builtins__.pyi` is probably not necessary, since this seems to be used by only around 100 test cases.
