### ISSUE TITLE
Support attr converters with new semantic analyzer

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#6438]
This is a follow up for https://github.com/python/mypy/pull/6435

The `attrs` plugin does some tricky things to support converters, in particular although the plugin is called during semantic analysis, it look like some parts belong to type checking. In particular, we need to know analyzed types of overloaded functions while still semantically analyzing top levels, which is especially tricky with the new semantic analyzer.

See also `testAttrsUsingBadConverter`.

**Comment by danie1k** [comment]
I've just ran with an issue with `converter`. Just a sample piece of code:
```python
from distutils.version import LooseVersion
import attr

@attr.s
class Manifest:
    version: LooseVersion = attr.ib(converter=LooseVersion, default='1.0')
```

And the output from mypy:
```
tst.py:6: error: Incompatible types in assignment (expression has type "str", variable has type "LooseVersion")
tst.py:6: error: Argument "converter" has incompatible type "Type[LooseVersion]"; expected "Optional[Callable[[Any], str]]"
```

The value given in `default` is always passed through `covnerter` before assigning to property.

**Comment by ilevkivskyi** [comment]
@danie1k your problem is unrelated to this issue and is a duplicate of https://github.com/python-attrs/attrs/issues/518

**Comment by danie1k** [comment]
@ilevkivskyi Thanks! :+1: 
I didn't thought about searching `attrs` issues in this case.
