### ISSUE TITLE
New semantic analyzer: support recursive TypedDicts and NamedTuples

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#6445]
These have (limited) support in old analyzer, with new semantic analyzer they just crash.

**Comment by ilevkivskyi** [comment]
There are some tests skipped with `--no-new-semantic-analyzer` that needs to be fixed.

**Comment by JukkaL** [comment]
Recursive type aliases are similar.

**Comment by ilevkivskyi** [comment]
I will take care of this issue.

**Comment by JukkaL** [comment]
I have a work-in-progress branch that turns these into blocking errors.

**Comment by JukkaL** [comment]
I think that this is now mostly resolved. Added #7111 as a follow-up issue.

**Comment by ilevkivskyi** [comment]
@JukkaL 
> I think that this is now mostly resolved. Added #7111 as a follow-up issue.

There are 7 tests that refer to this issue as an excuse, should we enable them first?
```
test-data/unit/check-classes.test:4358:# FIXME: #6445
test-data/unit/check-classes.test:4367:# FIXME: #6445
test-data/unit/check-classes.test:4375:# FIXME: #6445
test-data/unit/check-classes.test:4390:# FIXME: #6445
test-data/unit/check-unions.test:960:# https://github.com/python/mypy/issues/6445
test-data/unit/check-flags.test:1056:# Crashes on new semantic analyzer: https://github.com/python/mypy/issues/6445
test-data/unit/check-flags.test:1065:# Crashes on new semantic analyzer: https://github.com/python/mypy/issues/6445
```

**Comment by JukkaL** [comment]
Yeah, let's go through all of those issues firs.
