### ISSUE TITLE
New semantic analyzer: ClassVar

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6451]
Inheriting the class variable bit is a bit tricky. We can't do it fully in the main pass, since base class bodies may not have been fully processed yet. The old semantic analyzer does this in pass 3, which doesn't exist in the new semantic analyzer. The class variable bit needs to be set before type checking. Maybe the best option is to do this similar to how abstract status is calculated, in a pass between semantic analysis and type checking.

**Comment by JukkaL** [comment]
Another alternative might be to defer if the attribute is not ready in a base class, but there might not be an easy way to determine this generally, and this seems potentially fragile.

**Comment by ilevkivskyi** [comment]
The first option is probably a cleaner solution. We already have few "micro-passes", we can add one more.
