### ISSUE TITLE
Type checking seems to stop after 2 isinstance checks

### ISSUE THREAD

**Issue by euresti** [python/mypy#6464]
I was refactoring some code and mypy said it was fine but my tests failed.
I narrowed it down to some pretty weird code that uses `isinstance` twice.  It looks like mypy just stops either checking or emitting errors.  Not even `reveal_type` shows anything.

Here's the smallest repro I could come up with:

```
from abc import ABC
from typing import List
class MyBase(ABC):
    ...
class A(MyBase):
    ...
class B(MyBase):
    ...

def foo() -> None:
    txns: List[MyBase] = []
    reveal_type(txns)
    txn = txns[0]
    reveal_type(txn)
    assert isinstance(txn, A)
    reveal_type(txn)
    # This next line is optional.  Both will trigger the bug.
    # txn = [txn for txn in txns if False][0]
    reveal_type(txn)
    assert isinstance(txn, B)
    # Type checking seems to stop here. The reveal_types don't get printed
    reveal_type(txn)
    reveal_type(56)
    # And no error is printed about the assignment.
    txn = 67
```
If I remove either of the `isinstance` checks then it works fine.

However it doesn't happen if the file is just `foo.py` It has to be in `src/my_module/foo.py` probably with a blank `__init__.py` next to it.
mypy 0.670

**Comment by gvanrossum** [comment]
It is a (questionable) feature that mypy skips code it deems unreachable because isinstance() cannot be true.

**Comment by JukkaL** [comment]
The reachability checks should perhaps only be applied when there is a type variable with a value restriction being used.

**Comment by euresti** [comment]
Oh this is very strange. 
```
    # This next line is optional.  Both will trigger the bug.
    txn = [txn for txn in txns][1]
```
Will trigger the bug.
But if I change it to 
```
    # This next line is optional.  Both will trigger the bug.
    txn = [txn2 for txn2 in txns][1]
```
The bug goes away.

So it's because I'm using the variable name inside the list comprehension.  But the real code isn't actually buggy.

```
def foo() -> None:
    txns: List[MyBase] = [A(), B()]
    reveal_type(txns)
    txn = txns[0]
    reveal_type(txn)
    assert isinstance(txn, A)
    reveal_type(txn)
    # This next line is optional.  Both will trigger the bug.
    txn = [txn for txn in txns][1]
    reveal_type(txn)
    assert isinstance(txn, B)
    # Type checking seems to stop here. The reveal_types don't get printed and
    # No error is printed about the assignment.
    reveal_type(txn)
    reveal_type(56)
    txn = 67
```

Either way, it would be nice if mypy maybe would tell you that it thinks that the `assert isinstance(txn, B)` would always fail.

**Comment by erictraut** [comment]
I think this bug has been fixed along the way. It no longer occurs with the latest version of mypy.
