### ISSUE TITLE
Decide which technical terms to use and stick to them

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#65]
We should decide which technical terms to prefer for various language constructs (etc.) in the source code and implementation documentation. This would make the code more consistent and easier to read. 

These don't have to be the same as in user-facing documentation. For example, brevity might be more desirable than conformance to Python conventions.

Here are some choices we need to make:

 * data attribute / field / data member / member variable
 * base class / superclass
 * base interface / implemented interface / superinterface
 * a subclass / a derived class
 * inherit / inherit from / extend (a class)
 * implement an interface / extend an interface / inherit an interface
 * attribute / member (for both data attributes and methods)
 * method / member function

Please state your preferences, if any, in comments. You can also propose additional concepts and terms.

**Comment by gvanrossum** [comment]
@JukkaL Do you still carea bout this?

**Comment by JukkaL** [comment]
Not really. The terms used in the code haven't caused trouble to my knowledge, so this doesn't seem like a priority. Closing.
