### ISSUE TITLE
Add type fullname to AnalyzeTypeContext

### ISSUE THREAD

**Issue by mkurnikov** [python/mypy#6503]
In the hooks returned from 
```
    def get_type_analyze_hook(self, fullname: str
                              ) -> Optional[Callable[[AnalyzeTypeContext], Type]]: pass
```
user needs to create `Instance` objects in the hook, so `fullname` required there, but `UnboundType` does not have it. 

Surely, user can make a callable factory and initialize it wil a fullname, but it would be so much easier just to get it from context object.

**Comment by ilevkivskyi** [comment]
"make a callable factory and initialize it with a fullname" is literally one line:
```python
from functools import partial

def get_type_analyze_hook(fullname):
    if interesting_name(fullname):
        return partial(my_hook, fullname)
    return None

def my_hook(fullname, ctx):
    # you have fullname here
    ...
```
Do we really need to add this field to the context (then why not to all contexts) if one can get it (if necessary) with a single line? After all Python is not Java.

**Comment by mkurnikov** [comment]
Yes, you're right.
