### ISSUE TITLE
~ is not working in mypy.ini/cache_dir

### ISSUE THREAD

**Issue by jolaf** [python/mypy#6508]
I'd like to create a unified mypy cache for all my projects and store it in my home directory.

Moreover, I'd like other developers, as well as CI scripts, to do the same - storing cache in THEIR home directories on their local machines.

For that, I specify in mypy.ini:

`[mypy]`
`cache_dir=~/.mypy_cache`

But that's not working as mypy creates directory `~` in the current directory instead of creating `.mypy_cache` in my home directory.

I'm using mypy 0.670 from pip on Ubuntu.

**Comment by gvanrossum** [comment]
This seems a simple enough fix. Can you try your hand at sending us a PR?

**Comment by jolaf** [comment]
Unfortunately, I couldn't find the clear place in the code to easily fix this.

**Comment by aaalex5** [comment]
I was looking into working on this feature, when I look into "mypy.ini" I see"
```
[mypy]
mypy_path = ..
```
I was wondering if there would be some way to implement this feature? If anyone would want to give some help in guiding me to do this?

**Comment by jolaf** [comment]
Thank you very much!!

**Comment by weilbith** [comment]
The [documentation](https://mypy.readthedocs.io/en/latest/config_file.html#id2) states to support home (I guess this means `~`) and environment variables. But [the code](https://github.com/onlined/mypy/blob/7aedb1addb20227b61b133a28bc3352a080e881b/mypy/main.py#L1008) only expands the `~`. So instead of only calling `os.path.expanduser()`, I would also expect a `os.path.expandvars()` call. This would be really neat, since then I can use `$XDG_CACHE_HOME/mypy`.

**Comment by ilevkivskyi** [comment]
@weilbith What do you mean by "would be", this was already added several weeks ago https://github.com/python/mypy/blob/master/mypy/config_parser.py#L42, why are you pointing to a 5-month old code in someones fork?

**Comment by weilbith** [comment]
Okay my fault. Should researches this better. Apparently this does not work for me. :frowning_face: Have to checkout why not.

**Comment by weilbith** [comment]
Okay, just because the most recent version is from Jul 12 and this has been just implemented 15 days ago.

**Comment by ilevkivskyi** [comment]
The next release will happen soon (likely this month or early September).

**Comment by revmischa** [comment]
eagerly awaiting this feature
