### ISSUE TITLE
Logical 'and' inferred incorrectly

### ISSUE THREAD

**Issue by jolaf** [python/mypy#6512]
```python
from typing import Optional

class A:
    x = 'x'

a: Optional[A] = A()

v: Optional[str] = a and a.x
```

`mypy` complains:
`Incompatible types in assignment (expression has type "Union[A, None, str]", variable has type "Optional[str]")`

However in this situation the type of the expression can never be `A`.

**Comment by henribru** [comment]
This is only the case if A is truthy. If you define it like this for example, v will be an `A`:
```
 class A:
    x = 'x'
    
    def __bool__(self):
        return False

a = A()

v: str = a and a.x
```

**Comment by jolaf** [comment]
Okay, then what is the proper way to handle this?

```python
v: Optional[str] = cast(Optional[str], a and a.x)`
```
?

**Comment by gvanrossum** [comment]
Use a conditional expression:
```py
v: Optional[str] = a.x if a else None
```
This isn't going to change in mypy, so I'm closing it.
