### ISSUE TITLE
[question] handling a class with generated methods

### ISSUE THREAD

**Issue by AMDmi3** [python/mypy#6519]
Simplifying, I have a class with only constructor defined in code, and this constructor adds methods to class instance in runtime with `setattr`. mypy obviously complains `error: "MyClass" has no attribute "my_method"` on each call to these generated methods. How do I silence these errors without adding `# type: ignore` to each call?

**Comment by AMDmi3** [comment]
Example:
```python
class MyDynamicClass:
    def __init__(self):
        def dynmethod():
            print('calling dynmethod')

        setattr(self, 'dynmethod', dynmethod)

MyDynamicClass().dynmethod()
```
```shell
% python 1.py
calling dynmethod
% mypy 1.py
1.py:8: error: "MyDynamicClass" has no attribute "dynmethod"
```

**Comment by gvanrossum** [comment]
You can do something like
```py
import typing
class MyDynamicClass:
    if typing.TYPE_CHECKING:
        def __getattr__(self, name) -> Any: pass
```
