### ISSUE TITLE
Signature of "<classmethod>" incompatible with supertype "A"

### ISSUE THREAD

**Issue by Alexhuszagh** [python/mypy#6561]
# Issue

I am reporting a bug where mypy accidentally erases the return type of classmethods in `check_method_override_for_base_with_name`, and creating a signature for the base class with a return type of `<nothing>`.

# Reproducing

I am currently using version "0.670" of mypy on Python 3.7.2 (final release), however, I've confirmed the logic error is present on master. After running the following sample code through mypy (using the default arguments, `mypy $file`, I get the following error: `mypytest.py:14: error: Signature of "load" incompatible with supertype "A"`.

```python
from __future__ import annotations
import typing

T = typing.TypeVar('T', bound='A')

class A:
    @classmethod
    def load(cls: typing.Type[T], x) -> T:
        raise NotImplementedError


class B(A):
    @classmethod
    def load(cls: typing.Type[B], x: int) -> B:
        return cls()
```

# Expected Behavior

This example should trivially pass, so traced calls until I could find the issue. (I'm using diff syntax highlighting just so I can highlight the key lines). 

The return type was being erased in `bind_self`, which was being called from `check_method_override_for_base_with_name`.

```diff
def bind_self(method: F, original_type: Optional[Type] = None, is_classmethod: bool = False) -> F:
    if isinstance(method, Overloaded):
        return cast(F, Overloaded([bind_self(c, original_type) for c in method.items()]))
    ...
    if func.variables and (isinstance(self_param_type, TypeVarType) or
                           (isinstance(self_param_type, TypeType) and
                            isinstance(self_param_type.item, TypeVarType))):
        ...

        ids = [x.id for x in func.variables]
+        typearg = infer_type_arguments(ids, self_param_type, original_type)[0]
+        if (is_classmethod and isinstance(typearg, UninhabitedType)
+                and isinstance(original_type, (Instance, TypeVarType, TupleType))):
+            # In case we call a classmethod through an instance x, fallback to type(x)
+            # TODO: handle Union
+            typearg = infer_type_arguments(ids, self_param_type, TypeType(original_type))[0]

        ...
    return cast(F, res)
```

Unusually simply for me, the fix for the expected behavior seemed to be already present: the next lines check if the typearg is `UninhabitedType`, and if the original function is a classmethod, in which case it uses a smarter `infer_type_arguments`. However, upon further inspect, `is_classmethod` was not being set to true. Looking back in `check_method_override_for_base_with_name` however showed the problematic lines of code: although `is_classmethod` is an available function parameter, it was never being used. Simply adding `context.is_class` (which `FuncBase.is_class` determines if the function is a classmethod) to both calls to `bind_self` fixed the behavior.

```diff
diff --git a/mypy/checker.py b/mypy/checker.py
index 2fb94e5f3a..609f791743 100644
--- a/mypy/checker.py
+++ b/mypy/checker.py
@@ -1359,7 +1359,7 @@ def check_method_override_for_base_with_name(
                 typ = defn.var.type
                 override_class_or_static = defn.func.is_class or defn.func.is_static
             if isinstance(typ, FunctionLike) and not is_static(context):
-                typ = bind_self(typ, self.scope.active_self_type())
+                typ = bind_self(typ, self.scope.active_self_type(), context.is_class)
             # Map the overridden method type to subtype context so that
             # it can be checked for compatibility.
             original_type = base_attr.type
@@ -1388,7 +1388,9 @@ def check_method_override_for_base_with_name(
             elif isinstance(original_type, FunctionLike) and isinstance(typ, FunctionLike):
                 if (isinstance(base_attr.node, (FuncDef, OverloadedFuncDef, Decorator))
                         and not is_static(base_attr.node)):
-                    bound = bind_self(original_type, self.scope.active_self_type())
+                    bound = bind_self(original_type, 
+                                      self.scope.active_self_type(),
+                                      context.is_class)
                 else:
                     bound = original_type
                 original = map_type_from_supertype(bound, defn.info, base)
```

**Comment by Alexhuszagh** [comment]
I've submitted the patches in a fork, but since there are currently no tests for this behavior, I have not yet submitted a pull request.
https://github.com/Alexhuszagh/mypy

Let me know if this is a confirmed issue, and if my patch seems logical. If so, I'll look at how to implement the tests.

**Comment by gvanrossum** [comment]
Why don't you use `T` in code for B as well? As you wrote it, someone could derive `C` from `B` and the type system would claim `C.load(...)` returns a `B` whereas the code shows it returns a `C`.

(There's also the issue that the type for `x` is narrower in the subclass than in the superclass -- in general arguments must var *contra-variantly*.)

**Comment by Alexhuszagh** [comment]
@gvanrossum My mistake, thanks for catching that `x` should not have been none. And yes, the code does work if I do the following, as I expected it to:

```python
import typing

T = typing.TypeVar('T', bound='A')
U = typing.TypeVar('U', bound='B')

class A:
    @classmethod
    def load(cls: typing.Type[T], x) -> T:
        raise NotImplementedError


class B(A):
    @classmethod
    def load(cls: typing.Type[U], x: int) -> U:
        return cls()
```

This may make more sense within context: the practical application I have a series of finalized models, which are recommended (via comments, not strictly enforced) that they should not be inherited from. It is true that defining typevars for all the finalized models would definitely be preferable if they were to be instantiated from. Actually enforcing this in the type-checker is a bit of an anti-pattern, so that's fully understandable.

I was more so worried about how the behavior of the function changes entirely for `is_classmethod` is passed to the function, but seeing other examples produce the exact same behavior, I more so understand what mypy is trying to do here.

```python
class Foo1:
    def bar(self) -> T:
        return A()


class Foo2(Foo1): 
    def bar(self) -> B:   # errors like the previous example, which is good
        return B()

```
