### ISSUE TITLE
Diagnostic levels are kind of a mess

### ISSUE THREAD

**Issue by msullivan** [python/mypy#6574]
The current situation is:

 * mypy can emit "notes", "warnings", and "errors"
 * Any diagnostics will result in an error exit code
 * (... except for many config file diagnostics, which don't)
 * Of options that are enabled by flags named `--warn-something`, we produce all three kinds of diagnostics:
    * `--warn-redundant-cast` produces a note
    * `--warn-return-any` produces a warning
    * Most seem to produce errors

We emit very few warnings, so I think the right approach is to just eliminate them (and "bare" notes emitted without an error) and turn them all into errors.

The other approach would be to make warnings able to not cause an error return and to reclassify certain warnings as errors. I don't have a real problem with this other than not wanting to do that reclassification. Doing the first would not prevent us from doing this in the future.

**Comment by ilevkivskyi** [comment]
https://github.com/python/mypy/pull/6472 looks related (in the sense it also tries to add some systematics to error reporting).
