### ISSUE TITLE
"Edit on GitHub" links in documentation hosted on readthedocs.io does not work

### ISSUE THREAD

**Issue by grantwwu** [python/mypy#6581]
e.g. https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages has a link at top right:

https://github.com/python/mypy/blob/origin/master/docs/source/installed_packages.rst

which goes nowhere.

**Comment by ethanhs** [comment]
Hm it appears there is an extra `/origin/` in the URL. I don't see anything that would cause that though.

**Comment by gvanrossum** [comment]
Try filing a bug with the readthedocs project.

**Comment by grantwwu** [comment]
It seems like this is an instance of https://github.com/rtfd/readthedocs.org/issues/5518

**Comment by ilevkivskyi** [comment]
I don't think there is anything actionable here for mypy.
