### ISSUE TITLE
@typing.no_type_check_decorator is nonfunctional

### ISSUE THREAD

**Issue by lunixbochs** [python/mypy#6583]
```
from typing import no_type_check, no_type_check_decorator

@no_type_check_decorator
def test(fn):
    return fn

@test
def blah(x: {'x': 1}):
    pass

@no_type_check
def blah2(x: {'x': 1}):
    pass
```

```
$ mypy notypecheck.py 
notypecheck.py:1: error: Module 'typing' has no attribute 'no_type_check_decorator'
notypecheck.py:8: error: Invalid type comment or annotation
```

I think this firstly needs a typeshed stub, but I think it won't work without special case support in mypy as well.

Related: https://github.com/python/typeshed/issues/2884

**Comment by gvanrossum** [comment]
Also related: #607. I propose that we should reserve #607 for the issue that `@no_type_check` doesn't work for classes, and use *this* (new) issue for the "meta" decorator `@no_type_check_decorator`.

**Comment by lunixbochs** [comment]
There's now a typeshed stub: https://github.com/python/typeshed/pull/3460#event-2830418450

**Comment by lunixbochs** [comment]
Can someone advise on how to track within mypy that a function acts as no_type_check? The current no_type_check appears to be handled via the hardcoded path in a few places.

**Comment by ilevkivskyi** [comment]
> Can someone advise on how to track within mypy that a function acts as no_type_check? The current no_type_check appears to be handled via the hardcoded path in a few places.

Although in general we don't like adding new flags to "important" nodes, it looks like in this case this is the only way (because the other way I see is keeping a global state, which is even worse). You can add a flag to `FuncDef` indicating whether this function can act as a `no_type_check` decorator, then check this flag on looked up node for every decorator that is a `RefExpr`.

**Comment by AlexWaygood** [comment]
`no_type_check_decorator` has now been deprecated in Python 3.13, with removal scheduled for Python 3.15: https://github.com/python/cpython/issues/106309.
