### ISSUE TITLE
"Name is not defined" on module member type constraint

### ISSUE THREAD

**Issue by alekratz** [python/mypy#6587]
Not sure if this one has been reported or not - I did a few searches in the issues and couldn't find an issue that replicated my situation.

I'm using mypy v0.670 on Python 3.7.2. I have something like this:

```python
import re

def go(pat: re.Pattern):
    pass
```

and I get this error back from mypy:

```
error: Name 're.Pattern' is not defined
```

If this is a known issue, feel free to close this one up.

**Comment by gvanrossum** [comment]
Use `typing.Pattern` instead.

**Comment by pozsa** [comment]
What if `re.Pattern` is a custom class defined in another module within your project?

**Comment by JelleZijlstra** [comment]
Then mypy shouldn't give a "name is not defined" error, because the name would be defined. If there's something more complicated going on, feel free to open a new issue that explains what you're seeing in more detail.

**Comment by pozsa** [comment]
Yeah, realized the error was in the user (me :))
