### ISSUE TITLE
mypy is not recognizing dynamically constructed namedtuple in type hint

### ISSUE THREAD

**Issue by zasdfgbnm** [python/mypy#6590]
The following code

```python
from typing import NamedTuple, get_type_hints

def f(x : NamedTuple('T1', [('a', int), ('b', int)])):
    return 1

print(get_type_hints(f))
```
prints `{'x': <class '__main__.T1'>}` correctly, but when checking with mypy using
`mypy test.py`

The following error is produced:
```
test.py:3: error: Invalid type comment or annotation
test.py:3: note: Suggestion: use NamedTuple[...] instead of NamedTuple(...)
```

Is this a bug?

**Comment by gvanrossum** [comment]
Do you have a real use case for this? That syntax is too complicated for mypy to recognize, and it seems unlikely that anyone would need this -- you should just define the type before using it. At best it's an odd feature request.

**Comment by zasdfgbnm** [comment]
@gvanrossum The use case is https://github.com/pytorch/pytorch/pull/16505

In PyTorch, we are adding namedtuple support to our JIT compiler. We rely on type hints to tell our JIT compiler the types of functions. But mypy report our unittest for this as an error...

**Comment by JukkaL** [comment]
I don't that this would make sense, since mypy named tuples use nominal subtyping. That's also how they work at runtime:

```py
from typing import NamedTuple

N1 = NamedTuple('N1', [('x', int)])
N2 = NamedTuple('N2', [('x', int)])

print(isinstance(N1(1), N1)) # True
print(isinstance(N2(1), N1)) # False
```

Mypy would not accept the example in https://github.com/pytorch/pytorch/pull/16505 even if `NamedTuple(...)` was allowed in a type annotation because of this issue -- the two named tuple types would be assumed to be incompatible.

For this to work as intended mypy would need something like protocols that are also treated as tuples, but the use case seems somewhat marginal to me. 

Why wouldn't the PyTorch compiler accept `NamedTuple` definitions that live outside the function definition? Is it important for you to support this sort of structural subtyping?

**Comment by zasdfgbnm** [comment]
@JukkaL Yes I agree with you. It's a good point.

> Why wouldn't the PyTorch compiler accept NamedTuple definitions that live outside the function definition?

This is mainly implementation issue. Accepting NamedTuple definitions outside is definitely the correct way things should be done. Currently we are just hard coding the texts in type hints. And we need some simple way to tell the compiler the structural typing info.

> Is it important for you to support this sort of structural subtyping?

No, it's not an important feature. It just allows the users to write a bit cleaner code.

I will close this issue for now. We can keep discussing if you want.

**Comment by ilevkivskyi** [comment]
> For this to work as intended mypy would need something like protocols that are also treated as tuples, but the use case seems somewhat marginal to me.

Just a note that this is technically already possible (to some extent). One can define a protocol with `__getitem__()` overloaded on literals. Something like:
```python
class TwoTupleLike(Protocol[T, S]):
    first: T
    second: S
    @overload
    def __getitem__(self, item: Literal[0]) -> T: ...
    @overload
    def __getitem__(self, item: Literal[1]) -> S: ...
```
this is very approximate, and not tested, and will likely not work in some cases. Just wanted to mention that literal types _might_ be useful in similar cases sometimes.

**Comment by Juanlu001** [comment]
Linking some references to this issue:

* https://github.com/samuelcolvin/pydantic/issues/156
* "So what's really happening is the type expressions are pretending to be "just everyday python", but actually they have arbitrary restrictions (cannot be functions? need to work via overriding `__getitem__`?) that neither you nor I were aware of." https://news.ycombinator.com/item?id=18249259
