### ISSUE TITLE
Missing return statement for Optional[x]

### ISSUE THREAD

**Issue by swalladge** [python/mypy#6599]
* Are you reporting a bug, or opening a feature request? bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
from typing import Optional

def foo(a: bool) -> Optional[str]:
    if a:
        return 'true'


assert foo(True) == 'true'
assert foo(False) == None
```

* What is the actual behavior/output?

mypy complains about missing return statement.

* What is the behavior/output you expect?

no complaint. The type signature allows returning `None` (implicitely returned when no return statement)

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

mypy 0.670

* What are the mypy flags you are using? (For example --strict-optional)

defaults

**Comment by gvanrossum** [comment]
Sorry, this is intentional. IIRC it's written up somewhere in PEP 484 -- a function with a return type other than exactly `None` should have all `return` statements with expressions, and not fall off the bottom.

**Comment by swalladge** [comment]
Ok fair enough. Thanks. :)
