### ISSUE TITLE
Unbounded TypeVar implies call signature

### ISSUE THREAD

**Issue by markedwards** [python/mypy#6600]
I'm not sure if this is a bug or just me being clumsy.

My use-case is a deserialization function that takes a source string and either raises or returns an instance of the target class.  Since T is an unbounded TypeVar, I would hope that mypy would have no assumptions about its call signature, but it appears to assume (perhaps rightly) that it takes no arguments.

If I replace `Type[T]` with `Callable[..., T]` there is no complaint, but I would prefer to require a real class to be passed to target_class.
```python
T = TypeVar('T')

def deserializer(source: str, target_class: Type[T]) -> T:
    #
    # code that derives and validates kwargs
    #
    return target_class(**kwargs)  # Too many arguments for "object"
```

**Comment by gvanrossum** [comment]
Well, classes that don't implement `__init__` or `__new__` may only be called without arguments, so the type checker is correct. Presumably you have a common base class you can specify as upper bound for the type variable? And why don't you want to use `Callable[..., T]`? It may also be possible to use a Protocol type.

**Comment by markedwards** [comment]
Yes, I suspected this was correct on the part of the type checker, so thanks for confirming that.

The reason I don't want to use `Callable[..., T]` is that this implementation is specifically meant to work with dataclass instances, so I want to avoid the implication that any callable object will do.  Actually, I might annotate `target_class` as `Type[Dataclass]` but there is no such thing.

I have trouble importing Protocol due to being on Python 3.6.x at the moment, but I see that I can convince mypy if I define:

```python
class DataclassProtocol(ABC):

    @abstractmethod
    def __init__(self, **kwargs: Any) -> None:
        pass


T = TypeVar('T', bound=DataclassProtocol)
```

That seems like overkill compared to just accepting `Callable[..., T]`.

**Comment by gvanrossum** [comment]
You can import `Protocol` from `typing_extensions`.

**Comment by markedwards** [comment]
Thanks, really appreciate the help and quick responses.
