### ISSUE TITLE
Suggestion: a type for saying not of a type. E.g.: `Not[str]`.

### ISSUE THREAD

**Issue by guillaume-chevalier** [python/mypy#6603]
Suggestion: a type for saying not of a type. E.g.: `Not[str]`.

If it exists already, I couldn't find it in the docs.

**Comment by JukkaL** [comment]
Such feature does not exist. There's a similar existing proposal in the typing repository: https://github.com/python/typing/issues/599. Perhaps you should continue the discussion there, or if your suggestion is significantly different from the existing proposal, you could create a new issue in the typing repository. We generally discuss new type system features in the typing repository first, at least if they seem sufficiently general-purpose.
