### ISSUE TITLE
Right way to deserialize json value

### ISSUE THREAD

**Issue by juanfernandoe** [python/mypy#6605]
Hi,

Could anyone explain to me the preferred way to convert json file to typed structure?

Actually, I'm doing the next and works but can't use p.firstName as object
property regardless I remove TypedDict inheritance

```
class Class1:

    @dataclass
    class DataType1(TypedDict):
        firstName: str
        lastName: str

    def readJSON1(self) -> None:
        with open("data.json", "r") as read_file:
            tmp = json.load(read_file)
            p: Class1.DataType1 = cast(Class1.DataType1, tmp)

            print('name = ', p['firstName'], p['lastName']) #it works

            print('name = ', p.firstName) #error here

```

**Comment by JelleZijlstra** [comment]
You should probably use a TypedDict, but note that a TypedDict "class" is merely fancy notation for a dict; it won't work like a class with actual attributes. Combining TypedDict and `@dataclass` is meaningless.

**Comment by juanfernandoe** [comment]
@JelleZijlstra thanks for your answer.

I found a better solution for my use case, I hope it will be userful for other people.
be careful, this solution is only for a one level json structure.

````
class Class1:

    @dataclass
    class DataType1(NamedTuple):
        firstName: str
        lastName: str

    def readJSON1(self) -> None:
        with open("data.json", "r") as read_file:
            tmp = json.load(read_file, object_hook=lambda d: namedtuple(
                Class1.DataType1.__name__, d.keys())(*d.values()))

            p: Class1.DataType1 = cast(Class1.DataType1, tmp)
            print('name = ', p.firstName) #works 

````

**Comment by JelleZijlstra** [comment]
I don't think any solution combining `@dataclass` and `NamedTuple` in a single class should be advised.
