### ISSUE TITLE
Support _replace (etc.) with namedtuple

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#661]
Reported by Dedoig:

> Mypy disallows usage of _replace() method from namedtuple (and likewise for NamedTuple).

> from collections import namedtuple
> Person = namedtuple("Person", 'name')
> p = Person("bob")
> p._replace(name="sam")

> ==> "Person" has no attribute "_replace"

Also, these are missing:

* `_asdict()`
* `_fields`

**Comment by ddfisher** [comment]
Should be fixed by #1810.

**Comment by elazarg** [comment]
Fixed
