### ISSUE TITLE
Make List[<nothing>] a subtype of List[X]?

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6613]
We could probably treat `List[<nothing>]` as a subtype of `List[X]` without *significant* unsafety if we ensure that no variables will be inferred with `List[<nothing>]` types, and `List[<nothing>]` can't be used as a declared type. This was discussed elsewhere a while ago. With this restriction, you can't easily perform mutation operations on an empty list that would also be used as a value in another context, since all values are usually temporaries. (Yes it's easy enough to construct an example where this is still unsafe, but these seem very unlikely to happen in real code).

#6572 is an example that this could be useful, but this has come up in other contexts as well.

**Comment by ilevkivskyi** [comment]
This is basically what pyre does, see discussion in https://github.com/python/typeshed/pull/2817

**Comment by ilevkivskyi** [comment]
This may be also relevant for other empty containers that are invariant, like empty dicts, see https://github.com/python/mypy/issues/7727

**Comment by msullivan** [comment]
If this enables fixing the `get` type in typeshed, then I think it would fix some real world precision issues: #8123

**Comment by ilevkivskyi** [comment]
I just merged a PR doing this, and then found this issue again.
