### ISSUE TITLE
Issue while installing PyRqa

### ISSUE THREAD

**Issue by vamseedharg** [python/mypy#6658]
Hi All,

I am facing an issue while installing PyRqa library. I have Python 3 installed. The error message is as follows. 

*** Command "c:\users\openspace\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\OPENSP~1\\AppData\\Local\\Temp\\pip-install-u504ukr7\\pyopencl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\OPENSP~1\AppData\Local\Temp\pip-record-c7dbafe4\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\OPENSP~1\AppData\Local\Temp\pip-install-u504ukr7\pyopencl\ ***

Here is the image. Please help.

![Error while installing PyRqa](https://user-images.githubusercontent.com/46438279/55944254-db2b2180-5c65-11e9-9187-be558eeb180d.jpg)

Note: if you are reporting a wrong signature of a function or a class in
the standard library, then the typeshed tracker is better suited
for this report: https://github.com/python/typeshed/issues

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
* What is the actual behavior/output?
* What is the behavior/output you expect?
* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
* What are the mypy flags you are using? (For example --strict-optional)
* If mypy crashed with a traceback, please paste
  the full traceback below.

(You can freely edit this text, please remove all the lines
you believe are unnecessary.)

**Comment by ethanhs** [comment]
Hi, this is not the place to ask general Python-related questions. Please read https://www.python.org/about/help/ for more information.

**Comment by vamseedharg** [comment]
Its not just python related. It is something related to additional installations required for installing PyRqa. As it is related to Scientific way analysis of waveforms .

**Comment by ethanhs** [comment]
@vamseedharg This bug tracker is only for bugs/questions/issues related to the mypy type checker specifically. Other questions do not belong here. Please look elsewhere for assistance.

**Comment by vamseedharg** [comment]
Oh! I am really sorry to bother you. Thanks for the info.
