### ISSUE TITLE
Missing return statement after a call to quit()

### ISSUE THREAD

**Issue by johnwspirent** [python/mypy#6661]
I am getting "Missing return statement" with the following:

def foo() -> str:
    try:
        with open('bar.txt') as file:
            return ''
    except FileNotFoundError as error:
        print(error)    
    quit()

Is this correct behaviour? (MyPy 0.670, Python 3.7.1)

**Comment by ilevkivskyi** [comment]
This is a `typeshed` problem. `quit()` must be annotated with `NoReturn`, please open an issue there.

**Comment by johnwspirent** [comment]
Ok. Will do. Thanks.

**Comment by johnwspirent** [comment]
This has been fixed in typeshed now: #2912 via #2915.
