### ISSUE TITLE
Enable --fast-exit by default

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6662]
If we'd enable `--fast-exit` by default, mypy would run a bit faster.

**Comment by ilevkivskyi** [comment]
In general I am fine with this. What are the possible downsides? Also do you have some numbers to compare?

**Comment by msullivan** [comment]
We'd want to make sure that it didn't get turned on by default when mypy is invoked through the API, but other than that it seems like a basically good idea.

**Comment by JukkaL** [comment]
There are some edge cases where this could make a difference, such a plugin that relies on files being flushed at process exit, but these should be rare. I don't have recent performance measurements, but if I remember correctly, the speedup was in the 5% range for big mypy runs.

**Comment by gvanrossum** [comment]
I'm not too keen on this. People with big code bases should use the daemon
anyway. And if they don't, they can use this flag explicitly. (We probably
should do so in our internal scripts that don't use the daemon.)
