### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [python/mypy#6675]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by gvanrossum** [comment]
There is only a `sudo: required` in our `.travis.yml` file. Doesn't that mean that blog article doesn't apply here?

**Comment by cclauss** [comment]
The __sudo__ tag is now a no-op in .travis.yml. That means that __sudo__ is _always_ available in Travis jobs.

**Comment by gvanrossum** [comment]
Do you have a documentation reference for that as well?

**Comment by cclauss** [comment]
@BanzaiMan Can you please give us your read on this?  Should the __sudo__ tag be removed from .travis.yml files because sudo is _always_ available in Travis jobs?

**Comment by acnagy** [comment]
Hi @cclaus @gvanrossum! I'm no longer at Travis CI, so I think others may have more up-to-date references, but as of when I left, you could just drop `sudo: required` from your yaml. This was the [PR](https://github.com/travis-ci/docs-travis-ci-com/pull/2095) which removed references to it in the docs.

**Comment by gvanrossum** [comment]
Thanks, we'll take PRs that delete the sudo lines from all our projects.
