### ISSUE TITLE
Support bare Callable types

### ISSUE THREAD

**Issue by Dedoig** [python/mypy#670]
```
from typing import Iterable, TypeVar, Callable, Iterator, Generic

T = TypeVar("T")

def gen(f: Callable, *args) -> Callable[[], Iterator[T]]:
	return lambda: f(*args)
```

Related question: is it currently possible to type argument ```f: Callable[..., Iterator[T]]```?

**Comment by JukkaL** [comment]
Hmm, I don't think that PEP 484 says that `Callable` is a valid type, but mypy shouldn't crash when you try to use it. It should give an error.

Answer to the question: not yet, but it will become possible: https://github.com/JukkaL/mypy/issues/393

**Comment by JukkaL** [comment]
PEP 484 actually supports using `Callable` as a type, so mypy should support as well.

**Comment by JukkaL** [comment]
`Callable` should be equivalent to `Callable[..., Any]`.
