### ISSUE TITLE
Parameters are required for MultiDictProxy

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/mypy#6702]
MyPy thinks that `MultiDictProxy` from the `multidict` package is a generic type and requires parameters for it.
```
$ cat md.py 
from multidict import MultiDictProxy
x: MultiDictProxy
$ mypy --disallow-any-generics md.py 
md.py:2: error: Missing type parameters for generic type
```
But since it is not a generic type, it does not support indexing.
```
>>> from multidict import MultiDictProxy
>>> x: MultiDictProxy[dict]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

**Comment by ilevkivskyi** [comment]
Some classes (even in stdlib) are not generic at runtime, but are semantically generic, and therefore are annotated as such in typeshed. In such cases we recommend either using PEP 563 `from __future__ import annotations`, or if this doesn't help or is not possible the use https://mypy.readthedocs.io/en/latest/common_issues.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime
