### ISSUE TITLE
"TypeError: interpreted classes cannot inherit from compiled" after get_customize_class_mro_hook

### ISSUE THREAD

**Issue by kedder** [python/mypy#6706]
When using plugin, that provides `get_customize_class_mro_hook`, mypy errors out with `TypeError: interpreted classes cannot inherit from compiled` traceback. Tested on mypy-0.701 and python-3.6.

Consider this minimal plugin:

```python
from mypy.plugin import Plugin

class DummyPlugin(Plugin):
    def get_customize_class_mro_hook(self, fullname):
        def analyze(classdef_ctx):
            pass
        return analyze

def plugin(version):
    return DummyPlugin
```

When mypy is run with this plugin enabled on simple python file, e.g. 

```python
class Something:
    pass
```

Mypy will error out with this traceback:
```
tmp/sample.py:1: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
Traceback (most recent call last):
  File "ve/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "mypy/semanal.py", line 3791, in accept
  File "mypy/nodes.py", line 895, in accept__Node_glue
  File "mypy/nodes.py", line 896, in accept
  File "mypy/semanal.py", line 804, in visit_class_def__StatementVisitor_glue
  File "mypy/semanal.py", line 807, in visit_class_def
  File "mypy/semanal.py", line 819, in analyze_class
  File "mypy/semanal.py", line 1229, in analyze_base_classes
  File "mypy/semanal.py", line 1250, in calculate_class_mro
TypeError: interpreted classes cannot inherit from compiled
tmp/sample.py:1: : note: use --pdb to drop into pdb
```

**Comment by msullivan** [comment]
Could you give the full code for the plugin, with imports?

**Comment by msullivan** [comment]
(Nevermind, I managed to reproduce it.)

**Comment by msullivan** [comment]
The error message here is a bad one from mypyc. The actual problem here is that we are trying to instantiate Expression, which is a trait, which is not really supported.

**Comment by glyph** [comment]
I believe that this broke / is blocking the zope.interface plugin (see also #3960) https://github.com/Shoobx/mypy-zope/issues/7 - should it be treated as a regression?

**Comment by msullivan** [comment]
... I tracked this down and then forgot to fix it. I'll fix it now.

**Comment by glyph** [comment]
Thanks so much, @msullivan !
