### ISSUE TITLE
the CI is failing now 

### ISSUE THREAD

**Issue by gaborbernat** [python/mypy#6716]
due to https://github.com/pypa/pip/issues/6434; we'll have to pin the dev environment to an earlier pip 🤔 it seems

**Comment by gvanrossum** [comment]
Do you have an example PR that's failing? Do you have a suggested change to make it pass? I don't have time to read and understand that entire PIP issue.

**Comment by gaborbernat** [comment]
master at the moment, we have two option, either pin pip to 19.0.3 or disable the dev target in Travis

**Comment by gvanrossum** [comment]
I don't know what you mean by "dev target". I support pinning pip is a quick fix but not tenable long term. Are they planning a fix?

**Comment by gaborbernat** [comment]
we'll see it tomorrow what's the plan to solve it, will create either way a
PR to fix it

**Comment by gvanrossum** [comment]
Sully just put up a PR, https://github.com/python/mypy/pull/6718

**Comment by gaborbernat** [comment]
Thanks, will make a final fix PR when pip agrees how to handle this case. That will do in the meantime.

**Comment by gvanrossum** [comment]
Reopening the bug, awaiting the final fix.
