### ISSUE TITLE
Add a method for conditional deferral and use it in the new analyzer

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#6725]
This idea appeared in https://github.com/python/mypy/pull/6724. It will be useful for plugins and in general to have something like this in `SemanticAnalyzer`:
```python
def defer_if_possible(self) -> bool:
    if not self.final_iteration:
        self.defer()
        return True
    return False
```
Then it can be used like this:
```python
if ctx.api.defer_if_possible():
    ...
else:
    ... # probably give some error
```
Maybe we can also add it to the old analyzer as always returning `False`, then we can completely hide the old vs new analyzer details in plugin API.

**Comment by JukkaL** [comment]
`process_placeholder` is enough for now, as discussed in #7159.
