### ISSUE TITLE
Missing argument to Callable crashes mypy

### ISSUE THREAD

**Issue by spkersten** [python/mypy#673]
This code (missing return type in `Callable`) crashes mypy with an uncaught `IndexError`:

```python
from typing import Callable

def g(f: Callable[[int]]) -> None:
    pass
```

It should just report an error.

**Comment by JukkaL** [comment]
Yes, it definitely should not crash. Thanks for the bug report!

**Comment by gvanrossum** [comment]
FWIW bare `Callable` it should probably be equivalent to `Callable[..., Any]`. See https://github.com/ambv/typehinting/issues/133

**Comment by JukkaL** [comment]
This no longer crashes.
