### ISSUE TITLE
When there is a duplicate module, show path of other module

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6741]
It's easy to accidentally have two modules with the same name if a `__init__.py` file missing, for example. Mypy currently complains about one of the modules but it may not be obvious where the other conflicting module lives. It would be better to show the paths of both/all conflicting modules. Maybe also include a hint about possible missing `__init__.py` files.

Example:

```
foo.py
pkg/__init__.py
pkg/subpkg/foo.py
```

Note that `pkg/subpkg/__init__.py` is missing, which causes mypy to think that there are two instances of module `foo`.

Users get confused about this quite frequently, so we should perhaps prioritize this.

**Comment by jxcl** [comment]
Looking at this issue
