### ISSUE TITLE
"pytype and mypy" lightning talk

### ISSUE THREAD

**Issue by rchen152** [python/mypy#6745]
I've put together a potential PyCon lightning talk on the differences between pytype and mypy ([slides](https://docs.google.com/presentation/d/1GYqLeLkknjYaYX2JrMzxX8LGw_rlO-6kTk-VNPVG9gY/edit?usp=sharing)), since this is by far the most-asked question about pytype outside Google. (Even if I don't have the chance to give this at PyCon, I'll probably add it to the [pytype FAQ](https://google.github.io/pytype/faq.html).) I'd love to get some feedback here on my slides to make sure I'm not saying anything inaccurate or misleading about mypy.

**Comment by gvanrossum** [comment]
The characterization of mypy seems accurate. I’m surprised that you don’t
mention pytype’s capability of creating stubs though.
-- 
--Guido (mobile)

**Comment by rchen152** [comment]
Thanks, Guido! I didn't want to be too ambitious with 5-10 minutes of content, but I'll ponder whether I can work in stub creation after inference.

**Comment by ilevkivskyi** [comment]
Couple small details:

First, mypy still does some type inference, but never cross-function inference, e.g. with `--check-untyped-defs` you get:
```python
def f():
    x = 1
    y = x + 'no'  # error here
```

Second, `--allow-redefinition` flag in mypy makes mypy accept code like this:
```python
x = [1, 2, 3]
x = [str(i) for i in x]
```
but your example with `list.append()` still fails.

Both of these are not worth mentioning in a 5-10 minutes talk, just wanted to give some more details about mypy.

**Comment by rchen152** [comment]
That's good to know - thanks :)

**Comment by rchen152** [comment]
Thanks for all the feedback. I ended up being lucky enough to give this talk on Friday evening.
