### ISSUE TITLE
 Name '_' already defined for "@register" function registration pattern

### ISSUE THREAD

**Issue by jonathanslenders** [python/mypy#6752]
I'm adding type annotations to the prompt_toolkit library.
The code for handling the key bindings looks something like this:

```python
    @handle('up')
    def _(event: E) -> None:
        event.current_buffer.auto_up(count=event.arg)

    @handle('down')
    def _(event: E) -> None:
        event.current_buffer.auto_down(count=event.arg)

    @handle('delete', filter=has_selection)
    def _(event: E) -> None:
        data = event.current_buffer.cut_selection()
        event.app.clipboard.set_data(data)
```
The ``@handle`` decorator is registering the function as a callback somewhere. The name is irrelevant, because it's never referred to in the scope where it's defined, hence the name ``_``.

Mypy however, doesn't like it:
```
prompt_toolkit/key_binding/bindings/basic.py:179: error: Name '_' already defined on line 160
prompt_toolkit/key_binding/bindings/basic.py:183: error: Name '_' already defined on line 160
prompt_toolkit/key_binding/bindings/basic.py:187: error: Name '_' already defined on line 160
prompt_toolkit/key_binding/bindings/basic.py:194: error: Name '_' already defined on line 160
prompt_toolkit/key_binding/bindings/basic.py:207: error: Name '_' already defined on line 160
```

I would hate to give all 214 occurrences of key bindings a name, if it doesn't matter.
```
 $ grep 'def _(' -R prompt_toolkit/ | wc -l
214
```

Would it be possible to add an exception to mypy, which allows function names to be rebound in the same scope, if they are never called by their name binding?
If so, that would be great, and I think not just for prompt_toolkit and its users.

(Btw, I'm at PyCon right now.)

Thanks a lot!

**Comment by ethanhs** [comment]
@jonathanslenders You may be interested in the discussion in https://github.com/python/mypy/issues/2904. Unfortunately, there isn't a good method of making an exception to this pattern that I am aware of, so a plugin seems the optimal solution.

Also if you are at PyCon you may be interested in the typing summit https://mail.python.org/archives/list/typing-sig@python.org/thread/P36XOWSKFZRHW7SOJTGVJUOHAZRDAHVQ/

(I unfortunately couldn't make it to PyCon this year, but the rest of the mypy team is there).

**Comment by jonathanslenders** [comment]
Thank you @ethanhs for the quick reply,
That discussion covers the problem indeed.
I'll close this issue.

Otherwise, I'm really happy with everything mypy does.
