### ISSUE TITLE
Annotation Overridden Through Multilevel Inheritance

### ISSUE THREAD

**Issue by WillAyd** [python/mypy#6754]
Assuming a class structure as follows:

```python
class Base:
    attr = None  # type: Union[int, str]

class Derived1(Base):
    attr = 1

class Derived2(Derived1):
    attr = 'foo'
```

I was surprised to be getting the following error with Mypy:

```sh
error: Incompatible types in assignment (expression has type "str", base class "Derived1" defined the type as "int”)
```

Within the scope of Derived1 it makes sense to me that mypy may restrict the type to just int, but in the subsequent child class of Dervied2 I was surprised that the implicit annotation in Dervied1 took precedence over the explicit annotation provided in the Base class

I was getting this error with Python 3.7.2 on mypy master

**Comment by ilevkivskyi** [comment]
I may be equally (if not more) surprising if something like this would fail:
```python
x: int = Derived1.attr  # if the type of attr would still be union, this would fail
```
There are _some_ situation where keeping supertype context is desirable, but this is already discussed in https://github.com/python/mypy/issues/4547
