### ISSUE TITLE
Docs: Can I run mypy in a pre-commit hook?

### ISSUE THREAD

**Issue by cclauss** [python/mypy#6788]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
__feature request__

In the docs, perhaps in [__Common issues and solutions__](https://github.com/python/mypy/blob/master/docs/source/common_issues.rst), could the question "__Can I run mypy in a pre-commit hook?__" and answer be added?  Thanks for all your great work on mypy.

**Comment by ethanhs** [comment]
A PR adding this under the "linter integration" section of the Readme would be welcome :)
