### ISSUE TITLE
Generic Protocol breaks mypy when attrs class

### ISSUE THREAD

**Issue by wakemaster39** [python/mypy#6801]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```
from abc import abstractmethod
from typing import TypeVar

from attr import attrs
from typing_extensions import Protocol

T = TypeVar("T")


@attrs(auto_attribs=True)
class Test(Protocol[T]):
    a: int

    @abstractmethod
    def transition_to(self, t: T):
        raise NotImplementedError
```

* What is the actual behavior/output?
mypy crashes
* What is the behavior/output you expect?
```
test.py:20:1: error: Invariant type variable 'T' used in protocol where contravariant one is expected
test.py:24:5: error: Function is missing a return type annotation
```

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
Using 701, still exists with master

* What are the mypy flags you are using? (For example --strict-optional)
No config

* If mypy crashed with a traceback, please paste
  the full traceback below.

```
test.py:24:5: error: Function is missing a return type annotation
./test.py:19: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
Traceback (most recent call last):
  File "/Users/cahurst/.local/share/virtualenvs/automation_engine-fTGkomR2/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "mypy/checker.py", line 395, in accept
  File "mypy/nodes.py", line 896, in accept
  File "mypy/checker.py", line 1528, in visit_class_def__StatementVisitor_glue
  File "mypy/checker.py", line 1568, in visit_class_def
  File "mypy/checker.py", line 1588, in check_protocol_variance
  File "mypy/subtypes.py", line 95, in is_subtype
  File "mypy/types.py", line 625, in accept
  File "mypy/subtypes.py", line 185, in visit_instance__TypeVisitor_glue
  File "mypy/subtypes.py", line 218, in visit_instance
  File "mypy/subtypes.py", line 482, in is_protocol_implementation
AssertionError:
./test.py:19: : note: use --pdb to drop into pdb
```

Removing either the Generic aspect, or removing attrs from the class makes everything work as expected. It only occurs when both are in play at the same time.

**Comment by ilevkivskyi** [comment]
Thanks for reporting! I am curious what is the purpose of using `attrs` with protocols, is it to autogenerate default implementations for methods?

The crash itself is caused by the dummy type variable used for self-types in methods. I am not sure what is the best fix here. A simple possible solution is to ignore nor `FuncBase`/`Decorator`/`Var` nodes when collecting protocol attributes (especially if they are underscored). Maybe we should also emit an error if such node (e.g. a `TypeVarExpr`) appears in protocol namespace under non-private name.

**Comment by wakemaster39** [comment]
We uses attrs for basically all of our classes. So this was discovered because I was porting some of our abstract classes over to be protocols instead and had not removed the `@attrs` line. 

This specific example doesn't have a lot of it, but some of our abstracts have instead variables like `a: int` defined on them, and it saves having to copy and paste that code into the concrete implementation.

**Comment by ilevkivskyi** [comment]
Note this can happen even with non-generic protocols, see example in https://github.com/python/mypy/issues/6850.

**Comment by flisboac** [comment]
Can reproduce this with the following (Playground link: https://mypy-play.net/?mypy=latest&python=3.10):

```py

from abc import ABCMeta, abstractmethod
from typing import Any, Generic, TypeVar
from typing_extensions import Protocol


_TType = TypeVar('_TType')


class Comparable(Generic[_TType], metaclass=ABCMeta):
    @abstractmethod
    def __eq__(self, other: Any) -> bool:
        ...

    @abstractmethod
    def __ne__(self, other: Any) -> bool:
        ...

    @abstractmethod
    def __hash__(self) -> int:
        ...

    @abstractmethod
    def __lt__(self, other: _TType) -> bool:
        ...

    @abstractmethod
    def __le__(self, other: _TType) -> bool:
        ...

    @abstractmethod
    def __gt__(self, other: _TType) -> bool:
        ...

    @abstractmethod
    def __ge__(self, other: _TType) -> bool:
        ...


class SupportsComparable(Protocol[_TType]):  # ERROR HERE
    def __eq__(self, other: Any) -> bool:
        ...

    def __ne__(self, other: Any) -> bool:
        ...

    def __hash__(self) -> int:
        ...

    def __lt__(self, other: _TType) -> bool:
        ...

    def __le__(self, other: _TType) -> bool:
        ...

    def __gt__(self, other: _TType) -> bool:
        ...

    def __ge__(self, other: _TType) -> bool:
        ...
```

P.S.: In any case, why can't I also set `covariant=True` in `_TType` (`__lt__`, `__le__`, `__gt__` and `__ge__` are marked with the error `Cannot use a covariant type variable as a parameter`)? I fail to see why it can't be so.
