### ISSUE TITLE
Ignoring error does not work for "Unexpected keyword argument"

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/mypy#6807]
`# typing: ignore` is a way to ignore MyPy errors. But it does not work for the "Unexpected keyword argument" error. So I cannot silence errors in typeshed (see https://github.com/python/typeshed/issues/2976).

```
$ cat a.py
def foo() -> None:
    pass

foo(a=1)  # typing: ignore

$ mypy a.py
a.py:1: note: "foo" defined here
a.py:4: error: Unexpected keyword argument "a" for "foo"

$ mypy --version
mypy 0.701
```
Is there other workaround?

**Comment by ethanhs** [comment]
@serhiy-storchaka the spelling is `# type: ignore`, not `# typing: ignore`. (I verified just in case that `# type: ignore` does silence the error in your example).

**Comment by serhiy-storchaka** [comment]
Thanks @ethanhs!
