### ISSUE TITLE
Give more detail about original definition when override is incompatible

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6808]
If a method override is incompatible with the definition in a base class, it would be helpful to give the file + line number of the base class definition. Maybe we should also print out the signature of the original definition if we can't pinpoint the error to an incompatible argument/return type (that is, when we give the generic `Signature of "x" incompatible with supertype "A"` error).

Follow-up to #5025.

**Comment by ilevkivskyi** [comment]
I think just printing the signature would be better IMO. In other places (bad keyword argument IIRC) we put a note `"blah" defined here`, but they are not always clear, and previously caused troubles in incremental mode and/or if output is sorted by file.

**Comment by JukkaL** [comment]
The sounds reasonable. Alternatively, we could implement a more robust way of pointing to lines elsewhere in the target program.

**Comment by hauntsaninja** [comment]
I think we have better error messages here now.
