### ISSUE TITLE
Tuple with ellipsis is not working as expected

### ISSUE THREAD

**Issue by uriva** [python/mypy#6825]
> ... has incompatible type "Dict[str, Tuple[str, str, str, str, str]]"; expected "Dict[str, Tuple[str, ...]]"

Isn't `Tuple[str, ...]` a superset of `Tuple[str, str, str, str, str]`?

**Comment by gvanrossum** [comment]
To understand this, please read up on invariance:
https://mypy.readthedocs.io/en/latest/common_issues.html#invariance-vs-covariance
