### ISSUE TITLE
Different behaviour with parenthesis or without

### ISSUE THREAD

**Issue by uriva** [python/mypy#6826]
This causes an error:

`my_variable: Optional[Tuple] = something, something_else`

While this works:

`my_variable: Optional[Tuple] = (something, something_else)`

**Comment by ethanhs** [comment]
Hi, the first syntax is a syntax error in CPython, I'm not sure what behavior you are expecting from mypy? Also, please give complete reproducible examples, something anyone could just copy and run, it makes it easier to test these things.

**Comment by ilevkivskyi** [comment]
This is fixed in Python 3.8, see https://bugs.python.org/issue35814.
