### ISSUE TITLE
Sleep command sleeps entire program when I don't want it to

### ISSUE THREAD

**Issue by Ellgrey** [python/mypy#6844]
#imports#
from time import sleep

#varibles#
x_of_p1 = 250 #where the loading bar i on the x-axis# 

#moving the bar acorss the screen#
def bar_p1():
    sleep(5)#making the bar wait 5 seconds#
    global x_of_p1
    stroke(0,0,255)
    fill(0,0,25)
    line(x_of_p1,205,x_of_p1,235)
    x_of_p1 = x_of_p1+1

This is only part of my program but this is all you need to help. What is happening is that I need to make this progress bar move across the screen at one pixel every 5 seconds. I first thought to do this with the sleep function but this makes the whole program wait five seconds before updating. Any way to help is excepted, thank you.

**Comment by JukkaL** [comment]
This issue is off topic here, sorry.
