### ISSUE TITLE
disjoint unions in mypy?

### ISSUE THREAD

**Issue by kurtgn** [python/mypy#6863]
I am trying to customize a function that takes an object of a union type and accesses different attributes depending on the type. The type of the object is specified by a `type` attribute.

```
from typing import Union

from dataclasses import dataclass


TEXT = 'TEXT'
IMAGE = 'IMAGE'


@dataclass
class TextMessage:
    text: str
    type = TEXT


@dataclass
class ImageMessage:
    url: str
    type = IMAGE


def output(message: Union[TextMessage, ImageMessage]) -> None:
    if message.type == TEXT:
        print(message.text)
```

Mypy does not like this, saying:

```
 error: Item "ImageMessage" of "Union[TextMessage, ImageMessage]" has no attribute "text"
```

And I understand it. I am trying to guess one attribute based on the value of another one. This is poor engineering.

However, the same thing works in other languages, for example, in JS Flow:

```
// @flow

type TextMessage = {
	type: 'TEXT',
  	text: string
};
type ImageMessage = {
	type: 'IMAGE',
  	url: string
};

function output(message: TextMessage | ImageMessage) {
  if (message.type === 'TEXT') {
    console.log(message.text);
  }
} 
```

Live Flow link: [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AFSwB4oCyWAzmQIYDmOAvKAN6ICQ62AXKAOS4CiADVzcANIlCg2hFFzIoATgEsAdtUQBfANypMOAJIBbGllIVjoBsza6u3PcQCCAcT6jxkgK7zoshSrVayMiQHsoAxiiKsMqgsB4oGPEAFAbkVLRc+ESm6TgAPqCGxjnGAJRM7oqQoClpxgB07PR0DLyCwuXMEhJh0WSw0Fj1cNS1ZrSN0qXaEuoaoEA)

So the question is, is there a way to make mypy understand my conditions? Maybe using `Literal` types? I tried to figure this out but the docs are a bit confusing.

P.S. I can always do `if isinstance(message, TextMessage)` and this will satisfy mypy, but putting lots of `isinstance()` in my code seems even more hacky.

**Comment by ethanhs** [comment]
>P.S. I can always do if isinstance(message, TextMessage) and this will satisfy mypy, but putting lots of isinstance() in my code seems even more hacky.

Aren't you essentially trading off putinig lots of `isinstance(message, TextMessage)` with lots of `if message.type == 'TEXT'`? The first is 1) more Pythonic 2) better supported 3) more readable and 4) doesn't require you to add a type tag to all of your classes.

As for using `Literal` to solve your issues, under `"Extra" features to add` in https://github.com/python/mypy/issues/5935 there is "Type narrowing with equality and inequality checks", which is what you want.

**Comment by ilevkivskyi** [comment]
But why this
```python
def output(message: Union[TextMessage, ImageMessage]) -> None:
    if message.type == TEXT:
        print(message.text)
```
is better than this
```python
def output(message: Union[TextMessage, ImageMessage]) -> None:
    if isinstance(message, TextMessage):
        print(message.text)
```
?

Anyway, I propose to close this since this is essentially the same as "Type narrowing with equality and inequality checks" item from #5935 as @ethanhs mentioned.

**Comment by Garrett-R** [comment]
> Anyway, I propose to close this

Agreed!

Interestingly, TypeScript does offer [discriminating unions](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions), but @mneira10 pointed out that they're more important in TS given that TS doesn't have a clean way of doing `isinstance` like Python does.  You could write user-defined type guards ([example](https://stackoverflow.com/questions/14425568/interface-type-check-with-typescript/14426274#14426274)), but that's messy.

**Comment by JukkaL** [comment]
Besides, the original example works already if using Final and literal types:
```
from typing import Final, Literal
from dataclasses import dataclass


TEXT: Final = 'TEXT'
IMAGE: Final = 'IMAGE'


@dataclass
class TextMessage:
    type: Literal['TEXT']
    text: str


@dataclass
class ImageMessage:
    type: Literal['IMAGE']
    url: str


def output(message: TextMessage | ImageMessage) -> None:
    if message.type == TEXT:
        print(message.text)  # No error
```
