### ISSUE TITLE
Invalid Python in test cases

### ISSUE THREAD

**Issue by spkersten** [python/mypy#687]
Many test cases (>100) contain invalid Python code like this,

``` python
a = A()

class A: pass
```

where a name is referenced before it is bound. 

This impedes solving #686.

**Comment by JukkaL** [comment]
Yeah, this is unfortunate.

**Comment by JukkaL** [comment]
Many of these cases can likely be found using the test data parser used for running test cases and regular expressions.

**Comment by iamaspacecow** [comment]
I'm looking into this

**Comment by iamaspacecow** [comment]
Do we want blanket fixes over all tests so that names are only referenced after they are bound?
Or do we want to leave some tests incorrect so that we can validate that mypy correctly errors for them?

Also, @spkersten, can you point me to your changes that enable mypy to detect this issue?

**Comment by gvanrossum** [comment]
I'd define a few separate tests that check for various kinds of forward references (e.g. module, class, function, nested class, type variable, type alias, other kind of variable). Though it's possible that mypy needs to be fixed first to actually error out on them. It's also possible that we should fix the tests without fixing this in mypy (maybe fixing this in mypy is tricky, and of course it must still support forward references from type comments or type annotations in string literals).

**Comment by iamaspacecow** [comment]
Going by @gvanrossum comment, it seems that we want to make a separate set of tests to test forward references. Therefore I will move forward on my quest to fix all mis-referenced tests I can find

**Comment by iamaspacecow** [comment]
So right now I'm writing a test suite that tries to `exec` all the test cases and report their failure. 
My next task will be blacklisting the test-files that shouldn't be run (testing the pyi stuff), as well as 
the files/test cases that should intentionally fail

**Comment by ajjayymahato** [comment]
Hi there! I would like to work on this issue. Is this issue still open? Can you please assign this issue to me!

**Comment by hauntsaninja** [comment]
yup, still open, feel free to work on it. see https://github.com/python/mypy/blob/master/CONTRIBUTING.md#first-time-contributors

> You do not need to ask for permission to work on any of these issues. Just fix the issue yourself, [try to add a unit test](https://github.com/python/mypy/blob/master/CONTRIBUTING.md#running-tests) and [open a pull request](https://github.com/python/mypy/blob/master/CONTRIBUTING.md#submitting-changes).

**Comment by JukkaL** [comment]
I think that this was addressed in #14166.
