### ISSUE TITLE
Support 3.8 positional-only arguments

### ISSUE THREAD

**Issue by msullivan** [python/mypy#6878]
PEP 570 (https://www.python.org/dev/peps/pep-0570/) introduces positional-only arguments for 3.8, which we should support before the 3.8 release.

**Comment by JelleZijlstra** [comment]
I'm interested in working on this but might not find time for it, so if anybody else wants to, go for it.

**Comment by brandtbucher** [comment]
I'm interested in working on this as well. I've peeked around the argument handling code, and this seems like an issue that an outside contributor should be able to work out.

@JelleZijlstra, are you okay with me taking a pass at this this week/weekend and reaching out to you if I encounter anything tricky?

**Comment by JelleZijlstra** [comment]
Go for it! Maybe I'll take a stab at the walrus operator instead.

**Comment by gvanrossum** [comment]
Yay!
