### ISSUE TITLE
Request to update readme: replace vim-py by syntastic

### ISSUE THREAD

**Issue by robinchm** [python/mypy#6880]
Request to update Readme.

Currently the Readme features [vim-mypy](https://github.com/Integralist/vim-mypy) as the IDE integration for vim. As I just set up mypy with vim, this repo is dead. Its current HEAD is incompatible with the latest version of mypy (refer to its open issues) and it has not been updated for 2 years.

Instead I successfully integrate mypy with vim using [syntastic](https://github.com/vim-syntastic/syntastic). Putting the following in the `.vimrc` after installing syntastic works:
```
let g:syntastic_python_checkers=['mypy']
```

Could you consider updating the Readme so that vim users look into the working plugins?

**Comment by gvanrossum** [comment]
Sounds like a good idea. Can you provide a PR?

**Comment by gvanrossum** [comment]
Closed by #6886
