### ISSUE TITLE
`MapResult` object is multiprocessing library is of wrong typing.

### ISSUE THREAD

**Issue by yech1990** [python/mypy#6883]
```python
import multiprocessing
import time


def worker(i):
    time.sleep(1)
    return f"hello {i}"


with multiprocessing.Pool(processes=8) as pool:
    result_objs = pool.map_async(worker, list(range(10)))
    while not result_objs.ready():
        print(f"num left: {result_objs._number_left}")
        time.sleep(0.2)
```

The code works fine, and the type if `map_async` return is `<class 'multiprocessing.pool.MapResult'>`, but mypy report this error message.

```shell
test_pool.py:25: error: "ApplyResult[List[Any]]" has no attribute "_number_left"
```

**Comment by JelleZijlstra** [comment]
This is an issue in typeshed (https://github.com/python/typeshed), not in mypy directly. Feel free to open an issue there.

Note though that you're using a private attribute. typeshed will accept pull requests adding support for private attributes like this, but it's better to stick to using public APIs that are guaranteed to be stable.
