### ISSUE TITLE
Attempting to use a TypedDict as a type in a generic function results in a cryptic error message

### ISSUE THREAD

**Issue by MaxwellMiller** [python/mypy#6885]
The following code:
```
MyTypedDict = TypedDict('MyTypedDict', {})

T = TypeVar('T')
def _generic(output_type):
    # type: (Type[T]) -> T
    d = {}  # type: Any
    return d

def caller():
    # type: () -> MyTypedDict
    return _generic(MyTypedDict)
```

Gives me the error:
"Incompatible return value type (got "my.module.MyTypedDict", expected "MyTypedDict")

I would expect a more informative error message, telling me how those two types are different.

**Comment by ilevkivskyi** [comment]
Yeah, this doesn't work because `Type[...]` is not supposed to work with anything but classes, unions of classes, and `Any`, see PEP 484.

It seems to me it might be possible to relax this limitation to some extent, but first of all we should fix the errors message, which is cryptic.

**Comment by ethanhs** [comment]
I'm going to close this in favor of https://github.com/python/mypy/issues/7255 since that one has a more minimal repro.
