### ISSUE TITLE
mypy does not evaluate the type annotation with [] prior to type checking

### ISSUE THREAD

**Issue by superbobry** [python/mypy#6939]
Apologies if this has already been reported, typing issues are tricky to search. 

Use-case: I am trying to define a `Tensor` type which can be indexed using type variables, similarly to `Generic`, but in such way that the resulting type is equivalent to `Tensor` itself. The indices are there only for documentation purposes. For example:

```python
Batch = TypeVar("Batch")

def f() -> Tensor[Batch]:
  return Tensor(...)
```

Here's the implementation 

```python
class TensorMeta(type):
    def __getitem__(self, *unused):
        return self

class Tensor(metaclass=TensorMeta):
    pass
```

mypy 0.701 rejects the above example with 

```
error: "Tensor" expects no type arguments, but 1 given
```

I think this is happening because mypy does not evaluate the type annotation and instead assumes it's a generic. I understand that my use-case is a bit obscure, but I'm curious nonetheless if this is "working as intended" or a bug?

**Comment by ilevkivskyi** [comment]
`<something>[<something else>]` is a reserved syntax in mypy if `<something>` is a type. If you really don't want to inherit from `Generic` at runtime, then you can use the trick:
```python
from typing import TYPE_CHECKING:

if TYPE_CHECKING:
    class Tensor(Generic[T]):
        ...
else:
    # actual definition with the custom metaclass.
    ...
```

> I think this is happening because mypy does not evaluate the type annotation

Mypy never evaluates anything.
