### ISSUE TITLE
Nested alias definition treated as invalid type

### ISSUE THREAD

**Issue by yury-kramniou** [python/mypy#6941]
Nested alias definition was not passed types check. MyPy defined it as "Invalid type". 

* I think this is a deffect.
* Code example:
```
import typing

class IntClass(object):
    int_alias = int
    class ClassAlias():
        pass

alias_int = IntClass.int_alias
alias_class = IntClass.ClassAlias

def int_a() -> IntClass.int_alias: # error: Invalid type "main.IntClass.int_alias"
    return 0

def int_b() -> alias_int: # error: Invalid type "main.alias_int"
    return 0

def class_() -> alias_class: # it's OK
    return IntClass.ClassAlias()
```
* Current behavior:
```
PS ~\Documents\Workplace\Sources\Other\PROTOTYPE\LINTERTEST> mypy .\
main.py:11: error: Invalid type "main.IntClass.int_alias"
main.py:14: error: Invalid type "main.alias_int"
```
* Expected behavior is passing types check.
* Versions of mypy and Python:
```
PS ~\Documents\Workplace\Sources\Other\PROTOTYPE\LINTERTEST> python --version
Python 3.7.2
PS ~\Documents\Workplace\Sources\Other\PROTOTYPE\LINTERTEST> mypy --version
mypy 0.701
```

**Comment by ilevkivskyi** [comment]
This is expected behavior, an assignment of the form `X = Y` at class or function level creates a variable with type `Type[Y]`, not an alias. To force creation of an alias you can use a trick `X = Union[Y]` (aliases are created by default for subscipted r.h.s., even at nested scopes).

**Comment by yury-kramniou** [comment]
Ok, thank You. I've understood.
