### ISSUE TITLE
New semantic analyzer: conflict between direct import and add_submodules_to_parent_modules()

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#6944]
Consider this test case:
```
[case testNewAnalyzerConfusingImport]
# flags: --follow-imports=skip --ignore-missing-imports
# cmd: mypy -m other a.b a
[file a/__init__.py]
[file a/b/__init__.py]
import other
import a.b.a
import a.b.c

[file other.py]
from a.b.a import foo
[builtins fixtures/module.pyi]
[out]
```
It passes with the old analyzer, but there is a subtle conflict between what should name `a` 
point to in the symbol table of `a.b`: to module `a`, or to module `a.b.a`? The code that handles this is a bit fragile, and depending on the order of processing of modules may fail in new analyzer with:
```
tmp/a/b/__init__.py:2: error: Name 'a' already defined (possibly by an import)
tmp/a/b/__init__.py:3: error: Name 'a' already defined (possibly by an import)
```
I am not sure what to do about this. Should we try to avoid this error (maybe at least for case when one of the module is not in build like in the test above)?

**Comment by ilevkivskyi** [comment]
Btw, this is essentially a tricky variation of https://github.com/python/mypy/issues/6828

**Comment by ilevkivskyi** [comment]
@JukkaL it looks like this was also fixed by one of our your latest PRs, should we close it? Or maybe add this test first (since this pattern appears in the internal codebases)?

**Comment by JukkaL** [comment]
Let's add a test first.
