### ISSUE TITLE
Wrong type inference (object instead of List)

### ISSUE THREAD

**Issue by cdesvernois** [python/mypy#6968]
Bug: the following code (Python 3.6.7, mypy 0.701)

```
o = [[1, 2], ["foo", "bar"]]
reveal_type(o)
```

Outputs a type of `builtins.list[builtins.object*]` instead of something like `builtins.list[builtins.list[Any]]`. This in turn makes mypy raise an error (in my case) when I try to apply a `len` operation on elements of that list:

```
[len(x) for x in o]
```

Outputs: `error: Argument 1 to "len" has incompatible type "object"; expected "Sized"`

This is probably related to #4975 but only the union of `Tuple` was evoked there, and it seems that there is the same problem on lists.

Thanks!

**Comment by ilevkivskyi** [comment]
There is a policy that mypy _never_ infers `Any` in joins of precise types. So this is more related to https://github.com/python/mypy/issues/3830, in the sense should we instead infer `List[Sized]` in this case? On one hand I would say we can, but on the other hand this is quite tricky in general (see https://github.com/python/mypy/issues/3257) and therefore low priority. You can just use explicit annotations in such cases:
```python
o: List[Sized] = [[1, 2], ["foo", "bar"]]
```

**Comment by cdesvernois** [comment]
Thanks for your investigation, I don't have any legitimacy to discuss your policies, from an external eye it seems too bad to prefer the inference of `List[object]` over the correct (and imprecise) `List[List[Any]]`.
You're right it would also be sufficient in this case to have a `List[Sized]`, but it would still be incorrect and could lead to false positives with things like:
```
o: List[Sized] = [[1, 2], ["foo", "bar"]]
[x.count(1) for x in o]
```
I will try your suggestion to use explicit type annotation :)

**Comment by GPHemsley** [comment]
The workaround gets a little tedious when your problematic list is being defined as part of a dictionary. You'd have to explicitly pull out its definition just to give it a type.

**Comment by hauntsaninja** [comment]
This is a won't fix. mypy's inference should never produce `Any`. It would be expensive for mypy to construct ad hoc protocols and any time you create a type that a user cannot easily name it creates usability issues
