### ISSUE TITLE
error: "yield from" can't be applied to "Union[List[int], List[str]]"

### ISSUE THREAD

**Issue by asottile** [python/mypy#6995]
```python
rom typing import Generator, List, Union

def t(x: Union[List[int], List[str]]) -> Generator[Union[int, str], None, None]:
    yield from x

print(tuple(t([1, 2, 3])))
```

```console
$ mypy --version
mypy 0.701
$ python3 t.py
(1, 2, 3)
$ mypy t.py
t.py:4: error: "yield from" can't be applied to "Union[List[int], List[str]]"
```

**Comment by asottile** [comment]
this is the actual code triggering this for us if it helps with another example:
```python
T = TypeVar('T')


def _flatten_steps(steps: Union[List[Union[List[T], T]], List[T]]) -> Iterator[T]:
    for step in steps:
        if isinstance(step, list):
            yield from step
        else:
            yield step
```

**Comment by brandtbucher** [comment]
Looks like you want a `TypeVar` here. This checks fine:

```py
from typing import Generator, List, TypeVar

T = TypeVar("T", int, str)

def t(x: List[T]) -> Generator[T, None, None]:
    yield from x
```

**Comment by asottile** [comment]
the typevar does not help me here, the minimal reproduction is meaningless code but was enough to demonstrate the problem -- yield from isn't properly considering unions of iterables

here's a less special case:

```python
def t(x: Union[Tuple[int, ...], List[int]]) -> Generator[int, None, None]:
    yield from x
```

**Comment by asottile** [comment]
this does appear to pass on master however, so I guess this got fixed by something between then and now :)

**Comment by JelleZijlstra** [comment]
Probably we just need to add a case for union types in https://github.com/python/mypy/blob/master/mypy/checkexpr.py#L3393.

**Comment by brandtbucher** [comment]
I can take a peek at this to make sure it’s solid.

**Comment by ilevkivskyi** [comment]
I checked all the examples, there are no problems with `yields from`, likely because accessing special methods on unions was fixed.

**Comment by ilevkivskyi** [comment]
(plus also a very recent fix for `type_is_iterable()` that used to accept only instances)
