### ISSUE TITLE
Docs should display latest released version by default

### ISSUE THREAD

**Issue by matangover** [python/mypy#6999]
Accessing https://mypy.readthedocs.io redirects to https://mypy.readthedocs.io/en/latest. This might be confusing for users, assuming most users install the latest _released_ version and not the development version (readthedocs call the development version 'latest').

Seems like this default redirect [can be changed](https://docs.readthedocs.io/en/stable/versions.html#redirects-on-root-urls). Maybe also the labels can be changed (e.g. 'latest' -> 'development', 'stable' -> 'latest').

Example: right now the [config file docs](https://mypy.readthedocs.io/en/latest/config_file.html#config-file) describe a 'files' option which isn't supported yet in the latest released version.

**Comment by ilevkivskyi** [comment]
I am fine with the current behaviour, so I would propose to just leave it as is, unless someone else thinks we should switch to `stable` by default.

**Comment by JukkaL** [comment]
I think that pointing to stable would be better, since GitHub master can contain incomplete or work-in-progress documentation and there can be features that aren't supported by the most recent mypy release.

**Comment by JukkaL** [comment]
Updated readthedocs to show 'stable' by default, but the top Google result still points to 'latest', and I'm not sure if we can easily do anything about that.
