### ISSUE TITLE
Feature request: Cache directory environment variable

### ISSUE THREAD

**Issue by hetmankp** [python/mypy#7016]
The cache directory can currently be customised using the --cache-dir argument. It would be convenient to also be able to do this using an environment variable akin to the MYPYPATH variable.

For very large projects that are not pure Python and contain multiple Python packages within the source tree, both the search path and cache directory often need to be customised for the entire project. Being able to do this via the environment is very convenient. Additionally, environment variables can often provide more flexible options when dealing with wrapper tools.

I would be happy to provide the implementation if this feature is considered reasonable.

**Comment by ilevkivskyi** [comment]
I think it may be a reasonable thing to add, please go ahead with a PR.

**Comment by hetmankp** [comment]
I'm happy to provide an implementation however the one thing that is still not obvious to me is whether the environment should take precedence over the config file or the other way around.

Making the environment variable take precedence would give any wrapper scripts ultimate control, however it seems like in some circumstances this could lead to unexpected results as a localised config file option may be unexpectedly overwritten by a more global environment setting.

I think I would err on the side of removing potentially confusing situations at the cost of perhaps reducing the power of this feature and make the config file take precedence over the environment variable.

Any thoughts?

**Comment by ilevkivskyi** [comment]
I would try to match behaviour here with the one of `MYPYPATH` vs `mypy_path` as much as possible.

**Comment by hetmankp** [comment]
That would have been ideal but for `MYPYPATH` and `mypy_path` both are merged. In the case of `cache_dir` this is not possible as there is only a single path that can apply (rather than a set of paths) so either it or the environment variable would have to take precedence.

**Comment by ilevkivskyi** [comment]
> That would have been ideal but for `MYPYPATH` and `mypy_path` both are merged. In the case of cache_dir this is not possible as there is only a single path that can apply

Well, but when you merge something, one part goes first, and another goes last, why can't we have the same "order" here?

**Comment by hetmankp** [comment]
Sure I can do that. It's just that that order makes the environment variable take precedence. I mean it should be fine as long as it's clear that the environment variable should not be used as a default fallback and I can clarify that in the documentation.
