### ISSUE TITLE
New "module has no attribute" errors in 0.710

### ISSUE THREAD

**Issue by gregbedwell** [python/mypy#7030]
This is a change in behaviour I've noticed in 0.710.  I can't help but think it's so simple that I'm obviously doing something very wrong, but I can't obviously see what.  My apologies for wasting your time if it is user error!  None of the other checking/linting tools I've tried warn about any issues here.

Here's a reproducer for what I'm seeing:

```
(py3.6) e:\tmp\mypy-issue>cat foo.py
from bar import qaz

print(qaz())
```

```
(py3.6) e:\tmp\mypy-issue>cat bar\__init__.py
from bar.baz import qaz

__all__ = [
    'qaz',
]
```

```
(py3.6) e:\tmp\mypy-issue>cat bar\baz.py
def qaz() -> int:
    return 42
```

```
(py3.6) e:\tmp\mypy-issue>python --version
Python 3.6.4

(py3.6) e:\tmp\mypy-issue>python foo.py
42
```

```
(py3.6) e:\tmp\mypy-issue>pip install -q "mypy<0.710"

(py3.6) e:\tmp\mypy-issue>mypy --version
mypy 0.701

(py3.6) e:\tmp\mypy-issue>mypy --strict .

(py3.6) e:\tmp\mypy-issue>pip install -q "mypy==0.710"

(py3.6) e:\tmp\mypy-issue>mypy --version
mypy 0.710

(py3.6) e:\tmp\mypy-issue>mypy --strict .
foo.py:1: error: Module 'bar' has no attribute 'qaz'

(py3.6) e:\tmp\mypy-issue>
```

Let me know if you need any more information.

Thanks!

**Comment by msullivan** [comment]
This is a result of the new --no-implicit-reexports flag, which is part of
--strict. See
https://mypy.readthedocs.io/en/latest/command_line.html#miscellaneous-strictness-flags

It can be fixed by doing `import qaz as qaz`.

**Comment by gregbedwell** [comment]
Ah. Brilliant. Thanks!  Sorry for the noise

**Comment by pcorpet** [comment]
@msullivan this is blocking when this happens in a dependency (I want to access `init` from https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/__init__.py).

Should I just run mypy with `--implicit-reexport` then?
