### ISSUE TITLE
[Regression] dmypy run broken on Windows with 0.710

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#7031]
This is a regression in 0.710
My environment:
Windows 10
mypy (from pypi) 0.710
Python 3.7.2

I finally got to testing the release on Windows and it seems that dmypy run is broken on Windows. This seems to be an issue with how mypyc is handling the dmypy directory.

A sample of the behavior:
```
$ dmypy run -- test.py --follow-imports=error
Timed out waiting for daemon to start.
```

The work-around for now is to install mypy without mypyc via `pip install mypy --no-binary mypy`.

Not satisfied with that, I decided to start removing binary extensions until things worked. I was able to further narrow things down to the offending file, which is (oddly) `dmypy/__main__.py`. I'm not at all sure why deleting the extension module corresponding to that file should fix things, but it does. The corresponding PR that introduced this change is #6851.

cc @msullivan

**Comment by ethanhs** [comment]
Aha, so based on the PR:
>dmypy can be compiled. Unfortunately extension modules can't be run as scripts, so we move dmypy.py to dmypy/client.py and add an interpreted dmypy/__main__.py

It seems that `dmypy/__main__.py` isn't meant to be compiled in the first place. Perhaps this is an easy fix then.

**Comment by msullivan** [comment]
Ugh it's because I put a slash in `dmypy/__main__.py` in the file list asdf

**Comment by ethanhs** [comment]
@msullivan yeah I figured that out, PR incoming :)
