### ISSUE TITLE
Dict and TypedDict are considered non-overlapping

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#7036]
For example this code doesn't type-check with `--strict-equality`:
```python
class Config(TypedDict):
    a: str
    b: str

x: Dict[str, object]
y: Config

x == y
``` 
I think we should consider typed dicts overlapping with `Dict[str, <sufficiently wide type>]`, and with `Dict[<nothing>, <nothing>]` (empty dict) only for the case where all keys are optional.

Also we should probably flag the corresponding example with overloads (but I am less convinced):
```python
@overload
def f(x: Config) -> int: ...
@overload
def f(x: Dict[str, object]) -> str: ...
def f(x):
    pass

z: Dict[str, object] = {'a': 'oh', 'b': 'no'}
f(z)  # Is this int or str?
```
@Michael0x2a what do you think?

**Comment by Michael0x2a** [comment]
I agree with your analysis -- the last example should probably be flagged, yeah.
