### ISSUE TITLE
mypy thinks that instance of ClientSession() is None (under certain conditions)

### ISSUE THREAD

**Issue by haizaar** [python/mypy#7038]
Good day,

Originally posted in aiohttp repo: https://github.com/aio-libs/aiohttp/issues/3858, but they think it's a mypy issue:

The below code produces very strange mypy error (it's a reproduction ripped of a much bigger codebase, so please excuse a mild lack of purpose)
```python
import asyncio
from typing import Type, TypeVar
import aiohttp

ResponseType = TypeVar("ResponseType", str, bytes)
# ResponseType = TypeVar("ResponseType")  <- This works, but it's not what I need in real life

async def post(response_type: Type[ResponseType]) -> None:
    async with aiohttp.ClientSession() as session:
        async with session.get("https://google.com") as res:
            res.raise_for_status()

asyncio.run(post(str))
```
```
$ mypy bug.py 
bug.py:10: error: "None" has no attribute "get"
```
The code executes fine, so the session object is definitely not None.
Interestingly enough, if I define `ResponseType` just as `ResponseType = TypeVar()`, it works fine!

I think it's a bug/issue rotating around `TypeVar` - removing `response_type` from function signature "fixes" the problem. As well I encountered situations where result of `session.get()` being an async context manager was not recognized as such by mypy which complained about `__aenter__` and `__aexit__` methods being missed, though they are clearly defined in the returned object. And again, removing TypeVar-related input variables from the function made the warning go away.

Any ideas what is going on here? 

My environment is:
* aiohttp 3.5.4
* mypy==0.710, mypy-extensions==0.4.1
* python 3.7
* ubuntu 16.04, amd64

**Comment by ilevkivskyi** [comment]
This looks like a mystery. The thing about checking body of a function with type variable restrictions is that the function body is checked multiple times for each value. Maybe we do some subtle modification while checking async with statements that cause the error on the second pass.

**Comment by haizaar** [comment]
Hopefully you are right and the mystery can be resolved in a simple matter soon :)

**Comment by hauntsaninja** [comment]
It's been many years, I can't reproduce this with latest mypy
