### ISSUE TITLE
Potential bug with dataclass, default_factory and Tuple[str]

### ISSUE THREAD

**Issue by chaoflow** [python/mypy#7040]
With mypy version: 0.710, Python 3.7.3, inspired by https://docs.python.org/3/library/dataclasses.html#dataclasses.field
```python
from typing import List, Tuple
from dataclasses import dataclass, field

@dataclass
class Data:
    foo: List[str] = field(default_factory=list)
    bar: Tuple[str] = field(default_factory=tuple)
```
results in:
```
$ mypy mwe.py
mwe.py:7: error: Incompatible types in assignment (expression has type "Tuple[_T_co, ...]", variable has type "Tuple[str]")
```

**Comment by JelleZijlstra** [comment]
This seems correct to me. Recall that `Tuple[str]` means specifically a one-element tuple, but if you construct a `Data()` object without arguments, `Data.bar` will be a zero-element tuple, which is a different type. You probably want to use `bar: Tuple[str, ...]`.

**Comment by chaoflow** [comment]
@JelleZijlstra Thank you very much for pointing that out!
