### ISSUE TITLE
Erroneous overload signature overlap

### ISSUE THREAD

**Issue by ikonst** [python/mypy#7047]
On mypy 0.710, this code:
```python
from typing import overload

@overload
def foo(a: str = ...) -> str: ...
@overload
def foo(a: int = ...) -> int: ...
```

produces the error:
```(
error: Overloaded function signatures 1 and 2 overlap with incompatible return types
```

In this case, a workaround is easy (to remove the default in one of the overloads, or create a 3rd overload for the default case), but the error is misleading nonetheless.

**Comment by JelleZijlstra** [comment]
The error is correct. The signatures overlap because a call to `foo()` could match either overload. You should remove the default from one of the two overloads.

**Comment by ikonst** [comment]
D'oh!
