### ISSUE TITLE
"Invalid type" when using class attribute as type variable.

### ISSUE THREAD

**Issue by feluxe** [python/mypy#7052]
**Are you reporting a bug, or opening a feature request?**

A bug I guess. Please excuse me if I'm missing something here.

**Code to reproduce the issue:**

```python
@dataclass
class Column:
    name: str


class Pg:
    Column = Column

pg = Pg()

@dataclass
class SearchToken:
    column: pg.Column
```
**What is the actual behavior/output?**

Mypy marks the last line as an error:

> Invalid type mypackage.mymodule.pg

**What is the behavior/output you expect?**

Mypy not complaining about the last line or a better error message, that guides me somewhere to solve the given scenario. I feel kinda lost with this right now.

**What are the versions of mypy and Python you are using?**
`Python 3.7.3`
`mypy 0.710`

**Do you see the same issue after installing mypy from Git master?**
I couldn't get this to work with `pipenv`.

**What are the mypy flags you are using?**
I don't use any.

**Comment by ilevkivskyi** [comment]
Accessing nested class on an instance is not considered statically decidable. You should instead use it as class attribute:
```python
@dataclass
class SearchToken:
    column: Pg.Column
```

**Comment by ilevkivskyi** [comment]
(For the better error message we already have an issue https://github.com/python/mypy/issues/4030)

**Comment by ilevkivskyi** [comment]
Oh wait sorry, I thought it is a nested class, but it is actually a variable, this is even more tricky. You can try `Column = Union[Column]` to force it to be an alias, but after all, why can't you just use `Column` directly.

**Comment by feluxe** [comment]
Thanks for your reply!

> You can try Column = Union[Column] to force it to be an alias

Do you mean like this:

```python
class Pg:
    Column = Union[Column]
```
?

> but after all, why can't you just use Column directly?

My example is a simplified version of the actual code. The original version was rather like this:

`postgres.py`
```python
@dataclass
class Column:
    name: str
    # More stuff going on here

class Pg:
    Column = Column
    # More stuff going on here

    async def connect(self):
        self.pool = await init_pg()

pg = Pg()
```
The `pg` instance exposes everything from the `postgres` module that is important to other modules within the porject. Other modules within the project conveniently import it like this: 

```python
from postgres import pg
```
and have everything they need.

That's why I ran into the following issue in `search.py`:

`search.py`
```python
from postgres import pg

@dataclass
class SearchToken:
    column: pg.Column
    # More stuff going on here
```

I fixed the issue by moving all pg types (`Column`, `PgInt`, etc.) into another module `pgtype.py`. But now I have to work with `pg` and `pgtype` everywhere instead of just `pg`, which is less convenient. :-)

**Comment by ilevkivskyi** [comment]
> Do you mean like this: ...

Yes, exactly, and then you should be able to use it as `Pg.Column` in annotations.

> But now I have to work with `pg` and `pgtype` everywhere instead of just `pg`, which is less convenient

Well, some patterns that come from dynamic typing world are sometimes not very reasonable in the static world. Some things can be mitigated by writing a mypy plugin if this is really important (I think someone tried to write a plugin for `gino`, that uses a similar pattern extensively).
