### ISSUE TITLE
Tuple slice by variable results in incorrect type

### ISSUE THREAD

**Issue by asottile** [python/mypy#7056]
```python
from typing import Tuple

sz = 2
x: Tuple[int, ...] = (1, 2)[:sz]
```

```console
$ mypy --version
mypy 0.711
$ mypy t.py
mt.py:4: error: Incompatible types in assignment (expression has type "int", variable has type "Tuple[int, ...]")
```

**Comment by asottile** [comment]
this is of course reduced from a larger program to a minimal reproduction

**Comment by ethanhs** [comment]
I checked and you can accomplish this with `Literal`:
```
from typing import Tuple
from typing_extensions import Final

sz: Final = 2
x: Tuple[int, ...] = (1, 2)[:sz]
```
or if you prefer, a `Literal[2]` annotation should work as well for `sz`.

**Comment by asottile** [comment]
in reality, sz is not a literal -- it's used in the following way:

```python
ver = tuple(int(p) for p in x.split('.'))
sz = len(ver)
return min_ver[:sz] <= ver <= max_ver[:sz]
```

however this is lost when converting to a minimal testcase

Here's the [current code with the `# type: ignore`](https://github.com/asottile/setup-cfg-fmt/blob/a19c422ae3cb484a3164205709339d7ac0abe1d8/setup_cfg_fmt.py#L251-L257) -- this is definitely a bug and not a question, a slice of a tuple should never return a scalar

**Comment by ethanhs** [comment]
Ah, you are correct, sorry I misunderstood the issue.

**Comment by ethanhs** [comment]
It seems the changes in https://github.com/python/mypy/pull/3514 made the incorrect decision to return the union of elements when given a slice. I'm working on a fix.

**Comment by asottile** [comment]
:clap::clap::clap: awesome! thanks for the quick fix on this one :tada:
