### ISSUE TITLE
mypy does not catch erroneous variable assignemnt

### ISSUE THREAD

**Issue by MaxG87** [python/mypy#7068]
It appears to me that mypy does not check variable definitions inside functions. This is so fundamental that I am not sure whether it is actually a bug or more some form of expected behaviour I do not understand.

I use mypy 0.701, installed by Anaconda3.  The code I am checking is:

    class Bla:
        pass
    
    
    def blubb():
        bla: int = Bla()  # Wrong type not catched by mypy
        print(bla)
    
    
    blubb()
    blablubb: int = Bla()  # error catched by mypy
    print(blablubb)

I would expect mypy to catch the assignment of wrong type at line 6 (definiton of `bla`). However, mypy only reports the error at line 11 (definition of `blablubb`). Please note that the example still works if one replaces the call to the class' constructor by a plain string.

For the sake of completeness, I include the output of mypy:

    (base) ~$ mypy --version
    mypy 0.701
    (base) ~$ mypy mypy-test.py 
    mypy-test.py:11: error: Incompatible types in assignment (expression has type "Bla", variable has type "int")

If this is a bug, I would like to report it. If it is expected behaviour, I would like to understand it better.

EDIT: I added this code to PyCharm at both wrong type hints are found there.

**Comment by msullivan** [comment]
By default, mypy only checks the bodies of functions with annotations.

**Comment by MaxG87** [comment]
Thank you very much. Now it works perfectly fine.
