### ISSUE TITLE
new semantic analyzer

### ISSUE THREAD

**Issue by dfroger** [python/mypy#7070]
Hi,

FWIW, here are the news error messages we get by using `--new-semantic-analyzer`, on a 61k lines code base (no other options are passed to `mypy`):

| error message kind                                                        | occurrences | notes |
| -------------------------------------------------------------------- | ---------------- | -------- |
| No library stub file for module 'XXX'                               | 37          | |
| Cannot find module named 'XXX'                                  | 11          | |
| Cannot resolve name "XXX" (possible cyclic definition) | 9           | |
| Missing return statement                                               | 18          | https://github.com/python/mypy/issues/3974 |
| Return value expected                                                   | 7           | all fixed in master |
| Name 'XXX' is not defined                                              | 6           | all fixed in master |
| total                                                                                | 88          | |

I'll try to investigate. This "issue" is just an information, feel free to close it!

**Edit**: add the `notes` columns

**Comment by ilevkivskyi** [comment]
Thanks! We are much more interested in the repros for particular issues than the general "stats". Also please try it on master if possible, because couple issues were already fixed there since the release.

**Comment by JukkaL** [comment]
I'm particularly interested in repros for the "No library stub file" and "Cannot find module" errors, as they look different from previous issues I've seen. The other issues are interesting as well, but they may already be fixed or they may be known issues.
