### ISSUE TITLE
The export_map field seems to be unused in NewSemanticAnalyzer

### ISSUE THREAD

**Issue by bluetech** [python/mypy#7097]
While looking at the code, I noticed this field is not used or filled anywhere.

 https://github.com/python/mypy/blob/efd68dd752410f4d987ce407354623938ff8e7f3/mypy/newsemanal/semanal.py#L258-L259

Grepping for `export_map` shows such a field is defined and filled in the (old?) `SemanticAnalyzerPass2` class, and used by stubgen, which if I am reading correctly is not using the new semantic analyzer.

It looks "suspicious" so thought I'd mention it.

**Comment by ilevkivskyi** [comment]
Thanks for reporting! This is actually very important. We need to be sure `stubgen` works with the new analyser.
