### ISSUE TITLE
mypy fails to infer one type based on another in the same union of tuples

### ISSUE THREAD

**Issue by benjaminjkraft** [python/mypy#7105]
Consider the following code:
```
from typing import Tuple, Union
def foo(flag: bool) -> Union[Tuple[None, None], Tuple[str, str]]:
    if flag:
        return None, None
    else:
        return 'hello', 'world'
def bar(flag: bool) -> str:
    a, b = foo(flag)
    if a:
        return b    # reports an error
    else:
        return 'was none'
```
This code is safe and correctly typed, but mypy returns an error:
```test.py:10: error: Incompatible return value type (got "Optional[str]", expected "str")```

The issue is presumably that it can't infer that, because `a` is truthy, we must be in the second branch of the `Union`, so `b` must also be truthy.  I'd expect this code to typecheck successfully.

versions:
mypy 0.711 or master (6d0e6377b)
python 3.7.3

**Comment by msullivan** [comment]
Mypy doesn't support this sort of linked type refinement and is I think unlikely to. Sorry.
