### ISSUE TITLE
Can't initialize frozen dataclass properties in __init__

### ISSUE THREAD

**Issue by Stiivi** [python/mypy#7106]
I assume this is rather a missing feature than a bug.

The `__init__()` in the following code is offensive:

```python
from dataclasses import dataclass
from typing import Optional

@dataclass(init=False, frozen=True)
class Thing:
    name: str
    key: str

    def __init__(self, name: str, key: Optional[str]=None) -> None:
        self.name = name
        self.key = key or name
```

The output is:

```
test.py:10: error: Property "name" defined in "Thing" is read-only
test.py:11: error: Property "key" defined in "Thing" is read-only
```

The error follows the `frozen=True` flag, although I would expect to be able to initialize the properties in the `__init__()` (or `__post_init__()`) function.

MyPy version: 0.711.

**Comment by ilevkivskyi** [comment]
This is not a mypy issue, the code actually fails at runtime with
```
dataclasses.FrozenInstanceError: cannot assign to field 'name'
```
