### ISSUE TITLE
Annotating descriptor attributes for IDEs (PyCharm etc)

### ISSUE THREAD

**Issue by and3rson** [python/mypy#7110]
This is more of a usability question.

We're using descriptors for dependency injection. We attempt to force value type of the descriptor like this (which is obviously wrong in terms of typing itself):

```python
class Service: ...
class UsersService(Service): ...
class GroupsService(Service): ...

class ServiceInjector:
    def __init__(self, name):
        self.name = name
    def __get__(self, obj, objtype) -> Service:
        if self.name == 'users':
            return UsersService()
        elif self.name == 'groups':
            return GroupsService()
        raise NotImplementerError()

class Foo:
    users: UsersService = ServiceInjector('users')  # error: Incompatible types in assignment (expression has type "ServiceInjector", variable has type "UsersService")
    groups: GroupsService = ServiceInjector('groups')  # error: Incompatible types in assignment (expression has type "ServiceInjector", variable has type "GroupsService")
```

This error reported by mypy is technically correct because type of `users` is `ServiceInjector`. Removing the `users: UsersService` type annotation makes mypy happy, but breaks completion in PyCharm and several other IDEs.

What would be the correct way to make both mypy happy & PyCharm correctly suggesting the type of `users` and `groups`? The only solution I found so far is to create a stub file for `ServiceInjector` and set its type to `Any`.

**Comment by matangover** [comment]
I think you could use generics, e.g. this seems to work:
```python
from typing import TypeVar, Generic, Type

class Service: pass
class UsersService(Service): pass
class GroupsService(Service): pass

T = TypeVar('T', bound=Service)

class ServiceInjector(Generic[T]):
    def __init__(self, type: Type[T]):
        self.type = type

    def __get__(self, obj, objtype) -> T:
        return self.type()

class Foo:
    users = ServiceInjector(UsersService)
    groups = ServiceInjector(GroupsService)
```

If you really need to use names rather than types (e.g. `'users'` rather than `UsersService`) you might be able to use [literal types](https://mypy.readthedocs.io/en/latest/literal_types.html).

**Comment by msullivan** [comment]
If pycharm doesn't understand that, you can also just suppress the mypy errors with a `cast` or a `# type: ignore`

**Comment by jaryn** [comment]
> I think you could use generics, e.g. this seems to work:
> 
> ```python
> from typing import TypeVar, Generic, Type
> 
> class Service: pass
> class UsersService(Service): pass
> class GroupsService(Service): pass
> 
> T = TypeVar('T', bound=Service)
> 
> class ServiceInjector(Generic[T]):
>     def __init__(self, type_: Type[T]):
>         self.type = type_
> 
>     def __get__(self, obj, objtype) -> T:
>         return self.type()
> 
> class Foo:
>     users = ServiceInjector(UsersService)
>     groups = ServiceInjector(GroupsService)
> ```
> 
> If you really need to use names rather than types (e.g. `'users'` rather than `UsersService`) you might be able to use [literal types](https://mypy.readthedocs.io/en/latest/literal_types.html).

I think the suggested code should work but does not. PyCharm is not offering anything from the `Service` or `UserService` when typing `Foo.users.`

It does seem to work when generic is not used:
```
     def __get__(self, obj, objtype) -> int:
         return self.type()
```
Makes `Foo.users` display the attributes of `int`.

So I conclude Pycharm doesn't know to deal well with generic descriptors.

**Comment by jaryn** [comment]
I found this is a Pycharm bug and it is tracked here: https://youtrack.jetbrains.com/issue/PY-26184
