### ISSUE TITLE
Allow nested placeholders in type alias definitions?

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#7111]
PR #7091 broke some previously supported uses involving type aliases with the new semantic analyzer, since it doesn't allow nested placeholder types in type alias definitions. Example where this happens (there are other similar test cases; see #7091):

```
[case testNewAnalyzerAliasToNotReadyDirectBase]
from typing import List

x: B
B = List[C]
class C(B): pass

reveal_type(x)
reveal_type(x[0][0])
[builtins fixtures/list.pyi]
[out]
main:3: error: Cannot resolve name "B" (possible cyclic definition)
main:4: error: Cannot resolve name "B" (possible cyclic definition)
main:4: error: Cannot resolve name "C" (possible cyclic definition)
main:7: note: Revealed type is 'Any'
main:8: note: Revealed type is 'Any'
```

It would be better if there were no complaints about cyclic definitions and the revealed types were precise.

Support for nested placeholder types was removed since it causes infinite expansions and max iteration count errors. We'd need a way to prevent this to re-enable the feature.

**Comment by aviv-ebates** [comment]
Is this:
```
SomeType = Union[int, List['SomeType']]

error: Cannot resolve name "SomeType" (possible cyclic definition)
Revealed type is 'Union[builtins.int, builtins.list[Any]]'
```

an instance of this issue?

**Comment by JukkaL** [comment]
@aviv-ebates Your example is a different, since `SomeType` is defined recursively. There is an existing issue about recursive types: #731.

**Comment by antonagestam** [comment]
Is this the same issue as https://github.com/python/mypy/issues/7069 ? My issue should probably be closed if it's the same.

> Support for nested placeholder types was removed

Does this mean the old semantic analyzer will be removed before these definitions are handled? It seems like the behavior of an ignored recursive type definition changes drastically between the old/new analyzer. I mostly want to now if we should replace them with e.g. `Dict[str, Any]` until support for recursive types is in place, or if there will be some non-breaking way to keep the definitions in place until then. :)

**Comment by ilevkivskyi** [comment]
This was enabled when enabling recursive aliases.
