### ISSUE TITLE
'%d' % SupportsInt fails

### ISSUE THREAD

**Issue by jolaf** [python/mypy#7114]
```python
i: SupportsInt = 5
s = '%d' % i
```
results in
```
Incompatible types in string interpolation (expression has type "SupportsInt", placeholder has type "Union[int, float]")
```

While in runtime it provides a reasonable `'5'`.

**Comment by msullivan** [comment]
This should be a pretty straightforward fix to `checkstrformat` if you (or someone else) wants to submit a PR

**Comment by Patil2099** [comment]
@msullivan  Where do I have to add it? I can make a PR!

**Comment by JukkaL** [comment]
It looks like fixing this involves modifying the `conversion_type` function in `mypy/checkstrformat.py` and writing a test/tests for this.

**Comment by msullivan** [comment]
@Patil2099 it looks like Ivan has fixed this as part of a broader overhaul of string formatting, though. Sorry!
