### ISSUE TITLE
Type checking of imported classes and their subclasses

### ISSUE THREAD

**Issue by MaxG87** [python/mypy#7138]
Hi there. I am importing classes from another module. Since it is actually a class, I expected some type checking to happen, which it does not.

The minimum working example is as follows:

    #!/usr/bin/env python

    from numpy.random import RandomState

    class Foo:
        pass

    class Bar(RandomState):
        pass

    def testfun(arg: Foo) -> None:
        print(type(arg))

    testfun(Foo())
    testfun(RandomState())
    testfun(Bar())

The output of `mypy type-test.py` is:

    type-test.py:3: error: No library stub file for module 'numpy.random'
    type-test.py:3: note: (Stub files are from https://github.com/python/typeshed)

I was expecting that `mypy` would report errors in the last two lines. If I accept that `mypy` cannot infer that RandomState is actually non conformant to Foo (which is quite obvious because Foo is a class not used in the imported module), I would at least expect to get an error in the last line, where I use a new defined class.

In order to verify my assumptions, I tried PyCharm which detects the typing errors.

I now wonder whether this is a bug or whether I am victim to some severe misunderstanding of how `mypy` works. I tried to find other resources but failed too find some. If I missed an existing explanation I would love to get a pointer to it.

**Comment by JukkaL** [comment]
Mypy needs library stubs to type check code involving third-party libraries such as numpy. If the stubs don't exist, mypy won't report many errors. There are some stubs available for numpy at https://github.com/numpy/numpy-stubs, though I can't say how well they work.

**Comment by MaxG87** [comment]
Does that mean that for mypy a class that inherits from another class of type Any will also be considered to be of type Any during type checking? In my case that would be Bar inheriting from RandomState.

**Comment by MaxG87** [comment]
Thank you very much here. Thanks to this answer and the one of #7140 I now have a much clearer understanding of mypy.
