### ISSUE TITLE
Filter object not iterable

### ISSUE THREAD

**Issue by mamolli** [python/mypy#7142]
Hi,
I ran into what I consider a bug:

```
def test(pkey, sortkey: Optional[Tuple[str, str]]):
    pkeys = filter(lambda x: x, (pkey, sortkey))
    expr_dict = {k: v for k, v in pkeys}
```

mypy  0.711 returns: `error: 'None' object is not iterable`
flags: `ignore_missing_imports = True`

Clearly the behaviour at runtime is to filter out the None. So the pkeys in the end is iterable.
This seems like: https://github.com/python/mypy/issues/3835

**Comment by mamolli** [comment]
Syntax: `filter(None, (a, b))` passes correctly.
Still I have strong preference for more explicit identity func.

**Comment by mamolli** [comment]
@JelleZijlstra Ofcourse, updated.

**Comment by JelleZijlstra** [comment]
I can't reproduce this then:
```
$ cat bin/filters.py 
from typing import Optional, Tuple

def test(pkey, sortkey: Optional[Tuple[str, str]]):
    pkeys = filter(lambda x: x, (pkey, sortkey))
    expr_dict = {k: v for k, v in pkeys}
$ mypy --ignore-missing-imports bin/filters.py 
$ mypy -V
mypy 0.711
```

**Comment by ilevkivskyi** [comment]
I can't reproduce this on master either.
