### ISSUE TITLE
Union is not processed correctly if it's mentioned more than one time in an expression

### ISSUE THREAD

**Issue by jolaf** [python/mypy#7143]
```python
class A:
    def f(self, other: A) -> None: ...

class B:
    def f(self, other: B) -> None: ...

v: Union[A, B]

v.f(v)
```
results in
```
Argument 1 to "f" of "A" has incompatible type "Union[A, B]"; expected "A"
Argument 1 to "f" of "B" has incompatible type "Union[A, B]"; expected "B"
```
While in fact the expression is perfectly clear and correct, and provides an excellent example of Pythonic duck typing and works fine in runtime.

**Comment by refi64** [comment]
What if this were `v.f(v := B())` and `v` were initially an A? Or some other probable expression that could modify v...

**Comment by jolaf** [comment]
@refi46 `v` is a reference. It can't reasonably be modified between looking up a method and passing a parameter. Of course situations like `v.f(g(v))` are less clear and depend on type inference. But if `g(x)` returns the same type as it's parameter, by using `@overload`, for example, than it should work too.

**Comment by JukkaL** [comment]
Yeah, mypy could do better here, though this seems relatively low priority unless somebody figures a simple way to implement this. 

Thoughts about implementing this: If a receiver has a union type and the receiver is a simple expression (such as `x`), maybe mypy could use the binder to narrow down the receiver expression type in arguments (separately for each union item).

**Comment by ilevkivskyi** [comment]
After all I think this is a duplicate of https://github.com/python/mypy/issues/6478
