### ISSUE TITLE
How do you test that annotations are consitent with expected behavior

### ISSUE THREAD

**Issue by InvisibleHandOfDoom** [python/mypy#7150]
Hi. I am not sure if that's that right place to ask, so if I've made a mistake please forgive me.

I'd like to add type annotations to a package I develop. However I cannot wrap my head around testing part. I know I can use mypy directly to check if annotations are consistent, as typeshed project does.

However I'd be more comfortable with more comprehensive coverage to be confident that my annotations really express what I need.

Let's say I have:

```python
def foo(x: int, y: int) -> int: ....
```

I'd like to be able to express both positive

```python
foo(1, 2)  # typecheck: should pass
```

and negative test cases:

```python
foo(1, "bar")  # typecheck: should fail
```

Are there any established patterns for managing such test cases? 

For the positive ones I can imagine some workarounds (like testing against examples or doctests), but it won't cut it for the negative cases. 

Thanks in advance.

**Comment by ilevkivskyi** [comment]
First, please note it is not yet possible to test stubs against sources https://github.com/python/mypy/issues/5028 (although IIUC it is not exactly what you need).

For some ideas unit-testing the types, see https://github.com/python/mypy/issues/6115 (also some projects like `sqlalchemy-stubs` just (ab)use mypy's own test framework).

**Comment by sobolevn** [comment]
You can also use https://github.com/typeddjango/pytest-mypy-plugins
Usage example: https://github.com/dry-python/returns
