### ISSUE TITLE
Type error when assigning Union to one of the Union's types

### ISSUE THREAD

**Issue by MaxG87** [python/mypy#7183]
I try to assign a Union to one of the members of the Union. Please have a look at the minimum working example:

    #!/usr/bin/env python3

    from typing import Union

    def get_str_on_true(switch: bool) -> Union[int, str]:
        if switch:
            return "string"
        else:
            return 1337

    foo: int = get_str_on_true(True)
    bar: str = get_str_on_true(True)

Here, `mypy typetest.py` complains as follows:

    typetest.py:13: error: Incompatible types in assignment (expression has type "Union[int, str]", variable has type "int")
    typetest.py:14: error: Incompatible types in assignment (expression has type "Union[int, str]", variable has type "str")

I would at least expect the assignments to work out. Ideally `mypy` would detect that get_str_on_true return str when passed True, so mypy would complain about expression having type str.

**Comment by JelleZijlstra** [comment]
Mypy generally doesn't do interprocedural inference, so all it sees is that the function returns a Union and you assign to a non-Union. I don't think there's a bug here.

You can get closer to the behavior you want by overloading on Literals (e.g., have an overload that takes `Literal[True]` and returns `str`).

**Comment by MaxG87** [comment]
So how, in a type checked way, would I extract an int from the Union in my MWE. Writing overloads is not an option in the production code I struggled with. There I actually return Dict[str, Union[...]].

**Comment by JelleZijlstra** [comment]
The general way to narrow Unions is to use `isinstance` checks.

**Comment by MaxG87** [comment]
Just a minor note for future readers of this issue.

After calming down a bit I have to admit that `mypy` does this right and, e.g., PyCharm does wrong. Union[int, str] actually is a different type than int or str. For sure it is inconvenient that one cannot assign plainly, but it is not to blame `mypy` to do type checking right.

**Comment by GregHilston** [comment]
@MaxG87 so what solution did you end up using? Having the same problem that you described

**Comment by MaxG87** [comment]
I reorganised my code to require as few checks using `isinstance` as possible. I fear there is no silver bullet here :-(.
