### ISSUE TITLE
error: Cannot redefine 'T' as a type variable with new semantic analyzer

### ISSUE THREAD

**Issue by zero323** [python/mypy#7185]
Let's say I have a structure like this one:

```
foobar
├── bar.py
├── foo.py
└── __init__.py
```

where `foo` is defined 

```python
from typing import TypeVar

T = TypeVar("T")
```

and `bar` 

```python
from typing import TypeVar
from foobar.foo import *

T = TypeVar("T")
```

With old semantic analyzer (or before dc58be0a2c1aeed3965cf87490bdf3ebdad2afb1)

```bash
mypy --python-version 3.5 --strict-optional --no-site-packages --show-traceback --no-implicit-optional --no-new-semantic-analyzer foobar
```

things work just fine. However with the new one I get:

```bash
mypy --python-version 3.5 --strict-optional --no-site-packages --show-traceback --no-implicit-optional  foobar                          
foobar/bar.py:4: error: Cannot redefine 'T' as a type variable
foobar/bar.py:4: error: Invalid assignment target
foobar/bar.py:4: error: "object" not callable
```

I wonder if this is the intended behavior, and if so, what is the rationale.

**Comment by msullivan** [comment]
Whether this is a bug is arguable, I think. At the very lease I don't think it was introduced intentionally.

(It is certainly a bug that we produce 3 error messages, one of which is redundant and one of which is nonsensical.)

I don't have any strong feelings about whether this should be allowed but fixing it feels low priority because:
 * Importing typevars is dodgy
 * `import *` is a code smell and has lots of weirdness

The workaround I'd recommend is renaming typevars to have a leading underscore in modules that are intended to be `import *`d from.

(Though if you feel strongly about this and feel like writing a PR I'd certainly review it.)

**Comment by ilevkivskyi** [comment]
IMO this should be an error. This is essentially the same as writing:
```python
T = TypeVar('T')
T = TypeVar('T')
```
The old analyzer was just sloppy about this.

The error message is not good but this is not something special about the new analyzer and we have another issue about this https://github.com/python/mypy/issues/1573.

**Comment by zero323** [comment]
Thank you for your quick reply @msullivan 

I don't have strong feelings about this either. 

For me personally, it is an inconvenience:

- I work with conservative 3rd party code, so star imports are something that is realistically out of my control.
- Generics (both types and generic `self` in mixins) are relatively common, so are `TypeVars`. In practice I use small set of identifiers (`T`, `U` for arbitrary types, `K`, `V` for key-value objects, `M` for models, `R` for readable objects and so on). Combined with the first constraint, some conflicts are inevitable.

  Leading underscores are definitely an option (something I considered before, to avoid polluting namespace with all kinds of auxiliary objects, like type aliases), but I feel like it hurts readability a bit (`class Foo(Generic[R]): ...` vs.  `class Foo(Generic[_R]): ...`  or `def foo(self: T) -> T: ...` vs. `def foo(self: _T) -> _T: ...`).


nonetheless I recognize I might have an edge case here. 
 
As of:

> Importing typevars is dodgy

It wasn't the intended outcome here, but I will argue that there are valid use cases for such imports. As mentioned above I routinely use typevars, and [in some cases](https://github.com/zero323/pyspark-stubs/blob/82cb5c329b44aa2b63f14166f405ebccd46ba6e9/third_party/3/pyspark/rdd.pyi#L19-L26) these can amount to significant amount of boilerplate. This gets even worse when you introduce type bounds, and want things to be consistent across multiple modules.

Moving these out of the module, with other auxiliary typing objects (like [this](https://github.com/zero323/pyspark-stubs/blob/pandas-functions/third_party/3/pyspark/sql/_typing.pyi)), seems like an acceptable workaround to me, though I haven't used it in practice.

**Comment by ilevkivskyi** [comment]
> It wasn't the intended outcome here, but I will argue that there are valid use cases for such imports

Yes, I actually agree importing type variables may be handy in some cases, you just need to avoid name clashes.
