### ISSUE TITLE
Add static links for error codes

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#7186]
It would be great to provide a link with a bit more detailed explanation for every error code. For example:
```
main.py:10: error [bad_variance]: Invariant type variable 'T' used in protocol where covariant one is expected
main.py:10: note: See https://mypy-lang.org/error/bad_variance for more details
```
The the link will give some explanation why this is an error and links to relevant documentation section on Read the Docs. (Such notes may be shown only once for every error code.)

Something similar is used by SQLAlchemy (but their errors use numerical codes), see e.g. http://sqlalche.me/e/f405.

Depends on https://github.com/python/mypy/pull/6472

**Comment by Shivansh-khare** [comment]
I want to work on this issue. can you tell me where are these errors messages.

**Comment by JelleZijlstra** [comment]
@Shivansh-khare you can grep for them in source code, most of them (maybe all?) appear in `messages.py` I think.

**Comment by Shivansh-khare** [comment]
@JelleZijlstra Can I hard code it with msg variable or add error_note_function for every error msg as done with incompatible_argument function at line:563 .

**Comment by ilevkivskyi** [comment]
As a first step we can create consistent links in the docs, see https://github.com/python/mypy/pull/15435
