### ISSUE TITLE
__init_subclass__ is not type-checked

### ISSUE THREAD

**Issue by GoldsteinE** [python/mypy#7190]
This code reproduces the bug: https://mypy-play.net/?gist=7c59359096250bb558136c4595fa1a47

I expect that I won't be able to create classes `B` and `C` because of incompatible `__init_subclass__()` arguments, however mypy doesn't find any errors in this. Second case (`class C`) will raise an exception at import time, but the first (`class B`) will pass.

**Comment by msullivan** [comment]
The fix I think is to add a check to `visit_class_def` in checker that checks that class's `keywords` against any `__init_subclass__` in the mro. (Probably by synthesizing a function call.)
