### ISSUE TITLE
Add support for future.utils.with_metaclass

### ISSUE THREAD

**Issue by chadrik** [python/mypy#7193]
I'm working on a codebase that uses [`future.utils.with_metaclass`](https://github.com/PythonCharmers/python-future/blob/master/src/future/utils/__init__.py#L109). 
 The interface is the same as [`six.with_metaclass`](https://github.com/benjaminp/six/blob/master/six.py#L820) so perhaps this is as simple as updating `semanal` to add `'future.utils.with_metaclass'` everywhere that `'six.with_metaclass'` is present.

**Comment by msullivan** [comment]
I think that might work, yeah.

Want to submit a PR?

**Comment by chadrik** [comment]
Done.
