### ISSUE TITLE
Use literal values to narrow overloaded argument types inside "if" body

### ISSUE THREAD

**Issue by mthuurne** [python/mypy#7213]
When checking the following code with mypy 0.720:
```py
from typing import Union, overload
from typing_extensions import Literal

@overload
def f(x: Literal[1], y: int) -> int: ...

@overload
def f(x: Literal[2], y: str) -> str: ...

def f(x: Literal[1, 2], y: Union[int, str]) -> Union[int, str]:
    if x == 1:
        return y * y
    elif x == 2:
        return y + y
    else:
        assert False, x
```
It outputs:
```
12: error: Unsupported operand types for * ("str" and "str")
12: note: Both left and right operands are unions
14: error: Unsupported operand types for + ("int" and "str")
14: error: Unsupported operand types for + ("str" and "int")
14: note: Both left and right operands are unions
```
So mypy is using the annotation of the implementation function as the type of `y`. If mypy would use the literal value of `x` to narrow the type of `y` according to the matching overloaded signature, no errors would be reported.

Unrelated to this feature request, there is something interesting going on on line 14 (`y + y`): while `y` can be an `int` or a `str`, it cannot be both during the evaluation of the same expression. Is this worth filing a separate issue for, or does it have too little practical value?

The error report on line 14 can be avoided by replacing the `Union` in the implementation annotation by a `TypeVar`, but that doesn't solve the error reported on line 12 (`y * y`) nor does it solve the actual use case this test case was based on.

**Comment by JelleZijlstra** [comment]
In general, the implementation of an overloaded function is type checked in a way that isn't aware of the precise overloads. I don't think this is specific to literals.

The issue on line 14 is #7143.

**Comment by JukkaL** [comment]
Yeah, this is just how union work. In this case you can make some types `Any` in the implementation signature or perhaps insert some casts to help mypy a bit. There's no easy way to make mypy understand this.
