### ISSUE TITLE
Incompatible types in assignment when using stubs instead of inline

### ISSUE THREAD

**Issue by iamthen0ise** [python/mypy#7225]
Hi!
I consider this behaviour as a bug. MyPy works fine with inline typing of inherited class member but reports error in the same case but with typing in stub file.

Code is:

> main.py

```
from typing import Tuple


class InlineTypedMixin(object):
    my_tuple: Tuple[str, ...] = ()


class InlineTypedClass(InlineTypedMixin):
    my_tuple = ('a', 'b', 'c')


class StubTypedMixin(object):
    another_tuple = ()


class StubTypedClass(StubTypedMixin):
    another_tuple = ('a', 'b', 'c')
```

> main.pyi

```
from typing import Tuple


class StubTypedMixin:
    another_tuple: Tuple[str, ...] = ...


class StubTypedClass(StubTypedMixin): ...
```

[also you can check this Gist](https://gist.github.com/iamthen0ise/2cf6fc91f7892d9d4dbf6f970135e0a8)

* What is the actual behavior/output?

i run checks as easy as:

` mypy --config=mypy.ini  main.py`

mypy reports for `Incompatible types in assignment` when use standalone `.pyi` stubs but works fine when typing inline.
```
main.py:14: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "StubTypedMixin" defined the type as "Tuple[]")
```

* What is the behavior/output you expect?

i expect mypy to pass the type checking while working with stub file in this case

* What are the versions of mypy and Python you are using?

Python 3.7.3
mypy==0.720

* What are the mypy flags you are using? (For example --strict-optional)

i tried both with `mypy.ini` and without flags.

mypy.ini is :
```
disallow_subclassing_any = False
ignore_missing_imports = True
warn_return_any = True
warn_redundant_casts = True
strict_optional = False
```

Maybe i do it wrong. So i will be glad to have any feedback. Thank You!

**Comment by JukkaL** [comment]
Mypy only looks at the `.py` file or the `.pyi` file of each module, not both. There has been some preliminary work to implement merging py and pyi files, but it's non-trivial. You'll need to add an extra annotation in your `.py` file to get the code to type check cleanly:

```py
...
class StubTypedMixin(object):
    another_tuple: Tuple[str, ...] = ()  # Need annotation here in the .py file
...
```
