### ISSUE TITLE
Spurious `final` errors in function referencing undefined variable

### ISSUE THREAD

**Issue by msullivan** [python/mypy#7229]
```
from typing_extensions import Final

class A:
    def __init__(self) -> None:
        self.x = 10  # type: Final
        asdf  # type: ignore
```
produces the error `Cannot redefine an existing name as final`.

My assumption is that this has to do with deferred nodes, though a few attempts to produce this error in another way failed.

**Comment by ilevkivskyi** [comment]
This looks bad, I will try to fix this.

**Comment by ilevkivskyi** [comment]
Btw this happens only with the new analyzer.
