### ISSUE TITLE
Cannot declare the type of a type variable

### ISSUE THREAD

**Issue by jaswilli** [python/mypy#7233]
After updating a project to version `0.720` I'm encountering a new error triggered by applying `Final` (from `typing_extensions`) to a `TypeVar`. A reproduction is below:

```
from typing import TypeVar
from typing_extensions import Final

# ok
MyType1 = TypeVar("MyType1")

# not ok
MyType2: Final = TypeVar("MyType2")
```

output:
```
repro.py:8: error: Cannot declare the type of a type variable
repro.py:8: error: "object" not callable
```

* mypy version: 0.720
* python version: 3.7.4
* Do you see the same issue after installing mypy from Git master?
  
Yes (`mypy-0.730+dev.b405e05e220935dca6aa895045924ee68b435091`)

**Comment by JelleZijlstra** [comment]
What would be the point of adding `Final` to a TypeVar assignment? Mypy already disallows assigning to `MyType2`.

**Comment by jaswilli** [comment]
> What would be the point of adding `Final` to a TypeVar assignment? Mypy already disallows assigning to `MyType2`.

I didn't realize it was already disallowed by mypy, that's good to know. I simply annotated the TypeVars as `Final` because it seemed like a reasonable thing to do and then when I upgraded to `0.720` I got the error.

If the new behavior is actually correct and desired then feel free to close this issue.

**Comment by JelleZijlstra** [comment]
OK, I think the old behavior of accepting final was probably just an accident, but leaving to @msullivan or @ilevkivskyi  (authors of the `Final` PEP) to close this.

**Comment by ilevkivskyi** [comment]
Yes, type variables are always implicitly final. The error message is poor, but we already have https://github.com/python/mypy/issues/1573 to track bad error messages for invalid type variables.
