### ISSUE TITLE
Import in __init__ method throwa error when used in other methods in class

### ISSUE THREAD

**Issue by mshanfard** [python/mypy#7242]
* Are you reporting a bug, or opening a feature request?
Bug

* Please insert below the code you are checking with mypy,

```
class FooBar:
    def __init__(self) -> None:
        from . import models

    def some_method(self) -> None:
          models.DummyTable.objects.create(foo=bar)

...
```

* What is the actual behavior/output?
- the code works as expected and works at run time 
- using the `--no-new-semantic-analyzer` flag there is no error from mypy
- with out the flag we get the error:
`error: Name 'models' is not defined`

* What are the versions of mypy and Python you are using?
mypy: "version": "==0.720"
python: `Python 3.7.3 64-bit`

 Do you see the same issue after installing mypy from Git master?
Yes

**Comment by JelleZijlstra** [comment]
This doesn't work at runtime either. Why do you expect it to work for mypy?

**Comment by mshanfard** [comment]
> This doesn't work at runtime either. Why do you expect it to work for mypy?
 Apologies, I updated the description. The original code runs and the exmaple here is only a modification that demonstrates the scenario that mypy throws an error.

**Comment by JelleZijlstra** [comment]
It doesn't. If you import `models` inside a function, it only exists in that function's scope, not in another function.

**Comment by JukkaL** [comment]
Closing this since mypy seems to be working according to spec.
