### ISSUE TITLE
Dictionary infering value type

### ISSUE THREAD

**Issue by ronneke1996** [python/mypy#7244]
Is it possible for mypy to infer the value of an dictionary?

I've got a problem with value types not being recognized correctly.

Example:
```python
from typing import Dict, Union

D = Union[Dict[int, str], Dict[int, int], Dict[int, bool], Dict[int, float]]

d: D = {
    0: 1,
    1: 2
}

reveal_type(d[0])
d[0] = 123 # This generates an error, this should not error in my opinion

d2: D ={
    0: 'str1',
    1: 'str2'
}

reveal_type(d2[0])
d2[0] = 'newstr' # This generates an error, this should not error in my opinion

D2 = Dict[int, Union[str, int, bool, float]]

d3: D2 = {
    0: 1,
    1: 2
}

reveal_type(d3[0])
d3[0] = 1
d3[0] = 'asdf' # This is ok, but I don't want to be able to change the type of a value like this

```

mypy output
```
test.py:10: note: Revealed type is 'Union[builtins.str*, builtins.float*]'
test.py:11: error: Incompatible types in assignment (expression has type "int", target has type "str")
test.py:11: error: Incompatible types in assignment (expression has type "int", target has type "bool")
test.py:18: note: Revealed type is 'Union[builtins.str*, builtins.float*]'
test.py:19: error: Incompatible types in assignment (expression has type "str", target has type "bool")
test.py:28: note: Revealed type is 'Union[builtins.str, builtins.int, builtins.bool, builtins.float]'
```

The revealed type on line 10 and 18 also don't seem to be right.

**Comment by JukkaL** [comment]
The revealed types on linen 10 and 18 are simplified union types. Mypy considers `bool` compatible with `int`, and since `int` can be promoted to `float`, `Union[bool, int float]` is simplified to `float` (but we may want to change this at least in some contexts, since it's confusing -- see #6168).

Do the error messages make sense assuming unions are simplified, or there another issue with the errors mypy is reporting?

**Comment by ronneke1996** [comment]
That makes sense too me. Its indeed a bit confusing.

I see I made a typo though, I meant that the error shouldn't happen. At least thats what I thing. The error on line 11 and on line 19 are incorrect.

**Comment by JukkaL** [comment]
Errors on lines 11 and 19 are as expected. You can avoid the errors by having a separate variable type declaration and assignment. This causes mypy to narrow the type down. This doesn't happen if you declare the type and assign a value in the same statement. Example:

```py
from typing import Dict, Union

D = Union[Dict[int, str], Dict[int, int], Dict[int, bool], Dict[int, float]]

d: D  # Note separate declaration
d = {
    0: 1,
    1: 2
}

reveal_type(d[0])
d[0] = 123 # No error
```

I think that this might not be properly documented, though.

**Comment by ronneke1996** [comment]
I've tried with the seperate declaration and it seems to work, thanks!
Indeed this might not be properly documented, because I haven't found it.

**Comment by JukkaL** [comment]
I added an issue about documenting this #7252.
