### ISSUE TITLE
Better message when name not available due to --no-implicit-reexport

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#7251]
Currently if an imported name is not available because of `--no-implicit-reexport`, mypy just says that it's undefined. This is confusing since it doesn't match runtime semantics. It would be better to say that the name is not an exported name. We could also explain how to mark a name as exported and maybe explain why this check is enabled.

#7247 is an example where this came up, but there have been other issues.

**Comment by samyak-jn** [comment]
Hey, @JukkaL I want to take that task for correcting it if no one is on it?
If yes, Can you please brief me with some follow-ups?

**Comment by JukkaL** [comment]
Sure, nobody is working on this right now. I'll give some pointers tomorrow.

**Comment by JukkaL** [comment]
@samyak-jn The relevant code is in `mypy/semanal.py`, in `visit_import_from`, around here:

```py
            elif module and not missing_submodule:
                # Target module exists but the imported name is missing or hidden.
                self.report_missing_module_attribute(module_id, id, imported_id, imp)
```

The error message should be changed in this case to say that the name is not an exported name, and it would be nice to add a note explaining how to export a name (`from <module> import name as name`).

**Comment by hellocoldworld** [comment]
Any updates on this?

**Comment by JukkaL** [comment]
No updates.

**Comment by hauntsaninja** [comment]
I believe https://github.com/python/mypy/pull/9237 should fix this
