### ISSUE TITLE
trouble parametrizing over TypedDict

### ISSUE THREAD

**Issue by benjaminp** [python/mypy#7255]
I would expect the following to type check correctly:
```
from mypy_extensions import TypedDict
from typing import TypeVar, Generic, Type

T = TypeVar('T')

class G(Generic[T]):
    def __init__(self, x : Type[T]):
        self.x = x

D = TypedDict('D', {})

def f(x: G[D]):
    pass

f(G(D))
```
but as of 0a7cb9422d105c7099fdf4ef6a84765ffdcf3058, it doesn't:
```
example.py:15: error: Argument 1 to "G" has incompatible type "Type[D]"; expected "Type[D]"
```

**Comment by JukkaL** [comment]
There seem to be two issues going on:
* The error message is very confusing.
* `Type[T]` doesn't work correctly with `TypedDict` types.

Here is a simpler example:

```py
from typing import Type
from mypy_extensions import TypedDict

D = TypedDict('D', {})
x: Type[D] = D
```

It produces a message similar to the original example:

```py
t.py:5: error: Incompatible types in assignment (expression has type "Type[D]", variable has type "Type[D]")
```

**Comment by ethanhs** [comment]
In #6885 Ivan wrote:

>Yeah, this doesn't work because Type[...] is not supposed to work with anything but classes, unions of classes, and Any, see PEP 484.

>It seems to me it might be possible to relax this limitation to some extent, but first of all we should fix the errors message, which is cryptic.
