### ISSUE TITLE
[Request]: Warn for None types then using Union[None, ...]

### ISSUE THREAD

**Issue by gcoimbra** [python/mypy#7258]
I think it'll be a good idea to warn the developer to check for None types when he/she indicate that the types of the variable can be None. Like this:

```
def func(var: Union[None, int]) -> int:
    return (var + 1)
                 ^ - Operation could be done on a None.

```
Or something like that...

**Comment by JelleZijlstra** [comment]
That code should already throw an error in mypy. Are you seeing that it doesn't?

**Comment by gcoimbra** [comment]
> That code should already throw an error in mypy. Are you seeing that it doesn't?

Yes. It's true, but when you do type check like this:
```
def func(var: Union[None, int]) -> int:
    if type(var) is int:
        return (var + 1)
    else:
        return 0

```

It still prints an error:

> m.py:4: error: Unsupported operand types for + ("None" and "int")
> m.py:4: note: Left operand is of type "Optional[int]"

Then this is, instead of a feature request, an bugfix?

**Comment by JukkaL** [comment]
Mypy doesn't recognize `type(x) is int` as a valid type check, since `var` could be an instance of a subclass of `int` and it would evaluate to false. If you use `isinstance(var, int)`, everything should work as expected.

**Comment by JukkaL** [comment]
Created #7260 to discuss what we should do about this (if anything).
