### ISSUE TITLE
get_dynamic_class_hook for method calls

### ISSUE THREAD

**Issue by mkurnikov** [python/mypy#7266]
In Django, there's a method `from_queryset()`, which creates a new subclass of `Manager` based on passed `QuerySet` class
https://docs.djangoproject.com/en/2.2/topics/db/managers/#from-queryset

`get_dynamic_class_hook` is a hook to use it this case, but unfortunately it only called for functions, not for methods.

**Comment by msullivan** [comment]
Yeah, this sounds like something we need. Would you like to submit a PR?

**Comment by mkurnikov** [comment]
Sorry, I won't be able to do it anytime soon. Maybe @aleksanb would like to do it, as he was the one who pointed out the bug in `django-stubs`.
