### ISSUE TITLE
Remove old semantic analyzer

### ISSUE THREAD

**Issue by msullivan** [python/mypy#7278]
The new semantic analyzer seems to be working well, so we should delete the old one.

I'm happy to do this unless @JukkaL or @ilevkivskyi would like to do the honors after having built the new one ;)

**Comment by JukkaL** [comment]
I'm happy to do this next week, but if somebody else wants to do this, please go ahead :-)

**Comment by ilevkivskyi** [comment]
I think this can be closed now (normally we close issues that are fixed on master).
