### ISSUE TITLE
Singleton as enum doesn't work as expected

### ISSUE THREAD

**Issue by lmazuel** [python/mypy#7279]
Hello,

Based on the tag in the commit https://github.com/python/mypy/commit/e818a96917a5111c4a5b901d49aa6b36de9700d3 that is the merge commit of https://github.com/python/mypy/pull/7000, that is declared to fix https://github.com/python/mypy/issues/1803, the singleton scenario as described in https://www.python.org/dev/peps/pep-0484/#support-for-singleton-types-in-unions should be supported in 0.720.

However, it's still not the case:
```python
from typing import Union
from enum import Enum

class Empty(Enum):
    token = 0
_empty = Empty.token

def func(x: Union[int, None, Empty] = _empty) -> int:

    if x is _empty:
        return 0
    elif x is None:
        return 1
    else:  # At this point typechecker knows that x can only have type int
        return x * 2
```
does:
```
singleton.py:15: error: Unsupported operand types for * ("Empty" and "int")
singleton.py:15: note: Left operand is of type "Union[int, Empty]"
```

Have I misunderstood something?

Thank you!

**Comment by Michael0x2a** [comment]
You'll need to annotate `_empty` as being Final. For example, see [this test case](https://github.com/python/mypy/blob/master/test-data/unit/check-enum.test#L811).

Without it, mypy thinks that it's possible for `_empty` to be later reassigned to some other variant of the `Empty` enum. (Of course, that's impossible in this case since `Empty` contains only a single variant, but mypy doesn't treat single-variant enums any differently from other enums and so won't special-case this particular interaction.)

**Comment by lmazuel** [comment]
Gotcha. I have what I need then, thank you!
Out of curiosity, does it it mean PEP484 would need an update (I literally just copied/pasted it to follow the recommendation here)?

**Comment by JukkaL** [comment]
I wonder if we should special case this in mypy. @Michael0x2a What do you think about this?

**Comment by Michael0x2a** [comment]
Yeah, I think special-casing could be reasonable, though probably it's not a big priority given that there's an easy workaround.

Actually, now that I'm thinking about it, I wonder if it might be as easy as just adding another case to the `is_singleton_type` and `coerce_to_literal` functions at the bottom of https://github.com/python/mypy/blob/master/mypy/checker.py. I'll try following up on this idea later this weekend. (@lmazuel -- or do you maybe want to try taking a stab at this?)

**Comment by lmazuel** [comment]
Hi @Michael0x2a sorry for the late answer, was in vacation :).
I don't know if I have the skills to do that honestly, so please assume I don't (that's safer :)) but I will try to find time to understand this (maybe :))
Thanks!
