### ISSUE TITLE
`assert` second (error) expression should be type checked as conditional on the failed predicate

### ISSUE THREAD

**Issue by gwk** [python/mypy#7284]
`assert` has two forms; the two-expression form could be handled better by the type checker. The second expression only evaluates when the predicate (first expression) fails, and should therefore be type checked under that assumption.

For example, here we have a regex that validates a string. When the regex matches, the assertion fails; `m` was just shown not to be None, so the f-string is ok to evaluate `m[0]`.
```
import re
s = 'a!b'
m = re.search('\W', s)
assert not m, f'illegal char: {m[0]!r}'
```

Mypy currently rejects this code, but should accept it:
```
t.py:6: error: Value of type "Optional[Match[str]]" is not indexable
```

**Comment by msullivan** [comment]
I think it should be pretty simple to fix this using logic similar to how `and` and `or` are handled

**Comment by gantsevdenis** [comment]
May I take this?

**Comment by msullivan** [comment]
Sure! Thanks!
