### ISSUE TITLE
Protocol requires __slots__ to be explicitly typed

### ISSUE THREAD

**Issue by matthewvalentine** [python/mypy#7290]
Bug report. Mypy version: mypy 0.730+dev.445020f0ed9939b43371edbddcf5b083a706d6d8

**Code:**
```
class A(Protocol):
    __slots__ = ()
```

**Expected:**

Passes, and `__slots__` is not part of the Protocol interface. It's just being provided to prevent subclasses from being forced to have a `__dict__`.

**Actual:**
```
error: All protocol members must have explicitly declared types
```

**Comment by msullivan** [comment]
This is a definitely a bug, though should be easy to work around with a `type: ignore`. It should be pretty easy to fix if you want to take a look
