### ISSUE TITLE
"No library stub file for module" despite stubs in typeshed

### ISSUE THREAD

**Issue by EtienneBruines** [python/mypy#7298]
## Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
A bug.

* Please insert below the code you are checking with mypy,

```python
# This is the file a.py
from cryptography.hazmat.primitives import serialization
```

* What is the actual behavior/output?
```
a.py:2: error: No library stub file for module 'cryptography.hazmat.primitives'
```

* What is the behavior/output you expect?
No error (and mypy actually using the stubs)

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
Python 3.7.3, and mypy 0.720. Same behavior for mypy `0.730+dev` (current master)

* What are the mypy flags you are using? (For example --strict-optional)
None. 

## Some context

The module `cryptography.hazmat.primitives` does have stubs under `typeshed/third_party/2`, which is successfully installed under the `mypy` directory. 

I have tried running with different `PYTHONPATH` and `MYPYPATH` environment variables, even without either - but no luck. 

Tested for the same without `virtualenv` and a globally installed `mypy` - but it's not picking up the stubs. 

Of course, `ignore_missing_imports` is no option here because the stubs are present.

**Comment by srittau** [comment]
This is a [typeshed](/python/typeshed) issue. The problem is that the `cryptography` stubs are in `stdlib/2`, not `stdlib/2and3`, so they are only available under Python 2. Someone would need to vet that the stubs apply to Python 3 as well and provide a patch to move them over at the typeshed repository.

**Comment by EtienneBruines** [comment]
So that's what the `/2` means :see_no_evil: 

... meaning that the stubs aren't installed for python 3 and therefore the same "stubs are missing" would apply as for any other package. 

Thanks @srittau
