### ISSUE TITLE
Cannot find module named cattr even though it is installed

### ISSUE THREAD

**Issue by josephaxisa** [python/mypy#7305]
I am not sure if this is a `mypy` problem but importing `cattr` at the top of my file, VSCode can follow the import. `mypy` can follow other imports in the same `site-packages` directory but not `cattr`. The error I get is:
`Cannot find module named 'cattr'`

Here's a peek into my virtual environment:
```
❯ which mypy
/Users/myuser/.local/share/virtualenvs/python-tSv9DKEa/bin/mypy

❯ pipenv run pip install cattrs
Requirement already satisfied: cattrs in /Users/myuser/.local/share/virtualenvs/python-tSv9DKEa/lib/python3.7/site-packages (1.0.0rc0)
Requirement already satisfied: attrs>=17.3 in /Users/myuser/.local/share/virtualenvs/python-tSv9DKEa/lib/python3.7/site-packages (from cattrs) (19.1.0)

❯ which cattrs
cattrs not found

❯ which cattr
cattr not found

❯ which pytest
/Users/myuser/.local/share/virtualenvs/python-tSv9DKEa/bin/pytest

❯ ls -l /Users/myuser/.local/share/virtualenvs/python-tSv9DKEa/lib/python3.7/site-packages
drwxr-xr-x   13 myuser  staff       416  8 Aug 17:28 cattr
drwxr-xr-x    8 myuser  staff       256  8 Aug 17:28 cattrs-0.9.0.dist-info
```

**Comment by ethanhs** [comment]
AFAICT cattrs only added support for typing 3 months ago. Therefore you likely need a new version before mypy will be able to pick up the type information.

**Comment by AlexWaygood** [comment]
Hi! @josephaxisa, is this still a problem, or can this now be closed? :)

**Comment by erictraut** [comment]
This appears to no longer be an issue. I think it's safe to close.
