### ISSUE TITLE
PEP 572: Assignments not narrowed in right-hand side of and

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#7313]
The binder interaction doesn't work properly for assignments in the right-hand side of an `and` (after `if x and (y := 1):`, the type of `y` isn't narrowed to `int`).

Test case:
```

[case testAndRHS]
from typing import Optional

def f(x: Optional[int], y: Optional[int]) -> None:
    if x and (y := 1):
        reveal_type(y)  # N: Revealed type is 'builtins.int'
```
(Currently it produces `Revealed type is 'Union[builtins.int, None]'` instead.)

Followup from #6899

**Comment by ilevkivskyi** [comment]
@JelleZijlstra Just to clarify, will you have time/desire to work on the follow-up issues?

**Comment by JelleZijlstra** [comment]
Don't count on it; I don't have a lot of time right now. If I start work on one of them I'll assign it to myself.
