### ISSUE TITLE
Document error codes

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#7340]
Follow-up to  #7239.

I'm thinking of adding non-trivial documentation for each error code, as this would also serve as documentation about the kinds of issues mypy can find.

**Comment by ilevkivskyi** [comment]
Probably this was already discussed elsewhere, but maybe we should add a command flag like `--list-error-codes` that will just print a simple table like `error-code: Short description like in errorcodes.py`?

**Comment by JukkaL** [comment]
@ilevkivskyi Yeah, that was the idea. I'll create an issue.

**Comment by JukkaL** [comment]
This was implemented in #7451.
