### ISSUE TITLE
Type detection doesn't work with TypedDict

### ISSUE THREAD

**Issue by priyank-p** [python/mypy#7344]
* Are you reporting a bug, or opening a feature request? **Bug**
* Code that reproduces the issue:
```python3
from typing import Union, List, Iterable
from typing_extensions import Literal, TypedDict

# Goal here is to add mypy type so that
# if the dict's key is 'a' or 'b' mypy knows
# that the value should be int or str.
ABDictT = TypedDict('ABDictT', {
    'key': Literal['a', 'b'],
    'value': Union[str, int]
})

# If key is 'c', or 'd' then mypy should know
# value should be str, or int list.
CDDictT = TypedDict('CDDictT', {
    'key': Literal['c', 'd'],
    'value': Union[str, Iterable[int]],
})

ValueDictElementT = Union[ABDictT, CDDictT]
ValuesDictT = Iterable[ValueDictElementT]

def some_func(values: ValuesDictT) -> None:
    for element in values:
        if element['key'] == 'a':
            # The reveal_type here show the type to be
            # Union[str, int, Iterable[int]] since we
            # did a check that element['key'] is 'a' mypy
            # should be able to tell that the type is
            # ABDictT here?
            reveal_type(element['value'])
```

* What is the actual behavior/output?
```
$ mypy --strict repro.py
repro.py:30: note: Revealed type is 'Union[builtins.str, builtins.int, typing.Iterable[builtins.int]]'
```

* What is the behavior/output you expect?
`mypy` should be able to tell that the type is `ABDictT` after checking that the key is `a` and therefore the output on the `reveal_type` should be `Union[str, int]`.
```
$ mypy --strict repro.py
repro.py:30: note: Revealed type is 'Union[builtins.str, builtins.int]'
```

* What are the versions of mypy and Python you are using? **Python: 3.6.8, mypy: 0.720**
  Do you see the same issue after installing mypy from Git master? **Yes**
* What are the mypy flags you are using? (For example --strict-optional) **I did use `--strict` but it can also be reproduced with no flags.**

**Comment by priyank-p** [comment]
I also figured out a simpler code the reproduces this:
```python
from typing import Union, Iterable
from typing_extensions import TypedDict

Dict1T = TypedDict('Dict1T', {
    'key': str,
    'value': int
})

Dict2T = TypedDict('Dict2T', {
    'key': int,
    'value': Iterable[int]
})

ValuesDictElement = Union[Dict1T, Dict2T]
ValuesDictT = Iterable[ValuesDictElement]

def some_func(values: ValuesDictT) -> None:
    for element in values:
        if isinstance(element['key'], str):
            reveal_type(element['value'])
```

**Comment by JelleZijlstra** [comment]
There was a recent bug report asking for something like this in a simpler form (e.g. `Union[Tuple[A, B], Tuple[C, D]]`, where you isinstance the first element of the tuple and expect mypy to know the type of the second element). It's unlikely that mypy will support this.

**Comment by ilevkivskyi** [comment]
Actually, I think we might want to special-case typed dicts, because one can't use `isinstance()` to select an item item from union as one would do with other classes.

Also there is somewhat similar pattern in TypeScript where one can use a string literal to select an item from union.

**Comment by ilevkivskyi** [comment]
cc @Michael0x2a
