### ISSUE TITLE
Mypy doesn't behave consistently in a specific situation when a function is defined in `def` form vs when it's defined in `lambda` form

### ISSUE THREAD

**Issue by jrheard** [python/mypy#7345]
Please feel free to edit this issue's title, it isn't a good title, I think I'm missing some vocabulary here :)

Mypy behaves inconsistently when passing a `key` function to `sorted()` when sorting a list of heterogeneous dicts. if the `key` function is defined with `def` syntax, mypy passes; if the function is defined with `lambda` syntax, mypy emits an error. It seems to be necessary that the dicts are heterogeneous, I didn't see this behavior when sorting a list of `Dict[str, str]` dicts.

* Are you reporting a bug, or opening a feature request? **Bug**

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
sorted(
    [{'foo': 'bar'}, {2: 3}],
    key=lambda thing: thing['foo'],
)
```

* What is the actual behavior/output?

```
[jrheard@abaia:~] 🚂  mypy foo.py
foo.py:3: error: Value of type "object" is not indexable
[jrheard@abaia:~] 🚂
```

* What is the behavior/output you expect?

```
[jrheard@abaia:~] 🚂  mypy foo.py
[jrheard@abaia:~] 🚂
```

* What are the versions of mypy and Python you are using? **Python 3.7.4, mypy 0.7.20**

* Do you see the same issue after installing mypy from Git master? **Yes**

* What are the mypy flags you are using? (For example --strict-optional) **None**

---

Notice that this code passes mypy:

```python
def foo_getter(thing):
    return thing['foo']

sorted(
    [{'foo': 'bar'}, {2: 3}],
    key=foo_getter,
)
```

It looks like there's a bug/inconsistency having to do with passing `lambda`s to `sorted()`'s `key` kwarg when sorting a list of heterogeneous dicts. It's possible that the inconsistency gets triggered in other situations too, this is just the one that I ran into personally.

**Comment by refi64** [comment]
In the latter case, won't foo_getter be ignored by mypy since it has no
annotations, so no errors are reported?

**Comment by ethanhs** [comment]
I believe mypy is consistent here. As @refi64 notes, in the second case, the function is not checked, so it is allowed. In the error case, mypy must find a common base type for the elements of the list, and this is object. Therefore it infers `List[object]`. This is the correct behavior. You might consider using a union for the elements or something like that. But your example will raise an error so it's hard to tell what you are trying to do.
