### ISSUE TITLE
Werkzeug ProxyFix

### ISSUE THREAD

**Issue by revmischa** [python/mypy#7347]
Flask didn't answer my question and said to ask here
https://github.com/pallets/flask/issues/3335

The docs say (https://flask.palletsprojects.com/en/1.1.x/deploying/wsgi-standalone/#proxy-setups):
```python
from werkzeug.middleware.proxy_fix import ProxyFix
app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_host=1)
```
I get this from mypy:

`qc/create_app.py:47: error: Cannot assign to a method`

What's the correct solution here? Why can't I assign to it?

**Comment by ilevkivskyi** [comment]
Normally mypy doesn't allow monkey-patching (there is already a feature request about partially enabling this). You can `# type: ignore` this error.
