### ISSUE TITLE
False exception error in except clause with a ternary conditional operator

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/mypy#7356]
```python
import sys
try:
    f = open('.', 'rb')
except PermissionError if sys.platform == "win32" else ():
    pass
```
MyPy reports an error:
```
e.py:4: error: Exception type must be derived from BaseException
```
Actually `except` accepts either an exception type, or a tuple of exception types (including an empty tuple).

`(PermissionError,) if sys.platform == "win32" else ()` also causes an error. But `(PermissionError,) if sys.platform == "win32" else (IsADirectoryError,)` is accepted by MyPy.

**Comment by serhiy-storchaka** [comment]
See also #5128.

**Comment by ethanhs** [comment]
Yes, it looks like we need to special case except as well as raise as pointed out in #5128.

**Comment by hauntsaninja** [comment]
Fixed in https://github.com/python/mypy/pull/17427
