### ISSUE TITLE
Check class type parameter variance violations in inheritance

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#736]
In generic inheritance, we can't change the variance of a type from invariant to covariant/contravariant. This should probably be rejected:

```
IV = TypeVar('IV')
CV = TypeVar('CV', covariant=True)

class A(Generic[IV]): ... # Bunch of methods
class B(A[CV], Generic[CV]): pass  # Error, type variable should be invariant
```

Going from covariant to invariant is fine (for example, `List` has to do this since it subclasses `Sequence`, which is covariant).

**Comment by jhance** [comment]
Seems like we break this in our own tests but fixing the `lib-stub` to make `Sequence` covariant on `T` should fix that.

**Comment by jhance** [comment]
I have this done on a branch, will submit PR later when my other stuff related to variance is in (since fixing this depends on fixing variance in general)

**Comment by jhance** [comment]
It just struck me that we should reject things like `List[Sequence[T]]` where `T` is covariant. This is going to be fun...

**Comment by JukkaL** [comment]
Yeah, `List[Sequence[T]]` would also be invalid. 

I'm sure there's a research paper that goes through all the special cases. Some of these might be relevant, in case you want to dig deeper (warning greek alert):

http://research.microsoft.com/en-us/um/people/akenn/generics/
