### ISSUE TITLE
How to annotate concrete global object instance?

### ISSUE THREAD

**Issue by jacek-jablonski** [python/mypy#7377]
Hi,
I have defined concrete object which is global for my application:
`Undefined = object()`

Now I would like to annotate method, something like:
`def modify_account(uid: str, name: Union[str, Undefined] = Undefined):`
But it is not valid.
Now, how should I annotate function that accepts str, None or Undefined?

**Comment by ilevkivskyi** [comment]
There are two options:
1. Use singleton pattern (there are tons of recipes online), something like:

    ```python
    class Undefined:
        __instance: Optional[Undefined] = None
        def __new__(cls) -> Undefined:
            # Either raise or return existing instance here.
            ...
    ```
2. Mypy treats enum values as singletons, look at the examples in this section https://www.python.org/dev/peps/pep-0484/#support-for-singleton-types-in-unions

Also please next time ask your questions on typing Gitter channel (or other help forums). The tracker is for bug reports and feature requests.
