### ISSUE TITLE
Option to recurse into namespace packages

### ISSUE THREAD

**Issue by jack1142** [python/mypy#7380]
Unless current behaviour is unintended, this is more of a feature request.

I would like to have option for mypy to recurse into namespace packages - currently if I have `somepackage` with `ext` namespace package, mypy will not recurse into packages in that namespace package. Here's an example tree:

```
.
└── somepackage
    ├── __init__.py
    ├── module_a.py
    └── ext
        └── someextension
            ├── __init__.py
            └── module_b.py
```

For such tree, running `mypy --strict --namespace-packages -p somepackage` (I also tried adding ` will only check files that are inside `somepackage`. Adding empty `__init__.pyi` to `ext` folder will solve this problem but it's really just a workaround for this problem.

I checked this tree with mypy from master (Python 3.7.4) to make sure this wasn't solved in the meantime.

**Comment by ilevkivskyi** [comment]
Just double-check is this a duplicate of https://github.com/python/mypy/issues/6385 or you want something different?

**Comment by jack1142** [comment]
Yes, looks like it, my bad, I rushed with sending this issue a little and only looked through most recent issues regarding namespace packages.
