### ISSUE TITLE
Error codes in # type: ignore don't suppress related notes

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#7384]
For example:
```python
import nostubs  # type: ignore[import]
```
Causes
```
mypy/report.py:30: note: (Stub files are from https://github.com/python/typeshed)
```
and error code 1. I didn't check carefully, but I think this affects all error messages that also emit additional notes (there are quite many of them).

**Comment by JukkaL** [comment]
Looks like each note should have the same error code as the corresponding error.
