### ISSUE TITLE
Initializer not checked against declared type when annotating using self.x

### ISSUE THREAD

**Issue by sotte** [python/mypy#7398]
`mypy` accepts instance variables that are instantiated as `None` even though the type indicates int. This is not the case for equivalent `dataclasses`. I'm not sure if this is a bug or intended behavior.

Here is a minimal example:
```python
from dataclasses import dataclass, field


class Foo:
    def __init__(self):
        self.bar: int = None


@dataclass
class Foo2:
    bar: int = None
    bar2: int = field(default=None)
```

This is how I check the fiel: `mypy mypy_demo.py`.

Here the resulting error msgs:
```
mypy_demo.py:11: error: Incompatible types in assignment (expression has type "None", variable has type "int")
mypy_demo.py:12: error: Incompatible types in assignment (expression has type "None", variable has type "int")
```

I did not find anything helpful in the dataclass section: https://mypy.readthedocs.io/en/latest/additional_features.html#dataclasses

I'm testing with Mypy version 0.701.

**Comment by JukkaL** [comment]
Thanks for reporting this! The initialization in `Foo` should be rejected by mypy. This is quite serious, as even a totally bogus initializer is accepted:

```py
class Foo:
    def __init__(self):
        self.bar: int = 'x'  # No error even though this is clearly wrong!
```

**Comment by ilevkivskyi** [comment]
Adding `-> None` helps. Note however `--check-untyped-defs` is broken for `__init__()`, see https://github.com/python/mypy/issues/7309 (there are also couple issues mentioned that we may potentially close as duplicates).

**Comment by ilevkivskyi** [comment]
https://github.com/python/mypy/issues/7291 is also related (I think it was discussed whether we should just assume the `-> None` by default in other issues. IIRC there is no consensus because either option has drawbacks, so status quo wins)

**Comment by JukkaL** [comment]
Oops, #3948 bites again.

**Comment by sotte** [comment]
Thanks for the quick response!

Just for completeness sake: my assumption was, that I can do `self.bar: int = None` because it's also ok to do `def bob(a: int = None): print(a)`. That is that an implicit `Optional` would be used.

```python
from dataclasses import dataclass, field


class Foo:
    def __init__(self):
        self.bar: int = None

    def bob(self, a: int = None):
        print(a)


@dataclass
class Foo2:
    bar: int = None
    bar2: int = field(default=None)
```

**Comment by sotte** [comment]
Thanks for clarification!
