### ISSUE TITLE
Import Error on type_check_only

### ISSUE THREAD

**Issue by max-sixty** [python/mypy#7403]
* Are you reporting a bug, or opening a feature request? Bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
from typPython 3.7.4 (default, Jul  9 2019, 18:13:23)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from typing import type_check_only
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6cbfdb632622> in <module>
----> 1 from typing import type_check_only

ImportError: cannot import name 'type_check_only' from 'typing' (/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
```

* What is the behavior/output you expect?

Function as per https://docs.python.org/3/library/typing.html#typing.type_check_only

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

mypy master
Python 3.7.4

* If mypy crashed with a traceback, please paste
  the full traceback below.

Maybe I'm doing something very basically incorrect?

**Comment by brandtbucher** [comment]
From the link you provided:

> This decorator is itself not available at runtime. It is mainly intended to mark classes that are defined in type stub files if an implementation returns an instance of a private class:

**Comment by max-sixty** [comment]
Ah, I see now, thanks

I'm trying to mark a class as having a method that is monkey-patched on by an external library. Is there an idiomatic way of doing this?

**Comment by brandtbucher** [comment]
Typically, what you would use here is a typed signature where the body is just `raise NotImplementedError()`. Mypy gets the point:

```py
class MyIncompleteClass:
    
    def this_should_come_later(self, some: int, args: str) -> float:
        raise NotImplementedError()
```

**Comment by max-sixty** [comment]
Great! I had worried that that would stop the monkey patch working, but it actually works great. Thank you!
