### ISSUE TITLE
Explain that mypy should be run in the package root directory

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#7405]
If I have a package `pkg/` and I run mypy while the current working directory is `pkg`, mypy can't resolve imports from `pkg`. This is consistent with how Python works (see #7389 for discussion), but it may be surprising for some users. Mypy could detect this issue and generate a note that would tell the user to switch to another directory.

More details: If an imported module can't be resolved, but the current working directory contains a `__init__.py[i]` file, see if the import could be resolved if some parent directory was added to the search path. If yes, add a note suggesting that the current working directory should perhaps be changed to a parent directory.

**Comment by Shashankjain12** [comment]
hello @JukkaL  can you assign me the issue so that I can start working on this paricular issue?

**Comment by JelleZijlstra** [comment]
@Shashankjain12 feel free to just start working on this.

**Comment by Shashankjain12** [comment]
hello @JelleZijlstra  i am new to open source can you suggest me which file to edit in order to prompt users that they are in wrong directory while executing the code?

**Comment by JukkaL** [comment]
@Shashankjain12 You'll probably need to edit `mypy/build.py` (and/or maybe some other module imported there). One way to move forward is to find the code that generates the error message about the import, and look around there.
