### ISSUE TITLE
Support indexing and iterating Enum type objects

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#741]
Assume this definition of `Color`:

```
from enum import Enum
class Color(Enum):
    red = 1
    green = 2
    blue = 3
```

Now this should be valid, but mypy complains about it:

```
Color['red']
```

The error message indicates that mypy thinks that the programmer is trying to construct a generic type, which is not the case here:

```
$ mypy t.py
t.py:8: error: Name 'red' is not defined
```

**Comment by johnthagen** [comment]
@JukkaL Another related `Enum` issue is that Mypy currently doesn't understand that [`Enum`'s can be iterated on](https://docs.python.org/3/library/enum.html#creating-an-enum).

```python
import enum


@enum.unique
class Color(enum.Enum):
    red = 1
    green = 2
    blue = 3

for color in Color:
    print(color)
```

When run:

```
Color.red
Color.green
Color.blue
```

When `mypy` 0.4.4 is run on the file:

```
a.py:10: error: Iterable expected
a.py:10: error: "Color" has no attribute "__iter__"
```

**Comment by gvanrossum** [comment]
See also #2305.

**Comment by tgy** [comment]
Is someone working on this?

**Comment by gvanrossum** [comment]
> Is someone working on this?

Not yet.

**Comment by JukkaL** [comment]
Increasing priority since this seems to be among the most common issues mypy users encounter.

**Comment by ilevkivskyi** [comment]
I just have tried ``Color['red']`` and it works. The second snippet:
```python
for color in Color:
    print(color)
```
still fails however.

**Comment by JukkaL** [comment]
Yes, I just noticed that myself.

**Comment by gvanrossum** [comment]
Iterating is now fix by python/typeshed#1136.

**Comment by tgy** [comment]
Thanks @gvanrossum! 😄

**Comment by jboning** [comment]
I'm not sure this is completely fixed: `Color['red']` works, but `val = Color['red']` results in the old error.

Adding an explicit annotation (`val : Color = Color['red']`) fixes the error and is an easy workaround, so whatever remains here is probably a lower priority to fix.

**Comment by JelleZijlstra** [comment]
From the discussion on Gitter, it seems that `val = Color['red']` is interpreted as constructing a type alias.

**Comment by gvanrossum** [comment]
Could you file a new issue?

**Comment by jboning** [comment]
Forked off another issue at #3137
