### ISSUE TITLE
Use enum34 when running tests on pre-3.4 Python versions

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#742]
Currently `enum` is treated Python 3.4 only.

**Comment by berdario** [comment]
If I understand this correctly, this also means that the stub won't be used in Python3.5

**Comment by o11c** [comment]
@berdario the internal logic, just checks whether the name is `enum.Enum`, so if the stub is found it will work. Might also want to change the testsuite bits though.

**Comment by berdario** [comment]
I see. I'm not sure if the stub is correctly found then.

I wrote a small project to try out mypy, now that `typing` is in the stdlib, and I had to add a couple of ugly `Any` type declarations to get it to type check:

https://github.com/berdario/resumable-urlretrieve/blob/faa631f/resumable/__init__.py#L28-L29

Aside from that, it works quite well, and I even got [travis-ci to run `mypy`at every commit to type check the module](https://travis-ci.org/berdario/resumable-urlretrieve) :D

**Comment by o11c** [comment]
I don't think mypy is fully compatible with the stdlib's `typing` yet, I haven't been following that closely though.

**Comment by JelleZijlstra** [comment]
I think this is a typeshed issue now, but we still need enum34 stubs in typeshed.

**Comment by JukkaL** [comment]
Apparently `enum34` just installs `enum`, so making the current typeshed stubs available for all Python versions might be good enough. However, this issue is no longer relevant since we no longer use typeshed stubs for `enum` in mypy tests.
