### ISSUE TITLE
Support for variadiac arguments for inherited classes?

### ISSUE THREAD

**Issue by adewes** [python/mypy#7424]
I'm unsure if this might be a bug, a feature request or if I just failed to find the right spot in the documentation.

**What I want to do**: I have an abstract base class that defines an interface which derived classes need to implement. There's an abstract method `run` that requires several mandatory arguments, and may accept additional optional arguments (to override defaults). Currently I'm not sure how I can model this using mypy. Here's some example code that reproduces the issue (ran with **Python 3.7** and **mypy 0.720**:

```
import abc
  
from typing import Any

class Base(abc.ABC):

    @abc.abstractmethod
    def run(self, model: Any, **kwargs: int) -> None:
        pass

class Child(Base):
    def run(self, model: Any, foo : int) -> None:
        pass
```

This produces the following error:

```
mypy_test.py:12: error: Signature of "run" incompatible with supertype "Base"
```

I sued the `**kwargs` annotation in reference to [this PEP](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values) but I realize the use case is different. I couldn't find anything in the mypy documentation about annotating this correctly.

I could of course use `**kwargs` in the `Child` class and parse optional parameters from there, but I don't think that's a good solution. Any help to get this working would be highly appreciated!

**Comment by JukkaL** [comment]
The override is unsafe (violates Liskov substitutability), so mypy is acting as designed here. Mypy requires that method overrides have more general signatures than the original method. You can add a `# type: ignore` comment on the line with error to silence this.

**Comment by adewes** [comment]
Ok thanks for the feedback, I'll used the `kwargs` route then for now as I don't want to ignore the type information.

**Comment by bpshaver** [comment]
For anyone reading this in the future dealing with a similar problem, it appears that the following modification to the example code does pass mypy:

`import abc
  
from typing import Any

class Base(abc.ABC):

    @abc.abstractmethod
    def run(self, model: Any) -> None:
        pass

class Child(Base):
    def run(self, model: Any, foo : int = 5) -> None:
        pass
`

As far as I can tell, this works since it doesn't violate the Liskov substitution principle. Since `foo` now has a default value, instances of `Child` work where instances of any subclass `Base` might be expected.

**Comment by salihunnnmdn** [comment]
import abc
  
from typing import Any

class Base(abc.ABC):

    @abc.abstractmethod
    def run(self, model: Any) -> None:
        pass

class Child(Base):
    def run(self, model: Any, foo : int = 5) -> None:
        pass

**Comment by horace-extravaganza** [comment]
@JukkaL https://carlisle488.github.io/G3bexM08mP6MJj9MxtkH6zeRod3gtr8ToqULpudeg1BSUgH1XFMWohia/
