### ISSUE TITLE
Add an error warning for calling str(x) where x can be bytes

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#7432]
In most cases calling:
```python
x: bytes
y = str(x)
```
is an error on Python 3, because `str(b'abc')` results in `"b'abc'"`. Now that PR https://github.com/python/mypy/pull/7418 prohibits `'%s' % x` and `'{}'.format(x)` if `x` can be `bytes` it would make sense to prohibit a direct call as well. We can add a special error code for such errors so that people can easily ignore it (or use `repr(x)`, `'%r' % x`, or `'{!x}'.format(x)`).

**Comment by ilevkivskyi** [comment]
Note that we already have a plugin internally, so an easy solution would be to just make it part of mypy.

**Comment by hauntsaninja** [comment]
I haven't seen this feature request come up much and Python 2 has been dead for a long time, so closing
