### ISSUE TITLE
Dataclasses extending multiple dataclasses with at least one forward reference with new-semantic-analyzer causes "unexpected keyword argument"

### ISSUE THREAD

**Issue by EXBreder** [python/mypy#7447]
Mypy version: 0.720
Python version: 3.7.2

Minimal example I could create:
```python
from dataclasses import dataclass
from typing import Optional


@dataclass
class Foo:
    x: int
    next: Optional["ForwardReference"] = None


@dataclass
class ForwardReference:
    pass


@dataclass
class Bar:
    y: int


@dataclass
class FooWithBar(Foo, Bar):
    pass


fails = FooWithBar(x=1, y=2)
# foo.py:26: error: Unexpected keyword argument "x" for "FooWithBar"
```

Running with the default new-semantic-analyzer, causes the above error. Turning it off with `--no-semantic-analyzer` results in no issues.

While there are some obvious workarounds in the example (moving the `ForwardReference` above the `Foo` class), from what I can tell, this should be valid code and should type check properly.

**Comment by ilevkivskyi** [comment]
Thanks for reporting! This is already fixed on master.
