### ISSUE TITLE
Error in type comment points to wrong line

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#7472]
This fragment generates an error on the line `@deco` which is confusing:

```py
def deco(x): return x

@deco   # Error: Name 'bad' is not defined
def f(y):
    # type: (bad) -> None
    pass
```

**Comment by ethanhs** [comment]
This is an instance of https://github.com/python/mypy/issues/3871. I tested on 3.8 and with the better source information, it was able to correctly report the error on the function declaration line.

Perhaps we should document this?

**Comment by ilevkivskyi** [comment]
> Perhaps we should document this?

It probably makes sense to add a short item in `Common issues` explaining that type errors may rarely appear in strange locations, and `# type: ignore` must be placed exactly there.

**Comment by JukkaL** [comment]
Even in 3.8 the error points to the line `def f(y):`, but it would be better if we can somehow make it point to the type comment line. This may require some hacks if the AST doesn't contain information about the line of the type comment, but it may be worth it.

**Comment by AlexWaygood** [comment]
Changing priority to "low", since type comments are rarely used in modern Python (parameter and variable annotations are generally preferred).

**Comment by JelleZijlstra** [comment]
Maybe we should just deprecate type comment support.

**Comment by ethanhs** [comment]
I believe type comments are part of PEP 484 so they would need to be deprecated and removed as part of the PEP, there is also the consideration of for/with statements, I've opened a new thread on typing-sig about this https://mail.python.org/archives/list/typing-sig@python.org/thread/66JDHQ2I3U3CPUIYA43W7SPEJLLPUETG/

**Comment by hauntsaninja** [comment]
This isn't worth fixing
