### ISSUE TITLE
Callable[TypeVar, TypeVar] as a stop gap

### ISSUE THREAD

**Issue by fried** [python/mypy#7480]
I've seen the various proposals for making Callable more complex, but sometimes you have a decorator that changes the return type in some way, but doesn't change the arguments.  

We already allow "..." for any set of arguments, why not a TypeVar for a particular set of arguments. 

So you could write decorators, that make changes to return values

```
A = TypeVar("A")
R = TypeVar("R")
def something(fn: Callable[A, R]) -> Callable[A, Awaitable[R]]: ...
```

And later we can figure out how to mutate `A` which is a very complex problem, left to some other proposal that may or may not ever get accepted.

Pyre has something like this in its extensions, and even ways to refer to the keyward arguments of A, and the positional arguments of A,  so you can type the wrapping function inside the decorator correctly.  https://github.com/facebook/pyre-check/blob/master/pyre_extensions/__init__.py .  Their Parameters "TypeVar" thing returns a empty list to make Callable happy :), but it seems we should just make Callable also able to accept TypeVar in the same context as `...` 

I concede my entire approach may just be extremely naive, but I just spent the last week trying to fix the types of various decorators. And it got me asking WHY can't we just pass a TypeVar to Callable in place of the list of arguments?

**Comment by ilevkivskyi** [comment]
It is likely that mypy will need to have something like this even after we introduce variadic generics. The key point is that arguments hold not only types, but also names and kinds (i.e. is it optional or not). I think it is important to have a separate name for this kind of concept, IIRC `ArgSpec` is what is proposed most often.

Just to clarify, whether it will have a same name (i.e. `TypeVar`), or a new one has almost zero effect on time needed to implement this.

**Comment by JukkaL** [comment]
There's a new PEP (https://www.python.org/dev/peps/pep-0612/) that proposes a solution to this issue, so this issue is no longer relevant.
