### ISSUE TITLE
mypy checks whole module when invoked on specific file if __init__.py is present

### ISSUE THREAD

**Issue by MaxG87** [python/mypy#7484]
This issue might seem harmless but it breaks compatibility with VIm+Syntastic. See the Syntastic issue here: https://github.com/vim-syntastic/syntastic/issues/2282.

I work on [TD-Watson](https://github.com/TailorDev/Watson). If I change to the project's root directory and run

    mypy --ignore-missing-imports watson/watson.py

I get the following output:

    watson/config.py:9: error: Name 'RawConfigParser' already defined (possibly by an import)
    watson/frames.py:10: error: List or tuple literal expected as the second argument to namedtuple()
    watson/utils.py:28: error: Name 'unicode' is not defined
    watson/utils.py:30: error: Incompatible types in assignment (expression has type "Type[str]", variable has type "Tuple[Type[str], Any]")
    watson/watson.py:13: error: Name 'configparser' already defined (by an import)

Note that the output contains error messages for other files too, albeit I specified *exactly one file* and not the module itself.

It exists a file `watson/__init__.py` with following content:

    from .watson import __version__  # noqa
    from .watson import Watson, WatsonError
    
    __all__ = ['Watson', 'WatsonError']

If I delete this file, and again run `mypy --ignore-missing-imports watson/watson.py` I get:

    watson/watson.py:13: error: Name 'configparser' already defined (by an import)

which is what I expect.

I was not able to reproduce this problem in a minimum working example. I am sorry for this.

I try to understand this behaviour. From the point of view of integrating it with Syntastic this is very undesireable, as it might block showing the output of further linters.

Imho, if a user specifies a concrete file, she expects to get the output only for that file.

Thank you in advance.

**Comment by ilevkivskyi** [comment]
It sounds like what you need is `--follow-imports=skip`, please read the [docs] (https://mypy.readthedocs.io/en/latest/running_mypy.html#following-imports).
