### ISSUE TITLE
Don't warn about non keyword-only attributes after keyword-only attributes in attrs

### ISSUE THREAD

**Issue by oakkitten** [python/mypy#7489]
This behavior was recently [changed](https://github.com/python-attrs/attrs/pull/559) in `attrs`. [Relevant code](https://github.com/python/mypy/blob/master/mypy/plugins/attrs.py#L320-L324) in mypy.

**Comment by ilevkivskyi** [comment]
We will not have time to update implementation soon, but PRs are welcome.

**Comment by markusschmaus** [comment]
Here is a PR: https://github.com/python/mypy/pull/8803
