### ISSUE TITLE
Feature request: Type synonyms

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [python/mypy#7498]
If I have a file that inputs, for instance, a list of filenames and returns a list of URLs, it will have the type `List[str] -> List[str]`. I would like to be able to write `List[Filename] -> List[Url]`, where `Filename` and `Url` are just synonyms I defined for `str`. It would make it clearer what's going on.

**Comment by JelleZijlstra** [comment]
You can do that already by using a type alias: `Filename = str`.

**Comment by JeffreyBenjaminBrown** [comment]
SWEET! Thank you!
