### ISSUE TITLE
Question: unable to import package

### ISSUE THREAD

**Issue by earonesty** [python/mypy#7502]
Please provide more information to help us understand the issue:

* Looks like a bug to me
* "Cannot find module named: XXX"

If I create a single file module and publish it, there seems to be no way, except `typeshed`, to annotate it and have mypy find the import.

Looking at PEP561, a type checker should look for type information in "user code".   If I have a external library consisting of a single file, say "hello.py", mypy doesnt' attempt to import it and get type information from the library.   

Instead it seems to report "module not found"... *regardless* of whether there is type information in the file or not.

Looking here, it seems there's simply no way for a single-file package to comply with mypy, except to add *another* package named "-stubs" ...:

https://mypy.readthedocs.io/en/latest/installed_packages.html#installed-packages

**Comment by earonesty** [comment]
mypy *could* simply import it and see if there are annotations... the way it does with every other module.   it seems like this is a trivial change, right?

**Comment by ethanhs** [comment]
@earonesty that is not what mypy does actually! Mypy is completely static and thus we can only read files off the file system statically, and we have no idea if the annotations are meant for static analysis.

**Comment by earonesty** [comment]
Is there an example of a standalone module that has annotations that *isn't* meant for static analysis?   Why not simply parse the module, and ... if it has annotations, use them?

**Comment by ethanhs** [comment]
> I certainly didn't mean to imply some sort of dynamic behavior.

Ah I must have misunderstood.

>Were there lots of modules and libraries that had type annotations that weren't meant for static analysis?

There were/are several, I collect a list of all static/dynamic type checkers I am aware of here https://github.com/ethanhs/python-typecheckers

Regardless, PEP 561 needed to keep backwards compatibility with existing code using PEP 3107 (function annotations), and 3107 does not specify how annotations should be used.

>I guess maybe someone out there may have used wacky annotations for things that aren't typing.

Its not just for things that aren't typing, it is any typing usage that isn't PEP 484 compliant, and if you look, there are plenty. To be clear, if there was an easier way to do things, I'd be glad to take the happy path, but there are considerations that a lot of people have thought about that made PEP 561 what it is today.

>which will be obsolete in a couple years anyway

I don't see this happening anytime soon, if ever.
