### ISSUE TITLE
re.match().group() fails despite if check

### ISSUE THREAD

**Issue by jamesmcm** [python/mypy#7503]
The following code fails the mypy check:
```python
   df.loc[:, "col"] = df.loc[:, "col"].apply(
          lambda x: r.match(x).group(1) if r.match(x) else "0"
      )
```

With error:
```
error: Item "None" of "Optional[Match[str]]" has no attribute "group"
```

Despite the explicit check for r.match(x) that means .group() will never be called for None.

How can I work around this?

**Comment by Bidek56** [comment]
mypy with Python 3.8 still has the same issue with the example code:


```
import re

advertisement = '10% discount'
discount = 0.0
if (mo := re.search(r'(\d+)% discount', advertisement)):
    discount = float(mo.group(1)) / 100.0

```

results in: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
Any ideas would be appreciated. Thanks

**Comment by JelleZijlstra** [comment]
This is #7316.

**Comment by zachliu** [comment]
well, too bad some ppl can't use a list comprehension :joy_cat:
