### ISSUE TITLE
[False positive] error: Missing return statement

### ISSUE THREAD

**Issue by L1ghtn1ng** [python/mypy#7516]
When running mypy it complains about the following code 
```python
    def do_search(self) -> Set:
        try:
            data = set()  # type: Set
            url = f'https://crt.sh/?q=%25.{self.word}&output=json'
            headers = {'User-Agent': Core.get_user_agent()}
            request = requests.get(url, headers=headers, timeout=15)
            if request.ok:
                content = request.json()
                data = set([dct['name_value'][2:] if '*.' == dct['name_value'][:2] else dct['name_value'] for dct in content])
            return data
        except Exception:
            pass
```
That it does not contain a return statement, when as you can see it does and that the code runs fine at runtime

mypy ```0.720```
Python: ```3.7.4```
mypy.ini: 
```
ignore_missing_imports = True
show_traceback = True
```

**Comment by ethanhs** [comment]
Hello, thank you for opening an issue. I think mypy is doing the correct thing. If your code raises an exception, the function will not return.

**Comment by L1ghtn1ng** [comment]
Which is fine as if it did that then there would be no data to return
________________________________

**Comment by ilevkivskyi** [comment]
> Which is fine as if it did that then there would be no data to return

In Python a function always returns something, like `None` in this case.
