### ISSUE TITLE
Support for inline annotations from PEP 561 with py.typed but without .pyi

### ISSUE THREAD

**Issue by kiwi0fruit** [python/mypy#7517]
From this issue https://github.com/python/mypy/issues/1190 it isn't clear if inline annotations from [PEP 561](https://www.python.org/dev/peps/pep-0561) with `py.typed` file but without `.pyi`are supported by mypy.

If they are supported then please provide instruction what is need to make mypy use them (as I wasn't able to get them working). PyCharm supports them by the way.

If they are not supported then this is the issue to finally support them.

**Comment by ilevkivskyi** [comment]
Inline annotations are already supported, but PEP 561 packages must be installed if you want mypy to use them, see [these docs](https://mypy.readthedocs.io/en/latest/running_mypy.html#how-imports-are-found) and [other docs](https://mypy.readthedocs.io/en/latest/installed_packages.html#installed-packages) for details.

**Comment by kiwi0fruit** [comment]
Thanks!
