### ISSUE TITLE
NamedTuple triggered mypy error inside a class

### ISSUE THREAD

**Issue by yihengli** [python/mypy#7531]
```python
from typing import NamedTuple


class A:
    def __init__(self) -> None:
        self.tuple2 = NamedTuple('x', [('y', str), ('z', bool)])

    def run2(self) -> NamedTuple:
        return self.tuple2(y='y', z=True)


print(A().run2())
```
The script will trigger `"NamedTuple" not callable  mypy(error)`, not sure if this is as expected

Reference:
https://mypy.readthedocs.io/en/latest/kinds_of_types.html#named-tuples

---

Tested with Python37 and mypy==0.701

**Comment by JelleZijlstra** [comment]
This is expected (although the error message could be better). The NamedTuple constructor isn't meant to be used at runtime in a class constructor; instead you should define your NamedTuple type in the module scope.

**Comment by JukkaL** [comment]
It would be better if mypy would at least tell that defining a NamedTuple type as an attribute is not supported.

**Comment by AFanaei** [comment]
@JukkaL 
I created a test to fix this issue but the test causes some exceptions:
```
[case testNamedTupleAtRunTime]
from typing import NamedTuple

class A:
    def __init__(self) -> None:
        self.b = NamedTuple('x', [('s', str), ('n', int)])  # E: NamedTuple type as an attribute is not supported

```
could you give some hint what is wrong?

**Comment by JukkaL** [comment]
@AFanaei Try adding `[builtins fixtures/list.pyi]` to the end of the test case.
