### ISSUE TITLE
No longer respects [mypy] section in tox.ini?

### ISSUE THREAD

**Issue by OJFord** [python/mypy#7532]
Support for finding and respecting options in tox.ini (if `--config`, `mypy.ini`, `setup.cfg` not found first) was added in #2761.

That seems no longer to work in `mypy 0.720` (at latest).

Of course, a quick workaround is to `ln -s tox.ini mypy.ini` since both ini files use a `[mypy]` section for mypy's config, but that's less than ideal.

**Comment by JukkaL** [comment]
I don't think that #2761 added support for tox.ini. There was some discussion about it, but it wasn't ultimately included, as far as I can see.

**Comment by ilevkivskyi** [comment]
I think the reasons for not including support for it initially are still valid, so I propose to close this for now (until more requests will appear).

**Comment by claudiofinizio** [comment]
I am using mypy in a Django project (thanks to django-stubs). Since I already have a tox.ini file that contains configuration for various utilities (such as flake8 and coverage), I would appreciate to include also mypy settings inside that same tox.ini file.

**Comment by OJFord** [comment]
@claudiofinizio We still have `mypy.ini` as a symlink to `tox.ini`, been working fine for over a year. I'd also prefer not to need it, but I find the illusion that it's all in the same place preferable to having it all except mypy in the same place (and no illusion).

**Comment by McSinyx** [comment]
I think at this moment, setuptools is no longer the only possible build backend, thus in case a project uses e.g. flit, `setup.cfg` is not present and IMHO `tox.ini` would be the preferred location for testing/linting tools config, if one does not want a `mypy.ini` in per project's root dir.  Another possibility is `pyproject.toml`, which is being gradually adopted, although it's not in INI format.
