### ISSUE TITLE
Overloads from PySide2 don't seem to work correctly

### ISSUE THREAD

**Issue by rggjan** [python/mypy#7536]
I have this code in **test.py**:

```
1 from PySide2.QtCore import QRect
2 from PySide2.QtGui import QPixmap
3 
4 a = QPixmap()
5 
6 reveal_type(a.depth())
7 reveal_type(a.copy(rect=QRect()))
8 reveal_type(a.copy(1, 2, 3, 4))
9 reveal_type(a.copy())

```

Running `mypy test.py` produces:
```
test.py:6: note: Revealed type is 'builtins.int'
test.py:7: note: Revealed type is 'Any'
test.py:8: note: Revealed type is 'Any'
test.py:9: note: Revealed type is 'Any'
```

So the stubs are found and the non overloaded function on line 6 is evaluated correctly to `int`.

However, from the overload signature in **PySide2/QtGui.pyi**:
```
6188 class QPixmap(PySide2.QtGui.QPaintDevice):
...
6210     @typing.overload
6211     def copy(self, rect:PySide2.QtCore.QRect=...) -> PySide2.QtGui.QPixmap: ...
6212     @typing.overload
6213     def copy(self, x:int, y:int, width:int, height:int) -> PySide2.QtGui.QPixmap: ...
...
6218     def depth(self) -> int: ...
```

 I would expect lines 7 to 9 to evaluate to `QPixmap` instead of `Any`...

**Comment by rggjan** [comment]
Actually, could this be a python3.6 issue?

I'm using
- mypy 0.720
- python 3.6.8
- PySide2 5.13.1

**Comment by JelleZijlstra** [comment]
Could you give a more self-contained example, or at least link to the full `.pyi` files you're using?

One possible reason is that mypy doesn't know what `PySide2.QtGui.QPixmap` is and therefore treats is as Any.

**Comment by rggjan** [comment]
I installed pyside via pip, so you can get the pyi files I used from here:
https://pypi.org/project/PySide2/#files

Is it possible that it doesn't work because QPixmap is not known inside the definition of QPixmap in python 3.6?

**Comment by JukkaL** [comment]
Can you try `reveal_type(a.copy)`? It might produce useful output.

**Comment by rggjan** [comment]
`reveal_type(a.copy)` produces:

```
note: Revealed type is 'Overload(def (*Any, **Any) -> Any)'
```

**Comment by ilevkivskyi** [comment]
I looked at the stubs, and here is what I see: these stubs are autogenerated and are seriously broken. In particular they use `typing.Optional`, `typing.overload` etc., but `typing` appears as:
```python
from PySide2.support.signature import typing
```
Looking at `PySide2/support` directory I see it is almost empty, this means that lots of types in stubs are just `Any`. I would recommend reporting this to PySide2 maintainers.

**Comment by ctismer** [comment]
@ilevkivskyi Yes, the above statement works perfectly with PySide2, but only if the import really happens. If the analysis of mypy does everything without an import, then it cannot see anything.

I can probably change this, because I mainly did that to support Python2 in the early days when to external typing module was available. Maybe we can do this?
```
try:
    import typing
except ImportError:
    from PySide2.support.signature import typing
```
