### ISSUE TITLE
ctypes POINTER(c_type) is not allowed as function arg type

### ISSUE THREAD

**Issue by MarSoft** [python/mypy#7540]
* Are you reporting a bug, or opening a feature request?

This looks like a bug in Mypy. Probably related to #5144.

Here is my usecase: I wrote a small wrapper to declare foreign function signature with `ctypes` in a `pyi`-like syntax:

```
def func(lib, errcheck=None):
    def decorator(fn):
        name = fn.__name__
        res = fn.__annotations__.pop('return', None)
        args = tuple(fn.__annotations__.values())

        f = getattr(lib, name)
        f.argtypes = args
        f.restype = res
        if errcheck:
            f.errcheck = errcheck
        return f
    return decorator


mylib = ctypes.windll.mylib


@func(mylib)
def MyFuncOne(id: ctypes.c_uint32, val: ctypes.POINTER(ctypes.c_uint32) -> ctypes.uint32: ...
```

This requires `python3.7` or newer and works fine but `mypy` does not like my `val` variable annotation.

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

I tried two approaches:
```
# Naive approach
@func(mylib)
def MyFuncOne(id: ctypes.c_uint32, val: ctypes.POINTER(ctypes.c_uint32) -> ctypes.uint32: ...

# Try to use variable, since POINTER is declared in typeshed as
# (type: Type[_CT]) -> Type[pointer[_CT]]`
PTR_UINT32 = ctypes.POINTER(ctypes.c_uint32)
@func(mylib)
def MyFuncTwo(id: ctypes.c_uint32, val: PTR_UINT32) -> ctypes.uint32: ...
```

* What is the actual behavior/output?

```
# for naive approach:
error: Invalid type comment or annotation
note: Suggestion: use POINTER[...] instead of POINTER(...)

# for variable:
error: Variable "mymodule.PTR_UINT32" is not valid as a type
```

* What is the behavior/output you expect?

I would expect `mypy` to recognize that `POINTER(ctype)` produces a type.
Not sure though if it is possible with type annotations the way I use them.

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

`python 3.7.4`
`mypy 0.720`
Also tested with latest development `mypy` (commit 855076b)

* What are the mypy flags you are using? (For example --strict-optional)

No flags used.

**Comment by JukkaL** [comment]
`POINTER(...)` is not a syntactically valid type according to PEP 484. Only very specific expressions are supported as types in annotation. Something like `POINTER[...]` might work though, if `POINTER` was defined as a generic class in typeshed, or through a mypy plugin perhaps. 

This use case doesn't look important enough for special mypy-only type syntax.

(And apologies for the slow response.)

**Comment by thijsmie** [comment]
For anyone coming here from google, typeshed now has a stub for pointers, so this works:
```python
def fn(pt: ctypes.pointer[ctypes.c_bool]) -> bool:
    pass
```
This will make mypy happy. If you need to resolve these types at runtime you can add:
```python
if not TYPE_CHECKING:
    # Monkeypatch typed pointer from typeshed into ctypes
    class pointer:
        @classmethod
        def __class_getitem__(cls, item):
            return ct.POINTER(item)
    ct.pointer = pointer
```
I am not sure this is the correct way to go about this but it works :innocent:.

**Comment by EmDash00** [comment]
> ```python
> if not TYPE_CHECKING:
>     # Monkeypatch typed pointer from typeshed into ctypes
>     class pointer:
>         @classmethod
>         def __class_getitem__(cls, item):
>             return ct.POINTER(item)
>     ct.pointer = pointer
> ```

I believe the current implementation as of writing this still maintain `ctypes.POINTER` and `ctypes.pointer` are functions. It is actually `ctypes._Pointer` which is a typeshed type; however, it is not available at runtime. You would still need to use the patch as far as I know.

**Comment by KubaO** [comment]
`ctypes.pointer[ctypes.c_bool]` is roughly nonsense, because `pointer` is really the `addressof` operator.

`ctypes.POINTER[ctypes.c_bool]` is what we'd want.

This can be monkey-patched:

```
import ctypes
import typing

class POINTER[T](ctypes._Pointer):
    class _GenericAlias(typing.GenericAlias):
        def __repr__(self):
            val = super().__repr__()
            ibra = val.find('[')
            idot = val.rfind('.', 0, ibra)
            return f"{val[:idot+1]}POINTER{val[ibra:]}"

    def __class_getitem__(cls, *args):
        ptrtype = ctypes.POINTER(*args)
        alias = POINTER._GenericAlias(ptrtype, *args)
        return alias
```

To the type-checker, `POINTER` is a generic class that derives from `_Pointer`. And that's indeed how the type you get from `POINTER(Foo)` behaves. `issubclass(POINTER(c_int), ctypes._Pointer)` is true, and so is `issubclass(POINTER[c_int], ctypes._Pointer)` :)
