### ISSUE TITLE
Constructor of derived dataclass with parent containing dataclass depends on declaration order 

### ISSUE THREAD

**Issue by Goobley** [python/mypy#7546]
I came across what seems to me like a weird bug. Here is a minimal repro:

```python
from dataclasses import dataclass, field

@dataclass
class A:
    x: int
    c: 'C' = field(init=False)

@dataclass
class B(A):
    y: float

@dataclass
class C:
    a: A

b = B(1, 1.0)
```

This gives the error message "Too many arguments for "B""

However if I change which class is using the forwards reference:

```python
@dataclass
class C:
    a: 'A'

@dataclass
class A:
    x: int
    c: C = field(init=False)

@dataclass
class B(A):
    y: float

b = B(1, 1.0)
```

Then this typechecks with no problem at all. This seems like a bug to me, as I would expect both to be equivalent. I tried `# type: ignore` on various fields, but to no avail. Both appear 100% equivalent in the interpreter.

**Comment by JukkaL** [comment]
This has been fixed on master.
