### ISSUE TITLE
Incorrect unreachable branch detection when using suppress contextmanager

### ISSUE THREAD

**Issue by pirate** [python/mypy#7554]
It appears `mypy` doesn't recognize `return` statements under a `suppress` contextmanager as being a branch, and assumes the `return` will always run, when in fact the `return` will never execute if an exception is thrown.

**`mypy.ini`:**
```ini
[mypy]
...
warn_unreachable = True
```

**`sync/models.py`:**
```python3
from contextlib import suppress

...

class Version(models.Model):
    ...

    @classmethod
    def from_fuzzy_id(cls, fuzzy_id: str) -> Optional['Version']:
        with suppress(cls.DoesNotExist):
            return cls.objects.get(id__startswith=fuzzy_id)

        ...
        return None
```

**`mypy` output:**
```python3
sync/models.py: note: In member "from_fuzzy_id" of class "Version":
sync/models.py:240:9: error: Statement is unreachable
```

The error is not django-specific, but I figured I'd show our real world use-case (although note this code is greatly simplified to show just the relevant logic needed to see the error).

I assume this is due to `mypy` not having logic around detecting exception handling branches.  If this is something the `mypy` team isn't willing to fix, I understand, you can close this issue and we'll just use `type: ignore` or set `warn_unreachable = False`.

**Comment by ilevkivskyi** [comment]
This is fixed on master.

**Comment by ilevkivskyi** [comment]
(btw the next release where this will be available will happen in next couple days, so you are lucky :-))

**Comment by pirate** [comment]
Very serendipitous, thanks for the super-fast response @ilevkivskyi!
