### ISSUE TITLE
Force type annotations for function parameters, let missing return type mean None

### ISSUE THREAD

**Issue by Hubro** [python/mypy#7555]
In my project, I want the lack of a return type annotation to mean that the function returns None. I also want to force type annotations for all function parameters.

If I use the options `disallow_untyped_defs` or `disallow_incomplete_defs`, they force me to specify a return type even when it's None.

Is there any combination of options that will let me:

- Force type annotations for all functions and methods in the project
- Consider a missing return type to mean `-> None`

**Comment by gvanrossum** [comment]
There is no such feature.

I recommend that you just accept this and add `-> None` to your functions!

**Comment by porglezomp** [comment]
Every time I come back to mypy from being away for a while I get bit by the fact that no annotation doesn't mean `-> None` like I expect it to :(

**Comment by refi64** [comment]
If it's a cause for concern check out mypy's strict mode and the options it
implies:
https://mypy.readthedocs.io/en/latest/command_line.html#cmdoption-mypy-strict

Also check out the mypy.ini file for saving these options.
