### ISSUE TITLE
dict from generator

### ISSUE THREAD

**Issue by mmoehring** [python/mypy#7558]
I wanted to read a simple property file into a dict. Each line contains "key=value"

```python
with open(properties) as file:
    dict(line.split("=") for line in file)
```

gives
> Argument 1 to "dict" has incompatible type "Generator[List[str], None, None]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"

Using Python 3.74 and mypy 0.720.

**Comment by refi64** [comment]
line.split returns a list of potentially more or less than two items,
whereas dict's constructor expects an iterable of *pairs*.

**Comment by mmoehring** [comment]
I aware about the constructor arguments. Nonetheless it seems to work for special cases like

```python
>>> s= "Name1=Value1;Name2=Value2;Name3=Value3"
>>> dict(item.split("=") for item in s.split(";"))
{'Name1': 'Value1', 'Name2': 'Value2', 'Name3': 'Value3'}
```
(which gives the same type error)

So what is the correct way of handling this? Disable typing for this code segment?

**Comment by gvanrossum** [comment]
A static type checker can't know that your input will always be valid. If you have some reason to believe it is, you have to add `# type: ignore` to the line where mypy complains.
