### ISSUE TITLE
Regression: Missing return statement in method that is NOT missing a return statement

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [python/mypy#7560]
* Are you reporting a bug, or opening a feature request?
  A regression bug, that did not exist in 0.720 but now appears in 0.730 and is forcing us to pin everything to 0.720 because it can't be ignored.
* Please insert below the code you are checking with mypy.
  Please see these three linked code items: https://github.com/eventbrite/pysoa/blob/bb51a6a9/pysoa/client/client.py#L166-L173
  https://github.com/eventbrite/pysoa/blob/bb51a6a9/pysoa/common/transport/redis_gateway/core.py#L236-L243
  https://github.com/eventbrite/pysoa/blob/bb51a6a9/pysoa/common/transport/redis_gateway/core.py#L245-L298
* What is the actual behavior/output?
  ```
  pysoa/common/transport/redis_gateway/core.py:236: error: Missing return statement
  pysoa/common/transport/redis_gateway/core.py:245: error: Missing return statement
  pysoa/client/client.py:166: error: Missing return statement
  ```
* What is the behavior/output you expect?
  No complaint, passes MyPy. On the first linked code, which corresponds to the last output message, we even tried changing this:
  ```
              if message is None:
                  return None, None
              else:
                  return request_id, JobResponse(**message)
  ```
  To this:
  ```
              if message is None:
                  return None, None
              return request_id, JobResponse(**message)
  ```
  But that did not get rid of the error. All three of these errors are within code using the `with` clause. Other methods that don't use the `with` clause are not having this issue.
* What are the versions of mypy and Python you are using?
  We were not having this issue when using 0.720. When 0.730 was released today, it broke this. `# type ignore` did not help. We have only been able to resolve this by pinning our MyPy to the older 0.720 (TODO will insert link here after committing that pin change).
* What are the mypy flags you are using? (For example --strict-optional)
  https://github.com/eventbrite/pysoa/blob/bb51a6a9/setup.cfg#L35-L75

**Comment by srittau** [comment]
This is most likely related to the change "[Reachability and Context Managers](http://mypy-lang.blogspot.com/2019/09/mypy-730-released.html)". The solution is to change the return type of the context manager in question.

**Comment by ilevkivskyi** [comment]
Yes, context managers can "swallow" exceptions, so that function will return `None`. You should annotate `Timer.__exit__()` as returning `Literal[False]` (as in relerse notes, link posted above).

Also FYI, this can be ignored if you put the ignore comment on line where mypy shows it.

**Comment by nickwilliams-eventbrite** [comment]
>Also FYI, this can be ignored if you put the ignore comment on line where mypy shows it.
The line where `mypy` shows it is the method definition line. The method definition line already has a `# type: ` comment for the method's arguments and return type. I tried adding `# type: ignore` to the end of that but it did not work.

But, indeed, using `Literal[False]` solved the problem. Not intuitive at all, but I suppose if I had read the release notes...

A bit disappointed that adding a dependency on `typing_extensions` is the only way to properly annotate context manager `__exit__` methods. Glad that will be in the standard library in Python 3.8, but as long as we have to maintain backward compatibility with Python 2.7 and 3.5, that won't much matter.

**Comment by gvanrossum** [comment]
@nickwilliams-eventbrite Maybe you could turn your attitude around a bit? We're happy that you're trying out mypy's new features so soon after the release and we're thankful for your feedback. We're even sorry that your CI broke. But mypy is open source and you're getting it for free. So instead of using whiny phrases  like "Not intuitive at all" and "A bit disappointed", maybe you could roll up your sleeves and try to contribute a fix for this issue (or for some other issue that's been bothering you)?
