### ISSUE TITLE
New version release v0.730 broke existing ci jobs

### ISSUE THREAD

**Issue by MahdiBaghbani** [python/mypy#7564]
I have been running about 5 ci jobs for some months and all them are now failing because of new version of mypy released 7 hours ago. I think it is connected with typshed.

```terminal 
$ pipenv run mypy --package mersad
/root/.local/share/virtualenvs/XXXXX-e0t6KaBg/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.730
/root/.local/share/virtualenvs/XXXXX-e0t6KaBg/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: : note: please use --show-traceback to print a traceback when reporting a bug
```

specifying v0.720 in pipenv dependency file fixes the problem, so something is really wrong with v0.730

**Comment by ilevkivskyi** [comment]
Can you post the full traceback? (Use `--show-traceback` as the error message says.) Without it there is nothing we can do.

**Comment by ra-kete** [comment]
Not sure if it's the same issue, but I'm getting the same error message with 0.730 and not with 0.720. Here is my traceback:

```
Traceback (most recent call last):
  File "<redacted>/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "mypy/build.py", line 1845, in wrap_context
  File "mypy/build.py", line 1966, in parse_file
  File "mypy/build.py", line 726, in parse_file
  File "mypy/parse.py", line 23, in parse
  File "mypy/fastparse.py", line 157, in parse
  File "mypy/fastparse.py", line 297, in visit
  File "mypy/fastparse.py", line 454, in visit_Module
AttributeError: 'TypeIgnore' object has no attribute 'tag'
```

**Comment by ilevkivskyi** [comment]
@ra-kete In your case it looks like a broken install, you have wrong `typed_ast` version (one of mypy dependencies).

**Comment by ra-kete** [comment]
Good catch! Turns out I ran into a compatibility issue with pylint (https://github.com/PyCQA/astroid/issues/696). Updating astroid fixed it. Sorry for the noise.
