### ISSUE TITLE
Inverse of 'Type'

### ISSUE THREAD

**Issue by ayroblu** [python/mypy#7566]
I was just wondering if there was an inverse to the `Type` typings type? Like `Instance` or similar?

**Comment by gvanrossum** [comment]
There's not. What's your use case? I've never heard this request before -- maybe there's some simpler way to do what you're looking for...

**Comment by ayroblu** [comment]
Okay that's good to know, I think it's just an ergonomics thing. I'll just make sure I'm always using the instance version wherever relevant, so that I can add the `Type[Model]` if needed. I was a bit unsure if these statements were equivalent:

```python
A = Union[Type[AModel], Type[BModel]]
B = Type[Union[AModel, BModel]]
```

But it looks like they are unless I'm missing something

My actual issue I have, which I'm not sure is really solvable is that I wanted to do a generic (`TypeVar`) with this, so that if I pass in `Type[AModel]`, then I know the response will always be `AModel`. However I couldn't do it and ended up doing it with overloading, which is a little more verbose but works

**Comment by ethanhs** [comment]
@ayroblu if I understand correctly, you want something like this, which is supported by mypy:
```
def make_instance(typ: Type[T]) -> T:
     ...
```

**Comment by ilevkivskyi** [comment]
Yes, I think what @ethanhs mentioned should be the one way to do it.
