### ISSUE TITLE
Add complete tarballs to releases on GitHub or extend MANIFEST.in to include mypyc/lib-rt

### ISSUE THREAD

**Issue by mr-c** [python/mypy#7570]
Hello,

I'm updating the Debian Package for mypy and very happy to have mypyc included.

When using the sdist from PyPI we are unable to build with `MYPY_USE_MYPYC=1` as the `mypyc/lib-rt` directory is not present.

Switching to the autogenerated source code tarballs from the GitHub releases doesn't work because they lack the Git submodules, specifically `mypy/typeshed`

https://github.com/python/mypy/releases/tag/v0.730

We'd love to include the much faster and compiled version of mypy in Debian. 

Options:
1. Tarballs that contain `mypy/typeshed` are added to the GitHub releases (manually at first, and then automatically)
2. `MANIFEST.in` is augmented to include the missing paths, such at `mypyc/lib-rt` and `misc/proper_plugin.py` (referenced from `mypy_self_check.ini` which we run)

`mypyc/lib-rt/` is about 29K gzip'd, so I don't think that is too much to add to the sdist.

I'm happy to send a PR for option 2, just let me know.

Thanks, as always, for a fantastic project!

**Comment by ilevkivskyi** [comment]
Good idea, I personally would prefer the option 2. Let's see what other people say.

**Comment by joostvanzwieten** [comment]
I've tried to use `mypyc.build.mypycify` from the mypy wheel on PyPI, but it fails because the `mypyc/lib-rt` directory is not included. Option 2 fixes this problem as well. I've tested it with the following addition to `MANIFEST.in`:

```
recursive-include mypyc/lib-rt *.c *.h
```
