### ISSUE TITLE
Bug: stub for time.gmtime() is not working correctly

### ISSUE THREAD

**Issue by jolaf** [python/mypy#7588]
The following code:
```python3
from time import gmtime
(a, b, c, d, e, f, g, h, i) = gmtime()
print(a, b, c, d, e, f, g, h, i)
```
produces the following output:
```python3
$ python3 Test.py 
2019 9 30 16 29 49 0 273 0
$ mypy Test.py
Test.py:3: error: Too many values to unpack (9 expected, 11 provided)

$ mypy --version
mypy 0.730
$ python3 --version
Python 3.6.8
```
`reveal_type(gmtime)` produces the following output:
`Revealed type is 'def (secs: Union[builtins.float, None] =) -> Tuple[builtins.int, builtins.int, builtins.int, builtins.int, builtins.int, builtins.int, builtins.int, builtins.int, builtins.int, builtins.str, builtins.int, fallback=time.struct_time]`

**Comment by msullivan** [comment]
This seems to be a real issue that stems from all of the fields being listed as part of a namedtuple in the typeshed stub, when only 9 of them are part of the tuple and the rest are just attributes.

The bug should be filed against typeshed, though.
Thanks!

**Comment by jolaf** [comment]
Re-filed as https://github.com/python/typeshed/issues/3286
