### ISSUE TITLE
Property name overrides the module name with the types

### ISSUE THREAD

**Issue by nolar** [python/mypy#7589]
* Are you reporting a bug, or opening a feature request?

A bug.

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
import collections

class K:

    def f(self) -> collections.Container[int]:  # Works.
        return []

    @property
    def collections(self) -> collections.Container[int]:  # Fails.
        return []

    def g(self) -> collections.Container[int]:  # Fails.
        return []
```

_(In my actual case both the module name and the property are "resources" (app-specific), and the module is imported Google-style (`from app.pkg import resources`), but I've simplified here for one of the built-in modules.)_

* What is the actual behavior/output?

```
_mypy_property_and_module.py:10: error: Name 'collections.Container' is not defined
        def collections(self) -> collections.Container[int]:  # Fails.
        ^
_mypy_property_and_module.py:13: error: Name 'collections.Container' is not defined
        def g(self) -> collections.Container[int]:  # Fails.
        ^
Found 2 errors in 1 file (checked 1 source file)
```

* What is the behavior/output you expect?

Properly understanding the scopes of `collections`, and not mixing the class's property name with the module name.

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

```
$ pip freeze | grep mypy
mypy==0.730
mypy-extensions==0.4.1

$ python --version
Python 3.7.3
```

* What are the mypy flags you are using? (For example --strict-optional)

```
mypy _mypy_property_and_module.py --strict --pretty --ignore-missing-imports 
```

**Comment by nolar** [comment]
And only after few more hours I have found this paragraph giving a suggestion officially: https://mypy.readthedocs.io/en/latest/common_issues.html#dealing-with-conflicting-names

So, I consider this is not actually an issue, but is an expected behaviour with an existing work-around.

**Comment by gvanrossum** [comment]
(FWIW, excellent use of the new `--pretty` flag!)
