### ISSUE TITLE
[question] how to return a "subclass" of a generic?

### ISSUE THREAD

**Issue by ZeeD** [python/mypy#7592]
I'm trying to "stub" [mockito](https://github.com/kaste/mockito-python), that I use in my project.

I'm having difficulties trying to define the return type of the "mock", "when", and "captor" function.

Basically, in the most simplest way, I want do define a generic function that returns a "subclass" of the generic itself, with the same methods, but also some additional methods.

Take, for example, ["mockito.captor"](https://mockito-python.readthedocs.io/en/latest/the-matchers.html#mockito.matchers.captor):
it's a function that takes a type T and return an instance that you can put "as if" it was an instance of T in other function calls.
But also have a ".value" attribute, that contains the "captured" value (of type T)

now, how do I define the return type of this function?

```python
T = TypeVar('T')
def capture(cls: Type[T]) -> T: ... # no, because T doesn't have .name attribute
class Capture(Generic[T]):
  name: T = ...
def capture(cls: Type[T]) -> Capture[T]: ... # no, because functions expect T, not Capture[T]
```

**Comment by gvanrossum** [comment]
Maybe use a Protocol?
-- 
--Guido (mobile)

**Comment by msullivan** [comment]
Somewhat to my surprise, it actually kind of works if you make a generic class that subtypes its generic parameter. It reports an error, but if you ignore the error everything seems to work just fine!

Here is what I tried:
```
from typing import TypeVar, Type, Generic, TYPE_CHECKING
T = TypeVar('T')

if TYPE_CHECKING:
    # Don't make it a subclass of T at runtime since typing will choke
    # on that.
    class Selfify(Generic[T], T):  # type: ignore  # mypy doesn't believe that T is allowed here... but it still works?
        pass
else:
    class Selfify(Generic[T]):
        pass

class Capture(Selfify[T]):
    name: T

def capture(cls: Type[T]) -> Capture[T]: ... # no, because functions expect T, not Capture[T]


# Some testing
def foo(x: int) -> None:
    pass
def bar(x: str) -> None:
    pass

x = capture(int)
x.name
reveal_type(x)
foo(x)
x + 10
```

Let me know if this works for you

**Comment by ZeeD** [comment]
Umm, I'm not sure it's working: it seems that even if you write `x.not_name` instead of `x.name` mypy doesn't show warnings...
Maybe I'll try to use protocols

**Comment by JukkaL** [comment]
Closing as the discussion seems to have ended.
