### ISSUE TITLE
error: "HTTPBasicAuthHandler" has no attribute "add_password"

### ISSUE THREAD

**Issue by walles** [python/mypy#7598]
* Are you reporting a bug, or opening a feature request?

This is a bug report. Or at least I think it is :)

* Please insert below the code you are checking with mypy, or a mock-up repro if the source is private. We would appreciate if you try to simplify your case to a minimal repro.

```python
#!/usr/bin/env python3

import six

auth_handler = six.moves.urllib.request.HTTPBasicAuthHandler()
auth_handler.add_password(user='a', passwd='b', realm='c', uri='d')
```

* What is the actual behavior/output?

```bash
/t/hej $ mypy --version
mypy 0.720
/t/hej $ mypy six-http.py
six-http.py:6: error: "HTTPBasicAuthHandler" has no attribute "add_password"
```

* What is the behavior/output you expect?

No errors, the program runs fine:
```
/t/hej $ ./six-http.py
/t/hej $
```

* What are the versions of mypy and Python you are using?
```bash
/t/hej $ mypy --version
mypy 0.720
/t/hej $ python3 --version
Python 3.6.5
```

  Do you see the same issue after installing mypy from Git master?

Yes:
```bash
(env) ~/s/mypy (master|✔) $ mypy --version
mypy 0.740+dev.583b99e5096c979043a63dcf92bf3f0d5993d03a
(env) ~/s/mypy (master|✔) $ mypy /tmp/hej/six-http.py
/tmp/hej/six-http.py:6: error: "HTTPBasicAuthHandler" has no attribute "add_password"
Found 1 error in 1 file (checked 1 source file)
(env) ~/s/mypy (master|✔) [1] $
```

* What are the mypy flags you are using? (For example --strict-optional)

None.

**Comment by ethanhs** [comment]
This looks to be an issue with the typeshed stubs for six: https://github.com/python/typeshed, and should be reported there.

**Comment by walles** [comment]
This could be https://github.com/python/typeshed/issues/22.
