### ISSUE TITLE
a question in document about Class variables

### ISSUE THREAD

**Issue by Chise1** [python/mypy#7601]
In document,the classes :
`class MyClass:
    # You can optionally declare instance variables in the class body
    attr: int
    # This is an instance variable with a default value
    charge_percent: int = 100
`
how to use in class variables.
Or here is a problem or mistaken??

**Comment by JelleZijlstra** [comment]
I'm not sure I understand your question, but you can use `typing.ClassVar` to specify a class variable.

**Comment by Chise1** [comment]
In Cpython,
`class A:
&nbsp; &nbsp; &nbsp;ver_a:str="a veriables"
`
In code,ver_a is a class veriables.But why it say(in document):
`class MyClass:
    # You can optionally declare instance variables in the class body     attr: int     # This is an instance variable with a default value     charge_percent: int = 100`Why attr is  instance veriables?

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jelle Zijlstra"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月2日(星期三) 晚上7:45
收件人:&nbsp;"python/mypy"<mypy@noreply.github.com&gt;;
抄送:&nbsp;"Chise1"<chise123@live.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [python/mypy] a question in document about Class variables (#7601)




I'm not sure I understand your question, but you can use typing.ClassVar to specify a class variable.

**Comment by Chise1** [comment]
https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html
Itips:Classes


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jelle Zijlstra"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月2日(星期三) 晚上7:45
收件人:&nbsp;"python/mypy"<mypy@noreply.github.com&gt;;
抄送:&nbsp;"Chise1"<chise123@live.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [python/mypy] a question in document about Class variables (#7601)




I'm not sure I understand your question, but you can use typing.ClassVar to specify a class variable.

**Comment by earonesty** [comment]
i've found that class level typing solves some bugs in mypy (or more likely the typed ast) when it thinks it cannot dervice a type.   i have a class with a statement self.state = f"{var1}.{var2}" ... and mypy complained it couldn't devine the type.   assing state: str at the class level fixed this (for no discernible reason)

**Comment by JukkaL** [comment]
@earonesty Can you give a concrete example where mypy has trouble with an f-string? It seems to work when I tried it in a simple example.
