### ISSUE TITLE
How to use mypyc ?

### ISSUE THREAD

**Issue by Chise1** [python/mypy#7613]
I write a file :
#filename:chise_test_fbnq.py
```
import time
from typing import Tuple

#cpython:14.236642122268677
def fb(x:int,y:int)->Tuple[int,int]:
    return y,x+y

def test()->float:
    x:int=0
    y:int=1
    t:float=time.time()
    for i in range(1000000):
        x,y=fb(x,y)
    return time.time()-t
# print(test())
```
And I use command ‘mypyc chise_test_fbnq.py'
get a  file named 'chise_test_fbnq.cpython-36m-x86_64-linux-gnu.so'.
but when I use it:
```
fbnq_test=ctypes.CDLL("chise_test_fbnq.cpython-36m-x86_64-linux-gnu.so")
fbnq_test.test()
```
,here is a mistake:
AttributeError: undefined symbol: test
How I can use it?....
Thank you...

**Comment by msullivan** [comment]
Just import the module with `import chise_test_fbnq`. Good luck!

**Comment by msullivan** [comment]
(And we need to document this all better! https://github.com/mypyc/mypyc/issues/584)

**Comment by msullivan** [comment]
I was curious so I went and tested this myself, and the speedup is only marginal because the numbers get very big and so all of the time is spent doing big integer arithmetic, which mypyc won't speed up.

A similar microbenchmark without bigints gave a 5x speedup:
```
import time
from typing import Tuple

#cpython:14.236642122268677
def fb(x:int,y:int)->Tuple[int,int]:
    return y,x+y

def test()->float:
    x:int=0
    y:int=1
    t:float=time.time()
    for i in range(1000000):
        x = 0
        y = 1
        for j in range(100):
            x,y=fb(x,y)
    return time.time()-t
```

**Comment by Chise1** [comment]
That's more than I expected.
Maybe I need another way to test speed.
#cpython:13-13.5s
#mypyc:10.5s
#pypy:7.8s
Can you give me some advice to test this?

**Comment by msullivan** [comment]
That was the time on your original test?

The real question here is: what are you interested in learning here. What do you want to get a speedup on.

Tight microbenchmarks are often not very meaningful. (pypy will usually beat us on them, too, since pypy shines best with tight inner loops).

Building a test that looks similar to the code you actually care about speeding up might provide the most meaningful results.

https://github.com/python/mypy/blob/master/mypyc/test-data/run-bench.test are some tests I wrote that mimiced some of the things mypy does a lot. (But also it turns out that mypy does them a lot less than the test does!)

**Comment by Chise1** [comment]
Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Michael J. Sullivan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月4日(星期五) 上午8:59
收件人:&nbsp;"python/mypy"<mypy@noreply.github.com&gt;;
抄送:&nbsp;"Chise1"<chise123@live.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [python/mypy] How to use mypyc ? (#7613)




That was the time on your original test?
 
The real question here is: what are you interested in learning here. What do you want to get a speedup on.
 
Tight microbenchmarks are often not very meaningful. (pypy will usually beat us on them, too, since pypy shines best with tight inner loops).
 
Building a test that looks similar to the code you actually care about speeding up might provide the most meaningful results.
 
https://github.com/python/mypy/blob/master/mypyc/test-data/run-bench.test are some tests I wrote that mimiced some of the things mypy does a lot. (But also it turns out that mypy does them a lot less than the test does!)
