### ISSUE TITLE
attrs plugin doesn't support new `eq` and `order` arguments

### ISSUE THREAD

**Issue by jml** [python/mypy#7615]
attrs 19.2.0 has added `eq` and `order` arguments to `attr.ib`, and deprecated `cmp`. I think mypy needs to be updated to take this into account.

```python
@attr.s(auto_attribs=True, frozen=True)
class Context:
    _original: Dict[str, Any] = attr.ib(order=False)
```

```
_context.py:37: error: No overload variant matches argument type "bool"
_context.py:37: note: Possible overload variants:
_context.py:37: note:     def (default: None = ..., validator: None = ..., repr: bool = ..., cmp: bool = ..., hash: Optional[bool] = ..., init: bool = ..., convert: None = ..., metadata: Optional[Mapping[Any, Any]] = ..., type: None = ..., converter: None = ..., factory: None = ..., kw_only: bool = ...) -> Any
_context.py:37: note:     def [_T] (default: None = ..., validator: Union[Callable[[Any, Attribute[_T], _T], Any], Sequence[Callable[[Any, Attribute[_T], _T], Any]], None] = ..., repr: bool = ..., cmp: bool = ..., hash: Optional[bool] = ..., init: bool = ..., convert: Optional[Callable[[Any], _T]] = ..., metadata: Optional[Mapping[Any, Any]] = ..., type: Optional[Type[_T]] = ..., converter: Optional[Callable[[Any], _T]] = ..., factory: Optional[Callable[[], _T]] = ..., kw_only: bool = ...) -> _T
_context.py:37: note:     <2 more similar overloads not shown, out of 4 total overloads>
```

mypy 0.711 and 0.730

I expect this to pass type checking, as attrs 19.2.0 adds `eq` and `order` parameters to attr.ib: http://www.attrs.org/en/19.2.0/changelog.html#deprecations

Without this, using `cmp=` generates a DeprecationWarning. 

I haven't tried installing mypy from Git master.

```
[mypy]
python_version = 3.7
strict_optional = true
warn_redundant_casts = true
namespace_packages = true
```

**Comment by euresti** [comment]
Oh looks like attrs finally shipped.  I can work on fixing this in my spare time.

**Comment by ilevkivskyi** [comment]
@euresti Great, thanks!

**Comment by euresti** [comment]
@jml I'm seeing that your error is a stubs error.  In the venv in which you're running mypy is the latest `attrs` module installed?  The reason I ask is because `attrs` ships its own stubs.

**Comment by jml** [comment]
I don't know.

If I run `mypy` directly on the file (e.g. `mypy path/to/file`), then it checks just fine, even with a release of mypy without #7619. 

I think the problem is that whatever venv [pre-commit](https://pre-commit.com) is using has the wrong version. Since I had obliterated all its cached venvs and explicitly pinned attrs to 19.2 everywhere, I assumed that couldn't be the problem. 

Oh well.

**Comment by chris-cummings-eb** [comment]
I was running into this issue running mypy with pre-commit as well.
It took me a bit to figure out how to work around this. So just in case anyone else is still running into this @jml was right in that the venv pre-commit was using had an out-of-date attrs version installed.

To fix it you can add:
```
      hooks:
          - id: mypy
            additional_dependencies: [attrs~=19.3]
```
