### ISSUE TITLE
mypyc lib-rt file not found error

### ISSUE THREAD

**Issue by odra** [python/mypy#7625]
Note: if you are reporting a wrong signature of a function or a class in
the standard library, then the typeshed tracker is better suited
for this report: https://github.com/python/typeshed/issues

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
Bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

I am trying to run mypyc in python package of mine.

* What is the actual behavior/output?

```
Traceback (most recent call last):
  File "build/setup.py", line 5, in <module>
    ext_modules=mypycify([], ['bin/sumatra'], ),
  File "mypyc/build.py", line 368, in mypycify
FileNotFoundError: [Errno 2] No such file or directory: 'venv/lib/python3.7/site-packages/mypyc/lib-rt/CPy.c'
```

* What is the behavior/output you expect?

Dunno, not an error, it is the first time I am trying to use mypyc :)

* What are the versions of mypy and Python you are using?

```
mypy 0.730
Python 3.7.2
```

  Do you see the same issue after installing mypy from Git master?

Yes.

* What are the mypy flags you are using? (For example --strict-optional)

No flags, just `mypyc $package_folder`

* If mypy crashed with a traceback, please paste
  the full traceback below.

```
Traceback (most recent call last):
  File "build/setup.py", line 5, in <module>
    ext_modules=mypycify([], ['bin/sumatra'], ),
  File "mypyc/build.py", line 368, in mypycify
FileNotFoundError: [Errno 2] No such file or directory: 'venv/lib/python3.7/site-packages/mypyc/lib-rt/CPy.c'
```

**Comment by msullivan** [comment]
I was about to say that this was already fixed and would be in the next release, but I think we only fixed it for source packages? Thanks for the report.

**Comment by msullivan** [comment]
OK, confirmed that it *is* fixed for all dists on master but  that we have some unnecessary duplication between `MANIFEST` and `package_data` (which I think we can just eliminate??)
