### ISSUE TITLE
Lots of tests that are unnecessarily cmdline

### ISSUE THREAD

**Issue by msullivan** [python/mypy#7633]
There are a lot of tests (basically every one containing `disallowAny` in their name, probably more) that are cmdline tests but could easily be `check` tests. I think they were probably implemented before `testcheck` could specify flags easily.

**Comment by victorteodoro** [comment]
Is there anyone already working on it?

**Comment by msullivan** [comment]
Don't think so!

**Comment by tapish2000** [comment]
Why is this issue open, is there anything else to be done in this?

**Comment by JukkaL** [comment]
Looks like there is not much left to do and this issue can be closed.
