### ISSUE TITLE
Make all names and fullnames in mypy properties

### ISSUE THREAD

**Issue by msullivan** [python/mypy#7640]
^

**Comment by msullivan** [comment]
Oh ugh this would be a big plugin compatability break wouldn't it

**Comment by JukkaL** [comment]
Yeah, but on the other hand it would be good to do this before 1.0 release since the current situation is bad. I'd rather not be stuck with the current state forever.

**Comment by ilevkivskyi** [comment]
I agree with Jukka here.

**Comment by ethanhs** [comment]
I think this is probably a good idea. If we choose to move ahead with this, we should probably announce our intentions here ASAP https://github.com/python/mypy/issues/6617

**Comment by msullivan** [comment]
OK I'll do it after 0.740
