### ISSUE TITLE
type: ignore[arg] does not silence notes

### ISSUE THREAD

**Issue by jolaf** [python/mypy#7653]
The following code:
```python3
from typing import Union

x: Union[int, bytes] = b''

x += 5 # type: ignore[operator]
```
produces the following output:
```python3
$ mypy Test.py
Test.py:5:6: note: Left operand is of type "Union[int, bytes]"
$ echo $?
1
```
While it's expected that the `note` would also be silenced together with the warning it accompanies.

**NOTE that besides extra printout, this problem causes a non-zero exit code**, which makes the situation look like a typing error, which `type: ignore` explicitly should prevent.

If `[]` brackets are removed from `type: ignore`, the problem disappears.

If `type: ignore` is removed altogether, the following output is produced:
```python3
$ mypy Test.py
Test.py:5:6: error: Unsupported operand types for + ("bytes" and "int")  [operator]
    x += 5
         ^
Test.py:5:6: note: Left operand is of type "Union[int, bytes]"
Found 1 error in 1 file (checked 1 source file)
$ echo $?
1
```
exactly as expected.

```
$ mypy --version
mypy 0.730
$ python3 --version
Python 3.6.8
```

**Comment by JukkaL** [comment]
This is fixed on master. We are planning a new release for the next week where this will be fixed.

**Comment by jolaf** [comment]
Wow, great to hear! Thank you!
