### ISSUE TITLE
Type deduction of [None] or [42] leads to false return value incompatibility for List[Optional[int]]

### ISSUE THREAD

**Issue by ConradBailey** [python/mypy#7673]
This produces no errors
```python
from typing import *
def foo() -> List[Optional[int]]:
    return [None]
```

However adding a variable with type inference, like this
```python
from typing import *
def foo() -> List[Optional[int]]:
    x = [None]
    return x
```
Produces something like this
```
scratch.py:4: error: Incompatible return value type (got "List[None]", expected "List[Optional[int]]")
scratch.py:4: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
scratch.py:4: note: Consider using "Sequence" instead, which is covariant
scratch.py:4: note: Perhaps you need a type annotation for "x"? Suggestion: "List[Optional[int]]"
Found 1 error in 1 file (checked 1 source file)
```
Changing `List` to `Sequence` or `x = [None]` to `x: List[Optional[int]] = [None]` eliminates the error.

My thinking is that mypy should infer from `x = [None]` that `x` is of type `List[None]` and that `return x` should satisfy `-> List[None]` which should further satisfy `-> List[Optional[int]]`.

This is not specific to `int`; Many other classes will result in similar behavior.

Also of note, swapping `None` for an instance of `int`, like this
```python
from typing import *
def foo() -> List[Optional[int]]:
    x = [42]
    return x
```
Yields a similar, symmetric error
```
scratch.py:4: error: Incompatible return value type (got "List[int]", expected "List[Optional[int]]")
scratch.py:4: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
scratch.py:4: note: Consider using "Sequence" instead, which is covariant
scratch.py:4: note: Perhaps you need a type annotation for "x"? Suggestion: "List[Optional[int]]"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by JelleZijlstra** [comment]
This is known and relatively deep, so it's unlikely to get addressed soon. Note though that `List[None]` is *not* compatible with `List[Optional[int]]`, because `List` is an invariant type. That's (part of) why you get that error.

**Comment by gvanrossum** [comment]
The other part of the explanation is that mypy uses the initializing expression to infer the type of a variable that's not otherwise given a type -- there's no working backwards from the return statement.

The customary workaround is to write
```
x: List[Optional[int]] = [None]
```
