### ISSUE TITLE
Mypy can't decide on types

### ISSUE THREAD

**Issue by joelberkeley-pio** [python/mypy#7701]
This is a bug report. Python 3.7.3, mypy 0.670(?), flags: `--ignore_missing_imports``

For
```
U = TypeVar('U')


class Into(Protocol[U]):
    @abstractmethod
    def into(self, t: Type[U]) -> U:
        pass
```
and
```
class X: pass
class Y: pass
```
I'm getting a bug in this class
```
XY = TypeVar('XY', X, Y)


class B:
    def into(self, t: Type[XY]) -> XY:
        if t == X:
            return X()  # line 61
        
        if t = Y:
            return Y()  # line 64

        raise Exception
```
I get

> 61: error: Incompatible return value type (got "X", expected "Y")  
> 64: error: Incompatible return value type (got "Y", expected "X")

and if I switch the return values as suggested, I get the errors the other way round.

**Comment by joelberkeley-pio** [comment]
curiously I don't get problems with this version
```
class A:
    @overload
    def into(self, t: Type[X]) -> X:
        ...

    @overload
    def into(self, t: Type[Y]) -> Y:
        ...

    def into(self, t):
        if t == X:
            return X()

        if t == Y:
            return Y()

        raise Exception
```

**Comment by JelleZijlstra** [comment]
This is because methods with a typevar with value restriction get type checked multiple times, one each for each possible value of the typevar. Thus, you get one error when XY is instantiated as `X`, and another when it is `Y`.

The overload solution doesn't get errors because the body of the overload has no annotations, so mypy doesn't typecheck the body.

**Comment by joelberkeley-pio** [comment]
Does that mean it's a mypy limitation and I should # type: ignore it?

**Comment by JelleZijlstra** [comment]
It depends on exactly what your real-world code looks like (what's in your comments is obviously a simplification). Perhaps `if issubclass(t, X)` would work, but I haven't tried it.

**Comment by joelberkeley-pio** [comment]
hmmm ... it seems to depend on which solution I choose.

In the first it's safe cos I'm only ever claiming to return an `X` or `Y`, but in the second, I think it would have to be the other way round: `issubclass(X, t)`, otherwise someone might ask for a `class XX(X): pass`, expecting an `XX` and get an `X`, which would be most surprising

**Comment by joelberkeley-pio** [comment]
hmmm ... it seems to depend on which solution I choose.

In the first it's safe cos I'm only ever claiming to return an `X` or `Y`, but in the second, I think it would have to be the other way round: `issubclass(X, t)`, otherwise someone might ask for a `class XX(X): pass`, expecting an `XX` and get an `X`, which would be most surprising
