### ISSUE TITLE
Mypy does not appropriately typecheck dictionary union types when accessed through a variable

### ISSUE THREAD

**Issue by maltzj** [python/mypy#7705]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request? *bug report*
* Please insert below the code you are checking with mypy,
```
from typing import Dict, Union

sample_data = {"foo": "foo"}


def dummy_func(some_data: Dict[Union[str, float], str],):
    print(some_data)

print(dummy_func(sample_data))
```

* What is the actual behavior/output?
Mypy returns a type error 
```
app/api/scratch.py:10: error: Argument 1 to "dummy_func" has incompatible type
"Dict[str, str]"; expected "Dict[Union[str, float], str]"
    print(dummy_func(sample_data))
```

* What is the behavior/output you expect?
This type checks successfully.

* What are the versions of mypy and Python you are using?
Mypy 0.730 from https://github.com/pre-commit/mirrors-mypy/
Python 3.6 (happens on 3.7 as well)
  Do you see the same issue after installing mypy from Git master?
Yes.
* What are the mypy flags you are using? (For example --strict-optional):
`--ignore-missing-inputs`

Interestingly, the below code type checks successfully:

```
from typing import Dict, Union

sample_data = {"foo": "foo"}

def dummy_func(some_data: Dict[Union[str, float], str],):
    print(some_data)

print(dummy_func({"foo": "foo"}))
```

This suggests that for some reason mypy is not appropriately following the types of variables.

**Comment by refi64** [comment]
The reason for this is that dicts are mutable, so if this type checked, you
would be able to do `some_data[0.0] = 's'` and it would work, but the
caller would be stuck with an str-to-str dict that also has a float key
inside.
