### ISSUE TITLE
Name 'abc.ABC' is not defined

### ISSUE THREAD

**Issue by mortoray** [python/mypy#7710]
I'm getting an error using the `abc` module. Given this source file:

```py
import abc

class Node(abc.ABC):
	def __init__(self):
		super().__init__()
		
	@abc.abstractmethod
	def visit( self ):
		pass
```

I get the mypy errors:

```
abc.py:3: error: Name 'abc.ABC' is not defined
abc.py:7: error: Module has no attribute "abstractmethod"
```

I've tried mypy v 0.701 and 0.730, inside and outside of a python virtual environment.

I use mypy on all my projects; this was a simple test file I was writing to localize an error. I assume some kind of setup error, or something other simple failure, but I can't determine what the problem is.

**Comment by ilevkivskyi** [comment]
One possible explanation is a broken install with missing `typeshed`. Are you trying to install from git? If yes, did you follow [the docs](https://mypy.readthedocs.io/en/latest/common_issues.html#using-a-development-mypy-build)?

Another possible explanation is that you have a file named `abc.py` somewhere in the code that shadows the builtin one. Are you using namespace packages? If yes, you should use `--namespace-packages` flag. If no, then maybe you are missing an `__init__.py` somewhere?

**Comment by mortoray** [comment]
I do indeed have a file named `abc.py`, so this would be a duplicate of issue https://github.com/python/mypy/issues/7711  (we can decide there whether it's valid or not).
