### ISSUE TITLE
Mypy not treating bytes as typing.ByteString

### ISSUE THREAD

**Issue by willmcgugan** [python/mypy#7714]
According to the [docs](https://docs.python.org/3/library/typing.html#typing.ByteString), an argument typed as `bytes` should also accept `bytearray` and `memoryview`, but this doesn't seem to be the case.

The following example demonstrates this:

```python
def process(b: bytes) -> None:
    pass

process(memoryview(b"foo"))
```

Mypy produces the following error:

```
error: Argument 1 to "process" has incompatible type "memoryview"; expected "bytes"
```

I found https://github.com/python/mypy/issues/4871 which is essentially the same issue. If there hasn't been any relevant changes since April 2008, perhaps its a docs issue only?

**Comment by srittau** [comment]
In typeshed I have directed people to just use `bytes` instead of a union with `memoryview`, because of the documentation. In case we just change the documentation, we'd need to change the stubs as well.

**Comment by ilevkivskyi** [comment]
I think this should be just fixed in mypy. It should be not hard, one just needs to update `TYPE_PROMOTIONS_PYTHON2` and `TYPE_PROMOTIONS_PYTHON3` in `mypy/semanal_classprop.py` and add a test for this. Anyone wants to make a PR?
