### ISSUE TITLE
Specified version of Set does not qualifie as more generalized one

### ISSUE THREAD

**Issue by Eugene-1984** [python/mypy#7716]
The following MWE:
```
from typing import Union, Set

def foo(x: Set[Union[int, float]]):
    ...

def bar() -> Set[int]:
    ...

foo(bar())
```
fails with:
> Argument 1 to "foo" has incompatible type "Set[int]"; expected "Set[Union[int, float]]"

And yet the code:
```
def bazz() -> Set[Union[int, float]]:
    return {1}
```
considered to be correct. Is that a bug that a specified version of `Set[int]` does not qualify as `Set[Union[int, float]]` in the first case only?

Again, the following fails:
```
def foobar() -> Set[Union[int, float]]:
    return bar()
```
> Incompatible return value type (got "Set[int]", expected "Set[Union[int, float]]")

**Comment by ilevkivskyi** [comment]
This is because `set` is mutable and therefore invariant, see https://mypy.readthedocs.io/en/latest/common_issues.html#invariance-vs-covariance
