### ISSUE TITLE
Erroneous "missing return statement" using ExitStack

### ISSUE THREAD

**Issue by wadetregaskis-linkedin** [python/mypy#7726]
test.py:
```
from contextlib import ExitStack

def context_manager_with_return_bug() -> int:
    with ExitStack() as stack:
        return 5
```

mypy complains:  test.py:3: error: Missing return statement

Oddly this only seems to happen when using ExitStack specifically - no other context manager, based on other functions / classes / etc, in my codebase triggers this bug.

**Comment by ilevkivskyi** [comment]
The `ExitStack()` is annotated in `typeshed` as something that can swallow exceptions. This kind of matches the docs (if any of the context managers in the stack swallows exceptions).

Of course in this simplified case there is nothing that can raise an exception in the first place. But I assume your code is more complex. I think the best way forward is to just silence it by adding:
```python
assert False, "unreachable"
```
after the context manager.

In principle we can add some special-casing for `ExitStack()` and/or add a concept of non-raising statements. This may be tricky to add, so I think this is low priority.

**Comment by wadetregaskis-linkedin** [comment]
Ah, that makes sense, I hadn't considered that behaviour of ExitStack… seems this is working as intended - though maybe the error message from mypy could be improved to explain this better, e.g. "Missing return - the managed context using ExitStack can turn exceptions thrown inside the context into silently jumping to & falling off the end of the context.".

**Comment by ilevkivskyi** [comment]
> maybe the error message from mypy could be improved to explain this better

Yes, this is one of the potential ways to improve this, see also https://github.com/python/mypy/issues/7666

**Comment by hauntsaninja** [comment]
The actionable thing here is #7666
