### ISSUE TITLE
mypy fails on use of deprecated attrs API

### ISSUE THREAD

**Issue by belm0** [python/mypy#7737]
Unfortunately mypy 0.740 contained a half-baked implementation of attrs eq and order support, and fails on use of deprecated attrs API (which of course is not in the scope of mypy).

Namely, 0.740 has #7619, but not #7675.

```
@attrs(cmp=False)
class Foo:
    ...
```

```
foo.py:23: error: cmp is deprecated, use eq and order
```

**Comment by ilevkivskyi** [comment]
There is no point in opening an issue that is already fixed on master. Either use master or wait for the next release.

**Comment by belm0** [comment]
It's a regression, so you might consider it for a 0.741 release.
