### ISSUE TITLE
Mypy crashes with pytest

### ISSUE THREAD

**Issue by stan-sz** [python/mypy#7746]
Mypy 0.730 and 0.740 errors out when invoked from code as below:

```
> type .\mp.py
import unittest

class TestLint(unittest.TestCase):
    def test_mypy(self):
        import mypy.main
        import sys
        mypy_args = [__file__]
        mypy.main.main(None, args=mypy_args, stdout=sys.stdout, stderr=sys.stderr)
> python -m pytest .\mp.py
================================================= test session starts =================================================
platform win32 -- Python 3.6.8, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: c:\src
collected 1 item

mp.py F
====================================================== FAILURES =======================================================
_________________________________________________ TestLint.test_mypy __________________________________________________

self = <mp.TestLint testMethod=test_mypy>

    def test_mypy(self):
        import mypy.main
        import sys
        mypy_args = [__file__]
>       mypy.main.main(None, args=mypy_args, stdout=sys.stdout, stderr=sys.stderr)

mp.py:8:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: int object expected; got None

mypy\main.py:120: TypeError
```

In the prior versions this invocation was not throwing the `TypeError`.

**Comment by ilevkivskyi** [comment]
It is hard to tell what is wrong. The error points to the line that does `stdout.write()`, in your case this would be `sys.stdout.write()`. I just tried in Python 3.7 it actually returns an `int`. Did you override it to a buffer that returns `None` instead? Or maybe `pytest` does this?

You can re-install mypy with `--no-binary` flag, this will likely solve this issue, but will make mypy slower.

@msullivan

**Comment by ethanhs** [comment]
In addition, is there a reason `mypy.api` is not preferable?

**Comment by stan-sz** [comment]
Thanks @ethanhs. I've rewritten our test to use the `mypy.api` and let `pytest` handle the logging when return code is not `0`. Indeed, the problem here is between `pytest` and the way we invoked `mypy`.
