### ISSUE TITLE
Child of abstract class with Literal field doesn't support Final as field

### ISSUE THREAD

**Issue by b0g3r** [python/mypy#7751]
Possibly bug. Child of abstract class with Literal field doesn't support Final as field type.Reproducible example:
```python3
import abc

from typing_extensions import Literal, Final

PossibleKeysType = Literal['KEY1', 'KEY2']


class AbstractParent(abc.ABC):
    @property
    @abc.abstractmethod
    def key(self) -> PossibleKeysType:
        pass


class LiteralChild(AbstractParent):
    key: Literal['KEY1'] = 'KEY1'


class FinalChild(AbstractParent):
    key: Final = 'KEY1'  #  error: Incompatible types in assignment (expression has type "str", base class "AbstractParent" defined the type as "Union[Literal['KEY1'], Literal['KEY2']]")
```

I expect that FinalChild type checking should work similarly to LiteralChild and `something: Final = 'str'` is equal to `something: Literal['str'] = 'str'` like in TypedDict key checking.

I use mypy 0.740, python 3.6

**Comment by ilevkivskyi** [comment]
Yes, this is a bug, it looks like the Liskov check happens before we finalize the type. Essentially this is just another one in the https://github.com/python/mypy/issues/7724 bucket.

**Comment by b0g3r** [comment]
@ilevkivskyi Thank you for the fast response, It sounds like good news!

**Comment by 97littleleaf11** [comment]
Had been fixed in latest master branch!
