### ISSUE TITLE
Consulting the parameter of a Literal at runtime

### ISSUE THREAD

**Issue by calimeroteknik** [python/mypy#7755]
My objective today was to have a type for integers above a certain value.

I can already do positive integers:
```python
class PositiveInt(int):
    def __init__(self, candidate: int):
        if candidate < 0:
            raise ValueError(f"{candidate} isn't positive")
```
The objective is specifically that PositiveInt "converts" a runtime assertion to a type.
If I do have something of that type, I'm sure that its value is positive, because if it wasn't, a meaningful exception is raised before the object can be constructed.

But when I want to avoid copypasting this when I want numbers above 1, 10 or 42 I hit a wall:

```python
from typing import Generic, TypeVar  
from typing_extensions import Literal
T = TypeVar('T')

class IntAbove(int, Generic[T]):
    def __init__(self, candidate: int):
        if candidate < T.__args__[0]:
            raise ValueError(f"{candidate} is too small")
```

mypy doesn't like `T.__args__[0]`:
`error: 'T' is a type variable and only valid in type context`

I'm not sure if this feature request is reasonable at all, and maybe I could do it another way which I haven't found, if so I'd be glad to hear about it.

This of course takes us out of the realm where type annotations do not interfere with the runtime.

Theory wise, this would take python one step closer to a Pure Type System.

**Comment by ilevkivskyi** [comment]
This is not a question about mypy, which is a purely static tool. Anyway, you can get the information you want at runtime using some runtime inspection libraries, for example with https://github.com/ilevkivskyi/typing_inspect you can try something like:
```python
        if candidate < get_args(get_generic_type(self))[0]
```
This should generally work assuming instances are created with something like `x = IntAbove[Literal[5]](y)`.

**Comment by calimeroteknik** [comment]
Thanks! Indeed I realize I was confused, the module "typing" in Python isn't from mypy.

By the way, unfortunately it seems that the type parameter is accessible only after constructing the object, but not inside the constructor: self.__orig_class__ is not present in the constructor; it is present after construction however.

**Comment by pingyeh** [comment]
Is there a reason why `self.__orig_class__` is not present in `__init__()`? Can it be made present so we can check against args in it?

**Comment by AlexWaygood** [comment]
@pingyeho it's better to ask that kind of question [here](https://github.com/python/typing/discussions), rather than leaving a comment on an issue that's been closed for over two years.
