### ISSUE TITLE
New output "Success: no issues found" needs supression option

### ISSUE THREAD

**Issue by JohnCGriffin** [python/mypy#7759]
The recent change to output "Success: no issues found" affected a process by surprise.   Prior to 0.740, having no problems created no output.  I now must redirect mypy output, but mypy sends error output to standard out as well.  Fortunately, exit codes appear consistent with expectations.  Basically my code ran like this:

mypy somecode.py && python3 somecode.py

As the default appears to be for users liking the output, I would be delighted to have a quiet flag.

* Are you reporting a bug, or opening a feature request?
Feature request / Style Issue

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
---
print("hello")
-----

* What is the actual behavior/output?
-----
Success: no issues found in 1 source file
hello
------

* What is the behavior/output you expect?
-----
hello
-----
(Neither standard output nor standard error, as was the case prior to upgrade from 0.720 to 0.740.)

* What are the versions of mypy and Python you are using?
Python 3.7.4 and mypy-0.740

  Do you see the same issue after installing mypy from Git master?
I have not tried master branch

* What are the mypy flags you are using? (For example --strict-optional)
None

**Comment by ilevkivskyi** [comment]
`--no-error-summary`

**Comment by JohnCGriffin** [comment]
The --no-error-summary accomplishes exactly what I want of supressing the "Success" message and yet displaying errors.  Maybe a better name is --no-summary, because it supresses both errors and successes.

Thanks for the quick accurate response.
