### ISSUE TITLE
Type ignore not working with Black

### ISSUE THREAD

**Issue by IIBenII** [python/mypy#7762]
I have a this code: 
```python
while self.get_task_status(session, task_id)["progress"] < 1:  # type: ignore
   time.sleep(60)
```
when I launch black this code become:
```python
while (
    self.get_task_status(session, task_id)["progress"] < 1
):  # type: ignore
   time.sleep(60)
```
When `# type: ignore` is on multiple line mypy ignore it and raise an error `Unsupported operand types for < (\"str\" and \"int\")`

I'm using mypy 0.74 on python 3.7.4
Mypy is launch with `--ignore-missing-imports --follow-imports=silent --show-column-numbers`

Thanks for your help :)

**Comment by ethanhs** [comment]
This is an error in Black. In general, type ignores are per-line, and Black should not move them. In this case, the type ignore is on a different line after formatting, so the error is no longer ignored.
