### ISSUE TITLE
Feature Request: Specify which packages to ignore with `--no-site-packages`

### ISSUE THREAD

**Issue by alanhdu** [python/mypy#7769]
With `mypy 0.730`, I can currently run `--no-site-packages` to disable searching for any PEP 561 compliant packages which come with their own type hints. Unfortunately, this is a little coarse-grained: in our current codebase, there are some packages with PEP 561 typehints that we want to use, while others have typehints that are incomplete enough that we'd prefer to ignore them. Would it be possible to configure *which* packages to ignore instead of having to accept all of them or ignore all of them?

**Comment by JelleZijlstra** [comment]
I get that this may not be under your control, but incomplete PEP 561 packages should use the `def __getattr__() -> Any` trick to declare their incompleteness. Maybe you can get the relevant packages to add a `def __getattr__`?

**Comment by msullivan** [comment]
You can set `follow_imports = skip` for a particular package in your `mypy.ini`. Like:
```
[mypy-something.*]
follow_imports = skip
follow_imports_for_stubs = True
```

**Comment by msullivan** [comment]
Let me know if this doesn't work for you
