### ISSUE TITLE
Command line options for suppressing errors are not available

### ISSUE THREAD

**Issue by jolaf** [python/mypy#7774]
`mypy v0.740`

`show_none_errors` and `ignore_errors`, `follow_imports_for_stubs` config file options are not available as command line options, while it seems to be no reason for that.

`show_none_errors` WONT_FIX
`ignore_errors` WONT_FIX
`follow_imports_for_stubs` PR NEEDED

See https://mypy.readthedocs.io/en/latest/config_file.html#suppressing-errors

**Comment by ilevkivskyi** [comment]
I think first one is kind of legacy, second one is intended for per-file use, but the last one definitelly can be a CL flag.

**Comment by jolaf** [comment]
Is it the final decision? Should I provide a PR?

**Comment by ilevkivskyi** [comment]
> Is it the final decision? Should I provide a PR?

I can't speak for everyone, but I think go ahead, we can tweak the details if someone disagrees.
