### ISSUE TITLE
Error when assigning a ternary with an empty collection to a union type variable

### ISSUE THREAD

**Issue by raphj** [python/mypy#7780]
Hello,

the following code:
```python
from typing import List, Union
import sys
p : Union[int, List[int]] = 1 if len(sys.argv) else []
```

incorrectly generates the following error:

    t.py:3: error: Incompatible types in assignment (expression has type "Union[int, List[<nothing>]]", variable has type "Union[int, List[int]]")

Adding an integer in the list makes the error disappear. I first observed this issue with a dictionary:
```python
from typing import Dict, Union
import sys
p : Union[int, Dict[int, int]] = 1 if len(sys.argv) else {}
```
Error:

    t.py:3: error: Incompatible types in assignment (expression has type "Union[int, Dict[<nothing>, <nothing>]]", variable has type "Union[int, Dict[int, int]]")

It seems `<nothing>` should be matched with any type in type parameters in unions.

**Comment by nautics889** [comment]
Please, take a look at [this](https://github.com/python/typing/issues/157) topic. Perhaps mypy should consider an empty list like an object that fits `List[int]`, but unfortunately it doesn't. 
I think the best solution for you would be use `Any` type: 

`p : Union[int, List[Any]] = 1 if len(sys.argv) else []`

**Comment by raphj** [comment]
I worked around this issue by getting rid of the ternary condition and using a regular if statement instead.

**Comment by ilevkivskyi** [comment]
Another possible workaround could be using a covariant collection like `Sequence`. I however think mypy can do better here. We can probably pass through the type context in case of the ternary expressions.

**Comment by ilevkivskyi** [comment]
This actually may be not hard to fix, one just needs to update the logic in `mypy/checkexpr.py` in `visit_conditional_expr()` to try the original context `ctx` for the else expression.
