### ISSUE TITLE
Module in the virtualenv site-packages directory are not found by mypy

### ISSUE THREAD

**Issue by nicoe** [python/mypy#7788]
Hello,

With every mypy release I give it a try, this release is no different and the fact that environment variables are now taken into account in the config file will be very nice to find the python from the virtual environment.

So this is my config file:

```
nicoe@mirabelle:~% cat ~/.config/mypy/config
[mypy]
python_executable = $VIRTUAL_ENV/bin/python
```

When I execute this command:

```
mypy trytond/trytond/model/modelsql.py
```
(the complete file is available there: https://github.com/tryton/trytond/blob/develop/trytond/model/modelsql.py)

It won't find the `sql` package:

```
trytond/trytond/ir/lang.py:11: error: Cannot find module named 'sql'
```

Although the module is available through a simple import:

```
(tryton-trunk) nicoe@mirabelle:projets/tryton/tryton-env/tryton-env% python -c 'import sql; print(sql.__file__)'
/home/nicoe/.local/share/virtualenvs/tryton-trunk/lib/python3.7/site-packages/sql/__init__.py
```

And if I try to add this path to MYPYPATH it won't work either:

```
(tryton-trunk) nicoe@mirabelle:projets/tryton/tryton-env/tryton-env% MYPYPATH=/home/nicoe/.local/share/virtualenvs/tryton-trunk/lib/python3.7/site-packages/sql mypy trytond/trytond/model/modelsql.py
/home/nicoe/.local/share/virtualenvs/tryton-trunk/lib/python3.7/site-packages is in the MYPYPATH. Please remove it.
See https://mypy.readthedocs.io/en/latest/running_mypy.html#how-mypy-handles-imports for more info
```

Am I missing anything?

**Comment by ethanhs** [comment]
Have you tried manually passing `--python-executable=` via command line? Also please pass `-vv`, which should give more info.

**Comment by ethanhs** [comment]
Oh, if you are using python-sql, the package doesn't have a py.typed, nor does it have type annotations.

**Comment by nicoe** [comment]
OK thanks.

Since I saw some "No library stub file for module 'lxml'", I though mypy was not able to find the python-sql library while it was able to find the lxml one.

**Comment by JukkaL** [comment]
This seems like the same issue as #4542, which is already high priority.
