### ISSUE TITLE
Entry in mypy.ini for mypy_path not working

### ISSUE THREAD

**Issue by AmitGrowingData** [python/mypy#7793]
I have python 3.7.3 installed. I installed the latest version of mypy. I am getting the error of `test1.py:2: error: Cannot find module named 'f1.test2'` 

I have my mypy.ini in the base folder which has the entry
`[mypy]`
`python_version = 3.7`
`mypy_path = /temp/testmypypath`

the file structure is like 

- /temp/testmypypath/test1.py
- /temp/testmypypath/f1/test2.py
- /temp/testmypypath/f1/f2/test3.py

In test1.py I use 
`from f1.test2 import some_func_from_test2`

When I run `mypy test1.py` it does not identify the import despite the `mypi.ini`. The `mypi.ini` is definitely called because when I make a mistake in `mypy.ini`, an appropriate error is thrown.

If someone needs the file have loaded it on github

https://github.com/AmitGrowingData/IssueMyPy

Additional Info

- I am running windows 10
- The verbos trail of my error is 
LOG:  Mypy Version:           0.750+dev.09c1fc7a4c19fe76c2ca9f0c58eaeccfe1ef9ed5
LOG:  Config File:            mypy.ini
LOG:  Configured Executable:  c:\programdata\anaconda3\python.exe
LOG:  Current Executable:     c:\programdata\anaconda3\python.exe
LOG:  Cache Dir:              .mypy_cache
LOG:  Compiled:               False
LOG:  Could not load cache for test1: test1.meta.json
LOG:  Metadata not found for test1
LOG:  Parsing .\test1.py (test1)
LOG:  Metadata fresh for builtins: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\2and3\builtins.pyi
LOG:  Metadata fresh for typing: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\typing.pyi
LOG:  Metadata fresh for abc: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\abc.pyi
LOG:  Metadata fresh for ast: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\ast.pyi
LOG:  Metadata fresh for types: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\types.pyi
LOG:  Metadata fresh for sys: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\sys.pyi
LOG:  Metadata fresh for typing_extensions: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\third_party\2and3\typing_extensions.pyi
LOG:  Metadata fresh for collections: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\collections\__init__.pyi
LOG:  Metadata fresh for _ast: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\_ast.pyi
LOG:  Metadata fresh for _importlib_modulespec: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\_importlib_modulespec.pyi
LOG:  Metadata fresh for importlib.abc: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\importlib\abc.pyi
LOG:  Metadata fresh for collections.abc: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\collections\abc.pyi
LOG:  Metadata fresh for importlib: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\importlib\__init__.pyi
LOG:  Metadata fresh for os: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\os\__init__.pyi
LOG:  Metadata fresh for io: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\io.pyi
LOG:  Metadata fresh for posix: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\posix.pyi
LOG:  Metadata fresh for os.path: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\3\os\path.pyi
LOG:  Metadata fresh for codecs: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\2and3\codecs.pyi
LOG:  Metadata fresh for mmap: file c:\programdata\anaconda3\lib\site-packages\mypy\typeshed\stdlib\2and3\mmap.pyi
LOG:  Loaded graph with 20 nodes (0.051 sec)
LOG:  Found 2 SCCs; largest has 19 nodes
LOG:  Processing 1 queued fresh SCCs
LOG:  Processing SCC singleton (test1) as inherently stale
test1.py:2: error: Cannot find module named 'f1.test2'
test1.py:2: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
LOG:  Deleting test1 .\test1.py test1.meta.json test1.data.json
LOG:  No fresh SCCs left in queue
LOG:  Build finished in 0.215 seconds with 20 modules, and 2 errors
LOG:  Stats:
LOG:  cache_commit_time:      0.0
LOG:  data_json_load_time:    0.020951032638549805
LOG:  data_read_time:         0.012965202331542969
LOG:  deserialize_time:       0.06596708297729492
LOG:  files_parsed:           1
LOG:  find_module_calls:      22
LOG:  find_module_time:       0.0168302059173584
LOG:  fm_cache_size:          22
LOG:  fresh_metas:            19
LOG:  fresh_trees:            19
LOG:  graph_load_time:        0.05134129524230957
LOG:  graph_size:             20
LOG:  load_meta_from_dict_time:0.0
LOG:  load_meta_load_time:    0.004111766815185547
LOG:  load_meta_time:         0.004111766815185547
LOG:  load_tree_time:         0.10087871551513672
LOG:  metastore_read_time:    0.0030858516693115234
LOG:  modules_parsed:         1
LOG:  nodes_left:             0
LOG:  parse_time:             0.0
LOG:  process_fresh_time:     0.13578486442565918
LOG:  sccs_left:              0
LOG:  stubs_found:            19
LOG:  stubs_parsed:           0
LOG:  validate_meta_time:     0.015279293060302734
LOG:  validate_stat_time:     0.0020525455474853516
Found 1 error in 1 file (checked 1 source file)

**Comment by msullivan** [comment]
Your directories are missing `__init__.py` files.

By default mypy requires these to be present, even when in Python 3 they might not actually be necessary due to namespaces. You could try enabling the `namespace` option.

**Comment by emarbo** [comment]
Hi there. Just in case it could help somebody else. I had to enable both `namespace_packages` and `explicit_package_bases` to make it work. In fact, the second option requires the first one (mypy command line complains about it). 

Here is my `mypy.ini`:

```
[mypy]
allow_untyped_globals = True
warn_no_return = False

# Both options required to work with Python3 implicit namespace packages (no __init__.py)
namespace_packages = True
explicit_package_bases = True
```
