### ISSUE TITLE
Colon character ':' in Windows path is a separator for mypy_path

### ISSUE THREAD

**Issue by Djedouas** [python/mypy#7805]
How can I avoid the colon in my mypy_path to be considered as a separator ?
Thanks

**Comment by JukkaL** [comment]
I'm not sure if there's a way to do it. We could add support for an escape mechanism -- but backspace is a poor escape character, as it's already in use as a directory separator. Currently, using an UNC path of form `\\127.0.0.1\X$\MyDir` (where `X` is the drive letter) might work, though I don't have much experience with them.

**Comment by Djedouas** [comment]
This workaround works great, thanks ! 
Considering this, I think a note in the doc would be welcome.

**Comment by JukkaL** [comment]
> Considering this, I think a note in the doc would be welcome.

A good idea! Would you like to create a PR?

**Comment by Djedouas** [comment]
Yes, I'm on it :)
