### ISSUE TITLE
Update the website with the latest release?

### ISSUE THREAD

**Issue by utkarsh2102** [python/mypy#7833]
Hi,   
http://mypy-lang.org/ still mentions the new features in 0.730 while the next release is already done.  
Maybe it's a good time to update the website, too?

**Comment by ethanhs** [comment]
The PR was merged, it just needs to be deployed. https://github.com/JukkaL/mypy-website/pull/17

**Comment by utkarsh2102** [comment]
Hurray, thank you @JukkaL, @ethanhs.
