### ISSUE TITLE
Qustion: Why mypy required type annotation for var?

### ISSUE THREAD

**Issue by heckad** [python/mypy#7837]
```
from typing import Type
from typing import TypeVar

T = TypeVar('T')


class ObjectBuilder:
    def __init__(self, clazz: Type[T]):
        self.clazz = clazz

    def build(self) -> T:
        return self.clazz()


obj = ObjectBuilder(dict).build()
```

Expect: obj type is dict

Got: `test.py:15: error: Need type annotation for 'obj'`

Why mypy can't calculate the type of obj?

**Comment by brandtbucher** [comment]
I believe this error goes away if you have `ObjectBuilder` inherit from `typing.Generic[T]`. This is what allows the `T` to be "shared" across methods of an instance.

**Comment by heckad** [comment]
Yes, it's helped. Thanks!
