### ISSUE TITLE
documentation for module-level `# type: ignore` is unclear

### ISSUE THREAD

**Issue by bwo** [python/mypy#7839]
My expectation of a module-level `# type: ignore` comment is that it will skip *typechecking* of everything in the module; i.e., everything would be given the type `Any`.

The description in the documentation such a comment "has the effect of ignoring the *entire* module.", is, I think, consistent with that impression, since what "ignoring" means earlier in the documentation has been basically skipping typechecking.

What it *actually* does, though, seems to be to cause mypy to quite literally ignore the module: it is just skipped entirely, with the result that you *can't import names defined in that module in another one*:

```
(.venv3) BenW ~ 02:10:35 $ cat foo/a.py
# type: ignore

class A(object):
    pass
cat(.venv3) BenW ~ 02:10:45 $ cat foo/b.py
from foo.a import A

def b(a):
    # type: (A) -> int
    return len(str(type(a)))

print(b(A()))
(.venv3) BenW ~ 02:10:47 $ mypy foo
foo/b.py:1: error: Module 'foo.a' has no attribute 'A'
Found 1 error in 1 file (checked 3 source files)
```

This makes the feature somewhat less useful IMO, but also, I think it could be clearer in the docs that that's what it does.

**Comment by brandtbucher** [comment]
The actual implementation is that mypy marks the entire module as *unreachable*... as if the whole thing were indented inside of an `if False:` block. This is a side-effect of that change that I hadn't considered, though.

Perhaps modules should grow something like an `is_ignored` flag, which is checked when errors are reported, similar to how the module's ignored lines are checked. That could also mean that we report these if `--warn-unused-ignores` is enabled and there are no errors in the file. We can then also handle the various cases arising where there are other ignored lines in the file as well.

If we agree that this is the correct path forward, I can work on this.

**Comment by JukkaL** [comment]
Mypy has the `ignore_errors` option. Maybe a top-level `# type: ignore` should turn it on for the module being type checked? This already works and allows names to be imported:

```py
# mypy: ignore-errors
x = 1 + ''  # No error reported
```

**Comment by brandtbucher** [comment]
Agreed, they're functionally identical. I can take this.

**Comment by fluggo** [comment]
I am also suffering from this bug; a file marked `# type: ignore[no-redef]` is being treated as if nothing is defined in it.
