### ISSUE TITLE
optional subclass arguments typing is misread

### ISSUE THREAD

**Issue by JBKahn** [python/mypy#7843]
Assuming this is not the intended behavior, when running mypy on:

```python
from typing import Optional


class Base(object):
    thing: Optional[int]

    def __init_subclass__(cls, thing: Optional[int]):
        cls.thing = thing

class Child(Base, thing=0):
    def get_thing(self) -> int:
        return self.thing
```

I got this on `0.740` of mypy:
```
file.py:12: error: Incompatible return value type (got "Optional[int]", expected "int")
Found 1 error in 1 file (checked 1 source file)
```

I'm assuming since I've given it a value, it should be inferring this is an `int`. I have to add `thing: int` to `Child` right now to get rid of the error.

**Comment by JelleZijlstra** [comment]
This is intended behavior; mypy just looks at the type annotation. For example, you could have set `self.thing = None` elsewhere before calling `self.get_thing()`.
