### ISSUE TITLE
Cannot pass kwargs through for functions with default argument

### ISSUE THREAD

**Issue by pedroceles** [python/mypy#7850]
First, thanks a lot for this library!

This **bug** is probably related to https://github.com/python/mypy/issues/1969

```python
def test1(**kwargs: int) -> None:
    test2(**kwargs)

def test2(a: bool=True, **kwargs: int) -> None:
    print(a, kwargs)
```

results in this error:
```
test_mypy.py:2: error: Argument 1 to "test2" has incompatible type "**Dict[str, int]"; expected "bool"
```

The inconvenient fix would be:
```python
from typing import Mapping

def test1(**kwargs: int) -> None:
    temp = kwargs  # type: Mapping[str, int]
    test2(**temp)

def test2(a: bool=True, **kwargs: int) -> None:
    print(a, kwargs)
```

Python version: 3.5.3
Mypy version: 0.740

`mypy.ini`
```
[mypy]
python_version = 3.5
warn_return_any = True
warn_unused_configs = True
disallow_incomplete_defs = True
disallow_untyped_defs = True
```

**Comment by JelleZijlstra** [comment]
I think mypy is right here: the code is unsafe. If you call `test1(a=1)`, test2 would receive an `int` instead of a `bool` for its `a` parameter.

**Comment by ilevkivskyi** [comment]
> I think mypy is right here: the code is unsafe.

Yes, this code is technically unsafe, the error message is cryptic however, but we already have an issue to make it better, see https://github.com/python/mypy/issues/5382

**Comment by pedroceles** [comment]
If that is the case there should be an error raised in the second example as well, shouldn't it?

**Comment by ilevkivskyi** [comment]
> If that is the case there should be an error raised in the second example as well, shouldn't it?

Yes, I am however not super worried about the inconsistency. You may open an issue about this however if you want to prohibit this (or retitle this one).
