### ISSUE TITLE
abstractmethod + generic method seems to disturb inference results

### ISSUE THREAD

**Issue by beezee** [python/mypy#7863]
I believe this would qualify as a bug.

When a method takes generic input types that are also present in the return type, and that method is defined as abstract, the revealed type of the method appears correct, but the inferred type of the returned value is not consistent with the inferred method type. This is resolved when the method is not declared abstract.

I have a very broad use case for this code, but I've minimized for the example here. I hope this is clear and please let me know if there's anything else I can add or help with.

```python
from abc import ABC, abstractmethod
from typing import Generic, TypeVar

A = TypeVar('A')
B = TypeVar('B')

class TwoTypes(Generic[A, B]): pass

class MakeTwoSurprise(ABC, Generic[A]):

  @abstractmethod
  def __call__(self, a: B) -> TwoTypes[A, B]: pass

class MakeTwoExpected(Generic[A]):

  def __call__(self, a: B) -> TwoTypes[A, B]: pass


class Test():
  
  def make_two(self, 
                mts: MakeTwoSurprise[A], 
                mte: MakeTwoExpected[A]) -> None:
    reveal_type(mts.__call__) # Revealed type is 'def [B] (a: B`-1) -> repro.TwoTypes[A`-1, B`-1]'
    reveal_type(mts(2)) # Revealed type is 'repro.TwoTypes[builtins.int*, builtins.int*]'
    reveal_type(mte.__call__) # Revealed type is 'def [B] (a: B`2) -> repro.TwoTypes[A`-1, B`2]'
    reveal_type(mte(2)) # Revealed type is 'repro.TwoTypes[A`-1, builtins.int*]'
```

I'd expect both of these implementations to typecheck identically, but more importantly you can see `reveal_type(mts(2))` has inferred `int` for both type arguments in `TwoTypes`, even though the first argument, while still unknown to the implementation of `make_two`, would have previously been determined by a caller of this method, based on the instance of `MakeTwoSurprise` that they had passed.

Any and all feedback/assistance is greatly appreciated.

**Comment by ilevkivskyi** [comment]
Thanks for reporting, this definitely looks like a bug. Unfortunately we have a bunch of code duplication for decorated and non-decorated methods (for historical reasons), so I assume some corner cases are missing in the decorated part.

In particular, ``TwoTypes[A`-1, B`-1]`` is clearly wrong, two type variables should not have same ids. Just to clarify, is this specific to `__call__()` or any abstract methods in your code?

**Comment by beezee** [comment]
Any abstract will exhibit the same behavior, `__call__` was an arbitrary choice for the example.

Thanks for the fast response. Sounds like a missing corner case in a duplicate path at least has potential to be an easy fix? I've admittedly not looked at any of the mypy source, but if there's a place you think I might be able to start looking to familiarize myself around this issue, I'd be happy to take a crack at a fix.

**Comment by ilevkivskyi** [comment]
I think this is a medium complexity issue, but you can still try it. The relevant code lives in `mypy/checkmember.py` in `analyze_instance_member_access()` for non-decorated methods and in `analyze_member_var_access()` (and mostly in its helper `analyze_var()`) for decorated methods.

It looks like this part:
```python
        typ = map_instance_to_supertype(typ, method.info)
        member_type = expand_type_by_instance(signature, typ)
        freeze_type_vars(member_type)
```
is present in the first one, but not in the second (I am not sure all of them are needed).

When you will add tests, add not only your repro, but also more tricky examples (like when the abstract method is accessed on a subclass, on a subclass with rebound variables etc). Test cases can be put in `tests-data/unit/check-generics.test`.

**Comment by beezee** [comment]
@ilevkivskyi I have a PR open here - https://github.com/python/mypy/pull/7933 - with an open q about how I might reconcile my tests now that the ids on the type params from the original example are correctly being adjusted, since the values assigned will change depending on the context the test is run under (specifically what is typechecked prior to the test case in question.)

Would love any input you might have.

**Comment by ilevkivskyi** [comment]
> Would love any input you might have.

Sorry, I might not have time this week, feel free to ping me next week if you will not get a review.

**Comment by scole66** [comment]
Upvote for this issue. This just hit me. My testcase:
```python
from abc import ABCMeta, abstractmethod
from typing import TypeVar, Generic, Callable

A = TypeVar("A")
B = TypeVar("B")

class Functor(Generic[A], metaclass=ABCMeta):
    @abstractmethod
    def map(self, f: Callable[[A], B]) -> "Functor[B]":
        ...

def fmap(container: "Functor[A]", func: Callable[[A], B]) -> "Functor[B]":
    return container.map(func)
```
for which mypy gives me:
```
example.py:13: error: Argument 1 to "map" of "Functor" has incompatible type "Callable[[A], B]"; expected "Callable[[B], B]"
```

**Comment by beezee** [comment]
Funny Steven I was also implementing functor when I encountered this
