### ISSUE TITLE
Support more than just string literals with TypedDict indexing

### ISSUE THREAD

**Issue by wadetregaskis-linkedin** [python/mypy#7867]
```
from mypy_extensions import TypedDict

T = TypedDict('T', {'a': float, 'b': float, 'c': float})

foo: T = {'a': 0.0, 'b': 0.0, 'c': 0.0}

for key in ('a', 'b', 'c'):
    foo[key] = 1.0
```

mypy currently (0.730) complains about that last line, saying `error: TypedDict key must be a string literal; expected one of ('a', 'b', 'c')`.  It's understandable, but limiting - it'd be great if mypy could recognise that `key` is in fact one of the valid keys for `T`.

**Comment by wadetregaskis-linkedin** [comment]
Aaaaand now I see [this juicy-looking patch](https://github.com/python/mypy/pull/7645) that went into 0.740, which might be exactly this improvement.  Testing now (against my real code, not the hugely simplified case I provided previously)…

**Comment by wadetregaskis-linkedin** [comment]
Unfortunately, no, mypy 0.740 hasn't addressed this limitation.

**Comment by ilevkivskyi** [comment]
This looks like really low priority.

**Comment by jamesbraza** [comment]
Seems related: https://github.com/python/mypy/issues/7178

Also, +1 on this issue, I think this will be a nice feature.

**Comment by 97littleleaf11** [comment]
There is a duplicate issue https://github.com/python/mypy/issues/9230 with more discussion. Let's just close this one!
