### ISSUE TITLE
Iterating a list of nested named tuples causes type error

### ISSUE THREAD

**Issue by ruuda** [python/mypy#7902]
I am reporting a bug. Consider this code:

```python
from typing import List, NamedTuple, Union

class A(NamedTuple):
    p: int

class B(NamedTuple):
    q: int

class P(NamedTuple):
    a: A

class Q(NamedTuple):
    b: B

def f(xs: List[Union[P, Q]]) -> None:
    for x in xs:
        pass
```

I would not expect any type errors to be reported for this file, but when typechecking this file with Mypy, it reports the following type error:

```
repro.py:16: error: Invalid self argument "Iterator[Union[P, Q, P, Q]]" to attribute function "__next__" with type "Callable[[Iterator[Union[P, Q]]], Union[P, Q]]"
```

Adding an extra field to either `A` or `B` makes the error go away, but if they have the same number of fields, the error persists. The fields can have different types or names, that still triggers the error.

Note that this is a minimal example, but we are actually running into this bug in production code with more elaborate types with more fields.

I can reproduce this error with the following Mypy versions, by just running `mypy` with no additional flags:
* 0.720
* 0.750+dev.a94e649de794ecd169a5bcc42274e5205ffbb1fb (current master)

**Comment by ruuda** [comment]
Because the error goes away when the number of fields is different, a workaround is to add a dummy field with a default value to one of the named tuples.

**Comment by ilevkivskyi** [comment]
Wow, this is really mysterious. Probably something to do with either unions or tuple fallbacks (or both).

**Comment by AlexWaygood** [comment]
This [no longer reproduces](https://mypy-play.net/?mypy=0.750&python=3.10&flags=strict%2Cwarn-unreachable&gist=360f7d25865b966c30b697fc610274cf) on mypy 0.750+
