### ISSUE TITLE
`set` not always treated as a type of MutableSet

### ISSUE THREAD

**Issue by wadetregaskis-linkedin** [python/mypy#7914]
```
from typing import MutableSet, Tuple

def bar(arg: MutableSet[int]) -> None:
    pass

s1 = {5}
bar(s1)  # Fine, apparently.

def troz(arg: MutableSet[Tuple[int]]) -> None:
    pass

s2 = {(0,)}
troz(s2)  # Fine, apparently.

def foo(arg: MutableSet[Tuple]) -> None:
    pass

s3 = {(0,)}
foo(s3)  # Not fine, apparently.
foo({(0,)})  # But this works.
```

`test.py:19: error: Argument 1 to "foo" has incompatible type "Set[Tuple[int]]"; expected "MutableSet[Tuple[Any, ...]]"`

**Comment by ilevkivskyi** [comment]
This is a valid error, because `MutableSet` is invariant https://mypy.readthedocs.io/en/latest/generics.html#variance-of-generic-types

**Comment by wadetregaskis-linkedin** [comment]
Can you please elaborate?  There's no subtyping involved here, which is the crux of what I typically think about re invariance vs covariance etc.  I don't see why having the `Tuple` contents be unspecified would change how `MutableSet` behaves, nor why - orthogonally - mypy apparently will happily infer / coerce the type as desired when it's used inline, but not when it's merely given a name (stored in a local variable).
