### ISSUE TITLE
Is there a way to import type from a stub file?

### ISSUE THREAD

**Issue by Delgan** [python/mypy#7915]
Hi. I'm sorry to bother you with such a silly question, but I struggle to understand how types defined in stub files are supposed to be used by external applications.

Let's imagine a library like this:

```python
# lib/__init__.py
def foo():
    return {"a": "bar", "b": 123, "c": 0.987}
```

Which implements type hints in the following `.pyi` file:
```python
# lib/__init__.pyi
from typing import TypedDict

class FooDict(TypedDict):
    a: str
    b: int
    c: float

def foo() -> FooDict: ...
```
As expected, `mypy` warns about possible misuses:

```python
# script.py
import lib
res = lib.foo()
print(res["d"])
# script.py:3: error: TypedDict "FooDict" has no key 'd'
```

However, how could an user using `lib` annotate it's own function using `FooDict`? I don't understand how not to loose the type when passing the object of a custom type to another function.

```python
import lib

def my_func(val: ???):
    print(val["d"])

my_func(lib.foo())
```

Obviously, `lib.FooDict` does not work.

**Comment by Delgan** [comment]
Ok, I just needed postponed evaluation of annotations. :smiley: 

```python
from __future__ import annotations
import lib

def foo(x:lib.FooDict):
    print(x["d"])

foo(lib.foo())
```

The solution is obvious, as often it is revealed once the question properly posed.

**Comment by MarcBresson** [comment]
Hey, I'm working with loguru and I stumbled upon this issue and I cannot type using `loguru.Record`

Here is the full traceback

```
import loguru

def func1(record: loguru.Record) -> str:
    return record["message"]

>>> def func1(record: loguru.Record) -> str:
>>>      """
>>>      Format the record and returns the string to indentify the source
>>>      of the log following the format:
>>>      """
>>>      return record["message"]
>>> 
>>> AttributeError: module 'loguru' has no attribute 'Record'
```

**Comment by Delgan** [comment]
@MarcBresson Yes, you need to quote the type or use `from __future__ import annotations` until [PEP 563](https://peps.python.org/pep-0563/) become the default.

This is because `loguru.Record` does not exist at run-time, it's only valid during type checking.
