### ISSUE TITLE
Method of child class not applicable to decorator working on base class

### ISSUE THREAD

**Issue by karlch** [python/mypy#7919]
Sorry if I missed an issue pointing to this already, I looked but couldn't find one.

When I run mypy on the following code:
```
from typing import Callable

CallbackT = Callable[["Base"], None]


def decorator(func: CallbackT) -> CallbackT:

    def inner(self: Base):
        # do something with instance that only requires Base
        func(self)

    return inner


class Base:
    pass


class Child(Base):

    @decorator
    def other(self) -> None:
        pass
```

Running mypy 0.740 with python 3.7.4 I get:
```
test.py:24: error: Argument 1 to "decorator" has incompatible type "Callable[[Child], None]"; expected "Callable[[Base], None]"
Found 1 error in 1 file (checked 1 source file)
```

As the child class inherits from `Base`, I would have expected this to work fine. Am I missing something or is this a bug?

EDIT: this is reproducable on the currently latest git 84126ab9985844d8cda3809688034af895fdaf7c in a clean venv.

**Comment by saleemrashid** [comment]
```python
class Base:
    pass


class Child(Base):
    def child_method(self: Child) -> None:
        pass

    def other(self: Child) -> None:
        self.child_method()
```

If `Child.other` were compatible with `Callback[[Base], None]`, then you could be able to do `Child.other(Base())` which would obviously fail (as `Base.child_method` does not exist).

For your example, you want to use `TypeVar` to say that you accept a `Callable[[T], None]` where `T` is a subclass of `Base`, but not necessarily `Base`:

```python
from typing import Callable, TypeVar


class Base:
    def base_method(self) -> None:
        pass


T = TypeVar("T", bound=Base)


def decorator(func: Callable[[T], None]) -> Callable[[T], None]:
    def inner(self: T) -> None:
        self.base_method()
        func(self)

    return inner


class Child(Base):
    @decorator
    def other(self) -> None:
        pass
```

**Comment by karlch** [comment]
Thank you, this makes perfect sense!

Just a quick follow-up question, why can I not properly wrap the `Callable[[T], None]` into a definition like `F = Callable[[T], None]`?

Your example correctly complains with:
```
class NotBase:

    @decorator
    def something(self) -> None:
        pass
```
leading to:
```
test.py:25: error: Value of type variable "T" of "decorator" cannot be "NotBase"
```

But changing decorator to:
```
T = TypeVar("T", bound=Base)
F = Callable[[T], None]

def decorator(func: F) -> F:

    def inner(self: T):
        # do something with instance
        func(self)

    return inner
```

gives no mypy errors.

Thanks again!

**Comment by saleemrashid** [comment]
`F` is a [generic type alias](https://mypy.readthedocs.io/en/latest/generics.html#generic-type-aliases). You need to use `F[T]`.

**Comment by karlch** [comment]
Thanks for your help and sorry for the noise! Slowly grasping the concept behind this. Solved :)

**Comment by saleemrashid** [comment]
@karlch If you use `mypy --strict`, it would catch the usage of `F`, instead of `F[T]`

**Comment by karlch** [comment]
Nice! Unfortunately even only applying `--disallow-any-generics` goes completely bananas on my not so strict codebase, shame on me :laughing:
