### ISSUE TITLE
Regression involving generic class methods

### ISSUE THREAD

**Issue by msullivan** [python/mypy#7925]
Distilled from an issue in S:

```
from typing import Generic, List, Optional, TypeVar

Q = TypeVar("Q")
T = TypeVar("T", bound="RequestWrapper")

class RequestWrapper(Generic[Q]):
    @classmethod
    def valid(cls, reqs):
        # type: (List[T]) -> List[T]
        pass

class _ConcreteRequestWrapper(RequestWrapper[int]):
    pass

def test(valid_reqs):
    # type: (List[_ConcreteRequestWrapper]) -> None
    _ConcreteRequestWrapper.valid(valid_reqs)
```

This produces an error in `test`: `error: Argument 1 to "valid" of "RequestWrapper" has incompatible type "List[_ConcreteRequestWrapper]"; expected "List[<nothing>]"`

Looks like this was introduced in #7860.

**Comment by ilevkivskyi** [comment]
This one is pretty bad actually. I understand why this happens: `bind_self()` just always binds the _first_ type variable, but instead it should bind only variable(s) that appear in the self-type. I have a decent quick-fix, but I want to spend a bit more time maybe I will find a more principled fix for this while I am at it.
