### ISSUE TITLE
Bound TypeVar reported as incompatible with argument defaults

### ISSUE THREAD

**Issue by ambv** [python/mypy#7927]
This is probably a herp derp on my part but I can't figure out what's wrong here.

Example:
```py3
from typing import *

class C:
    pass

C_T = TypeVar("C_T", bound=C)

def func(factory: Type[C_T] = C) -> C_T:
    return factory()
```

On the penultimate line Mypy reports:
```
error: Incompatible default for argument "type" (default has type "Type[C]",
argument has type "Type[C_T]")
```

I would expect it to be happy about the default.

**Comment by TH3CHARLie** [comment]
I'm not 100% sure but you may check #7864 on @ilevkivskyi 's clarification on default values.

**Comment by ilevkivskyi** [comment]
This is actually a special case that we might want to special-case, see https://github.com/python/mypy/issues/3737. But yes, the general solution is to use overloads.
