### ISSUE TITLE
Invalid base class even though the type is defined

### ISSUE THREAD

**Issue by ckarnell** [python/mypy#7954]
* Are you reporting a bug, or opening a feature request?
A bug.

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```
from typing import cast, Type

class ClassToCastTo:
    pass

class ClassToCast:
    pass

ActualBaseClass = cast(Type[ClassToCastTo], ClassToCast)

class ActualClass(ActualBaseClass): # Invalid base class "ActualBaseClass"  [misc]
    pass
```

* What is the actual behavior/output?
A type error: `Invalid base class "ActualBaseClass"  [misc]`

* What is the behavior/output you expect?
No type error. I don't know why `Type[ClassToCastTo]` wouldn't be a valid type for a base class.

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
mypy 0.740

* What are the mypy flags you are using? (For example --strict-optional)
disallow_untyped_calls = False
disallow_untyped_defs = True
ignore_missing_imports = True
warn_return_any = False
follow_imports = silent
no_implicit_optional = True
warn_unused_ignores = True
mypy_path = ./stubs
show_error_codes = True

**Comment by msullivan** [comment]
mypy won't think of `ActualBaseClass` as a class, just a variable of `Type[ClassToCastTo]`. It won't be able to figure out what the MRO of the object is, since it can't see what class.

What are you trying to accomplish here? If the goal is to have a different base class when check and at runtime, you probably can define a type alias in an `if TYPE_CHECKING` block

**Comment by ckarnell** [comment]
@msullivan I'm basically trying to accomplish exactly what's shown above. Basically, it's a workaround to creating some complex stubs for flask-sqlalchemy's model object, which involves meta-programming shenanigans that I'd have to write a plugin to allow mypy to make any sense of.

Could you show me an example of what you mean with the type alias?

**Comment by ckarnell** [comment]
>mypy won't think of ActualBaseClass as a class, just a variable of Type[ClassToCastTo]. It won't be able to figure out what the MRO of the object is, since it can't see what class.

Can you please explain the distinction you're making here? I always thought even a "normal syntax" class definition was essentially just a variable definition, since these are syntactic sugar:

```
class TestClass:
    pass


TestClass = type('TestClass', (object,), {})
```

I must be having a fundamental misunderstanding of how mypy operates, or I'm missing some corner case in the difference between these. Can you please enlighten me?

**Comment by JukkaL** [comment]
My assumes that class definitions defined using `class Foo` are not assigned to at runtime. If you try to do that, mypy will genenerate an error. Of course you can still do this at runtime, but then mypy can't catch some errors that it would otherwise be able to catch. This is conceptually no different than declaring `x` as a final attribute -- mypy tries to ensure that you don't assign to it after initialization, but nothing prevents you from doing it at runtime.

**Comment by zedrdave** [comment]
@ckarnell Sorry to kinda-hijack the thread, but I found this issue while trying to solve my own headaches, trying to write stubs for flask-sqlalchemy. Have you ever got anywhere with this? Would you mind sharing the stubs by any chance?

**Comment by ckarnell** [comment]
Sure @zedrdave. I basically just wanted the SQLAlchemy stubs plugin to understand that my base model class should by type checked as a SQLAlchemy model even though it's using flask-sqlalchemy, so I just did this (this is an approximation but you'll get the idea):


```
if TYPE_CHECKING:
    # Create fake base SQLAlchemy stubs will understand. 
    from sqlalchemy.ext.declarative import declarative_base
    Base = declarative_base()
    class BaseeModel(Base):
        pass
else:
    # Create runtime object.
    from flask_sqlalchemy import SQLAlchemy
    db = SQLAlchemy()
    class BaseModel(db.Model):
        __abstract__ = True
```
