### ISSUE TITLE
Improve documentation - cannot locate mypy.ini nor setup.cfg files

### ISSUE THREAD

**Issue by cibic89** [python/mypy#7961]
Trying to get started and I cannot find the config file to inform mypy where the libraries that I'm using are. The documentation is ambiguous as to where the config file is nor does it inform you on how to generate one; there is also no samples of a config file that I could find.

**Comment by JukkaL** [comment]
Did you read https://mypy.readthedocs.io/en/latest/config_file.html?

**Comment by cibic89** [comment]
Of course I did. What is defined as current directory, mypy's install directory, the active environment, or the current directory I'm calling mypy from? There are other options, why don't stick to one to reduce ambiguity? I like the --config-file command line flag by the way.

The key problem for new to mypy individuals I think is the missing config file example with some libraries is crucial for adoption. Think about your audience; you'd want someone new to get started as soon as possible before they move on to something else or give up.
________________________________

**Comment by JukkaL** [comment]
Thanks for the feedback -- I agree that the section could be clearer. Would like to suggest a PR that improves the wording? The current directory refers to the current working directory. A more detailed example or examples would also be good to have.

**Comment by cibic89** [comment]
> 
> 
> Thanks for the feedback -- I agree that the section could be clearer. Would like to suggest a PR that improves the wording? The current directory refers to the current working directory. A more detailed example or examples would also be good to have.

Sure, I'd like to contribute!

**Comment by PrasanthChettri** [comment]
@JukkaL  I tried my hand in simplifying the wording, let me know if I need to make changes

**Comment by williamsantosa** [comment]
Hi everyone, this is my first time contributing to an open source project. Please review my changes and let me know what changes need to be made. Thank you!
