### ISSUE TITLE
Set MYPY_CONFIG_FILE_DIR environment variable

### ISSUE THREAD

**Issue by blueyed** [python/mypy#7968]
In addition to / as an alternative to https://github.com/python/mypy/issues/7967 mypy could set an environment variable of the config file being used.

This could be used with e.g. `mypy_path` then (`mypy_path = $MYPY_CONFIGFILE/src`), and also with defaults like `cache_dir`.

**Comment by JukkaL** [comment]
I like this better than #7967, since this preserves backward compatibility. My proposal for the name of the variable is `MYPY_CONFIG_FILE_DIR`.

**Comment by mridullpandey** [comment]
hi @blueyed  i want work on it will  you please elaborate  it

**Comment by blueyed** [comment]
@mridullpandey 
What is unclear here?
It should set `MYPY_CONFIG_FILE_DIR` in `os.environ`, so that it can be expanded / is available while parsing the config.

**Comment by blueyed** [comment]
btw: I think `$MYPY_CONFIG_FILE(_PATH)` might be more flexible: it would provide the actual file (which might be `mypy.ini`, `setup.cfg` etc), and could also be used as `$MYPY_CONFIG_FILE/../…` to have its directory then.
While `$MYPY_CONFIG_FILE_DIR` might be more explicit, we might end up with adding `$MYPY_CONFIG_FILE_PATH` additionally afterwards.

**Comment by JukkaL** [comment]
@blueyed Do you have a use case for using the path to the config file, instead of the directory where it's located? Using `..` after a path to a file looks odd to me (though it's not hard to support), and I'd rather avoid it.

@mridullpandey Config file parsing is implemented in `mypy.config_parser`. In particular, `expand_path` seems relevant.

**Comment by blueyed** [comment]
@JukkaL 
Not really, but thought about it when adding `PYTEST_CONFIG_{FILE,DIR}` to pytest, and figured it might be more flexible, since you cannot determine the ini file being used from the dir (due to different names).
As for pytest I've thought that processes/tests being run by pytest then might be able to get the used config file location, but have not thought much about a use case.

`$file/..` is a bit weird, but gets resolved fine via `os.path.{normpath,realpath}`.

So I am +0 myself on using the file - mainly to avoid having to add another env var later, and given that it is more explicit/precise.  But it has the downside of having to append "/.." for the more typical use case (this issue).

**Comment by joybhallaa** [comment]
i'm taking this issue

**Comment by gvanrossum** [comment]
PR was reverted (it broke CI).
