### ISSUE TITLE
Inferring actual return type when Union is specified in signature 

### ISSUE THREAD

**Issue by deeplook** [python/mypy#7973]
I want to use `Union` as a return type annotation for multiple possible return types. But I get two unexpected `mypy` errors and wonder if these are correct behavior, and if they are how to use `Union`s as intended? It appears that the actual return type of the function `_str()` cannot be inferred from the function body.

```
$ python --version
Python 3.7.3

$ mypy --version
mypy 0.740

$ cat check_typing.py
#!/usr/bin/env python3

from typing import Union

def _str(num: int) -> Union[str, int]:
    res: str = str(num)
    return res

s = _str(42)
assert s == "42"
assert type(s) == str

s2 = s + s  # line 13

$ python3 check_typing.py

$ mypy check_typing.py
check_typing.py:13: error: Unsupported operand types for + ("str" and "int")
check_typing.py:13: error: Unsupported operand types for + ("int" and "str")
check_typing.py:13: note: Both left and right operands are unions
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by ethanhs** [comment]
Hi, in your case you probably want to use `isinstance(s, str)`. You can read https://mypy.readthedocs.io/en/latest/casts.html for more.

**Comment by deeplook** [comment]
I don't think I want to use `isinstance()` at runtime on the function result because I could do that also without any type annotations.

The function signature says what to expect. I understand that `s = _str(42)` doesn't tell mypy which type it will be at runtime. What I'm surprised about is that using `s: str = _str(42)` is not enough to tell it what it should be at that point while meeting the type annotation (and causing `Incompatible types in assignment (expression has type "Union[str, int]", variable has type "str")`), but `s = cast(str, _str(42))` is sufficient and passes.

**Comment by JukkaL** [comment]
A type annotation and a cast are two different things. Assigning a value with a union type to a variable with a non-union type is unsafe, and that's why you have to use a cast (or `isinstance()`). Adding a type annotation is supposed to be type-safe -- if it would perform an implicit cast, it would be much harder to write type-safe code, since each type annotation in an assignment could be hiding a bug (a source of runtime type errors).
