### ISSUE TITLE
Optional in TypeDict does not allow to omit values.

### ISSUE THREAD

**Issue by scharf** [python/mypy#7993]
Given the following code structure, mypy complains:

> `Key 'name' missing for TypedDict "Field"`

```python
from typing import List, Optional, TypedDict

Field = TypedDict('Field', {
    'id': str,
    'name': Optional[str],
})

data: List[Field] = [
    {
        "id": "x1",
        "name": "This field is optional"
    },
    {
        "id": "x2",  # error: Key 'name' missing for TypedDict "Field"
    },
]
```

There should be a way to tell mypy that it is OK to omit a value.

**Comment by JukkaL** [comment]
`Optional[x]` doesn't mean that something can be left out; it means that `None` is a valid value. Use `total=False` to make keys optional. It's all in the docs: https://mypy.readthedocs.io/en/latest/more_types.html#totality

**Comment by scharf** [comment]
Since `TypedDict` is now part of python `3.8` it would be good if `total` would be also documented in the official documentation https://docs.python.org/3/library/typing.html?highlight=typeddict#typing.TypedDict. I did not find it there and I did not know that the specs of the types live at https://mypy.readthedocs.io (since there is no mention of mypy or https://mypy.readthedocs.io  in https://docs.python.org/3/library/typing.html).

I wanted to report a bug at `mypy_extensions` but there I was told that this is not the right place: https://github.com/python/mypy_extensions/issues/17#issuecomment-557097384

So, it's a bit confusing to figure out where the documentation for the type hints and the `typing` module actually resides.

**Comment by JukkaL** [comment]
Feel free to file an issue about missing docs about `total` in CPython (https://bugs.python.org/). It's supposed to be documented in Python docs, and the omission must be an oversight.

Mypy documentation covers much of the same ground as Python documentation, but that makes sense since mypy documentation can cover details that are specific to mypy and would be out of place in Python documentation.

**Comment by asfaltboy** [comment]
For whomever comes across this ticket looking for the docs, `total` usage is currently mentioned in https://docs.python.org/3/library/typing.html#typing.TypedDict

**Comment by alex9311** [comment]
related PEP `PEP 655 -- Marking individual TypedDict items as required or potentially-missing` 
https://www.python.org/dev/peps/pep-0655/

**Comment by Tobils** [comment]
> `Optional[x]` doesn't mean that something can be left out; it means that `None` is a valid value. Use `total=False` to make keys optional. It's all in the docs: https://mypy.readthedocs.io/en/latest/more_types.html#totality

workk for me by adding Total=False

`class name_class(TypedDict, total=False):`
   `var: Optional[str]`

**Comment by cglacet** [comment]
Using `total=False` doesn't really help, it means none of the keys are required (which is probably not what is needed here).

It seems like there is an experimental `NotRequired` here : https://github.com/python/typing/blob/master/typing_extensions/README.rst

```python
# pip install typing-extensions
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired

class Field(TypedDict):
    id: str
    name: NotRequired[str]


data: List[Field] = [
    {"id": "x1", "name": "This field is optional"},
    {"id": "x2"},  # No more error here
    {"name": "still optional"},  # Missing key "id" for TypedDict "Field"
]
```

**Comment by erictraut** [comment]
Mypy doesn't have support for `Required` and `NotRequired` yet. In the meantime, you can use class inheritance to define combinations of required and not-required fields. 

```python
class FieldBase(TypedDict, total=True):
    id: str

class Field(FieldBase, total=False):
    name: str
```

It's a little verbose, but it gets the job done.

**Comment by JelleZijlstra** [comment]
Actually, mypy 0.930 does support Required and NotRequired. See http://mypy-lang.blogspot.com/2021/12/mypy-0930-released.html.
