### ISSUE TITLE
Variant of alias for enum type cannot be used as Literal

### ISSUE THREAD

**Issue by colinfang** [python/mypy#7996]
```python
class Foo(Enum):
    A = 1

F = Foo

# works
x: Literal[Foo.A]
# name-defined error
y: Literal[F.A]
```

Is there a simple workaround here? I also tried `F: Final = Foo` which doesn't work either

**Comment by JukkaL** [comment]
This looks like a bug. I'm not sure if there's any general workaround right now.

cc @Michael0x2a (literal types) and @ilevkivskyi (type aliases)

**Comment by ilevkivskyi** [comment]
This looks like a missing case in `lookup_qualified()`, this doesn't work either:
```python
class Out:
    class In:
        ...
O = Out
z: O.In  # Same name not defined error
```
Interestingly, `visit_member_expr()` has an `elif` branch for this, so for example this works (on master):
```python
f: Final = F.A
reveal_type(f)  # Revealed type is 'Literal[__main__.Foo.A]?'
```
Should be easy to fix.
