### ISSUE TITLE
False positive on returning Any from function declared to return object

### ISSUE THREAD

**Issue by GoldsteinE** [python/mypy#8008]
mypy with `--warn-return-any` gives a warning for this function:
```python
def f() -> object:
    x: Any = 1
    return x
```
This code is correct in fact: any type is `object`, so we can safely return `Any`.
It can be fixed like that:
```python
def f() -> object:
    x: Any = 1
    return cast(object, x)
```
but `cast(object, ...)` should be a no-op for mypy IMO.

**Comment by ilevkivskyi** [comment]
I agree we can make an exception in this case. I think it is relatively low priority, but since the fix may be trivial I am setting priority to normal.

**Comment by TH3CHARLie** [comment]
see #8011
