### ISSUE TITLE
Can not find compiled (pyd) module

### ISSUE THREAD

**Issue by Djedouas** [python/mypy#8033]
Hello,

I have the following directory structure:

  |--`my_libs/`
 &nbsp; &nbsp; &nbsp; |--`qgis/`
&nbsp; &nbsp; &nbsp;  |--`core/`
&nbsp; &nbsp; &nbsp;  |&nbsp; &nbsp; &nbsp;|--`__init__.py`
&nbsp; &nbsp; &nbsp; |--`_core.pyd`

My `mypy_path` is set with a config file to the `my_libs` directory.

In the `qgis.__init__` module there is a `from qgis._core import *` statement.

In my python test code I have:
```
from qgis._core import QgsAction
from qgis.core import QgsAction
```

The mypy output is:
```
error: Cannot find module named 'qgis._core'
error: Module 'qgis.core' has no attribute 'QgsAction'
```

On the first line mypy can't find the module, but on the second line the module is found, it's the attribute which is not found.

Because mypy can't find the `_core` module, it can't find the `QgsAction` attribute in the `core` module because the latter imports `_core`.

If mypy was able to find `qgis._core` there would be no error.

I don't understand why mypy can find `qgis` module whereas `_core` is not found, since they are in the same source folder.

Thanks !

**Comment by ilevkivskyi** [comment]
Mypy doesn't support any binary/compiled Python formats (`.pyc`, `.pyd`, `.so`, etc), since it is a _static_ type checker. Mypy needs to see source code `.py`, or a type stub `.pyi` (it's like a header file for Python). You can try using `stubgen` to generate `.pyi` for compiled files, see https://mypy.readthedocs.io/en/latest/stubgen.html

**Comment by Djedouas** [comment]
OK!

I tried `stubgen` but it outputs an error:
```
Critical error during semantic analysis: mypy: can't decode file '_core.pyd': 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

**Comment by JukkaL** [comment]
The stubgen error is not releated pyd files -- can you create a new issue?

**Comment by kerim371** [comment]
I'm sorry for disturbing but I can't understand whether `stubgen` supports `.pyd` files or not? The question arised after I saw these links:
1. https://github.com/python/mypy/issues/5283
2. https://github.com/pybind/pybind11/issues/2350#issuecomment-668879301
3but when I try to run the command `stubgen mymodule.pyd` I get error:
**Critical error during semantic analysis: mypy: stubgen does not support .pyd files**

**Comment by Tinyblack** [comment]
> I'm sorry for disturbing but I can't understand whether `stubgen` supports `.pyd` files or not? The question arised after I saw these links:
> 
> 1. [Trying to generate .pyi from .pyd raises UnicodeDecodeError #5283](https://github.com/python/mypy/issues/5283)
> 2. [creating stub pyi files automatically from pybind projects pybind/pybind11#2350 (comment)](https://github.com/pybind/pybind11/issues/2350#issuecomment-668879301)
>    3but when I try to run the command `stubgen mymodule.pyd` I get error:
>    **Critical error during semantic analysis: mypy: stubgen does not support .pyd files**

Sorry for disturbing. If you are still waiting for an answer to this problem, the short answer I think is yes. But you may need to alter the command a bit.
By referring to the comment https://github.com/python/mypy/issues/7692#issuecomment-541001171, the command I ran successfully is `stubgen --parse-only -m mymodule` (and try `stubgen --parse-only --ignore-errors -m mymodule` if some errors show). `mymodule` is the name of your module you used when generating your `mymodule.pyd`.
I hope this will help.
