### ISSUE TITLE
stubgen pyd file utf-8 error

### ISSUE THREAD

**Issue by Djedouas** [python/mypy#8035]
Hello,

I have a file `_core.pyd` that comes from [QGIS](http://www.qgis.org) installation (file enclosed) that I can't use with stubgen:

```
Critical error during semantic analysis: mypy: can't decode file '_core.pyd': 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```
[_core.zip](https://github.com/python/mypy/files/3905454/_core.zip)

**Comment by JukkaL** [comment]
Stubgen doesn't support `.pyd` files. It would be nice if it would generate a better error message, however. Leaving this issue open because of the confusing error message.
