### ISSUE TITLE
Mypy behavior when the object passes through a typeshed function?

### ISSUE THREAD

**Issue by eff-kay** [python/mypy#8037]
Sorry, I didnt know where else to post this to get an immediate response, and this is probably not a bug. I dont seem to understand Mypy's behaviour in the following case. The code is simplified for this question

    import typing as t
    ...

    self._store:t.Dict[str,str] = dict()
    ...

    def set_kv(self, key:str, value:int)->t.Any:
        assert isinstance(key, six.string_types)
        assert isinstance(value, six.string_types)
        with self.__lock.write():
            self.__store[key] = value
            self.__persist()

I test this code with mypy by running the following command

    mypy docido_sdk/index/test.py --ignore-missing-imports --follow-imports=error --strict-optional

now ideally this should throw an error at line `self.__store[key]= value`. But it does not. 
When I remove `assert isinstance(value, six.string_types)`, only then does it throw an error. The isinstance is a typshed function given below

    def isinstance(__o: object, __t: Union[type, Tuple[Union[type, Tuple], ...]]) -> bool: ...

Is this a bug or an expected behaviour of mypy, because if I understand correctly `isinstance` should not affect the understanding of mypy about the type of `value`.

**Comment by JelleZijlstra** [comment]
Mypy special cases the `isinstance` function. I think what's going on is that mypy considers the code after the `isinstance()` check to be unreachable, because `value` can hardly be both an int and a str.

**Comment by eff-kay** [comment]
Hay @JelleZijlstra, thanks for the comment. Shouldnt it throw an error then, that "value" could have a possible type collision. Also, why would mypy consider the code after isinstance() to be unreachable??

**Comment by ilevkivskyi** [comment]
You can use `--warn-unreachable` for such situations.

**Comment by eff-kay** [comment]
yup, it threw an error statement is unreachable, thanks. But sorry, I still dont understand why would mypy think that the statement is unreachable. Or more precisely which did mypy special case the isinstance function.

**Comment by JelleZijlstra** [comment]
The annotation says the value is an int. The assertion will fail if the value is a str. It can't be both, so mypy concludes that the assertion will always trigger and the code after the assertion is unreachable.

**Comment by eff-kay** [comment]
ok got it, I didn't realize mypy understood what six.string_types meant. Thanks for clearing that up.
