### ISSUE TITLE
omitting optional argument before kwargs results in incompatible type

### ISSUE THREAD

**Issue by pabiswas** [python/mypy#8038]
* Are you reporting a bug, or opening a feature request?
  Bug

* Please insert below the code you are checking with mypy,
```python
class Client:
    def __init__(self, enforce_checks: bool = False, **defaults: Any ) -> None:
        pass

auth_headers = {
    'HTTP_AUTHORIZATION': 'JWT dummy'
}

Client(HTTP_AUTHORIZATION='JWT dummy') # ok
Client(**auth_headers) # test.py:12: error: Argument 1 to "Client" has incompatible type "**Dict[str, str]"; expected "bool"
```

* Output:
$ mypy test.py
test.py:12: error: Argument 1 to "Client" has incompatible type "**Dict[str, str]"; expected "bool"
Found 1 error in 1 file (checked 1 source file)

* What are the versions of mypy and Python you are using?
$python -V
Python 3.7.2
$mypy -V
mypy 0.750+dev.b7465deaac4c76f8ed1c2a87c177697d566f0bc6

* What are the mypy flags you are using? (For example --strict-optional)
None

**Comment by ilevkivskyi** [comment]
Mypy is technically correct here, what if:
```python
auth_headers = {
    'enforce_checks': 'surprise!'
    'HTTP_AUTHORIZATION': 'JWT dummy'
}
```
The workaround is to use explicit `TypedDict` as a type for `auth_headers`, so that mypy knows which keys are allowed to be in the dictionary. For example:
```python
class AuthHeaders(TypedDict, total=False):
    HTTP_AUTHORIZATION: str
```
