### ISSUE TITLE
mypy raises exception when isinstance wrapped in a function

### ISSUE THREAD

**Issue by PJCampi** [python/mypy#8048]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request? 
bug
* Please insert below the code you are checking with mypy,
```
from typing import Union

def foo(x: Union[int, str]) -> int:
    if isinstance(x, int):
        return x + 1  # no error
    raise ValueError()


def bar(x: Union[int, str]) -> bool:
    return isinstance(x, int)


def baz(x: Union[int, str]) -> int:
    if bar(x):
        return x + 1  # error: Unsupported operand types for + ("str" and "int")
    raise ValueError()
```
* What is the actual behavior/output?
Unsupported operand types for + ("str" and "int") in baz

* What is the behavior/output you expect?
no mypy error because the type of x is known to be int at that point.

* What are the versions of mypy and Python you are using? 750 and 3.7

* What are the mypy flags you are using? None

**Comment by JukkaL** [comment]
The logic is too complicated for mypy to figure it out. In order to support the idiom, we'd need to have something like TypeScript's user-defined type guards (https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards).

You can use a cast as a workaround:

```py
def baz(x: Union[int, str]) -> int:
    if bar(x):
        return cast(int, x) + 1
    raise ValueError()
```
