### ISSUE TITLE
TypedDict subclass are not allowed overwritten method arguments

### ISSUE THREAD

**Issue by rmorshea** [python/mypy#8049]
This seems like a bug: `TypedDict` subclasses are incompatible with supertypes when overwriting method argument types. Overwriting return types seems to work fine though:

```python
from typing import TypedDict

class BaseDict(TypedDict):
    x: int

class SuperDict(BaseDict):
    y: int

class ParentClass:
    def f(self, a: BaseDict) -> BaseDict: ...

# --- Return Type Works ---

class OverwriteReturn(ParentClass):
    def f(self, a: BaseDict) -> SuperDict: ...

# --- Argument Doesn't Work ---

class OverwriteArgument(ParentClass):
    def f(self, a: SuperDict) -> BaseDict: ...  # Argument 1 of "f" is incompatible with supertype "ParentClass"; supertype defines the argument type as "BaseDict"
```

**Comment by JukkaL** [comment]
It's unsafe to override a method with a more specific argument type, as it violates the Liskov substitution principle. For return types, it's unsafe to override a method with a more general return type. Mypy is behaving correctly, though the error message is pretty terse.

#7994 proposes making the error message more informative, as this is a common source of confusion.

**Comment by rmorshea** [comment]
@JukkaL on second thought, if `SuperDict` has `total=False` (which is actually my use case), then technically `OverwriteArgument` would satisfy the Liskov substitution principle since `y` would not be a required key and thus `ParentClass.f` could be substituted for `OverwriteMethod.f`.

**Comment by JukkaL** [comment]
Mypy does not allow the omission of an optional key (the reason is somewhat technical) -- `BaseDict` is not considered compatible with `SuperDict` (but the reverse is true).
