### ISSUE TITLE
Code with conditional expressions to specify types typechecks

### ISSUE THREAD

**Issue by mrwright** [python/mypy#805]
The code below, as is is now, typechecks. When we comment the last line and uncomment the one before it, it (correctly) fails to typecheck. My understanding is that mypy doesn't support conditional expressions, so neither should typecheck right now.
```
from typing import *

x = 5 # type: Union[str, int]

#w = x # type: int
w = x if isinstance(x, int) else 5 # type: int
```

**Comment by rwbarton** [comment]
Mypy understands `isinstance` checks in conditional expressions as of a4447fc884a5a0507409ced34229716b680bd847, so this correctly type checks (and doesn't if you insert a `not` before `isinstance`).
