### ISSUE TITLE
Inferencing type reference of abstract class inferred from concrete type values

### ISSUE THREAD

**Issue by achimnol** [python/mypy#8050]
```python3
import abc

class MyAbstractType(metaclass=abc.ABCMeta):
  @abc.abstractmethod
  def do(self): pass

class MyConcreteA(MyAbstractType):
  def do(self):
    print('A')

class MyConcreteB(MyAbstractType):
  def do(self):
    print('B')

my_types = {
  'A': MyConcreteA,
  'B': MyConcreteB,
}
reveal_type(my_types)  # Revealed type is 'builtins.dict[builtins.str*, def () -> test-abc.MyAbstractType]'

a = my_types['A']()  # Cannot instantiate abstract class 'MyAbstractType' with abstract attribute 'do'
a.do()
b = my_types['B']()  # Cannot instantiate abstract class 'MyAbstractType' with abstract attribute 'do'
b.do()
```
The above example does not pass the type check as-is.
I need to change it to pass the type check as follows:

```python3
import abc
from typing import Mapping, Type

class MyAbstractType(metaclass=abc.ABCMeta):
  @abc.abstractmethod
  def do(self): pass

class MyConcreteA(MyAbstractType):
  def do(self):
    print('A')

class MyConcreteB(MyAbstractType):
  def do(self):
    print('B')

my_types: Mapping[str, Type[MyAbstractType]] = {  # explicit annotation
  'A': MyConcreteA,
  'B': MyConcreteB,
}
reveal_type(my_types)  # Revealed type is 'typing.Mapping[builtins.str, Type[test-abc.MyAbstractType]]'

a = my_types['A']()
a.do()
b = my_types['B']()
b.do()
```

Since mypy is able to infer `MyAbstractType` from the dictionary in the first snippet, I believe that it should be also able to infer `Type[MyAbstractType]` since the dictionary values are not instances but class names.

My setup: Python 3.8.0 + mypy 0.750

Related issues/PRs:
 - #5135 looks like a similar issue as the author did not use explicit annotation for the dictionaries.
 - #2853 allowed using explicit annotation above.

**Comment by JukkaL** [comment]
There are two potential ways to improve the situation:
1. Infer `Type[X]` as the value type instead of a callable type.
2. Make it possible to instantiate an abstract type object represented as a callable type.

The first option is harder to implement and is not backward compatible, so my preference would be option 2.

A potential way to implement 2 would be to only flag as errors direct calls to an ABC type object (e.g. `MyAbstractType()`). If the callee is any other kind of expression or a variable, mypy wouldn't complain, since it could actually be a reference to a concrete derived class at runtime.

**Comment by ilevkivskyi** [comment]
More details about ways to implement option 2. There may be a really simple way: set the `from_type_type` flag to `True`,  when computing join and meet of callables (probably unless some/all items represent an abstract class object).

**Comment by scottfurry** [comment]
This assumes both abstract and _all_ concrete implementations are in the same model.

Has someone tried appending to the mapping?
Each concrete implementation would append itself to the mapping?

Seems like a lot of contortions to silence this error.
Note - it took a handful of searches to end up here.
Stopped at along the way... : bugs #1843, #3048, #5135, and #6586.
