### ISSUE TITLE
Supertype to all types except Any

### ISSUE THREAD

**Issue by levsa** [python/mypy#8059]
It seems like there is a missing type below `Any` and above all other types. E.g., I would like to do an overloading like this:

```
    @overload
    def get_fingerprint(self, model: object) -> Fingerprint:
        pass

    @overload
    def get_fingerprint(self, model: None) -> None:
        pass

    def get_fingerprint(self, model: Optional[object]) -> Optional[Fingerprint]:
      ...
```

But mypy complains with `error: Overloaded function signature 2 will never be matched: signature 1's parameter type(s) are the same or broader`

Hence, a builtin type would be needed to include all types except `None`. I would rather not need to introduce a type variable including all builtin types and class types but excluding None. Or is there another way?

**Comment by JukkaL** [comment]
I think that your best bet is to have the `model: None` overload as the first item before the `model: object` item, and `# type: ignore` the error:
 
```py
    @overload
    def get_fingerprint(self, model: None) -> None:  # type: ignore[misc]
        pass

    @overload
    def get_fingerprint(self, model: object) -> Fingerprint:
        pass

    def get_fingerprint(self, model: Optional[object]) -> Optional[Fingerprint]:
      ...
```

This way things should work as you'd expect. There is no way to say 'any object except `None`' at the moment.

**Comment by levsa** [comment]
Ok, thanks! I hope there will such a type in the future, though.
