### ISSUE TITLE
Aliases to literal types can cause str/unicode confusion in stub files on Python 2

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#8062]
This doesn't work properly when put in a stub file in Python 2 mode:
```python
alias = Literal[u'foo']
a: alias
reveal_type(a3)  # Revealed type is Literal['foo'], but must be Literal[u'foo']
```
See https://github.com/python/mypy/pull/8026#pullrequestreview-325816054 for context.

**Comment by JukkaL** [comment]
Closing due to Python 2 feature freeze (#12237).
