### ISSUE TITLE
Return value annotation with pass statement

### ISSUE THREAD

**Issue by zkksch** [python/mypy#8068]
mypy==0.750

```python
class Foo:
    def bar(self) -> int:
        pass


x: int = Foo().bar()
y = x + 2
```

I expected "Incompatible return value type", but mypy says that there are no issues. Is it bug or I can configure mypy in some way to disallow this kind of cases?

**Comment by ilevkivskyi** [comment]
Duplicate of https://github.com/python/mypy/issues/2350
