### ISSUE TITLE
Refer to ClassVar[Type[...]] from annotation

### ISSUE THREAD

**Issue by flying-sheep** [python/mypy#8070]
I’m not sure if what I try to do should be possible, but I feel like it should be easier than the convoluted way it can be done in now. The way I thought it should work doesn’t, since annotations are evaluated at top level, and there’s no way to refer to “current class” (no “Self” type):

```py
from __future__ import annotations
from abc import ABC
import typing as t

class Singleton(ABC):
    Class: t.ClassVar[t.Type[t.Any]]
    def __init__(self):
        self.instance = self.Class()
    def __call__(self) -> Class:
        return self.instance

class IntSingleton(Singleton):
    Class = int

print(t.get_type_hints(IntSingleton.__call__))
```

Defining `Singleton` like this works, but the type variable doesn’t get resolved:

```py
from __future__ import annotations
from abc import ABC
import typing as t

Class = t.TypeVar("Class")

class Singleton(ABC):
    Class: t.ClassVar[t.Type[Class]]
    def __init__(self):
        self.instance = self.Class()
    def __call__(self) -> Class:
        return self.instance

class IntSingleton(Singleton):
    Class = int

print(t.get_type_hints(IntSingleton.__call__))
# {'return': ~Class}
```

I’d like to see `{'return': int}` here, but it doesn’t seem to be possible.

**Comment by JelleZijlstra** [comment]
I think you should make `Singleton` generic over `Class`, so `IntSingleton` can inherit from `Singleton[int]`.

It's hardly going to help with `get_type_hints()` though; that's runtime behavior that mypy doesn't control.

**Comment by flying-sheep** [comment]
> It's hardly going to help with `get_type_hints()` though; that's runtime behavior that mypy doesn't control.

True, that feature request should go to https://github.com/python/typing, right?

**Comment by AlexWaygood** [comment]
The bit of this that doesn't really work with mypy is the lack of support for generic `ClassVar`s. What would be nice would be if you could do this:

```python
from typing import TypeVar, Generic, ClassVar
from abc import ABCMeta

ClassT = TypeVar("ClassT")

class Singleton(Generic[ClassT], metaclass=ABCMeta):
    Class: ClassVar[type[ClassT]]

    def __init__(self) -> None:
        self.instance = self.Class()

    def __call__(self) -> ClassT:
        return self.instance

class IntSingleton(Singleton[int]):
    Class: ClassVar[type[int]] = int
```

But [that doesn't work](https://mypy-play.net/?mypy=latest&python=3.10&gist=782ffaef41e81dce2ddbd21ac50851da); instead you have to do [something hacky like this](https://mypy-play.net/?mypy=latest&python=3.10&gist=b20b102f21caf506372498bd3eac71c7):

```python
from typing import Generic, TypeVar, ClassVar, cast
from abc import ABCMeta

ClassT = TypeVar("ClassT")

class Singleton(Generic[ClassT], metaclass=ABCMeta):
    Class: ClassVar[type]

    def __init__(self) -> None:
        self.instance = cast(ClassT, self.Class())

    def __call__(self) -> ClassT:
        return self.instance

class IntSingleton(Singleton[int]):
    Class: ClassVar[type[int]] = int

reveal_type(IntSingleton()())  # revealed type is "builtins.int"
```

Nonetheless, I'm closing this issue: there are [other issues](https://github.com/python/mypy/issues/5144) that have more discussion about whether generic `ClassVar`s should be allowed, and discussion of runtime semantics such as `get_type_hints()` should go to the https://github.com/python/typing repo or the [typing-sig mailing list](https://mail.python.org/archives/list/typing-sig@python.org/).
