### ISSUE TITLE
Redefining variable to more specific type

### ISSUE THREAD

**Issue by wakemaster39** [python/mypy#8071]
This is a really contrived example, but my goal is to provide mypy with knowledge that the developer has of the code base to help specify the type more explicitly. 

```python
T = TypeVar("T")

@attrs(auto_attribs=True)
class TestClass(Generic[T]):
    a: T
    b: T


def func(var: TestClass[T]) -> None:
    reveal_type(var)
    if isinstance(var.a, int):
        var: TestClass[int]
        reveal_type(var)
```

The actual of mypy when run against the full file is:

```
t.py:14:17: note: Revealed type is 't.TestClass[T`-1]'
t.py:16:9: error: Name 'var' already defined on line 13
t.py:17:21: note: Revealed type is 't.TestClass[T`-1]'
```

What I would have expected the behaviour to be is:

```
t.py:14:17: note: Revealed type is 't.TestClass[T`-1]'
t.py:17:21: note: Revealed type is 't.TestClass[int]'
```

My basic thought process here is that based on my knowledge of the code base, I know at runtime that if this block of code is reached I also know the type that it is. While this example is specific to generics, it can be extended to protocols and unions as well. Any time you have the possibility of it not concrete type based on knowledge of the code base you can pass additional knowledge to mypy of the type of the variable.

I can work around this problem doing something like `var2 = cast(TestClass[int], var)` but it makes the code feel very awkward and adds extra mental overhead to make sure you are using the casted variable if you want mypy to ensure type checking.

**Comment by JukkaL** [comment]
A type annotation does not override type checking, i.e. it can't force a type that mypy would consider incompatible. In your example mypy can't verify that `TestClass[int]` is a safe type for `var`, so even if mypy would allow multiple variable annotations for a variable, the example would generate an error. 

It looks like a cast is your best bet, though I agree that it looks ugly.

**Comment by ilevkivskyi** [comment]
You can also use a constrained type variable as a workaround (although this may cause other issues), for example:
```python
T = TypeVar('T', int, str)

def func(var: TestClass[T]) -> None:
    reveal_type(var)
    if isinstance(var.a, int):
        reveal_type(var)  # mypy understands it can be only `TextClass[int]` here
```
Yet another alternative is to use a union type:
```python
def func(var: Union[TestClass[int], TestClass[str]]) -> None:
    reveal_type(var)
    if isinstance(var.a, int):
        reveal_type(var)  # again, mypy understands it can be only `TextClass[int]` here
```
