### ISSUE TITLE
dmypy start doesn't work when files is defined in mypy.ini

### ISSUE THREAD

**Issue by rggjan** [python/mypy#8088]
I have a mypy.ini with some default files to be checked like:

```
[mypy]
files = path/to/**/*.py
```

Running `mypy` with this config works fine. Running `dmypy run` also works fine.

However, running
`dmypy start`
gives the following error:
`dmypy: start/restart does not accept sources`

Wouldn't it make sense to just ignore the files configuration in this case? Or do I need a second mypy.ini with exactly the same content and just the `files` line deleted to be able to start mypy with it?

**Comment by JukkaL** [comment]
Yeah, this this clearly doesn't make much sense. Ignoring the files in configuration seems like the right thing to do.
