### ISSUE TITLE
Why is Tuple not a Mapping[int, Any]?

### ISSUE THREAD

**Issue by rggjan** [python/mypy#8089]
This code:

```
    a = ('a', 2, 3)

    def foo(b: Mapping[int, Any]) -> Any:
        return b[0]

    foo(a)
```

Gives this error:

```
error: Argument 1 to "foo" has incompatible type "Tuple[str, int, int]"; expected "Mapping[int, Any]"
```

even though Tuple supports all required methods from a Mapping (`__len__`, `__iter__`, `__getitem__`).

Why?

**Comment by JelleZijlstra** [comment]
`Mapping` also requires `keys`, `items`, and similar methods, and its `__contains__` means something different than `tuple.__contains__`.

For your use case, your best bet is to write a custom protocol with `def __getitem__(self, key: int) -> Any`.

**Comment by rggjan** [comment]
I see, thanks!
