### ISSUE TITLE
stubgen generates __init__ with return type Any for partially annotated input

### ISSUE THREAD

**Issue by perrinjerome** [python/mypy#8110]
From this code, which typechecks
 
```python
class X:
  def __init__(self, x: str):
     pass
```
`stubgen` generates:

```python
from typing import Any

class X:
  def __init__(self, x: str) -> Any: ...
```
for which `mypy` reports:
```
out/repro.pyi:4: error: The return type of "__init__" must be None
Found 1 error in 1 file (checked 1 source file)
```

`stubgen` already has knowledge of `__init__` return value special case, when converting `__init__` without type annotations, the return value is annotated as `None`, but when `__init__` is partially annotated and lacks a type annotation for returned value, it is annotated as `Any`.

I don't know how much this practice of omitting type annotation for return value of `__init__` is common, but I noticed that there also are cases in some examples from pep048 (
https://www.python.org/dev/peps/pep-0484/#forward-references ).

If that makes sense, it seems easy to annotate `__init__`  with `None` also in the case where there are partial type annotations. It would also prevent the weird behaviour of generating stubs which do not typecheck from code which typechecks.

The selection of return type is implemented here https://github.com/python/mypy/blob/bbb192d9aab3803cb172ce4674c026e20606fcb0/mypy/stubgen.py#L604-L613

we could move the special casing of `__init__` around to also use `None` in that case. Please let me know if this looks correct and if you want me to submit a pull request for this.

**Comment by msullivan** [comment]
That does look correct and I would love for you to submit a pull request for this!
