### ISSUE TITLE
MyPy not reporting issues on trivial code

### ISSUE THREAD

**Issue by Juanlu001** [python/mypy#8116]
I created this incorrect Python script:

```
$ cat main.py
$ cat main.py 
class Foo:
    def __init__(self):
        pass


def bar():
    return Foo(a="a")


if __name__ == "__main__":
    print(bar())
```

which gives this error:

```
$ python -V
Python 3.7.4
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    print(bar())
  File "main.py", line 7, in bar
    return Foo(a="a")
TypeError: __init__() got an unexpected keyword argument 'a'
```

but this is not detected by MyPy:

```
$ mypy --version
mypy 0.750
$ mypy main.py 
Success: no issues found in 1 source file
```

And also, no issues are detected on this correct, but still type-inconsistent script:

```
class Foo:
    def __init__(self, a: int):
        self.a = a


def bar():
    return Foo(a="a")


if __name__ == "__main__":
    print(bar())
```

After I started to write this issue I discovered that I should have enabled `--strict` though. Not sure how to change the mypy CLI to help the user discover it.

**Comment by ethanhs** [comment]
Code is not checked inside unannotated functions. You can use `--check-untyped-defs` to enable that. I'd recommend you read the getting started documentation https://mypy.readthedocs.io/en/latest/getting_started.html
