### ISSUE TITLE
Multiple types for variable-length Tuples

### ISSUE THREAD

**Issue by rggjan** [python/mypy#8126]
After https://github.com/python/mypy/issues/184 is supported, it would be great if variable-length Tuples would also work with multiple types.

For example, a Tuple with a string and zero or more ints inside could look like this:

`Tuple[str, int, ...]`

which currently can only be expressed as:

`Tuple[Any, ...]`

**Comment by msullivan** [comment]
While that could be useful in some cases, I think it's unlikely we're going to support that. In any case, a change to `Tuple` is a pretty fundamental change to the `typing` module, so I think it would need to be proposed at https://github.com/python/typing/ and would require a change to the PEP (or a new PEP?).

**Comment by rggjan** [comment]
👍 

See https://github.com/python/typing/issues/692
