### ISSUE TITLE
Callable returning non-None is not accepted where Callable returning None is expected

### ISSUE THREAD

**Issue by jolaf** [python/mypy#8127]
The following code:
```python3
from typing import Callable

def f(x: Callable[[], None]) -> None:
    x()

def g() -> int:
    print("OK")
    return 5

f(g)
```
produces the following output:
```python3
$ python3 Test.py
OK
$ mypy Test.py
Test.py:10: error: Argument 1 to "f" has incompatible type "Callable[[], int]"; expected "Callable[[], None]"
$ python3 --version
Python 3.6.9
$ mypy --version
mypy 0.750
```
It seems to me that wherever a `Callable` returning `None` is expected (meaning nobody is going to use its return value), a `Callable` returning anything at all should be accepted.

**Comment by msullivan** [comment]
I'm tempted to say this is intended behavior and shouldn't change. There's documentary purpose in a None return -- it is a function called solely for side effects, and the callable could return `object` if it wants to permit this.

I'm also wary about changing something is fundamental as the subtyping rule for callables. (Though it would probably be pretty easy.)

I could easily imagine myself being on the other side of this argument, though, so I'm curious what @ilevkivskyi and @JukkaL think.

(mypyc used to raise a runtime `TypeError` if a function that was expected to return `None` returned something else. Maybe the fact that I changed that should be an argument against my position here.)

**Comment by jolaf** [comment]
I agree that function declared to return `None` and trying to return something else should be reported - as it indicates a potential error in either function code or annotation. And the same goes for inherited methods - if in superclass method returned `None` and subclass method tries to return something else, it's also weird.

But PASSING a function returning something, as argument somewhere where function returning nothing is expected (like most callbacks) seems pretty safe and done rather often.

**Comment by Evpok** [comment]
Why not just type it `Callable[[], Any]` in that case ?

**Comment by ilevkivskyi** [comment]
I don't really like arbitrary special-casing, we already have a name for "don't care", and this name is `Any`, so essentially +1 to what @Evpok says.

**Comment by msullivan** [comment]
OK, I'm going to go with my original inclination and say intended behavior. Thanks for the suggestion!
