### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by akanowhere** [python/mypy#8131]
from time import sleep
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
import socket
#import csv

message_text='Ola essa é uma mensagem automatizada de Whats App.' # message
no_of_message = 1 # no. of time
moblie_no_list = [5551981440050, 555182073305] # list of phone number
#moblie_no_list= open('entrada.csv', 'r')

def element_presence(by,xpath,time):
    element_present = EC.presence_of_element_located((By.XPATH, xpath))
    WebDriverWait(driver, time).until(element_present)

def is_connected():
    try:
        # connect to the host -- tells us if the host is actually
        # reachable
        socket.create_connection(("www.google.com", 80))
        return True
    except :
        is_connected()
driver = webdriver.Chrome(executable_path="D:\Programas\Aulas\scripts\Projetos\whatsautomatico\chromedriver.exe")
driver.get("http://web.whatsapp.com")
sleep(10) #wait time to scan the code in second

def send_whatsapp_msg(phone_no,text):
    driver.get("https://web.whatsapp.com/send?phone={}&source=&data=#".format(phone_no))
    try:
        #driver.switch_to_alert().accept()#alterar a linha ou comenta#  
        driver.switch_to_alert.accept()
        #driver.switch_to_alert().accept()
    except Exception as e:
        pass

    try:
        element_presence(By.XPATH,'//*[@id="main"]/footer/div[1]/div[2]/div/div[2]',30)
        txt_box=driver.find_element(By.XPATH , '//*[@id="main"]/footer/div[1]/div[2]/div/div[2]')
        global no_of_message
        for x in range(no_of_message):
            txt_box.send_keys(text)
            txt_box.send_keys("\n")

    except Exception as e:
        print("invailid phone no :"+str(phone_no))
for moblie_no in moblie_no_list:
    try:
        send_whatsapp_msg(moblie_no, message_text)

    except Exception as e:
        sleep(10)
        is_connected()

**Comment by akanowhere** [comment]
I need help in this code the list in line 13 only read the first phone number and in the second occuried an error.

Please help me

**Comment by ethanhs** [comment]
@akanowhere this issue tracker is not for general Python help.

**Comment by ponsoniro** [comment]
in 2021/07/09 the projetc stoped in the part in typing in the whatsapp.

  You could help me.
tks
