### ISSUE TITLE
Problem in tracking variable definition in condition

### ISSUE THREAD

**Issue by h8hawk** [python/mypy#8132]
mypy validate this code without any issue :

```
def foo(b: bool) -> int:
    if b: 
        a = 9
    return a
```

**Comment by msullivan** [comment]
mypy doesn't really track variable definedness, which is a known bug. I am certain that this must be filed already but I can't find it so I guess I'll triage this one for now!

**Comment by hauntsaninja** [comment]
Duplicate of #2400
