### ISSUE TITLE
MyPy encounters fatal error when typechecking subclasses of dataclasses

### ISSUE THREAD

**Issue by parkerhancock** [python/mypy#8138]
This is a bug encountered when attempting to typecheck dataclasses that inherit from other dataclasses. Code to reproduce:

Configuration:

- macOS Catalina v.10.15.2
- Python 3.7.4
- MyPy 0.750

Python file (mypy_bug.py):
```python
from dataclasses import dataclass

@dataclass
class BaseClass():
    name: str
    attribute: int

@dataclass
class ChildClass(BaseClass):
    birthdate: str
```

Syntax is correct, you can instantiate both classes just fine, and create instances of both

```console
Python 3.7.4 (default, Aug  5 2019, 17:06:28) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mypy_bug import BaseClass, ChildClass
>>> BaseClass('Parker', 'some attribute')
BaseClass(name='Parker', attribute='some attribute')
>>> ChildClass('Parker', 'some attribute', '1900-01-01')
ChildClass(name='Parker', attribute='some attribute', birthdate='1900-01-01')
```

MyPy invocation:
```bash
mypy --verbose mypy_bug.py
```

Output:
```console
LOG:  Could not load plugins snapshot: @plugins_snapshot.json

LOG:  Mypy Version:           0.750
LOG:  Config File:            mypy.ini
LOG:  Configured Executable:  /{omitted}/bin/python3
LOG:  Current Executable:     /{omitted}/bin/python3
LOG:  Cache Dir:              .mypy_cache
LOG:  Compiled:               True
LOG:  Could not load cache for mypy_bug: mypy_bug.meta.json
LOG:  Metadata not found for mypy_bug
LOG:  Parsing mypy_bug.py (mypy_bug)
LOG:  Bailing due to parse errors
LOG:  Build finished in 0.006 seconds with 0 modules, and 1 errors
mypy_bug.py:5: error: invalid syntax
Found 1 error in 1 file (checked 1 source file)
```
**Expected result:** valid typecheck, no errors

**Actual result:** fatal error that stops all further typechecking

Additionally, this error is non-skippable. Identical output results from:

```python
from dataclasses import dataclass # type: ignore

@dataclass # type: ignore
class BaseClass(): # type: ignore
    name: str # type: ignore
    attribute: int # type: ignore

@dataclass # type: ignore
class ChildClass(BaseClass): # type: ignore
    birthdate: str # type: ignore
```

**Comment by msullivan** [comment]
I can't reproduce this error. I suspect that you are typechecking in python 2 mode and are getting an error on the variable annotations? Check your mypy.ini.

**Comment by msullivan** [comment]
(Closed because I'm like 90% sure about this, but reopen if I'm wrong)

**Comment by parkerhancock** [comment]
Thanks for the quick response! You were right, my mypy.ini was set to Python **2.7** rather than 3.7.  

I copied it from the documentation [here](https://mypy.readthedocs.io/en/latest/config_file.html), and just didn't see the major version number. My bad.

Keep up the good work!

**Comment by CoolCat467** [comment]
Not causing a crash but I'm curious, what is `LOG:  Could not load plugins snapshot: @plugins_snapshot.json` talking about? I was noticing this in a `-v` run of my own and wanted to see if it was an issue.
