### ISSUE TITLE
Weird behavior with stubs and relative imports

### ISSUE THREAD

**Issue by ZeeD** [python/mypy#8142]
I have this "layout" of my sources and the stub of an external library
```
$ tree ..
..
├── src
│   ├── mypy.ini
│   └── use_foo.py
└── stubs
    └── foo
        ├── bar.pyi
        └── __init__.pyi

3 directories, 4 files
```

with the following content:

```
$ cat mypy.ini 
[mypy]
mypy_path = ../stubs
```
```
$ cat use_foo.py 
import foo

baz = foo.Baz()
quux = foo.qux('hello')
```
```
$ cat ../stubs/foo/bar.pyi 
class Baz:
    ...

def qux(int) -> str:
    ...
```
```
$ cat ../stubs/foo/__init__.pyi 
from .bar import Baz, qux
```

mypy doesn't like the stubs:

```
$ mypy --config-file mypy.ini use_foo.py 
use_foo.py:3: error: Module has no attribute "Baz"
use_foo.py:4: error: Module has no attribute "qux"
```

but... shouldn't the `from .bar import ...` inside the `../stubs/foo/__init__.pyi ` expose the names?

I'm using `mypy 0.720`

btw: the stub code has been generated automatically by `stub_gen` on `flask_admin` library

**Comment by msullivan** [comment]
Imports in stubs don't implicitly reexport their names.

To reexport the names, you need to explicitly do `from .bar import Baz as Baz, qux as qux`

(This is to make it easy to avoid implicitly reexporting lots of stuff)

**Comment by ZeeD** [comment]
Hi
as I said, this kind of import has been automatically generated by `stub_gen`. Shouldn't it create a "correct" import?

**Comment by JelleZijlstra** [comment]
That's a fair point. What did your `__init__.py` look like?

**Comment by ZeeD** [comment]
I have run `stub_gen` on the version `1.5.3` of `Flask-Admin`.
The source code should be available on https://github.com/flask-admin/flask-admin/blob/v1.5.3/flask_admin/__init__.py
