### ISSUE TITLE
Protocol 'composition' doesn't work?

### ISSUE THREAD

**Issue by ze-phyr-us** [python/mypy#8143]
* Are you reporting a bug, or opening a feature request? _bug, probably_
* Please insert below the code you are checking with mypy
```python
from typing_extensions import Protocol

class ChildProtocol(Protocol):
    def method(self) -> int: ...

class ParentProtocol(Protocol):
    child: ChildProtocol


class Child:
    def method(self) -> int:
        return 42

class Parent:
    def __init__(self) -> None:
        self.child = Child()


def f(x: ParentProtocol) -> None:
    x.child.method()


f(Parent())
```

* What is the actual behavior/output?
```
test.py:24: error: Argument 1 to "f" has incompatible type "Parent"; expected "ParentProtocol"
test.py:24: note: Following member(s) of "Parent" have conflicts:
test.py:24: note:     child: expected "ChildProtocol", got "Child"
Found 1 error in 1 file (checked 1 source file)
```
* What is the behavior/output you expect?

_As `Child` implements `ChildProtocol` and `Parent` implements `ParentProtocol` I'd expect `f` to accept the actual `Parent`-`Child` implementation.

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

Python 3.7 & 3.8, mypy 0.750 & master all give the same result.

* What are the mypy flags you are using? (For example --strict-optional)

No flags.

**Comment by msullivan** [comment]
I believe the issue here is that because attributes are mutable they need to match exactly. See https://www.python.org/dev/peps/pep-0544/#covariant-subtyping-of-mutable-attributes.

If it is read only (at least as far as uses through the protocol are concerned), you could declare it as
```
    @property
    def child(self) -> ChildProtocol: ...
```

**Comment by ze-phyr-us** [comment]
Thank you! `@property` works, even if it feels like a workaround :)
