### ISSUE TITLE
Dictionaries not accepted for implicit cast to TypedDict Union

### ISSUE THREAD

**Issue by fluggo** [python/mypy#8156]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request? **Bug**

```python
from typing import TypedDict, Literal, Union, Mapping, Any, cast

A = TypedDict('A', {'@type': Literal['a-type'], 'a': str})
B = TypedDict('B', {'@type': Literal['b-type'], 'b': int})

bad_cast: Union[A, B] = {'@type': 'a-type', 'a': 'Test'}
good_cast_1: Union[A, B] = cast(Union[A, B], {'@type': 'a-type', 'a': 'Test'})
good_cast_2: Union[A, B] = cast(A, {'@type': 'a-type', 'a': 'Test'})
```

* What is the actual behavior/output?

```test_mypy_discriminate.py:6:25: error: Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "Union[A, B]")```

* What is the behavior/output you expect?

Since the given type matches one of the types in the Union, it should be accepted.

* What are the versions of mypy and Python you are using? **Python 3.8, mypy 0.750**
* Do you see the same issue after installing mypy from Git master? **Don't know how to do that**

**Comment by ilevkivskyi** [comment]
Yeah, I think this is a bug. The TypedDict return context is special-cased, but as it often happens special-casing doesn't take into account union types.

**Comment by PattenR** [comment]
I had a look into this and given a suggestion as to how the special-case could be improved to correctly handle this case. 

It's not totally clear how to handle this so I'd be interested to see any other suggestions anyone might have!
