### ISSUE TITLE
Correctly initialize VT100 parsing on Windows with dmypy

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#8164]
I just installed the latest release and it seems that dmypy is not changing the correct settings to have the Windows terminal parse color output.
![image](https://user-images.githubusercontent.com/9504279/71036176-fe01b580-20d1-11ea-97d0-69c486eecc57.png)

Note this is *not* a regression. I can take a look and work on a fix now.

**Comment by ethanhs** [comment]
Ah hm, this is likely due to the formatting being done in the server, so it isn't setting the terminal up correctly in the client.

Fixing this would require moving the formatting to the client.

**Comment by ilevkivskyi** [comment]
Somehow I don't have this issue. I see nice color output from daemon, I however added some key in the registry (somewhere in HKCU IIRC).

**Comment by ethanhs** [comment]
Hm, then perhaps my diagnosis is wrong, I was pretty sure I had tested the daemon so I was surprised it didn't work. I'll try to dig around a bit more.

@ilevkivkyi could you tell me what the output of `ver` at the command line is? Thanks!

**Comment by ilevkivskyi** [comment]
10.0.18363.535

**Comment by ethanhs** [comment]
I don't think this is an issue in mypy, maybe it was a bug in Windows 🤷‍♂️
