### ISSUE TITLE
mypy 0.760 source tarball missing on pypi

### ISSUE THREAD

**Issue by Foxboron** [python/mypy#8172]
Hi,

Seems like the source tarball for `mypy` wasn't uploaded to pypi. It exists for previous versions.

See https://pypi.org/project/mypy/0.750/#files
versus https://pypi.org/project/mypy/0.760/#files

**Comment by ilevkivskyi** [comment]
@JukkaL is this intentional?

**Comment by JukkaL** [comment]
No. The install script failed the first time I ran it, and it looks like not everything was uploaded correctly. Maybe we should make a 0.761 release with the only difference being the new version number and a full set of files uploaded.

**Comment by ilevkivskyi** [comment]
@Foxboron what is the scale of trouble this causes? If it is non-trivial, then I would say yes, it is better to have a 0.761 release.

**Comment by Foxboron** [comment]
I'm the `mypy` package maintainer for Arch Linux. This broke the current package file when updating the version. This isn't a big problem, but sometimes the pypi and github source tarballs have different content. So I can check that first if it helps to determine a `0.761` release or not.

**Comment by JukkaL** [comment]
I think that we should do the 0.761 release since it will be hard to predict the impact of the missing tarball, and making another release doesn't take much effort. I can do it tomorrow.

**Comment by Foxboron** [comment]
Ack, thanks!

**Comment by tobypeterson** [comment]
The pypi and github tarballs for 0.750 are significantly different. Worth filing a separate issue? (I'm in the same boat here, MacPorts package depends on pypi tarball.)

**Comment by Foxboron** [comment]
I believe it's the Manifest file which isn't read by github, but read when creating the source tarball for pypi. I see `typeshed` is included in pypi, but not the github tarball.

**Comment by JukkaL** [comment]
I just uploaded 0.761 to PyPI. Can somebody verify that it works as expected now?

The github tarball isn't really usable.

**Comment by Foxboron** [comment]
Seems like everything is working on my end :) Thanks for solving this!
