### ISSUE TITLE
Debugging `Incompatible types`

### ISSUE THREAD

**Issue by rafalp** [python/mypy#8173]
**Are you reporting a bug, or opening a feature request?**

Bug or feature request

**Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.**

`types.py`:

```python
class AuthError(Exception):
    pass


class Error(TypedDict):
    loc: Sequence[Union[int, str]]
    msg: str
    type: str


class ErrorsList(List[Error]):
    def __add__(self, other_list: Sequence[Error]) -> "ErrorsList":
        ...

    def add_root_error(
        self, error: Union[AuthError, TypeError, ValueError]
    ):
        ...

    def add_error(
        self,
        location: Union[str, Sequence[str]],
        error: Union[AuthError, TypeError, ValueError],
    ):
        ...
```

`validation/errorslist.py`:

```python
class ErrorsList(List[Error]):
    ROOT_LOCATION = DEFAULT_ROOT_LOCATION

    def __add__(self, other_list: Sequence[Error]) -> "ErrorsList":
        errors_list = list(self)
        for error in other_list:
            if error not in errors_list:
                errors_list.append(error)
        return ErrorsList(errors_list)

    def add_root_error(
        self, error: Union[AuthError, TypeError, ValueError]
    ):
        self.add_error("__root__", error)

    def add_error(
        self,
        location: Union[str, Sequence[str]],
        error: Union[AuthError, TypeError, ValueError],
    ):
        error_dict = get_error_dict(error, location)
        if error_dict not in self:  # pylint: disable=unsupported-membership-test
            super().append(error_dict)

    def get_errors_locations(self) -> List[str]:
        return [
            ".".join(map(str, e["loc"]))
            for e in self  # pylint: disable=not-an-iterable
        ]

    def get_errors_types(self) -> List[str]:
        return [e["type"] for e in self]  # pylint: disable=not-an-iterable
```

**What is the actual behavior/output?**

```
 error: Incompatible types in assignment (expression has type "misago.types.ErrorsList", variable has type "misago.validation.errorslist.ErrorsList")
```

*What is the behavior/output you expect?**

Be compatibile, or tell me which attributes/behaviours different between the two.

**What are the versions of mypy and Python you are using?**

`Mypy==0.760`, `Python==3.8.0`

**What are the mypy flags you are using? (For example --strict-optional)**

`--ignore-missing-importss`

**Comment by JelleZijlstra** [comment]
Mypy's type system is nominal by default, which means that two types that are defined separately are not compatible, even if they have the same name (and even if they're otherwise identical). I don't think this error message can really be improved much without making it a lot longer.

**Comment by rafalp** [comment]
Thanks for reaching back to me so quick, @JelleZijlstra!

I've moved my code around to create single `ErrorsList` type, which resolved my problem. This error originally caught me by surprise because Mypy reported no issues about my codebase until I've committed more code to it (cache key/checksum collision?).

>  I don't think this error message can really be improved much without making it a lot longer.

I understand this, but I feel that currently only way in which such knowledge is available to the library users is by means of creating issue and waiting for one of contributors to explain why mypy works the way it works. Perhaps Mypy should offer error code that could be looked up somewhere?

**Comment by ilevkivskyi** [comment]
> I feel that currently only way in which such knowledge is available to the library users is by means of creating issue and waiting for one of contributors to explain why mypy works the way it works

Another option is to read the docs, for example https://mypy.readthedocs.io/en/latest/duck_type_compatibility.html
> Perhaps Mypy should offer error code that could be looked up somewhere?

Mypy already will show error codes if you use `--show-error-codes`, they are listed in the docs, for example https://mypy.readthedocs.io/en/latest/error_code_list.html
