### ISSUE TITLE
Assigning new function to a function variable requires identically named arguments

### ISSUE THREAD

**Issue by bluebird75** [python/mypy#8176]
A short example shall speak for itself :

```
def toto(v: int) -> None: pass

def titi(u: int) -> None: pass

def tata(v: int) -> None: pass

toto = titi  # mypy complains

toto = tata  # ok with mypy because argements are named identically
```

What does mypy say about this : 

```
>mypy --version 
mypy 0.760

>mypy qproc.py
qproc.py:18: error: Incompatible types in assignment (expression has type "Callable[[Arg(int, 'u')], None]", variable has type "Callable[[Arg(int, 'v')], None]")
Found 1 error in 1 file (checked 1 source file)
```

The issue is that when assigning a function to a variable containing another function, mypy complains if the arguments of the new function are not named identically as the old function.

Practically, it happened to me when using sys.excepthook.

**Comment by ilevkivskyi** [comment]
I don't see what is the problem here, this code is actually unsafe if you call `toto(v=1)`
 after the first assignment. If you don't want the argument name to be part of the callable type use a new variable with an explicit `Callable[[int], None]` annotation.

**Comment by bluebird75** [comment]
I did not think of that use case. Not a bug indeed although a bit surprising the first time you encounter it.
