### ISSUE TITLE
overriding variable with property: `error Signature incompatible with supertype`

### ISSUE THREAD

**Issue by Kamik423** [python/mypy#8185]
```python
class A:
    foo: str = "foo"

class B(A):
    @property
    def foo(self) -> str:
        return "bar"

print(B().foo) # "bar"
```

When overriding a variable with a property I get the error:

```
mypy: error
Signature of "foo" incompatible with supertype "A"
```

The code executes fine, though.

```
$ mypy --version
mypy 0.750
$ python3 --version
Python 3.7.5
```

The only idea I have is, that this overrides a variable which is both an instance variable and a class variable with one that is instance only.

**Comment by ilevkivskyi** [comment]
This code is actually unsafe and mypy is right, you can't override a writeable attribute with a read-only one.
