### ISSUE TITLE
Unreachable Warning Code

### ISSUE THREAD

**Issue by llchan** [python/mypy#8190]
There are sometimes cases where I'd like deliberately put something in a statically-unreachable section---maybe some asserts, maybe some debug info, etc.---in case it does hit that case at runtime.  I currently silence them with a `# type: ignore[misc]` which isn't particularly informative to someone reading the code.  Could we give `unreachable` its own dedicated error/warning code?

EDIT: just so it's clear, I do want to keep the warning on to detect legitimate issues.

**Comment by ilevkivskyi** [comment]
Sure, PR is welcome!
