### ISSUE TITLE
Support keywords/special char in field name in TypedDict class syntax

### ISSUE THREAD

**Issue by szhangpitt** [python/mypy#8202]
Please provide more information to help us understand the issue:

* Opening **a feature request**?
* Please insert below the code you are checking with mypy,

```py
class Bond(TypedDict):
    yield: float
    ^ error: invalid syntax

Bond = TypedDict('Bond', { 'yield': float })
```

* What is the actual behavior/output?

With class syntax, mypy reports error: invalid syntax

* What is the behavior/output you expect?

There should be some way defining field names with keywords or special characters (e.g. dot `.`), as you could with `TypedDict(...)` syntax

* What are the versions of mypy and Python you are using?

mypy 0.740 Python 3.8.0

* What are the mypy flags you are using? (For example --strict-optional)

None 

* If mypy crashed with a traceback, please paste
  the full traceback below.

**Comment by JelleZijlstra** [comment]
This is a Python syntax error, so there's not much mypy can do about it. Your options are to either use the call-based syntax or rename the field to `yield_` or something.
