### ISSUE TITLE
TypedDict union not narrowed on literal match

### ISSUE THREAD

**Issue by fluggo** [python/mypy#8204]
* Are you reporting a bug, or opening a feature request? **Bug**
* Please insert below the code you are checking with mypy, or a mock-up repro if the source is private. We would appreciate if you try to simplify your case to a minimal repro.

```python
from typing import Union, TypedDict, Literal, cast

A = TypedDict('A', {'@type': Literal['A'], 'stuff': str})
B = TypedDict('B', {'@type': Literal['B'], 'thing': int})

data: Union[A, B] = cast(A, {'@type': 'A', 'stuff': 'horp'})

assert data['@type'] == 'A'
assert data['stuff'] == 'horp'
```

* What is the actual behavior/output?

mypy flags the second assert: `TypedDict "B" has no key 'stuff'`

* What is the behavior/output you expect?

The first assert should narrow the Union[A, B] to just A.

* What are the versions of mypy and Python you are using? **mypy 0.761, Python 3.8**
* Do you see the same issue after installing mypy from Git master? **Don't know how to do that**

**Comment by JukkaL** [comment]
An explicit type annotation overrides the inferred type. Thus the type of `data` is `Union[A, B]`, not `A`. You can work around this by assigning after the declaration, which will narrow down the type:

```py
from typing import Union, TypedDict, Literal, cast

A = TypedDict('A', {'@type': Literal['A'], 'stuff': str})
B = TypedDict('B', {'@type': Literal['B'], 'thing': int})

data: Union[A, B]
data = cast(A, {'@type': 'A', 'stuff': 'horp'})  # <-- separate assignment narrows down to 'A'

assert data['@type'] == 'A'
assert data['stuff'] == 'horp'  # OK
```
