### ISSUE TITLE
Allow plugins to add symbols to namespaces other than current one

### ISSUE THREAD

**Issue by mkurnikov** [python/mypy#8214]
In django-stubs, we're creating a lot of classes and methods dynamically. That's a lot of `add_symbol_table_node()`. 
But symbol table to use it for is fixed in the 
```
names = self.current_symbol_table(escape_comprehensions=escape_comprehensions)
```
Only place in the method that actually uses current semanal context is if-condition
```
name not in self.missing_names and '*' not in self.missing_names
```

Possibly refs https://github.com/python/mypy/issues/6382

**Comment by mkurnikov** [comment]
I figured out that I can just use nested classes for cases like that.

**Comment by camertron** [comment]
@mkurnikov can you expand a bit on what you mean? I don't understand how nesting classes can help with this.

**Comment by mkurnikov** [comment]
I can't find that piece of code. IIRC, I've just added a symbol table node inside the class namespace, like
```
class User:
    class UserManager: 
        pass
```
instead of 
```
class User:
    pass
class UserManager: 
    pass
```
to avoid conflicts.

**Comment by camertron** [comment]
Ah ok that makes sense, thanks :) For what it's worth, I was able to add a class to the current module by doing this:

```python
def class_hook(ctx: ClassDefContext) -> None:
    ctx.api.cur_mod_node.names[class_name] = sym_node
```
