### ISSUE TITLE
f string syntax error

### ISSUE THREAD

**Issue by akeidleh** [python/mypy#8227]
I am new to python and I am having f strings syntax error. I tried, followed the the example from the book and it is not working. please help me fix this.

Thank you
![image](https://user-images.githubusercontent.com/59420785/71645764-b9197980-2ca2-11ea-9aca-8f26eb19cf46.png)

**Comment by TH3CHARLie** [comment]
This is mypy's issue tracker and it is not served for general Python issues. However, for your case, I believe changing the 4th line into
```python
full_name = f"{first_name} {last_name}" # remove space between 'f' and quotes
```
would help

@ethanhs Would you mind close this?
