### ISSUE TITLE
Top-level assert does not skip 'type: ignore' comments

### ISSUE THREAD

**Issue by hashstat** [python/mypy#8234]
When using mypy with the _--warn-unused-ignore_ option, `type: ignore` comments are still analyzed, and possibly reported, when occurring after `assert sys.platform == ...` statements.

Take the following module as an example:

```python
# test.py

import sys

assert sys.platform == "win32"

class Foo:
    pass

foo = Foo()
foo.bar = 1  # type: ignore[attr-defined]
```

Running `mypy --warn-unused-ignore --platform win32 test.py` finds no errors, as expected. However, `mypy --warn-unused-ignore --platform linux test.py` reports the following error:

```
test.py:11: error: unused 'type: ignore' comment
Found 1 error in 1 file (checked 1 source file)
```

I would expect (by reading the documentation) that the assert should cause the rest of the file to be skipped, including `type: ignore` comments, since they also are likely platform-specific. The same issue likely occurs for `sys.version_info` asserts as well.

I am experiencing the issue with Python 3.7.5 and mypy 0.750, 0.760, 0.761, and master.

**Comment by msullivan** [comment]
I would agree that this is a bug although I suspect it is might be more painful to fix than it is worth, since the unused type: ignore check is pretty divorced from everything else (and just looks at the errors reported).

It might be worth disabling this for your platform specific files, which you can do with `# mypy: no-warn-unused-ignore` at the top of the file

**Comment by hashstat** [comment]
@msullivan, I had worked around it by adding the following to mypy.ini:
```ini
[mypy-mypackage.exclusive.*]
# Work around mypy bug #8234: https://github.com/python/mypy/issues/8234
warn_unused_ignores = False
```

But I like your idea better as it's more targeted, but gave me an error at first until I added the missing 's' in ignores. Thanks for the reminder of the inline mypy configuration. This is the first time I've had to use it.

**Comment by hauntsaninja** [comment]
See https://github.com/python/mypy/issues/8823#issuecomment-1556288015
