### ISSUE TITLE
Is there a way to tell mypy to check a class implements a Protocol without inheriting from it?

### ISSUE THREAD

**Issue by danballance** [python/mypy#8235]
Hi, this is just a question. I couldn't see a forum or email list. I hope this is the right place to ask. I have spent some searching and reading docs etc but couldn't see an answer.

I love the new user-defined Protocols and structural subtyping and this is what I'd like to achieve:

1. I define my custom interface / protocol
2. I create one or more implementations of my protocol without inheriting from the protocol I just created
3. I'd still like a way to nudge mypy to check that my implementation actually meets the requirements of the protocol I have implemented

It's the 3rd step I am struggling with. Since we have this lovely structural subtyping feature available, it seems a shame to have to then inherit from the protocol in order to check the interface is implemented correctly.

Is the above possible? Am I overthinking this? I'm not overly keen on multiple inheritance and this is where I end up if each of my class has to inherit from the protocols it implements, plus any "real" inheritance they are required to do from a parent class.

If there's an answer to the above problem I'd love to hear it. I'm also interested to get general feedback on my approach. Thanks in advance.

**Comment by Michael0x2a** [comment]
One trick you could do is to just try assigning your new class to a throwaway variable with the protocol type, like so:

```python
class SupportsBlah(Protocol):
    # ...snip...

class Foobar:
    # ...snip...

_supports_blah: SupportsBlah = Foobar()
```

Mypy will then report an error on the last line if your class doesn't happen to support the declared protocol.

You could also play around with using `typing.TYPE_CHECKING` if you don't actually want to instantiate anything within the module scope.

Alternatively, you could try writing a unit test for `Foobar` that tries passing it into some function that expects a `SupportsBar` or something. This would help keep your code looking clean -- with the downside that making a test serve dual-purpose as both a runtime and type check time check is maybe a little confusing/unintuitive.

**Comment by danballance** [comment]
Thanks @Michael0x2a for your excellent suggestions.

I think I did see something similar to your first suggestion in one of the examples. I did wonder if that was purely for demo code or a more serious suggestion for checking the protocol implementation. I'll give this a try - perhaps together with typing.TYPE_CHECKING.

The unit test idea seems pretty good as well. (I kind of wish I'd thought of that!)

I really appreciate you taking the time to reply to me - that's super-helpful advice.

**Comment by adriangb** [comment]
Here's another way that I accidentally came across:

```python
class SupportsBlah(Protocol):
    def foo(self) -> int:
        ...

class Foobar:
    def _(self) -> SupportsBlah:
        return self
```

**Comment by bersbersbers** [comment]
> Here's another way that I accidentally came across:

I haven't tried this one just now, but I think I remember that checks like this do not check if the class can actually be instantiated. Especially when `Foobar` inherits from `SupportsBlah`, an assignment `x : SupportBlah = foobar` is valid by definition, and then the important check to is to include `Foobar()` as well. This is a bit less clean when `Foobar.__init__` expects parameters - for that, inspired by https://github.com/python/mypy/issues/15243#issuecomment-1547225481, I use constructs such as
```python
def check(parm1: Parm1, parm2: Parm2):
    _ : SupportsBlah = Foobar(parm1, parm2)
```

**Comment by bpshaver** [comment]
I like 

```python
from typing import TYPE_CHECKING

...

if TYPE_CHECKING:
    _: type[SupportsBlah] = Foobar
```

if `if TYPE_CHECKING` block is really just for readability since the type isn't instantiated.
