### ISSUE TITLE
Assigment of more specialized Dict fails for a Dict with a Union[int, str] key.

### ISSUE THREAD

**Issue by omry** [python/mypy#8237]
This could be a bug, or some fundamental misunderstanding I have.

* Are you reporting a bug, or opening a feature request?
Bug

* Please insert below the code you are checking with mypy

```python
from typing import Dict, Union

foo: Dict[Union[int, str], str] = {}
bar : Dict[str, str] = {}

#  error: Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "Dict[Union[int, str], str]")
foo = bar
```

* What is the actual behavior/output?
Mypy reports the assignment `foo = bar` as an error

* What is the behavior/output you expect?
I am expecting this assignment to be legal because any key in bar is a legal key in foo.

* What are the versions of mypy and Python you are using?
```
mypy 0.761
Python 3.6.9 :: Anaconda, Inc.
```
  Do you see the same issue after installing mypy from Git master?
Yes.

* What are the mypy flags you are using? (For example --strict-optional)
None

**Comment by JelleZijlstra** [comment]
See https://mypy.readthedocs.io/en/latest/common_issues.html#invariance-vs-covariance.

**Comment by omry** [comment]
Thanks.
For anyone coming later, In the term of the question, the problem is as follows:

```python

foo: Dict[Union[int, str], str] = {}
bar : Dict[str, str] = {}

#  error: Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "Dict[Union[int, str], str]")
foo = bar
```

After the assignment foo and bar points to the same object.
bar is declared as Dict[str, str], and it's now possible to add an int key to the object through the foo reference, violating the type declared for bar.

**Comment by layday** [comment]
Also a union is defined as a supertype of its members and dicts are invariant.
