### ISSUE TITLE
Issue implementing a Protocol interface for collections.Mapping

### ISSUE THREAD

**Issue by danballance** [python/mypy#8239]
* Are you reporting a bug, or opening a feature request?
This is potentially a bug.

* Please insert below the code you are checking with mypy
```
from collections import Mapping
from typing import Sized, Iterable, Container, Protocol


class MappingProtocol(Sized, Iterable, Container, Protocol):
    def __getitem__(self, key):
        ...

    def __eq__(self, other):
        ...

    def get(self, key, default=None):
        ...

    def keys(self):
        ...

    def items(self):
        ...

    def values(self):
        ...


class CollectionMap(Mapping, MappingProtocol):
    def __len__(self):
        pass

    def __iter__(self):
        pass

    def __getitem__(self, key):
        pass
```

* What is the actual behavior/output?
```
> mypy example.py
example.py:25: error: Definition of "get" in base class "Mapping" is incompatible with definition in base class "MappingProtocol"
Found 1 error in 1 file (checked 1 source file)
```
* What is the behavior/output you expect?
I expect mypy to pass the checks.

* What are the versions of mypy and Python you are using? Do you see the same issue after installing mypy from Git master?
The example above has been run from master just now:
mypy 0.770+dev.cdd91ba819646b0138b05a8e9180faba4ef0ff92
Python version is 3.7.4.

* What are the mypy flags you are using? (For example --strict-optional)
I'm not using any flags or settings - just the defaults.

* What am I trying to achieve?
In my project I have a custom class that behaves like a Mapping container with additional features. I want to create a Protocol for this implementation. So for example, I want the type hinting in my IDE to know that `object.get("param", {})` is valid.  Since I don't believe that one already exists, I am trying to create a Protocol for the Mapping abstract base class in the collections package (that my implementation inherits from). (Please do correct me if I am wrong on this - it would be much easier if I could just import a Mapping protocol from the typing package)

What is odd with the above code is if I change MappingProtocol.get as below, and drop the additional default parameter, then the checks pass:
```
from collections import Mapping
from typing import Sized, Iterable, Container, Protocol


class MappingProtocol(Sized, Iterable, Container, Protocol):
    def __getitem__(self, key):
        ...

    def __eq__(self, other):
        ...

    def get(self, key):
        ...

    def keys(self):
        ...

    def items(self):
        ...

    def values(self):
        ...


class CollectionMap(Mapping, MappingProtocol):
    def __len__(self):
        pass

    def __iter__(self):
        pass

    def __getitem__(self, key):
        pass
```

```
mypy example.py
Success: no issues found in 1 source file
```

But this can't be correct, surely? Dictionaries allow default values to be passed to `get()` and this matches the function definition below from `_collections_abc.py`:
```
class Mapping(Collection):
    # snip
    def get(self, key, default=None):
        'D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.'
        try:
            return self[key]
        except KeyError:
            return default
```

Is this is bug? Or alternatively, what am I misunderstanding? Any help or advice greatly appreciated :)

**Comment by JelleZijlstra** [comment]
The definition of Mapping in `typing.pyi` (https://github.com/python/typeshed/blob/master/stdlib/3/typing.pyi#L400) has an overload for `get`. Presumably mypy doesn't think the overload is compatible with your implementation.

Your best workaround would be to put a similar overload in your protocol.

**Comment by danballance** [comment]
Thanks so much for pointing me towards the typeshed definition @JelleZijlstra. I am pretty new to typeshed. With this pointer I should be able to get my code working. I'll leave this issue open for now and post my working code this weekend once I have an answer - just in case anyone else stumbles across a similar problem in the future.

**Comment by danballance** [comment]
Okay so my "solution" was simply to copy the signature from the typing.pyi file pointed to above. Once I did this my custom mapping objects in my IDE (PyCharm) started to get seen as mapping objects with get() etc.

```
class MappingProtocol(CollectionProtocol, Protocol):
    def __len__(self):
        ...

    def __iter__(self):
        ...

    def __getitem__(self, key):
        ...

    def __eq__(self, other):
        ...

    def get(self, k: _KT, default: Union[_VT_co, _T]) -> Union[_VT_co, _T]:
        ...

    def keys(self):
        ...

    def items(self):
        ...

    def values(self):
        ...
```

Thanks again for your help @JelleZijlstra
