### ISSUE TITLE
Show closest candidates for misspellings

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#824]
Instead of just saying `"foobar" undefined` try to look for closest candidates (using edit distance, for example) and give suggestions. For example: `"get_stats" undefined, did you mean "getstats"?`.

**Comment by JukkaL** [comment]
This would be useful for at least these things:

* Attribute lookups
* Keyword argument names
* Module imports

**Comment by JukkaL** [comment]
There is basic support for attribute lookups in the `hack` branch.

**Comment by JelleZijlstra** [comment]
This is done for attribute lookups, but not for the other things Jukka mentions.

**Comment by marcodoordash** [comment]
#4934 adds more details and use cases to the **Module imports** part of this issue, pasting those here and closing it as a duplicate of this one.

`Mypy can suggest correct spellings for some attributes, but it doesn't seem to work for module attributes:

```
from subprocess import popen  # Module 'subprocess' has no attribute 'popen'

import subprocess
subprocess.popen  # Module has no attribute "popen"

class Foobar:
    def do_it(self): pass
foobar  # Name 'foobar' is not defined

Foobar().doit()  # "Foobar" has no attribute "doit"; maybe "do_it"?
```
It would be better if mypy would suggest corrections for all of the cases in the above example.`

**Comment by marcodoordash** [comment]
looking at this one

**Comment by Wuisch** [comment]
I took a shot at the keyword argument name case. Comments are welcome.

**Comment by ilevkivskyi** [comment]
This is now fully implemented.
