### ISSUE TITLE
bad Callable pattern matching and overlaps in overload

### ISSUE THREAD

**Issue by rmorshea** [python/mypy#8241]
MyPy thinks `Callable[..., Any]` always overlaps even though MyPy already understands (in some cases) that it ought to pick the second signature if the function passed to `x` has more than one argument.

```python
from typing import overload, Callable, Union, List, Set

@overload
def f(x: Callable[[str], str]) -> Set: ...

@overload
def f(x: Callable[..., str]) -> List: ...

def f(x: Callable[..., str]) -> Union[list, set]: ...  # E: Overloaded function signatures 1 and 2 overlap with incompatible return types
```

Despite the error, MyPy can usually figure out which signature to apply:

```python
def g(a: str) -> str: ...

reveal_type(f(g))  # N: Revealed type is 'Set[Any]'

def h(a: str, b: int) -> str: ...

reveal_type(f(g))  # N: Revealed type is 'List[Any]'
```

However sometimes it doesn't seem to understand variable positional or keyword args:

```python
def m(a: str, *b: int) -> str: ...

reveal_type(f(m))  # N: Revealed type is 'Set[Any]'

def n(a: str, **b: int) -> str: ...

reveal_type(f(n))  # N: Revealed type is 'Set[Any]'
```

## Details

- have you tried this on master: no
- what version of mypy: 0.761
- option flags in use: none

**Comment by hauntsaninja** [comment]
Yeah, this is expected. The overlapping overload message can be more like a lint
