### ISSUE TITLE
distutils.command.install_data.install_data class does exist but mypy thinks it doesn't

### ISSUE THREAD

**Issue by CMCDragonkai** [python/mypy#8243]
The mypy keeps complaining that `distutils.command.install_data.install_data` class doesn't exist. But it does.

It also doesn't complain about `distutils.command.install.install` class. So that's a weird discrepancy.

**Comment by ethanhs** [comment]
Hi, this probably an issue for typeshed (https://github.com/python/typeshed). If I had to guess it is missing from the stubs.
