### ISSUE TITLE
Mypy unable to detect overriden types is subclasses

### ISSUE THREAD

**Issue by canassa** [python/mypy#8255]
**Are you reporting a bug, or opening a feature request?**
Bug 

**Please insert below the code you are checking with mypy**

The scenario is one class overriding the type of `__init__` argument from its base class. 

```python
from typing import Union


class Base:
    def __init__(self, a: Union[int, dict, str]):
        self.a = a

    def reveal_a(self) -> None:
        reveal_type(self.a)
        print(self.a)


class Child(Base):
    def __init__(self, a: Union[int, str]):
        self.a = a

    def reveal_child(self) -> None:
        reveal_type(self.a)
        print(self.a)
```

**What is the actual behavior/output?**

Mypy detects type subclass property type to be the type on the parent pass `Union[int, dict, str]`

```
a.py:9: note: Revealed type is 'Union[builtins.int, builtins.dict[Any, Any], builtins.str]'
a.py:18: note: Revealed type is 'Union[builtins.int, builtins.dict[Any, Any], builtins.str]'
```

**What is the behavior/output you expect?**

I expected that mypy detected the `self.a` type on the `Child` class to be `Union[int, str]`, like this:

```
a.py:9: note: Revealed type is 'Union[builtins.int, builtins.dict[Any, Any], builtins.str]'
a.py:18: note: Revealed type is 'Union[builtins.int, builtins.str]'
```

Please note that this bug doesn't happen if you override a class property:

```python
from typing import Union


class Base:
    a: Union[int, dict, str]

    def reveal_a(self) -> None:
        reveal_type(self.a)
        print(self.a)


class Child(Base):
    a: Union[int, str]

    def reveal_child(self) -> None:
        reveal_type(self.a)
        print(self.a)
```

```
a.py:8: note: Revealed type is 'Union[builtins.int, builtins.dict[Any, Any], builtins.str]'
a.py:16: note: Revealed type is 'Union[builtins.int, builtins.str]'
```

**What are the versions of mypy and Python you are using?**
0.761

**What are the mypy flags you are using? (For example --strict-optional)**
```
[mypy]
python_version = 3.7
check_untyped_defs = True
ignore_errors = False
ignore_missing_imports = True
strict_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
disallow_untyped_defs = True
```

**Comment by msullivan** [comment]
I don't think this is a bug. `Union[int, str]` is a subtype of `Union[int, dict, str]` and there's no way of knowing that you want the narrower type. It can be fixed with a type annotation (like you showed).

(Also: overriding the type of a mutable field is unsound and mypy really ought not allow it, but we think we would break too much code.)
