### ISSUE TITLE
feature - support class method annotation for call which changes the "refinement type" of 'self'

### ISSUE THREAD

**Issue by wahuneke** [python/mypy#8261]
I'm relatively new to type annotation and static analysis in Python.  Very excited about the potential though.

I'm noticing that there doesnt seem to be an annotation to effect a type of analysis that I think would be a great addition to mypy.  I'm fairly sure this is not supported presently and there is not even a way to do it by implementing a plugin.

Here's a simple example of what I seek, using Python's most ubiquitous class.  I am not actually interested in sorted lists, but this illustrates:

```python
   NormalList = NewType('NormalList', List)
   SortedList = NewType('SortedList', List)

   l:NormalList  = [1, 3, 2]

   # I want to annotate List.sort() to show that 'self' arrives as a NormalList and at
   # end of execution it is now a SortedList
   l.sort()

   # Now, I can annotate this function to indicate that it expects a sorted list.  
   # Huge static analysis benefit!  (I think)
   function_that_wants_sorted_lists(l)
```

I think this usage of types might be called _Refinement Types_  . I've noticed it's already been discussed a bit elsewhere.  I believe I already know how to satisfactorily express the different flavors of List.

The problem is there is no way to annotate that a function like List.sort mutates the 'self' object into a new refinement type.

Thank for your attention on this question.

**Comment by msullivan** [comment]
This is a super cool idea but also almost certainly not one we are going to implement.

Applying this sort of thing to imperative programming languages is hard and requires a lot of careful work and support from other parts of the language; I am sure there has been research into it but it's probably not something we want to tackle.

To give a flavor of what I think some of the difficulties would be:
First, everything that can *break* the sortedness of a list would need to be annotated as such. That's probably fine, though, in the simple case of a list of ints. With a list of objects that are themselves mutable, though, the sortedness of the list can be broken without performing any operations on the list at all. I understand sorted lists are just an example, but I think many properties can be broken in subtle ways by mutation.

The bigger problem is detecting when *other* code modifies the property. So for example:
```
l:NormalList  = [1, 3, 2]
l2 = l
l.sort()  # l is a sorted list
l2.append(0)  # l isn't sorted anymore :(
```
Doing refinements on mutable data structures without some sort of system for tracking aliases or enforcing linearity I think probably can't work?
