### ISSUE TITLE
Misleading type inference on complicated dict literal

### ISSUE THREAD

**Issue by alanhdu** [python/mypy#8277]
This might not be a "bug" per se, but I'm going to report it anyways in case.

Running `mypy 0.761` on Python 3.6 on the following code

```python
def get_api_message(a: str, b: str, c: int, d: str) -> None:
    api_message = {
        "d": d,
        "api_request": {"c": c, "start_stream_request": {"b": b, a: {}}},
    }
    reveal_type(api_message)
```

gives us a revealed type of:

```
$ mypy scratch.py
Revealed type is 'builtins.dict[builtins.str*, typing.Collection*[builtins.str]]'
```

This led to a confusing error downstream where code that edits part of the dict literal gets a `Value of type "Collection[str]" is not indexable`.

I get why `Collection` is being inferred, but probably in this case it'd be better to either explicitly require a type annotation or to infer `Dict[str, Any]` instead.

**Comment by JukkaL** [comment]
Yeah, the inferred type is confusing, but I'm not sure if there's anything we can easily do about it, since it's consistent with how mypy does type inference in general. One of the underlying problems is that string is a sequence of strings, which is a feature of Python (even though it sometimes feels like a misfeature).

**Comment by yesthesoup** [comment]
For anyone else ending up here, I solved this by declaring my dictionary as a `JsonDict` type

i.e. given the example in the OP
```python
from mypy.types import JsonDict

api_message: JsonDict = { .... }
```

**Comment by JelleZijlstra** [comment]
You should not be importing `mypy.types.JsonDict` or anything else from mypy (unless you're writing a mypy plugin). Mypy is not meant to be used as a library and its internal types may change at any time. `mypy.types.JsonDict` is currently an alias for `Dict[str, Any]`, so if that's the type you want, write `Dict[str, Any]` directly.

**Comment by yesthesoup** [comment]
> You should not be importing `mypy.types.JsonDict` or anything else from mypy (unless you're writing a mypy plugin). Mypy is not meant to be used as a library and its internal types may change at any time. `mypy.types.JsonDict` is currently an alias for `Dict[str, Any]`, so if that's the type you want, write `Dict[str, Any]` directly.

Thanks for the feedback! I wasn't aware
