### ISSUE TITLE
TypeVar Should Accept Arguments When Bound To Generic

### ISSUE THREAD

**Issue by rmorshea** [python/mypy#8278]
I've posted about this on [gitter](https://gitter.im/python/typing) but haven't gotten a response. Could someone help me understand how I would construct the type spec for a function `def (G[T]) -> G[List[G]]` where `G` is any subclass of `MyGeneric` class. My current approach results in the commented error:

```python
from typing import TypeVar, Generic

Val = TypeVar("Val")

class MyGeneric(Generic[Val]):
    def __call__(self, a: Val) -> Val: ...

T = TypeVar("T")
G = TypeVar("G", bound=MyGeneric)

def listify_my_generic(g: G[T]) -> G[List[T]]: ...  # error: Type variable "G" used with arguments
```

Here's a playground link:

https://mypy-play.net/?mypy=0.750&python=3.8&gist=290ef32f0638a648674b98873a263d6f

**Comment by rmorshea** [comment]
Ok, I've managed to create a work around:

```python
from typing import TypeVar, Generic, List

Val = TypeVar("Val")

class MyGeneric(Generic[Val]):
    def __init__(self, a: Val): ...

T = TypeVar("T")

SingleG = MyGeneric[T]
ListG = MyGeneric[List[T]]

def listify_my_generic(g: SingleG[T]) -> ListG[T]: ...

reveal_type(listify_my_generic(MyGeneric(1)))  # note: Revealed type is 'main.MyGeneric[builtins.list[builtins.int*]]'
```

However it would be nice if the example above worked - the work around requires more typing and is only able to communicate what's happening so long as we use descriptive variable names.

**Comment by JukkaL** [comment]
This looks essentially the same as https://github.com/python/typing/issues/548. Discussion can continue there. More generally, this is a type system enhancement and we generally discuss them in the typing issue tracker (or typing-sig@).
