### ISSUE TITLE
Mypy fires on  __anext__ function

### ISSUE THREAD

**Issue by sallyruthstruik** [python/mypy#8280]
I suppose there is a bug when checking async iterable class with `async def __anext__` method.
With provided code snippet:

```python
import asyncio


class Sample:

	def __init__(self):
		self._iter = iter(range(10))

	async def __aiter__(self) -> "Sample":
		return self

	async def __anext__(self) -> int:
		try:
			return next(self._iter)
		except StopIteration:
			raise StopAsyncIteration()


async def main() -> None:
	s = Sample()
	async for item in s:
		print(item)


asyncio.get_event_loop().run_until_complete(main())
```
mypy gives an error, but it shouldn't because code is correct (when run it prints numbers 0-9  as expected)

## Actual behavior
mypy gives an error:
```
temp.py:21: error: "Coroutine[Any, Any, Sample]" has no attribute "__anext__"
```

## Expected behavior
No errors

## Versions

```
$ python --version
Python 3.6.8

$ mypy --version
mypy 0.761
```

## Mypy configuration
```
[mypy]
python_version=3.6
ignore_missing_imports=True
warn_unreachable=True
disallow_untyped_defs=True

```

**Comment by JukkaL** [comment]
The program generates an exception for me. To me it looks like mypy is correct? Here's the output I get if I run the program (Python 3.7.4):

```
t/t.py:21: RuntimeWarning: coroutine 'Sample.__aiter__' was never awaited
  async for item in s:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "t/t.py", line 25, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "t/t.py", line 21, in main
    async for item in s:
TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: coroutine
```

**Comment by sallyruthstruik** [comment]
Funny, looks like the code works normally in 3.6.8, but fails in 3.7.4 

Anyway, there was `python_version=3.6` in mypy.ini, so mypy hadn't fire an error i think

**Comment by sallyruthstruik** [comment]
https://bugs.python.org/issue31709 asynchronous aiter was removed here (starting from python 3.7.0)

**Comment by JukkaL** [comment]
Yeah, mypy could support also the old behavior. However, this seems fairly low priority since most code should probably migrate to the new semantics eventually.

**Comment by sallyruthstruik** [comment]
As a solution it is also possible to use `def __iter__` in python3.6

In such case mypy doesn't fire and code works in the same way
