### ISSUE TITLE
Bug: when having functions with different type signatures store in a list/dict and declaring their type in an Union[], mypy combines types declaration instead of picking the right one

### ISSUE THREAD

**Issue by Psycojoker** [python/mypy#8282]
Hello,

Have a situation where:
- you have 2 functions, `a` and `b`, with different type signature
- store those functions in a dict or a list
- declare all those type using type annotation and a Union for the functions
- try to call those function while accessing them using index/key on the list/dict

If:
- you respect function `a` type declaration, mypy will complains that you don't respect function `b` type declaration
- the other way around if you respect function `b` type signature

To make it less asbtract here is 2 code examples, first one is with number of arguments (the errors generated by mypy are in comment at the end of the code):

```python
from typing import Dict, Union, Callable, List


def one_argument(a: str) -> int:
    return 42


def two_arguments_optional(a: str, b: str) -> int:
    return 1


functions_type = Union[Callable[[str], int],
                       Callable[[str, str], int],
                       ]
some_dict: Dict[str, functions_type] = {
    "a": one_argument,
    "b": two_arguments_optional,
}


some_dict["a"]("")  # error: Too few arguments
some_dict["b"]("", "")  # error: Too many arguments

some_list: List[functions_type] = [one_argument, two_arguments_optional]

some_list[0]("")  # error: Too few arguments
some_list[1]("", "")  # error: Too many arguments
```

And with arguments type:

```python
def wants_int(a: int) -> str:
    return ""


def wants_str(a: str) -> str:
    return ""


another_functions_type = Union[Callable[[str], str],
                               Callable[[int], str],
                               ]

another_list: List[another_functions_type] = [wants_int, wants_str]

another_list[0](42)  # Argument 1 has incompatible type "int"; expected "str"
another_list[1]("")  # Argument 1 has incompatible type "str"; expected "int"


another_dict: Dict[str, another_functions_type] = {
    "a": wants_int, "b": wants_str,
}

another_dict["a"](42)  # Argument 1 has incompatible type "int"; expected "str"
another_dict["b"]("")  # Argument 1 has incompatible type "str"; expected "int"
```

> What is the behavior/output you expect?

My code is correct so I shouldn't get an error, especially if I refer to how "Union" is [described in the documentation](https://docs.python.org/3/library/typing.html#typing.Union): "Union type; Union[X, Y] means either X or Y." 

Here mypy seems to be applying a "all members of the Union must be respected" instead of "at least one of them must be respected".

Maybe a warning (if needed) with hints on how to remove it would make sens too (but not a error.)

I also understand that this is far from being the best code in the world but I'm in a situation where I'm introducing type in an existing code base.

> What are the versions of mypy and Python you are using?

Latest on pypi and git version for mypy and python 3.7.3

> Do you see the same issue after installing mypy from Git master?

Yes

> What are the mypy flags you are using? (For example --strict-optional)

None

Kind regards and thanks for dedicating time in making python better :heart:

**Comment by JukkaL** [comment]
Even though the documentation is pretty vague about this, `Union[X, Y]` is checked so that any operation must be valid for *both* `X` and `Y`. Consider what would happen if you'd do `another_dict["a"]("")`.

Using a TypedDict may help if you are defining a dictionary that contains functions with different signatures.

**Comment by Psycojoker** [comment]
> Even though the documentation is pretty vague about this

Shouldn't we change the documentation then?

**Comment by JukkaL** [comment]
> Shouldn't we change the documentation then?

That would be good, though there's a question of how much detail should the CPython documentation contain. Mypy documentation already explains things in sufficient detail, I think (https://mypy.readthedocs.io/en/latest/kinds_of_types.html#union-types). Would you like to file an issue against CPython docs?

Looks like PEP 484 also might benefit from some extra explanation.
