### ISSUE TITLE
github link broken on https://mypy.readthedocs.io

### ISSUE THREAD

**Issue by etnnth** [python/mypy#8285]
The github link given by 'Edit on GitHub' on top right of [https://mypy.readthedocs.io](https://mypy.readthedocs.io) links to : 
[https://github.com/python/mypy/blob/origin/master/docs/source/index.rst](https://github.com/python/mypy/blob/origin/master/docs/source/index.rst) instead of :
https://github.com/python/mypy/blob/master/docs/source/index.rst](https://github.com/python/mypy/blob/master/docs/source/index.rst).
The same also append for github link on the bottom left.

**Comment by JukkaL** [comment]
Yeah, the link is broken. I wonder what is going on. Does anybody know how readthedocs is configured?

**Comment by JukkaL** [comment]
Thanks! It seems to work now when I toggled the settings mentioned in the comment to 'master' and back. Can somebody else verify that it works?

**Comment by TH3CHARLie** [comment]
It is not broken anymore but points to a strange commit like https://github.com/python/mypy/blob/f53b718bdf5935443332a43d8c1b448af8b80b57/docs/source/index.rst

**Comment by etnnth** [comment]
It looks fine for me, this is the last commit of the last release.

**Comment by JukkaL** [comment]
I also (separately) changed readthedocs to point to the last stable release, so everything seems fine.
