### ISSUE TITLE
Unable to deduce/coerce types in Union

### ISSUE THREAD

**Issue by dosisod** [python/mypy#8287]
* Are you reporting a bug, or opening a feature request?

Bug

* Please insert below the code you are checking with mypy:
```python
from typing import Union

def convert(num: Union[str, int]) -> int:
	if type(num) is str:
		 return int(num)

	#since we returned above, this can only be an `int`
	return num

print( convert("1") + convert(2) )
```

* What is the actual behavior/output?

`test.py:8: error: Incompatible return value type (got "Union[str, int]", expected "int")`

* What is the behavior/output you expect?

No error.

* What are the versions of mypy and Python you are using?
```
mypy 0.761
Python 3.6.9
```
* Do you see the same issue after installing mypy from Git master?

Did not check with master.

* What are the mypy flags you are using? (For example --strict-optional)

None.

This is similar to #8264 such that the type is not deduced.

If there is `N` types in the `Union`, and one of the `if` statements return for a given type, there should be `N-1` valid types in the `Union` proceeding the if statement.

This can get annoying when I have to cast the variable when I know the type:
```python
from typing import Union, cast

def convert(num: Union[str, int]) -> int:
	if type(num) is str:
		 return int(num)

	return cast(int, num)

print( convert("1") + 2 ) # prints 3
```

**Comment by JukkaL** [comment]
Things should work as expected if you use `isinstance(num, str)` instead of `type(num) is str`. The `type(...) is` check is not recommended since it doesn't work with subclasses (of `str`, in this case).

**Comment by dosisod** [comment]
This solved my problem, thanks!
