### ISSUE TITLE
Support pyxl

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#829]
Pyxl uses a custom source file encoding. Somehow get it to work.

**Comment by o11c** [comment]
If the encoding is installed, shouldn't it Just Work™ since the parser operates directly on decoded `unicode` objects?

Or are there python2-specific issues with how parsing works? I admit I'm operating from a python3 perspective.

The "mess with `builtins`" is the nastier part IMO.

**Comment by o11c** [comment]
Or wait, is the issue "how to use both `coding: mypy` and `coding: pyxl`" ? In that case, I think it's possible to modify the lookup to do multi-stage encoding with `coding:mypy-pyxl` ...

**Comment by JelleZijlstra** [comment]
I'm guessing this is no longer an issue, but somebody at Dropbox should confirm.

**Comment by gvanrossum** [comment]
Oh man, we're really not very good at closing issues when they're fixed. This was fixed by https://github.com/gvanrossum/pyxl3 over two years ago.

**Comment by ethanhs** [comment]
@gvanrossum perhaps we should adopt @msullivan's proposal in #4849? That would certainly help :)
