### ISSUE TITLE
San Francisco mypy community meetup on Friday Jan 24

### ISSUE THREAD

**Issue by msullivan** [python/mypy#8300]
I'm not sure if this will actually reach people, but our tech lead @JukkaL is visiting and so we'd like to host a small mypy community meetup in San Francisco on Friday Jan 24 at 1 PM.

Send me an email or hit me up on the typing gitter (https://gitter.im/python/typing) if you are interested.

**Comment by andychu** [comment]
I'm interested in attending!  I couldn't find your e-mail address though, mine is andy at oilshell.org :)  Please let me know how to attend.
