### ISSUE TITLE
Module 'typing' has no attribute 'ForwardRef'

### ISSUE THREAD

**Issue by dosisod** [python/mypy#8301]
* Are you reporting a bug, or opening a feature request?
Bug.
* Please insert below the ~~code~~ files you are checking with mypy,
```python
# a.py
class x:
	def __init__(self, num):
		self.num=num


# b.py
try:
	# python 3.8
	from typing import ForwardRef
except ImportError:
	# ForwardRef is private in python 3.6 and 3.7
	from typing import _ForwardRef as ForwardRef

def get_num1(x_ref: "x") -> None:
	print(x_ref.num)

def get_num2(x_ref: ForwardRef("x")) -> None:
	print(x_ref.num)


# c.py
import a
import b

b.get_num1(a.x(123))
b.get_num2(a.x(321))
```
* What is the actual behavior/output?
```
$ python3 c.py   # no errors
123
321

$ mypy c.py  # has errors
b.py:2: error: Module 'typing' has no attribute 'ForwardRef'
b.py:5: error: Module 'typing' has no attribute '_ForwardRef'
b.py:7: error: Name 'x' is not defined
b.py:10: error: Invalid type comment or annotation
b.py:10: note: Suggestion: use ForwardRef[...] instead of ForwardRef(...)
Found 4 errors in 1 file (checked 1 source file)
```
* What is the behavior/output you expect?
No errors.
* What are the versions of mypy and Python you are using?
Python 3.6.9
mypy 0.761
* Do you see the same issue after installing mypy from Git master?
Did not try.
* What are the mypy flags you are using? (For example --strict-optional)
None

For my code, I need to forward reference a class from another file. Running `c.py` with python has no errors, but type checking with mypy does. It says that it cannot import `ForwardRef`, though it is imported properly in python.

The note suggests that I use `ForwardRef[...]` instead of `ForwardRef(...)`, though this still results in errors in mypy and causes the python code to throw a `TypeError`.

**Comment by JukkaL** [comment]
The missing import is due to a missing typeshed definition (https://github.com/python/typeshed). Can you file an issue there?

However, `ForwardRef` should not be instantiated by a user or used in an annotation (if I'm reading the docs correctly: https://docs.python.org/3/library/typing.html#typing.ForwardRef).
