### ISSUE TITLE
Pretty print option breaks when tabs are in source

### ISSUE THREAD

**Issue by dosisod** [python/mypy#8306]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
Bug + PR
* Please insert below the code you are checking with mypy:
```python
# 4spaces.py
def test_4spaces() -> str:
    return None
test_4spaces()

# 8spaces.py
def test_8spaces() -> str:
        return None
test_8spaces()

# tabs.py
def test_tabs() -> str:
	return None
test_tabs()
```
* What is the actual behavior/output?
```
$ mypy *.py --pretty
tabs.py:2: error: Incompatible return value type (got "None", expected "str")
    	return None
            ^
8spaces.py:2: error: Incompatible return value type (got "None", expected "str")
            return None
                   ^
4spaces.py:2: error: Incompatible return value type (got "None", expected "str")
        return None
               ^
```
* What is the behavior/output you expect?
The `^` indicator to be in correct position in all 3 examples. Fixed in PR.
* What are the versions of mypy and Python you are using?
mypy 0.770+dev.861f01c3be99b9faf2e8d42e316aee4ec6e571c4.dirty
Python 3.6.9
* Do you see the same issue after installing mypy from Git master?
Yes.
* What are the mypy flags you are using? (For example --strict-optional)
--pretty

In most terminals the `tab` character will be expanded to the nearest tab column, that being every 8 characters.

When mypy is displaying the source, lines with tabs gobble up space, and the column attribute treats tabs as a single character and not 8. This causes many problems when displaying source lines with tabs.

**Comment by ilevkivskyi** [comment]
Fixed by https://github.com/python/mypy/pull/8307
