### ISSUE TITLE
[Question] - Per file or per folder options in .ini?

### ISSUE THREAD

**Issue by Plotnus** [python/mypy#8311]
Is there a way to specify options in mypy.ini that are meant to be per file or per folder?

Given the size of the repo I'm working with it'd be much easier than adding options per module.
Is this supported? I looked on the docs and it seems that only per module options is supported.

**Comment by refi64** [comment]
Not quite per-folder, but you can use globs in package names to get a very
similar effect, as shown here:
https://mypy.readthedocs.io/en/latest/config_file.html#examples

**Comment by ilevkivskyi** [comment]
Module/package glob is the way to do this (see above comment). It is unlikely mypy will also support directory globs.
