### ISSUE TITLE
Re-exporting from `typing` module using assignment to variable doesn't work

### ISSUE THREAD

**Issue by jack1142** [python/mypy#8315]
Please provide more information to help us understand the issue:

**Issue type**
Bug

**Mock-up repro**
A simple package with two files is needed to test this. Inside the package's folder put:
- `__init__.py` file
```py
from .external_typings import RedOptional

def func(arg: RedOptional[bool] = True) -> None:
    pass
```
- `external_typings.py` file
```py
from typing import Optional

__all__ = ("RedOptional",)

RedOptional = Optional
```
After that run:
```
python -m mypy -p package_name
```

**Expected output**
`RedOptional` should properly be resolved as `typing.Optional` which means there should be no errors.

**Actual output**
```
mypy_issue\__init__.py:4: error: Variable "mypy_issue.external_typings.RedOptional" is not valid as a type
```

**Python version**
Python 3.8.1

**mypy version**
0.761, also happens on master

**Used flags**
No flags used.

---

A little more info, I tried doing same thing but using other module instead, e.g:
```py
from typing import TYPE_CHECKING
from io import BytesIO

__all__ = ("RedOptional",)

RedOptional = BytesIO
```
And this gets properly exported and mypy knows it got `BytesIO` class.

**Comment by ilevkivskyi** [comment]
Aliases to special forms are not supported (and unlikely to be supported). You need to write:
```python
from typing import Optional as RedOptional
```
