### ISSUE TITLE
dataclass is not type checked inside of functions

### ISSUE THREAD

**Issue by jackric** [python/mypy#8318]
Minimal repro:
```python
from dataclasses import dataclass

@dataclass
class Coord:
    x: int

a = Coord("a")

def main():
    b = Coord("a")
```

Expected:
Report type errors for both bad instantiations of `Coord`.

Actual:
```
$ mypy main.py
main.py:7: error: Argument 1 to "Coord" has incompatible type "str"; expected "int"
Found 1 error in 1 file (checked 1 source file)
```
Mypy only reports an error for the global scope instantiation.
Interestingly, [the docs can claim accuracy because the examples are only in the global scope](https://mypy.readthedocs.io/en/stable/additional_features.html#dataclasses) too. If this is known and the examples are careful, then it should be mentioned.

**Mypy version** 0.761
**Python version** 3.8.1

**Comment by ilevkivskyi** [comment]
`--check-untyped-defs`
