### ISSUE TITLE
ReadTheDocs build failures

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#8321]
Somehow the readthedocs build failure emails go to me, and I've seen two failures lately. The latest is: https://readthedocs.org/projects/mypy/builds/10315378/

**Comment by TH3CHARLie** [comment]
may be related to a readthedocs issue https://github.com/readthedocs/readthedocs.org/issues/6554

**Comment by gvanrossum** [comment]
Thanks! I've followed the instructions there and wiped both "latest" and "stable", then triggered new builds. As soon as both have completed successfully I will close this issue.

**Comment by gvanrossum** [comment]
Reopening, I keep getting these failures, e.g. https://readthedocs.org/projects/mypy/builds/10324259/

**Comment by TH3CHARLie** [comment]
Looks like it is cached therefore only affects a single wipe: https://github.com/readthedocs/readthedocs.org/pull/6571

**Comment by TH3CHARLie** [comment]
No more failures in recent builds due to updates on readthedocs side. So I think it's reasonable to close this now. @gvanrossum

**Comment by gvanrossum** [comment]
Indeed. Thanks!
