### ISSUE TITLE
mypy -m <module> does not follow imports for PEP 561 compatible packages

### ISSUE THREAD

**Issue by ericvw** [python/mypy#8323]
From reading the `mypy`'s documenation on [Specifying code to be checked](https://mypy.readthedocs.io/en/stable/running_mypy.html#specifying-code-to-be-checked), the behavior for `-m` states:

> [...] if we had used the -m flag, mypy would have type checked just html’s __init__.py file and anything imported from there.

However, that does not seem to be the case for an installed PEP 561 compatible package that the `__init__.py` and anything imported from there is checked.  Below, is a reproducer script illustrating the issue...

`reproducer.sh`:
```shell
#! /bin/sh
# In an activated virtual environment...

mkdir -p mypy_test_case
cd mypy_test_case || exit

cat >setup.py <<EOF
from setuptools import setup
setup(
    name="package_a",
    version="0.0.1",
    packages=["package_a"],
    package_data={"package_a": ["py.typed"]},
    zip_safe=False,
)
EOF

mkdir -p package_a
cat >package_a/__init__.py <<EOF
from . import internal
internal.ex(1)
EOF
cat >package_a/internal.py <<EOF
def ex(arg: str) -> str:
    return arg
EOF
touch package_a/py.typed

python -m pip install .
python -m pip install mypy

# Observe mypy follows imports.
python -m mypy --strict -m package_a
# package_a/__init__.py:2: error: Argument 1 to "ex" has incompatible type "int"; expected "str"
# Found 1 error in 1 file (checked 1 source file)

# Observe mypy fails to follow imports.
cd .. || exit
python -m mypy --strict -m package_a
# Success: no issues found in 1 source file
```

I was expecting a failure when the package is installed compared to running `mypy -m` in the directory where the physical package is located.

The reason for desiring this behavior is that in the case of typing stubs, I would like to ensure that all `*.pyi` files are correctly installed via `package_data` for a well-formed PEP 561 package.

If the behavior is expected and desired, what would be the recommendation be for testing that an installed PEP 561 package is well-formed with all the proper typings and stubs?  Thanks!

**Comment by ilevkivskyi** [comment]
I think you can try `--no-silence-site-packages` to show the errors. But if you are a package maintainer, I would personally recommend a tiny script for a direct check of the package, see for example https://github.com/dropbox/sqlalchemy-stubs/blob/master/.travis.yml#L28

**Comment by ericvw** [comment]
` --no-silence-site-packages` did elicit the error.  Thanks!
