### ISSUE TITLE
Imported from __init__.py needs __all__

### ISSUE THREAD

**Issue by cblegare** [python/mypy#8338]
* Are you reporting a bug, or opening a feature request?: **bug**
* Please insert below the code you are checking with mypy,
  ```python
  from fastapi import Depends
  ```
* What is the actual behavior/output?
  ```
  error: Module 'fastapi' has no attribute 'Depends'
  ```
* What is the behavior/output you expect?
  > No error
* What are the versions of mypy and Python you are using?
  * mypy 0.761
  * Python 3.7.5 
  * From git repo (be883f6770b24bc467ccb993fd77864248b61979) the issue is still present.
* What are the mypy flags you are using? (For example --strict-optional)
  ```
  [mypy]
  warn_unused_configs = True
  disallow_subclassing_any = True
  disallow_any_generics = True
  disallow_untyped_calls = True
  disallow_untyped_defs = True
  disallow_incomplete_defs = True
  check_untyped_defs = True
  disallow_untyped_decorators = True
  no_implicit_optional = True
  warn_redundant_casts = True
  warn_unused_ignores = True
  warn_return_any = True
  no_implicit_reexport = True
  follow_imports_for_stubs = True
  mypy_path = stubs
  plugins = sqlmypy,pydantic.mypy
  namespace_packages = True
  ```

When I manually edit `fastapi/__init__.py` in my site-packages to add a `__all__ = ["Depends"]` I get no error.

Here is the original content of `fastapi/__init__.py` [see also their github](https://github.com/tiangolo/fastapi/blob/master/fastapi/__init__.py).

```python
"""FastAPI framework, high performance, easy to learn, fast to code, ready for production"""

__version__ = "0.47.1"

from starlette.background import BackgroundTasks

from .applications import FastAPI
from .datastructures import UploadFile
from .exceptions import HTTPException
from .param_functions import (
    Body,
    Cookie,
    Depends,
    File,
    Form,
    Header,
    Path,
    Query,
    Security,
)
from .routing import APIRouter
```

**EDIT**

* Added content of `fastapi/__init__.py` as requested by @JelleZijlstra

**Comment by JelleZijlstra** [comment]
Could you share what is in `fastapi/__init__.py` when the error happens?

**Comment by bluetech** [comment]
This is due to the `no_implicit_reexports = True` setting. According to its [rules](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport), `Depends` is not considered reexported.

To be compatible with the flag, `fastapi` should either use `__all__` or use `from .param_functions import Depends as Depends` etc.

**Comment by tiangolo** [comment]
This was fixed in FastAPI, on https://github.com/tiangolo/fastapi/pull/2547 :tada:

So it should be safe to close this issue here. :heavy_check_mark:

**Comment by ethanhs** [comment]
Thanks for the follow up @tiangolo! I'll go ahead and close this.
