### ISSUE TITLE
Type[T] not working correctly with T=TypeVar('T', bound=…)

### ISSUE THREAD

**Issue by ruohola** [python/mypy#8352]
* Are you reporting a bug, or opening a feature request?
Bug
* Please insert below the code you are checking with mypy:

```
from typing import Dict, Optional, Type, TypeVar

class Model:
    objects: Dict[int, 'Model'] = {}

T = TypeVar('T', bound=Model)

def get_obj_or_none(model: Type[T], obj_id: int) -> Optional[T]:
    try:
        return model.objects[obj_id]
    except KeyError:
        return None
```
* What is the actual behavior/output?
>```
>type_example.py:10: error: Incompatible return value type (got "Model", expected "Optional[T]")
>Found 1 error in 1 file (checked 1 source file)
>```
* What is the behavior/output you expect?
No errors
* What are the versions of mypy and Python you are using?
mypy 0.761 with Python 3.8.1
* Do you see the same issue after installing mypy from Git master?
Yes, using `mypy 0.770+dev.150d4921e702512e8afa0fc9cc22e71e720c3069` gave the exact same error.
* What are the mypy flags you are using? (For example --strict-optional)
No flags, just `$ mypy filename.py`

**Comment by JelleZijlstra** [comment]
PEP 484 generally disallows this sort of construct (https://www.python.org/dev/peps/pep-0484/#the-type-of-class-objects), except if the method is a classmethod. I don't see why what you're doing shouldn't be supported, though.

**Comment by ruohola** [comment]
@JelleZijlstra I don't see how it disallowes this in any way, as far as I see, it's pretty much identical with one of the examples:

>However using `Type[]` and a type variable with an upper bound we can do much better:
>```
>U = TypeVar('U', bound=User)
>def new_user(user_class: Type[U]) -> U:
>     ...
>```

**Comment by JukkaL** [comment]
The error from mypy is correct. The `objects` attribute can contain an instance of an arbitrary `Model` subclass, but the return type of `get_obj_or_none` contains a specific subtype `T` of `Model`. `Type[T]` has no effect in this example, since the type of the `objects` attribute is the same in subclasses (it doesn't use a "self" type). I don't think that there's a way to use a self type for a class variable.
