### ISSUE TITLE
Cannot return concrete type within `isinstance` block of generic function

### ISSUE THREAD

**Issue by PeterJCLaw** [python/mypy#8354]
I'm not sure if this is a bug or a known limitation. I think this is different to the other similar generics vs `isinstance` issues, but please do point me at another if this is a duplicate.

Given some function:
``` python
from typing import TypeVar

T = TypeVar('T')

def foo(val: T) -> T:
    if isinstance(val, str):
        return "abc"
    return val
```

I would hope that `mypy` can tell that, within the `isinstance` block, `T` can only be `str` (since that's what `val` is) and thus returning something which is explicitly `str` is fine.

Unfortunately this case seems to error:
```
foo.py:5: error: Incompatible return value type (got "str", expected "T")
```

I realise this construct looks a bit odd in the cut-down above -- my actual use-case involves walking nested list and dictionary structures to modify values, but ends up with what I believe is the same error. Just to give a sense of that a slightly larger but still very cut-down version would be:

``` python
from typing import Any, List, TypeVar, Union

T = TypeVar('T', bound=Union[str, List[Any], int])

def do_expansion(value: T) -> T:
    if isinstance(value, str):
        return value.upper()  # just using .upper() as an example
    elif isinstance(value, list):
        return [do_expansion(x) for x in value]
    else:
        return value
```

I realise I could use overloads to achieve a similar effect for consumers of the function, however I would also like to be able to type the implementation and get checking there.

In case it's useful, I'm using `mypy` version `0.761` (latest at the time of writing) on Python 3.5.2.

**Comment by hauntsaninja** [comment]
I think the issue this runs into is:
```
from typing import *

class A: ...
class B(A): ...

T = TypeVar("T")

def test(x: T) -> T:
    if isinstance(x, A):
        return A()
    return x

test(B())  # you'd expect this to be a B
```
To make it more problematic, substitute `A` with `object`.

As you say, overloads will work for consumers, maybe for yourself try `functools.singledispatch`?

**Comment by PeterJCLaw** [comment]
Ah, yeah I'd missed that subclasses might break that.
Using [`functools.singledispatch`](https://docs.python.org/3/library/functools.html#functools.singledispatch) as you suggest definitely looks like it could help (and maybe clarify my code a little too!) with this, once `mypy` is happy with how it works.

**Comment by hauntsaninja** [comment]
Actually, `mypy` is okay with the TypeVar, as long as you don't have more complicated overloads:

```
from typing import *
import functools

T = TypeVar("T")

@functools.singledispatch
def foo(val: T) -> T:
    return val

@foo.register
def _(x: int) -> int:
    return x + 1
```

**Comment by JukkaL** [comment]
It looks like there's nothing actionable here?
