### ISSUE TITLE
get_dynamic_class_hook() not invoked on generic types

### ISSUE THREAD

**Issue by mkurnikov** [python/mypy#8359]
In Django, there's a method called `as_manager()` on `QuerySet` 
https://docs.djangoproject.com/en/3.0/ref/models/querysets/#django.db.models.query.QuerySet.as_manager
which returns an instance of a dynamically created manager with callee `QuerySet` method copied inside
```
class AnonymousManager(models.Manager):
    ... methods of QuerySet callee copied ...
```

I'd like to be able to call it like with generic parameters
```
MyQuerySet[MyModel].as_manager()
```

Now, because of clause
```
            if isinstance(callee_expr, RefExpr) and callee_expr.fullname:
                method_name = call.callee.name
                fname = callee_expr.fullname + '.' + method_name
```
`get_dynamic_class_hook()` never called. `callee_expr` is `TypeApplication` here, not `RefExpr`.

**Comment by msullivan** [comment]
I'd be happy to review a PR if you send one!

**Comment by flaeppe** [comment]
@sobolevn Seems that what I also discovered here https://github.com/typeddjango/django-stubs/pull/1683#discussion_r1315571526 is already reported

**Comment by sobolevn** [comment]
@flaeppe do you want to contribute? :)
I would be happy to merge this feature, since it is affecting us for like 3 years now.

**Comment by flaeppe** [comment]
Yeah, sure, I'll have a look as soon as I get some time
