### ISSUE TITLE
Bug if use async init pattern

### ISSUE THREAD

**Issue by heckad** [python/mypy#8362]
```
from typing import Dict
from typing import Optional


class A:
    def __init__(self):
        self.var: Optional[Dict[str, str]] = None

    async def _init(self):
        # Do some work
        self.var = {}

    async def get(self, key) -> str:
        if self.var is None:
            await self._init()

        return self.var[key]
```
Error
```
test.py:17: error: Value of type "Optional[Dict[str, str]]" is not indexable
Found 1 error in 1 file (checked 1 source file)
```

**Comment by hauntsaninja** [comment]
You can add `assert self.var is not None` on line 16 to work around this (as per the last line on https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#built-in-types). If that's cumbersome, maybe try changing `__init__` to have: `self.var: Dict[str, str] = None  # type: ignore` (but then you have to manually make sure you `_init` everywhere you need to).

**Comment by msullivan** [comment]
The same thing happens even without async, and is for better or worse just how mypy is. I don't think we're going to track which methods change types and process that.

Is it particularly worse in the async case?
