### ISSUE TITLE
Using Callable as a member variable of a class Protocol fails

### ISSUE THREAD

**Issue by jbcpollak** [python/mypy#8367]
I'm not sure if this is a bug or I just don't know the proper incantation. I am trying to define a class that implements a Protocol having a member function which is a callable. The code looks like this:

sample.py:
```
from dataclasses import dataclass, field
from typing import List, Any, Callable
from typing_extensions import Protocol

class TaskFactory(Protocol):
    def __call__(self, strs: List[str]) -> Any:
        ...

class TaskSpec(Protocol):
    factory: TaskFactory
    strs: List[str] = field(default_factory=list)

@dataclass
class TaskSpecAdapter:
    factory: TaskFactory
    strs: List[str] = field(default_factory=list)

class NewStyleTask:

    strs: List[str] = ['pick-cam']

    def factory(self, strs: List[str]) -> Any:
        # no op
        pass

specA: TaskSpec = TaskSpecAdapter(
    lambda strs: 'noop'
)
specB: TaskSpec = NewStyleTask()
```

`mypy sample.py` fails with this:

```
sample.py:30: error: Incompatible types in assignment (expression has type "NewStyleTask", variable has type "TaskSpec")
sample.py:30: note: Protocol member TaskSpec.factory expected settable variable, got read-only attribute
```

searching for the `expected settable variable` error I found https://github.com/python/typing/issues/622, but when I added `@property` to the TaskSpec.factory definition, I get an invalid syntax error.

How do I define a member function of a class to implement a callable of a Protocol?

**Comment by msullivan** [comment]
To make it a property, you need to write
```
    @property
    def factory(self) -> TaskFactory:
        pass
```

That should work.

**Comment by jbcpollak** [comment]
@msullivan  - doesn't that make a property of TaskSpec called `factory` that returns an object of type `TaskFactory` when called?

ie, `mySpec.factory()(self, ['string1', 'string2'])`?

what I'm looking for is to be able to do:

`mySpec.factory(['string1', 'string2'])`

where I know `factory` will typecheck as a TaskFactory.
