### ISSUE TITLE
Use fully qualified name for class with confusing name such as "Any"

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#8372]
The following example generates a confusing error message, since it's unclear which `Any` type it is referring to:

```py
class Any: pass

x = Any()
x = 1  # Incompatible types in assignment 
       # (expression has type "int", variable has type "Any")
```

(It would be more confusing if the `Any` type is inferred from the return type of a function.)

It would be better to always use a fully qualified name for a class named `Any` in error messages (similarly also for `None`, `Union`, etc.). 

This can also happen with classes that have names resembling built-in types:

```py
class float: pass

x = float()
x = 0  # Incompatible types in assignment 
       # (expression has type "int", variable has type "float")
```

The relevant code seems to be in `mypy.messages.format_type`.

**Comment by Macavitycode** [comment]
May I take this up as my first contribution?

**Comment by vegarsti** [comment]
This has been bothering me from time to time. I'd be happy to give this a shot. Do you have any thoughts on what classes this should apply to? I don't immediately see a nice way to find a good criteria to separate here.

**Comment by JelleZijlstra** [comment]
Maybe everything in `typing` and `builtins`, or everything that appears more than once somewhere in the whole program.

**Comment by vegarsti** [comment]
I like the first one. Thanks!

**Comment by Muks14x** [comment]
Since it's been a while, I hope it's okay if I work on this?

**Comment by vegarsti** [comment]
Appreciate you asking! I was hoping to get around to it this weekend, I was
on vacation the past week. But feel free to do it, I won't stop you!

**Comment by vegarsti** [comment]
Nice, I'm glad you did it! I'm not able to do it this weekend anwyay!
