### ISSUE TITLE
mypy doesn't understand if with and

### ISSUE THREAD

**Issue by GoldsteinE** [python/mypy#8378]
**Bug**
Code to reproduce: https://mypy-play.net/?mypy=latest&python=3.8&gist=119ad8a52e4c5eae1cb9acdca7b5dc25.

**Actual behaviour:**
mypy compains that `b` can be `None`.

**Expected behaviour:**
mypy should accept this code because `b` can't be `None` as checked in line 4.

**Comment by msullivan** [comment]
This requires a much more elaborate system of predicate and control flow tracking than we are likely to support. Sorry!
