### ISSUE TITLE
Treat methods on protocols with empty bodies as abstract 

### ISSUE THREAD

**Issue by JarnoRFB** [python/mypy#8395]
When declaring a protocol it is suggested in the [documentation](https://mypy.readthedocs.io/en/stable/protocols.html#simple-user-defined-protocols) that method that have to be defined in implementations of that protocol can be marked with `...` and I find this syntax quite pretty. However, currently the `...` is treated as a default implementation. Which can lead to confusing behavior. An example is the following:

```python
from typing_extensions import Protocol


class SupportsAdding(Protocol):
    def add(self, x: int, y: int) -> int: ...


class Adder(SupportsAdding):
    def subtract(self, x: int, y: int) -> int:
        return x + y


if __name__ == '__main__':
    adder: SupportsAdding = Adder()
    z = adder.add(1, 2)
    print(type(z))
    reveal_type(z)
```

Given the rather drastic misspelling of `add` as `subtract`, mypy still infers the protocol to be correctly implemented. The result of `reveal_type(z)` is `int`, while it is actually `NoneType`. [PEP 544](https://www.python.org/dev/peps/pep-0544/#explicitly-declaring-implementation) recommends to decorate non-default implementations with `@abstractmethod`. However, this leads to less elegant code and additional runtime checks. Since it seems kind of obvious that `...` is never a default implementation of a method, I would suggest to treat it the same way as protocol methods decorated with `@abstractmethod`.

I am using mypy version `0.761`.

**Comment by ilevkivskyi** [comment]
This is essentially a particular case of https://github.com/python/mypy/issues/2350

(Btw I wanted to fix this at some point but decided it is not worth it)
