### ISSUE TITLE
Running mypy for file in directory starting with "@" fails

### ISSUE THREAD

**Issue by MikiGrit** [python/mypy#8399]
I have a problem with running mypy for a file inside directory starting with `@`.

E.g. running `mypy @somedir/script.py` fails with
```bash
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: [Errno 2] No such file or directory: 'somedir/script.py'
```

while running `mypy script.py` is fine.

Thanks for help.

**Comment by ilevkivskyi** [comment]
Mypy treats `@` on command line in a special manner, this indicates that a file after `@` is not a file to be checked, but rather a file that contains a list of files to be checked, see https://mypy.readthedocs.io/en/stable/running_mypy.html#reading-a-list-of-files-from-a-file

**Comment by MikiGrit** [comment]
Ok, I understand that. But what should I do in that case... it is a perfectly valid path. It is unexpected that mypy on some paths "just doesn't works".

**Comment by ilevkivskyi** [comment]
`--strict` is also a perfectly valid file path, yet mypy treats is special. As with most other Linux tools, prefixing paths with `./` should work.
