### ISSUE TITLE
<directory> is not a valid Python package name

### ISSUE THREAD

**Issue by jcrben** [python/mypy#8400]
Note that this message appears for a couple other reported issues, but it's not clear that they are the same: https://github.com/python/mypy/issues/8229 and https://github.com/python/mypy/issues/6003

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request? 

Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

Code is this in test1.py:
```
def greeting(name: str) -> str:
    return "Hello " + name
```

Directory layout is more critical:
test -> nested -> nested-2 -> test1.py

Next to test1.py is `__init__.py` - other directories are empty.

* What is the actual behavior/output?

When I run `~/.local/pyenv/versions/3.7.2/bin/python -m mypy /Users/bencreasy/test/nested/nested-2/test1.py` I get:
`nested-2 is not a valid Python package name`

If I remove `__init__.py`, the message goes away.

* What is the behavior/output you expect?

Don't see why it can't run the file, but if it cannot, a better error message.

* What are the versions of mypy and Python you are using?

Python: Python 3.7.2
mypy: mypy 0.761

* Do you see the same issue after installing mypy from Git master?

Yes, after running `pip install git+git://github.com/python/mypy.git@a07dbd00638c35729e30dfc4ae441a8985183563` - same message.

* What are the mypy flags you are using? (For example --strict-optional)

None.

**Comment by ilevkivskyi** [comment]
`__init__.py` files exist in Python for a reason: this means the directory represents a package (so that one can import it). Since `import nested-2` is obviously a syntax error, package names must be valid Python identifiers.

TBH, I don't see what is not clear in this error message, but if you will make a PR with alternative wording we _might_ consider it.

**Comment by abcdenis** [comment]
Hi,
what I did:
- checkout some-project-with-dashes-in-name
- cd to it
- run [mypy .]
- got error ". is not a valid Python package name"

Now I have to investigate: 
- check if there is __init__.py file inside
- wonder that mypy stops on such condition
- remove __init__.py and rerun

It will be nice to print invalid package full name/directory.
Or print option name to skip such checking.

Thank you.

**Comment by markfickett** [comment]
I'm getting a similar error where my directory structure is `/path/with/some-directory-in-it/pkgdir/file.py` . When I cd to `pkgdir` and run `mypy file.py` I get an error saying `some-directory-in-it` is not a valid Python package. There is a `some-directory-in-it/__init__.py`, but I can use other Python tools, like `pip install -e .` (there's a `setup.py` that specifies a valid Python package name) and `python file.py` just fine, so it's confusing that `mypy` does not work in this context.

**Comment by wangkuiyi** [comment]
@markfickett I got the same problem. After renaming `some-directory-in-it` into `some_directory_in_it`, `mypy` worked!

**Comment by BTripp1986** [comment]
I am getting this error for a parent directory which is not coupled with the actual project.  

`/home/me/my-code/python/my_project_with_mypy/main.py`  

The `my_project_with_mypy` directory is a git repository, and therefore independent of the parent directory.  

I could move the project into another directory hierarchy, but then what if someone clones my repo into a directory with dashes?  

This definitely seems like an error, but I am new to MyPy so I could just be missing some kind of configuration which will work around this.

**Comment by stevleibelt** [comment]
@BTripp1986 do you get any response if this is indeed an issue or not?

I ran into the same problem. Checking out a git repository with the name `foo-bar`.
It feels so wrong that this is an issue since I execute mypy inside the repository.

**Comment by elmago** [comment]
I had the same problem, but I managed to make progress by directly pointing to the Python package I needed using the --package option like: `mypy -p src`

**Comment by AntiSol** [comment]
I just ran into this in a situation where I am using a submodule

```
core-project:
  |- .git
  |- pyproject.toml
  |- __init__.py
  |- module.py
  
  
client-project:
  |- .git
  |- README
  |- pyproject.toml
  |- src
  |  |- core_project -> git@host:core-project.git
  |  |- main.py
  
  ```
  
  main.py:
  ```
  
  from core_project import module
  
  module.do_stuff()
  
  ```

* when running mypy over the core-project repo (using `mypy .` in core-project), I get this error
* core-project needs its own linting / validation, independant of the client project, because core-project has no knowledge of the client project
* core-project's root directory is a package. This is still not ideal because now there's e.g a pyproject.toml in `client-project/src/core_project/`, but git doesn't really offer an option to do a "partial submodule" that only includes a single directory from another repo. core-project's root does not have a subdirectory like `src`, because then you'd have to `import core_project.src.module` all over the place, which is ugly and unnecessary. This could be alleviated somewhat by manually importing `src.module` in an __init__.py at the root level, but that would still cause the same issue with mypy, and also means adding every module that you want to import there.
* our company has a policy of naming repos with hyphens, naming the repo `core_project` would violate policy. Note that it is named `core_project` when added as a submodule, because as mypy points out core-project is not a valid package name.

**Comment by koljapluemer** [comment]
Kindly, why is this issue closed? This makes `mypy`  effectively unusable within projects that have a naming standard that happens to not be PEP8, for very little reason. A development library forcing naming standards of *wrapper* directories is an absurd overreach for extremely little reason.

**Comment by sabpamdev1** [comment]
How to disable this rule, if anyone can help please?

**Comment by AntiSol** [comment]
Frankly your best option is to just disable mypy completely, that's we ended up doing at my company. It's incredibly slow and it's output is wrong most of the time anyway. 

Plus, you'll note the lack of response on tickets like this one.

My advice is to save yourself a heap of time and needless hassle and just chuck mypy in the bin :)

**Comment by klalumiere** [comment]
> __init__.py files exist in Python for a reason: this means the directory represents a package (so that one can import it). Since import nested-2 is obviously a syntax error, package names must be valid Python identifiers.

> TBH, I don't see what is not clear in this error message, but if you will make a PR with alternative wording we might consider it.

Well, your explanation is actually perfect: thanks for this! 🙂 So for the ~error~ help message, I suggest something based on your explanation:

`<invalid-name> is not a valid Python package name. Hint: a parent or child directory might contain a ' __init__.py' file when it shouldn't.`

Low cost to change, and it's going to help hundreds of people. 😎 Thanks!

**Comment by foges** [comment]
I'm not sure if this is an issue with `uv` or `mypy`, but I have a `uv` managed project with a workspace and I'm trying to run mypy with python 3.12 and am getting the following error

```
$ uv run mypy --config-file common_utils/mypy.ini common_utils/
common_utils-0.1.0 is not a valid Python package name
```

My package is called `common_utils` and I don't have any `__init__.py` in any path. I see there's a hyphen in the generated package name, but that's only from the version number which is auto-generated. I don't see why this should be an error?

**Comment by caldempsey** [comment]
@foges just switch to pyright

**Comment by jibril-sharafi** [comment]
This issue is still present on the latest versions of mypy.

**Comment by caldempsey** [comment]
@jibril-sharafi this is never getting fixed, switch to something else

**Comment by ilevkivskyi** [comment]
@klalumiere Btw on current master error message is more explicit (and hopefully helpful):
```
foo-bar contains __init__.py but is not a valid Python package name
```
