### ISSUE TITLE
Catch invalid typing imports when targeting Python 3.5.1

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#8409]
Python 3.5.1 doesn't have `typing.TYPE_CHECKING` and doesn't support overloading outside stubs. It would be nice if mypy could catch these issues when targeting Python 3.5(.1).

I was bitten by these twice only today.

Python 3.5 will reach end of life soon, however, so it's not clear whether this is worth it.

**Comment by bluetech** [comment]
FYI, there is https://github.com/asottile/flake8-typing-imports written by @asottile. We use it in pytest, at least until the blessed day when we can drop support for Python 3.5.

**Comment by JukkaL** [comment]
@bluetech Nice, I'll need to give it a try.

**Comment by asottile** [comment]
and if ya'll know more version-specific rules to add I'm happy to add them.  I recently learned about 3.6.0 `NamedTuple` deficiencies for example (and now there's two new rules for it!)

**Comment by hauntsaninja** [comment]
We should just drop 3.5 entirely

**Comment by asottile** [comment]
@hauntsaninja this is still relevant for 3.6.x and 3.7.x which introduced typing things in patch versions

**Comment by hauntsaninja** [comment]
That's a good point.
However, typeshed has a policy of only supporting the latest patch version for each minor release and mypy doesn't currently support patch versions for its `--python-version` flag. So not sure that mypy's well positioned to do this well.
Plus I believe mypy doesn't even properly support `typing.OrderedDict` yet. So maybe it is best to rely on flake8-typing-imports :-)
