### ISSUE TITLE
Improve type of `or` operator when used for fallback logic

### ISSUE THREAD

**Issue by jingw** [python/mypy#842]
e.g. this code fails because the `or` statement has type `object`

```
int(os.environ.get('blah blah') or 2)
```

it should generate `Union[str, int]`

**Comment by JukkaL** [comment]
Alternatively, `or` could look at the surrounding type context (in the example, it would be the first argument type of `int`) and use that to guide what to do.

**Comment by ethanhs** [comment]
This works as the original post described (generates `Union[str, int]`) as of at least 0.510 and in master.
