### ISSUE TITLE
Question: Why is TypedDict not compatible with matching Mapping?

### ISSUE THREAD

**Issue by abiro** [python/mypy#8420]
Consider the following code:

```python
from typing import Any, Mapping, TypedDict


class MyDict(TypedDict):
    foo: bool


def my_func_any(a: Mapping[str, Any]) -> None:
    print(a)


def my_func_bool(a: Mapping[str, bool]) -> None:
    print(a)


d: MyDict = {
    'foo': True
}

my_func_any(d)
my_func_bool(d)  # line 21

```

This gives the following error when checked with mypy==0.761 on Python 3.8:

`test.py:21: error: Argument 1 to "my_func_bool" has incompatible type "MyDict"; expected "Mapping[str, bool]"
`

I expected both `my_func_any(d)` and `my_func_bool(d)` to be ok, yet the latter is an error. Is this a bug or am I missing something?

(I posted this originally on [SO,](https://stackoverflow.com/q/60304154/2650622) but had no luck finding an answer there. Hope it's ok to ask here)

**Comment by abiro** [comment]
Got an [answer on SO](https://stackoverflow.com/a/60324417) from @hoefling that I copy here for posterity:

> Quoting the PEP 589:
> 
> Type Consistency
> First, any TypedDict type is consistent with Mapping[str, object].
> 
> [...]
> 
> A TypedDict with all int values is not consistent with Mapping[str, int], since there may be additional non-int values not visible through the type, due to structural subtyping. These can be accessed using the values() and items() methods in Mapping, for example. Example:
> 
```
class A(TypedDict):
    x: int

class B(TypedDict):
    x: int
    y: str

def sum_values(m: Mapping[str, int]) -> int:
    n = 0
    for v in m.values():
        n += v  # Runtime error
    return n

def f(a: A) -> None:
    sum_values(a)  # Error: 'A' incompatible with Mapping[str, int]

b: B = {'x': 0, 'y': 'foo'}
f(b)

```

**Comment by gwerbin** [comment]
Is there a way to indicate that this `TypedDict` must not have additional non-int values? I see `total=True` requires that all stated key/value pairs are present, but I don't see a way to require that *no additional* key/value pairs be present.
