### ISSUE TITLE
Failure to understand optional is not none

### ISSUE THREAD

**Issue by jordan-schneider** [python/mypy#8422]
* Are you reporting a bug, or opening a feature request?
bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```python
# No errors without inner function definition return type
class A:
    pass

def g(x: A) -> A:
    return x

def f(x: Optional[A] = None) -> A:
    if x is None:
        raise ValueError()

    def h():
        return g(x)

    return h()

# Errors when you specify inner function defintion's return type
def j(x: Optional[A] = None) -> A:
    if x is None:
        raise ValueError()

    def k() -> A:
        return g(x)  # Argument 1 to "g" has incompatible type "Optional[A]"; expected "A"

    return k()
```
* What is the actual behavior/output?
Error on given line due to failure to infer that x cannot be None
* What is the behavior/output you expect?
No error
* What are the versions of mypy and Python you are using?
mypy 0.761
Python 3.7.6
  Do you see the same issue after installing mypy from Git master?
Yes
* What are the mypy flags you are using? (For example --strict-optional)
None

**Comment by JelleZijlstra** [comment]
This is #2608.

**Comment by jordan-schneider** [comment]
Why does this only happen if I type the inner function? If I don't type it, does mypy just give up entirely? The problem here isn't the output type, it's the function call.

**Comment by JelleZijlstra** [comment]
Mypy doesn't type-check untyped functions.

**Comment by JelleZijlstra** [comment]
(By default; you can use the `--check-untyped-defs` option to change this behavior.)
