### ISSUE TITLE
"BinaryIO" has no attribute "peek"

### ISSUE THREAD

**Issue by jnsnow** [python/mypy#8433]
- I think this is a bug, but whether it's in mypy or typeshed I do not know.
- I am running with `mypy --strict`.

Mypy version: 0.670

I've got a snippet like this:
```python
with open(self.path, "rb") as infile:
    if infile.peek(2)[0:2] == b'\x1f\x8b':
        ...
```

mypy guesses that this type is BinaryIO, but that it does not have the peek() method. That type is correct with regard to the abstract types of things open() can return, but in this case it's an `_io.BufferedReader`, which does have `peek()`.

**Comment by jnsnow** [comment]
I came across #2166, but this looks more like stub definition problems. This case appears to be that `peek` is really only applicable to a very specific subclass that open() can return to which BinaryIO is not meant to apply, necessarily.

For now, I suppose my workaround is this:
```python
with cast(io.BufferedReader, open(self.path, "rb")) as infile:
    if infile.peek(2)[0:2] == b'\x1f\x8b':
        ...
```

**Comment by JukkaL** [comment]
`BinaryIO` and `open` are defined in typeshed. If you believe that this could be improved, you can file a typeshed issue.
