### ISSUE TITLE
Type issue not found in function call

### ISSUE THREAD

**Issue by MaxNoe** [python/mypy#8434]
Running mypy on this small code example:

```python
def build_greeting(name: str = 'World') -> str:
    return f'Hello {name}!'


def greet(name='World'):
    print(build_greeting(name))


if __name__ == '__main__':
    greet('foo')
    greet(4)
```

results in it reporting "no issues". Although `greet` and thus `build_greeting` are called with an integer.

**Comment by ethanhs** [comment]
Hi, since greet isn't annotated it isn't checked, please see https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code

**Comment by MaxNoe** [comment]
This also shows no issue:
```
from typing import Any


def build_greeting(name: str = 'World') -> str:
    return f'Hello {name}!'


def greet(name: Any = 'World') -> None:
    print(build_greeting(name))


if __name__ == '__main__':
    greet(4)
```

So transitive problems don't seem to be checked.

**Comment by ethanhs** [comment]
Mypy doesn't really do interprocedural analysis like that.
