### ISSUE TITLE
Hi I am  Manas here . This is my first time to take part Google Summer of Code also I don't have any experience in open source . At this time I am thinking to contribute for mypy but want a guidence for open source and project

### ISSUE THREAD

**Issue by manastole03** [python/mypy#8442]
Note: if you are reporting a wrong signature of a function or a class in
the standard library, then the typeshed tracker is better suited
for this report: https://github.com/python/typeshed/issues

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
* What is the actual behavior/output?
* What is the behavior/output you expect?
* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
* What are the mypy flags you are using? (For example --strict-optional)
* If mypy crashed with a traceback, please paste
  the full traceback below.

(You can freely edit this text, please remove all the lines
you believe are unnecessary.)

**Comment by TH3CHARLie** [comment]
For project ideas, check #8373. For general discussion and guidance, check gitter at https://gitter.im/python/typing

**Comment by TH3CHARLie** [comment]
Since gitter is used for general discussion, please close this issue since it's not related to mypy's bug reports or feature requests. Thanks!

**Comment by ethanhs** [comment]
As @TH3CHARLie pointed out, #8373 has project ideas, in addition, please read the [README](https://github.com/python/mypy/blob/master/README.md) and [CONTRIBUTING](https://github.com/python/mypy/blob/master/CONTRIBUTING.md).
