### ISSUE TITLE
PEP 572 Walrus Operator Regex Assignment in Condition

### ISSUE THREAD

**Issue by NickHackman** [python/mypy#8447]
Mypy version: 0.761
Python version: 3.8.1

 #6899 implements `PEP 572`, or at least parts of it, as mentioned in the PR assignments can occur anywhere. Fails with an example similar to [here](https://www.python.org/dev/peps/pep-0572/#id9) with `regex`.

Minimal Example:
```python
import re


TXT = "b"
if (a := re.search(r"a", TXT)) is not None:
    string = a.string
    print(f"{string}")
else:
    print("not in there") #=> not in there
```
mypy message:
```sh
~ λ mypy test.py
test.py:8: error: Item "None" of "Optional[Match[str]]" has no attribute "string"
Found 1 error in 1 file (checked 1 source file)
```
but the type of `a` is not `Optional[Match[str]]` it's `Match[str]` as a result of the if check.

**Comment by JukkaL** [comment]
Yeah, type inference doesn't seem to work correctly here.

As a workaround, you can remove the `is not None` check, and things should work as expected (when using GitHub master, at least):

```py
import re


TXT = "b"
if a := re.search(r"a", TXT):   # <<-- removed the None check
    string = a.string  # No error here
    print(f"{string}")
else:
    print("not in there")
```

**Comment by hauntsaninja** [comment]
Same issue as in #8236
