### ISSUE TITLE
Expanded FuncDef can contain a cycle

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#845]
I've seen `FuncDef.expanded` to have a cycle to the original function definition object when generating stats. I don't have a simple repro yet, but filing this anyway so that I won't forget about it.

**Comment by ilevkivskyi** [comment]
IIUC this is the same as #3503 so that this should be fixed now by #3504

**Comment by JukkaL** [comment]
Hmm not sure if #3504 fixes the original issues -- it fixes stat generation to work when there is a cycle, but it doesn't remove the cycle.

**Comment by JukkaL** [comment]
We haven't seen happen in a long time. Closing since there is also no repro.
