### ISSUE TITLE
native python types are also creation methods, but mypy doesn't know

### ISSUE THREAD

**Issue by sinback** [python/mypy#8455]
Hi, I'm not sure if this is an issue or an implementation choice that I'm just interacting with incorrectly, but I am curious about this.

For native python datatypes, there are creation methods for instances of that type with the same name as a type. The type of those creation methods is actually type, but they are methods too. For example, `float` is a type, but `float(1)` returns a float of value 1. (Similar for str, dict, int, tuple, list, maybe some others.) Therefore you can write the following code, for a polymorphic data deserializer (which I just wrote) and it works:

```
from typing import Generic, TypeVar, Union, cast


NumericTypes = Union[float, int]

T = TypeVar('T')


class NumeralSerializer(Generic[T]):
    def __init__(self, dest_class: NumericTypes):
        self.dest_class = dest_class

    def serialize(self, r: T) -> bytes:
        return str(r).encode()


class NumeralDeserializer(Generic[T]):
    def __init__(self, dest_class: NumericTypes):
        self.dest_class = dest_class

    def deserialize(self, msg: bytes) -> T:
        return cast(T, self.dest_class(msg.decode()))
```

...if you instantiate a NumeralDeserializer(float), it can deserialize bytes representing floats into a float, because the dest_class is float (a type, but one which is also callable in this case). However mypy complains:

```
file.py:22: error: "float" not callable
```

(or error "int" not callable if you get rid of the polymorphism between float and int).

Should the native python datatypes be classified as Callable by mypy? Or would I have to do that explicitly? For now I just have the deserialize() method be like this, and it's fine, but ugly, especially because the example I just gave is valid python which works like it should:

```
     def deserialize(self, msg: bytes) -> T:
         # if/else because mypy doesn't understand that float and int are callable as well as types
         if self.dest_class == float:
             return cast(T, float(msg.decode()))
         else:
             return cast(T, int(msg.decode()))
```

Any thoughts about why this is, or if it should change? I think it should change, but I can also see why it might be confusing sometimes since normally types aren't also callable.

I think the typing module's definition of Callable is probably the same as the type of the thing being "function", so it might be challenging to make a Callable also be a "type" sometimes, but it would be cool if I didn't get this error.

**Comment by JelleZijlstra** [comment]
Your `NumericTypes = Union[float, int]` means a `NumericTypes` is an *instance* of float or int, while what you seem to want is to pass the *types* float or int. For that you want `Union[Type[float], Type[int]]`.

**Comment by sinback** [comment]
Oh, awesome! Thank you so much for your help with what was probably a beginner issue :)
