### ISSUE TITLE
(bug) A Mapping[Any, Any] is a Mapping[str, Any]

### ISSUE THREAD

**Issue by opk12** [python/mypy#8470]
```
$ cat example.py
from typing import *

def mapping_of_any() -> Mapping[Any, Any]:
    return {1: 1}

def mapping_of_str() -> Mapping[str, Any]:
    return mapping_of_any()

keys: List[str] = list(mapping_of_str().keys())
keys[0].lower()
```

```
$ mypy example.py
Success: no issues found in 1 source file
```

```
$  python3 -c 'import example'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/example.py", line 13, in <module>
    keys[0].lower()
AttributeError: 'int' object has no attribute 'lower'
```

Version:
- Fedora 31 + pip's mypy 0.761 + Python 3.7.6
- Fedora 31 + python3-mypy 0.740-2.fc31 from the repo + Python 3.7.6

**Comment by hauntsaninja** [comment]
This is how `Any` works: https://mypy.readthedocs.io/en/stable/dynamic_typing.html#operations-on-any-values (also read the next section on `object`, which might be something you're interested in for your use case). This behaviour of Any is what enables gradual typing and particularly dynamic dynamically-typed code.

**Comment by opk12** [comment]
Thank you. For posterity: see also [PEP 483](https://www.python.org/dev/peps/pep-0483/#summary-of-gradual-typing), [PEP 484](https://www.python.org/dev/peps/pep-0484/#the-any-type), `mypy --warn-return-any`.
