### ISSUE TITLE
Simple example of correct dataclass/attrs wrapping?

### ISSUE THREAD

**Issue by quicknir** [python/mypy#8490]
I've read this page on the docs: https://mypy.readthedocs.io/en/stable/additional_features.html which says that you can't simply write a function like this:

```
def foo(cls):
    return dataclasses.dataclass(cls)
```

And expect things to work properly (same goes for attrs). My question would be, how would one get this to work? Is there a hello world example? My use case is pretty straightforward; I want to simply change some defaults in attrs. For example:

```
def my_dataclass(cls):
    return attr.s(cls, auto_attribs=True)
```

I always want auto_attribs on and it seems pretty annoying to specify it in dozens of places (I'm currently using dataclasses, but I want some of the additional features from attrs).

It looks like pydantic has done it (https://github.com/samuelcolvin/pydantic/blob/master/pydantic/dataclasses.py), but it's hard for me to separate out the bits that are related to their extra functionality, from the bare minimum, so a minimal example would be very helpful.

**Comment by ilevkivskyi** [comment]
The only thing currently supported is aliased import plus `TYPE_CHECKING`. For example:
```python
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from dataclasses import dataclass as foo
else:
    def foo(cls):
        # Actual runtime definition that doesn't change types.
        ...
```

**Comment by quicknir** [comment]
plugins are supported, are they not? And the dataclass and attrs functionality are implemented via plugins? So it would be possible to have a minimal plugin, that simply forwards all the "real work" from the dataclass/attrs plugins? Something like that would practically be enough on its own to handle the simplest cases (like changing defaults) and a great starting point for anything else.

**Comment by ilevkivskyi** [comment]
Sure, you can try writing your own plugin that re-uses the default plugin. This will however requires some familiarity with mypy internals.

**Comment by quicknir** [comment]
I agree, it will be pretty tough, which is why I'm suggesting that a minimal example in the documentation would be incredibly helpful. My guess is that it's probably 100 lines of code but for somebody not involved with mypy, figuring out those 100 lines will take many hours. As opposed to tweaking an existing example which could take fifteen minutes. An example like that on the doc page that I linked would be a huge help to many people.

attrs for example is having a huge discussion about changing defaults, which means many people don't like the defaults, so providing an easy way for people to get the behavior they want is clearly high value (and in this case, doesn't involve any code changes to mypy at all).
