### ISSUE TITLE
Unable to infer tuple type from inline if

### ISSUE THREAD

**Issue by VioletRainbows** [python/mypy#8491]
Bug - The following code will generate:
 `error: Argument 1 to "bar" has incompatible type "object"; expected "Tuple[Any, ...]"`
```python
import sys
from typing import Tuple

def bar(t: Tuple) -> Tuple:
    return t

t = (1, 2) if len(sys.argv) > 1 else (1,)
print(bar(t))
```
https://mypy-play.net/?mypy=latest&python=3.8&gist=0adbffb4d8019987e13f42b149e5b39d

Changing `t` to this will still generate the same error:
`t: Tuple = (1, 2) if len(sys.argv) > 1 else (1,)`

Changing `t` like so will remove the error.
```python
if len(sys.argv) > 1:
    t: Tuple = (1, 2)
else:
    t = (1,)
```
Thus, I believe that this issue exist only with inline if.

**Comment by pr4k** [comment]
Weird, Also If you just replace `len(sys.argv)` with `True`, it works fine
[playground](https://mypy-play.net/?mypy=latest&python=3.8&gist=0adbffb4d8019987e13f42b149e5b39d)

but with any other conditional statement its giving error

**Comment by ilevkivskyi** [comment]
Fixed on master.
