### ISSUE TITLE
[Feature Request / Question] Minimum length List / Sequence

### ISSUE THREAD

**Issue by ayroblu** [python/mypy#8501]
Hi I was wondering if it's possible to create a List/Sequence type with a minimum length
I work with TypeScript a lot too and here's an example TS example: https://stackoverflow.com/questions/49910889/typescript-array-with-minimum-length
(this uses some of the oddities of JavaScript to achieve this I guess)

So I'd like to have an `my_list = AtLeastOneList[str]` which will fail the type check on `my_list[0]`

Just wondering if it's possible!

**Comment by JelleZijlstra** [comment]
This isn't supported by the current type system, and I don't think there are any currently planned features that would allow it.

**Comment by ilevkivskyi** [comment]
I am keeping this open for now because theoretically we can think about overloading `__getitem__()` on literal values. But this is very low priority, so don't be surprised if it will be ultimately closed.

**Comment by ayroblu** [comment]
Yeah no worries, probably can pass around some opaque lists or just runtime
check it in the meantime

**Comment by AlexWaygood** [comment]
Similar idea to #8441

**Comment by hauntsaninja** [comment]
This would require a new type system feature, so should be discussed at https://github.com/python/typing, possibly at https://github.com/python/typing/issues/786
