### ISSUE TITLE
Generic type is not inferred across descriptor class methods

### ISSUE THREAD

**Issue by sjustas** [python/mypy#8516]
Tried to write type stubs for [lazy](https://pypi.org/project/lazy/) package.  `Lazy` provides a descriptor that invokes the underlying method only once and caches the result in the instance.

The inferred type is `<nothing>`, so mypy crashes when checking expressions.

```python
from typing import Any, Generic, Callable, TypeVar

T = TypeVar('T')

class lazy:
    def __init__(self, func: Callable[[Any], T]) -> None: ...
    def __get__(self, inst: Any, inst_cls: Any) -> T: ...

class Haystack:
    @lazy
    def hasNeedles(self) -> bool:
        # some expensive lookup we want to execute only once
        return True

reveal_type(Haystack().hasNeedles)

# checking this expression crashes
x = Haystack().hasNeedles or True
```

```
<...>
note: Revealed type is '<nothing>'
<...>
version: 0.761
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3645, in accept
  File "mypy/nodes.py", line 1736, in accept
  File "mypy/checkexpr.py", line 2029, in visit_op_expr
  File "mypy/checkexpr.py", line 2662, in check_boolean_op
```

If lazy was defined as a function, type gets inferred correctly.
```python
def lazy(func: Callable[[Any], T]) -> T: ...
```

```
note: Revealed type is 'builtins.bool*'
```

**Comment by sjustas** [comment]
Issues that might be related: https://github.com/python/mypy/issues/5738, https://github.com/python/mypy/issues/1317

**Comment by janverb** [comment]
This works as expected if you change `lazy` to inherit from `Generic[T]`. Crashing seems like the wrong response though.

**Comment by ethanhs** [comment]
We definitely should not crash. It might be nice if we have an unused type variable in a method that the class may need to be generic.

**Comment by sjustas** [comment]
Thanks for such a quick response.  You guys rock!
Yeah, a warning that class needs to be generic would've been useful.

**Comment by JukkaL** [comment]
This doesn't crash any more on master. Here's the output I get:
```
$ mypy t/t3.py
t/t3.py:7: error: A function returning TypeVar should receive at least one argument containing the same Typevar
t/t3.py:15: note: Revealed type is "<nothing>"
t/t3.py:18: error: Need type annotation for "x"
Found 2 errors in 1 file (checked 1 source file)
```
