### ISSUE TITLE
Access abstract class property from class method

### ISSUE THREAD

**Issue by olirice** [python/mypy#8532]
When accessing a class property from a class method mypy does not respect the property decorator. 

Steps to reproduce:
```python3
class Example:

    @property
    @classmethod
    def name(cls) -> str:
        return "my_name"

    def name_length_from_method(self) -> int:
        return len(self.name) # succeeds

    @classmethod
    def name_length_from_class_method(cls) -> int:
        return len(cls.name)  # error: Argument 1 to "len" has incompatible type "Callable[[], str]"
```

- Python Version: 3.7.2
- Mypy Version: 0.770
- The issue persisted when installed from master 20f7f2d

**Comment by ErwanDL** [comment]
I would like to try and tackle this issue since it is labelled as a good first issue. @msullivan do you have an idea of where I should start looking ?

**Comment by msullivan** [comment]
Probably in `checkmember.py`

**Comment by Sanchit-Trivedi** [comment]
### Hi @msullivan @olirice . I am a newbie to open source. Please excuse if you perceive this as a dumb question. Saw this issue as it was marked as a good first issue. I ran the given code in python 3.6.9. It is not even working in normal python let alone mypy.  Can you please clarify whether this was supposed to be a mypy specific bug or could be in python3 itself?

**Comment by olirice** [comment]
@Sanchit-Trivedi thank you for catching that. I boiled the example down a little too far!

Here is an updated minimal reproducable example:

```python3
from abc import ABC, abstractmethod


class MyBase(ABC):

    @property
    @classmethod
    @abstractmethod
    def name(cls) -> str:
        raise NotImplementedError()

    def name_length_from_method(self) -> int:
        return len(self.name)  # succeeds

    @classmethod
    def name_length_from_class_method(cls) -> int:
        return len(
            cls.name
        )  # error: Argument 1 to "len" has incompatible type "Callable[[], str]"
```

The valid usage of that abstract base class could be
```python3
# Usage Example
class MyClass(MyBase):
    name = "some_name"

print(MyClass().name_length_from_method()) # prints 9
print(MyClass.name_length_from_class_method()) # prints 9
```

**Comment by ErwanDL** [comment]
@olirice are you sure about the usage of the abstract base class ? In the ABC you define `name` as a property + classmethod, but in your derived class you override it as a class attribute by doing `name = "some_name"` (so technically it runs, but I am not sure it really does what you intended it to).

After doing a bit of research, it actually seems that combining the `@property` and `@classmethod` decorators is not possible the way you did it (https://bugs.python.org/issue20659, https://stackoverflow.com/questions/128573/using-property-on-classmethods). You apparently have to define the property in the metaclass.

**Comment by olirice** [comment]
@ErwanDL you're right. There are a bunch of examples floating around that stack abstractmethod, classmethod, and property decorators, but it doesn't appear to be officially supported.

Thanks for your help and sorry this wasn't the good first issue you were looking for!

**Comment by ErwanDL** [comment]
@olirice no problem, and don't worry there are plenty of issues on this repo for me to dive into :)

**Comment by Sanchit-Trivedi** [comment]
@olirice will have to look up other first issues to fix I guess. Can you suggest any?

**Comment by olirice** [comment]
@Sanchit-Trivedi thank you as well!
wrt suggesting an issue: sorry, I can't be much help there. I'm similarly new to this codebase

**Comment by rominf** [comment]
In 3.9 it's supported: https://docs.python.org/3.9/library/functions.html#classmethod

**Comment by skymandr** [comment]
Can confirm this is still an issue.

**Comment by tilsche** [comment]
I have the same issue. It would be great if this could be reopened (and fixed of course).

**Comment by hauntsaninja** [comment]
Feel free to follow https://github.com/python/mypy/issues/11619 , note that CPython might rollback some of the related changes in 3.9
