### ISSUE TITLE
Mypy is confused about Type[TypeVar(..., bound=)]

### ISSUE THREAD

**Issue by dcbaker** [python/mypy#8535]
python 3.7.6
mypy 0.760

I also tried python 3.8.1 with mypy from git 20f7f2dd71c21bde4d3d99f9ab69bf6670c7fa03, with the same results.

Here is a super simplified version of my case, the real cases takes input to decide which potential to use, and the returns it. Mypy insists that both A and B do not fit the type in the list, and that the return type is wrong as well.

```python
import typing

class Base:
    pass

class A(Base):
    pass

class B(Base):
    pass

BaseBound = typing.TypeVar('BaseBound', bound=Base)

def fun() -> BaseBound:
    potentials: typing.List[typing.Type[BaseBound]] = [A, B]

    return potentials[0]()
```

```console
test.py:20: error: List item 0 has incompatible type "Type[A]"; expected "Type[BaseBound]"
test.py:20: error: List item 1 has incompatible type "Type[B]"; expected "Type[BaseBound]"
```

**Comment by msullivan** [comment]
This is correct, I think. The type variable BaseBound could be `any` subtype of `Base`, so there's no guarantee that `A` and `B` are subtypes of it.

In this particular example, though, there's no real need for a type variable at all. (In general, it doesn't usually make sense to have a type variable that appears only once.) It could just return `Base`. Is there a more fleshed out example where it is needed?

**Comment by dcbaker** [comment]
I guess you're right. I thought in the past when I'd tried that mypy had complained that "A isn't a Base" or something similar.
