### ISSUE TITLE
Incompatible type with Dict[Union, Any]

### ISSUE THREAD

**Issue by dfarley1** [python/mypy#8554]
```
from typing import Any, Dict, Union

def foo(a: Dict[Union[str, int, float], Any]) -> None:
    return

b = {"1": 234}
foo(b)   # error on "b" here
```

I get the following error from Mypy without any specific strictness flags enabled:
`Argument 1 to "foo" has incompatible type "Dict[str, int]"; expected "Dict[Union[str, int, float], Any]"`

Why is this an error? `"1"` is a str and should satisfy the Union key type, right?

* What are the versions of mypy and Python you are using?
Python v3.6, Mypy v0.760

**Comment by jceresini** [comment]
I've noticed a similar issue, reported here: https://github.com/samuelcolvin/pydantic/issues/959#issuecomment-600829091

All of the detail is in that comment, but if you prefer I can include it inline here as well

**Comment by JelleZijlstra** [comment]
This is because `Dict` is invariant. See https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance. You probably want to use `Mapping` for argument types.
