### ISSUE TITLE
Type checking parent class + hasattr for child attr returns overzealous error

### ISSUE THREAD

**Issue by ex-nerd** [python/mypy#8565]
mypy (default config settings) is returning a `has no attribute` error even after an explicit `hasattr()` check.  The following `test.py` reproduces the error:

```python
from typing import ClassVar


class Parent(Exception):
    pass


class Child(Parent):
    code: ClassVar[str] = "Error"


# Returns error
try:
    raise Child()
except Parent as e:
    if hasattr(e, "code"):
        print(f"code: {e.code}")
    else:
        print("no code")

# Works as expected (in this test)
e2 = Child()
if isinstance(e2, Parent):
    if hasattr(e2, "code"):
        print(f"code: {e2.code}")
    else:
        print("still no code")
```

Even more interesting, the scenario in my actual real-world code is more like the `e2` block, and still returns an error ... but doesn't in this example.

**Comment by JelleZijlstra** [comment]
Mypy doesn't currently support type inference using `hasattr`; see #1424. Your second example passes because the type of `e2` is still `Child`, while `e` is `Parent`. You can see this with the `reveal_type()` function.
