### ISSUE TITLE
[Bug] MyPy falsely infers dictionary subtypes

### ISSUE THREAD

**Issue by ActionCactus** [python/mypy#8577]
Given the following class hierarchy:
```python
class AbstractClass(ABC):
  pass

class A(AbstractClass):
  pass

class B(AbstractClass):
  pass
```

And the following code:
```python
class_map = {
  "A": A,
  "B": B
}

some_input:str = get_input()
class_name = class_map[some_input]

class_name()
```

MyPy will produce this error when analyzing the project:
> Cannot instantiate abstract class 'AbstractClass' with abstract attributes ...

This is because MyPy appears to be looking at the contents of the `class_map` variable and inferring the type shared between each of the values.  It then correctly assumes the shared type but incorrectly performs type checks based off of that assumption.

To verify this is actually what is happening you can add `"test": "test"` as a new entry to the dictionary; this will get MyPy to pass because it introduces a new type (string) which breaks the common type check.  Additionally, if you comment out either the A or B line in the dictionary, MyPy will pass.

I'm testing this using MyPy 0.730 with no optional arguments.

**Comment by ilevkivskyi** [comment]
This is an expected behavior, type inference always uses common base class for homogeneous collections. If you want to override it, just use an explicit annotation for `class_map`.
