### ISSUE TITLE
Release process: moving to a release every two months

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#8581]
The mypy core team members responsible for making mypy releases (I, @ilevkivskyi and @msullivan) have been experimenting with less frequent mypy releases (approximately once per two months). Previously our goal was to make a release approx. every 3 weeks, and in practice releases were about monthly.

Another related change is that we will lower the threshold for releasing bug fix releases, in case there is a major regression or a critical bug in a new feature. Two months is too long to wait for a bug fix.

These were our main motivating factors:

*   The rate of new features has been slowing, as mypy is becoming a mature project.
*   Each release takes a significant amount of work and preparation, and much of that is fixed overhead. By lowering the release frequency we'll also lower the overall effort involved.

Later on, I hope that we'll move to a modular typeshed where third-party stubs are released as PyPI packages, instead of being shipped with mypy. Allowing stubs for (most) third party packages to be installed and upgraded independently of mypy would further reduce our dependency on frequent mypy releases.

There are other options that we haven't thought about much yet, such as bringing in more people to who can act as release managers. With one extra release manager we could perhaps make a release every 6 weeks or so.

Thoughts?

**Comment by ilevkivskyi** [comment]
FWIW I think a release every two months would be more reasonable at this stage (and the modular typeshed would make it even more so).

**Comment by Michael0x2a** [comment]
Personally, I'm fine with switching to an 8 week release cadence. But we decide that 6 weeks would be more optimal, lmk -- I'd be happy to volunteer as a release manager :)

**Comment by ethanhs** [comment]
I also would be happy to volunteer as a release manager. I think regardless it would be very good to get typeshed in a place to release to PyPi.
