### ISSUE TITLE
Need type with metadata

### ISSUE THREAD

**Issue by om26er** [python/mypy#8582]
I am writing a tool to remove duplicate parameter validation. Today with mypy, I can write a decorator that ensures that the underlying function is called with parameters that match the types defined in function signature. I want to extend that thing further; I want to be able to implement type validation that would also validate the length of a parameter. For that we'd need a custom type that would allow to provide "length" to it, something like
```
@type_check
def hello(name: String[10]):
    print(name)
```

Note: `String` will be a custom type that supports providing "extra info" to it.

**Comment by ethanhs** [comment]
You can use https://www.python.org/dev/peps/pep-0593/ to do this, with your own tool.
