### ISSUE TITLE
How can I define a typed decorators that call an existing untyped decorators

### ISSUE THREAD

**Issue by davideicardi** [python/mypy#8585]
In my code I use AWS xray decorator (https://github.com/aws/aws-xray-sdk-python#capture).
The problem is that all functions decorated with xray are not considered "typed", and mypy ignore all these function. It is like the function is declared with Any parameters.
I think the reason is because xray decorator doesn't maintain the function signature. Correct?

What do you suggest to use both xray decorator and mypy?
I'm thinking to redefine the decorator following the guide here https://mypy.readthedocs.io/en/stable/generics.html#declaring-decorators but not sure how can I call AWS xray internally. Any help appreciated.

thanks

**Comment by hauntsaninja** [comment]
You could make your own typed wrapper for the untyped decorator
