### ISSUE TITLE
Namedtuple  typed as Tuple when called immediately after creation

### ISSUE THREAD

**Issue by kchaplick** [python/mypy#8588]
* Are you reporting a bug, or opening a feature request?
Bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate if you try to simplify your case to a minimal repro.

```
def __init__(self, user: User, account: Account):
    self.request: NamedTuple = namedtuple("Request", ("user", "account"))(user,account)
 ```
* What is the actual behavior/output?

```
error: Too many arguments for "tuple"
error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "NamedTuple")
```

* What is the behavior/output you expect?
mypy should see this as a NamedTuple

* What are the versions of mypy and Python you are using?
mypy 0.641
Python 3.7

* What are the mypy flags you are using? (For example --strict-optional)

```
ignore_missing_imports = true
follow_imports = skip
```

* If mypy crashed with a traceback, please paste
  the full traceback below.

(You can freely edit this text, please remove all the lines
you believe are unnecessary.)

**Comment by mintchkin** [comment]
Minimal examples:

```python
from collections import namedtuple

# this works
T = namedtuple('T', ('a',))
t = T(1)

# these do not
u = namedtuple('U', ('a',))(1)  # error: Argument 1 to "tuple" has incompatible type "int"; expected "Iterable[Any]"

v = namedtuple('V', ('a',))(a=1)  # error: Unexpected keyword argument "a" for "tuple"
```

Playground: https://mypy-play.net/?mypy=latest&python=3.8&gist=3d1658c6c867859e935fde58bec7f179

**Comment by ilevkivskyi** [comment]
Named tuple is a special form and should be used according to the docs.
