### ISSUE TITLE
Metaclass __call__ ignores return type

### ISSUE THREAD

**Issue by DevilXD** [python/mypy#8595]
* Are you reporting a bug, or opening a feature request?
Bug/Feature request ?

* Minimal repro:
```py
class BaseMeta(type):
    # make it so that constructing a class' instance will return a string instead
    def __call__(cls, *args, **kwargs) -> str:
        return "test"

class Base(metaclass=BaseMeta):
    pass

inst = Base()
reveal_type(inst)  # revealed type is 'Base' instance
print(inst)  # prints 'test' at runtime
```

* What is the actual behavior/output?
As explained by the comments in the example above

* What is the behavior/output you expect?
Revealed type would be `str`, as the `__call__` return type specifies.

* What are the versions of mypy and Python you are using?
* Do you see the same issue after installing mypy from Git master?
Python 3.8. Happens on the current Git master, and the previous version of MyPy I was using (it was like 0.76X).

* What are the mypy flags you are using? (For example --strict-optional)
Default configuration for VSCode, which would be:
`follow-imports=silent`
`ignore-missing-imports`
`show-column-numbers`
Personal addition:
`check-untyped-defs`

I know this is a rather non-standard usage case (as the `__call__` normally would return a class instance), but I figured this should be relatively easy to support.

**Comment by ilevkivskyi** [comment]
It is unlikely this will be ever supported, so doesn't really make sense to keep this open.

**Comment by DevilXD** [comment]
Why is that so? Can I get a better explanation? Inspecting the metaclass for the `__call__` return type should be easy to do, I'd think =/

**Comment by DevilXD** [comment]
@ilevkivskyi Can you please respond to this?

**Comment by DannyPinghero** [comment]
I'm doing a very similar thing - curious if there is any further information available as well.
