### ISSUE TITLE
Error reported on an Union into a NamedTuple

### ISSUE THREAD

**Issue by dvarrazzo** [python/mypy#8599]
Running mypy on the following snippet:

```python
from typing import NamedTuple, Union

class QueryPart(NamedTuple):
    index: Union[int, str]
```

returns the following error:

```
$ mypy mypybug.py 
mypybug.py:4: error: Incompatible types in assignment (expression has type "Union[int, str]", base class "tuple" defined the type as "Callable[[Tuple[Union[int, str], ...], Any, int, int], int]")
Found 1 error in 1 file (checked 1 source file)
```

Tested with python 3.6 and 3.7, mypy 0.770 and master

**Comment by JelleZijlstra** [comment]
The problem isn't the `Union`, it's that `index` already exists as a method on tuples, so you're creating an incompatible override. You should either rename your attribute or `# type: ignore` it if you don't want to, at some cost to type safety.

**Comment by dvarrazzo** [comment]
D'oh, you are right :) Sorry for the noise.
