### ISSUE TITLE
ForwardRef's and recursive type aliases are still broken

### ISSUE THREAD

**Issue by ulidtko** [python/mypy#8609]
The minimal Hutton razor doesn't typecheck.

```py
# hutton.py

from typing import Union, Tuple

HuttonRazor = Union[
    int,
    Tuple['HuttonRazor', 'HuttonRazor'],
]
```

I've tested on these git tags with Python 3.8.2:
 * v0.761
 * v0.760
 * v0.750
 * v0.740
 * v0.730
 * v0.720
 * v0.710
 * v0.701
 * v0.700

None of them work; all emit an **error** of *possible cyclic definition*:

> hutton.py:5: error: Cannot resolve name "HuttonRazor" (possible cyclic definition)
> hutton.py:7: error: Cannot resolve name "HuttonRazor" (possible cyclic definition)

Which is bitterly upsetting, after having read:
 * [the `typing.ForwardRef` docs][1],
 * [StackOverflow hits][2] for the error message,
 * the [mypy FAQ][3] (doesn't <kbd>Ctrl</kbd><kbd>F</kbd> `cyclic` anything).

The error message of v0.710 was much better:
> hutton.py:5: error: Recursive types not fully supported yet, nested types replaced with "Any"

To be explicit: my expectation is no error. I'm following the `typing` module doc (and ergo, PEP 484).

I'd also searched among GitHub issues off course. #7069 is closed as "known limitation". #731 is the canonical f̶i̶v̶e̶-̶y̶e̶a̶r̶-̶o̶l̶d̶ issue where actual discussion & development of recursive types support happen. I can remember looking at it ~2 years ago, still open today.

The special prize goes to #6740 — "Stop saying mypy is beta software?". Haha, yes. Nice joke. Save it for tomorrow.

[1]: https://docs.python.org/3/library/typing.html#typing.ForwardRef
[2]: https://stackoverflow.com/questions/59739516/possible-cyclic-definition-when-extending-a-base-that-is-generic-in-stubs-but-no
[3]: https://mypy.readthedocs.io/en/stable/common_issues.html

**Comment by ethanhs** [comment]
>Haha, yes. Nice joke.

There is no need to be rude. Consider this a warning to not be rude further.

Just because mypy doesn't support what you want doesn't mean it isn't ready to be used in production. Regardless this is a duplicate so I am closing.
