### ISSUE TITLE
bytes/ByteString incompatibility

### ISSUE THREAD

**Issue by srittau** [python/mypy#8610]
This came up in python/typeshed#3890. According to the typing documentation, [`bytes` can be used instead of `ByteString` in argument types](https://docs.python.org/3/library/typing.html#typing.ByteString). Nevertheless, mypy 0.770 (Python 3.8.2) does not accept the following:

```python
from typing import ByteString

x: ByteString = b""

def foo(y: bytes) -> None:
    pass

foo(x)
```

This was previously discussed in #4871 and #7714, but it still seems like an open issue.

**Comment by erictraut** [comment]
This appears to have been fixed, probably as part of the PEP 688 effort. I can't repro the problem with the latest versions of mypy.

**Comment by JelleZijlstra** [comment]
ByteString is deprecated now anyway and shouldn't be used.
