### ISSUE TITLE
Cannot ignore untyped exception with `as e` syntax

### ISSUE THREAD

**Issue by bitbier** [python/mypy#8612]
We are trying to utilize mypy in order to introduce strict type checking in our code. However, there are some libraries that we need to add `# type: ignore` that don't have any type stubs on. This works most of the time, but I believe we ran into some edge cases where this doesn't work.

Consider the following code (`test.py`):

```
import jsonschema  # type: ignore

schema = {
    "type": "object",
    "properties": {"price": {"type": "number"}, "name": {"type": "string"}},
}

try:
    jsonschema.validate(instance={"name": "Eggs", "price": 34.99}, schema=schema)  # type: ignore
except jsonschema.ValidationError as e:  # type: ignore
    print(str(e))  # type: ignore
```

Running mypy on above code:

```
$ mypy test.py --disallow-any-expr
test.py: error: Expression has type "Any"
Found 1 error in 1 file (checked 1 source file)
```

Results in the entire file having an `Any` expression without a line number representing where the issue is occuring.

However, if I don't use the exception `e`:

```
import jsonschema  # type: ignore

schema = {
    "type": "object",
    "properties": {"price": {"type": "number"}, "name": {"type": "string"}},
}

try:
    jsonschema.validate(instance={"name": "Eggs", "price": 34.99}, schema=schema)  # type: ignore
except jsonschema.ValidationError:  # type: ignore
    print("not used")
```

mypy with the strict flag will report success:

```
$ mypy test.py --disallow-any-expr
Success: no issues found in 1 source file
```

I have been trying to comb through the documentation and also github issues for something similar, but I haven't come across this specific use case or how to workaround it. I'm able to add a `type: ignore` to the top of the file, but then I lose type checking for the rest of the file. I guess another work around would also be to add a module to dump all of the non-mypy specific usage and then just ignore those files.

Is this currently expected behavior for this flag?

mypy version: **0.77**
python version: **3.7.5**

**Comment by msullivan** [comment]
This one wound up being pretty simple, so I'm gonna land a fix in a minute.

I will say, though, that --disallow-any-expr is generally too strict to be useful.
