### ISSUE TITLE
How to express the meaning that `return a list just only have 2 element` , 

### ISSUE THREAD

**Issue by 625781186** [python/mypy#8615]
![image](https://user-images.githubusercontent.com/30521429/78107417-fe774f80-7427-11ea-959a-bf0466661d55.png)

You can't express the meaning that `return a list just only have 2 element` , 

So , I think need 
1. 
`List[Union[str, int ], ... ]` express the meaning that `return a list have Uncertain number element` 

and 
2. 
`List[str, int]` express the meaning that `return a list just only have 2 element`

**Comment by 625781186** [comment]
https://github.com/python/mypy/issues/4791

**Comment by MrGreenTea** [comment]
`List` might not be the type you want here then? `Tuple` is for fixed-size, `List` is mutable and should be used for things where the length is expected to be variable.

**Comment by 625781186** [comment]
> `List` might not be the type you want here then? `Tuple` is for fixed-size, `List` is mutable and should be used for things where the length is expected to be variable.

That's a shame.

**Comment by 625781186** [comment]
> `List` might not be the type you want here then? `Tuple` is for fixed-size, `List` is mutable and should be used for things where the length is expected to be variable.

That's a shame.
