### ISSUE TITLE
Update fastparse for 3.9 AST changes

### ISSUE THREAD

**Issue by msullivan** [python/mypy#8627]
In 3.9.0a5, some changes landed to the AST for subscripting (https://github.com/python/cpython/pull/9605). We need to support them.

This first got reported in #8614 as "syntax error in type comment", which is pretty bad, also! We should clean up that error message when we fix this.

**Comment by cooperlees** [comment]
If it helps, I've got a failing 3.9.0a5 here: https://travis-ci.org/github/cooperlees/aioexabgp/jobs/673829413
- If not, please ignore. Subscribing.

**Comment by gvanrossum** [comment]
Do you need help for this? I reviewed the CPython change and I can probably figure out how to do this easily.

**Comment by jaraco** [comment]
I'm attempting to test against Python 3.9b1, but the [test suite is failing](https://dev.azure.com/jaraco/path/_build/results?buildId=668&view=logs&j=fe32783c-2eeb-5f5c-e434-5dc06b98b497&t=0d99eb90-1334-5367-1020-c4e7bb0592c9) with the "syntax error in type comment". Does this patch fix it? Is a release planned?

**Comment by JelleZijlstra** [comment]
@jaraco on another issue Jukka said that another release is planned in a week or so.

**Comment by jaraco** [comment]
I see v0.780 includes the fix for the issue.
