### ISSUE TITLE
Document how to reuse the type of a variable

### ISSUE THREAD

**Issue by ksamuel** [python/mypy#8630]
I'm currently trying to type an API wrapping `sys.excepthook`. The type required for a handler to be set to `sys.excepthook` is defined as followed in typeshed:

```
excepthook: Callable[[Type[BaseException], BaseException, TracebackType], Any]
```

See: https://github.com/python/typeshed/blob/95cafc0b7c276964f1d74d8ff9cd6d02b7f0cd12/stdlib/2/sys.pyi#L93

I can import `sys.excepthook`, but I cannot use it as a type, not can I use `Type[sys.excepthook]`. Still, I wish to reuse the type definition from the stub, instead of copying manually in my own code, and I could not find a way to do that in the documentation.

**Comment by JukkaL** [comment]
Reusing a type from a stub is not supported, unless the stub defines a type alias for the type. `Type[x]` means a class object, not an arbitrary type such as `Callable`.
