### ISSUE TITLE
strict=False in config file mistakenly sets strict=True

### ISSUE THREAD

**Issue by matangover** [python/mypy#8633]
Starting with mypy 0.770, putting `strict=False` in mypy.ini causes mypy to behave as if it was 
`strict=True`. In fact, the value of `strict` is not checked at all.

Inadvertently caused by https://github.com/python/mypy/pull/8192

**Comment by scop** [comment]
That mirrors the behavior of `--strict` -- there's no `--no-strict` either, one just specifies strict or not.

I do agree it's kind of weird like that in the config file, and I think it would be fairly easy to change. Just a sec.

**Comment by scop** [comment]
Note however that before 0.770 and #8192, strict was not allowed in config files at all, so in that sense this is not "caused" by that change.

**Comment by matangover** [comment]
Thanks for the super quick fix!!
