### ISSUE TITLE
[Feature Inquiry] Runtime @overload information

### ISSUE THREAD

**Issue by Tinche** [python/mypy#8639]
Hello,

the @overload functionality is very useful. It would be even more useful if we could access the overloads programmatically, during runtime. To give a little context, I'm the author of [cattrs](https://github.com/Tinche/cattrs), which uses runtime type information heavily for de/serialization purposes.

For example, given a class like:
```
from typing import overload
import attr


@attr.s
class Test:
    @overload
    def a(self, b: int) -> int:
        ...

    @overload
    def a(self, b: float) -> float:
        ...

    def a(self, x):
        return x
```

It would be amazing if `Test.a` (or just `Test`) could be inspected for all overloads. As far as I can see, this information gets completely lost at runtime. I'm not sure what amount of black magic would make this possible?

I would be happy to go into more detail about why this would be very useful to be able to do if the authors are unconvinced of its utility.

**Comment by ethanhs** [comment]
This would be more fitting for https://github.com/python/typing. FWIW, I don't this is feasible (without re-parsing the source code), because the overloaded definitions are discarded after the AST is generated.
