### ISSUE TITLE
Figure out how to detect unused imports

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#865]
Linters like `flake8` can detect unused imports, but this actually doesn't work with PEP 484 compliant code, as some of the uses can be in comments that are not seen by the linter. For example:

```
from typing import List   # 'List' imported but unused 
x = []  # type: List[int]
```

We should either try to get linters fixed (file issues) or allow mypy to detect these kinds of errors reliably.

**Comment by o11c** [comment]
Not just unused imports, but all unused variables (that do not start with _).

I think it's best to make mypy do this, controlled via a `-W` option. But rewriting the parser is going slower than I expected, I keep restarting when I see a better way ...

Related: #465

**Comment by pradyunsg** [comment]
What needs to be done to help move this forward?

**Comment by ilevkivskyi** [comment]
> What needs to be done to help move this forward?

Make a PR (assuming you are confident enough, since this might be not a small change).

**Comment by ilevkivskyi** [comment]
(Btw, latest versions of popular linters already understand/will soon understand type comments).

**Comment by pradyunsg** [comment]
> Make a PR (assuming you are confident enough, since this might be not a small change).

Any pointers for where to get started on this?

> (Btw, latest versions of popular linters already understand/will soon understand type comments).

Oh, is this due to the work on typed-ast, which would get adopted by the linters?

**Comment by ethanhs** [comment]
I believe linters now can detect PEP 484 type comments without issue (see e.g. https://github.com/PyCQA/pyflakes/pull/400), so I think we can close this?

**Comment by jdahlin** [comment]
Would be nice if mypy could support this, its one less tool is needed to lint a code base.

This doesn't seem possible with the current plugin API, perhaps extending the plugin API to expose enough information to make this possible in third-party code would be good enough.
