### ISSUE TITLE
Mypy checks all the files in the project when I specify to check a single file

### ISSUE THREAD

**Issue by nazariyv** [python/mypy#8652]
* Are you reporting a bug, or opening a feature request?
bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

I have created a txt file that mypy reads from to know which files to check `mypy @mypy_files.txt`. That file points to a single `routes.py` file (Flask, this file uses a Blueprint). Mypy checks ALL file in the project. If I run `mypy path_to_file` I get the same behaviour. I have a different non-Flask file, and it has correct behaviour. Here is what the `mypy_files.txt` looks like:

```
backend/app/core/bond_heatmap
backend/app/project/bond_heatmap/routes.py
inv_public/src/handler/bond_heatmap.py
backend/tests/backend/app/core/bond_heatmap/test_heatmap.py
```

* What is the actual behavior/output?
Mypy checks the whole repo instead of a single file

* What is the behavior/output you expect?
Check single file

* What are the versions of mypy and Python you are using?
`Python@3.7`
`mypy@0.77.0`

  Do you see the same issue after installing mypy from Git master?

Same on `mypy 0.770+dev.e86adb116ecf79f22dc8eb112ce1a6bbc0fa9746`

* What are the mypy flags you are using? (For example --strict-optional)
no flags. just `mypy @mypy_files.txt`

* If mypy crashed with a traceback, please paste
  the full traceback below.
-

**Comment by JukkaL** [comment]
By default mypy follows imports in files. I.e., if you pass it file `x.py` and it imports `y.py`, mypy will also type check `y.py`. This can be changed, however, and it's explained in the docs: https://mypy.readthedocs.io/en/stable/running_mypy.html#following-imports

If this doesn't help, we can reopen this issue.
