### ISSUE TITLE
Reorganise wiki and README.md information about testing process

### ISSUE THREAD

**Issue by davidzwa** [python/mypy#8659]
#### Feature request: 
Reorganise wiki, docs and test information about tests.
#### No code involved
Just the Github wiki, docs page and README.md (add a TESTING.md?)
#### Expected outcome: 
a) add a Wiki page for developers about how to test with `pytest` (pragmatic info about process or 'how-to')
b) move testing from README.md to TESTING.md to be more clear about 'how to test' and only then 'what is the syntax'. Explain how to test and contribute, f.e. what is the testing policy (coverage?) and avoid leaving the developer to figure it out or having to wait for someone to explain

#### The request
I'd like to have go-ahead to work on this:
- TESTING.md
- Add 'how-to testing' Wiki page for developers
- Restructure the data-driven testing explaination, so it becomes more to the point. (I had to look around for examples, which can be enumerated and listed in the wiki/.md page I'm suggesting)

**Comment by hauntsaninja** [comment]
(Not a maintainer, and maybe I'm misunderstanding, but) I feel like https://github.com/python/mypy/blob/master/test-data/unit/README.md#running-tests-and-linting does a pretty good job of providing pragmatic, how-to pytest commands. It's true that this testing README file does feel less discoverable than it should be.

**Comment by davidzwa** [comment]
It does indeed! I wanted to put everything in a separate, recognizable section instead of under a document which should only be 'quick info'

**Comment by ethanhs** [comment]
Yeah I do think the README could use some work. I think the current order of things buries at lot of important information (people don't read far into READMEs). At a minimum a table of contents at the top would be good IMO.

@JukkaL @msullivan thoughts?

**Comment by davidzwa** [comment]
To summarize:
- Add TESTING.md
- Add [Testing Guide](https://github.com/python/mypy/wiki/) section (**don't** bury under Developer Guides.)
- Refer to TESTING.md in README.md (cleanup README.md)

**Comment by davidzwa** [comment]
@ethanhs shall I progress? I don't think it is much work and I will draft the PR so they can still jump in later.

**Comment by ethanhs** [comment]
I think I want to hear from @JukkaL or another core dev first, this would be a significant change.

**Comment by davidzwa** [comment]
(I'm suggesting to create a PR which can be aborted if so required: I have to finish my contributions report for my uni project soon.)

**Comment by ethanhs** [comment]
Sure if you want to make a PR, go ahead.

**Comment by davidzwa** [comment]
I'll add a small WIKI page with a recollection of the knowledge I missed before and during developing tests. This could really help newcomers progress.

After that I'll let it await approval.

**Comment by davidzwa** [comment]
PR is #8680
