### ISSUE TITLE
QUESTION/HOWTO: Check if callable is bound to specific base class?

### ISSUE THREAD

**Issue by CoenSchalkwijk** [python/mypy#8667]
Base class is type `A`, I have no control over this code

Note:
* func_A can have all kinds of parameters and/or return values

```
class ClassA(A):
    def func_A(a_param: str) -> str: ...

class ClassB(B):
    def func_B(b_param: str) -> str: ...

def func_C(c_param:str) -> str: ...

def func_D(d_param: ? ) -> str: ...

inst_a = ClassA()
inst_b = ClassB()

# What I think I need:
func_D(inst_a.func_A)  # OK, callable, bound, from class instance derived from A 
func_D(inst_b.func_B)  # FAIL: callable, bound, but not from class instance derived from A
func_D(func_C)  # FAIL: callable, but not bound.
```

Is this something I can already do with mypy or is this a silly expectation?

**Comment by JelleZijlstra** [comment]
This sounds similar to python/typing#706, and like Guido in that issue I'm not sure I see what you're trying to achieve here.

**Comment by AlexWaygood** [comment]
I'm closing this issue due to lack of response from OP
