### ISSUE TITLE
Mypy incorrectly infers the dict value types as "object"

### ISSUE THREAD

**Issue by layoaster** [python/mypy#8673]
* Are you reporting a bug, or opening a feature request?
 bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

Given the following code:
```python
def projection(self, length: int, start_year: Optional[int] = None) -> List[PricingProjection]:
        init_year: int = start_year or datetime.now().year
        projection = []

        for year in range(init_year, init_year + length):
            projection.append(
                {
                    "year": year,
                    "annual_price": self.annual(year),
                    "monthly_price": self.monthly(year),
                }
            )

        return projection
```
And;
```python 
PricingProjection = TypedDict(
    "PricingProjection", {"year": int, "annual_price": Decimal, "monthly_price": Decimal}
)
```
and `annual` and `montly` are annotated as:
```python
def monthly(self, policy_year: Optional[int] = None) -> Decimal:
def annual(self, policy_year: Optional[int] = None) -> Decimal:
```

* What is the actual behavior/output?
```
Incompatible return value type (got "List[Dict[str, object]]", expected "List[PricingProjection]")  [return-value]
```
* What is the behavior/output you expect?
Mypy Infer that the type of `projection` is exactly `List[PricingProjection]`
* What are the versions of mypy and Python you are using?
mypy 0.770
Python 3.7.6

* What are the mypy flags you are using? (For example --strict-optional)
```
check_untyped_defs = True
disallow_any_generics = False
ignore_missing_imports = True
implicit_reexport = False
strict_equality = True
no_implicit_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
warn_unreachable = False
warn_no_return = False
```

Lastly, the following annotation produce the same result:

```python
def projection(self, length: int, start_year: Optional[int] = None) -> List[Dict[str, Union[Decimal, int]]]:
```

**Comment by ilevkivskyi** [comment]
Not a bug. You should use `PricingProjection(year=..., ...)` instead of the dict literal (it will behave the same at runtime).

Technically it is possible to implement this kind of backtracking for type inference, but is really hard and not worth the effort IMO.
