### ISSUE TITLE
Add Code_of_Conduct.md

### ISSUE THREAD

**Issue by csharp489** [python/mypy#8678]
No Code_of_Conduct.md file is present.
As a open sourec Contributor, I would like to add a Code_of_conduct.md file in this project.

**Comment by ethanhs** [comment]
Hi, as a project under the Python organization I believe we abide by the PSF code of conduct, I'd be happy to review a PR that adds a CODE_OF_CONDUCT.md file pointing to the PSF code of conduct.

**Comment by EkanshMangal** [comment]
Hello Sir, If issue is still open
Can i fix this issue?

**Comment by hauntsaninja** [comment]
Closing as per discussion in https://github.com/python/mypy/pull/8690
