### ISSUE TITLE
Mypy loses track of explicit variable typing with builtin classes

### ISSUE THREAD

**Issue by reinhrst** [python/mypy#8684]
* Are you reporting a bug, or opening a feature request? Bug
* Please insert below the code you are checking with mypy

```
import typing as t

constructor: t.Type[t.FrozenSet]
reveal_type(constructor)
constructor = frozenset
reveal_type(constructor)
constructor(range(10))
```
 output:

```
test.py:4: note: Revealed type is 'Type[builtins.frozenset[Any]]'
test.py:6: note: Revealed type is '<nothing>'
test.py:7: error: <nothing> not callable
Found 1 error in 1 file (checked 1 source file)
```

It seems that the assignment of `frozenset` destroys any type information to `None`.

If I try the same with a custom class (rather than `frozenset`) all works fine.

If I do the type hint and assignment in 1 line, it works fine: `constructor: t.Type[t.FrozenSet] = frozenset`, however since the actual code is more complex, this is not possible.

Even just saying `constructor = frozenset` without the initial typehint, leaves a type on the constructor: `'def [_T_co] (iterable: typing.Iterable[_T_co`1] =) -> builtins.frozenset[_T_co`1]'`

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
Python 3.8.2, mypy 0.770 & master (mypy-0.770+dev.b8bdc26127d7b7f3ac42b308350b0ec0fba01fcc)
* What are the mypy flags you are using? (For example --strict-optional)
None

**Comment by ilevkivskyi** [comment]
This works correctly on master.
