### ISSUE TITLE
`reveal_type` shows incompatible type for argument, but mypy doesn't throw `error:`

### ISSUE THREAD

**Issue by DBCerigo** [python/mypy#8691]
I have code _along the lines_ of:

```
class MyClass():

    def process(self) -> None:
        x = func_int()
        reveal_type(x)
        func_str(x)

    def func_int(self) -> int:
         return 1

    def func_str(self, s: str) -> str:
         return s
```

The code above will (to state the obvious) give:
```
note: Revealed type is 'builtins.int'
error: Argument 1 to "func_str" of "MyClass" has incompatible type "int"; expected "str"
```

In code that I am working on, which is significantly more complex, I have the same situation in that `reveal_type` correctly gives a type for a var, which is incompatible with a subsequent function call, but in my case the `error:` is not thrown. 

My code looks like:

```
class MyRealClass(SubClass):

...

    def some_func(self) -> None:

    ...

                    reveal_type(alert)
                    self.publish_alert(alert)

...

    def publish_alert(self, alert: my_project.common.dtypes.alert.Alert) -> None:

    ...
```
and gives 
```
note: Revealed type is 'my_project.common.models.alert_models.Alert*'
```
but no `error:`. I understand that the `*` implies it is an inferred type, but I would assume that doesn't mean it won't be used for type checking.

Given that `reveal_type` knows the type of the argument correctly, and that that type doesn't match the signature for the function on the subsequent line, it seems surprising to me that mypy is, for whatever reason, not throwing the corresponding `error:`. And I can't think/don't know of any other ways to dig into this. 

Any ideas on how this might be happening, or other ways to debug it? Thanks :)

**Comment by JelleZijlstra** [comment]
I'm guessing that mypy doesn't find exactly what the type of `self` or `self.publish_alert` is. You can check this with `reveal_type(self.publish_alert)`.

**Comment by DBCerigo** [comment]
Thanks for the tip. It further confirms the odd behaviour:
```
reveal_type(alert)
reveal_type(self.publish_alert)
self.publish_alert(alert)
```
--> 
```
note: Revealed type is 'myproject.common.models.alert_models.Alert*'
note: Revealed type is 'def (alert: myproject.common.dtypes.alert.Alert)'
```

**Comment by DBCerigo** [comment]
My suspicion is it must be to do with a mypy plugin, as I'm assuming this isn't a bug in mypy core. Closing unless I can reproduce without plugins. 

Feel free to reopen if thinking it might actually be pertinent to mypy.
