### ISSUE TITLE
Feature requests: recognise that some types always evaluate to False

### ISSUE THREAD

**Issue by reinhrst** [python/mypy#8692]
* Are you reporting a bug, or opening a feature request?
Feature Request
* Please insert below the code you are checking with mypy,
```
import typing as t


class NotPresent:
    def __bool__(self) -> t.Literal[False]:
        return False


x: t.Union[NotPresent, t.Sequence[int]] = [1]
reveal_type(x)
if x:
    print(x[0])
```
* What is the actual behavior/output?
`test.py:12:11: error: Value of type "Union[NotPresent, Sequence[int]]" is not indexable`
* What is the behavior/output you expect?
The `if x` branch should recognise that x cannot be of type `NotPresent` (as it would do if it was `None` rather than `NotPresent`)

* What are the versions of mypy and Python you are using?
0.770 & master
* What are the mypy flags you are using? (For example --strict-optional)
None

**Comment by povilasb** [comment]
This is awesome.
A funny thing is that I posted exactly the same question on Stackoverflow yesterday :)

If I were to contribute some of my precious time, how would I approach this problem given I haven't worked with `mypy` source code?

**Comment by hauntsaninja** [comment]
Might need some discussion, since you could subclass NotPresent to do something else.

**Comment by reinhrst** [comment]
I think that (rightly) mypy does not allow you to subclass `NotPresent` with a `__bool__` method with a more permissive returntype than `t.Literal[False]`, right?

**Comment by hauntsaninja** [comment]
Yup, you're right. I believe this is also fixed on master by https://github.com/python/mypy/pull/9297
