### ISSUE TITLE
[Feature Request] Choices

### ISSUE THREAD

**Issue by docyx** [python/mypy#8694]
**Feature Request: Choices**

My proposal is the introduction of choices, which can be annotated using brackets `[` `]` with its choices inside.

For example, the builtin function `open` has 11 different possibilities in its `mode` argument ("r", "r+", "rb", "w", etc...)

We can use choices annotation in this case:

```py
def open(..., mode: ["r", "rb", "r+", "w", ...] = "r", ...)
```

Another example with a log mode variable:

```py
log_mode: ["INFO", "WARN", "ERROR"] = "INFO"

print(f"{log_mode}: {log_msg}")
```

If we were to assign a value not inside the options, for example from the example above with the `log_mode`, let's say `"FOOBAR"`, mypy would send a warning.

Just an idea.

**Comment by ethanhs** [comment]
You can do this at the type level with `typing.Literal`. https://www.python.org/dev/peps/pep-0586/#shortening-unions-of-literals

**Comment by Baghdadev** [comment]
Terible Idea.
