### ISSUE TITLE
The generic type of an inner function cannot be made to match the generic type of an enclosing function

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#8696]
With the following example:

```python
from typing import Callable, Generic, Type, TypeVar

XType = TypeVar('XType', bound=int)


class C(Generic[XType]):
    def f(self, x_init: XType) -> XType:
        return x_init


def combinator(c_cls: Type[C[XType]]) -> Callable[[C[XType], XType], XType]:
    old_f = c_cls.f

    def new_f(c: C[XType], x_init: XType) -> XType:
        return old_f(c, x_init)

    return new_f
```

MyPy 0.910 says:
```
a.py:15: error: Incompatible return value type (got "XType", expected "XType")
a.py:15: error: Argument 1 has incompatible type "C[XType]"; expected "C[XType]"
a.py:15: error: Argument 2 has incompatible type "XType"; expected "XType"
```

**Comment by msullivan** [comment]
Ugh! This is a bad error message, and pretty confusing.

I think that the issue here is that the inner function binds those type variables separately (but maybe it shouldn't?), which is why there is a type mismatch: they are different `XType`s. But it is definitely a bug in the error message!

**Comment by NeilGirdhar** [comment]
@msullivan Thanks for taking a look.  I ended up redesigning this, so it's not a priority for me anymore.

However, thank you, MyPy people, for the great project.  It's really useful!

**Comment by NicolaDonelli** [comment]
Sorry for resuming this old issue but I just stumbled in (what I believe is) this same situation and I could not find a solution.

My code is:
```
from abc import ABC, abstractmethod
from typing import TypeVar, Iterable, Iterator

T = TypeVar('T')


class MyABC(ABC):

    @property
    @abstractmethod
    def items(self) -> Iterable[T]: ...

    def __iter__(self) -> Iterator[T]:
        for item in self.items:
            yield item
```

and, while running mypy command (version 0.910), I got: 
```
 error: Incompatible types in "yield" (actual type "T", expected type "T")
```

I admit I am not completely sure it is the same issue as the one reported by @NeilGirdhar and that @msullivan suggested being due to the fact that "they are different T type", but it seemed so and I couldn't find a way to change my code to avoid this error. 
In particular, I need to bind the type of the elements in 'items' to the YieldType of '__iter__' , but I didn't find a good solution to do that.

**Comment by NeilGirdhar** [comment]
@NicolaDonelli  I'm not sure, but did you try inheriting from `Generic[T]`?

**Comment by NicolaDonelli** [comment]
@NeilGirdhar, nope I didn't try before and effectively your proposed solution works like a charm, thanks a lot!

For what it takes the issue about the error messate, would you prefer me to open it or you'd prefer to open it yourself?

**Comment by NeilGirdhar** [comment]
> would you prefer me to open it or you'd prefer to open it yourself?

I'm not opening it.

**Comment by NeilGirdhar** [comment]
Looks like the error message is fixed!
