### ISSUE TITLE
Bug: Not understand else in try except block

### ISSUE THREAD

**Issue by heckad** [python/mypy#8697]
```
try:
    pass
except Exception:
    a:int = 1
else:
    a:int = 1
```
Output 
```
test.py:6: error: Name 'a' already defined on line 4
Found 1 error in 1 file (checked 1 source file)
```

**Comment by JelleZijlstra** [comment]
Mypy doesn't allow you to declare a variable more than once in one function. You should put `a: int` above the try block once, then just write `a = 1` in the except and else blocks.
