### ISSUE TITLE
Remove typing.AwaitableGenerator from typeshed

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#8699]
As mentioned in the code, AwaitableGenerator doesn't exist in typing.py or PEP 484.
https://github.com/python/typeshed/blob/626a0f3f7353e484e8a6c5d7a2b3f37e4694e132/stdlib/3/typing.pyi#L208

It appears it's an "intentionally undocumented" implementation detail of mypy, as mentioned in https://github.com/python/mypy/issues/2907. Ideally, these shouldn't leak into typeshed.

**Comment by msullivan** [comment]
We could make it underscored or (and?) move it into mypy_extensions. Probably it still needs to live in typeshed somewhere because at least as it stands now we don't have anywhere *else* to put class definitions that mypy uses internally...

**Comment by hauntsaninja** [comment]
Moving it to `mypy_extensions`, makes sense to me. I guess we don't actually need to change `mypy_extensions`, just typeshed's `third_party/2and3/mypy_extensions.pyi`? Which seems fine to me...

I'd like to make it underscored (wherever it lives, but particularly if it remains in typing.pyi), since it's implementation detail. But based on `check-async-await.test` it seems to make its way into error messages, so maybe the underscore is undesirable?

Happy to submit a PR for the following:
1. In typeshed, remove it from typing.pyi, and add it to mypy_extensions.pyi
2. In mypy, s/typing.AwaitableGenerator/mypy_extensions._AwaitableGenerator/g
3. Update typeshed submodule

This also doesn't really matter, so if it's not as straightforward as that, happy to back-burner this.

**Comment by srittau** [comment]
@hauntsaninja +1 from me and I would also prefer not having mypy-specific types in `typing.pyi`, but I'll leave the decision about this to the mypy maintainers.

**Comment by graingert** [comment]
I suspect twisted.internet.defer.Deferred should be an AwaitableGenerator, how can I use this type?

**Comment by AlanBogarin** [comment]
> I suspect twisted.internet.defer.Deferred should be an AwaitableGenerator, how can I use this type?

Is an `Iterable & Awaitable`
