### ISSUE TITLE
Add MutableSequence, MutableMapping and MutableSet to Python 2 typing module

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#870]
It's probably a good idea to get the method implementations from `collections` when possible.

**Comment by ddfisher** [comment]
@JukkaL: this needs future clarification.

**Comment by gvanrossum** [comment]
This sounds out of date; we have a complete typing module (both the stub and the real thing) for Python 2 now.

**Comment by JukkaL** [comment]
Yeah, everything seems to be included now.
