### ISSUE TITLE
[question] How to add type stub file (.pyi) to module only project?

### ISSUE THREAD

**Issue by tamuhey** [python/mypy#8709]
I want to add a type stub file (.pyi) to my module-only project. The projects consists as follows:

```
foo.py
foo.pyi
setup.py
```

I know `foo.py` should be added to `py_modules` arguments in `setup` function.
But I don't know where `foo.pyi` should be added.

The repository I'm trying to handle is https://github.com/studio-ousia/mojimoji

**Comment by msullivan** [comment]
You probably want to include it in `package_data`. See https://github.com/more-itertools/more-itertools/blob/master/setup.py#L34 for an example of a project that does this

**Comment by ethanhs** [comment]
I will add, you need to make the stubs a package, you can't just include a stub module.

**Comment by tamuhey** [comment]
@ethanhs Thanks! So should I create `foo` directory and put the `foo.pyi` into `foo` directory, and rename it to `__init__.py`?

**Comment by ethanhs** [comment]
Basically yes, but you want it to be `__init__.pyi` since it's a stub.
