### ISSUE TITLE
List comprehension has incompatible type: if-clause is not considered

### ISSUE THREAD

**Issue by sebastian-philipp** [python/mypy#8713]
* Are you reporting a bug, or opening a feature request?

Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
from typing import List, Dict

ds: List[Dict[str, str]] = []
x: List[str] = [d.get('key') for d in ds if d.get('key') is not None]
```

* What is the actual behavior/output?

```
$ mypy test.py
test.py:4: error: List comprehension has incompatible type List[Optional[str]]; expected List[str]
Found 1 error in 1 file (checked 1 source file)
```

* What is the behavior/output you expect?

As the if-clause in the comprehension prevents any `None` values in x, the error is unexpected.

* What are the versions of mypy and Python you are using?

0.770

* What are the mypy flags you are using? (For example --strict-optional)

none

**Comment by hauntsaninja** [comment]
I don't think that's a safe assumption to make. There's nothing to say that the output of `d.get` is deterministic, and it needn't be if you're dealing with the wrong dict subclass.
For this example, I'd rewrite it as `[d["key"] for d in ds if "key" not in d]`, since `None` isn't a valid value in `d`. More generally, if you're on Python 3.8, you should be able to use `[value for d in ds if (value := d.get("key")) is not None]`.

**Comment by NeilGirdhar** [comment]
This is a perfect use of `:=` to elide out the second `get` call.

**Comment by sebastian-philipp** [comment]
```python
from typing import List, Dict

ds: List[Dict[str, str]] = []
x: List[str] = [d['key'] for d in ds if "key" in d]
```

works. Thanks!

**Comment by vincent-czi** [comment]
Thanks @hauntsaninja! The solution of
```
[value for d in ds if (value := d.get("key")) is not None]
```
works great!

For anyone else who isn't used to the `:=` operator you can look into "assignment expression" (AKA "walrus operator") if you want more info. Here's a guide to specifically using it in the context of a list comprehension (but basically it boils down to the above): https://realpython.com/python-walrus-operator/#list-comprehensions
