### ISSUE TITLE
Mypy confuses enum constants with enum values in enum instance methods

### ISSUE THREAD

**Issue by tdsmith** [python/mypy#8719]
* Are you reporting a bug, or opening a feature request?

a bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
class AnalysisPeriod(enum.Enum):
    DAY = "day"
    WEEK = "week"
    OVERALL = "overall"

    @property
    def adjective(self) -> str:
        return {self.DAY: "daily", self.WEEK: "weekly", self.OVERALL: "overall"}[self]
```

* What is the actual behavior/output?

Typechecking `.adjective()` fails with `error: Invalid index type "AnalysisPeriod" for "Dict[str, str]"; expected type "str"`

The revealed type of `self.DAY` inside `adjective()` is `builtins.str`.

* What is the behavior/output you expect?

Typechecking should succeed

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

mypy 0.770, Python 3.8.0

Yes, persists from mypy git master

* What are the mypy flags you are using? (For example --strict-optional)

none

---

This is similar to #6712, but provides the requested minimal example.

**Comment by JelleZijlstra** [comment]
This is also similar to #8722. Closing this one as a duplicate because the other one has more discussion of a possible solution.
