### ISSUE TITLE
'if callable(fn)' should infer that 'fn' is not None

### ISSUE THREAD

**Issue by cmeyer** [python/mypy#8720]
Reporting a bug.

Code.
```
fn = None
if callable(fn):
  fn()
```

Actual output.
```
$ mypy  xyz.py 
xyz.py:3: error: "None" not callable
Found 1 error in 1 file (checked 1 source file)
```

Expected behavior.
I would expect `if callable(fn)` to infer a non-None type.

This is a workaround, but shouldn't be necessary:
```
fn = None
if fn and callable(fn):
  fn()
```

mypy version.
```
$ mypy --version
mypy 0.770
$ python --version
Python 3.8.2
```

**Comment by msullivan** [comment]
Yeah that seems reasonable. I'd review a PR for it. The code to update is `conditional_callable_type_map` in `checker.py`.
