### ISSUE TITLE
singledispatchmethod not Callable error

### ISSUE THREAD

**Issue by JeremyRubin** [python/mypy#8728]
It seems the way that singledispatch method is implemented is not compatible with being type checked.

The below example fails to check. Adding an `assert(callable(x.y))` before the call to `y` fixes this issue, but isn't really the right thing to do. 
```python
from functools import singledispatchmethod
class X:
    @singledispatchmethod
    def y(self, arg):
        raise ValueError("No Impl")
    @y.register
    def _meth1(self, arg:int):
        print(arg)

if __name__ == "__main__":
    x = X()
    x.y(1)
# $ mypy example.py
# error: "singledispatchmethod[Any]" not callable
# Found 1 error in 1 file (checked 1 source file)
```

My hunch is that singledispatchmethod should be re-implemented as a function not a class, or add an __call__ override so as to have a callable type.

This is also annoying because the type of the function varies from call site to call site, so really we should be getting a "dependently typed" function back for the return value... it's unclear this is in scope, so just making something that type checks when all the return types are the same would be really neat.

One possible way would be to replace the singeldispatch dispatcher with a typedict, that way it can be known the exact function type returned.

**Comment by graingert** [comment]
@JeremyRubin https://github.com/python/typeshed/pull/3899

**Comment by JeremyRubin** [comment]
Yes that seems to fix it -- are there any reasonable hotfixes for this or just assert it away till the next release?

**Comment by msullivan** [comment]
Using master will probably fix it. Otherwise just wait I think, or assert it away
