### ISSUE TITLE
Adding Interface to existing class

### ISSUE THREAD

**Issue by andrewsonin** [python/mypy#8730]
Hi there.
I am working on a library that defines some functions that extend arbitrary iterable types with some specified interfaces. I wonder if it is possible to express my intention with native `Python 3.8` typing tools and explain to the static type checker what I want to do?

The main idea is presented below.
```python
from abc import ABC
from typing import Generic, Iterable, TypeVar, Type                


T = TypeVar('T')

class Interface(ABC, Generic[T]):
    """Some interface here"""
    pass

def extend_interface(cls: Type[Iterable[T]]) -> ...:
    class Updated(cls, Interface[T]):
        pass
    return Updated
```
The question is:
Is it possible to specify the return type of the function, which indicates that the return value is a

- `type` which instances implement both
- all the `cls` methods
- and the entire API of the interface?

So that the type checker would resolve the following cases:
```python
a = extend_interface(list)([3, 4, 5])    # a: List[int] + Interface[int]
b = extend_interface(list)([3, 4, 5.6])  # a: List[float] + Interface[float]
```
If it is possible, could you recommend a best practice for this?

Thank you in advance.

**Comment by JelleZijlstra** [comment]
That sounds like an intersection type, which mypy doesn't currently support.
