### ISSUE TITLE
Feature request: display warning when 'type: ignore' hint added but no typing error found on the line

### ISSUE THREAD

**Issue by actionless** [python/mypy#8731]
That's useful when `'type: ignore'` hint was added to workaround some mypy bug and in further version it got fixed.

**Comment by ethanhs** [comment]
Good news, this feature already exists! https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-warn-unused-ignores

**Comment by actionless** [comment]
my bad in searching, thanks!
