### ISSUE TITLE
untyped function in third-party code

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#8735]
I am getting this error:
`error: Call to untyped function "run_app" in typed context`

The code is referring to a 3rd-party function:
```
from aiohttp import web
[...]
web.run_app(app)
```

But, this function has type annotation, and I can even print them out:
```
>>> web.run_app.__annotations__
{'app': typing.Union[aiohttp.web_app.Application, typing.Awaitable[aiohttp.web_app.Application]], 'host': typing.Union[str, NoneType], 'port': typing.Union[int, NoneType], 'path': typing.Union[str, NoneType], 'sock': typing.Union[socket.socket, NoneType], 'shutdown_timeout': <class 'float'>, 'ssl_context': typing.Union[ssl.SSLContext, NoneType], 'print': typing.Callable[..., NoneType], 'backlog': <class 'int'>, 'access_log_class': typing.Type[aiohttp.abc.AbstractAccessLogger], 'access_log_format': <class 'str'>, 'access_log': typing.Union[logging.Logger, NoneType], 'handle_signals': <class 'bool'>, 'reuse_address': typing.Union[bool, NoneType], 'reuse_port': typing.Union[bool, NoneType], 'return': None}
```

I've read through the documentation for mypy, and as far as I could understand, this should work. So, why does it think they are untyped functions? What have I missed?

**Comment by msullivan** [comment]
The rules that mypy uses for finding type annotations in third-party code are somewhat complex; see https://mypy.readthedocs.io/en/stable/installed_packages.html. The code having annotations isn't always enough.

aiohttp does have a `py.typed` file, though, so its type annotations should be discovered by mypy. Is aiohttp installed in the python environment that mypy is running in?

**Comment by Dreamsorcerer** [comment]
Yep:
```
pip3 install aiohttp
mypy .
```
Still reproduces the error for me. I'll have a look later and see if I can try it on a different environment.

I skimmed that documentation, and assumed that "The first is a package that has only inline type annotations in the code itself." meant that such packages with annotations would be sufficient. But, as I say, I was only skim-reading as I wasn't trying to publish a package.

**Comment by srittau** [comment]
As a data point: We are using aiohttp in an internal codebase, which type checks successfully.

**Comment by Dreamsorcerer** [comment]
OK, I completely uninstalled aiohttp, and after reinstalling it, it's working correctly now.
