### ISSUE TITLE
Can't find .mypy.ini file

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#8736]
When running mypy, it fails to find the `.mypi.ini` config by default in the current directory. The documentation says it should pick this up automatically.

i.e. These 2 commands produce completely different output:
```
mypy .
mypy . --config-file=.mypy.ini
```

* What are the versions of mypy and Python you are using? 0.77 and 3.6.8.

**Comment by srittau** [comment]
The file in the current directory must be named `mypy.ini`. `.mypy.ini` with a leading dot is looked for in the user's home directory.

**Comment by Dreamsorcerer** [comment]
Ah, thanks, on rereading the documentation, I see that now.
