### ISSUE TITLE
mypy reporting error with default value for typevar

### ISSUE THREAD

**Issue by madkinsz** [python/mypy#8739]
I’m struggling with a generic type var and have reduced it to a simple example. I’m trying to have a function that takes a generic type and returns an instance of that type

```python
from __future__ import annotations

from typing import Type, TypeVar


class A:
    pass

class B(A):
    pass

T = TypeVar('T', bound=A)

def test(x: Type[T] = B) -> T:
    return x()
```

```
test.py:14: error: Incompatible default for argument "x" (default has type "Type[B]", argument has type "Type[T]")
```
Am I missing something obvious or is this a bug? My understanding is that Type[B]  should be a subset of Type[T] and not cause an incompatibility

I get a similar error with  modifications such as
```
T = TypeVar('T', bound=B)
```
and
```
def test(x: Type[T] = A) -> T:
    return x()
```

I made a thread on gitter and got no response 🤷 

**Versions**
mypy 0.770
Python 3.8.2

**Comment by hauntsaninja** [comment]
You get a similar failure on a simpler, more general case:
```
from typing import *

T = TypeVar("T")

def foo(x: T = 0) -> T: ...

reveal_type(foo())
```

So it looks like this is a duplicate of https://github.com/python/mypy/issues/3737. As that thread mentions, a good workaround is using `overload`.

**Comment by madkinsz** [comment]
Ah geez, I did see that. I'll try the solutions there and close this.

Thanks!
