### ISSUE TITLE
Unable to create a new type from a Plugin

### ISSUE THREAD

**Issue by patrick91** [python/mypy#8740]
Hi there! I'm working on a library that makes use of types at runtime, and I have the necessity of creating a new type with some metadata attached to it, something like this:

```
Result = strawberry.union("Name", (int, str))

# Result would be an alias to typing.Union[int, str]

x: Result
```

unfortunately this doesn't seem to be allowed by mypy, as only NewType is allowed for creating new types as variable.

I've created a repo here for this example:
https://github.com/patrick91/mypy-newtype-example

The error I get from the plugin is this:

```
example.py:14: error: Variable "example.Result" is not valid as a type
example.py:14: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
example.py:11: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.770
Traceback (most recent call last):
  File "mypy/checker.py", line 401, in accept
  File "mypy/nodes.py", line 1062, in accept
  File "mypy/checker.py", line 2011, in visit_assignment_stmt
  File "mypy/checker.py", line 2149, in check_assignment
  File "mypy/erasetype.py", line 135, in remove_instance_last_known_values
  File "mypy/types.py", line 1898, in accept
AssertionError:
example.py:11: : note: use --pdb to drop into pdb
```

from what I have understood and from the conversation on gitter, at the moment this is not supported by mypy, right?

**Comment by JelleZijlstra** [comment]
You may be interested in PEP 593 too.

**Comment by JukkaL** [comment]
If you need to attach metadata to a type, `Annotated[...]` seems to be the way to go. If that doesn't work for you, please let us know.

**Comment by patrick91** [comment]
@JukkaL but I wouldn't be able to a create a type from a function, right?

my goal is to be able to provide this API:

```
Result = strawberry.union("Name", (int, str))
```

strawberry.union will also do some checks at runtime (you can pass all the types).

Does that make sense?

**Comment by patrick91** [comment]
@JukkaL can we reopen this? I still want to be able to use this API in my library:

```python
Result = strawberry.union("Name", (int, str))
```
