### ISSUE TITLE
Using Annotated for purely type-stub expressiveness

### ISSUE THREAD

**Issue by ikonst** [python/mypy#8750]
Following #7021, mypy has rudimentary support for Annotated. The rationale for Annotated is to enable new features -- in other words, new code in the type checker (a plugin?) that makes use of the annotation.

In [Advanced uses of self-types](https://mypy.readthedocs.io/en/stable/more_types.html#advanced-uses-of-self-types) there are some recipes for changing behavior of classes based on how they're initialized, by capturing this information into a type parameter. I was wondering if Annotated could be an alternative mechanism for this -- something that we could match the `self` parameter on in our methods to specify different overloads with different behaviors.

Or, more plainly, if there's no extra code whatsoever to 'special handle' an annotation, can we see the mechanism itself being useful to increase the expressiveness of type stubs?

WDYT?

**Comment by JukkaL** [comment]
Can you give a code example that should how this could be helpful? I haven't really thought about how Annotated could be used by mypy.

**Comment by ikonst** [comment]
I have some use cases in my head that I haven't completely vetted. I was mostly thinking about specializing classes without using generics (which have pitfalls like diverging stub-land and runtime) but in a way that's meaningful during the type check. For example, annotating a `datetime` as being initialized with/without a `tzinfo` (as comparing naive vs. tz-aware is an error).
