### ISSUE TITLE
[bug] Doesn't ignore explicit any on a single line

### ISSUE THREAD

**Issue by theoden-dd** [python/mypy#8759]
```
        body: Optional[Mapping[str, Any]] = None,  # type: ignore[misc] # noqa: F821
```

* What is the actual behavior/output?
file.py:17: error: Explicit "Any" is not allowed  [misc]
file.py:22: error: unused 'type: ignore' comment

Actually, I tried no-explicit-any and no-any-explicit as error code, but neither worked.

* What is the behavior/output you expect?
No errors.

* What are the versions of mypy and Python you are using?
Python 3.8.2 mypy 0.761

* What are the mypy flags you are using? (For example --strict-optional)
In setup.cfg:
```
show_error_codes = True
disallow_any_explicit = True
```

Related issue: #7239

**Comment by JelleZijlstra** [comment]
This sounds like there's some mismatch in line number. To fix it, you need to put the type ignore on the line that the error indicates.

But this also suggests a bug in where we raise the error. I'm just guessing, but maybe we produce an error on the `def` line when we should do it on the line for a specific parameter.

**Comment by theoden-dd** [comment]
Thank you! That worked:
```python
    def api_response(  # type: ignore[misc] # noqa: F821
        self,
        endpoint,
        verb: str = 'get',
        headers: Optional[Mapping[str, str]] = None,
        body: Optional[Mapping[str, Any]] = None,
    ) -> Response:
```
If you're sure that the solution is obvious, please, close the issue.

**Comment by ethanhs** [comment]
Perhaps this should be added to https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code
