### ISSUE TITLE
Overloaded function typing error where it shouldn't be

### ISSUE THREAD

**Issue by DevilXD** [python/mypy#8761]
Please provide more information to help us understand the issue:

* Bug report

* Code:

```py
from typing import Union, List, Literal, overload

class One:
    pass

class Two:
    pass

@overload
def func(x: Literal[False]) -> List[Two]:
    ...

@overload
def func(x: Literal[True]) -> List[Union[Two, One]]:
    ...

# actual definition typed with the most inclusive type
def func(x: bool) -> List[Union[Two, One]]:
    # instead of the code below, this can be just 'return []' or 'pass'
    # all 3 cases cause the same error
    if x:
        return [Two(), One()]
    else:
        return [Two()]
```

* What is the actual behavior/output?

This error on the last `func` definition:
```
Overloaded function implementation cannot produce return type of signature 1
```

* What is the behavior/output you expect?

Well, for this to type check correctly? It appears to be correct to me.

* What are the versions of mypy and Python you are using?

Python 3.8.1, latest git master: `mypy-0.770+dev.6534935ce64b69e2b41364e0a3254f1d6262148d`

* What are the mypy flags you are using? (For example --strict-optional)

Default VSCode ones + untyped defs:
```
--follow-imports=silent
--show-column-numbers
--check-untyped-defs
--ignore-missing-imports
```

**Comment by hauntsaninja** [comment]
Seems like you're just running into the invariance of List. Hence your "most inclusive type" doesn't actually include `List[Two]`. You can use Sequence, or a union of lists instead of a list of unions.

**Comment by DevilXD** [comment]
The type returned from the function is a list though, I feel like using `Sequence` would just make incorrect. A union of lists sounds pretty eh too, since the list returned may have both types in random amounts and order. Changing the type to `Union[List[Two], List[One]]` and trying a quick `reveal_type` like so:

```py
result = func(True)
reveal_type(result[0])
```

Reveals only `One` as a type, not `Union[Two, One]` which is correctly returned from `List[Union[Two, One]]` =/

**Comment by erictraut** [comment]
Mypy is doing the right thing here. This isn't a bug. The correct return type annotation for the overload implementation in the sample is `list[Two | One] | list[Two]`. If you make that change, the type error will go away.
