### ISSUE TITLE
Error assigning int to callable returning T

### ISSUE THREAD

**Issue by PeterJCLaw** [python/mypy#8765]
``` python
from typing import Callable, TypeVar
T = TypeVar('T')

def parse_difference_string(
    string: str,
    type_converter: Callable[[str], T] = int,  # Incompatible default for argument "type_converter"
        # (default has type "Type[int]", argument has type "Callable[[str], T]")
) -> Callable[[T], bool]:
    parsed = type_converter(string)
    return lambda x: x == parsed
```

I can sort-of see why this is the case -- `mypy` is presumably inferring that `T` could be anything and doesn't like that `int` isn't compatible with that.

However since that argument is the one which defines what `T` _is_, I'd hope that `mypy` would be able to work out that this is actually fine and thus determine that the default value of `T` is `int`.

I can somewhat work around this by using overloads, but if I want the implementation to also be type checked I need to mark the parameter's default as `ignore[assignment]`.

----
Python 3.6, mypy 0.770, also master (at 2a3de7b7941f24b6bc53fe0cf8a2b7f8f7fd4e15)

**Comment by JelleZijlstra** [comment]
This is #3737.
