### ISSUE TITLE
Please consider making Tuple[Hashable, ...] a subtype of Hashable

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#8767]
```python
from typing import Hashable, Tuple


class A:
    def f(self, h: Hashable) -> None:
        pass


class B(A):
    def f(self, h: Tuple[Hashable, ...]) -> None:
        pass
```
but MyPy says:
```
a.py:10: error: Argument 1 of "f" is incompatible with supertype "A"; supertype defines the argument type as "Hashable"
```

**Comment by bluenote10** [comment]
Has this actually been changed? I'm getting the same error in mypy 1.16.0 ([playground link](https://mypy-play.net/?mypy=latest&python=3.12&gist=70d1147d00125beef97985dcd92b685e)).

**Comment by NeilGirdhar** [comment]
I don't remember why I closed it, but I guess Hashable is just not that well handled in Python.
