### ISSUE TITLE
Ways to install the codec.

### ISSUE THREAD

**Issue by o11c** [python/mypy#877]
I just realized adding a `.pth` file to site-packages allows execution of arbitrary code (as long as the line starts with `import`). That could be used to hook up the encoding without requiring the user to do it explicitly (this is impossible with the main file anyway).

Unfortunately this does not work for the current directory, only the system and user site-packages directories.

Instead of directly registering the codec (from the `.pth` file), it might be possible to set a custom `__path__` element in `encodings`, that should enable autodiscovery.

**Comment by o11c** [comment]
Note, I also looked at `sitecustomize.py` and `usercustomize.py`, but those only works if you `export PYTHONPATH=.`, i.e. not in the implicit path from the script which is apparently only set later.

**Comment by JukkaL** [comment]
Having the encoding available implicitly would be handy, though only if it doesn't significantly slow down the start up of programs that don't use the encoding (i.e., I'd like to import the implementation of the encoding lazily).

I wonder what the best practice for doing this would be? At least we can document how to do this manually. Or maybe we could have a separate package for the codec that would do this automatically.

**Comment by o11c** [comment]
Yeah, obviously the python2-only bits need to be installable separately from the python3 mypy proper.

I put some thoughts in #724
