### ISSUE TITLE
About the reports "imprecision"

### ISSUE THREAD

**Issue by ThomasCrc** [python/mypy#8771]
Hello dear developers,

I've recently been taking a look upon mypy as a quality tool for about a few weeks, but a few questions remain. I've tried to look for a mailing list to address these, but happened to know that the Github issues tracker is where questions should be asked, I hope this is still the case, and if this is not the case, I'd like to be indicated where I should ask them.

One of my question is about mypy reports, displaying a percentage of imprecision among the code (in HTML reports, and as raw numbers in other reports). Using the `--lineprecision-report` option, I've understood that this percentage is calculated using `Any` variables lines and imprecise lines, against all lines of code in the file(s). What I cannot get a hand on is what, precisely, is an "imprecise" line. Same goes for "empty", which appears to be most of my lines of code.

Here is a screenshot of one of my report, as an example :
<img width="285" alt="lineprecision report" src="https://user-images.githubusercontent.com/50206837/80966930-c8a5fc00-8e15-11ea-897b-0d163812567f.png">

What I want to know here is not why my code is analyzed this way, but what every column is expected to represent.

Thanks in advance for your upcoming answers !

**Comment by EkanshMangal** [comment]
@ThomasCrc Hello Sir, I want to contribute in this.
Can u explain more into it

**Comment by ThomasCrc** [comment]
I'd like to get a grasp on the "imprecise" notion. What could be considered an "imprecise" type variable I wonder ? I understand why `Any` is treated as such, but I have no clue for any other variable for which it is the case as well.

For `Empty` lines, I suppose a line is considered empty when there is no mention whatsoever of a variable within it, but I could be mistaken, which is why I addressed the issue.

Thank you for your concern.

**Comment by msullivan** [comment]
I believe that an imprecise line is one where the expressions in it have a mix of Any and non-Any types. I believe empty is supposed to be lines without expresssions in them.

**Comment by ThomasCrc** [comment]
Thank you very much for your answer @msullivan ! Closing the issue.

**Comment by manojyadav4444** [comment]
what are Any lines
