### ISSUE TITLE
mypy can't infer type of lambdas returning None

### ISSUE THREAD

**Issue by mikolajz** [python/mypy#8773]
* Are you reporting a bug, or opening a feature request?

feature request?

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
from concurrent.futures import ThreadPoolExecutor


def do_something(param):
    # type: (int) -> None
    pass


def test():
    # type: () -> None
    ThreadPoolExecutor().submit(lambda: do_something(42))  # [*]
```

* What is the actual behavior/output?

Error in line [*] - `test_types.py:11: error: Cannot infer type argument 1 of "submit" of "Executor"`.
Note that when `do_something` returns something other than None, it works.

* What is the behavior/output you expect?

mypy should infer that the lambda returns None, since the called function is explicitly annotated as returning None.

* What are the versions of mypy and Python you are using?

0.770

* What are the mypy flags you are using? (For example --strict-optional)

None

**Comment by AlexWaygood** [comment]
[Cannot reproduce on mypy 0.941](https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=de41360e507046b33dba82073dd19cfd) (can reproduce on 0.770); this seems to be fixed

**Comment by mikolajz** [comment]
I can confirm - we didn't see this issue for some time already (and I forgot we have this bug still open).
