### ISSUE TITLE
Type[T] incompatible with default type value

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#8794]
The following program works, but gives a MyPy error:
```python
from typing import Type, TypeVar, Any, Optional


T = TypeVar('T')


def check(element: Any, types: Type[T] = object) -> Optional[T]:
    if not isinstance(element, types):
        return None
    return element


print(check(123, int))
print(check(123, object))
```
MyPy complains:
```
main.py:7: error: Incompatible default for argument "types" (default has type "Type[object]", argument has type "Type[T]")
Found 1 error in 1 file (checked 1 source file)
```

Replacing `object` with `Type[object]` mysteriously works.  I thought we weren't supposed to use `Type[]` outside type annotations?

**Comment by jkhsjdhjs** [comment]
This is https://github.com/python/mypy/issues/3737

**Comment by NeilGirdhar** [comment]
@jkhsjdhjs Thanks for the link!  I closed this because someone explained to me the need to use `overload`.  It will be interesting to see if the situation changes.
