### ISSUE TITLE
Addition of Pre-Commit hooks

### ISSUE THREAD

**Issue by jsparmani** [python/mypy#8799]
**Implement Pre-Commit Hooks**

We can setup `pre-commit` hooks to rectify the linting issues so as to keep the code base consistent and prevent travis build fails. This would reduce the time of testing on travis and getting back.

**Comment by hauntsaninja** [comment]
The only linter we run is flake8, and I don't like autoflake8. There's discussion elsewhere for adding an autoformatter

**Comment by ssbarnea** [comment]
I am glad that later the situation changed and now I see [black](https://github.com/python/mypy/blob/master/.pre-commit-config.yaml) listed there.
