### ISSUE TITLE
Protocol documentation for arguments is misleading

### ISSUE THREAD

**Issue by silviogutierrez** [python/mypy#8805]
Very happy to be using protocols. One small note, in the documentation here:

https://mypy.readthedocs.io/en/stable/protocols.html#callback-protocols

`Keyword argument names in __call__ methods must be identical, unless a double underscore prefix is used`

Really, I think this should say "Arguments" and not "Keyword" arguments. Unless I'm missing something, this applies to *all* argument names, not just keyword ones.

**Comment by JelleZijlstra** [comment]
I'm guessing it also doesn't apply to the name of `*args` and `**kwargs`. Maybe a precise wording would be "Arguments that can be used as keyword arguments".

**Comment by msullivan** [comment]
Yeah that seems reasonable. Do you want to submit a PR?
