### ISSUE TITLE
NewType context on literal

### ISSUE THREAD

**Issue by ErwanDL** [python/mypy#8808]
I am not sure if this is a bug or an expected behaviour, but I am wondering if it possible to achieve structural typing when defining type aliases with mypy.

Here is an example : 
```python
from typing import List, NewType

UserId = NewType("UserId", int)

a: List[UserId] = [5]    # (mypy) error: List item 0 has incompatible type "int"; expected "UserId"
```
This code triggers a mypy error, but I would actually want it not to. In this use case, I want to use the type alias `UserId` more as documentation than as a type-checking information, and thus I would expect it not to trigger an error (I think Typescript for example would produce the behaviour I expect).

Is there a way to achieve the behaviour I describe here ?

This is with Python 3.7.2 and mypy 0.770.

**Comment by JelleZijlstra** [comment]
It also fails with just `a: UserId = 5`. I can't find an existing issue for this, although #2448 is similar, but it seems like a reasonable request to me to make this work.

As a workaround, writing `a = [UserId(5)]` should work.

**Comment by hauntsaninja** [comment]
Note that using NewType is different from using a type alias. Since you mention you want UserId to serve more as documentation than as type-checking information, you can alias by setting `UserId = int` and mypy will treat them as equivalent, see https://mypy.readthedocs.io/en/stable/kinds_of_types.html#type-aliases

**Comment by ErwanDL** [comment]
@hauntsaninja you are very right ! I wasn't aware of the difference in behaviour between `NewType` and type aliases with `=`. I think this solves the problem then.
