### ISSUE TITLE
dataclass signature in help screen

### ISSUE THREAD

**Issue by lhfriedman** [python/mypy#8813]
### What steps will reproduce the problem?

The help screen does not properly display dataclass signatures. This example was taken from the python dataclasses doc page, and it improperly displays. However, the __init__ method displays properly.

In IPython console ::

from dataclasses import dataclass

    >>> @dataclass
    >>> class InventoryItem:
    >>>     '''Class for keeping track of an item in    inventory.'''
    >>>     name: str
    >>>     unit_price: float
    >>>     quantity_on_hand: int = 0
    >>> 
    >>>     def total_cost(self) -> float:
    >>>         return self.unit_price * self.quantity_on_hand
        

    InventoryItem <no return here, but click ctrl-I>

Help produces the following in text mode:

> =============
> InventoryItem
> =============
> 
> Definition: InventoryItem(...)
> 
> Type: Function of __main__ module
> 
> ----
> 
> Class for keeping track of an item in inventory.
> 

Now, try help on ``InventoryItem.__init__``

> ========
> __init__
> ========
> 
> Definition: __init__(name: str, unit_price: float, quantity_on_hand: int=0) -> None
> 
> Type: Function of __main__ module
> 
> ----

**Comment by JelleZijlstra** [comment]
I don't know what tool you're using that is producing these help screens, but it's definitely not mypy. Maybe pydoc?

**Comment by lhfriedman** [comment]
My mistake. This is a problem with Spyder or sphinx

**Comment by lhfriedman** [comment]
Sorry to waste your time. I followed links to the wrong place.
