### ISSUE TITLE
Accept any NamedTuple as function argument

### ISSUE THREAD

**Issue by finkandreas** [python/mypy#8815]
The following code runs fine, but throws an error with mypy:
```
class MyTuple(NamedTuple):
    a: int
    b: float

def namedtuple_to_str(tpl: NamedTuple) -> str:
        return ' '.join([f'{name}={tpl[idx]}' for idx,name in enumerate(tpl._fields)])

x = MyTuple(a=1, b=2.0)
print(namedtuple_to_str(x))
```

The error message is:
```
/tmp/test.py:11: error: Argument 1 to "namedtuple_to_str" has incompatible type "MyTuple"; expected "NamedTuple"
Found 1 error in 1 file (checked 1 source file)
````

The function `namedtuple_to_str` can accept any NamedTuple and does not need any extra information whatever tuple is passed there. How can I annotate it correctly?

**Comment by JelleZijlstra** [comment]
You could add a Protocol that has a `_fields` attribute with the right type (although I'm not positive mypy actually knows that NTs have a `_fields` attribute). `NamedTuple` isn't a type, either at runtime or to the typechecker, so it can't be used directly in type annotations.

**Comment by finkandreas** [comment]
This is a non trivial task, because I need to provide a `__getitem__(self, idx: int) -> T[idx]`, which is potentially a different type for each idx.
I also tried to define `_fields` as `Iterable[str]` but mypy complains that `Iterable[str]` does not match `Tuple[str, str]`.

**Comment by finkandreas** [comment]
I tried the following, but none of them will be accepted by mypy without errors:
```
class ImitatesNamedTuple(Protocol):
    # the following declaration generates the error message: _fields: expected "Tuple[str, ...]", got "Tuple[str, str]"
    _fields: Tuple[str, ...]
    # the following declaration generates the error message: _fields: expected "Iterable[str]", got "Tuple[str, str]"
#    _fields: Iterable[str]
    def __getitem__(self, idx: int) -> Any: ...
```

**Comment by msullivan** [comment]
Making _fields an attribute I thik doesn't work because of mutability/invariance concerns.

```
class ImitatesNamedTuple(Protocol):
    @property
    def _fields(self) -> Iterable[str]: ...
    def __getitem__(self, idx: int) -> Any: ...
```
seems to work.

**Comment by SimpleArt** [comment]
> Making _fields an attribute I thik doesn't work because of mutability/invariance concerns.
> 
> ```
> class ImitatesNamedTuple(Protocol):
>     @property
>     def _fields(self) -> Iterable[str]: ...
>     def __getitem__(self, idx: int) -> Any: ...
> ```
> 
> seems to work.

The precise way to type this would actually be to use a type variable:

```python
FT = TypeVar("FT", bound=tuple[str, ...])


class NamedTupleProtocol(Protocol[FT]):
    _fields: FT
```

Example:

```python
class Point(NamedTuple):
    x: int
    y: int


def fields(x: NamedTupleProtocol[FT]) -> FT:
    return x._fields

reveal_type(fields(Point(2, 3)))  # tuple[str, str] since it has 2 fields.
```

The reason this works is because `Point._fields` has type `tuple[str, str]`, meaning it accepts reads *and writes* of that type. With what you have, you're saying that it allows reads of type `tuple[str, ...]`, which is correct since `tuple[str, str]` is a subtype of `tuple[str, ...]`. Without the `@property` solution, it would mean named tuple subclasses should support writes of type `tuple[str, ...]`, but as you can see in this example, only writes of type `tuple[str, str]` should be allowed.
