### ISSUE TITLE
mypy stops checking after assert

### ISSUE THREAD

**Issue by ikonst** [python/mypy#8817]
Given the code
```python
class Foo:
    bar = 5


def bar() -> None:
    foo = Foo()
    reveal_type(foo)
    assert foo.bar is None
    reveal_type(foo)
```
I'm getting this from mypy 0.770+dev.c90b405934cbf2142b8a575ddd89dbedf762106c:
```
test.py:7: note: Revealed type is 'test.Foo'
```

**Comment by JelleZijlstra** [comment]
This is because mypy thinks this code is unreachable (because types indicate `foo.bar` is never None). You can use the `--warn-unreachable` mypy option to have mypy warn about this.

This has come up a lot, so maybe it should be discussed in https://mypy.readthedocs.io/en/stable/common_issues.html.

**Comment by ikonst** [comment]
In my case bad typing had caused mypy to assume this is unreachable. (The assertion was there for test code, not mypy.)
