### ISSUE TITLE
Using type variables with isinstance

### ISSUE THREAD

**Issue by kyprifog** [python/mypy#8820]
This is more of a question.  I believe the answer is, it is not currently possible but I want to check before I give up.

Does anyone know if its currently possible to implement a function like this?  Currently it throws an error about Type variables not being used in isinstance?  Whats the correct way to do it?

```
T = TypeVar("T")
R = TypeVar("R")

def sequence(l : List[Union[T, R]]) -> Tuple[List[T], List[R]]:
    l1: List[T] = []
    l2: List[R] = []
    for l0 in l:
        if isinstance(l0, Type[T]): 
            l1.append(l0)
        else:
            l2.append(l0)
    return l1, l2
```

**Comment by JelleZijlstra** [comment]
Yes that doesn't work. I'm not sure I can suggest any realistic way for this to work, since types don't really exist at runtime.

**Comment by kyprifog** [comment]
But I can implement this same function in python without generic types T and R, just using concrete types.  It just means that I have to copy and paste this function any time I need this functionality.  I think the question is still about type annotations in that sense.

**Comment by JelleZijlstra** [comment]
You could take an additional arguments of type `Type[T]` to make it a bit less repetitive. There's no way for the type system itself to detect at runtime what types are in the list, or what value `T` actually takes.

**Comment by hauntsaninja** [comment]
You probably want something like:
```
from typing import *

A = TypeVar("A")
B = TypeVar("B")

def seq(l: List[Union[A, B]], type_a: Type[A], type_b: Type[B]) -> Tuple[List[A], List[B]]: ...

l: List[Union[int, str]] = ...  # type: ignore
reveal_type(seq(l, int, str))
```

**Comment by kyprifog** [comment]
@hauntsaninja this did exactly what I wanted it to.  Thank you, also I understand a bit more about type variables in python.

Here is the finished code that worked exactly as I wanted:

```
A = TypeVar("A")
B = TypeVar("B")

def sequence(l: List[Union[A, B]], type_a: Type[A], type_b: Type[B]) -> Tuple[List[A], List[B]]:
    l1: List[A] = []
    l2: List[B] = []
    for l0 in l:
        if isinstance(l0, type_a):
            l1.append(l0)
        else:
            assert(isinstance(l0, type_b))
            l2.append(l0)
    return l1, l2
```
