### ISSUE TITLE
bug: subclassing asyncio locks fail due to mixin

### ISSUE THREAD

**Issue by potatochip** [python/mypy#8826]
Creating the following class:

```python
class Semaphore2(asyncio.Semaphore):
    def release(self) -> None:
        self._value += 1
        self._wake_up_next()
```

Fails with: 

```
"Semaphore2" has no attribute "_value"
"Semaphore2" has no attribute "_wake_up_next"
```

Presumably this has to do with the whole mixin problem.

**Comment by JelleZijlstra** [comment]
I'm not sure why you think this has something to do with mixins.

Most likely this is because these private attributes don't appear in the asyncio stubs on typeshed https://github.com/python/typeshed/blob/master/stdlib/3/asyncio/locks.pyi#L56). We would accept a typeshed PR adding these attributes.
