### ISSUE TITLE
Difficult to diagnose problem with stubgen

### ISSUE THREAD

**Issue by jacob414** [python/mypy#8830]
Hello, thank you for your great work!

I don't know if I'm too stupid or if this is an issue in `stubgen`, but here goes...

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?

  It's either a bug or a missunderstanding of documentation.

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

I recently committed this: [399f0f8](https://github.com/jacob414/kingston/commit/399f0f8) _(note, on branch `'XXX-forward'`)_. It's a very short module to a (public) utility library of mine. I'm getting a very sparse error, "`Critical error during semantic analysis:`" when I try to run `stubgen`.

* What is the actual behavior/output?
```shell
(py) sugarline:~/src/oss/kingston XXX-forward
kingston $ stubgen  -out . kingston/kind.py
Critical error during semantic analysis:
(py) sugarline:~/src/oss/kingston XXX-forward
kingston $
```

* What is the behavior/output you expect?
```shell
(py) sugarline:~/src/oss/kingston XXX-forward
kingston $ stubgen  -out . kingston/kind.py
kingston $ file kingston/kind.pyi
kingston/kind.pyi: Python script text executable, ASCII text
```

or
```shell
(py) sugarline:~/src/oss/kingston XXX-forward
kingston $ stubgen  -out . kingston/kind.py
 <... diagnostic messages on how to correct kingston/kind.py ...>
kingston $ 
```

* What are the versions of mypy and Python you are using?

0.770

  Do you see the same issue after installing mypy from Git master?

Yes

* What are the mypy flags you are using? (For example --strict-optional)

No flags used.

* If mypy crashed with a traceback, please paste
  the full traceback below.

Not an `mypy` traceback, it's from `stubgen`. Output can be seen under the section "actual behaviour/output".

---

Here is a short transcript from me trying to troubleshoot with [ipdb](https://github.com/gotcha/ipdb):
```python
ipdb> bt
  /Users/jacob/src/oss/kingston/sg_poc.py(4)<module>()
      2 import sys
      3 sys.argv = ['-out', '.', 'kingston/kind.py']
----> 4 main()

  /Users/jacob/src/ext/python/mypy/mypy/stubgen.py(1564)main()
   1563     options = parse_options(sys.argv[1:])
-> 1564     generate_stubs(options)
   1565

  /Users/jacob/src/ext/python/mypy/mypy/stubgen.py(1430)generate_stubs()
   1429     # Use parsed sources to generate stubs for Python modules.
-> 1430     generate_asts_for_modules(py_modules, options.parse_only, mypy_opts, options.verbose)
   1431     files = []

  /Users/jacob/src/ext/python/mypy/mypy/stubgen.py(1363)generate_asts_for_modules()
   1362     try:
-> 1363         res = build(list(py_modules), mypy_options)
   1364     except CompileError as e:

  /Users/jacob/src/ext/python/mypy/mypy/build.py(181)build()
    180         result = _build(
--> 181             sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
    182         )

  /Users/jacob/src/ext/python/mypy/mypy/build.py(252)_build()
    251     try:
--> 252         graph = dispatch(sources, manager, stdout) # THROWS FROM HERE
    253         if not options.fine_grained_incremental:

  /Users/jacob/src/ext/python/mypy/mypy/build.py(2573)dispatch()
   2572     t0 = time.time()
-> 2573     graph = load_graph(sources, manager)  # RAISES HERE
   2574

  /Users/jacob/src/ext/python/mypy/mypy/build.py(2752)load_graph()
   2751                 import ipdb; ipdb.set_trace(); pass
-> 2752             manager.errors.raise_error()
   2753         graph[st.id] = st

> /Users/jacob/src/ext/python/mypy/mypy/errors.py(414)raise_error()
    413         # been returned from a file_messages() call.
--> 414         raise CompileError(self.new_messages(),
    415                            use_stdout=use_stdout,
ipdb> a
self = <mypy.errors.Errors object at 0x1091a7320>
use_stdout = True
```

But I realized I was getting way out of my depth here. Help?

**Comment by jacob414** [comment]
Forgot to describe, I'm those:
```
(py) sugarline:~/src/
ormsnack $ python --version
Python 3.7.3
(py) sugarline:~/src
ormsnack $ uname -a
Darwin sugarline.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
(py) sugarline:~/src/oss/ormsnack write-compile-eval
ormsnack $
```

**Comment by msullivan** [comment]
I wasn't able to reproduce this using the file you linked to. Could you try to provide a more self-contained example?

**Comment by jacob414** [comment]
Yes – it's indeed quite difficult to reproduce. When I re-tried I noticed that it only showed up when I used the `-out .` flag I used above. Without knowing details, I suspect that could be a quite difficult use case to support (thinking something along the lines of circular imports).

For me that's not strictly neccessary – close the issue if you want.
