### ISSUE TITLE
mypy incorrectly verifies sys.stderr.isatty() in order to enable coloring

### ISSUE THREAD

**Issue by ssbarnea** [python/mypy#8834]
The logic at https://github.com/python/mypy/blob/310f9e3486054912e431904936c0516a0baaf3d5/mypy/util.py#L498 is flawed because it does break coloring two valid use-cases where is should not.

First case is when stderr is redirected to a file, example:
```bash
python -c "import sys; print(sys.stderr.isatty())"
True

python -c "import sys; print(sys.stderr.isatty())" >/dev/null
False

# While stdout still isatty(), it loses the coloring just 
# because stderr was redirected.
```

The second case is bit more complex as involves terminals that are tuned to preprocess stderr, usually to print it with a different color than stdout. Example https://github.com/sickill/stderred and maybe even easier to understand variances at https://github.com/cehoffman/dotfiles/blob/master/zsh/config#L174-L193 --- to summarize when these tricks are running, they have the side effect of making `sys.stderr.isatty()` report False, even if it does have ANSI support.

I am not sure if these implementations can be changed to report a fake tty, but I am sure that this would not solve the first case, which should be a good enough reason to not rely on stderr when deciding ANSI availability.

A similar bug affected https://github.com/pre-commit/pre-commit/issues/1459 and apparently the check for stderr check was introduced in order to accomodate Windows users where the opposite happens (someone needs to make a clear report with: windows version, terminal type: console, powershell, cygwin, ubuntu-on-windows).

I am not aware of other tools that are affected by the same issue, maybe one of them already addressed it better than us.

**Comment by JelleZijlstra** [comment]
Would it make sense to remove the check for stderr being a tty? If we print colored output only to stdout, I don't see why we should care whether stderr is a tty.

For your second case, do you have suggestions for how to fix the issue? Do tools like `ls` detect the ability of ANSI colors correctly in such cases?

**Comment by ssbarnea** [comment]
Apparently at least on powershell, both ttys report true, so no need to hack special condition for Windoze:
![](https://scontent-lhr8-1.xx.fbcdn.net/v/t1.15752-9/98920516_256477905733620_841599086464335872_n.png?_nc_cat=102&_nc_sid=b96e70&_nc_ohc=voAh-mSsdSEAX9wYAvF&_nc_ht=scontent-lhr8-1.xx&oh=19ced4d1ef37fd904722a97616366768&oe=5EE530B9)

**Comment by ssbarnea** [comment]
Closing it as I am no longer able to reproduce with current versions.
