### ISSUE TITLE
Mypy fails to ignore runtime function after @overload definitions.

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#8839]
I wrote some code along the lines of:
```
    def wrapper(func: _TemplateHandler) -> _HandlerType:
        @overload
        async def wrapped(request: web.Request) -> web.StreamResponse:
            ...
        @overload
        async def wrapped(view: AbstractView) -> web.StreamResponse:
            ...
        @overload
        async def wrapped(self: Any, request: web.Request) -> web.StreamResponse:
            ...
        @functools.wraps(func)
        async def wrapped(*args):
```

And I get: `Function is missing a type annotation  [no-untyped-def]` on the last line shown.
According to the typing documentation, mypy should ignore this line and use the overload lines for type checking: https://docs.python.org/3/library/typing.html?highlight=annotations#typing.overload

**Comment by JelleZijlstra** [comment]
We still enforce type annotations for the implementation function so that it itself can be typechecked.

**Comment by Dreamsorcerer** [comment]
But, isn't the point of the overload to provide the different typing possibilities? In this example, the implementation function would surely be `async def wrapped(*args: Any) -> web.StreamResponse`, which would mean no type checking on the arguments?

I thought the point of overload, was to be able to define the different combination of types it can take, and that's what the example in the documentation looks like to me.

I guess what I'm expecting, is to ignore annotations on the function itself, and instead perform typechecking of the implementation 3 times as if it was called with the annotations of each overload.

**Comment by msullivan** [comment]
The typing of overload is more about the callers than in doing a good job typechecking the overloaded function itself. The function itself needs to be given a type that matches all of the possibilities, which, yeah, a lot of time involves anys.

**Comment by Dreamsorcerer** [comment]
Perhaps the typing documentation should be updated to match this practice? Otherwise, it still looks like Mypy is treating these functions differently from what the Python documentation suggests it should.

**Comment by JukkaL** [comment]
@Dreamsorcerer Updating typing documentation sounds like a good idea. We don't maintain it here, so you'd need to create a CPython issue.
