### ISSUE TITLE
TypedDict cannot be used in more generic functions

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#8840]
```
class EmptyDict(TypedDict):
    pass

def foo(d: Dict):
    print(d)

a: EmptyDict = {}
foo(a)
```
gives `Argument 1 to "foo" has incompatible type "EmptyDict"; expected "Dict[Any, Any]"  [arg-type]`

Seems like a function that is supposed to be taking any `dict`, should be allowed to take a `TypedDict`.

**Comment by Dreamsorcerer** [comment]
I think at worst, a `TypedDict` should match anything under `Dict[str, Any]`.

At best, it could inspect the TypedDict and match `Dict[Any, Any]` if it is an empty dict, or match `Dict[str, specific_type]` if all the attributes are declared as the same type.

**Comment by silviogutierrez** [comment]
Have you tried using `Mapping` instead on the function?

**Comment by Dreamsorcerer** [comment]
That does work (though I need to get the change approved in the 3rd-party library). But, I still think TypedDict and Dict should be compatible, as they are both dict at runtime.

**Comment by msullivan** [comment]
The reason why `TypedDict` isn't considered a `Dict`, I think, is that then you could delete the attributes , which would be wrong.

**Comment by JukkaL** [comment]
The current behavior also makes it easier to refactor `Dict[str, Any]` types to TypedDict types, as mypy will complain about remaining `Dict[str, Any]` types. I've found that useful many times.

**Comment by Dreamsorcerer** [comment]
So, basically use `Mapping` for parameters and `Dict` for return types?

**Comment by JukkaL** [comment]
For things that work for many kinds of dicts, probably yes. You can sometimes use `Mapping[str, object]` if you want to avoid `Any` types.
