### ISSUE TITLE
# type: ignore import not working for python-pytun library

### ISSUE THREAD

**Issue by mrkeuz** [python/mypy#8844]
* Reporting a bug
* What i do: use python-pytun lib and try next code
```
...
# type: ignore
import pytun
...
```

* Got `mytun.py:7: error: Cannot find implementation or library stub for module named 'pytun'`

Then I followed instructions as described on section https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports and try some option but ```# type: ignore``` still not working, seems lib have only pure c bindings (see: https://github.com/montag451/pytun)

Only helped global --ignore-missing-imports flag.

* I want ignore type checking for import
* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

* My environment is Pycharm + numpy plugin
* What are the mypy flags you are using? (For example --strict-optional)
```
$: dmypy run -- --follow-imports=skip .
mypy 0.770 + same on master ver (mypy 0.770+dev.8748e69cccb8606fcfc03d336382b2836b7b29fe)
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Ubuntu 18.04.4 LTS
Linux ubnt 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by JelleZijlstra** [comment]
You need to put `# type: ignore` on the line of the error, not the line before it.

**Comment by mrkeuz** [comment]
Thanks a lot!
