### ISSUE TITLE
Document impact of reachability on typechecking

### ISSUE THREAD

**Issue by msullivan** [python/mypy#8846]
Like Jelle suggested in https://github.com/python/mypy/issues/8817, we should document how we can decide that code is unreachable and talk about --warn-unreachable in https://mypy.readthedocs.io/en/stable/common_issues.html

**Comment by ChetanKhanna** [comment]
Hi! I created a PR using the examples from the linked issue.

**Comment by asnature** [comment]
Hello @msullivan , Abhishek here! I'm a complete beginner to Open Source and would like to contribute to this project. Kindly guide me. Thanks!

**Comment by harshita-d** [comment]
Hi, I am Harshita. This is my first time contributing to open source. I would like to contribute to this issue. Kindly guide me.

**Comment by hauntsaninja** [comment]
This was documented in #8997 and #8899

**Comment by asnature** [comment]
@harshita-d  this issue is closed now. You can choose another issue from different repository...
