### ISSUE TITLE
Feature request: plugins that have access to both `semanal` and `typechecker` APIs

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#8848]
I am working on several plugins that requires using both `get_type_analyze_hook` during semanal and type checking hooks during actual type checking phase. Let me show an example of what I am trying to build.

### AttrOf

One of the simplest things I can show to illustrate my point is `AttrOf` type.

That's how it works:

```python
    from mypy_extras.types import AttrOf
    from typing_extensions import Literal

    class Test(object):
        x: int

    test: AttrOf[Test, Literal['x']]
    reveal_type(test)  # N: Revealed type is 'builtins.int'
```

It is just a generic type of two args, everything is done inside a mypy plugin:

```python
# mypy_extras/types.py

_ObjectType = TypeVar('_ObjectType')
_AttrQueryType = TypeVar('_AttrQueryType', bound=str)

class AttrOf(Generic[_ObjectType, _AttrQueryType]):
    ...
```

And here's the plugin itself:

```python
# plugin.py

class _MypyExtrasPlugin(Plugin):
    def get_type_analyze_hook(
        self,
        fullname: str,
    ) -> Optional[Callable[[AnalyzeTypeContext], MypyType]]:
        if fullname == 'mypy_extras.types.AttrOf':
            return _AttrOf().semanal
        return None

class _AttrOf(object):
    @fallback_to_any_on_error
    def semanal(self, ctx: AnalyzeTypeContext) -> MypyType:
        object_type = ctx.api.anal_type(ctx.type.args[0])
        argument_type = ctx.api.anal_type(ctx.type.args[1])

        assert isinstance(object_type, Instance)
        assert isinstance(argument_type, LiteralType)
        assert isinstance(argument_type.value, str)

        sym = object_type.type.names[argument_type.value]
        return sym.node.type
```

The logic is pretty simple: we bound both unbound types, then I use the second literal type to get the required information from the SymbolTable. And it works for simple cases, like the one in the example above. Problems come when requested attr type is a method:

```python
class User(object):
    def auth(self, username: str, password: str) -> bool:
        return False  # Just an example

def get_callback(user: User) -> AttrOf[User, Literal['auth']]:
    return user.auth
# ex.py:14: error: Incompatible return value type (got "Callable[[str, str], bool]", expected "Callable[[User, str, str], bool]")
```

There's a problem with an extra `User` parameter. AFAIK, I can use [`analyze_member_access`](https://github.com/python/mypy/blob/65e3a89890518aa2ce7bf2e37579c927267c3851/mypy/checkmember.py#L81) to fix that. But, there's no `TypeChecker` instance during the `get_type_analyze_hook`. And it is impossible to do any type checking during this hook (which is intended). And this simple feature becomes impossible to implement. 😞 

The same is applied for other plugins I am working on, like simulated HKT support or typeclasses. 

### Proposed solution

I propose to add a mechanism to provide type-checker instance together with semanal API.
It might be called at the very end of semanal phase, when there are no unbound types left.

Does this sound like a good idea?

Best, 
Nikita Sobolev

**Comment by JukkaL** [comment]
Unfortunately this won't work, since some AST state may not be fully initialized during semantic analysis, and calling into the type checker won't be safe. To achieve what you want to do, you'd need to figure out how to implement this using what the semantic analyzer has access to. Maybe you can duplicate enough of the behavior what the type checker does (but you won't be able to do everything).

**Comment by sobolevn** [comment]
@JukkaL can we go another way? Can we provide some hook to process `AttrOf[User, Literal['auth']]` with the typechecker?

**Comment by JukkaL** [comment]
That's not possible either. Type annotations are always resolved during semantic analysis.

**Comment by sobolevn** [comment]
Are there any reasonable work-arounds you can recommend for my use-case? I would really love to ship this feature.
And what is even more important, my other project with `HKT` emulation suffers the same problem.

Any help is appreciated 🙂

**Comment by JukkaL** [comment]
To remove the `self` type, you can look at `bind_self` and implement a simplified version of that perhaps? Note that most type operations are not allowed during semantic analysis, but you can strip out the first argument type safely.

You won't be able to support attributes whose types are inferred during type inference, however. But for things that have explicit type annotations this might work. It will be quite hacky though. I can't see a way to implement this in a way that works generally.

**Comment by sobolevn** [comment]
This means I would have to stop working on these projects for now 😞 

Thanks a lot for your time and the help! 👍
