### ISSUE TITLE
String not recognized as hashable when key in dict

### ISSUE THREAD

**Issue by jenssss** [python/mypy#8855]
When I check the following with mypy
```python
from typing import Hashable, Any, Dict


def iden(x: Dict[Hashable, Any]):
    return x


d = {"spam": 2}

iden(d)
```
I get the error
```
mapping_and_typing.py:10: error: Argument 1 to "iden" has incompatible type "Dict[str, int]"; expected "Dict[Hashable, Any]"
```
I expected this to pass type checking, since `str` is `Hashable`.

I tested using mypy 0.770 and 0.770+dev.aa97427dad5b8e61c23f59ee500e86d34d326a33, with no flags.

**Comment by JelleZijlstra** [comment]
The invariance demon strikes again! See https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance.
