### ISSUE TITLE
Overloaded callable protocol not checking correctly

### ISSUE THREAD

**Issue by pmeier** [python/mypy#8856]
* Are you reporting a bug, or opening a feature request?
 
    This is a bug report, although it could also be a usage error on my end. I asked this on the [`python/typing` Gitter](https://gitter.im/python/typing?at=5ec221cb49a1b73184801a11) and was [encouraged to open an issue](https://gitter.im/python/typing?at=5ec45000b0256038f9dd6c60) here. During the discussion [PEP612](https://www.python.org/dev/peps/pep-0612/) was mentioned as possible (easy) solution, but this has not been accepted yet.

* Please insert below the code you are checking with mypy.

    I'm trying to solve the following: I want to annotate a Callable in way that enforces the first positional argument to be `str` but leaves the remaining signature as well as the output type arbitrary. I unsuccessfully came up with this:

    ```python
    from typing import Any, overload
    from typing_extensions import Protocol  # py36
    
    
    class StrCallable(Protocol):
        @overload
        def __call__(self, x: str) -> Any:
            ...
    
        @overload
        def __call__(self, x: str, *args: Any) -> Any:
            ...
    
        def __call__(self, x: str, *args: Any, **kwargs: Any) -> Any:
            ...
    
    
    def foo(fn: StrCallable) -> StrCallable:
        pass
    
    
    @foo
    def bar1(x: str) -> str:
        pass
    
    
    @foo
    def bar2(x: str, *args: Any) -> str:
        pass
    
    
    @foo
    def bar3(x: str, *args: Any, **kwargs: Any) -> str:
        pass
    ```

* What is the actual behavior/output?

    [mypy-playground](https://mypy-play.net/?mypy=0.770&python=3.6&gist=ffc97e1aba8cceb57d2876df85fea51e)
    ```
    error: Argument 1 to "foo" has incompatible type "Callable[[str], str]"; expected "StrCallable"
    ```
    (pointing to the decorator of `bar1`) 

* What is the behavior/output you expect?

    Run without error.

* What are the versions of mypy and Python you are using?

    `python==3.6.9`, `mypy==0.770`

**Comment by JukkaL** [comment]
This is behaving as expected. `StrCallable` defined a type where `__call__` must be an overloaded function. 

Defining the decorator as an overloaded function might work. Or maybe you can use a type variable with a value restriction over some callable protocols. I don't think that there is a very satisfactory alternative, however.

**Comment by pmeier** [comment]
> `StrCallable` defined a type where `__call__` must be an overloaded function.

In that case, why are `bar2` and `bar3` checked fine? How are they identified as overloaded callable?

> Or maybe you can use a type variable with a value restriction over some callable protocols.

Could you elaborate? The whole point that I wanted to have a specific signature that AFAIK not achievable without a `Protocol`. How is a value restriction here of importance other than the `str` annotation of the first parameter?

**Comment by scanny** [comment]
Excellent question I thought @pmeier, exactly the situation I encountered. Here's how I solved it, for the benefit of others who end up here on search as I did:

```python
from __future__ import annotations

from typing_extensions import Protocol, TypeAlias


class _NoArgsStrCallable(Protocol):
    def __call__(self, x: str) -> Any: ...

class _ArgsStrCallable(Protocol):
    def __call__(self, x: str, *args: Any) -> Any: ...

StrCallable: TypeVar = _NoArgsStrCallable | _ArgsStrCallable
```
