### ISSUE TITLE
Use of NewType in function

### ISSUE THREAD

**Issue by MiroFurtado** [python/mypy#8860]
I'm currently trying to use NewType in a function 

~~~python
from typing import NewType

class Axis: pass

def NewAxis(name):
    return NewType(name, Axis)

MyAxis = NewAxis('MyAxis')

a: MyAxis = 5
~~~

This obviously works during runtime, but when running mypy it gives ` error: Variable "check_types.Vocab" is not valid as a type`

I'm curious if this is intentional and/or open to discussion - it would be helpful for my usecase at least. Alternatively, exposing new type creation to plugins would help.

**Comment by JelleZijlstra** [comment]
Mypy generally doesn't support dynamic creation of types. It's not something we're likely to work on soon and it might be difficult to get right, but a PR adding support might be accepted.

**Comment by JukkaL** [comment]
I'm closing this since it seems unlikely that we'll directly support this. Supporting this via a plugin might be feasible at some point. If somebody wants to pursue the plugin approach feel free to open a new issue. However, I'd like to see a proposed extension to the plugin API.
