### ISSUE TITLE
Feature: reveal_type should work from comments

### ISSUE THREAD

**Issue by ramalho** [python/mypy#8864]
It would be great if reveal_type could be called from comments.

Mypy already looks at various comments to do its job, and reveal_type is not a runtime function, it only exists during a type check.

While experimenting with type hints in test code, I could write this:

`a = some_func()  # reveal_type(a)`

Instead of:

```
a = some_func()
if typing.TYPE_CHECKING:
    reveal_type(a)
```

**Comment by JukkaL** [comment]
I'm not sure if this would be a net improvement. Now it's possible to comment out uses of `reveal_type` to temporarily silence them. What do others think?

Also, this may be tricky to support since the parser we use drops most comments, I think.

**Comment by ramalho** [comment]
Thanks for you response and your work on Mypy, @JukkaL.

The syntax for the comment can be different, to accommodate the current use of commenting out uses of `reveal_type`, and make it easier for the parser. Maybe this:

```
a = some_func() # type: reveal_type(a)
```

Before focusing on the syntax of the comment, what do people think of the idea of having a way to put calls to `reveal_type` in test suites in a way that does not interfere with running the tests, and also doesn't require the cumbersome `if TYPE_CHECKING` guards?

**Comment by msullivan** [comment]
It doesn't seem to me that it would be enough less cumbersome than `if
TYPE_CHECKING` to be worth having and documenting as an extra feature

**Comment by ramalho** [comment]
`reveal_type()` is a great debugging and learning feature.

My use case is as a teacher and a writer: I have code that is tested with pytest, and is sprinkled with `reveal_type` to demonstrate Mypy's type inference. Perhaps having `if TYPE_CHECKING` guards is not too bad in normal Mypy usage, but in my examples it does add noise.

I am biased, but I do believe that features that help with learning should be carefully considered, even if they don't seem useful to those with a lot of experience with the tool.

**Comment by AlexWaygood** [comment]
@ramalho, does the [recent addition of `typing.reveal_type`](https://github.com/python/cpython/pull/30646) to the stdlib work for your use case? (It will be new in 3.11, but [has also been added](https://github.com/python/typing/pull/1055) to the `typing_extensions` backports package.)

**Comment by ramalho** [comment]
No, it does not solve my use case. Please consider my initial feature request and my responses to the other comments. Thanks!

**Comment by JelleZijlstra** [comment]
The use case seems too marginal to justify the complexity, especially now that we have the runtime `reveal_type()` available so you shouldn't need `if TYPE_CHECKING:`.

**Comment by ramalho** [comment]
I agree @JelleZijlstra. I did not know that `reveal_type()` would no longer require the `if`. Thanks!
