### ISSUE TITLE
Problem with Python 3.9.0a5

### ISSUE THREAD

**Issue by ok2** [python/mypy#8872]
I have tried to test my application on Python 3.9.0 alpha 5, may be it is just a bug of the unstable python, but I get strange error, here small program to reproduce:
```python
from typing import List
def a1(b: List[int]) -> int:
    return b[0]
```

Starting that:
```shell
(py39) $ mypy --show-error-context --pretty --strict test.py
test.py:2: error: syntax error in type comment
    def a1(b: List[int]) -> int:
              ^
Found 1 error in 1 file (checked 1 source file)
```

On python 3.8 environment it works without any problems.

**Comment by hauntsaninja** [comment]
This is a known issue that is fixed on mypy master (https://github.com/python/mypy/issues/8627)
