### ISSUE TITLE
Type definition doesn't work when assigned to a name

### ISSUE THREAD

**Issue by danpascu** [python/mypy#8882]
I have a function that is supposed to receive an argument that is either a type or a tuple of types. 
If I use Union[T, Tuple[T, ...]] in the function signature directly it works as expected, but if I assign this type definition to a name and use that name instead it no longer works and accepts anything for the argument without reporting an error.

The minimal code that showcases the issue is this:

```
from typing import TypeVar, Tuple, Union

T = TypeVar('T', bound=type)
TypeFilter = Union[T, Tuple[T, ...]]

def func1(t: TypeFilter = None):
    pass

def func2(t: Union[T, Tuple[T, ...]] = None):
    pass

func1(None)        # ok
func1(str)         # ok
func1((str, int))  # ok
func1(1)           # should fail but it doesn't

func2(None)        # ok
func2(str)         # ok
func2((str, int))  # ok
func2(1)           # it fails as expected
```

I use python 3.7.1 and mypy 0.770 with no flags (mypy script.py)

I am unsure if I hit a bug in mypy or I'm doing something wrong. If I inspect the annotations for the 2 functions they look the same, so in that regard assigning the type definition to a name seems to work, but when it comes to actually detecting the type, it fails for func1.

I am also a bit confused by the error message for func2(1):

```
Argument 1 to "func2" has incompatible type "int"; expected "Optional[Tuple[<nothing>, ...]]"
```

Why does it say ```Tuple[<nothing>, ...]```? I would have expected to see ```Tuple[~T, ...]```

Also why is it only Optional[Tuple[...]]? That sounds like just an optional tuple, but the definition says T or Tuple[T, ...]. I tried to extend the type definition to ```Union[T, Tuple[T, ...], None]``` but it didn't make any difference. The error message remains the same.

**Comment by JelleZijlstra** [comment]
Have you tried `TypeFilter[T]` for `func1`? You're missing the type argument to the generic alias.

The error messages for the second case sound like mypy isn't considering the typevar's bound properly in generating error messages.

Maybe your real code is more complicated, but in your example you shouldn't actually need a type variable; you should be able to just use `Union[Type[Any], Tuple[Type[Any], ...]]`.

**Comment by danpascu** [comment]
```TypeFilter[T]``` works, thanks. It's just a bit counter intuitive, because when I inspect the annotations for the 2 functions in python they are the same, so python accepts the aliasing of the type definition without requiring the type argument and produces the same result in annotations.

My code is not much more complicated. What I try to do is have a function accept a type filter which can be None, a type or a tuple of types. When not None, the type_filter is directly passed to isinstance to filter out the result. Something like this:

```
def func(type_filter=None):
    ...
    values = ...  # compute list of values
    if type_filter is None:
        return values
    else:
        return [v for v in values if isinstance(v, type_filter)
```

The reason why I added a TypeVar and tried to alias ```Union[T, Tuple[T, ...]]``` to TypeFilter is because I need to use it in multiple places. Something like ```Union[Type[Any], Tuple[Type[Any], ...]]``` would not only make the code a lot more verbose and less readable IMO, but is also prone to errors as it is easy to mistype it if one has to type it many times. That's why I tried to alias it (I wanted to avoid typing the Union everywhere).

**Comment by danpascu** [comment]
I just experimented a bit and I found that I can alias it like this:

```
TypeFilter = Union[Type, Tuple[Type, ...]]
```

and then I can use it directly as ```def func(filter: TypeFilter = None)``` without the need for the TypeVar and the type argument. I wasn't aware of typing.Type, which removes the need for the TypeVar. Thanks for the suggestion.

**Comment by danpascu** [comment]
Unless you want to take a look at those error messages, you can close this issue.

**Comment by danpascu** [comment]
I'm trying to understand the reason why the type argument is needed needed again with ```TypeFilter[T]```.

When I put ```Union[T, Tuple[T, ...]]``` directly in the annotation of the function it works and the type variable ```T``` is mentioned in the type definition, so that version is clear.

If I alias it like ```TypeFilter = Union[T, Tuple[T, ...]]```, the type variable is also mentioned in the definition, so in my initial example assumed it was tied to TypeFilter. So why does one need to mention it again when using TypeFilter in an annotation like ```TypeFilter[T]``` and why doesn't it already know that TypeFilter is associated with T?
