### ISSUE TITLE
Expression type contains Any with await

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#8884]
With a line like:
`response = cast(TokenResponse, await resp.json())`
I get:
`Expression type contains "Any" (has type "Coroutine[Any, Any, Any]")  [misc]`

I assume this is because the `resp.json()` is still evaluated with Any, before the `await`.

It seems like the correct code is therefore:
`response = await cast(Coroutine[None, None, TokenResponse], resp.json())`

But, is there a nicer way to do this, or can we avoid the Mypy warning when it is only used in an await, thus allowing the first example to work?

**Comment by hauntsaninja** [comment]
Yes, `cast(..., resp).json()` or just good ol' type ignore is the way to go. I think moving around which expression is Any would be more confusing.
In general, `--disallow-any-expr` and friends aren't particularly usable. Your other issue #9153 is a better place to discuss that.
