### ISSUE TITLE
MutableSequence[MutableSet[Any]] does not take List[Set[int]

### ISSUE THREAD

**Issue by RexYuan** [python/mypy#8909]
* Are you reporting a bug, or opening a feature request?
Reporting a bug.
* Please insert below the code you are checking with mypy
```
from typing import *
#from z3 import *

def o() -> List[Set[int]]:
    return [{1,2}]

def f(a : MutableSequence[MutableSet[Any]] ):
    return a
x = o()
reveal_type(x)
f(x)
```
* What is the actual behavior/output?
```
note: Revealed type is 'builtins.list[builtins.set[builtins.int]]'
error: Argument 1 to "f" has incompatible type "List[Set[int]]"; expected "MutableSequence[MutableSet[Any]]"
Found 1 error in 1 file (checked 1 source file)
```
* What is the behavior/output you expect?
It should clear the check as if I understand correctly, `MutableSequence[MutableSet[Any]]` should take `List[Set[int]`
* What are the versions of mypy and Python you are using?
mypy 0.761 and Python 3.8.2
* What are the mypy flags you are using? (For example --strict-optional)
None

**Comment by JelleZijlstra** [comment]
This is because `MutableSequence` is invariant. See https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance.
