### ISSUE TITLE
Incompatible return value type

### ISSUE THREAD

**Issue by aabramovrepo** [python/mypy#8910]
Dear All,

   running mypy on the code:

```
from typing import Dict, List, Union

ListItemType = List[Dict[str, Union[str, float, int]]]


def get_item_list() -> ListItemType:
    my_list = list()

    item_1 = {'param_1': 'string one',
              'param_2': 3.4,
              'param_3': 10}

    item_2 = {'param_1': 'string two',
              'param_2': 55.4,
              'param_3': 22}

    my_list.append(item_1)
    my_list.append(item_2)

    return my_list


def main():
    my_list = get_item_list()
    print(my_list)


if __name__ == '__main__':
    main()

```

I get the following error:

`main.py:24: error: Incompatible return value type (got "List[Dict[str, object]]", expected "List[Dict[str, Union[str, float, int]]]")
`
any ideas what can be wrong here? 

Many thanks in advance!

Best,
Alexey

**Comment by JelleZijlstra** [comment]
`List` is invariant. See https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance.
