### ISSUE TITLE
mypy cannot parse type comment of "with" and "for" statement in PEP 484

### ISSUE THREAD

**Issue by t2y** [python/mypy#892]
- https://www.python.org/dev/peps/pep-0484/#type-comments

I tried to check type comments, but it cannot parse "with" and "for" statement as below.

``` python
# Example 1
x = []   # type: List[Employee]
x, y, z = [], [], []  # type: List[int], List[int], List[str]
x, y, z = [], [], []  # type: (List[int], List[int], List[str])
x = [
   1,
   2,
]  # type: List[int]

# Example 2
from contextlib import contextmanager

@contextmanager
def frobnicate():
    yield 1

with frobnicate() as foo:  # type: int
    # Here foo is an int
    ...

# Example 3
points = [(1.0, 2.5)]  # type: List[Tuple[float, float]]
for x, y in points:  # type: float, float
    # Here x and y are floats
    ...
```

``` bash
$ mypy type_comments.py 
type_comments.py:17: error: Parse error before "int"
type_comments.py:23: error: Parse error before "float"
```

**Comment by o11c** [comment]
Not supporting type comments of anything other than a function (is that even in the PEP?) or assignment is a known bug. I'm currently rewriting the parser (to track location information better and give better errors) but haven't gotten to type comments yet.

Ugh, since when are tuples of types directly supported? I know it's given in an example in the PEP, but it doesn't *specify* this stuff at *all*.

@gvanrossum What are we supposed to do about an unclear PEP?

**Comment by mgeisler** [comment]
I ran into this today and have resorted to using `cast` on the context manager:
```python
with cast(BinaryIO, open(path, 'rb')) as fp:
    # use fp...
```
That makes the work-around nicely localized.

**Comment by gvanrossum** [comment]
Since this is specified in PEP 484, mypy should support it. But it's not high priority.

**Comment by ddfisher** [comment]
The WIP fast parser (#1353) supports parsing types on `with` statements, so this should be easier to implement after that lands.

**Comment by gvanrossum** [comment]
Moving to 0.5.0 given we aren't very far with the fast parser yet and this feels pretty unimportant.

**Comment by gvanrossum** [comment]
(This is still TODO; we parse those type comments but don't use them.)

**Comment by afrieder** [comment]
How would type comments work with multiple targets in `with` stmts. For example:
```python
with X as (x, y), Z as (z, w):  # type: ...?
```
Would the type comment be of the form `# type: int, float, float, int`, where the number of elements in the type-tuple must match the number of targets in the with?

**Comment by gvanrossum** [comment]
Maybe like this:
```python
with X as (a, b):  # type: Tuple[int, float]
    ...
with X as (a, b), Y as (c, d):  # type Tuple[int, float], Tuple[str, str]
    ...
```
This may be tricky because IIRC the `# type:` parser currently only doesn't allow more than one top-level type.

**Comment by ddfisher** [comment]
I think this should work okay for the new parser, actually.  `Tuple[int, float], Tuple[str, str]` is a valid Python expression which parses the same as `(Tuple[int, float], Tuple[str, str])`, so there shouldn't be an issue.  (And I tried `mypy -c 'x, y = 1, 2  # type: int, str'`, which works and gives you the error you'd expect.)
