### ISSUE TITLE
Should TypedDict be compatible with Dict[str, Any] ?

### ISSUE THREAD

**Issue by dmerejkowsky** [python/mypy#8923]
This is more a question than a bug report per se.

Here it is.

I have the following code:

```python
from typing import Any, Dict, TypedDict


IndexContext = TypedDict("IndexContext", {"user": str})


def get_context() -> IndexContext:
    return {"user": "john"}


def render(context: Dict[str, Any]) -> None:
    print(context)


def main() -> None:
    context = get_context()
    render(context)
```

Here's what I get when running mypy:

```
$ mypy foo.py
foo.py:17: error: Argument 1 to "render" has incompatible type "IndexContext"; 
  expected "Dict[str, Any]"
Found 1 error in 1 file (checked 1 source file)
```

I was expecting that mypy would not complain, because the `IndexContext` seems compatible with a plain `Dict[str, Any]`. Am I missing something ?

**Comment by sobolevn** [comment]
Some context: https://github.com/typeddjango/django-stubs/issues/355

**Comment by dmerejkowsky** [comment]
Sorry, this is a duplicate of #4976  (I somehow missed it when I open this issue). Let's close this one.
