### ISSUE TITLE
Collection of Generic[T] and Generic[real type] becomes Collection[object]

### ISSUE THREAD

**Issue by crusaderky** [python/mypy#8947]
```python
import asyncio
from typing import Awaitable, TypeVar

T = TypeVar("T")


async def f(aw: Awaitable[T], t: asyncio.Task[None]) -> None:
    futs = {aw, t}
    await asyncio.wait(futs)
    reveal_type(futs)
```

mypy 0.780 output:
```
9: error: Argument 1 to "wait" has incompatible type "Set[object]"; expected "Iterable[Union[Future[<nothing>], Generator[Any, None, <nothing>], Awaitable[<nothing>]]]"
10: note: Revealed type is 'builtins.set[builtins.object*]'
Found 1 error in 1 file (checked 1 source file)
```
Expected output:
```
10: note: Revealed type is 'builtins.set[Union[Awaitable[T], asyncio.Task[None]]]'
```

The issue disappears if I either
- replace ``Awaitable[T]`` with ``Awaitable[None]``
- replace ``Task[None]`` with ``Task[Any]``

This issue is not new in 0.780; however starting from 0.780 ``asyncio.create_task`` propagates the return type of its input whereas before it was returning ``Task[Any]``, so it makes the issue crop up.

**Comment by JukkaL** [comment]
Mypy can't infer a good enough type for `futs`. The recommended workaround is to add a type annotation for `futs`. This is basically an instance of #3816.
