### ISSUE TITLE
False positive "Missing return statement" when exception is raised from function in try-except block

### ISSUE THREAD

**Issue by jamesbraza** [python/mypy#8964]
I am reporting what I think is a bug in mypy.  I think it raises a false positive `error: Missing return statement` when one has a function that is guaranteed to raise an exception (never return) while in the except clause of a try statement.

---

**Code Sample**

`false_pos_no_return.py`:

```python
def raise_exception():
    raise Exception


def test() -> int:
    try:
        return 1
    except Exception:
        raise_exception()
```

What mypy reports:

```
path/to/false_pos_no_return.py: note: In function "test":
path/to/false_pos_no_return.py:5: error: Missing return statement  [return]
```

---

**Workarounds**

One can add either of the following statements at the end of the except clause:
- `raise`
- `assert False`

And the error goes away: `Success: no issues found in 1 source file`

---

**Expectations**

My expectations are that mypy should be able to detect that `raise_exception` will never actually return.

---

**Similar Issues**

https://github.com/python/mypy/issues/1229 seems to be similar, but it seems a decisive conclusion wasn't reached.

---

**Versions**

```
python==3.6.5
mypy==0.780
```

**Comment by JelleZijlstra** [comment]
You should annotate `raise_exception()` as returning `typing.NoReturn`. By default, mypy assumes all functions return something.

**Comment by jamesbraza** [comment]
Ah yes, that does it!  Thank you again @JelleZijlstra!

**Comment by andredasilvapinto** [comment]
what if `raise_exception()` lives in an external library that you cannot change?

**Comment by JelleZijlstra** [comment]
@andredasilvapinto you could provide a stub file for the library, or write something like `assert False, "unreachable"` to help mypy.

**Comment by jamesbraza** [comment]
I believe the answer in that case is to make a stub, read [here](https://mypy.readthedocs.io/en/stable/stubs.html).  I am not sure how to make an in-module stub.  If you figure it out, I would be interested to see the syntax.

You could also use `typing.cast`.  See here:

```python
from typing import Callable, NoReturn, cast

from .third_party_lib import raise_exception  # Return type is not type hinted

def test() -> int:
    try:
        return 1
    except Exception:
        # raise_exception()  # mypy error
        cast(Callable[[], NoReturn], raise_exception)()  # mypy success

if __name__ == "__main__":
    test()
```
