### ISSUE TITLE
mypy dosn't get type through function wrapper

### ISSUE THREAD

**Issue by mde-pach** [python/mypy#8967]
* Are you reporting a bug, or opening a feature request?
**Bug**
* Please insert below the code you are checking with mypy
```python
# test.py
import typing

def return_string() -> str:
    return "a string"

def wrapper() -> typing.Callable:
    return return_string

def return_test_result() -> str:
    wrapped_fun = wrapper()
    return wrapped_fun()
```
better example [bellow](#issuecomment-640728046)
* What is the actual behavior/output?
```
test.py:11: error: Returning Any from function declared to return "str"
        return wrapped_fun()
        ^
Found 1 error in 1 file (checked 1 source file)
```
* What is the behavior/output you expect?
no error
* What are the versions of mypy and Python you are using?
`python3.6.8`
`mypy==0.780`
* What are the mypy flags you are using? (For example --strict-optional)
`mypy --warn-return-any`

As you can see in the (simplified) code, I got a function (`wrapper`) that return another function (`return_string`) that return a `str` type.

I don't know if it's my usage of python annotations that is incorrect in this specific situaton but it seems a bug to me because the function `return_test_result` return an str typed var.

It seems to have a missing "depth callable" behavior in Mypy here

**Comment by Kangaroux** [comment]
You need to explicitly declare what kind of callable it's returning:

```python
def wrapper() -> typing.Callable[[], str]:  # Callable[ [ arg_types ], return_type ]
    return return_string
```

**Comment by Kangaroux** [comment]
A little more info about what's going on.

```python
def wrapper() -> typing.Callable:
    return return_string

reveal_type(wrapper)
# Revealed type is 'def () -> def (*Any, **Any) -> Any'
```

Whenever you don't specify a type it always defaults to `Any`. So if you just say `typing.Callable` what you're telling mypy is that this is a callable, period. You're not making any claims about what the callable looks like.

In other words,

```python
def return_string() -> str
```

can also be written as

```python
def return_string(*args, **kwargs) -> str
```

And because `str` is a subset of `Any` the types match so mypy doesn't complain

**Comment by mde-pach** [comment]
Ok, I understand your point. But this example is a simplified one and I think that the related point you are talking about it's not the one I wanted to expose there.

With an other example:
```
# test.py
import typing

def return_string() -> str:
    return "a string"

def wrapper(wrapped_thing: typing.Any) -> typing.Any:
    return wrapped_thing

def return_test_result() -> str:
    wrapped_fun = wrapper(return_string)
    return wrapped_fun()
```

In this situation, my `wrapper` return `Any` for a good reason, because it can't know what it will return.
But my `return_test_result` knows which type of var is sent to `wrapper` so it knows the return value. What is the good implementation in this case ?

**Comment by Kangaroux** [comment]
@mde-pach 

If `wrapper` returns `Any`, and `return_test_result` returns `str`, then they aren't compatible.

All `str` are compatible with `Any`. Not all `Any` are compatible with `str`.

mypy is complaining because you're trying to go from `Any -> str`, which without a type cast won't work. However, if you went from `str -> Any` that would be ok, since `str` is a subset of `Any`.

**Comment by Kangaroux** [comment]
```python
class MyAny:
    pass

class MyStr(MyAny):
    pass

print(issubclass(MyAny, MyStr))  # Any -> str isn't valid
print(issubclass(MyStr, MyAny))  # Can convert str -> Any
```

**Comment by mde-pach** [comment]
Ok I didn't know `typing.cast` until now that fix my issue.
Because I know the type of my `Any` returned var, I can cast it with `typing.cast(wrapped_fun(), str)` that fix my point.

Thank you !

**Comment by JelleZijlstra** [comment]
A better type for your `wrapper` would actually be:

```python
from typing import TypeVar

T = TypeVar("T")

def wrapper(obj: T) -> T:
     return obj
```
This will tell mypy that the function returns the same type it takes.

**Comment by mde-pach** [comment]
Yes but in this case I don't have the control of the wrapper :)
