### ISSUE TITLE
Is there a way to exclude python executables (not ending in .py) from mypy?

### ISSUE THREAD

**Issue by kevinmu** [python/mypy#8971]
I have a folder containing many python executable scripts with no `.py` file extension. I'm wondering if there is a way to exclude these scripts from mypy via the config or some other method?

I've tried adding the folder to the config file with 

```
[mypy-pythonscripts.*]
ignore_errors = True
```

and even added an `__init__.py` file in that folder, but mypy still seems to pick it up. I guess it doesn't recognize the files as modules? Thanks for your help!

**Comment by hauntsaninja** [comment]
Hi Kevin, hope you're doing well :-)

I can't repro the issue as described:
```
λ ls -l tmp                             
total 8
-rwxr-xr-x  1 shantanu  staff  51 Jun  8 16:56 lol

λ cat tmp/lol       
#!/usr/bin/env python3
print("hi")
a: int = "asdf"

λ mypy tmp
There are no .py[i] files in directory 'tmp'

λ # Note if I check the file directly, mypy will check it
λ mypy tmp/lol
tmp/lol:3: error: Incompatible types in assignment (expression has type "str", variable has type "int")
Found 1 error in 1 file (checked 1 source file)
```

Maybe share more details about your config or how you're invoking mypy, or see if you can provide a small reproducer?

**Comment by kevinmu** [comment]
@hauntsaninja Thanks for the response! I'm invoking `mypy` through `arc lint,` which in turn actually does invoke `mypy` on each changed file individually.

Interesting that the behavior is different when invoking on a directory vs on a specific file.

**Comment by kevinmu** [comment]
Actually I found that I could just exclude those files from arc lint directly. So if you don't think it would be valuable to change the behavior of mypy in this case, I am happy to close this issue.

**Comment by hauntsaninja** [comment]
Sounds good!
