### ISSUE TITLE
Error to infer types from a curried function with more than two args

### ISSUE THREAD

**Issue by thepabloaguilar** [python/mypy#8978]
This is possibly a **BUG**

I'm using [returns](https://returns.readthedocs.io/en/latest/) lib that provide fully typed functions, it has a [curry decorator](https://returns.readthedocs.io/en/latest/pages/curry.html#id3). I'm trying to use it, but `mypy` has got an error when we have a curried function with more than two args and try to create a [Result container](https://returns.readthedocs.io/en/latest/pages/result.html) with the function.

[Result.from_value(...) source code](https://returns.readthedocs.io/en/latest/_modules/returns/result.html#Result.from_value)
[@curry source code](https://returns.readthedocs.io/en/latest/_modules/returns/curry.html#curry)

Working example:
```python
from returns.curry import curry
from returns.result import Result

@curry
def first(a: int, b: int) -> int:
    ...

reveal_type(
    Result.from_value(first),
)
# Revealed type is 'returns.result.Result[Overload(def (a: builtins.int) -> def (b: builtins.int) -> builtins.int, def (a: builtins.int, b: builtins.int) -> builtins.int), Any]'
```

Nonworking example:
```python
from returns.curry import curry
from returns.result import Result

@curry
def first(a: int, b: int, c: int) -> int:
    ...

reveal_type(
    Result.from_value(first),
)
```
mypy output:
```sh
ex.py:9: note: Revealed type is 'returns.result.Result[Overload(def (a: builtins.int) -> Overload(def (b: builtins.int, c: builtins.int) -> builtins.int, def (b: builtins.int) -> def (c: builtins.int) -> builtins.int), def (a: builtins.int, b: builtins.int) -> def (c: builtins.int) -> builtins.int, def (a: builtins.int, b: builtins.int, c: builtins.int) -> builtins.int), Any]'
ex.py:9: error: Argument 1 to "from_value" of "Result" has incompatible type overloaded function; expected overloaded function
Found 1 error in 1 file (checked 1 source file)
```
---

**Versions**
* mypy: 0.770
* returns: 0.0.14
* Python: 3.8.2

My config file:
```cfg
[mypy]
# suppress errors about unsatisfied imports
ignore_missing_imports=True

# Custom plugins
plugins =
    returns.contrib.mypy.returns_plugin

# be strict
warn_return_any = True
strict_optional = True
warn_no_return = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_any_generics = True

disallow_untyped_defs = True
check_untyped_defs = True

# Temporally disabled
disallow_untyped_calls = False
```

Refs: https://github.com/dry-python/returns/issues/410

**Comment by ilevkivskyi** [comment]
Can you post a self-contained example? There is a known very old bug that generic functions when passed as arguments to another generic functions don't work.

**Comment by sobolevn** [comment]
Oups! I have posted a duplicate: https://github.com/python/mypy/issues/9017
But, I have posted a reproduction link: https://github.com/sobolevn/mypy-bug-410

**Comment by JukkaL** [comment]
This looks like a bug, though it might plausibly be an issue with the returns plugin.

Using a complex overloaded function as a type variable doesn't seem to work in the example, even though it isn't generic.

**Comment by sobolevn** [comment]
Oups, I forgot about this issue. I was able to find a hacky solution here: https://github.com/python/mypy/issues/9147
