### ISSUE TITLE
Path escaping bug in HTML report

### ISSUE THREAD

**Issue by angusholder** [python/mypy#8979]
Bug in MyPy 0.780 with Python 3.7.1 on Windows 10, including args `--html_report coverage_report/`

The template for the HTML report includes a path without normalizing the path separators, so on windows uses '\\' instead of '/', and this appears in the browser as %5C: 

    <a href="html/example%5Capp%5Cmain.py.html">example.app.main</a>

The browser then misbehaves when when navigating to this url with backslashes in it, appearing like so in the URL bar

    file:///C:/proj/example/coverage_report/html/example\app\main.py.html

It can be found [here](https://github.com/python/mypy/blob/793cf187f0e529f9d6623a512ae0149124ded542/mypy/xml/mypy-html.xslt#L40) in the template, and I believe is formatting [the name property](https://github.com/python/mypy/blob/793cf187f0e529f9d6623a512ae0149124ded542/mypy/nodes.py#L286-L288) of the `MyPyFile` class

**Comment by ilevkivskyi** [comment]
Thanks for reporting! PRs are welcome.
