### ISSUE TITLE
Weird behaviour on os.path.* in 0.870

### ISSUE THREAD

**Issue by dchirikov** [python/mypy#8980]
Updating mypy to the latest (0.870) version I got it complaining about the following code:
```
import os
path = "/tmp"
for call in [os.path.exists, os.path.isdir]:
    assert(call(path))
```
```
test.py:3: error: List item 0 has incompatible type "Callable[[Union[AnyStr, _PathLike[AnyStr]]], bool]"; expected "Callable[[_PathLike[AnyStr]], bool]"
test.py:4: error: Argument 1 has incompatible type "str"; expected "_PathLike[AnyStr]"
```
0.770 version is happy with it.
Is this an expected behavior, or a bug?

If it is expected - what's the proper way to make the latest mypy happy?

**Comment by JelleZijlstra** [comment]
This sounds similar to #8961 and #8962.

**Comment by AlexWaygood** [comment]
[Can't reproduce](https://mypy-play.net/?mypy=0.902&python=3.10&gist=3651d8a3a96519748be616bcdb90f1d4) on mypy 0.902+.
