### ISSUE TITLE
'Any' with a bound?

### ISSUE THREAD

**Issue by mthuurne** [python/mypy#8981]
When mypy is run on the following code:

```py
from typing import Any, Generic, TypeVar

T = TypeVar('T', bound=int)

class C(Generic[T]):
    x: T

c: C[Any] = C()
c.x = 123
c.x = 'abc'
```

It will not report any errors. However, since `T` has `int` as a bound, assigning a string to `x` should be considered invalid even if we don't know the exact type of `x`.

It seems that when `Any` is substituted for the type argument of `C`, the knowledge of the bound is lost. Perhaps `AnyType` could be given a bound, `object` by default, to restrict which types `Any` can represent in a particular context.

**Comment by Akuli** [comment]
Plain `C` is same as `C[Any]`. Should that be `C[bound of T]` instead?

**Comment by erictraut** [comment]
This issue appears to be based on a misunderstanding of how `Any` works in the Python type system. For details about how `Any` is meant to work and why it exists, refer to PEP 483.

The use of `Any` as a type argument is especially important in cases where the type parameter is invariant, as the use of any concrete type such as `object` or `bound of T` will result in invariant type incompatibilities.

Mypy is doing the right thing in how it's treating `Any`, and it would be inappropriate to emit an error in any of the above cases.

I recommend closing this issue.
