### ISSUE TITLE
false unreachable error after pytest.raises block

### ISSUE THREAD

**Issue by rkm** [python/mypy#8985]
Hi. mypy returns an unreachable error for code after a `pytets.raises` block:

```shell
$ cat t.py
import pytest

def testeroni() -> None:
    with pytest.raises(Exception):
        raise Exception("oh noes")
    print("hello there")

$ mypy --version
mypy 0.780

$ mypy t.py
t.py: note: In function "testeroni":
t.py:7: error: Statement is unreachable
        print("hello there")
        ^
Found 1 error in 1 file (checked 1 source file)
```

I'm actually not sure if this is a bug in mypy, since it might not be aware that pytest swallows the exception there. Any advice appreciated!

**Comment by bluetech** [comment]
pytest 6 is going to have published type annotations, hopefully ([link](https://github.com/pytest-dev/pytest/blob/c76077c63ef8365b251bfa719452e4f49ce49b4f/src/_pytest/python_api.py#L548-L564)), though we're still working on the details.

**Comment by rkm** [comment]
I'm happy to confirm that this is fixed with https://github.com/pytest-dev/pytest/pull/7448. Thanks again for your work on this @bluetech! :)
