### ISSUE TITLE
Incorrectly flagging annotations from the __future__ module on 3.7.

### ISSUE THREAD

**Issue by SalomonSmeke** [python/mypy#9009]
Please provide more information to help us understand the issue:

In a screenshot:

<img width="536" alt="Screen Shot 2020-06-16 at 13 45 03" src="https://user-images.githubusercontent.com/9869123/84814831-a936ed00-afd7-11ea-95f2-d2b5bbfb04d3.png">

* Are you reporting a bug, or opening a feature request?

🐛

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

`from __future__ import annotations`

* What is the actual behavior/output?

`error: Module '__future__' has no attribute 'annotations'`

* What is the behavior/output you expect?

no ⚠️

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

🐍3.7.7
mypy 0.780
on mypy-0.790+dev.8577ea4c0cfbc9b3ccfcc74b670bd40089a783a8 (master) the problem persists.

* What are the mypy flags you are using? (For example --strict-optional)

none!

**Comment by mwchase** [comment]
I can reproduce this in the playground by switching the Python version to 3.6 (or presumably earlier). Is it possible that mypy is using a different Python version?

**Comment by SalomonSmeke** [comment]
Certainly possible! Let me see if I can hop on another machine.

**Comment by SalomonSmeke** [comment]
<img width="752" alt="Screen Shot 2020-06-17 at 10 43 30" src="https://user-images.githubusercontent.com/9869123/84919391-7c421300-b087-11ea-8f05-bb62d0784223.png">

plot thickens.

**Comment by SalomonSmeke** [comment]
Figured it out! It was 100% user error. I had configured Mypy to think its on 3.6 somehow.

**Comment by dengwxn** [comment]
> Figured it out! It was 100% user error. I had configured Mypy to think its on 3.6 somehow.

I've met the same problem. Could you tell me how I can solve it? Thanks.

**Comment by JelleZijlstra** [comment]
See https://mypy.readthedocs.io/en/stable/command_line.html#platform-configuration

**Comment by SalomonSmeke** [comment]
In my particular case, my problem was that my `mypy.ini` had the python version set to 3.6.
