### ISSUE TITLE
0.781 release missing from pypi

### ISSUE THREAD

**Issue by timsoftgit** [python/mypy#9024]
0.781 has been out for a week but pypi.org/project/mypy still lists 0.780 as the latest version.

**Comment by JukkaL** [comment]
Our release pipeline was broken and the release had to be postponed. It should go out soon. Sorry for the delay!

**Comment by timsoftgit** [comment]
No problems. I noticed the update and was going to update the slackbuild when I spotted the issue. It has missed this weeks deadline, but if it goes out in the next few days I should be able to get it in next weekend's push.
