### ISSUE TITLE
[Feature Request] mypyc support compilation to WebAssembly

### ISSUE THREAD

**Issue by redradist** [python/mypy#9028]
It would be nice to be able to compile Python to WebAssembly as AssemblyScript does https://github.com/AssemblyScript/assemblyscript

This feature not only increase performance of Python Applications, but also expand ecosystem !!

**Comment by ilevkivskyi** [comment]
Mypyc uses separate tracker, transferring there.

**Comment by ilevkivskyi** [comment]
It looks like GitHub transfer doesn't work between orgs, please re-open at https://github.com/mypyc/mypyc/issues
