### ISSUE TITLE
[Feature Request] mypyc support compilation to native executable

### ISSUE THREAD

**Issue by redradist** [python/mypy#9029]
From documentation to mypyc I've read that it compiles to native C extensions and should be run through Python:
```console
python3 -c extension
```

But it limits mypyc to platforms where `CPython` compiles ... (

With adding support compiling to native binary or library we expand warranty of platforms where `Python` could run:
1) Android Native Library
2) iOS Native Library
3) MicroControllers
4) WebAssembly runtimes
5) ... and much more ;)

Python would became even greater !!

**Comment by ilevkivskyi** [comment]
Please re-open at https://github.com/mypyc/mypyc/issues

**Comment by redradist** [comment]
@ilevkivskyi I think we should reopen it here, due to mypyc was moved in this repo
