### ISSUE TITLE
How to deal with *args/**kwargs in decorator?

### ISSUE THREAD

**Issue by waxlamp** [python/mypy#9032]
(`mypy` is a blessing, it has made my programming life far more enjoyable; thank you!)

I am trying to write a generic decorator for a class of functions that take an initial, named argument, followed by arbitrary other arguments. Here's a dummy implementation, showing an "identity" decorator:

```python
F = Callable[[Arg(str, "workspace"), VarArg(), KwArg()], Any]

def deco(f: F) -> F:
    def wrapper(workspace: str, *args: Any, **kwargs: Any) -> Any:
        return f(workspace, *args, **kwargs)

    return wrapper
```

When I try to use this decorator as follows:

```python
@deco 
def do_something(workspace: str) -> Any:
   pass
```

I get the following error from `mypy`:

```
error: Argument 1 to "do_something" has incompatible type "Callable[[str], Any]"; expected "Callable[[str, VarArg(Any), KwArg(Any)], Any]"
```

**Shouldn't `do_something` be compatible with the `VarArg`-laden `Callable` type? If not, what can I do to make this pass typechecking?**

I also tried using a `Protocol` for this:

```python
class WorkspaceFn(Protocol):
    def __call__(self, workspace: str, *args: Any, **kwargs: Any) -> Any: ...
```

Replacing the `F = ...` line from above with `F = WorkspaceFn` yields this similar error message:

```
error: Argument 1 to "do_something" has incompatible type "Callable[[str], Any]"; expected "WorkspaceFn"
```

**Comment by ilevkivskyi** [comment]
Technically mypy is correct, because `(str) -> Any` is not a subtype of `(str, *Any, **Any) -> Any`. But it is pretty typical to use `*args, **kwargs` as a synonym for "don't care". So essentially this is no different than https://github.com/python/mypy/issues/5876

For now you can use:
```python
F = TypeVar('F', bound=Callable[..., Any])
def deco(f: F) -> F:
    ...
```
