### ISSUE TITLE
mypy complains about from typing import TypedDict in python-3.8

### ISSUE THREAD

**Issue by zyxue** [python/mypy#9039]
```
$python --version
Python 3.8.2

$mypy --version 
mypy 0.782

$cat test.py
from typing import TypedDict

$mypy test.py
test.py:1:1: error: Module 'typing' has no attribute 'TypedDict'; maybe "_TypedDict"?
Found 1 error in 1 file (checked 1 source file)
```
Is this expected although TypedDict is available in typing in python-3.8 now?

**Comment by hauntsaninja** [comment]
Your mypy is probably using an older Python.
If you're unable to fix your setup, you can also explicitly pass the Python version you want, eg `mypy --python-version 3.8 test.py`

**Comment by zyxue** [comment]
how does mypy find the python version when `--python-version 3.8` is not specified?

**Comment by hauntsaninja** [comment]
As mentioned in the previous comment:
- mypy will check against the version of Python you use to mypy
- You're probably running mypy with an older version of Python
- You can investigate where your mypy is coming from by running something like `which mypy` and tracking down where that takes you
- You can be explicit about which version of Python you want to use to run mypy by running something like `python3.8 -m mypy ...`

**Comment by zyxue** [comment]
I did the following experiment:

First add a line in mypy script to show the version of python
```diff --git a/mypy b/mypy
index 203961d..f5fb950 100755
--- a/mypy
+++ b/mypy
@@ -3,6 +3,8 @@
 import re
 import sys
 
+print(f'*****{sys.version}*****')
+
 from mypy.__main__ import console_entry
 
 if __name__ == '__main__':
```
Then, run
```
(mypy-playground-gWRARtq9-py3.8) ➜  mypy-playground git:(dev) ✗ mypy test.py                                                                                                                                                           [0] 0s 
*****3.8.2 (default, Mar 25 2020, 11:22:43) 
[Clang 4.0.1 (tags/RELEASE_401/final)]*****
test.py:1:1: error: Module 'typing' has no attribute 'TypedDict'; maybe "_TypedDict"?
Found 1 error in 1 file (checked 1 source file)
```

why am I'm still seeing the error, as you can see the python used to run mypy is 3.8.2.

I also tried `mypy --python-version 3.8 test.py`, which works out, but I'd prefer use mypy without `--python-version`.

**Comment by hauntsaninja** [comment]
Hmm, I'm not sure then. For what it's worth, I've not been able to repro. You wouldn't happen to have configuration in any of [these locations](https://mypy.readthedocs.io/en/stable/config_file.html#the-mypy-configuration-file) that happens to specify a python version, would you?

If you're willing to muck around with mypy code to debug this, maybe try looking around https://github.com/python/mypy/blob/6ee562a8f3e69ac134f8c501b79b3712c9e24bbd/mypy/main.py#L833 and https://github.com/python/mypy/blob/6ee562a8f3e69ac134f8c501b79b3712c9e24bbd/mypy/options.py#L69

**Comment by zyxue** [comment]
Ahh, I see, there was 
```
python_version = 3.7
```
in my `~/.mypy.ini`, I removed it and now it works fine.

Thank you so much for demystifying my problem!
