### ISSUE TITLE
getattr on enum considered as Any instead of enum

### ISSUE THREAD

**Issue by mhooreman** [python/mypy#9044]
### Issue category
Bug: false positive (unless I'm mistaking)

### Description
I'm defining a function which returns an enum member from a member string, using the code below. It is then checked with mypy.

    import enum

    class E(enum.Enum):
        a = enum.auto()
        b = enum.auto()

    def f(x: str) -> E:
        return getattr(E, x)

    print(f('a'))

### Expected behavior

No issue found

### Current behavior

There is a ``[no-any-return]`` issue:

    demo.py: note: In function "f":
    demo.py:8: error: Returning Any from function declared to return "E"  [no-any-return]
            return getattr(E, x)
            ^
    Found 1 error in 1 file (checked 1 source file)

### Notes

I'm not sure if that's the best approach for this use case, but if any case, ``f`` should return a member of ``E``. 

The ``getattr`` function is obviously 'flexible', but since it returns an attribute of a know class, mypy should maybe guess the type of the returned value. So, I'm pretty sure that this is related on analysis of ``getattr`` outcomes.

### Versions

* Python 3.7.4
* Mypy 0.782

**Comment by mhooreman** [comment]
Not really a bug because getattr cannot know what it returns. Using a dict-like syntax like `return E[x]` avoids the issue.

**Comment by JelleZijlstra** [comment]
Note that getattr() on an enum may not even return an enum member: `f("__doc__")` is a string, `f("mro")` a function.
