### ISSUE TITLE
Patch validation stopped working after version upgrade

### ISSUE THREAD

**Issue by staticdev** [python/mypy#9045]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request? Bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
from unittest.mock import Mock
from unittest.mock import patch

import click.testing
import pytest
from pytest_mock import MockFixture

from irpf_cei import __main__

@pytest.fixture
def mock_cei_validate_header(mocker: MockFixture) -> Mock:
    """Fixture for mocking cei.validate."""
    mock = mocker.patch("irpf_cei.cei.validate_header")
    mock.return_value = 2019, "ABC"
    return mock
```

* What is the actual behavior/output?

```
error: Returning Any from function declared to return "Mock" 
[no-any-return]
        return mock
```

* What is the behavior/output you expect?

It should work since I expect a Mock from patch.

* What are the versions of mypy and Python you are using?

v0.782 / 3.8.3

*  Do you see the same issue after installing mypy from Git master?

Didn't try.

* What are the mypy flags you are using? (For example --strict-optional)

```
[mypy]
check_untyped_defs = True
disallow_any_generics = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_decorators = True
disallow_untyped_defs = True
no_implicit_optional = True
no_implicit_reexport = True
pretty = True
show_column_numbers = True
show_error_codes = True
show_error_context = True
strict_equality = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
warn_unused_configs = True
warn_unused_ignores = True

[mypy-tests.*]
disallow_untyped_decorators = False
```

* If mypy crashed with a traceback, please paste
  the full traceback below.

N/A

**Comment by staticdev** [comment]
It seems a fix was pushed to typeshed for this https://github.com/python/typeshed/pull/3871

**Comment by hauntsaninja** [comment]
Yup, no actions for mypy here, we should close this in favour of https://github.com/python/typeshed/issues/4263

**Comment by staticdev** [comment]
Agreed.
