### ISSUE TITLE
None checks not occurring in some function

### ISSUE THREAD

**Issue by robertocarta** [python/mypy#9056]
In the following example the first two functions will result in  `#Item "None" of "Optional[List[ComplexRange]]" has no attribute "__iter__" (not iterable)` in lines 183 and 190, whereas the third functions type checks with no errors. Is this a bug or am I missing something?

![image](https://user-images.githubusercontent.com/15035783/85886299-158acb00-b7e6-11ea-91da-c852760a03bc.png)

**Comment by JukkaL** [comment]
Can you give a self-contained, simplified example that illustrates the issue? The example doesn't show how `CrosswalkRow` is defined, for example.

**Comment by AlexWaygood** [comment]
Closing due to lack of response from OP.
