### ISSUE TITLE
Assertion Error Can't add to finished block

### ISSUE THREAD

**Issue by HJarausch** [python/mypy#9060]
When I try to compile (mypyc) a lengthy Python script I get the
Assertion "Error Can't add to finished block" 
Unfortunately there is no indication which part of my script might have caused this. 
Many thanks for a hint. 
P. S. mypy itself doesn't find any problems

**Comment by JukkaL** [comment]
Can you post the issue to https://github.com/mypyc/mypyc/issues instead? Also, a full stack trace would be helpful, even if mypyc doesn't point to the relevant line.
