### ISSUE TITLE
[Feature request] Recombine complete union of enum literals into original type

### ISSUE THREAD

**Issue by ethan-leba** [python/mypy#9063]
This is feature that I think needs to be implemented before I can publish a PR for issue #6113.

```
from enum import Enum

class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3


x: Color
if x is Color.RED:
    pass
reveal_type(x)
```
*  Actual behavior/output
```
➜  mypy git:(master) ✗ python3 -m mypy leba_misc/test.py
leba_misc/test.py:12: note: Revealed type is 'Union[Literal[test.Color.RED], Literal[test.Color.GREEN], Literal[test.Color.BLUE]]'
```
* Desired behavior/output
```
leba_misc/test.py:12: note: Revealed type is 'test.Color'
```
While this isn't a bug per se, since the type is correct, but it's much less readable than displaying the original type. The problem becomes particularly bad with my implementation of #6113 , displaying `bool` as `Union[Literal[True], Literal[False]]`.

My thoughts on implementation are that it should be done either:
1. As an aesthetic change, only attempting to recombine literal unions for the purposes of user facing messages.
2. As part of the type checker.

Not sure what the best approach is, so I'd like to hear the mypy team's thoughts!

**Comment by JukkaL** [comment]
Agreed that the error message looks awkward, especially if there are many enum items. Doing this as part of the type checker is my favorite, since I'd prefer if error messages roughly corresponded to the internal representation (unless the implementation is tricky).

**Comment by ethan-leba** [comment]
@JukkaL I've created a [pull request](https://github.com/python/mypy/pull/9097) for this issue, any time you get a chance to review would be great!
