### ISSUE TITLE
Combine inheritance with protocol

### ISSUE THREAD

**Issue by jbwdevries** [python/mypy#9074]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
  Most likely a feature request, unless I'm missing something
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```python
from typing_extensions import Protocol


class MyParent:
    pass

class MyChild1(MyParent):
    attr1: str

class MyChild2(MyParent):
    attr1: str

def my_parent_func(arg: MyParent) -> None:
    ...


class MyProtocol(Protocol):
    attr1: str

def my_protocol_func(arg: MyProtocol) -> None:
    ...


def my_combined_func(arg: '?') -> None:
    my_parent_func(arg)
    my_protocol_func(arg)

my_combined_func(MyChild1())
my_combined_func(MyChild2())
```
* What is the actual behavior/output?
  I can't find anything to put at the '?' that would satifisfy mypy. `MyParent` is not enough, since it also needs `attr1`. `MyProtocol` is also not enough, since it needs to subclass `MyParent`. A union is the oppositive of what I want. I can't make `MyProtocol` a subclass, since "All bases of a protocol must be protocols".
* What is the behavior/output you expect?
  For there to be some way to combine these.
* What are the versions of mypy and Python you are using?
  python 3.6.9
  0.782
  0.790+dev.eae1860bef0a6fe06753459bf97633a41e789ed7
* What are the mypy flags you are using? (For example --strict-optional)
  `--strict`

**Comment by JelleZijlstra** [comment]
That sounds like you want an intersection type, which mypy currently does not support.
