### ISSUE TITLE
Not None checks ignored when passing to a lambda

### ISSUE THREAD

**Issue by ltworf** [python/mypy#9076]
```python3

from typing import *

def f(p: Optional[str]) -> Callable[[str], bool]:
    assert p
    if p is None:
        raise Exception('asd')
    return lambda a: p.startswith(a)
```

This doesn't pass, despite the 2 checks to make sure that `p` is indeed a string.

**Comment by ltworf** [comment]
It seems to work if instead of the lamda I use functools.partial

**Comment by kaste** [comment]
This is a dupe of https://github.com/python/mypy/issues/4297

**Comment by JelleZijlstra** [comment]
Closing as a duplicate.
