### ISSUE TITLE
Default non-optional function parameter is accepted with a default as None.

### ISSUE THREAD

**Issue by Jiehong** [python/mypy#9077]
Hi,

Mypy seems to not be bothered by `None` as a default function argument, even if that argument is not an `Optional`.

Here is an example:

```python
def type_check_me(index: int = None) -> str:
    return f"{index}"
```

Running mypy on this does not lead to any issue.

mypy version: 0.782

Expected:

I would expect mypy to tell me that `None` is not a valid default value for `index`, because it has type `int`.

Instead, the following code should be considered valid:

```python
from typing import Optional

def type_check_me(index: Optional[int] = None) -> str:
    return f"{index}"
```

**Comment by Jiehong** [comment]
Note: I tried with `--strict-optional` (even though it's the default now), with no difference.

**Comment by kaste** [comment]
I think you're looking for `--no-implicit-optional` https://mypy.readthedocs.io/en/stable/config_file.html#none-and-optional-handling

**Comment by JelleZijlstra** [comment]
Maybe we should flip the default on `--no-implicit-optional`?

**Comment by JukkaL** [comment]
> Maybe we should flip the default on --no-implicit-optional?

Yeah, I've been thinking about this. We might want to do it separately from other major breaking changes, such as the switch to a modular typeshed.

**Comment by JukkaL** [comment]
Closing in favor of #9091. Let's continue the discussion there.
