### ISSUE TITLE
Wrong message "arg-type" where "assignment" is expected

### ISSUE THREAD

**Issue by kaste** [python/mypy#9078]
Consider the following 

```
from typing import Generic, Iterator, TypeVar, Iterable
T = TypeVar("T")

class rewindable(Generic[T], Iterator[T]):
    def __init__(self, iterable: Iterable[T]) -> None: ...
    def __iter__(self) -> "rewindable[T]": ...
    def __next__(self) -> T: ...
    def rewind(self) -> None: ...


def ints() -> Iterator[int]:
    ...


a: rewindable[Iterator[int]]
b: rewindable[int]

a = rewindable(ints())  # err: Argument 1 to "rewindable" has incompatible type
                          "Iterator[int]"; expected "Iterable[Iterator[int]]"
b = rewindable(ints())

c: Iterable[str] = rewindable(ints())  # Argument 1 to "rewindable" has incompatible type
                                         "Iterator[int]"; expected "Iterable[str]"
```

Illustration

![image](https://user-images.githubusercontent.com/8558/86239061-e508af80-bb9e-11ea-8cc5-945ec68d2181.png)

`a` and `c` both have obviously an error.  But saying for `a` `Argument 1 to "rewindable" has incompatible type "Iterator[int]"; expected "Iterable[Iterator[int]]"` is completely backwards.  The call to "rewindable" is okay but the assignment to `a` fails.  

For simple cases like `c` it is maybe understandable but still too clever IMO.

**Comment by JukkaL** [comment]
This is a result of how mypy does type inference "from the outside in". It uses the assignment target to infer the type variable `T` of `rewindable`, and matches the argument against this. Perhaps a documentation improvements would be helpful? If so, feel free to open a separate issue about documenting this better.

**Comment by kaste** [comment]
Don't agree here, it's a good explanation of what's going on here, but the error message is not helpful, imo even misleading. 

"pyright" for example tells you for `a`

```
  20:5 - error: Expression of type "rewindable[int]" cannot be assigned to declared type "rewindable[Iterator[int]]"
  TypeVar "T" is invariant
    "__next__" is not present
    "__iter__" is not present
    "__iter__" is not present (reportGeneralTypeIssues)
```

for `c`

```
  23:20 - error: Expression of type "rewindable[int]" cannot be assigned to declared type "Iterable[str]"
  TypeVar "_T_co" is covariant
    "int" is incompatible with "str" (reportGeneralTypeIssues)
```

I'm not that happy that I posted the "rewindable" demonstration here, I actually had this issue here often enough, thinking  "Well, mypy that wasn't particular helpful <rolling eyes>".  I thought the example here would be telling but maybe it is distracting. 

So for the simple:

```
d: List[str] = list(ints())
mypy:
Argument 1 to "list" has incompatible type "Iterator[int]"; expected "Iterable[str]"

pyright:
Expression of type "list[int]" cannot be assigned to declared type "List[str]"
  TypeVar "_T" is invariant
    "int" is incompatible with "str" (reportGeneralTypeIssues)
```

Of course, in the real world the type of the variable is determined 50 lines elsewhere, and the function `ints` is actually complicated enough so you don't know what's going on just glimpsing.
