### ISSUE TITLE
Bug: Functional Enum API Unexpected arguments to Enum()

### ISSUE THREAD

**Issue by xylix** [python/mypy#9079]
I get error 
```
enum-repro.py:3: error: Unexpected arguments to Enum()
Found 1 error in 1 file (checked 1 source file)
```

When mypy checking for example 
```python
from enum import Enum

enum_name = Enum(
    value="enum_name",
    names={
        "a": 1,
        "b": 2
    }
)
print(enum_name)
```

I'm using mypy 0.782 and Python 3.8.3. Also tried latest master (0.790+dev.eae1860bef0a6fe06753459bf97633a41e789ed7)

Since this is valid python3 syntax, I would expect mypy to at least let it through, maybe with a warning about dynamic types being impossible to infer at static typecheck time.

For my actual use case, I could try using the class EnumName(Enum)): form but It doesn't fully support my use case, because I would like to use names containing spaces and special symbols.

**Comment by JelleZijlstra** [comment]
This should work if you use positional instead of keyword arguments. For example, the mypy test suite contains a `E = Enum('E', {'foo': 1, 'bar': 2})`. It wouldn't be hard to support keyword arguments (feel free to submit a PR!), but we just haven't taken the time to implement it.

**Comment by xylix** [comment]
Okay great, I understand that specifically not being implemented. The unnamed arguments will do as a workaround for now, solves my use case.

**Comment by LiuYuHui** [comment]
hi, @JukkaL @JelleZijlstra I want to fix this issue, could you please give some suggestions about where to start?

**Comment by JelleZijlstra** [comment]
@LiuYuHui you can add new test cases to the `check-enum.test` file. The implementation would probably go in the `parse_enum_call_args` method in `semanal_enum.py`.

**Comment by charnugagoo** [comment]
I am having the same issue.
