### ISSUE TITLE
"has no attribute" then suggests another missing attribute

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#9084]
Output in a mypy run:
```
vaults.py:14: error: Module 'datatypes' has no attribute 'VaultDataResponse'; maybe "VaultSummaryResponse"?  [attr-defined]
vaults.py:14: error: Module 'datatypes' has no attribute 'VaultSummaryResponse'; maybe "VaultDataResponse"?  [attr-defined]
```

Hopefully the error in the above output is self explanatory, it's contradicting itself.

**Comment by Dreamsorcerer** [comment]
Note that the attributes do exist, but I'm running with the `--no-implicit-reexport` option. So, it looks like the suggestions are generated without that option or something.

In this case, as the variable does exist, the suggestion should probably indicate something about implicit reexport, rather than another variable.

**Comment by JukkaL** [comment]
Yeah, this is a bug. Would you like to contribute a fix -- it should be pretty easy? You can look at the implementation of `--no-implicit-reexport` for context (#6562).

**Comment by Dreamsorcerer** [comment]
I can probably look at it in a few weeks.
