### ISSUE TITLE
no check for concrete types in dict literals

### ISSUE THREAD

**Issue by jkhsjdhjs** [python/mypy#9085]
mypy doesn't seem to check whether types in a dict literal are concrete. It does check this when assigning a type to a dict entry manually. List literals are checked as expected.

MWE:
```python
from abc import ABC, abstractmethod
from typing import Type, Dict, List

class Abstract(ABC):
    @abstractmethod
    def method(self):
        pass

# this doesn't print an error, but should, because Abstract is not a concrete type
DICT: Dict[int, Type[Abstract]] = {0: Abstract}

# error as expected
DICT[1] = Abstract

# error as expected, lists are not affected
LIST: List[Type[Abstract]] = [Abstract];
```
Tested with python 3.8.3 and mypy 0.782 / mypy [0.790+dev.eae1860bef0a6fe06753459bf97633a41e789ed7](https://github.com/python/mypy/tree/eae1860bef0a6fe06753459bf97633a41e789ed7) without any flags.

**Comment by JukkaL** [comment]
Yeah, this looks like a bug.

**Comment by erictraut** [comment]
This appears to have been fixed. The latest version of mypy emits errors in all three cases as expected.

**Comment by jkhsjdhjs** [comment]
Yep!
