### ISSUE TITLE
MYPYPATH results in reporting errors in stubs

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#9089]
I'm not sure if I'm doing something wrong, but when running mypy and it finds stubs outside of path it doesn't report any errors. But if I use MYPYPATH to override some stubs (e.g. to test fixes for upstream stubs), then I suddenly get a huge amount of errors in those stubs.

My expectation is that I don't get errors reported for code that is not part of my project, regardless of whether it is found through MYPYPATH, typeshed or something else.

**Comment by hauntsaninja** [comment]
This hasn't gotten much traction in the last three years. Changing behaviour too much here would be breaking for users who rely on mypy's import following to report errors.
