### ISSUE TITLE
Support variable type alias

### ISSUE THREAD

**Issue by adiroiban** [python/mypy#9093]
I have read the documentation at https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases

I am not sure how to annotate this. I was expecting that no annotation is required or at least to annotate it to `Type[Interface]`

I have the following code:

```python
import os
from typing import Type

class Interface:
    def test(self):
        pass

class TestLinux(Interface):
    def test(self):
        return 'linux'

class TestWindows(Interface):
    def test(self):
        return 'windows'

if os.name != 'nt':
    Test = TestLinux
else:
    Test = TestWindows


class TestUsage(Test):
    pass

```

I am expecting this to  work without any error

```bash
$ mypy type_alias.py 
type_alias.py:19:5: error: Cannot assign multiple types to name "Test" without an explicit "Type[...]" annotation  [misc]
type_alias.py:19:12: error: Incompatible types in assignment (expression has type "Type[TestWindows]", variable has type "Type[TestLinux]")  [assignment]
Found 2 errors in 1 file (checked 1 source file)

```

**Comment by glyph** [comment]
My workaround in situations like this right now would be something like:

```
if TYPE_CHECKING:
    Test = TestLinux
elif os.name != 'nt':
    Test = TestLinux
else:
    Test = TestWindows
```

If `TestLinux` and `TestWindows` aren't equivalent from the *type checker*'s perspective, than Mypy's job is impossible here; you can't statically check anything.

**Comment by hauntsaninja** [comment]
mypy should be able to do this with `sys.platform` checks (which it has special cased understanding of).

For checks that mypy doesn't have special casing of, this isn't really feasible, as glyph mentions.
