### ISSUE TITLE
Problem when using generics with callable and optional return

### ISSUE THREAD

**Issue by kiancross** [python/mypy#9109]
I have written the following function (a small example to demonstrate the issue):

```python3
from typing import List, Callable, Optional, TypeVar

T = TypeVar("T")

def foo(value: T, matcher: Callable[[T], bool]) -> Optional[T]:

    if matcher(value):
        return value

    return None

print(foo("foo", lambda x: x.endswith("oo")))
```

However when running with mypy I get the following error:

```none
$ mypy --strict test.py 
file.py:14: error: "object" has no attribute "endswith"
file.py:14: error: Returning Any from function declared to return "bool"
Found 2 errors in 1 file (checked 1 source file)
```

Alternatively, the following works:

```python3
from typing import List, Callable, Optional, TypeVar

T = TypeVar("T")

def foo(value: T, alternate: T, matcher: Callable[[T], bool]) -> T:

    if matcher(value):
        return value

    else:
        return alternate

    return None
```

So it seems to be something to do with the `Optional[T]` return type?

I am using mypy 0.782 and Python 3.8.2.

**Comment by JelleZijlstra** [comment]
I'm guessing what happens is that because `print()` takes an `object` as an argument, mypy infers that T is `object` and goes with that. Instead in this case it would be better to use `"foo"` to infer that `T` is `str`, but that might not generalize. There are a lot of issues about inference edge cases like this one.

**Comment by kiancross** [comment]
@JelleZijlstra Yep that looks like it was the problem - explains a lot of weird stuff that was going on in my project!!

Is this a bug, or would you like me to close the issue?

**Comment by hauntsaninja** [comment]
Basically the same as https://github.com/python/mypy/issues/8718 which has a suggestion from Jukka.

**Comment by kiancross** [comment]
@hauntsaninja Yeah looks the same - I'll close this one. Thanks for the help everyone.
