### ISSUE TITLE
Equation of a line is not displaying correct slope based on parameters.

### ISSUE THREAD

**Issue by BrittanyH1997** [python/mypy#9139]
Hello.

I am working on the intersection of two equations; one is a Hill function (sigmoid curve) and the other a basic straight line. For example, I have two variables x and a, where x is known (although dependent on parameters, seen commented out in the below picture) and I want to illustrate if the variable "line" either (1) does not intersect with the Hill function, (2) intersects only once with the Hill function, or (3) intersects three times with the Hill function (for stability analysis). When I conduct basic tests on my variable "line" (representing the straight line), such as omitting one half of the equation (where only -alpha*x remains) and tested for various values of alpha (randomized). But when alpha becomes negative, the line is given with a positive slope, and the same result happens when I complete the equation (all terms after -alpha*x). I am not sure why the basic equation of a line is not plotting correctly. Maybe it has something to do with how I am plotting them or using the append() functions, but I could really use some help.

Thank you.
![Screen Shot 2020-07-12 at 10 31 18 PM](https://user-images.githubusercontent.com/56805876/87266027-2c8e1600-c492-11ea-8e81-c9a1b8eb0fbf.png)

**Comment by JelleZijlstra** [comment]
This doesn't seem to be the right repo. Try reporting this issue to matplotlib.
