### ISSUE TITLE
Literal ellipsis and literal tuples

### ISSUE THREAD

**Issue by joshbode** [python/mypy#9140]
I'm trying to determine how to annotate ellipsis (`...`) and I'm getting an error that `...` is invalid for `typing.Literal` - is there a correct way to annotate a variable to indicate that it may contain ellipsis?

I also, out of curiosity, tried using a tuple as an element in `Literal` and got an unexpected result in that it appears the tuple is unpacked (e.g. `Literal[("a", "b")] == Literal["a", "b"]`) which may be correct, but surprised me :)

*Inputs*:
```python
# test.py
from typing import Literal

x: Literal["a", 1, None, True, False]
y: Literal[("a", "b")]
z: Literal["a", ...]

x = "a"
y = ("a", "b")
z = ...
```

*Output*:
```
$ mypy test.py
test.py:5: error: Parameter 2 of Literal[...] is invalid
test.py:8: error: Incompatible types in assignment (expression has type "Tuple[str, str]", variable has type "Union[Literal['a'], Literal['b']]")
Found 2 errors in 1 file (checked 1 source file)
```

*Versions*:
```
$ python --version
Python 3.8.3
$ mypy --version
mypy 0.782
```

**Comment by JelleZijlstra** [comment]
From looking at typeshed, you should be able to annotate Ellipsis as `ellipsis` (https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi#L1747). PEP 586 explicitly lists all types allowed as Literals (https://www.python.org/dev/peps/pep-0586/#legal-parameters-for-literal-at-type-check-time), and Ellipsis is not among them.

The tuple thing is because the AST is the same whether or not you put the parens in, so mypy can't (easily) distinguish between `Literal[1, 2]` and `Literal[(1, 2)]`.

**Comment by JukkaL** [comment]
There seems to be no further action required.

**Comment by BvB93** [comment]
> From looking at typeshed, you should be able to annotate Ellipsis as `ellipsis`

Based on, among others, https://github.com/python/mypy/issues/8240 there seems to be a desire to either make `ellipsis` private or get rid of it. 
With this in mind I'm concerned that annotation objects using `ellipsis` will cause issues in the (near?) future.

**Comment by gvanrossum** [comment]
> Based on, among others, #8240 there seems to be a desire to either make `ellipsis` private or get rid of it.
> With this in mind I'm concerned that annotation objects using `ellipsis` will cause issues in the (near?) future.

You should probably petition the CPython project to add that type to `types.py` in the stdlib, so it can be added to typeshed.

**Comment by BvB93** [comment]
> You should probably petition the CPython project to add that type to `types.py` in the stdlib, so it can be added to typeshed.

Yeah, that would be the most definitive solution; I just opened [bpo-41810](https://bugs.python.org/issue41810) for the (re-)introduction request.
