### ISSUE TITLE
"Too many arguments" for function called with curried/unpacked list

### ISSUE THREAD

**Issue by ReagentX** [python/mypy#9142]
Reproducible example:

```python
def test(a: int, b: int, c: int, d: int, e: int) -> int:
    return a + b + c + d + e

print(test(*[1, 2, 3, 4, 5]))
print(test(*[1, 2, 3, 4], 5))
```

`test(*[1, 2, 3, 4, 5])` passes mypy
`test(*[1, 2, 3, 4], 5)` does not

    ❯ mypy test.py
    test.py:5: error: Too many arguments for "test"
    Found 1 error in 1 file (checked 1 source file)
    ❯ mypy --version                                                 
    mypy 0.782

**Comment by hauntsaninja** [comment]
This is probably because mypy in general does not track the length of lists

**Comment by JukkaL** [comment]
Yeah, mypy conservatively assumes that the list could be too long. There's nothing we can easily do about this, other than perhaps recognizing a special case where all arguments have the same type. This seems too specialized to be very useful.
