### ISSUE TITLE
Don't allow for casting to Optional[type]

### ISSUE THREAD

**Issue by twolodzko** [python/mypy#9145]
I submitted a bug request to [PyRight repository](https://github.com/microsoft/pyright/issues/825) since it wasn't behaving consistently with mypy, but I learned from from the discussion that the inconsistency is by design. The difference between both type checkers is in regard to cases like

```pytnon
condition = cast(Optional[bool], condition)
```

PyRight flags this as incorrect, mypy allows for this. I'm posting this as a bug, but if that is not the case, I'd be happy to learn what _is_ correct in here? If casting to optional type is correct, this would be probably an opinionated argument for PyRight.

**Comment by JelleZijlstra** [comment]
This code should be allowed; `cast()` should allow any type.

**Comment by hauntsaninja** [comment]
I replied with some thoughts at https://github.com/microsoft/pyright/issues/825#issuecomment-658584901

I don't think I can read PEP 484 in a way that would imply this is a bug in mypy... I guess I can understand the reading of the semantics of `Type[T]` (even though I wouldn't read it that way), but the language about `cast`-ing in PEP 484 is very clear about the intended behaviour. So if pyright chooses to define slightly different semantics for `Type` than the one used by mypy (and in typeshed's definition of `cast`), it seems to me they should special-case `cast`.
