### ISSUE TITLE
Not able to install typing in python 3.6

### ISSUE THREAD

**Issue by amrit3327** [python/mypy#9146]
Note: if you are reporting a wrong signature of a function or a class in
the standard library, then the typeshed tracker is better suited
for this report: https://github.com/python/typeshed/issues

Please provide more information to help us understand the issue:

* Bug
Notice: /Stage[main]/Airflow::Pip/Exec[resolving pip dependencies]/returns:   Downloading http://pypi.us-east-1.aws.cloud.viacom.com/root/pypi/+f/6f6/f3553709d2234/typing-3.7.4.2.tar.gz (78kB)
Notice: /Stage[main]/Airflow::Pip/Exec[resolving pip dependencies]/returns:     Complete output from command python setup.py egg_info:
Notice: /Stage[main]/Airflow::Pip/Exec[resolving pip dependencies]/returns:     ERROR: You need Python 2.7 or 3.4 to install the typing package

I am trying to install air flow using pip3.6 install APACHE-AIRFLOW[CELERY,HIVE,POSTGRESS,MYSQL,JDBC,SSH,S3] and typing is one of the dependencies. 2 days back it was working but not its failing when trying to install typing.

**Comment by JukkaL** [comment]
`typing` in the standard library in Python 3.5 and later, so you shouldn't install it using pip.
