### ISSUE TITLE
mypy cannot find font module in tkinter

### ISSUE THREAD

**Issue by mfncooper** [python/mypy#9157]
When using fonts in a tkinter application, mypy does not find the font module.

* Are you reporting a bug, or opening a feature request?
Bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
Simplified test case:
```python
import tkinter as tk
from tkinter import ttk
from tkinter import font as tkFont

root = tk.Tk()
appHighlightFont = tkFont.Font(family='Helvetica', size=16, weight='bold')
ttk.Label(root, text='Attention!', font=appHighlightFont).grid()
root.mainloop()
```

* What is the actual behavior/output?
> $ mypy tktest.py
> tktest.py:3: error: Module 'tkinter' has no attribute 'font'
> Found 1 error in 1 file (checked 1 source file)

* What is the behavior/output you expect?
No error. This is valid, working tkinter code.
* What are the versions of mypy and Python you are using?
> $ python3 --version
> Python 3.7.0
> $ mypy --version
> mypy 0.782

**Comment by Akuli** [comment]
I'm currently working on a pull request that will add `tkinter.font` module (some conversation on https://github.com/python/typeshed/issues/1631).

This is actually a typeshed issue, and not a mypy issue.

**Comment by Akuli** [comment]
I guess I should mention that you don't need a font object for specifying the font of a label, and you can instead use a `(family, size, bold_and_stuff)` tuple:

```
ttk.Label(root, text='Attention!', font=('Helvetica', 16, 'bold')).grid()
```

**Comment by mfncooper** [comment]
> I guess I should mention that you don't need a font object for specifying the font of a label

Yeah, I know. I was just trying to provide a "minimal repro", as requested. My actual use case is quite different, but boils down to the same issue.

Thanks for the link to the typeshed issue.

**Comment by Akuli** [comment]
pull request is ready for review (but turned out to not be related to the discussion I linked earlier)

mypy will behave correctly once pull request has been merged and new release of mypy (with new typeshed) comes out. If you want to try the new tkinter.font stubs now:

```
git clone https://github.com/Akuli/typeshed akuli-typeshed
mypy --custom-typeshed-dir=akuli-typeshed mycode.py
```

**Comment by mfncooper** [comment]
I tried your fork/branch, and it works just fine. Thanks!

**Comment by Akuli** [comment]
pull request was merged, this issue can be closed imo because mypy will start working once a new version of mypy (with new typeshed) is released
