### ISSUE TITLE
Providing additional stubs in stubtest.py

### ISSUE THREAD

**Issue by pikachu** [python/mypy#9161]
Currently, with `stubtest.py`, we are allowed to pass in a custom typeshed with `--custom-typeshed-dir`. I have a case where I have custom stubs in standalone (not in a typeshed) `myproject/stubs/`. We add `myproject/stubs/` to the `mypy_path` before running mypy to make sure it picks up those stubs during static typechecking. 

In `stubtest.py`, the modules are [grabbed](https://github.com/python/mypy/blob/master/mypy/stubtest.py#L977) in `get_typeshed_stdlib_modules`. There is currently not a way for me to add additional stubs that live outside of the typeshed (in my `mypy_path`, for example). 

Is there a way to reference other stubs (or all stubs in the `mypy_path`) or is this a potential feature request?

Please let me know if you need any more information! Thanks in advance.

**Comment by hauntsaninja** [comment]
IIRC stubtest will find stubs that are on your mypy path, but you'll need to invoke stubtest with the names of the stubs you wish to test. That is, `stubtest my_custom_stub` should work, if you have stubs for `my_custom_stub` on your mypy path.

Note the function you linked to is only called when running stubtest with the `--check-typeshed` flag. If you wanted that flag to find and check all the stubs mypy could in theory find, that would be a feature request (and we'd probably need to rename the flag).

**Comment by pikachu** [comment]
@hauntsaninja thanks for responding - I set my mypy properly and stubtest is able to find all of those stubs. 

However, I am a little confused by your suggestion to run `stubtest my_custom_stub <and other stubs>`. Aren't we trying to run `stubtest module_1 <other modules` to see if all the types match up with stubs at runtime? The stubs should be discoverable on the path.

**Comment by hauntsaninja** [comment]
Yes, sorry. You're passing in module names to stubtest. I see how the example module name I chose is confusing :-)

**Comment by pikachu** [comment]
Thanks for your help!
