### ISSUE TITLE
Create package for mypy encoding

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#919]
Add package `mypy-encoding` with a separate setup script that installs the mypy encoding. It should be installable using both Python 2 and Python 3.

This is based on the original issue from here: https://github.com/JukkaL/mypy/issues/917

**Comment by chadrik** [comment]
I would love to see this completed.  What is involved beyond creating a setup.py for the new package?  Just wondering if it's straight-forward enough that I might be able to create a pull request for this.

**Comment by gvanrossum** [comment]
Actually the mypy codec has long been deprecated. We should probably delete the code. Python 2 code should use the Python 2 type comments described in the docs. http://mypy.readthedocs.io/en/latest/python2.html

Maybe we should just close all codec-related issues and instead add an issue "Rip out codec"?

**Comment by JukkaL** [comment]
Sounds reasonable -- as the codec is unneeded, undocumented and unmaintained, keeping the code around isn't very useful.
