### ISSUE TITLE
unreachable code after suppress()

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#9199]
Mypy reports this as unreachable code on the last line:

```
with suppress(KeyError):
    return _get_session()[name]

weights = AB_TESTS.get(name)
```

If the indexing causes a KeyError, this code will be reached. `_get_session()` is `Any`, but I also tried casting it to a `Dict`. So, it looks like Mypy assumes this will always succeed, despite us explicitly catching the error.

**Comment by ilevkivskyi** [comment]
IIRC there is a way to tell mypy that a context manager can swallow an exception by annotating its `__exit__()` method in a special way, so this may be fixed by updating `suppress.__exit__()` annotation in typeshed. I however don't remember details on this.

**Comment by Dreamsorcerer** [comment]
It appears that's already been done (by return `bool`): https://github.com/python/typeshed/pull/3179/files

I think the problem is that Mypy fails to recognise that _if_ an exception is thrown then the `return` won't be executed, and therefore there are 2 branches of code here.

**Comment by Dreamsorcerer** [comment]
Actually, it looks like the exact same issue that introduced this: https://github.com/python/mypy/issues/7214
So, unsure why this isn't working.

**Comment by gvanrossum** [comment]
Perhaps you have some configuration flag that affects this? And (just to be sure) what mypy version are you using? I can't repro your issue, but it looks like you didn't show all the code of a self-contained example.

**Comment by Dreamsorcerer** [comment]
Hmm, running it again, the error has now disappeared...
I'll close this unless I see it return again.
