### ISSUE TITLE
Protocol-typed arguments to callback Protocols fail.

### ISSUE THREAD

**Issue by A5rocks** [python/mypy#9205]
* Are you reporting a bug, or opening a feature request?

This is a bug.

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```py
import typing


class BlahProto(typing.Protocol):
	bleh: str


class CallbackProto(typing.Protocol):
	def __call__(self, __arg: BlahProto) -> None:
		...


class NeedsCB:
	cb: CallbackProto

	def __init__(self, cb: CallbackProto) -> None:
		self.cb = cb


class Blah:
	bleh: str


def blah_cb(arg: Blah) -> None:
	...


NeedsCB(blah_cb)
```

* What is the actual behavior/output?

```
main.py:24: error: Argument 1 to "NeedsCB" has incompatible type "Callable[[Blah], None]"; expected "CallbackProto"
Found 1 error in 1 file (checked 1 source file)
```
* What is the behavior/output you expect?

Nothing should be an error.

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

`Python 3.8.2` & `mypy 0.782`
And yes, the problems remain for mypy from Git master.

* What are the mypy flags you are using? (For example --strict-optional)

`--strict` (though `mypy .` also has this problem)

I suspect `mypy` is seeing `BlahProto` as a literal class to typecheck against instead of as the Protocol it is, though the error messages don't help much :^).

**Comment by JelleZijlstra** [comment]
This is a variance issue, and mypy flagged this code correctly. The problem is that `blah_cb` *only* accepts `Blah` objects, but `CallbackProto` requires that it accepts any object that fulfills `BlahProto`.

**Comment by A5rocks** [comment]
Oh I see, oops...
