### ISSUE TITLE
Cannot pass List[List[int]] where a List[Optional[List[int]]] is expected.

### ISSUE THREAD

**Issue by fabioz** [python/mypy#9210]
The example below gives an error saying that a `List[List[int]]` can't be passed to a function where a `List[Optional[List[int]]]` is expected. 

I believe that an optional should accept a non-optional version of that item (even if it's a list variable), so, this seems like a bug to me.

```
from typing import List, Optional

def some_call(a: List[Optional[List[int]]]):
    pass

def method() -> None:
    a: List[List[int]] = []
    b: List[Optional[List[int]]] = []

    some_call(a)  # Argument 1 to "some_call" has incompatible type "List[List[int]]"; expected "List[Optional[List[int]]]"
    some_call(b)
```

Note that the example below works, so, this is specific to the `List` typing.

```
from typing import List, Optional

def some_call(a: Optional[List[int]]):
    pass

def method() -> None:
    a: List[int] = []
    b: Optional[List[int]] = []

    some_call(a)
    some_call(b)
```

**Comment by Akuli** [comment]
This is by design. If `List[Optional[List[int]]]` was a valid argument for a function expecting `List[List[int]]`, then what should this do?

```python
from typing import List, Optional

def some_call(a: List[Optional[List[int]]]):
    a.append(None)

foo: List[List[int]] = [[1, 2, 3], [4, 5, 6]]
some_call(foo)
print(foo)
```

The error message has a link to mypy docs that try to explain this problem. The error message also suggests using `Sequence` instead of `List`, and in this case, the outer `List` should be replaced with `Sequence`:

```
def some_call(a: Sequence[Optional[List[int]]]):
    ...
```

**Comment by JelleZijlstra** [comment]
As @akuli said, and see https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance.

Usually the best solution for this sort of thing is to use a covariant, immutable type, like Sequence or Iterable.

**Comment by fabioz** [comment]
Got it. Thanks for the explanation (sorry for the noise).
