### ISSUE TITLE
Unsure about behaviour with type checking in muli-type variables

### ISSUE THREAD

**Issue by egeres** [python/mypy#9212]
The following code exemplifies the problem:

```
from typing import List, Union

a : List[Union[str, int]] = [0, 1, 2, "b"]

for i in a:
    if type(i) is str:
        print (i.endswith("b"))
```

The variable **i** that is used in the loop is correctly identified as type **Union[str, int]**. However, I believe mypy should also determine that after the if statement, the type of **i** could only be a **str**.

Since this issue might not ever be solved or implemented. Is there a way to define the type of a variable after it has been declared ? I haven't found any information regarding this option 🤔.

Thanks in advance !

**Comment by JelleZijlstra** [comment]
You should use `isinstance(i, str)`, which works today. There is probably an existing issue asking for support for type narrowing through `type(...) is str` but I can't find it.

**Comment by egeres** [comment]
It works ! Than you so much !
