### ISSUE TITLE
sys.version_info check does not recognize patch version

### ISSUE THREAD

**Issue by rhysd** [python/mypy#9216]
* Are you reporting a bug, or opening a feature request?: bug

### Versions

- Python: 3.7.7
- mypy: 0.782

### Repro:

```python
import sys
if sys.version_info >= (3, 6, 2):
    from typing import NoReturn
else:
    NoReturn = 'NoReturn'
```

Write above code to file `foo.py` and run `mypy foo.py`

### Expected behavior

- With Python `>= 3.6.2`, `NoReturn` is imported from `typing` module
- With Python `< 3.6.2`, `NoReturn` is literal `'NoReturn'`

without type error

### Actual behavior

Type error:

```
error: Cannot assign multiple types to name "NoReturn" without an explicit "Type[...]" annotation
```

### Description

As described in [documentation](https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks), mypy recognizes two elements tuple like `sys.version_info >= (3, 6)` but it doesn't three elements tuple `sys.version_info >= (3, 6, 2)` which includes patch version.

Patch version check is necessary because `NoReturn` is available in Python 3.6.2 and later but not available in 3.6.0 and 3.6.1.

I'm not sure, but modifying this line

https://github.com/python/mypy/blob/23dba19098857a72e0ad2284b164e2fceaee44ac/mypy/reachability.py#L146

to

```python
if 0 <= lo < hi <= 3:
```

would solve this issue.

**Comment by JelleZijlstra** [comment]
Your proposed fix wouldn't help because mypy relies on typeshed, and typeshed doesn't separate stubs by patch version.

The easiest solution for you code might be to use `from typing_extensions import NoReturn`, which works on any Python version (but requires installing `typing_extensions`).

**Comment by Akuli** [comment]
alternatively, if you don't want to use `typing_extensions` on python versions that don't need it:

```
import sys
if sys.version_info >= (3, 6, 2):
    from typing import NoReturn
else:
    from typing_extensions import NoReturn
```

**Comment by JukkaL** [comment]
Closing since a mypy fix doesn't seem feasible, and there is a workaround.
