### ISSUE TITLE
Can't annotate property in ABC class.

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#9217]
I'm getting this error: `Definition of "total_views" in base class "SourceCounts" is incompatible with definition in base class "OACountsBase"`

Based on code that looks like this:
```
@attr.s
class SourceCounts:
    @property
    def total_views(self) -> int:
        ...

@attr.s
class OACountsBase(ABC):
    total_views: int

@attr.s
class AllDataCounts(SourceCounts, OACountsBase):
    pass
```

It seems that the property is not being recognised as compatible with int (which may be correct, as assignment will fail), but there is no indication as to what type it thinks it is, or how I might annotate it correctly. `reveal_type()` is not really helping either, I can't see how to type this correctly.

**Comment by JelleZijlstra** [comment]
This is because it's settable in the ABC but not in the concrete class. You should define it as a property in the ABC too, so that it's clear to mypy that it's read-only. This should perhaps be added to https://mypy.readthedocs.io/en/stable/common_issues.html.
