### ISSUE TITLE
Fails to infer keyword arguments for a hard-coded dictionary.

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#9218]
```
    extra_args = {"stdout": subprocess.DEVNULL, "stderr": subprocess.DEVNULL} if suppress else {}
    subprocess.run(
        (...),
        check=True,
        **extra_args,
    )
```

Output: `No overload variant of "run" matches argument types "Tuple[...]", "bool", "Dict[str, int]"`

Seems like Mypy should be able to infer the arguments for the hard-coded dict.

It works correctly, if I annotate the variable with a TypedDict:
```
class _SubprocessArgs(TypedDict, total=False):
    stdout: int
    stderr: int
```

I wonder if a possible solution would be to infer the type as a kind of soft TypedDict, where Mypy tracks it as a TypedDict, but if some code modifies it in a way that Mypy can no longer know the type, it will fallback to a Dict.

So, it might infer something along these lines:
```
extra_args = {"foo": 4}  # SoftTypedDict[foo: int]
extra_args["bar"] = "abc"  # SoftTypedDict[foo: int, bar: str]
extra_args.pop(input())  # Dict[str, object]
```

**Comment by JukkaL** [comment]
Annotating with a TypedDict is the recommended way to deal with this. 

> I wonder if a possible solution would be to infer the type as a kind of soft TypedDict, where Mypy tracks it as a TypedDict, but if some code modifies it in a way that Mypy can no longer know the type, it will fallback to a Dict.

This would be a fairly complex feature to support, and it would only work in fairly narrow circumstances, so we are unlikely to support this. We've thought about supporting use cases like this, but the complexity doesn't seem worth it in the end (also explicit is better than implicit to avoid surprises).
