### ISSUE TITLE
Incomplete or inconsistent Literal and Union behavior on conditional checks

### ISSUE THREAD

**Issue by kprzybyla** [python/mypy#9220]
Used mypy version: `0.782`

I stumbled upon some incomplete behavior related to `Literal` and `Union`. In most cases `Union` is not properly expanded upon conditional check when dealing with literals. Below example should describe clearly the situation.

```python
from typing import Union
from typing_extensions import Literal

class A:
    def __bool__(self) -> Literal[True]:
        return True

    @property
    def is_ok(self) -> Literal[True]:
        return True

    def ok(self) -> Literal[True]:
        return True

class B:
    def __bool__(self) -> Literal[False]:
        return False

    @property
    def is_ok(self) -> Literal[False]:
        return False

    def ok(self) -> Literal[False]:
        return False


def get_a_or_b() -> Union[A, B]: ...

thing = get_a_or_b()

if thing:
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'
else:
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'

if bool(thing):
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'
else:
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'

if thing.is_ok:
    reveal_type(thing)  # Revealed type is 'main.A'
else:
    reveal_type(thing)  # Revealed type is 'main.B'

if thing.ok():
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'
else:
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'
```

I would expect that all examples will give the same result as the one with `is_ok` property. Maybe the `bool()` example would require some additional thought but it would seem wise to make it also work. Also, walrus operator makes it so that even the `is_ok` property example does not work. Other examples behave the same as before:

```python
if thing := get_a_or_b():
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'
else:
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'

if bool(thing := get_a_or_b()):
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'
else:
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'

if (thing := get_a_or_b()).is_ok:
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'
else:
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'

if (thing := get_a_or_b()).ok():
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'
else:
    reveal_type(thing)  # Revealed type is 'Union[main.A, main.B]'
```

**Comment by Akuli** [comment]
i discovered similar `:=` operator problems in #9229

**Comment by JukkaL** [comment]
Yeah, the behavior seems inconsistent. I'm not sure about the `bool()` case, though.

**Comment by kprzybyla** [comment]
I opened PR https://github.com/python/mypy/pull/9288 that at least fixes the walrus operator usage for the property case. I would be grateful for any kind of feedback :)
I will try to also work on the rest of examples but it will probably take some time since I'm not that much familiar with the code base. And the rest of cases seems like a bit of work.

The `bool()` case is not so obvious so this probably would need to be discussed a bit more. I will probably try to fix the other examples first and then it can be decided whether it is reasonable to handle this `bool()` case.
