### ISSUE TITLE
Strange Index error on string formatting

### ISSUE THREAD

**Issue by staticdev** [python/mypy#9221]
* Are you reporting a bug, or opening a feature request? Bug.
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
import github # PyGithub
g = github.Github("access_token")
github_repo = "staticdev/git-portfolio"
repo = g.get_repo(github_repo)
try:
    created_pr = repo.create_pull(
        title="title", body="body", head="head", base="base", draft=False,
    )
except github.GithubException as github_exception:
    extra = ""
    for error in github_exception.data["errors"]:
        if "message" in error:
            extra += f"{error['message']} "
        else:
            extra += f"Invalid field {error['field']}. "
```

* What is the actual behavior/output?
```
src/git_portfolio/mypy.py:13:31: error: Invalid index type "str" for "Union[str, Dict[str, str]]"; expected type "Union[int, slice]"  [index]
                extra += f"{error['message']} "
                                  ^
src/git_portfolio/mypy.py:15:45: error: Invalid index type "str" for "Union[str, Dict[str, str]]"; expected type "Union[int, slice]"  [index]
                extra += f"Invalid field {error['field']}. "
                                                ^
```
* What is the behavior/output you expect?
I expected no error, since I did not declare any type for f-strings, and these are strings.

* What are the versions of mypy and Python you are using?
mypy v0.782 python 3.8.2

  Do you see the same issue after installing mypy from Git master?
yes

* What are the mypy flags you are using? (For example --strict-optional)
None.

**Comment by JelleZijlstra** [comment]
I haven't checked, but are you sure the f-strings are important here? This sounds to me like `error` is just of type `Union[str, Dict[str, str]]`, and you'd get the same complaints from mypy whenever you try to index `error` with a string.

The error message is a bit weird though, since using an `int` or `slice` wouldn't work on the `Dict` part of the union either.

**Comment by staticdev** [comment]
@JelleZijlstra no, I am not sure about the relevance of f-strings here I will try other test. I never came to these Index errors on mypy before. And also this error cames from PyGithub [GithubException](https://github.com/PyGithub/PyGithub/blob/6eba4506d4d44892c5e224054b809003fc3326f6/github/GithubException.pyi) data field:

```
class GithubException(Exception):
    @property
    def data(self) -> Dict[str, Union[str, List[str], List[Dict[str, str]]]]: ...
```

**Comment by Akuli** [comment]
`string[bla]` requires `bla` to be `int` or `slice`, as in `"hello"[0]` or `"hello"[:3]` (which is same as `"hello"[slice(None, 3, None)]`)

possible workaround:

```
errors = cast(List[Dict[str, str]], github_exception.data["errors"])
for error in errors:
    ...
```

ideally `GithubException.pyi` would use a TypedDict (non-total if necessary)

**Comment by Akuli** [comment]
maybe this issue should be closed and you should instead make an issue to https://github.com/PyGithub/PyGithub ?

**Comment by staticdev** [comment]
@Akuli so your recommendation is create an issue asking them to use TypedDict?

**Comment by Akuli** [comment]
yes, either ask them to use TypedDict or write documentation about how to access `github_exception.data["errors"]`

**Comment by staticdev** [comment]
Done @Akuli, closing this one. Thanks.
