### ISSUE TITLE
Possible regression in support for future.utils.with_metaclass

### ISSUE THREAD

**Issue by valmar** [python/mypy#9222]
I would like to report a suspected regression in support for future.utils.with_metaclass in mypy version: 0.782

According to this:

https://github.com/python/mypy/issues/7193

I think mypy should support future.utils.with_metaclass. However the following code (inspired by the unittests):

```
import future.utils
class M(type):
    x = 5
class A(future.utils.with_metaclass(M)): pass
```

Gives me the error (with mypy --strict): 

```
test.py:4: error: Unsupported dynamic base class "future.utils.with_metaclass"
```

Instead the following code, which uses six, gives no such error:

```
import six
class M(type):
    x = 5
class A(six.with_metaclass(M)): pass
```

**Comment by JukkaL** [comment]
You need to install stubs for `future` for this to work, I suspect. Mypy doesn't ship with the necessary stubs.

**Comment by valmar** [comment]
@JukkaL I am sorry for the delay, I was busy moving.

Sorry, but are you sure about having to install the stubs?
This commit, in the master branch seems to imply that support was added directly in mypy:

https://github.com/python/mypy/commit/d60724543a1df90f4e1c50fd6ba1bf04bf17ba6e

And indeed, looking at these lines, it seems that it should be supported:

https://github.com/python/mypy/blob/v0.782/mypy/semanal.py#L1538

**Comment by JukkaL** [comment]
Mypy has some special casing for `future`, but mypy doesn't ship with `future` stubs, and the special casing only works if mypy can find type information for `future`.
