### ISSUE TITLE
Make intersections part of the plugin API

### ISSUE THREAD

**Issue by mthuurne** [python/mypy#9231]
This is a feature request.

We have no syntax yet to annotate type intersections, see python/typing#213. Perhaps a good intermediate step would be to make mypy's `TypeChecker.intersect_instances()` available to plugins.

This would be useful for plugins that determine that a particular value conforms to multiple interfaces, without knowing its exact type or with the exact type only existing at runtime (dynamically created class).

I'm using `cast(mypy.checker.TypeChecker, method_ctx.api)` as a workaround, but of course using mypy's internal API from a plugin is a fragile construct and I'd prefer to use only the official plugin API instead.

**Comment by JukkaL** [comment]
`intersect_instances` is a pretty hacky thing, and I'm not sure if we want to bless it as part of the public API.

**Comment by mthuurne** [comment]
It would be nice to have some way to handle type intersections. If it's done in a different way than `intersect_instances()`, that would be fine too.

**Comment by JukkaL** [comment]
Unfortunately proper support for intersection types would be a major undertaking. The hacky support only convers a very narrow but somewhat common use case and it's not easy to generalize it.
