### ISSUE TITLE
ENH: Add wheels for arm64

### ISSUE THREAD

**Issue by mattip** [python/mypy#9233]
Over at NumPy, we added type checking tests and run them with mypy. We noticed a significant slowdown on arm64 CI. xref numpy/numpy#16980. It seems there are no arm64 builds of mypyc. It would be nice if they existed. Where are the wheels actually built?

**Comment by JukkaL** [comment]
The wheels are built in https://github.com/mypyc/mypy_mypyc-wheels.

`mypy/misc/download-mypyc-wheels.py` would also need to be updated for the wheels to be included in a release.

**Comment by hauntsaninja** [comment]
Duplicate of https://github.com/python/mypy/issues/9688
