### ISSUE TITLE
Inheritance from nested class doesn't always work

### ISSUE THREAD

**Issue by evhub** [python/mypy#9239]
I can't tell if this is the same issue as my previous issue #9238 or not, so I'm raising it separately.

On MyPy 0.780, the code

```python
class B:
    pass

class A:
    B = B

class C(A.B):
    pass
```

raises

```
test.py:7: error: Variable "test.A.B" is not valid as a type
test.py:7: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
test.py:7: error: Invalid base class "A.B"
Found 2 errors in 1 file (checked 1 source file)
```

despite the equivalent code

```python
class A:
    class B:
        pass

class C(A.B):
    pass
```

working fine.

**Comment by ilevkivskyi** [comment]
This works as intended. See my comment in #9238

**Comment by evhub** [comment]
@ilevkivskyi Is there any way to annotate the above code that would work (aside from `type: ignore`)? I'd like to be able to properly type-check that code.

**Comment by ilevkivskyi** [comment]
Something that _may_ work is `B = Union[B]`.
