### ISSUE TITLE
mypy doesn't understand callable package

### ISSUE THREAD

**Issue by karmux** [python/mypy#9240]
mypy gives "Module not callable" error about callable package. Below I have provided a minimal reproducible example.

`mypkg/__init__.py`
```
import sys


class MyPkg(sys.modules[__name__].__class__):  # type: ignore

    def __call__(self) -> int:
        return 1


sys.modules[__name__].__class__ = MyPkg
```

`main.py`
```
import mypkg

print(mypkg())
```

`$ python main.py`
```
1
```

`$ mypy .`
```
main.py:3: error: Module not callable
Found 1 error in 1 file (checked 2 source files)
```

Python 3.8.3
mypy==0.782

How to make mypy understand that it is a callable package? Writing `# type: ignore` in the main.py (and in every other place in the application code) makes this short callable package syntax quite useless.

**Comment by hauntsaninja** [comment]
This is probably too dynamic for mypy to understand, so I'm inclined to close as won't fix. Here's a workaround that will help mypy out and preserve type safety:

```
import mypkg as _mypkg
mypkg: _mypkg.MyPkg = _mypkg  # type: ignore

print(mypkg())
reveal_type(mypkg())
```
It's still a little bit of boilerplate, but you only have to do it once for each file where mypkg is used.

**Comment by JukkaL** [comment]
Yeah, this seems too dynamic so I'm closing this issue. A workaround will be required.
