### ISSUE TITLE
Question: When to use Alias over NewType?

### ISSUE THREAD

**Issue by Integralist** [python/mypy#9255]
Apologies if this is the wrong forum to ask this question, but I'm confused by when i would want to use `NewType()` over an alias?

The examples in the documentation feel contrived, and any example I think up is generally contrived too so it's hard to reason about when it would be useful.

Any help distinguishing a good use case for choosing one over the other would be appreciated.

Many thanks!

**Comment by Akuli** [comment]
Following the example from [typing docs](https://docs.python.org/3/library/typing.html#newtype), `NewType('UserId', int)` is useful if you want to avoid accidentally passing an `int` to something that expects a `UserId`. That's all it does, but it comes with some nice benefits.

For example, let's say that your program has a bug where it treats some unrelated `int` as a UserId. If the program uses an alias like `UserId = int`, then mypy can't help you much with finding that bug. But if the code uses `UserId = NewType('UserId', int)` instead, then the bug must be one of the places that do `UserId(blah)`, and it's enough to search for something like `UserId(` in the code.

**Comment by gvanrossum** [comment]
After this:
```
A = int
B = int
```
the types A and B are completely equivalent. For example:
```
def f(a: A) -> B:
    return a  # Okay
def g(b: B) -> A:
    return b  # Okay
def h(i: int) -> A:
    return i  # Okay
```

But if instead we had this:
```
A = NewType('A', int)
B = NewType('B', int)
```
all of the above would fail, and only this function would work:
```
def foo(a: A) -> int:
    return a
```
IOW `NewType` creates a type that is a *strict subtype* of its argument; a type alias creates a type that is *equivalent* to the RHS.

Also, `NewType` only takes class arguments, while a type alias can use anything for its RHS. If there is a free type variable in the RHS, the alias is generic.
```
A = List
a: A[int]  # same as a: List[int]
b: A  # BEWARE! same as b: List[Any]
```
 `NewType` does not work with generics.
```
A = NewType('A', List)
a: A[int]  # Error: "A" expects no type arguments, but 1 given
```

**Comment by Integralist** [comment]
Thank you.
