### ISSUE TITLE
union of tuples doesn't work

### ISSUE THREAD

**Issue by Akuli** [python/mypy#9262]
I can't figure out how to use a value that has this type:

```
_ThingsToAdd = Union[
    Tuple[int, int],
    Tuple[str, str],
]
```

This doesn't work

```
def add(pair: _ThingsToAdd) -> None:
    print(pair[0] + pair[1])    # errors about int+str and str+int
```

This doesn't work either:

```
pairs: List[_ThingsToAdd] = [(12, 34), ('ab', 'cd')]
for a, b in pairs:
    print(a + b)    # errors about int+str and str+int
```

* bug
* mypy errors about int+str and str+int even though that never happens
* expecting no errors
* mypy 0.790 (from git master), python 3.8
* no mypy flags

**Comment by reidswan** [comment]
Playground link reproducing the issue [here](https://mypy-play.net/?mypy=latest&python=3.8&gist=36e6d95a350e959e747bf61198bc5bee).

I'm new to the mypy codebase, but from what I can gather, in [`visit_index_with_type`](https://github.com/python/mypy/blob/master/mypy/checkexpr.py#L2865) the type checker sees that the tuple is being literal indexed, so it reduces from `Union[Tuple[int, int], Tuple[str, str]]` to `Union[int, str]` (i.e., it takes the type at the corresponding index). Then it tries to add a `Union[int, str]` to a `Union[int. str]` and fails. 

Once again, I'm new to mypy, so a maintainer or more experienced contributor would need to verify. Here's  [another playground](https://mypy-play.net/?mypy=latest&python=3.8) which does the same thing using `functools.reduce` (i.e. no indexing) which type checks without issue

**Comment by reidswan** [comment]
Okay, I'm _fairly_ certain my investigation is correct, because we can get a successful typecheck by inserting a `return left_type` above [this line](https://github.com/python/mypy/blob/master/mypy/checkexpr.py#L2867) (skipping the simplification).

**Comment by JukkaL** [comment]
Yeah, this is a false positive, but it's too difficult for mypy to figure out that this is safe. For this use case you'll need to either rewrite your code or use `# type: ignore`.

**Comment by Akuli** [comment]
Nevermind, I can make the `add` function work by adding an if statement with the same stuff copy/pasted to `if` and `else`:

```python3
def add(pair: _ThingsToAdd) -> None:
    if isinstance(pair[0], int):
        print(pair[0] + pair[1])
    else:
        print(pair[0] + pair[1])
```

The for loop works if it uses a function that works instead of doing the addition without a function:

```python3
pairs: List[_ThingsToAdd] = [(12, 34), ('ab', 'cd')]
for pair in pairs:
    add(pair)
```

**Comment by hauntsaninja** [comment]
You might also have luck changing to `_ThingsToAdd = Tuple[T, T]` (and if you wanted to be thorough, bounding the type var)
