### ISSUE TITLE
"raise from" type checking is broken if multiple except blocks

### ISSUE THREAD

**Issue by aviau** [python/mypy#9270]
This should not pass type checking:

```python

def test() -> None:
    try:
        raise Exception()
    except NotImplementedError as e:
        raise Exception("notimplemented") from e
    except Exception:
        raise Exception("test") from e

test()
```

``e`` does not exist on the second ``except`` block, so we cannot raise from it:
```
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by gvanrossum** [comment]
Oh, pretty subtle. I’m not even sure mypy has the internal data structures to keep track of this. Does it give you an error if you use a local variable after deleting it with ‘del’?

**Comment by aviau** [comment]
Yes.

code:
```python
def test() -> None:
    a = "aa"
    del a
    print(a)

test()
```
mypy output:
````
test.py:4: error: Trying to read deleted variable 'a'
````

**Comment by isra17** [comment]
Note that this check successfully:

```
def test() -> None:
    a = "aa"
    del a
    raise Exception from a
test()
```

and 

```
def test() -> None:
    try:
        pass
    except NotImplementedError as e:
        pass
    except Exception:
        reveal_type(e)

test()
```

Does reveal `e` being deleted. So this might be due to `raise from` not checking if the source value is deleted?

**Comment by gvanrossum** [comment]
Oh, very interesting. Does the source for raise-from checking reveal anything interesting? For that matter, is the from clause type checked at all?

**Comment by aviau** [comment]
> is the from clause type checked at all?

I think yes.

The following code raises a mypy error:
```python
def test() -> None:
    try:
        raise Exception("test")
    except Exception as e:
        raise Exception("test2") from some_other_variable
````

```
test.py:5: error: Name 'some_other_variable' is not defined
```

Support this was apparently tracked in this [issue](https://github.com/python/mypy/issues/337) and merged in [this Pull Request](https://github.com/python/mypy/pull/463)

**Comment by isra17** [comment]
Had some fun looking at mypy internals for the first time. The checker only check for the source (And the exception too actually) to match the subtypes: https://github.com/python/mypy/blob/781caffa5c325b197e2c206a7322e671d2fee442/mypy/checker.py#L3332 , but the subtype see `DeletedType` as a subtype of everything.

This fix the issue:

```
--- a/mypy/checker.py
+++ b/mypy/checker.py
@@ -3317,6 +3317,9 @@ class TypeChecker(NodeVisitor[None], CheckerPluginInterface):
     def type_check_raise(self, e: Expression, s: RaiseStmt,
                          optional: bool = False) -> None:
         typ = get_proper_type(self.expr_checker.accept(e))
+        if isinstance(typ, DeletedType):
+            self.msg.deleted_as_rvalue(typ, e)
+            return
         exc_type = self.named_type('builtins.BaseException')
         expected_type = UnionType([exc_type, TypeType(exc_type)])
         if optional:
```

**Comment by gvanrossum** [comment]
Excellent. Could you add a unit test and submit it as a PR?

**Comment by aviau** [comment]
I submitted a PR here: https://github.com/python/mypy/pull/9272
