### ISSUE TITLE
Analysation API

### ISSUE THREAD

**Issue by atollk** [python/mypy#9273]
I am interested in writing a flake8 plugin that checks certain usage of objects of certain types. For that, I need some kind of analyzer to determine the type of a variable.
My first thought went to mypy, as I suppose this is something that is being done behind the scenes. But looking at the documentation, there does not seem to be an API exposing that information.

* Is my.assumption correct in that the current mypy API does not offer type analysis without error analysis or reporting?
* if so, is this something that mypy is planned to offer in the future?
* If so, what can I do to help reach that point?

**Comment by Akuli** [comment]
asking mypy "what type is this object" could be useful for other things too:
- generating documentation
- autocompletion (currently there's jedi, but sometimes mypy knows the type of a variable while jedi has no idea)

**Comment by gvanrossum** [comment]
Mypy’s internal architecture is not particularly suited to this, and it is not on the roadmap. I don’t think it would be easy to change things to support such a use case. Sorry.

**Comment by Akuli** [comment]
how does mypy implement `reveal_type()` then?

**Comment by hauntsaninja** [comment]
You might have some luck writing a mypy plugin instead (https://mypy.readthedocs.io/en/stable/extending_mypy.html#extending-mypy-using-plugins) or possibly twisting the mypy daemon's arm to do what you want (https://mypy.readthedocs.io/en/stable/mypy_daemon.html#static-inference-of-annotations).

**Comment by atollk** [comment]
Thanks for the replies. Since mypy doesn't have this feature planned, I'll consider whether starting an entire new library is worth the effort for my use case.

Plugins seem to be the opposite use case (support mypy, rather than extend mypy) unless I am missing something.
The deamon's function isn't quite enough, since it only seems to support functions and not single variables.

**Comment by Akuli** [comment]
>Plugins seem to be the opposite use case (support mypy, rather than extend mypy) unless I am missing something

hauntsaninja gave you a link that literally says "Extending mypy using plugins". Did you mean that a flake8 plugin with mypy features isn't what mypy plugins are for?

**Comment by atollk** [comment]
@Akuli Yes.

> Mypy supports a plugin system that lets you customize the way mypy type checks code. This can be useful if you want to extend mypy so it can type check code that uses a library that is difficult to express using just PEP 484 types.

That an "extension" of mypy in the sense that you are adding extended support to use the current behavior on more code. It's not an extension to the behavior itself, which is what flake8 plugins are.
