### ISSUE TITLE
"None" has no attribute 

### ISSUE THREAD

**Issue by sunyunlee** [python/mypy#9274]
For a piece of code like the following
```
x = None 
if True: 
    x = "apple"
    print(x.capitalize())
```
I would get errors like 
`"None" has no attribute "capitalize""` or "Incompatible types in assignment (expression has type ____, variable has type "None"). I passed in no-strict-optional flag.

**Comment by gvanrossum** [comment]
You have to add a type declaration in this case, e.g.
```
x: Optional[str] = None
if True:
    x = "apple"
    print(x.capitalize())
```

**Comment by hauntsaninja** [comment]
I also can't repro this with latest mypy, even with `--strict`, so you should try updating.
