### ISSUE TITLE
mypy cannot properly infer resulting type of logical expressions

### ISSUE THREAD

**Issue by mykola-mokhnach** [python/mypy#9278]
The testing code is:

```python
from typing import Optional
from dataclasses import dataclass


@dataclass
class User:
    org_id: str


def do_something_with_org(org_id: str) -> None
    pass

def do_something_else(user: Optional[User] = None) -> None
    do_something_with_org(user and user.org_id)
```

Upon checking this piece of code with mypy (version 0.782, Python version 3.7.8) it always complains to something like
`Argument 1 to "do_something_with_org" has incompatible type "Union[User, None, str]"; expected "Optional[str]"`, which seems odd to me, because I always expect the result of `user and user.org_id` to be either a `str` or `None` and never of `User` type. 

Changing the `user and user.org_id` expression to `user.org_id if user else None` helps to workaround the error though

**Comment by gvanrossum** [comment]
It's because it doesn't know that `User` instances can never be false, so the only way the first part is false would be if `user is None`. (I assume you meant the signature for the first function to be `Optional[str]`.)

**Comment by mykola-mokhnach** [comment]
Thanks for the quick response Guido,

sorry, it should be Optional[str] in the example code, fixed it. Although the original issue is still there: org_id can only be str or None in such case, but never of type User. Is it the expected behaviour or a bug of mypy?

**Comment by hauntsaninja** [comment]
To go over what Guido said in a little more detail,
- if `user` is None, then `user and user.org_id` equals `user`, which is None
- if `user` is User and truthy, then `user and user.org_id` equals `user.org_id`, which is of type str
- if `user` is User and falsey, then `user and user.org_id` equals `user` which is of type `User`

Since mypy doesn't know that User is never falsey, it infers `Union[User, None, str]` for the expression.

**Comment by mykola-mokhnach** [comment]
sure @hauntsaninja . Could you please elaborate more on the third option: `user is User and falsey`? Perhaps I don't know something, but how this situation could be possible? According to the [doc](https://docs.python.org/3/library/stdtypes.html#truth-value-testing):

```
By default, an object is considered true unless its class defines either a __bool__() method that returns False or a __len__() method that returns zero, when called with the object
```

and the User class does not override any of these methods.

**Comment by hauntsaninja** [comment]
But a subclass could!
