### ISSUE TITLE
Arguments in `__truediv__` and `__itruediv__` is not specified as positional-only

### ISSUE THREAD

**Issue by KKawamura1** [python/mypy#9296]
When I name a function `__div__` or `__idiv__`, it seems to have different type signature from normal functions.
Is it intended behavior?

## Code to reproduce

```
$ cat main.py
class A:
    def f(self, other: int) -> int:
        pass

    def __div__(self, other: int) -> int:
        pass

    def __truediv__(self, other: int) -> int:
        pass

    def __idiv__(self, other: int) -> int:
        pass

    def __itruediv__(self, other: int) -> int:
        pass


reveal_type(A.f)
reveal_type(A.__div__)
reveal_type(A.__truediv__)
reveal_type(A.__idiv__)
reveal_type(A.__itruediv__)

$ mypy main.py
main.py:18: note: Revealed type is 'def (self: main.A, other: builtins.int) -> builtins.int'
main.py:19: note: Revealed type is 'def (main.A, builtins.int) -> builtins.int'
main.py:20: note: Revealed type is 'def (self: main.A, other: builtins.int) -> builtins.int'
main.py:21: note: Revealed type is 'def (main.A, builtins.int) -> builtins.int'
main.py:22: note: Revealed type is 'def (self: main.A, other: builtins.int) -> builtins.int'

$ mypy --version
mypy 0.782
```

**Comment by gvanrossum** [comment]
Mypy knows that these are standard operator overloads and those have positional-only parameter lists. So yes, this is intended. The anomaly here is actually `__[i]truediv__`, which ought to be treated the same way but isn't.

**Comment by KKawamura1** [comment]
OK thanks, I got it. I'll rename the issue.

**Comment by KKawamura1** [comment]
By the way, should I explicitly annotate that they are positional-only:

```python
class C:
    def __add__(self, other: int, /) -> int:
        ...
```

or not? If we are encouraged to do that, would we make a new option, say, `--disallow-operator-overload-with-keyword-argument`, to prevent not to use `/` in positional-only operator overloads?

**Comment by JukkaL** [comment]
There's no need to annotate them as positional-only.
