### ISSUE TITLE
Documentation: Mention `__future__.annotations` in forward refs section

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#9311]
In https://mypy.readthedocs.io/en/stable/kinds_of_types.html#class-name-forward-references, we should mention the situation with `from __future__ import annotations` that makes forward references unnecessary in recent versions of Python.

**Comment by gvanrossum** [comment]
Note that there are still some scenarios where forward references need to be placed in string quotes, e.g. when defining a type alias or the bound of a type variable (IIRC there are a few others).

**Comment by tech-cobber** [comment]
I can do this issue if you don't mind. I will use [PEP 563](https://www.python.org/dev/peps/pep-0563/#forward-references) as a source.
