### ISSUE TITLE
docs: mention py.typed files

### ISSUE THREAD

**Issue by Akuli** [python/mypy#9323]
* documentation bug
* ctrl+f for `py.typed`: https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
* it's not found
* I would expect it to be mentioned so that library authors know how to make mypy recognize the packages as having type hints
* latest documentation from the above link

**Comment by ethanhs** [comment]
It is mentioned on the page here linked from that page: https://mypy.readthedocs.io/en/latest/installed_packages.html#installed-packages.

`py.typed` files are really a thing package maintainers should worry about, so I'm not sure if we should include information about them on the page you linked.

Though I'm interested to hear what you think.

**Comment by Akuli** [comment]
How about replacing "declared themselves to be PEP 561 compliant stub package" with "declared themselves to be PEP 561 compliant stub package with a `py.typed` file"? I think it would make lazy readers like me notice that better without confusing people who don't care about it.

**Comment by gvanrossum** [comment]
Just submit a PR already. :-)

**Comment by Akuli** [comment]
I didn't expect "needs discussion" to mean that but ok.
