### ISSUE TITLE
Mypy reports Callback protocols and  Callable types as incompatible for Async Attributes

### ISSUE THREAD

**Issue by klairetan** [python/mypy#9328]
I'm seeing some errors that seem to contradict the supposed interchangeability of callback protocols and callable types. Wasn't sure if I just missed something or there's actually a bug here.

```python
class Provider(Protocol):
    def __call__(self) -> int: ...

class AsyncProvider(Protocol):
    async def __call__(self) -> int: ...

async_func: Callable[[], Awaitable[int]]
async_provider: AsyncProvider

async_func = async_provider  # works
async_provider = async_func  # works

class Example:
    async_provider: AsyncProvider
    provider: Provider

    def __init__(self, async_func: Callable[[], Awaitable[int]], func: Callable[[], int]):
        self.async_provider = async_func  # ERROR: Incompatible types
        self.provider = func  # works
```
This produces errors of when assigning the `async_func` argument to `self.async_provider`.

```python 
error: Incompatible types in assignment (expression has type "Callable[[], Awaitable[int]]", variable has type "AsyncProvider")
note: "AsyncProvider.__call__" has type "Callable[[], Coroutine[Any, Any, int]]"
```
It seems this should be allowed if we can do `async_provider = async_func`.
Am I missing something? 

Edit:

Note I used `AsyncProvider` instead of `Callable[[], Awaitable[int]]` for 
```python
class Example:
    async_provider: AsyncProvider
``` 
because of https://github.com/python/mypy/issues/708

**Comment by hauntsaninja** [comment]
A Coroutine is a subtype of Awaitable. So if your async_func claims to be an AsyncProvider, its `__call__` needs to return a Coroutine.

You can fix by changing your definition of AsyncProvider to:
```
class AsyncProvider(Protocol):
    def __call__(self) -> Awaitable[int]: ...
```
or by changing the type of `async_func` to be a callable that returns a coroutine.
