### ISSUE TITLE
Signature incompatible with supertype when using static methods

### ISSUE THREAD

**Issue by barisione** [python/mypy#9330]
This code:
```
class Base:
    @staticmethod
    def method(n: int) -> None:
        print(n)


class Deriv(Base):
    def method(self, n: int) -> None:
        print(f"{n} from {self}")
```

Produces this:
```
$ mypy test_static.py
test_static.py:8: error: Signature of "method" incompatible with supertype "Base"
Found 1 error in 1 file (checked 1 source file)
```

When using mypy from git (`mypy 0.790+dev.c231ee4fdca075582e1177a8ecea3f379ccaa784`) with Python 3.8.

This is pretty similar to https://github.com/python/mypy/issues/4125 (attributes overwritten with properties) and could end up being fixed by https://github.com/python/mypy/issues/7724.
I'm still reporting the issue as I didn't see any mention of static methods in other issues.

**Comment by ilevkivskyi** [comment]
FWIW mypy is correct here, this is not a safe override, since methods can be called on class objects:
```python
x: Type[Base] = Deriv
x.method(42) # Oops, TypeError at runtime here
```
