### ISSUE TITLE
Addition of pull_request template and issue template for mypy

### ISSUE THREAD

**Issue by iamrajiv** [python/mypy#9342]
Adding ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md file will enhance the workflow of the repository.

I will try to use the new form of ISSUE_TEMPLATE i.e. making a folder ISSUE_TEMPLATE in `.github` and adding different types of `.md ` files for different issues like `bug.md`, `documentation.md`, `proposal.md`, `feature.md` etc. A contributor can choose the type of templates whenever they make an issue or PR.

Reference: https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by gvanrossum** [comment]
Have you looked at the templates of other projects of similar size? There# should be no reason to reinvent the wheel here. :-)

**Comment by gvanrossum** [comment]
This is *not* fixed, PR #9345 did not work.

**Comment by iamrajiv** [comment]
@gvanrossum The PR #9345 does not work because I have deleted the `about` section from issue template without  `about` section it does not work. I have made new PR #9367 please take a look.
