### ISSUE TITLE
Generic type maintaining its concrete inferred type

### ISSUE THREAD

**Issue by internetimagery** [python/mypy#9350]
Hi everyone!

I'm not sure if this is a bug, or a misunderstanding of mine about how this should work.
What it appears to be, to my layman self, is that the generic type MM_T (protocol bound generic) is being set to the first
thing that mypy sees. Then remains as that concrete type from then on.

If that is indeed the intended usage, sorry for the misunderstanding. It would be awesome if someone in the know could hint as to how this could be achieved? A great learning experience.

An example case below, with some notes at the bottom. Run on mypy version `0.782`, with the command `mypy minmaxtest.py`

``` python
# minmaxtest.py

from typing import (
    Any,
    Optional,
    Iterable,
    Callable,
    TypeVar,
    overload,
    Protocol,
    Union,
    Tuple,
    cast,
    Type,
)


class _SupportsMinMax(Protocol):
    def __lt__(self, other):
        # type: (Any) -> bool
        pass

    def __gt__(self, other):
        # type: (Any) -> bool
        pass


T = TypeVar("T")
MM_T = TypeVar("MM_T", bound=_SupportsMinMax)


@overload
def minmax(__values):
    # type: (Iterable[MM_T]) -> Tuple[MM_T, MM_T]
    pass


@overload
def minmax(__values, key=None):
    # type: (Iterable[T], Callable[[T], MM_T]) -> Tuple[MM_T, MM_T]
    pass


def minmax(
    values,  # type: Union[Iterable[T], Iterable[MM_T]]
    key=None,  # type: Optional[Callable[[T], MM_T]]
):
    # type: (...) -> Tuple[MM_T, MM_T]
    """
    Retrieve the minimum and maximum of the provided values.
    The two CAN be the same value.
    """
    small = large = None

    for value in values:
        value = key(cast(T, value)) if key else cast(MM_T, value)
        if value < small:
            small = value
        if value > large:
            large = value

    if small is None or large is None:
        raise ValueError("Not enough values provided")
    return small, large


val = minmax([1,2,3,4,5,6])
reveal_type(val)
val = minmax("abcde")
reveal_type(val)
val = minmax("abcde", key=lambda x: x)
reveal_type(val)

# minmaxtest.py:67: note: Revealed type is 'Tuple[builtins.int*, builtins.int*]'
# minmaxtest.py:69: note: Revealed type is 'Tuple[builtins.int*, builtins.int*]'
# minmaxtest.py:70: error: Argument "key" to "minmax" has incompatible type "Callable[[str], str]"; expected "Optional[Callable[[str], int]]"
# minmaxtest.py:70: error: Incompatible return value type (got "str", expected "int")
# minmaxtest.py:71: note: Revealed type is 'Tuple[builtins.int*, builtins.int*]'
```

My expectations would be that the first reveal_type is correct. The second and third should be `Tuple[str, str]`. The callable should be correct as `Callable[[str], str]`.
It seems like the generic `MM_T` has been permanently cast as int (in this case as it's the first type seen?). 

Thanks a lot everyone. This is amazing software, and type checking python in general is an absolute game changer!

**Comment by hauntsaninja** [comment]
The issue is that `val` is permanently considered to be `int`. If you use a different variable each time you'll get the results you want. You can change the behaviour to allow `val` to change type by using `--allow-redefinition`.

**Comment by internetimagery** [comment]
Hah. Well that is embarrassing. Thanks a lot @hauntsaninja!  :+1:
