### ISSUE TITLE
mypy is missing check that variable of type `Optional[str]` is not None, raising error when assigning this to type `str`

### ISSUE THREAD

**Issue by Axel-Jacobsen** [python/mypy#9355]
Reporting Bug

* Minimal Reproduction

File is `typeme.py`
```python3
import random
from typing import Optional

def maybe_str() -> Optional[str]:
    if random.getrandbits(1):
        return 'Hello, World!'
    return None

left  = maybe_str()
right = maybe_str()

if left is None and right is None:
    raise RuntimeError('end of the world!')

if right is not None:
    output: str = right
else:
    output = left
```

* What is the actual behavior/output? With `mypy typeme.py`, we get

``` bash
typeme.py:20: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")
Found 1 error in 1 file (checked 1 source file)
```

* What is the behavior/output you expect?

This should not fail. In the `if left is None and right is None` statement, we raise a `RuntimeError` if both `left` is `None` and `right` is `None`. In the next `if` statement, if `right` is not None, we assign the `output` variable to the value of `right`. If that fails, we know that `left` is also not None.

I understand that `left` has the type `Optional[str]`, just like `right`. Due to the `if right is not None` statement, mypy allows the assignment `output: str = right`. It misses the fact that in this case, we know that `left` is also not None, and therefore the assignment to a `str` type is not invalid. Including a cast to `str` also does not fix the issue (i.e. adding `cast(str, left); output = left` also raises the same error).

* What are the versions of mypy and Python you are using?

Python version: 3.7.7, mypy version 0.780

* Do you see the same issue after installing mypy from Git master?

Yes - created virtualenv, installed from master, issue still remains.

If I am correct that this is a bug, I may be interested in trying to fix this issue, but I would only be able to start on the 3rd of September. If someone snatches it before then, it is plenty alright with me!

**Comment by JelleZijlstra** [comment]
Mypy doesn't have this sort of complicated understanding of the dependencies between variables (if A is None, then B is not None). There are several similar previous issues, but it feels unlikely that we'd add support for it.

**Comment by Axel-Jacobsen** [comment]
OK sounds good - I will close the issue. Thank you!

**Comment by Akuli** [comment]
as a quick fix, you can add `assert left is not None` before `output = left`
