### ISSUE TITLE
No description for strict flag

### ISSUE THREAD

**Issue by staticdev** [python/mypy#9374]
## 📚 Documentation

I haven't seen in the documentation explaining the effects of adding to [mypy configuration](https://mypy.readthedocs.io/en/stable/config_file.html) file `strict = True`.

After some more search I saw this option in [here](https://mypy.readthedocs.io/en/stable/getting_started.html?highlight=strict#configuring-mypy) but it only says it `enables many (though not all) of the available strictness options – including --disallow-untyped-defs.`.

What would be very nice to have is a list of all checks/strictness options it enables.

**Comment by hauntsaninja** [comment]
As documented in https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict you can see the exact set of flags in `mypy --help`:

```
  --strict                  Strict mode; enables the following flags: --warn-
                            unused-configs, --disallow-any-generics,
                            --disallow-subclassing-any, --disallow-untyped-
                            calls, --disallow-untyped-defs, --disallow-
                            incomplete-defs, --check-untyped-defs, --disallow-
                            untyped-decorators, --no-implicit-optional,
                            --warn-redundant-casts, --warn-unused-ignores,
                            --warn-return-any, --no-implicit-reexport,
                            --strict-equality
```

The reason for the slight inconvenience, as per the documentation is:
> Note: the exact list of flags enabled by running --strict may change over time.

Leaving the issue open since there's a good chance people feel like we're unlikely to make changes to `--strict` soon, and so maintenance burden of making the documentation more explicit is small.

**Comment by staticdev** [comment]
Thanks a lot @hauntsaninja!

**Comment by gvanrossum** [comment]
Would it kill us to add a pseudo option to the config file that selects all strict options?

**Comment by staticdev** [comment]
@gvanrossum nice idea. There is a configuration for [strictness in darglint](https://github.com/terrencepreilly/darglint#strictness-configuration) that could be mirrored here.

`strict = full # would be what you look for`

**Comment by JukkaL** [comment]
@Hyperion101010 Done!

Note that `strict = True` works in the config file, but it doesn't seem to be documented.

**Comment by staticdev** [comment]
@JukkaL this is my main concern. You don't know in advance what `strict` means since you don't have a clear definition. This can also change between versions and in the worst case scenario break CI/CDs all along. Having different levels of strictness (and a full option as suggested by @gvanrossum) would be ideal IMO, since you have an intention well defined.

**Comment by JukkaL** [comment]
@staticdev Ah that makes sense. We'd need to think carefully about the strictness levels, since as you mentioned they will be hard to change afterwards. Can we move the discussion of this in #3507, since this issue is about the missing/incomplete documentation?

**Comment by staticdev** [comment]
Sure @JukkaL, I will close here then.
