### ISSUE TITLE
Support recursive NamedTuple

### ISSUE THREAD

**Issue by habilain** [python/mypy#9397]
## 🐛 Bug Report

NamedTuple's appear to behave in unexpected ways with recursion, especially when compared to frozen dataclasses (which are rather similar, as far as the user is concerned).

## To Reproduce

```python
from __future__ import annotations
from typing import NamedTuple, Optional

class A(NamedTuple):
  a: Optional[A]
```

Produces a "mypy-sample1.py:5: error: Cannot resolve name "A" (possible cyclic definition)". However,

```python
from __future__ import annotations
from typing import Optional
from dataclasses import dataclass

@dataclass(frozen=True)
class A:
  a: Optional[A]
```

Passes MyPy just fine, and as far as a user is concerned, presents a very similar surface for MyPy to type check (i.e. both have a read-only attribute a which is either None or of class A).

## Expected Behavior

The expected behaviour would be that both NamedTuple and frozen dataclass behave the same, as NamedTuple and frozen dataclasses present logically similar behaviour with regards to the attribute 'a'.

## Actual Behavior

In addition to the odd behaviour with cycle checker triggering on NamedTuple but not on dataclasses, it's possible to fool the cycle checker completely and have MyPy crash by recursing too far (e.g. issue #8695 and although that issue has been reported with a recursive type that could never be instantiated, I've encountered the same behaviour with type definitions that can be instantiated, but not in a minimal example friendly format). I think this specific behaviour is the root cause, as the real problem is that for some reason NamedTuple's are behaving differently to what would be expected.

## Your Environment

- Mypy version used: mypy 0.782
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.8.2
- Operating system and version: Linux

**Comment by ramalho** [comment]
To illustrate the bug with a more "realistic" example, here is the top of an `Order` class to demonstrate the **Strategy** pattern, where a concrete strategy is named a `promotion`, and it must be a callable that accepts an `Order` argument:

```python
@dataclass
class Order:  # the Context
    customer: Customer
    cart: Sequence[LineItem]
    promotion: Optional[Callable[['Order'], float]] = None  # the Strategy
```

Mypy accepts the code above, but bombs with the code below:

```python
class Order(NamedTuple):
    customer: Customer
    cart: Sequence[LineItem]
    promotion: Optional[Callable[['Order'], float]] = None  # the Strategy
```

**Comment by AlexWaygood** [comment]
I've added the "crash" label — although the original report is a bug, @ramalho's example is clearly a crash.

**Comment by JelleZijlstra** [comment]
I opened #12629 to discuss the crash. This issue should be focused on the enhancement request (support for recursive namedtuples). Any crashes should get their own issue.

**Comment by mrolle45** [comment]
I believe the source of the problem is in the `TypeAnalyzer.visit_unbound_type_nonoptional` method:
```
...
            if isinstance(node, PlaceholderNode):
                if node.becomes_typeinfo:
                    # Reference to placeholder type.
                    if self.api.final_iteration:
                        self.cannot_resolve_type(t)
                        return AnyType(TypeOfAny.from_error)
                    elif self.allow_placeholder:
                        self.api.defer()
                    else:
                        self.api.record_incomplete_ref()
                    return PlaceholderType(node.fullname, self.anal_array(t.args), t.line)
...
```

Before the final iteration, the reference is considered incomplete.  In the final iteration, it is still a placeholder, and reported as an error.  Also, the type is deemed to be Any, rather than the type of the class being defined.

Why this does not happen with non-NamedTuple classes, I cannot tell.  mypy can form a correct TypeInfo for the class and for each of its members.

```

**Comment by ilevkivskyi** [comment]
This now works on master with `--enable-recursive-aliases`.
