### ISSUE TITLE
Unpin setuptools

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#9401]
https://github.com/python/mypy/pull/9400 pins us to setuptools<50

Once the burning has stopped (to quote https://github.com/pypa/setuptools/pull/2376), we should unpin this. One day, everything will work.

Also while I'm here, a couple months ago I pinned virtualenv<20 to fix CI. virtualenv might work for us now, so another thing we could unpin.

**Comment by hauntsaninja** [comment]
Should be easy to find something that works, now that setuptools has merged and released that PR.

**Comment by vhawk19** [comment]
@hauntsaninja Could I work on this issue? I am relatively new to the open source ecosystem, but would like to contribute. Would this be a good first issue for me to pick up?

**Comment by hauntsaninja** [comment]
Welcome! Of course, go ahead. I suspect simply undoing #9400 should work (as judged by CI passing). If so, you could maybe exclude the problematic setuptools versions in the version constraint. However, if that doesn't work / you're unfamiliar with how Python packaging works, you might want to try another issue.

https://github.com/python/mypy/blob/master/CONTRIBUTING.md has more general guidance

**Comment by harshest2019** [comment]
@hauntsaninja I am new here as well and want to start contributing to open source, i have sound knowledge of python and i am eager to learn.
Please guide me on what to do and where to get started, it would help me a lot and I hope then i will be able to help open source community as well.
Thank You.

**Comment by gvanrossum** [comment]
@harshest2019 I'm sorry, but a specific issue like this is not an appropriate place to ask for guidance with your first steps contributing. Please use the Gitter channel linked from the repo's README.md. Also study the CONTRIBUTING.mg file in the repo.

**Comment by harshest2019** [comment]
@gvanrossum I am sorry sir, I will do as you asked.
Thank You and please excuse my mistake.

**Comment by Cyatos** [comment]
@hauntsaninja Is this issue still up for grabs? I'd like to raise a PR if one hasn't been raised already.

**Comment by gvanrossum** [comment]
@Cyatos Please go ahead.
