### ISSUE TITLE
Implicit return in function which does not return for "NoReturn" hint

### ISSUE THREAD

**Issue by qiujiangkun** [python/mypy#9411]
```python3
from typing import NoReturn
def foo() -> NoReturn:
    pass
```
gives a warning `Implicit return in function which does not return`

**Comment by gvanrossum** [comment]
Please ask on Gitter.

**Comment by qiujiangkun** [comment]
I suppose it’s a bug rather than a question. I know how to work around it but mypy should also support this special situation by checking if the hint of return value is NoReturn.

**Comment by srittau** [comment]
It's not a bug. `foo()` returns `None`. `NoReturn` is used for situations, where the function does not return at all. (For example, because an exception is thrown unconditionally or `sys.exit()` is called.)
