### ISSUE TITLE
Support `or` in `isinstance` expressions.

### ISSUE THREAD

**Issue by jhance** [python/mypy#942]
I saw in some place in mypy something like

```
class A:
    pass

class B(A):
    pass

class C(A):
    pass

x = C()  # type: A
if isinstance(x, B) or isinstance(x, C):
    y = cast(Union[B, C], x)
    ...
```

We should be able to infer `Union[B, C]` as the type of `x` within this expression.

**Comment by JukkaL** [comment]
Yes, that would be nice. #947 is related (tuple as the second argument to `isinstance`).

**Comment by jhance** [comment]
It seems like this can get complex pretty quickly (imagine using tuples inside an `and`, now you effectively have an intersection of unions).

It might make sense to do the following:
- Walk the expression. Create a predicate logic tree, converting *both* `OrExpr` and splitting tuple-based isintance-s into `Or` in the predicate logic tree. On top of the predicate tree, but it in an `And` with the current type of each variable (we would convert unions to ors).
- Convert the predicate logic tree to DNF and get a result like `List[Tuple[List[Tuple[Var, Type]], Tuple[Var, List[Type]]]]`. The if and the else case will be symmetric, so lets only consider the if case. Remove "impossible" phrases (where some type contradicts each other, this may be somewhat hard?). First take every variable that appears in here and filter the resulting DNF to only those expressions that include that variable. Take the current type of the variable and on each element in the list, take the intersection of all the types. Then take the union type of all of those at the end.

**Comment by JukkaL** [comment]
At this point it's okay to add some limitations, such as for `and` all the operands must target different variables. So this wouldn't work correctly:

```
if isinstance(x, A) and isinstance(x, B): ...
```

(we'd only recognize the first `isinstance`, since mypy doesn't support intersection types)

We can revisit this later, but the complex cases are going to be pretty marginal so it's not worth it to complicate everything because of them.

**Comment by JukkaL** [comment]
In general, if in doubt whether a particular idiom or construct is worth supporting, try to find actual examples of that in some existing projects. If you can't find any (or just find a few isolated examples), it's probably not that important, and there are lot of things that mypy can't deal with that we *know* to be important (such as every issue tagged with 'priority').
