### ISSUE TITLE
Optional[Type] ignores None check, resulting in Item "None" of "Optional[Type]" has no attribute "attribute"

### ISSUE THREAD

**Issue by elegos** [python/mypy#9428]
## 🐛 Bug Report

I've got an `Optional[WhateverType]` object, on which I check if the object is None, in that case I raise an exception (or return, it's the same). I expect mypy to understand that the type can now be considered WhateverType, and not Optional anymore.

## To Reproduce

```python
from typing import Optional

def testFormat(string: Optional[str]) -> str:
  if string == None:
    return 'String is None'
  return string.format('whatever')
  # Item "None" of "Optional[str]" has no attribute "format"

def testFormat2(string: Optional[str]) -> str:
  if string != None:
    return string.format('whatever')
    # Item "None" of "Optional[str]" has no attribute "format"
  return 'String is None'
```
## Expected Behavior

Whenever I directly (`if obj != None`) or indirectly (after an early return / exception raise) exclude the `None` type of an `Optional` variable, I expect mypy to consider the type as non-Optional.

## Actual Behavior

mypy doesn't recognize the `Optional` value is not `None`, even with an explicit condition

## Your Environment

- Mypy version used: 0.782
- Mypy command-line flags: n/a (running without additional parameters via vscode)
- Mypy configuration options from `mypy.ini` (and other config files): n/a
- Python version used: 3.6.12
- Operating system and version: Fedora 32

**Comment by gvanrossum** [comment]
You should use ‘is’ instead of ‘==‘.
