### ISSUE TITLE
math.comb is not recognized

### ISSUE THREAD

**Issue by lecarrera-tec** [python/mypy#9429]
## 🐛 Bug Report

Using math.comb reports an error: Module has no attribute "comb"

## To Reproduce
file: foo.py

import math

localDict = {
        'factorial': math.factorial,
        'binomial': math.comb
}

## Expected Behavior
running mypy foo.py:

Success: no issues found in 1 source file

## Actual Behavior

foo.py:5: error: Module has no attribute "comb"
Found 1 error in 1 file (checked 1 source file)

## Your Environment

- Mypy version used: 0.761
- Python version used: 3.8.5

**Comment by gvanrossum** [comment]
Please file this bug with typeshed.
