### ISSUE TITLE
State-based profiling for builds

### ISSUE THREAD

**Issue by jhance** [python/mypy#943]
It would be nice to have our own profiling metrics based on how long particular modules take for each pass in `mypy.build`. I think that this is something thats hard to get at with an actual profiler but something very easy for us to measure ourselves automatically.

In particular I'm interested in the current cost of stubs (which is done every time and has static results).

**Comment by jhance** [comment]
Some measurements I took:

https://gist.github.com/anonymous/dcf729892d141e4a8142

**Comment by JukkaL** [comment]
Cool! I've done some ad hoc measurements myself and the results were similar to yours (though off by a factor of 2.5 or so -- I did them on my Core i7-2600K Ubuntu desktop).

Some notes:

* Type checking only takes about 30% of the runtime. There might be some easy wins in the parser and semantic analyzer to speed things up.
* If we'd reimplement the parser and lexer as C extension modules, we could potentially speed up type checking by 30-50% or so (this is most likely *not* the low-hanging fruit -- we should first look into incremental and parallel type checking).

**Comment by kirbyfan64** [comment]
What about using a parser library like PLY (which is really fast) in combination with using a library like re2 for lexing?

**Comment by JukkaL** [comment]
I looked at a C parser that uses PLY (https://github.com/eliben/pycparser). In a simple experiment it could parse about ~8000 lines per second; the mypy parser has roughly similar speed. This is definitely not apples to apples but may indicate that PLY might not be a huge win (assuming that the C parser doesn't do something that compromises performance). 

Parsing in C can be made really fast -- the bottleneck might be creating the AST.

**Comment by JukkaL** [comment]
We've done a bunch of profiling and improved performance. This issue doesn't seem relevant any more.
