### ISSUE TITLE
mypy compiler

### ISSUE THREAD

**Issue by wilkluka** [python/mypy#9460]
Would it be useful to add possibility for mypy to compile stubs into actual files used by end users?

Since keeping type hints stubs is useful because of backward compatibility with python 2, although is would be useful to use type hints in python3 for programmers (and notebook users for pandas, sklearn etc.), so maybe it would be a good idea to produce files that have these type hints in them (maybe even during tests some type check errors will come up in some projects hence reducing number of silly mistakes that compilation and static typing eliminates)

```python

stub
def add(x: int) -> int: ...

add.py (precompiled)
def add(x):
    return x+1

add.py (compiled)
def add(x: int) -> int:
    return x+1
```

or to create a "downgrader" that will remove type hints from python 3 code (and create automatic stubs) and downgrade it to python 2

**Comment by gvanrossum** [comment]
I believe there are already tools that do this. Please ask on Gitter.
