### ISSUE TITLE
Failure to derive correct type in Dict of Tuples

### ISSUE THREAD

**Issue by MaxG87** [python/mypy#9463]
**Bug Report**
I have a dictionary `Dict[str, Tuple[str, Callable]]`. If I put in a `lambda`, mypy fails to deduce the correct type.

```python
from typing import Callable, Dict, Optional, Tuple


def format_number(arg: Optional[float]) -> str:
    if arg is None:
        return "-"
    return str(arg)


# Broken
table_formatting_options = {
    "attr_name_1": ("Column Name 1", format_number),
    "attr_name_4": ("Column Name 4", lambda x: x.foobar),
}

# Working 1
functions = [format_number, lambda x: x.some_attr]

# Working 2
table_formatting_options_2 = {
    "attr_name_1": format_number,
    "attr_name_4": lambda x: x.foobar,
}

# Working 3
table_formatting_options_3: Dict[str, Tuple[str, Callable]] = {
    "attr_name_1": ("Column Name 1", format_number),
    "attr_name_4": ("Column Name 4", lambda x: x.foobar),
}
```

**Expected Behavior**
I would expect that mypy derives the type `Dict[str, Tuple[str, Callable[[Any], Any]]` itself. If this is to problematic, I would expect that the error message points out that mypy rather not derive types for `lambda`.

**Actual Behavior**

```
mwe.py:13: error: Item "float" of "Optional[float]" has no attribute "foobar"
mwe.py:13: error: Item "None" of "Optional[float]" has no attribute "foobar"
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.782
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: Python 3.7.9
- Operating system and version: Ubuntu 20.04

**Comment by MaxG87** [comment]
I found an slightly simpler version:

```python
# Broken 2
table_formatting_options = [
    ("Column Name 1", format_number),
    ("Column Name 2", lambda x: x.foobar),
]
```

Type inference seems to have some trouble with `Tuple`.

**Comment by gvanrossum** [comment]
Think about argument contravariance. Is format_number really a subtype of Callable[[Any], Any]? (You can easily test this.)

If it is, I suspect an issue with the handling of lambda.

**Comment by MaxG87** [comment]
The problem does not reproduce on mypy 0.790.
