### ISSUE TITLE
Mypy does not recognize the attributes of a decorated class' method output

### ISSUE THREAD

**Issue by elicutler** [python/mypy#9465]
**Bug Report**

Mypy does not recognize the attributes of a decorated class' method output. 

**To Reproduce**

I have a convenience decorator for  treating callable classes as functions. Here is the decorator with a couple contrived applications

```
import typing as T
from functools import wraps

import pandas as pd


def class_to_func(cls: type) -> T.Callable[..., T.Any]:
  @wraps(cls)
  def wrapper(*args: T.Any, **kwargs: T.Any) -> T.Any:
    return cls(*args, **kwargs)()
  return wrapper


@class_to_func
class make_dict:
    def __call__(self) -> dict:
        return {'a': 1}


d = make_dict()
print(d['a'])


@class_to_func
class make_df:
    def __call__(self) -> pd.DataFrame:
        return pd.DataFrame({'x': [1]})


df = make_df()
print(df.shape)


def make_dict_real_func() -> dict:
    return {'b': 2}


d2 = make_dict_real_func()
print(d2['b'])
```

The program runs fine:
```
C:\Users\ecutler\projects\ds-utils>python test.py
1
(1, 1)
2
```

However, mypy does not recognize the fact that `d` is a dict and therefore indexable, nor that `df` is a pandas DataFrame and therefore has a shape attribute, even though these annotations are specified in the `__call__` method of their respective classes.

```
C:\Users\ecutler\projects\ds-utils>mypy test.py
test.py:21: error: Value of type "make_dict" is not indexable  [index]
    print(d['a'])
          ^
test.py:31: error: "make_df" has no attribute "shape"  [attr-defined]
    print(df.shape)
          ^
Found 2 errors in 1 file (checked 1 source file)
```

By contrast, `d2`, created by a function without the class-to-function decorator, has its attributes recognized by mypy.

**Expected Behavior**

mypy should not raise any errors

**Actual Behavior**

mypy raised errors as shown above

**Your Environment**

```
C:\Users\ecutler\projects\ds-utils>python --version
Python 3.8.5

C:\Users\ecutler\projects\ds-utils>mypy --version
mypy 0.782

C:\Users\ecutler\projects\ds-utils>cat mypy.ini
[mypy]
allow_untyped_globals = True
disallow_incomplete_defs = True
disallow_untyped_defs = True
no_strict_optional = True
pretty = True
show_error_codes = True
strict_equality = True
ignore_missing_imports = True
warn_unreachable = True
```

OS: Windows 10 Pro, Version 2004, OS Build 19041.508

**Comment by gvanrossum** [comment]
You’re expecting a miracle. Your decorator loses the type of its input.

For more help please use Gitter.

**Comment by elicutler** [comment]
Welp, I appreciate the quick response time!
