### ISSUE TITLE
EAFP handling of optional attribute results in `Item "None" of Optional[...] has no attribute "..."`

### ISSUE THREAD

**Issue by MicaelJarniac** [python/mypy#9467]
**Bug Report**

If I use the [EAFP](https://docs.python.org/3/glossary.html) style like in the following example, mypy doesn't understand the error handling.

```python
from contextlib import suppress

from typing import Optional


class MyClass:
    def __init__(self):
        self.__name: Optional[str] = None

    @property
    def name(self) -> Optional[str]:
        return self.__name

    @name.setter
    def name(self, name: str):
        self.__name = name

    @property
    def upper_name(self) -> Optional[str]:  # Missing return statement - mypy(error)
        with suppress(AttributeError):
            return self.name.upper()  # Item "None" of "Optional[str]" has no attribute "upper" - mypy(error)
```

Using `try` and `except` also results in that error.

Doing the following makes mypy happy, but it breaks the EAFP style:

```python
from typing import Optional


class MyClass:
    def __init__(self):
        self.__name: Optional[str] = None

    @property
    def name(self) -> Optional[str]:
        return self.__name

    @name.setter
    def name(self, name: str):
        self.__name = name

    @property
    def upper_name(self) -> Optional[str]:  # Missing return statement - mypy(error)
        if self.name is not None:
            return self.name.upper()  # No error here this time
```

**To Reproduce**

1. Create a class with an optional property
1. Create a method that uses an attribute of the optional property, with exception handling (like `suppress`)

**Expected Behavior**

I expect mypy to detect the exception handling and not report an error there, since I'm using the EAFP style.

**Actual Behavior**

mypy does not seem to understand the exception handling or the EAFP concept in use, and throws an error, since `None` does not have the expected attribute.

**Your Environment**

- Mypy version used: `mypy 0.782`
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: `Python 3.8.3`
- Operating system and version: Windows 10 Version 1909 (OS Build 18363.1082)

**Comment by JelleZijlstra** [comment]
I'm afraid this coding style is just not compatible with mypy's philosophy. Your suggestion essentially boils down to "don't emit attribute-not-defined errors within a `suppress(AttributeError)` block"—but that also means mypy won't help you if you try to access `self.nmae.upepr`.

**Comment by MicaelJarniac** [comment]
I think instead of suppressing each and every bad type possible that would cause an `AttributeError`, since it has an `Optional[type]` type, it could check if at least one of `type` are valid, and ignore `AttributeError` just for `None`, or something like that.

So if it was
```python
with suppress(AttributeError):
    return self.nmae.upepr
```
there'd be no match for `nmae`, so it would still raise an error, but if it was
```python
with suppress(AttributeError):
    return self.name.upper()
```
it'd find a match for `name`, and it'd see that its type is `Optional[str]`, and then it'd check if `str` has attribute `upper`, which it does, so it doesn't error, despite `None` not having attribute `upper`.

So it'd basically be suppressing the error only for `None`, and still check the other type, that is `str`, to see if that one is valid. If both are invalid, throw error, but if one of them, in this case `str`, is valid, then it doesn't throw the error.

I don't think that'd be easy to implement, but I do think it's at least possible.
