### ISSUE TITLE
`str` is not `unicode` in py2

### ISSUE THREAD

**Issue by bwo** [python/mypy#9471]
mypy erroneously allows functions annotated as accepting `unicode` or a synonym thereof (`six.text_type`, e.g.) to be called with arguments of type `str`:

```
10:19:32 $ cat foo.py
def foo(x):
    # type: (unicode) -> int
    return len(x)


x = 'hi'  # type: bytes
reveal_type(x)
foo(x)
foo('hi')
foo(u'bye')
reveal_type(foo)
10:20:32 $ .mypy/.venv/bin/mypy -2 foo.py
foo.py:7: note: Revealed type is 'builtins.str'
foo.py:11: note: Revealed type is 'def (x: builtins.unicode) -> builtins.int'
10:20:40 $ .mypy/.venv/bin/mypy -V
mypy 0.790+dev.bfdad80003c8ad761bdade1fc5aa7fb19c1121a5
```

I *believe* this is a regression, but I'm not 100% certain of that.

**Comment by gvanrossum** [comment]
This is intentional. In Python 2, mypy treats str as a subtype of unicode, because in 99% of cases that actually is the intention.
