### ISSUE TITLE
Extract argument and return types

### ISSUE THREAD

**Issue by w0rp** [python/mypy#9472]
**Feature**

I would like to have some way to extract the types of the arguments for a function, and also the return type of a function.

**Pitch**

I don't know if this has been raised before, but I tried searching through issues for a while and I couldn't find anything quite like it, at least not easily. This is more of an issue for Python's `typing` module, and it's not straightforward to implement.

I use TypeScript a lot, and two utility types that are really useful from TypeScript are [ReturnType](https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype) and [Parameters](https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype). They allow you to extract the return type of a function, or the type of its arguments. These utility types have a number of applications. If we had equivalents in Python, they would be useful for defining the types of decorated functions. For example:

```py
OldFunction = Callable[[int], str]

# Equivalent to Callable[[int], str]
ModifiedResult = Callable[Parameters[OldFunction], int] 

# Equivalent to Callable[[str], str]
ModifiedArguments = Callable[[str], ReturnType[OldFunction]]
```

Here are extremely naive implementations of the above utility types:

```py
>>> class Parameters:
...     def __class_getitem__(cls, callable):
...         return list(callable.__args__[0:-1])
... 
>>> class ReturnType:
...     def __class_getitem__(cls, callable):
...         return callable.__args__[-1]
... 
>>> Parameters[Callable[[int, list], str]]
[<class 'int'>, <class 'list'>]
>>> ReturnType[Callable[[int, list], str]]
<class 'str'>
```

A finished product would require a lot more boilerplate, such as error messages for when you pass in values that aren't `Callable`, etc. Let me know what people think. I'm willing to implement this for the typing module itself if it seems like a good idea.

**Comment by gvanrossum** [comment]
This would be a good topic for typing-sig. The implementation needs support from type checkers; this is not just a runtime function.

**Comment by hauntsaninja** [comment]
You might be interested in the Rejected Alternatives section of the accepted PEP 612: https://www.python.org/dev/peps/pep-0612/#defining-parametersof

**Comment by w0rp** [comment]
@gvanrossum Thanks, I'll figure out how to create a topic for typing-sig. I've never really used any mailing lists in my 10 years of being a developer.

@hauntsaninja Thanks, I couldn't find that, despite by best efforts to Google for it. Despite the same idea being previously rejected in PEP, I think it's a general language concept that's proven to be very useful in the world of TypeScript. I'll make a note to open up a discussion in the mailing list.
