### ISSUE TITLE
Some Python2 tests are skipped in CI

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#9473]
https://github.com/python/mypy/pull/9196 appears to have broken tests (https://github.com/python/typeshed/runs/1157402752?check_suite_focus=true, testAssignToComplexReal_python2). It looks like this is because it needs a Python 2 with typing installed. If that isn't the case, the test gets skipped.

**Comment by vbarbaresi** [comment]
It seems that these tests are skipped on purpose, because they're too slow:
https://github.com/python/mypy/blob/3e77959eacf3d445a0cb4db5a4bc6dcf606fc040/mypy/test/testpythoneval.py#L9-L10
