### ISSUE TITLE
[FYI] mypy_primer

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#9490]
With apologies to black_primer, I jotted down a script that lets us run mypy over a large amount of open source Python code. Hopefully this helps democratise the process of identifying issues and regressions and evaluating risky changes.

This has informed:
https://github.com/python/typeshed/pull/4579
https://github.com/python/typeshed/pull/4574
https://github.com/python/typeshed/pull/4582
https://github.com/python/typeshed/pull/4583
And you can see it in action at:
https://github.com/python/mypy/pull/9275
https://github.com/python/mypy/issues/9290#issuecomment-701631733

More details at: https://github.com/hauntsaninja/mypy_primer

Feel free to close or otherwise discuss!

**Comment by TH3CHARLie** [comment]
Very interesting(and of course powerful) utility!

**Comment by obi1kenobi** [comment]
This seems pretty cool, nicely done!

Does it support `mypy` settings other than the defaults? Asking because in #9493 I ran into an issue where seemingly *relaxing* `mypy`'s settings from their default values caused a crash when analyzing `xarray` as a dependency of another project, and I noticed that one of the issues you found and helped fix was discovered by analyzing `xarray`.

**Comment by hauntsaninja** [comment]
Not quite, it's meant to try to invoke mypy the way the projects are invoking mypy. So each project has a hardcoded mypy command that I stole (usually from their CI) / it picks up the project's mypy configuration files.
I do agree that using mypy_primer is a good approach to explore / test flags and it should be fairly easy to change the script to do this sort of thing.

PS: Thanks for sharing and writing `typing_copilot`, seems useful! I've seen a number of projects setting `ignore_errors = True` in their config files as a way of ratcheting (e.g [scipy](https://github.com/scipy/scipy/blob/a240c178a3f80461d9aef7daf3d4d9de5bdbdfcb/mypy.ini#L177)). Incorporating stricter settings for subpackages like that into typing_copilot could be a interesting (but potentially complex) addition.

**Comment by hauntsaninja** [comment]
Closing, since mypy_primer is now in mypy CI.
