### ISSUE TITLE
Ensuring that mypy gets the hint that compared values are always of same types when comparing Unions of multiple types

### ISSUE THREAD

**Issue by lGp2XKSsVZNrMQ** [python/mypy#9499]
I get the following traceback that mypy throws: 

    dust/core/validator/_validators.py:504: error: Unsupported operand types for < ("str" and "ValidateProperty")
    dust/core/validator/_validators.py:504: error: Unsupported operand types for < ("float" and "ValidateProperty")
    dust/core/validator/_validators.py:504: error: Unsupported operand types for < ("float" and "str")
    dust/core/validator/_validators.py:504: error: Unsupported operand types for < ("str" and "float")

for the code that goes something like following. 
    
    class Value(ValidateProperty):
        def __init__(min_value: VALUE_RANGE=None, max_value: VALUE_RANGE=None):
            if min_value is not None and max_value is not None:
                if max_value < min_value:
                    raise ValueError(f"max_value can not be less than min_value")

where `VALUE_RANGE` is 

    VALUE_RANGE = typing.Union[FLOAT,STRING, None]
such that:

    FLOAT = typing.Union[float, "ValidateProperty", None]
    STRING = typing.Union[str, "ValidateProperty", None]

and `ValidateProperty` is an ABC class with `__get__` and `__set__` methods.

how to ensure that mypy gets that comapred values are always of same types ?

**Comment by gvanrossum** [comment]
I think your point is that you're always calling `Value(x, y)` such that x and y have the same type.

To do that, you have to use type variables.

For more help, please use Gitter.
