### ISSUE TITLE
Walrus Operator  with bool leads to internal error

### ISSUE THREAD

**Issue by marincandenza** [python/mypy#9516]
**Bug Report**

test\qtest\test_api.py:228: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.782
Traceback (most recent call last):
  File "...Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "mypy\checker.py", line 401, in accept
  File "mypy\nodes.py", line 1195, in accept
  File "mypy\checker.py", line 3212, in visit_if_stmt
  File "mypy\checker.py", line 3928, in find_isinstance_check
  File "mypy\checker.py", line 4104, in find_isinstance_check_helper
  File "mypy\checker.py", line 4108, in find_isinstance_check_helper
KeyError: <mypy.nodes.NameExpr object at 0x0000027B2E517AC0>
test\qtest\test_api.py:228: : note: use --pdb to drop into pdb

**To Reproduce**

1. Create two dict with some k, v pairs 
2. Iterate in a for loop over dict
3. if match := (dict_expected["id"] == dict_actual["id"]): break

mypy should crash in point 3.

**Expected Behavior**

mypy should not crash.

**Actual Behavior**
mypy crashes in the if expression
```
        assert cycle["id"] > 0, 
        assert cycle["name"] == name,
        all_cycle_under_root = qtest_client.get_test_cycles(parent_type="root")
        match = False
        for query_cycle in all_cycle_under_root:
            if match := (query_cycle["id"] == cycle["id"]):    # line 228
                break
```

**Your Environment**

- Mypy version used: 0.782
- Mypy command-line flags: python -m mypy test\qtest\test_api.py --show-traceback
- Mypy configuration options from `setup.cfg`:
```
[mypy]
mypy_path = src
check_untyped_defs = True
disallow_any_generics = True
ignore_missing_imports = True
no_implicit_optional = True
show_error_codes = True
strict_equality = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
warn_unused_configs = True
no_implicit_reexport = True
```
- Python version used: Python 3.8.2 (Windows), Python 3.8.5-final0 (Ubuntu)
- Operating system and version: see last point

**Comment by hauntsaninja** [comment]
I believe this is fixed on master, could you confirm?

**Comment by marincandenza** [comment]
> I believe this is fixed on master, could you confirm?

I tried several clones but no pip installation did succeed within 10 minutes under windows:

`python -m pip install -U git+git://github.com/python/mypy.git`

**Comment by gvanrossum** [comment]
I see no reason why the fix for this issue could be platform dependent, so I think your installation problems are separate. For more help please use Gitter.
