### ISSUE TITLE
When using self in Enum types, type of self.value is used instead of the Enum type

### ISSUE THREAD

**Issue by levsa** [python/mypy#9520]
**Bug Report**

When using `self` to refer to an enum in an Enum class, type of `self.ENUM_MEMBER` becomes type of `self.value` instead.

**To Reproduce**

```python
from enum import Enum

from typing import Sequence


class Order(Enum):
    FIRST = 1
    SECOND = 2

    @property
    def all(self) -> Sequence['Order']:
        return [self.FIRST, self.SECOND]


print(Order.FIRST.all)
```

**Expected Behavior**

No mypy errors

**Actual Behavior**

```
file.py:12: error: List item 0 has incompatible type "int"; expected "Order"
file.py:12: error: List item 1 has incompatible type "int"; expected "Order"
```

**Your Environment**

- Mypy version used: mypy 0.782
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
```
ignore_missing_imports = True
strict_optional = False
plugins = sqlmypy
```
- Python version used: 3.7.2
- Operating system and version: macOS Mojave

**Comment by gvanrossum** [comment]
You're supposed to write `Order.FIRST, Order.SECOND` instead of `self....`

**Comment by levsa** [comment]
Thanks for the quick response!
