### ISSUE TITLE
reveal_type(x) where x: Tuple[int, ...] doesn't show "..."

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#9522]
**Bug Report**

Using `reveal_type()` on a variable whose type is a variable-length tuple shows misleading output.

While it's different from the output for a fixed-length tuple (which shows `Tuple[builtins.int]`), it doesn't clearly indicate that the type is variable-length.

Note that with PEP 585 accepted, eventually we'll have to use `builtins.tuple` (or, I'd recomment, plain `tuple`) for both situations.

**To Reproduce**
```py
from typing import Tuple
a: Tuple[int, ...]
reveal_type(a)
```

**Expected Behavior**
```
t.py:3: note: Revealed type is 'builtins.tuple[builtins.int, ...]'
```
or
```
t.py:3: note: Revealed type is 'Tuple[builtins.int, ...]'
```

**Actual Behavior**
```
t.py:3: note: Revealed type is 'builtins.tuple[builtins.int]'
```

**Your Environment**

Master or 0.782, no flags.

**Comment by hauntsaninja** [comment]
It looks like mypy uses builtins.tuple as a homogenous tuple type: https://github.com/python/mypy/blob/b884a394b4406b647317668a28538821ca08c056/mypy/typeanal.py#L290 Seems possibly worrisome for transitioning to the PEP 585 world, eg #9459
