### ISSUE TITLE
attr.ib default support

### ISSUE THREAD

**Issue by ItayGoren** [python/mypy#9525]
**Questions and Help**

As documented here: https://mypy.readthedocs.io/en/stable/additional_features.html#id1
there is no current support for `attr.ib(default=...)`.
Is it planned to be supported?
A simple example is:
```
from typing import Optional

import attr

@attr.s
class A:
    x: int = attr.ib(default=0)


def f(val: Optional[int]) -> A:
    return A(val) 
```
Is there a quick fix i can use to satisfy mypy? I know i can use `A(cast(int, val))` but anyone that use my class would have to know it.

**Comment by euresti** [comment]
Hi.  The documentation talks about "default decorators". i.e.

```
>>> @attr.s
... class C(object):
...     x = attr.ib(default=1)
...     y = attr.ib()
...     @y.default
...     def _any_name_except_a_name_of_an_attribute(self):
...         return self.x + 1
```

The error in your code is that `val` is an `Optional[int]` but `x` isn't `Optional` so you can't pass it in.
