### ISSUE TITLE
Passing `Optional[int]` as parameter to `Type[Any]`

### ISSUE THREAD

**Issue by ItayGoren** [python/mypy#9526]
**Bug Report**
I'm tying to run the following simple code
```python
from typing import Any, Type, Optional

def f(x: int, t: Type[Any]) -> None:
    pass

f(3, Optional[int])
```
using `mypy my_file.py`
and get the following error: `error: Argument 2 to "f" has incompatible type "object"; expected "Type[Any]"`

I expect `Optional[int]` to be a type and hence be accepted by the function.
The code work when calling `f(3. int)`. So I assume it something to do with the type of `Optional`. I see that its type is `typing._GenericAlias` but it looks like mypy doesn't recognise this type.

What am I missing and how can I make it work?
Thanks

**Your Environment**
- Mypy version used: 0.782
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3,8
- Operating system and version: mac

**Comment by gvanrossum** [comment]
`Type[]` indicates a class object is expected. `Optional[int]` is not a class object, it's a special form.

For more info, please use Gitter.
