### ISSUE TITLE
Make the stub generator official

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#953]
The stub generator is pretty useful, but it's undocumented and a little rough around the edges. 

Some possible things to do:
- Add script such as `mypy-stubgen` that is installed automatically and has help etc.
- Document the stub generator.
- Maybe even give a pointer to the stub generator when mypy can't find a module (#952).
- Do more testing and polishing.
- Add support for generating stubs for Python 2 C extension modules.

We should create separate issues at least for the bigger tasks here.

The stub generator can be currently run as `python3 -m mypy.stubgen`.

**Comment by ilevkivskyi** [comment]
OK, it is already official.
