### ISSUE TITLE
Ignore existing errors for gradual MyPy integration into project

### ISSUE THREAD

**Issue by dbalabka** [python/mypy#9540]
**Feature**

It would be helpful to have the possibility to ignore all existing errors while integrating MyPy into a new project. All existing errors might be saved into “baseline” file which might be stored in the repository.

**Pitch**

It will bring the following advantages:
1. Integrate MyPy immediately into existing project w/o fixing of all errors, but check a new code
2. Upgrade MyPy to newer version immediately w/o fixing existing code and check a new code

References:
1. https://phpstan.org/user-guide/baseline
2. https://psalm.dev/running_psalm/dealing_with_code_issues/

**Comment by JukkaL** [comment]
This seems out of scope for mypy, and better achieved with a separate tool. One option would be to write a script to add `# type: ignore` comments  that ignore existing errors based on the error code. This would be my recommended approach if there aren't too many errors. 

Another option would be to use a wrapper script that filters the output of mypy and removes errors that aren't relevant.

If such tools were available, we could link to them in the mypy documentation.

**Comment by dbalabka** [comment]
@JukkaL could you please elaborate more about why my proposal can not fit into MyPy project's goals and plans?
Are you suggesting to use [plugins API](https://mypy.readthedocs.io/en/stable/extending_mypy.html?highlight=plugin#current-list-of-plugin-hooks) to extend MyPy functionality in this case?

> One option would be to write a script to add # type: ignore comments that ignore existing errors based on the error code.
> Another option would be to use a wrapper script that filters the output of mypy and removes errors that aren't relevant.

I'm going to integrate MyPy into CI/CD pipeline in multiple projects and would like to have jUnit report which represents the correct state of ignored errors. Probably, the first option might fit my needs.

**Comment by KotlinIsland** [comment]
FYI basedmypy supports baseline https://github.com/KotlinIsland/basedmypy
https://pypi.org/project/basedmypy/

**Comment by orsinium** [comment]
I've just released a tool that solves exactly this. It's not a fork of mypy but rather a separate tool that filters the mypy output.

https://github.com/orsinium-labs/mypy-baseline

**Comment by AndreiMiculita** [comment]
Good tool! But ideally it should also support running in an IDE (i.e. via `dmypy`).

**Comment by orsinium** [comment]
You can add `alias dmypy="mypy | mypy-baseline filter"` into your `.bashrc`.

https://linuxize.com/post/how-to-create-bash-aliases/
