### ISSUE TITLE
Config setting strict_optional overrides no_implicit_optional

### ISSUE THREAD

**Issue by ErikssonM** [python/mypy#9546]
I recently got into the following situation where I wanted to disable implicit optional for a project where we are successively implementing type hinting. Minimal reproduction: 

main.py:

    def main(x: int = None) -> Optional[int]:
        print(x)
        return x

mypy.ini

    [mypy]
    no_implicit_optional = True
    no_strict_optional = True

With `no_implicit_optional = True` I expected `x: int = None` to produce an error, but it seems `no_strict_optional = True` consumes the error. (Removing `no_strict_optional` produces the error).

After digging through the docs I realise that this behaviour is somewhat by design (see: [Disabling strict optional checking](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#no-strict-optional)).

**Solution**
This behaviour could be noted in the [config file](https://mypy.readthedocs.io/en/stable/config_file.html) and [command line](https://mypy.readthedocs.io/en/stable/command_line.html) documentation entries for `no_implicit_optional`.

Is this a good idea, or should it be reported as a bug instead?

**Comment by gvanrossum** [comment]
It's definitely by design. Unless you're ready to provide a PR with a doc fix now I recommend closing this issue (most doc improvements don't need issues, people can just submit PRs).

**Comment by ErikssonM** [comment]
Okay, I suspected that would be the case. I'll close the issue for now and make a PR this week.
