### ISSUE TITLE
Error when trying to set __name__ of a partially applied function

### ISSUE THREAD

**Issue by korommatyi** [python/mypy#9556]
**Bug Report**

When setting the `__name__` attribute of a partially applied function, `mypy` complains that `"partial[int]" has no attribute "__name__"`.

**To Reproduce**

Running `mypy` on a file with the following code

```python
from functools import partial

f = partial(int, base=2)
f.__name__ = 'int_base_2'
```

results in

```
tmp.py:4: error: "partial[int]" has no attribute "__name__"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: `0.782`
- Mypy command-line flags: nothing
- Mypy configuration options from `mypy.ini` (and other config files): nothing
- Python version used: `3.7.8`
- Operating system and version: MacOS 10.15.6

**Comment by gvanrossum** [comment]
That sounds like a typeshed issue.
