### ISSUE TITLE
Incorrect redundant cast warning in lambda

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#9568]
With a `cast()` in a lambda, `--warn-redundant-cast` tells me to remove the cast, but then I get a different error if I actually do so. This is a regression in 0.790.

```
$ cat tmp/matchcast.py 
from typing import cast, Match, Pattern


def _get_nodes(key: str, rgx: Pattern[str]) -> None:
    matches = rgx.fullmatch(key)
    if matches is None:
        return

    sorted(
        matches.groupdict().items(),
        key=lambda g: cast(Match[str], matches).start(g[0]),
    )
$ mypy --warn-redundant-casts tmp/matchcast.py 
tmp/matchcast.py:11: error: Redundant cast to "Match[str]"
Found 1 error in 1 file (checked 1 source file)
```
And if I remove the cast:
```
$ mypy --warn-redundant-casts tmp/matchcast.py 
tmp/matchcast.py:11: error: Item "None" of "Optional[Match[str]]" has no attribute "start"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: `--warn-redundant-casts`
- Python version used: 3.6
- Operating system and version: Ubuntu

**Comment by hauntsaninja** [comment]
(Aliasing will probably work as a workaround)

**Comment by hauntsaninja** [comment]
mypy_primer bisects it to #8965 , I assume it's triggered by the typeshed change to `sorted`. There's probably some relation to #2608 as well

**Comment by hauntsaninja** [comment]
https://github.com/python/mypy/pull/16407 will make this work if you remove the cast
