### ISSUE TITLE
Generate warnings for redundant casts

### ISSUE THREAD

**Issue by jhance** [python/mypy#958]
If we visit `cast(x, T)` and the inferred type of `x` is a subtype of `T` then we should emit a warning. Unnecessary casts are bad casts.

There should also be a way to make this an error instead of a warning (for example, so we can enforce that we don't have any unnecessary casts in the mypy codebase).

**Comment by JukkaL** [comment]
This sounds like a great idea -- other than the fact that mypy currently doesn't distinguish between warnings and errors :-/ 

I wonder how other languages with casts do this? 

One potential issue is that if people use different tools to analyze the same code, these tools might have slightly different type inference capabilities and people may need casts to silence errors generated by some tools. I guess using `# type: ignore` is reasonable for cases like this, or maybe it should be possible to either enable/disable all warnings or individual categories of warnings (similar to `flake8` lets silence some warnings, for example).

**Comment by jhance** [comment]
In that case we should implement some feature that allows us to create types of warnings and emit them.

**Comment by JukkaL** [comment]
I added #962 for adding support for warnings.

**Comment by rwbarton** [comment]
> One potential issue is that if people use different tools to analyze the same code, these tools might have slightly different type inference capabilities and people may need casts to silence errors generated by some tools.

Or (moving my comment from #1470) we need to type check the same program in multiple configurations, such as python versions or versions of dependencies.

A special case which mypy can handle itself with some extra care is type checking generic functions with type variables with value restrictions, which are type checked once for each combination of legal values; a cast might be needed when specializing `AnyStr` to `bytes` but not `str`, for example.
