### ISSUE TITLE
removed analysis.py is still used in ./mypyc/transform/uninit.py

### ISSUE THREAD

**Issue by doko42** [python/mypy#9584]
seen when trying to generate manual pages with 0.790 and python3.9:

I: pybuild base:217: /usr/bin/python3.9 setup.py build 
Traceback (most recent call last):
  File "/packages/tmp/mypy-0.790/setup.py", line 144, in <module>
    from mypyc.build import mypycify
  File "/packages/tmp/mypy-0.790/mypyc/build.py", line 43, in <module>
    from mypyc.codegen import emitmodule
  File "/packages/tmp/mypy-0.790/mypyc/codegen/emitmodule.py", line 41, in <module>
    from mypyc.transform.uninit import insert_uninit_checks
  File "/packages/tmp/mypy-0.790/mypyc/transform/uninit.py", line 5, in <module>
    from mypyc.analysis.dataflow import (
ModuleNotFoundError: No module named 'mypyc.analysis'

apparently the analysis module was removed, however mypyc/transform/uninit.py still uses it

**Comment by hauntsaninja** [comment]
https://github.com/python/mypy/tree/master/mypyc/analysis still exists
I can't repro with `python3.9 setup.py build` on master, so closing. Feel free to reopen with more details :-)

**Comment by JelleZijlstra** [comment]
I haven't tried to repro this, but noticed that `mypyc.analysis` is missing from `setup.py`, so I submitted a PR to fix it.

**Comment by doko42** [comment]
re-adding this module lets the build continue, and then it fails with (building from the release tarball):

mypy/fastparse.py:1260: error: "ExtSlice" has no attribute "dims"
mypy/fastparse.py:1264: error: "Index" has no attribute "value"

**Comment by TH3CHARLie** [comment]
> re-adding this module lets the build continue, and then it fails with (building from the release tarball):
> 
> mypy/fastparse.py:1260: error: "ExtSlice" has no attribute "dims"
> mypy/fastparse.py:1264: error: "Index" has no attribute "value"

I think these errors are not related to the PR which closes this issue, these failures, I guess, are related to typeshed, maybe @hauntsaninja has some insight on this.

**Comment by hauntsaninja** [comment]
I fixed these last week in #9552 and #9562. If you pull those in, compiling with mypyc works.
(Note that 0.790 doesn't officially support 3.9 — https://mypy-lang.blogspot.com/2020/10/mypy-0790-released.html)
