### ISSUE TITLE
Can't cast from Fraction to int?

### ISSUE THREAD

**Issue by jvdwetering** [python/mypy#9588]
In mypy 0.770 the following typechecks:

```
from fractions import Fraction

def f(a: Fraction) -> int:
	return int(a)
```

But it raises the following error in mypy 0.790: "error: No overload variant of "int" matches argument type "Fraction""

If I replace the last line with `return int(float(a))`, it does typecheck.

Is this intended behaviour?

EDIT: The code above actually also doesn't compile on 0.770, see below on modified code that does work on 0.770 but gives an error on 0.790

**Comment by hauntsaninja** [comment]
This fails for me with 0.770 as well. I assume this is similar to #3186

**Comment by jvdwetering** [comment]
My bad, I accidentally had it ignoring the error in my 0.770 installation. But similar code I had in a more complicated code base did parse with 0.770, but started to raise errors when I upgraded mypy to 0.790 (even though I did not change anything about the codebase).

And yeah, this definitely looks to be related to #3186.

**Comment by hauntsaninja** [comment]
Regressions are typically easier to fix than features, so if you found the failure that would be useful. Could be related to https://github.com/python/typeshed/pull/4401 if that made it into the release

**Comment by jvdwetering** [comment]
That makes sense. So now the remaining problem is that int() should really know how to deal with a Fraction, right?

**Comment by hauntsaninja** [comment]
Yeah. From a glance, I'm not actually sure how this is even accomplished in CPython since Fraction doesn't have `__int__`, but will take a look later.

**Comment by hauntsaninja** [comment]
Here you go, this should fix things: https://github.com/python/typeshed/pull/4665
