### ISSUE TITLE
Returning Any from function declared to return object

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#9590]
Minimum test case:
```
[case testNoReturnAny]
# flags: --warn-return-any
import itertools
from typing import Any
things: Any = ()
for a, b in itertools.groupby(things, key=lambda e: e):
    pass
[builtins fixtures/tuple.pyi]
```

Mypy outputs:
`error: Returning Any from function declared to return "object"  [no-any-return]`

But, the error disappears if I change the code to:
```
k = lambda e: e
for a, b in itertools.groupby(things, key=k):
```

Despite there being no more or less typing information here.

**Comment by alanhdu** [comment]
We are also running into this when upgrading from mypy 0.782 to 0.790. It seems that `lambda`s now have `no-any-return` applied to them, which can lead to a bunch of errors with `--check-untyped-defs`.

**Comment by hauntsaninja** [comment]
The original issue reproes for me on v0.782 (and older), which suggests you're seeing something slightly different. Regressions are often easier to fix (if it is a regression), so would be useful if you could post a minimal repro of what you're seeing.

**Comment by alanhdu** [comment]
Split off into https://github.com/python/mypy/issues/9656.

**Comment by Dreamsorcerer** [comment]
I had a little dig through the code, and have found that the behaviour forks in `visit_lambda_expr()`:
https://github.com/python/mypy/blob/master/mypy/checkexpr.py#L3487

When it evaluates the lambda in the second form (i.e. assigned to a variable), `inferred_type` is `None`, but when used inline it appears as `def (<Erased>) -> <Erased>`. The warning is then only triggered in the `else` block, so does not occur in the second form.

**Comment by ilevkivskyi** [comment]
FWIW this works on current master (due to special-casing of `object` for this error).
