### ISSUE TITLE
Support PEP 604 - union types as X | Y

### ISSUE THREAD

**Issue by cdce8p** [python/mypy#9610]
**Feature**
Add support for [PEP 604](https://www.python.org/dev/peps/pep-0604/) to mypy. Since it has been officially accepted, should mypy add support for `X | Y` now? The syntax won't change anymore, is backwards compatible and there is an existing implementation https://github.com/pprados/mypy/tree/PEP604

**Pitch**
Adding this now would allow projects to already take advantage of the new syntax for type checking when using  
`from __future__ import annotations`.

**Comment by JelleZijlstra** [comment]
We should definitely add support, and it's great there's already an implementation by @pprados. Looks like this feature will be available only in 3.10, so there's no great hurry. I'm guessing we'll also need typeshed changes to add `type.__or__`.

**Comment by cdce8p** [comment]
@JelleZijlstra That's not entirely correct. Although `type.__or__` will only be added in `3.10`, `X | Y` for typing is backwards compatible. The AST parser already knows how to handle it. I did some tests with the original implementation. Type comments work without issue. For type annotations `from __future__ import annotations` is necessary [PEP 563](https://www.python.org/dev/peps/pep-0563/).
```py
from __future__ import annotations

t1: str | None = "Hello World"
t2 = "Hello World"  # type: str | None
```

What doesn't work are type aliases. The following would cause a type error:
```py
from __future__ import annotations

T1 = str | None  # TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
d: T1 = "Hello World"
```

**Comment by hauntsaninja** [comment]
@cdce8p it occurred to me that `isinstance(x, int | str)` won't yet work. As Jelle mentioned, that'll probably require typeshed changes, but thought I'd flag in case you want to try getting that working :-)

**Comment by cdce8p** [comment]
@hauntsaninja Thanks for letting me know. To be honest, I just wanted to replace `Optional` 😅
Although with the PR now finished, the Typeshed changes should be all to fully support PEP604 once 3.10 is released (if I didn't miss anything)

**Comment by hauntsaninja** [comment]
Would you be up for making the needed changes to typeshed / adding a test to mypy with an `isinstance` check (with `--python-version 3.10`, of course)? (no rush, just at some point in the next year 😊)

**Comment by cdce8p** [comment]
I can try. No promises :)
At the moment I'm still waiting for a review on open Typeshed PR. Would you mind taking a look? I don't seem to get any new responses. https://github.com/python/typeshed/pull/4752

**Comment by matejcik** [comment]
> What doesn't work are type aliases.

are type aliases _supposed to_ work? ISTM from reading PEP0604 that they are, but mypy is still failing on them

**Comment by JelleZijlstra** [comment]
@matejcik yes, they should work (always in stubs and at runtime in Python >3.10). If they don't, that's a bug in mypy.

**Comment by cdce8p** [comment]
Runtime uses of the PEP 604 aren't supported by `mypy` yet, see: #9880
