### ISSUE TITLE
[mypyc] support of `@final` types

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#9612]
**Bug Report**

I am trying to compile a module with `@final` types.
This does not seem possible at the moment with `mypyc`.

Actual source: https://github.com/dry-python/returns/blob/master/returns/result.py#L312

**To Reproduce**

```python
from typing_extensions import final


class Base(object):
    """Can be sub-classed."""


@final
class Child(Base):
    """Final instance."""
```

When `mypyc` is used on top of this code, this happens:

```
» mypyc ex.py
ex.py:9: error: Non-extension classes may not inherit from extension classes
```

As I understand, `mypyc` treats `@final` as a regular decorator and then makes `Child` a non-exntesion class.
And this does not seem correct to me. 

**Expected Behavior**

I would expect this code to compile without any warnings.
And `@final` should be treated the same way `mypy` does with regular `python` code.

- Mypy version used: `0.790`

**Comment by jairov4** [comment]
still happening in 1.0.9
even I think it would be benefical for codegen to apply optimization
