### ISSUE TITLE
Can't cast to generic list type

### ISSUE THREAD

**Issue by Ver1Sus** [python/mypy#9622]
I try to create Object or List of Objects (depending on the different situations), using the generic types, but mypy throws error that function can't return the List of Objects

Here some code to reproduce what I mean:
```python
from typing import List, TypeVar, Type, cast, Union


class Stuff:
    pass


T = TypeVar("T", bound=Stuff)


def foo(stuff: Type[T]) -> T:
    if stuff.mro()[0] == list:
        model = stuff.__args__[0]  # type: ignore
        return cast(T, [model()])
    return stuff()


stuff = foo(Stuff)
stuff_list = foo(List[Stuff])

reveal_type(stuff_list)
```

However, this is List of Stuff)

```bash
$ mypy -p list_type --strict
list_type.py:19: error: Value of type variable "T" of "foo" cannot be "List[Stuff]"
list_type.py:21: note: Revealed type is 'builtins.list*[core.list_type.Stuff*]'
```

**Expected Behavior**

I got a working solution, by adding new generic type, bounded to List of Stuff
```python
from typing import List, TypeVar, Type, cast, Union


class Stuff:
    pass


T = TypeVar("T", bound=Stuff)
L = TypeVar("L", bound=List[Stuff])


def foo(stuff: Union[Type[T], Type[L]]) -> Union[T, L]:
    if stuff.mro()[0] == list:
        model = stuff.__args__[0]  # type: ignore
        return cast(L, [model()])
    return stuff()


stuff: Stuff = foo(Stuff)
stuff_list: List[Stuff] = foo(List[Stuff])

reveal_type(stuff_list)
```

But, why mypy think that `foo()` from the first example cannot return the List of Stuff's, even though it does?)

- Mypy version used: 0.790
- Mypy command-line flags: --strict
- Mypy configuration options from `mypy.ini` (and other config files): no
- Python version used: 3.7.5 
- Operating system and version: Ubuntu 18.04.3 LTS (also try on docker python:3.7-stretch)

**Comment by hauntsaninja** [comment]
Because you've bounded your TypeVar by Stuff, and List[Stuff] is not a Stuff. For more help, ask on Gitter
