### ISSUE TITLE
Callable with a concrete subtype as a parameter don’t check properly in higher order function

### ISSUE THREAD

**Issue by amosson** [python/mypy#9639]
**Bug Report**

I would expect Callable[[Derived], None] would be a subtype of Callable[[Base], None] and compatible in a higher order function.  

**To Reproduce**
```
from typing import Callable

class Base:
    pass

class Derived(Base):
    pass

def first_order(b: Base) -> None:
    pass

b = Base()
d = Derived()

first_order(b)
first_order(d)

def higher_order(f: Callable[[Base], None]) -> None:
    pass

def f(d: Derived) -> None:
    pass

higher_order(f)
```
**Expected Behavior**

Should type check.

(Write what you thought would happen.)

**Actual Behavior**
```

$mypy mypy_tests.py 
mypy_tests.py:27: error: Argument 1 to "higher_order" has incompatible type "Callable[[Derived], None]"; expected "Callable[[Base], None]"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

```
$ mypy --version
mypy 0.790
$ python --version
Python 3.8.2
```

**Comment by amosson** [comment]
May be same issue as #8718 - in that case the issue is surfaced via a TypeVar

**Comment by JelleZijlstra** [comment]
This is expected behavior. `higher_order` is allowed to call `f(Base())`, but `f()` only accepts `Derived`. This is why function argument types are contravariant.
