### ISSUE TITLE
Mypy much slower under Python 3.9

### ISSUE THREAD

**Issue by kojiromike** [python/mypy#9669]
**Bug Report**

Running mypy runs orders of magnitude slower on Python 3.9 than it had run on 3.8.

**To Reproduce**

Here's the script I used to gather the results reproducibly:

```
#!/bin/sh

echo 'Testing mypy performance under python 3.8 and 3.9.'

echo 'Setup:'

set -x
export MYPY_CACHE_DIR MYPY_NO_INCREMENTAL PYTHONDONTWRITEBYTECODE
MYPY_CACHE_DIR=/dev/null
MYPY_NO_INCREMENTAL=1
PYTHONDONTWRITEBYTECODE=1

python3.8 -m mypy --version
python3.9 -m mypy --version
uname -a
set +x


echo 'Timing mypy with Python 3.8 (Control)'
timing38=$({ time python3.8 -m mypy . > /dev/null; } 2>&1 )
printf '%s\n\n\n' "$timing38"


echo 'Timing mypy with Python 3.9 (PEG parser)'
timing39PEG=$({ time python3.9 -m mypy . > /dev/null; } 2>&1 )
printf '%s\n\n\n' "$timing39PEG"


echo 'Timing mypy with Python 3.9 (LL parser)'
timing39LL=$({ time python3.9 -X oldparser -m mypy . > /dev/null; } 2>&1 )
printf '%s\n\n\n' "$timing39LL"
```

**Expected Behavior**

I expected mypy to run in about the same amount of time in Python 3.9 as it had in 3.8. When it took a long time, I thought maybe it was something about the new parser.

**Actual Behavior**

```
Testing mypy performance under python 3.8 and 3.9.
Timing mypy with Python 3.8 (Control)

real    0m7.167s
user    0m6.629s
sys     0m0.483s


Timing mypy with Python 3.9 (PEG parser)

real    0m26.106s
user    0m25.579s
sys     0m0.484s


Timing mypy with Python 3.9 (LL parser)

real    0m27.758s
user    0m26.339s
sys     0m0.538s
```

**Your Environment**

I originally discovered the problem on a particular Django-based project I'm working on, which took about 11 minutes in 3.9 vs 90 seconds in 3.8 to return mypy results on 36 Python files. (Subsequent runs using the cache took seconds.) The results above are from running in a local clone of [Django](https://github.com/django/django) at commit f06beea929. I used Django so others could reproduce the results, since I can't share the other project right now. I ran mypy with caching disabled, three times. I ran using python 3.8, 3.9, and again with 3.9 with the LL parser.

Mypy is invoked as in the script above, just in case I write something wrong here:

- Mypy version used: 0.790 (for both python3.8 and 3.9)
- Mypy command-line flags: Just `.`
- Mypy configuration options from the environment:
  - `MYPY_CACHE_DIR=/dev/null`
  - `MYPY_NO_INCREMENTAL=1`
- Python version used: 3.8 and 3.9 (Also with `PYTHONDONTWRITEBYTECODE=1` in the environment.)
- Operating system and version: macOS Catalina 10.15.7, using pyenv and homebrew to install and manage python versions.

**Comment by hauntsaninja** [comment]
mypy does not yet officially support 3.9. This also means we don't publish mypyc-compiled mypy wheels. If you need speed, you'll need to run with 3.8 or wait for the next release :-)

**Comment by kojiromike** [comment]
@hauntsaninja that's fine, this isn't a support request, but I thought it would be valuable to report it. Thank you for the prompt reply!  :)

**Comment by hauntsaninja** [comment]
And thank you for the detailed report! I appreciate that a speed difference like this is an unfortunate and mysterious thing to run into for users; for the most part mypyc is just an implementation detail of mypy.
