### ISSUE TITLE
Running mypy on the current directory without some OS-specific stuff

### ISSUE THREAD

**Issue by Holt59** [python/mypy#9677]
**Feature**

Have a way to pass the current directory to `mypy`. I can run `mypy dir`, but `mypy .` fails because `.` is not a valid Python package name.

**Pitch**

Would be very useful to have generic CI commands. I'm currently figuring out how I can pass the full path to the current directory in an OS-dependent manner. Other tools (flake8, black, ...) have no issue with "."

**Comment by hauntsaninja** [comment]
Note that `mypy .` does work, it just usually needs to be run in the folder above your package (or maybe you have a stray `__init__.py`). That said, I do agree that we should make this work; see my comment at https://github.com/python/mypy/issues/8726#issuecomment-716892078 for more
