### ISSUE TITLE
Continue analysis after parse errors

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#969]
As continuation of #966, mypy should continue processing additional modules even if there is a parse error in one module. Currently mypy stops at a parse error.

Any module that can't be parsed should be considered to be the equivalent of having type `Any` elsewhere in the program.

**Comment by JukkaL** [comment]
As the parser is now in better shape this is no longer as urgent as this used to be.

**Comment by hauntsaninja** [comment]
While blocking errors are a bad experience, they're fairly rare these days
