### ISSUE TITLE
Refactor[Rename]: anal_type to analyze_type (and generally fully spell-out objects with short-form 'anal' as part of the name)

### ISSUE THREAD

**Issue by jp-larose** [python/mypy#9692]
**Feature**

I understand that we generally prefer to type less.  However, it would better serve external users (like me) to spell out the names of classes, methods, functions, etc., especially for public interfaces like the plug-in subsystem.  

In this particular case, the abbreviation 'anal' more readily evokes the anatomical part, rather than the intended 'analyze' (and variants).

**Pitch**

Deprecate the short forms of the names in favour of the long forms of the names.
Here are a few I have come across:

- `mypy.plugin.SemanticAnalyzerPluginInterface.anal_type`  (along with any implementations)
- files: mypy\semanal*.py
- file: mypy\typeanal.py

It's not that I find the term or the evocations of the term offensive.  If anything, I had a childish chuckle over it.  It's just that I found the cognitive shift quite jarring.  I imagine I'm not the only one.

**Comment by hauntsaninja** [comment]
This seems unnecessarily disruptive to all the plugins that already exist and not a big enough deal to bother maintaining support for two sets of names.
