### ISSUE TITLE
Type narrowing fails on generic type except if it's in union

### ISSUE THREAD

**Issue by Phlogistique** [python/mypy#9704]
**Bug Report**

When guarding with `isinstance` on a generic class, mypy fails narrowing to `NoReturn`

**To Reproduce**

Run mypy on this file:
```python
from typing import NoReturn, TypeVar, Generic, Union

T = TypeVar("T")


def assert_never(x: NoReturn) -> NoReturn:
    assert False


class Foo(Generic[T]):
    ...


class Bar:
    ...


def foo(x: Foo[T]) -> None:
    if isinstance(x, Foo):
        return
    assert_never(x)

def bar(x: Bar) -> None:
    if isinstance(x, Bar):
        return
    assert_never(x)

def foobar(x: Union[Foo[T], Bar]) -> None:
    if isinstance(x, Foo):
        return
    if isinstance(x, Bar):
        return
    assert_never(x)

def barfoo(x: Union[Foo[T], Bar]) -> None:
    if isinstance(x, Bar):
        return
    if isinstance(x, Foo):
        return
    assert_never(x)
```

**Expected Behavior**

`foo`, `bar`, `foobar` and `barfoo` should all type check.
 
**Actual Behavior**

`bar` and `foobar` type check, but `foo` and `barfoo` fail to type check with the following message:

```
test.py:21: error: Argument 1 to "assert_never" has incompatible type "Foo[T]"; expected "NoReturn"
test.py:43: error: Argument 1 to "assert_never" has incompatible type "Foo[T]"; expected "NoReturn"
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: Reproduced with 0.750 and master
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.7
- Operating system and version: macOS High Sierra 10.13.6

**Comment by A5rocks** [comment]
By the way, this works on mypy's master branch now.

**Comment by Phlogistique** [comment]
Yay! Thanks.

Should I close the ticket now or wait for the next release?

**Comment by A5rocks** [comment]
I would close the ticket now while you remember, but up to you!
