### ISSUE TITLE
The use of `six.raise_from()` causes false positive "missing return statement"

### ISSUE THREAD

**Issue by webknjaz** [python/mypy#9717]
**Bug Report**

I believe mypy is getting confused when a helper function that always raises an exception gets called.

**To Reproduce**

```python
from six import raise_from

def func():  # type: () -> SomeType
    try:
        return some_call()
    except SomeException as exc:
        raise_from(RuntimeError(str(exc)), exc)
```

**Expected Behavior**

No error reported.

**Actual Behavior**

mypy says "Missing return statement".

There's a workaround for this: if I prepend the `raise_from()` call with either of `raise` or `return`, the error will disappear.

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: just the target file path
- Mypy configuration options from `mypy.ini` (and other config files): global `follow_imports=skip` and `ignore_missing_imports=True` for the six library
- Python version used: 3.9.0
- Operating system and version: Gentoo Linux (I'm pretty sure this is irrelevant though)

N.B. I'm using a vendored version of six rather than installed separately.

**Comment by JukkaL** [comment]
This should work as expected, as long as you are using typeshed stubs for six.

> I'm using a vendored version of six rather than installed separately.

This might explain it. Perhaps mypy is analyzing the implementation of six instead of typeshed stubs? You can verify this by using `-v` to run mypy. If you are using the implementation and it's missing type annotations, the behavior you are seeing is expected.

**Comment by hauntsaninja** [comment]
Closing based on Jukka's comment and a lack of response

**Comment by webknjaz** [comment]
Oh, sorry. This got lost among my notifications. I think Jukka is correct in his assumption.
