### ISSUE TITLE
reveal_type hides errors

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#9719]
```py
a = 2
reveal_type(a)  # Revealed type is 'builtins.int'
a = "asdf"
```
```
note: Revealed type is 'builtins.int'
```

**Comment by hauntsaninja** [comment]
I can't repro

**Comment by KotlinIsland** [comment]
@hauntsaninja I can reproduce:
![image](https://user-images.githubusercontent.com/65446343/99200926-0d164980-27f4-11eb-8e49-c0d302b33e7f.png)

**Comment by hauntsaninja** [comment]
Maybe try sharing a repro from https://mypy-play.net?
Obviously as the filer of this issue you can repro; repeating that information doesn't help. On the other hand, filling out the information the issue template asks for, e.g. like your mypy version, does.

**Comment by hauntsaninja** [comment]
E.g. https://mypy-play.net/?mypy=latest&python=3.9&flags=strict&gist=07840bf89fe7ef07e4e3521d1a3708a9 shows that I can't reproduce the error based on what you've posted so far

**Comment by KotlinIsland** [comment]
Oh sorry, my bad. I forgot I had a mypy.ini, it's `--allow-redefinition`

**Comment by KotlinIsland** [comment]
mypy playground doesn't have option for allow-redefinition?

**Comment by hauntsaninja** [comment]
If you have `--allow-redefinition` then your code isn't incorrect. The behaviour changes due to `reveal_type` (but substitute literally any use of `a`) because of https://github.com/python/mypy/issues/6963

**Comment by hauntsaninja** [comment]
Yusuke would probably happily accept a PR adding the option to mypy playground at https://github.com/ymyzk/mypy-playground/pulls :-)
