### ISSUE TITLE
Unsupported target for indexed assignment

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#9735]
With this code:
`AB_TESTS: Mapping[str, Union[Sequence[str], Sequence[int]]] = MappingProxyType({})`
or
`AB_TESTS: Mapping[str, Union[Sequence[str], Sequence[int]]] = {}`

I get:
`error: Unsupported target for indexed assignment ("Mapping[str, Union[Sequence[str], Sequence[int]]]")  [index]`

However, the error does not appear with:
`AB_TESTS: Dict[str, Union[Sequence[str], Sequence[int]]] = {}`

I don't see a reason for this error to occur, and am not sure what it is referring to as an 'indexed assignment'.

**Comment by Dreamsorcerer** [comment]
Nevermind, looked at the wrong line.

**Comment by codeeDrunk** [comment]
i have the same problem can you tell me how did you fixed this

**Comment by Dreamsorcerer** [comment]
As mentioned, I was looking at the wrong code. Error was probably simple when I looked at the correct code. Without any idea what your code is, I can't guess what your issue is.
