### ISSUE TITLE
error with double tuple assignment

### ISSUE THREAD

**Issue by d10genes** [python/mypy#974]
Not sure how to describe this with words so apologies if this has already been noted.

mypy has no problem checking `a = b = 1` or `a, b = 1, 2`, but chokes on

    c = a, b = 1, 2

with `KeyError: <mypy.nodes.TupleExpr object at 0x1017950b8>`. Full traceback is [here](https://gist.github.com/d10genes/4427eb29e68521a9b078).

**Comment by JukkaL** [comment]
Thanks for reporting this! This is clearly a bug in how mypy handles assignment statements.

**Comment by JukkaL** [comment]
The current workaround is to split the assignment into two or more assignment statements, for example:

```
c = 1, 2
a, b = c
```
