### ISSUE TITLE
@overload cannot be used with conditional "if TYPE_CHECKING"

### ISSUE THREAD

**Issue by blueyed** [python/mypy#9744]
**Bug Report**

The handling of `@overload` decorators happens in (code) blocks only, which makes it not find the implementation when using:
```python
from typing import overload
from typing import TYPE_CHECKING
from typing import Union


class K:
    if TYPE_CHECKING:
        @overload
        def foo(self, arg: int) -> int:
            ...

        @overload
        def foo(self, arg: str) -> str:
            ...

    def foo(self, arg: Union[int, str]) -> Union[int, str]:
        ...
```

```
t-overload.py:8: error: An overloaded function outside a stub file must have an implementation  [misc]
t-overload.py:16: error: Name 'foo' already defined on line 8  [no-redef]
Found 2 errors in 1 file (checked 1 source file)
```

I think it would be nice / feasible to merge `if TYPE_CHECKING` blocks maybe, so that the parser would handle it together?

mypy 0.800+dev.6e99a2db100d794b1bf900746470527cd03fce16

**Comment by davidatbu** [comment]
I'm curious, why would you like an `if TYPE_CHECKING` block shielding overloads? They are ignored by the runtime anyways.

**Comment by blueyed** [comment]
> I'm curious, why would you like an `if TYPE_CHECKING` block shielding overloads? They are ignored by the runtime anyways.

While it's just a dummy decorator I'd like to keep typing separate from runtime altogether.
Apart from that it just confused me initially until I've looked into how mypy parses/handles it, and was surprised to see that `if` blocks are considered to be separate in this regard, i.e. it looked like something that could/should get improved/fixed in mypy anyway.

**Comment by altendky** [comment]
I think this applies to my present issue as well.  I am exploring merging trio-stubs (from trio-typing) into Trio itself and the hints for `open_process()` and `run_process()` are platform dependent.

https://github.com/python-trio/trio-typing/blob/f32f17b0f242daf2d42407f383ca581d64b6c299/trio-stubs/__init__.pyi#L567-L682
https://github.com/python-trio/trio/blob/d890affa8fed3a49b616a8fd218f4fb928bd3002/trio/_subprocess.py#L279
https://github.com/python-trio/trio/blob/d890affa8fed3a49b616a8fd218f4fb928bd3002/trio/_subprocess.py#L419-L428

**Comment by hauntsaninja** [comment]
For your use case you could just put the whole stub in an `if TYPE_CHECKING` and add a dummy implementation to each `sys.platform` branch. And then put the real implementation in the `else` of the `if TYPE_CHECKING`

**Comment by altendky** [comment]
Thanks for the workaround.  I'll keep subscribed here in case there's a full fix.  `:]`

**Comment by cdce8p** [comment]
I opened a PR a while ago that would also fix this issue. Still waiting for a review though. #10712
Maybe you would be interested to take a look, @hauntsaninja?

**Comment by blueyed** [comment]
@cdce8p 
Thank you for fixing it!
I can confirm that it both fixes my example, and the actual use case I have at hand.

**Comment by cdce8p** [comment]
@blueyed Great to hear that! Unfortunately I'm still waiting for a review on the PR so no idea when it will get merged. I would be able to remove 300 lines in one file alone just from `overloads` I need to duplicate at the moment.

**Comment by cdce8p** [comment]
Sorry to bother you again @hauntsaninja. Do you have an idea who might be able to review it?
