### ISSUE TITLE
Need a way to ignore a missing attribute of a module

### ISSUE THREAD

**Issue by Hi-Angel** [python/mypy#9749]
**Feature**

A way to ignore a missing attribute of a module is needed.

**Pitch**

A testcase:
```python
 λ cat test.py
import pytest

def setup_module(_):
    pytest.conn = 'create connection'

def test_foo():
    print(pytest.conn)
 λ mypy test.py --check-untyped-defs
test.py:5: error: Module has no attribute "conn"
test.py:8: error: Module has no attribute "conn"
Found 2 errors in 1 file (checked 1 source file)
```

The usecase here is that pytest runs `setup_module`, and thus gets connection configured. This connection is assigned to variable `pytest.conn`, and then is used in hundreds of testcases. From POV of mypy the attribute does not exist. There needs to be some way to make mypy ignore checking on this particular attribute.

**Comment by Hi-Angel** [comment]
Please excuse me if there is already a workaround, but I only managed to find ones for the case of a missing attribute of a class, and they didn't work for module.

**Comment by hauntsaninja** [comment]
You could alias the missing symbol or type the module as an instance of a protocol. There isn't a naive way to tell mypy about some new monkeypatched attribute though
