### ISSUE TITLE
Recursive/forward cross-module type references

### ISSUE THREAD

**Issue by yang** [python/mypy#976]
I believe there is no way to specify recursive/forward cross-module type references, but wanted to confirm.  (edit: I realize this is a type hints spec question, not nec. a mypy one, though presently I just care about getting things to work in mypy)

I found a nasty approach that works with respect to typing.get_type_hints(), since it just appears to straight-up eval the string annotation, but I doubt this is the intention or anything meant to be supported by static type checkers:

```
def f(x: 'importlib.import_module("mymodule").MyType'): ...
```

**Comment by JukkaL** [comment]
Yeah, that isn't *supposed* to work but happens to work. Can you give a somewhat realistic example where something like that would be useful?

**Comment by yang** [comment]
A simple rough sketch:

visitor.py:

```
class Visitor:
  def visit(node: Node): ...
```

node.py:

```
class Node:
  def accept(visitor: Visitor): ...
```

**Comment by darjus** [comment]
Sorry, but I thought Python does not support circular imports.

**Comment by kirbyfan64** [comment]
@darjus It *kind of* does:

x.py:

```python
a = 1
import y
b = 2
```

y.py:

```python
import x
print x.a # 1
print x.b # AttributeError
```

**Comment by darjus** [comment]
Sorry, you're absolutely right @kirbyfan64 what i meant is this:

    ➜  recurse  ls *.py
    x.py y.py
    ➜  recurse  cat *.py


    # y.py
    import y
    
    class X:
    
        def __init__(self, m: y.Y):
            self._y = m


    # x.py
    import x
    
    class Y:
    
        def __init__(self, m: x.X):
            self._x = m


    ➜  recurse  python3 y.py
    Traceback (most recent call last):
      File "y.py", line 1, in <module>
        import x
      File "/Users/darjus/Documents/recurse/x.py", line 1, in <module>
        import y
      File "/Users/darjus/Documents/recurse/y.py", line 3, in <module>
        class Y:
      File "/Users/darjus/Documents/recurse/y.py", line 5, in Y
        def __init__(self, m: x.X):
    AttributeError: 'module' object has no attribute 'X'

**Comment by yang** [comment]
@darjus The example normally doesn't require recursive imports. The problem is that the type signatures would.

**Comment by JukkaL** [comment]
There are a few ways to work around the original issue.

First, you can use `import x` even if this introduces a circular import and use `x.ClassName` with string literal quoting. Perhaps this works for your use case? Example:

```
# x.py
import y
class X: pass
def f(y: 'y.Y') -> None: ...

# y.py 
import x
class Y: pass
def f(x: 'x.X') -> None: ...
```

Another way is to define ABCs for the related types in a third module z, and use these ABCs in annotations so you don't need to introduce circular imports at all. This isn't always easy to do, though. Simple example:

```
# z.py
from abc import ABCMeta
class XA(metaclass=ABCMeta): ...
class YA(metaclass=ABCMeta): ...

# x.py
from z import XA, YA

class X(XA): ...
def f(y: YA) -> None: ...

# y.py
from z import XA, YA
class Y(YA): ...
def f(x: XA) -> None: ...
```
