### ISSUE TITLE
can't refine Dict[str, str] with isinstance check

### ISSUE THREAD

**Issue by sbdchd** [python/mypy#9783]
**Bug Report**

Refining `x: Dict[Any, Any]` works via `isinstance(x, dict)`, but doesn't for `x: Dict[str, str]`

**To Reproduce**

```python
from typing import Dict, Any

z: Dict[str, str]
if not isinstance(z, dict):
    reveal_type(z) # note: Revealed type is 'builtins.dict[builtins.str, builtins.str]'

x: Dict[Any, Any]
if not isinstance(x, dict):
    reveal_type(x) # error: Statement is unreachable
```

**Expected Behavior**

`Dict[str, str]` would be refined such that `mypy` gives a `statement is unreachable` error

**Actual Behavior**

`Dict[str, str]` doesn't get refined

**Your Environment**

- Mypy version used: 0.7.9
- Mypy command-line flags: `--warn-unreachable`
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: `3.9`
- Operating system and version: linux

**Comment by AlexWaygood** [comment]
[Can't reproduce](https://mypy-play.net/?mypy=0.940&python=3.10&flags=warn-unreachable&gist=e6025fdf25a1e5d5edaa4f824709b3b0) on 0.940+
