### ISSUE TITLE
`==` Narrows the type of an Enum in an if-elif block when following an `is`

### ISSUE THREAD

**Issue by parsons-kyle-89** [python/mypy#9786]
`is` and `==` work strangely together when narrowing the type of an `Enum` in an if-elif block.  [It is known](https://github.com/python/mypy/issues/6366#issuecomment-673876383) that you need to use `is` rather than `==` to narrow the type of an `Enum`, but it seems if the `if` statement uses `is` then the `elif` can have `==` and still narrow the type of the variable.

**To Reproduce**
```
from enum import Enum

class Foo(Enum):
    A = 1
    B = 2
    C = 3

def f0(x: Foo) -> str:
    if x is Foo.A:
        return 'one'
    elif x == Foo.B:
        return 'two'
    elif x == Foo.C:
        return 'three'
    reveal_type(x)  # Not revealed by mypy as it apparently considers this line unreachable
```
This is compared to how have come to expect `==` to work with an enum where it will not narrow the type.

```
def f1(x: Foo) -> str:
    if x == Foo.A:
        return 'one'
    elif x == Foo.B:
        return 'two'
    elif x == Foo.C:
        return 'three'
    reveal_type(x)  # Revealed type is Foo
```
Interestingly this doesn't just occur when an `is` is used in the `if`.  It can occur in an `elif` and still "propogate" its narrowing ability to the following `==`'s.
```
def f2(x: Foo) -> str:
    if x == Foo.A:
        return 'one'
    elif x is Foo.B:
        return 'two'
    elif x == Foo.C:
        return 'three'
    reveal_type(x)  # Revealed type is Literal[Foo.A]
```

**Expected Behavior**

`==` would either narrow the type of an enum or not and it would not depend on whether or not it was preceded by an `is`.

**Actual Behavior**

`==` narrows the type of an enum only when it is preceded by an `is`.

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: none or `--strict` will both demonstrate this behavior
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]
disallow_any_decorated = True
disallow_any_explicit = True
disallow_any_generics = True
disallow_subclassing_any = True
disallow_untyped_defs = True
disallow_untyped_calls = True
disallow_incomplete_defs = True
disallow_untyped_decorators = True
```
- Python version used: 3.9.0
- Operating system and version: Ubuntu 20.04.1 LTS under WSL

**Comment by AlexWaygood** [comment]
Closing in favour of #10915, which is a newer issue but has more discussion attached to it.
