### ISSUE TITLE
Get the type of a var

### ISSUE THREAD

**Issue by wlf100220** [python/mypy#9788]
**Feature**
A similar feature in [typescript](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html)
```ts
const foo: number = 1
type Foo = typeof foo  // type Foo = number

function bar(x: string): void {

}

type Bar = typeof bar // type Bar = (x: string) => void
```

**Pitch**
The expected way in future python.
use the predefined method `type` is not possible because `type(foo)` returns string.
so we need to introduce an additinal method for example `typing.typeof`: 
```py
from typing import typeof
foo: int = 1
Foo = typeof(foo)  # equivalent to Foo = int

def bar(x: string) -> None :
    ...
Bar = typeof(bar)  # equivalent to Bar = Callable[[str], None]
```
or make `typing.Type` callable:
```py
from typing import Type
foo: int = 1
Foo = Type(foo)  # equivalent to Foo = int
```

**Comment by danr** [comment]
Why was this closed? Is there a way to do TypeScript's `typeof` in mypy?

**Comment by wlf100220** [comment]
@danr [I open anonther one here in python/typing repo](https://github.com/python/typing/issues/769)
