### ISSUE TITLE
[Question]A simple implementation of utility generic ReturnType not work in mypy

### ISSUE THREAD

**Issue by wlf100220** [python/mypy#9792]
**Questions and Help**

I don't know how mypy check Generic types under the hood. 
I've try to implement an generic type to return the return type of an Callable type:
This simple implementation is intended to suit a simple test case.
But it doesn't work. 

Could someone explain that? Than you very much!
```python3
import typing as t

T = t.TypeVar('T', bound=t.Callable)


class ReturnType(t.Generic[T]):
    def __class_getitem__(cls, item):
        return_type = item.__args__[-1]
        return return_type


C = t.Callable[..., t.List[int]]

assert ReturnType[C] == t.List[int]  # pass

foo: ReturnType[C] = [1, 2]  # error: Incompatible types in assignment (expression has type "List[int]", variable has type "ReturnType[Callable[..., List[int]]]")

```

**Comment by oremanj** [comment]
You can't define type transformations like this. You're defining ReturnType as a class that's generic in one parameter. Its `__class_getitem__` runs at runtime but mypy pays it no heed.

You might be able to support this sort of thing by creating a mypy plugin that uses the `get_type_analyze_hook`. But you can't do it just with code in the file you're type-checking.

**Comment by hauntsaninja** [comment]
Yup, remember that static type checkers will not run your code.

**Comment by wlf100220** [comment]
@oremanj @hauntsaninja Thank you!
