### ISSUE TITLE
Nested Protocol unexpected behavior

### ISSUE THREAD

**Issue by wlf100220** [python/mypy#9803]
**Bug Report**

Nested Protocol resolved uncorrectly.

**To Reproduce**

```python3
from typing import Protocol


class ProtoA(Protocol):
    a: int


class ProtoB(Protocol):
    b: int
    a: ProtoA


class A:
    a: int


class B:
    b: int
    a: A

a: ProtoA = A()  # pass
b: ProtoB = B()  # error 
# bug_nested_protocol.py:22: error: Incompatible types in assignment (expression has type "B", variable has type "ProtoB")
# bug_nested_protocol.py:22: note: Following member(s) of "B" have conflicts:
# bug_nested_protocol.py:22: note:     a: expected "ProtoA", got "A"
```

**Expected Behavior**

No error.
Because type A repect to Protocol A, and mypy tell me that too.

**Actual Behavior**
type `B` is not compitiple with type` ProtoB`

**Your Environment**

- Mypy version used: 0.79
- Mypy command-line flags: only `mypy file`
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.9
- Operating system and version: windows 10

**Comment by wlf100220** [comment]
Duplicate of #7041

**Comment by wlf100220** [comment]
how to solve this problem if I change the type of `B.a` to `List[ProtoA]`

```python3
from typing import Protocol, List


class ProtoA(Protocol):
    a: int


class ProtoB(Protocol):
    b: int

    @property  # change according to #7041
    def a(self)->List[ProtoA]:
        pass


class A:
    a: int


class B:
    b: int
    a: List[A]  # change here

a: ProtoA = A()  # pass
b: ProtoB = B()  # error
# typing_\bug_nested_protocol.py:25: error: Incompatible types in assignment (expression has type "B", variable has type "ProtoB")
# typing_\bug_nested_protocol.py:25: note: Following member(s) of "B" have conflicts:
# typing_\bug_nested_protocol.py:25: note:     a: expected "List[ProtoA]", got "List[A]"
```

**Comment by ethanhs** [comment]
The related problem occurs because `List` is invariant. If you replace `List` with `Sequence` then the code passes as expected. You may want to read https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance

**Comment by wlf100220** [comment]
@ethanhs 
thank you!
I should have read the common issues!
