### ISSUE TITLE
Feature request : compile type checking for protected attribute/method

### ISSUE THREAD

**Issue by idarous** [python/mypy#9808]
Hello,

is there any plan to support the check of a usage of a protected attribute/method during the compile type checking like TypeScript does https://www.typescriptlang.org/docs/handbook/classes.html#understanding-protected ?

It can be done using the `_` prefix usually used by the Python community in order to specify that a method or an attribute is protected like explained in the followings posts.

https://towardsdatascience.com/private-protected-attributes-in-python-demystified-once-and-for-all-9456d4e56414
https://towardsdatascience.com/private-protected-attributes-in-python-demystified-once-and-for-all-9456d4e56414
https://www.tutorialsteacher.com/python/public-private-protected-modifiers

Another in order to be retro compatible with other programs that use `_` in another way could be to add a new decorator named for example `protected`

We can have this kind of code

```python
class Employee:
    def __init__(self, sal):
        @protected
        self._salary=sal # protected attribute

e = Employee(2000)
print(e._salary)
# Throw an error when checking this code with mypy
```

**Comment by hauntsaninja** [comment]
Nope, no plans, consenting adults and all that. Such a feature is best discussed on the typing-sig mailing list or at https://github.com/python/typing
