### ISSUE TITLE
delayed staticmethod()

### ISSUE THREAD

**Issue by melassa** [python/mypy#9816]
**Bug Report**

**To Reproduce**

```
class A():
    def b():
        return 0
    x = b()
    b = staticmethod(b)
A().b()
```

**Expected Behavior**

No errors or ignorable errors for this working code.

**Actual Behavior**

Mypy output:

error: Method must have at least one argument
error: Incompatible types in assignment (expression has type " staticmethod", variable has type "Callable[[], Any]")
error: Attribute function "b" with type "Callable[[], Any]" does not accept self argument

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8
- Operating system and version: w7

**Comment by hauntsaninja** [comment]
As a workaround, you can do:
```
class A:
    def _b():  # type: ignore
        return 0
    b = staticmethod(_b)

A().b()
```
This will fix callers without them having to do anything. You'll still need to type ignore the "Method must have at least one argument", which seems reasonable to me. Somewhat generally, mypy doesn't do well with redefining things to have different types, so this might be the best you get.
