### ISSUE TITLE
Make Callable a valid base

### ISSUE THREAD

**Issue by PythonCoderAS** [python/mypy#9819]
**Bug Report**

`typing.Callable` is considered an invalid base class by stubtest, which should not be happening. Any class that has a `__call__` method should be a `Callable`. Per https://github.com/python/typeshed/pull/4832#issuecomment-747861050, it is completely possible to have such a class exist during runtime, so I think that Callable should be a valid base class.

**To Reproduce**

(Write your steps here:)

1. Make a class with a base class of `typing.Callable`
2. Run stubtest on it

**Expected Behavior**

The class should be marked as valid. Furthermore, during type checking, the resultant class can be used anywhere a `Callable` is expected.

**Actual Behavior**

Stubtest reports it as an error.

**Your Environment**

- Mypy version used: latest
- Mypy command-line flags: `--ignore-missing-stub --check-typeshed --custom-typeshed-dir . --whitelist tests/stubtest_whitelists/py3_common.txt --whitelist tests/stubtest_whitelists/py38.txt --ignore-unused-whitelist --whitelist tests/stubtest_whitelists/linux.txt --whitelist tests/stubtest_whitelists/linux-py38.txt --ignore-positional-only`
- Mypy configuration options from `mypy.ini` (and other config files): Official config of typeshed repo's tests.
- Python version used: 3.6 - 3.9
- Operating system and version: Ubuntu, Windows

**Comment by JelleZijlstra** [comment]
This isn't specific to stubtest; running mypy directly gives the same issue.

Instead of subclassing Callable it's probably better in general to override `__call__`.
