### ISSUE TITLE
Check function argument types inside another function

### ISSUE THREAD

**Issue by alicezou** [python/mypy#9824]
**Feature**
Hi, can we get error for this kind of code? Currently I am not getting anything.
```
def func2(lol: typing.Tuple[int, int]):
    print(lol)

def test2():
    func2(("gdp", 1))


test2()
```
**Pitch**

It can check function in another function. I believe this is useful because a lot of time, we want to extract a functionality into a function.

**Comment by hauntsaninja** [comment]
--check-untyped-defs
