### ISSUE TITLE
Optional with a test still think it could be None

### ISSUE THREAD

**Issue by assafmendelson** [python/mypy#9826]
**Bug Report**
Mypy mistakes an Optional for possibly being None even though there is an explicit test otherwise.

Sample code:

`
    
    from typing import Optional
    
    
    class Example(object):
        """
        Example class to show the mypy issue.
        It is a bit synthetic but should show the issue
        """
        def __init__(self):
            """
            Constructor, in it we setup a member to None
            """
            self.example_member: Optional[str] = None
    
        def override(self, v: str) -> None:
            assert v is not None
            self.example_member = v
    
        def _tester(self) -> bool:
            return self.example_member is not None
    
        def run_the_test(self) -> None:
            assert self._tester()
            print(self.example_member.startswith("some"))
`

**To Reproduce**
Run mypy with the following switches:
`
    mypy --follow-imports=error --disallow-untyped-calls --ignore-missing-imports example.py
`

**Expected Behavior**

The code is correct and should have no issues
**Actual Behavior**

I am getting An error:
`
    example.py:24: error: Item "None" of "Optional[str]" has no attribute "startswith"
`
**Your Environment**

- Mypy version used: mypy==0.790, mypy-extensions==0.4.3
- Mypy command-line flags: --follow-imports=error --disallow-untyped-calls --ignore-missing-imports
- Mypy configuration options from `mypy.ini` (and other config files): Non were changed
- Python version used: Python 3.6.8 (default, Nov 21 2019, 19:31:34), [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
- Operating system and version: centos8

**Comment by JelleZijlstra** [comment]
Mypy doesn't look inside methods to see how they might constrain their arguments. There is an active proposal to add a concept of "type guards" to the Python type system, which would support patterns like this. You'd still need a special annotation on the method, though.
