### ISSUE TITLE
Support option for type inference to default to immutable types when possible

### ISSUE THREAD

**Issue by justinaustin** [python/mypy#9829]
**Feature**

Add an option for mypy, maybe something like `--infer-immutable-when-possible`, that would cause mypy to infer immutable version of types (like `Sequence`, `Mapping`, `FrozenSet`) instead of mutable (`List`, `Dict`, `Set`)

With this feature turned on the below code:
```python
x = [1, 2, 3]
x.append(4)
```
mypy would give `error: "Sequence[int]" has no attribute "append"` as it would infer `x` to be `Sequence[int]` instead of `List[int]`

**Pitch**

Many developers support the idea of immutability by default for a number of reasons, and adding this option would be a nice way for them to opt-in to some version of this with mypy. Currently if I want my variable `x = [1, 2, 3]` to be `Sequence[int]` instead of `List[int]`, I need to explicitly add a `Sequence[int]` type annotation, which is easy to forget. If I had this feature option turned on, I would instead need to explicitly opt-in to mutability with `x: List[int] = [1, 2, 3]`

I'd love to find out if this feature is something that would be 1. feasible and 2. welcome in the project. If so, I could take a shot with implementing it!

**Comment by hauntsaninja** [comment]
There haven't been any other requests for this feature. I think it wouldn't be usable in most Python programs, and could interact surprisingly with narrowing. I think https://github.com/python/mypy/pull/5756 would be the good, explicit way to do this.
