### ISSUE TITLE
Support dict with combination of positional arguments, keyword arguments and **args

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#984]
This is a follow-up to #239.

**Comment by gvanrossum** [comment]
Is this about the following?
```
    a = dict(x=1, y=2)
    b = dict(a, z=3)
```
The first works but the second gets:
```
...: error: No overload variant of "dict" matches argument types [Any, builtins.int]
```
I have three live occurrences of this.

**Comment by JukkaL** [comment]
Yeah, that was well. I was thinking about `dict(x=1, **d)`.

**Comment by gvanrossum** [comment]
Oh, the latter is probably less common?

**Comment by ahaven** [comment]
Our code has a bunch of instances of the `b = dict(a, z=3)` kind of constructor, using it to copy dicts with some specific values changed.

**Comment by JukkaL** [comment]
The discussion at https://github.com/python/mypy/issues/1370#issuecomment-209907086 is relevant.
