### ISSUE TITLE
Emit warning when using mypy on python versions it doesn't support yet

### ISSUE THREAD

**Issue by velit** [python/mypy#9844]
**Feature**

When specifying a python version mypy doesn't yet fully support, emit a warning about the situation.

**Pitch**

Mypy 0.790 allows the specification of python 3.9 version without complaint. When using it mypy will complain about list[str] syntax because full 3.9 support is not implemented yet. Emitting a warning will make it clear to the end-user that the software is working as intended and there is no problem in their environment, mypy just doesn't fully support the requested version yet.

**Comment by abhinaypandey02** [comment]
I can try working on this.
You mean the warning should be visible each time we check with mypy?

**Comment by velit** [comment]
I can only tell my perspective as a user that I would've wanted some info from the tool that when I request 3.9 that the tool cannot really comply fully yet. I spent some time scouring google and docs trying to figure out if mypy supports this feature yet or if there was some problem in my configuration or environment. First hit on google was this thread https://github.com/python/mypy/issues/7907 which looked like it did. Finally I found this https://github.com/python/mypy/issues/9761 which gave me the answer that it's not.

As to the potential implementation of this I'm not nearly familiar enough with the tool and its user groups that I could answer the ramifications of a specific implementation. It might be problematic if the warning was always emitted and it couldn't be silenced because I can imagine there being a lot of users who would quite quickly migrate into a new python version but might not actually use any features in those versions that would cause issues with mypy even if mypy technically didn't officially support that new python version yet.

**Comment by hauntsaninja** [comment]
Sorry, mypy isn't going to do this. Things mostly work from Python version to Python version. If you're interested in checking out which Python versions mypy claims to support, check out the trove classifiers (as is fairly standard across the ecosystem) over at https://pypi.org/project/mypy/ or https://github.com/python/mypy/blob/v0.790/setup.py#L158
