### ISSUE TITLE
Generic return types with cached_property

### ISSUE THREAD

**Issue by adshieh** [python/mypy#9862]
**Bug Report**

Generic return types in a parent class method set by a child class method override work with the `property` decorator, but not with the `functools.cached_property` decorator.

**To Reproduce**

Minimal example:
```python
import functools
from typing import Generic, TypeVar

T = TypeVar("T")


class A(Generic[T]):
    @property
    def field1(self) -> T:
        raise NotImplementedError

    @functools.cached_property
    def field2(self) -> T:
        raise NotImplementedError


class B(A[None]):
    @property
    def field1(self) -> None:
        return None

    @functools.cached_property
    def field2(self) -> None:
        return None
```

**Expected Behavior**

Mypy should accept `B`.

**Actual Behavior**

Mypy reports an error for `B.field2`, but not for `B.field1`:
```
error: Signature of "field2" incompatible with supertype "A"
```

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8.5
- Operating system and version: Ubuntu 20.04.1 LTS

**Comment by gvanrossum** [comment]
Please look for help in Gitter, this may be fixable in typeshed (or it may not).
