### ISSUE TITLE
PEP 593 Annotated containing string literal is marked incorrect

### ISSUE THREAD

**Issue by Richardk2n** [python/mypy#9868]
**Bug Report**

Annotated as descirbed by [PEP 593](https://www.python.org/dev/peps/pep-0593/) should work according to #7021 but does not if the Annotated is annotating a function parameter and contains a string literal, that is not itself a function parameter. Se examples below.

**To Reproduce**

`a: Annotated[str, "metadata"]` is fine
`def f(a: Annotated[str, str("metadata")]):` is also fine
`def f(a: Annotated[str, "metadata"]):` gives `Name 'metadata' is not defined`

**Expected Behavior**

All thre examples should be valid

**Actual Behavior**

They are not.

**Your Environment**

- Mypy version used:master branch as of time of writing
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used:3.9.1
- Operating system and version:Windows 10

**Comment by gvanrossum** [comment]
Confirmed on master branch -- the last example gives `Name 'metadata' is not defined`.
