### ISSUE TITLE
Add something like `mypy: opt-in/opt-out` to switch typing on/off on module/function basis.

### ISSUE THREAD

**Issue by Pand9** [python/mypy#9872]
**Feature**

- Adding `# mypy: opt-out` right at the top of the file (just under a docstring) would disable type checking, except for opt-ins mentioned below.
- Adding `# mypy: opt-in` to top-level a function or method (in the same line as `def`, or just above it) would enable typing even with `mypy: off`.

**Pitch**

I want to add `mypy` run to my company's CI for all files modified in a commit. However, some of our legacy files are big and we can't reasonably expect developers to fix all errors on a first edit. Being able to run mypy only for specified functions within a module would resolve this.

**Comment by gvanrossum** [comment]
The first part can be done by putting ‘# type: ignore’ at the top of a file.

**Comment by JelleZijlstra** [comment]
Yes, and you can also use mypy config files to manage which files mypy checks. I don't think we need yet another similar mechanism.

**Comment by Pand9** [comment]
Opt-in element is crucial here.

**Comment by gvanrossum** [comment]
I don’t think we will ever implement that. Closing.

**Comment by Pand9** [comment]
Please elaborate.

**Comment by JukkaL** [comment]
Mypy already doesn't type check functions without type annotations, so there already is a per-function opt-out mechanism -- just leave out a type annotation. You can also ignore errors on specific lines by adding a `# type: ignore` comment.

**Comment by hauntsaninja** [comment]
There's also `typing.no_type_check`, which flies somewhat under the radar.
