### ISSUE TITLE
PEP 585 support is broken.

### ISSUE THREAD

**Issue by truedodiq** [python/mypy#9873]
**Bug Report**

PEP 585 support seems broken.

**To Reproduce**

Run mypy over `foo: list[int] = [1, 2, 3]`

**Expected Behavior**

No errors.

**Actual Behavior**

`"list" is not subscriptable, use "typing.List" instead` error.

**Your Environment**

- Mypy version used: 0.790
- Python version used: 3.9.1
- Operating system and version: Windows 10 20H2

**Comment by hauntsaninja** [comment]
#7907 / #9761

**Comment by Tshimanga** [comment]
I'm running into this again with the same example. On Python 3.12, Mypy 1.11.0, MacOS 14

**Comment by Tshimanga** [comment]
I also am seeing this error
```
error: "type" expects no type arguments, but 1 given
```
