### ISSUE TITLE
dataclass and `field` alias

### ISSUE THREAD

**Issue by CedricCabessa** [python/mypy#9875]
Hi,

**Bug Report**

I'm trying to write a simple wrapper around `dataclass.field`

**To Reproduce**

Here is a simple snippet that work perfectly under mypy

```
from dataclasses import field, dataclass

@dataclass
class C:
    some_int: int
    some_str: str = field(metadata={"doc": "foo"})
    another_int: int

c = C(42, "bla", 43)
```

Now in order to make doc creation easy, I want to write an helper like this

```
def doc(documentation: str):
    return field(metadata={"doc": documentation})
```

So, my snippet can be written:

```
@dataclass
class C:
    some_int: int
    some_str: str = doc("foo")
    another_int: int
```

**Expected Behavior**

mypy return no error like in the first snippet

**Actual Behavior**

```
error: Attributes without a default cannot follow attributes with one
```

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: python3.8
- Operating system and version: ubuntu 20.04

**Related Info**

I believe those bugs are kind of related.

https://github.com/python/mypy/issues/8853
https://github.com/python/mypy/issues/5383

There is a few users that need to alias freely assign / alias dataclass method and class.

**Comment by gvanrossum** [comment]
Fixing this will require some changes to the plugin that's used to deal with dataclass semantics. I'm not sure it is easy -- there would have to be a way to mark specific functions (like your `doc()`) as having similar semantics as `field()`. But you're free to look over the source code (start at mypy/plugins/dataclasses.py).

**Comment by hauntsaninja** [comment]
Closing, see https://github.com/python/mypy/issues/5383#issuecomment-1691288663
