### ISSUE TITLE
Using TypeVar with bound in Generic

### ISSUE THREAD

**Issue by pbabics** [python/mypy#9878]
**Questions and Help**
Hello,

I was testing code similar to

```python
from typing import TypeVar, Generic, NamedTuple, Dict, Any

Key = TypeVar('Key', bound = NamedTuple)

class Test(Generic[Key]):

	def get_fields(self, key: Key) -> Dict[str, Any]:
		return {
				field_name: key[idx]
			for idx, field_name in enumerate(key._fields)
		}

class TestKey(NamedTuple):
	name: str
	value: str

test = Test[TestKey]()
test.get_fields(TestKey('a', 'b'))  # error: Value of type variable "Key" of "Test" cannot be "TestKey"  [type-var]
```

But was unable to get this working, although to me it seems fine, If i omit `, bound = NamedTuple` and use `isinstance` check in `get_fields` it works.
Is there any trick to get this working?

I've tested this using mypy 0.790, same issue can be observed on current master.

I am not sure if this is related to https://github.com/python/typing/issues/548

**Comment by gvanrossum** [comment]
NamedTuple is treated as a special form (like Tuple), not as a regular generic class. I don't think this can be made to work, and I don't see why it would matter.

**Comment by AlexWaygood** [comment]
This [works in the way you'd like it to](https://mypy-play.net/?mypy=0.930&python=3.10&flags=strict%2Ccheck-untyped-defs&gist=33c64a7021586bf120443892fe4a6136) on mypy 0.930+.
