### ISSUE TITLE
Allow stricter typing in subclass methods 

### ISSUE THREAD

**Issue by Spenhouet** [python/mypy#9912]
A subclass most of the time is a more specific implementation of the super class.
If the super class accepts different types for a parameter, I should be able to restrict that in the subclass method:

```python
class Foo():

    def the_method(self, test: Union[str, int]) -> None:
        pass


class Bar(Foo):

    def the_method(self, test: str) -> None:
        pass
```

but mypy does not like that:

> Argument 1 of "the_method" is incompatible with supertype "Foo"; supertype defines the argument type as "Union[str, int]"mypy(error)

I don't think being more strict on a subclass does introduce any problems. It still expects a type which the super class can handle / also expects.

I would propose that mypy checks if the type defined in the overwritten method is a subset of the types defined by the super class.

**Comment by gvanrossum** [comment]
To the contrary. Please read up on contravariance.
