### ISSUE TITLE
Disagreement between MyPy and pytype

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#9913]
I contributed some type annotations to the wonderful JAX project recently, and we ran into a problem whereby MyPy and pytype disagree on type inference.  Unfortunately, PEP 484 doesn't clarify the situation.  Would someone mind commenting on what the expected overload resolution is here?

```python
from typing import Any, Callable, overload, TypeVar

T = TypeVar('T')
U = TypeVar('U')

@overload	
def tree_map(f: Callable[[U], U], tree: T) -> T:	
    ...	

@overload	
def tree_map(f: Callable[[T], U], tree: T) -> U:	
    ...	

@overload	
def tree_map(f: Callable[[Any], Any], tree: Any) -> Any:	
    ...	

def tree_map(f: Callable[[Any], Any], tree: Any) -> Any:
  pass
  

def bar(x: Any) -> str:
  return repr(x)

reveal_type(tree_map(bar, [2, 3, 4]))
```
MyPy returns `Any`, but pytype returns `List[int]`.

(Edited to repair typo.)

**Comment by hauntsaninja** [comment]
`List[str]` seems definitely wrong, did you mean `List[int]`?

**Comment by hauntsaninja** [comment]
For what it's worth, I'd expect `List[int]`, since I believe mypy currently uses the overload order, and the first overload should match:
```
from typing import Any, Callable, overload, TypeVar

U = TypeVar('U')

def hmm(f: Callable[[U], U]) -> int: pass

def bar(x: Any) -> str:
  return repr(x)

reveal_type(hmm(bar))
```

**Comment by hauntsaninja** [comment]
Oh okay, maybe it's the first exception outlined in https://mypy.readthedocs.io/en/stable/more_types.html#type-checking-calls-to-overloads

**Comment by hauntsaninja** [comment]
What is the third overload meant to get that isn't covered by the first two?

**Comment by NeilGirdhar** [comment]
@hauntsaninja
Yes, I mean `List[int]`.

The third overload catches cases like
```
tree_map(Callable[[int], str], List[int]) -> List[str]
```

Can you point to the exception directly?  I can't seem to find it.

**Comment by hauntsaninja** [comment]
Grep for `However, there are two exceptions to the “pick the first match” rule`

**Comment by NeilGirdhar** [comment]
@hauntsaninja Okay, thanks for taking a look.  I'm sure you know better than me.  It would be nice to know if the current typing rules should be changed, and whether it is mypy or pytype that is following the typing rules.

**Comment by erictraut** [comment]
FWIW, pyright agrees with pytype and reveals `List[int]`.

**Comment by erictraut** [comment]
Overload resolution rules are not spelled out in any specifications, so it's up to each type checker to implement their own rules. In pyright, I've made many attempts to (but have not been 100% successful) at matching mypy's overload behavior. My comment above is now outdated, and pyright now matches mypy's behavior in this case. The revealed type is now `Any`.

I think this issue should be closed. Mypy is behaving the way it is intended to in this case.

**Comment by NeilGirdhar** [comment]
Sounds good, closing.
