### ISSUE TITLE
Assertion over Optional[] is ignored, if used from a separate method.

### ISSUE THREAD

**Issue by MrMino** [python/mypy#9917]
**Bug Report**

<sub>I have a feeling that it's too obvious to be a bug - apologies if that's the case.</sub>

Mypy ignores an assertion that would normally narrow `Optional[x]` to `x`, if its inside another method.

**To Reproduce**

```
from typing import Optional


class Foo:
    def __init__(self, opt: Optional[str]) -> None:
        self.opt = opt

    def open(self) -> None:
        self.fail_if_none()
        self.opt.strip()

    def fail_if_none(self) -> None:
        assert self.opt is not None
```

**Actual Behavior**

Mypy shows the following error:

```
mpt.py:10: error: Item "None" of "Optional[str]" has no attribute "strip"
```

Moving this assertion above the `strip()` removes the error. Similar issue happens if an `if check() → raise` is utilized instead:

```
    def open(self) -> None:
        if self.is_none():
            raise Exception()
        self.opt.strip()

    def is_none(self) -> bool:
        return self.opt is None
```

**Environment**

- Mypy version used: 0.790
- Mypy command-line flags: (none)
- Mypy configuration options from `mypy.ini` (and other config files): (none)
- Python version used: 3.8.5
- Operating system and version:  Ubuntu 20.04.1 LTS

**Comment by JelleZijlstra** [comment]
This is a known limitation that's been reported before (but I don't know what to search for to find the duplicates). It will be fixed by TypeGuards in the upcoming PEP 647.

**Comment by vineetsharma883** [comment]
is there a way to ignore this for a particular line. I am getting same issue for following line 
```python
data = json.loads(os.environ.get("DATA").strip("'"))
```
