### ISSUE TITLE
Project website is not accessible via https

### ISSUE THREAD

**Issue by djbrown** [python/mypy#9919]
**Documentation**

The project website www.mypy-lang.org is not secured via ssl/tls.

It's 2021 now, can you please provide your webserver with a certificate? 
In the age of [#letsencrypt](https://letsencrypt.org) I don't see any reason not to.

Every modern browser complains about it when visiting the website.
Some browsers (Chrome) also prevent the loading/inclusion of insecure content on secured websites.
E.g. the mypy badge on [my docker hub page](https://hub.docker.com/r/djbrown/hbscorez)
... which - personally - is bugging me the most 😭

**Comment by gvanrossum** [comment]
@JukkaL, I think you are the only one who can do something about this.

**Comment by Paul-AUB** [comment]
Well, it also prevent using the badge (http://www.mypy-lang.org/static/mypy_badge.svg) with https, which is annoying since most GitHub Enterprise configuration prevent access to http.

It makes the badge not usable for me.

**Comment by cpach** [comment]
Hi folks! Any progress on this issue?

**Comment by 97littleleaf11** [comment]
cc @JukkaL

**Comment by johnthagen** [comment]
This seems to be fixed these days?

https://www.mypy-lang.org

I think this issue can be closed.

**Comment by hauntsaninja** [comment]
Thanks for checking!
