### ISSUE TITLE
Unbound method rejected as FunctionType,  Callable cast as FunctionType

### ISSUE THREAD

**Issue by tlambert03** [python/mypy#9934]
**Bug Report**

This feels related to #8869, but different enough to warrant a separate issue.
There, the issue was that a _bound_ method of `MethodType` is incorrectly rejected as a Callable, here, I'm noticing that an _unbound_ class method is rejected as a `FunctionType`:

**To Reproduce**

```python
import types

class Cls:
    def meth(self):
        pass

assert isinstance(Cls.meth, types.FunctionType)  # no problem

x: types.FunctionType = Cls.meth
```

```sh
Incompatible types in assignment (expression has type "Callable[[Cls], Any]", variable has type "FunctionType")  [assignment]
```

**Expected Behavior**

I expected an unbound class method to work for an argument expecting `FunctionType`

**Actual Behavior**

`Incompatible types in assignment`

**Your Environment**

- mypy 0.790
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.8.6
- Operating system and version: macos 10.15.7

**Additional info**

(In this case, I didn't want to use `x: Callable` because I'd like to be able to assert that the standard function object methods will be available)

**Comment by tlambert03** [comment]
Actually, I guess I'm realizing that mypy more generally interprets `Callable` as having many of the attributes of a typical `FunctionType` ... though this may not always be the case.  For example.  The following code will fail at runtime with `AttributeError: 'Cls' object has no attribute '__name__'`, but mypy has no problem with it:

```python
from typing import Callable

def w(f: Callable):
    print(f.__name__)

class Cls:
    def __call__(self) -> None:
        pass

w(Cls())
```

**Comment by erictraut** [comment]
This bug appears to have been fixed. I can no longer repro the problem with the latest version of mypy (1.5).
