### ISSUE TITLE
PEP 604 and aliases

### ISSUE THREAD

**Issue by asottile** [python/mypy#9945]
**Feature**

PEP 604 `|` operator should be sufficient to make an alias

**Pitch**

This is accepted:

```python
from typing import Union
Alias = Union[int, str]
def f(x: Alias) -> None: ...
f(1)
f('2')
```

so the equivalent post-PEP-604 I believe should be allowed as well?

```python
Alias = int | str
def f(x: Alias) -> None: ...
f(1)
f('2')
```

currently it produces this output:

```console
$ mypy t.py --python-version 3.10
t.py:1: error: Unsupported left operand type for | ("Type[int]")
t.py:2: error: Variable "t.Alias" is not valid as a type
t.py:2: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
Found 2 errors in 1 file (checked 1 source file)
$ cat t.py 
Alias = int | str
def f(x: Alias) -> None: ...
f(1)
f('2')
$ mypy --version
mypy 0.800
```

**Comment by hauntsaninja** [comment]
Yeah, the PEP 604 support in mypy doesn't yet cover anything that would require runtime support. This is the same as https://github.com/python/mypy/issues/9880

**Comment by gvanrossum** [comment]
Probably we should first support PEP 613 (`TypeAlias`) and then you can write
```
A: TypeAlias = int | str
```

**Comment by asottile** [comment]
cool -- will follow #9880 instead 👍
