### ISSUE TITLE
Drop support for running on Python 3.5

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#9950]
Python 3.5 has reached its end of life. However, Ubuntu 16.04 LTS still ships with
Python 3.5 and reaches its end of life in April 2021, and I'd like to keep supporting 3.5
until April (unless it becomes too difficult).

My motivation for waiting this long is that it's fairly common for organizations to leave 
upgrades until the last minute.

**Comment by JelleZijlstra** [comment]
@JukkaL is there anything still blocking this? It would be good to do this sooner rather than later so contributors can stop worrying about Python 3.5 support (e.g. in #10219).

**Comment by JukkaL** [comment]
I'd like to make at least one more public release with Python 3.5 support. We should be able to drop it (soon) afterwards. However, in the next release we can mark Python 3.5 as deprecated and any new features will no longer need to support 3.5.

**Comment by hauntsaninja** [comment]
mypy no longer supports 3.5, as of #10706
