### ISSUE TITLE
Make `--explicit-package-bases` revertible

### ISSUE THREAD

**Issue by gustavgransbo** [python/mypy#9968]
**Feature**

`--explicit-package-bases` should have an inverse: `--no-explicit-package-bases`.

**Pitch**

I have a `mypy.ini` that declares `explicit_package_bases = True`. It would be convenient to be able to override this setting from the command line by passing  `--no-explicit-package-bases`.

My use case is that I have a mono repo with a shared `mypy.ini`, where I mostly want to use `--explicit-package-bases`.
However, in some sub directories I have the following structure:
```
sub-dir
│
└───src
│   └───pkg
│   │   └─── # Package content
│   └───tests
│
└───noxfile.py
```
The `noxfile.py` is used to trigger a `mypy src/ tests/ --config {PATH_TO_CONFIG}` session with `sub-dir` as working directory.
I would like to use the same `mypy.ini` I use in the rest of the repo to not have to duplicate settings, but this sets `--explicit-package-bases`. Unfortunately this leads to `mypy` thinking that `src` is the namespace of `pkg`, since it is located at the working directory. The most convenient solution for me would be to pass `--no-explict-package-bases` when invoking `mypy` in `sub-dir`.

**Comment by hauntsaninja** [comment]
I might be misunderstanding, but I'm not sure that would help if `pkg` is actually a namespace package, since mypy wouldn't correctly map files to module names. Try putting src in your mypy path instead? (on the lines of the example in point 3 of https://mypy.readthedocs.io/en/latest/running_mypy.html#mapping-file-paths-to-modules)

**Comment by gustavgransbo** [comment]
Sorry, maybe the example was not clear enough.

`pkg` is not a namespace package, but when mypy is invoked with the working directory `sub-dir`, it thinks that `pkg` is a namespace package. I would like to be able to explicitly turn of `explicit-namespace-packages` when I run `mypy` in `sub-dir`.

**Comment by gustavgransbo** [comment]
Since it was such a small addition I went ahead and made an attempt at implementing this.

Maybe my use case seems slim, but since you already support inverting many other flags, I hope you wont mind supporting this specific flag.

One thing that had me a little bit perplexed was why the flag is part of the `Running code` section. It seems like it would be more at home in `Import discovery`, next to `--namespace-packages`.

**Comment by gustavgransbo** [comment]
> Try putting src in your mypy path instead?

Actually, this should solve my use case regardless of `pkg` not being a namespace package, thank you for the suggestion!

I think having the option to override the config could still be useful though. Adding `src` to `mypy_path` would potentially affect other parts of the repository, whereas explicitly turning the feature of in a specific circumstance has a clear effect. Also, it could be useful for experimenting with the setting directly on the command line.

Anyway, thank you for the solution to my use case!

**Comment by gustavgransbo** [comment]
I would really appreciate some feedback in regards to this issue and my PR! @hauntsaninja
