### ISSUE TITLE
stubgen: import List[module

### ISSUE THREAD

**Issue by hiaselhans** [python/mypy#9970]
**Bug Report**

stubgen created C++ stubs are wrong.

**To Reproduce**

I created a nested pybind11 module.

mymodule
 - submodule1
 - submodule2

then ran stubgen -p mymodule

**Expected Behavior**

correct stubs should be generated

**Actual Behavior**

in submodule1.pyi:

`import List[mymodule.submodule1`

also `__init__` functions are overloaded with return type of the class.

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9.1
- Operating system and version: archlinux

**Comment by AWhetter** [comment]
This was fixed in mypy v0.800 via https://github.com/python/mypy/pull/8939
