### ISSUE TITLE
mypy.ini module-specific override doesn't work without `__init__.py`

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#9974]
In the following layout:

- mypy.ini contains
```
[mypy]
disallow_untyped_defs = True

[mypy-a.b.*]
disallow_untyped_defs = False
```
- `a` contains `__init__.py` and a directory `a/b`
- `a/b` contains `c.py` with an untyped def

Mypy will complain about missing type annotations in `a.b.c`. If I create `a/b/__init__.py`, the errors go away. This is a regression in v0.800.

**Comment by hauntsaninja** [comment]
Are you using `--namespace-packages`? (It's probably not a regression as much as mypy previously just didn't check `c.py`)

**Comment by JelleZijlstra** [comment]
I'm not using `--namespace-packages`. I think you're right that the file was not checked before, so this is not so much as a regression as a pre-existing bug that got exposed by recent changes.

**Comment by hauntsaninja** [comment]
You'll need to use `--namespace-packages` for mypy to treat `a/b/c.py` as `a.b.c` instead of `c`. Alternatively, you can add `__init__.py` to `a/b`.

**Comment by hauntsaninja** [comment]
So I don't think that there is a bug here, although mypy should make `--namespace-packages` the default (https://github.com/python/mypy/pull/9636)
