### ISSUE TITLE
Dict, List and Set are imported by default

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#999]
This code (no import from typing) complains, as expected:

```
a = None  # type: Any
```

However, this code passes:

```
a = None  # type: Dict
```

Similar with List, Set.

**Comment by JukkaL** [comment]
Ah, seems like a problem with how mypy handles generic type aliases, such as `Dict` -> `dict`. Not sure exactly why this happens, but my guess is that they leak from `builtins.pyi` somehow.

**Comment by gvanrossum** [comment]
FWIW the same thing happens to Set. I don't believe there are other types that have this issue; those three (List, Dict, Set) are treated special by mypy. See https://github.com/python/mypy/blob/master/mypy/nodes.py#L74

**Comment by gvanrossum** [comment]
This is a bit thorny to fix, because Dict/List/Set are currently implemented as aliases to dict/list/set, and all the genericity is specified in typeshed/*/builtins.pyi.

I propose not to worry too much about it for 0.3.2.

**Comment by JukkaL** [comment]
Agreed. Maybe move this to 0.3.3?

**Comment by gvanrossum** [comment]
Moved to 0.3.3.

**Comment by tharvik** [comment]
Same idea for `@classmethod`
```python
class A:
    @classmethod
    def f(cls) -> None: ...
```
output nothing but should output something as
```
/tmp/asd2.py:2: error: Name 'classmethod' is not defined
```

**Comment by tharvik** [comment]
(oups, that was stupid, ignore my comment)
