### ISSUE TITLE
`--install-types` not recognized

### ISSUE THREAD

**Issue by klieret** [python/mypy#9997]
**Bug Report**

`mypy --install-types` (as recommended [in the docs](https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports)) produces `mypy: error: unrecognized arguments: --install-types`. I suspect this might be a leftover in the documentation.

**Your Environment**

- Mypy version used: 0.770
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: Python 3.7.5
- Operating system and version: Ubuntu 19.10

**Comment by JukkaL** [comment]
Those docs are for the development version of mypy (GitHub master). 

Here are the docs for the latest release: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

**Comment by klieret** [comment]
Oh, sorry, I must have misclicked, I thought I had checked :see_no_evil:   Sorry for the noise & thanks for your quick follow up!

**Comment by AIGeneratedUsername** [comment]
@JukkaL Here is an issue anyway.

When Mypy finds an error, it must show to a user a valid URL.

If Mypy is a "stable" version, it must show a URL to a "stable" version docs. 

I have 0.812 version at this moment and it suggests me to open a URL: https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports which contains a not supported command.

**Comment by hauntsaninja** [comment]
That's a good point, thanks for bringing it up! Opened https://github.com/python/mypy/pull/10159 to fix

**Comment by JelleZijlstra** [comment]
See #10596 for the segfault.

**Comment by Ollymid** [comment]
Hi there,
I have mypy version 0.902 and I am seeing `mypy: error: unrecognized arguments: --install-types` when trying to install stub packages  
I've checked [the docs ](https://github.com/python/mypy/issues/9997#issuecomment-770224186) mentioned above but it says that that command should run and install all missing known stubs

I've tried the --non-interactive alternative too and that also states it's unrecognized

Any help with the correct command would be greatly appreciated

**Comment by JukkaL** [comment]
@Ollymid I'd recommend trying the recently released mypy 0.910. `--non-interactive` is not supported in mypy 0.902 yet. Also, can you try creating a fresh virtualenv, install mypy in it using `pip install mypy`, check `mypy --version` and try `mypy --install-types --non-interactive -c 'import requests'`?

**Comment by Ollymid** [comment]
Thanks for swift response @JukkaL - I was inadvertently using an older version of mypy that didn't support the `--install-types` command (d'oh!) - just made sure I was using correct version and now that command is working for me :+1:
